var searchData=
[
  ['rank_20filters',['Rank Filters',['../group__image__rank__filters.html',1,'']]],
  ['rectstddev',['RectStdDev',['../group__image__rectstddev.html',1,'']]],
  ['remap',['Remap',['../group__image__remap.html',1,'']]],
  ['resize',['Resize',['../group__image__resize.html',1,'']]],
  ['resizebatch',['ResizeBatch',['../group__image__resize__batch.html',1,'']]],
  ['resizesqrpixel',['ResizeSqrPixel',['../group__image__resize__square__pixel.html',1,'']]],
  ['rotate',['Rotate',['../group__image__rotate.html',1,'']]],
  ['rshiftc',['RShiftC',['../group__image__rshiftc.html',1,'']]],
  ['re',['re',['../struct_n_p_p___a_l_i_g_n__8.html#ac6778b6767d48b002939b79e521713ce',1,'NPP_ALIGN_8::re()'],['../struct_n_p_p___a_l_i_g_n__8.html#a5148c7ab78c99a9065a8dca3130a6795',1,'NPP_ALIGN_8::re()'],['../struct_n_p_p___a_l_i_g_n__8.html#a0f68f209d4a8ff00ef765b51618146cf',1,'NPP_ALIGN_8::re()'],['../struct_n_p_p___a_l_i_g_n__16.html#a61eecd12ba9c14a2adc4fde723681c40',1,'NPP_ALIGN_16::re()'],['../struct_n_p_p___a_l_i_g_n__16.html#a125e6a3b722989c4a7d12853434655ff',1,'NPP_ALIGN_16::re()']]],
  ['rgbtocbycr422',['RGBToCbYCr422',['../group__rgbtocbycr422.html',1,'']]],
  ['rgbtohls',['RGBToHLS',['../group__rgbtohls.html',1,'']]],
  ['rgbtohsv',['RGBToHSV',['../group__rgbtohsv.html',1,'']]],
  ['rgbtoluv',['RGBToLUV',['../group__rgbtoluv.html',1,'']]],
  ['rgbtoxyz',['RGBToXYZ',['../group__rgbtoxyz.html',1,'']]],
  ['rgbtoycbcr',['RGBToYCbCr',['../group__rgbtoycbcr.html',1,'']]],
  ['rgbtoycbcr411',['RGBToYCbCr411',['../group__rgbtoycbcr411.html',1,'']]],
  ['rgbtoycbcr420',['RGBToYCbCr420',['../group__rgbtoycbcr420.html',1,'']]],
  ['rgbtoycbcr422',['RGBToYCbCr422',['../group__rgbtoycbcr422.html',1,'']]],
  ['rgbtoycc',['RGBToYCC',['../group__rgbtoycc.html',1,'']]],
  ['rgbtoycrcb420',['RGBToYCrCb420',['../group__rgbtoycrcb420.html',1,'']]],
  ['rgbtoycrcb422',['RGBToYCrCb422',['../group__rgbtoycrcb422.html',1,'']]],
  ['rgbtoyuv',['RGBToYUV',['../group__rgbtoyuv.html',1,'']]],
  ['rgbtoyuv420',['RGBToYUV420',['../group__rgbtoyuv420.html',1,'']]],
  ['rgbtoyuv422',['RGBToYUV422',['../group__rgbtoyuv422.html',1,'']]],
  ['rho',['rho',['../struct_npp_point_polar.html#a07aee7b2513862c14e0ed6dbebe2cee3',1,'NppPointPolar']]],
  ['rotate',['Rotate',['../group__rotate__.html',1,'']]],
  ['rotate_20utility_20functions',['Rotate Utility Functions',['../group__rotate__utility__functions.html',1,'']]],
  ['rshiftc',['RShiftC',['../group__signal__rshiftc.html',1,'']]]
];
