var searchData=
[
  ['masked_20copy',['Masked Copy',['../group__image__masked__copy.html',1,'']]],
  ['masked_20set',['Masked Set',['../group__image__masked__set.html',1,'']]],
  ['max',['Max',['../group__image__max.html',1,'']]],
  ['maxindx',['MaxIndx',['../group__image__max__index.html',1,'']]],
  ['maxevery',['MaxEvery',['../group__image__maxevery.html',1,'']]],
  ['maximumerror',['MaximumError',['../group__image__maximum__error.html',1,'']]],
  ['maximumrelativeerror',['MaximumRelativeError',['../group__image__maximum__relative__error.html',1,'']]],
  ['mean',['Mean',['../group__image__mean.html',1,'']]],
  ['mean_5fstddev',['Mean_StdDev',['../group__image__mean__stddev.html',1,'']]],
  ['memory_20management',['Memory Management',['../group__image__memory__management.html',1,'']]],
  ['min',['Min',['../group__image__min.html',1,'']]],
  ['minindx',['MinIndx',['../group__image__min__index.html',1,'']]],
  ['minmax',['MinMax',['../group__image__min__max.html',1,'']]],
  ['minmaxindx',['MinMaxIndx',['../group__image__min__max__index.html',1,'']]],
  ['minevery',['MinEvery',['../group__image__minevery.html',1,'']]],
  ['mirror',['Mirror',['../group__image__mirror.html',1,'']]],
  ['morphblackhatborder',['MorphBlackHatBorder',['../group__image__morph__black__hat__border.html',1,'']]],
  ['morphcloseborder',['MorphCloseBorder',['../group__image__morph__close__border.html',1,'']]],
  ['morphgetbuffersize',['MorphGetBufferSize',['../group__image__morph__get__buffer__size.html',1,'']]],
  ['morphgradientborder',['MorphGradientBorder',['../group__image__morph__gradient__border.html',1,'']]],
  ['morphopenborder',['MorphOpenBorder',['../group__image__morph__open__border.html',1,'']]],
  ['morphtohatborder',['MorphToHatBorder',['../group__image__morph__top__hat__border.html',1,'']]],
  ['morphological_20operations',['Morphological Operations',['../group__image__morphological__operations.html',1,'']]],
  ['mul',['Mul',['../group__image__mul.html',1,'']]],
  ['mulc',['MulC',['../group__image__mulc.html',1,'']]],
  ['mulcscale',['MulCScale',['../group__image__mulcscale.html',1,'']]],
  ['mulscale',['MulScale',['../group__image__mulscale.html',1,'']]],
  ['major',['major',['../struct_npp_library_version.html#add7f9daea09372c52c277c369ce27050',1,'NppLibraryVersion']]],
  ['minor',['minor',['../struct_npp_library_version.html#a9bd0a9fb29be5a492db1c1c83e95283f',1,'NppLibraryVersion']]],
  ['mirrorbatch',['MirrorBatch',['../group__mirror__batch.html',1,'']]],
  ['malloc',['Malloc',['../group__signal__malloc.html',1,'']]],
  ['maximum',['Maximum',['../group__signal__max.html',1,'']]],
  ['maximumerror',['MaximumError',['../group__signal__maximum__error.html',1,'']]],
  ['maximumrelativeerror',['MaximumRelativeError',['../group__signal__maximum__relative__error.html',1,'']]],
  ['mean',['Mean',['../group__signal__mean.html',1,'']]],
  ['mean_20and_20standard_20deviation',['Mean And Standard Deviation',['../group__signal__mean__and__standard__deviation.html',1,'']]],
  ['memory_20management',['Memory Management',['../group__signal__memory__management.html',1,'']]],
  ['minimum',['Minimum',['../group__signal__min.html',1,'']]],
  ['minevery_20and_20maxevery_20functions',['MinEvery And MaxEvery Functions',['../group__signal__min__every__or__max__every.html',1,'']]],
  ['minimum_20maximum',['Minimum Maximum',['../group__signal__min__max.html',1,'']]],
  ['mul',['Mul',['../group__signal__mul.html',1,'']]],
  ['mulc',['MulC',['../group__signal__mulc.html',1,'']]]
];
