var searchData=
[
  ['affine_20transform',['Affine Transform',['../group__affine__transform.html',1,'']]],
  ['affine_20transform_20batch',['Affine Transform Batch',['../group__affine__transform__batch.html',1,'']]],
  ['affine_20transform_20utility_20functions',['Affine Transform Utility Functions',['../group__affine__transform__utility__functions.html',1,'']]],
  ['abs',['Abs',['../group__image__abs.html',1,'']]],
  ['absdiff',['AbsDiff',['../group__image__absdiff.html',1,'']]],
  ['absdiffc',['AbsDiffC',['../group__image__absdiffc.html',1,'']]],
  ['add',['Add',['../group__image__add.html',1,'']]],
  ['addc',['AddC',['../group__image__addc.html',1,'']]],
  ['addproduct',['AddProduct',['../group__image__addproduct.html',1,'']]],
  ['addsquare',['AddSquare',['../group__image__addsquare.html',1,'']]],
  ['addweighted',['AddWeighted',['../group__image__addweighted.html',1,'']]],
  ['affine_20transforms',['Affine Transforms',['../group__image__affine__transform.html',1,'']]],
  ['alpha_20composition',['Alpha Composition',['../group__image__alpha__composition__operations.html',1,'']]],
  ['alphacomp',['AlphaComp',['../group__image__alphacomp.html',1,'']]],
  ['alphacompc',['AlphaCompC',['../group__image__alphacompc.html',1,'']]],
  ['alphapremul',['AlphaPremul',['../group__image__alphapremul.html',1,'']]],
  ['alphapremulc',['AlphaPremulC',['../group__image__alphapremulc.html',1,'']]],
  ['and',['And',['../group__image__and.html',1,'']]],
  ['andc',['AndC',['../group__image__andc.html',1,'']]],
  ['arithmetic_20and_20logical_20operations',['Arithmetic and Logical Operations',['../group__image__arithmetic__and__logical__operations.html',1,'']]],
  ['arithmetic_20operations',['Arithmetic Operations',['../group__image__arithmetic__operations.html',1,'']]],
  ['averageerror',['AverageError',['../group__image__average__error.html',1,'']]],
  ['averagerelativeerror',['AverageRelativeError',['../group__image__average__relative__error.html',1,'']]],
  ['abs',['Abs',['../group__signal__abs.html',1,'']]],
  ['add',['Add',['../group__signal__add.html',1,'']]],
  ['addc',['AddC',['../group__signal__addc.html',1,'']]],
  ['addproduct',['AddProduct',['../group__signal__addproduct.html',1,'']]],
  ['addproductc',['AddProductC',['../group__signal__addproductc.html',1,'']]],
  ['and',['And',['../group__signal__and.html',1,'']]],
  ['andc',['AndC',['../group__signal__andc.html',1,'']]],
  ['arithmetic_20operations',['Arithmetic Operations',['../group__signal__arithmetic.html',1,'']]],
  ['arithmetic_20and_20logical_20operations',['Arithmetic and Logical Operations',['../group__signal__arithmetic__and__logical__operations.html',1,'']]],
  ['averageerror',['AverageError',['../group__signal__average__error.html',1,'']]],
  ['averagerelativeerror',['AverageRelativeError',['../group__signal__average__relative__error.html',1,'']]],
  ['arctan',['Arctan',['../group__signal__inversetan.html',1,'']]]
];
