var searchData=
[
  ['scale_20bit_20depth',['Scale Bit Depth',['../group__image__scale.html',1,'']]],
  ['scale_20to_20higher_20bit_20depth',['Scale To Higher Bit Depth',['../group__image__scale__to__higher__bit__depth.html',1,'']]],
  ['scale_20to_20lower_20bit_20depth',['Scale To Lower Bit Depth',['../group__image__scale__to__lower__bit__depth.html',1,'']]],
  ['set',['Set',['../group__image__set.html',1,'']]],
  ['sqr',['Sqr',['../group__image__sqr.html',1,'']]],
  ['sqrintegral',['SqrIntegral',['../group__image__sqrintegral.html',1,'']]],
  ['sqrt',['Sqrt',['../group__image__sqrt.html',1,'']]],
  ['statistical_20operations',['Statistical Operations',['../group__image__statistics__functions.html',1,'']]],
  ['sub',['Sub',['../group__image__sub.html',1,'']]],
  ['subc',['SubC',['../group__image__subc.html',1,'']]],
  ['sum',['Sum',['../group__image__sum.html',1,'']]],
  ['swap_20channels',['Swap Channels',['../group__image__swap__channels.html',1,'']]],
  ['set',['Set',['../group__signal__set.html',1,'']]],
  ['sqrt',['Sqrt',['../group__signal__sqrt.html',1,'']]],
  ['sqr',['Sqr',['../group__signal__square.html',1,'']]],
  ['standard_20deviation',['Standard Deviation',['../group__signal__standard__deviation.html',1,'']]],
  ['statistical_20functions',['Statistical Functions',['../group__signal__statistical__functions.html',1,'']]],
  ['sub',['Sub',['../group__signal__sub.html',1,'']]],
  ['subc',['SubC',['../group__signal__subc.html',1,'']]],
  ['subcrev',['SubCRev',['../group__signal__subcrev.html',1,'']]],
  ['sum',['Sum',['../group__signal__sum.html',1,'']]],
  ['sumln',['SumLn',['../group__signal__sumln.html',1,'']]],
  ['sqrdistancefull_5fnorm',['SqrDistanceFull_Norm',['../group__sqrdistancefullnorm.html',1,'']]],
  ['sqrdistancesame_5fnorm',['SqrDistanceSame_Norm',['../group__sqrdistancesamenorm.html',1,'']]],
  ['sqrdistancevalid_5fnorm',['SqrDistanceValid_Norm',['../group__sqrdistancevalidnorm.html',1,'']]]
];
