var searchData=
[
  ['cbycr422torgb',['CbYCr422ToRGB',['../group__cbcr422torgb.html',1,'']]],
  ['cbycr422tobgr',['CbYCr422ToBGR',['../group__cbycr422tobgr.html',1,'']]],
  ['cbycr422tobgr_5f709hdtv',['CbYCr422ToBGR_709HDTV',['../group__cbycr422tobgr709hdtv.html',1,'']]],
  ['compare_20image_20difference_20with_20constant_20within_20epsilon_20operations',['Compare Image Difference With Constant Within Epsilon Operations',['../group__compare__image__difference__to__constant__with__epsilon__operations.html',1,'']]],
  ['compare_20image_20differences_20with_20epsilon_20operations',['Compare Image Differences With Epsilon Operations',['../group__compare__image__differences__with__epsilon__operations.html',1,'']]],
  ['compare_20image_20with_20constant_20operations',['Compare Image With Constant Operations',['../group__compare__image__with__constant__operations.html',1,'']]],
  ['compare_20images_20operations',['Compare Images Operations',['../group__compare__images__operations.html',1,'']]],
  ['crosscorrfull_5fnorm',['CrossCorrFull_Norm',['../group__crosscorrfullnorm.html',1,'']]],
  ['crosscorrfull_5fnormlevel',['CrossCorrFull_NormLevel',['../group__crosscorrfullnormlevel.html',1,'']]],
  ['crosscorrsame_5fnorm',['CrossCorrSame_Norm',['../group__crosscorrsamenorm.html',1,'']]],
  ['crosscorrsame_5fnormlevel',['CrossCorrSame_NormLevel',['../group__crosscorrsamenormlevel.html',1,'']]],
  ['crosscorrvalid',['CrossCorrValid',['../group__crosscorrvalid.html',1,'']]],
  ['crosscorrvalid_5fnorm',['CrossCorrValid_Norm',['../group__crosscorrvalidnorm.html',1,'']]],
  ['crosscorrvalid_5fnormlevel',['CrossCorrValid_NormLevel',['../group__crosscorrvalidnormlevel.html',1,'']]],
  ['channel_20copy',['Channel Copy',['../group__image__channel__copy.html',1,'']]],
  ['channel_20set',['Channel Set',['../group__image__channel__set.html',1,'']]],
  ['color_20and_20sampling_20conversion',['Color and Sampling Conversion',['../group__image__color__conversion.html',1,'']]],
  ['colordebayer',['ColorDebayer',['../group__image__color__debayer.html',1,'']]],
  ['color_20gamma_20correction',['Color Gamma Correction',['../group__image__color__gamma__correction.html',1,'']]],
  ['colorlut',['ColorLUT',['../group__image__color___l_u_t.html',1,'']]],
  ['colorlutcubic',['ColorLUTCubic',['../group__image__color___l_u_t__cubic.html',1,'']]],
  ['colorlutlinear',['ColorLUTLinear',['../group__image__color___l_u_t___linear.html',1,'']]],
  ['colorlutpalette',['ColorLUTPalette',['../group__image__color___l_u_t__palette.html',1,'']]],
  ['colorluttrilinear',['ColorLUTTrilinear',['../group__image__color___l_u_t___trilinear.html',1,'']]],
  ['color_20model_20conversion',['Color Model Conversion',['../group__image__color__model__conversion.html',1,'']]],
  ['color_20processing',['Color Processing',['../group__image__color__processing.html',1,'']]],
  ['color_20sampling_20format_20conversion',['Color Sampling Format Conversion',['../group__image__color__sampling__format__conversion.html',1,'']]],
  ['colortogray_20conversion',['ColorToGray Conversion',['../group__image__color__to__gray.html',1,'']]],
  ['colortwist',['ColorTwist',['../group__image__color__twist.html',1,'']]],
  ['colortwistbatch',['ColorTwistBatch',['../group__image__color__twist__batch.html',1,'']]],
  ['comparison_20operations',['Comparison Operations',['../group__image__comparison__operations.html',1,'']]],
  ['complement_20color_20key',['Complement Color Key',['../group__image__complement__color__key.html',1,'']]],
  ['computer_20vision',['Computer Vision',['../group__image__computer__vision__filtering__functions.html',1,'']]],
  ['convert_20bit_20depth',['Convert Bit Depth',['../group__image__convert.html',1,'']]],
  ['convert_20to_20decreased_20bit_20depth',['Convert To Decreased Bit Depth',['../group__image__convert__decrease.html',1,'']]],
  ['convert_20to_20increased_20bit_20depth',['Convert To Increased Bit Depth',['../group__image__convert__increase.html',1,'']]],
  ['convolution',['Convolution',['../group__image__convolution.html',1,'']]],
  ['copy',['Copy',['../group__image__copy.html',1,'']]],
  ['copy_20constant_20border',['Copy Constant Border',['../group__image__copy__constant__border.html',1,'']]],
  ['copy_20replicate_20border',['Copy Replicate Border',['../group__image__copy__replicate__border.html',1,'']]],
  ['copy_20sub_2dpixel',['Copy Sub-Pixel',['../group__image__copy__sub__pixel.html',1,'']]],
  ['copy_20wrap_20border',['Copy Wrap Border',['../group__image__copy__wrap__border.html',1,'']]],
  ['countinrange_2e',['CountInRange.',['../group__image__count__in__range.html',1,'']]],
  ['compressmarkerlabels',['CompressMarkerLabels',['../group__image__filter__compress__marker__labels.html',1,'']]],
  ['compleximagemorphology',['ComplexImageMorphology',['../group__image__morph.html',1,'']]],
  ['cauchy_2c_20cauchyd_2c_20and_20cauchydd2',['Cauchy, CauchyD, and CauchyDD2',['../group__signal__cauchy.html',1,'']]],
  ['conversion_20functions',['Conversion Functions',['../group__signal__conversion__functions.html',1,'']]],
  ['convert',['Convert',['../group__signal__convert.html',1,'']]],
  ['copy',['Copy',['../group__signal__copy.html',1,'']]],
  ['count_20in_20range',['Count In Range',['../group__signal__count__in__range.html',1,'']]],
  ['count_20zero_20crossings',['Count Zero Crossings',['../group__signal__count__zero__crossings.html',1,'']]],
  ['cubrt',['Cubrt',['../group__signal__cuberoot.html',1,'']]],
  ['cmyk_5for_5fycck_5fjpeg_5fto_5fbgr',['CMYK_OR_YCCK_JPEG_TO_BGR',['../group__ycckorcmyktobgr.html',1,'']]],
  ['cmyk_5for_5fycck_5fjpeg_5fto_5frgb',['CMYK_OR_YCCK_JPEG_TO_RGB',['../group__ycckorcmyktorgb.html',1,'']]]
];
