var pairs =
{
"jetson":{"nano":1,"linux":1}
,"nano":{"devices":1,"2gb":1}
,"devices":{"software":1,"path":1}
,"software":{"features":1,"plugins":1,"hardware":1}
,"nvidia":{"jetson":1}
,"linux":{"driver":1,"targeted":1}
,"driver":{"package":1,"suspend":1,"release":1}
,"package":{"l4t":1,"bring":1}
,"l4t":{"supports":1}
,"supports":{"following":1,"gen2":1,"link":1,"egl":1,"uvc":1,"pcm":1,"sample":1,"output":1,"stereo":1,"interfaces":1,"audio":1,"normal":1,"eight":1,"two":1,"sampling":1,"four":1,"gain":1,"mixing":1,"five":1,"amixer":1}
,"following":{"software":1,"opengl":1,"sections":1}
,"features":{"provide":1,"probed":1,"include":1,"following":1,"nvgstcapture-1.0":1}
,"provide":{"users":1}
,"users":{"complete":1}
,"complete":{"package":1}
,"bring":{"linux":1}
,"targeted":{"nvidia":1}
,"always":{"check":1,"feature":1}
,"check":{"release":1}
,"release":{"notes":1,"1.0.66":1,"consult":1,"supports":1}
,"notes":{"constraints":1}
,"constraints":{"related":1}
,"related":{"features":1}
,"boot":{"device":1,"atf":1}
,"qspi":{"card":1,"usb":1}
,"2nd":{"stage":1}
,"stage":{"load":1}
,"load":{"device":1}
,"sku":{"0000":1,"0002":1}
,"0000":{"card":1}
,"0002":{"emmc":1}
,"storage":{"devices":1,"device":1,"usb0":1}
,"execution":{"cpu":1}
,"display":{"splash":1,"console":1,"support":1,"hdmi":1,"port":1,"without":1,"outputs":1}
,"splash":{"menu":1}
,"cboot":{"console":1,"drivers":1,"dynamic":1,"supported":1}
,"uart":{"printf":1}
,"printf":{"support":1}
,"standard":{"expanded":1,"combined":1,"mode":1}
,"spi":{"qspi":1}
,"quad":{"ddr":1,"mode":1}
,"hs200":{"hs400":1}
,"hs400":{"ddr50":1}
,"ddr50":{"card":1}
,"ehci":{"xhci":1}
,"xhci":{"host":1}
,"host":{"mode":1,"low":1,"full":1,"high":1,"auto":1,"controller":1}
,"class":{"drivers":1,"support":1,"usb0":1}
,"drivers":{"msd":1}
,"msd":{"hub":1}
,"dynamic":{"hardware":1,"clock":1,"voltage":1}
,"hardware":{"probe":1,"information":1,"chip":1,"flow":1,"clock":1}
,"carveouts":{"vpr":1}
,"vpr":{"plugin":1}
,"plugin":{"boards":1,"manager":1}
,"boards":{"eeproms":1}
,"information":{"added":1,"opengl":1,"supported":1,"csi":1}
,"added":{"dtb":1}
,"dtb":{"memory":1,"lib":1,"dtb":1}
,"memory":{"passed":1,"warning":1,"low":1,"falls":1}
,"passed":{"kernel":1}
,"support":{"plugin":1,"l0s":1,"gstreamer":1,"u\u2011law":1}
,"via":{"software":1}
,"supported":{"features":1,"link":1,"modes":1,"sensors":1}
,"lib":{"driver":1}
,"kernel":{"dtb":1,"decompression":1,"userspace":1}
,"bmp":{"blob":1}
,"blob":{"decompression":1}
,"eeprom":{"manager":1}
,"detects":{"board":1}
,"device":{"support":1,"life":1,"need":1,"mode":1,"capabilities":1}
,"emmc":{"card":1}
,"card":{"usb":1}
,"bus":{"support":1,"speed":1,"clock":1,"clear":1}
,"i2c":{"gpio":1,"gen1":1,"gen2":1,"gen3":1,"ddc":1,"pwr":1,"message":1,"bus":1}
,"gpio":{"spi":1,"led":1,"configuration":1,"interrupt":1}
,"usb":{"device":1,"2.0":1,"3.0":1,"video":1,"audio":1,"camera":1,"dac":1}
,"tool":{"chains":1}
,"64-bit":{"kernel":1}
,"userspace":{"u-boot":1}
,"reboot":{"support":1,"hang":1}
,"shutdown":{"support":1}
,"sc7":{"except":1}
,"except":{"jetson":1}
,"wake":{"idle":1,"sleep":1,"lp0":1}
,"cpu":{"hotplug":1,"gpu":1}
,"gpu":{"frequency":1,"vdd_in":1}
,"frequency":{"governor":1,"tuning":1,"changes":1,"dvps":1,"bit":1,"converter":1,"conversion":1}
,"emc":{"bandwidth":1}
,"bandwidth":{"manager":1,"notification":1}
,"power":{"monitor":1,"management":1,"notification":1,"down":1,"consumption":1}
,"clock":{"thermal":1,"polarity":1,"speed":1,"gating":1,"always":1,"frequency":1,"power":1}
,"thermal":{"management":1}
,"initrd":{"support":1}
,"system":{"boot":1,"error":1,"handles":1,"sluggishness":1}
,"atf":{"secure":1}
,"secure":{"monitor":1}
,"version":{"4.9.140":1,"10.2":1,"egl":1,"release":1}
,"dsi":{"display":1,"ganged":1}
,"ganged":{"mode":1}
,"pwm":{"backlight":1}
,"continuous":{"mode":1}
,"dual":{"display":1,"quad":1}
,"run":{"time":1}
,"time":{"power":1}
,"edid":{"support":1}
,"hot-plug":{"detection":1}
,"detection":{"mechanism":1}
,"hdmi":{"1.4":1,"primary":1,"1.4b":1,"2.0":1}
,"480p":{"720p":1}
,"720p":{"1080p":1}
,"1080p":{"rgb":1}
,"rgb":{"444":1}
,"suspend":{"resume":1,"support":1,"ram":1}
,"resume":{"low":1}
,"low":{"power":1,"speed":1,"light":1,"memory":1}
,"primary":{"display":1,"volume":1}
,"1.4b":{"compliance":1}
,"2.0":{"compliance":1,"support":1,"3.0":1}
,"audio":{"support":1,"supported":1,"class":1,"playback":1,"demultiplexer":1,"demultiplexing":1,"multiplexer":1,"multiplexing":1,"streams":1,"mixer":1}
,"1.2":{"support":1}
,"link":{"rates":1,"training":1,"speed":1,"width":1,"layer":1,"active":1,"bandwidth":1,"control":1}
,"rates":{"1.62":1,"44.1":1,"11.025":1,"11.05":1,"11.025,16":1}
,"1.62":{"2.7":1}
,"2.7":{"5.4":1}
,"5.4":{"second":1}
,"hbr3":{"8.1":1}
,"8.1":{"second":1}
,"second":{"supported":1}
,"full":{"link":1,"duplex":1,"speed":1}
,"hotplug":{"detection":1}
,"plug":{"unplug":1,"support":1}
,"unplug":{"wake":1}
,"deep":{"color":1,"power":1}
,"color":{"supported":1}
,"alt-mode":{"supported":1}
,"100":{"1000":1,"mbps":1}
,"1000":{"base":1}
,"mac":{"filtering":1}
,"speed":{"control":1,"mode":1,"devices":1,"supports":1}
,"control":{"sysfs":1,"temperature":1,"mvc":1}
,"temperature":{"variation":1}
,"master":{"mode":1,"slave":1}
,"camera":{"support":1,"features":1,"functionality":1,"app":1,"development":1,"uvc":1,"supported":1}
,"csi":{"input":1,"usb":1}
,"input":{"support":1,"formats":1,"stream":1,"streams":1}
,"v4l2":{"media-controller":1,"api":1}
,"api":{"bypasses":1,"support":1,"registry":1}
,"bypasses":{"isp":1}
,"csi0":{"csi1":1}
,"csi1":{"csi2":1}
,"csi2":{"csi3":1}
,"csi3":{"csi4":1}
,"csi4":{"csi5":1}
,"peripheral":{"devices":1}
,"ina":{"support":1}
,"current":{"monitoring":1,"available":1}
,"monitoring":{"cpu":1}
,"max":{"bus":1,"payload":1}
,"spi1":{"mhz":1,"spi2":1,"audio":1}
,"spi2":{"mhz":1,"cam":1}
,"chip":{"select":1}
,"packed":{"unpacked":1,"commands":1}
,"duplex":{"mode":1}
,"enable":{"bit":1,"byte":1,"tnr.v1":1,"tnr.v2":1}
,"least":{"significant":1}
,"significant":{"bit":1,"byte":1}
,"byte":{"first":1}
,"select":{"polarity":1,"option":1}
,"polarity":{"section":1,"phase":1}
,"purpose":{"client":1}
,"cam":{"display":1}
,"available":{"sku":1,"memory":1}
,"phase":{"mode":1}
,"ddr":{"sdr":1,"mode":1}
,"sdr":{"mode":1}
,"speeds":{"clock":1}
,"sdmmc1":{"204":1,"sdmmc3":1}
,"204":{"mhz":1}
,"mhz":{"sku":1}
,"sdmmc3":{"204":1,"sdmmc4":1}
,"sdmmc4":{"200":1}
,"200":{"mhz":1}
,"hot":{"plug":1}
,"high":{"speed":1,"power":1}
,"voltage":{"switching":1,"frequency":1}
,"cache":{"control":1}
,"field":{"firmware":1,"support":1}
,"firmware":{"upgrade":1}
,"cmd":{"queuing":1}
,"life":{"estimation":1}
,"estimation":{"type":1}
,"pre":{"eol":1}
,"eol":{"information":1}
,"gen1":{"i2c":1,"gen2":1}
,"gen2":{"i2c":1,"speeds":1}
,"gen3":{"i2c":1}
,"ddc":{"i2c":1}
,"pwr":{"i2c6":1,"led":1}
,"mode":{"100kbps":1,"400kbps":1,"plus":1,"3.4mbps":1,"i2c":1,"ljm":1,"rjm":1}
,"fast":{"mode":1}
,"plus":{"1mbps":1}
,"7-bit":{"10-bit":1}
,"10-bit":{"slave":1}
,"slave":{"addressing":1,"support":1}
,"lost":{"arbitration":1}
,"arbitration":{"detect":1}
,"packet":{"mode":1}
,"multi-master":{"support":1}
,"pio":{"mode":1}
,"message":{"length":1,"split":1,"size":1,"signaled":1}
,"length":{"bytes":1}
,"bytes":{"dma":1}
,"dma":{"mode":1,"engines":1}
,"feature":{"device":1,"details":1}
,"need":{"faster":1,"rework":1}
,"faster":{"responses":1}
,"split":{"message":1}
,"size":{"greater":1,"128":1,"high-order":1}
,"greater":{"bytes":1}
,"runtime":{"i2c":1}
,"changes":{"sysfs":1}
,"bit":{"banging":1,"rate":1}
,"banging":{"gpios":1}
,"clubbing":{"transactions":1}
,"transactions":{"program":1}
,"program":{"packets":1}
,"packets":{"together":1}
,"clear":{"support":1}
,"otg":{"mode":1,"support":1}
,"usb0":{"usb1":1,"480":1,"micro":1,"usb":1}
,"auto":{"suspend":1}
,"480":{"mbps":1}
,"usb1":{"gbps":1,"pex5":1,"type":1,"usb":1}
,"3.0":{"support":1}
,"remote":{"wakeup":1}
,"wakeup":{"support":1,"sc7":1}
,"mass":{"storage":1}
,"video":{"class":1,"decoders":1,"decode":1,"encoders":1,"encode":1,"format":1,"scaling":1,"cropping":1,"rotation":1}
,"hid":{"usb0":1}
,"mtp":{"usb0":1}
,"cdc":{"ncm":1}
,"ncm":{"ecm":1}
,"ecm":{"usb0":1}
,"led":{"supportgpio":1,"support":1,"controlled":1}
,"pinmux":{"configuration":1}
,"configuration":{"programming":1}
,"interrupt":{"support":1,"enable":1}
,"uart0":{"115200":1,"uart2":1}
,"uart2":{"921600":1,"uart3":1}
,"uart3":{"3000000":1}
,"flow":{"control":1}
,"fifo":{"mode":1}
,"pcie":{"gen1":1,"features":1,"device":1,"jetson":1,"pcie":1,"connected":1}
,"lane":{"width":1}
,"controller":{"features":1}
,"lanes":{"xbar":1}
,"xbar":{"config":1}
,"config":{"x4_x1":1,"space":1}
,"x4_x1":{"x2_x1":1}
,"extended":{"config":1,"tag":1,"capabilities":1}
,"down":{"dpd":1}
,"signaled":{"interrupts":1}
,"vendor":{"specific":1,"neutral":1}
,"specific":{"messages":1}
,"payload":{"size":1}
,"128":{"bytes":1,"256":1}
,"tag":{"field":1}
,"role-based":{"error":1}
,"error":{"reporting":1,"correctable":1,"non-fatal":1,"fatal":1}
,"maximum":{"link":1}
,"width":{"supports":1}
,"aspm":{"support":1}
,"data":{"link":1,"data":1,"upper":1}
,"layer":{"link":1}
,"active":{"reporting":1}
,"reporting":{"capable":1,"aer":1,"ltr":1}
,"notification":{"capability":1}
,"read":{"completion":1}
,"completion":{"boundary":1}
,"root":{"control":1}
,"correctable":{"error":1}
,"non-fatal":{"error":1}
,"fatal":{"error":1}
,"pme":{"interrupt":1}
,"advanced":{"error":1}
,"latency":{"tolerance":1}
,"tolerance":{"reporting":1}
,"miscellaneous":{"features":1}
,"ram":{"lp0":1}
,"jtag":{"attach":1,"halt":1}
,"rework":{"test":1}
,"test":{"point-":1}
,"halt":{"step":1}
,"ccplex":{"watchdog":1}
,"watchdog":{"reboot":1,"kick":1}
,"pmic":{"watchdog":1}
,"path":{"ahb-dma":1}
,"ahb-dma":{"apb-dma":1,"apb":1}
,"apb-dma":{"engines":1}
,"engines":{"pcie":1,"interact":1}
,"connected":{"directly":1,"respective":1}
,"directly":{"mselect":1}
,"mselect":{"ahb-dma":1}
,"apb":{"dma":1,"buses":1,"engines":1}
,"interact":{"ips":1}
,"ips":{"connected":1}
,"respective":{"ahb":1}
,"ahb":{"apb":1}
,"buses":{"thus":1}
,"thus":{"possible":1}
,"possible":{"either":1}
,"either":{"ahb":1}
,"graphics":{"apis":1,"context":1,"interface":1}
,"glvnd":{"version":1}
,"neutral":{"functionality":1}
,"nvdc":{"direct":1}
,"direct":{"rendering":1}
,"rendering":{"manager":1,"apis":1,"synchronization":1,"using":1}
,"manager":{"drm":1}
,"compatibility":{"drm":1}
,"drm":{"2.0":1}
,"egl":{"stream":1,"without":1,"opengl":1,"interface":1,"enables":1,"1.5":1}
,"x11":{"abi-20":1,"usage":1,"window":1}
,"legacy":{"24.2":1}
,"24.2":{"using":1}
,"using":{"ubuntu":1,"khronos":1,"libargus":1}
,"ubuntu":{"16.04":1,"desktop":1}
,"without":{"x11":1}
,"content":{"display":1}
,"vulkan":{"loader":1,"details":1}
,"loader":{"version":1}
,"1.0.66":{"verified":1}
,"verified":{"working":1}
,"working":{"properly":1}
,"properly":{"release":1}
,"consult":{"https":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"vulkan":1}
,"opengl":{"support":1,"underlying":1,"driver":1,"specifications":1,"common":1,"4.5":1,"khronos":1,"api":1}
,"interface":{"khronos":1,"egl":1,"configured":1}
,"khronos":{"rendering":1,"apis":1,"native":1,"opengl":1}
,"apis":{"opengl":1,"topic":1}
,"underlying":{"native":1}
,"native":{"platform":1}
,"platform":{"window":1,"graphics":1}
,"window":{"system":1}
,"handles":{"graphics":1}
,"context":{"management":1}
,"management":{"surface":1}
,"surface":{"buffer":1}
,"buffer":{"binding":1}
,"binding":{"rendering":1}
,"synchronization":{"egl":1}
,"enables":{"high-performance":1}
,"high-performance":{"accelerated":1}
,"accelerated":{"mixed-mode":1,"gstreamer":1}
,"mixed-mode":{"rendering":1}
,"1.5":{"specification":1}
,"specification":{"khronos":1,"2.0":1}
,"common":{"profile":1}
,"profile":{"specification":1}
,"output":{"formats":1,"stream":1,"streams":1}
,"sampling":{"frequency":1}
,"rate":{"frame":1}
,"frame":{"rate":1}
,"nv12":{"nvmm:nv12":1,"nvmm:1420":1,"nvmm:i420":1}
,"3840":{"2160":1}
,"2160":{"fps":1}
,"fps":{"120":1}
,"120":{"mbps":1}
,"full-frame":{"disable-dpb":1}
,"disable-dpb":{"skip-frames":1}
,"skip-frames":{"enable-error-check":1}
,"enable-error-check":{"enable-frame-type-reporting":1}
,"160":{"mbps":1}
,"decode":{"support":1}
,"gstreamer":{"1.4.5":1,"user":1}
,"1.4.5":{"later":1}
,"i420":{"nvmm:i420":1,"nv12":1}
,"600":{"sec":1}
,"140":{"mbps":1}
,"1920":{"1080":1}
,"1080":{"240":1}
,"240":{"fps":1}
,"nvmm:1420":{"nvmm:nv12":1}
,"nvmm:i420":{"nvmm:nv12":1}
,"gst-inspect-1.0":{"utility":1,"omxh264enc":1,"nvv4l2h264enc":1}
,"utility":{"understand":1}
,"understand":{"feature":1}
,"details":{"example":1,"h.264":1,"argus":1}
,"example":{"gst-inspect-1.0":1}
,"omxh264enc":{"command":1}
,"command":{"gst-inspect-1.0":1,"provides":1}
,"nvv4l2h264enc":{"command":1}
,"provides":{"feature":1}
,"h.264":{"encoder":1}
,"panel":{"overlay":1}
,"conversion":{"scaling":1,"gstreamer-1.0":1,"pcm":1}
,"scaling":{"cropping":1,"gstreamer-1.0":1}
,"cropping":{"rotation":1,"gstreamer-1.0":1}
,"rotation":{"formats":1,"gstreamer-1.0":1}
,"flip-method":{"interpolation-method":1}
,"interpolation-method":{"crop":1}
,"crop":{"format":1}
,"format":{"conversion":1}
,"additional":{"information":1}
,"sections":{"topic":1}
,"topic":{"accelerated":1,"camera":1}
,"basic":{"camera":1}
,"sensors":{"imx219":1}
,"imx219":{"demonstrated":1}
,"demonstrated":{"argus":1}
,"argus":{"camera":1,"refer":1}
,"app":{"nvgstcapture":1,"details":1}
,"nvgstcapture":{"app":1}
,"refer":{"applications":1}
,"applications":{"using":1}
,"libargus":{"low-level":1}
,"low-level":{"apis":1}
,"development":{"capture":1}
,"capture":{"validated":1,"loopback":1}
,"validated":{"3280x2464":1}
,"tnr":{"support":1}
,"option":{"switch":1,"enable":1,"reference":1}
,"switch":{"two":1}
,"two":{"types":1,"adx":1,"amx":1,"channels":1,"mvc":1}
,"types":{"noise":1}
,"noise":{"reduction":1}
,"vics-based":{"temporal":1}
,"temporal":{"noise":1}
,"reduction":{"compromises":1,"improves":1}
,"compromises":{"image":1}
,"image":{"quality":1}
,"quality":{"due":1,"cost":1}
,"due":{"low":1}
,"consumption":{"select":1,"especially":1}
,"tnr.v1":{"camera_overrides.isp":1}
,"gpu-based":{"temporal":1}
,"improves":{"image":1}
,"cost":{"high":1}
,"especially":{"effective":1}
,"effective":{"low":1}
,"light":{"scenes":1}
,"scenes":{"select":1}
,"tnr.v2":{"camera_overrides.isp":1}
,"uvc":{"compliant":1}
,"compliant":{"usb2.0":1}
,"usb2.0":{"usb3.0":1}
,"usb3.0":{"cameras":1}
,"nvgstcapture-1.0":{"option":1}
,"reference":{"section":1}
,"section":{"accelerated":1}
,"user":{"guide":1,"current":1,"aware":1}
,"hda":{"hdmi":1}
,"pcm":{"playback":1,"audio":1}
,"playback":{"stereo":1,"capture":1}
,"stereo":{"5.1":1,"capture":1,"i2s":1,"pcm":1}
,"5.1":{"7.1":1}
,"7.1":{"channel":1}
,"channel":{"configurations":1}
,"sample":{"sizes":1,"rates":1,"size":1}
,"sizes":{"bits":1}
,"bits":{"s16_le":1,"s32_le":1,"used":1,"sample":1,"s24_le":1,"bits":1,"s24_3le":1}
,"s16_le":{"bits":1,"bis":1}
,"s32_le":{"sample":1,"osr":1}
,"44.1":{"88.2":1,"khz":1,"192":1}
,"88.2":{"176.4":1}
,"176.4":{"192":1}
,"192":{"khz":1}
,"khz":{"32\u2011bit":1,"supports":1}
,"32\u2011bit":{"sample":1,"data":1}
,"high-order":{"bits":1}
,"note":{"24\u2011bit":1}
,"24\u2011bit":{"samples":1}
,"samples":{"stored":1}
,"stored":{"32\u2011bit":1}
,"upper":{"bits":1}
,"dmic":{"support":1}
,"s24_le":{"bits":1}
,"osr":{"128":1}
,"256":{"sample":1}
,"interfaces":{"dmic1":1,"i2s3":1}
,"dmic1":{"dmic2":1}
,"i2s":{"support":1,"left":1,"interface":1}
,"11.025":{"22.5":1}
,"22.5":{"44.1":1}
,"normal":{"stereo":1}
,"left":{"justified":1}
,"justified":{"mode":1}
,"ljm":{"right":1}
,"right":{"justified":1}
,"rjm":{"tdm":1}
,"tdm":{"modes":1}
,"modes":{"dsp":1}
,"dsp":{"dsp":1,"channels":1}
,"channels":{"i2s":1,"eight-port":1,"output":1,"supports":1,"per":1}
,"configured":{"master":1}
,"u\u2011law":{"a\u2011law":1}
,"a\u2011law":{"compression":1}
,"compression":{"decompression":1}
,"i2s3":{"i2s4":1}
,"s24_3le":{"sample":1}
,"eight":{"channels":1,"stream":1}
,"eight-port":{"usb":1}
,"demultiplexer":{"adx":1}
,"demultiplexing":{"input":1}
,"stream":{"channels":1}
,"streams":{"channels":1,"two":1,"supports":1}
,"adx":{"instances":1}
,"instances":{"adx1":1,"amx1":1,"sfc1":1,"mvc1":1}
,"adx1":{"adx2":1}
,"multiplexer":{"amx":1}
,"multiplexing":{"four":1}
,"four":{"input":1,"sfc":1}
,"bis":{"s24_le":1}
,"amx":{"instances":1}
,"amx1":{"amx2":1}
,"converter":{"sfc":1}
,"sfc":{"instances":1}
,"sfc1":{"sfc2":1}
,"sfc2":{"sfc3":1}
,"sfc3":{"sfc4":1}
,"volume":{"control":1}
,"gain":{"attenuation":1}
,"attenuation":{"range":1}
,"range":{"120db":1}
,"120db":{"40db":1}
,"11.05":{"22.05":1}
,"22.05":{"44.1":1}
,"mvc":{"instances":1}
,"mvc1":{"mvc2":1}
,"mixing":{"input":1}
,"five":{"outputs":1}
,"outputs":{"combination":1}
,"combination":{"input":1}
,"11.025,16":{"22.05":1}
,"per":{"stream":1}
,"amixer":{"instance":1}
,"warning":{"feature":1,"available":1}
,"notify":{"user":1}
,"desktop":{"issues":1}
,"issues":{"warning":1}
,"falls":{"below":1}
,"below":{"threshold":1}
,"threshold":{"limit":1}
,"limit":{"helps":1,"user-configurable":1}
,"helps":{"user":1}
,"aware":{"new":1}
,"new":{"process":1}
,"process":{"may":1}
,"may":{"lead":1}
,"lead":{"oom-killer":1}
,"oom-killer":{"cause":1}
,"cause":{"system":1}
}
;Search.control.loadWordPairs(pairs);
