var pairs =
{
"opengl":{"programming":1,"want":1,"application":1,"specification":1,"api":1,"comes":1,"2.0":1,"applications":1,"egl":1,"provides":1,"primitives":1,"apis":1}
,"programming":{"tips":1,"opengl":1,"efficiently":1}
,"topic":{"readers":1,"incompatible":1,"thoroughly":1,"contains":1,"describes":1}
,"readers":{"experience":1}
,"experience":{"programming":1,"determining":1}
,"want":{"improve":1,"mipmaps":1}
,"improve":{"performance":1,"image":1,"dma":1,"allocation":1}
,"performance":{"opengl":1,"increase":1,"improvement":1,"boost":1,"consideration":1,"avoided":1,"continuously":1,"benefits":1,"treat":1,"several":1,"loss":1,"even":1,"splitting":1,"cost":1,"therefore":1,"budget":1,"reasons":1,"bottlenecks":1,"cem":1,"speed":1,"distributing":1,"guidelines":1}
,"application":{"aims":1,"initialization":1,"render":1,"makes":1,"needs":1,"frequently":1,"change":1,"lifetime":1,"sends":1,"bottleneck":1,"advantage":1,"memory":1,"becomes":1,"initializes":1,"limited":1,"generating":1,"level":1,"specific":1,"creating":1,"high":1,"knowledge":1,"may":1,"afford":1,"grayscale":1,"updating":1,"judgment":1,"start":1,"reading":1,"always":1,"allocate":1,"complex":1,"rendering":1,"strive":1,"buffer":1,"choose":1,"ability":1}
,"aims":{"providing":1}
,"providing":{"recommendations":1}
,"recommendations":{"getting":1,"topic":1}
,"getting":{"api":1}
,"api":{"hardware":1,"good":1}
,"hardware":{"resources":1,"enabling":1,"high":1,"instance":1,"s3tc":1,"accelerated":1,"amount":1}
,"resources":{"without":1,"expensive":1}
,"without":{"diving":1,"good":1,"rebuilding":1,"buffer":1,"alpha":1,"impacting":1,"seams":1,"prior":1}
,"diving":{"architectural":1}
,"architectural":{"details":1}
,"incompatible":{"consider":1}
,"consider":{"trade-offs":1,"structure":1,"combining":1,"cycling":1,"encoding":1,"case":1,"using":1,"tiling":1}
,"trade-offs":{"cpu":1,"avoided":1}
,"cpu":{"load":1,"doing":1,"gpu":1,"side":1,"bound":1,"efficient":1,"high":1,"optimizing":1,"vertex":1,"instance":1,"usage":1}
,"load":{"memory":1,"may":1,"application":1,"number":1,"subregion":1,"render":1}
,"memory":{"bandwidth":1,"access":1,"locations":1,"every":1,"stored":1,"gldrawarrays":1,"specify":1,"fragmentation":1,"whether":1,"compressed":1,"computations":1,"off-line":1,"32-bit":1,"saved":1,"pot":1,"remember":1,"offsets":1,"pack_subimage":1,"allocations":1,"issues":1,"techniques":1,"overview":1,"heterogenous":1,"allocation":1,"types":1,"often":1,"regions":1,"allocator":1,"major":1,"instead":1,"buffer":1,"buffers":1,"management":1,"avoid":1,"space":1}
,"bandwidth":{"shader":1,"increase":1,"rather":1,"applications":1,"optimize":1,"reduces":1,"saved":1,"requirements":1,"intensive":1,"image":1,"often":1}
,"shader":{"processing":1,"changes":1,"programs":1,"program":1,"e.g":1,"important":1,"gpu":1,"sure":1,"part":1,"unit":1,"state":1,"functions":1,"source":1,"compiler":1,"executed":1,"operation":1,"code":1,"primary":1,"assuming":1,"manipulating":1}
,"processing":{"power":1,"engine":1,"bottleneck":1,"look":1,"likely":1,"hidden":1,"definitely":1,"applications":1}
,"power":{"precision":1,"two":1,"matched":1}
,"precision":{"image":1,"qualifiers":1,"vertex":1,"until":1,"may":1,"optimizations":1,"lowp":1,"several":1,"accessed":1,"fp32":1}
,"image":{"quality":1,"number":1,"texture":1,"icons":1,"width":1,"rectangle":1,"repeat":1,"processing":1,"may":1,"first":1}
,"quality":{"premature":1,"adding":1,"useful":1,"extensions":1,"using":1,"extra":1,"reduced":1,"appropriate":1,"performance":1,"compressed":1,"tiling":1}
,"premature":{"assumptions":1}
,"assumptions":{"effectiveness":1,"changes":1,"fit":1,"performance":1}
,"effectiveness":{"trade-offs":1}
,"avoided":{"definite":1,"cases":1,"possible":1,"defining":1,"expense":1,"whenever":1}
,"definite":{"answers":1}
,"answers":{"benchmarking":1}
,"benchmarking":{"looking":1,"arriving":1,"shaders":1,"final":1,"therefore":1}
,"looking":{"rendered":1}
,"rendered":{"images":1,"buffers":1,"sorted":1,"efficiently":1,"maximum":1,"pixels":1,"time":1,"image":1,"opengl":1}
,"items":{"below":1}
,"below":{"ordered":1,"locations":1}
,"ordered":{"according":1}
,"according":{"importance":1}
,"importance":{"potential":1}
,"potential":{"performance":1,"throughput":1,"gpu":1}
,"increase":{"identifiers":1,"chance":1,"efficiency":1,"sizes":1,"few":1}
,"identifiers":{"parentheses":1}
,"parentheses":{"exist":1}
,"exist":{"reference":1,"vertices":1}
,"inefficient":{"management":1,"code":1}
,"management":{"state":1}
,"state":{"leads":1,"change":1,"unless":1,"redundantly":1,"back":1,"render":1,"initially":1,"variable":1,"tables":1,"queries":1,"assumed":1,"two":1,"always":1,"loop":1,"changes":1,"shaders":1,"generating":1,"binding":1,"bound":1,"stored":1,"generates":1,"backface":1,"almost":1}
,"leads":{"increased":1,"improvement":1,"opportunity":1,"large":1,"high":1}
,"increased":{"cpu":1}
,"may":{"limit":1,"determine":1,"sufficient":1,"lead":1,"logically":1,"fact":1,"required":1,"need":1,"negative":1,"faster":1,"run":1,"improve":1,"even":1,"hide":1,"matter":1,"appear":1,"large":1,"worthwhile":1,"preferable":1,"cases":1,"case":1,"noticeable":1,"possible":1,"better":1,"inconvenient":1,"appropriate":1,"support":1,"padded":1,"expensive":1,"cost":1,"require":1,"two":1,"difficult":1,"consist":1,"orthogonal":1,"special":1,"functionality":1,"high":1}
,"limit":{"amount":1,"discarding":1,"rendering":1,"rendered":1,"texturing":1}
,"amount":{"useful":1,"geometry":1,"memory":1,"indirect":1,"available":1,"minification":1,"cpu":1}
,"useful":{"work":1,"developing":1,"result":1,"high":1,"instance":1,"terrain":1,"minimizing":1,"wrapping":1,"setting":1}
,"work":{"cpu":1,"efficiently":1,"done":1,"deciding":1,"introduced":1,"needed":1,"backwards":1}
,"doing":{"elsewhere":1}
,"elsewhere":{"reducing":1}
,"reducing":{"number":1,"throughput":1,"precision":1,"texture":1,"risk":1,"fragmentation":1}
,"number":{"times":1,"state":1,"vertex":1,"bytes":1,"vertices":1,"components":1,"primitives":1,"attribute":1,"draw":1,"unique":1,"tests":1,"fragments":1,"needed":1,"blended":1,"names":1,"larger":1,"glbindbuffer":1}
,"times":{"rendering":1,"unconditionally":1,"fragment":1,"nearest":1}
,"rendering":{"paused":1,"code":1,"back-faces":1,"optimal":1,"loop":1,"pipeline":1,"screen-aligned":1,"opaque":1,"back-to-front":1,"user":1,"artifacts":1,"example":1,"based":1,"blending":1,"applications":1,"type":1,"surface":1,"subregion":1,"time":1}
,"paused":{"due":1}
,"due":{"state":1,"efficient":1,"syntax":1,"sparse":1,"speed":1}
,"change":{"increase":1,"additionally":1,"source":1}
,"chance":{"realizing":1,"compiling":1}
,"realizing":{"potential":1}
,"throughput":{"gpu":1,"updating":1,"lower":1}
,"gpu":{"main":1,"switching":1,"load":1,"enough":1,"time":1,"caches":1,"able":1,"jump":1,"benefit":1,"introduce":1,"rasterize":1,"work":1,"decide":1,"application":1,"cannot":1,"quickly":1,"opt":1,"careful":1,"resources":1,"parallelism":1,"limits":1,"waiting":1,"gems":1,"model":1,"specific":1,"tracks":1,"native":1,"architectures":1,"whose":1}
,"main":{"point":1,"render":1,"code":1}
,"point":{"section":1,"writing":1,"textures":1}
,"section":{"modify":1,"allocated":1}
,"modify":{"query":1,"depth":1}
,"query":{"state":1,"implementation":1}
,"unless":{"absolutely":1,"depth":1,"relaxed":1,"lighting":1}
,"absolutely":{"necessarily":1,"necessary":1}
,"relevant":{"states":1,"fragment":1,"vector":1}
,"states":{"initialized":1}
,"initialized":{"during":1}
,"during":{"application":1,"rendering":1,"mode":1}
,"initialization":{"main":1,"well-written":1,"left":1,"may":1}
,"render":{"loop":1,"directly":1,"arbitrary":1,"subregion":1,"related":1,"subset":1}
,"loop":{"instance":1,"even":1,"just":1,"application":1,"question":1,"reusing":1,"invariants":1,"single":1,"overhead":1}
,"instance":{"occasionally":1,"batching":1,"rarely":1,"smooth":1,"vertex":1,"lighting":1,"rendering":1,"orthonormal":1,"dot":1,"write":1,"rotation":1,"consider":1,"blending":1,"already":1,"unsigned":1,"less":1}
,"occasionally":{"glcleardepthf":1}
,"glcleardepthf":{"glcolormask":1}
,"glcolormask":{"glviewport":1,"first":1}
,"glviewport":{"finds":1,"int":1,"limit":1}
,"finds":{"application":1}
,"even":{"values":1,"simple":1,"bytes":1,"represented":1,"may":1,"buffer":1,"larger":1,"worse":1,"implemented":1,"efficiently":1,"result":1,"extension":1,"better":1,"one-to-one":1,"accurately":1,"textures":1,"quarter":1,"requires":1,"algorithms":1,"reuse":1}
,"values":{"passed":1,"changed":1,"actually":1,"stencil":1,"although":1,"quantized":1,"may":1,"two":1}
,"passed":{"functions":1,"directly":1}
,"functions":{"always":1,"values":1,"begin":1,"intended":1,"tend":1,"instance":1,"texture":1,"need":1,"variable":1,"textures":1,"copying":1,"avoided":1,"effectively":1}
,"always":{"constant":1,"done":1,"known":1,"enable":1,"during":1,"vertex":1,"used":1,"avoided":1,"benchmarking":1,"result":1,"one-to-one":1,"smallest":1,"expensive":1,"benchmarks":1,"fetches":1,"covers":1}
,"constant":{"times":1,"draw":1,"value":1,"updated":1,"dynamic":1,"stored":1,"per":1,"variable":1}
,"unconditionally":{"loop":1,"used":1}
,"just":{"case":1,"single":1,"operand":1}
,"case":{"values":1,"normalizing":1,"vertices":1,"entire":1,"rendering":1,"result":1,"interpolating":1,"often":1,"user":1,"significantly":1,"heightmap":1,"24-bit":1,"may":1,"unpack_subimage":1,"application":1,"source":1}
,"changed":{"per":1,"value":1,"glfrontface":1}
,"per":{"frame":1,"object":1,"vertex":1,"buffer":1,"model":1,"primitive":1,"draw":1,"fragment":1,"component":1,"face":1,"allocation":1}
,"frame":{"call":1,"hundreds":1,"rate":1,"texture":1,"stalls":1,"special":1,"bandwidth":1}
,"call":{"functions":1,"disable":1,"overhead":1,"buffer":1,"null":1,"computations":1,"belong":1,"texture":1,"glclear":1,"limit":1}
,"actually":{"need":1,"end":1,"contributes":1,"lead":1}
,"need":{"change":1,"query":1,"repeat":1,"specify":1,"one-to-one":1,"loaded":1,"evaluated":1,"highp":1,"anything":1,"low":1,"updated":1}
,"additionally":{"automatically":1,"careful":1}
,"automatically":{"state":1,"packed":1,"expensive":1,"mean":1}
,"back":{"predefined":1,"forth":1,"framebuffer":1,"perhaps":1,"sub-rectangle":1,"application-allocated":1,"buffer":1}
,"predefined":{"value":1}
,"value":{"e.g":1,"described":1,"last":1,"vertexattrib":1,"uniforms":1,"written":1,"clamped":1,"results":1}
,"e.g":{"defaults":1,"sqrt":1,"non-uniform":1,"alpha":1,"lanczos":1,"unsigned_short_5_6_5":1,"image":1,"moved":1,"near":1}
,"defaults":{"idiom":1}
,"idiom":{"useful":1}
,"developing":{"application":1}
,"makes":{"easier":1,"sense":1,"optimizing":1,"possible":1,"technique":1,"practical":1}
,"easier":{"re-order":1}
,"re-order":{"pieces":1}
,"pieces":{"rendering":1,"code":1}
,"code":{"done":1,"without":1,"necessary":1,"easily":1,"geometry":1,"calling":1,"run":1,"contribute":1,"paths":1,"re-use":1,"shared":1,"rewritten":1,"determine":1,"graphics":1,"example":1,"manageable":1,"minimize":1,"path":1}
,"done":{"production":1,"initialization":1,"avoid":1,"eye-space":1,"even":1,"minimally":1,"practice":1}
,"production":{"code":1}
,"good":{"reason":1,"approach":1,"results":1,"performance":1,"introduction":1,"enough":1,"candidate":1,"practices":1,"dynamically":1}
,"avoid":{"querying":1,"wasting":1,"allocating":1,"reducing":1,"computations":1,"conditionals":1,"reading":1,"clearing":1,"video":1,"system":1,"minimize":1}
,"querying":{"state":1}
,"context":{"created":1}
,"created":{"state":1}
,"initially":{"well-defined":1,"using":1}
,"well-defined":{"every":1}
,"every":{"state":1,"time":1,"few":1}
,"variable":{"default":1,"null":1,"particular":1,"gl_frontfacing":1,"follows":1}
,"default":{"value":1,"state":1,"buffer":1,"precision":1,"texture":1}
,"described":{"opengl":1,"below":1,"matrix":1}
,"specification":{"state":1}
,"tables":{"except":1}
,"except":{"compiling":1}
,"compiling":{"shaders":1,"optimally":1}
,"shaders":{"determining":1,"blending":1,"leads":1,"relatively":1,"critical":1,"pieces":1,"source":1,"minimal":1,"run":1,"supported":1,"against":1,"generally":1,"executed":1,"possible":1,"benchmarking":1,"determine":1,"actually":1,"mipmapped":1,"highp":1,"default":1,"normally":1,"sometimes":1}
,"determining":{"available":1,"bottlenecks":1}
,"available":{"extensions":1,"extension":1,"degenerate":1,"platforms":1,"memory":1,"video":1,"free":1}
,"extensions":{"application":1,"provide":1,"experiment":1}
,"needs":{"query":1}
,"implementation":{"specific":1,"algorithm":1,"supports":1}
,"specific":{"constants":1,"geometry":1,"knowledge":1,"application":1,"types":1}
,"constants":{"need":1,"hopefully":1}
,"queries":{"almost":1}
,"almost":{"always":1,"need":1}
,"well-written":{"applications":1}
,"applications":{"check":1,"heavily":1,"best":1,"identify":1,"complex":1,"addition":1}
,"check":{"errors":1,"code":1,"framebuffer":1}
,"errors":{"debug":1,"reported":1}
,"debug":{"builds":1}
,"builds":{"errors":1}
,"reported":{"result":1,"algorithm":1,"graphics":1,"cpu":1}
,"result":{"changing":1,"rendering":1,"false":1,"needed":1,"negative":1,"texture":1,"application":1,"inferior":1,"textures":1,"lower":1,"buffer":1}
,"changing":{"state":1,"usage":1}
,"assumed":{"changes":1}
,"changes":{"part":1,"batching":1,"form":1,"smaller":1,"smooth":1,"enables":1,"mipmap":1,"notes":1}
,"part":{"new":1,"current":1,"color":1}
,"new":{"state":1,"buffers":1,"data":1}
,"two":{"reasons":1,"gpu":1,"sets":1,"attributes":1,"components":1,"commonly":1,"vertices":1,"normals":1,"buffers":1,"linear":1,"dimensions":1,"sizes":1}
,"reasons":{"current":1,"low":1,"minimize":1,"better":1}
,"current":{"state":1,"view":1,"bottleneck":1}
,"known":{"almost":1,"remaining":1,"document":1}
,"frequently":{"calls":1,"alone":1,"updates":1,"middle":1}
,"calls":{"functions":1,"tracked":1,"state":1,"based":1,"uniforms":1,"opengl":1,"batches":1,"thus":1,"issued":1,"opaque":1,"transparent":1,"thought":1,"required":1}
,"begin":{"glis":1,"optimizing":1,"coloring":1,"optimizations":1}
,"glis":{"glget":1}
,"glget":{"calls":1}
,"tracked":{"down":1,"exploited":1}
,"down":{"eliminated":1,"pipeline":1}
,"batch":{"shared":1,"further":1,"geometry":1,"alu":1}
,"shared":{"state":1,"functions":1,"buffer":1}
,"efficient":{"approach":1,"pack":1,"memory":1,"array":1,"volumes":1,"advanced":1,"shaders":1}
,"approach":{"reduce":1,"revealing":1,"waste":1,"often":1,"combining":1,"particularly":1}
,"reduce":{"number":1,"vertex":1,"memory":1,"workload":1,"register":1,"loop":1,"available":1,"variation":1,"total":1,"reported":1}
,"batching":{"together":1,"shader":1,"shaders":1,"tool":1,"opportunities":1,"geometry":1,"less":1}
,"together":{"draw":1,"may":1,"degenerate":1,"geometry":1,"textures":1,"ideally":1}
,"draw":{"calls":1,"call":1,"ordering":1,"assumptions":1}
,"blending":{"textures":1,"texture":1,"testing":1,"alpha":1,"disabled":1,"enabled":1,"needed":1,"operations":1}
,"textures":{"instance":1,"look":1,"return":1,"sub-expressions":1,"sufficient":1,"nearest":1,"consume":1,"taking":1,"less":1,"even":1,"dynamically":1,"size":1,"consider":1,"user":1,"exception":1,"necessarily":1,"water":1,"metal":1,"buildings":1,"objects":1,"different":1,"may":1,"always":1,"floating-point":1,"simply":1,"scaling":1,"cases":1,"supported":1,"used":1,"effectively":1,"sparingly":1,"texture":1,"efficiently":1,"appropriately":1,"mipmaps":1,"saves":1,"repeat":1,"t13":1,"generated":1,"architecture":1,"vbos":1,"surfaces":1,"there\u0027s":1,"together":1,"large":1,"makes":1}
,"gluseprogram":{"drawx1":1,"drawy1":1,"drawx2":1,"drawy2":1,"shaders":1}
,"drawx1":{"gluseprogram":1,"drawx2":1}
,"drawy1":{"gluseprogram":1,"drawy2":1}
,"drawx2":{"gluseprogram":1}
,"improvement":{"fewer":1,"vertex":1,"applies":1}
,"fewer":{"shader":1,"attributes":1,"buffers":1,"larger":1,"textures":1,"buffer":1,"components":1,"bits":1}
,"quite":{"effective":1,"large":1}
,"effective":{"group":1}
,"group":{"draw":1,"dynamic":1,"similar":1,"related":1}
,"based":{"shader":1,"depth":1,"criteria":1,"alpha":1,"whether":1,"bilinear":1}
,"programs":{"reprogramming":1,"vertex":1,"different":1}
,"reprogramming":{"gpu":1}
,"switching":{"shaders":1}
,"relatively":{"costly":1,"few":1,"low-frequency":1}
,"costly":{"operation":1}
,"operation":{"within":1,"discards":1,"forces":1,"depends":1,"latency":1}
,"within":{"batch":1}
,"further":{"optimization":1,"complication":1}
,"optimization":{"made":1,"quickly":1,"rejects":1,"opportunities":1,"iterative":1}
,"made":{"grouping":1,"fit":1,"entirely":1,"abrupt":1,"performance":1}
,"grouping":{"draw":1,"last":1}
,"uniforms":{"texture":1,"intended":1}
,"texture":{"objects":1,"parameters":1,"object":1,"coordinates":1,"sampling":1,"lod":1,"width":1,"samples":1,"samplers":1,"operations":1,"occur":1,"operation":1,"cache":1,"size":1,"compression":1,"resolution":1,"tools":1,"minification":1,"takes":1,"determined":1,"existing":1,"necessarily":1,"magnified":1,"instead":1,"format":1,"needed":1,"single":1,"stored":1,"atlas":1,"page":1,"texture":1,"atlases":1,"images":1,"cubemap":1,"array":1,"tiling":1,"sometimes":1,"extension":1,"may":1,"updates":1,"reused":1,"used":1,"gltexsubimage":1,"filters":1,"filtering":1,"repeats":1,"glcopyteximage":1,"attachment":1,"sure":1,"rendered":1,"put":1,"can\u0027t":1,"containing":1,"maps":1,"image":1,"vbo":1,"map":1,"related":1,"means":1}
,"objects":{"state":1,"perhaps":1,"always":1,"static_draw":1,"larger":1,"non-optimal":1,"rendered":1,"contain":1,"environment":1,"fbo":1,"complex":1,"glteximage":1,"texture":1,"reduce":1,"purpose":1,"information":1,"usually":1,"benchmarking":1,"shared":1,"allocated":1}
,"generating":{"log":1,"excess":1,"mipmap":1,"mipmaps":1,"textures":1}
,"log":{"function":1,"without":1}
,"function":{"calls":1,"reflect":1,"emphasizes":1}
,"revealing":{"poor":1}
,"poor":{"batching":1,"due":1}
,"tool":{"perfhudes":1}
,"perfhudes":{"conveniently":1}
,"conveniently":{"generate":1,"overloads":1}
,"generate":{"log":1}
,"rebuilding":{"application":1}
,"source":{"code":1,"data":1,"shaders":1,"comes":1,"particular":1}
,"repeat":{"per":1,"rebind":1,"mirrored_repeat":1,"few":1,"wrap":1}
,"object":{"state":1,"affects":1,"need":1,"common":1,"bound":1,"shorts":1,"geometry":1,"used":1,"textures":1,"distinct":1,"texture":1,"defined":1,"disabled":1,"greater":1,"newer":1}
,"recall":{"state":1,"vertices":1,"default":1,"mipmapped":1,"sampling":1}
,"bound":{"object":1,"common":1,"draw":1}
,"affects":{"state":1,"work":1}
,"stored":{"object":1,"server":1,"called":1,"bytes":1,"array":1,"smaller":1,"previously":1,"uniform":1,"pre-normalized":1,"luts":1,"luminance":1,"added":1,"unused":1,"texture":1,"using":1}
,"rebind":{"object":1}
,"common":{"mistake":1,"user":1,"images":1}
,"mistake":{"setting":1,"updating":1,"small":1,"normalizing":1,"call":1}
,"setting":{"texture":1,"pack_row_length":1}
,"parameters":{"filtering":1}
,"filtering":{"wrapping":1,"apply":1,"remember":1,"always":1,"fetches":1,"may":1,"trilinear":1,"used":1,"applies":1,"significantly":1,"angle":1,"enable":1,"users":1,"method":1}
,"wrapping":{"every":1,"mode":1,"filtering":1,"restrictions":1,"modes":1}
,"time":{"texture":1,"particular":1,"geometry":1,"consider":1,"rendered":1,"spent":1,"computations":1,"increases":1,"opaque":1,"undefined":1,"consuming":1,"reduces":1}
,"updating":{"uniform":1,"buffers":1,"buffer":1,"existing":1,"sub-rectangle":1,"client":1,"subregion":1,"arbitrary":1}
,"uniform":{"variables":1,"varying":1,"rather":1}
,"variables":{"changed":1,"shader":1,"optimized":1,"interpolated":1,"normalized":1}
,"last":{"time":1,"component":1,"resort":1}
,"particular":{"shader":1,"batching":1,"vertex":1,"value":1,"discard":1,"image":1,"subregion":1}
,"program":{"used":1,"average":1,"start":1}
,"used":{"particular":1,"sample":1,"ways":1,"store":1,"select":1,"gpu":1,"simplify":1,"result":1,"bias":1,"lighting":1,"obvious":1,"instance":1,"textures":1,"remapped":1,"represent":1,"significant":1,"shadow":1,"supported":1,"decision":1,"round-robin":1,"avoid":1,"read":1,"hold":1,"waste":1}
,"opportunities":{"limited":1,"due":1}
,"limited":{"repeating":1,"resource":1,"vertex":1,"sped":1}
,"repeating":{"per":1,"vertex":1}
,"generates":{"enormously":1}
,"enormously":{"inefficient":1}
,"easily":{"measurable":1,"allows":1}
,"measurable":{"impact":1}
,"impact":{"framerate":1,"cpu":1}
,"enable":{"backface":1,"face":1,"anisotropic":1,"expensive":1}
,"backface":{"culling":1}
,"culling":{"whenever":1,"disabled":1,"often":1,"algorithms":1}
,"whenever":{"possible":1,"back-faces":1}
,"face":{"culling":1,"culled":1,"compute":1,"texture":1}
,"back-faces":{"visible":1,"primitives":1}
,"visible":{"rendering":1,"case":1}
,"primitives":{"often":1,"geometry":1,"constant":1,"vertices":1,"substitutes":1,"common":1,"projection":1,"specified":1}
,"often":{"necessary":1,"represented":1,"combined":1,"g10":1,"employed":1,"decreased":1,"texture":1,"yield":1,"case":1,"doubled":1,"makes":1,"banked":1,"improves":1,"offset":1,"freed":1,"consecutive":1,"better":1,"nearly":1}
,"disabled":{"state":1,"example":1,"perform":1,"easily":1}
,"left":{"enabled":1,"int":1}
,"enabled":{"application":1,"straightforward":1,"expensive":1,"sub-textures":1,"taking":1,"number":1}
,"geometry":{"transferred":1,"inefficiently":1,"submitted":1,"minimally":1,"however":1,"optimal":1,"complex":1,"using":1,"requires":1,"instance":1,"winding":1,"face":1,"batches":1,"either":1,"indices":1,"fewer":1,"similar":1,"stitched":1,"degenerate":1,"uses":1,"several":1,"allocate":1,"testing":1,"against":1,"rotational":1,"spheres":1,"hierarchical":1,"entirely":1,"normals":1,"projected":1,"defines":1,"vertex":1,"rendered":1,"alpha":1,"textures":1}
,"transferred":{"large":1}
,"large":{"impact":1,"performance":1,"vertex":1,"buffers":1,"generalized":1,"shaders":1,"number":1,"begin":1,"width":1,"i.e":1,"nothing":1,"100":1,"surfaces":1,"areas":1,"texture":1,"buffer":1}
,"sends":{"geometry":1}
,"inefficiently":{"frequently":1}
,"alone":{"create":1}
,"create":{"bottleneck":1,"large":1}
,"bottleneck":{"cpu":1,"fully":1,"vertex":1,"multiplying":1,"worthwhile":1,"alu":1}
,"side":{"give":1,"accessed":1,"lot":1}
,"give":{"gpu":1}
,"enough":{"data":1,"good":1,"rule":1,"bandwidth":1,"ensure":1,"justify":1,"similarity":1}
,"data":{"work":1,"per":1,"application":1,"creating":1,"type":1,"pointer":1,"photographs":1,"enum":1,"back":1,"texture":1,"loaded":1,"fixed":1,"used":1,"vbos":1}
,"efficiently":{"geometry":1,"mat3":1,"calculate":1,"hardware":1,"draw":1}
,"submitted":{"sizable":1,"application":1}
,"sizable":{"chunks":1}
,"chunks":{"realize":1,"branches":1}
,"realize":{"potential":1}
,"minimally":{"defined":1,"scheduled":1}
,"defined":{"stored":1,"code":1,"homogenous":1,"otherwise":1}
,"server":{"side":1}
,"accessed":{"two":1,"textures":1}
,"caches":{"exist":1}
,"vertices":{"transformed":1,"stored":1,"accomplished":1,"lot":1,"cache":1,"geometry":1,"needed":1,"coincident":1,"index":1,"using":1,"per":1,"fall":1,"need":1,"gpu":1,"ndc":1}
,"indexed":{"primitives":1}
,"vertex":{"processing":1,"cache":1,"order":1,"attributes":1,"increases":1,"attribute":1,"simple":1,"normals":1,"shader":1,"coordinates":1,"comes":1,"sequentially":1,"structure":1,"index":1,"array":1,"buffer":1,"processor":1,"belong":1,"even":1,"fragment":1,"shaders":1,"position":1,"layout":1,"arrays":1}
,"engine":{"contains":1,"already":1}
,"contains":{"cache":1,"miscellaneous":1}
,"cache":{"previously":1,"taking":1,"lead":1,"topic":1,"optimisation":1,"storage":1,"misses":1,"stores":1,"called":1,"instance":1,"indirect":1,"texture_compression_s3tc":1,"utilization":1}
,"previously":{"transformed":1,"applies":1,"rendered":1,"allocated":1}
,"transformed":{"vertices":1,"eye-space":1,"normal":1,"e.g":1}
,"called":{"post-tnl":1,"vcacne":1,"pre-tnl":1}
,"post-tnl":{"vertex":1}
,"taking":{"full":1,"less":1,"account":1}
,"full":{"advantage":1,"screen":1}
,"advantage":{"cache":1,"characteristics":1,"application":1,"specific":1}
,"lead":{"large":1,"limitations":1,"fastest":1,"overly":1,"scattered":1,"long-term":1}
,"fully":{"utilize":1}
,"utilize":{"necessary":1}
,"necessary":{"gpu":1,"used":1,"cpu":1,"p12":1,"least":1,"part":1}
,"able":{"recognize":1}
,"recognize":{"previously":1}
,"accomplished":{"specifying":1}
,"specifying":{"indexed":1}
,"however":{"non-trivial":1,"mean":1,"floating-point":1,"glgeneratemipmap":1,"npot":1,"incorrect":1,"it\u0027s":1}
,"non-trivial":{"geometry":1}
,"optimal":{"order":1,"opengl":1,"performance":1,"reducing":1}
,"order":{"indices":1,"maximizes":1,"worst":1,"depth":1,"ensure":1,"compute":1,"10-15":1,"render":1}
,"indices":{"obvious":1,"achieve":1,"check":1,"may":1}
,"obvious":{"programmer":1,"one-to-one":1}
,"programmer":{"geometry":1}
,"complex":{"application":1,"larger":1,"functions":1,"scene":1,"may":1,"consist":1}
,"look":{"computing":1,"combining":1,"improvements":1}
,"computing":{"vertex":1}
,"maximizes":{"hit":1}
,"hit":{"ratio":1}
,"ratio":{"post":1,"suitable":1,"improves":1}
,"post":{"tnl":1}
,"tnl":{"cache":1}
,"thoroughly":{"studied":1}
,"studied":{"years":1}
,"years":{"even":1,"find":1}
,"simple":{"greedy":1,"object":1,"bounding":1,"box":1}
,"greedy":{"algorithms":1}
,"algorithms":{"provide":1,"heavily":1,"following":1,"require":1}
,"provide":{"substantial":1,"block-based":1,"visual":1,"better":1}
,"substantial":{"performance":1}
,"boost":{"good":1}
,"results":{"reported":1,"ensure":1,"changing":1,"zero-product":1,"executed":1,"good":1}
,"algorithm":{"described":1,"library":1,"leads":1,"assumptions":1}
,"url":{"latest":1}
,"linear-speed":{"vertex":1}
,"optimisation":{"tom":1}
,"tom":{"forsyth":1}
,"forsyth":{"rad":1}
,"rad":{"game":1}
,"game":{"tools":1}
,"tools":{"28th":1,"compress":1}
,"28th":{"september":1}
,"september":{"2006":1}
,"free":{"implementation":1,"cubemap":1,"allocated":1,"vbos":1,"space":1,"buffer":1,"reallocate":1}
,"library":{"called":1}
,"attributes":{"size":1,"fixed":1,"32\u2011bit":1,"normally":1,"completely":1,"automatically":1,"limited":1,"together":1,"even":1,"two":1,"given":1,"due":1,"constant":1,"separate":1,"vertex":1,"updated":1,"read":1,"remain":1}
,"size":{"attribute":1,"components":1,"minimize":1,"format":1,"may":1,"content":1,"texture":1,"framebuffer":1,"used":1,"const":1,"small":1,"allocated":1,"say":1,"blocks":1}
,"attribute":{"may":1,"data":1,"size":1,"primitive":1,"index":1,"four":1,"layout":1,"non-zero":1,"components":1,"stride":1,"gl_position":1}
,"determine":{"efficiency":1,"conditionals":1,"forward":1,"improved":1,"really":1,"improves":1}
,"efficiency":{"cache":1,"texture":1,"blending":1}
,"storage":{"fixed":1,"un-mipmapped":1}
,"fixed":{"number":1,"therefore":1,"point":1,"overhead":1,"allocation":1,"size":1}
,"bytes":{"active":1,"per":1,"flag":1,"shorts":1,"normalized":1,"modified":1}
,"active":{"attributes":1}
,"lot":{"attribute":1,"faster":1}
,"increases":{"risk":1,"efficiency":1}
,"risk":{"cache":1,"gpu":1}
,"misses":{"resulting":1}
,"resulting":{"potentially":1}
,"potentially":{"redundant":1,"lower":1}
,"redundant":{"transformations":1}
,"transformations":{"vertices":1,"applied":1}
,"important":{"appropriate":1,"benchmark":1,"increase":1,"specify":1,"begin":1,"gpu":1,"large":1}
,"appropriate":{"attribute":1,"vertex":1,"offset":1,"usage":1,"offsets":1,"precision":1,"size":1,"texture":1}
,"minimize":{"number":1,"possibility":1,"floating-point":1,"benefit":1,"memory":1,"fragmentation":1,"dynamic":1,"allocations":1}
,"components":{"avoid":1,"direction":1,"fewer":1,"instead":1,"unpacking":1,"rarely":1,"sizes":1,"cos":1,"using":1,"bits":1}
,"wasting":{"memory":1}
,"stores":{"pre-transformed":1,"attributes":1,"vertex":1}
,"pre-transformed":{"vertices":1}
,"pre-tnl":{"vertex":1}
,"rarely":{"need":1,"performance":1,"done":1}
,"specify":{"attributes":1,"vertices":1,"eliminates":1,"mipmap":1,"texture":1}
,"32\u2011bit":{"floats":1}
,"floats":{"possible":1,"fp16":1}
,"possible":{"define":1,"static_draw":1,"need":1,"data":1,"shortcuts":1,"instance":1,"e.g":1,"textures":1,"texture":1,"store":1,"last":1,"free":1,"replace":1,"improve":1,"performance":1,"combine":1,"cases":1,"memory":1,"grouping":1}
,"define":{"object-space":1,"specular":1,"minimal":1}
,"object-space":{"geometry":1}
,"using":{"bytes":1,"offset":1,"extension":1,"unsigned_byte":1,"glshadersource":1,"stencil":1,"highp":1,"lowp":1,"cubemaps":1,"texture":1,"simple":1,"advanced":1,"smaller":1,"bit":1,"texels":1,"single":1,"bits":1,"npot":1,"gltexsubimage":1,"textures":1,"mirrored_repeat":1,"instance":1,"opengl":1,"buffer":1}
,"shorts":{"complex":1,"flag":1,"few":1}
,"larger":{"object":1,"buffers":1,"integer":1,"data":1,"performance":1,"batches":1,"range":1,"allocations":1,"besides":1,"buffer":1}
,"requires":{"floating-point":1,"loop":1,"always":1,"allocating":1}
,"floating-point":{"representation":1,"texture":1,"textures":1,"format":1}
,"representation":{"half-floats":1}
,"half-floats":{"available":1}
,"extension":{"oes_vertex_half_float.txt":1,"nv_primitive_restart2":1,"available":1,"gives":1,"yields":1,"supports":1,"supported":1,"importantly":1,"reason":1,"used":1}
,"oes_vertex_half_float.txt":{"may":1}
,"sufficient":{"per-vertex":1,"precision":1,"store":1}
,"per-vertex":{"colors":1}
,"colors":{"accurately":1,"normals":1,"values":1,"low":1,"remapped":1}
,"accurately":{"stored":1,"represented":1}
,"flag":{"normalize":1,"allocating":1,"may":1,"alternatives":1}
,"normalize":{"vertexattributepointer":1,"tiling":1,"vectors":1,"normal":1}
,"vertexattributepointer":{"texture":1}
,"coordinates":{"sometimes":1,"necessary":1,"normal":1,"multi-texturing":1,"full-screen":1,"-1.0,1.0":1,"may":1,"uncompressed":1,"reference":1,"possible":1,"used":1,"wrapping":1}
,"sometimes":{"represented":1,"factor":1,"stored":1,"implemented":1,"useful":1,"reduced":1,"case":1,"hard":1,"referred":1,"possible":1,"even":1}
,"represented":{"bytes":1,"shorts":1,"components":1,"using":1,"half-precision":1}
,"exception":{"case":1}
,"normalizing":{"texture":1,"vectors":1}
,"sample":{"cube":1}
,"cube":{"map":1}
,"map":{"texture":1,"describe":1,"visual":1,"area":1,"ability":1}
,"normals":{"often":1,"even":1,"inverse-transpose":1,"texture":1,"having":1,"order":1,"interpolated":1,"coordinates":1}
,"few":{"cases":1,"frames":1,"vertices":1,"orders":1,"large":1,"patterns":1}
,"cases":{"cuboids":1,"time":1,"lead":1,"always":1,"smaller":1,"avoiding":1,"reported":1}
,"cuboids":{"even":1}
,"normalized":{"normals":1,"vertex":1,"device":1,"ensure":1}
,"direction":{"sign":1}
,"sign":{"normal":1}
,"normal":{"implicit":1,"trivially":1,"light":1,"matrix":1,"vectors":1,"maps":1}
,"implicit":{"given":1,"case":1}
,"given":{"length":1,"vertex":1,"frame":1,"operations":1,"texture":1}
,"length":{"known":1,"vectors":1}
,"remaining":{"coordinate":1,"ones":1}
,"coordinate":{"derived":1}
,"derived":{"vertex":1,"fragment":1}
,"sqrt":{"memory":1}
,"rather":{"vertex":1,"repeating":1,"free":1}
,"likely":{"bottleneck":1,"performance":1,"identical":1}
,"characteristics":{"specific":1}
,"smooth":{"sphere":1,"colors":1}
,"sphere":{"uses":1}
,"uses":{"normalized":1,"relatively":1}
,"trivially":{"computed":1,"rejected":1}
,"computed":{"vertex":1,"number":1}
,"benchmark":{"intermediate":1,"determine":1,"application":1,"changes":1}
,"intermediate":{"results":1}
,"ensure":{"vertex":1,"opaque":1,"correct":1,"dot-product":1,"smaller":1}
,"already":{"saturated":1,"8-bit":1}
,"saturated":{"finally":1}
,"finally":{"remember":1}
,"remember":{"attribute":1,"driver":1,"nearest-neighbor":1}
,"primitive":{"number":1,"per":1,"face":1}
,"disable":{"particular":1,"color":1,"depth":1,"early-z":1,"blending":1}
,"index":{"constant":1,"buffer":1,"buffers":1}
,"vertexattrib":{"instead":1}
,"instead":{"replicating":1,"two":1,"unsigned_short":1,"built-in":1,"spent":1,"separate":1,"re-defining":1,"starting":1,"requiring":1}
,"replicating":{"data":1}
,"pack":{"vertex":1,"attributes":1,"components":1}
,"normally":{"different":1,"contain":1,"requires":1,"affects":1}
,"different":{"sets":1,"memory":1,"geometry":1,"textures":1,"code":1,"kinds":1,"frequency":1,"stages":1,"types":1,"alignment":1,"banks":1}
,"sets":{"attributes":1,"texture":1}
,"completely":{"unrelated":1}
,"unrelated":{"unlike":1,"models":1}
,"unlike":{"uniform":1,"s3tc":1}
,"varying":{"variables":1,"sizes":1}
,"packed":{"number":1,"texture":1}
,"resource":{"failure":1,"recall":1}
,"failure":{"pack":1}
,"limitations":{"sooner":1}
,"sooner":{"expected":1}
,"expected":{"efficient":1}
,"logically":{"related":1,"separate":1}
,"related":{"instance":1,"images":1,"vertex":1,"objects":1,"allocations":1,"cpus":1}
,"comes":{"two":1,"functions":1,"application":1}
,"multi-texturing":{"often":1,"using":1}
,"combined":{"attribute":1,"end":1,"approach":1}
,"four":{"components":1,"texels":1,"times":1}
,"unpacking":{"swizzling":1}
,"swizzling":{"components":1}
,"choose":{"appropriate":1,"right":1,"contiguous":1}
,"commonly":{"used":1}
,"ways":{"storing":1}
,"storing":{"vertex":1,"packed":1}
,"array":{"structures":1,"indices":1,"texture":1,"textures":1}
,"structures":{"arrays":1,"stores":1,"preferred":1,"cases":1,"expensive":1,"attributes":1}
,"sequentially":{"appropriate":1,"respectively":1}
,"offset":{"attribute":1,"sizeiptr":1,"saving":1}
,"non-zero":{"stride":1}
,"stride":{"stride":1,"computed":1,"zero":1,"pixels":1}
,"sizes":{"array":1,"batches":1,"especially":1,"aren\u0027t":1,"chosen":1,"smallest":1}
,"preferred":{"storing":1,"layout":1,"additionally":1}
,"access":{"vertex":1,"texture":1,"write":1}
,"updated":{"render":1,"dynamically":1,"frequency":1,"every":1,"per":1}
,"question":{"array":1}
,"contrast":{"structure":1}
,"structure":{"arrays":1}
,"arrays":{"stores":1,"layout":1,"combined":1,"single":1}
,"separate":{"buffers":1,"buffer":1,"textures":1,"draw":1,"rendering":1,"banks":1}
,"buffers":{"using":1,"graphics":1,"draw":1,"used":1,"leading":1,"appropriate":1,"needed":1,"rendering":1,"application":1,"helps":1,"consider":1,"minimize":1,"needlessly":1,"full":1,"textures":1,"whether":1,"ability":1,"early":1,"start":1,"ideally":1,"varying":1,"whenever":1,"often":1,"makes":1}
,"zero":{"layout":1,"default":1,"accomplishes":1}
,"layout":{"forces":1,"therefore":1,"attributes":1,"multiple":1,"likely":1}
,"forces":{"gpu":1}
,"jump":{"around":1}
,"around":{"fetch":1,"basic":1}
,"fetch":{"different":1}
,"locations":{"assembles":1}
,"assembles":{"needed":1}
,"needed":{"attributes":1,"vertex":1,"tends":1,"lighting":1,"scalar":1,"time":1,"sub-image":1,"later":1,"reuse":1}
,"therefore":{"less":1,"important":1,"application":1,"makes":1}
,"less":{"efficient":1,"fixed":1,"memory":1,"available":1,"hard":1,"accuracy":1,"splitting":1,"twice":1,"expensive":1}
,"dynamically":{"strided":1,"stored":1,"due":1,"generated":1,"application":1,"allocated":1}
,"strided":{"writes":1}
,"writes":{"array":1,"glcolormask":1,"enabled":1,"gldepthmask":1}
,"expensive":{"relative":1,"test":1,"vertex":1,"fragment":1,"alu":1,"manually":1,"applies":1,"conversion":1,"texture":1,"bilinear":1,"bandwidth":1,"filtering":1,"grey-scale":1,"objects":1}
,"relative":{"number":1,"cost":1}
,"modified":{"scenario":1,"constrain":1}
,"scenario":{"recommendation":1}
,"recommendation":{"partition":1}
,"partition":{"attributes":1,"rendering":1,"analysis":1}
,"dynamic":{"attributes":1,"allocation":1,"allocations":1}
,"read":{"written":1,"back":1,"write":1,"subregion":1}
,"written":{"sequentially":1,"depth":1,"fragment":1}
,"respectively":{"attributes":1,"techniques":1}
,"remain":{"constant":1}
,"smaller":{"separate":1,"specialized":1,"size":1,"texture":1,"appropriately":1,"memory":1,"mipmaps":1,"pieces":1,"number":1,"images":1,"work":1}
,"buffer":{"objects":1,"attributes":1,"bind":1,"usage":1,"although":1,"always":1,"contents":1,"large":1,"store":1,"common":1,"specify":1,"choose":1,"object":1,"content":1,"high":1,"mask":1,"first":1,"serve":1,"frame":1,"modified":1,"allocation":1,"reusing":1,"deleting":1,"second":1,"glclear":1,"subregion":1,"opengl":1,"long":1,"isn\u0027t":1,"reduce":1,"size":1,"sizes":1,"contain":1,"new":1,"program":1,"handle":1,"followed":1}
,"perhaps":{"just":1,"typically":1,"picking":1}
,"single":{"buffer":1,"simple":1,"component":1,"precision":1,"pixel":1,"pattern":1,"texture":1,"vbo":1,"size":1}
,"consistent":{"winding":1}
,"winding":{"clockwise":1,"different":1}
,"clockwise":{"counter-clockwise":1}
,"counter-clockwise":{"determined":1}
,"determined":{"front":1,"size":1}
,"front":{"defined":1}
,"culled":{"changed":1,"cpu":1}
,"glfrontface":{"having":1}
,"having":{"switch":1,"transformed":1}
,"switch":{"back":1}
,"forth":{"winding":1}
,"batches":{"during":1,"geometry":1,"whenever":1,"broken":1,"rendering":1}
,"either":{"sourced":1,"wrapping":1}
,"sourced":{"application":1}
,"graphics":{"memory":1,"ji\u0159\u00ED":1,"application":1,"pipeline":1,"bottlenecks":1,"applications":1,"driver":1}
,"applies":{"vertex":1,"textures":1,"depth":1,"anisotropic":1}
,"achieve":{"good":1}
,"continuously":{"source":1}
,"gldrawarrays":{"buffer":1,"code":1,"enum":1,"allows":1}
,"store":{"geometry":1,"two":1,"multiple":1,"outside":1,"values":1,"using":1,"parameter":1}
,"calling":{"gldrawarrays":1,"gldrawelements":1,"gluseprogram":1,"gltexsubimage":1}
,"gldrawelements":{"without":1}
,"usage":{"flag":1,"flags":1,"careless":1,"may":1,"environment":1}
,"allocating":{"buffer":1,"new":1,"freeing":1,"buffers":1,"video":1,"large":1,"larger":1}
,"static_draw":{"cases":1,"mean":1,"flag":1}
,"fastest":{"access":1}
,"mean":{"write":1,"gpu":1,"trilinear":1}
,"write":{"buffer":1,"large":1,"shader":1,"framebuffer":1,"application":1,"differently":1}
,"although":{"writing":1,"glsl":1,"glgeneratemipmap":1,"colors":1,"non-power-of-two":1,"replaced":1}
,"writing":{"buffer":1,"efficient":1,"generalized":1,"shader":1,"twice":1,"disabled":1,"gpu":1}
,"fact":{"appropriate":1,"yield":1}
,"flags":{"even":1}
,"contents":{"updated":1,"teximage":1,"read":1}
,"frames":{"careful":1,"environment":1}
,"careful":{"benchmarking":1,"writing":1,"assuming":1}
,"arriving":{"conclusive":1}
,"conclusive":{"results":1}
,"alternatives":{"dynamic_draw":1}
,"dynamic_draw":{"stream_draw":1}
,"stream_draw":{"considered":1}
,"becomes":{"cpu":1}
,"overhead":{"less":1,"sending":1,"otherwise":1,"per":1,"approach":1}
,"one-to-one":{"correspondence":1,"mapping":1}
,"correspondence":{"draw":1}
,"similar":{"layout":1,"geometry":1,"size":1,"used":1,"apis":1,"allocations":1}
,"multiple":{"models":1,"buffers":1,"images":1,"distinct":1,"types":1,"independent":1,"objects":1,"vertex":1}
,"models":{"index":1,"fewer":1}
,"select":{"subset":1}
,"subset":{"vertices":1,"texture":1,"vbo":1}
,"small":{"buffers":1,"shaders":1,"order":1,"apis":1,"allocations":1,"multiples":1,"percentage":1}
,"leading":{"draw":1,"null":1,"twice":1}
,"thus":{"high":1}
,"high":{"cpu":1,"cost":1,"depth":1,"precision":1,"resolution":1,"fact":1}
,"issued":{"given":1}
,"hundreds":{"thousands":1,"texels":1,"objects":1}
,"thousands":{"time":1,"vertices":1}
,"combining":{"similar":1,"several":1,"related":1,"multiple":1,"group":1}
,"offsets":{"defining":1,"pointer":1}
,"defining":{"attribute":1,"vertices":1}
,"creating":{"index":1,"modelview":1}
,"unconnected":{"geometry":1}
,"stitched":{"together":1}
,"degenerate":{"triangles":1}
,"triangles":{"alternatively":1,"triangles":1,"two":1,"fewer":1,"down":1}
,"alternatively":{"using":1}
,"nv_primitive_restart2":{"available":1}
,"coincident":{"leading":1}
,"null":{"surface":1,"data":1,"vector":1}
,"surface":{"trivially":1,"first":1,"transferring":1,"back":1,"native":1}
,"rejected":{"ignored":1}
,"ignored":{"gpu":1}
,"benefit":{"stitching":1,"texture":1}
,"stitching":{"together":1}
,"tends":{"outweigh":1,"increase":1,"lead":1}
,"outweigh":{"minor":1}
,"minor":{"overhead":1}
,"sending":{"degenerates":1}
,"degenerates":{"triangles":1}
,"pipeline":{"geometry":1,"useful":1,"traversed":1,"early-z":1,"limits":1,"work":1,"normally":1,"introduction":1,"performance":1}
,"broken":{"bind":1,"smaller":1}
,"bind":{"different":1,"framebuffer":1}
,"several":{"images":1,"unrelated":1,"reasons":1,"benefits":1,"frames":1}
,"images":{"fewer":1,"channels":1,"compress":1,"hard":1,"stored":1,"sometimes":1,"texture":1,"geometry":1,"good":1,"running":1,"worthwhile":1,"contain":1,"vbos":1,"single":1}
,"smallest":{"possible":1,"free":1}
,"type":{"indices":1,"es2":1,"batching":1,"e.g":1,"texture":1,"object":1,"const":1,"void":1}
,"unsigned_byte":{"instead":1}
,"unsigned_short":{"even":1}
,"integer":{"type":1}
,"es2":{"implementation":1,"clamp_to_edge":1}
,"supports":{"count":1,"compressing":1}
,"count":{"number":1}
,"unique":{"vertices":1,"colors":1}
,"right":{"data":1}
,"required":{"concern":1,"workload":1,"efficiently":1,"geometry":1,"determine":1,"separate":1,"render":1}
,"concern":{"compared":1}
,"compared":{"larger":1}
,"benefits":{"batching":1,"result":1}
,"updates":{"geometry":1,"required":1,"transforms":1}
,"allocate":{"sufficiently":1,"minimal":1,"minimize":1,"large":1}
,"sufficiently":{"large":1,"invalidate":1}
,"initializes":{"glbufferdata":1}
,"glbufferdata":{"call":1,"enum":1}
,"pointer":{"reserve":1,"arithmetic":1}
,"reserve":{"amount":1}
,"eliminates":{"time":1}
,"spent":{"waiting":1,"actually":1}
,"waiting":{"allocation":1,"resource":1}
,"allocation":{"complete":1,"algorithms":1,"speed":1,"regardless":1,"overhead":1,"freeing":1,"even":1,"mandatory":1,"buffer":1,"happens":1}
,"complete":{"rendering":1}
,"reusing":{"pre-allocated":1,"existing":1,"buffer":1}
,"pre-allocated":{"buffers":1}
,"helps":{"reduce":1}
,"introduce":{"bubbles":1}
,"bubbles":{"pipeline":1}
,"cycling":{"multiple":1}
,"possibility":{"updating":1}
,"content":{"currently":1,"gives":1,"entire":1}
,"currently":{"rendered":1}
,"cull":{"early":1,"clip":1}
,"early":{"often":1,"pipeline":1}
,"rasterize":{"primitives":1}
,"fall":{"outside":1}
,"outside":{"viewport":1,"view":1,"texture":1}
,"viewport":{"avoids":1}
,"avoids":{"processing":1}
,"hidden":{"fragments":1}
,"fragments":{"depth":1,"based":1,"overdrawn":1,"applications":1,"modify":1,"early":1,"processed":1,"kept":1}
,"depth":{"test":1,"stencil":1,"complexity":1,"testing":1,"buffer":1,"writes":1,"unless":1,"writing":1,"value":1,"texture":1}
,"test":{"stencil":1,"fails":1,"against":1,"made":1}
,"stencil":{"test":1,"culling":1,"testing":1,"buffer":1,"buffers":1}
,"fails":{"however":1}
,"deciding":{"visible":1}
,"loaded":{"assembled":1,"doesn\u0027t":1}
,"assembled":{"processed":1}
,"processed":{"vertex":1,"chunks":1}
,"decide":{"whether":1}
,"whether":{"cull":1,"shader":1,"constant":1,"trade-off":1,"alpha":1,"textures":1}
,"clip":{"parts":1}
,"parts":{"geometry":1}
,"testing":{"single":1,"hundreds":1,"fragment":1,"enabled":1,"unless":1,"t10":1,"required":1,"define":1,"needed":1}
,"bounding":{"volume":1}
,"volume":{"encloses":1,"choice":1}
,"encloses":{"geometry":1}
,"against":{"current":1,"volume":1,"conflicting":1}
,"view":{"frustum":1}
,"frustum":{"cpu":1,"culled":1}
,"faster":{"testing":1,"max":1,"download":1,"given":1,"linear":1}
,"definitely":{"place":1}
,"place":{"begin":1,"rendering":1}
,"optimizing":{"spheres":1,"expensive":1,"shaders":1,"uncompressed":1,"opengl":1,"rendering":1}
,"spheres":{"efficient":1,"tend":1}
,"volumes":{"test":1}
,"choice":{"geometry":1}
,"rotational":{"symmetrical":1}
,"symmetrical":{"geometry":1}
,"tend":{"lead":1,"overly":1,"occur":1,"break":1}
,"overly":{"conservative":1,"generic":1}
,"conservative":{"visibility":1}
,"visibility":{"acceptance":1,"computer":1}
,"acceptance":{"rectangular":1}
,"rectangular":{"cuboid":1}
,"cuboid":{"box":1}
,"box":{"slightly":1,"filter":1,"region":1}
,"slightly":{"expensive":1,"blurred":1}
,"fit":{"tightly":1,"particular":1}
,"tightly":{"geometry":1}
,"hierarchical":{"culling":1}
,"employed":{"reduce":1}
,"tests":{"necessary":1}
,"advanced":{"culling":1,"filters":1}
,"heavily":{"researched":1,"fragment":1}
,"researched":{"published":1}
,"published":{"years":1}
,"find":{"good":1}
,"introduction":{"survey":1,"identifying":1}
,"survey":{"below":1}
,"computer":{"graphics":1}
,"ji\u0159\u00ED":{"bittner":1}
,"bittner":{"peter":1}
,"peter":{"wonka":1}
,"critical":{"achieving":1,"resist":1,"limit":1,"areas":1}
,"achieving":{"good":1}
,"treat":{"shaders":1,"system":1}
,"run":{"inner-most":1,"fast":1,"slow":1,"experiments":1,"twice":1,"slower":1,"determine":1}
,"inner-most":{"loops":1}
,"loops":{"cpu":1}
,"cost":{"littering":1,"however":1,"dot":1,"based":1,"four":1,"interpolating":1,"filtering":1}
,"littering":{"conditionals":1}
,"conditionals":{"recomputing":1,"shaders":1,"skip":1,"vertex":1,"fragment":1}
,"recomputing":{"loop":1}
,"invariants":{"optimizing":1}
,"sure":{"geometry":1,"application":1,"benchmark":1,"check":1}
,"entirely":{"outside":1,"observing":1}
,"fragment":{"shader":1,"processor":1,"light":1,"gets":1,"limited":1,"shaders":1,"i.e":1}
,"excess":{"number":1}
,"contribute":{"output":1}
,"output":{"variables":1,"variable":1,"images":1}
,"optimized":{"compiler":1}
,"compiler":{"feature":1,"gpu":1,"reduce":1}
,"feature":{"exploited":1}
,"exploited":{"gain":1,"possible":1}
,"gain":{"knowledge":1}
,"knowledge":{"whether":1,"used":1,"reduce":1,"stride":1}
,"multiplying":{"output":1}
,"vector":{"reduce":1,"transformed":1,"naturally":1,"computations":1,"may":1,"terms":1,"generalized":1,"matrix":1,"obeys":1}
,"workload":{"measure":1,"offload":1,"tends":1,"warning":1,"conditional":1}
,"measure":{"frame":1,"headroom":1}
,"rate":{"improves":1,"even":1,"batching":1,"result":1}
,"improves":{"conversely":1,"quality":1,"frame":1,"reduces":1,"rendering":1}
,"conversely":{"final":1}
,"final":{"stages":1,"shader":1,"say":1,"application":1}
,"stages":{"optimization":1,"graphics":1,"often":1}
,"quickly":{"measure":1,"reject":1}
,"headroom":{"increasing":1}
,"increasing":{"workload":1,"texture":1}
,"offload":{"computations":1}
,"computations":{"shader":1,"pipeline":1,"constant":1,"belong":1,"math":1,"transforming":1,"reduce":1,"unlike":1}
,"unit":{"improve":1,"length":1}
,"adding":{"meaningless":1,"further":1}
,"meaningless":{"expensive":1}
,"alu":{"instructions":1,"texture":1,"operations":1}
,"instructions":{"texture":1,"instance":1,"unpack":1}
,"sampling":{"output":1,"difficult":1,"texture":1,"anisotrophically":1}
,"move":{"computations":1,"remaining":1}
,"traversed":{"cpu":1}
,"processor":{"fragment":1,"required":1,"moved":1,"earlier":1}
,"orders":{"magnitude":1}
,"magnitude":{"time":1}
,"model":{"per":1,"gpus":1}
,"belong":{"fragment":1,"vertex":1,"shader":1}
,"moved":{"vertex":1,"cpu":1,"rotated":1}
,"earlier":{"per":1}
,"lighting":{"done":1,"equation":1,"equations":1,"per":1,"objects":1}
,"eye-space":{"light":1,"stored":1}
,"light":{"vector":1,"reflected":1}
,"worse":{"per":1}
,"naturally":{"stored":1}
,"pre-normalized":{"usually":1}
,"usually":{"light":1,"represented":1,"consist":1}
,"generalized":{"shaders":1,"rotation":1}
,"resist":{"temptation":1}
,"temptation":{"write":1}
,"paths":{"depending":1}
,"depending":{"whether":1,"texture":1,"composition":1}
,"intended":{"constants":1,"concatenation":1}
,"hopefully":{"primitives":1}
,"substitutes":{"calling":1}
,"minimal":{"specialized":1,"scissor":1,"pool":1}
,"specialized":{"task":1,"shaders":1}
,"task":{"perform":1}
,"perform":{"better":1,"experiments":1,"draw":1}
,"better":{"small":1,"performance":1,"image":1,"store":1,"nearest":1,"indication":1,"bind":1,"create":1,"organize":1}
,"fast":{"few":1,"non-lod":1,"hardware":1}
,"slow":{"code":1}
,"re-use":{"source":1}
,"supported":{"handled":1,"array":1,"es2":1,"unpack_row_length":1,"useful":1}
,"handled":{"application":1}
,"level":{"using":1,"int":1,"enum":1}
,"glshadersource":{"advice":1}
,"advice":{"writing":1}
,"conflicting":{"goal":1}
,"goal":{"minimizing":1}
,"minimizing":{"shader":1,"state":1}
,"generally":{"preferred":1,"bad":1,"least":1,"it\u0027s":1}
,"concatenation":{"final":1}
,"generic":{"harder":1}
,"harder":{"exploit":1}
,"exploit":{"possible":1,"texture":1}
,"simplify":{"avoid":1}
,"math":{"shortcuts":1,"optimizations":1}
,"shortcuts":{"pursued":1}
,"pursued":{"everywhere":1}
,"everywhere":{"optimizations":1}
,"optimizations":{"shader":1,"approached":1,"p11":1,"yield":1,"identifying":1}
,"cannot":{"instance":1,"used":1,"even":1,"mipmapped":1}
,"screen-aligned":{"primitives":1}
,"user":{"interface":1,"interfaces":1}
,"interface":{"post-processing":1,"elements":1,"helpful":1}
,"post-processing":{"effects":1}
,"effects":{"case":1}
,"entire":{"modelview":1,"framebuffer":1,"contents":1,"region":1,"color":1}
,"modelview":{"transformation":1,"matrix":1}
,"transformation":{"avoided":1}
,"ndc":{"normalized":1}
,"device":{"coordinates":1}
,"full-screen":{"quad":1}
,"quad":{"vertex":1}
,"-1.0,1.0":{"range":1}
,"range":{"passed":1,"values":1}
,"directly":{"vertex":1,"accessing":1,"texture":1}
,"gl_position":{"types":1}
,"types":{"matrix":1,"video":1,"number":1,"vary":1,"gpu":1,"memory":1,"important":1,"faster":1,"adding":1}
,"matrix":{"transformations":1,"tracked":1,"e.g":1,"defined":1,"just":1,"described":1,"applied":1,"components":1,"practice":1,"common":1,"rotates":1}
,"applied":{"application":1,"vec3":1}
,"orthonormal":{"matrix":1}
,"non-uniform":{"scaling":1}
,"scaling":{"leads":1,"instructions":1}
,"opportunity":{"avoid":1}
,"transforming":{"normals":1}
,"inverse-transpose":{"sub-matrix":1}
,"optimize":{"depth":1,"texture":1}
,"reject":{"fragments":1,"order":1}
,"executed":{"depth":1,"disable":1,"block":1}
,"complexity":{"scene":1,"measured":1,"ensure":1,"often":1}
,"scene":{"number":1,"result":1,"mipmaps":1,"done":1}
,"gets":{"written":1,"difficult":1}
,"measured":{"incrementing":1}
,"incrementing":{"values":1}
,"opaque":{"objects":1,"color":1,"geometry":1}
,"non-optimal":{"order":1}
,"worst":{"case":1}
,"back-to-front":{"aka":1}
,"aka":{"painter\u0027s":1}
,"painter\u0027s":{"algorithm":1}
,"overdrawn":{"application":1}
,"sorted":{"front-to-back":1}
,"front-to-back":{"order":1}
,"straightforward":{"rendering":1}
,"interfaces":{"leads":1,"recall":1}
,"decreased":{"technique":1}
,"technique":{"using":1,"practical":1}
,"mask":{"fragments":1}
,"sped":{"significantly":1}
,"significantly":{"clever":1,"outnumber":1,"smaller":1,"expensive":1}
,"clever":{"techniques":1}
,"techniques":{"sometimes":1,"similar":1,"avoiding":1}
,"worthwhile":{"run":1,"investigate":1,"perform":1,"benchmark":1}
,"experiments":{"prime":1,"degree":1}
,"prime":{"depth":1}
,"first":{"pass":1,"case":1,"specifies":1,"sizei":1}
,"pass":{"disable":1,"fragments":1,"color":1,"point":1}
,"color":{"writes":1,"images":1,"gradients":1,"normal":1,"texture":1,"buffer":1}
,"serve":{"occluders":1}
,"occluders":{"second":1}
,"second":{"pass":1,"rendering":1,"updates":1}
,"gldepthmask":{"second":1}
,"discard":{"fragments":1,"operation":1}
,"operations":{"prevent":1,"batch":1,"may":1,"significantly":1,"worthwhile":1,"encoded":1,"region":1,"require":1,"gpu":1}
,"prevent":{"hardware":1}
,"enabling":{"automatic":1,"scissor":1}
,"automatic":{"optimization":1}
,"rejects":{"fragments":1}
,"early-z":{"particular":1,"platforms":1,"reject":1}
,"discards":{"fragments":1}
,"criteria":{"disable":1}
,"platforms":{"critical":1,"depth":1}
,"discarding":{"possible":1}
,"alpha":{"testing":1,"relatively":1,"component":1,"blending":1,"may":1}
,"example":{"found":1,"residential":1,"rendered":1}
,"found":{"gl_nv_fragdepth":1,"gpu":1}
,"gl_nv_fragdepth":{"extension":1}
,"opt":{"early-z":1}
,"correct":{"rendering":1}
,"branches":{"conditional":1}
,"conditional":{"may":1,"code":1,"run-time":1}
,"evaluated":{"result":1}
,"false":{"branch":1}
,"branch":{"discarded":1}
,"discarded":{"gpu":1}
,"assuming":{"conditionals":1,"direction":1}
,"skip":{"computations":1}
,"warning":{"particularly":1}
,"particularly":{"relevant":1,"good":1,"important":1}
,"end":{"decreasing":1,"pipeline":1,"end":1,"larger":1}
,"decreasing":{"workload":1}
,"rewritten":{"terms":1}
,"terms":{"algebra":1,"dot-products":1}
,"algebra":{"built-in":1,"instead":1}
,"built-in":{"functions":1,"variable":1,"function":1}
,"dot":{"product":1}
,"product":{"normal":1,"tint":1}
,"negative":{"case":1,"value":1}
,"equation":{"instead":1}
,"ndotl":{"0.0":1}
,"clamp":{"ndotl":1,"may":1}
,"0.0":{"1.0":1}
,"zero-product":{"clamp":1}
,"max":{"min":1}
,"min":{"0.0":1}
,"1.0":{"cases":1}
,"say":{"matter":1}
,"matter":{"reason":1,"depending":1}
,"reason":{"effort":1,"instance":1,"normalize":1,"pot":1,"alternate":1,"nvidia":1}
,"effort":{"avoiding":1,"directed":1}
,"avoiding":{"conditionals":1,"memory":1,"system":1,"fragmentation":1}
,"mipmapped":{"textures":1,"texture":1,"unless":1}
,"return":{"undefined":1}
,"undefined":{"results":1,"reason":1}
,"block":{"statement":1}
,"statement":{"conditional":1}
,"run-time":{"values":1}
,"glsl":{"functions":1,"syntax":1,"shading":1}
,"lod":{"used":1,"expensive":1,"addition":1,"biasing":1}
,"bias":{"specify":1}
,"mipmap":{"lod":1,"levels":1,"chain":1}
,"manually":{"derive":1}
,"derive":{"mipmap":1,"third":1}
,"addition":{"lod":1,"avoiding":1,"restrictions":1}
,"biasing":{"samplers":1}
,"samplers":{"may":1,"need":1}
,"non-lod":{"samplers":1}
,"highp":{"fragment":1,"gradually":1,"texture":1,"depending":1}
,"until":{"explicitly":1,"rendering":1}
,"explicitly":{"precision":1,"deleted":1}
,"qualifiers":{"valuable":1}
,"valuable":{"hints":1}
,"hints":{"compiler":1}
,"register":{"pressure":1}
,"pressure":{"may":1}
,"low":{"precision":1,"experiment":1}
,"twice":{"fast":1,"memory":1,"expensive":1}
,"approached":{"initially":1}
,"gradually":{"reducing":1}
,"lowp":{"until":1,"highp":1,"however":1}
,"artifacts":{"appear":1}
,"appear":{"looks":1,"slightly":1}
,"looks":{"good":1}
,"rule":{"thumb":1}
,"thumb":{"vertex":1,"large":1}
,"position":{"exponential":1}
,"exponential":{"trigonometry":1}
,"trigonometry":{"functions":1}
,"anything":{"lowp":1,"better":1}
,"width":{"height":1,"image":1,"normally":1,"sizei":1}
,"height":{"application-defined":1,"framebuffer":1,"suggests":1,"int":1,"enum":1}
,"application-defined":{"uniform":1}
,"interpolated":{"colors":1,"varying":1}
,"samples":{"usually":1,"texture":1}
,"built-ins":{"higher":1}
,"higher":{"chance":1}
,"optimally":{"may":1}
,"implemented":{"hardware":1,"textures":1}
,"forward":{"primitive":1}
,"compute":{"reflection":1,"lighting":1}
,"reflection":{"vector":1}
,"dot-products":{"algebra":1}
,"gl_frontfacing":{"built-in":1}
,"reflect":{"respectively":1}
,"encoding":{"complex":1}
,"contain":{"arithmetic":1,"multiple":1,"repeated":1,"data":1}
,"arithmetic":{"alu":1,"operators":1,"case":1}
,"hide":{"latency":1,"tends":1}
,"latency":{"fetching":1,"texture":1}
,"fetching":{"samples":1}
,"occur":{"parallel":1,"effort":1,"allocations":1,"free":1}
,"parallel":{"shader":1}
,"primary":{"bottleneck":1}
,"outnumber":{"texture":1}
,"investigate":{"operations":1}
,"encoded":{"textures":1}
,"sub-expressions":{"shaders":1}
,"luts":{"look-up-tables":1,"sometimes":1}
,"look-up-tables":{"luts":1}
,"nearest":{"filtering":1}
,"old":{"trick":1}
,"trick":{"using":1}
,"cubemaps":{"normalize":1}
,"vectors":{"likely":1,"matrices":1,"rotation":1,"done":1,"necessary":1,"required":1,"interpolating":1,"normals":1}
,"loss":{"discrete":1}
,"discrete":{"gpus":1}
,"gpus":{"pursue":1,"case":1,"generally":1}
,"pursue":{"idea":1}
,"idea":{"sure":1}
,"improved":{"worsened":1,"image":1}
,"worsened":{"performance":1}
,"indirect":{"texturing":1}
,"texturing":{"p10":1,"sometimes":1,"degrade":1,"source":1}
,"depends":{"texture":1}
,"difficult":{"hide":1,"know":1,"allocations":1}
,"scattered":{"reads":1}
,"reads":{"minimize":1}
,"reduced":{"avoided":1,"aliasing":1,"fragmentation":1}
,"expense":{"memory":1}
,"trade-off":{"makes":1,"memory":1}
,"sense":{"course":1,"work":1}
,"course":{"analyzed":1}
,"analyzed":{"benchmarked":1}
,"syntax":{"obscure":1,"simplification":1}
,"obscure":{"math":1}
,"shading":{"language":1,"normal":1}
,"language":{"conveniently":1}
,"overloads":{"arithmetic":1}
,"operators":{"vectors":1}
,"matrices":{"care":1}
,"care":{"taken":1}
,"taken":{"miss":1,"consideration":1}
,"miss":{"optimization":1}
,"simplification":{"instance":1}
,"rotation":{"matrix":1,"around":1}
,"homogenous":{"4x4":1}
,"4x4":{"matrix":1}
,"operand":{"vec4":1}
,"vec4":{"vector":1}
,"vec3":{"vectors":1,"directly":1,"may":1}
,"basic":{"vectors":1}
,"mat3":{"vec3":1}
,"accessing":{"relevant":1}
,"cos":{"sin":1}
,"sin":{"advantage":1}
,"scalar":{"instructions":1}
,"normalization":{"vectors":1,"required":1}
,"calculate":{"angle":1}
,"angle":{"perhaps":1,"textured":1}
,"typically":{"diffuse":1}
,"diffuse":{"component":1}
,"component":{"commonly":1,"textures":1,"something":1,"texture":1,"32-bit":1,"define":1}
,"equations":{"theory":1}
,"theory":{"normalization":1}
,"practice":{"may":1,"combining":1}
,"composition":{"matrix":1}
,"least":{"visually":1,"two":1}
,"visually":{"discernible":1,"acceptable":1,"disturbing":1}
,"discernible":{"result":1}
,"slower":{"good":1}
,"interpolating":{"vertex":1,"mipmaps":1}
,"i.e":{"phong":1,"hundreds":1}
,"phong":{"shading":1}
,"rotates":{"little":1}
,"little":{"reason":1,"fragmentation":1}
,"barycentric":{"interpolation":1}
,"interpolation":{"preserve":1}
,"preserve":{"unit":1}
,"dot-product":{"light":1}
,"obeys":{"cosine":1}
,"cosine":{"emission":1}
,"emission":{"law":1}
,"consume":{"largest":1}
,"largest":{"amount":1}
,"best":{"places":1,"return":1,"practices":1}
,"places":{"look":1}
,"improvements":{"short":1}
,"short":{"memory":1}
,"format":{"usage":1,"data":1,"fewer":1,"using":1,"may":1,"type":1,"avoided":1,"enum":1}
,"careless":{"texturing":1}
,"degrade":{"frame":1}
,"inferior":{"image":1}
,"compression":{"whenever":1,"brings":1,"decompressed":1,"ratio":1,"always":1,"cannot":1}
,"brings":{"several":1}
,"compressed":{"textures":1,"separately":1,"s3tc":1}
,"reduces":{"download":1,"frame":1,"number":1}
,"download":{"time":1,"smaller":1}
,"texture_compression_s3tc":{"texture_compression_latc":1}
,"texture_compression_latc":{"extensions":1}
,"block-based":{"lossy":1}
,"lossy":{"texture":1}
,"decompressed":{"efficiently":1}
,"s3tc":{"extension":1,"images":1,"may":1,"channels":1,"algorithm":1}
,"gives":{"8:1":1,"acceptable":1}
,"8:1":{"4:1":1}
,"4:1":{"compression":1}
,"suitable":{"color":1}
,"channels":{"without":1,"latc":1}
,"low-frequency":{"data":1}
,"photographs":{"images":1}
,"compress":{"satisfactory":1,"textures":1}
,"satisfactory":{"jpeg":1,"latc":1}
,"jpeg":{"great":1}
,"great":{"candidates":1}
,"candidates":{"s3tc":1}
,"hard":{"crisp":1,"using":1,"edges":1}
,"crisp":{"edges":1}
,"edges":{"poorer":1,"color":1}
,"poorer":{"candidates":1}
,"blurred":{"noisy":1}
,"noisy":{"latc":1}
,"latc":{"extension":1,"compressed":1,"format":1}
,"yields":{"2:1":1}
,"2:1":{"compression":1}
,"resolution":{"normal":1,"memory":1}
,"maps":{"third":1,"compress":1,"unless":1,"respectively":1}
,"third":{"coordinate":1,"shader":1}
,"afford":{"trade-off":1}
,"separately":{"quantization":1}
,"quantization":{"less":1}
,"lower":{"perceived":1,"performance":1,"frame":1}
,"perceived":{"image":1}
,"experiment":{"increasing":1,"storing":1}
,"off-line":{"tools":1,"using":1}
,"compressing":{"on-the-fly":1}
,"on-the-fly":{"search":1}
,"search":{"nvidia":1}
,"nvidia":{"developer":1,"video":1,"gpus":1,"support":1,"jetson":1}
,"developer":{"website":1}
,"website":{"texture":1}
,"mipmaps":{"appropriate":1,"used":1,"access":1,"off-line":1,"always":1,"generated":1,"automatically":1,"trilinear":1}
,"mapping":{"texels":1,"image":1,"algorithms":1}
,"texels":{"framebuffer":1,"pixels":1,"neighboring":1,"npot":1,"updated":1,"trilinear":1,"however":1,"tiled":1}
,"framebuffer":{"pixels":1,"textured":1,"texture":1,"may":1,"objects":1,"object":1,"completeness":1,"contents":1,"flushes":1,"scan":1}
,"pixels":{"texture":1,"sometimes":1,"may":1,"client":1,"image":1,"framebuffer":1}
,"minification":{"occurs":1,"occurring":1}
,"occurs":{"scene":1,"often":1}
,"utilization":{"poor":1}
,"sparse":{"sampling":1}
,"coloring":{"mipmap":1}
,"levels":{"differently":1,"visually":1,"given":1}
,"differently":{"provide":1,"types":1}
,"visual":{"clue":1,"difference":1}
,"clue":{"amount":1}
,"occurring":{"reducing":1}
,"degree":{"magnification":1,"light":1}
,"magnification":{"visually":1}
,"acceptable":{"improves":1,"image":1}
,"glgeneratemipmap":{"convenient":1,"may":1}
,"convenient":{"option":1}
,"option":{"generating":1}
,"chain":{"function":1}
,"emphasizes":{"execution":1}
,"execution":{"speed":1}
,"speed":{"image":1,"situations":1,"application":1,"framebuffer":1}
,"filter":{"generating":1,"textures":1}
,"filters":{"e.g":1,"enable":1}
,"lanczos":{"sinc":1}
,"sinc":{"often":1}
,"yield":{"improved":1,"best":1,"related":1}
,"extra":{"cost":1,"constraints":1}
,"preferable":{"generating":1}
,"situations":{"want":1}
,"takes":{"storage":1}
,"un-mipmapped":{"provide":1}
,"textured":{"geometry":1,"primitives":1}
,"projected":{"onto":1}
,"onto":{"even":1}
,"existing":{"content":1,"texture":1,"buffer":1}
,"necessarily":{"width":1,"faster":1}
,"magnified":{"produce":1}
,"produce":{"results":1}
,"saved":{"using":1,"quite":1,"clearing":1}
,"appropriately":{"sized":1,"t11":1}
,"sized":{"texture":1}
,"contributes":{"better":1}
,"accelerated":{"texture":1}
,"bits":{"per":1,"la8":1,"color-renderable":1}
,"elements":{"sometimes":1}
,"gradients":{"result":1}
,"quantized":{"assumptions":1}
,"bit":{"texel":1}
,"texel":{"e.g":1,"bilinear":1}
,"unsigned_short_5_6_5":{"although":1}
,"remapped":{"less":1,"vec3":1}
,"accuracy":{"may":1}
,"noticeable":{"final":1,"performance":1}
,"grayscale":{"images":1}
,"luminance":{"tinted":1,"alpha":1}
,"tinted":{"images":1}
,"added":{"cost":1}
,"tint":{"color":1}
,"uncompressed":{"luminance_alpha":1,"textures":1}
,"luminance_alpha":{"derive":1}
,"heightmap":{"terrain":1}
,"24-bit":{"rgb":1}
,"rgb":{"textures":1}
,"32-bit":{"rgba":1}
,"rgba":{"gpus":1,"component":1}
,"something":{"useful":1}
,"8-bit":{"greyscale":1}
,"greyscale":{"texture":1}
,"unused":{"alpha":1}
,"specular":{"reflectance":1}
,"reflectance":{"map":1}
,"describe":{"degree":1}
,"reflected":{"useful":1}
,"terrain":{"satellite":1,"icons":1}
,"satellite":{"imagery":1}
,"imagery":{"land":1}
,"land":{"cover":1}
,"cover":{"textures":1}
,"water":{"snow":1,"terrain":1}
,"snow":{"ice":1}
,"ice":{"areas":1}
,"areas":{"car":1,"instead":1,"free":1}
,"car":{"textures":1}
,"metal":{"glass":1}
,"glass":{"surfaces":1,"windows":1}
,"surfaces":{"textures":1,"glreadpixels":1,"gets":1}
,"buildings":{"glass":1,"factories":1,"rendered":1,"landmarks":1,"water":1}
,"requirement":{"one-to-one":1}
,"distinct":{"images":1,"texture":1}
,"referred":{"texture":1}
,"atlas":{"texture":1,"instead":1,"border":1,"mipmapping":1}
,"page":{"geometry":1}
,"defines":{"texture":1}
,"reference":{"subset":1}
,"atlases":{"useful":1}
,"enables":{"larger":1}
,"residential":{"houses":1}
,"houses":{"office":1}
,"office":{"buildings":1}
,"factories":{"distinct":1}
,"identical":{"share":1}
,"share":{"buffer":1}
,"kinds":{"buildings":1}
,"cubemap":{"texture":1}
,"note":{"mipmapping":1}
,"mipmapping":{"enabled":1,"wrapping":1}
,"sub-textures":{"atlas":1}
,"border":{"wide":1,"enum":1}
,"wide":{"enough":1}
,"generated":{"using":1,"textures":1,"dynamically":1}
,"neighboring":{"images":1}
,"tiling":{"repeat":1,"t12":1,"textures":1,"variation":1}
,"mirrored_repeat":{"needed":1,"consider":1}
,"sub-image":{"may":1}
,"emulating":{"either":1}
,"mode":{"shader":1,"unless":1,"sometimes":1,"int":1,"switches":1}
,"manipulating":{"texture":1}
,"apply":{"per":1}
,"inconvenient":{"sub-images":1}
,"sub-images":{"similar":1}
,"icons":{"images":1,"user":1}
,"candidate":{"array":1}
,"restrictions":{"taken":1,"hardware":1,"above":1,"match":1,"enhance":1}
,"float":{"textures":1}
,"simply":{"used":1}
,"represent":{"larger":1}
,"replace":{"fixed":1}
,"unsigned":{"16-bit":1}
,"16-bit":{"integers":1}
,"integers":{"cannot":1}
,"half-precision":{"floats":1}
,"fp16":{"stored":1}
,"fp32":{"leading":1}
,"requirements":{"better":1,"may":1}
,"la8":{"spend":1}
,"spend":{"alu":1}
,"unpack":{"shader":1}
,"support":{"anything":1,"multiple":1}
,"prefer":{"power-of-two":1}
,"power-of-two":{"pot":1}
,"pot":{"textures":1}
,"non-power-of-two":{"npot":1}
,"npot":{"textures":1,"however":1,"texture":1}
,"clamp_to_edge":{"restriction":1}
,"restriction":{"wrapping":1}
,"relaxed":{"extension":1}
,"importantly":{"cannot":1}
,"significant":{"memory":1,"amount":1}
,"padded":{"internally":1}
,"internally":{"accommodate":1}
,"accommodate":{"alignment":1}
,"alignment":{"restrictions":1,"requirements":1}
,"suggests":{"rule":1}
,"effectively":{"save":1,"graphics":1}
,"save":{"significant":1}
,"update":{"textures":1,"entire":1,"subregion":1}
,"really":{"need":1}
,"reused":{"several":1}
,"environment":{"maps":1,"transformed":1,"variable":1}
,"rotated":{"sufficiently":1}
,"invalidate":{"previous":1}
,"previous":{"map":1}
,"difference":{"may":1,"small":1}
,"shadow":{"mapping":1}
,"gltexsubimage":{"instead":1,"important":1,"repeatedly":1,"call":1}
,"re-defining":{"entire":1}
,"teximage":{"possible":1}
,"otherwise":{"may":1,"necessary":1}
,"conversion":{"texels":1}
,"sub-rectangle":{"pixels":1}
,"client":{"memory":1}
,"driver":{"knowledge":1,"cpu":1}
,"rectangle":{"differs":1}
,"differs":{"texture":1}
,"pixel":{"rows":1,"formats":1,"store":1,"operations":1}
,"rows":{"calling":1}
,"repeatedly":{"updating":1}
,"unpack_subimage":{"extension":1}
,"unpack_row_length":{"pixelstore":1}
,"pixelstore":{"parameter":1}
,"parameter":{"update":1,"reduce":1}
,"region":{"gltexsubimage":1,"enabling":1,"applies":1,"buffer":1}
,"splitting":{"rendering":1,"draw":1}
,"maximum":{"efficiency":1}
,"transparent":{"geometry":1}
,"account":{"draw":1}
,"ordering":{"transparent":1}
,"benchmarks":{"run":1}
,"anisotropic":{"filtering":1}
,"nearest-neighbor":{"filtering":1}
,"fetches":{"texel":1,"four":1,"eight":1}
,"bilinear":{"filtering":1,"even":1,"trilinear":1}
,"trilinear":{"fetches":1,"less":1,"filtering":1}
,"eight":{"texels":1}
,"incorrect":{"draw":1}
,"decision":{"made":1}
,"observing":{"images":1}
,"running":{"application":1}
,"judgment":{"made":1}
,"abrupt":{"changes":1}
,"disturbing":{"enough":1}
,"justify":{"cost":1}
,"intensive":{"bilinear":1}
,"projection":{"plane":1}
,"plane":{"e.g":1,"large":1}
,"near":{"plane":1}
,"nothing":{"gained":1}
,"gained":{"sampling":1}
,"anisotrophically":{"potentially":1}
,"start":{"simplest":1,"exactly":1,"program":1,"reuse":1}
,"simplest":{"possible":1}
,"users":{"inspected":1}
,"inspected":{"output":1}
,"notes":{"along":1}
,"along":{"provide":1}
,"indication":{"relative":1}
,"method":{"concessions":1,"updating":1}
,"concessions":{"made":1}
,"budget":{"exceeded":1}
,"try":{"exploit":1,"group":1}
,"repeated":{"pattern":1,"patterns":1}
,"pattern":{"pixels":1,"without":1}
,"patterns":{"close":1,"crop":1}
,"close":{"enough":1}
,"similarity":{"replaced":1}
,"replaced":{"single":1,"texture":1,"whenever":1}
,"impacting":{"image":1}
,"saves":{"memory":1}
,"identify":{"repeated":1}
,"crop":{"tiled":1}
,"tiled":{"infinitely":1,"texture":1}
,"infinitely":{"without":1}
,"seams":{"using":1}
,"wrap":{"mode":1}
,"quarter":{"tile":1}
,"tile":{"shingle":1}
,"shingle":{"may":1}
,"variation":{"restored":1,"size":1}
,"restored":{"achieved":1}
,"achieved":{"multi-texturing":1}
,"grey-scale":{"texture":1}
,"repeats":{"different":1}
,"frequency":{"modulate":1}
,"modulate":{"texels":1}
,"fbo":{"dynamically":1}
,"copying":{"previously":1,"data":1,"subregion":1}
,"glcopyteximage":{"glcopytexsubimage":1,"functions":1}
,"glcopytexsubimage":{"functions":1}
,"attachment":{"render":1}
,"formats":{"color-renderable":1,"components":1}
,"color-renderable":{"formats":1,"opengl":1}
,"2.0":{"luminance":1}
,"require":{"fallback":1,"read":1,"dynamic":1}
,"fallback":{"glcopyteximage":1}
,"miscellaneous":{"opengl":1}
,"reading":{"back":1,"frequently":1}
,"flushes":{"pipeline":1}
,"limits":{"amount":1,"throughput":1}
,"parallelism":{"reading":1}
,"middle":{"frame":1}
,"stalls":{"gpu":1}
,"picking":{"objects":1}
,"scheduled":{"beginning":1}
,"beginning":{"next":1,"pipeline":1}
,"next":{"frame":1}
,"special":{"case":1,"restrictions":1}
,"pack_subimage":{"extension":1}
,"pack_row_length":{"pixel":1}
,"clearing":{"buffers":1,"common":1}
,"covers":{"entire":1}
,"glclear":{"gl_color_buffer_bit":1,"affect":1}
,"gl_color_buffer_bit":{"necessary":1}
,"constrain":{"pixel":1}
,"scissor":{"testing":1,"box":1}
,"screen":{"testing":1}
,"doubled":{"rendering":1}
,"blended":{"fragments":1}
,"kept":{"minimum":1}
,"minimum":{"drastically":1}
,"drastically":{"speed":1}
,"glteximage":{"functions":1}
,"allocations":{"reusing":1,"sequence":1,"sensitive":1,"occur":1,"smaller":1,"disproportionately":1,"tend":1,"frees":1,"often":1}
,"fragmentation":{"geometry":1,"appendix":1,"generally":1,"graphics":1,"techniques":1,"system":1,"control":1,"applied":1,"means":1,"combining":1,"ability":1,"fixed":1,"wastage":1}
,"pool":{"objects":1}
,"purpose":{"during":1}
,"round-robin":{"fashion":1}
,"fashion":{"optimal":1}
,"alternate":{"objects":1}
,"information":{"memory":1}
,"iterative":{"process":1}
,"process":{"time":1}
,"consuming":{"especially":1}
,"especially":{"without":1,"true":1,"mipmapped":1,"sizes":1}
,"prior":{"experience":1}
,"bottlenecks":{"tend":1,"graphics":1,"different":1,"found":1}
,"directed":{"towards":1}
,"towards":{"critical":1}
,"starting":{"random":1}
,"random":{"place":1}
,"know":{"start":1}
,"exactly":{"optimizations":1}
,"analysis":{"manageable":1}
,"manageable":{"chunks":1}
,"consist":{"hundreds":1,"logically":1,"roads":1}
,"roads":{"buildings":1}
,"landmarks":{"points":1}
,"points":{"interest":1}
,"interest":{"sky":1}
,"sky":{"clouds":1}
,"clouds":{"buildings":1}
,"helpful":{"write":1}
,"allows":{"easy":1,"application":1}
,"easy":{"identification":1}
,"identification":{"expensive":1}
,"become":{"familiar":1}
,"familiar":{"bottlenecks":1}
,"identifying":{"performance":1,"graphics":1}
,"introduced":{"beginning":1}
,"later":{"stages":1}
,"backwards":{"end":1}
,"gems":{"book":1}
,"book":{"chapter":1}
,"chapter":{"graphics":1}
,"cem":{"cebenoyan":1}
,"cebenoyan":{"nvidia":1}
,"bad":{"thing":1}
,"thing":{"especially":1}
,"true":{"computer":1}
,"system":{"memory":1,"chip":1}
,"strive":{"avoid":1}
,"video":{"memory":1}
,"fortunately":{"controlling":1}
,"controlling":{"video":1,"direct":1}
,"control":{"fairly":1}
,"fairly":{"known":1}
,"document":{"treat":1}
,"issues":{"passing":1}
,"passing":{"focuses":1}
,"focuses":{"video":1}
,"heterogenous":{"system":1}
,"following":{"account":1,"list":1}
,"names":{"types":1}
,"vary":{"gpu":1}
,"linear":{"essentially":1,"memory":1}
,"essentially":{"unformatted":1}
,"unformatted":{"gpu":1}
,"tracks":{"different":1}
,"native":{"types":1,"windowing":1}
,"architectures":{"difference":1}
,"10-15":{"others":1}
,"others":{"quite":1}
,"100":{"faster":1}
,"banked":{"especially":1}
,"architecture":{"alternating":1}
,"alternating":{"mipmap":1}
,"put":{"separate":1}
,"banks":{"separation":1,"improve":1}
,"separation":{"mandatory":1}
,"mandatory":{"nvidia":1,"try":1}
,"above":{"different":1}
,"regions":{"different":1}
,"match":{"host":1,"size":1}
,"host":{"pages":1}
,"pages":{"improve":1}
,"dma":{"performance":1}
,"scan":{"alignment":1}
,"orthogonal":{"memory":1}
,"allocator":{"may":1,"allocations":1,"fixed":1}
,"enhance":{"performance":1}
,"distributing":{"allocations":1}
,"sequence":{"different":1}
,"constraints":{"complicate":1}
,"complicate":{"video":1}
,"sensitive":{"reductions":1}
,"reductions":{"available":1}
,"major":{"reason":1}
,"independent":{"heaps":1}
,"heaps":{"video":1}
,"requiring":{"application":1}
,"freeing":{"video":1,"buffers":1,"inner":1,"allocation":1}
,"describes":{"considerations":1}
,"considerations":{"allocating":1}
,"egl":{"small":1,"show":1}
,"apis":{"actually":1,"free":1}
,"long-term":{"video":1}
,"enum":{"target":1,"usage":1,"format":1,"type":1,"internalformat":1,"mode":1}
,"target":{"sizeiptr":1,"int":1,"intptr":1,"texture":1}
,"sizeiptr":{"size":1}
,"const":{"void":1,"eglint":1,"uint":1}
,"void":{"data":1,"pixels":1}
,"glteximage2d":{"enum":1}
,"int":{"level":1,"internalformat":1,"border":1,"int":1,"sizei":1,"xoffset":1,"yoffset":1,"left":1,"bottom":1,"first":1}
,"internalformat":{"sizei":1,"int":1}
,"sizei":{"width":1,"height":1,"uint":1,"const":1,"sizei":1,"count":1}
,"glcopyteximage2d":{"enum":1,"allocates":1,"glcopytexsubimage2d":1}
,"allocates":{"copies":1}
,"copies":{"null":1}
,"eglcreatewindowsurface":{"egldisplay":1}
,"egldisplay":{"dpy":1}
,"dpy":{"eglconfig":1,"eglsurface":1}
,"eglconfig":{"config":1}
,"config":{"nativewindowtype":1,"const":1,"nativepixmaptype":1}
,"nativewindowtype":{"win":1}
,"win":{"const":1}
,"eglint":{"attrib_list":1}
,"eglcreatepbuffersurface":{"egldisplay":1}
,"eglcreatepixmapsurface":{"egldisplay":1}
,"nativepixmaptype":{"pixmap":1}
,"pixmap":{"const":1}
,"allocated":{"video":1,"vbos":1,"buffers":1,"buffer":1,"data":1}
,"vbos":{"surfaces":1,"texture":1,"textures":1,"gldrawarrays":1,"multiple":1}
,"gldeletebuffers":{"sizei":1}
,"uint":{"buffers":1,"textures":1}
,"gldeletetextures":{"sizei":1,"works":1}
,"egldestroysurface":{"egldisplay":1}
,"eglsurface":{"surface":1}
,"works":{"texture":1}
,"greater":{"zero":1}
,"can\u0027t":{"explicitly":1}
,"deleted":{"although":1}
,"containing":{"two":1}
,"dimensions":{"zero":1}
,"accomplishes":{"thing":1}
,"conceptually":{"calls":1}
,"thought":{"malloc":1}
,"malloc":{"free":1}
,"subregion":{"buffer":1,"target":1,"rendering":1,"texture":1,"display":1,"backbuffer":1,"vbo":1,"independently":1}
,"means":{"placing":1,"data":1}
,"placing":{"multiple":1}
,"deleting":{"overwriting":1}
,"overwriting":{"older":1}
,"older":{"object":1}
,"newer":{"opengl":1}
,"provides":{"method":1}
,"arbitrary":{"section":1,"subregion":1}
,"glbuffersubdata":{"enum":1}
,"intptr":{"offset":1}
,"gltexsubimage2d":{"enum":1,"glcopytexsubimage2d":1}
,"xoffset":{"int":1}
,"yoffset":{"sizei":1,"int":1}
,"glcopytexsubimage2d":{"enum":1,"update":1,"restrict":1}
,"glscissor":{"int":1,"glviewport":1}
,"bottom":{"sizei":1}
,"specifies":{"region":1}
,"affect":{"second":1}
,"transforms":{"limit":1}
,"specified":{"subregion":1,"order":1}
,"completing":{"functionality":1}
,"functionality":{"needed":1}
,"reuse":{"allocated":1,"rather":1,"particularly":1,"during":1,"buffers":1,"however":1}
,"ability":{"arbitrary":1,"load":1,"render":1,"reload":1,"reuse":1}
,"vbo":{"surface":1,"texture":1,"often":1}
,"glreadpixels":{"int":1,"used":1}
,"contiguous":{"subset":1}
,"there\u0027s":{"explicit":1}
,"explicit":{"call":1}
,"modes":{"specified":1}
,"display":{"copying":1,"surface":1,"window":1}
,"application-allocated":{"buffer":1}
,"restrict":{"themselves":1}
,"themselves":{"copying":1}
,"transferring":{"data":1}
,"area":{"that\u0027s":1}
,"that\u0027s":{"problematic":1}
,"problematic":{"controlling":1}
,"direct":{"display":1}
,"window":{"surface":1}
,"show":{"subregion":1}
,"backbuffer":{"surface":1}
,"windowing":{"systems":1}
,"systems":{"may":1}
,"practices":{"video":1,"allocating":1}
,"list":{"good":1}
,"ideally":{"allocate":1,"single":1,"allocation":1}
,"average":{"allocating":1}
,"space":{"broken":1,"allocator":1,"smaller":1,"causes":1,"allocated":1}
,"combine":{"small":1,"vbos":1}
,"disproportionately":{"reduce":1}
,"regardless":{"size":1}
,"break":{"large":1}
,"independently":{"makes":1}
,"hold":{"grid":1}
,"grid":{"smaller":1}
,"besides":{"reducing":1}
,"glbindbuffer":{"glbindtexture":1}
,"glbindtexture":{"calls":1}
,"aren\u0027t":{"small":1}
,"multiples":{"disruptive":1}
,"disruptive":{"memory":1}
,"causes":{"fragmentation":1}
,"doesn\u0027t":{"match":1}
,"long":{"it\u0027s":1}
,"it\u0027s":{"smaller":1,"safe":1,"small":1,"better":1}
,"waste":{"space":1,"often":1}
,"isn\u0027t":{"used":1}
,"saving":{"reduced":1}
,"total":{"wastage":1}
,"wastage":{"generally":1,"it\u0027s":1,"excessive":1}
,"safe":{"ignore":1}
,"ignore":{"wastage":1}
,"percentage":{"allocated":1}
,"blocks":{"often":1}
,"freed":{"reallocated":1}
,"reallocated":{"little":1}
,"excessive":{"buffer":1}
,"chosen":{"often":1}
,"consecutive":{"power":1}
,"reallocate":{"buffers":1}
,"reload":{"previously":1}
,"practical":{"reuse":1,"even":1}
,"switches":{"even":1}
,"handle":{"possible":1}
,"inner":{"loop":1}
,"organize":{"code":1}
,"frees":{"move":1,"together":1,"replaced":1}
,"ones":{"main":1}
,"path":{"possible":1}
,"followed":{"freeing":1}
,"happens":{"rarely":1}
,"nearly":{"effective":1}
,"again":{"allocations":1}
,"cpus":{"reduce":1}
,"export":{"__gl_yield":1}
,"__gl_yield":{"usleep":1}
,"jetson":{"system":1}
,"chip":{"soc":1}
,"soc":{"includes":1}
,"includes":{"extremely":1}
,"extremely":{"powerful":1}
,"powerful":{"flexible":1}
,"flexible":{"gpu":1}
,"whose":{"power":1}
,"matched":{"opengl":1}
}
;Search.control.loadWordPairs(pairs);
