var pairs =
{
"debugging":{"kernel":1,"linux":1,"e.g":1,"disconnect":1}
,"kernel":{"jetson":1,"source-level":1,"nvidia":1,"operations":1,"enabled":1,"connect":1,"configuration":1,"currently":1,"compiled":1,"config_ikconfig_proc":1,"kgdb":1,"directory":1,"kernel-4.9":1,"using":1,"target":1,"command":1,"boot":1,"waits":1,"displays":1,"waiting":1,"vmlinux":1}
,"jetson":{"devices":1,"tx2":1,"processor":1,"device":1}
,"applies":{"jetson":1}
,"tx2":{"series":1}
,"series":{"devices":1}
,"topic":{"describes":1}
,"describes":{"linux":1}
,"linux":{"kernel":1,"build":1}
,"source-level":{"debugger":1,"debugging":1}
,"debugger":{"kgdb":1,"started":1}
,"kgdb":{"debugging":1,"available":1,"index.html":1,"requires":1,"trace":1,"gdb":1,"compilingakernel.html":1,"attach":1,"attached":1,"wait":1,"specify":1,"boot":1,"during":1,"registered":1,"waiting":1,"i.e":1,"console":1,"break":1,"entering":1,"define":1}
,"nvidia":{"jetson":1,"recommends":1,"kernel":1}
,"detailed":{"information":1}
,"information":{"kgdb":1}
,"https":{"www.kernel.org":1}
,"www.kernel.org":{"doc":1}
,"doc":{"htmldocs":1}
,"htmldocs":{"kgdb":1}
,"using":{"kgdb":1,"gdb":1,"new":1,"two":1,"serial":1}
,"requires":{"host":1}
,"host":{"system":1,"target":1,"serial":1,"output":1,"identify":1,"execute":1}
,"system":{"serial":1,"calls":1,"request":1,"started":1}
,"serial":{"connection":1,"port":1,"device":1,"data":1,"line":1,"console":1}
,"connection":{"target":1,"host":1,"e.g":1,"work":1,"including":1,"usb":1,"tunnel":1,"remote":1,"kgdb":1,"running":1}
,"target":{"device":1,"jetson":1,"remote":1,"system":1,"enter":1}
,"device":{"debugged":1,"jetson":1,"used":1,"bpc":1,"baudrate":1,"serial":1,"debugging":1,"e.g":1,"type":1,"kgdboc":1,"port":1,"configured":1,"number":1,"ttys0":1}
,"debugged":{"allows":1}
,"allows":{"live":1}
,"live":{"source-level":1}
,"operations":{"setting":1}
,"setting":{"breakpoints":1}
,"breakpoints":{"tracing":1}
,"tracing":{"errors":1}
,"errors":{"back":1}
,"back":{"function":1}
,"function":{"calls":1}
,"cannot":{"kgdb":1}
,"trace":{"system":1}
,"calls":{"types":1}
,"types":{"processes":1}
,"processes":{"tracer":1}
,"tracer":{"type":1}
,"type":{"debugging":1,"connection":1}
,"reconfiguring":{"rebuilding":1}
,"rebuilding":{"kernel":1,"linux":1}
,"kdgb":{"determine":1,"feature":1,"config_frame_pointer":1,"boot":1,"runtime":1,"target":1}
,"determine":{"whether":1,"host":1}
,"whether":{"kdgb":1,"kernel":1,"console":1}
,"feature":{"enabled":1}
,"enabled":{"kernel":1,"reconfigure":1,"command":1,"defconfig":1}
,"reconfigure":{"rebuild":1}
,"rebuild":{"kernel":1}
,"connect":{"gdb":1,"kgdb":1,"standard":1}
,"gdb":{"serial":1,"8.0":1,"7.0":1,"kgdb":1,"connection":1,"target":1,"usual":1,"enter":1,"debugger":1,"host":1}
,"port":{"terminal":1,"usb":1,"receives":1,"dev":1,"replace":1,"number":1,"receive":1,"receiving":1,"gdb":1}
,"terminal":{"debugging":1,"device":1,"window":1,"application":1,"connected":1}
,"debug":{"device":1,"console":1}
,"processor":{"nvidia":1,"due":1}
,"recommends":{"using":1}
,"8.0":{"connect":1}
,"7.0":{"used":1}
,"used":{"past":1,"debugging":1}
,"past":{"tested":1}
,"tested":{"current":1}
,"current":{"release":1,"0xffffffc1ecb30000":1,"0xffffffc1e9259c00":1}
,"configuration":{"modified":1,"file":1}
,"execute":{"command":1,"commands":1}
,"zcat":{"proc":1}
,"proc":{"config.gz":1,"sysrq-trigger":1}
,"config.gz":{"egrep":1,"exist":1}
,"egrep":{"\u0027config_kgdb":1}
,"\u0027config_kgdb":{"kdgb":1}
,"config_frame_pointer":{"config_watchdog":1}
,"config_watchdog":{"ikconfig":1}
,"currently":{"requisite":1}
,"requisite":{"macros":1}
,"macros":{"enabled":1,"correctly":1}
,"command":{"displays":1,"line":1,"gdb":1}
,"displays":{"exactly":1,"messages":1}
,"exactly":{"following":1}
,"following":{"output":1,"arguments":1}
,"config_kdb_default_enable":{"0x1":1}
,"output":{"indicates":1,"device":1}
,"indicates":{"proc":1}
,"exist":{"kernel":1}
,"compiled":{"config_ikconfig_proc":1}
,"config_ikconfig_proc":{"case":1}
,"case":{"recompile":1}
,"recompile":{"kernel":1}
,"general":{"instructions":1}
,"instructions":{"reconfiguring":1}
,"modifying":{"kernel":1}
,"may":{"modify":1}
,"modify":{"kernel":1}
,"file":{"above-mentioned":1,"target":1,"t186":1,"executing":1}
,"above-mentioned":{"macros":1}
,"select":{"appropriate":1}
,"appropriate":{"configuration":1}
,"example":{"configuration":1,"console":1,"minicom":1,"terminal":1}
,"t186":{"board":1}
,"board":{"tegra_defconfig":1}
,"build":{"environment":1}
,"environment":{"execute":1}
,"commands":{"within":1,"prompt":1,"host":1}
,"within":{"kernel":1}
,"$tegra_top":{"kernel":1,"l4t-t186ref-debug-aarch64":1}
,"export":{"arch":1}
,"arch":{"arm64":1}
,"defconfig_path":{"arch":1}
,"arm64":{"configs":1}
,"configs":{"tegra_defconfig":1}
,"update":{"config":1}
,"config":{"options":1}
,"defconfig":{"arch":1,"kernel":1,"command":1}
,"new":{"configuration":1,"kernel":1}
,"executing":{"command":1,"commands":1}
,"tmp":{"kernel":1}
,"flash":{"new":1}
,"attach":{"gdb":1}
,"attached":{"using":1}
,"two":{"methods":1,"ways":1}
,"methods":{"depending":1}
,"depending":{"state":1}
,"state":{"system":1}
,"boot":{"kernel":1,"command":1,"messages":1,"opens":1}
,"runtime":{"sysfs":1}
,"sysfs":{"node":1}
,"node":{"system":1}
,"request":{"trigger":1}
,"trigger":{"kgdb":1}
,"wait":{"gdb":1}
,"starting":{"kdgb":1}
,"custom":{"kernel":1}
,"line":{"kgdb":1,"correctly":1,"console":1}
,"baud":{"rate":1}
,"rate":{"serial":1,"parity":1,"host":1}
,"kgdbwait":{"command":1}
,"start":{"kgdb":1,"gdb":1,"kdgb":1}
,"check":{"whether":1}
,"console":{"parameter":1,"device":1,"parameters":1,"ttys0,115200n8":1,"displays":1,"ttys0":1,"entering":1,"debugging":1,"example":1,"configured":1,"minicom":1}
,"parameter":{"using":1,"add":1,"direct":1}
,"add":{"following":1}
,"arguments":{"kernel":1}
,"bpc":{"kgdboc":1,"specifies":1}
,"kgdboc":{"device":1,"ttys0,115200":1,"parameter":1,"parameters":1}
,"baudrate":{"kgdbwait":1,"baud":1}
,"e.g":{"ttys0":1,"115200n8":1,"115200":1}
,"specifies":{"baud":1}
,"parity":{"character":1}
,"character":{"length":1}
,"length":{"serial":1}
,"specific":{"example":1}
,"ttys0,115200n8":{"kgdboc":1}
,"ttys0,115200":{"kgdbwait":1,"sys":1}
,"verify":{"baud":1}
,"work":{"rs-232":1}
,"rs-232":{"serial":1}
,"including":{"connection":1}
,"usb":{"bridge":1,"port":1,"device":1}
,"bridge":{"cable":1}
,"cable":{"network":1}
,"network":{"connection":1}
,"tunnel":{"serial":1}
,"receives":{"boot":1}
,"messages":{"device":1,"waits":1,"port":1}
,"direct":{"gdb":1}
,"once":{"kernel":1}
,"correctly":{"two":1}
,"ways":{"connect":1}
,"config_kdb":{"macros":1}
,"waits":{"kgdb":1,"connection":1}
,"during":{"boot":1}
,"opens":{"terminal":1}
,"window":{"showing":1}
,"showing":{"kdb":1}
,"kdb":{"console":1,"current":1,"commands":1,"help":1}
,"3.600430":{"console":1}
,"ttys0":{"enabled":1,"typically":1,"host":1}
,"3.604746":{"kgdb":1}
,"registered":{"driver":1}
,"driver":{"kgdboc":1}
,"3.626509":{"kgdb":1}
,"waiting":{"connection":1}
,"remote":{"gdb":1,"dev":1}
,"entering":{"kdb":1,"standard":1,"kgdb":1}
,"0xffffffc1ecb30000":{"pid":1}
,"pid":{"processor":1,"4362":1}
,"due":{"keyboard":1}
,"keyboard":{"entry":1}
,"ends":{"procedure":1}
,"procedure":{"debug":1}
,"standard":{"kdb":1,"serial":1}
,"2.368148":{"console":1}
,"2.375339":{"bootconsole":1}
,"bootconsole":{"uart0":1}
,"uart0":{"disabled":1}
,"2.383940":{"kgdb":1}
,"2.402324":{"kgdb":1}
,"next":{"step":1}
,"perform":{"remaining":1}
,"remaining":{"steps":1}
,"steps":{"kernel":1}
,"i.e":{"config_kdb":1}
,"disconnect":{"terminal":1}
,"application":{"console":1}
,"minicom":{"point":1,"screen":1}
,"usual":{"executing":1}
,"path_to_toolchain":{"linaro":1}
,"linaro":{"gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu":1}
,"gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu":{"bin":1}
,"bin":{"aarch64-linux-gnu-gdb":1}
,"aarch64-linux-gnu-gdb":{"$tegra_top":1}
,"l4t-t186ref-debug-aarch64":{"nvidia":1}
,"dev":{"ttyusb2":1,"tty_device":1,"ttys0":1}
,"enter":{"command":1}
,"tty_device":{"host":1}
,"configured":{"gdb":1,"terminal":1,"baud":1}
,"connected":{"usb":1,"serial":1}
,"replace":{"usb":1}
,"number":{"serial":1,"dev":1}
,"typically":{"port":1}
,"receive":{"boot":1}
,"started":{"described":1}
,"described":{"section":1}
,"running":{"system":1}
,"open":{"terminal":1}
,"enable":{"kgdb":1}
,"echo":{"ttys0,115200":1,"proc":1,"remotebaud":1,"target":1}
,"sys":{"module":1}
,"module":{"kgdboc":1}
,"parameters":{"kgdboc":1}
,"sets":{"target":1}
,"identify":{"serial":1}
,"receiving":{"boot":1}
,"already":{"connected":1}
,"screen":{"kernel":1}
,"60.206779":{"kgdb":1}
,"signal":{"kgdb":1}
,"break":{"kgdb":1}
,"54.299912":{"sysrq":1}
,"sysrq":{"sysrq":1,"debug":1}
,"0xffffffc1e9259c00":{"pid":1}
,"4362":{"processor":1}
,"68.398684":{"sysrq":1}
,"68.402103":{"kgdb":1}
,"sudo":{"gdb_name":1}
,"gdb_name":{"$tegra_top":1}
,"remotebaud":{"115200":1}
,"save":{"typing":1}
,"typing":{"time":1}
,"time":{"connect":1}
,"define":{"dbgattach":1}
,"dbgattach":{"alias":1}
,"alias":{".gdbinit":1}
,".gdbinit":{"file":1}
}
;Search.control.loadWordPairs(pairs);
