var pairs =
{
"camera":{"software":1,"solution":1,"support":1,"architecture":1,"core":1,"gstreamer":1,"partners":1,"api":1,"apis":1,"configuration":1,"contain":1,"records":1,"features":1,"output":1,"format":1,"work":1,"module":1,"modules":1,"cases":1,"sensor":1,"driver":1,"frames":1,"server":1}
,"software":{"development":1,"solution":1,"architecture":1,"releases":1,"stack":1,"converter":1}
,"development":{"solution":1,"options":1,"customization":1,"complete":1}
,"applies":{"jetson":1}
,"jetson":{"agx":1,"platform":1,"board":1,"embedded":1,"isp":1,"download":1,"developer":1,"multimedia":1,"linux":1}
,"agx":{"xavier":1}
,"xavier":{"series":1}
,"document":{"describes":1}
,"describes":{"nvidia":1}
,"nvidia":{"jetson":1,"supported":1,"camera":1,"components":1,"provides":1,"tunes":1,"drivers":1,"certified":1,"write":1,"embedded":1,"multimedia":1,"sdk":1}
,"series":{"camera":1}
,"solution":{"explains":1,"usb":1,"preferred":1}
,"explains":{"nvidia":1}
,"supported":{"recommended":1,"camera":1,"using":1}
,"recommended":{"camera":1}
,"architecture":{"fast":1,"stack":1,"includes":1}
,"fast":{"optimal":1}
,"optimal":{"time":1}
,"time":{"market":1}
,"market":{"development":1}
,"options":{"outlined":1,"control":1}
,"outlined":{"explained":1}
,"explained":{"customize":1}
,"customize":{"camera":1}
,"usb":{"yuv":1,"uvc":1,"interface":1,"camera":1}
,"yuv":{"bayer":1,"sensor":1,"images":1}
,"bayer":{"camera":1,"sensor":1,"data":1,"sensors":1}
,"includes":{"nvidia":1,"following":1,"initial":1}
,"components":{"allow":1,"using":1}
,"allow":{"ease":1}
,"ease":{"development":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"generated":1}
,"generated":{"high":1}
,"high":{"confidence":1}
,"following":{"nvidia":1}
,"libargus":{"provides":1,"preferred":1,"low-level":1,"apis":1,"jetpack":1}
,"provides":{"low-level":1,"options":1,"ov5693":1,"additional":1,"samples":1}
,"low-level":{"api":1,"apis":1}
,"api":{"based":1,"matrix":1,"reference":1,"provides":1,"installed":1}
,"based":{"camera":1,"media":1,"software":1,"hardware":1}
,"core":{"stack":1,"release":1}
,"nvarguscamerasrc":{"nvidia":1,"plugin":1,"gstreamer":1,"num-buffers":1,"video":1}
,"gstreamer":{"plugin":1,"multimedia":1,"nvarguscamerasrc":1,"v4l2":1,"jetson":1}
,"plugin":{"provides":1,"supported":1}
,"control":{"isp":1}
,"isp":{"properties":1,"csi":1,"v4l2":1,"post-processing":1,"support":1,"configuration":1,"usb":1,"bypass":1}
,"properties":{"using":1}
,"using":{"argus":1,"libargus":1,"gstreamer":1,"yuv":1,"v4l2":1,"third":1}
,"argus":{"api":1,"libargus":1}
,"v4l2src":{"standard":1,"num-buffers":1,"device":1}
,"standard":{"linux":1}
,"linux":{"v4l2":1,"multimedia":1}
,"v4l2":{"application":1,"functionality":1,"api":1,"driver":1,"source":1,"ioctl":1,"gstreamer":1}
,"application":{"uses":1,"validate":1}
,"uses":{"direct":1,"jetson":1}
,"direct":{"kernel":1}
,"kernel":{"ioctl":1,"nvidia":1}
,"ioctl":{"calls":1,"directly":1,"verify":1}
,"calls":{"access":1}
,"access":{"v4l2":1,"camera":1}
,"ov5693":{"bayer":1,"camera":1,"raw":1}
,"sensor":{"sample":1,"nvidia":1,"support":1,"tuning":1,"driver":1,"characterization":1,"stream":1,"usb":1,"format":1,"bringup":1,"streams":1,"triggered":1,"camera":1,"hardware":1}
,"sample":{"nvidia":1}
,"tunes":{"sensor":1}
,"platform":{"drive":1,"jep":1}
,"drive":{"code":1}
,"code":{"based":1}
,"media":{"controller":1,"i2c":1}
,"controller":{"framework":1}
,"framework":{"available":1}
,"drivers":{"media":1,"provided":1,"customer":1}
,"i2c":{"ov5693.c":1}
,"additional":{"sensor":1,"isp":1}
,"support":{"jetson":1,"package":1,"work":1,"peripheral":1,"available":1,"camera":1,"case":1,"suspending":1}
,"board":{"support":1}
,"package":{"bsp":1,"release":1,"sdk":1,"includes":1}
,"bsp":{"software":1}
,"releases":{"developers":1,"libraries":1}
,"developers":{"work":1}
,"work":{"nvidia":1,"involved":1,"isp":1}
,"certified":{"camera":1}
,"partners":{"bayer":1,"community":1}
,"tuning":{"support":1}
,"involved":{"includes":1}
,"driver":{"development":1,"interface":1,"associated":1,"resume":1,"hardware":1,"know":1}
,"custom":{"tools":1,"camera":1}
,"tools":{"sensor":1,"operating":1,"application":1}
,"image":{"quality":1}
,"quality":{"tuning":1}
,"operating":{"mechanisms":1,"remote":1}
,"mechanisms":{"part":1}
,"part":{"public":1}
,"public":{"jetson":1}
,"embedded":{"platform":1,"download":1,"downloads":1}
,"jep":{"board":1}
,"matrix":{"camera":1}
,"apis":{"available":1,"preview":1}
,"available":{"camera":1,"nvidia":1,"download":1,"jetson":1}
,"configuration":{"follows":1,"files":1}
,"csi":{"interface":1,"cameras":1,"sensor":1}
,"provided":{"nvidia":1,"tools":1,"isp":1}
,"write":{"drivers":1}
,"customer":{"support":1}
,"peripheral":{"bus":1}
,"bus":{"device":1}
,"device":{"ethernet":1,"dev":1}
,"ethernet":{"non-uvc":1}
,"non-uvc":{"usb":1}
,"preferred":{"path":1,"partners":1}
,"path":{"access":1}
,"default":{"ov5693":1}
,"contain":{"integrated":1}
,"integrated":{"isp":1}
,"reference":{"camera":1,"may":1,"sensors":1}
,"records":{"raw":1}
,"raw":{"bayer":1,"camera":1}
,"approaches":{"validating":1}
,"validating":{"testing":1}
,"testing":{"v4l2":1}
,"once":{"driver":1}
,"complete":{"provided":1}
,"validate":{"test":1}
,"test":{"v4l2":1}
,"general":{"gstreamer":1}
,"multimedia":{"operations":1,"user":1,"api":1,"20api":1,"components":1}
,"operations":{"multimedia":1}
,"user":{"guide":1}
,"guide":{"available":1}
,"download":{"center":1,"jetson":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"applications":{"using":1}
,"samples":{"demonstrate":1}
,"demonstrate":{"libargus":1}
,"preview":{"capture":1,"file":1,"hdmi":1,"screen":1}
,"capture":{"record":1,"bayer":1,"frames":1}
,"record":{"sensor":1}
,"installed":{"nvidia":1}
,"sdk":{"manager":1}
,"manager":{"standalone":1,"available":1}
,"standalone":{"package":1}
,"may":{"downloaded":1,"create":1}
,"downloaded":{"jetson":1}
,"downloads":{"search":1}
,"search":{"multimedia":1}
,"features":{"argus":1}
,"enable":{"isp":1,"feature":1}
,"post-processing":{"bayer":1,"nvidia":1}
,"perform":{"format":1}
,"format":{"conversion":1,"1080p":1,"nv12":1,"string":1,"480p":1,"yuy2":1}
,"generate":{"output":1,"specified":1}
,"output":{"directly":1,"yuv":1}
,"directly":{"yuv":1}
,"example":{"bayer":1,"usb":1,"capture":1}
,"1080p":{"bggr":1,"rg10":1}
,"save":{"preview":1}
,"file":{"follows":1}
,"gst-launch-1.0":{"nvarguscamerasrc":1,"v4l2src":1}
,"num-buffers":{"200":1}
,"200":{"\u0027video":1,"device":1}
,"\u0027video":{"x-raw":1}
,"x-raw":{"memory:nvmm":1,"format":1}
,"memory:nvmm":{"width":1,"format":1}
,"width":{"1920":1,"640":1,"int":1}
,"1920":{"height":1}
,"height":{"1080":1,"480":1,"int":1}
,"1080":{"framerate":1,"format":1,"pixelformat":1}
,"framerate":{"format":1,"fraction":1,"videoconvert":1,"xvimagesink":1}
,"nv12":{"omxh264enc":1,"framerate":1}
,"omxh264enc":{"qtmux":1}
,"qtmux":{"filesink":1}
,"filesink":{"location":1}
,"location":{"test.mp4":1}
,"render":{"preview":1}
,"hdmi":{"screen":1}
,"screen":{"follows":1}
,"video":{"x-raw":1}
,"string":{"nv12":1,"uyvy":1}
,"fraction":{"nvoverlaysink":1,"nvvidconv":1,"xvimagesink":1}
,"source":{"plugin":1}
,"images":{"without":1}
,"without":{"isp":1,"timeout":1}
,"480p":{"yuy2":1,"uyvy":1}
,"follows":{"based":1}
,"dev":{"video0":1}
,"video0":{"\u0027video":1,"--stream-to":1}
,"yuy2":{"width":1}
,"640":{"height":1}
,"480":{"framerate":1}
,"videoconvert":{"omxh264enc":1}
,"test.mp4":{"-ev":1}
,"export":{"display":1}
,"display":{"operating":1}
,"remote":{"console":1}
,"xvimagesink":{"-ev":1}
,"hardware":{"accelerated":1,"waiting":1,"always":1,"module":1}
,"accelerated":{"converter":1}
,"uyvy":{"width":1}
,"int":{"640":1,"480":1}
,"nvvidconv":{"\u0027video":1}
,"verify":{"basic":1}
,"basic":{"functionality":1}
,"functionality":{"during":1}
,"during":{"sensor":1}
,"v4l2-ctl":{"--set-fmt-video":1}
,"--set-fmt-video":{"width":1}
,"pixelformat":{"rg10":1}
,"rg10":{"--stream-mmap":1}
,"--stream-mmap":{"--stream-count":1}
,"--stream-count":{"dev":1}
,"--stream-to":{"ov5693.raw":1}
,"built-in":{"camera":1}
,"release":{"package":1,"eglstreams":1,"symlink":1}
,"initial":{"isp":1}
,"files":{"reference":1}
,"cameras":{"integrated":1}
,"bypass":{"mode":1}
,"mode":{"provided":1}
,"developer":{"kit":1}
,"kit":{"ov5693":1}
,"modules":{"supported":1}
,"third":{"party":1}
,"party":{"partners":1}
,"infinite":{"timeout":1}
,"timeout":{"support":1,"issues":1}
,"case":{"different":1,"camera":1}
,"different":{"typical":1}
,"typical":{"camera":1}
,"cases":{"camera":1}
,"streams":{"frames":1}
,"frames":{"continuously":1,"stops":1,"coming":1}
,"continuously":{"finite":1}
,"finite":{"timeouts":1}
,"timeouts":{"camera":1}
,"associated":{"hardware":1}
,"waiting":{"camera":1}
,"triggered":{"generate":1}
,"specified":{"number":1}
,"number":{"frames":1}
,"stops":{"streaming":1}
,"streaming":{"indefinitely":1,"camera":1,"start":1}
,"indefinitely":{"whenever":1,"incoming":1}
,"whenever":{"resumes":1}
,"resumes":{"streaming":1}
,"resume":{"capturing":1}
,"capturing":{"without":1}
,"issues":{"camera":1}
,"always":{"ready":1}
,"ready":{"capture":1}
,"coming":{"csi":1}
,"know":{"streaming":1}
,"start":{"again":1}
,"again":{"wait":1}
,"wait":{"indefinitely":1}
,"incoming":{"frames":1}
,"module":{"support":1}
,"suspending":{"resuming":1}
,"resuming":{"streaming":1}
,"feature":{"run":1}
,"run":{"camera":1}
,"server":{"i.e":1}
,"i.e":{"nvargus-daemon":1}
,"nvargus-daemon":{"service":1,"stop":1}
,"service":{"setting":1,"nvargus-daemon":1}
,"setting":{"environment":1}
,"environment":{"variable":1}
,"sudo":{"service":1,"enablecaminfinitetimeout":1}
,"enablecaminfinitetimeout":{"nvargus-daemon":1}
,"symlinks":{"changed":1}
,"changed":{"mesa":1}
,"mesa":{"installation":1,"egl":1}
,"installation":{"mesa":1}
,"egl":{"may":1,"including":1}
,"create":{"usr":1}
,"usr":{"lib":1}
,"lib":{"abi_directory":1}
,"abi_directory":{"libegl.so":1,"tegra-egl":1}
,"libegl.so":{"symlink":1,"disrupts":1}
,"symlink":{"overwriting":1,"implementation":1,"replaced":1}
,"overwriting":{"symlink":1}
,"implementation":{"library":1}
,"library":{"used":1}
,"used":{"instead":1}
,"instead":{"usr":1}
,"tegra-egl":{"libegl.so":1}
,"disrupts":{"client":1}
,"client":{"egl":1}
,"including":{"libraries":1}
,"libraries":{"release":1,"libgl":1}
,"replaced":{"system":1}
,"system":{"rebooted":1}
,"rebooted":{"fixing":1}
,"fixing":{"issue":1}
,"issue":{"reboot":1}
,"reboot":{"similar":1}
,"similar":{"workarounds":1}
,"workarounds":{"applied":1}
,"applied":{"previous":1}
,"previous":{"releases":1}
,"libgl":{"libglx":1}
,"details":{"integrating":1,"argus":1,"building":1}
,"integrating":{"jetson":1}
,"jetpack":{"documentation":1}
,"building":{"custom":1}
}
;Search.control.loadWordPairs(pairs);
