var pairs =
{
"related":{"documentation":1,"nvidia":1}
,"documents":{"related":1,"whose":1,"jetson":1,"may":1}
,"nvidia":{"jetson":1,"developer":1,"xavier":1}
,"jetson":{"linux":1,"download":1,"developer":1,"xavier":1,"nano":1,"developers":1,"tx2":1,"agx":1,"getting":1,"devices":1,"module":1,"tx1":1,"product":1,"fuse":1,"virtual":1,"faq":1,"modules":1,"sensor":1}
,"linux":{"driver":1}
,"driver":{"package":1}
,"package":{"l4t":1,"api":1}
,"l4t":{"available":1,"home":1}
,"download":{"center":1,"documents":1,"document":1}
,"home":{"page":1}
,"page":{"nvidia":1,"invites":1,"links":1}
,"developer":{"web":1,"kit":1,"program":1,"kits":1,"guide":1}
,"web":{"site":1,"page":1}
,"search":{"jetson":1}
,"center":{"documents":1,"try":1}
,"whose":{"titles":1}
,"titles":{"contain":1}
,"contain":{"specified":1}
,"specified":{"word":1}
,"word":{"sequence":1}
,"sequence":{"words":1}
,"words":{"example":1}
,"example":{"find":1}
,"find":{"jetson":1}
,"kit":{"documents":1,"user":1,"carrier":1}
,"xavier":{"developer":1,"series":1,"system-on-module":1,"product":1,"oem":1,"fuse":1}
,"user":{"guide":1,"guides":1}
,"guide":{"jetson":1,"accessible":1}
,"nano":{"developer":1,"2gb":1,"module":1,"product":1}
,"carrier":{"board":1}
,"board":{"specification":1}
,"specification":{"searching":1,"application":1,"app":1}
,"searching":{"developer":1}
,"member":{"nvidia":1}
,"program":{"download":1}
,"try":{"download":1}
,"document":{"may":1,"number":1}
,"may":{"shown":1,"particular":1}
,"shown":{"log-in":1}
,"log-in":{"page":1}
,"invites":{"join":1}
,"published":{"documents":1}
,"following":{"documents":1}
,"particular":{"interest":1}
,"interest":{"jetson":1}
,"title":{"link":1}
,"last":{"published":1}
,"getting":{"started":1}
,"started":{"jetson":1,"nvidia":1}
,"2gb":{"developer":1}
,"tx2":{"developer":1,"series":1,"fuse":1}
,"accessible":{"general":1}
,"general":{"link":1}
,"link":{"above":1}
,"agx":{"xavier":1}
,"links":{"introduction":1}
,"introduction":{"artificial":1}
,"artificial":{"intelligence":1}
,"intelligence":{"documentation":1}
,"documentation":{"several":1,"archives":1}
,"several":{"jetson":1}
,"devices":{"developer":1}
,"technical":{"reference":1}
,"reference":{"manuals":1,"manual":1}
,"manuals":{"trms":1}
,"series":{"system-on-chip":1,"soc":1,"module":1,"oem":1,"fuse":1}
,"system-on-chip":{"technical":1}
,"tegra":{"series":1,"soc":1}
,"soc":{"technical":1}
,"module":{"data":1}
,"data":{"sheets":1,"sheet":1}
,"system-on-module":{"data":1}
,"tx1":{"module":1,"oem":1,"fuse":1}
,"product":{"design":1}
,"design":{"guides":1,"guide":1}
,"oem":{"product":1}
,"fuse":{"specifications":1,"specification":1}
,"application":{"note":1}
,"app":{"note":1}
,"virtual":{"channel":1}
,"channel":{"gmsl":1}
,"gmsl":{"framework":1}
,"framework":{"guide":1}
,"api":{"reference":1,"guide":1}
,"faq":{"part":1}
,"part":{"numbers":1}
,"numbers":{"formal":1}
,"formal":{"names":1}
,"names":{"jetson":1}
,"modules":{"developer":1}
,"sensor":{"processing":1}
,"processing":{"engine":1}
,"engine":{"spe":1}
,"spe":{"developer":1}
,"tensorrt":{"documentation":1,"support":1,"release":1,"developer":1,"installation":1,"performance":1,"samples":1,"api":1,"software":1}
,"support":{"matrix":1}
,"release":{"notes":1}
,"installation":{"guide":1}
,"best":{"practices":1}
,"practices":{"tensorrt":1}
,"working":{"tensorrt":1}
,"software":{"license":1}
,"license":{"agreement":1}
}
;Search.control.loadWordPairs(pairs);
