var pairs =
{
"jetson":{"xavier":1,"linux":1,"agx":1,"nano":1,"development":1,"download":1,"gpio":1}
,"xavier":{"adaptation":1,"developer":1,"jetson":1,"mb1":1,"modules":1,"thermal":1,"module":1,"pinmux":1,"files":1,"two":1,"pcie":1,"nx-specific":1,"support":1,"p3509":1,"xhci":1,"pin":1,"xudc":1}
,"adaptation":{"bring-up":1}
,"topic":{"describes":1,"jetson":1,"topic":1,"shows":1,"kernel":1}
,"describes":{"port":1,"usb":1,"gpio":1}
,"port":{"nvidia":1,"index":1,"group":1,"name":1,"assigned":1,"example":1,"pin":1,"gpio":1,"case":1,"kernel":1,"three":1,"design":1,"nine":1,"numbers":1,"number":1,"capability":1,"usb2":1,"port":1,"mapped":1,"usb3":1,"using":1,"p3509":1,"root":1,"node":1,"usb":1,"switch":1,"adds":1,"separate":1,"switching":1,"controlled":1,"operating":1,"defined":1,"fixed":1,"host-only":1,"except":1,"transitions":1,"plus":1}
,"nvidia":{"jetson":1,"customization":1,"platform":1,"soc":1,"documentation":1,"tegra19x-pcie.txt":1,"team":1,"function":1,"usb2-companion":1,"oc-pin":1,"xusb-padctl.txt":1,"boost_cpu_freq":1,"boost_cpu_trigger":1,"xusb-padctl":1,"tegra-xhci.txt":1,"tegra-xudc.txt":1}
,"linux":{"driver":1,"host":1,"root":1,"kernel":1,"gpio":1,"rootfs":1}
,"driver":{"package":1,"xhci":1,"xudc":1,"node":1}
,"package":{"l4t":1,"directory":1}
,"l4t":{"nvidia":1,"installer":1,"standard":1}
,"developer":{"kit":1}
,"kit":{"hardware":1,"p3518":1,"includes":1,"som":1,"fansink":1,"jetson":1,"appears":1,"board":1,"carrier":1,"cannot":1,".conf":1}
,"hardware":{"platform":1,"applied":1,"nvidia":1,"design":1}
,"examples":{"described":1,"valid":1,"based":1}
,"described":{"include":1,"above":1,"xhci":1}
,"include":{"code":1,"regulator":1,"statements":1,"configuring":1,"entry":1}
,"code":{"jetson":1,"data":1,"device":1,"nvtbootwb0.bin":1}
,"information":{"customizing":1,"enable":1,"file":1,"jetson":1,"xusb_padctl":1,"xhci":1,"state":1,"extcon":1,"xudc":1}
,"customizing":{"configuration":1}
,"configuration":{"files":1,"modifications":1,"odm":1,"accommodate":1,"boot":1,"kernel":1,"changes":1,"hardware":1,"tables":1,"applied":1,"download":1,"board":1,"file":1,"code":1,"bringup":1,"device":1}
,"files":{"topic":1,"whose":1,"named":1,"define":1,"disabling":1,"describe":1,"available":1,"referenced":1,"may":1,"overrides":1,"based":1,"already":1,"name":1,"archive":1}
,"agx":{"xavier":1}
,"mb1":{"platform":1,"configuration":1,"boot":1}
,"platform":{"configuration":1,"c2f0000.gpio":1,"2200000.gpio":1,"modify":1,"t19x":1,"tegra":1}
,"board":{"configuration":1,"p\u2011number":1,"eeprom":1,"saved":1,"p3509":1,"instead":1,"required":1,"p3449-0000":1,"automatically":1,"naming":1,"assign":1,"combination":1,"name":1,"linux":1,"names":1,"used":1,"substitute":1,"provided":1,"copies":1,"schematic":1,"change":1,"translate":1,"configurations":1,"custom":1,"modified":1,"consequently":1,"modify":1,"designed":1,"verify":1,"consulting":1,"design":1,"find":1,"controlled":1,".conf":1,"mmcblk0p1":1}
,"includes":{"p3668-0000":1}
,"p3668-0000":{"system":1,"p3518-0000-devkit":1}
,"system":{"module":1,"configurations":1,"assumes":1}
,"module":{"som":1,"provided":1,"l4t":1,"carrier":1,"custom":1,"socket":1}
,"som":{"connected":1,"carrier":1,"used":1,"table":1,"connector":1,"gpio":1,"socket":1}
,"connected":{"p3509-0000":1,"p3509":1,"root":1,"usb2":1,"pin":1,"cable":1,"remains":1,"vbus_detect":1,"logical":1,"boot":1,"property":1}
,"p3509-0000":{"carrier":1,"p3668-0000":1,"p3668-0000-qspi-sd.conf":1}
,"carrier":{"board":1,"board\u2019s":1}
,"p\u2011number":{"p3518":1}
,"p3518":{"designates":1}
,"designates":{"complete":1}
,"complete":{"jetson":1}
,"eeprom":{"board":1,"custom":1,"parameters":1,"value":1}
,"saved":{"som":1}
,"used":{"without":1,"represent":1,"controller":1}
,"without":{"software":1}
,"software":{"configuration":1}
,"modules":{"provision":1}
,"provision":{"attaching":1}
,"attaching":{"heatsink":1}
,"heatsink":{"fansink":1}
,"fansink":{"module":1,"already":1}
,"provided":{"jetson":1,"driver":1,"nvidia":1,"external":1,"host":1,"cable":1}
,"already":{"attached":1,"present":1}
,"attached":{"jetson":1,"usb":1}
,"thermal":{"design":1,"solution":1}
,"design":{"guide":1,"platform":1,"changes":1,"carrier":1,"jetson":1,"files":1,"consider":1}
,"guide":{"guidance":1}
,"guidance":{"designing":1,"checking":1}
,"designing":{"procuring":1}
,"procuring":{"thermal":1}
,"solution":{"production":1}
,"production":{"jetson":1}
,"using":{"som":1,"script":1,"p3668":1,"value":1}
,"p3509":{"change":1,"eeprom":1,"carrier":1,"board":1,"need":1}
,"change":{"kernel":1,"pinmux":1,"detected":1}
,"kernel":{"device":1,"pinmux":1,"assigns":1,"messages":1,"debug":1,"case":1,"configuration":1,"customization":1,"kernel-4.9":1,"zimage":1}
,"device":{"tree":1,"tree\u2019s":1,"port":1,"a-plug":1,"b-plug":1,"role":1,"drivers":1,"driver":1,"wake":1,"node":1,"mode":1,"sector":1,"emmc":1}
,"tree":{"mb1":1,"proc":1,"platform":1,"documentation":1,"changes":1,"examples":1,"structure":1,"file":1}
,"odm":{"data":1}
,"data":{"flashing":1,"specific":1,"based":1,"transfer":1,"limit":1}
,"flashing":{"configuration":1,"directory":1,"build":1,"script":1,"process":1}
,"accommodate":{"new":1}
,"new":{"carrier":1}
,"instead":{"p3509":1}
,"custom":{"board":1,"carrier":1,"board\u2019s":1}
,"reference":{"carrier":1,"p3668.conf.common":1}
,"p3449-0000":{"included":1}
,"included":{"jetson":1}
,"nano":{"developer":1}
,"installer":{"detects":1}
,"detects":{"type":1,"usb":1}
,"type":{"module":1,"port_number":1,"usb2":1}
,"automatically":{"installs":1,"generated":1}
,"installs":{"appropriate":1}
,"appropriate":{"drivers":1,"targeted":1}
,"drivers":{"device-specific":1,"detect":1,"something":1}
,"device-specific":{"components":1}
,"support":{"jetson":1,"custom":1,"dual":1,"aspm":1,"enhanced":1,"usb":1,"contain":1,"contains":1,"phandle":1}
,"assign":{"module":1}
,"combination":{"board":1}
,"name":{"name":1,"consist":1,"environment":1,"filenames":1,"throughout":1,"custom":1,"default":1,"refers":1,"file":1,"modify":1,"spi0_cs1":1,"gpio3_pz.07":1,"example":1,"indicates":1,"board":1,"parameter":1,"function":1,"extcon":1,"output":1,"vbus_id":1,"vbus":1,"flashing":1,"mts_si":1,"mts_preboot_si":1}
,"consist":{"lower":1}
,"lower":{"case":1}
,"case":{"letters":1,"320":1}
,"letters":{"numerals":1}
,"numerals":{"hyphens":1}
,"hyphens":{"underscores":1}
,"underscores":{"board":1}
,"environment":{"variable":1,"variables":1}
,"variable":{"board":1,"settings":1}
,"host":{"system":1,"controller":1,"device":1,"e.g":1,"driver":1,"mode":1,"machine":1}
,"valid":{"board":1,"gpios":1}
,"names":{"p3509-0000":1,"device":1,"form":1}
,"p3518-0000-devkit":{"devboard":1}
,"installation":{"process":1}
,"process":{"uses":1}
,"uses":{"board":1,"usb":1,"configuration":1}
,"filenames":{"pathnames":1}
,"pathnames":{"including":1,"contain":1}
,"including":{"names":1,".dts":1}
,"proc":{"filesystem":1}
,"placeholder":{"board":1}
,"represent":{"board":1}
,"throughout":{"topic":1}
,"shows":{"command":1,"gpio3-pz.07":1}
,"command":{"contains":1,"resulting":1,"usage":1}
,"contains":{"board":1,"code":1,"gpio":1,"two":1,"extcon-cable":1}
,"substitute":{"name":1}
,"modify":{"files":1,"support":1,".dts":1,"distributed":1}
,"whose":{"filenames":1}
,"contain":{"system\u2019s":1,"entry":1,"pointer":1,"pointers":1}
,"system\u2019s":{"default":1}
,"default":{"board":1,"configuration":1,"pinmux":1,"values":1,"512byte":1}
,"refers":{"carrier":1}
,"development":{"kit":1}
,"appears":{"file\u2019s":1}
,"file\u2019s":{"name":1}
,"file":{"contains":1,"generated":1,"configures":1,"replace":1,"tegra194-mb1-bct-pmic-p3668-0001-a00.cfg":1,"used":1,".dtsi":1,"including":1,"check":1,"covers":1,"included":1,"during":1,"board":1,"flashed":1,"name":1,"sign":1,"encrypt":1,"camera-rtcpu-sce.img":1,"path":1,"reflected":1,"p3509-0000":1}
,"specific":{"board":1,"values":1}
,"copies":{"files":1}
,"named":{"custom":1,"pads":1}
,"board\u2019s":{"board":1,"pinmux":1,"requirements":1,"schematic":1}
,"root":{"filesystem":1,"hub":1}
,"filesystem":{"configuration":1,"rootfs":1,"provided":1}
,"standard":{"customized":1,"usb":1}
,"customized":{"linux":1,"jetson":1}
,"rootfs":{"appropriate":1,"configurations":1,"location":1,"size":1,"directory":1}
,"targeted":{"embedded":1}
,"embedded":{"applications":1}
,"however":{"certain":1}
,"certain":{"settings":1}
,"settings":{"configured":1,"source":1,"p3509":1,"configure":1,"external":1,"otg":1,"above":1,"jetson":1}
,"configured":{"rootfs\u2019s":1,"target":1,"endpoints":1}
,"rootfs\u2019s":{"boot-up":1}
,"boot-up":{"framework":1,"scripts":1}
,"framework":{"default":1}
,"boot":{"core":1,"time":1,"configuration":1,"expressed":1,"control":1,"partition":1}
,"core":{"functionalities":1}
,"functionalities":{"run":1}
,"run":{"expected":1}
,"nv.sh":{"nvfb.sh":1}
,"nvfb.sh":{"boot-up":1}
,"scripts":{"platform-specific":1}
,"platform-specific":{"configuration":1}
,"xorg":{"libraries":1}
,"libraries":{"correctly":1}
,"correctly":{"configured":1}
,"target":{"device":1,"rootfs":1,"cmdline":1,"machine":1,"board\u0027s":1}
,"nvpmodel":{"clock":1}
,"clock":{"frequency":1}
,"frequency":{"configured":1,"boosted":1,"dvfs":1,"further":1,"enabled":1,"pmqos":1}
,"configurations":{"customizations":1,"defined":1}
,"customizations":{"provided":1}
,"directory":{"subdirectories":1,"name":1}
,"linux_for_tegra":{"nv_tegra":1,"apply_binaries.sh":1,"kernel":1}
,"incorporate":{"relevant":1}
,"relevant":{"customization":1}
,"customization":{"target":1,"applied":1}
,"sample":{"ubuntu":1}
,"ubuntu":{"root":1}
,"applied":{"using":1,"bootloader":1,"software":1}
,"script":{"linux_for_tegra":1,"uses":1,"updates":1}
,"multiple":{".cfg":1}
,".cfg":{"files":1,"instructions":1}
,"define":{"boot":1,"board\u2019s":1,"pinmux":1,"tegra_main_gpio_port_z":1,"phy":1,"board-specific":1}
,"time":{"configuration":1,"slot":1,"milliseconds":1,"passed":1}
,"bootloader":{"mb1":1,"t186ref":1,"-------------":1,"binary":1,"images":1,"spe.bin":1,"nvtboot.bin":1}
,"tables":{"available":1}
,"l4t_top":{"bootloader":1,"top-level":1}
,"t186ref":{"bct":1}
,"top-level":{"bsp":1}
,"bsp":{"flashing":1}
,"pinmux":{"changes":1,"configuration":1,"table":1,"settings":1,"t19x":1,"spreadsheet":1}
,"schematic":{"differs":1,"file":1,"conclude":1,"following":1}
,"differs":{"jetson":1}
,"download":{"jetson":1,"center":1}
,"table":{"jetson":1,"som":1,"spreadsheet":1,"pinmux":1,"spi0_cs1":1,"gpio":1,"describes":1,"configuration":1}
,"center":{"sure":1,"search":1}
,"sure":{"right":1}
,"right":{"version":1}
,"version":{"table":1}
,"spreadsheet":{"provided":1,"configuration":1,"gpio":1}
,"show":{"locations":1}
,"locations":{"default":1}
,"source":{"code":1,"ldk_dir":1}
,"customize":{"spreadsheet":1}
,"once":{"done":1}
,"done":{"convert":1}
,"convert":{".dtsi":1}
,".dtsi":{"file":1,"files":1}
,"generated":{"excel":1}
,"excel":{".cfg":1}
,"instructions":{"readme":1}
,"readme":{"file":1}
,"perform":{"conversion":1,"following":1}
,"conversion":{"gpio.dtsi":1}
,"gpio.dtsi":{"padvoltage.dtsi":1}
,"gpio":{"changes":1,"numbers":1,"mapping":1,"number":1,"name":1,"group":1,"belongs":1,"port":1,"ports":1,"controller":1,"expander-based":1,"regulator":1,"states":1,"state":1,"corresponds":1}
,"designed":{"carrier":1,"verified":1,"internal":1}
,"translate":{"som":1}
,"connector":{"pins":1,"example":1,"called":1,"supports":1,"class":1,"connector\u2019s":1,"wired":1}
,"pins":{"actual":1,"connect":1,"usp_d_p":1,"117":1,"161":1,"wire":1}
,"actual":{"gpio":1}
,"numbers":{"understand":1,"controlled":1,"name":1}
,"understand":{"gpio":1}
,"mapping":{"formula":1}
,"formula":{"below":1,"calculate":1}
,"below":{"translated":1,"reference":1}
,"translated":{"gpio":1}
,"controlled":{"driver":1,"hub":1,"host":1}
,"example":{"check":1,"gpio3_pz.07":1,"output":1,"pin":1,"following":1,"configuration":1,"host-only":1,"consider":1,"create":1,"otg":1,"environment":1}
,"check":{"gpio":1,"changes":1,"realtek":1,"usb":1,"pinmux":1}
,"number":{"signal":1,"base":1,"spi0_cs1":1,"rts5489-gr":1,"cells":1}
,"signal":{"name":1,"pairs":1,"integrity":1,"pins":1,"pair":1}
,"spi0_cs1":{"perform":1,"320":1}
,"following":{"procedure":1,"settings":1,"diagram":1,"odd-numbered":1,"environment":1,"command":1}
,"open":{"jetson":1}
,"changes":{"above":1,"include":1,"taken":1,"port":1,"device":1}
,"search":{"table":1,"kernel":1,"consecutive":1}
,"confirm":{"customer":1}
,"customer":{"usage":1}
,"usage":{"field":1}
,"field":{"contains":1}
,"refer":{"tegra194-gpio.h":1,"documentation":1}
,"tegra194-gpio.h":{"determine":1}
,"determine":{"gpio":1}
,"group":{"gpio":1,"port":1,"offset":1,"base":1,"xusb":1}
,"belongs":{"port":1,"main":1,"tegra-gpio":1,"case":1}
,"index":{"gpio":1,"determined":1,"320":1,"index":1,"pin":1,"within":1,"extcon-gpio":1,"specified":1}
,"determined":{"last":1}
,"last":{"letter":1,"part":1}
,"letter":{"dot":1}
,"dot":{"port":1}
,"gpio3_pz.07":{"belongs":1}
,"main":{"jetson":1}
,"assigns":{"gpio":1}
,"ports":{"dynamically":1,"jetson":1,"device":1,"describe":1,"form":1,"subnode":1}
,"dynamically":{"search":1}
,"messages":{"find":1}
,"find":{"base":1,"socket":1,"corresponding":1}
,"base":{"index":1,"port":1,"base":1}
,"offset":{"first":1}
,"first":{"gpio":1,"element":1}
,"assigned":{"controller":1,"according":1}
,"controller":{"command":1,"i.e":1,"linux":1,"jetson":1,"state":1,"configuration":1,"based":1,"features":1,"operates":1,"complies":1,"names":1,"field\u2019s":1,"therefore":1,"supports":1}
,"resulting":{"output":1}
,"output":{"similar":1,"shows":1,"cable":1}
,"sudo":{"grep":1,"flash.sh":1}
,"grep":{"tegra-gpio":1}
,"tegra-gpio":{"sys":1,"group":1}
,"sys":{"kernel":1}
,"debug":{"gpio":1}
,"gpiochip1":{"gpios":1}
,"gpios":{"256-319":1,"320-511":1,"list":1,"states":1,"provided":1,"&tegra_main_gpio":1}
,"256-319":{"parent":1}
,"parent":{"platform":1}
,"c2f0000.gpio":{"tegra-gpio-aon":1}
,"gpiochip0":{"gpios":1}
,"320-511":{"parent":1}
,"2200000.gpio":{"tegra-gpio":1}
,"gpio3-pz.07":{"belongs":1}
,"part":{"gpio":1}
,"indicates":{"gpio\u2019s":1}
,"gpio\u2019s":{"pin":1}
,"pin":{"index":1,"within":1,"group":1,"port":1,"standard":1,"otg":1,"grounded":1,"floating":1,"111":1,"109":1,"vbus_detect":1,"gpio_q0":1,"example":1,"pin":1,"designed":1,"pulled":1,"depends":1,"matter":1,"settings":1,"connector":1,"extcon":1}
,"within":{"gpio":1}
,"calculate":{"gpio":1}
,"i.e":{"offset":1}
,"hence":{"gpio":1,"function":1}
,"320":{"527":1}
,"pmic":{"changes":1,"configuration":1,"p3668":1,"turn":1,"fps":1,"ddr":1}
,"configures":{"initial":1}
,"initial":{"pmic":1}
,"p3668":{"som":1}
,"expander-based":{"gpio":1}
,"regulator":{"settings":1,"information":1,"parameter":1,"corresponding":1}
,"defined":{"review":1,"information":1,"state":1}
,"review":{"configuration":1}
,"replace":{"references":1}
,"references":{"p3509":1}
,"required":{"include":1,"device":1}
,"enable":{"file":1,"disable":1,"vdd_3v3_sys":1}
,"configure":{"pmic":1}
,"turn":{"sd4":1}
,"sd4":{"i2c":1,"vdd_ddr_1v1":1}
,"i2c":{"address":1}
,"address":{"0x3c":1,"colon":1}
,"0x3c":{"example":1}
,"fps":{"turn":1,"gpio2":1,"slot":1}
,"vdd_ddr_1v1":{"time":1}
,"gpio2":{"en_ddr_vddq":1}
,"en_ddr_vddq":{"high":1}
,"high":{"time":1,"speed":1,"logical":1,"a-plug":1}
,"slpen":{"clrse":1}
,"clrse":{"por":1}
,"por":{"reset":1}
,"pmic.system.block":{".type":1,".controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".block-delay":1,".commands":1}
,".type":{"i2c":1}
,".slave-add":{"0x78":1}
,"0x78":{"7bit:0x3c":1}
,".commands":{".0x53.0x38":1,".0x55.0x38":1,".0x41.0x1c":1}
,".0x53.0x38":{"0x00":1}
,"0x00":{"_sd4":1}
,"_sd4":{"fps":1}
,".0x55.0x38":{"0x10":1}
,"0x10":{"_gpio2":1}
,"_gpio2":{"fps":1}
,".0x41.0x1c":{"0x1c":1}
,"0x1c":{"_slpen":1}
,"_slpen":{"clrse":1}
,"porting":{"linux":1,"usb":1}
,"assumed":{"using":1}
,"modified":{"qspi":1,"reflect":1}
,"qspi":{"pmic":1}
,"ddr":{"routing":1}
,"routing":{"lines":1}
,"lines":{"modifications":1}
,"modifications":{"making":1}
,"making":{"som":1}
,"consequently":{"based":1}
,"based":{"peripherals":1,"feature":1,"nvidia":1,"synopsis":1,"design":1,"device":1,"need":1,"board":1}
,"peripherals":{"present":1}
,"present":{"carrier":1,"rename":1}
,".dts":{"files":1,".dtsi":1,"final":1}
,"disabling":{"enabling":1}
,"enabling":{"controllers":1}
,"controllers":{"changing":1,"specifications":1,"controllers":1,"support":1}
,"changing":{"supplies":1}
,"distributed":{"configuration":1}
,"describe":{"design":1,"usb2":1}
,"top":{"hardware":1}
,"soc":{"t19x":1,"controller":1}
,"final":{"dtb":1,".dtb":1}
,"dtb":{"file":1,"dts":1}
,"reading":{"above":1}
,"above":{"file":1,"table":1}
,"referenced":{"include":1}
,"statements":{"common":1}
,"common":{".dtsi":1,"kernel-dts":1,"properties":1}
,"may":{"modified":1,"different":1}
,"reflect":{"hardware":1}
,"types":{"changes":1,"cables":1}
,"dtsi":{"filename":1}
,"filename":{"location":1}
,"power":{"supply":1,"just":1}
,"supply":{"changes":1,"cable":1}
,"parameter":{"changes":1,"description":1}
,"display":{"panel":1,"configuration":1}
,"panel":{"node":1}
,"node":{"changes":1,"follows":1,"property":1,"host-only":1}
,"details":{"display":1}
,"bringup":{"section":1}
,"section":{"topic":1,"gives":1,"uses":1,"takes":1}
,"feature":{"configuration":1}
,"state":{"enable":1,"changes":1,"pin":1,"vbus_detect":1,"change":1,"following":1,"otg":1}
,"disable":{"controller":1}
,"t19x":{"kernel-dts":1}
,"kernel-dts":{"tegra194-soc":1,"panels":1}
,"panels":{"related":1}
,"related":{".dts":1}
,"tegra":{"common":1}
,"verify":{".dts":1,"compatibility":1}
,"overrides":{"changes":1}
,"best":{"practice":1}
,"practice":{"create":1}
,"create":{".dts":1,"pad":1,"xhci":1,"table":1,"extcon":1,"xudc":1}
,"rename":{"newly":1}
,"newly":{"created":1}
,"created":{"files":1}
,"fdtdump":{"dtc":1,"dts":1}
,"dtc":{"generate":1,"dtb":1}
,"generate":{".dts":1}
,".dtb":{"file":1}
,"taken":{"effect":1}
,"dts":{"tegra194-p3668-all-p3509-0000.dtb":1}
,"tegra194-p3668-all-p3509-0000.dtb":{"tegra194-p3668-all-p3509-0000.dts":1}
,"pcie":{"controller":1,"host":1,"intellectual":1,"controllers":1,"configuration":1,"slots":1,"sata":1}
,"synopsis":{"designware":1}
,"designware":{"pcie":1}
,"intellectual":{"property":1}
,"property":{"thus":1,"values":1,"list":1,"valid":1}
,"thus":{"inherits":1}
,"inherits":{"common":1}
,"properties":{"defined":1,"pads":1,"ports":1,"node":1}
,"kernel_top":{"nvidia":1}
,"documentation":{"devicetree":1,"file":1}
,"devicetree":{"bindings":1}
,"bindings":{"pci":1,"phy":1,"usb":1,"extcon":1}
,"pci":{"nvidia":1}
,"two":{"pcie":1,"differential":1,"groups":1}
,"lane":{"width":1,"uphy":1,"usb":1}
,"width":{"speed":1,"advertisement":1}
,"dual":{"mode":1}
,"mode":{"configured":1,"m.2":1,"string":1,"host":1,"usb3":1,"otg":1}
,"aspm":{"controllers":1,"states":1}
,"slots":{"available":1}
,"available":{"jetson":1}
,"m.2":{"key":1}
,"key":{"controller":1,"form":1,"file":1}
,"operates":{"mode":1}
,"form":{"factor":1,"type":1}
,"factor":{"nvme":1,"cards":1}
,"nvme":{"cards":1}
,"cards":{"connected":1,"wi-fi":1}
,"wi-fi":{"connected":1}
,"nx-specific":{"pcie":1}
,"covers":{"topics":1}
,"topics":{"include":1}
,"configuring":{"maximum":1,"usb":1}
,"maximum":{"link":1}
,"link":{"speed":1,"width":1}
,"speed":{"link":1,"usb":1,"full":1,"low":1}
,"advertisement":{"different":1}
,"different":{"aspm":1,"types":1}
,"usb":{"universal":1,"port":1,"ports":1,"structure":1,"3.1":1,"signal":1,"2.0":1,"nvidia":1,"on-the-go":1,"otg":1,"act":1,"connector":1,"connectors":1,"hdmi":1,"pin":1,"vbus":1,"charger":1}
,"universal":{"serial":1}
,"serial":{"bus":1}
,"enhanced":{"superspeed":1}
,"superspeed":{"usb":1,"data":1,"on-board":1,"protocols":1}
,"three":{"high":1}
,"verified":{"usb3.1":1}
,"usb3.1":{"port":1}
,"compatibility":{"p3509":1}
,"consulting":{"nvidia":1}
,"nine":{"pins":1}
,"differential":{"signal":1,"pairs":1}
,"pairs":{"superspeed":1,"usp_tx_":1,"wired":1}
,"ground":{"gnd_drain":1,"logical":1}
,"gnd_drain":{"drain":1}
,"drain":{"wire":1}
,"wire":{"termination":1,"lead":1}
,"termination":{"managing":1}
,"managing":{"emi":1}
,"emi":{"rfi":1}
,"rfi":{"signal":1}
,"connect":{"utmi":1,"uphy":1,"flash":1}
,"utmi":{"pads":1,"pad":1}
,"pads":{"sstx":1,"ports":1,"subnode":1,"usb2":1,"usb3":1}
,"sstx":{"ssrx":1}
,"ssrx":{"signal":1}
,"uphy":{"handled":1,"lane":1,"lanes":1}
,"handled":{"single":1}
,"single":{"uphy":1}
,"lanes":{"shared":1,"assigned":1,"usb2-1":1,"usb3-2":1,"usb2-0":1}
,"shared":{"pcie":1}
,"sata":{"ufs":1}
,"ufs":{"xusb":1}
,"xusb":{"uphy":1}
,"according":{"custom":1,"state":1}
,"gives":{"step-by-step":1}
,"step-by-step":{"guidance":1}
,"checking":{"schematics":1}
,"schematics":{"configuring":1}
,"host-only":{"port":1}
,"3.1":{"gen2":1,"port":1,"superspeed":1}
,"gen2":{"realtek":1}
,"realtek":{"enhanced":1,"hub":1}
,"on-board":{"hub":1}
,"hub":{"model":1,"example":1,"p3509":1,"itself":1,"always":1,"port":1,"power":1,"create":1}
,"model":{"number":1}
,"rts5489-gr":{"hereafter":1}
,"hereafter":{"realtek":1}
,"archive":{"available":1}
,"consecutive":{"words":1}
,"words":{"separated":1}
,"separated":{"spaces":1}
,"spaces":{"e.g":1}
,"e.g":{"xavier":1,"connect":1,"127.0.0.1":1}
,"socket":{"location":1,"pins":1}
,"location":{"wired":1}
,"wired":{"p3668":1,"utmi":1,"uphy":1,"gpio00":1}
,"usb2":{"signal":1,"port":1,"usb3":1,"property":1,"lanes":1}
,"usp_d_p":{"usp_d_n":1}
,"usp_d_n":{"wire":1}
,"lead":{"module":1,"pin":1}
,"117":{"usb1_d":1}
,"usb1_d":{"115":1}
,"115":{"usb1_d":1}
,"screenshot":{"cell":1}
,"cell":{"phonedescription":1}
,"phonedescription":{"automatically":1}
,"usb3":{"differential":1,"signals":1,"port_number":1,"property":1,"port":1,"lanes":1,"signal":1}
,"usp_tx_":{"usp_rx_":1}
,"usp_rx_":{"wire":1}
,"161":{"sbss_rx":1}
,"sbss_rx":{"168":1}
,"168":{"usbss_tx":1}
,"pair":{"wired":1}
,"pad":{"usb2":1,"&battery_reg":1,"port":1}
,"xusb_padctl":{"node":1,"refer":1,"xusb_padctl@3520000":1,"settings":1}
,"tree\u2019s":{"xusb_padctl":1}
,"follows":{"conventions":1}
,"conventions":{"pinctrl-bindings.txt":1}
,"pinctrl-bindings.txt":{"contains":1}
,"groups":{"named":1}
,"signals":{"along":1}
,"along":{"parameters":1}
,"parameters":{"port":1,"passed":1,"added":1}
,"description":{"subnode":1}
,"subnode":{"pads":1}
,"port_number":{"type":1,"associated":1}
,"associated":{"port":1}
,"function":{"string":1,"mux":1,"xusb":1,"host":1,"device":1}
,"string":{"containing":1,"describes":1}
,"containing":{"name":1}
,"mux":{"pin":1}
,"capability":{"port":1}
,"usb2-companion":{"usb2":1}
,"mapped":{"port":1}
,"oc-pin":{"overcurrent":1}
,"overcurrent":{"vbus":1,"detection":1}
,"vbus":{"pin":1,"regulator":1,"provided":1}
,"value":{"positive":1,"cpu":1,"greater":1,"extcon-gpio-states":1,"array":1}
,"positive":{"zero":1}
,"detection":{"handling":1,"support":1,"driver":1}
,"handling":{"realtek":1}
,"itself":{"therefore":1}
,"therefore":{"need":1,"dummy":1,"state":1}
,"need":{"property":1,"control":1,"cpu":1,"boosted":1}
,"vbus-supply":{"vbus":1,"&battery_reg":1}
,"corresponding":{"utmi":1,"gpio":1,"output":1}
,"&battery_reg":{"dummy":1}
,"dummy":{"regulator":1,"regulators":1}
,"always":{"connected":1}
,"control":{"hub":1,"table":1}
,"just":{"enable":1,"otg":1}
,"vdd_3v3_sys":{"therefore":1}
,"regulators":{"p3509":1}
,"detailed":{"information":1}
,"kernel-4.9":{"documentation":1}
,"phy":{"nvidia":1,"used":1,"phy-names":1}
,"consider":{"realtek":1,"schematic":1}
,"list":{"based":1,"gpios":1}
,"structure":{"described":1}
,"status":{"okay":1}
,"xhci":{"node":1,"controller":1,"specifications":1,"refer":1,"device":1,"settings":1}
,"complies":{"xhci":1}
,"specifications":{"support":1}
,"2.0":{"high":1,"micro":1}
,"full":{"speed":1}
,"low":{"speed":1,"b-plug":1,"vbus":1}
,"phys":{"contain":1,"xusb_padctl@3520000":1,"array":1}
,"entry":{"entry":1,"phy-names":1,"phy":1,"usb":1,"detects":1}
,"phy-names":{"include":1,"usb2-1":1,"usb2-0":1,"array":1,"usb2":1}
,"boost_cpu_freq":{"value":1,"1200":1}
,"cpu":{"frequency":1,"loading":1,"boost":1,"load":1}
,"boosted":{"minimum":1}
,"minimum":{"frequency":1,"buffer":1}
,"dvfs":{"scale":1}
,"scale":{"cpu":1}
,"further":{"based":1}
,"loading":{"cpu":1}
,"boost":{"frequency":1,"applicable":1}
,"enabled":{"pmqos":1,"xudc":1}
,"pmqos":{"xhci":1,"enabled":1}
,"field\u2019s":{"value":1}
,"greater":{"zero":1}
,"zero":{"boost":1}
,"applicable":{"bulk":1,"large":1}
,"bulk":{"isoc":1,"transfers":1,"endpoints":1}
,"isoc":{"transfers":1}
,"transfers":{"endpoints":1,"beyond":1,"bulk":1}
,"endpoints":{"need":1,"endpoints":1}
,"boost_cpu_trigger":{"minimum":1}
,"buffer":{"length":1}
,"length":{"bulk":1}
,"beyond":{"boost":1}
,"xusb-padctl":{"pointer":1,"node":1,"&xusb_padctl":1}
,"pointer":{"xusb-padctl":1,"extcon-cable":1}
,"tegra_xhci":{"xhci@3610000":1}
,"xusb_padctl@3520000":{"pads":1}
,"usb2-1":{"usb3-2":1}
,"otg":{"on-the-go":1,"just":1,"specification":1,"port":1,"cable":1,"a-device":1,"support":1}
,"on-the-go":{"port":1,"often":1}
,"often":{"abbreviated":1,"device":1}
,"abbreviated":{"usb":1}
,"specification":{"allows":1}
,"allows":{"usb":1}
,"act":{"host":1}
,"switch":{"back":1}
,"back":{"forth":1}
,"forth":{"roles":1}
,"roles":{"host":1,"otg":1}
,"takes":{"usb2.0":1}
,"usb2.0":{"micro":1}
,"micro":{"connector":1}
,"adds":{"fifth":1}
,"fifth":{"pin":1}
,"called":{"pin":1}
,"cable":{"a-plug":1,"connected":1,"states":1,"names":1,"state":1}
,"a-plug":{"end":1,"inserted":1,"connected":1}
,"end":{"b-plug":1,"a-plug\u2019s":1}
,"b-plug":{"end":1,"inserted":1,"connected":1}
,"a-plug\u2019s":{"pin":1}
,"grounded":{"b-plug\u2019s":1}
,"b-plug\u2019s":{"pin":1}
,"floating":{"device":1,"fixed":1,"vbus_detect":1,"port":1}
,"inserted":{"becomes":1}
,"becomes":{"otg":1,"b-device":1}
,"a-device":{"host":1}
,"b-device":{"device":1}
,"fixed":{"device":1}
,"role":{"jetson":1}
,"cannot":{"function":1}
,"flash":{"drive":1,"application":1,"server":1,"build":1}
,"drive":{"keyboard":1}
,"keyboard":{"mouse":1}
,"connectors":{"p3509":1,"may":1}
,"111":{"usb0_d":1}
,"usb0_d":{"pin":1,"som":1}
,"109":{"usb0_d":1}
,"supports":{"highspeed":1,"notifier":1,"usb":1}
,"highspeed":{"mode":1}
,"external":{"connector":1,"connectors":1,"power":1}
,"class":{"extcon":1}
,"cables":{"attached":1}
,"hdmi":{"analog":1}
,"analog":{"others":1}
,"others":{"often":1}
,"detect":{"state":1}
,"separate":{"device":1}
,"something":{"according":1}
,"extcon":{"introduced":1,"node":1,"device":1,"refer":1,"extcon-gpio-states.txt":1,"settings":1,"cable":1,"specifier":1}
,"introduced":{"2012":1}
,"2012":{"supports":1}
,"notifier":{"passing":1}
,"passing":{"information":1}
,"generally":{"port":1,"pin":1}
,"switching":{"roles":1}
,"xudc":{"defined":1,"node":1,"controller":1,"refer":1}
,"vbus_detect":{"pin":1,"logical":1,"initially":1}
,"taking":{"gpio_m3":1,"usb":1,"j51":1}
,"gpio_m3":{"vbus_detect":1}
,"gpio_q0":{"pin":1,"gpio_m3":1}
,"states":{"vbus_detect":1,"corresponding":1,"gpio":1,"value":1,"gpio_q0":1,"gpio_pz1":1}
,"internal":{"pull":1,"emmc":1}
,"pull":{"high":1}
,"logical":{"high":1,"low":1}
,"pulled":{"ground":1}
,"remains":{"logical":1}
,"operation":{"vbus_detect":1}
,"depends":{"device\u2019s":1}
,"device\u2019s":{"design":1}
,"diagram":{"example":1}
,"close":{"mapdescription":1}
,"mapdescription":{"automatically":1}
,"initially":{"logical":1}
,"matter":{"otg":1}
,"operating":{"host":1}
,"0x0":{"excon_none":1,"0x2":1,"0x1":1}
,"0x2":{"extcon_usb_host":1,"0x1":1}
,"0x1":{"extcon_usb":1,"0x2":1,"0x0":1}
,"compatible":{"value":1,"extcon-gpio-states":1}
,"extcon-gpio":{"name":1,"irq-flags":1,"debounce":1,"wait-for-gpio-scan":1,"out-cable-names":1,"cable-states":1}
,"irq-flags":{"irq":1}
,"irq":{"flags":1}
,"flags":{"gpio":1}
,"debounce":{"debounce":1,"time":1}
,"wait-for-gpio-scan":{"wait":1}
,"wait":{"timeout":1}
,"timeout":{"scanning":1}
,"scanning":{"gpios":1}
,"detected":{"debounce":1}
,"out-cable-names":{"output":1,"first":1,"extcon_usb":1}
,"cable-states":{"gpio":1,"0x3":1}
,"array":{"bytes":1,"contain":1}
,"bytes":{"even-numbered":1}
,"even-numbered":{"byte":1}
,"byte":{"gpio":1,"corresponding":1}
,"odd-numbered":{"byte":1}
,"cable-connected-on-boot":{"name":1}
,"expressed":{"index":1}
,"element":{"index":1}
,"specified":{"system":1}
,"assumes":{"cable":1}
,"wakeup-source":{"boolean":1}
,"boolean":{"true":1}
,"true":{"device":1}
,"wake":{"system":1}
,"vbus_id_extcon":{"extcon@1":1}
,"0x3":{"0x0":1}
,"&tegra_main_gpio":{"tegra194_main_gpio":1}
,"extcon_usb":{"extcon_usb_host":1}
,"extcon_usb_host":{"extcon_none":1}
,"connector\u2019s":{"pin":1}
,"gpio00":{"corresponds":1}
,"corresponds":{"gpio_pz1":1,"pin":1}
,"gpio_pz1":{"hence":1,"vbus_detect":1,"customized":1}
,"reg":{"0x1":1}
,"except":{"mode":1,"addition":1}
,"addition":{"extcon":1}
,"extcon-cables":{"otg":1,"&vbus_id_extcon":1}
,"extcon-cable":{"entry":1}
,"transitions":{"host":1,"device":1}
,"extcon-cells":{"number":1}
,"cells":{"extcon":1}
,"j51":{"usb":1}
,"plus":{"extcon":1}
,"extcon-cable-names":{"vbus":1}
,"charger-detector":{"usb":1}
,"charger":{"detection":1}
,"phandle":{"usb":1}
,"pointers":{"nodes":1}
,"nodes":{"define":1}
,"load":{"cpu":1}
,"large":{"bulk":1}
,"tegra_xudc":{"xudc@3550000":1}
,"build":{"image":1}
,"image":{"specific":1,"file":1}
,".conf":{"file":1,"override":1}
,"during":{"flashing":1}
,"setting":{"optional":1}
,"optional":{"environment":1}
,"flash.sh":{"script":1,"board":1}
,"updates":{"following":1}
,"variables":{"based":1,"define":1}
,"passed":{"want":1}
,"want":{"give":1}
,"give":{"specific":1}
,"values":{"variables":1}
,"board-specific":{"file":1}
,"override":{"default":1,"eeprom":1}
,"bctfile":{"----------------":1}
,"----------------":{"boot":1,"pass":1,"partition":1,"target":1,"device":1,"flash":1,"static":1,"nfsroot":1,"odmdata":1,"sce":1,"spe":1,"warmboot":1}
,"boardid":{"----------------":1,"override":1}
,"pass":{"boardid":1,"board_revision":1,"board_sku":1}
,"boardrev":{"---------------":1}
,"---------------":{"pass":1,"size":1,"flash":1}
,"board_revision":{"override":1}
,"boardsku":{"---------------":1}
,"board_sku":{"override":1}
,"-------------":{"bootloader":1,"mts":1,"linux":1}
,"binary":{"flashed":1}
,"bootpartlimit":{"----------":1}
,"----------":{"gpt":1}
,"gpt":{"data":1}
,"limit":{"max":1}
,"max":{"bct":1}
,"bct":{"size":1}
,"size":{"ppt":1,"default":1,"target":1,"internal":1}
,"ppt":{"size":1}
,"bootpartsize":{"-----------":1}
,"-----------":{"total":1,"linux":1}
,"total":{"emmc":1}
,"emmc":{"boot":1,"boot0":1,"nand":1}
,"partition":{"size":1,"table":1}
,"cfgfile":{"----------------":1}
,"cmdline":{"----------------":1,"help":1}
,"help":{"information":1}
,"devsectsize":{"------------":1}
,"------------":{"device":1}
,"sector":{"size":1}
,"dtbfile":{"----------------":1}
,"emmcsize":{"---------------":1}
,"boot0":{"boot1":1}
,"boot1":{"user":1}
,"flashapp":{"---------------":1}
,"application":{"running":1}
,"running":{"host":1,"target":1}
,"flasher":{"----------------":1}
,"server":{"running":1}
,"initrd":{"-----------------":1,"image":1}
,"-----------------":{"initrd":1,"rsa":1,"sbk":1}
,"kernel_image":{"-----------":1}
,"zimage":{"file":1}
,"mts":{"--------------------":1,"file":1,"preboot":1}
,"--------------------":{"mts":1,"target":1}
,"mtspreboot":{"-------------":1}
,"preboot":{"file":1}
,"nfsargs":{"----------------":1}
,"static":{"network":1}
,"network":{"assignments":1}
,"assignments":{"client":1}
,"client":{"server":1}
,"gateway":{"addresses":1}
,"addresses":{"netmask":1}
,"netmask":{"format":1}
,"c_ip":{"s_ip":1}
,"s_ip":{"g_ip":1}
,"g_ip":{"netmask":1}
,"nfsroot":{"----------------":1,"address":1}
,"colon":{"path":1}
,"127.0.0.1":{"exported":1}
,"exported":{"rootfs_dir":1}
,"odmdata":{"----------------":1,"used":1}
,"pkckey":{"-----------------":1}
,"rsa":{"key":1}
,"sign":{"bootloader":1}
,"rootfssize":{"-------------":1}
,"rootfs_dir":{"-------------":1}
,"sbkkey":{"-----------------":1}
,"sbk":{"key":1}
,"encrypt":{"bootloader":1}
,"scefile":{"----------------":1}
,"sce":{"firmware":1}
,"firmware":{"file":1}
,"spefile":{"----------------":1}
,"spe":{"firmware":1}
,"path":{"bootloader":1}
,"fab":{"--------------------":1}
,"board\u0027s":{"fab":1}
,"tegraboot":{"--------------":1}
,"--------------":{"lowerlayer":1}
,"lowerlayer":{"bootloader":1}
,"wb0boot":{"----------------":1}
,"warmboot":{"code":1}
,"added":{"below":1}
,"p3668.conf.common":{"file":1}
,"reflected":{"flashed":1}
,"flashed":{"image":1}
,"ldk_dir":{"p3668.conf.common":1}
,"blblocksize":{"1048576":1}
,"emmc_cfg":{"flash_l4t_t194_spi_sd_p3668.xml":1}
,"recrootfssize":{"100mib":1}
,"execute":{"following":1}
}
;Search.control.loadWordPairs(pairs);
