var pairs =
{
"jetson":{"module":1,"linux":1,"developer":1,"platforms":1,"platform":1,"nano":1,"download":1}
,"module":{"adaptation":1,"describes":1,"intended":1}
,"adaptation":{"bring-up":1}
,"topic":{"users":1}
,"users":{"developing":1}
,"developing":{"production":1}
,"production":{"software":1}
,"software":{"nvidia":1,"bring-up":1}
,"nvidia":{"jetson":1,"bring-up":1}
,"describes":{"port":1}
,"port":{"nvidia":1}
,"linux":{"driver":1}
,"driver":{"package":1}
,"package":{"l4t":1}
,"l4t":{"u-boot":1,"nvidia":1}
,"u-boot":{"boot":1}
,"boot":{"loader":1}
,"loader":{"nvidia":1}
,"developer":{"kit":1}
,"kit":{"hardware":1}
,"hardware":{"platform":1,"bring-up":1}
,"initial":{"subtopics":1}
,"subtopics":{"apply":1}
,"apply":{"ports":1}
,"ports":{"jetson":1}
,"subtopic":{"applies":1}
,"applies":{"ports":1}
,"platform":{"currently":1,"during":1}
,"currently":{"supported":1}
,"supported":{"l4t":1}
,"nano":{"2gb":1}
,"2gb":{"included":1,"developer":1}
,"included":{"module":1}
,"intended":{"educational":1}
,"educational":{"experimental":1}
,"experimental":{"applications":1}
,"applications":{"sold":1}
,"sold":{"component":1}
,"component":{"nvidia":1}
,"checklist":{"recommended":1}
,"recommended":{"steps":1}
,"steps":{"hardware":1,"software":1}
,"bring-up":{"process":1,"framework":1,"20framework":1}
,"process":{"processor":1,"download":1}
,"framework":{"checking":1,"suite":1,"jetson":1,"follow":1}
,"checking":{"functions":1}
,"suite":{"scripts":1}
,"scripts":{"checking":1}
,"functions":{"platform":1}
,"during":{"bring-up":1}
,"download":{"bring-up":1,"center":1,"untar":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"downloads":1}
,"downloads":{"search":1}
,"search":{"bring-up":1}
,"untar":{"bring-up":1}
,"follow":{"instructions":1}
,"instructions":{"readme":1}
,"readme":{"file":1}
}
;Search.control.loadWordPairs(pairs);
