var pairs =
{
"jetson":{"tx2":1,"bsp":1,"linux":1}
,"tx2":{"boot":1,"series":1,"bootrom":1,"bootloader":1,"microboot1":1,"tegraboot":1,"tegraboot-cpu":1,"cboot":1,"mb1":1}
,"boot":{"flow":1,"software":1,"media":1,"configuration":1,"sequence":1,"downloading":1,"tegraboot-bpmp":1,"similar":1,"except":1,"tegraboot-cpu":1,"integrating":1,"path":1,"logo":1,"kernel":1}
,"applies":{"nvidia":1}
,"nvidia":{"jetson":1,"tegra":1,"owned":1,"provided":1}
,"series":{"devices":1}
,"flow":{"control":1,"follows":1,"rcm":1}
,"control":{"boot":1,"mb1":1,"bpmp-fw":1,"tegraboot-cpu":1,"cboot":1}
,"software":{"follows":1,"support":1,"design":1,"libraries":1,"component":1}
,"screenshot":{"cell":1,"video":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1,"generated":1}
,"automatically":{"generated":1}
,"bootrom":{"hard-wired":1,"boot":1,"hardware":1,"uses":1,"signed":1,"following":1}
,"hard-wired":{"processor":1}
,"processor":{"initializes":1,"executing":1}
,"initializes":{"boot":1,"cpu":1,"usb":1}
,"media":{"loads":1}
,"loads":{"microboot1":1}
,"microboot1":{"mb1":1}
,"mb1":{"boot":1,"tegraboot-bpmp":1,"first":1,"considered":1,"provides":1,"extension":1,"responsible":1,"owned":1,"reads":1,"mb1":1,"bct":1,"component":1,"binaries":1,"platform":1}
,"multiple":{"copies":1}
,"copies":{"bootrom":1}
,"configuration":{"table":1,"parameters":1,"includes":1,"files":1}
,"table":{"br-bct":1,"mb1-bct":1,"called":1}
,"br-bct":{"may":1,"contains":1}
,"may":{"stored":1}
,"stored":{"start":1,"separate":1}
,"start":{"boot-media":1}
,"boot-media":{"br-bct":1}
,"contains":{"configuration":1,"information":1,"binaries":1}
,"parameters":{"used":1,"initializing":1}
,"used":{"bootrom":1,"cold":1,"mobile":1}
,"hardware":{"initialization":1}
,"bct":{"contains":1}
,"information":{"bootloader":1,"verify":1,"mb1":1}
,"bootloader":{"including":1,"boot":1,"components":1,"flash":1,"software":1,"partner":1,"tboot-bpmp":1,"component":1,"device":1,"used":1,"nvidia":1}
,"entry":{"point":1}
,"load":{"address":1,"bootloader":1,"firmware":1,"next":1}
,"uses":{"information":1,"interrupt":1,"cdf":1}
,"verify":{"load":1}
,"swdocs":{"mobile":1}
,"mobile":{"tegra":1,"platforms":1}
,"tegra":{"images":1,"bootloader":1}
,"images":{"bdk_bootrom_flow.jpg":1,"bdk_microboot.jpg":1}
,"flash":{"components":1,"device":1}
,"common":{"driver":1,"across":1,"pool":1}
,"driver":{"framework":1,"package":1}
,"framework":{"cdf":1,"follows":1,"consists":1}
,"tboot-bpmp":{"mb2":1,"two":1,"responsible":1,"follows":1}
,"tegraboot-bpmp":{"tegraboot-cpu":1,"mb2":1}
,"tegraboot-cpu":{"cboot":1,"responsible":1,"initializes":1,"takes":1}
,"cboot":{"needs":1,"primary":1,"feature-rich":1,"el2":1,"responsible":1,"follows":1,"available":1}
,"needs":{"several":1}
,"several":{"drivers":1}
,"drivers":{"moreover":1,"libraries":1,"emmc":1,"uart":1}
,"moreover":{"libraries":1}
,"libraries":{"common":1,"binaries":1,"called":1,"modules":1,"linuxboot":1}
,"across":{"bootloader":1}
,"components":{"instead":1,"tboot-bpmp":1,"tboot-cpu":1,"cboot":1}
,"instead":{"using":1}
,"using":{"separate":1,"common":1,"boot":1,"different":1}
,"separate":{"sets":1,"keys":1,"device":1,"partitions":1}
,"sets":{"drivers":1}
,"binaries":{"share":1,"loading":1,"blob":1,"transferred":1,"host":1,"flashed":1}
,"share":{"common":1}
,"pool":{"drivers":1}
,"called":{"common":1,"mb1-bct":1}
,"u-boot":{"built":1,"boot":1,"default":1,"customization":1}
,"built":{"separately":1}
,"separately":{"nvidia-proprietary":1}
,"nvidia-proprietary":{"bootloader":1}
,"support":{"cdf":1,"flashing":1,"rcm":1,"sc7":1,"cold":1}
,"design":{"architecture":1}
,"architecture":{"using":1}
,"storage":{"drivers":1}
,"emmc":{"qspi-nor":1}
,"qspi-nor":{"msata":1}
,"msata":{"ufs":1}
,"host":{"interface":1,"usb":1,"one-by-one":1}
,"interface":{"drivers":1}
,"uart":{"usb":1}
,"display":{"drivers":1,"boot":1}
,"debug":{"console":1}
,"console":{"library":1}
,"partition":{"manager":1}
,"transport":{"libraries":1}
,"decompression":{"library":1}
,"library":{"supports":1,"cache":1}
,"supports":{"lzf":1,"display":1}
,"lzf":{"zlib":1}
,"zlib":{"lz4":1}
,"clib":{"dynamic":1}
,"dynamic":{"memory":1}
,"memory":{"allocation":1,"gpu":1}
,"allocation":{"library":1}
,"cache":{"library":1}
,"cdf":{"provided":1,"frameworks":1}
,"top":{"vendor":1}
,"vendor":{"nvidia":1}
,"partner":{"common":1,"t18x":1}
,"t18x":{"common":1}
,"first":{"boot":1}
,"component":{"loaded":1,"implements":1,"executes":1,"divided":1,"runs":1}
,"loaded":{"sysram":1,"directly":1,"path":1}
,"sysram":{"runs":1}
,"runs":{"bpmp":1,"released":1}
,"bpmp":{"mb1":1,"tboot-bpmp":1}
,"considered":{"extension":1}
,"extension":{"mb1":1,"bootrom":1}
,"provides":{"extensive":1}
,"extensive":{"flexibility":1}
,"flexibility":{"alter":1}
,"alter":{"fix":1}
,"fix":{"boot":1}
,"sequence":{"component":1}
,"implements":{"delicate":1}
,"delicate":{"functionality":1}
,"functionality":{"denver":1}
,"denver":{"initialization":1}
,"initialization":{"security":1,"include":1,"gives":1,"passes":1}
,"security":{"fabric":1,"settings":1}
,"fabric":{"changes":1}
,"signed":{"encrypted":1}
,"encrypted":{"nvidia":1}
,"owned":{"key":1,"nvidia":1}
,"key":{"separate":1}
,"keys":{"residing":1}
,"residing":{"bootrom":1}
,"following":{"diagram":1}
,"diagram":{"shows":1}
,"shows":{"flow":1}
,"firmware":{"initialization":1,"initializes":1,"components":1}
,"include":{"mts":1}
,"mts":{"preboot":1}
,"preboot":{"spe":1}
,"platform":{"configuration":1,"using":1}
,"configuring":{"pinmux":1,"gpio":1,"scr":1}
,"pad":{"settings":1}
,"prod":{"settings":1}
,"initializing":{"rails":1,"firmware":1,"bootloader":1}
,"rails":{"including":1}
,"including":{"required":1}
,"required":{"cpu":1}
,"cpu":{"memory":1,"complex":1,"initialization":1,"starts":1,"bootloader":1}
,"pmic":{"commands":1,"vdd_cpu":1,"reset":1}
,"commands":{"required":1}
,"initialize":{"sdram":1}
,"sdram":{"based":1,"tos":1}
,"based":{"mb1":1,"little":1}
,"complex":{"ccplex":1}
,"configure":{"pinmux":1,"behavior":1,"platform":1}
,"pinmux":{"gpio":1}
,"gpio":{"soc":1}
,"program":{"pmic":1}
,"vdd_cpu":{"vdd_ddr":1}
,"vdd_ddr":{"rails":1}
,"create":{"carveouts":1}
,"flashing":{"available":1,"tegraboot-cpu":1}
,"available":{"different":1,"public":1}
,"different":{"mb1_recovery.bin":1,"configuration":1}
,"mb1_recovery.bin":{"binary":1}
,"rcm":{"boot":1}
,"downloading":{"blob":1}
,"blob":{"contains":1,"downloaded":1}
,"loading":{"binaries":1,"initializing":1,"next":1,"bootloader":1}
,"next":{"stage":1}
,"stage":{"bootloader":1}
,"provided":{"binary":1}
,"binary":{"jetson":1,"configure":1}
,"bsp":{"package":1}
,"package":{"although":1}
,"although":{"provided":1}
,"behavior":{"specific":1}
,"specific":{"platform":1}
,"mb1-bct":{"mb1":1,"configure":1}
,"reads":{"mb1-bct":1}
,"tegraboot":{"bootloader":1,"runs":1}
,"executes":{"mb1":1}
,"divided":{"two":1}
,"two":{"portions":1,"variants":1}
,"executing":{"determines":1,"tos":1}
,"determines":{"component":1}
,"released":{"oems":1}
,"oems":{"source":1}
,"source":{"code":1,"bootloader":1}
,"code":{"reference":1,"completes":1,"cboot":1,"file":1}
,"reference":{"implementation":1}
,"portion":{"jetson":1}
,"variants":{"tegraboot-bpmp":1}
,"cold":{"boot":1}
,"recovery":{"boot":1}
,"generated":{"using":1,"high":1}
,"files":{"files":1}
,"creating":{"carveouts":1}
,"completing":{"cpu":1}
,"supporting":{"flashing":1,"rcm":1,"update":1}
,"mb2":{"recovery":1}
,"reading":{"pmic":1}
,"reset":{"reason":1}
,"device":{"tree":1,"trees":1}
,"tree":{"passing":1,"load":1}
,"passing":{"device":1}
,"address":{"cpu-bl":1}
,"giving":{"control":1}
,"video":{"game":1}
,"game":{"description":1}
,"high":{"confidence":1}
,"similar":{"cold":1}
,"except":{"binaries":1}
,"transferred":{"host":1}
,"usb":{"loaded":1,"starts":1}
,"directly":{"sdram":1}
,"tos":{"bpmp-fw":1,"monitor":1,"tos":1,"completes":1}
,"bpmp-fw":{"loaded":1}
,"soon":{"cpu":1}
,"starts":{"running":1,"el3":1,"protocol":1}
,"running":{"starts":1}
,"el3":{"mode":1}
,"mode":{"tos":1,"begins":1}
,"monitor":{"code":1}
,"completes":{"initialization":1}
,"gives":{"control":1}
,"protocol":{"flash":1}
,"normal":{"flashing":1}
,"takes":{"binaries":1}
,"one-by-one":{"flashes":1}
,"flashes":{"device":1}
,"downloaded":{"mb1":1}
,"flashed":{"onto":1}
,"onto":{"device":1}
,"tboot-cpu":{"support":1,"tested":1,"follows":1}
,"integrating":{"relevant":1}
,"relevant":{"libraries":1}
,"linuxboot":{"version":1}
,"version":{"tboot-cpu":1}
,"tested":{"maintained":1}
,"primary":{"cpu":1}
,"platforms":{"cold":1}
,"path":{"cboot":1}
,"feature-rich":{"bootloader":1}
,"boots":{"kernel":1}
,"logo":{"verified":1}
,"verified":{"boot":1}
,"little":{"kernel":1}
,"kernel":{"open":1,"separate":1,"chaining":1}
,"open":{"source":1}
,"interrupt":{"scheduling":1}
,"scheduling":{"frameworks":1}
,"frameworks":{"lkc":1,"drivers":1}
,"begins":{"executing":1}
,"passes":{"control":1}
,"el2":{"mode":1}
,"trees":{"stored":1}
,"partitions":{"cboot":1}
,"parsing":{"cpu-bl":1}
,"cpu-bl":{"parameters":1}
,"booting":{"kernel":1}
,"chaining":{"u-boot":1}
,"update":{"mechanism":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"downloads":1}
,"file":{"named":1}
,"named":{"cboot_src.tbz2":1}
,"cboot_src.tbz2":{"includes":1}
,"includes":{"instructions":1}
,"instructions":{"users":1}
,"default":{"bootloader":1}
,"linux":{"driver":1}
}
;Search.control.loadWordPairs(pairs);
