var pairs =
{
"trusty":{"trusted":1,"consists":1,"part":1,"extends":1,"based":1,"nvidia":1,"tee":1,"running":1,"resides":1,"runs":1,"software":1,"server":1,"client":1,"linux":1,"kernel":1,"disabled":1,"app":1,"source":1,"lib":1,"code":1,"system":1,"trusty":1,"include":1,"device":1,"tas":1,"rebuilds":1,"api":1,"trusty-ref":1,"uses":1,"application":1,"utilizes":1,"during":1,"decrypts":1,"performs":1,"choose":1,"derives":1,"boot":1,"jetson":1,"provides":1,"random":1,"rng":1}
,"trusted":{"execution":1,"nvidia":1,"firmware":1,"application":1,"applications":1,"trusty":1,"used":1,"android":1,"provided":1,"operations":1,"binary":1,"boot":1,"initializes":1,"managing":1,"ekb":1,"tos":1}
,"execution":{"environment":1,"steps":1,"control":1}
,"applies":{"jetson":1}
,"jetson":{"xavier":1,"agx":1,"tx2":1,"linux":1,"devices":1,"security":1,"device":1,"device\u0027s":1,"processors":1}
,"xavier":{"jetson":1,"series":1,"nvidia":1,"tegra194-br-bct-qspi.cfg":1}
,"agx":{"xavier":1}
,"series":{"jetson":1,"devices":1,"nvidia":1,"tegra194-br-bct-sdmmc.cfg":1,"emmc.cfg":1}
,"tx2":{"series":1,"device":1}
,"consists":{"software":1}
,"software":{"components":1,"operate":1,"trusty":1,"crypto":1,"cannot":1}
,"components":{"supporting":1,"non-secure":1}
,"supporting":{"trusted":1}
,"environment":{"tee":1,"includes":1,"secure":1,"provided":1,"nse":1,"running":1,"provides":1,"trusted":1}
,"tee":{"mobile":1,"provides":1,"trusted":1,"separate":1}
,"mobile":{"devices":1}
,"devices":{"tee":1,"following":1,"based":1}
,"provides":{"execution":1,"trusted":1,"interface":1,"hardware-based":1,"alternative":1}
,"includes":{"security":1,"sample":1}
,"security":{"features":1,"trusty":1,"modes":1,"functions":1,"engine":1,"keyslots":1,"reasons":1,"precaution":1,"purposes":1}
,"features":{"ensure":1}
,"ensure":{"code":1}
,"code":{"data":1,"functions":1,"simple":1,"based":1,"used":1,"hwkey-agent":1,"includes":1}
,"data":{"device":1,"structure":1,"keys":1,"used":1,"different":1,"ekb":1,"encryption":1,"two":1,"encrypted":1,"key":1,"buffer":1,"return":1,"dev":1}
,"device":{"protected":1,"different":1,"burns":1,"provisioned":1,"nvidia":1,"secure":1,"boot":1,"provisioning":1,"boots":1,"once":1,"contrast":1,"decide":1,"node":1}
,"part":{"android":1,"chain":1,"kek2_rk":1}
,"android":{"open":1,"documentation":1}
,"open":{"source":1}
,"source":{"project":1,"package":1,"files":1,"code":1,"key":1,"linux":1,"secure":1,"file":1,"setting":1}
,"project":{"aosp":1,"trusted":1,"t186-l4t.mk":1}
,"aosp":{"information":1,"packaged":1}
,"information":{"trusty":1,"little":1,"trustzone":1,"atf":1,"consumed":1,"fuses":1,"secureboot":1,"ekb":1,"burning":1}
,"https":{"source.android.com":1,"github.com":1,"www.uuidgenerator.net":1}
,"source.android.com":{"security":1}
,"extends":{"technology":1}
,"technology":{"made":1,"information":1}
,"made":{"available":1}
,"available":{"development":1}
,"development":{"little":1}
,"little":{"kernel":1,"endian":1,"ekb":1}
,"kernel":{"designed":1,"documentation":1,"driver":1,"framework":1,"encryption":1,"images":1,"kernel-dtb":1,"accumulated":1}
,"designed":{"provide":1,"generic":1}
,"provide":{"primitives":1,"rng":1}
,"primitives":{"threads":1}
,"threads":{"mutexes":1}
,"mutexes":{"simple":1}
,"simple":{"lightweight":1,"example":1}
,"lightweight":{"package":1}
,"github.com":{"littlekerneltravisg":1,"arm-software":1}
,"littlekerneltravisg":{"wiki":1}
,"based":{"arm":1,"atf":1,"reference":1,"aes-cmac":1}
,"arm":{"trustzone":1,"trusted":1}
,"trustzone":{"technology":1,"white":1}
,"white":{"paper":1}
,"http":{"infocenter.arm.com":1}
,"infocenter.arm.com":{"help":1}
,"help":{"topic":1,"design":1}
,"topic":{"com.arm.doc.prd29-genc-009492c":1,"uses":1,"information":1,"secureboot":1}
,"com.arm.doc.prd29-genc-009492c":{"prd29-genc-009492c_trustzone_security_whitepaper.pdf":1}
,"nvidia":{"jetson":1,"serve":1,"t186":1,"strongly":1,"recommends":1}
,"linux":{"driver":1,"typically":1,"kernel":1,"device":1,"trusted":1,"supports":1}
,"driver":{"package":1,"routes":1}
,"package":{"l4t":1}
,"l4t":{"enables":1,"monitor":1}
,"enables":{"booting":1,"three":1}
,"booting":{"trusted":1,"utilize":1}
,"following":{"sections":1,"layout":1,"steps":1,"nist-sp-800-108":1,"diagram":1,"outline":1}
,"sections":{"explain":1,"multiple":1}
,"explain":{"trusty":1}
,"uses":{"terms":1,"tipc":1,"encrypted":1,"key":1,"tegra-crypto":1,"cryptographic":1,"user-defined":1,"ekb_ak":1,"hardware":1}
,"terms":{"specific":1,"used":1}
,"specific":{"trusty":1}
,"atf":{"arm":1,"information":1}
,"client":{"application":1,"libraries":1}
,"application":{"application":1,"runs":1,"running":1,"secure":1,"perform":1,"calling":1,"library":1,"request":1,"handle":1,"receives":1,"development":1,"corresponding":1,"map":1,"source":1,"directory":1,"derive":1,"hwkey-app":1,"command-line":1,"offers":1,"uses":1,"hwkey-agent":1,"typically":1}
,"runs":{"within":1,"environment":1,"secure":1,"software":1,"openssl":1}
,"within":{"trusty":1}
,"secure":{"environment":1,"boot":1,"mode":1,"world":1,"secure":1,"operations":1,"operation":1,"storage":1,"keys":1,"key":1,"manner":1,"samples":1,"sample":1,"techniques":1,"enough":1,"random":1}
,"provided":{"trusty":1,"l4t":1,"hwkey-agent":1}
,"running":{"trusted":1,"software":1,"non-secure":1,"normal":1}
,"tos":{"trusted":1,"image":1,"hardware-based":1}
,"used":{"l4t":1,"discuss":1,"encrypting":1,"kek2":1,"encrypt":1,"ekb_ek":1,"derive":1,"authenticate":1,"ekb":1,"directly":1,"generate":1,"verify":1,"hwkey-agent":1,"flash":1,"two":1}
,"resides":{"separate":1}
,"separate":{"storage":1,"environment":1,"128\u2011bit":1,"128-bit":1}
,"storage":{"partition":1,"area":1,"keyslots":1,"derived":1}
,"partition":{"boots":1,"default":1,"size":1,"device":1}
,"boots":{"part":1}
,"chain":{"trust":1}
,"trust":{"secure":1,"tee":1}
,"boot":{"sequence":1,"bootrom":1,"via":1,"flow":1,"visible":1,"inside":1,"using":1,"may":1,"booting":1,"time":1,"stage":1,"requirements":1,"configuration":1}
,"sequence":{"creates":1,"operations":1}
,"creates":{"two":1,"uuid":1,"rng-srv":1}
,"two":{"environments":1,"tas":1,"additional":1,"secure":1,"different":1,"options":1,"major":1,"keys":1,"steps":1,"fvs":1,"reference":1,"128\u2011bit":1,"apis":1}
,"environments":{"device":1}
,"different":{"security":1,"types":1,"ways":1,"purposes":1,"keys":1,"files":1}
,"non-secure":{"environment":1,"mode":1}
,"nse":{"environment":1}
,"mode":{"mode":1,"known":1,"enforced":1,"kdf":1}
,"known":{"normal":1,"secure":1}
,"normal":{"world":1,"secure":1}
,"world":{"rich":1,"trusty":1,"initiates":1,"protocol":1,"ekb":1,"plaintext":1,"request":1}
,"rich":{"linux":1}
,"typically":{"runs":1,"multiple":1}
,"operations":{"runs":1,"initiated":1,"flags":1,"behind":1,"case":1,"user-defined":1,"ssk":1,"nist-sp-800-108":1,"creating":1,"extracting":1}
,"enforced":{"hardware":1}
,"hardware":{"mode":1,"registers":1,"security":1,"random":1,"key":1,"kdf":1}
,"operate":{"client-server":1}
,"client-server":{"relationship":1}
,"relationship":{"trusty":1}
,"bootloader":{"allocates":1,"stage":1,"match":1}
,"allocates":{"dedicated":1}
,"dedicated":{"carveout":1}
,"carveout":{"tz-dram":1}
,"tz-dram":{"run":1}
,"run":{"secure":1,"trusty\u0027s":1,"ekb":1}
,"initiated":{"client":1}
,"initiates":{"contact":1}
,"contact":{"non-secure":1}
,"diagram":{"shows":1,"illustrates":1,"below":1,"describes":1,"description":1}
,"shows":{"relationships":1,"process":1,"overview":1,"logical":1,"run":1,"architecture":1,"flow":1}
,"relationships":{"among":1}
,"among":{"components":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1}
,"automatically":{"generated":1}
,"perform":{"secure":1,"direct":1,"steps":1,"cryptographic":1,"ekb":1}
,"operation":{"sends":1}
,"sends":{"request":1}
,"request":{"trusted":1,"trusty":1,"arm":1,"mappings":1,"parameters":1,"random":1}
,"calling":{"functions":1}
,"functions":{"trusty":1,"mmap":1,"declared":1,"prepare_dma":1,"often":1,"similar":1,"details":1,"implement":1}
,"libraries":{"routes":1}
,"routes":{"request":1,"client":1}
,"firmware":{"atf":1}
,"monitor":{"routes":1,"implementation":1}
,"implementation":{"based":1,"hardware-based":1}
,"arm-software":{"arm-trusted-firmware":1}
,"framework":{"determines":1,"passes":1,"developed":1}
,"determines":{"trusted":1,"direction":1,"bootrom":1}
,"handle":{"request":1,"different":1}
,"passes":{"control":1,"encrypted":1}
,"control":{"handle":1,"returns":1,"actual":1}
,"upon":{"completion":1}
,"completion":{"execution":1}
,"returns":{"along":1,"random":1}
,"along":{"reverse":1}
,"reverse":{"path":1,"process":1}
,"path":{"client":1,"makefile":1}
,"receives":{"return":1}
,"return":{"value":1,"requested":1,"random":1,"2048":1}
,"value":{"processed":1,"part":1,"less":1,"step":1,"kek2_dk":1,"odmfuse.sh":1}
,"processed":{"data":1}
,"section":{"gives":1,"accessible":1,"describes":1,"encrypted":1,"sign":1,"signing":1}
,"gives":{"instructions":1}
,"instructions":{"developing":1}
,"developing":{"trusted":1}
,"applications":{"tas":1,"running":1,"helps":1,"demonstrate":1,"counter":1,"require":1,"ekb":1,"store":1,"either":1}
,"tas":{"run":1,"default":1,"constitute":1,"aosp":1,"located":1,"combined":1,"defined":1,"applications":1,"inside":1,"communicate":1}
,"trusty\u0027s":{"trusted":1}
,"default":{"trusted":1,"tas":1,"0xbad66eb4484983684b992fe54a648bb8":1,"enable":1,"ssk":1,"value":1}
,"three":{"tas":1}
,"sample":{"ipc-unittest":1,"skel":1,"applications":1,"programs":1,"implemented":1,"uses":1,"function":1}
,"ipc-unittest":{"main":1,"srv":1}
,"nvidia-sample":{"hwkey-agent":1}
,"first":{"two":1}
,"constitute":{"functional":1}
,"functional":{"testing":1,"areas":1}
,"testing":{"framework":1}
,"developed":{"part":1,"nvidia":1}
,"third":{"developed":1}
,"serve":{"reference":1}
,"reference":{"implementing":1,"device":1,"may":1,"implementations":1,"implementation":1}
,"implementing":{"hardware-backed":1}
,"hardware-backed":{"encrypted":1,"key":1,"kek2":1}
,"encrypted":{"keyblobs":1,"blob":1,"content":1,"keyblob":1,"ekb":1,"keys":1,"128-bit":1,"key":1,"ciphertext":1,"user-defined":1,"binary":1}
,"keyblobs":{"jetson":1}
,"burns":{"aes":1}
,"aes":{"keys":1,"key":1,"ecb":1,"128":1}
,"keys":{"fuses":1,"encrypted":1,"encrypt":1,"usually":1,"confidential":1,"unauthorized":1,"fuse":1,"keyslots":1,"keys":1,"often":1,"similar":1,"extracts":1,"user-defined":1,"hardware-based":1,"using":1,"ekb":1,"loaded":1,"nvidia":1,"different":1,"derived":1,"explains":1,"topic":1,"key":1,"odm":1,"option":1}
,"fuses":{"kek":1,"fuse":1,"including":1,"kek0":1,"single":1,"related":1,"two":1}
,"kek":{"sbk":1,"fuses":1,"fuse":1}
,"sbk":{"device":1,"pkc":1}
,"provisioned":{"encrypted":1,"device":1}
,"blob":{"containing":1,"holds":1,"sample":1,"ekb":1,"refer":1,"file":1}
,"containing":{"keys":1,"plaintext":1}
,"additional":{"tas":1,"keys":1,"sets":1}
,"packaged":{"trusty":1}
,"disabled":{"default":1}
,"located":{"trusty_top":1}
,"trusty_top":{"trusty":1,"root":1}
,"app":{"directory":1,"e.g":1,"my_trusted_app":1,"sample":1,"note":1,"nvidia-sample":1}
,"directory":{"trusty_top":1,"trusty":1,"holds":1,"inside":1,"linux_for_tegra_folder":1}
,"root":{"directory":1,"key":1,"keys":1}
,"manifests":{"trusted":1}
,"corresponding":{"manifest":1}
,"manifest":{"specifies":1,"data":1,"defined":1,"specify":1,"file":1}
,"specifies":{"ta\u2019s":1,"ta\u0027s":1}
,"ta\u2019s":{"configuration":1,"memory":1}
,"configuration":{"properties":1,"options":1,"table":1,"file":1}
,"properties":{"manifest":1}
,"typedef":{"struct":1}
,"uuid_t":{"uuid":1}
,"uuid":{"uuid":1,"unique":1,"generator":1,"defined":1}
,"unique":{"identifier":1,"mapping":1,"jetson":1}
,"uint32_t":{"config_options":1,"size":1,"flags":1,"handle":1,"rng_size":1}
,"lib":{"include":1}
,"include":{"trusty_app_manifest.h":1,"mm.h":1,"paths":1}
,"holds":{"trusty":1,"developer-defined":1,"key":1}
,"specify":{"configurations":1,"address":1,"unique":1}
,"configurations":{"stack":1}
,"stack":{"size":1,"heap":1}
,"size":{"heap":1,"map":1,"uint32_t":1,"restrictions":1,"ekb":1,"range":1}
,"heap":{"size":1,"sizes":1}
,"map":{"mmio":1,"registers":1,"address":1}
,"mmio":{"address":1,"regions":1}
,"address":{"uuid":1,"space":1,"regions":1,"load":1}
,"generator":{"https":1,"nvidia":1,"function":1,"rng":1}
,"www.uuidgenerator.net":{"creates":1}
,"example":{"manifest":1,"file":1,"makefile":1,"adding":1,"shows":1,"perform":1}
,"trusty_app_manifest_t":{"trusty_app_manifest_attrs":1}
,"trusty_app_manifest_attrs":{"trusty_app_manifest":1}
,".uuid":{"service_sample_uuid":1}
,"optional":{"configuration":1}
,"pages":{"heap":1,"stack":1}
,"trusty_app_config_min_heap_size":{"4096":1}
,"trusty_app_config_min_stack_size":{"4096":1}
,"tegra_device_addr":{"tegra_device_addr_len":1}
,"accessing":{"mmio":1}
,"access":{"hardware":1,"operations":1,"dma":1}
,"registers":{"trusted":1,"mmio":1,"named":1}
,"regions":{"address":1,"manifest":1}
,"mapping":{"manifest":1}
,"system":{"functions":1,"crash":1}
,"mmap":{"munmap":1,"void":1}
,"munmap":{"map":1,"void":1}
,"declared":{"trusty_calls.h":1,"trusty_syscalls.h":1}
,"long":{"mmap":1,"munmap":1,"prepare_dma":1,"finish_dma":1,"little":1,"contain":1,"may":1}
,"void":{"uaddr":1,"pmem":1}
,"uaddr":{"uint32_t":1}
,"flags":{"uint32_t":1,"argument":1,"defined":1,"void":1}
,"direct":{"memory":1}
,"memory":{"access":1,"memory":1,"region":1}
,"prepare_dma":{"finish_dma":1,"void":1}
,"finish_dma":{"perform":1,"void":1}
,"dma":{"operations":1,"cache":1}
,"argument":{"determines":1}
,"direction":{"dma":1}
,"cache":{"operations":1}
,"values":{"flags":1,"shown":1}
,"implement":{"new":1,"counter-mode":1}
,"new":{"trusted":1,"application":1,"ekb":1}
,"place":{"trusted":1}
,"files":{"new":1,"my_trusted_app":1,"include":1,"topic":1}
,"inside":{"trusty_top":1,"jetson":1,"trusty":1,"tzdram":1}
,"e.g":{"trusty_top":1}
,"create":{"manifest":1,"makefile":1}
,"assign":{"uuid":1}
,"defined":{"described":1,"trusty_all_user_tasks":1,"nist-sp":1}
,"described":{"manifests":1,"android":1,"section":1,"nist-sp-800-108":1}
,"update":{"mappings":1}
,"mappings":{"needed":1}
,"needed":{"optional":1}
,"declare":{"minimum":1}
,"minimum":{"stack":1}
,"sizes":{"optional":1}
,"add":{"source":1,"path":1,"line":1,"additional":1}
,"my_trusted_app":{"directory":1}
,"skel":{"skel_app.c":1,"rules.mk":1}
,"makefile":{"rules.mk":1,"list":1}
,"rules.mk":{"specifies":1}
,"ta\u0027s":{"source":1,"heap":1}
,"paths":{"module":1}
,"module":{"dependencies":1}
,"list":{"user":1}
,"user":{"tasks":1,"data":1,"two":1,"key":1,"sbk":1}
,"tasks":{"trusty_all_user_tasks":1}
,"trusty_all_user_tasks":{"located":1,"path_to_app":1,"lk.bin":1}
,"t186":{"project":1}
,"path_to_app":{"pathname":1}
,"pathname":{"relative":1}
,"relative":{"directory":1}
,"rebuild":{"trusty":1}
,"combined":{"build":1}
,"build":{"rebuilding":1}
,"rebuilding":{"trusty":1}
,"rebuilds":{"tas":1}
,"protect":{"integrity":1,"secure":1,"private":1}
,"integrity":{"confidentiality":1}
,"confidentiality":{"trusted":1}
,"binary":{"nvidia":1,".img":1,"often":1,"flashed":1,"starting":1,"bytes":1,"zero":1,"size":1,"least":1,"length":1,"random":1,"discards":1,"jetson":1,"files":1,"blob":1}
,"strongly":{"recommends":1}
,"recommends":{"secureboot":1,"kdf":1,"bytes":1,"padding":1,"ekb":1,"key":1,"se_clear_aes_keyslots":1,"using":1,"layout":1}
,"secureboot":{"encrypt":1,"topic":1,"jetson":1}
,"encrypt":{"sign":1,"decrypt":1,"ekb":1,"key":1,"custom-built":1}
,"sign":{"tos":1,"flash":1}
,"communicate":{"applications":1,"tas":1,"acquire":1}
,"tipc":{"protocol":1}
,"protocol":{"communicate":1,"described":1}
,"documentation":{"trust":1}
,"api":{"reference":1,"functions":1}
,"may":{"found":1,"exceed":1,"cause":1}
,"key":{"derivation":1,"user-defined":1,"128-bit":1,"burned":1,"visible":1,"called":1,"kek2_rk":1,"derived":1,"used":1,"kek2_dk":1,"generation":1,"kek2_dks":1,"ekb_ek":1,"device\u0027s":1,"persist":1,"wiped":1,"ekb":1,"secure":1,"ssk-derived":1,"ssk":1,"unique":1,"bound":1,"device":1,"perform":1,"trusted":1,"stored":1,"management":1,"uses":1,"maintenance":1,"ssk_dk":1,"default":1,"looks":1,"further":1,"count":1,"plaintext":1,"ekb_ak":1,"command":1,"user":1,"encrypt":1,"data":1,"source":1,"key":1,"disk":1,"password":1,"encryption":1,"odm":1,"slot":1,"provision":1,"definition":1}
,"derivation":{"function":1,"key":1,"odm":1}
,"function":{"fuse":1,"kdf":1,"provided":1,"clears":1,"prf":1,"named":1,"return":1,"trusty":1}
,"fuse":{"key":1,"storage":1,"information":1,"specification":1,"keys":1,"secure":1,"used":1,"shown":1,"addresses":1,"kdf":1}
,"user-defined":{"key":1}
,"often":{"need":1,"provisioned":1,"called":1}
,"need":{"different":1,"kek2":1,"secure":1,"random":1}
,"types":{"keys":1,"sensitive":1}
,"decrypt":{"data":1,"ekbs":1,"ekb":1}
,"usually":{"confidential":1}
,"confidential":{"sensitive":1,"data":1}
,"sensitive":{"compromising":1,"user":1}
,"compromising":{"serious":1}
,"serious":{"consequences":1}
,"consequences":{"trusty":1}
,"keyblob":{"ekb":1,"encrypted":1,"overview":1,"format":1,"structure":1,"generation":1,"decryption":1}
,"ekb":{"mechanism":1,"feature":1,"eks":1,"encryption":1,"authentication":1,"contents":1,"accomplish":1,"content":1,"format":1,"binary":1,"header":1,"blob\u2019s":1,"binary\u2019s":1,"generation":1,"decryption":1,"derives":1,"openssl":1,"using":1,"ssk-derived":1,"holds":1,"ciphertext":1,"adding":1,"layout":1,"modified":1,"kek2":1,"blob":1,"easily":1,"plain":1,"extraction":1,"essentially":1,"match":1,"plaintext":1,"file":1}
,"mechanism":{"provision":1,"secure":1}
,"provision":{"keys":1,"source":1}
,"several":{"specialized":1,"keyslots":1}
,"specialized":{"terms":1}
,"discuss":{"ekb":1}
,"eks":{"encrypted":1,"partition":1}
,"developer-defined":{"content":1}
,"keyslot":{"secure":1,"key":1,"clearing":1,"longer":1,"nvidia":1,"prevent":1,"cleared":1,"hardware":1,"using":1,"derives":1,"demonstrates":1,"enable":1,"fv_for_ekb":1,"fv_for_ssk_dk":1}
,"area":{"inside":1}
,"engine":{"protect":1,"derive":1,".the":1,"rng1":1,"keyslot":1}
,"unauthorized":{"reading":1}
,"reading":{"writing":1}
,"writing":{"during":1}
,"during":{"early":1,"boot":1,"device":1,"initialization":1}
,"early":{"boot":1}
,"bootrom":{"loads":1,"boot":1,"identifies":1}
,"loads":{"secure":1,"kek0":1,"fuses":1,"bct":1}
,"keyslots":{"later":1,"cleared":1,"security":1,"during":1,"derive":1,"aes-ecb":1}
,"later":{"trusty":1,"section":1}
,"derive":{"keys":1,"key":1,"kek2_dk":1,"kek2_rk":1,"ssk_dk":1,"derived":1,"multiple":1,"ekb":1,"kek2":1}
,"kek2":{"fuse":1,"root":1,"keyslot":1,"derived":1,"ekb":1}
,"128-bit":{"aes":1,"symmetric":1,"input":1,"output":1,"keys":1}
,"burned":{"kek2":1,"device\u2019s":1}
,"visible":{"software":1,"secure":1,"plaintext":1,"normal":1}
,"utilizes":{"during":1,"ekb":1}
,"via":{"security":1}
,"called":{"kek2":1,"eks.img":1,"ekb_ek":1,"root":1}
,"kek2_rk":{"128-bit":1,"trusty":1,"key":1,"using":1,"aes":1,"formula":1,"derived":1}
,"derived":{"kek2":1,"key":1,"kek2_rk":1,"hardware-backed":1,"keyslot":1,"formulas":1,"keys":1}
,"encrypting":{"user":1,"kernel":1}
,"kek2_dk":{"128-bit":1,"value":1,"used":1,"called":1,"kek2":1}
,"kdf":{"follows":1,"secure":1,"recommendation":1,"fuse":1,"described":1,"used":1,"generation":1,"derive":1,"generates":1,"defined":1}
,"follows":{"nist-sp-800-108":1}
,"nist-sp-800-108":{"derive":1,"kdf":1,"cmac":1,"kek2_rk_for_ekb":1,"ssk_rk":1,"context_string":1}
,"generation":{"application":1,"device":1,"process":1,"support":1,"fuse":1,"exercise":1,"tool":1,"luks":1,"network":1}
,"ways":{"generate":1}
,"generate":{"case":1,"ekb":1,"128-bit":1,"random":1,"new":1,"fixed":1,"items":1}
,"ekb_ek":{"ekb":1,"derived":1,"using":1,"following":1,"kek2_rk":1,"software":1,"nist-sp-800-108":1,"ekb_ciphertext":1}
,"encryption":{"key":1,"trusty":1,"according":1,"decryption":1,"reference":1}
,"kek2_dks":{"used":1}
,"ekb_ak":{"ekb":1,"authenticate":1,"nist-sp-800-108":1,"ekb_content":1}
,"authentication":{"key":1,"code":1,"succeeds":1}
,"fixed":{"vector":1,"16-byte":1}
,"vector":{"fixed":1,"constant":1,"used":1,"user-defined":1,"deriving":1}
,"16-byte":{"value":1,"ekb":1,"random":1}
,"mb2":{"bootloader":1,"trusted":1}
,"stage":{"passes":1,"trusty":1}
,"contents":{"trusted":1,"ta\u0027s":1}
,"flow":{"executes":1,"diagram":1,"kdf":1,"aes-256":1,"key":1}
,"executes":{"mb2":1}
,"cleared":{"immediately":1,"during":1}
,"immediately":{"trusty":1}
,"common":{"case":1}
,"case":{"trusted":1,"key":1}
,"managing":{"secret":1}
,"secret":{"keys":1}
,"manner":{"accessible":1}
,"accessible":{"trusted":1,"trusty":1}
,"accomplish":{"ekb":1}
,"content":{"visible":1,"ciphertext":1,"completely":1,"section":1,"pad":1,"encrypted":1,"generate":1,"plaintext":1,"ekb_ek":1,"random_iv":1,"encryption":1}
,"plaintext":{"secure":1,"ekb_ek":1,"native":1,"desired":1,"encrypted":1}
,"format":{"designed":1,"value":1,"ekb":1,"resulting":1}
,"generic":{"possible":1}
,"possible":{"giving":1}
,"giving":{"full":1}
,"full":{"control":1}
,"actual":{"keyblob":1}
,"structure":{"ekb":1}
,".img":{"file":1}
,"file":{"16-byte":1,"fully":1,"generated":1,"ekb":1,"intended":1,"$trusty_top":1,"stored":1}
,"header":{"prefixed":1,"bytes":1,"information":1,"ekb":1,"16\u2011byte":1,"ekb_cmac":1}
,"prefixed":{"ekb":1}
,"blob\u2019s":{"contents":1}
,"eks.img":{"name":1}
,"name":{"ekb":1}
,"flashed":{"eks":1,"onto":1}
,"consumed":{"mb2":1}
,"match":{"following":1,"proceed":1}
,"ekb_size":{"bytes":1,"length":1,"four":1}
,"magic":{"bytes":1,"field":1,"eight":1}
,"length":{"ekb":1,"least":1,"random":1,"need":1}
,"starting":{"magic":1}
,"field":{"ekb_size":1}
,"four":{"bytes":1,"unused":1,"32\u2011bit":1}
,"bytes":{"long":1,"nvidia":1,"binary":1,"need":1}
,"endian":{"format":1}
,"less":{"length":1}
,"eight":{"bytes":1}
,"contain":{"exact":1}
,"exact":{"string":1}
,"string":{"nvekbp":1}
,"contains":{"four":1}
,"unused":{"bytes":1}
,"completely":{"implementation-defined":1}
,"implementation-defined":{"restrictions":1}
,"restrictions":{"although":1}
,"although":{"intended":1}
,"intended":{"hold":1,"help":1,"flashed":1}
,"hold":{"encrypted":1}
,"similar":{"data":1,"openssl":1}
,"reasons":{"ekb":1}
,"least":{"1024":1}
,"1024":{"bytes":1}
,"exceed":{"eks":1}
,"binary\u2019s":{"size":1}
,"range":{"flashing":1,"results":1}
,"flashing":{"fails":1}
,"pad":{"ekb":1}
,"padding":{"binary":1}
,"random":{"data":1,"initial":1,"number":1,"dev":1,"blocks":1,"uniformly":1,"numbers":1}
,"decrypts":{"entire":1,"ekb":1}
,"entire":{"binary":1}
,"discards":{"padding":1}
,"symmetric":{"key":1,"kek2":1}
,"device\u2019s":{"kek2":1}
,"describes":{"operations":1,"scenarios":1,"flow":1}
,"behind":{"formula":1}
,"formula":{"detail":1}
,"define":{"format":1,"rng_srv_data_size":1}
,"burn":{"kek2":1,"kek0":1,"single":1}
,"device\u0027s":{"kek2":1,"eks":1}
,"specification":{"app":1}
,"note":{"jetson":1,"fvs":1}
,"change":{"fixed":1}
,"constant":{"randomly":1}
,"randomly":{"generated":1}
,"generated":{"value":1,"ekb":1,"encrypted":1}
,"step":{"required":1,"using":1}
,"required":{"nvidia":1}
,"compute":{"kek2_rk":1,"ekb_content":1,"ekb_cmac":1,"cmac":1,"ekb":1}
,"using":{"aes":1,"desired":1,"chosen":1,"trusty":1,"openssl":1,"tegra-crypto":1,"different":1,"kdf":1,"dev":1,"user":1}
,"ecb":{"encryption":1,"kek2":1}
,"according":{"formula":1}
,"128":{"ecb":1,"count":1,"bit":1}
,"follow":{"nist-sp-800-108":1}
,"recommendation":{"derive":1}
,"desired":{"crypto":1,"within":1}
,"crypto":{"algorithm":1,"library":1,"operations":1}
,"algorithm":{"obtain":1,"used":1,"derivation":1}
,"obtain":{"ekb":1,"plaintext":1}
,"append":{"ekb":1}
,"ciphertext":{"described":1,"ta\u2019s":1,"decrypted":1,"bytes":1,"encrypted":1,"fields":1,"aes-128-cbc":1}
,"resulting":{"file":1}
,"fully":{"generated":1}
,"flash":{"ekb":1,"command":1,"step":1}
,"illustrates":{"ekb":1,"encrypt":1}
,"performs":{"following":1,"cryptographic":1,"key":1}
,"ensures":{"matches":1}
,"matches":{"used":1}
,"requests":{"security":1,"applications":1}
,"derives":{"kek2_dk":1,"ekb_ek":1,"key":1,"ssk-derived":1}
,"maps":{"ekb":1}
,"region":{"inside":1}
,"tzdram":{"aperture":1}
,"aperture":{"copy":1}
,"copy":{"contents":1}
,"chosen":{"crypto":1}
,"native":{"crypto":1}
,"library":{"trusty":1,"perform":1}
,"choose":{"import":1}
,"import":{"crypto":1}
,"process":{"ekb":1}
,"longer":{"need":1,"query":1}
,"persist":{"keyslot":1}
,"wiped":{"keyslot":1}
,"prevent":{"component":1}
,"component":{"utilizing":1}
,"utilizing":{"device":1}
,"hwkey-agent":{"demonstrates":1,"function":1,"derive":1,"hwkey-app":1,"trusted":1,"creates":1,"ca_sample":1}
,"demonstrates":{"keyslot":1,"derive":1}
,"clearing":{"procedure":1}
,"procedure":{"nvidia":1,"derive":1}
,"se_clear_aes_keyslots":{"function":1}
,"clears":{"several":1}
,"cause":{"system":1}
,"crash":{"guarantee":1}
,"guarantee":{"clocks":1}
,"clocks":{"enabled":1}
,"enabled":{"means":1}
,"means":{"ekb_ek":1}
,"utilize":{"ekb_ek":1}
,"below":{"shows":1}
,"overview":{"two":1}
,"helps":{"users":1}
,"users":{"encrypt":1}
,"extracts":{"user-defined":1}
,"ssk-derived":{"key":1}
,"ssk":{"keyslot":1,"ssk":1}
,"once":{"data":1}
,"bound":{"device":1}
,"contrast":{"user-defined":1}
,"decide":{"key":1}
,"cryptographic":{"operations":1,"services":1,"processes":1}
,"scenarios":{"apply":1}
,"apply":{"secure":1}
,"command-line":{"program":1}
,"program":{"illustrates":1}
,"offers":{"user":1}
,"stored":{"ekb":1,"kek2":1,"directory":1}
,"openssl":{"library":1,"rand":1,"tool":1,"cmac":1}
,".the":{"application":1}
,"tegra-crypto":{"library":1}
,"option":{"disabled":1,"--kek256":1}
,"enable":{"manually":1}
,"major":{"functional":1}
,"openssl_crypto":{"performs":1,"provides":1}
,"tegra_se_crypto":{"performs":1}
,"background":{"service":1}
,"service":{"started":1,"tas":1,"model":1,"ipc":1}
,"started":{"boot":1}
,"time":{"performs":1}
,"management":{"two":1}
,"services":{"openssl":1}
,"maintenance":{"user-defined":1,"ekbs":1}
,"ssk_dk":{"ssk":1,"needs":1,"nist-sp-800-108":1}
,"purposes":{"procedure":1,"securing":1,"using":1}
,"interface":{"receive":1}
,"receive":{"ipc":1,"return":1}
,"ipc":{"request":1,"channel":1,"packet\u2019s":1}
,"parameters":{"specify":1}
,"whether":{"encrypt":1}
,"buffer":{"containing":1}
,"important":{"purpose":1}
,"purpose":{"sample":1}
,"demonstrate":{"secure":1}
,"techniques":{"deriving":1}
,"deriving":{"keys":1,"kek2":1}
,"hardware-based":{"fuse":1,"random":1,"key":1,"nist-sp":1,"aes-cmac":1}
,"securing":{"user-defined":1}
,"ekb_header":{"bytes":1}
,"ekb_cmac":{"bytes":1,"authentication":1,"random_iv":1,"aes-cmac":1,"ekb_content":1,"key":1}
,"random_iv":{"bytes":1,"ekb":1,"random":1,"key":1,"initial":1,"ekb_ciphertext":1}
,"fields":{"ekb":1,"extending":1}
,"16\u2011byte":{"ekb":1}
,"aes-cmac":{"algorithm":1,"key":1,"functions":1}
,"authenticate":{"ekb":1}
,"initial":{"vector":1}
,"adding":{"additional":1,"multiple":1}
,"sets":{"ekb_cmac":1}
,"extending":{"script":1}
,"script":{"tool":1,"options":1}
,"tool":{"ekb":1,"generate":1,"output":1}
,"support":{"additional":1}
,"layout":{"looks":1,"intended":1,"example":1,"sample":1}
,"ekb_cmac_1":{"bytes":1}
,"random_iv_1":{"bytes":1}
,"ekb_cmac_2":{"bytes":1}
,"random_iv_2":{"bytes":1}
,"ekb_cmac_n":{"bytes":1}
,"random_iv_":{"bytes":1}
,"succeeds":{"confirming":1}
,"confirming":{"ekb":1}
,"modified":{"decrypt":1}
,"loaded":{"keyslots":1}
,"cannot":{"read":1}
,"read":{"back":1}
,"back":{"keyslots":1}
,"aes-ecb":{"algorithm":1}
,"directly":{"crypto":1}
,"further":{"crypto":1}
,"thus":{"two":1}
,"steps":{"getting":1}
,"getting":{"fuse":1}
,"aes-ecb-128":{"fuse":1}
,"counter":{"mode":1}
,"cmac":{"pseudo-random":1,"cmac":1,"ekb":1,"implementation":1}
,"pseudo-random":{"function":1}
,"production":{"application":1}
,"multiple":{"cases":1,"keys":1,"sections":1,"times":1}
,"cases":{"need":1}
,"outline":{"describes":1,"shows":1}
,"number":{"generator":1,"displays":1,"source":1,"requests":1,"generation":1}
,"dev":{"random":1,"urandom":1}
,"command":{"generates":1,"line":1,"section":1}
,"generates":{"16-byte":1,"numbers":1,"derived":1}
,"displays":{"hexadecimal":1}
,"rand":{"-rand":1}
,"-rand":{"dev":1}
,"urandom":{"-hex":1,"block":1}
,"-hex":{"iv_hex_file":1}
,"require":{"two":1}
,"fv_for_ekb":{"used":1}
,"fv_for_ssk_dk":{"used":1}
,"rks":{"root":1}
,"kek2_rk_for_ekb":{"aes-128-ecb":1}
,"aes-128-ecb":{"kek2":1,"ssk":1}
,"ssk_rk":{"aes-128-ecb":1}
,"dks":{"derived":1}
,"pseudocode":{"nist-sp-800-108":1}
,"context_string":{"label_string":1,"output":1}
,"uint8_t":{"count":1,"rng_data":1}
,"count":{"0x01":1,"128":1,"label_string":1}
,"0x01":{"count":1}
,"aes-128-cmac":{"key":1}
,"label_string":{"0x00":1,"values":1}
,"0x00":{"context_string":1}
,"output":{"&ko":1,"key":1,"binary":1}
,"&ko":{"count":1}
,"input":{"key":1}
,"bit":{"length":1,"size":1}
,"shown":{"table":1,"figure":1}
,"figure":{"key":1}
,"ekbs":{"sample":1}
,"design":{"mechanism":1}
,"enough":{"protect":1,"entropic":1}
,"private":{"data":1}
,"store":{"user-defined":1,"different":1}
,"easily":{"extend":1}
,"extend":{"ekb":1}
,"programs":{"replace":1}
,"replace":{"know":1}
,"know":{"even":1}
,"even":{"secure":1}
,"logical":{"sequence":1}
,"creating":{"ekb":1}
,"aes-128-cbc":{"random_iv":1}
,"plain":{"text":1}
,"text":{"user-defined":1}
,"verify":{"message":1}
,"message":{"changed":1}
,"ekb_content":{"intermediate":1,"random_iv":1}
,"intermediate":{"result":1}
,"extracting":{"information":1}
,"essentially":{"reverse":1}
,"aes-cmac_verify":{"ekb_cmac":1}
,"compare":{"computed":1}
,"computed":{"cmac":1}
,"ekb_plaintext":{"aes-128-cbc_decrypt":1}
,"aes-128-cbc_decrypt":{"random_iv":1}
,"generating":{"ekb":1}
,"refer":{"secureboot":1}
,"burning":{"keys":1}
,"including":{"kek2":1}
,"requirements":{"using":1}
,"explains":{"generate":1}
,"line":{"runs":1}
,"items":{"separately":1}
,"separately":{"store":1}
,"fvs":{"ekb":1,"confidential":1}
,"extraction":{"ekb":1,"sample":1,"source":1}
,"exercise":{"due":1}
,"due":{"caution":1}
,"caution":{"keep":1}
,"keep":{"fvs":1}
,"python3":{"gen_ekb.py":1}
,"gen_ekb.py":{"-kek2_key":1}
,"-kek2_key":{"kek2_fuse_key_file":1}
,"-fv":{"fv_for_ekb_ek":1}
,"-in_sym_key":{"sym_key_file":1}
,"-in":{"sym_key2":1}
,"sym_key2":{"sym2_key_file":1}
,"-out":{"eks_image_file":1}
,"kek2_fuse_key_file":{"key":1}
,"fv_for_ekb_ek":{"fixed":1}
,"sym_key_file":{"kernel":1}
,"pkc":{"keys":1}
,"custom-built":{"kernel":1}
,"images":{"section":1}
,"signing":{"encrypting":1}
,"kernel-dtb":{"initrd":1}
,"initrd":{"binary":1}
,"sym2_key_file":{"disk":1}
,"disk":{"encryption":1}
,"implementations":{"secure":1}
,"implemented":{"hwkey-agent":1}
,"hwkey-app":{"sample":1}
,"decryption":{"case":1}
,"luks":{"key":1}
,"eks_image_file":{"image":1}
,"image":{"file":1}
,"onto":{"eks":1}
,"password":{"generation":1}
,"network":{"protocols":1}
,"protocols":{"cryptographic":1}
,"processes":{"jetson":1}
,"processors":{"provides":1}
,"node":{"dev":1}
,"blocks":{"until":1}
,"until":{"kernel":1}
,"accumulated":{"enough":1}
,"entropic":{"data":1}
,"requested":{"amount":1}
,"amount":{"random":1}
,"alternative":{"source":1}
,"rng":{"compliant":1,"service":1,"random":1,"function":1,"ipc":1}
,"compliant":{"nist-sp":1}
,"nist-sp":{"800-90":1,"800-108":1}
,"800-90":{"draft":1}
,"draft":{"specifications":1}
,"specifications":{"reseed":1}
,"reseed":{"itself":1}
,"itself":{"generates":1}
,"numbers":{"truly":1,"extracted":1,"rng-srv":1,"hwkey-agent":1,"obtained":1,"numbers":1,"compliant":1,"rng":1,"longer":1}
,"truly":{"random":1}
,"uniformly":{"distributed":1}
,"distributed":{"range":1}
,"acquire":{"random":1}
,"architecture":{"trusty":1}
,"extracted":{"secure":1}
,"model":{"rng":1}
,"initialization":{"hwkey-agent":1}
,"rng-srv":{"service":1,"initializing":1,"uses":1}
,"channel":{"receive":1,"extract":1}
,"either":{"normal":1}
,"initializing":{"ipc":1}
,"extract":{"random":1}
,"named":{"get_random":1,"kek00":1,"kek10":1,"kek20":1}
,"get_random":{"returns":1}
,"obtained":{"source":1}
,"$trusty_top":{"app":1}
,"ca_sample":{"hwkey-app.c":1}
,"rng1":{"generate":1}
,"packet\u2019s":{"definition":1}
,"rng_srv_data_size":{"2048":1}
,"struct":{"rng_srv_msg":1}
,"rng_data":{"rng_srv_data_size":1}
,"maximum":{"length":1}
,"2048":{"bytes":1}
,"query":{"multiple":1}
,"times":{"concatenate":1}
,"concatenate":{"results":1}
,"results":{"length":1}
,"aes-256":{"hardware":1}
,"odm":{"kek":1}
,"load":{"odm":1}
,"kek0":{"kek1":1}
,"kek1":{"separate":1,"single":1,"security":1,"fuses":1}
,"128\u2011bit":{"fuses":1,"keys":1}
,"single":{"256\u2011bit":1,"256-bit":1}
,"256\u2011bit":{"fuse":1,"key":1}
,"related":{"secureboot":1}
,"32\u2011bit":{"registers":1}
,"kek00":{"kek03":1}
,"kek10":{"kek13":1}
,"distinct":{"fuse":1}
,"addresses":{"kek0":1}
,"kek20":{"kek23":1}
,"bctkekkeyselect":{"flag":1}
,"flag":{"bootrom":1,"example":1}
,"table":{"br-bct":1}
,"br-bct":{"determines":1}
,"bct":{"configuration":1,"hardware-based":1}
,"linux_for_tegra_folder":{"\u200Cbootloader":1}
,"\u200Cbootloader":{"\u200Ct186ref":1}
,"\u200Ct186ref":{"\u200Cbct":1}
,"\u200Cbct":{"file\u2019s":1}
,"file\u2019s":{"name":1}
,"identifies":{"key":1}
,"setting":{"bct":1}
,"800-108":{"kdf":1,"key":1,"nist":1}
,"odmfuse.sh":{"script":1}
,"options":{"--kek0":1}
,"--kek0":{"--kek1":1}
,"--kek1":{"burn":1}
,"--kek256":{"burn":1}
,"256-bit":{"key":1}
,"supports":{"two":1}
,"apis":{"hardware-based":1}
,"nist":{"800-108":1}
,"definition":{"functions":1}
,"counter-mode":{"kdf":1}
}
;Search.control.loadWordPairs(pairs);
