var pairs =
{
"window":{"systems":1,"system":1}
,"topic":{"describes":1}
,"describes":{"window":1}
,"systems":{"supported":1}
,"supported":{"l4t":1}
,"gnome":{"standard":1,"wayland":1}
,"standard":{"ubuntu":1,"implementation":1}
,"ubuntu":{"window":1}
,"system":{"default":1,"nvidia":1,"known":1,"jetson":1}
,"default":{"window":1}
,"nvidia":{"jetson":1}
,"jetson":{"platforms":1,"nano":1}
,"wayland":{"newer":1}
,"newer":{"server":1}
,"server":{"communication":1,"standard":1}
,"communication":{"protocol":1}
,"protocol":{"designed":1}
,"designed":{"replacement":1}
,"replacement":{"window":1}
,"implementation":{"window":1}
,"known":{"x11":1}
,"ldxe":{"lightweight":1}
,"lightweight":{"x11":1}
,"x11":{"window":1}
}
;Search.control.loadWordPairs(pairs);
