var pairs =
{
"lightweight":{"x11":1}
,"x11":{"display":1}
,"display":{"environment":1}
,"environment":{"lxde":1}
,"lxde":{"x11-based":1,"instead":1,"compton":1}
,"x11-based":{"window":1}
,"window":{"system":1}
,"system":{"designed":1,"jetson":1}
,"designed":{"fewer":1}
,"fewer":{"resources":1}
,"resources":{"gnome":1,"supported":1}
,"gnome":{"making":1,"may":1}
,"making":{"popular":1}
,"popular":{"systems":1}
,"systems":{"limited":1}
,"limited":{"resources":1}
,"supported":{"nvidia":1}
,"nvidia":{"jetson":1}
,"jetson":{"platforms":1,"nano":1}
,"platforms":{"default":1}
,"default":{"window":1}
,"using":{"lxde":1}
,"instead":{"gnome":1}
,"may":{"reduce":1}
,"reduce":{"boot":1}
,"boot":{"time":1}
,"time":{"response":1,"memory":1}
,"response":{"time":1}
,"memory":{"consumption":1}
,"consumption":{"cpu":1}
,"cpu":{"utilization":1}
,"install":{"enable":1,"lxde":1}
,"enable":{"lxde":1}
,"enter":{"commands":1}
,"sudo":{"apt-get":1}
,"apt-get":{"update":1,"install":1}
,"create":{"configuration":1}
,"configuration":{"file":1}
,"file":{"xdg":1}
,"xdg":{"autostart":1}
,"autostart":{"lxde-compton.desktop":1}
,"lxde-compton.desktop":{"containing":1}
,"containing":{"commands":1}
,"desktop":{"entry":1}
,"type":{"application":1}
,"name":{"compton":1}
,"compton":{"compositor":1,"--backend":1}
,"genericname":{"compositor":1}
,"comment":{"compositor":1}
,"tryexec":{"compton":1}
,"exec":{"compton":1}
,"--backend":{"glx":1}
,"onlyshowin":{"lxde":1}
}
;Search.control.loadWordPairs(pairs);
