var pairs =
{
"window":{"system":1,"enter":1}
,"system":{"provides":1,"supported":1,"documentation":1,"display":1,"\u2011\u2011output":1,"support":1}
,"provides":{"windowing":1,"several":1,"utilities":1,"help":1,"guidance":1,"basic":1}
,"windowing":{"graphic":1}
,"graphic":{"display":1,"user":1}
,"display":{"device":1,"configuration":1,"properties":1,"implement":1,"upon":1,"x11":1,"select":1,"enablement":1,"identification":1,"lists":1,"may":1,"invalid":1,"correct":1,"custom":1,"second":1,"mode":1,"specify":1,"whose":1,"appears":1,"screen":1,"right":1,"configure":1,"size":1,"itself":1,"behind":1,"multi-display":1,"done":1}
,"device":{"management":1,"section":1}
,"management":{"services":1}
,"services":{"graphic":1}
,"user":{"interface":1}
,"interface":{"gui":1}
,"gui":{"applications":1}
,"applications":{"run":1}
,"run":{"linux":1,"default":1}
,"linux":{"server":1}
,"server":{"standard":1,"manually":1,"server":1,"starts":1,"enter":1,"provides":1,"utility":1,"running":1,"command-line":1,"configuration":1,"log":1,"layout":1,"screen":1,"current":1}
,"standard":{"implementation":1,"server":1}
,"implementation":{"window":1}
,"supported":{"l4t":1,"displays":1,"options":1,"color":1}
,"official":{"window":1}
,"documentation":{"available":1,"page":1}
,"available":{"x.org":1,"modes":1,"options":1}
,"x.org":{"foundation\u2019s":1,"documentation":1}
,"foundation\u2019s":{"x.org":1}
,"lightdm":{"gdm3":1}
,"gdm3":{"service":1}
,"service":{"currently":1}
,"currently":{"enabled":1}
,"enabled":{"default":1,"jetson":1,"driver":1,"displays":1,"display":1}
,"default":{"therefore":1,"ubuntu":1,"xorg.conf":1,"settings":1,"server":1,"configuration":1,"span":1,"x11":1,"detects":1,"255":1}
,"therefore":{"start":1}
,"start":{"server":1,"specified":1}
,"manually":{"differs":1,"run":1}
,"differs":{"previous":1}
,"previous":{"releases":1}
,"releases":{"either":1}
,"either":{"start":1}
,"ubuntu":{"root":1}
,"root":{"filesystem":1}
,"filesystem":{"started":1}
,"started":{"lightdm":1}
,"starting":{"server":1}
,"define":{"display":1,"server":1,"additional":1}
,"configuration":{"xorg.conf":1,"information":1,"run-time":1,"files":1,"optional":1,"tool":1,"based":1,"maps":1,"side-by-side":1,"changes":1,"file":1}
,"xorg.conf":{"starting":1,"xorg.conf.d":1,"installed":1,"contains":1,"file":1,"enter":1,"add":1}
,"starts":{"xrandr":1}
,"xrandr":{"runtime":1,"standard":1,"1.2":1,"command":1,"utility":1,"information":1,"--help":1,"commands":1,"--output":1,"specify":1,"--prop":1}
,"runtime":{"configuration":1,"xrandr":1,"manipulation":1}
,"information":{"using":1,"supported":1,"tool":1,"options":1,"troubleshoot":1,"enter":1}
,"using":{"xrandr":1,"nvidia-xconfig":1}
,"enter":{"command":1,"nvidia-xconfig":1,"commands":1}
,"sudo":{"-ac":1,"kill":1}
,"-ac":{"-noreset":1}
,"-noreset":{"-nolisten":1}
,"-nolisten":{"tcp":1}
,"command":{"line":1,"specifies":1,"xrandr":1}
,"line":{"arguments":1,"options":1,"utility":1}
,"arguments":{"may":1,"meant":1}
,"may":{"vary":1,"xrandr":1,"edit":1,"display":1}
,"vary":{"depending":1}
,"depending":{"platform":1}
,"stop":{"server":1}
,"pid":{"server":1}
,"aux":{"grep":1}
,"kill":{"pid":1}
,"several":{"mechanisms":1}
,"mechanisms":{"setting":1}
,"setting":{"configuration":1,"display":1,"color":1,"resolution":1,"controls":1,"following":1,"value":1}
,"run-time":{"parameters":1,"via":1}
,"environment":{"variables":1}
,"files":{"xorg.conf":1,"located":1,"text":1}
,"fallback":{"defaults":1}
,"l4t":{"provides":1}
,"utilities":{"changing":1}
,"changing":{"configuration":1}
,"utility":{"setting":1,"control":1,"included":1,"provides":1}
,"nvidia-xconfig":{"nvidia":1,"tool":1,"configure":1,"simplifies":1,"--help":1,"--advanced-help":1,"specify":1,"--custom-edid":1,"color":1,"--depth":1,"display\u2019s":1,"-mode":1,"\u2011\u2011help":1,"enable":1,"-mode-debug":1,"-no-mode-debug":1,"-only-one-x-screen":1,"--metamode-orientation":1}
,"nvidia":{"tool":1,"jetson":1,"recommends":1,"server":1}
,"tool":{"assists":1,"edit":1,"nvidia-xconfig":1,"provides":1,"enter":1}
,"assists":{"configuring":1}
,"configuring":{"xorg.conf":1,"edid":1}
,"customers":{"support":1}
,"support":{"hot":1,"alpha":1}
,"hot":{"plugging":1}
,"plugging":{"hdmi":1}
,"hdmi":{"display":1,"output":1}
,"implement":{"x11":1}
,"x11":{"client":1,"event":1,"response":1,"registers":1,"rotate":1,"xorg.conf":1,"xorg.conf.d":1,"recognize":1,"start":1,"features":1}
,"client":{"reconfigures":1}
,"reconfigures":{"hdmi":1}
,"upon":{"receipt":1}
,"receipt":{"rrscreenchangenotify":1}
,"rrscreenchangenotify":{"x11":1}
,"event":{"typically":1}
,"typically":{"gnome-settings-daemon":1}
,"solution":{"required":1}
,"required":{"work":1}
,"work":{"around":1}
,"around":{"x11":1}
,"response":{"hot-plugged":1}
,"hot-plugged":{"hdmi":1}
,"registers":{"hdmi":1}
,"output":{"connected":1,"similar":1}
,"connected":{"perform":1,"primary":1}
,"perform":{"automatic":1}
,"automatic":{"mode-set":1}
,"jetson":{"driver":1,"driver\u2019s":1}
,"driver":{"supports":1,"optimum":1,"cannot":1,"logs":1,"poll":1,"default":1}
,"supports":{"xrandr":1,"single":1}
,"1.2":{"x11":1}
,"rotate":{"resize":1}
,"resize":{"extension":1}
,"extension":{"extension":1,"allows":1}
,"allows":{"dynamic":1}
,"dynamic":{"enabling":1}
,"enabling":{"resizing":1,"debug":1,"screen":1,"blending":1}
,"resizing":{"positioning":1}
,"positioning":{"orienting":1}
,"orienting":{"displays":1}
,"displays":{"xrandr":1,"screen":1,"detect":1,"enabled":1,"attached":1,"map":1,"disabled":1}
,"control":{"xrandr":1}
,"included":{"x11-xserver-utils":1}
,"x11-xserver-utils":{"package":1}
,"package":{"drive-setup.sh":1}
,"drive-setup.sh":{"installation":1}
,"installation":{"script":1}
,"script":{"installs":1}
,"installs":{"package":1}
,"querying":{"supported":1}
,"screen":{"resolutions":1,"minimum":1,"resolution":1,"display":1,"example":1,"single":1,"smallest":1,"default":1,"configuration":1,"mirroring":1,"spanning":1,"relative":1,"saver":1,"blanking":1}
,"query":{"attached":1,"blending":1}
,"attached":{"displays":1,"server":1}
,"detect":{"available":1}
,"running":{"enter":1}
,"similar":{"following":1}
,"minimum":{"current":1}
,"current":{"2560":1,"supports":1}
,"2560":{"1600":1}
,"1600":{"maximum":1}
,"maximum":{"16384":1}
,"16384":{"16384":1}
,"dp-0":{"connected":1,"--mode":1}
,"primary":{"2560x1600":1}
,"2560x1600":{"normal":1,"60.0":1}
,"normal":{"left":1}
,"left":{"inverted":1}
,"inverted":{"right":1}
,"right":{"axis":1,"display":1}
,"axis":{"axis":1,"220mm":1}
,"220mm":{"140mm":1}
,"hdmi-0":{"disconnected":1,"--mode":1,"--set":1}
,"disconnected":{"normal":1}
,"obtaining":{"additional":1}
,"additional":{"help":1,"modes":1}
,"help":{"menu":1,"view":1,"nvidia-xconfig":1}
,"menu":{"lists":1}
,"lists":{"supported":1,"modes":1}
,"options":{"provides":1,"modifying":1}
,"further":{"help":1}
,"view":{"available":1}
,"modifying":{"static":1,"xorg.conf":1}
,"static":{"configuration":1}
,"minimal":{"xorg.conf":1}
,"installed":{"target":1}
,"target":{"location":1}
,"additionally":{"directories":1}
,"directories":{".conf":1}
,".conf":{"fragment":1,"file":1}
,"fragment":{"files":1}
,"located":{"locations":1}
,"usr":{"share":1}
,"share":{"x11":1}
,"contains":{"specific":1,"custom":1}
,"specific":{"settings":1}
,"settings":{"screen":1,"based":1,"along":1}
,"resolution":{"virtual":1,"bit":1,"xorg.conf":1,"used":1,"usually":1}
,"virtual":{"desktop":1}
,"desktop":{"size":1,"mapped":1,"part":1,"display":1}
,"size":{"bit":1,"screen":1}
,"bit":{"depth":1}
,"depth":{"display":1,"following":1}
,"select":{"instead":1}
,"instead":{"queries":1,"statically":1}
,"queries":{"driver":1}
,"optimum":{"settings":1}
,"based":{"displays":1,"choice":1}
,"driver\u2019s":{"default":1}
,"along":{"runtime":1}
,"commands":{"server":1}
,"command-line":{"arguments":1,"options":1}
,"meant":{"sufficient":1}
,"sufficient":{"needs":1,"configure":1,"multi-display":1}
,"needs":{"cases":1}
,"cases":{"sufficient":1}
,"configure":{"appropriate":1,"xorg.conf":1,"mirrored":1}
,"appropriate":{"settings":1}
,"enablement":{"create":1}
,"create":{"custom":1}
,"custom":{"defaults":1,"edid":1}
,"defaults":{"may":1,"nvidia-auto-select":1}
,"recommends":{"nvidia-xconfig":1}
,"edit":{"xorg.conf":1,"hand":1}
,"file":{"rather":1,"parses":1,"saves":1,"contains":1,"customarily":1,"makes":1,"debug":1,"information":1,"driver":1,"setting":1}
,"rather":{"edit":1}
,"hand":{"may":1,"circumstances":1}
,"simplifies":{"task":1}
,"task":{"modifying":1}
,"parses":{"file":1}
,"saves":{"backup":1}
,"backup":{"modifies":1}
,"modifies":{"configuration":1}
,"choice":{"command-line":1}
,"getting":{"help":1}
,"basic":{"advanced":1,"information":1}
,"advanced":{"help":1}
,"specifying":{"custom":1,"modes":1}
,"edid":{"display":1,"extended":1,"case":1,"defined":1,"filetype":1,"polling":1,"modes":1}
,"extended":{"display":1}
,"identification":{"data":1}
,"data":{"collection":1,"display":1}
,"collection":{"data":1}
,"modes":{"operation":1,"display\u2019s":1,"reported":1,"described":1,"remove":1,"modes":1}
,"operation":{"resolutions":1}
,"resolutions":{"refresh":1}
,"refresh":{"rates":1}
,"recognize":{"mode":1}
,"mode":{"list":1,"resolution":1,"mode":1,"display":1,"expressed":1,"xorg.conf":1,"enabled":1,"validation":1,"database":1,"whose":1,"property":1}
,"list":{"particular":1,"changed":1}
,"particular":{"model":1,"display":1}
,"model":{"display":1}
,"invalid":{"edid":1}
,"case":{"driver":1}
,"cannot":{"accurately":1}
,"accurately":{"determine":1}
,"determine":{"capabilities":1}
,"capabilities":{"display":1}
,"correct":{"problem":1}
,"problem":{"using":1}
,"specify":{"valid":1,"custom":1,"display":1,"two":1,"particular":1}
,"valid":{"edid":1}
,"--custom-edid":{"hdmi-":1}
,"hdmi-":{"path":1}
,"index":{"hdmi":1}
,"defined":{"first":1}
,"first":{"hdmi":1}
,"path":{"complete":1,"file":1}
,"complete":{"path":1,"setting":1}
,"filetype":{"file":1}
,"customarily":{".bin":1}
,"color":{"bit-depth":1}
,"bit-depth":{"xorg.conf":1,"values":1}
,"makes":{"x11":1}
,"specified":{"color":1,"defaults":1}
,"--depth":{"depth":1}
,"following":{"supported":1,"form":1}
,"display\u2019s":{"display":1,"native":1}
,"add":{"mode":1,"setting":1}
,"terminal":{"window":1}
,"-mode":{"mode":1,"1024x768":1}
,"expressed":{"pixels":1}
,"pixels":{"example":1,"undefined":1}
,"whose":{"mode":1,"overlay":1}
,"changed":{"enter":1}
,"\u2011\u2011help":{"information":1}
,"debug":{"mode":1}
,"enable":{"debug":1,"screen":1,"features":1}
,"logs":{"verbose":1}
,"verbose":{"details":1}
,"details":{"mode":1}
,"validation":{"server":1}
,"log":{"file":1}
,"troubleshoot":{"mode":1}
,"database":{"issues":1}
,"disable":{"debug":1}
,"multi-display":{"server":1,"systems":1,"system":1}
,"layout":{"refers":1,"specify":1,"sufficient":1,"nvidia":1,"maps":1,"shown":1}
,"refers":{"number":1}
,"number":{"displays":1}
,"appears":{"position":1}
,"position":{"display":1}
,"example":{"server":1,"complete":1}
,"two":{"displays":1}
,"map":{"screen":1}
,"single-display":{"systems":1}
,"systems":{"default":1,"define":1}
,"single":{"screen":1,"virtual":1}
,"mapped":{"multiple":1,"enabled":1}
,"multiple":{"displays":1}
,"maps":{"different":1,"desktop":1}
,"different":{"part":1}
,"part":{"screen":1,"desktop":1}
,"mirrored":{"layout":1}
,"smallest":{"rectangle":1}
,"rectangle":{"covers":1}
,"covers":{"parts":1}
,"parts":{"mapped":1}
,"illustration":{"screen":1}
,"side-by-side":{"layout":1}
,"text":{"description":1,"editor":1}
,"description":{"automatically":1}
,"automatically":{"generated":1}
,"specifies":{"layout":1,"position":1,"name":1}
,"shown":{"above":1}
,"--output":{"hdmi-0":1,"dp-0":1}
,"--mode":{"1920x1080":1,"1280x1024":1}
,"1920x1080":{"--output":1}
,"1280x1024":{"--right-of":1}
,"--right-of":{"hdmi-0":1}
,"--metamode-orientation":{"clone":1,"value":1}
,"value":{"specifies":1,"meaning":1,"setting":1,"new":1}
,"relative":{"display":1}
,"rightof":{"default":1}
,"configurations":{"require":1}
,"require":{"editing":1}
,"editing":{"xorg.conf":1,"configuration":1}
,"section":{"describes":1,"xorg.conf":1}
,"describes":{"configuration":1}
,"changes":{"modify":1}
,"modify":{"configuration":1,"blending":1}
,"editor":{"enabling":1}
,"saver":{"features":1}
,"features":{"edid":1,"screen":1,"editing":1}
,"polling":{"blending":1,"native":1,"always":1}
,"blending":{"video":1,"alpha":1,"enabled":1,"natively":1}
,"video":{"overlays":1,"overlay":1}
,"blanking":{"suspending":1}
,"suspending":{"disabling":1}
,"disabling":{"displays":1}
,"disabled":{"enable":1}
,"xorg.conf.d":{"disable_screensaver.conf":1}
,"native":{"resolution":1}
,"statically":{"setting":1}
,"used":{"configuration":1}
,"poll":{"edid":1}
,"usually":{"highest":1}
,"highest":{"resolution":1}
,"always":{"enabled":1}
,"detects":{"edid":1}
,"reported":{"display":1,"edid":1}
,"itself":{"define":1}
,"described":{"specifying":1}
,"remove":{"added":1}
,"added":{"modes":1}
,"tegraoverlaypriority":{".conf":1}
,"controls":{"overlay":1}
,"overlay":{"stacking":1,"priority":1,"present":1,"combined":1,"behind":1,"attributes":1,"values":1,"properties":1}
,"stacking":{"order":1}
,"order":{"range":1}
,"range":{"255":1}
,"255":{"inclusive":1,"larger":1,"behind":1}
,"inclusive":{"default":1}
,"larger":{"numbers":1}
,"numbers":{"represent":1}
,"represent":{"greater":1}
,"greater":{"depths":1}
,"depths":{"thus":1}
,"thus":{"overlay":1}
,"priority":{"front":1}
,"front":{"others":1}
,"others":{"255":1,"value":1}
,"behind":{"others":1,"during":1,"server":1}
,"meaning":{"overlay":1,"external":1}
,"present":{"display":1}
,"tegraoverlayblendmode":{"determines":1,"premultsourcealphablend":1}
,"determines":{"overlay":1}
,"combined":{"overlay":1}
,"during":{"scanout":1,"run-time":1}
,"scanout":{"possible":1}
,"possible":{"modes":1}
,"opaque":{"default":1}
,"external":{"process":1}
,"process":{"created":1}
,"created":{"display":1}
,"option":{"metamodes":1,"information":1}
,"metamodes":{"mode_name":1,"nvidia-auto-select":1}
,"mode_name":{"property":1,"specifies":1,"specified":1}
,"property":{"value":1,"name":1}
,"name":{"mode":1}
,"attributes":{"mode_name":1}
,"new":{"value":1}
,"nvidia-auto-select":{"tegraoverlayblendmode":1}
,"premultsourcealphablend":{"tegraoverlaypriority":1}
,"properties":{"per-output":1}
,"per-output":{"queried":1}
,"queried":{"modified":1}
,"modified":{"during":1}
,"via":{"xrandr":1}
,"\u2011\u2011output":{"option":1}
,"--set":{"tegraoverlaypriority":1,"tegraoverlayblendmode":1}
,"alpha":{"blending":1}
,"done":{"opengl":1}
,"opengl":{"rendering":1}
,"rendering":{"alpha":1}
,"natively":{"rendered":1}
,"rendered":{"pixels":1}
}
;Search.control.loadWordPairs(pairs);
