var pairs =
{
"submit":{"bug":1,"completed":1}
,"bug":{"report":1,"nvidia":1,"procedure":1}
,"encounter":{"apparent":1}
,"apparent":{"bug":1}
,"nvidia":{"jetson":1,"support":1}
,"jetson":{"linux":1}
,"linux":{"driver":1}
,"driver":{"package":1}
,"package":{"documentation":1}
,"documentation":{"procedure":1}
,"procedure":{"submit":1,"reproducing":1}
,"enter":{"following":1}
,"following":{"commands":1}
,"commands":{"target":1}
,"export":{"display":1}
,"xhost":{"si:localuser:root":1}
,"sudo":{"nvidia-bug-report-tegra.sh":1}
,"nvidia-bug-report-tegra.sh":{"script":1}
,"script":{"collects":1}
,"collects":{"logs":1}
,"logs":{"information":1}
,"information":{"include":1}
,"include":{"detailed":1}
,"detailed":{"bug":1}
,"report":{"writes":1,"nvidia":1}
,"writes":{".log":1}
,".log":{"file":1}
,"file":{"current":1,"post":1}
,"current":{"directory":1}
,"prepare":{"description":1}
,"description":{"bug":1}
,"reproducing":{"applicable":1}
,"completed":{"bug":1}
,"support":{"forums":1}
,"forums":{"attach":1}
,"attach":{"script\u2019s":1}
,"script\u2019s":{".log":1}
,"currently":{"forum":1}
,"forum":{"member":1}
}
;Search.control.loadWordPairs(pairs);
