var pairs =
{
"bsp":{"customization":1,"linux_for_tegra":1,"location":1,"version":1}
,"customize":{"nvidia":1,"package":1,"bootloader":1,"l4t":1}
,"nvidia":{"jetson":1,"sdk":1,"cboot-options-v1":1,"t-boot":1,"provides":1,"maintains":1,"adds":1,"uses":1,"developer":1,"recommends":1}
,"jetson":{"linux":1,"device":1,"developer":1,"reference":1,"agx":1,"board":1,"nano":1,"tx2":1,"tx1":1,"module":1,"modules":1,"xavier":1,"t210":1,"t186":1,"t194":1,"platforms":1,"common":1,"devices":1,"platform":1,"functions":1}
,"linux":{"driver":1,"boots":1,"host":1,"reference":1,"obtain":1,"triggers":1,"tegra-ubuntu":1}
,"driver":{"package":1}
,"package":{"l4t":1,"configures":1,"bsp":1,"dependencies":1,"manually":1,"nvidia-l4t-apt-source":1,"yourself":1,"installs":1,"support":1,"change":1,"may":1,"depending":1,"jetson":1,"scripts":1,"post-installation":1,"nvidia-l4t-jetson-io":1,"prevents":1,"installation":1,"upgrades":1,"package":1,"command":1}
,"manually":{"configuring":1,"executing":1}
,"configuring":{"setting":1,"nfs":1}
,"setting":{"software":1,"tftp":1}
,"software":{"drivers":1,"prerequisites":1,"components":1,"source":1}
,"using":{"nvidia":1,"sdk":1,"custom":1,"bootloader":1,"procedure":1,"flags":1}
,"sdk":{"manager":1}
,"manager":{"perform":1,"performs":1,"skip":1,"alternatives":1,"cases":1,"nvidia":1,"purpose":1}
,"perform":{"customized":1,"booting":1,"installation":1}
,"customized":{"setup":1,"versions":1,"package":1}
,"performs":{"following":1,"bup":1,"actions":1}
,"installs":{"nvidia":1,"payload":1,".dtb":1}
,"configures":{"flashes":1}
,"flashes":{"jetson":1}
,"device":{"runs":1,"network-accessible":1,"jetson":1,"tree":1,"priority":1,"specified":1,"controller":1,"obtains":1,"instructions":1,"platforms":1,"host":1,"package\u2019s":1,"using":1,"nvidia-l4t-core":1,"nfs":1,"sure":1}
,"runs":{"samples":1}
,"installed":{"using":1,"l4t":1}
,"skip":{"topics":1}
,"topics":{"information":1}
,"information":{"section":1,"possible":1,"node":1,"topic":1,"subsections":1,"specified":1}
,"section":{"installing":1,"boot":1,"describes":1,"skipping":1,"discusses":1,"lxde":1}
,"installing":{"jetpack":1,"additional":1,"jetson":1}
,"jetpack":{"jetson":1}
,"developer":{"kit":1,"board":1,"center":1}
,"kit":{"user":1}
,"user":{"guide":1,"nobody":1}
,"guide":{"platform":1,"debian":1}
,"boot":{"options":1,"device":1,"configuration":1,"network":1,"devices":1,"sequence":1,"linux":1,"flash":1,"dtb":1,"substitutes":1,"target":1,"verify":1,"time":1}
,"reference":{"board":1,"carrier":1,"create":1,"file":1}
,"board":{"linux":1,"support":1,"requires":1,"mmcblk0p1":1,"name":1,"shown":1,"column":1,"may":1,"installs":1,"boot":1,"specification":1,"usb":1,"t186ref":1}
,"boots":{"root":1}
,"root":{"file":1,"filesystem":1,"linux":1,"mount":1,"point":1,"access":1}
,"file":{"system":1,"directory":1,"necessary":1,"xinetd.d":1,"save":1,"performs":1,"named":1,"used":1,"boot":1,".dtb":1,"puts":1,"script":1,"specify":1}
,"system":{"rootfs":1,"prerequisites":1,"following":1,"network-accessible":1,"provide":1,"nfsroot":1,"configured":1,"install":1,"running":1,"performance":1,"installed":1}
,"rootfs":{"integrated":1,"using":1}
,"integrated":{"memory":1}
,"memory":{"emmc":1,"card":1,"consumption":1}
,"emmc":{"qspi":1,"represents":1,"net":1,"possible":1}
,"qspi":{"attached":1}
,"attached":{"memory":1}
,"card":{"usb":1,"formatted":1,"controller":1}
,"usb":{"device":1,"drive":1,"represents":1,"mass":1,"nvme":1,"cable":1,"internal":1}
,"network-accessible":{"storage":1,"server":1}
,"bootloader":{"loaded":1,"nvidia":1,"boot_sigheader.img.encrypt":1,"tegra194-p3668-p3509-0000_sigheader.dtb.encrypt":1,"tegra194-p2888-0001-p2822-0000_sigheader.dtb.encrypt":1,"package":1,"payload":1,"packages":1,"update":1,"package\u2019s":1}
,"loaded":{"internal":1}
,"internal":{"emmc":1}
,"kernel":{"dtb":1,"dtc":1,"image":1,"--no-flash":1,"debian":1,"getting":1,"source":1,"packages":1,"package":1,"jetson":1,"itself":1,"postinst.d":1,"updated":1,"update":1,"header":1,"version":1,"directory":1,"build":1}
,"dtb":{"loaded":1,"cbo.dtb":1,"checking":1,"gets":1}
,"formatted":{"gpt":1}
,"drive":{"formatted":1}
,"network":{"via":1,"boot":1,"file":1}
,"via":{"dhcp":1}
,"dhcp":{"tftp":1,"server":1,"enabled":1}
,"nvme":{"ssd":1,"represents":1,"storage":1,"device":1,"net":1,"emmc":1}
,"ssd":{"formatted":1,"storage":1}
,"choosing":{"boot":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"jetson":1}
,"series":{"platforms":1,"jetson":1,"cboot":1,"https":1}
,"applies":{"jetson":1}
,"cboot":{"boot":1,"uses":1}
,"options":{"cbo":1,"boot":1}
,"cbo":{"device":1}
,"tree":{"used":1,"node":1,"blobs":1}
,"used":{"certain":1,"boot":1,"jetson":1,"upgrade":1,"board":1}
,"certain":{"boot":1}
,"configuration":{"options":1,"dhcp":1,"static-ip":1,"specified":1,"files":1,"supported":1,"following":1,"correct":1,"present":1,"example":1,"p2792-0000.conf.common":1,"follows":1}
,"priority":{"addresses":1,"device":1,"determined":1}
,"addresses":{"used":1}
,"name":{"cbo":1,"controller":1,"configuration":1}
,"node":{"boot-configuration":1,"properties":1}
,"boot-order":{"property":1,"usb":1}
,"property":{"contains":1,"specifies":1,"specified":1,"value":1,"chosen":1,"step":1}
,"contains":{"list":1,"kernel":1,"archive":1,"three":1,"files":1,"l4t":1,"python":1}
,"list":{"boot":1,"apt":1}
,"devices":{"order":1,"jetson":1}
,"order":{"priority":1}
,"specified":{"name":1,"exports":1}
,"controller":{"information":1,"port":1}
,"possible":{"entries":1,"mount":1}
,"represents":{"card":1,"external":1,"network":1,"built-in":1}
,"external":{"usb":1}
,"mass":{"storage":1}
,"storage":{"device":1,"format":1,"pcie":1}
,"net":{"represents":1,"emmc":1}
,"built-in":{"mmc":1,"nvme":1}
,"mmc":{"storage":1}
,"format":{"entry":1}
,"pcie":{"device":1,"address":1}
,"nvme:pcie@":{"addr":1}
,"address":{"addr":1,"tftp":1,"configuration":1,"subnet":1,"linux":1}
,"available":{"nvme":1}
,"tftp-server-ip":{"property":1,"bits":1}
,"specifies":{"address":1,"static":1,"address\u2019s":1,"gateway\u2019s":1}
,"tftp":{"server":1,"package":1,"example":1}
,"four":{"parts":1,"kernel":1}
,"parts":{"address":1}
,"dhcp-enabled":{"property":1,"false":1}
,"value":{"present":1}
,"present":{"device":1,"flashing":1}
,"obtains":{"configuration":1}
,"server":{"absent":1,"host":1,"target":1,"usr":1,"know":1}
,"absent":{"device":1}
,"static-ip":{"ip-netmask":1,"property":1,"bits":1}
,"ip-netmask":{"ip-gateway":1,"property":1,"bits":1}
,"ip-gateway":{"properties":1,"property":1,"bits":1}
,"static":{"address":1,"configuration":1}
,"address\u2019s":{"subnet":1}
,"subnet":{"mask":1}
,"mask":{"configuration":1}
,"gateway\u2019s":{"address":1}
,"three":{"properties":1,"four":1,"directories":1}
,"properties":{"required":1,"specified":1,"examples":1}
,"required":{"dhcp-enabled":1}
,"false":{"unspecified":1}
,"unspecified":{"otherwise":1}
,"otherwise":{"needed":1}
,"needed":{"ignored":1}
,"ignored":{"present":1}
,"topic":{"presents":1,"u\u2011boot":1,"quick":1,"updating":1,"flashing":1,"window":1}
,"presents":{"examples":1}
,"examples":{"complete":1,"above":1,"assume":1}
,"complete":{"boot-configuration":1}
,"boot-configuration":{"definitions":1}
,"example":{"dhcp":1,"static":1,"entering":1,"jetson-xavier.conf":1}
,"compatible":{"nvidia":1}
,"bits":{"255":1}
,"255":{"255":1}
,"rebuilding":{"dtb":1}
,"modify":{"dts":1,"file":1,"exports":1}
,"dts":{"rebuild":1,"dtb":1}
,"rebuild":{"dtb":1,"kernel":1,"nvidia-l4t-kernel":1}
,"locate":{"cbo.dts":1}
,"cbo.dts":{"file":1}
,"linux_for_tegra":{"bootloader":1,"kernel":1,"tools":1}
,"location":{"jetson":1}
,"support":{"package":1,"jetson":1}
,"necessary":{"information":1}
,"enter":{"command":1}
,"command":{"convert":1,"un-exports":1,"proves":1,"target":1,"kernel":1}
,"convert":{"dts":1}
,"dtc":{"dts":1,"executable":1}
,"cbo.dtb":{"cbo.dts":1}
,"executable":{"available":1}
,"flash":{"partition":1,"board":1}
,"partition":{"cpubl-cfg":1}
,"cpubl-cfg":{"flashing":1}
,"flashing":{"booting":1,"nvidia":1,"configuration":1}
,"booting":{"target":1,"process":1}
,"target":{"device":1,"board":1,"system":1,"nfs":1}
,"nano":{"devices":1,"devicesand":1,"device":1}
,"tx2":{"series":1,"kernel":1}
,"platforms":{"nvidia":1,"https":1}
,"uses":{"u\u2011boot":1,"build":1}
,"u\u2011boot":{"perform":1,"customization":1}
,"process":{"boot":1}
,"determined":{"u\u2011boot":1}
,"sequence":{"sysboot":1}
,"sysboot":{"configuration":1}
,"files":{"topic":1,"depending":1,"creating":1,"l4t":1,"l4t\u2019s":1,"boot":1,"build":1,"directory":1,"jetson-xavier.conf":1}
,"host":{"system":1,"running":1,"machine":1,"nfs":1,"configuration":1}
,"l4t":{"linux":1,"contains":1,"commands":1,"provide":1,"software":1,"root":1,"information":1,"debian":1,"kernel":1,"package":1,"packages":1,"gnome":1}
,"following":{"hardware":1,"apt":1,"payloads":1,"links":1,"command":1,"step":1,"information":1}
,"hardware":{"software":1}
,"prerequisites":{"met":1}
,"running":{"linux":1,"adds":1,"determine":1}
,"image":{"alternatively":1,"source":1,"create":1}
,"alternatively":{"download":1,"export":1}
,"download":{"rebuild":1,"install":1,"archive":1}
,"requires":{"bootloader":1}
,"t-boot":{"nvtboot":1}
,"intend":{"boot":1}
,"cable":{"plug":1}
,"plug":{"recovery":1}
,"recovery":{"port":1}
,"provide":{"tftp":1,"default":1,"nfs":1}
,"install":{"tftp":1,"xinetd":1,"packages":1,"customized":1,"following":1,"nfs":1,"nfs-common":1}
,"dependencies":{"entering":1,"scripts":1,"extracting":1}
,"entering":{"command":1}
,"sudo":{"apt-get":1,"vim":1,"flash.sh":1,"service":1,"tar":1,"init.d":1,"mkdir":1,"chmod":1,"chown":1,"nfsroot":1,"exportfs":1,"ufw":1,"mount":1}
,"apt-get":{"install":1}
,"xinetd":{"tftpd":1,"server":1,"restart":1}
,"tftpd":{"tftp":1}
,"create":{"text":1,"directory":1,"log-in":1,"bootloader":1,"debian":1,"nfsroot":1}
,"text":{"file":1}
,"xinetd.d":{"tftp":1}
,"vim":{"xinetd.d":1}
,"put":{"content":1}
,"content":{"file":1}
,"service":{"tftp":1,"xinetd":1}
,"protocol":{"udp":1}
,"socket_type":{"dgram":1}
,"usr":{"sbin":1,"lib":1,"src":1}
,"sbin":{"in.tftpd":1}
,"server_args":{"tftpboot":1,"copy":1}
,"generate":{"signed":1,"customized":1}
,"signed":{"kernel":1,".dtb":1,"gpg":1}
,"directory":{"tftpboot":1,"linux":1}
,"tftpboot":{"specify":1,"boot.img":1,"jetson.dtb":1}
,"specify":{"pathname":1,"additions":1}
,"pathname":{"defined":1}
,"defined":{"server_args":1,"kernel":1}
,"copy":{"kernel":1,".dtb":1,"file":1}
,"flash.sh":{"kernel":1,"kernel-dtb":1}
,"--no-flash":{"--sign":1}
,"--sign":{"board":1,"jetson-xavier-nx-devkit":1,"jetson-xavier":1}
,"mkdir":{"tftpboot":1,"nfsroot":1,"rootfs":1}
,"boot_sigheader.img.encrypt":{"tftpboot":1}
,"supported":{"specific":1}
,"specific":{"jetson":1}
,"module":{"carrier":1}
,"carrier":{"board":1,"boards":1}
,"shown":{"board":1}
,"column":{"table":1}
,"table":{"jetson":1}
,"modules":{"configurations":1}
,"configurations":{"topic":1}
,"quick":{"start":1}
,".dtb":{"copy":1,"file":1,"files":1}
,"kernel-dtb":{"--no-flash":1}
,"jetson-xavier-nx-devkit":{"mmcblk0p1":1}
,"tegra194-p3668-p3509-0000_sigheader.dtb.encrypt":{"tftpboot":1}
,"jetson-xavier":{"mmcblk0p1":1}
,"tegra194-p2888-0001-p2822-0000_sigheader.dtb.encrypt":{"tftpboot":1}
,"restart":{"xinetd":1,"command":1}
,"extracting":{"jetson":1,".deb":1,"debian":1}
,"procedures":{"extract":1,"determine":1}
,"extract":{"jetson":1,"package":1}
,"commands":{"examples":1}
,"assume":{"extracted":1}
,"extracted":{"release":1}
,"release":{"package":1,"number":1,"e.g":1,"32.4":1,"32.5":1,"trigger":1}
,"executing":{"command":1,"following":1,"mount":1}
,"tar":{"-vxjf":1}
,"-vxjf":{"jetson_linux_r":1}
,"jetson_linux_r":{"release_num":1}
,"release_num":{"_aarch64.tbz2":1,"release":1}
,"number":{"current":1}
,"current":{"release":1}
,"login":{"credentials":1}
,"default":{"log-in":1,"kernel":1}
,"log-in":{"credentials":1}
,"credentials":{"create":1,"first":1}
,"first":{"time":1}
,"time":{"boot":1,"response":1,"memory":1}
,"additional":{"packages":1,"l4t":1}
,"provides":{"additional":1,"following":1}
,"components":{"updates":1,"host":1}
,"updates":{"apt":1,"bootloader":1,"two":1}
,"apt":{"debian":1,"utility":1,"repositories":1,"download":1}
,"debian":{"repositories":1,"packages":1,"linux_for_tegra":1,"nvdebrepack.txt":1,"bootloader":1,"maintainers":1,"file":1}
,"repositories":{"accessible":1,"software":1,"signed":1,"added":1,"described":1}
,"accessible":{"apt":1}
,"maintains":{"following":1}
,"tx1":{"https":1}
,"https":{"repo.download.nvidia.com":1}
,"repo.download.nvidia.com":{"jetson":1}
,"packages":{"used":1,"apt":1,"install":1,"nvidia":1,"script":1,"above":1,"yourself":1,"making":1,"may":1,"open":1,"public_sources.tbz2":1,"pre-depend":1,"depend":1,"host":1}
,"nvidia-l4t-apt-source":{"pre-installed":1}
,"pre-installed":{"l4t":1}
,"filesystem":{"identifies":1,"once":1}
,"identifies":{"platform":1}
,"platform":{"running":1,"e.g":1,"information":1}
,"adds":{"appropriate":1,"initially":1}
,"appropriate":{"repositories":1}
,"source":{"list":1,"packages":1,"three":1,"files":1,"point":1}
,"gpg":{"keys":1}
,"keys":{"corresponding":1}
,"corresponding":{"public":1,".dtb":1}
,"public":{"key":1}
,"key":{"pre-installed":1}
,"once":{"repositories":1}
,"added":{"source":1}
,"described":{"used":1}
,"upgrade":{"existing":1,"l4t":1}
,"existing":{"packages":1,"l4t":1}
,"initially":{"installed":1}
,"updating":{"jetson":1}
,"repackaging":{"debian":1}
,"script":{"nvdebrepack.sh":1,"found":1,"automatically":1,"performs":1,"extracting":1}
,"nvdebrepack.sh":{"repackage":1}
,"repackage":{"existing":1}
,"found":{"linux_for_tegra":1}
,"tools":{"debian":1}
,"nvdebrepack.txt":{"usage":1}
,"usage":{"examples":1}
,"building":{"debian":1,"kernel":1}
,"procedure":{"alternative":1,"repackaging":1,"rebuild":1,"section":1}
,"alternative":{"procedure":1}
,"payload":{"files":1,"bup":1}
,"depending":{"type":1,"jetson":1,"configuration":1}
,"type":{"processor":1}
,"processor":{"jetson":1}
,"package\u2019s":{"post-install":1,"pre-dependencies":1,"major":1,"dependencies":1}
,"post-install":{"script":1}
,"automatically":{"updates":1}
,"distributed":{"versions":1}
,"versions":{"bootloader":1,"bups":1}
,"boards":{"using":1}
,"custom":{"carrier":1}
,"may":{"customize":1,"reference":1,"disable":1}
,"change":{"odm":1}
,"odm":{"data":1}
,"data":{"pinmux":1}
,"pinmux":{"assignments":1}
,"assignments":{"customize":1}
,"bups":{"need":1,"customized":1,"package":1,"jetson":1}
,"need":{"change":1}
,"unpack":{"package":1}
,"replace":{"applicable":1}
,"applicable":{"bup":1}
,"bup":{"bups":1,"update":1,"installation":1}
,"repack":{"bups":1}
,"describes":{"package":1}
,"scripts":{"nvidia":1,"concerned":1}
,"build":{"bootloader":1,"kernel":1,"source":1,"configuration":1}
,"obtain":{"either":1}
,"either":{"two":1}
,"two":{"versions":1,"symbolic":1}
,"opt":{"ota_package":1}
,"ota_package":{"t21x":1,"t19x":1,"t18x":1}
,"t21x":{"bl_update_payload":1}
,"t19x":{"bl_only_payload":1,"bl_update_payload":1}
,"t18x":{"bl_only_payload":1,"bl_update_payload":1}
,"subsections":{"headed":1}
,"headed":{"generating":1}
,"generating":{"bootloader":1}
,"update":{"payload":1,"redundancy":1,"initramfs":1,"procedure":1}
,"redundancy":{"sections":1}
,"sections":{"concerning":1}
,"concerning":{"jetson":1}
,"pre-dependencies":{"dependencies":1}
,"nvidia-l4t-core":{"match":1,"package":1,"perform":1,"prevents":1}
,"match":{"package\u2019s":1}
,"major":{"release":1}
,"post-installation":{"script":1}
,"installation":{"extracting":1,"incompatible":1,"detects":1,"instructions":1}
,".deb":{"file":1}
,"nvidia-l4t-kernel":{"above":1,"contains":1}
,"getting":{"kernel":1}
,"making":{"changes":1}
,"changes":{"building":1}
,"working":{"packages":1}
,"open":{"source":1}
,"public_sources.tbz2":{"download":1}
,"archive":{"nvidia":1,"contains":1,"named":1}
,"center":{"following":1}
,"devicesand":{"jetson":1}
,"named":{"kernel_src.tbz2":1,"usr":1}
,"kernel_src.tbz2":{"turn":1}
,"turn":{"contains":1}
,"directories":{"header":1,"want":1,"using":1}
,"header":{"files":1,"tarball":1}
,"debian.org":{"guide":1}
,"maintainers":{"gives":1}
,"gives":{"guidelines":1}
,"guidelines":{"modifying":1}
,"modifying":{"open":1}
,"creating":{"new":1}
,"new":{"debian":1,"major":1}
,"fourth":{"kernel":1}
,"nvidia-l4t-jetson-io":{"discussed":1,"below":1,"contains":1}
,"discussed":{"nvidia-l4t-jetson-io":1}
,"pre-depend":{"nvidia-l4t-core":1}
,"prevents":{"package":1,"partial":1}
,"incompatible":{"jetson":1,"platform":1}
,"e.g":{"installing":1,"release":1}
,"detects":{"incompatible":1}
,"partial":{"upgrade":1,"upgrades":1}
,"upgrades":{"new":1,"cause":1}
,"32.4":{"release":1}
,"32.5":{"l4t":1}
,"depend":{"upgraded":1}
,"upgraded":{"partial":1,"ones":1}
,"cause":{"compatibility":1}
,"compatibility":{"issues":1,"information":1}
,"issues":{"firmware":1,"performing":1}
,"firmware":{"programs":1}
,"programs":{"libraries":1}
,"libraries":{"upgraded":1}
,"executes":{"depmod":1}
,"creates":{"dpkg":1}
,"dpkg":{"trigger":1}
,"trigger":{"file":1,"invokes":1}
,"lib":{"linux":1}
,"triggers":{"release":1}
,"invokes":{"actions":1}
,"actions":{"defined":1}
,"postinst.d":{"update":1}
,"initramfs":{"grub":1}
,"grub":{"configs":1}
,"configs":{"kernel":1,"tegra_defconfig":1}
,"updated":{"conforms":1}
,"conforms":{"standard":1}
,"standard":{"ubuntu":1}
,"ubuntu":{"kernel":1,"firewall":1,"window":1}
,"nvidia-l4t-kernel-dtbs":{"contains":1}
,"l4t\u2019s":{"device":1}
,"blobs":{"dtbs":1}
,"checking":{"board":1}
,"specification":{"against":1}
,"against":{"dtbs":1}
,"dtbs":{"compatibility":1}
,"decompiles":{".dtb":1,"corresponding":1}
,"gets":{"bootargs":1}
,"bootargs":{"property":1}
,"chosen":{"node":1}
,"substitutes":{"bootargs":1}
,"step":{"resulting":1,"booted":1}
,"resulting":{".dts":1}
,".dts":{"file":1}
,"recompiles":{".dts":1}
,"puts":{"boot":1}
,"nvidia-l4t-kernel-headers":{"contains":1}
,"extracts":{"kernel":1}
,"tarball":{"usr":1}
,"symbolic":{"link":1}
,"link":{"files":1}
,"point":{"correct":1,"linux":1,"target":1,"flashing":1}
,"correct":{"kernel":1}
,"python":{"scripts":1}
,"concerned":{"jetson":1}
,"nfs":{"root":1,"provide":1,"components":1,"server":1,"bootable":1,"boot":1}
,"mount":{"point":1,"host":1,"nfsvers":1,"command":1}
,"ethernet":{"connection":1}
,"connection":{"install":1,"target":1}
,"configure":{"nfs":1}
,"nfs-common":{"nfs-kernel-server":1,"package":1}
,"know":{"directories":1}
,"want":{"export":1}
,"export":{"clients":1,"root":1,"un-export":1}
,"clients":{"information":1}
,"exports":{"file":1,"look":1}
,"look":{"somewhat":1}
,"nfsroot":{"nohide":1,"directory":1,"rootfs":1}
,"nohide":{"insecure":1}
,"insecure":{"no_subtree_check":1}
,"no_subtree_check":{"async":1}
,"async":{"no_root_squash":1}
,"adding":{"entry":1}
,"entry":{"restart":1}
,"init.d":{"nfs-kernel-server":1}
,"nfs-kernel-server":{"restart":1}
,"permissions":{"nfsroot":1}
,"chmod":{"755":1}
,"755":{"nfsroot":1}
,"chown":{"root.root":1}
,"root.root":{"nfsroot":1}
,"disable":{"oem\u2011config":1}
,"oem\u2011config":{"rootfs":1,"topic":1}
,"skipping":{"oem\u2011config":1}
,"un-export":{"directories":1}
,"flags":{"following":1}
,"un-exports":{"directories":1}
,"exportfs":{"-au":1}
,"optionally":{"ubuntu":1}
,"firewall":{"blocks":1}
,"blocks":{"nfs":1}
,"access":{"disabled":1}
,"disabled":{"depending":1}
,"ufw":{"disable":1}
,"performing":{"nfs":1}
,"verify":{"everything":1}
,"everything":{"host":1}
,"configured":{"properly":1}
,"properly":{"executing":1}
,"booted":{"target":1}
,"nfsvers":{"ip-addr":1}
,"ip-addr":{"nfsroot":1,"address":1}
,"machine":{"taken":1}
,"taken":{"ifconfig":1}
,"ifconfig":{"command":1}
,"proves":{"host":1}
,"sure":{"include":1}
,"include":{"option":1}
,"option":{"nfs":1}
,"determining":{"version":1}
,"version":{"platform":1,"command":1}
,"flashed":{"bsp":1}
,"determine":{"bsp":1,"kernel":1,"boot":1}
,"execute":{"command":1}
,"head":{"nv_tegra_release":1,"-22":1}
,"output":{"similar":1}
,"similar":{"following":1}
,"r31":{"revision":1}
,"revision":{"0.0":1}
,"0.0":{"gcid":1}
,"gcid":{"board":1}
,"t186ref":{"eabi":1}
,"eabi":{"aarch64":1}
,"aarch64":{"date":1,"gnu":1}
,"date":{"wed":1}
,"wed":{"aug":1}
,"aug":{"23:57:14":1}
,"23:57:14":{"utc":1}
,"utc":{"2018":1}
,"-22":{"makefile":1}
,"makefile":{"tail":1}
,"sublevel":{"140":1}
,"tegra-ubuntu":{"4.9.140-tegra":1}
,"4.9.140-tegra":{"smp":1}
,"smp":{"preempt":1}
,"preempt":{"mon":1}
,"mon":{"jun":1}
,"jun":{"12:08:39":1}
,"12:08:39":{"pdt":1}
,"pdt":{"2019":1}
,"2019":{"aarch64":1}
,"gnu":{"linux":1}
,"jetson-xavier.conf":{"provides":1,"reference":1}
,"chipid":{"0x19":1}
,"0x19":{"emmc_cfg":1}
,"emmc_cfg":{"flash_t194_sdmmc.xml":1}
,"flash_t194_sdmmc.xml":{"bootpartsize":1}
,"bootpartsize":{"8388608":1}
,"8388608":{"emmcsize":1}
,"emmcsize":{"31276924928":1}
,"31276924928":{"its_file":1}
,"its_file":{"sysbootfile":1}
,"sysbootfile":{"p2972-0000":1}
,"p2972-0000":{"extlinux.conf":1}
,"extlinux.conf":{"bpfdtb_file":1}
,"bpfdtb_file":{"tegra194-a01-bpmp-p2888-a01.dtb":1}
,"tegra194-a01-bpmp-p2888-a01.dtb":{"dtb_file":1}
,"dtb_file":{"tegra194-p2888-0001-p2822-0000.dtb":1}
,"tegra194-p2888-0001-p2822-0000.dtb":{"tbcdtb_file":1}
,"tbcdtb_file":{"tegra194-p2888-0001-p2822-0000.dtb":1}
,"full":{"definition":1}
,"definition":{"boot":1}
,"p2792-0000.conf.common":{"files":1}
,"additions":{"changes":1}
,"arch":{"arm64":1}
,"arm64":{"configs":1}
,"improving":{"system":1}
,"discusses":{"types":1}
,"types":{"customization":1}
,"customization":{"improve":1}
,"improve":{"performance":1}
,"performance":{"jetson":1}
,"lightweight":{"window":1}
,"window":{"manager":1,"system":1,"systems":1}
,"gnome":{"standard":1,"lightweight":1}
,"cases":{"reduce":1}
,"reduce":{"boot":1}
,"response":{"time":1}
,"consumption":{"cpu":1}
,"cpu":{"utilization":1}
,"utilization":{"replacing":1}
,"replacing":{"gnome":1}
,"recommends":{"lxde":1}
,"lxde":{"environment":1,"installation":1,"topic":1}
,"environment":{"compton":1}
,"compton":{"compositing":1}
,"compositing":{"manager":1}
,"instructions":{"information":1}
}
;Search.control.loadWordPairs(pairs);
