var pairs =
{
"generic":{"timestamp":1}
,"timestamp":{"engine":1,"configured":1,"raw":1,"nanoseconds":1,"read":1,"gpio":1}
,"applies":{"jetson":1}
,"jetson":{"agx":1,"generic":1,"timestamps":1,"device":1,"devices":1,"device\u2019s":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"carrier":1}
,"driver":{"experimental":1,"provides":1,"enabled":1,"accompanied":1,"demonstrates":1,"api":1,"modify":1,"gte":1,"test":1,"host":1,"modifying":1}
,"experimental":{"promised":1}
,"promised":{"stable":1}
,"api":{"subject":1,"retrieve":1}
,"subject":{"change":1}
,"change":{"future":1,"falling":1,"client":1,"test":1,"value":1}
,"future":{"releases":1}
,"releases":{"enabled":1}
,"enabled":{"default":1,"creates":1,"jetson":1}
,"gpio":{"direction":1,"irq":1,"monitoring":1,"user":1,"state":1,"bb-1":1,"bb-0":1,"input":1,"pin":1,"output":1,"257":1,"timestamp":1,"256":1,"export":1,"gpio256":1,"event":1,"unexport":1}
,"direction":{"change":1,"i.e":1}
,"falling":{"rising":1,"edges":1}
,"rising":{"information":1,"falling":1}
,"information":{"reliable":1,"correctly":1}
,"reliable":{"using":1}
,"using":{"gte":1}
,"gte":{"gte":1,"monitoring":1,"provides":1,"kernel":1,"instances":1,"hardware":1,"driver":1,"device":1,"sample":1,"tests":1,"feature\u2019s":1,"test":1,"timestamp":1,"gpio":1,"lic":1,"user":1,"chip":1,"instance":1,"event":1}
,"monitoring":{"lic":1,"gpio":1,"successfully":1,"aon":1}
,"lic":{"irq":1,"legacy":1,"interrupt":1}
,"irq":{"convey":1,"gte":1,"monitoring":1,"i2c-0":1,"gpio":1,"line":1,"reading":1,"timestamp":1}
,"convey":{"information":1}
,"engine":{"gte":1}
,"provides":{"hardware":1,"various":1,"details":1}
,"hardware":{"timestamping":1,"jetson":1}
,"timestamping":{"state":1,"events":1}
,"state":{"changes":1}
,"changes":{"specific":1,"monitored":1,"gte":1}
,"specific":{"signals":1}
,"signals":{"including":1,"guide":1}
,"including":{"lic":1}
,"legacy":{"interrupt":1}
,"interrupt":{"controller":1,"lines":1,"line":1}
,"controller":{"interrupt":1}
,"lines":{"aon":1,"tegra194-p2822-0000-a00.dtsi":1}
,"aon":{"always":1,"gpio":1,"events":1,"specifies":1}
,"always":{"domain":1,"gpio":1}
,"domain":{"gpios":1}
,"gpios":{"gpios":1,"monitored":1,"256":1}
,"monitored":{"configured":1,"line\u2019s":1}
,"configured":{"input":1,"signal":1,"output":1}
,"input":{"gpio":1,"pin":1}
,"kernel":{"device":1,"driver":1,"sample":1,"rebuild":1,"drivers":1,"customization":1,"test":1,"source":1,"sources":1,"configuration":1,"kernel":1,"jetson":1,"debug":1,"printk":1,"tegra_gte_test":1}
,"device":{"driver":1,"node":1,"tree":1,"following":1,"gte":1,"restart":1,"root":1,"step":1,"enter":1,"install":1,"internally":1,"event":1}
,"various":{"apis":1}
,"apis":{"clients":1}
,"clients":{"register":1}
,"register":{"retrieve":1}
,"retrieve":{"unregister":1,"timestamp":1}
,"unregister":{"specific":1}
,"guide":{"provides":1}
,"details":{"enable":1}
,"enable":{"gte":1,"compile":1,"kernel":1}
,"once":{"gte":1}
,"creates":{"two":1,"device":1}
,"two":{"gte":1}
,"instances":{"device":1}
,"sys":{"devices":1,"kernel":1,"class":1}
,"devices":{"3aa0000.gte":1,"c1e0000.gte":1,"information":1,".gte":1,"gte":1}
,"3aa0000.gte":{"lic":1}
,"c1e0000.gte":{"aon":1}
,"cle0000.gte":{"turn":1}
,"turn":{"creates":1}
,"node":{"dev":1}
,"dev":{"gtechip0":1}
,"gtechip0":{"user":1,"257":1,"specifies":1}
,"user":{"space":1}
,"space":{"utility":1,"sample":1,"applications":1}
,"utility":{"monitor":1}
,"monitor":{"aon":1,"lic":1}
,"accompanied":{"kernel":1,"user":1}
,"sample":{"test":1,"application":1,"kernel":1,"gte":1}
,"test":{"driver":1,"kernel":1,"procedures":1,"lic":1}
,"demonstrates":{"monitor":1}
,"line":{"aon":1,"i2c0":1}
,"line\u2019s":{"state":1}
,"timestamps":{"change":1}
,"client":{"program":1}
,"program":{"gte":1}
,"application":{"demonstrates":1,"thus":1,"prints":1,"enter":1}
,"enabling":{"gte":1}
,"modify":{"device":1,".dtsi":1,"setup":1}
,"tree":{"gte-related":1,"reflash":1,"jetson":1,"nodes":1,"blob":1,".dtb":1}
,"gte-related":{"configuration":1}
,"configuration":{"options":1,"file":1}
,"options":{"kernel":1,"file":1,"control":1}
,"rebuild":{"kernel":1}
,"reflash":{"rebuilt":1}
,"rebuilt":{"kernel":1}
,"following":{"steps":1,"lines":1,"kernel":1}
,"steps":{"accomplish":1}
,"accomplish":{"things":1}
,"default":{"setup":1}
,"setup":{"scenario":1,"modify":1,"change":1}
,"scenario":{"ensure":1}
,"ensure":{"gpios":1,"proper":1}
,"256":{"257":1,"bb0":1,"generate":1,"sys":1,"maps":1,"output":1,"i.e":1}
,"257":{"used":1,"gpio_out":1,"bb1":1,"specifies":1}
,"used":{"kernel":1}
,"drivers":{"user":1,"staging":1}
,"host":{"add":1,"flash":1,"source":1,"copy":1}
,"add":{"following":1}
,"status":{"okay":1}
,"delete-property":{"use-timestamp":1}
,".dtsi":{"file":1}
,"file":{"locate":1,"topic":1,"tegra_defconfig":1}
,"locate":{"compiled":1,"source":1,"files":1}
,"compiled":{"device":1}
,"blob":{"tegra194-p2888-0001-p2822-0000.dtb":1}
,"tegra194-p2888-0001-p2822-0000.dtb":{"host":1}
,"flash":{"instructions":1,"device":1}
,"instructions":{"compile":1}
,"compile":{"flash":1,"gte":1,"tegra_gte_mon.c":1}
,".dtb":{"file":1}
,"topic":{"kernel":1,"debugging":1}
,"source":{"code":1,"nvidia":1}
,"code":{"gte":1,"directory":1,"download":1}
,"kernel_source":{"drivers":1,"directory":1}
,"staging":{"platform":1}
,"platform":{"tegra":1}
,"directory":{"chosen":1,"building":1,"choice":1,"usr":1}
,"chosen":{"hold":1}
,"hold":{"kernel":1}
,"download":{"obtaining":1}
,"obtaining":{"kernel":1}
,"sources":{"git":1}
,"git":{"topic":1}
,"control":{"gte":1}
,"modifying":{"kernel":1}
,"debugging":{"kernel":1}
,"proper":{"cross-compiler":1}
,"cross-compiler":{"toolchain":1}
,"toolchain":{"topic":1}
,"customization":{"information":1,"locate":1}
,"environment":{"build":1}
,"build":{"kernel":1}
,"copy":{"built":1,"image":1,"tegra194_gte_test.ko":1,"made":1,"kernel":1}
,"built":{"files":1}
,"files":{"jetson":1,"image":1}
,"host\u2019s":{"output":1}
,"output":{"directory":1,"pin":1}
,"building":{"nvidia":1}
,"nvidia":{"kernel":1,"include":1,"tools":1}
,"image":{"tegra194_gte_test.ko":1,"boot":1,"jetson":1}
,"boot":{"image":1}
,"tegra194_gte_test.ko":{"directory":1,"lic_irq":1,"refers":1}
,"choice":{"jetson":1}
,"enter":{"command":1}
,"command":{"jetson":1,"enable":1,"test":1,"read":1,"disable":1,"start":1,"prints":1,"gpio":1,"clear":1,"unexport":1}
,"restart":{"device":1}
,"sudo":{"systemctl":1}
,"systemctl":{"reboot":1}
,"running":{"sample":1,"tests":1}
,"tests":{"described":1,"short":1}
,"described":{"gte":1}
,"feature\u2019s":{"default":1}
,"procedures":{"appropriately":1}
,"run":{"sample":1,"gte":1,"command":1}
,"short":{"pins":1}
,"pins":{"jetson":1}
,"carrier":{"board\u2019s":1}
,"board\u2019s":{"40\u2011pin":1}
,"40\u2011pin":{"header":1}
,"header":{"pin":1}
,"pin":{"aon":1,"257":1,"gpio":1,"256":1,"may":1}
,"bb-1":{"configured":1}
,"bb-0":{"configured":1}
,"log":{"jetson":1}
,"root":{"run":1}
,"insmod":{"tegra194_gte_test.ko":1}
,"lic_irq":{"gpio_in":1,"indicates":1}
,"gpio_in":{"257":1}
,"gpio_out":{"256":1}
,"refers":{"copy":1}
,"made":{"jetson":1}
,"step":{"5.3":1}
,"5.3":{"above":1}
,"indicates":{"lic":1}
,"i2c-0":{"irq":1}
,"bb1":{"gpio":1}
,"bb0":{"gpio":1}
,"parameter":{"values":1}
,"values":{"shown":1}
,"shown":{"suggested":1}
,"suggested":{"starting":1}
,"starting":{"points":1}
,"points":{"may":1}
,"may":{"change":1}
,"debug":{"messages":1}
,"echo":{"proc":1,"sys":1,"256":1}
,"proc":{"sys":1}
,"tegra_gte_test":{"gpio_en_dis":1,"lic_irq_en_dis":1,"lic_irq_ts":1}
,"successfully":{"enabled":1,"jetson":1}
,"device\u2019s":{"console":1}
,"console":{"prints":1}
,"prints":{"message":1,"description":1}
,"raw":{"xxxx":1,"form":1}
,"xxxx":{"yyyy":1,"represents":1,"ts_ns":1}
,"represents":{"gte":1,"timestamp":1}
,"form":{"yyyy":1}
,"yyyy":{"represents":1}
,"i2c0":{"controller":1}
,"reading":{"eeprom":1}
,"eeprom":{"generating":1}
,"generating":{"i2c":1}
,"i2c":{"interrupts":1}
,"i2cdump":{"0x50":1}
,"read":{"lic":1,"successfully":1}
,"cat":{"sys":1}
,"ts_raw":{"xxxx":1}
,"ts_ns":{"yyyy":1}
,"disable":{"gte":1}
,"gcc":{"already":1,"tegra_gte_mon.c":1}
,"already":{"installed":1}
,"installed":{"jetson":1}
,"apt":{"install":1}
,"install":{"gcc":1}
,"include":{"uapi":1,"linux":1}
,"uapi":{"linux":1}
,"linux":{"tegra-gte-ioctl.h":1,"jetson":1}
,"tegra-gte-ioctl.h":{"directory":1}
,"usr":{"include":1}
,"tools":{"tegra-gte":1}
,"tegra-gte":{"tegra_gte_mon.c":1}
,"tegra_gte_mon.c":{"directory":1,"gte_mon":1}
,"start":{"sample":1,"timestamping":1,"toggling":1}
,"thus":{"start":1}
,"gte_mon":{"gtechip0":1,"different":1}
,"specifies":{"aon":1,"gte":1,"direction":1}
,"value":{"gte_mon":1}
,"different":{"pins":1}
,"specify":{"timestamping":1}
,"events":{"rising":1,"due":1,"registered":1}
,"chip":{"device":1}
,"internally":{"maps":1}
,"maps":{"gte":1,"port":1}
,"instance":{"monitoring":1}
,"description":{"application\u2019s":1}
,"application\u2019s":{"usage":1}
,"toggling":{"gpio":1}
,"generate":{"observable":1}
,"observable":{"events":1}
,"class":{"gpio":1}
,"gpio256":{"direction":1,"value":1}
,"port":{"aon":1}
,"i.e":{"configures":1,"change":1}
,"configures":{"gpio":1}
,"event":{"xxxx":1,"yyyy":1,"statistics":1,"numbers":1,"enter":1,"num_dropped_events":1,"number":1,"queried":1,"num_events_avail":1}
,"clear":{"gpio":1}
,"close":{"sample":1}
,"press":{"ctrl":1}
,"unexport":{"release":1}
,"release":{"gpio":1}
,"display":{"gte":1,"event":1,"number":1}
,"numbers":{"registered":1}
,"registered":{"gte":1,"type":1}
,".gte":{"events_registered":1}
,"number":{"dropped":1,"event":1,"available":1}
,"dropped":{"events":1}
,"due":{"software":1}
,"software":{"fifo":1}
,"fifo":{"overrun":1}
,"overrun":{"registered":1}
,"type":{"event":1}
,"available":{"events":1}
}
;Search.control.loadWordPairs(pairs);
