var pairs =
{
"jetson":{"nano":1,"linux":1}
,"nano":{"boot":1,"devices":1,"bootrom":1,"bootloader":1,"tegraboot":1,"cboot":1}
,"boot":{"flow":1,"software":1,"logo":1,"media":1,"configuration":1,"flashing":1,"path":1,"kernel":1}
,"applies":{"jetson":1}
,"primary":{"function":1,"cpu":1}
,"function":{"nvidia":1}
,"nvidia":{"jetson":1}
,"software":{"initialize":1,"performs":1,"follows":1,"component":1}
,"initialize":{"soc":1}
,"soc":{"system":1,"initializes":1}
,"system":{"chip":1}
,"chip":{"including":1}
,"initializing":{"emc":1,"firmware":1,"bootloader":1}
,"emc":{"cpu":1,"training":1}
,"setting":{"security":1,"memory":1}
,"security":{"parameters":1}
,"loading":{"different":1,"initializing":1,"next":1,"bootloader":1}
,"different":{"firmware":1,"configuration":1}
,"maintaining":{"chain":1}
,"chain":{"trust":1}
,"memory":{"carveouts":1}
,"carveouts":{"different":1}
,"flashing":{"device":1}
,"booting":{"operating":1}
,"operating":{"system":1}
,"additionally":{"jetson":1}
,"performs":{"operations":1}
,"operations":{"defined":1}
,"defined":{"product":1}
,"product":{"requirements":1}
,"requirements":{"including":1}
,"including":{"limited":1}
,"initialization":{"hdmi":1,"passes":1}
,"hdmi":{"dsi":1}
,"displaying":{"boot":1}
,"flow":{"control":1,"follows":1}
,"control":{"boot":1,"cboot":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1,"generated":1}
,"automatically":{"generated":1}
,"bootrom":{"hard-wired":1,"boot":1,"hardware":1,"uses":1}
,"hard-wired":{"soc":1}
,"initializes":{"boot":1}
,"media":{"loads":1}
,"loads":{"bootloaders":1}
,"bootloaders":{"firmware":1}
,"firmware":{"boot":1,"components":1}
,"multiple":{"copies":1}
,"copies":{"bootrom":1}
,"configuration":{"table":1,"parameters":1,"files":1}
,"table":{"bct":1}
,"bct":{"may":1,"contains":1}
,"may":{"stored":1}
,"stored":{"start":1,"separate":1}
,"start":{"boot-media":1,"running":1}
,"boot-media":{"bct":1}
,"contains":{"configuration":1,"information":1}
,"parameters":{"used":1,"initializing":1}
,"used":{"bootrom":1,"cold":1,"mobile":1}
,"hardware":{"initialization":1}
,"information":{"bootloader":1,"verify":1,"u-boot":1}
,"bootloader":{"including":1,"boot":1,"components":1,"flash":1,"device":1,"dtb":1,"used":1,"nvidia":1}
,"entry":{"point":1}
,"load":{"address":1,"bootloader":1}
,"uses":{"information":1,"interrupt":1,"cdf":1}
,"verify":{"load":1}
,"flash":{"components":1}
,"tegraboot":{"aka":1,"nvtboot":1,"responsible":1,"follows":1,"cpu":1}
,"aka":{"nvtboot":1,"nvtboot-cpu":1}
,"nvtboot":{"just":1,"first":1}
,"just":{"tboot":1}
,"cpu-bl":{"aka":1,"parameters":1}
,"first":{"boot":1}
,"component":{"loaded":1}
,"loaded":{"sysram":1}
,"sysram":{"runs":1}
,"runs":{"bpmp":1}
,"two":{"variants":1}
,"variants":{"tegraboot":1}
,"cold":{"boot":1}
,"recovery":{"boot":1}
,"generated":{"using":1,"high":1}
,"using":{"different":1,"bootloader":1}
,"files":{"files":1}
,"components":{"tos":1,"tegraboot":1,"cboot":1}
,"creating":{"carveouts":1}
,"completing":{"cpu":1}
,"cpu":{"initialization":1,"bootloader":1,"starts":1}
,"next":{"stage":1}
,"stage":{"bootloader":1}
,"supporting":{"flashing":1,"rcm":1,"update":1}
,"rcm":{"boot":1}
,"reading":{"pmic":1}
,"pmic":{"reset":1}
,"reset":{"reason":1}
,"device":{"tree":1,"trees":1}
,"tree":{"passing":1,"load":1}
,"passing":{"device":1}
,"address":{"cboot":1}
,"stops":{"execution":1}
,"execution":{"ccplex":1}
,"ccplex":{"booted":1}
,"high":{"confidence":1}
,"add":{"rollback":1}
,"rollback":{"prevention":1}
,"dtb":{"perform":1,"training":1}
,"perform":{"emc":1}
,"training":{"update":1,"results":1}
,"update":{"kernel":1,"mechanism":1}
,"kernel":{"dtb":1,"open":1,"separate":1}
,"pass":{"control":1}
,"cboot":{"primary":1,"feature-rich":1,"starts":1,"el2":1,"responsible":1,"follows":1}
,"mobile":{"platforms":1}
,"platforms":{"cold":1}
,"path":{"cboot":1}
,"feature-rich":{"bootloader":1}
,"boots":{"u\u2011boot":1}
,"supports":{"display":1}
,"display":{"boot":1}
,"logo":{"bmp":1}
,"bmp":{"splash":1}
,"based":{"little":1}
,"little":{"kernel":1}
,"open":{"source":1}
,"source":{"bootloader":1}
,"interrupt":{"scheduling":1}
,"scheduling":{"frameworks":1}
,"cdf":{"frameworks":1}
,"frameworks":{"drivers":1}
,"drivers":{"libraries":1}
,"soon":{"cpu":1}
,"starts":{"running":1,"el3":1}
,"running":{"cboot":1}
,"el3":{"mode":1}
,"mode":{"begins":1}
,"begins":{"executing":1}
,"executing":{"tos":1}
,"tos":{"tos":1,"completes":1}
,"completes":{"initialization":1}
,"passes":{"control":1}
,"el2":{"mode":1}
,"separate":{"device":1,"partitions":1}
,"trees":{"stored":1}
,"partitions":{"cboot":1}
,"parsing":{"cpu-bl":1}
,"chaining":{"u-boot":1}
,"u-boot":{"boot":1,"default":1,"customization":1}
,"unhalts":{"bpmp":1}
,"bpmp":{"bpmp-fw":1}
,"bpmp-fw":{"start":1}
,"default":{"bootloader":1}
,"linux":{"driver":1}
,"driver":{"package":1}
}
;Search.control.loadWordPairs(pairs);
