var pairs =
{
"jetson":{"tx2":1}
,"tx2":{"series":1,"mb1":1,"boot":1,"pinmux":1,"prod":1,"pad":1,"pins":1,"pmic":1,"module":1,"devices":1,"platforms":1,"systems":1}
,"series":{"mb1":1,"devices":1}
,"mb1":{"platform":1,"uses":1,"bct":1,"executes":1,"stage":1,"allows":1,"reads":1,"enables":1,"device":1,"device-side":1,"contain":1,"cfg":1,"code":1,"controls":1,"waits":1,"resumes":1,"wait":1,"programs":1,"mb2":1}
,"platform":{"configuration":1,"calls":1,"specific":1,"ver":1,"prod":1,"software":1,"data":1,"feature":1}
,"applies":{"nvidia":1}
,"nvidia":{"jetson":1,"signed":1,"oem":1}
,"boot":{"sequence":1,"flow":1,"jetson":1,"stored":1,"exclude":1,"done":1,"temperature":1,"cpu":1}
,"sequence":{"jetson":1,"may":1,"rail":1,"commands":1,"starting":1,"beginning":1,"recommendation":1,"delay":1}
,"uses":{"mb1":1,"following":1}
,"bct":{"configure":1,"specifies":1,"uses":1,"required":1,"tegra186-mb1-bct-pinmux-gpio-":1,"tegra186-mb1-bct-prod-":1,"tegra":1,"configuration":1,"binary":1,"mb1":1,"auto_scr.cfg":1,"cold":1,"allows":1,"tegra186-mb1-bct-misc-quill-p2382.cfg":1,"flag":1}
,"configure":{"platform-specific":1,"devices":1}
,"platform-specific":{"static":1,"data":1,"configuration":1,"mb1":1}
,"static":{"settings":1}
,"settings":{"mb1":1,"required":1,"contain":1,"passed":1,"cluster":1,"various":1,"specify":1,"used":1}
,"executes":{"cpus":1}
,"cpus":{"enabled":1}
,"enabled":{"mb1":1,"disabled":1}
,"stage":{"owned":1,"signed":1,"offers":1}
,"owned":{"nvidia":1}
,"signed":{"nvidia":1,"oem":1}
,"information":{"jetson":1,"typical":1,"format":1,"commands":1,"generic":1,"collected":1,"system":1,"flashing":1}
,"specifies":{"platform-specific":1,"block":1,"command":1,"delay":1,"number":1}
,"data":{"tegraflash":1,"register":1,"pair":1,"value":1,"address":1,"size":1,"support":1,"scr":1,"platform":1,"cannot":1,"cfg":1,"bct":1}
,"tegraflash":{"invoked":1}
,"invoked":{"flash":1}
,"flash":{"platform":1}
,"calls":{"tegrabct_v2":1}
,"tegrabct_v2":{"tool":1}
,"tool":{"create":1}
,"create":{"mb1":1,"configuration":1}
,"following":{"data":1,"pmic":1,"format":1,"code":1,"values":1}
,"configuration":{"files":1,"file":1,"information":1,"data":1,"system":1,"tuple":1,"identified":1,"rail":1,"without":1,"default":1,"required":1,"devices":1,"baseboard":1,"p2597":1,"registers":1,"uses":1,"example":1}
,"tegrabl_mb1_bct.h":{"header":1}
,"header":{"file":1}
,"required":{"stage":1,"interface":1,"based":1,"mb1":1,"commands":1,"multiple":1,"mmio":1,"split":1,"however":1,"reset":1}
,"oem":{"mb1":1}
,"offers":{"perform":1}
,"perform":{"platform":1,"configuration":1,"recommended":1}
,"specific":{"initialization":1,"commands":1,"parameters":1,"example":1,"configuration":1}
,"initialization":{"sets":1,"spe-can":1}
,"sets":{"secure":1,"commands":1}
,"secure":{"control":1,"register":1,"start":1}
,"control":{"register":1,"fields":1,"bpmp":1,"apb":1,"axi-cbb":1,"controller":1,"aon":1,"can0":1,"can1":1}
,"register":{"scr":1,"configuration":1,"address":1,"data":1,"size":1,"addresses":1,"absolute":1,"configurations":1,"programmed":1,"values":1,"value":1}
,"files":{"specify":1}
,"pinmux":{"gpios":1,"gpio":1,"configuration":1,"address":1,"domain":1,"used":1,"unused":1,"level":1}
,"gpios":{"configuration":1}
,"prod":{"setting":1,"configuration":1,"address":1,"domain":1}
,"pad":{"voltage":1,"control":1,"configuration":1}
,"voltage":{"setting":1,"configuration":1,"levels":1,"pads":1,"higher":1,"lower":1,"required":1,"rail":1,"reprogram":1,"register":1}
,"pmic":{"setting":1,"configuration":1,"configurations":1,"command":1,"parameter":1,"rail-names":1,"rail-name":1,"mbldp":1,"consider":1,"default":1,"jetson":1,"pmic":1}
,"top":{"bootloader":1}
,"bootloader":{"platform":1,"kernel":1}
,"ver":{"bct":1}
,"gpio":{"configuration":1,"address":1,"pinmux":1}
,"file":{"provides":1,"located":1,"provide":1,"need":1,"sequence":1,"load":1,"created":1,"based":1}
,"provides":{"pinmux":1}
,"typical":{"format":1,"configurations":1,"rail":1}
,"format":{"data":1,"configuration":1,"supports":1,"support":1,"address":1,"follows":1}
,"address":{"data":1,"range":1,"value":1,"absolute":1,"mask":1,"modifies":1,"pad":1,"device":1,"register":1,"size":1,"bpmp-fw":1,"mb2-fw":1,"sce-fw":1,"audio-protected":1,"ape-fw":1,"location":1}
,"pair":{"mb1":1}
,"allows":{"writes":1,"scr":1}
,"writes":{"pinmux":1,"back":1}
,"range":{"table":1}
,"tegra186-mb1-bct-pinmux-gpio-":{"board":1}
,"board":{"board_revision":1}
,"board_revision":{".cfg":1}
,"domain":{"name":1}
,"name":{"gpio":1,"prefix":1}
,"absolute":{"register":1,"addresses":1}
,"value":{"32-bit":1,"address":1,"mb1":1,"writes":1,"bytes":1,"data":1,"mask":1,"block-count":1,"reg_name":1,"less":1,"field":1,"pll-aon":1,"corresponds":1,"ios":1}
,"32-bit":{"data":1}
,"device-side":{"implementation":1,"code":1}
,"write":{"value":1,"val":1,"correct":1,"commands":1,"configuration":1}
,"used":{"pins":1,"property":1,"pmic":1,"eliminate":1,"ape-fw":1,"mb1":1,"different":1}
,"pinmux.0x02434060":{"value1":1}
,"value1":{"gen1_i2c_scl_pc5.padctl_conn_gen1_i2c_scl_0":1,"gen1_i2c_sda_pc6.padctl_conn_gen1_i2c_sda_0":1,"gpio_wan4_ph0.padctl_conn_gpio_wan4_0":1,"gpio_wan3_ph1.padctl_conn_gpio_wan3_0":1}
,"pinmux.0x02434064":{"value2":1}
,"value2":{"gen1_i2c_scl_pc5.padctl_conn_cfg2tmc_gen1_i2c_scl_0":1,"gen1_i2c_sda_pc6.padctl_conn_cfg2tmc_gen1_i2c_da_0":1,"gpio_wan4_ph0.padctl_conn_cfg2tmc_gpio_wan4_0":1,"gpio_wan3_ph1.padctl_conn_cfg2tmc_gpio_wan3_0":1}
,"pinmux.0x02434068":{"value1":1}
,"pinmux.0x0243406c":{"value2":1}
,"unused":{"pins":1}
,"pins":{"low-power":1,"pads":1}
,"low-power":{"configuration":1}
,"pinmux.0x02434040":{"value1":1}
,"pinmux.0x02434044":{"value2":1}
,"pinmux.0x02434048":{"value1":1}
,"pinmux.0x0243404c":{"value2":1}
,"setting":{"configuration":1,"controller":1,"rail":1,"voltages":1,"initializing":1,"voltage":1,"required":1}
,"system":{"characterization":1,"boot":1,"power":1,"pmic":1,"using":1,"module":1,"temperature":1,"team":1}
,"characterization":{"interface":1}
,"interface":{"controller":1,"work":1,"operate":1,"power":1,"pad":1}
,"controller":{"settings":1,"level":1,"instance":1,"i2c":1,"frequency":1,"register":1}
,"work":{"reliably":1,"level":1}
,"reliably":{"given":1}
,"given":{"platform":1,"interface":1,"rail":1,"rails":1,"blocks":1,"block":1}
,"level":{"separately":1,"pad":1}
,"separately":{"pinmux":1}
,"tuple":{"register":1}
,"mask":{"data":1,"value":1,"mask":1,"data0":1}
,"reads":{"data":1}
,"modifies":{"based":1}
,"based":{"mask":1,"interface":1,"power":1,"platform":1,"location":1,"above":1}
,"back":{"address":1}
,"tegra186-mb1-bct-prod-":{"board":1}
,"prefix":{"setting":1}
,"bytes":{"unsigned":1}
,"val":{"read":1,"val":1,"mask":1,"address":1}
,"read":{"address":1,"read-modify-write":1,"written":1}
,"prod.0x02436010.0x00006000":{"0x00002000":1}
,"0x00002000":{"sdmmc4_dat7":1,"sdmmc4_dat6":1,"sdmmc4_dat5":1,"sdmmc4_dat4":1,"sdmmc4_dat3":1}
,"sdmmc4_dat7":{"drv_type":1}
,"drv_type":{"drive_2x":1}
,"prod.0x02436014.0x00006000":{"0x00002000":1}
,"sdmmc4_dat6":{"drv_type":1}
,"prod.0x02436018.0x00006000":{"0x00002000":1}
,"sdmmc4_dat5":{"drv_type":1}
,"prod.0x0243601c.0x00006000":{"0x00002000":1}
,"sdmmc4_dat4":{"drv_type":1}
,"prod.0x02436020.0x00006000":{"0x00002000":1}
,"sdmmc4_dat3":{"drv_type":1}
,"pads":{"designed":1,"enable":1,"consequently":1}
,"designed":{"support":1}
,"support":{"multiple":1,"read":1,"read-modify-write":1}
,"multiple":{"voltage":1,"blocks":1,"devices":1,"commands":1}
,"levels":{"given":1}
,"operate":{"1.2":1,"temperature":1}
,"1.2":{"volts":1}
,"volts":{"1.8":1}
,"1.8":{"3.3":1}
,"3.3":{"based":1}
,"power":{"tree":1,"rail":1,"rails":1,"down":1}
,"tree":{"given":1}
,"software":{"write":1}
,"correct":{"voltage":1,"pad":1}
,"enable":{"interface":1,"pwm":1,"ecc":1,"sc7":1,"log":1,"setting":1,"rails":1}
,"higher":{"power":1,"temperature":1}
,"rail":{"pin":1,"damage":1,"voltages":1,"configurations":1,"command":1,"required":1,"defined":1,"name":1,"customizing":1,"specific":1,"blocks":1,"data":1,"per":1}
,"pin":{"work":1}
,"lower":{"power":1}
,"damage":{"soc":1}
,"soc":{"pads":1,"registers":1}
,"consequently":{"configuring":1}
,"configuring":{"correct":1,"pwm":1,"generic":1,"security":1,"bridge":1}
,"tegra":{"t-arch":1}
,"t-arch":{"-mb1-bct-pad-quill-":1,"-mb1-bct-pmic-quill-":1}
,"-mb1-bct-pad-quill-":{"board":1}
,"pmc":{"address":1,"domain":1}
,"pmc.0x0c36003c":{"0x0000003e":1}
,"0x0000003e":{"pmc_impl_e_18v_pwr_0":1}
,"pmc.0x0c360040":{"0x00000079":1}
,"0x00000079":{"pmc_impl_e_33v_pwr_0":1}
,"during":{"system":1,"transfer":1,"dummy":1}
,"enables":{"system":1,"fuse":1,"shutdown":1,"disables":1}
,"rails":{"cpu":1,"may":1,"configuration":1,"indexed":1,"pmic":1,"brought":1,"perform":1}
,"cpu":{"sram":1,"command":1,"rails":1,"nic":1,"frequency":1,"parameters":1,"means":1}
,"sram":{"core":1,"commands":1}
,"core":{"system":1,"commands":1,"rail":1}
,"configurations":{"typical":1,"i2c":1,"divided":1,"pmic":1,"som":1}
,"enabling":{"rails":1,"setting":1,"configuring":1}
,"fps":{"configurations":1}
,"voltages":{"rails":1}
,"may":{"require":1,"high":1}
,"i2c":{"command":1,"commands":1,"pulse":1,"pwm":1,"mmio":1,"type":1,"type-specific":1,"information":1,"specific":1,"mmios":1,"platform":1,"settings":1,"bus":1,"controller":1}
,"command":{"devices":1,"400khz":1,"domains":1,"related":1,"sequence":1,"attempts":1,"wait":1,"commands":1,"given":1,"blocks":1,"type":1}
,"mmio":{"access":1,"commands":1,"i2c":1}
,"access":{"soc":1,"delays":1}
,"registers":{"either":1,"address":1,"configuring":1,"scrs":1}
,"either":{"read-modify-write":1,"mmio":1,"configured":1}
,"read-modify-write":{"write-only":1,"format":1,"sequence":1}
,"delay":{"commands":1,"provided":1,"required":1,"microseconds":1}
,"rail-specific":{"configurations":1,"parameters":1}
,"commands":{"mmio":1,"sequence":1,"read-modify-write":1,"enabling":1,"pwm":1,"related":1,"thermal":1,"shutdown":1,"divided":1,"required":1,"broken":1,"commands":1,"sent":1,"given":1,"type":1,"different":1,"block":1,"either":1,"indexed":1,"command-index":1,"follows":1,"enable":1,"per":1,"blocks":1,"send":1,"used":1,"reset":1}
,"delays":{"platform-specific":1}
,"provide":{"configuration":1}
,"mb1-cfg":{"format":1}
,"pulse":{"width":1}
,"width":{"modulation":1,"qspi":1}
,"modulation":{"pwm":1}
,"pwm":{"commands":1,"controller":1,"i2c":1,"specific":1,"clock":1,"periods":1,"regulator":1,"just":1,"type":1}
,"7-bit":{"slave":1}
,"slave":{"address":1}
,"amount":{"delay":1}
,"size":{"device":1,"i2c":1,"register":1,"parameters":1,"bits":1,"carveout":1,"cpu-bl":1,"mb2":1}
,"device":{"registers":1,"side":1,"i2c":1,"address":1,"sequence":1,"cooled":1,"settings":1,"internal":1,"different":1}
,"divided":{"following":1,"blocks":1}
,"generic":{"general":1,"format":1,"rail":1,"rails":1,"setting":1}
,"general":{"pmic":1}
,"related":{"cpu":1,"gpu":1,"sram":1,"core":1,"memory":1,"configurations":1}
,"gpu":{"commands":1}
,"mem":{"commands":1}
,"thermal":{"commands":1,"configurations":1}
,"shutdown":{"commands":1,"related":1,"using":1}
,"identified":{"given":1}
,"side":{"code":1}
,"code":{"ignores":1,"snippets":1,"scr":1,"lists":1}
,"ignores":{"configuration":1}
,"defined":{"unique":1}
,"unique":{"parsing":1,"ids":1}
,"parsing":{"bct":1}
,"binary":{"easier":1}
,"easier":{"unique":1}
,"ids":{"follows":1}
,"-mb1-bct-pmic-quill-":{"board":1}
,"review":{"power":1}
,"customizing":{"carrier":1}
,"carrier":{"board":1}
,"common":{"parameters":1,"rail":1}
,"parameter":{"value":1,"blocks":1}
,"rail-names":{"rail-id":1}
,"rail-id":{"parameters":1,".block-count":1,".block":1}
,"parameters":{"value":1,"following":1,"required":1,"prefixed":1,"follows":1,"generic":1}
,"number":{"allowed":1,"rails":1,"command":1,"commands":1}
,"allowed":{"command":1,"operate":1}
,"wait":{"timeout":1,"time":1,"system":1}
,"timeout":{"microseconds":1}
,"microseconds":{"issuing":1,"provided":1,"command":1}
,"issuing":{"bus":1}
,"bus":{"clear":1,"frequency":1,"mb1":1,"during":1}
,"clear":{"command":1}
,"time":{"calculated":1,"mb1":1,"accessing":1}
,"calculated":{"microseconds":1}
,"provided":{"parameter":1,"command":1}
,"need":{"configured":1,"functional":1,"change":1}
,"pmic.command-retries-count":{"value":1,"u32":1}
,"pmic.wait-before-start-bus-clear-us":{"value":1,"u32":1}
,"pmic.rail-count":{"value":1,"u32":1}
,"blocks":{"block":1,"i2c":1,"given":1,"indexed":1,"module":1,"blocks":1,"contain":1,"aoblocks":1}
,"block":{"given":1,"contains":1,"contain":1,"delay":1,"count":1,"identification":1,"commands":1,"follows":1}
,"indexed":{"starting":1,"facilitate":1,"list":1}
,"contains":{"either":1,"i2c":1,"max":1,"setting":1,"bpmp":1,"sce":1,"aon\u2019s":1,"rtc2_ao":1,"top_wdt0":1,"top_wdt1":1,"top_wdt2":1}
,"broken":{"multiple":1}
,"type":{"commands":1,"device":1,"either":1,"specific":1,"i2c":1}
,"sent":{"device":1}
,"devices":{"split":1,"system":1,"pmic":1,"ensures":1,"separate":1}
,"split":{"multiple":1,"commands":1}
,"contain":{"command":1,"data":1,"initial":1,"multiple":1}
,"different":{"delay":1,"configurations":1,"different":1,"blocks":1,"reset":1}
,"prefixed":{"following":1}
,"rail-name":{"rail-id":1,".block-count":1}
,".block-count":{"value":1}
,"block-count":{"number":1}
,"identification":{"parameter":1}
,".block":{"index":1,".type":1,".delay":1,".count":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".commands":1}
,"type-specific":{"parameters":1}
,"bits":{"8:1":1}
,"8:1":{"byte":1}
,"facilitate":{"multiple":1}
,"starting":{"index":1}
,"index":{"following":1}
,"command-index":{"addr":1}
,"addr":{"mask":1}
,"clock":{"source":1,"control":1,"divider":1,"i2c":1}
,"source":{"freq":1,"value":1}
,"period":{"nanoseconds":1}
,"nanoseconds":{"pwm":1}
,"vout":{"pwm":1}
,"regulator":{"duty":1,"initialization":1}
,"duty":{"cycle":1}
,"cycle":{"100":1}
,"just":{"configure":1}
,"950mv":{"voltage":1}
,"pmic.core.3.block":{".type":1,".controller-id":1,".source-frq-hz":1,".period-ns":1,".min-microvolts":1,".max-microvolts":1,".init-microvolts":1,".enable":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".delay":1,".count":1,".commands":1}
,".type":{"pwm":1,"mmio":1,"i2c":1}
,".controller-id":{"gp_pwm6":1}
,".source-frq-hz":{"102000000":1}
,"102000000":{"102mhz":1}
,".period-ns":{"2600":1}
,"2600":{"384k":1}
,"384k":{"period":1}
,".min-microvolts":{"600000":1}
,".max-microvolts":{"1200000":1}
,".init-microvolts":{"950000":1}
,"snippets":{"show":1}
,"show":{"common":1}
,".delay":{"u32":1,"1000":1}
,".count":{"calculated":1}
,".i2c-controller-id":{"u32":1}
,".slave-add":{"u32":1,"0x78":1,"0x70":1}
,".reg-data-size":{"u32":1}
,".reg-add-size":{"u32":1}
,".commands":{"addr":1,".0x00.0x40":1,".0x07.0xff":1}
,"example":{"usage":1}
,"mbldp":{"cnfgglbl1":1}
,"cnfgglbl1":{"bit":1}
,"pmic.generic.1.block":{".type":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".delay":1,".count":1,".commands":1}
,"0x78":{"7bit:0x3c":1}
,".0x00.0x40":{"0x40":1}
,"0x70":{"7bit:0x38":1}
,".0x07.0xff":{"0x2e":1}
,"gpio3":{"power":1}
,"down":{"slot":1,"device":1,"temperature":1,"below":1}
,"consider":{"following":1}
,"correcting":{"pmic":1}
,"default":{"configuration":1,"otp":1,"visible":1,"100":1}
,"without":{"otp":1}
,"otp":{"required":1,"reconfiguration":1,"values":1}
,"however":{"configuration":1}
,"reconfiguration":{"required":1}
,"using":{"i2c":1,"aotag":1,"bct":1}
,"module":{"system":1,"som":1,"used":1}
,"som":{"perform":1,"performed":1,"used":1}
,"baseboard":{"devices":1,"p2597":1}
,"ensures":{"setup":1}
,"setup":{"includes":1}
,"includes":{"different":1}
,"performed":{"successfully":1}
,"assist":{"removing":1}
,"removing":{"blocks":1}
,"property":{"comment":1}
,"comment":{"block":1}
,"module_name":{"device":1}
,"p3310":{"pmic":1}
,"expander":{"configuration":1,"5v0_hdmi_en":1}
,"p2597":{"baseboard":1,"expander":1}
,"security":{"configuration":1,"bridge":1}
,"separate":{"registers":1}
,"bridge":{"client":1,"firewalls":1}
,"client":{"security":1}
,"firewalls":{"known":1}
,"known":{"security":1}
,"scrs":{"scrs":1,"either":1,"re-configuration":1,"loaded":1}
,"configured":{"nvidia":1,"mb1":1}
,"platforms":{"re-configured":1,"custom":1,"mb1":1}
,"re-configured":{"custom":1}
,"custom":{"platforms":1,"configuration":1}
,"list":{"scrs":1,"commands":1}
,"re-configuration":{"custom":1}
,"scr":{"platform":1,"register":1,"configuration":1,"reg_index":1,"domain":1,"programming":1}
,"addresses":{"hard":1,"indexed":1,"firmware":1,"based":1}
,"hard":{"coded":1}
,"coded":{"mb1":1}
,"cannot":{"masked":1,"read":1}
,"masked":{"written":1}
,"written":{"registers":1,"default":1,"register":1}
,"reg_index":{"exclusion-info":1,"matching":1}
,"exclusion-info":{"bit":1,"following":1}
,"bit":{"value":1,"mode":1}
,"matching":{"mb1":1}
,"cfg":{"file":1}
,"include":{"regular":1}
,"regular":{"scrs":1}
,"loaded":{"bct":1,"mb1":1,"firmware":1}
,"cold":{"boot":1}
,"stored":{"context":1}
,"context":{"warm":1}
,"warm":{"boot":1}
,"exclude":{"present":1,"warm":1}
,"present":{"data":1}
,"load":{"data":1}
,"programming":{"mb2":1}
,"mb2":{"later":1,"virtual":1,"programs":1,"carveout":1,"default":1,"bpmp-dma":1}
,"sc7":{"resume":1,"state":1,"disable":1}
,"resume":{"program":1}
,"program":{"bct":1,"cpu":1,"apb":1,"axi_cbb":1,"divider":1,"cpu_nic":1,"can0":1,"can1":1,"value":1}
,"lists":{"scr":1}
,"scr.134.1":{"0x20000000":1}
,"0x20000000":{"gpio_m_scr_00_0":1,"gpio_m_scr_01_0":1}
,"scr.135.1":{"0x20000000":1}
,"miscellaneous":{"configurations":1,"configuration":1}
,"fields":{"misc.cfg":1,"hold":1}
,"misc.cfg":{"follows":1}
,"controls":{"early":1,"dram":1,"sc7":1,"enablement":1,"maximum":1}
,"early":{"initialization":1}
,"spe-can":{"firmware":1}
,"firmware":{"loading":1,"loaded":1,"mb1":1,"memory":1}
,"loading":{"spe-r5":1}
,"spe-r5":{"processor":1}
,"processor":{"boot":1}
,"dram":{"ecc":1,"normally":1}
,"ecc":{"denylisting":1}
,"disable":{"ecc":1,"sc7":1}
,"denylisting":{"enable":1}
,"state":{"entry":1}
,"certain":{"fuses":1}
,"fuses":{"cannot":1}
,"visible":{"field":1}
,"field":{"mb1":1,"directly":1}
,"fuse":{"visibility":1}
,"visibility":{"fuses":1}
,"enablement":{"vpr":1}
,"vpr":{"resize":1}
,"resize":{"functionality":1}
,"eliminate":{"execution":1}
,"execution":{"el3":1}
,"el3":{"secure":1}
,"start":{"el2":1,"location":1}
,"el2":{"bootloader":1}
,"ao-tag":{"register":1}
,"programmed":{"mb1":1}
,"maximum":{"temperature":1}
,"temperature":{"jetson":1,"exceeds":1,"threshold":1,"higher":1,"specified":1,"down":1,"above":1}
,"systems":{"allowed":1}
,"exceeds":{"limit":1}
,"limit":{"auto-shutdown":1}
,"auto-shutdown":{"triggered":1}
,"aotag":{"control":1,"temperature":1}
,"threshold":{"millicentigrade":1,"temperature":1}
,"millicentigrade":{"temperature":1,"mb1":1}
,"specified":{"field":1}
,"waits":{"shuts":1}
,"shuts":{"down":1}
,"aotag.boot_temp_threshold":{"105000":1}
,"cool":{"down":1}
,"resumes":{"booting":1}
,"booting":{"device":1}
,"cooled":{"threshold":1}
,"aotag.cooldown_temp_threshold":{"85000":1}
,"max":{"time":1}
,"below":{"cooldown_temp_threshold":1}
,"cooldown_temp_timeout":{"30000":1}
,"above":{"boot":1,"details":1}
,"hold":{"clock":1}
,"divider":{"values":1,"control":1}
,"values":{"various":1,"values":1,"configured":1,"desired":1}
,"various":{"modules":1,"firmware":1}
,"modules":{"mb1":1}
,"nic":{"divider":1}
,"bpmp":{"cpu":1,"processer":1}
,"less":{"value":1}
,"directly":{"written":1}
,"apb":{"divider":1,"bus":1,"frequency":1}
,"axi_cbb":{"divider":1}
,"axi-cbb":{"bus":1}
,"cpu_nic":{"divider":1}
,"aon":{"spe":1}
,"spe":{"cpu":1,"apb":1}
,"can0":{"divider":1,"controller":1}
,"can1":{"divider":1,"controller":1}
,"initial":{"settings":1,"nafll":1,"address":1}
,"passed":{"cpu-init":1}
,"cpu-init":{"change":1}
,"change":{"settings":1}
,"specify":{"boot":1,"address":1,"operating":1,"clock":1,"width":1,"dma":1,"mode":1,"watchdog":1}
,"means":{"a57":1}
,"a57":{"cpu0":1}
,"cpu0":{"mean":1}
,"mean":{"denver0":1}
,"denver0":{"automotive":1}
,"automotive":{"applications":1}
,"applications":{"a57-cpu0":1}
,"feature":{"passed":1}
,"cpu.ccplex_platform_features":{"0x581":1}
,"initializing":{"adc":1}
,"adc":{"dvc":1}
,"dvc":{"need":1}
,"functional":{"cpu":1}
,"cpu.lsr_dvcomp_params_b_cluster":{"0xc0780f05c":1}
,"cpu.lsr_dvcomp_params_m_cluster":{"0xc0780f05c":1}
,"nafll":{"settings":1}
,"cluster":{"denver":1,"a57":1}
,"cpu.nafll_m_cluster_data":{"0x11f04461":1}
,"cpu.nafll_b_cluster_data":{"0x11f04461":1}
,"ast":{"settings":1}
,"virtual":{"addresses":1,"address":1}
,"programs":{"corresponding":1}
,"corresponding":{"physical":1}
,"physical":{"addresses":1}
,"location":{"loaded":1,"cpu-bl":1,"during":1}
,"memory":{"dram":1}
,"normally":{"need":1}
,"ast.bpmp_fw_va":{"0x50000000":1}
,"ast.mb2_va":{"0x52000000":1}
,"ast.sce_fw_va":{"0x70000000":1}
,"audio-protected":{"region":1}
,"region":{"used":1}
,"ast.apr_va":{"0xc0000000":1}
,"ast.ape_fw_va":{"0x80000000":1}
,"cpu-bl":{"carveout":1}
,"sw_carveout.cpubl_carveout_addr":{"0x96000000":1}
,"sw_carveout.cpubl_carveout_size":{"0x02000000":1}
,"sw_carveout.mb2_carveout_size":{"0x00400000":1}
,"debug":{"functionality":1,"control":1}
,"functionality":{"enabled":1}
,"disabled":{"using":1}
,"configures":{"uart":1,"100sec":1}
,"uart":{"instance":1,"instances":1}
,"instance":{"console":1}
,"console":{"prints":1,"logging":1}
,"valid":{"uart":1}
,"disables":{"console":1}
,"operating":{"frequency":1}
,"frequency":{"i2c":1}
,"100":{"khz":1}
,"i2c.0":{"400":1}
,"i2c.4":{"1000":1}
,"dev":{"parameters":1}
,"corresponds":{"mentioned":1}
,"mentioned":{"qspi":1}
,"qspi":{"clk":1,"bus":1,"mb1":1}
,"clk":{"src":1}
,"src":{"register":1}
,"pllp_out0":{"pllc4_muxed":1}
,"clk_div":{"hence":1}
,"hence":{"clk_rate":1}
,"clk_rate":{"163.2":1}
,"163.2":{"mhz":1}
,"mhz":{"408":1}
,"408":{"mhz":1}
,"mode":{"bit":1,"transfer":1}
,"dma":{"transfer":1,"qspi":1}
,"transfer":{"mode":1,"dma":1,"pio":1}
,"bpmp-dma":{"used":1}
,"gpc-dma":{"bpmp-dma":1}
,"dummy":{"cycles":1}
,"cycles":{"allow":1,"data":1}
,"allow":{"device":1}
,"internal":{"circuits":1}
,"circuits":{"additional":1}
,"additional":{"time":1}
,"accessing":{"initial":1}
,"ios":{"don\u2019t":1}
,"don\u2019t":{"care":1}
,"care":{"may":1}
,"high":{"impedance":1}
,"tx_clk_tap_delay":{"qspi":1}
,"rx_clk_tap_delay":{"qspi":1}
,"watchdog":{"timer":1}
,"timer":{"controller":1,"register":1}
,"processer":{"watchdog":1}
,"wdt.bpmp_wdtcr":{"0x710640":1}
,"0x710640":{"configures":1}
,"sce":{"processer":1}
,"wdt.sce_wdtcr":{"0x707103":1}
,"aon\u2019s":{"watchdog":1}
,"wdt.aon_wdtcr":{"0x700000":1}
,"rtc2_ao":{"watchdog":1}
,"wdt.rtc2_ao_wdtcr":{"0x700000":1}
,"top_wdt0":{"watchdog":1}
,"wdt.top_wdt0_wdtcr":{"0x715016":1}
,"top_wdt1":{"watchdog":1}
,"wdt.top_wdt1_wdtcr":{"0x710640":1}
,"top_wdt2":{"watchdog":1}
,"wdt.top_wdt2_wdtcr":{"0x707103":1}
,"created":{"manually":1}
,"manually":{"follows":1}
,"desired":{"voltage":1}
,"reprogram":{"voltage":1}
,"recommended":{"boot":1}
,"per":{"boot":1,"rail":1}
,"once":{"information":1}
,"collected":{"split":1}
,"communicate":{"device":1}
,"anything":{"different":1}
,"bootrom":{"configuration":1}
,"send":{"device":1}
,"reset":{"path":1,"paths":1}
,"possible":{"type":1}
,"paths":{"collect":1,"aocommand":1}
,"collect":{"information":1}
,"path":{"independently":1}
,"pickup":{"commands":1}
,"put":{"blocks":1}
,"similarly":{"aoblocks":1}
,"aoblocks":{"reset":1}
,"initialize":{"different":1}
,"aocommand":{"aoblock":1}
,"aoblock":{"indexes":1}
,"flashing":{"refer":1,"bootloader":1}
,"refer":{"flashing":1}
}
;Search.control.loadWordPairs(pairs);
