var pairs =
{
"jetson":{"virtual":1,"agx":1,"tx2":1,"nano":1,"tx1":1,"platform":1,"linux":1,"camera":1,"tegra186-camera-imx390-a00.dtsi":1}
,"virtual":{"channel":1,"channels":1}
,"channel":{"gmsl":1,"programming":1,"stream":1,"software-configurable":1,"programmed":1,"nodes":1,"channel":1}
,"gmsl":{"camera":1,"protocol":1,"module":1,"aggregators":1,"setup":1,"communication":1,"based":1,"specifically":1,"deserializer":1,"links":1,"reference":1,"max9296":1,"virtual":1,"kernel":1,"link":1,"device":1,"devices":1,"software":1,"sensor":1,"kits":1}
,"camera":{"framework":1,"monitoring":1,"frame":1,"appears":1,"connector":1,"cases":1,"example":1,"modules":1,"module":1}
,"applies":{"jetson":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"platforms":1,"jetson":1,"soc":1,"supports":1,"csi":1,"muxer":1,"device":1,"tegra194-p2822-0000-camera-imx390-a00.dtsi":1,"tegra194-camera-imx390-a00.dtsi":1,"tegra194-camera-plugin-manager.dtsi":1,"tegra194-p2822-camera-modules.dtsi":1,"developer":1,"vendor":1,"carrier":1}
,"series":{"jetson":1}
,"tx2":{"series":1,"nvidia":1,"jetson":1,"platforms":1,"via":1,"connections":1,"tegra186-quill-camera-imx390-a00.dtsi":1,"tegra186-camera-imx390-a00.dtsi":1,"tegra186-quill-camera-plugin-manager.dtsi":1,"tegra186-quill-camera-modules.dtsi":1,"support":1}
,"topic":{"contains":1}
,"contains":{"details":1,"gmsl-link":1}
,"gigabit":{"multimedia":1}
,"multimedia":{"serial":1}
,"serial":{"link":1}
,"link":{"gmsl":1,"video":1,"configuration":1,"deserializer":1,"sensor":1,"caller\u2019s":1,"ones":1,"enables":1,"disables":1,"first":1,"respective":1,"requests":1,"dual":1,"addresses":1,"proxy":1,"serializer":1}
,"hardware":{"connectivity":1,"module":1,"connection":1,"connections":1}
,"connectivity":{"serializer":1,"controlled":1}
,"serializer":{"deserializer":1,"maxim":1,"transmitting":1,"max9296":1,"link":1,"device":1,"devices":1,"sensor":1,"connected":1}
,"deserializer":{"reference":1,"maxim":1,"receiving":1,"device":1,"connected":1,"assigns":1,"host":1,"devices":1,"drivers":1,"modules":1,"api":1,"link":1,"driver":1,"gets":1,"hosts":1,"0x48":1,"common":1,"aggregator":1,"board":1}
,"reference":{"module":1,"developing":1,"gmsl":1,"setup":1,"sensor":1}
,"module":{"platforms":1,"nvidia":1,"used":1,"jetson":1,"described":1,"validated":1,"connectivity":1,"max9295":1,"connected":1,"device":1,"setup":1,"sensors":1,"configuration":1,"currently":1,"disabled":1}
,"software":{"framework":1,"camera":1}
,"configuration":{"including":1,"valid":1,"four":1,"sensor":1,"details":1,"power":1,"timing":1,"gmsl":1,"device":1,"added":1,"virtual":1,"fields":1,"port-index":1,"module":1,"configuration":1,"below":1,"follow":1,"deserializer":1,"match":1}
,"including":{"virtual":1}
,"nvidia":{"validates":1,"jetson":1,"soc":1,"xavier":1,"max9296":1,"max9295":1,"gmsl-dser-device":1,"gmsl-ser-device":1,"tegra-camera-platform":1}
,"validates":{"reference":1}
,"platforms":{"sony":1,"support":1}
,"sony":{"imx390":1,"dual":1}
,"imx390":{"sensors":1,"raw12":1,"30-001b":1,"30-001c":1,"reference":1,"module":1}
,"sensors":{"source":1,"paired":1,"receiver":1,"via":1,"single":1,"connected":1,"may":1,"device":1,"physical":1,"stream":1,"num_csi_lanes":1,"different":1,"streaming":1}
,"source":{"however":1,"documented":1,"default":1}
,"however":{"reference":1}
,"used":{"starting":1,"reference":1,"v4l2":1,"cases":1,"sensors":1,"devname":1,"sensor":1}
,"starting":{"point":1}
,"point":{"bringing":1}
,"bringing":{"gmsl":1}
,"framework":{"described":1,"programming":1,"sensor":1,"sequence":1,"module":1}
,"described":{"document":1,"uses":1,"jetson":1}
,"document":{"used":1,"applies":1}
,"developing":{"serdes":1}
,"serdes":{"serializer-deserializer":1,"two":1,"programming":1,"kernel":1,"quite":1,"drivers":1}
,"serializer-deserializer":{"links":1,"technology":1}
,"links":{"gmsl":1,"using":1,"serdes":1,"updates":1}
,"uses":{"csi":1,"serializer":1,"stp":1,"virtual":1,"different":1}
,"csi":{"interface":1,"port":1,"mipi":1,"deserializer":1,"connectivity":1,"bricks":1,"aggregator":1,"connection":1,"lane":1,"mode":1,"lanes":1,"channel":1,"number":1,"channels":1,"ports":1,"aggregators":1}
,"interface":{"interface":1,"validated":1}
,"aggregators":{"supported":1,"connected":1,"generally":1}
,"supported":{"nvidia":1,"jetson":1}
,"nano":{"devices":1}
,"devices":{"nvidia":1,"apart":1,"v4l2":1,"sharing":1,"sensor":1,"single":1,"gmsl":1,"physical":1,"proxy":1,"hosted":1,"link":1,"i2c@0":1,"reset":1}
,"tx1":{"platforms":1}
,"support":{"virtual":1,"node":1,"multiple":1,"supplying":1}
,"channels":{"document":1,"supported":1,"isp":1,"without":1,"connect":1,"module":1,"dual-sensor":1,"sensors":1}
,"sensor":{"sony":1,"connections":1,"driver":1,"framework":1,"serializer":1,"source":1,"corresponding":1,"devices":1,"device\u2019s":1,"device":1,"connected":1,"csi":1,"streaming":1,"match":1,"mode":1,"modules":1,"proxy":1,"module":1,"streams":1,"tuning":1,"1.14":1}
,"dual":{"imx390":1,"mode":1,"sensors":1,"gmsl":1}
,"raw12":{"1080p":1,"pixels":1}
,"1080p":{"30fps":1}
,"30fps":{"csi":1,"raw12":1}
,"port":{"lanes":1,"side":1,"port":1,"example":1,"deserializer":1,"aggregator":1,"csi":1,"via":1,"i2c":1,"sensor":1,"jetson":1,"binding":1,"lane":1,"v4l2":1}
,"maxim":{"max9295":1,"max9296":1,"integrated":1}
,"integrated":{"supports":1}
,"supports":{"gmsl":1,"maximum":1}
,"communication":{"link":1,"takes":1}
,"video":{"applications":1,"transfer":1}
,"applications":{"automotive":1}
,"automotive":{"industry":1}
,"industry":{"gmsl":1}
,"based":{"serdes":1,"device":1,"hardware":1,"argus":1}
,"technology":{"uses":1}
,"transmitting":{"side":1}
,"side":{"deserializer":1,"following":1,"nvidia":1,"connected":1}
,"receiving":{"side":1}
,"following":{"diagram":1,"figure":1,"table":1,"code":1,"module":1,"rework":1}
,"diagram":{"shows":1,"above":1}
,"shows":{"high-level":1,"control":1,"maximum":1,"jetson":1,"sensor":1,"four":1,"two":1,"call":1,"i2c":1}
,"high-level":{"architecture":1}
,"architecture":{"gmsl":1,"kernel":1}
,"specifically":{"designed":1}
,"designed":{"advanced":1}
,"advanced":{"driver":1}
,"driver":{"assistance":1,"framework":1,"reference":1,"exposed":1,"without":1,"expose":1,"internally":1,"programming":1,"sensor\u2019s":1,"populates":1,"uses":1,"instead":1,"sensor":1,"unaware":1,"perform":1,"enables":1,"gets":1,"updates":1,"finally":1,"v4l2":1,"fails":1}
,"assistance":{"systems":1}
,"systems":{"adas":1,"cms":1}
,"adas":{"camera":1}
,"monitoring":{"systems":1}
,"cms":{"provide":1}
,"provide":{"video":1}
,"transfer":{"speeds":1}
,"speeds":{"second":1}
,"second":{"uses":1}
,"stp":{"coaxial":1}
,"coaxial":{"cable":1,"cables":1}
,"cable":{"inexpensive":1}
,"inexpensive":{"robust":1}
,"robust":{"emc":1}
,"emc":{"disturbances":1}
,"control":{"data":1,"operations":1,"setup":1,"serializer":1,"pipeline":1,"configuration":1}
,"data":{"clock":1,"streaming":1,"sheet":1}
,"clock":{"connections":1}
,"connections":{"reference":1,"supported":1,"cameras":1,"nvidia":1,"system":1,"device":1}
,"validated":{"jetson":1,"using":1,"csi":1,"hardware":1}
,"setup":{"two":1,"uses":1,"release":1,"data":1,"calls":1,"identified":1,"deserializer":1,"required":1,"shown":1,"performs":1,"port-index":1,"plugin":1,"i2c@0":1,"draw":1}
,"two":{"sensors":1,"different":1,"addresses":1,"links":1}
,"paired":{"respective":1}
,"respective":{"serializers":1,"physical":1,"csi":1}
,"serializers":{"streaming":1,"connected":1,"sensors":1}
,"streaming":{"1080p":1,"pipeline":1,"single":1,"preview":1}
,"pixels":{"csi":1}
,"mipi":{"lanes":1,"adapter":1,"white":1,"adapter\u2019s":1,"adapters":1}
,"connected":{"gmsl":1,"jetson":1,"csi":1,"port":1,"remaining":1,"keeps":1,"link":1,"tegra":1,"adaptor":1,"example":1,"deserializer":1,"single":1}
,"device":{"different":1,"tree":1,"using":1,"stream":1,"boot":1,"physical":1,"data":1,"fixed":1,"proxy":1,"common":1,"properties":1,"addressing":1,"two":1,"initiates":1,"power-on":1,"connected":1,"gmsl":1,"identified":1,"communication":1,"configuration":1,"nodes":1,"module":1,"acts":1,"node":1,"node\u2019s":1,"name":1}
,"different":{"gmls":1,"pixel":1,"location":1,"proxy":1,"csi":1}
,"gmls":{"ports":1}
,"ports":{"ports":1,"gmsl":1,"modules":1}
,"using":{"coaxial":1,"gmsl":1,"sensor":1,"complicated":1,"argus":1}
,"output":{"port":1}
,"soc":{"desired":1}
,"desired":{"csi":1}
,"transmit":{"two":1}
,"pixel":{"streams":1}
,"streams":{"two":1,"ued-u1":1,"sensor":1,"connected":1,"share":1}
,"receiver":{"shared":1,"side":1}
,"shared":{"csi":1,"deserializer":1,"port":1}
,"assigns":{"unique":1,"0x30":1}
,"unique":{"virtual":1,"physical":1,"address":1,"board":1}
,"stream":{"virtual":1,"control":1,"setup":1,"start":1,"deserializer":1,"lane":1}
,"software-configurable":{"via":1}
,"via":{"device":1,"serializers":1,"three":1,"mipi":1,"deserializer":1}
,"tree":{"match":1,"programming":1,"depending":1,"configuration":1,"during":1,"node":1,"assigned":1,"describes":1,"follows":1,"file":1,"full":1,"sensor":1,"nodes":1,"reference":1,"files":1,"additions":1,"defined":1}
,"match":{"stream\u2019s":1,"vc_id":1,"gmsl-link":1,"streams":1}
,"stream\u2019s":{"virtual":1}
,"programmed":{"receiver":1,"boot":1}
,"host":{"two":1,"four":1}
,"four":{"sensors":1,"cameras":1}
,"single":{"shared":1,"model":1,"common":1,"csi":1}
,"aggregator":{"shown":1,"isp":1,"without":1,"uses":1,"hardware":1,"serdes":1,"sharing":1,"data":1,"validated":1}
,"shown":{"following":1,"diagram":1,"diagrams":1,"illustrate":1,"above":1}
,"table":{"below":1,"shows":1}
,"below":{"shows":1,"gmsl-link":1,"reference":1}
,"maximum":{"number":1,"connections":1,"virtual":1,"1.21":1}
,"number":{"sensor":1,"virtual":1,"csi":1}
,"without":{"isp":1,"external":1}
,"three":{"aggregators":1}
,"bricks":{"lane":1,"total":1,"possible":1}
,"lane":{"configuration":1,"fashion":1}
,"valid":{"combination":1}
,"above":{"shows":1,"separate":1,"full":1,"setup":1,"based":1,"match":1}
,"cameras":{"virtual":1,"csi":1,"running":1,"sharing":1}
,"isp":{"virtual":1}
,"total":{"csi":1,"number":1}
,"possible":{"lane":1}
,"remaining":{"csi":1}
,"connect":{"four":1}
,"muxer":{"sends":1}
,"sends":{"camera":1}
,"frame":{"different":1,"rate":1}
,"location":{"memory":1}
,"appears":{"separate":1}
,"separate":{"v4l2":1,"kernel":1,"statically":1}
,"v4l2":{"device":1,"sensor":1,"framework":1,"camera":1,"application":1}
,"figure":{"below":1,"shows":1}
,"max9295":{"max9296":1,"serializer":1}
,"max9296":{"serdes":1,"deserializer":1}
,"may":{"connected":1}
,"platform":{"via":1,"device":1}
,"adapter":{"mipi":1,"pca9546":1}
,"white":{"cables":1}
,"cables":{"plugged":1}
,"plugged":{"platform\u2019s":1}
,"platform\u2019s":{"camera":1}
,"connector":{"socket":1,"port":1,"jetson":1}
,"socket":{"several":1}
,"several":{"ways":1}
,"ways":{"aggregator":1}
,"section":{"describes":1,"summarizes":1}
,"describes":{"kernel":1,"hardware":1,"properties":1,"sensor":1}
,"kernel":{"drivers":1}
,"drivers":{"device":1,"devices":1,"serializer":1,"registered":1,"separate":1,"perform":1,"control":1,"configuration":1,"during":1,"whereas":1,"stream-on":1}
,"programming":{"required":1,"happens":1,"sensor":1,"module":1}
,"required":{"gmsl":1,"serdes":1,"on-board":1,"jetson":1}
,"apart":{"sensor":1,"csi":1}
,"exposed":{"rest":1}
,"rest":{"system":1,"configuration":1}
,"system":{"generic":1,"static":1}
,"generic":{"v4l2":1}
,"external":{"aggregator":1}
,"happens":{"hood":1}
,"hood":{"sensor":1}
,"registered":{"client":1}
,"client":{"programmable":1}
,"programmable":{"isolated":1,"functionality":1}
,"isolated":{"devices":1}
,"reason":{"design":1,"devices":1}
,"design":{"certain":1}
,"certain":{"fixed":1}
,"fixed":{"sequence":1,"similar":1}
,"sequence":{"operations":1,"sensors":1}
,"operations":{"performed":1,"power":1}
,"performed":{"serdes":1}
,"quite":{"fit":1}
,"fit":{"generic":1}
,"statically":{"linked":1,"device":1}
,"linked":{"sensors":1}
,"depending":{"hardware":1}
,"controlled":{"sensor":1,"deserializer":1,"via":1}
,"expose":{"programmable":1}
,"functionality":{"directly":1}
,"directly":{"user":1,"serializer":1}
,"user":{"clients":1}
,"internally":{"links":1}
,"perform":{"device":1,"gmsl":1}
,"power":{"control":1,"management":1,"shared":1,"rails":1,"sources":1,"supply":1,"jetson":1}
,"release":{"stream":1}
,"start":{"stop":1}
,"stop":{"based":1}
,"modules":{"serializer":1,"configuration":1,"device":1,"expect":1,"similar":1,"tegra186-quill-camera-plugin-manager.dtsi":1}
,"api":{"described":1,"references":1}
,"linux":{"drive":1}
,"drive":{"package":1}
,"package":{"api":1}
,"structure":{"gmsl_link_ctx":1,"fields":1,"passes":1,"context":1,"sensor":1}
,"gmsl_link_ctx":{"core":1}
,"core":{"entity":1}
,"entity":{"defines":1}
,"defines":{"entire":1}
,"entire":{"link":1}
,"documented":{"api":1}
,"fields":{"populated":1,"shown":1}
,"populated":{"sensor":1,"serializer":1}
,"sensor\u2019s":{"gmsl-link":1}
,"gmsl-link":{"node":1,"device":1}
,"node":{"device":1,"details":1,"contains":1,"describes":1,"sensor":1,"configuration":1,"specifies":1,"fragment-imx390@0":1,"platform\u2019s":1}
,"during":{"device":1,"power-on":1,"probing":1}
,"boot":{"module":1,"time":1}
,"details":{"fields":1,"found":1,"platform":1,"sensor":1}
,"populates":{"instance":1}
,"instance":{"structure":1}
,"passes":{"serializer":1}
,"found":{"structure":1}
,"context":{"during":1}
,"power-on":{"control":1,"call":1,"request":1}
,"pipeline":{"setup":1}
,"defined":{"structure":1,"platform":1,"device":1,"using":1}
,"corresponding":{"serializer":1}
,"physical":{"i2c":1}
,"i2c":{"slave":1,"bus":1,"save":1,"expander":1,"node":1}
,"slave":{"address":1,"addresses":1,"causes":1}
,"address":{"assigned":1,"user-defined":1,"device":1,"conflicts":1,"proxy":1,"defined":1,"0x1a":1,"0x62":1,"assignments":1,"conflict":1,"port":1,"0x40":1,"0x60":1,"0x1b":1,"paths":1}
,"assigned":{"according":1,"slave":1,"during":1,"distinct":1,"runtime":1,"sensor":1}
,"according":{"device":1}
,"sheet":{"proxy":1,"additional":1}
,"proxy":{"i2c":1,"addresses":1,"address":1}
,"sharing":{"hardware":1,"csi":1}
,"connection":{"gmsl":1}
,"identified":{"i2c":1,"uniquely":1}
,"bus":{"unique":1,"further":1}
,"addresses":{"physical":1,"statically":1,"proxy":1,"user-configurable":1,"active":1,"devices":1,"0x1a":1,"0x1b":1,"until":1,"currently":1,"instead":1}
,"similar":{"types":1,"naming":1,"mipi":1}
,"types":{"devices":1,"streams":1}
,"model":{"assigned":1}
,"causes":{"address":1}
,"conflicts":{"resolve":1,"driver":1}
,"resolve":{"conflicts":1}
,"call":{"flow":1,"deserializer":1}
,"flow":{"among":1}
,"among":{"gmsl":1,"sensors":1,"sensor":1}
,"management":{"handled":1}
,"handled":{"shared":1}
,"instead":{"sensor":1,"physical":1}
,"device\u2019s":{"driver":1}
,"unaware":{"sensor":1}
,"common":{"among":1,"deserializer":1}
,"stream-on":{"stream-off":1}
,"stream-off":{"calls":1,"controlled":1,"operation":1}
,"calls":{"mapped":1}
,"mapped":{"directly":1}
,"whereas":{"stream-on":1}
,"static":{"device":1}
,"properties":{"drivers":1,"gmsl":1}
,"addressing":{"configured":1}
,"configured":{"platform":1}
,"explained":{"driver":1}
,"0x1a":{"assigned":1,"sensor1":1,"default":1}
,"distinct":{"proxy":1}
,"user-configurable":{"default":1}
,"default":{"0x1b":1,"0x40":1,"serializer":1,"slave":1,"unless":1,"ports":1}
,"0x1b":{"0x1c":1,"sensor1":1,"proxy":1}
,"similarly":{"serializer":1}
,"0x62":{"proxy":1,"ser1":1}
,"0x40":{"0x60":1,"ser1":1,"proxy":1}
,"assignments":{"reference":1}
,"initiates":{"power_on":1}
,"power_on":{"request":1,"deserializer":1}
,"request":{"deserializer":1,"sensor":1}
,"enables":{"gmsl":1}
,"caller\u2019s":{"sensor":1}
,"keeps":{"disabled":1}
,"disabled":{"address":1,"sensor":1}
,"conflict":{"two":1}
,"updates":{"devices":1,"proxy":1,"physical":1}
,"active":{"link":1}
,"ones":{"defined":1}
,"follows":{"procedure":1}
,"procedure":{"gmsl":1}
,"gets":{"power_on":1,"power-on":1}
,"save":{"addresses":1}
,"hosted":{"deserializer":1}
,"example":{"reference":1,"platform":1,"below":1}
,"disables":{"gmsl":1}
,"first":{"communicates":1}
,"communicates":{"serializer":1}
,"sensor1":{"0x62":1,"0x40":1}
,"ser1":{"updates":1,"performs":1}
,"performs":{"steps":1,"port":1}
,"steps":{"gmsl":1}
,"requests":{"power_on":1}
,"finally":{"sets":1}
,"sets":{"gmsl":1}
,"mode":{"thus":1,"device":1,"imx390_mode_1920x1080_crop_30fps":1,"review":1}
,"thus":{"device":1}
,"uniquely":{"i2c":1}
,"further":{"device":1}
,"takes":{"place":1}
,"place":{"proxy":1}
,"until":{"reboot":1,"resolved":1}
,"currently":{"programmed":1,"available":1,"unique":1}
,"time":{"during":1}
,"probing":{"due":1}
,"due":{"control":1}
,"timing":{"constraints":1}
,"code":{"example":1}
,"diagrams":{"above":1}
,"full":{"details":1}
,"tegra":{"jetson":1}
,"pca9546":{"i2c":1}
,"expander":{"gmsl":1,"assigns":1}
,"compatible":{"nxp":1,"nvidia":1}
,"nxp":{"pca9546":1}
,"hosts":{"serializers":1}
,"adaptor":{"onto":1}
,"onto":{"port":1}
,"i2c@0":{"expander":1,"closing":1,"imx390_a@1b":1,"imx390_b@1c":1}
,"dser":{"max9296@48":1}
,"reg":{"0x48":1,"0x62":1,"0x40":1,"0x60":1}
,"csi-mode":{"2x4":1,"1x4":1}
,"2x4":{"tells":1}
,"tells":{"max":1}
,"max":{"csi":1,"sources":1}
,"max-src":{"max":1}
,"reset":{"power":1}
,"rails":{"controlled":1}
,"reset-gpios":{"&tegra_main_gpio":1}
,"&tegra_main_gpio":{"cam0_rst_l":1}
,"cam0_rst_l":{"gpio_active_high":1}
,"vdd_cam_1v2-supply":{"&en_vdd_cam_1v2":1}
,"ser_prim":{"max9295_prim@62":1}
,"max9295_prim@62":{"default":1}
,"is-prim-ser":{"primary":1}
,"primary":{"ser":1}
,"ser":{"device":1}
,"ser_a":{"max9295_a@40":1}
,"gmsl-dser-device":{"&dser":1}
,"&dser":{"link":1}
,"ser_b":{"max9295_b@60":1}
,"0x60":{"proxy":1}
,"def-addr":{"0x1a":1}
,"gmsl-ser-device":{"&ser_a":1,"&ser_b":1}
,"&ser_a":{"link":1}
,"define":{"clocks":1}
,"clocks":{"pins":1}
,"pins":{"power":1}
,"&ser_b":{"link":1}
,"tca9546@70":{"closing":1,"i2c@0":1}
,"added":{"module":1}
,"few":{"snippets":1}
,"snippets":{"shown":1}
,"illustrate":{"configuration":1}
,"acts":{"controller":1}
,"controller":{"device":1,"maximum":1}
,"src-csi-port":{"port":1}
,"dst-csi-port":{"destination":1}
,"destination":{"csi":1,"assigned":1}
,"serdes-csi-link":{"gmsl":1}
,"1x4":{"sensor":1}
,"st-vc":{"sensor":1}
,"overridden":{"sensor":1}
,"vc-id":{"destination":1,"property":1,"used":1}
,"num-lanes":{"number":1}
,"lanes":{"used":1}
,"ued-u1":{"raw12":1}
,"add":{"vc-id":1}
,"property":{"value":1,"used":1,"gmsl-link":1,"sensor":1,"channel":1,"meaning":1,"vc-id":1,"specifies":1,"similar":1,"default":1,"plugin-manager":1}
,"value":{"respective":1,"two":1}
,"nodes":{"module":1,"used":1,"sensors":1,"port-index":1,"contain":1,"defined":1,"i2c":1}
,"file":{"property":1}
,"vc_id":{"property":1}
,"cases":{"based":1,"mentioned":1}
,"argus":{"camera":1,"cameras":1}
,"mode0":{"mode":1}
,"mclk_khz":{"24000":1}
,"tegra_sinterface":{"serial_a":1}
,"binding":{"csi":1}
,"dual-sensor":{"setup":1}
,"port-index":{"field":1,"property":1}
,"field":{"based":1}
,"imx390_vi_in0":{"endpoint":1}
,"remote-endpoint":{"&imx390_csi_out0":1,"&imx390_csi_out1":1,"&imx390_imx390_out0":1,"&imx390_vi_in0":1,"&imx390_imx390_out1":1,"&imx390_vi_in1":1}
,"imx390_vi_in1":{"endpoint":1}
,"imx390_csi_in0":{"endpoint@0":1}
,"imx390_csi_out0":{"endpoint@1":1}
,"imx390_csi_in1":{"endpoint@2":1}
,"imx390_csi_out1":{"endpoint@3":1}
,"meaning":{"channels":1}
,"contain":{"new":1}
,"new":{"property":1}
,"mentioned":{"above":1}
,"node\u2019s":{"vc-id":1}
,"bus-width":{"property":1}
,"specifies":{"number":1,"details":1}
,"tegra-camera-platform":{"node":1,"device":1}
,"max_lane_speed":{"4000000":1,"appropriate":1}
,"badge":{"imx390_rear":1,"imx390_front":1}
,"position":{"rear":1,"front":1}
,"pcl_id":{"v4l2_sensor":1}
,"devname":{"imx390":1,"property":1}
,"proc-device-tree":{"proc":1,"property":1}
,"proc":{"device-tree":1}
,"device-tree":{"i2c@3180000":1}
,"i2c@3180000":{"tca9546@70":1}
,"num_csi_lanes":{"sensors":1,"total":1}
,"fashion":{"unlike":1}
,"unlike":{"dual":1}
,"appropriate":{"value":1}
,"paths":{"proc-device-tree":1}
,"naming":{"used":1}
,"follow":{"guidelines":1}
,"guidelines":{"sensors":1}
,"refer":{"following":1}
,"plugin":{"manager":1}
,"manager":{"device":1,"sensor":1,"support":1,"board":1}
,"additions":{"plugin":1}
,"files":{"assign":1}
,"assign":{"correct":1}
,"correct":{"values":1}
,"values":{"property":1}
,"plugin-manager":{"sensor-specific":1}
,"sensor-specific":{"module":1}
,"fails":{"register":1}
,"register":{"stream":1}
,"share":{"deserializer":1}
,"generally":{"support":1}
,"multiple":{"identical":1}
,"identical":{"cameras":1}
,"running":{"frame":1}
,"rate":{"sensor":1}
,"review":{"aggregator":1}
,"additional":{"restrictions":1}
,"restrictions":{"using":1}
,"complicated":{"configuration":1}
,"preview":{"capture":1,"flickers":1}
,"capture":{"validated":1}
,"known":{"issues":1}
,"summarizes":{"known":1}
,"issues":{"gmsl":1}
,"general":{"issues":1}
,"flickers":{"scene":1}
,"scene":{"change":1}
,"tuning":{"image":1}
,"image":{"quality":1}
,"quality":{"substandard":1}
,"limitation":{"rework":1}
,"rework":{"apply":1,"max9296":1,"required":1}
,"apply":{"older":1}
,"older":{"gmsl":1}
,"kits":{"draw":1}
,"draw":{"on-board":1,"required":1}
,"on-board":{"deser":1,"1.2":1}
,"deser":{"1.2":1}
,"1.2":{"supply":1,"power":1,"camera":1,"jetson":1}
,"supply":{"needs":1,"enough":1,"1.2":1}
,"needs":{"rework":1}
,"board":{"used":1,"dropped":1,"mipi":1,"lprd-001":1}
,"developer":{"kit":1}
,"kit":{"carrier":1}
,"carrier":{"board":1,"board\u2019s":1}
,"dropped":{"support":1}
,"supplying":{"1.2":1}
,"vendor":{"modules":1}
,"expect":{"1.2v":1}
,"1.2v":{"carrier":1}
,"spare":{"ldo":1}
,"ldo":{"sata":1,"supply":1}
,"sata":{"controller":1}
,"1.21":{"vmin":1}
,"vmin":{"requirement":1}
,"requirement":{"imx390":1}
,"1.14":{"range":1,"1.26":1}
,"range":{"1.14":1}
,"1.26":{"ldo":1}
,"enough":{"supply":1}
,"board\u2019s":{"camera":1}
,"adapter\u2019s":{"board":1}
,"lprd-001":{"used":1}
,"adapters":{"imx274":1}
,"imx274":{"imx185":1}
,"imx185":{"work":1}
,"work":{"around":1}
,"around":{"issue":1}
,"issue":{"until":1}
,"resolved":{"imx390":1}
}
;Search.control.loadWordPairs(pairs);
