var pairs =
{
"jetson":{"xavier":1,"agx":1,"registers":1}
,"xavier":{"jetson":1,"series":1,"devices":1,"device":1,"boot":1,"p2888":1,"development":1,"developer":1,"production":1,"module":1,"platforms":1,"hardware":1}
,"agx":{"xavier":1}
,"series":{"mb1":1,"devices":1}
,"mb1":{"platform":1,"mb2":1,"bct":1,"executes":1,"owned":1,"stage":1,"allows":1,"reads":1,"writes":1,"enables":1,"device":1,"entry":1,"skip":1,"supports":1,"additional":1,"loads":1,"load":1,"based":1,"properties":1,"feature":1,"loading":1,"write":1,"until":1,"documented":1,"uses":1,"waits":1,"resumes":1,"configure":1,"allocate":1,"ast":1}
,"platform":{"configuration":1,"calls":1,"prod":1,"t19x":1,"bct":1,"software":1,"platform":1,"i2c":1,"configurations":1,"features":1}
,"applies":{"nvidia":1,"e.g":1}
,"nvidia":{"jetson":1,"signed":1,"oem":1,"platform":1}
,"topic":{"nvidia":1}
,"devices":{"collectively":1,"term":1,"mb1":1,"pinmux":1,"prod":1,"pins":1,"split":1,"separate":1,"uphy":1}
,"collectively":{"described":1}
,"described":{"jetson":1,"below":1}
,"term":{"jetson":1}
,"device":{"understood":1,"registers":1,"side":1,"-tegra194-mb1-bct-pmic-":1,"type":1,"jetson-nx":1,"i2c":1,"address":1,"sequence":1,"configuration":1,"storage-device":1,"controller":1,"value":1,"mb1":1,"cools":1}
,"understood":{"refer":1}
,"refer":{"two":1}
,"two":{"types":1,"byte":1}
,"types":{"devices":1,"mapped":1}
,"boot":{"sequence":1,"flow":1,"mb1":1,"devices":1,"configuration":1,"component":1,"stage":1,"paths":1,"properties":1,"temperature":1,"temperate":1,"carveout":1,"stages":1}
,"sequence":{"jetson":1,"may":1,"rail":1,"commands":1,"starting":1}
,"mb2":{"mb1":1,"executes":1,"program":1,"instead":1,"file":1,"bootloader":1,"feature":1,"although":1,"rather":1,"ast":1,"address-translation":1,"carveout":1,"mb2":1,"temporary":1,"cpubl":1,"binary":1,"entry":1}
,"bct":{"configure":1,"specifies":1,"uses":1,"required":1,"tegra194-mb1-bct-pinmux-gpio-p2972":1,"tegra186-mb1-bct-prod-":1,"t194-mb1-bct-pad-padvoltage-":1,"configuration":1,"binary":1,"device":1,"scr":1,"mb1":1,"ratchet":1,"t194":1,"specified":1}
,"configure":{"platform-specific":1,"system":1,"enable":1,"pin4":1,"certain":1,"ast":1,"mb2":1}
,"platform-specific":{"static":1,"data":1,"initialization":1,"configuration":1,"configurations":1,"mb1":1,"settings":1}
,"static":{"settings":1}
,"settings":{"mb1":1,"group":1,"required":1,"storage":1,"fit":1}
,"executes":{"cpus":1,"immediately":1}
,"cpus":{"enabled":1}
,"enabled":{"mb2":1,"default":1,"scrub":1,"dram":1,"spin":1,"non-ecc":1,"specifies":1}
,"immediately":{"mb1":1}
,"owned":{"nvidia":1,"various":1}
,"signed":{"nvidia":1,"oem":1}
,"information":{"jetson":1,"typical":1,"format":1,"required":1,"including":1}
,"specifies":{"platform-specific":1,"command":1,"mmio":1,"i2c":1,"pwm":1,"block":1,"delay":1,"number":1,"qspi":1,"fifo":1,"whether":1,"transfer":1,"wait":1,"reset":1,"mss":1,"ction":1,"divn":1,"carveout\u0027s":1,"additional":1}
,"data":{"tegraflash":1,"register":1,"pair":1,"value":1,"address":1,"given":1,"size":1,"support":1,"rate":1,"structures":1}
,"tegraflash":{"invoked":1}
,"invoked":{"flash":1}
,"flash":{"platform":1,"parameters":1}
,"calls":{"tegrabct_v2":1}
,"tegrabct_v2":{"tool":1}
,"tool":{"create":1}
,"create":{"mb1":1}
,"uses":{"following":1,"aotag":1}
,"following":{"data":1,"pmic":1,"format":1,"code":1,"parameters":1,"table":1}
,"configuration":{"files":1,"file":1,"information":1,"data":1,"properties":1,"mb1":1,"identified":1,"rail":1,"registers":1,"values":1,"programmed":1,"support":1,"defined":1,"table":1}
,"tegrabl_mb1_bct.h":{"header":1}
,"header":{"file":1,"bch":1}
,"required":{"stage":1,"given":1,"based":1,"mb1":1,"commands":1,"multiple":1,"mmio":1,"split":1}
,"stage":{"signed":1,"offers":1,"binary":1}
,"oem":{"mb1":1}
,"offers":{"perform":1}
,"perform":{"platform-specific":1}
,"initialization":{"sets":1,"cpu-bl":1}
,"sets":{"secure":1,"blocks":1,"pllaon_base":1}
,"secure":{"control":1,"register":1}
,"control":{"register":1,"knobs":1,"backbone":1}
,"register":{"scr":1,"configuration":1,"address":1,"i2c":1,"facilitate":1,"size":1,"data":1,"onoffcnfg2":1,"onoffcnfg1":1}
,"files":{"specify":1,"may":1,"kept":1}
,"pinmux":{"gpios":1,"gpio":1,"configuration":1,"address":1,"domain":1,"used":1,"unused":1,"level":1,"pad":1}
,"gpios":{"configuration":1}
,"prod":{"setting":1,"configuration":1,"properties":1,"address":1,"domain":1,"configurations":1,"settings":1}
,"pad":{"voltage":1,"control":1,"levels":1,"configuration":1}
,"voltage":{"setting":1,"configuration":1,"levels":1,"pads":1,"higher":1,"lower":1,"required":1,"monitor":1}
,"pmic":{"setting":1,"configuration":1,"configurations":1,"command":1,"cparameter":1,"railname":1,"fps":1,"rail-name":1,"mbldp":1,"rails":1}
,"linux_for_tegra":{"bootloader":1}
,"bootloader":{"t186ref":1,"loads":1}
,"t186ref":{"bct":1}
,"gpio":{"configuration":1,"address":1,"pinmux":1,"mode":1,"expander":1,"interrupt":1,"pins":1,"controller":1,"pin":1,"int0":1,"aa0":1,"aa1":1,"aa2":1}
,"file":{"provides":1,"contains":1,"mb1":1,"located":1,"provide":1,"property":1,"scrs":1,"locked":1,"kept":1,"defines":1,"apply":1,"blocks":1,"along":1,"specifies":1}
,"provides":{"pinmux":1}
,"typical":{"format":1,"configurations":1,"rail":1}
,"format":{"data":1,"supports":1,"support":1,"address":1,"follows":1}
,"address":{"data":1,"range":1,"value":1,"absolute":1,"mask":1,"modifies":1,"pad":1,"within":1,"device":1,"mmio":1,"i2c":1,"size":1,"register":1,"reg-addr":1,"space":1,"mb2":1,"spe-fw":1,"misc":1,"rcm-blob":1,"temporary":1,"spaces":1,"properties":1,"ape":1,"apr":1,"bpmp":1,"sce":1,"rce":1,"camera":1,"specified":1,"carveout":1}
,"pair":{"mb1":1}
,"allows":{"writes":1}
,"writes":{"pinmux":1,"back":1,"specified":1}
,"range":{"table":1}
,"tegra194-mb1-bct-pinmux-gpio-p2972":{"board":1}
,"board":{"revision":1,"device\u2019s":1,"name":1}
,"revision":{".cfg":1,"board":1,"number":1,"module\u2019s":1}
,"device\u2019s":{"board":1}
,"name":{"p3668":1,"gpio":1,"prefix":1,"sdmmc":1,"e.g":1,"boot":1,"firmware":1,"begins":1}
,"p3668":{"jetson":1}
,"p2888":{"jetson":1}
,"number":{"e.g":1,"device":1,"allowed":1,"rails":1,"blocks":1,"commands":1,"command":1,"dummy":1,"ufs":1,"configured":1,"bct":1,"firmware":1,"range":1}
,"e.g":{"a01":1,"sdmmc4":1,"default":1}
,"domain":{"name":1}
,"absolute":{"padctl_a":1,"register":1,"address":1}
,"padctl_a":{"gpio_ctl":1}
,"gpio_ctl":{"aon_gpio":1}
,"aon_gpio":{"register":1}
,"value":{"32-bit":1,"address":1,"mb1":1,"writes":1,"bytes":1,"data":1,"mask":1,"four":1,"specified":1,"parameter":1,"block-count":1,"may":1,"written":1,"enables":1,"minus":1,"pllaon":1,"programmed":1,"program":1,"expected":1}
,"32-bit":{"data":1,"mmio":1,"value":1}
,"device-side":{"implementation":1}
,"write":{"value":1,"val":1,"correct":1,"commands":1,"several":1,"access":1}
,"used":{"pins":1,"ufs":1,"optimize":1,"loading":1,"secureos":1,"executing":1,"various":1,"combined":1}
,"pinmux.0x02434060":{"value1":1}
,"value1":{"gen1_i2c_scl_pc5.padctl_conn_gen1_i2c_scl_0":1,"gen1_i2c_sda_pc6.padctl_conn_gen1_i2c_sda_0":1,"gpio_wan4_ph0.padctl_conn_gpio_wan4_0":1,"gpio_wan3_ph1.padctl_conn_gpio_wan3_0":1}
,"pinmux.0x02434064":{"value2":1}
,"value2":{"gen1_i2c_scl_pc5.padctl_conn_cfg2tmc_gen1_i2c_scl_0":1,"gen1_i2c_sda_pc6.padctl_conn_cfg2tmc_gen1_i2c_da_0":1,"gpio_wan4_ph0.padctl_conn_cfg2tmc_gpio_wan4_0":1,"gpio_wan3_ph1.padctl_conn_cfg2tmc_gpio_wan3_0":1}
,"pinmux.0x02434068":{"value1":1}
,"pinmux.0x0243406c":{"value2":1}
,"unused":{"pins":1}
,"pins":{"low-power":1,"pads":1,"single":1}
,"low-power":{"configuration":1}
,"pinmux.0x02434040":{"value1":1}
,"pinmux.0x02434044":{"value2":1}
,"pinmux.0x02434048":{"value1":1}
,"pinmux.0x0243404c":{"value2":1}
,"common":{"prod":1,"rail-specific":1,"parameters":1,"bct":1}
,"properties":{"configure":1,"correctly":1,"controller":1,"configured":1,"separately":1,"parameters":1,"boolean":1,"described":1,"sdram":1,"control":1,"read":1,"powers":1,"aligned":1}
,"system":{"characterization":1,"characterized":1,"boot":1,"power":1,"pmic":1,"generic":1,"configurations":1}
,"characterization":{"interface":1}
,"interface":{"controller":1,"work":1,"operate":1,"power":1,"pad":1}
,"controller":{"settings":1,"level":1,"prod":1,"pinmux":1,"mode":1,"instance":1,"i2c":1,"t19x":1,"qspiflash":1,"frequency":1,"clock":1,"mb2":1,"carveout":1,"used":1}
,"group":{"properties":1}
,"correctly":{"interface":1}
,"work":{"reliably":1,"level":1}
,"reliably":{"given":1,"platform":1}
,"given":{"platform":1,"interface":1,"address":1,"rail":1,"rails":1,"blocks":1,"block":1}
,"level":{"separately":1,"prod":1,"pad":1}
,"separately":{"pinmux":1,"controller":1}
,"configured":{"tuple":1,"nvidia":1,"customer":1,"owned":1,"access":1,"may":1}
,"tuple":{"register":1}
,"mask":{"data":1,"value":1,"mask":1,"specifies":1,"32-bit":1,"i2c":1,"applied":1,"data0":1}
,"reads":{"data":1}
,"modifies":{"based":1}
,"based":{"mask":1,"interface":1,"power":1,"platform":1,"bootrom":1,"mcvideoprotectsizemb":1}
,"back":{"address":1}
,"tegra186-mb1-bct-prod-":{"board":1}
,"prefix":{"setting":1}
,"bytes":{"unsigned":1}
,"val":{"read":1,"val":1,"mask":1,"address":1}
,"read":{"address":1,"read-modify-write":1,"mmio":1,"written":1,"mb1":1}
,"prod.0x02434064.0x01f1f000":{"0x0001f000":1}
,"0x0001f000":{"padctl_conn_cfg2tmc_gen1_i2c_scl_0":1,"padctl_conn_cfg2tmc_gen1_i2c_sda_0":1}
,"padctl_conn_cfg2tmc_gen1_i2c_scl_0":{"drive":1}
,"drive":{"settings":1,"strength":1}
,"prod.0x0243406c.0x01f1f000":{"0x0001f000":1}
,"padctl_conn_cfg2tmc_gen1_i2c_sda_0":{"drive":1}
,"configurations":{"system":1,"typical":1,"i2c":1,"divided":1,"kept":1}
,"characterized":{"values":1}
,"values":{"interface":1,"mmio":1,"cindex":1,"read":1,"byte":1,"scr":1,"scrs":1,"0-7":1,"reset":1,"watchdog5":1,"defined":1}
,"levels":{"file":1,"given":1}
,"contains":{"controller":1,"either":1,"i2c":1,"platform-specific":1}
,"hardware":{"nvidia":1}
,"t19x":{"platform":1,"configuration":1,"common":1,"eight":1}
,"deviceprod":{"controller-name":1}
,"controller-name":{"controller-id":1,"module\u2019s":1}
,"controller-id":{"mode":1,"module\u0027s":1,"pwm":1}
,"mode":{"address":1,"controller":1,"prod":1,"value":1,"operation":1,"supported":1,"temporary":1}
,"module\u2019s":{"name":1,"revision":1}
,"sdmmc":{"qspi":1,"sata":1,"parameters":1,"parameter":1,"controller":1}
,"qspi":{"i2c":1,"flash":1,"parameter":1,"controller":1,"data":1,"sdr":1,"ddr":1,"bus":1,"lane":1}
,"module\u0027s":{"origin-0":1}
,"origin-0":{"instance":1}
,"instance":{"number":1,"0-7":1,"parameter":1,"instance":1,"storage":1,"kilohertz":1}
,"setting":{"applies":1,"rail":1,"configures":1}
,"default":{"hs400":1,"cold":1,"others":1}
,"within":{"controller":1}
,"four":{"bytes":1}
,"entry":{"prod":1,"pad":1,"value":1,"properties":1,"point":1}
,"deviceprod.qspi.0.default.0x03270004.0x7c00":{"0x0":1}
,"0x0":{"trimmer":1,"auto":1,"soc_gpio10":1}
,"deviceprod.qspi.0.default.0x03270004.0xff":{"0x10":1}
,"0x10":{"trimmer":1,"gpio2":1}
,"deviceprod.qspi.1.default.0x03300004.0x7c00":{"0x0":1}
,"deviceprod.qspi.1.default.0x03300004.0xff":{"0x10":1}
,"deviceprod.sdmmc.3.default.0x034601e4.0x00003fff":{"0x0":1}
,"auto":{"cal":1,"mode":1}
,"cal":{"offsets":1}
,"deviceprod.sdmmc.3.hs400.0x03460100.0x1fff0000":{"0x14080000":1}
,"0x14080000":{"tap":1}
,"tap":{"trim":1}
,"trim":{"values":1,"val":1,"value":1}
,"deviceprod.sdmmc.3.hs400.0x0346010c.0x00003f00":{"0x00000028":1}
,"0x00000028":{"dqs":1}
,"dqs":{"trim":1}
,"deviceprod.sdmmc.3.ddr52.0x03460100.0x1fff0000":{"0x14080000":1}
,"pads":{"designed":1,"enable":1,"consequently":1}
,"designed":{"support":1}
,"support":{"multiple":1,"read":1,"read-modify-write":1,"clients":1}
,"multiple":{"voltage":1,"blocks":1,"devices":1,"commands":1}
,"operate":{"1.2":1}
,"1.2":{"volts":1}
,"volts":{"1.8":1}
,"1.8":{"3.3":1}
,"3.3":{"based":1}
,"power":{"tree":1,"rail":1,"rails":1,"down":1,"cycling":1}
,"tree":{"given":1}
,"software":{"write":1,"version":1}
,"correct":{"voltage":1,"pad":1}
,"enable":{"interface":1,"enable":1,"pwm":1,"hs400":1,"ufs":1,"fast":1,"rate":1,"disable":1,"vpr":1,"checks":1,"shutdown":1,"ccplex":1,"pllx":1}
,"higher":{"power":1,"temperature":1}
,"rail":{"pin":1,"damage":1,"voltages":1,"configurations":1,"command":1,"required":1,"defined":1,"name":1,"customizing":1,"configuration":1,"blocks":1,"data":1}
,"pin":{"work":1,"non-tristate":1,"eight":1,"port":1,"valid":1}
,"lower":{"power":1,"ratchet":1}
,"damage":{"soc":1}
,"soc":{"pads":1,"rail":1,"temperature":1}
,"consequently":{"configuring":1}
,"configuring":{"correct":1,"pwm":1,"configure":1,"bridge":1}
,"t194-mb1-bct-pad-padvoltage-":{"board":1}
,"pad-voltage":{"address":1}
,"specified":{"value":1,"address":1,"block":1,"configuration":1,"first":1,"miscellaneous":1,"field":1}
,"pmc.0x0c36003c":{"0x0000003e":1}
,"0x0000003e":{"pmc_impl_e_18v_pwr_0":1}
,"pmc.0x0c360040":{"0x00000079":1}
,"0x00000079":{"pmc_impl_e_33v_pwr_0":1}
,"during":{"system":1,"boot":1,"rcm":1}
,"enables":{"system":1,"map":1,"disables":1,"disable":1,"checks":1}
,"rails":{"cpu":1,"configuration":1,"sc7":1,"indexed":1,"otp":1}
,"cpu":{"sram":1,"command":1,"rails":1,"cpu0":1,"rail":1,"pwr_req":1,"l2-ecc":1,"frequency":1,"properties":1,"platform":1,"variables":1}
,"sram":{"core":1,"commands":1}
,"core":{"system":1,"commands":1,"core":1,"soc":1,"rail":1}
,"enabling":{"rails":1,"setting":1,"configuring":1}
,"fps":{"configurations":1,"turn":1,"gpio2":1,"slot":1,"programming":1,"fps0":1}
,"voltages":{"may":1}
,"may":{"require":1,"either":1,"hsio":1,"lane":1,"overlap":1}
,"require":{"certain":1,"bootrom":1}
,"certain":{"platform-specific":1,"steps":1,"functionality":1,"fuses":1,"features":1}
,"i2c":{"command":1,"commands":1,"pulse":1,"pwm":1,"mmio":1,"configuration":1,"slave":1,"parameter":1,"controller":1,"type":1,"type-specific":1,"information":1,"specific":1,"mmios":1,"frequency":1,"bus":1}
,"command":{"devices":1,"400khz":1,"domains":1,"related":1,"sequence":1,"attempts":1,"wait":1,"block":1,"specifies":1,"index":1,"commands":1,"given":1,"blocks":1,"type":1,"indexed":1}
,"pwm":{"commands":1,"controller":1,"i2c":1,"parameter":1,"clock":1,"time":1,"regulator":1,"configuring":1,"type":1,"periods":1,"just":1,"mode":1,"gear1":1,"gear2":1,"gear3":1,"gear4":1}
,"commands":{"devices":1,"mmio":1,"sequence":1,"read-modify-write":1,"enabling":1,"pwm":1,"related":1,"thermal":1,"shutdown":1,"specified":1,"specify":1,"divided":1,"required":1,"broken":1,"commands":1,"sent":1,"given":1,"type":1,"different":1,"block":1,"either":1,"indexed":1,"command-index":1,"follows":1,"encoded":1,"include":1,"microseconds":1,"case":1}
,"mmio":{"access":1,"commands":1,"i2c":1,"command":1,"register":1,"mask":1,"type":1,"region":1}
,"access":{"jetson":1,"delays":1,"registers":1,"mode":1,"storage":1,"vpr":1}
,"registers":{"either":1,"address":1,"configuring":1,"scrs":1,"protect":1,"mb1":1}
,"either":{"read-modify-write":1,"common":1,"mmio":1,"configured":1}
,"read-modify-write":{"write-only":1,"format":1,"operations":1,"sequence":1}
,"delay":{"commands":1,"command":1,"provided":1,"required":1,"microseconds":1}
,"entries":{"pmic":1}
,"rail-specific":{"rail-specific":1,"configurations":1,"parameters":1,"commands":1}
,"delays":{"platform-specific":1}
,"provide":{"configuration":1,"information":1}
,"mb1-cfg":{"format":1}
,"pulse":{"width":1}
,"width":{"modulation":1,"value":1}
,"modulation":{"pwm":1}
,"7-bit":{"slave":1,"i2c":1}
,"slave":{"address":1,"register":1,"mask":1}
,"amount":{"delay":1}
,"size":{"device":1,"i2c":1,"bits":1,"register":1,"parameters":1,"temporary":1,"properties":1,"permissions":1,"preferred":1,"size":1,"carveout":1}
,"divided":{"following":1,"blocks":1}
,"generic":{"general":1,"system":1,"pmic":1,"format":1,"rail":1}
,"general":{"pmic":1}
,"related":{"cpu":1,"gpu":1,"sram":1,"core":1,"memory":1,"configurations":1}
,"gpu":{"commands":1}
,"mem":{"commands":1}
,"thermal":{"commands":1,"configurations":1,"external":1,"sensor":1,"alarm":1,"protection":1}
,"shutdown":{"commands":1,"related":1,"max77620":1,"sensor":1,"using":1}
,"identified":{"given":1}
,"side":{"code":1}
,"code":{"ignores":1,"snippets":1}
,"ignores":{"configuration":1}
,"defined":{"unique":1,"gpio":1,"file":1,"block":1,"miscellaneous":1}
,"unique":{"parsing":1,"ids":1,"owner":1,"index":1}
,"parsing":{"bct":1}
,"binary":{"easier":1,"loads":1,"loaded":1,"entry":1}
,"easier":{"unique":1}
,"ids":{"follows":1}
,"-tegra194-mb1-bct-pmic-":{"partnumber":1}
,"partnumber":{"revision":1,"full":1}
,"type":{"device":1,"commands":1,"either":1,"uphy":1,"block":1,"values":1}
,"jetson-nx":{"jetson-agx":1}
,"full":{"part":1}
,"part":{"number":1}
,"p3668-0000":{"jetson":1}
,"development":{"module":1}
,"module":{"distributed":1,"memory":1,"map":1}
,"distributed":{"jetson":1}
,"developer":{"kit":1}
,"p3668-0001":{"jetson":1}
,"production":{"module":1}
,"p2888-0001":{"original":1}
,"original":{"jetson":1}
,"p2888-0004":{"jetson":1}
,"review":{"power":1}
,"customizing":{"carrier":1}
,"carrier":{"board":1}
,"usage":{"common":1,"rail-specific":1,"specifying":1}
,"cparameter":{"value":1}
,"command-retries-count":{"number":1}
,"allowed":{"command":1,"specified":1,"carveout":1}
,"wait-before-start-bus-clear-us":{"determines":1}
,"determines":{"wait":1}
,"wait":{"timeout":1,"time":1,"debugger":1,"boot":1}
,"timeout":{"issuing":1,"microseconds":1}
,"issuing":{"bus":1,"i2c":1}
,"bus":{"clear":1,"width":1,"speed":1}
,"clear":{"command":1}
,"microseconds":{"value":1,"command":1,"delay":1,"wait":1}
,"rail-count":{"number":1}
,"pmic.command-retries-count":{"value":1,"u32":1}
,"pmic.wait-before-start-bus-clear-us":{"value":1,"u32":1}
,"pmic.rail-count":{"value":1,"u32":1}
,"railname":{"rparameter":1,"identifies":1}
,"rparameter":{"value":1}
,"identifies":{"rail":1,"storage":1,"clock":1,"specified":1,"i2c":1,"carveout":1}
,"cpu0":{"cpu":1,"rail":1}
,"cpu1":{"cpu":1}
,"memio":{"memory":1}
,"memory":{"rail":1,"controller":1}
,"external":{"thermal":1}
,"sensor":{"configuration":1,"reset":1,"ao-tag":1,"higher":1}
,"block-count":{"number":1}
,"blocks":{"rail":1,"block":1,"i2c":1,"given":1,"indexed":1,"commands":1,"specified":1,"mentioned":1,"using":1}
,"block":{"bindex":1,"valid":1,"counting":1,"microseconds":1,"index":1,"given":1,"contains":1,"contain":1,"delay":1,"count":1,"identification":1,"commands":1,"multiple":1,"mapping":1,"specification":1}
,"bindex":{".type":1,"index":1,".count":1,".delay":1,".commands":1}
,".type":{"type":1,"specifies":1,"i2c":1,"pwm":1,"mmio":1,"indicating":1}
,"valid":{"values":1,"block":1,"combinations":1}
,"index":{"block":1,"counted":1,"i2c-parameter":1,".type":1,"pwm-command":1,"following":1,"scr":1,"oem-fw":1,"command":1}
,".count":{"number":1,"calculated":1,"specifies":1}
,".delay":{"delay":1,"u32":1,"1000":1}
,".commands":{"cindex":1,".0x53.0x38":1,".0x55.0x38":1,".0x41.0x1c":1,".0x50.0xc0":1,".0x51.0xc0":1,".0x4a.0xc0":1,".0x4b.0xc0":1,".0x4c.0xc0":1,".0x1a.0xff":1,".0x02434080.0x10":1,".0x02214e00.0x3":1,".0x02214e0c.0x1":1,".0x02214e10.0x1":1,".0x02446008.0x400":1,".0x02446008.0x10":1,".0x02434098.0x10":1,".0x03.0x30":1,".0x01.0x30":1,"addr":1,".0x00.0x40":1,".0x07.0xff":1,"command-index":1,".0x42":1,".0x41":1}
,"cindex":{"address":1,"command":1}
,"counted":{"write":1}
,"several":{"commands":1,"groups":1}
,"specify":{"parameters":1,"divider":1,"i2c":1}
,"parameters":{"consecutive":1,"required":1,"prefixed":1,"follows":1,"generic":1,"form":1,"shown":1}
,"consecutive":{"values":1}
,"applied":{"values":1}
,"facilitate":{"read-modify-write":1,"multiple":1}
,"i2c-parameter":{"specifies":1,"following":1}
,"parameter":{"valid":1,"blocks":1,"value":1,"controller-specific":1,"shown":1,"may":1,"following":1}
,"i2c-controller-id":{"i2c":1}
,"slave-add":{"7-bit":1}
,"reg-data-size":{"register":1}
,"bits":{"valid":1,"8:1":1,"3-7":1,"forced":1}
,"byte":{"byte":1,"two":1}
,"reg-add-size":{"register":1}
,"pwm-command":{"specifies":1}
,"pwm-parameter":{"following":1}
,"source-frq-hz":{"pwm":1}
,"clock":{"source":1,"properties":1,"burst":1,"variables":1}
,"source":{"frequency":1,"freq":1,"value":1,"hertz":1}
,"frequency":{"hertz":1,"clock":1,"clk_source_bpmp_cpu_nic":1,"clk_source_bpmp_apb":1,"clk_source_axi_cbb":1,"clk_source_se":1,"clk_source_aon_cpu_nic":1,"clk_source_can1":1,"clk_source_can2":1,"request":1,"i2c":1}
,"period-ns":{"pwm":1}
,"time":{"period":1,"slot":1,"gpio":1,"microseconds":1}
,"period":{"nanoseconds":1}
,"min-microvolts":{"vout":1}
,"vout":{"pwm":1}
,"regulator":{"duty":1,"initialization":1}
,"duty":{"cycle":1}
,"max-microvolts":{"vout":1}
,"cycle":{"100":1}
,"init-microvolts":{"vout":1}
,"turn":{"sd4":1}
,"sd4":{"vdd_ddr_1v1":1,"fps":1,"1.1v":1}
,"vdd_ddr_1v1":{"time":1}
,"gpio2":{"en_ddr_vddq":1,"fps":1}
,"en_ddr_vddq":{"high":1}
,"high":{"time":1,"gpio":1}
,"slpen":{"clrse":1}
,"clrse":{"por":1}
,"por":{"reset":1}
,"pmic.system.block":{".type":1,".controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".block-delay":1,".commands":1}
,".slave-add":{"0x78":1,"0x40":1,"u32":1,"0x70":1,"7\u2011bit":1,"0x3c":1}
,"0x78":{"7bit:0x3c":1}
,".0x53.0x38":{"0x00":1}
,"0x00":{"sd4":1,"sd1":1,"sd2":1,"ldo4":1,"ldo5":1,"ldo6":1,"soc_gpio13":1,"configure":1}
,".0x55.0x38":{"0x10":1}
,".0x41.0x1c":{"0x1c":1}
,"0x1c":{"slpen":1}
,"programming":{"reassign":1,"bpmp":1,"control":1,"security":1,"aon":1}
,"reassign":{"sd1":1}
,"sd1":{"sd2":1,"fps":1}
,"sd2":{"ldo4":1,"fps":1}
,"ldo4":{"ldo5":1,"fps":1}
,"fps0":{"leave":1}
,"leave":{"rails":1}
,".0x50.0xc0":{"0x00":1}
,".0x51.0xc0":{"0x00":1}
,".0x4a.0xc0":{"0x00":1}
,".0x4b.0xc0":{"0x00":1}
,"ldo5":{"fps":1}
,".0x4c.0xc0":{"0x00":1}
,"ldo6":{"fps":1}
,"vddio_ddr":{"1.1v":1}
,"1.1v":{"sd4":1}
,".0x1a.0xff":{"0x28":1}
,"0x28":{"sd4":1}
,"850mv":{"voltage":1}
,"pmic.core.block":{".type":1,".controller-id":1,".source-frq-hz":1,".period-ns":1,".min-microvolts":1,".max-microvolts":1,".init-microvolts":1,".enable":1,".block-delay":1,".commands":1}
,".controller-id":{"soc_gpio10":1,"soc_gpio13":1,"gen2":1,"gp_pwm6":1}
,"soc_gpio10":{"pwm7":1,"pin":1,"tristate":1}
,".source-frq-hz":{"204000000":1,"102000000":1}
,"204000000":{"204mhz":1}
,".period-ns":{"1255":1,"2600":1}
,"1255":{"800khz":1}
,".min-microvolts":{"400000":1,"600000":1}
,".max-microvolts":{"1200000":1}
,".init-microvolts":{"850000":1,"800000":1,"950000":1}
,".block-delay":{"3000":1}
,".0x02434080.0x10":{"0x0":1}
,"800mv":{"voltage":1}
,"pmic.cpu0.block":{".type":1,".controller-id":1,".source-frq-hz":1,".period-ns":1,".min-microvolts":1,".max-microvolts":1,".init-microvolts":1,".enable":1,".block-delay":1,".commands":1}
,"soc_gpio13":{"pwm6":1,"untristate":1}
,"pwr_req":{"cpu_pwr_req_0_pb0":1}
,".0x02214e00.0x3":{"0x00000003":1}
,"0x00000003":{"config":1}
,".0x02214e0c.0x1":{"0x00000000":1}
,"0x00000000":{"control":1,"cpu_pwr_req_0_pb0":1}
,".0x02214e10.0x1":{"0x00000001":1}
,"0x00000001":{"output":1}
,".0x02446008.0x400":{"0x00000000":1}
,"cpu_pwr_req_0_pb0":{"gpio":1,"tristate":1}
,".0x02446008.0x10":{"0x00000000":1}
,".0x02434098.0x10":{"0x00":1}
,"pin4":{"pin5":1,"low":1}
,"pin5":{"output":1,"high":1}
,"output":{"gpio":1}
,"expander":{"0x40":1}
,"low":{"pin5":1}
,"pmic.platform.block":{".type":1,".controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".block-delay":1,".commands":1}
,"0x40":{"7bit:0x20":1}
,".0x03.0x30":{"0x00":1}
,".0x01.0x30":{"0x20":1}
,"0x20":{"configure":1}
,"indexed":{"starting":1,"facilitate":1,"command-index":1}
,"broken":{"multiple":1}
,"sent":{"device":1}
,"split":{"multiple":1}
,"contain":{"command":1}
,"provided":{"command":1}
,"different":{"delay":1,"firmware":1}
,"prefixed":{"following":1}
,"rail-name":{"rail-id":1,".block-count":1}
,"rail-id":{".block-count":1,".block":1}
,".block-count":{"value":1,"specifies":1}
,"identification":{"parameter":1}
,".block":{"index":1,".type":1,".delay":1,".count":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".commands":1,"block-index":1}
,"type-specific":{"parameters":1}
,"8:1":{"byte":1}
,"starting":{"index":1}
,"command-index":{"addr":1,"reg-addr":1}
,"addr":{"mask":1}
,"pwm-specific":{"commands":1,"example":1}
,"nanoseconds":{"pwm":1}
,"just":{"configure":1}
,"950mv":{"voltage":1}
,"pmic.core.3.block":{".type":1,".controller-id":1,".source-frq-hz":1,".period-ns":1,".min-microvolts":1,".max-microvolts":1,".init-microvolts":1,".enable":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".delay":1,".count":1,".commands":1}
,"102000000":{"102mhz":1}
,"2600":{"384k":1}
,"384k":{"period":1}
,"snippets":{"show":1}
,"show":{"common":1}
,".i2c-controller-id":{"u32":1,"identifies":1}
,".reg-data-size":{"u32":1,"register":1}
,".reg-add-size":{"u32":1,"register":1}
,"example":{"usage":1}
,"mbldp":{"cnfgglbl1":1}
,"cnfgglbl1":{"bit":1}
,"pmic.generic.1.block":{".type":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".delay":1,".count":1,".commands":1}
,".0x00.0x40":{"0x40":1}
,"0x70":{"7bit:0x38":1}
,".0x07.0xff":{"0x2e":1}
,"gpio3":{"power":1}
,"down":{"slot":1,"device":1,"temperature":1}
,"security":{"configuration":1,"bridge":1,"bugs":1,"engine":1}
,"separate":{"registers":1}
,"bridge":{"client":1,"firewalls":1}
,"client":{"security":1}
,"firewalls":{"known":1,"t19x":1,"order":1,"specified":1}
,"known":{"security":1}
,"scrs":{"scrs":1,"either":1,"firewalls":1,"programmed":1}
,"platforms":{"configured":1,"may":1}
,"customer":{"custom":1}
,"custom":{"platforms":1}
,"program":{"scrs":1,"coldboot":1,"end":1,"value":1,"pllaon_base":1,"coresight_cfg_system_ctl":1,"coresight_cfg_csite_mc_wr_ctrl":1,"coresight_cfg_csite_mc_rd_ctrl":1,"coresight_cfg_etr_mc_wr_ctrl":1,"coresight_cfg_etr_mc_rd_ctrl":1,"coresight_cfg_csite_cbb_wr_ctrl":1,"coresight_cfg_csite_cbb_rd_ctrl":1,"se0_oem_group_0":1}
,"scr":{"configuration":1,"bct-scr-cbb-mini.cfg":1,"bct-scr-cbb-mini-p3668.cfg":1,"reg_index":1,"firewall":1}
,"list":{"scrs":1}
,"order":{"addresses":1,"configuration":1,"appear":1}
,"addresses":{"predetermined":1}
,"programmed":{"order":1,"mb1":1,"pllaon_misc_1":1}
,"property":{"indexes":1,"name":1}
,"indexes":{"order":1}
,"appear":{"configuration":1}
,"locked":{"without":1}
,"without":{"restricting":1,"filtering":1}
,"restricting":{"access":1}
,"reg_index":{"exclusion-info":1,"index":1}
,"exclusion-info":{"32-bit":1,"bit":1}
,"firewall":{"predefined":1}
,"predefined":{"list":1}
,"bit":{"field":1,"program":1,"sft_rst_wk":1,"sft_rst":1,"regenerate":1,"toggle":1}
,"coldboot":{"sc7-exit":1,"skip":1}
,"skip":{"sc7-exit":1,"certain":1}
,"end":{"mb2":1,"mb1":1,"dram":1,"2gb":1}
,"instead":{"mb1":1}
,"3-7":{"unused":1}
,"scr.161.7":{"0x3f008080":1}
,"0x3f008080":{"tke_aon_scr_wdtscr0_0":1}
,"scr.162.4":{"0x18000303":1}
,"0x18000303":{"dmaapb_1_scr_br_intr_scr_0":1,"dmaapb_1_scr_br_scr_0":1}
,"scr.163.4":{"0x18000303":1}
,"interrupt":{"mapping":1,"hunt":1,"lines":1,"configuration":1,"route":1}
,"mapping":{"configuration":1,"defined":1,"used":1,"carveouts":1}
,"reduce":{"interrupt":1}
,"hunt":{"time":1}
,"single":{"isr":1}
,"isr":{"gpio":1}
,"eight":{"interrupt":1,"interrupts":1}
,"lines":{"lic":1,"form":1}
,"lic":{"enables":1}
,"map":{"gpio":1,"dram":1}
,"interrupts":{"interrupt":1}
,"gpio-intmap.port":{"port-name":1}
,"port-name":{".pin":1,"port":1}
,".pin":{"pin-id":1}
,"pin-id":{"interrupt-id":1,"pin":1}
,"port":{"name":1,"valid":1}
,"interrupt-id":{"interrupt":1}
,"route":{"pin":1}
,"gpio-intmap.port.b.pin.1":{"gpio":1}
,"gpio-intmap.port.aa.pin.0":{"gpio":1}
,"aa0":{"int0":1}
,"gpio-intmap.port.aa.pin.1":{"gpio":1}
,"aa1":{"int0":1}
,"gpio-intmap.port.aa.pin.2":{"gpio":1}
,"aa2":{"int0":1}
,"storage":{"device":1,"devices":1,"controller":1,"mb1":1}
,"storage-device":{"instance":1,"identifies":1,"qspi":1,"sdmmc":1,"ufs":1,"sata":1}
,"qspiflash":{"ufs":1}
,"ufs":{"sdmmc":1,"parameters":1,"parameter":1,"device":1,"lanes":1,"data":1,"modes":1,"initialized":1,"boot":1}
,"controller-specific":{"parameter":1}
,"shown":{"below":1,"following":1}
,"clock-source-id":{"identifies":1,"sdmmc":1}
,"clock-source-frequency":{"frequency":1}
,"interface-frequency":{"qspi":1}
,"enable-ddr-mode":{"specifies":1}
,"rate":{"value":1}
,"sdr":{"mode":1}
,"ddr":{"mode":1}
,"maximum-bus-width":{"maximum":1}
,"maximum":{"qspi":1,"number":1}
,"fifo-access-mode":{"specifies":1}
,"fifo":{"access":1}
,"pio":{"mode":1}
,"dma":{"mode":1}
,"ready-dummy-cycle":{"number":1}
,"dummy":{"cycles":1}
,"cycles":{"per":1}
,"per":{"qspi":1}
,"trimmer1-val":{"trimmer":1}
,"trimmer":{"value":1}
,"trimmer2-val":{"trimmer":1}
,"best-mode":{"highest":1}
,"highest":{"supported":1,"mode":1,"pwm":1,"ccplex":1}
,"supported":{"mode":1,"ufs":1}
,"operation":{"value":1}
,"pd-offset":{"pull-down":1}
,"pull-down":{"offset":1}
,"pu-offset":{"pull-up":1}
,"pull-up":{"offset":1}
,"enable-strobe-hs400":{"enable":1}
,"hs400":{"strobe":1,"dqs":1}
,"dqs-trim-hs400":{"hs400":1}
,"max-hs-mode":{"highest":1}
,"max-pwm-mode":{"highest":1}
,"max-active-lanes":{"maximum":1}
,"lanes":{"value":1,"configured":1}
,"page-align-size":{"alignment":1}
,"alignment":{"pages":1,"alignment":1,"base":1}
,"pages":{"used":1,"allowed":1,"using":1}
,"structures":{"bytes":1,"shared":1}
,"enable-hs-mode":{"specifies":1}
,"whether":{"enable":1,"setting":1,"send":1,"allocate":1,"bad":1}
,"modes":{"value":1}
,"enable-fast-auto-mode":{"specifies":1}
,"fast":{"auto":1,"nafll":1}
,"enable-hs-rate-a":{"specifies":1}
,"enable-hs-rate-b":{"specifies":1}
,"init-state":{"initial":1}
,"initial":{"state":1}
,"state":{"ufs":1}
,"initialized":{"bootrom":1,"blocks":1}
,"bootrom":{"mb1":1,"reset":1,"bring":1,"issues":1,"parameter":1,"reset-name":1}
,"sata":{"parameters":1,"parameter":1,"mphy":1,"ufs":1}
,"transfer-speed":{"specifies":1}
,"transfer":{"speed":1}
,"speed":{"value":1,"khz":1}
,"device.qspiflash.0.clock-source-frequency":{"13000000":1}
,"device.qspiflash.0.interface-frequency":{"13000000":1}
,"device.sdmmc.3.clock-source-id":{"pllp_out0":1}
,"device.sdmmc.3.clock-source-frequency":{"52000000":1}
,"device.sdmmc.3.best-mode":{"ddr52":1}
,"ddr52":{"hs400":1}
,"device.ufs.0.page-align-size":{"4096":1}
,"uphy":{"lane":1,"lanes":1,"needs":1}
,"lane":{"configuration":1,"configurations":1,"pll":1}
,"various":{"ip\u0027s":1,"auxiliary":1,"purposes":1,"data":1}
,"ip\u0027s":{"xusb":1}
,"xusb":{"sata":1}
,"mphy":{"pcie":1}
,"pcie":{"nvlink":1}
,"nvlink":{"mb1":1}
,"supports":{"sata":1}
,"defines":{"uphy":1}
,"loads":{"bpmp":1,"component":1,"firmware":1}
,"bpmp":{"firmware":1,"cpu":1,"apb":1,"carveout":1}
,"firmware":{"bpmp-fw":1,"governed":1,"component":1,"corresponding":1,"components":1,"load":1}
,"bpmp-fw":{"keep":1,"binary":1,"entry":1}
,"keep":{"configuration":1}
,"additional":{"lane":1,"information":1}
,"clients":{"lane":1}
,"apply":{"bpmp-fw":1,"mb2":1}
,"uphy-lane":{"instance-type":1}
,"instance-type":{"uphy-component":1,"type":1}
,"uphy-component":{"owner-id":1,"specifies":1}
,"needs":{"configured":1}
,"hsio":{"nvhs":1}
,"configures":{"lane":1,"wdt_reset_out":1}
,"pll":{"may":1,"number":1,"assigned":1}
,"owner-id":{"unique":1}
,"owner":{"lane":1}
,"oem-fw":{"ratchet":1,"component":1}
,"ratchet":{"configuration":1,"version":1,"fw_index":1}
,"ratcheting":{"mechanism":1}
,"mechanism":{"prevents":1}
,"prevents":{"loading":1}
,"loading":{"old":1,"spe-fw":1,"sce-fw":1,"rce-fw":1,"ape-fw":1,"binaries":1,"kernel":1,"rcm-blob":1}
,"old":{"version":1}
,"version":{"firmware":1,"kept":1,"version":1,"stored":1,"bch":1,"number":1}
,"governed":{"oem-fw":1}
,"kept":{"boot":1}
,"table":{"bct":1}
,"component":{"incremented":1,"compares":1,"header":1,"avoid":1}
,"incremented":{"security":1}
,"bugs":{"fixed":1}
,"fixed":{"mb1":1}
,"compares":{"component\u2019s":1}
,"component\u2019s":{"ratchet":1}
,"stored":{"boot":1}
,"bch":{"software":1,"lower":1}
,"load":{"firmware":1,"entry":1}
,"fw_index":{"loader_name":1,"unique":1}
,"loader_name":{"fw_name":1,"name":1}
,"fw_name":{"ratchet_value":1,"name":1}
,"corresponding":{"fw_index":1}
,"ratchet_value":{"ratchet":1}
,"reset":{"pmic":1,"boot":1,"configuration":1,"cases":1,"case":1,"conditions":1,"type":1,"types":1,"soft":1,"vector":1}
,"t194":{"platforms":1,"misc":1}
,"bring":{"pmic":1}
,"otp":{"values":1}
,"paths":{"done":1}
,"done":{"issuing":1,"without":1}
,"encoded":{"scratch":1}
,"scratch":{"registers":1}
,"cases":{"bootrom":1,"bct":1}
,"issues":{"commands":1}
,"watchdog":{"expiry":1}
,"sc7":{"exit":1,"sc8":1}
,"sc8":{"exit":1,"soft-reset":1}
,"ao-tag":{"sensor":1}
,"hsm":{"reset":1}
,"case":{"three":1}
,"three":{"sets":1}
,"first":{"reset":1}
,"conditions":{"initialized":1}
,"specifying":{"blocks":1,"reset":1}
,"aoblock-count":{"number":1}
,"mentioned":{"file":1}
,"aoblock":{"aoblock-index":1}
,"aoblock-index":{".command-retries-count":1,"identifies":1,".delay-between-command-us":1,".wait-before-start-bus-clear-us":1,".block-count":1,".block":1,"values":1}
,".command-retries-count":{"specifies":1}
,"attempts":{"allowed":1}
,"counting":{"zero":1}
,".delay-between-command-us":{"specifies":1}
,".wait-before-start-bus-clear-us":{"specifies":1}
,"block-index":{".type":1,".count":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".commands":1}
,"indicating":{"i2c":1}
,"7\u2011bit":{"i2c":1}
,"reg-addr":{"value":1,"command":1}
,"written":{"i2c":1,"fuses":1}
,"mapped":{"previously":1}
,"previously":{"declared":1}
,"declared":{"blocks":1}
,"using":{"lines":1,"aotag":1,"smmu":1}
,"reset-name":{".aocommand":1,"specifies":1}
,".aocommand":{"ao-command-index":1}
,"ao-command-index":{"ao-block-id":1,"index":1}
,"watchdog5":{"watchdog4":1}
,"watchdog4":{"sc7":1}
,"soft-reset":{"sensor-aotag":1}
,"sensor-aotag":{"vfsensor":1}
,"vfsensor":{"hsm":1}
,"ao-block-id":{"aoblock-index":1}
,"specification":{"above":1}
,"automatic":{"power":1}
,"cycling":{"max77620":1}
,"onoffcnfg2":{"bit":1}
,"sft_rst_wk":{"default":1}
,"cold":{"boot":1}
,"onoffcnfg1":{"bit":1}
,"bootrom.aoblock":{".command-retries-count":1,".delay-between-commands-us":1,".wait-before-start-bus-clear-us":1,".block-count":1,".block":1}
,"0x3c":{"7bit:0x3c":1}
,".0x42":{"0xda":1,"0x5a":1}
,".0x41":{"0xf8":1}
,"soft":{"reset":1}
,"miscellaneous":{"configurations":1,"configuration":1,"carveout":1}
,"fit":{"category":1}
,"category":{"specified":1}
,"groups":{"properties":1,"mb1":1}
,"feature":{"value":1,"properties":1,"mb2":1,"used":1,"flags":1}
,"boolean":{"flags":1,"enables":1,"controls":1,"specifies":1}
,"flags":{"enable":1}
,"disable":{"certain":1,"vpr":1,"checks":1}
,"functionality":{"mb1":1}
,"below":{"category":1}
,"disable_spe":{"boolean":1}
,"disables":{"mb1":1,"dram":1,"sc7-entry":1,"fuse":1,"video":1,"property":1,"staged":1,"waiting":1,"cpu":1,"loading":1,"combined":1}
,"enable_dram_page_blacklisting":{"boolean":1}
,"dram":{"ecc":1,"error":1,"scrubbing":1,"stages":1,"portions":1,"carveout":1,"region-based":1,"regions":1,"page":1,"32b":1}
,"ecc":{"page":1,"possible":1,"enabled":1,"protected":1}
,"page":{"denylisting":1}
,"denylisting":{"feature":1,"enabled":1}
,"disable_sc7":{"boolean":1}
,"sc7-entry":{"exit":1}
,"exit":{"support":1}
,"disable_fuse_visibility":{"boolean":1}
,"fuse":{"visibility":1,"revision":1}
,"visibility":{"fuse":1,"disabled":1}
,"disabled":{"certain":1,"dram":1,"don\u0027t":1}
,"fuses":{"visible":1,"enabled":1}
,"visible":{"cannot":1}
,"cannot":{"read":1}
,"others":{"disabled":1}
,"enable_vpr_resize":{"boolean":1}
,"video":{"protected":1}
,"protected":{"region":1,"information":1,"dram":1}
,"region":{"vpr":1}
,"vpr":{"resize":1,"carveout":1,"keys":1,"vpr":1}
,"resize":{"feature":1}
,"carveout":{"allocated":1,"enabled":1,"different":1,"bpmp-r5":1,"aon-r5":1,"sce-r5":1,"properties":1,"carveout-type":1,"various":1,"used":1,"bytes":1,"ecc":1,"possible":1,"allocation":1,"mb2":1,"el3":1,"cpubl":1,"ape-fw":1,"bpmp-fw":1,"sce-fw":1,"rce-fw":1,"alignment":1}
,"allocated":{"based":1,"mb1":1}
,"mcvideoprotectsizemb":{"mcvideoprotectwriteaccess":1}
,"mcvideoprotectwriteaccess":{"properties":1}
,"sdram":{"configuration":1}
,"l2_mss_encrypt_regeneration":{"specifies":1}
,"mss":{"encryption":1}
,"encryption":{"keys":1}
,"keys":{"regenerated":1}
,"regenerated":{"carveouts":1}
,"carveouts":{"ramdump":1,"miscellaneous":1,"protected":1,"handled":1,"parameters":1}
,"ramdump":{"reset":1}
,"regenerate":{"tzdram":1,"vpr":1,"gsc":1}
,"tzdram":{"keys":1,"tzdram":1,"carveout":1,"mb2":1}
,"gsc":{"keys":1,"1-31":1,"carveout":1}
,"disable_mb2_glitch_protection":{"boolean":1}
,"checks":{"dcls":1,"disables":1}
,"dcls":{"faults":1}
,"faults":{"tcm":1}
,"tcm":{"parity":1,"cache":1}
,"parity":{"error":1}
,"error":{"tcm":1,"injection":1}
,"cache":{"ecc":1}
,"possible":{"values":1,"large":1}
,"note":{"value":1}
,"begins":{"disable":1}
,"enable_dram_error_injection":{"boolean":1}
,"injection":{"tests":1}
,"enable_dram_staged_scrubbing":{"boolean":1}
,"staged":{"dram":1}
,"scrub":{"entire":1,"dram":1}
,"entire":{"dram":1}
,"stages":{"responsible":1}
,"responsible":{"dram":1}
,"portions":{"uses":1}
,"wait_for_debugger_connection":{"boolean":1}
,"waiting":{"debugger":1}
,"debugger":{"connection":1}
,"don\u0027t":{"wait":1,"send":1}
,"connection":{"end":1,"occurs":1}
,"spin":{"loop":1}
,"loop":{"end":1}
,"until":{"debugger":1}
,"features":{"mb2":1}
,"although":{"apply":1,"sdram":1}
,"rather":{"mb1":1}
,"documented":{"defined":1}
,"along":{"several":1}
,"disable_cpu_l2ecc":{"boolean":1}
,"enable_sce":{"boolean":1}
,"sce-fw":{"mb2":1,"binary":1,"entry":1}
,"enable_rce":{"boolean":1}
,"rce-fw":{"mb2":1,"binary":1,"entry":1}
,"enable_ape":{"boolean":1}
,"ape-fw":{"mb2":1,"binary":1,"entry":1}
,"enable_combined_uart":{"boolean":1}
,"combined":{"uart":1}
,"uart":{"feature":1,"controller":1,"spe":1}
,"enable_emmc_send_cmd0_cmd1":{"boolean":1}
,"controls":{"whether":1,"programming":1,"aon":1,"divm":1,"divp":1}
,"send":{"cmd0":1,"sdmmc4":1}
,"cmd0":{"cmd1":1}
,"cmd1":{"sdmmc4":1}
,"sdmmc4":{"controller":1,"initialization":1,"cmd0":1}
,"optimize":{"sdmmc4":1}
,"aotag":{"properties":1,"always-on":1,"sensor":1,"variables":1}
,"always-on":{"thermal":1}
,"alarm":{"generator":1}
,"generator":{"thermal":1}
,"protection":{"during":1}
,"knobs":{"aotag":1}
,"aotag.boot_temp_threshold":{"boot":1,"97000":1}
,"temperature":{"threshold":1,"measured":1,"specified":1}
,"threshold":{"units":1}
,"units":{"0.001":1}
,"0.001":{"soc":1,"mb1":1}
,"measured":{"aotag":1}
,"field":{"mb1":1}
,"waits":{"shuts":1}
,"shuts":{"down":1}
,"aotag.enable_shutdown":{"boolean":1}
,"ction":{"boot":1}
,"temperate":{"exceeds":1}
,"exceeds":{"aotag.boot_temp_threshold":1}
,"aotag.cooldown_temp_threshold":{"cooldown":1,"87000":1}
,"cooldown":{"temperature":1}
,"resumes":{"booting":1}
,"booting":{"device":1}
,"cools":{"down":1}
,"clock.bpmp_cpu_nic_divider":{"controls":1}
,"clk_source_bpmp_cpu_nic":{"bpmp_cpu_nic_clk_divisor":1}
,"non-zero":{"program":1}
,"clock.bpmp_apb_divider":{"controls":1}
,"apb":{"frequency":1}
,"clk_source_bpmp_apb":{"bpmp_apb_clk_divisor":1}
,"clock.axi_cbb_divider":{"controls":1}
,"backbone":{"cbb":1}
,"cbb":{"frequency":1}
,"clk_source_axi_cbb":{"axi_cbb_clk_divisor":1}
,"clock.se_divider":{"controls":1}
,"engine":{"frequency":1}
,"clk_source_se":{"se_clk_divisor":1}
,"clock.aon_cpu_nic_divider":{"controls":1}
,"aon":{"spe":1,"apb":1,"can1":1,"can2":1}
,"spe":{"cpu":1,"reset":1,"btcm":1}
,"clk_source_aon_cpu_nic":{"aon_cpu_nic_clk_divisor":1}
,"clock.aon_apb_divider":{"controls":1}
,"clock.aon_can0_divider":{"controls":1}
,"can1":{"frequency":1}
,"clk_source_can1":{"can1_clk_divisor":1}
,"clock.aon_can1_divider":{"controls":1}
,"can2":{"frequency":1}
,"clk_source_can2":{"can2_clk_divisor":1}
,"clock.osc_drive_strength":{"oscillator":1}
,"oscillator":{"drive":1}
,"clock.pllaon_divn":{"specifies":1,"0x1f":1}
,"divn":{"value":1}
,"pllaon_divn":{"pllaon_divm":1,"value":1}
,"pllaon_divm":{"pllaon_divp":1,"value":1}
,"pllaon_base":{"pllaon_divn":1,"pllaon_divm":1,"pllaon_divp":1}
,"clock.pllaon_divm":{"controls":1,"0x1":1}
,"divm":{"value":1}
,"pllaon":{"pllaon_base":1}
,"ignored":{"clock.pllaon_divn":1}
,"clock.pllaon_divp":{"controls":1,"0x3":1}
,"divp":{"value":1}
,"pllaon_divp":{"value":1}
,"clock.pllaon_divn_frac":{"value":1,"0x03e84000":1}
,"pllaon_misc_1":{"pllaon_divn_frac":1}
,"ast":{"properties":1,"module":1,"mb1":1}
,"address-translation":{"ast":1}
,"components":{"32\u2011bit":1}
,"32\u2011bit":{"virtual":1}
,"virtual":{"address":1}
,"space":{"various":1}
,"auxiliary":{"processor":1}
,"processor":{"clusters":1}
,"ast.mb2_va":{"virtual":1,"0x52000000":1}
,"bpmp-r5":{"address":1}
,"ast.spe_fw_va":{"virtual":1}
,"spe-fw":{"carveout":1}
,"aon-r5":{"address":1}
,"ast.misc_carveout_va":{"virtual":1,"0x70000000":1}
,"misc":{"carveout":1,"miscellaneous":1,"rcm":1}
,"sce-r5":{"address":1}
,"ast.rcm_blob_carveout_va":{"virtual":1,"0x60000000":1}
,"rcm-blob":{"carveout":1,"during":1}
,"ast.temp_map_a_carveout_va":{"virtual":1,"0x80000000":1}
,"temporary":{"mapping":1,"boot":1}
,"ast.temp_map_a_carveout_size":{"size":1,"0x40000000":1}
,"none":{"virtual":1}
,"spaces":{"above":1}
,"above":{"may":1}
,"overlap":{"mmio":1}
,"aligned":{"mapping":1}
,"clusters":{"properties":1}
,"carveout.ape_ast_va":{"virtual":1,"0x80000000":1}
,"ape":{"carveout":1}
,"carveout.apr_ast_va":{"virtual":1,"0xc0000000":1}
,"apr":{"carveout":1}
,"carveout.bpmp_ast_va":{"virtual":1,"0x50000000":1}
,"carveout.sce_ast_va":{"virtual":1,"0x70000000":1}
,"sce":{"carveout":1}
,"carveout.rce_ast_va":{"virtual":1,"0x70000000":1}
,"rce":{"carveout":1}
,"carveout.camera_task_ast_va":{"virtual":1,"0x78000000":1}
,"camera":{"task":1}
,"task":{"carveout":1}
,"carveout\u0027s":{"preferred":1}
,"preferred":{"base":1}
,"base":{"size":1,"address":1}
,"permissions":{"provide":1}
,"allocate":{"carveouts":1,"carveout":1,"non-ecc":1,"ecc":1}
,"including":{"size":1}
,"carveout-type":{"parameter":1,"identifies":1}
,"1-31":{"gsc":1,"mts":1}
,"mts":{"mts":1,"cpu-ucode":1,"vpr":1}
,"cpu-ucode":{"carveout":1}
,"executing":{"mb2":1}
,"cpubl":{"cpu-bl":1,"misc":1,"carveout":1,"binary":1,"entry":1}
,"cpu-bl":{"carveout":1}
,"shared":{"across":1}
,"across":{"boot":1}
,"rcm":{"rcm":1,"carveout":1,"mode":1}
,"pref_base":{"preferred":1}
,"ecc_protected":{"dram":1}
,"region-based":{"ecc":1}
,"non-ecc":{"protected":1}
,"regions":{"specifies":1}
,"bad_page_tolerant":{"dram":1}
,"bad":{"pages":1}
,"large":{"carveouts":1}
,"handled":{"completely":1}
,"completely":{"component":1}
,"avoid":{"bad":1}
,"smmu":{"mmu":1}
,"allocation":{"done":1,"direction":1}
,"filtering":{"bad":1}
,"combinations":{"carveouts":1}
,"coresight":{"properties":1}
,"coresight.cfg_system_ctl":{"value":1}
,"coresight.cfg_csite_mc_wr_ctrl":{"value":1}
,"coresight.cfg_csite_mc_rd_ctrl":{"value":1}
,"coresight.cfg_etr_mc_wr_ctrl":{"value":1}
,"coresight.cfg_etr_mc_rd_ctrl":{"value":1}
,"coresight.cfg_csite_cbb_wr_ctrl":{"value":1}
,"coresight.cfg_csite_cbb_rd_ctrl":{"value":1}
,"mb2_load_offset":{"offset":1}
,"offset":{"mb2":1,"tzram":1,"el3":1,"cpubl":1,"ape":1,"ape-fw":1,"bpmp":1,"bpmp-fw":1,"sce":1,"sce-fw":1,"rce":1,"rce-fw":1}
,"mb2_entry_offset":{"offset":1}
,"point":{"mb2":1,"tzram":1,"cpubl":1,"ape":1,"bpmp":1,"sce":1,"rce":1}
,"tzram_el3_load_offset":{"offset":1}
,"tzram":{"carveout":1}
,"el3":{"binary":1}
,"tzram_el3_entry_offset":{"offset":1}
,"cpubl_load_offset":{"offset":1}
,"cpubl_entry_offset":{"offset":1}
,"ape_fw_load_offset":{"offset":1}
,"ape_fw_entry_offset":{"offset":1}
,"bpmp_fw_load_offset":{"offset":1}
,"bpmp_fw_entry_offset":{"offset":1}
,"sce_fw_load_offset":{"offset":1}
,"sce_fw_entry_offset":{"offset":1}
,"rce_fw_load_offset":{"offset":1}
,"rce_fw_entry_offset":{"offset":1}
,"cpu.ccplex_platform_features":{"cpu":1,"0x00000":1}
,"cpu.clock_mode.clock_burst_policy":{"ccplex":1}
,"ccplex":{"clock":1,"avfs":1,"nafll":1,"lut":1,"adc":1}
,"burst":{"policy":1}
,"cpu.clock_mode.max_avfs_mode":{"highest":1,"0x2e":1}
,"avfs":{"mode":1}
,"nafll_cfg2.fll_init":{"ccplex":1}
,"nafll":{"cfg2":1,"cfg3":1,"ctrl1":1,"ctrl2":1,"coefficient":1}
,"cfg2":{"fll":1}
,"fll":{"init":1,"ldmem":1,"switch":1,"frug":1}
,"nafll_cfg2.fll_ldmem":{"ccplex":1}
,"nafll_cfg2.fll_switch_ldmem":{"ccplex":1}
,"switch":{"ldmem":1}
,"nafll_cfg3":{"ccplex":1}
,"nafll_ctrl1":{"ccplex":1}
,"nafll_ctrl2":{"ccplex":1}
,"cpu.lut_sw_freq_req.sw_override_ndiv":{"override":1}
,"override":{"ccplex":1}
,"lut":{"frequency":1}
,"cpu.lut_sw_freq_req.ndiv":{"ndiv":1,"102":1}
,"ndiv":{"ccplex":1}
,"cpu.lut_sw_freq_req.vfgain":{"vfgain":1}
,"vfgain":{"ccplex":1,"override":1}
,"cpu.lut_sw_freq_req.sw_override_vfgain":{"vfgain":1}
,"cpu.nafll_coeff.mdiv":{"mdiv":1}
,"mdiv":{"nafll":1}
,"cpu.nafll_coeff.pdiv":{"pdiv":1,"0x1":1}
,"pdiv":{"nafll":1}
,"cpu.nafll_coeff.fll_frug_main":{"fll":1,"0x9":1}
,"frug":{"main":1,"fast":1}
,"main":{"nafll":1}
,"cpu.nafll_coeff.fll_frug_fast":{"fll":1,"0xb":1}
,"cpu.adc_vmon.enable":{"enable":1,"0x0":1}
,"adc":{"voltage":1,"fuse":1}
,"cpu.min_adc_fuse_rev":{"minimum":1}
,"minimum":{"adc":1}
,"cpu.pllx_base.divm":{"pllx":1}
,"pllx":{"divm":1,"divn":1,"divp":1,"bypass":1}
,"cpu.pllx_base.divn":{"pllx":1,"104":1}
,"cpu.pllx_base.divp":{"pllx":1}
,"cpu.pllx_base.enable":{"enable":1}
,"cpu.pllx_base.bypass":{"pllx":1}
,"bypass":{"enable":1}
,"spe_uart_instance":{"uart":1}
,"aocluster.evp_reset_addr":{"aon":1,"0xc480000":1}
,"vector":{"spe":1}
,"carveout_alloc_direction":{"carveout":1}
,"2gb":{"dram":1}
,"32b":{"address":1}
,"start":{"dram":1}
,"se_oem_group":{"value":1}
,"se0_oem_group_0":{"se_rng1_rng1_oem_group_0":1}
,"se_rng1_rng1_oem_group_0":{"nvhs":1}
,"nvhs":{"nvls":1}
,"nvls":{"lock":1}
,"lock":{"bits":1}
,"kilohertz":{"i2c":1}
,"pmc_rst_req_cfg":{"configures":1}
,"wdt_reset_out":{"signal":1,"expiry":1,"software-initiated":1}
,"signal":{"generation":1}
,"generation":{"watchdog":1}
,"toggle":{"wdt_reset_out":1}
,"expiry":{"wdt":1,"aowdt":1}
,"software-initiated":{"reset":1}
,"cpu.nafll_cfg2.fll_init":{"0xd":1}
,"cpu.nafll_cfg2.fll_ldmem":{"0xc":1}
,"cpu.nafll_cfg2.fll_switch_ldmem":{"0xa":1}
,"cpu.nafll_cfg3":{"0x38000000":1}
,"cpu.nafll_ctrl1":{"0x0000000c":1}
,"cpu.nafll_ctrl2":{"0x22250000":1}
,"sw_carveout":{"variables":1}
,"carveout.misc.size":{"0x800000":1}
,"0x800000":{"8mb":1}
,"carveout.misc.alignment":{"0x800000":1}
,"carveout.os.size":{"0x08000000":1}
,"0x08000000":{"128mb":1}
,"carveout.os.pref_base":{"0x80000000":1}
,"carveout.os.alignment":{"0x200000":1}
,"carveout.cpubl.alignment":{"0x200000":1}
,"firmware.cpubl_load_offset":{"0x600000":1}
,"carveout.cpubl.size":{"0x04000000":1}
,"0x04000000":{"64mb":1}
,"carveout.rcm.size":{"0x0":1}
,"carveout.mb2.size":{"0x01000000":1}
,"0x01000000":{"16mb":1}
,"carveout.mb2.alignment":{"0x01000000":1}
,"carveout.tzdram.size":{"0x01000000":1}
,"carveout.tzdram.alignment":{"0x00100000":1}
,"0x00100000":{"1mb":1}
,"carveout.vpr.alignment":{"0x100000":1}
,"carveout.gsc":{".alignment":1}
,".alignment":{"0x400000":1,"0x800000":1,"0x100000":1,"0x200000":1,"0x2000000":1}
,"ast.temp_map_b_carveout_va":{"0xc0000000":1}
,"ast.temp_map_b_carveout_size":{"0x20000000":1}
,"bpmp_cpu_nic":{"bpmp_apb":1}
,"bpmp_apb":{"axi_cbb":1}
,"divider":{"pllp_out0":1,"pllaon_out":1,"value":1}
,"pllp_out0":{"408mhz":1}
,"408mhz":{"source":1}
,"aon_cpu_nic":{"aon_can0":1}
,"aon_can0":{"aon_can1":1}
,"pllaon_out":{"source":1}
,"expected":{"divider":1}
,"aotag.cooldown_temp_timeout":{"30000":1}
,"i2c.4":{"918":1}
,"aocluster":{"data":1}
}
;Search.control.loadWordPairs(pairs);
