var pairs =
{
"controller":{"area":1,"always-on":1,"several":1,"base":1,"working":1,"available":1}
,"area":{"network":1}
,"applies":{"jetson":1}
,"jetson":{"xavier":1,"agx":1,"tx2":1,"platform":1,"carrier":1,"requires":1,"platform\u2019s":1,"can_rx":1,"can_tx":1,"3.3v":1,"gnd":1,"mttcan":1,"nano":1,"device":1}
,"xavier":{"jetson":1,"series":1,"mhz":1}
,"agx":{"xavier":1}
,"series":{"jetson":1,"devices":1,"mhz":1}
,"tx2":{"series":1}
,"topic":{"describes":1,"clocks":1}
,"describes":{"time":1}
,"time":{"triggered":1}
,"triggered":{"ttcan":1,"controller":1}
,"ttcan":{"controller":1}
,"always-on":{"block":1}
,"block":{"nvidia":1}
,"nvidia":{"soc":1,"recommends":1,"t194":1}
,"soc":{"userspace":1,"parent":1}
,"important":{"features":1}
,"several":{"important":1,"ways":1,"debugging":1}
,"supports":{"standard":1,"mode":1,"minimum":1}
,"standard":{"extended":1}
,"extended":{"frame":1}
,"frame":{"transmission":1,"can0":1}
,"bus":{"bit":1,"subsystem":1,"behaving":1,"mcp":1}
,"bit":{"rate":1,"rates":1,"data":1}
,"rate":{"configured":1,"mbps":1,"based":1,"500":1,"exactly":1,"follow":1,"mttcan":1,"software":1,"hardware":1}
,"configured":{"kbps":1}
,"kbps":{"mbps":1,"data":1}
,"mode":{"maximum":1,"bus":1}
,"maximum":{"data":1}
,"data":{"bit":1,"mode":1,"abcdabcd":1}
,"mbps":{"types":1,"data":1,"enter":1,"enable":1}
,"types":{"transceivers":1}
,"transceivers":{"achieve":1}
,"achieve":{"mbps":1}
,"deliver":{"higher":1}
,"higher":{"data":1,"bit":1,"clock":1}
,"rates":{"configure":1,"configuring":1}
,"configure":{"tdcr":1}
,"tdcr":{"transmission":1,"higher":1}
,"transmission":{"delay":1}
,"delay":{"compensation":1}
,"compensation":{"register":1}
,"register":{"userspace":1,"settings":1,"address":1}
,"userspace":{"sysfs":1}
,"sysfs":{"node":1}
,"platform":{"details":1,"pinmux":1}
,"following":{"table":1,"connections":1}
,"table":{"shows":1,"section":1}
,"shows":{"details":1,"example":1,"controller":1,"two":1}
,"details":{"implementation":1}
,"implementation":{"supported":1}
,"supported":{"platform":1}
,"number":{"controllers":1}
,"base":{"address":1}
,"mttcan@c310000":{"mttcan@c320000":1}
,"pins":{"jetson":1}
,"carrier":{"board":1,"board\u2019s":1}
,"j30":{"40-pin":1}
,"40-pin":{"header":1}
,"j26":{"30-pin":1}
,"30-pin":{"header":1}
,"default":{"pin":1,"nodes":1,"clock":1}
,"pin":{"configuration":1,"jetson":1}
,"sfio":{"functionality":1}
,"interface":{"jetson":1,"support":1,"necessary":1,"properties":1,"flexible":1,"network":1,"works":1,"select":1}
,"requires":{"transceiver":1}
,"transceiver":{"supports":1,"production":1,"jetson":1,"vcc":1,"gnd":1,"confirm":1,"used":1}
,"minimum":{"3.3":1}
,"3.3":{"transfer":1}
,"transfer":{"rate":1,"packets":1}
,"based":{"jetson":1,"nvidia":1}
,"platform\u2019s":{"specifications":1}
,"specifications":{"section":1}
,"section":{"important":1,"jetson":1,"discusses":1,"configuring":1,"obtaining":1,"jetson\u2011io":1}
,"features":{"details":1}
,"recommends":{"waveshare":1}
,"waveshare":{"sn65hvd230":1}
,"sn65hvd230":{"board":1}
,"board":{"development":1}
,"development":{"systems":1}
,"systems":{"choice":1}
,"choice":{"transceiver":1}
,"production":{"devices":1}
,"devices":{"depends":1,"network":1,"c320000.mttcan":1,"based":1,"mcp251x":1,"connect":1}
,"depends":{"application\u2019s":1}
,"application\u2019s":{"requirements":1}
,"connections":{"transceiver":1,"correctly":1,"device":1}
,"vcc":{"jetson":1}
,"3.3v":{"pin":1}
,"gnd":{"jetson":1,"pin":1}
,"diagram":{"shows":1}
,"example":{"correct":1,"writes":1,"commands":1,"command":1}
,"correct":{"connection":1}
,"kernel":{"dtb":1,"device":1,"drivers":1,"net":1,"driver":1,"customization":1,"sources":1,"source":1,"debug":1}
,"nodes":{"enabled":1,"can0":1,"present":1,"missing":1}
,"enabled":{"kernel":1}
,"device":{"tree":1,"logs":1,"jetson\u2011io":1,"reboots":1,"connected":1}
,"status":{"okay":1}
,"check":{"field":1,"whether":1,"clock":1,"actual":1,"network":1}
,"field":{"userspace":1}
,"cat":{"proc":1,"sys":1}
,"proc":{"device-tree":1}
,"device-tree":{"mttcan":1}
,"mttcan":{"@c310000":1,"native":1,"section":1,"kernel":1,"driver":1}
,"@c310000":{"status":1}
,"sure":{"pinmux":1,"transceiver":1}
,"pinmux":{"register":1,"updated":1,"configuration":1}
,"settings":{"applied":1}
,"applied":{"shown":1}
,"shown":{"table":1}
,"updated":{"several":1,"files":1}
,"busybox":{"devmem":1}
,"devmem":{"tool":1,"0x0c303020":1}
,"tool":{"write":1,"enable":1,"jetson":1}
,"write":{"hardware":1}
,"hardware":{"registers":1,"via":1,"section":1}
,"registers":{"changes":1}
,"changes":{"persist":1}
,"persist":{"until":1}
,"until":{"system":1}
,"system":{"rebooted":1}
,"enter":{"command":1,"commands":1}
,"command":{"install":1,"transfers":1,"receives":1,"displays":1,"polling":1}
,"install":{"busybox":1,"group":1,"utilities":1,"can-utils":1}
,"sudo":{"apt-get":1}
,"apt-get":{"install":1}
,"writes":{"value":1}
,"value":{"0x458":1}
,"0x458":{"register":1}
,"address":{"0x0c303020":1}
,"0x0c303020":{"0x458":1}
,"update":{"respective":1,"clock":1}
,"respective":{"platform":1,"spi":1}
,"configuration":{"files":1}
,"files":{"flash":1}
,"flash":{"updated":1}
,"jetson-io":{"tool":1}
,"enable":{"pins":1,"drivers":1,"done":1,"pllaon":1}
,"load":{"necessary":1,"kernel":1}
,"necessary":{"kernel":1,"enable":1}
,"drivers":{"order":1,"net":1,"kernel":1,"information":1}
,"order":{"shown":1}
,"insert":{"bus":1,"raw":1}
,"subsystem":{"support":1}
,"support":{"module":1,"jetson":1,"higher":1}
,"insmod":{"lib":1}
,"lib":{"modules":1}
,"modules":{"4.x.xxx-tegra":1}
,"4.x.xxx-tegra":{"kernel":1}
,"net":{"can.ko":1,"can-raw.ko":1,"mttcan":1,"can1":1}
,"raw":{"protocol":1}
,"protocol":{"module":1}
,"module":{"can-id":1}
,"can-id":{"filtering":1}
,"modprobe":{"can_raw":1,"mttcan":1}
,"add":{"real":1}
,"real":{"interface":1}
,"native":{"mttcan.ko":1}
,"managing":{"network":1}
,"network":{"first":1,"install":1,"interface":1,"problems":1,"transfer":1,"information":1,"connections":1,"shows":1}
,"first":{"bring":1}
,"bring":{"devices":1,"interface":1}
,"group":{"utilities":1}
,"utilities":{"testing":1}
,"testing":{"transfer":1}
,"packets":{"debug":1,"try":1,"managing":1,"connected":1}
,"debug":{"network":1,"methods":1,"bpmp":1,"clk":1}
,"commands":{"network":1}
,"flexible":{"data":1}
,"500":{"kbps":1}
,"link":{"can0":1,"can1":1}
,"can0":{"type":1,"can\u2011id":1,"123":1,"1000":1,"rate":1,"pto_counter":1,"can1":1}
,"type":{"bitrate":1}
,"bitrate":{"500000":1}
,"500000":{"dbitrate":1,"loopback":1}
,"dbitrate":{"1000000":1}
,"1000000":{"berr-reporting":1}
,"can1":{"type":1,"tdcr":1,"watch":1}
,"transfers":{"packet":1,"frame":1}
,"packet":{"can0":1,"node":1}
,"can\u2011id":{"123":1}
,"123":{"data":1,"abcdabcd":1,"flag":1,"1abcdabcd":1}
,"cansend":{"can0":1,"enter":1,"--help":1}
,"receives":{"packet":1}
,"node":{"connected":1,"enter":1}
,"connected":{"bus":1,"correctly":1,"devices":1}
,"flag":{"bit":1}
,"information":{"cansend":1,"using":1}
,"tools":{"cangen":1}
,"cangen":{"different":1,"can0":1}
,"different":{"filtering":1}
,"filtering":{"options":1}
,"discusses":{"methods":1}
,"methods":{"debugging":1}
,"debugging":{"network":1,"techniques":1}
,"loopback":{"test":1}
,"may":{"perform":1,"useful":1}
,"perform":{"loopback":1}
,"test":{"determine":1,"successful":1,"shows":1}
,"determine":{"whether":1}
,"whether":{"controller":1,"steps":1,"bus":1}
,"short":{"pins":1}
,"board\u2019s":{"can0":1,"40\u2011pin":1}
,"candump":{"can0":1}
,"successful":{"last":1}
,"last":{"command":1}
,"techniques":{"may":1}
,"useful":{"appropriate":1}
,"appropriate":{"cases":1}
,"working":{"correctly":1}
,"correctly":{"able":1,"made":1,"network":1}
,"able":{"send":1,"support":1}
,"send":{"receive":1,"enter":1}
,"receive":{"packets":1}
,"try":{"reconnecting":1}
,"reconnecting":{"transceiver":1}
,"confirm":{"connections":1}
,"steps":{"necessary":1}
,"done":{"properly":1}
,"connect":{"oscilloscope":1,"mcp251x":1,"mcp":1,"int":1,"spi1":1,"bus":1,"canh":1}
,"oscilloscope":{"whether":1}
,"behaving":{"properly":1}
,"logs":{"buffer":1}
,"buffer":{"space":1}
,"space":{"available":1}
,"available":{"message":1,"jetson":1}
,"message":{"during":1}
,"during":{"send":1}
,"polling":{"mechanism":1}
,"obtaining":{"higher":1,"kernel":1}
,"obtain":{"higher":1,"bit":1,"kernel":1}
,"configuring":{"tdcr":1,"clocks":1}
,"used":{"able":1}
,"echo":{"0x600":1}
,"0x600":{"sys":1}
,"sys":{"devices":1,"kernel":1}
,"c320000.mttcan":{"net":1}
,"changing":{"parent":1,"clock":1}
,"parent":{"clock":1}
,"clock":{"t194":1,"pll_c":1,"frequency":1,"parent":1,"mttcan":1,"rate":1}
,"t194":{"platforms":1,"soc":1}
,"pll_c":{"pll_c":1,"clock\u2019s":1}
,"clock\u2019s":{"core":1}
,"core":{"clock":1,"clk":1}
,"frequency":{"mhz":1,"obtain":1}
,"exactly":{"mbps":1}
,"pllaon":{"clock":1,"parent":1}
,"using":{"pllaon":1}
,"clocks":{"topic":1}
,"driver":{"sets":1,"code":1}
,"sets":{"clock":1}
,"follow":{"instructions":1}
,"instructions":{"kernel":1}
,"customization":{"topic\u2019s":1}
,"topic\u2019s":{"section":1}
,"sources":{"git":1}
,"git":{"obtain":1}
,"source":{"code":1}
,"code":{"update":1,"snippet":1}
,".set_can_core_clk":{"true":1}
,".can_core_clk_rate":{"50000000":1}
,"50000000":{"modify":1}
,".can_clk_rate":{"200000000":1}
,"200000000":{"four":1}
,"four":{"times":1}
,"times":{"core":1}
,"clk":{"rate":1,"can0":1}
,"software":{"via":1}
,"via":{"userspace":1}
,"bpmp":{"debug":1}
,"actual":{"clock":1}
,"nano":{"devices":1,"carrier":1,"mcp251x":1}
,"mcp251x":{"chip":1,"device\u0027s":1}
,"chip":{"spi":1,"jetson":1}
,"spi":{"interface":1,"controllers":1,"pins":1}
,"works":{"spi":1}
,"mcp":{"device\u2019s":1,"device":1,"devices":1}
,"device\u2019s":{"int":1}
,"int":{"pin":1,"40\u2011pin":1}
,"40\u2011pin":{"expansion":1}
,"expansion":{"header":1,"header\u2019s":1}
,"two":{"spi":1,"nodes":1}
,"controllers":{"pin-outs":1}
,"pin-outs":{"40\u2011pin":1}
,"spi1":{"connect":1,"spi2":1}
,"header\u2019s":{"pin":1}
,"spi2":{"connect":1,"mosi":1}
,"mosi":{"miso":1}
,"miso":{"cs0":1}
,"cs0":{"sck":1}
,"sck":{"pins":1}
,"device\u0027s":{"respective":1}
,"start":{"jetson-io":1}
,"jetson\u2011io":{"interface":1,"prompts":1}
,"select":{"mcp":1}
,"reboot":{"jetson":1}
,"reboots":{"check":1}
,"watch":{"nodes":1}
,"present":{"nodes":1}
,"canh":{"canh":1,"canl":1}
,"canl":{"canl":1}
}
;Search.control.loadWordPairs(pairs);
