var pairs =
{
"graphics":{"programming":1,"specifications":1,"api":1}
,"information":{"chapter":1,"includes":1,"graphics":1}
,"chapter":{"understand":1}
,"understand":{"graphics":1}
,"programming":{"release":1}
,"release":{"information":1}
,"includes":{"topics":1}
,"topics":{"binary":1}
,"binary":{"shader":1}
,"shader":{"program":1}
,"program":{"management":1,"compiler":1}
,"management":{"shader":1}
,"compiler":{"image":1}
,"image":{"stream":1}
,"stream":{"translation":1}
,"translation":{"eglstream":1}
,"specifications":{"extensions":1}
,"extensions":{"supported":1,"nvidia":1,"document":1}
,"supported":{"release":1}
,"opengl":{"specs":1}
,"specs":{"extensions":1}
,"nvidia":{"jetson":1}
,"jetson":{"linux":1}
,"linux":{"graphics":1}
,"api":{"reference":1}
,"egl":{"egl":1,"extensions":1}
}
;Search.control.loadWordPairs(pairs);
