var pairs =
{
"boot":{"flow":1,"software":1,"logo":1}
,"part":{"bootloader":1}
,"bootloader":{"topic":1}
,"topic":{"describes":1}
,"describes":{"boot":1}
,"primary":{"function":1}
,"function":{"jetson":1}
,"jetson":{"boot":1}
,"software":{"initialize":1,"performs":1}
,"initialize":{"soc":1}
,"soc":{"system":1}
,"system":{"chip":1}
,"chip":{"including":1}
,"initializing":{"emc":1}
,"emc":{"cpu":1}
,"setting":{"security":1,"memory":1}
,"security":{"parameters":1}
,"loading":{"different":1}
,"different":{"firmware":1}
,"maintaining":{"chain":1}
,"chain":{"trust":1}
,"memory":{"carveouts":1}
,"carveouts":{"different":1}
,"flashing":{"device":1}
,"booting":{"operating":1}
,"operating":{"system":1}
,"additionally":{"jetson":1}
,"performs":{"operations":1}
,"operations":{"defined":1}
,"defined":{"product":1}
,"product":{"requirements":1}
,"requirements":{"including":1}
,"including":{"limited":1}
,"initialization":{"hdmi":1}
,"displaying":{"boot":1}
}
;Search.control.loadWordPairs(pairs);
