var pairs =
{
"jetson":{"xavier":1,"agx":1,"tx2":1,"board":1,"device":1,"carrier":1,"module":1,"modules":1,"nano":1,"tx1":1}
,"xavier":{"agx":1,"tx2":1,"jetson":1,"series":1,"board":1,"jetson-xavier-nx-devkit-emmc":1}
,"agx":{"xavier":1,"agx":1}
,"tx2":{"update":1,"series":1,"board":1}
,"update":{"redundancy":1,"process":1,"ensures":1,"achieves":1,"feature":1,"provide":1,"rootfs":1,"images":1,"engine":1,"slot":1,"updated":1,"contains":1,"uses":1,"slots":1,"failure":1,"progress":1,"complete":1,"applied":1,"partitions":1,"payload":1,"bup":1,"supported":1,"just":1,"adding":1,"removing":1,"uncomment":1,"bootloader":1,"jetson":1}
,"applies":{"jetson":1,"bootloader":1}
,"series":{"jetson":1,"processor":1,"devices":1,"board":1,"jetson-agx-xavier-devkit":1,"jetson-tx2-devkit":1,"device":1}
,"bootloader":{"update":1,"partition":1,"partitions":1,"redundancy":1,"image":1,"slots":1,"slot":1,"resets":1,"implementation":1,"bootloader":1,"runs":1,"attempts":1,"marks":1,"tools":1,"directory":1,"signed":1,"multi-signed":1,"psd":1,"payload_dir":1,"autosync":1,"i.e":1,"images":1,"non-current":1}
,"process":{"provides":1,"two":1}
,"provides":{"safe":1,"nvbootctrl":1}
,"safe":{"bootloader":1}
,"ensures":{"workable":1}
,"workable":{"bootloader":1}
,"partition":{"remains":1,"selection":1,"loaded":1,"settings":1,"loading":1,"table":1,"root":1,"kernel-dtb":1,"slots":1,"app":1,"userspace":1,"bpmp-fw_b":1}
,"remains":{"boot":1}
,"boot":{"storage":1,"images":1,"unused":1,"failure":1,"however":1,"process":1,"current":1,"operation":1,"normal":1,"device":1,"slot":1,"attempt":1,"certain":1,"retries":1,"updated":1,"following":1,"now-unused":1,"newly":1,"system":1,"service":1,"command":1,"update":1,"state":1,"control":1,"firmware":1,"slots":1,"loads":1,"log":1,"chain":1}
,"storage":{"during":1}
,"during":{"update":1,"immediately":1,"system":1}
,"achieves":{"update":1}
,"feature":{"maintains":1,"added":1}
,"maintains":{"two":1,"bootloader":1}
,"two":{"sets":1,"shadow":1,"methods":1,"headers":1}
,"sets":{"bootloader":1,"partitions":1}
,"partitions":{"slot":1,"contain":1,"known":1,"names":1,"instructed":1,"named":1,"assigned":1,"newer":1,"kernel":1,"00000003":1,"00010003":1}
,"slot":{"slot":1,"partitions":1,"current":1,"corrupted":1,"layout":1,"two-slot":1,"implementation":1,"system":1,"several":1,"called":1,"course":1,"fails":1,"next":1,"bootable":1,"contains":1,"may":1,"recent":1,"boots":1,"updated":1,"normally":1,"last":1,"status":1,"metadata":1,"priority":1,"highest":1,"booted":1,"ensure":1,"handles":1,"caches":1,"number":1,"along":1,"retry":1,"device":1,"value":1,"boot":1,"unused":1,"updating":1,"progress":1,"marked":1,"reboot":1,"first":1,"successful":1,"duplication":1,"due":1,"bootloader":1,"recovered":1,"information":1,"forcefully":1,"available":1,"effectively":1,"info":1,"command":1,"having":1,"good":1,"invalid":1,"zero-based":1,"selected":1,"message":1,"pri":1}
,"contain":{"boot":1,"information":1,"update":1}
,"root":{"filesystems":1,"file":1}
,"filesystems":{"redundancy":1}
,"redundancy":{"rootfs":1,"feature":1,"automatically":1,"reduce":1,"disabled":1,"settings":1,"creating":1,"using":1,"support":1,"update":1,"bootloader":1,"one-time":1,"describes":1}
,"rootfs":{"redundancy":1}
,"added":{"top":1}
,"top":{"update":1,"pathname":1,"bootloader":1,"sudo":1,"location":1}
,"provide":{"bootloader":1,"guidance":1}
,"automatically":{"maintains":1,"generated":1}
,"image":{"bootloader":1,"setting":1,"updated":1,"consult":1,"generator":1,"dump":1,"slot_metadata.bin":1,"file":1,"enable":1,"stored":1,"board":1,"indicated":1}
,"slots":{"allowing":1,"slot":1,"formerly":1,"prepare":1,"contain":1,"switched":1,"modifications":1}
,"allowing":{"system":1}
,"system":{"boot":1,"update":1,"updates":1,"running":1,"may":1,"updated":1,"used":1,"attempted":1,"uses":1,"booted":1,"normal":1,"slot":1,"reboot":1,"attempt":1,"booting":1,"checks":1,"completed":1,"fails":1,"failed":1,"generate":1,"launch":1,"flashed":1,"directory":1,"partition":1,"newly":1,"usb":1,"target":1}
,"unused":{"slot":1,"slots":1,"current":1,"slot\u2019s":1,"previously":1,"newly":1}
,"current":{"slot":1,"bootloader":1,"unused":1,"slot\u2019s":1,"update":1,"state":1,"boot":1}
,"reduce":{"risk":1}
,"risk":{"boot":1}
,"failure":{"bootloader":1,"cases":1,"recovery":1}
,"images":{"current":1,"unused":1,"type":1,"bootloader":1,"kernel":1}
,"disabled":{"default":1,"smd":1}
,"default":{"enable":1,"smd":1,"image":1,"smd_info.cfg":1,"disable":1,"value":1,"file":1,"setting":1,"heap":1}
,"enable":{"enabling":1,"redundancy":1,"slots":1,"flashed":1,"rootfs":1,"update":1,"disable":1}
,"enabling":{"bootloader":1,"rootfs":1}
,"principle":{"shadow":1}
,"shadow":{"copies":1}
,"copies":{"enables":1,"copy":1,"commonly":1}
,"enables":{"multiple":1,"update":1}
,"multiple":{"placeholders":1,"firmware":1}
,"placeholders":{"placeholders":1,"holds":1}
,"holds":{"backup":1}
,"backup":{"copies":1}
,"copy":{"constitutes":1,"binary":1,"bup":1}
,"constitutes":{"potential":1}
,"potential":{"candidate":1}
,"candidate":{"boot":1}
,"however":{"based":1,"may":1}
,"based":{"runtime":1}
,"runtime":{"decisions":1}
,"decisions":{"correct":1}
,"correct":{"copy":1,"system":1}
,"binary":{"loaded":1,"type":1,"size":1}
,"loaded":{"continue":1,"derived":1,"0x40043400":1,"0xd7800000":1}
,"continue":{"boot":1}
,"commonly":{"referred":1}
,"referred":{"slot":1}
,"two-slot":{"implementation":1}
,"implementation":{"follows":1}
,"following":{"diagram":1,"scenarios":1,"nvidia":1,"commands":1,"sample":1}
,"diagram":{"gives":1,"schematic":1}
,"gives":{"conceptual":1}
,"conceptual":{"example":1}
,"example":{"slot":1}
,"updates":{"affects":1,"two":1,"images":1,"applied":1,"now-unused":1}
,"affects":{"components":1}
,"known":{"slots":1}
,"several":{"attributes":1}
,"running":{"booted":1,"current":1,"update":1,"slot":1}
,"booted":{"slot":1,"next":1,"current":1,"newly":1}
,"called":{"unused":1}
,"may":{"exchange":1,"different":1,"older":1,"may":1,"bootable":1,"slot":1,"wish":1}
,"exchange":{"roles":1}
,"roles":{"current":1,"now-current":1}
,"course":{"update":1}
,"fails":{"repeatedly":1,"normally":1,"boot":1,"current":1}
,"repeatedly":{"during":1}
,"immediately":{"boot":1,"system":1}
,"active":{"slot":1}
,"next":{"boot":1,"power":1}
,"operation":{"attempt":1}
,"attempt":{"boot":1,"succeeded":1,"fails":1}
,"normal":{"state":1,"boot":1}
,"state":{"active":1,"machine":1,"slot":1,"reboots":1,"boots":1,"update":1,"runs":1}
,"bootable":{"slot":1,"attribute":1,"unused":1,"attributes":1,"successful":1,"updated":1,"becomes":1,"active":1,"boots":1}
,"updated":{"may":1,"slot":1,"boot":1,"software":1,"version":1,"update":1,"current":1,"smd":1}
,"attribute":{"indicates":1,"switches":1}
,"indicates":{"whether":1,"system":1}
,"whether":{"slot":1}
,"contains":{"correct":1,"error":1,"boot-related":1,"just":1,"pdk":1,"whitespace":1,"firmware":1}
,"used":{"boot":1,"recent":1,"mb2":1,"active":1,"update":1,"implement":1}
,"device":{"system":1,"hangs":1,"partitions":1,"disabled":1,"run":1,"updating":1,"configuration":1,"00000003":1,"00010003":1,"mmcblk0p1":1,"replace":1}
,"older":{"identical":1}
,"identical":{"newer":1}
,"newer":{"version":1,"versions":1}
,"version":{"system":1,"specifies":1,"number":1,"bootloader":1,"features":1,"259":1,"01.00.160913-t186-m-00.00-mobile-09b4fbd4":1}
,"successful":{"attribute":1,"boot":1,"bootable":1,"active":1,"current":1,"successful":1,"unused":1,"lower":1}
,"attempted":{"boot":1}
,"recent":{"attempt":1,"successful":1}
,"succeeded":{"user":1}
,"user":{"space":1,"update":1}
,"space":{"update":1}
,"engine":{"first":1,"update":1,"performs":1,"usage":1,"bootloader":1,"states":1,"nv_update_engine":1,"marks":1,"allowed":1,"launched":1,"applies":1,"loads":1,"normal":1,"simply":1,"during":1,"run":1,"script":1,"state":1}
,"first":{"time":1}
,"time":{"newly":1,"duplicated":1}
,"newly":{"updated":1,"duplicated":1,"created":1}
,"boots":{"successfully":1,"newly":1,"unused":1}
,"successfully":{"kernel":1,"update":1}
,"kernel":{"reset":1,"partition":1,"kernel-dtb":1}
,"reset":{"slot":1,"reason":1}
,"normally":{"happens":1,"current":1}
,"happens":{"immediately":1}
,"software":{"contains":1,"used":1,"slot":1}
,"certain":{"number":1}
,"number":{"times":1,"software":1,"slots":1,"boot":1,"slot":1,"failed":1,"specifies":1}
,"times":{"bootloader":1}
,"resets":{"bootable":1,"current":1}
,"switches":{"roles":1}
,"formerly":{"unused":1,"current":1}
,"last":{"update":1,"mts-fallback":1}
,"boot-related":{"software":1}
,"status":{"details":1,"communicates":1,"system":1,"slot":1,"0x00000000":1}
,"details":{"defined":1}
,"defined":{"structure":1,"bl_autosync":1}
,"structure":{"stored":1}
,"stored":{"slot":1,"file":1}
,"metadata":{"smd":1,"store":1,"find":1,"instruct":1,"evaluates":1}
,"smd":{"partition":1,"image":1,"configuration":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1}
,"magic":{"fixed":1,"pattern":1}
,"fixed":{"value":1}
,"value":{"identifies":1,"slot":1,"build_l4t_bup.sh":1,"board":1,"value":1}
,"identifies":{"smd":1}
,"specifies":{"version":1,"number":1,"type":1,"maximum":1}
,"num_slots":{"specifies":1}
,"slot_info":{"array":1}
,"array":{"structures":1}
,"structures":{"contain":1}
,"information":{"slots":1,"used":1,"generating":1,"generate":1}
,"priority":{"priority":1,"slot":1,"retry_count":1,"lower":1,"suffix":1}
,"suffix":{"string":1,"slot":1,"boot_successful":1,"retry_count":1,"retry":1}
,"string":{"either":1,"containing":1,"contains":1}
,"either":{"suffixed":1}
,"suffixed":{"partitions":1}
,"names":{"unique":1}
,"retry_count":{"number":1,"greater":1,"boot_successful":1}
,"retries":{"remaining":1}
,"remaining":{"bootloader":1}
,"slot\u2019s":{"successful":1,"partitions":1}
,"attributes":{"tries":1}
,"tries":{"boot":1}
,"boot_successful":{"slot\u2019s":1}
,"highest":{"priority":1}
,"greater":{"slot":1}
,"power":{"cycle":1}
,"uses":{"update":1,"boot":1,"slot":1,"appropriate":1}
,"prepare":{"system":1}
,"performs":{"actions":1}
,"reads":{"bl_update_payload":1}
,"bl_update_payload":{"writes":1,"placed":1}
,"writes":{"data":1}
,"data":{"unused":1,"corruption":1}
,"instructed":{"payload":1}
,"calls":{"boot_control":1}
,"boot_control":{"interface":1}
,"interface":{"pre-defined":1}
,"pre-defined":{"workflow":1}
,"reboots":{"system":1,"slot":1}
,"previously":{"current":1}
,"ensure":{"slots":1,"backward":1}
,"store":{"slot":1,"bup":1}
,"communicates":{"update":1}
,"runs":{"state":1,"pre-defined":1}
,"machine":{"select":1,"flow":1}
,"select":{"boot":1}
,"handles":{"update":1}
,"cases":{"follows":1}
,"mb1":{"uses":1,"find":1,"mb2":1,"following":1,"available":1,"messages":1}
,"find":{"current":1}
,"caches":{"current":1}
,"along":{"valid":1,"flash.sh":1}
,"valid":{"flag":1}
,"flag":{"scratch":1}
,"scratch":{"register":1}
,"register":{"used":1,"layout":1}
,"mb2":{"cboot":1,"until":1,"always":1,"tboot-bpmp":1}
,"cboot":{"later":1}
,"later":{"stage":1}
,"stage":{"loaders":1}
,"retry":{"count":1,"boot_succ":1}
,"maximum":{"slots":1,"boot":1}
,"pattern":{"caf\u00E9":1}
,"name":{"partition":1}
,"derived":{"follows":1}
,"partition_name":{"base_name":1}
,"base_name":{"slot_value":1}
,"named":{"follows":1,"bl_update_payload":1}
,"empty":{"suffix":1}
,"backward":{"compatibility":1}
,"compatibility":{"legacy":1}
,"legacy":{"unaware":1}
,"unaware":{"partition":1}
,"loading":{"mechanisms":1,"mb1-bct":1,"partition":1}
,"nv_update_engine":{"uses":1,"--install":1,"--verify":1,"tool":1,"-enable-ab":1,"-disable-ab":1,"--enable-ab":1}
,"instruct":{"bootloader":1}
,"scenarios":{"identify":1}
,"identify":{"states":1}
,"table":{"shows":1,"contents":1,"jetson":1}
,"shows":{"status":1,"slot":1}
,"lower":{"slot":1,"priority":1}
,"updating":{"unused":1,"single-spec":1,"section":1}
,"progress":{"system":1,"slot":1}
,"reboot":{"state":1,"pending":1,"new":1}
,"applied":{"reboot":1,"slot":1,"duplicate":1,"update":1}
,"now-current":{"unused":1}
,"switched":{"thus":1}
,"thus":{"system":1}
,"now-unused":{"slot":1}
,"marked":{"bootable":1,"successful":1,"good":1}
,"becomes":{"active":1}
,"attempts":{"boot":1}
,"pending":{"slot":1}
,"new":{"update":1}
,"booting":{"newly":1,"new":1,"slot":1}
,"marks":{"current":1,"slot":1}
,"duplication":{"progress":1,"complete":1,"slot":1,"allowed":1,"enabled":1}
,"duplicated":{"current":1,"slot":1}
,"completed":{"slot":1}
,"due":{"data":1}
,"corruption":{"errors":1}
,"failed":{"attempts":1,"boot":1}
,"recovered":{"booting":1}
,"allowed":{"duplicate":1,"until":1,"modify":1}
,"duplicate":{"slot":1,"required":1}
,"until":{"system":1,"cboot":1}
,"modify":{"partition":1,"smd":1,"boot":1}
,"contents":{"partitions":1}
,"assigned":{"slot":1}
,"launched":{"scenarios":1,"boot":1}
,"explicit":{"launch":1}
,"launch":{"user":1,"nv_update_engine":1,"image":1,"update":1}
,"versions":{"command":1}
,"sudo":{"nv_update_engine":1,"nvbootctrl":1,"l4t_generate_soc_bup.sh":1,"env":1,"nv_smd_generator":1,"fab":1,"build_l4t_bup.sh":1}
,"payload":{"bup":1,"generator":1,"applied":1,"information":1}
,"bup":{"during":1,"named":1,"payload":1,"generated":1,"single-spec":1,"multi-spec":1,"includes":1,"contains":1,"string":1,"file":1,"locations":1,"just":1,"directory":1,"host":1,"built":1,"used":1,"below":1,"image":1,"boards":1,"topic":1,"run":1,"procedure":1}
,"opt":{"ota_package":1}
,"service":{"during":1}
,"loads":{"slot":1,"executes":1}
,"evaluates":{"current":1}
,"workflow":{"normal":1}
,"required":{"update":1}
,"simply":{"exits":1}
,"methods":{"enabling":1}
,"creating":{"smd":1}
,"setting":{"redundancy":1,"slot":1}
,"using":{"nv_update_engine":1}
,"tool":{"enable":1,"nv_smd_generator":1,"intended":1,"build_l4t_bup.sh":1,"linux":1,"x86":1,"testing":1}
,"configuration":{"file":1,"shown":1,"disables":1,"enables":1}
,"file":{"smd_info.cfg":1,"jetson":1,"system":1,"stored":1,"target":1,"slot_metadata.bin":1,"slot":1,"board":1}
,"smd_info.cfg":{"enable":1,"slot_metadata.bin":1,"default":1,"configuration":1}
,"run":{"host":1,"flash.sh":1,"updater":1,"debug":1,"nv_smd_generator":1,"update":1}
,"host":{"tool":1,"systems":1,"system":1}
,"nv_smd_generator":{"x86":1,"tool":1,"config_file":1,"smd_info.cfg":1,"default":1}
,"x86":{"system":1,"host":1}
,"generate":{"smd":1,"multi-spec":1,"bup":1,"single-spec":1,"default":1}
,"instructions":{"generating":1,"consult":1}
,"generating":{"smd":1,"multi-spec":1,"bootloader":1,"single-spec":1,"bup":1}
,"consult":{"smd":1,"running":1}
,"flash.sh":{"script":1,"flashing":1,"generate":1,"command":1}
,"script":{"perform":1,"packaged":1,"tool":1,"directory":1,"run":1,"target":1}
,"perform":{"fresh":1}
,"fresh":{"flash":1}
,"flash":{"device":1}
,"target":{"system":1,"board":1,"original":1}
,"flashed":{"device":1,"smd":1}
,"nvidia":{"tools":1,"provide":1,"provides":1,"nvbootctrl":1,"assistance":1}
,"tools":{"provided":1}
,"provided":{"ease-of-use":1}
,"ease-of-use":{"bootloader":1}
,"nvbootctrl":{"tool":1,"command":1,"get-current-slot":1,"dump-slots-info":1}
,"intended":{"debugging":1}
,"debugging":{"purposes":1}
,"purposes":{"load":1,"however":1}
,"load":{"smd":1}
,"dump":{"slot":1}
,"forcefully":{"change":1}
,"change":{"boot":1}
,"display":{"command":1}
,"command":{"usage":1,"line":1,"enable":1,"disable":1,"fails":1,"switch":1,"follows":1,"located":1,"generates":1}
,"enter":{"command":1,"commands":1,"following":1}
,"generated":{"host":1}
,"build_l4t_bup.sh":{"script":1,"options":1,"jetson-xavier-nx-devkit-emmc":1,"jetson-agx-xavier-devkit":1,"jetson-tx2-devkit":1,"device":1,"pkc_key_file":1}
,"packaged":{"along":1}
,"flashing":{"script":1}
,"linux":{"jetson":1}
,"board":{"support":1,"relative":1,"rootdev":1,"value":1,"jetson":1,"connected":1,"force":1,"contact":1,"located":1}
,"support":{"package":1,"default":1,"removing":1,"want":1,"redundancy":1}
,"package":{"bsp":1,"flash.sh":1,"nv_smd_generator":1}
,"section":{"describes":1,"generate":1,"generating":1}
,"describes":{"procedures":1,"procedure":1}
,"procedures":{"generating":1,"store":1}
,"multi-spec":{"bup":1,"procedure":1}
,"single-spec":{"bup":1,"procedure":1}
,"includes":{"multiple":1}
,"firmware":{"binaries":1,"blob":1}
,"binaries":{"bct":1,"type":1}
,"bct":{"images":1}
,"type":{"used":1,"jetson":1,"device":1,"processor":1,"redundancy":1,"needed":1}
,"supported":{"type":1}
,"updater":{"uses":1}
,"appropriate":{"binary":1,"type":1}
,"just":{"binary":1,"jetson":1,"location":1}
,"l4t_generate_soc_bup.sh":{"pkc_key_file":1}
,"pkc_key_file":{"options":1,"rsa":1,"jetson-tx2-devkit":1,"pkc_key_file":1,"device":1}
,"options":{"processor":1,"string":1,"passed":1,"board":1}
,"pathname":{"directory":1,"interpreted":1}
,"directory":{"contains":1,"update":1,"exist":1,"command":1,"pdk":1,"specified":1,"complete":1}
,"pdk":{"installation":1}
,"installation":{"package":1}
,"rsa":{"private":1,"keyslots":1}
,"private":{"key":1}
,"key":{"file":1,"copy":1}
,"carrier":{"board":1}
,"relative":{"pathname":1,"top":1}
,"interpreted":{"relative":1}
,"causes":{"script":1}
,"debug":{"mode":1,"build":1}
,"mode":{"keeps":1}
,"keeps":{"boot":1}
,"blob":{"images":1}
,"signed":{"bootloader":1,"bup":1}
,"containing":{"command":1}
,"line":{"options":1,"below":1}
,"passed":{"flash.sh":1}
,"whitespace":{"characters":1}
,"characters":{"enclosed":1}
,"enclosed":{"quotes":1}
,"processor":{"t19x":1,"t18x":1}
,"t19x":{"jetson":1,"command":1}
,"t18x":{"jetson":1}
,"procedure":{"stores":1,"generating":1,"jetson":1}
,"stores":{"bup":1}
,"psd":{"bl_update_payload":1}
,"env":{"value":1}
,"module":{"configuration":1}
,"shown":{"table":1}
,"modules":{"configurations":1}
,"configurations":{"topic":1}
,"topic":{"quick":1,"jetson":1}
,"quick":{"start":1}
,"rootdev":{"partition":1}
,"payload_dir":{"bl_update_payload":1}
,"devices":{"payloads_t19x":1,"payloads_t18x":1,"payloads_t21x":1}
,"nano":{"jetson":1,"tx1":1}
,"tx1":{"devices":1,"update":1}
,"locations":{"respective":1}
,"respective":{"group":1}
,"group":{"processors":1}
,"processors":{"single-spec":1}
,"location":{"appropriate":1,"parent":1}
,"place":{"bup":1,"target":1}
,"systems":{"generate":1}
,"slot_metadata.bin":{"flashed":1,"output":1,"installed":1}
,"config_file":{"output_file":1,"smd":1}
,"output_file":{"slot_metadata.bin":1}
,"output":{"smd":1}
,"installed":{"directory":1}
,"available":{"slot":1,"debug":1}
,"effectively":{"disables":1}
,"disables":{"redundancy":1,"update":1}
,"please":{"sure":1}
,"sure":{"field":1}
,"field":{"slot":1}
,"info":{"config":1,"order":1}
,"config":{"disable":1,"enable":1,"create":1}
,"disable":{"support":1,"bootloader":1,"uncommenting":1,"rootfs":1,"redundancy":1}
,"order":{"important":1}
,"removing":{"comments":1,"beginning":1}
,"autosync":{"bl_autosync_disable":1}
,"redundancy_enable":{"redundancy_user":1}
,"redundancy_user":{"defined":1,"statement":1}
,"bl_autosync":{"disable":1}
,"create":{"smd":1,"executing":1,"bup":1,"pkc":1}
,"comment":{"configuration":1}
,"adding":{"beginning":1}
,"beginning":{"parameter":1}
,"parameter":{"line":1,"lines":1}
,"below":{"config":1,"information":1}
,"uncomment":{"configuration":1,"redundancy_user":1}
,"lines":{"below":1}
,"bootloader-related":{"partitions":1}
,"kernel-dtb":{"partition":1,"partitions":1}
,"want":{"enable":1}
,"statement":{"replace":1}
,"replace":{"number":1,"t21x":1}
,"i.e":{"mb1":1}
,"enabled":{"default":1,"messages":1}
,"uncommenting":{"configuration":1}
,"max_bl_retry_count":{"specifies":1}
,"count":{"default":1}
,"app":{"created":1}
,"created":{"nvidia":1,"bup":1}
,"guidance":{"enabling":1}
,"switch":{"superuser":1}
,"superuser":{"mode":1}
,"one-time":{"command":1}
,"exist":{"create":1}
,"executing":{"command":1}
,"mkdir":{"opt":1}
,"scp":{"host_loc:bl_update_payload":1}
,"host_loc:bl_update_payload":{"opt":1,"bup":1}
,"built":{"host":1}
,"usb":{"key":1}
,"non-current":{"slot":1}
,"flow":{"follows":1}
,"schematic":{"description":1}
,"manually":{"modifying":1,"change":1,"modify":1}
,"modifying":{"boot":1}
,"testing":{"development":1}
,"development":{"purposes":1}
,"wish":{"manually":1}
,"modifications":{"smd":1}
,"having":{"higher":1}
,"higher":{"priority":1}
,"printer":{"number":1}
,"prints":{"currently":1,"suffix":1,"enablement":1,"information":1}
,"currently":{"running":1}
,"set-active-boot-slot":{"slot":1}
,"executes":{"slot":1}
,"set-slot-as-unbootable":{"slot":1}
,"is-slot-bootable":{"slot":1}
,"returns":{"slot":1}
,"is-slot-marked-successful":{"slot":1}
,"get-suffix":{"slot":1}
,"enablement":{"status":1,"slot":1}
,"toggles":{"enablement":1}
,"zero-based":{"slot":1}
,"show":{"current":1,"slot":1}
,"root@tegra-ubuntu":{"home":1}
,"home":{"nvidia":1}
,"magic:0x43424e00":{"version":1}
,"features":{"num_slots":1}
,"dump-slots-info":{"magic:0x43424e00":1}
,"sample":{"boot":1,"log":1}
,"selected":{"mb1":1,"boot":1}
,"log":{"shows":1}
,"message":{"displayed":1}
,"displayed":{"mb1":1}
,"build":{"mb1":1}
,"messages":{"enabled":1,"mb2":1}
,"always":{"available":1}
,"0000.040":{"welcome":1}
,"welcome":{"mb1-coldboot":1,"mb2":1}
,"mb1-coldboot":{"dev-version":1}
,"dev-version":{"14.00.170822-t186-m-00.00-96e265a3":1}
,"0000.048":{"rst_source":1}
,"rst_source":{"0xb":1}
,"0000.051":{"rst_level":1}
,"rst_level":{"0x1":1}
,"0000.053":{"read":1}
,"read":{"lock":1}
,"lock":{"aes":1,"rsa":1}
,"aes":{"keyslots":1}
,"0000.057":{"read":1}
,"0000.061":{"clear":1}
,"clear":{"keyslots":1}
,"keyslots":{"left":1}
,"left":{"open":1}
,"0000.065":{"last":1}
,"mts-fallback":{"status":1}
,"0000.070":{"boot-device":1}
,"boot-device":{"emmc":1}
,"0000.094":{"sdmmc":1}
,"sdmmc":{"ddr50":1,"bdev":1}
,"ddr50":{"mode":1}
,"0000.098":{"bin_type":1}
,"bin_type":{"slot":1}
,"0000.102":{"binary":1}
,"size":{"512":1,"528848":1}
,"512":{"loaded":1,"device":1}
,"0000.108":{"boot":1}
,"chain":{"chosen":1}
,"0000.111":{"boot":1}
,"0000.114":{"magic:0x43424e00":1}
,"259":{"num_slots":1}
,"0000.119":{"slot":1}
,"pri":{"suffix":1}
,"0000.125":{"slot":1}
,"0000.131":{"loading":1}
,"mb1-bct":{"sysram":1}
,"0000.135":{"bin_type":1}
,"0000.138":{"boot-device":1}
,"0000.888":{"welcome":1}
,"tboot-bpmp":{"version":1}
,"0000.897":{"default":1}
,"heap":{"0xd486400":1,"0x84a00000":1}
,"0xd486400":{"0xd488400":1}
,"0000.901":{"dma":1}
,"dma":{"heap":1}
,"0x84a00000":{"0x85300000":1}
,"0000.906":{"bit":1}
,"bit":{"0xd480000":1}
,"0000.909":{"br-bct":1}
,"br-bct":{"relocated":1}
,"relocated":{"0xd7020000":1}
,"0000.913":{"boot-device":1}
,"0000.917":{"sdmmc":1}
,"bdev":{"already":1}
,"already":{"initialized":1}
,"0000.922":{"pmic":1}
,"pmic":{"reset":1}
,"reason":{"nverc":1}
,"nverc":{"0x0":1}
,"0000.926":{"reading":1}
,"reading":{"gpt":1,"two":1}
,"gpt":{"512":1,"8388096":1}
,"0000.932":{"reading":1}
,"8388096":{"device":1}
,"0000.939":{"found":1}
,"found":{"partitions":1}
,"00000003":{"device":1}
,"0000.944":{"reading":1}
,"0000.950":{"found":1}
,"00010003":{"device":1}
,"0000.956":{"bin_type":1}
,"0000.959":{"loading":1}
,"bpmp-fw_b":{"0xd7800000":1}
,"0000.964":{"reading":1}
,"headers":{"addr:0xd7800000":1}
,"addr:0xd7800000":{"blocks:1":1}
,"0000.970":{"addr":1}
,"addr":{"0xd7800000":1}
,"0xd7800000":{"start-block":1}
,"start-block":{"58762425":1}
,"58762425":{"num_blocks":1}
,"0000.985":{"binary":1}
,"528848":{"loaded":1}
,"implement":{"bootloader":1}
,"needed":{"update":1}
,"commands":{"create":1}
,"connected":{"host":1}
,"indicated":{"fab":1}
,"fab":{"boardid":1,"100":1,"400":1,"c04":1}
,"boardid":{"fuselevel":1,"3668":1,"2888":1,"3310":1}
,"fuselevel":{"jetson":1,"fuselevel_production":1}
,"100":{"boardid":1}
,"3668":{"fuselevel":1}
,"fuselevel_production":{"boardsku":1,"build_l4t_bup.sh":1}
,"boardsku":{"0001":1}
,"0001":{"build_l4t_bup.sh":1,"boardrev":1}
,"jetson-xavier-nx-devkit-emmc":{"mmcblk0p1":1}
,"400":{"boardid":1}
,"2888":{"fuselevel":1}
,"boardrev":{"h.0":1}
,"h.0":{"build_l4t_bup.sh":1}
,"jetson-agx-xavier-devkit":{"mmcblk0p1":1}
,"c04":{"boardid":1}
,"3310":{"fuselevel":1}
,"jetson-tx2-devkit":{"mmcblk0p1":1}
,"force":{"recovery":1}
,"recovery":{"mode":1}
,"pkc":{"signed":1}
,"original":{"jetson":1}
,"contact":{"nvidia":1}
,"assistance":{"generating":1}
,"boards":{"jetson":1}
,"parent":{"directory":1}
,"located":{"top":1}
,"specified":{"complete":1}
,"complete":{"absolute":1}
,"absolute":{"pathname":1}
,"t21x":{"t19x":1,"t18x":1}
,"generates":{"bup":1}
}
;Search.control.loadWordPairs(pairs);
