var pairs =
{
"u-boot":{"customization":1,"default":1,"build":1,"source":1,"reference":1,"binaries":1,"files":1,"sources":1,"executing":1,"binary":1,"flashing":1,".bin":1,"full":1,"fetches":1,"specify":1,"select":1,"kernel":1,"u-boot":1,"reads":1,"expects":1,"functionality":1,"performs":1,"boot":1,"uses":1,"reduce":1,"delays":1,"runtime":1,"environment":1,"begins":1,"shell":1,"executes":1,"pauses":1,"scans":1,"scan":1,"searches":1,"search":1,"script":1,"starts":1,"configuration":1,"cause":1,"execute":1,"runs":1,"automatic":1,"fw_env":1,"merges":1,"support":1,"command":1,"doc":1,"consult":1,"documentation":1,"sign-on":1,"help":1,"sends":1}
,"applies":{"nvidia":1,"jetson":1,"device\u2019s":1}
,"nvidia":{"jetson":1,"developer":1,"kernel":1,"offers":1,"recommends":1,"extensions":1}
,"jetson":{"nano":1,"tx2":1,"tx1":1,"linux":1,"device":1,"l4t":1}
,"nano":{"devices":1,"2gb":1,"development":1,"device":1}
,"devices":{"nvidia":1,"flash_l4t_t210_spi_sd_p3448.xml":1,"following":1,"boot":1,"takes":1,"need":1,"until":1,"network":1,"imx477":1,"interface":1,"u-boot":1}
,"tx2":{"series":1,"jetson":1}
,"series":{"nvidia":1,"jetson":1,"flash_l4t_t186.xml":1,"commands":1}
,"default":{"bootloader":1,"option":1,"directory":1,"booting":1,"u-boot":1,"configuration":1,"boot":1,"list":1,"values":1,"l4t":1,"setenv":1,"menu":1,"primary":1}
,"bootloader":{"nvidia":1,"platform":1,"u\u2011boot":1,"optimize":1,"directory":1,"dtb":1}
,"linux":{"driver":1,"distributions":1,"distribution":1,"host":1,"toolchain":1,"kernel":1,"apply":1,"boot":1,"extlinux.conf":1,"overlay":1,"convention":1}
,"driver":{"package":1,"support":1}
,"package":{"l4t":1,"nvidia":1,"management":1,"back":1,"image":1}
,"l4t":{"supported":1,"package":1,"release":1,"tree":1,"image":1,"flashing":1,"partition":1,"boot":1,"target":1,"u-boot":1}
,"supported":{"platforms":1,"jetson":1,"hardware":1,"commands":1}
,"software":{"requirements":1,"layout":1}
,"requirements":{"prerequisites":1}
,"prerequisites":{"include":1}
,"linux-based":{"host":1}
,"host":{"system":1,"ipa":1,"runs":1,"l4t":1}
,"functionality":{"u-boot":1,"includes":1,"full":1}
,"build":{"flashing":1,"dtc":1,"linux":1,"u-boot":1,"environment":1}
,"flashing":{"utilities":1,"u-boot":1,"copy":1,"reference":1,"time":1,"process":1,"board":1,"tools":1,"file":1,"directory":1}
,"utilities":{"validated":1}
,"validated":{"using":1}
,"using":{"ubuntu":1,"linaro":1,"scp":1,"dhcp":1,"extlinux":1,"serial":1,"l4t":1,"u-boot":1}
,"ubuntu":{"host":1,"alternative":1}
,"system":{"later":1,"nvidia":1,"boots":1,"required":1,"hardware":1,"boot":1,"directories":1,"layouts":1,"based":1,"known":1,"detects":1,"modify":1,"file":1,"directory":1}
,"later":{"versions":1}
,"versions":{"ubuntu":1}
,"alternative":{"linux":1,"boot":1,"ways":1}
,"distributions":{"may":1}
,"may":{"work":1,"necessary":1,"know":1,"interrupt":1,"boot":1,"separate":1,"variable":1,"technique":1,"result":1,"ignored":1,"file":1}
,"work":{"host-specific":1}
,"host-specific":{"modifications":1}
,"download":{"install":1,"build":1,"reference":1,"dtc":1,"syslinux":1,"u-boot":1}
,"install":{"latest":1,"prefix":1}
,"latest":{"l4t":1}
,"developer":{"zone":1,"modify":1}
,"http":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"linux-tegra":1}
,"device":{"tree":1,"containing":1,"partition":1,"datasheet":1,"information":1,"device":1,"u-boot":1,"root":1,"configuration":1,"card":1,"host":1,"jetson":1,"run":1,"target":1,"nvme":1,"contains":1,"consequently":1,"explicitly":1,"specific":1,"booting":1,"example":1,"reflash":1,"loading":1,"requires":1,"isn\u2019t":1}
,"tree":{"compiler":1,"files":1,"detailed":1,"reside":1,"blob":1}
,"compiler":{"dtc":1}
,"dtc":{"used":1,"source":1,"binary":1,"packages":1,"supports":1,"directory":1,"building":1,"built":1,"filename":1,"usr":1,"dtc.git":1,"default":1,"specific":1}
,"used":{"compile":1,"partitions":1,"initially":1,"along":1,"flash":1}
,"compile":{"device":1,"manufacturing":1,"time":1}
,"files":{"contained":1,"exist":1,"app":1,"using":1,"boot":1,"mnt":1,"root":1,"test":1,"certain":1,"found":1,"script":1,"support":1,"identified":1,"named":1,"including":1,"distinguish":1,"u\u2011boot":1,"listing":1,"single":1}
,"contained":{"u-boot":1}
,"source":{"tree":1,"building":1,"code":1,"following":1,"add":1,"upstream":1}
,"detailed":{"example":1}
,"example":{"building":1,"reference":1,"boot":1,"config_bootdelay":1,"bootdelay":1,"below":1,"extlinux.conf":1,"cannot":1,"loaded":1,"similar":1,"illustrates":1,"output":1,"list":1,"print":1,"modify":1}
,"building":{"dtc":1,"device":1,"kernel":1,"u-boot":1,"nvidia":1}
,"pre-built":{"dtc":1}
,"binary":{"included":1,"built":1,"l4t":1}
,"included":{"kernel":1}
,"kernel":{"directory":1,"sources":1,"dtbs":1,"source":1,"root":1,"u-boot":1,"device":1,"command":1,"looks":1,"mount":1,"installed":1,"lnx":1,"able":1,"bootloader":1,"files":1,"image":1,"custom":1,"procedure":1,"directly":1,"system":1,"systems":1,"without":1,"boot":1,"dtb":1,"initrd":1,"sees":1,"via":1}
,"directory":{"release":1,"build":1,"relative":1,"u-boot":1,"target":1,"flash.sh":1,"contains":1,"root":1,"dtc":1,"$home":1,"run":1,"jetson":1,"boot":1,"host":1,"bootable":1,"may":1,"name":1,"bootloader":1,"structure":1,"pathname":1,"image":1,"listing":1}
,"release":{"dtc":1,"sources":1,"package":1,"tag":1,"notes":1}
,"packages":{"available":1}
,"available":{"standard":1,"downloading":1,"devices":1,"l4t":1}
,"standard":{"linux":1,"text-format":1}
,"distribution":{"package":1}
,"management":{"systems":1,"aspm":1}
,"systems":{"apt":1,"boot":1,"flexibility":1}
,"apt":{"updated":1}
,"updated":{"version":1,"u-boot":1}
,"version":{"dtc":1,"u\u2011boot":1,"u-boot":1}
,"supports":{"features":1,"nvidia":1}
,"features":{"required":1,"searches":1}
,"required":{"u\u2011boot":1,"flash.sh":1,"files":1}
,"u\u2011boot":{"makefile":1,"source":1,"suitable":1,"however":1,"environment":1,"looks":1,"sources":1,"directed":1,"displays":1,"complain":1,"load":1,"require":1,"command":1,"uses":1,"readme":1,"ext2ls":1,"new_value":1}
,"built":{"kernel":1,"source":1,"u-boot":1}
,"sources":{"release":1,"located":1,"space":1,"u-boot_source":1}
,"located":{"scripts":1,"logical":1,"lba":1,"last":1,"tools":1,"host":1,"$fdt_addr":1}
,"scripts":{"dtc":1,"enables":1,"contained":1,"execute":1,"configuration":1,"found":1,"replace":1,"related":1}
,"dtbs":{"target":1}
,"linaro":{"aarch64":1,"7.3.1":1}
,"aarch64":{"toolchain":1}
,"toolchain":{"available":1,"without":1,"cross_prefix":1,"information":1}
,"https":{"www.linaro.org":1}
,"www.linaro.org":{"downloads":1}
,"information":{"downloading":1,"download":1,"following":1,"prevent":1,"primary":1,"indicates":1,"merged":1}
,"downloading":{"building":1}
,"setting":{"root":1,"environment":1,"boot_targets":1}
,"root":{"file":1,"filesystem":1,"filesystem-on-ip-network":1,"dtc":1,"directory":1,"dev":1}
,"file":{"system":1,"kernel":1,"boot":1,"contains":1,"causes":1,"extlinux":1,"following":1,"u-boot":1,"user-accessible":1,"extlinux.conf":1,"system\u2019s":1,"board":1,"already":1,"host":1,"data":1,"rather":1,"suitable":1,"configured":1,"located":1,"onto":1,"device":1,"dbt":1,"above":1,"rootfs":1,"found":1,"systems":1,"shown":1,"system-specific":1}
,"adding":{"compiled":1}
,"compiled":{"kernel":1}
,"placeholders":{"commands":1,"board":1,"described":1}
,"topic":{"describes":1,"based":1}
,"describes":{"commands":1}
,"commands":{"placeholders":1,"download":1,"search":1,"executed":1,"modify":1,"sent":1,"u-boot":1,"similar":1,"u\u2011boot":1,"usage":1,"implemented":1}
,"board":{"board_and_rev":1,"remove":1,"data":1,"boot_targets":1,"described":1,"arrange":1,"execute":1,"u-boot":1,"merge":1}
,"board_and_rev":{"substitute":1,"described":1,"_defconfig":1}
,"substitute":{"values":1}
,"values":{"table":1,"include":1,"configs":1,"variables":1,"even":1,"built":1,"following":1,"appear":1,"boot_targets":1}
,"described":{"section":1,"following":1}
,"section":{"uses":1,"placeholders":1}
,"reference":{"platform":1,"arm64":1,"toolchain":1,"l4t":1}
,"platform":{"download":1,"board_and_rev":1,"soc":1,"mmcblk0p1":1,"interface":1,"flashing":1,"cfg":1}
,"offers":{"git":1}
,"git":{"repository":1,"clone":1,"nv-tegra.nvidia.com":1,"tag":1,"checkout":1,"git.kernel.org":1}
,"repository":{"containing":1}
,"containing":{"source":1,"root":1,"keywords":1}
,"code":{"version":1,"placed":1,"directory":1,"example":1,"modify":1}
,"suitable":{"l4t":1,"jetson":1}
,"overwriting":{"u-boot":1}
,"binaries":{"extracted":1}
,"extracted":{"l4t":1,"environment":1}
,"back":{"original":1}
,"original":{"u-boot":1,"jetson":1}
,"linux_for_tegra":{"bootloader":1,"sources":1,"p3448-0000.conf.common":1,"p2771-0000.conf.common":1,"p2371-2180-devkit.conf":1,"target_board":1}
,"soc":{"name":1}
,"name":{"platform":1,"provided":1,"local":1,"eth0":1,"u-boot":1,"known":1}
,"perform":{"either":1}
,"either":{"following":1}
,"following":{"steps":1,"location":1,"files":1,"kernel":1,"directories":1,"command":1,"order":1,"directory":1,"values":1,"value":1,"table":1,"variables":1,"places":1,"sections":1,"example":1}
,"run":{"command":1,"source_sync.sh":1,"script":1,"commands":1,"flash.sh":1}
,"clone":{"git":1}
,"nv-tegra.nvidia.com":{"3rdparty":1}
,"3rdparty":{"u-boot.git":1,"u-boot":1}
,"source_sync.sh":{"script":1,"without":1,"tag_name":1}
,"script":{"want":1,"prompts":1,"syncs":1,"passing":1,"flashes":1,"select":1,"mount":1,"creates":1,"treats":1,"adds":1,"explicitly":1,"parse":1,"simpler":1,"hard-codes":1,"search":1,"innocuous":1,"executed":1,"names":1,"name":1}
,"want":{"place":1,"pass":1}
,"place":{"l4t":1}
,"without":{"parameters":1,".gcc":1,"flashing":1,"fdt":1}
,"parameters":{"script":1,"control":1}
,"prompts":{"tag_name":1}
,"tag_name":{"release":1,"follows":1}
,"tag":{"name":1}
,"provided":{"release":1,"script":1}
,"option":{"source_sync":1,"provided":1,"identify":1,"recommended":1}
,"source_sync":{"syncs":1}
,"syncs":{"kernel":1,"source":1}
,"space":{"options":1,"used":1}
,"options":{"allowed":1}
,"allowed":{"default":1}
,"passing":{"tag_name":1}
,"your_l4t_root":{"linux_for_tegra":1,"location":1}
,"location":{"relative":1,"source_sync.sh":1,"l4t":1,"gpt":1,"booting":1,"easily":1,"data":1}
,"relative":{"location":1}
,"placed":{"directory":1}
,"rest":{"instructions":1,"procedure":1}
,"instructions":{"assume":1}
,"assume":{"current":1}
,"current":{"working":1}
,"working":{"directory":1}
,"check":{"git":1}
,"checkout":{"branch_name":1}
,"branch_name":{"tag_name":1,"name":1}
,"local":{"branch":1,"network":1,"directory":1,"bin":1}
,"export":{"cross_compile":1}
,"cross_compile":{"cross_prefix":1}
,"cross_prefix":{"absolute":1}
,"absolute":{"path":1}
,"path":{"arm64":1}
,"arm64":{"toolchain":1}
,".gcc":{"suffix":1}
,"suffix":{"example":1}
,"toolchain_install_path":{"bin":1}
,"bin":{"aarch64-linux-gnu-":1,"beginning":1}
,"recommends":{"using":1}
,"7.3.1":{"2018.05":1}
,"2018.05":{"toolchain":1}
,"copy":{"updated":1,"new":1,"root":1,"always":1,"environment":1}
,"command":{"linux":1,"line":1,"path":1,"build":1,"jetson":1,"attach":1,"read":1,"bootcmd":1,"true":1,"prompt":1,"target":1,"functions":1,"preserved":1}
,"uboot_src_dir":{"u-boot":1,"your_l4t_root":1}
,".bin":{".dtb":1}
,".dtb":{",-dtb.bin":1,"files":1}
,"full":{"jetson":1,"pathname":1,"boot":1,"list":1}
,"boot":{"time":1,"configuration":1,"storage":1,"memory":1,"partition":1,"device":1,"directory":1,"jetson":1,"nfs":1,"sequence":1,"extlinux":1,"location":1,"information":1,"command":1,"scripts":1,"configurations":1,"script":1,"process":1,"specific":1,"menu":1,"devices":1,"files":1,"file":1,"using":1,"kernel":1,"options":1,"image":1,"initrd":1,"processing":1,"new":1,"dtb":1}
,"time":{"u-boot":1,"initialize":1,"constrained":1,"storage":1,"configure":1,"taking":1,"user":1,"u\u2011boot":1,"replace":1,"variable":1,"remove":1}
,"fetches":{"boot":1}
,"configuration":{"file":1,"special":1,"files":1,"extlinux.conf":1,"enables":1,"variables":1}
,"reside":{"boot":1}
,"storage":{"device":1,"boot":1,"devices":1,"network":1}
,"card":{"jetson":1,"emmc":1,"usb":1,"slot":1,"dtb":1,"card":1,"plugged":1}
,"2gb":{"p3448-0003":1}
,"p3448-0003":{"original":1}
,"development":{"module":1,"debugging":1}
,"module":{"p3448-0000":1}
,"internal":{"emmc":1}
,"emmc":{"memory":1,"hardware":1,"property":1,"boot":1,"usable":1,"device":1}
,"memory":{"jetson":1,"device":1,"devices":1,"location":1,"built-in":1,"alternative":1,"region":1}
,"execute":{"script":1,"empty":1,"scan_dev_for_extlinux":1,"u-boot":1,"commands":1,"program":1,"sequence":1}
,"flashes":{"u-boot":1,"following":1,"kernel":1}
,"specify":{"command":1,"subset":1}
,"line":{"option":1,"parameters":1,"specifies":1,"added":1}
,"identify":{"storage":1}
,"filesystem":{"enables":1,"internal":1,"boot":1,"nfs":1,"alongside":1,"size":1,"partition":1,"storage":1,"flashed":1,"device":1,"directory":1}
,"enables":{"script":1,"supported":1,"out-of-the-box":1}
,"select":{"appropriate":1,"script":1,"boot":1}
,"appropriate":{"boot":1,"flash":1}
,"contains":{"kernel":1,"u-boot":1,"device":1,"guid":1,"information":1,"dtc":1,"boot":1,"required":1,"series":1,"number":1,"sequence":1,"space-delimited":1,"script":1,"list":1,"just":1}
,"control":{"linux":1,"boot":1}
,"looks":{"root":1,"extlinux.conf":1}
,"flash":{"u-boot":1,"full":1,"new":1,"memory":1,"during":1,"chips":1,"image":1,"board\u0027s":1,"passed":1}
,"mount":{"root":1,"dev":1}
,"causes":{"kernel":1}
,"sudo":{"flash.sh":1,"mount":1}
,"flash.sh":{"platform":1,"ipa":1,"lnx":1,"script":1,"command":1,"flash":1}
,"nfs":{"server":1,"directory":1,"network":1}
,"ipa":{"nfs":1,"host":1,"gateway":1,"netmask":1,"static":1}
,"target":{"ipa":1,"device":1,"system":1}
,"gateway":{"ipa":1}
,"netmask":{"platform":1,"static":1,"local":1}
,"interface":{"name":1,"40\u2011pin":1}
,"server":{"hosting":1,"configured":1}
,"hosting":{"root":1}
,"nfs_directory":{"full":1}
,"pathname":{"exported":1,"directory":1,"filesystem":1}
,"exported":{"root":1}
,"static":{"address":1,"netmask":1}
,"address":{"target":1,"nfs":1,"gateway":1,"lba":1,"pxe":1,"tftp":1}
,"eth0":{"rj45":1}
,"rj45":{"connector":1}
,"connector":{"eth1":1,"developer":1}
,"eth1":{"usb":1}
,"usb":{"ethernet":1,"storage":1,"device":1,"support":1,"devices":1,"entry":1,"mass":1}
,"ethernet":{"dongle":1}
,"dongle":{"supported":1}
,"recommended":{"point-to-point":1}
,"point-to-point":{"network":1}
,"network":{"connections":1,"via":1,"devices":1,"protocols":1,"using":1}
,"connections":{"dhcp":1}
,"dhcp":{"server":1,"pxe":1,"receive":1,"network":1}
,"image":{"reference":1,"above":1,"file":1,"filename":1,"ram":1,"rerunning":1}
,"new":{"version":1,"kernel":1,"contents":1,"device":1,"properties":1,"information":1,"value":1}
,"lnx":{"platform":1,"partition":1}
,"changing":{"boot":1}
,"partition":{"layout":1,"contains":1,"size":1,"largest":1,"key":1,"table":1,"ordinarily":1,"u-boot":1,"boot":1,"bootable":1,"number":1,"mounted":1,"alternatively":1,"enter":1}
,"based":{"card":1,"layout":1,"content":1}
,"hardware":{"software":1,"features":1,"support":1,"happen":1}
,"layout":{"information":1,"determination":1,"boot":1,"xml":1}
,"cfg":{"flash_l4t_t210_spi_sd_p3448.xml":1,"flash_l4t_t186.xml":1,"gnu_linux_tegraboot_emmc_full.xml":1}
,"installed":{"filesystem":1,"l4t":1}
,"alongside":{"boot":1}
,"property":{"determined":1,"dtb":1,"extlinux.conf":1,"separated":1}
,"determined":{"two":1,"u-boot":1}
,"two":{"variables":1}
,"variables":{"linux_for_tegra":1,"compile":1,"modified":1,"data":1,"u\u2011boot":1,"example":1,"scripts":1,"flash":1}
,"target_board":{".conf.common":1}
,"bootpartsize":{"specifies":1,"user":1}
,"specifies":{"emmc":1,"pathname":1,"fdtoverlays":1}
,"size":{"boot0":1,"boot1":1,"bootpartsize":1,"obtained":1,"total":1,"partition":1}
,"boot0":{"partition":1,"boot1":1}
,"boot1":{"partition":1,"user":1}
,"emmcsize":{"specifies":1}
,"usable":{"data":1}
,"data":{"size":1,"area":1,"stored":1,"determined":1,"missing":1,"flash":1,"written":1,"using":1,"$fdt_addr":1}
,"user":{"partition":1,"boot":1,"may":1,"wants":1,"requests":1,"three":1}
,"obtained":{"emmc":1}
,"limits":{"size":1}
,"total":{"usable":1,"space":1}
,"determines":{"location":1,"legal":1}
,"gpt":{"partitions":1,"partition":1,"serves":1}
,"largest":{"partitions":1}
,"partitions":{"size":1,"cannot":1,"automatically":1}
,"key":{"factors":1,"presses":1,"interrupt":1}
,"factors":{"partition":1}
,"modify":{"root":1,"value":1,"include":1,"manufacturing":1,"save":1,"jetson":1,"l4t":1,"extlinux.conf":1,"kernel":1,"devices":1}
,"value":{"rootfssize":1,"configs":1,"application":1,"devplist":1,"rather":1,"bootdelay":1,"boot_targets":1,"compile":1,"variable":1}
,"rootfssize":{"variable":1}
,"variable":{"linux_for_tegra":1,"specify":1,"single":1,"contain":1,"script":1,"affect":1,"desired":1,"value":1,"prevents":1,"u\u2011boot":1}
,".conf.common":{"file":1}
,"cannot":{"exceed":1,"represent":1}
,"exceed":{"emmcsize":1}
,"creates":{"primary":1}
,"primary":{"secondary":1,"gpt":1,"kernel":1}
,"secondary":{"gpt":1}
,"automatically":{"based":1,"boot":1}
,"protective":{"mbr":1}
,"mbr":{"contains":1}
,"prevent":{"traditional":1}
,"traditional":{"bootloaders":1}
,"bootloaders":{"performing":1,"passes":1,"used":1}
,"performing":{"destructive":1}
,"destructive":{"actions":1}
,"actions":{"located":1}
,"logical":{"block":1}
,"block":{"address":1}
,"guid":{"partition":1}
,"table":{"located":1,"identifies":1,"determine":1}
,"serves":{"backup":1}
,"backup":{"located":1}
,"last":{"lba":1}
,"lba":{"boot":1,"varies":1}
,"varies":{"device":1}
,"able":{"obtain":1}
,"obtain":{"last":1}
,"ordinarily":{"contains":1}
,"however":{"partition":1}
,"reads":{"kernel":1}
,"app":{"partition":1}
,"flashed":{"partition":1}
,"expects":{"boot":1}
,"exist":{"rootfs":1}
,"rootfs":{"boot":1,"image":1,"booting":1,"jetson":1,"following":1,"card":1}
,"extlinux":{"extlinux.conf":1,"location":1,"configuration":1,"control":1}
,"treats":{"root":1}
,"filesystem-on-ip-network":{"configuration":1}
,"special":{"case":1}
,"case":{"flashes":1,"builds":1,"represent":1,"jetson-mcp251x.dtbo":1,"resets":1}
,"pass":{"dtc":1}
,"filename":{"parameter":1,"device":1,"kernel":1}
,"parameter":{"u\u2011boot":1}
,"environment":{"ensure":1,"configuration":1,"u-boot":1,"variables":1,"variable":1,"save":1,"data":1,"examples":1,"case":1}
,"ensure":{"local":1}
,"usr":{"local":1}
,"beginning":{"shell":1}
,"shell":{"command":1,"interrupted":1,"reached":1,"commands":1}
,"git.kernel.org":{"pub":1}
,"pub":{"scm":1}
,"scm":{"utils":1}
,"utils":{"dtc":1}
,"procedure":{"assumes":1,"applies":1}
,"assumes":{"current":1,"bootloader":1}
,"$home":{"run":1}
,"specific":{"directory":1,"device":1,"manner":1,"storage":1}
,"prefix":{"usr":1,"specifies":1}
,"builds":{"following":1}
,"directories":{"below":1,"scan":1}
,"below":{"installation":1,"supports":1,"following":1}
,"installation":{"directory":1}
,"replacing":{"kernel":1}
,"replace":{"kernel":1,"script":1}
,"custom":{"kernel":1}
,"device\u2019s":{"type":1}
,"type":{"boot":1,"file":1}
,"directly":{"live":1,"rather":1}
,"live":{"system":1}
,"process":{"card":1,"access":1,"u-boot":1,"write":1,"sends":1,"programs":1,"specified":1,"cause":1}
,"scp":{"boot":1,"copy":1}
,"reboot":{"jetson":1}
,"boots":{"card":1,"kernel":1,"system":1}
,"connect":{"boot":1,"terminal":1}
,"disconnect":{"boot":1}
,"enter":{"following":1,"commands":1,"command":1}
,"dev":{"mmcblk0p1":1}
,"mmcblk0p1":{"mnt":1,"rootwait":1}
,"mnt":{"boot":1}
,"copying":{"root":1}
,"external":{"media":1,"card":1}
,"media":{"copy":1}
,"attach":{"device":1}
,"adds":{"required":1}
,"sequence":{"sysboot":1,"scans":1,"during":1,"u-boot":1,"commands":1,"u\u2011boot":1}
,"sysboot":{"configuration":1,"command":1}
,"includes":{"default":1}
,"booting":{"scan":1,"extlinux.conf":1,"require":1,"jetson":1,"reduce":1}
,"scan":{"sequence":1,"boot":1}
,"scans":{"bootable":1,"find":1}
,"bootable":{"devices":1,"partition":1,"device":1}
,"nvme":{"device":1}
,"via":{"dhcp":1,"booti":1,"denx":1}
,"extlinux.conf":{"configuration":1,"file":1,"standard":1,"uses":1,"regenerate":1,"rootfs":1,"boot":1,"remove":1,"file\u2019s":1,"better":1}
,"upon":{"finding":1}
,"finding":{"extlinux.conf":1}
,"performs":{"following":1}
,"uses":{"sysboot":1,"default":1,"extlinux":1,"find":1,"timeout":1,"apply":1}
,"read":{"boot":1}
,"loads":{"kernel":1,"executes":1,"configuration":1}
,"user-accessible":{"rootfs":1}
,"easily":{"change":1}
,"change":{"files":1}
,"test":{"kernel":1}
,"text-format":{"sysboot":1}
,"indicates":{"kernel":1}
,"blob":{"filename":1}
,"optimizing":{"u-boot":1}
,"searches":{"available":1,"root":1}
,"out-of-the-box":{"support":1}
,"support":{"widest":1,"takes":1,"reduce":1,"plug-in":1,"needed":1,"new":1,"multi-line":1,"missing":1}
,"widest":{"possible":1}
,"possible":{"variety":1,"values":1,"add-on":1}
,"variety":{"storage":1}
,"flexibility":{"delays":1,"may":1}
,"delays":{"execution":1,"enumerating":1}
,"execution":{"final":1,"waits":1}
,"final":{"operating":1}
,"operating":{"system":1}
,"takes":{"time":1}
,"initialize":{"scanning":1,"environment":1}
,"scanning":{"attached":1}
,"attached":{"storage":1,"usb":1,"nvme":1,"may":1}
,"constrained":{"pre-configured":1,"cases":1}
,"pre-configured":{"systems":1}
,"necessary":{"may":1,"nodes":1}
,"know":{"ahead":1,"type":1}
,"ahead":{"time":1}
,"certain":{"devices":1}
,"need":{"initialized":1}
,"initialized":{"bootloader":1}
,"optimize":{"boot":1}
,"configure":{"u-boot":1}
,"reduce":{"system":1,"boot":1}
,"taking":{"advantage":1}
,"advantage":{"constraints":1}
,"changes":{"made":1,"needed":1}
,"made":{"u\u2011boot":1}
,"disabling":{"pcie":1,"aspm":1,"usb":1}
,"pcie":{"support":1,"devices":1,"device":1,"aspm":1}
,"enumerating":{"initializing":1}
,"initializing":{"pcie":1,"active":1,"usb":1}
,"until":{"user":1}
,"explicitly":{"attempts":1}
,"attempts":{"access":1,"initialize":1,"load":1}
,"access":{"pcie":1,"usb":1,"u-boot":1}
,"consequently":{"disabling":1}
,"disable":{"pcie":1,"aspm":1,"usb":1}
,"remove":{"following":1,"include":1,"usb":1,"timeout":1,"lines":1}
,"include":{"configs":1,"tegra-common-usb-gadget.h":1,"config_distro_bootcmd.h":1,"config":1}
,"configs":{"board":1,"board_and_rev":1,"tegra-common-post.h":1,"tegra\u2011common\u2011post.h":1}
,"enabling":{"disabling":1}
,"aspm":{"support":1,"pcie":1,"device":1}
,"active":{"state":1}
,"state":{"power":1}
,"power":{"management":1,"reset":1}
,"enable":{"aspm":1}
,"add":{"following":1,"command-line":1,"necessary":1,"support":1}
,"edit":{"include":1,"u-boot":1,"boot":1,"extlinux.conf":1}
,"tegra-common-post.h":{"remove":1}
,"entry":{"boot_target_devices":1}
,"runtime":{"behavior":1}
,"behavior":{"controlled":1}
,"controlled":{"scripts":1}
,"begins":{"execution":1,"running":1}
,"waits":{"bootdelay":1}
,"bootdelay":{"seconds":1}
,"seconds":{"executing":1,"u-boot":1,"booting":1}
,"executing":{"automatic":1,"scan_dev_for_scripts":1,"attempts":1}
,"automatic":{"boot":1}
,"during":{"time":1,"subsequent":1,"development":1}
,"interrupt":{"boot":1,"u-boot":1,"automatic":1}
,"interrupted":{"u-boot":1}
,"executes":{"bootcmd":1,"commands":1}
,"bootcmd":{"shell":1,"contains":1}
,"search":{"storage":1,"unnecessary":1,"extlinux":1,"u-boot":1}
,"modifying":{"values":1,"variable":1}
,"manufacturing":{"time":1,"flashing":1,"flow":1,"process":1}
,"directed":{"boot":1}
,"manner":{"thereby":1}
,"thereby":{"reducing":1}
,"reducing":{"boot":1}
,"identifies":{"variables":1}
,"number":{"seconds":1,"known":1,"hexadecimal":1}
,"pauses":{"determine":1}
,"determine":{"whether":1,"partition":1}
,"whether":{"user":1}
,"wants":{"interrupt":1}
,"eliminate":{"delay":1}
,"note":{"user":1,"simple":1,"entries":1,"default":1,"changed":1}
,"requests":{"interrupt":1}
,"reached":{"request":1}
,"request":{"honored":1}
,"honored":{"even":1}
,"even":{"bootdelay":1,"single":1}
,"delay":{"less":1}
,"less":{"u\u2011boot":1}
,"displays":{"boot":1}
,"menu":{"disables":1,"label":1,"title":1,"user":1}
,"disables":{"autoboot":1}
,"executed":{"automatically":1}
,"simple":{"customizations":1}
,"customizations":{"selecting":1}
,"selecting":{"specific":1}
,"require":{"editing":1,"alternative":1}
,"editing":{"value":1}
,"space-delimited":{"list":1}
,"list":{"storage":1,"file":1,"u-boot":1,"supported":1,"directory":1,"contents":1,"devices":1}
,"protocols":{"u-boot":1}
,"find":{"boot":1}
,"valid":{"values":1}
,"mmc0":{"built-in":1,"saveenv":1}
,"built-in":{"emmc":1,"copy":1,"default":1}
,"mmc1":{"card":1}
,"usb0":{"attached":1}
,"mass":{"storage":1}
,"nvme0":{"attached":1}
,"pxe":{"network":1,"download":1}
,"receive":{"address":1}
,"syslinux":{"configuration":1,"pxelinux":1}
,"tftp":{"download":1}
,"subset":{"possible":1}
,"single":{"value":1,"partition":1,"directory":1,"line":1}
,"application":{"require":1,"serial":1}
,"parse":{"device":1}
,"known":{"ahead":1,"extlinux":1,"u-boot":1}
,"simpler":{"script":1}
,"hard-codes":{"value":1}
,"devplist":{"single":1}
,"hexadecimal":{"runs":1}
,"runs":{"either":1,"executes":1}
,"layouts":{"vary":1}
,"vary":{"different":1}
,"different":{"installations":1}
,"installations":{"example":1}
,"system\u2019s":{"root":1}
,"separate":{"partition":1}
,"mounted":{"elsewhere":1}
,"elsewhere":{"file":1}
,"cases":{"user":1}
,"unnecessary":{"directories":1}
,"entries":{"variable":1}
,"contain":{"leading":1}
,"leading":{"trailing":1}
,"trailing":{"slash":1}
,"found":{"boots":1,"loads":1,"parsing":1}
,"innocuous":{"command":1}
,"true":{"leave":1,"explanation":1}
,"leave":{"empty":1}
,"empty":{"u\u2011boot":1,"variable":1}
,"complain":{"attempt":1}
,"attempt":{"execute":1}
,"explanation":{"scan_dev_for_extlinux":1}
,"scan_dev_for_extlinux":{"prior":1}
,"prior":{"executing":1,"flashing":1}
,"scan_dev_for_scripts":{"therefore":1,"search":1}
,"therefore":{"modifying":1}
,"affect":{"systems":1}
,"names":{"scan_dev_for_scripts":1,"upper":1,"lower":1}
,"desired":{"value":1}
,"rather":{"default":1,"using":1,"reference":1}
,"starts":{"executing":1}
,"stored":{"flash":1,"boot":1}
,"missing":{"corrupted":1,"hardware":1}
,"corrupted":{"u-boot":1}
,"write":{"data":1,"saved":1,"execute":1}
,"always":{"used":1}
,"initially":{"built-in":1}
,"places":{"u-boot":1}
,"fixed-space":{"names":1}
,"upper":{"case":1}
,"represent":{"configuration":1,"environment":1,"every":1,"plug-in":1,"comprehensive":1}
,"lower":{"case":1}
,"defines":{"variables":1}
,"related":{"automatic":1}
,"config":{"auto.conf":1,"board":1}
,"config_bootdelay":{"sets":1}
,"sets":{"value":1}
,"boot_target_devices":{"sets":1,"determines":1}
,"legal":{"values":1}
,"appear":{"boot_targets":1,"key":1}
,"boot_targets":{"removing":1,"board-specific":1,"mmc0":1}
,"removing":{"entries":1,"extlinux.conf":1}
,"prevents":{"values":1}
,"config_distro_bootcmd.h":{"avoid":1}
,"avoid":{"setting":1}
,"board-specific":{"configuration":1}
,"already":{"defined":1}
,"defined":{"value":1}
,"flow":{"write":1}
,"saved":{"copy":1,"extracted":1,"environment":1,"modified":1}
,"ways":{"modify":1}
,"arrange":{"board":1}
,"cause":{"u-boot":1,"conflicts":1}
,"save":{"environment":1,"extract":1,"modified":1}
,"reset":{"board":1}
,"sent":{"using":1}
,"serial":{"console":1,"port":1}
,"console":{"write":1,"ttys0,115200n8":1,"tty0":1,"output":1}
,"program":{"host":1}
,"detects":{"u-boot":1}
,"running":{"interrupts":1}
,"interrupts":{"u-boot":1}
,"sends":{"commands":1,"console":1}
,"env":{"default":1,"directory":1}
,"setenv":{"boot_targets":1,"environment_variable":1,"stdout":1}
,"manually":{"edit":1}
,"extract":{"appropriate":1}
,"region":{"file":1}
,"xml":{"file":1}
,"written":{"flash":1}
,"subsequent":{"flashing":1}
,"technique":{"manufacturing":1}
,"programs":{"flash":1}
,"chips":{"directly":1}
,"tools":{"board":1,"env":1}
,"merge":{"saved":1}
,"generate":{"saved":1}
,"fw_env":{"tool":1}
,"tool":{"located":1}
,"specified":{"syslinux":1,"fdt":1}
,"pxelinux":{"spec":1}
,"spec":{"loads":1}
,"ram":{"disk":1}
,"disk":{"optionally":1}
,"optionally":{"kernel":1}
,"dtb":{"add":1,"overlays":1,"overlay":1,"cannot":1,"source":1,"difficult":1,"distributed":1,"loaded":1,"kernel":1,"specified":1,"bootloaders":1,"files":1,"rootfs":1,"jetson-mcp251x.dtbo":1,"file\u2019s":1,"jetson-mcp51x.dtbo":1,"located":1}
,"command-line":{"arguments":1}
,"arguments":{"kernel":1}
,"timeout":{"default":1}
,"label":{"kernel":1,"primary":1,"line":1,"load":1}
,"initrd":{"fdt":1,"boot":1}
,"fdt":{"append":1,"property":1,"ensures":1,"addr":1,"resize":1,"apply":1,"print":1}
,"append":{"directives":1,"cbootargs":1}
,"directives":{"example":1}
,"extensions":{"described":1}
,"regenerate":{"system.img":1}
,"system.img":{"rootfs":1}
,"rerunning":{"flash.sh":1}
,"board\u0027s":{"app":1,"kernel":1}
,"alternatively":{"edit":1}
,"apply":{"new":1,"$fdtoverlay_addr_r":1,"dtbo":1}
,"contents":{"next":1,"directory":1,"boot":1}
,"next":{"reboot":1}
,"title":{"l4t":1}
,"cbootargs":{"root":1}
,"rootwait":{"rootfstype":1}
,"rootfstype":{"ext4":1}
,"ext4":{"console":1}
,"ttys0,115200n8":{"console":1}
,"tty0":{"fbcon":1}
,"fbcon":{"map:0":1}
,"map:0":{"net.ifnames":1}
,"configured":{"display":1}
,"display":{"boot":1}
,"three":{"seconds":1}
,"processing":{"time":1}
,"lines":{"containing":1}
,"load":{"dtb":1,"multiple":1,"driver":1,"dtbo":1,"mmc":1,"method":1}
,"overlay":{"dtbo":1,"files":1,"contains":1,"fe-pi":1,"case":1,"u-boot":1,"file":1,"load":1}
,"dtbo":{"files":1,"file":1}
,"plug-in":{"devices":1}
,"imx477":{"camera":1}
,"camera":{"mcp51x":1}
,"mcp51x":{"controller":1}
,"controller":{"fe-pi":1}
,"fe-pi":{"audio":1}
,"audio":{"card":1}
,"identified":{"extlinux.conf":1}
,"file\u2019s":{"fdtoverlays":1,"data":1}
,"fdtoverlays":{"property":1,"without":1,"line":1,"boot":1}
,"overlays":{"useful":1,"used":1,"typically":1}
,"useful":{"carrier":1}
,"carrier":{"board\u0027s":1}
,"every":{"possible":1}
,"add-on":{"device":1}
,"40\u2011pin":{"expansion":1}
,"expansion":{"connector":1,"header":1}
,"nodes":{"properties":1,"device":1}
,"properties":{"changes":1,"nodes":1,"keep":1,"attempts":1}
,"needed":{"support":1,"device":1}
,"reflash":{"reload":1}
,"reload":{"dtb":1}
,"difficult":{"error-prone":1}
,"error-prone":{"process":1}
,"conflicts":{"phandles":1}
,"phandles":{"repeated":1}
,"repeated":{"times":1}
,"times":{"during":1}
,"better":{"approach":1}
,"approach":{"add":1,"fdtoverlays":1}
,"loading":{"overlay":1,"dtb":1}
,"onto":{"kernel":1}
,"distributed":{"jetson":1}
,"just":{"new":1}
,"merges":{"dtbo":1}
,"named":{"fdtoverlays":1}
,"loaded":{"earlier":1,"overlay":1}
,"earlier":{"bootloaders":1}
,"passes":{"merged":1}
,"merged":{"dtb":1,"dtbo":1}
,"along":{"disk-based":1}
,"disk-based":{"kernel":1}
,"ensures":{"dtb":1}
,"passed":{"kernel":1}
,"including":{"overlays":1}
,"typically":{"stored":1}
,"convention":{"extension":1}
,"extension":{".dtbo":1}
,".dtbo":{"overlay":1}
,"distinguish":{"global":1}
,"global":{".dtb":1}
,"multiple":{"dtbo":1}
,"listing":{"line":1,"u-boot":1,"commands":1}
,"separated":{"spaces":1}
,"spaces":{"u-boot":1}
,"multi-line":{"properties":1}
,"keep":{"dtbo":1}
,"applying":{"dtbo":1}
,"isn\u2019t":{"attached":1}
,"result":{"errors":1}
,"errors":{"warnings":1}
,"warnings":{"kernel":1}
,"sees":{"nodes":1}
,"happen":{"example":1}
,"plugged":{"40-pin":1}
,"40-pin":{"expansion":1}
,"dbt":{"overlay":1}
,"similar":{"example":1}
,"above":{"illustrates":1}
,"illustrates":{"load":1,"assumes":1}
,"jetson-mcp251x.dtbo":{"note":1}
,"changed":{"menu":1}
,"added":{"fdtoverlays":1}
,"prompt":{"load":1}
,"$fdt_addr":{"rootfs":1,"passed":1}
,"mmc":{"$fdtoverlay_addr_r":1,"0:1":1}
,"$fdtoverlay_addr_r":{"boot":1}
,"addr":{"$fdt_addr":1}
,"resize":{"8192":1}
,"combined":{"dtb":1}
,"booti":{"examined":1}
,"examined":{"dumped":1}
,"dumped":{"fdt":1}
,"print":{"sequence":1,"u-boot":1,"environment":1,"list":1}
,"parsing":{"extlinux.conf":1}
,"manual":{"overlay":1}
,"method":{"discussed":1}
,"discussed":{"u\u2011boot":1}
,"doc":{"readme.fdt-overlays":1}
,"readme":{"available":1}
,"upstream":{"via":1}
,"denx":{"document":1}
,"document":{"fdtoverlays":1}
,"debugging":{"u-boot":1,"tips":1}
,"tips":{"help":1}
,"help":{"debug":1,"text":1}
,"debug":{"u-boot":1}
,"examples":{"represent":1}
,"comprehensive":{"listing":1}
,"usage":{"u-boot":1}
,"consult":{"u-boot":1}
,"documentation":{"source":1}
,"terminal":{"application":1}
,"port":{"board":1}
,"wait":{"u-boot":1}
,"sign-on":{"message":1}
,"message":{"appear":1,"appears":1}
,"presses":{"message":1}
,"appears":{"may":1}
,"press":{"key":1}
,"text":{"enter":1}
,"structure":{"device":1,"emmc":1}
,"functions":{"correctly":1}
,"correctly":{"ext2":1}
,"ext2":{"fat":1}
,"fat":{"file":1}
,"output":{"follows":1,"below":1,"run":1,"looks":1}
,"dir":{"4096":1,"1024":1}
,"4096":{"bin":1,"boot":1,"dev":1,"home":1,"lib":1,"lost":1,"media":1,"mnt":1,"opt":1,"proc":1,"root":1,"sbin":1,"selinux":1,"srv":1,"sys":1,"tmp":1,"usr":1,"var":1}
,"lost":{"found":1}
,"0:1":{"directory":1,"boot":1}
,"shown":{"example":1}
,"908":{"extlinux":1}
,"5910248":{"image":1}
,"system-specific":{"directory":1}
,"implemented":{"u\u2011boot":1}
,"ext2ls":{"fatls":1}
,"printenv":{"environment_variable":1,"stdout":1}
,"environment_variable":{"environment":1,"new_value":1}
,"stdout":{"serial":1}
,"new_value":{"new":1}
,"modified":{"environment":1}
,"preserved":{"saved":1}
,"resets":{"reboots":1}
}
;Search.control.loadWordPairs(pairs);
