var pairs =
{
"asoc":{"driver":1,"core":1,"machine":1,"codecs":1,"architecture":1,"drivers":1,"source":1,"failed":1,"sink":1,"cpu":1,"may":1,"pre_pmu":1,"sound_card":1}
,"driver":{"jetson":1,"enables":1,"may":1,"supports":1,"leverages":1,"instantiation":1,"provides":1,"responsible":1,"admaif":1,"registers":1,"least":1,"connects":1,"together":1,"identifying":1,"software":1,"comprises":1,"pcm":1,"forming":1,"probe":1,"introduces":1,"initializes":1,"subset":1,"asoc":1,"interfaces":1,"helps":1,"platform-agnostic":1,"correct":1,"defines":1,"registered":1,"implementation":1,"interconnects":1,"remaining":1,"used":1,"exposes":1,"linking":1,"audio":1,"available":1,"parses":1,"sound":1,"widgets":1,"uses":1,"sets":1,"details":1,"usage":1,"specifies":1,"dapm":1,"identify":1,"support":1,"decide":1,"enabled":1,"update":1,"whenever":1,"kernel":1,"platforms":1,"updated":1,"integrate":1,"populate":1,"data":1,"prefixed":1,"mixer":1,"i2s":1,"providing":1}
,"jetson":{"products":1,"xavier":1,"tx2":1,"nano":1,"agx":1,"platform":1,"tx1":1,"leverages":1,"platforms":1,"asoc":1,"kernel-dts":1,"devices":1,"high":1,"device":1,"developer":1,"module":1,"i2s":1,"boards":1,"download":1,"platform\u2019s":1}
,"advanced":{"linux":1}
,"linux":{"sound":1,"community":1,"kernel":1,"user":1,"driver":1}
,"sound":{"architecture":1,"device":1,"card":1,"i2s":1,"processors":1,"soc":1,"node":1,"node\u2019s":1,"card\u2019s":1,"interface\u2019s":1,"file":1,"capture":1,"files":1,"cards":1,"audible":1}
,"architecture":{"alsa":1,"inside":1,"asoc":1,"makefile":1,"header":1}
,"alsa":{"framework":1,"system-on-chip":1,"work":1,"includes":1,"software":1,"applications":1,"core":1,"designed":1,"details":1,"support":1,"amixer":1,"interfaces":1,"examples":1,"mixer":1}
,"framework":{"defines":1,"part":1,"jetson":1,"available":1}
,"defines":{"api":1,"dais":1,"mux":1,"cif":1,"snd_soc_dai_link":1,"dapm":1,"number":1}
,"api":{"sound":1}
,"device":{"drivers":1,"tree":1,"registers":1,"add":1,"name":1,"amx":1,"adx":1,"entry":1,"source":1,"properties":1,"i2s":1,"apart":1,"mvc":1,"clocks":1,"dspk":1,"tree\u2019s":1,"present":1,"state":1,"supports":1,"e.g":1,"sure":1,"may":1,"used":1,"node":1,"dev":1,"rt5658":1,"sound":1,"map":1,"change":1,"codec":1}
,"drivers":{"nvidia":1,"including":1,"support":1,"directly":1,"driver":1,"pcm":1,"roles":1,"described":1,"ahub":1,"drivers":1,"connected":1,"presented":1,"responsibilities":1,"platform":1,"i2s":1,"dynamic":1,"probable":1}
,"nvidia":{"alsa":1,"socs":1,"jetson":1,"audio":1,"tegra":1,"platform":1,"tegra210-aconnect":1,"tegra186-axbar":1,"tegra186-i2s":1,"ahub-i2s-id":1,"tegra210-dmic":1,"ahub-dmic-id":1,"tegra186-dspk":1,"ahub-dspk-id":1,"sound":1,"tegra-audio-t186ref-mobile-rt565x":1,"model":1,"num-codec-link":1,"audio-routing":1,"xbar":1,"dai-link-1":1,"tegra-audio-t210ref-mobile-rt565x":1,"dai-link-":1,"recommends":1,"dai-link-x":1,"dai-link-5":1,"dai-link-2":1,"dai-link-4":1,"soc":1,"developer":1}
,"system-on-chip":{"asoc":1,"processors":1}
,"enables":{"alsa":1,"custom":1,"given":1,"mixer":1,"input":1,"instance":1,"eight":1,"first":1,"clock":1,"jetson":1}
,"work":{"seamlessly":1,"correctly":1}
,"seamlessly":{"different":1}
,"different":{"nvidia":1,"types":1,"interfaces":1,"jetson":1,"audio":1,"hda":1,"clock":1,"channel":1,"causes":1}
,"socs":{"platform-independent":1}
,"platform-independent":{"generic":1}
,"generic":{"components":1,"device":1,"block":1,"properties":1}
,"components":{"maintained":1,"enables":1}
,"maintained":{"upstream":1,"larger":1,"dmic":1}
,"upstream":{"linux":1,"apis":1}
,"may":{"directly":1,"referenced":1,"adjusted":1,"connected":1,"i2s":1,"lead":1,"experience":1,"impacted":1,"need":1,"operate":1,"on-board":1,"clocked":1,"support":1,"sourced":1,"needed":1,"choose":1,"value":1,"changed":1,"instantiated":1,"occur":1}
,"directly":{"support":1,"libraries":1,"interface":1,"available":1,"i2s4":1,"indirectly":1}
,"support":{"audio":1,"alsa":1,"adding":1,"various":1,"called":1,"embedded":1,"simultaneous":1,"stereo":1,"channels":1,"third-party":1,"two":1,"rates":1,"dynamic":1,"high":1,"codec":1,"custom":1,"master":1,"modes":1,"asoc":1,"runtime":1,"articles":1}
,"audio":{"hardware":1,"features":1,"playback":1,"capture":1,"header":1,"via":1,"routing":1,"control":1,"applications":1,"pipeline":1,"power":1,"subsystem":1,"codecs":1,"hub":1,"acceleration":1,"multiplexers":1,"demultiplexers":1,"direct":1,"samples":1,"client":1,"devices":1,"input":1,"cross":1,"multiplexer":1,"demultiplexer":1,"interface":1,"audio":1,"paths":1,"components":1,"path":1,"output":1,"codec":1,"connections":1,"data":1,"tape":1,"stream":1,"streams":1,"card":1,"device":1,"format":1,"record":1,"hda":1,"rendering":1,"supports":1,"specification":1,"formats":1,"bandwidth":1,"supported":1,"equipment":1,"accessible":1,"respectively":1,"channels":1,"disabled":1,"profiles":1,"a2dp":1,"package":1,"interfaces":1,"cards":1,"pins":1,"interface\u2019s":1,"pll":1,"panel":1,"connector":1,"directly":1,"function":1,"signals":1,"circular":1,"pops":1}
,"hardware":{"interfaces":1,"audio":1,"codecs":1,"configurations":1,"architecture":1,"module":1,"configuration":1,"conforms":1,"acceleration":1,"settings":1,"devices":1,"nvidia":1,"mux":1,"modules":1}
,"interfaces":{"functionality":1,"jetson":1,"i2s":1,"usb":1,"via":1,"information":1,"signal":1,"playback":1,"exposed":1,"play":1,"usage":1,"pcm":1,"xbar":1,"physical":1,"interface":1,"headphone":1,"may":1,"on-board":1,"used":1,"available":1,"connected":1,"accessible":1,"aplay":1,"proc":1,"instance":1,"ahub":1,"determine":1}
,"functionality":{"present":1}
,"present":{"jetson":1,"fifo":1,"allows":1,"dummy":1,"i2s":1,"codec":1,"due":1}
,"products":{"review":1,"digital":1,"available":1}
,"review":{"following":1,"driver":1}
,"following":{"sections":1,"diagram":1,"directory":1,"example":1,"features":1,"modes":1,"frequency":1,"device":1,"properties":1,"debugfs":1,"table":1,"note":1,"diff":1,"guidelines":1,"examples":1,"patch":1,"command":1,"information":1}
,"sections":{"determine":1,"playback":1,"give":1,"provide":1}
,"determine":{"whether":1,"properties":1,"appropriate":1}
,"whether":{"driver":1,"codec":1,"linux":1,"default":1,"dapm":1,"pinmux":1,"performance":1}
,"supports":{"audio":1,"different":1,"features":1,"bidirectional":1,"following":1,"mixing":1,"five":1,"two":1,"hdmi":1,"pinmux":1,"modes":1,"intel\u2019s":1,"formats":1}
,"features":{"need":1,"supported":1}
,"xavier":{"developer":1,"jetson":1,"instances":1,"series":1,"nvidia":1,"amixer":1,"generates":1,"note":1,"case":1,"idle":1,"devices":1,"hdmi":1,"industrial":1,"audio":1,"asoc":1,"boost":1}
,"developer":{"kit":1,"kits":1,"forum":1}
,"kit":{"jetson":1,"audio":1,"hardware":1,"however":1,"supports":1,"carrier":1}
,"tx2":{"developer":1,"instances":1,"series":1,"hdmi":1,"platforms":1,"sys":1,"example":1,"device":1}
,"playback":{"supported":1,"front":1,"adma":1,"record":1,"capture":1,"pcmc1d0c":1,"pcmc1d1c":1,"stereo":1,"mono":1,"fifo":1,"start":1,"operations":1,"recording":1,"route":1,"ports":1,"pin":1,"volume":1,"switch":1,"port":1,"playback":1,"dspk1":1,"i2s":1,"hdmi":1,"usb":1,"overrun":1,"cpu":1,"dma":1}
,"supported":{"carrier":1,"using":1,"on-board":1,"maintained":1,"instances":1,"hardware":1,"samples":1,"per":1,"monitor":1,"s16_le":1,"s32_le":1,"audio":1,"interfaces":1,"codec":1}
,"carrier":{"board\u2019s":1,"board":1,"boards":1}
,"board\u2019s":{"hdmi":1,"device":1}
,"hdmi":{"interfaces":1,"interface":1,"usb\u2011c":1,"two":1,"1.3a":1,"configuration":1,"hdmi":1,"j504":1,"playback":1,"device":1}
,"capture":{"included":1,"supported":1,"audio":1,"inside":1,"ports":1,"stereo":1,"mono":1,"rate":1,"route":1,"starts":1,"mixer":1,"port":1,"recording":1,"i2s4":1,"dmic3":1,"using":1,"usb":1,"settings":1,"direct":1,"case":1,"via":1,"initiated":1,"dma":1,"data":1,"happen":1}
,"included":{"developer":1,"nvidia":1,"admaif-dma":1}
,"however":{"audio":1,"observe":1}
,"using":{"interfaces":1,"usb":1,"user":1,"device":1,"proprietary":1,"alsa":1,"dapm":1,"widgets":1,"set_runtime_pm_ops":1,"respective":1,"multichannel":1,"different":1,"admaif2":1,"command":1,"following":1,"i2s":1}
,"i2s":{"dmic":1,"dspk":1,"implemented":1,"codec":1,"interfaces":1,"modules":1,"loopback":1,"controller":1,"mode":1,"node":1,"instance":1,"pll_a_out0":1,"device":1,"respective":1,"input":1,"fsync":1,"sample":1,"channels":1,"capture":1,"playback":1,"frame":1,"left-j":1,"mux":1,"module":1,"jetson":1,"dai":1,"interface":1,"bit-clock":1,"slave":1,"right_j":1,"bit":1,"transmitting":1,"receiving":1,"gpio":1,"address":1,"master":1,"operate":1,"respectively":1,"data":1,"internal":1,"ports":1,"i2s_clk_parent":1,"timing":1,"connected":1,"case":1,"probe":1,"used":1,"channel":1,"software":1,"via":1,"starts":1}
,"nano":{"developer":1,"devices":1,"2gb":1,"jetson":1}
,"interface":{"hardware":1,"usb\u2011c":1,"external":1,"acif":1,"application":1,"admaif":1,"dai":1,"i2s-compatible":1,"pdm":1,"soc":1,"pins":1,"defined":1,"connecting":1,"connector":1,"sample":1,"audio":1,"added":1,"i2c":1,"following":1,"exposed":1,"enabled":1,"codec":1,"always":1,"diagram":1,"cpu":1,"configured":1,"error":1,"active":1,"bit":1,"i2s":1}
,"usb":{"i2s":1,"audio":1,"using":1,"microphone":1,"host":1,"devices":1,"device":1,"headphone":1,"ports":1,"card":1}
,"board":{"included":1,"interfaces":1,"interface":1,"dummy":1,"may":1,"consequently":1,"shown":1,"name":1,"i2s":1}
,"agx":{"xavier":1,"rt5659":1}
,"front":{"panel":1}
,"panel":{"audio":1,"header":1}
,"header":{"via":1,"file":1,"describes":1,"exposes":1,"connect":1,"topic":1,"i2c":1,"i2s":1,"platform-specific":1,"dai":1,"drive":1,"external":1,"jetson":1,"j511":1,"pinout":1,"internally":1,"configure":1}
,"via":{"on-board":1,"usb\u2011c":1,"interfaces":1,"byte":1,"dap3":1,"dap5":1,"dap4":1,"dap1":1,"dap2":1,"dap6":1,"usb-c":1,"header":1,"admaif":1,"adder1":1,"i2s":1,"ahub":1}
,"on-board":{"realtek":1,"hdmi":1,"oscillator":1,"alc5658":1}
,"realtek":{"alc5658":1}
,"alc5658":{"codec":1}
,"codec":{"hdmi":1,"possible":1,"drivers":1,"blocks":1,"module\u2019s":1,"driver":1,"machine":1,"board":1,"given":1,"bit":1,"frame":1,"master":1,"i2s\u2019s":1,"soc":1,"headphone":1,"clocks":1,"clock":1,"found":1,"widgets":1,"represent":1,"present":1,"connected":1,"40-pin":1,"slave":1,"i2s":1,"common":1,"jetson":1,"node":1,"add":1,"device":1,"codecs":1,"uses":1,"configure":1,"may":1,"cpu":1,"asoc":1,"clocking":1,"exploring":1,"driver\u0027s":1,"dapm":1,"dai":1,"configuration":1,"board\u2019s":1,"operates":1,"interface":1,"absence":1,"operate":1,"sysclk":1,"requires":1,"typically":1,"timing":1,"order":1,"initialization":1,"operation":1,"provides":1,"mclk":1,"enabling":1,"init":1,"parameters":1,"shown":1,"whenever":1,"integration":1,"following":1,"mixer":1,"functional":1,"datasheet":1,"verify":1,"instantiated":1,"enabled":1,"config.gz":1,"example":1,"configured":1,"probed":1,"place":1,"determine":1,"vendor":1,"pins":1,"dai\u2019s":1,"appropriate":1,"problem":1,"powered":1}
,"usb\u2011c":{"interfaces":1,"display":1,"ports":1}
,"display":{"port":1,"resolutions":1,"resolution":1,"settings":1}
,"port":{"adapter":1,"port":1,"ahub":1,"transmitting":1,"exposed":1,"adx":1,"mixer":1,"output":1,"connected":1,"names":1,"play":1,"numbering":1,"record":1,"devid":1,"device":1,"name":1,"platform-specific":1,"correct":1}
,"adapter":{"usb":1}
,"possible":{"capture":1,"channels":1,"values":1,"parents":1,"devid":1,"causes":1}
,"microphone":{"i2s":1,"inputs":1,"headphone":1,"jack":1}
,"part":{"linux":1,"alsa":1,"integrating":1,"configuring":1}
,"kernel":{"supported":1,"space":1,"controls":1,"flashed":1,"kernel-4.9":1,"control":1,"sources":1,"nvidia":1,"source":1,"debug":1,"driver":1,"enabling":1,"configuration":1,"selecting":1,"config":1,"log":1}
,"larger":{"linux":1}
,"community":{"makes":1}
,"makes":{"feasible":1,"easier":1}
,"feasible":{"adapt":1}
,"adapt":{"framework":1}
,"platform":{"designing":1,"passed":1,"driver":1,"board":1,"codec":1,"either":1,"t19x":1,"customize":1,"support":1,"t210":1,"t18x":1,"probe":1,"subsequent":1,"devid":1,"dai":1,"used":1}
,"designing":{"driver":1}
,"leverages":{"nvidia":1,"features":1}
,"routing":{"support":1,"available":1,"audio":1,"scenarios":1,"examples":1,"connections":1,"kcontrols":1,"path":1,"general":1,"complex":1}
,"includes":{"collection":1,"libraries":1}
,"collection":{"sound":1}
,"card":{"drivers":1,"consult":1,"device":1,"instantiation":1,"software":1,"update":1,"registration":1,"name":1,"details":1,"enumerated":1,"external":1,"configure":1,"order":1,"sgtl5000-codec":1,"shown":1,"refers":1}
,"including":{"actual":1,"limited":1,"usb":1}
,"actual":{"codec":1,"hardware":1,"codecs":1}
,"adding":{"new":1}
,"new":{"codec":1,"devices":1,"device":1}
,"libraries":{"utilities":1,"control":1,"include":1,"initialize":1}
,"utilities":{"enable":1,"dynamically":1,"rendering":1}
,"enable":{"refined":1,"flag":1,"internal":1,"additional":1,"disable":1,"mask":1,"bluetooth":1,"codec":1,"sgtl5000":1,"support":1,"capture":1,"playback":1,"grep":1,"maximum":1}
,"refined":{"audio":1}
,"control":{"linux":1,"audio":1,"mvc":1,"module":1,"enable":1,"applies":1,"interface":1,"settings":1,"port":1,"volume":1}
,"user":{"space":1,"determine":1,"interface":1,"home":1}
,"space":{"libraries":1,"drivers":1,"alsa":1,"apis":1,"applications":1,"using":1,"utilities":1}
,"applications":{"without":1,"interact":1,"aplay":1}
,"without":{"having":1,"rebuilding":1,"entries":1,"codec":1}
,"having":{"interact":1,"txcif":1}
,"interact":{"kernel":1,"alsa":1}
,"include":{"alsa":1}
,"diagram":{"illustrates":1,"alsa":1,"summarizes":1,"below":1,"shows":1,"description":1,"codec":1}
,"illustrates":{"alsa":1,"generic":1}
,"software":{"hierarchy":1,"architecture":1,"configurable":1,"component":1,"driver":1,"stack":1,"changes":1,"reset":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1}
,"automatically":{"generated":1}
,"core":{"kernel":1,"provides":1,"manages":1,"viewed":1,"logic":1,"snd_soc_codec_driver":1,"call":1}
,"apis":{"provided":1,"dma":1}
,"provided":{"user-space":1,"pins":1,"external":1}
,"user-space":{"libraries":1}
,"initialize":{"actual":1}
,"codecs":{"backend":1,"comprises":1,"listed":1,"involves":1,"number":1,"spdif-dit0":1,"replaced":1,"rt5658":1,"either":1,"may":1}
,"backend":{"audio":1}
,"information":{"alsa":1,"clocking":1,"supported":1,"topic":1,"pinmux":1,"certain":1,"possible":1}
,"https":{"www.kernel.org":1,"www.intel.com":1}
,"designed":{"support":1}
,"various":{"functionalities":1,"codec":1,"groups":1,"kinds":1,"ahub":1,"hardware":1,"jetson":1,"usb":1,"audio":1,"device":1,"alsa":1,"modules":1}
,"functionalities":{"including":1}
,"limited":{"dynamic":1}
,"dynamic":{"audio":1,"power":1,"range":1,"ramp":1}
,"available":{"pcm":1,"codec":1,"enabled":1,"kernel":1,"various":1,"audio":1,"card":1,"bsp":1,"show":1,"40-pin":1,"interfaces":1,"i2s":1,"i2c":1}
,"pcm":{"devices":1,"registration":1,"driver":1,"interfaces":1,"pulse":1,"audio":1,"delta-sigma":1,"signal":1,"bit":1,"parameters":1,"sample-rate":1,"data":1,"device":1}
,"devices":{"component":1,"platform":1,"jetson":1,"expected":1,"nvidia":1,"asoc":1,"device":1,"digital":1,"avoid":1,"codecs":1,"similar":1,"work":1,"tvs":1,"i.e":1,"including":1,"speakers":1,"proc":1,"dev":1,"different":1}
,"component":{"alsa":1,"details":1,"included":1,"asoc":1}
,"provides":{"support":1,"better":1,"define":1,"overview":1,"nvidia":1,"flexibility":1,"set_sysclk":1,"set_pll":1}
,"called":{"dynamic":1,"audio":1}
,"power":{"management":1,"flow":1,"consumption":1,"help":1,"efficiency":1,"corresponding":1,"switching":1,"clocks":1,"supplies":1,"dapm":1}
,"management":{"dapm":1,"kcontrols":1,"option":1}
,"dapm":{"dapm":1,"controls":1,"introduces":1,"part":1,"widgets":1,"paths":1,"path":1,"routes":1,"tracing":1}
,"controls":{"power":1,"form":1,"registered":1,"listed":1,"instance":1,"jetson":1,"configure":1,"enter":1,"grep":1,"codec":1,"refer":1,"enable":1}
,"flow":{"various":1,"reversed":1,"thereby":1}
,"blocks":{"audio":1}
,"subsystem":{"minimizing":1,"codec":1}
,"minimizing":{"power":1}
,"consumption":{"dapm":1}
,"introduces":{"switches":1,"mux":1}
,"switches":{"kernel":1}
,"form":{"widgets":1,"full":1}
,"widgets":{"turn":1,"classified":1,"power":1,"xbar":1,"audio":1,"establishing":1,"interfacing":1,"permanently":1,"inside":1,"implemented":1,"establish":1,"indicated":1,"follows":1,"shown":1,"routes":1,"platform\u2019s":1,"machine":1,"defined":1,"codec":1,"input":1,"connected":1,"hp_out":1,"connect":1,"value":1,"specified":1,"capture":1,"spdif-dit":1}
,"turn":{"module\u2019s":1,"fixed":1,"connected":1}
,"module\u2019s":{"power":1}
,"help":{"manipulate":1,"patch":1,"post":1}
,"manipulate":{"required":1}
,"required":{"bit":1,"device":1,"sampling":1,"sources":1,"except":1,"field":1,"support":1,"interface":1,"enabling":1,"codec":1,"internal":1,"pinmux":1}
,"bit":{"specific":1,"hardware":1,"format":1,"width":1,"clock":1,"masks":1,"frame":1}
,"specific":{"register":1,"input":1,"output":1,"mixer":1,"admaif":1,"devid":1}
,"register":{"dynamically":1,"setting":1,"base":1,"initialization":1,"dump":1}
,"dynamically":{"using":1,"control":1}
,"aplay":{"arecord":1,"utility":1,"-dhw":1,"output":1,"hw:tegrasndt19xmob":1,"cardname":1}
,"arecord":{"amixer":1,"utilities":1,"-dhw":1,"wav":1,"-dhw:tegrasndt19xmob":1,"cardname":1}
,"amixer":{"widgets":1,"utility":1,"tegrasndt19xmob":1,"cardname":1}
,"classified":{"various":1}
,"terms":{"software":1,"bit-clocks":1,"functional":1}
,"hierarchy":{"dapm":1,"diagram":1}
,"manages":{"codec":1}
,"efficiency":{"alsa":1}
,"clocking":{"power":1,"requirements":1,"establish":1}
,"tree":{"data":1,"composed":1,"structures":1,"example":1,"structure":1,"instantiated":1,"edit":1,"entry":1,"files":1,"node":1,"entries":1,"i.e":1,"order":1,"properties":1,"configuration":1,"file":1,"different":1,"asoc":1,"nodes":1,"binding":1,"40-pin":1,"documentation":1,"source":1,"log":1}
,"data":{"structure":1,"xbar":1,"admaif":1,"specific":1,"synchronization":1,"forming":1,"available":1,"table":1,"flow":1,"transfer":1,"dsp":1,"offset":1,"onto":1,"formats":1,"passing":1,"mvc":1,"machine":1,"default":1,"slots":1,"stream":1,"pin":1,"sent":1,"sheet":1,"mux":1,"parameter":1,"path":1,"received":1,"dmic3":1,"appropriate":1,"case":1,"lost":1,"codec":1,"specified":1}
,"structure":{"describes":1,"parsed":1,"asoc":1,"provides":1,"pcm":1,"files":1,"jetson":1,"file":1,"dts":1,"linux":1}
,"describes":{"devices":1,"route":1,"interfacing":1,"issues":1}
,"passed":{"operating":1,"codec":1}
,"operating":{"system":1}
,"system":{"boot":1,"makes":1,"bluetooth.service.d":1,"performance":1,"reading":1,"format":1,"latencies":1}
,"boot":{"time":1,"complete":1,"dts":1,"asoc":1,"indicates":1}
,"time":{"avoid":1,"oct":1,"division":1,"therefore":1,"depending":1,"consequently":1}
,"avoid":{"hard":1,"need":1,"clock":1,"loss":1,"saturation":1}
,"hard":{"coding":1}
,"coding":{"component":1}
,"details":{"operating":1,"writing":1,"hardware":1,"route":1,"driver":1,"proc":1,"properties":1,"codec":1,"intel\u2019s":1,"mixer":1}
,"easier":{"change":1}
,"change":{"hardware":1,"assigned-clock-rates":1,"line":1,"instructions":1,"pathname":1}
,"configurations":{"without":1}
,"rebuilding":{"kernel":1}
,"composed":{"nodes":1}
,"nodes":{"properties":1,"property":1,"clocks":1}
,"properties":{"node":1,"child":1,"platform-specific":1,"fsync-width":1,"sound":1,"described":1,"required":1,"unique":1,"dai":1,"configured":1,"present":1,"common":1,"populated":1,"instantiate":1,"given":1,"appropriate":1}
,"node":{"properties":1,"entry":1,"definition":1,"enables":1,"platform":1,"jetson":1,"added":1,"compatible":1,"describe":1,"described":1,"below":1,"various":1,"subnode":1,"overall":1,"listing":1,"following":1,"device":1,"represent":1,"update":1,"dai":1,"specifies":1,"e.g":1,"sgtl5000":1,"names":1,"i2c":1,"index":1,"appropriate":1}
,"child":{"nodes":1}
,"property":{"consists":1,"identify":1,"follows":1,"okay":1,"specifies":1,"sound":1,"left_j":1,"dsp_a":1,"codec\u2019s":1,"values":1,"corresponding":1}
,"consists":{"name":1,"interpolator":1}
,"name":{"values":1,"$kernel_top":1,"base":1,"\u0027i2s1":1,"customized":1,"table":1,"sound":1,"input":1,"prefix":1,"i2s1":1,"headphone":1,"stereo":1,"hpo":1,"admaif1":1,"recmix1l":1,"recmix1r":1,"in2":1,"stereo1":1,"tdm":1,"in1":1,"appropriate":1,"plugging":1,"proc":1,"file":1,"i2s2":1,"admaif":1,"i2s4":1,"codec-x":1,"dmic3":1,"mvc1":1,"dspk1":1,"amx2-1":1,"amx2-2":1,"amx2":1,"amx2-3":1,"adx1":1,"dspk2":1,"sfc1":1,"admaif2":1,"mixer1-1":1,"mixer1-2":1,"adder1":1,"mixer":1,"admaif3":1,"setting":1,"tegra210-i2s":1,"per":1,"example":1}
,"values":{"device":1,"determined":1,"sample-rate":1,"given":1}
,"structures":{"written":1}
,"written":{"correct":1,"specific":1}
,"correct":{"format":1,"dma":1,"desired":1,"instructed":1,"enter":1,"edit":1,"jetson":1}
,"format":{"data":1,"i2s":1,"dai":1,"configures":1,"value":1,"support":1,"supported":1,"nvidia":1,"following":1,"timing":1,"24-bit":1,"property":1,"dsp_a":1,"jetson":1}
,"parsed":{"operating":1,"total":1,"num-codec-link":1}
,"simple":{"device":1,"100":1}
,"example":{"available":1,"reflash":1,"jetson":1,"input":1,"i2s":1,"device":1,"gives":1,"above":1,"customize":1,"eight":1,"shows":1,"below":1,"sgtl5000":1,"codec-specific":1,"corresponding":1,"admaif":1,"running":1,"log":1,"codec_name":1,"parsed":1,"specified":1,"using":1,"tegra-snd-t186ref-mobile-rt565x":1}
,"instantiation":{"using":1,"boot":1}
,"better":{"alsa":1}
,"embedded":{"system-on-chip":1}
,"processors":{"e.g":1,"modems":1,"support":1}
,"e.g":{"dsp":1,"usb":1,"pin":1,"i2s1":1,"first":1,"monitor":1}
,"dsp":{"ahub":1,"mode":1,"modes":1}
,"ahub":{"portable":1,"modules":1,"hardware":1,"direct":1,"path":1,"client":1,"clients":1,"86000000":1,"mixer":1,"card":1,"usage":1,"case":1,"cpu":1}
,"portable":{"audio":1}
,"comprises":{"components":1,"platform":1}
,"responsible":{"pcm":1}
,"registration":{"interfacing":1,"passing":1}
,"interfacing":{"pcm":1,"modules":1,"codec":1}
,"admaif":{"platform":1,"fifos":1,"fifo":1,"implemented":1,"booting":1,"channels":1,"amx":1,"may":1,"want":1,"channel":1,"index":1,"playback":1,"capture":1,"mux":1,"enter":1,"instance":1,"left":1,"right":1,"case":1}
,"registers":{"snd_soc_codec_driver":1,"pcm":1,"asoc":1,"i2s4__reg_dump":1}
,"snd_soc_codec_driver":{"structure":1,"individual":1}
,"viewed":{"codec":1}
,"least":{"input":1,"port":1,"level":1}
,"input":{"output":1,"fed":1,"module":1,"streams":1,"frames":1,"stream":1,"channel":1,"bytes":1,"frame":1,"receives":1,"channels":1,"port":1,"data":1,"rxcif":1,"bit":1,"sample":1,"ports":1,"sampling":1,"rate":1,"stereo":1,"devices":1,"lines":1,"audio":1,"oversampled":1,"pcm":1,"file":1}
,"define":{"dapm":1,"properties":1,"routes":1}
,"kcontrols":{"register":1,"user":1,"needed":1,"volume":1}
,"setting":{"user":1,"appropriate":1,"display":1,"required":1,"group":1,"property":1,"represents":1,"correct":1}
,"machine":{"driver":1,"drivers":1,"driver\u2019s":1,"driver\u0027s":1}
,"connects":{"codec":1}
,"together":{"given":1}
,"given":{"platform":1,"maximum":1,"i2s":1,"chip":1,"input":1,"dspk":1,"ahub":1,"interface":1,"following":1,"bclk":1,"cardid":1,"case":1}
,"writing":{"machine":1,"audio":1}
,"identifying":{"sound":1,"dai":1}
,"consult":{"asoc":1}
,"hub":{"hardware":1,"contains":1,"support":1,"supports":1,"ahub":1}
,"module":{"intended":1,"i2s":1,"xavier":1,"behavior":1,"specific":1,"input":1,"multiplex":1,"found":1,"demultiplex":1,"ahub":1,"mixer":1,"usage":1,"instantiates":1,"adaptation":1,"control":1}
,"intended":{"audio":1}
,"acceleration":{"topic":1,"platform":1}
,"topic":{"provides":1,"device":1,"jetson":1,"applies":1}
,"inside":{"soc":1,"machine":1,"xbar":1,"ahub":1,"snd_soc_dapm_route":1}
,"summarizes":{"hardware":1}
,"contains":{"modules":1}
,"modules":{"i2s":1,"using":1,"audio":1,"least":1,"port":1,"except":1,"defining":1,"admaif":1,"dependent":1,"found":1,"expose":1,"interfaces":1,"amx":1}
,"dspk":{"digital":1,"exposed":1,"pdm":1,"controller":1,"node":1,"instance":1,"pll_a_out0":1,"device":1,"ahub-dspk-id":1,"corresponding":1,"mux":1,"input":1,"osr":1,"fifo":1,"client":1,"module":1,"playback":1,"dmic":1,"interface-based":1,"xbar":1,"aud_mclk":1}
,"digital":{"mic":1,"microphones":1,"speakers":1,"audio":1,"sound":1,"signal":1,"speaker":1}
,"mic":{"controller":1,"bias":1,"mic":1,"capture":1,"jack":1}
,"controller":{"dmic":1,"implements":1,"converts":1,"directly":1,"consists":1,"table":1,"exposed":1}
,"dmic":{"interface":1,"dspk":1,"mixer":1,"controller":1,"pll_a_out0":1,"device":1,"ahub-dmic-id":1,"corresponding":1,"boost":1,"mono":1,"output":1,"sample":1,"osr":1,"processing":1,"select":1,"left":1,"client":1,"usage":1,"external":1,"gpio":1,"therefore":1,"i2s":1,"mvc":1,"less":1,"avoid":1}
,"external":{"world":1,"pdm-capable":1,"devices":1,"audio":1,"device":1,"clock":1,"oscillator":1,"codec":1,"source":1,"mic":1}
,"world":{"audio":1}
,"sampling":{"frequency":1,"rate":1,"rates":1}
,"frequency":{"converter":1,"required":1,"conversion":1,"conversions":1,"cases":1,"response":1,"equal":1,"explained":1}
,"converter":{"sfc":1,"connect":1}
,"primary":{"volume":1,"audio":1,"function":1}
,"volume":{"control":1,"input":1,"gain":1,"ramp":1,"0x1e":1,"during":1,"direct":1}
,"multiplexers":{"amx":1}
,"demultiplexers":{"adx":1}
,"direct":{"memory":1,"admaif1":1,"i2s1":1,"aif1":1,"aif1tx":1,"if1":1,"dac_ref":1,"tdm":1,"adc1":1,"bst1":1,"in2p":1,"in1p":1}
,"memory":{"access":1}
,"access":{"adma":1,"interface":1,"codec":1,"example":1}
,"adma":{"component":1,"transfers":1}
,"admaif-dma":{"communicate":1}
,"communicate":{"memory":1}
,"crossbar":{"xbar":1}
,"xbar":{"facilitates":1,"ports":1,"hence":1,"switch":1,"audio":1,"digital":1,"default":1,"routing":1,"driver":1,"codec":1,"interconnections":1,"i2s1":1,"port":1,"four":1,"dap":1,"output":1,"dapm":1,"interfaces":1,"&tegra_axbar":1,"switched":1}
,"facilitates":{"routing":1,"configuration":1}
,"samples":{"modules":1,"channels":1,"two":1,"received":1}
,"proprietary":{"protocol":1}
,"protocol":{"called":1}
,"client":{"interface":1,"device":1,"txcif":1,"refers":1,"port":1}
,"tx1":{"instances":1,"generate":1,"nvidia":1,"hdmi":1,"sys":1}
,"inputs":{"outputs":1}
,"instances":{"module":1}
,"exposed":{"platform":1,"admaif":1,"snd_pcm_ops":1,"dai":1,"module":1,"jetson":1,"different":1}
,"kinds":{"audio":1}
,"expected":{"interface":1,"sysclk":1}
,"application":{"processor":1}
,"cellular":{"baseband":1}
,"baseband":{"devices":1}
,"types":{"audio":1}
,"bluetooth":{"modules":1,"chips":1,"audio":1,"software":1,"bluetoothd":1,"headset":1}
,"signal":{"quality":1,"path":1,"pdm":1,"dsp-a":1,"external":1,"attenuated":1}
,"quality":{"requirements":1}
,"requirements":{"devices":1,"modules":1}
,"ports":{"receive":1,"send":1,"playback":1,"form":1,"platform":1,"receiving":1,"transmit":1,"interfaces":1,"port":1,"mapped":1,"master":1}
,"receive":{"data":1,"clock":1,"direct":1}
,"send":{"data":1,"audio":1}
,"hence":{"xbar":1,"software":1,"bit":1,"xrun":1}
,"switch":{"audio":1,"recmix1r":1,"recmix1l":1}
,"fed":{"multiple":1}
,"multiple":{"outputs":1,"aud_mclk":1}
,"outputs":{"depending":1,"mix":1,"microphone":1}
,"depending":{"case":1,"generation":1,"incoming":1,"data":1}
,"fifos":{"support":1}
,"simultaneous":{"recording":1}
,"recording":{"playback":1,"begins":1,"initiated":1,"ports":1,"microphone":1}
,"transfers":{"data":1}
,"fifo":{"audio":1,"transmitted":1,"threshold":1,"cif":1}
,"examples":{"usage":1,"details":1,"full":1,"note":1,"various":1,"amx":1,"adx":1,"i2s":1,"mixer":1,"sfc":1,"dmic":1,"mvc":1,"dspk":1,"available":1,"detail":1,"written":1,"multiplexing":1,"playback":1}
,"usage":{"examples":1,"example":1,"guide":1,"available":1,"hostless":1}
,"configuration":{"module":1,"custom":1,"interface":1,"configuring":1,"customized":1,"increasing":1,"bluetooth":1,"indicated":1,"section":1,"part":1,"dai":1,"symbols":1,"symbol":1,"entry":1,"required":1,"snd_soc_dai_set_sysclk":1,"codec":1,"triggered":1,"found":1,"override":1,"nvidia":1,"note":1,"needed":1,"enter":1,"check":1}
,"series":{"soc":1,"nvidia":1,"tegra":1,"jetson":1,"except":1}
,"soc":{"technical":1,"dma":1,"dai":1,"connect":1,"route":1,"tegra-alt":1,"external":1,"drive":1,"pins":1,"audio":1,"i2s":1,"t210":1}
,"technical":{"reference":1}
,"reference":{"manual":1,"definitions":1}
,"manual":{"nvidia":1,"jetson":1}
,"tegra":{"parker":1,"soc":1,"number":1}
,"parker":{"series":1}
,"conforms":{"alsa":1}
,"mentioned":{"earlier":1,"following":1}
,"earlier":{"asoc":1,"codec\u2019s":1}
,"roles":{"drivers":1}
,"described":{"briefly":1,"below":1,"properties":1,"section":1,"preceding":1,"codec":1}
,"briefly":{"below":1}
,"below":{"detail":1,"instance":1,"lists":1,"dotted":1,"mixer":1,"list":1,"described":1,"codec":1,"shows":1,"cpu-dai-name":1,"executed":1,"patch":1,"nvidia":1,"cases":1,"sample":1}
,"detail":{"subsequent":1,"alsa":1}
,"subsequent":{"sections":1,"output":1}
,"implemented":{"platform":1,"codec":1,"audio":1}
,"record":{"rest":1,"audio":1,"pcm":1,"playback":1,"stops":1,"mono":1,"case":1}
,"rest":{"ahub":1,"available":1}
,"cross":{"bar":1}
,"bar":{"xbar":1}
,"multiplexer":{"amx":1}
,"amx":{"audio":1,"adx":1,"module":1,"four":1,"code":1,"handles":1,"respective":1,"mux":1,"input":1,"output":1,"byte":1,"client":1,"except":1}
,"demultiplexer":{"adx":1,"supports":1}
,"adx":{"inter-ic":1,"i2s":1,"module":1,"receives":1,"input":1,"demultiplexer":1,"respective":1,"mux":1,"output":1,"byte":1,"client":1,"demultiplexing":1,"adx":1,"afc":1}
,"inter-ic":{"sound":1}
,"connected":{"xbar":1,"corresponding":1,"dummy":1,"given":1,"using":1,"codec\u2019s":1,"on-board":1,"external":1,"rxcif0":1,"rxcif1":1,"rxcif2":1,"codec":1,"i2c":1,"directly":1}
,"dai":{"inside":1,"indicated":1,"links":1,"link":1,"link\u2019s":1,"node":1,"codec":1,"respectively":1,"params":1,"parameters":1,"spdif-dit":1,"ist":1,"registered":1,"found":1,"dap":1,"i2s-to-codec":1,"i2s":1,"admaif":1}
,"forming":{"audio":1,"first":1}
,"probe":{"instantiates":1,"calls":1,"audio":1,"frame":1}
,"instantiates":{"sound":1,"ports":1}
,"booting":{"using":1}
,"play":{"back":1,"record":1,"capture":1}
,"back":{"record":1,"mono":1}
,"paths":{"inside":1,"power":1,"examples":1}
,"default":{"xbar":1,"few":1,"values":1,"additional":1,"perform":1,"without":1,"avoid":1,"pinmux":1,"sfio":1,"root":1,"size":1}
,"connections":{"boot":1,"stored":1,"shown":1}
,"complete":{"dapm":1,"example":1,"pair":1,"case":1}
,"corresponding":{"widgets":1,"mapping":1,"codec":1,"dapm":1,"codec\u0027s":1,"asoc":1,"init":1,"dai":1,"i2s1":1,"nvidia":1}
,"mux":{"widgets":1,"widget":1,"register":1,"\u0027admaif1":1,"admaif1":1,"i2s1":1,"ad1:ad2:dac:nul":1,"admaif":1,"i2s2":1,"i2s4":1,"dmic3":1,"mvc1":1,"dmic2":1,"amx2":1,"adx1-1":1,"admaif3":1,"sfc1":1,"admaif2":1,"mixer1-1":1,"direct":1,"dac1":1,"adc1":1,"adc":1}
,"custom":{"routing":1,"audio":1,"names":1}
,"utility":{"audio":1,"put":1,"rendering":1}
,"path":{"complete":1,"closed":1,"examples":1,"setup":1,"order":1,"admaif1":1,"characteristics":1,"mvc":1,"trace":1,"play":1,"completed":1,"dapm":1,"populated":1,"case":1}
,"closed":{"hardware":1}
,"settings":{"applied":1,"admaif":1,"shown":1,"follows":1,"check":1,"correct":1,"i2c":1,"codec":1,"audio":1,"sfio":1,"required":1,"enter":1}
,"applied":{"audio":1,"input":1,"output":1}
,"output":{"cannot":1,"physical":1,"module":1,"modules":1,"xbar":1,"stream":1,"frame":1,"frames":1,"bytes":1,"channels":1,"streams":1,"port":1,"sample":1,"ports":1,"rate":1,"bit":1,"mono":1,"digital":1,"audio":1,"dspk":1,"high":1,"file":1,"power":1,"sound":1,"provide":1,"shows":1,"in1p":1}
,"cannot":{"heard":1,"support":1,"proceed":1}
,"route":{"play":1,"data":1,"dapm":1,"jetson":1,"case":1,"out-":1,"linein-x-":1}
,"initializes":{"instantiates":1}
,"users":{"connect":1,"play":1}
,"connect":{"ports":1,"various":1,"interfaces":1,"sink":1,"bluetooth":1,"per":1,"headphones":1,"microphones":1}
,"full":{"audio":1}
,"note":{"elements":1,"address":1,"interfaces":1,"however":1,"dai":1,"device":1,"remarks":1,"clock":1,"i2s4":1}
,"elements":{"full":1}
,"setup":{"discussed":1,"configuring":1,"details":1,"i2s4":1}
,"discussed":{"subsequent":1}
,"helps":{"perform":1}
,"perform":{"dma":1,"necessary":1,"high-quality":1,"pinmux":1,"required":1,"loopback":1,"tdm":1,"mono":1,"stereo":1,"playback":1,"capture":1}
,"dma":{"operations":1,"engine\u2019s":1,"engine":1,"driver":1,"settings":1,"reads":1,"writes":1,"case":1}
,"operations":{"overriding":1,"progress":1}
,"overriding":{"function":1}
,"function":{"pointers":1,"pll_a":1,"individual":1,"sampling":1,"codec":1,"usually":1,"mclk":1,"register":1,"shown":1,"sgtl5000":1,"ios":1,"board":1}
,"pointers":{"exposed":1}
,"snd_pcm_ops":{"structure":1}
,"platform-agnostic":{"interacts":1}
,"interacts":{"soc":1,"platform-specific":1}
,"engine\u2019s":{"upstream":1}
,"engine":{"interacts":1}
,"platform-specific":{"dma":1,"may":1,"device":1,"dai":1,"instance":1,"ensure":1,"pinmux":1}
,"dais":{"registers":1,"exposed":1}
,"either":{"admaifs":1,"streams":1,"11.025x":1,"gpio":1,"i2c":1,"playback":1,"recording":1,"jetson":1,"underrun":1}
,"admaifs":{"depending":1}
,"generation":{"facilitating":1}
,"facilitating":{"either":1,"pll":1}
,"streams":{"playback":1,"channels":1,"data":1,"mapping":1,"output":1,"byte":1,"directed":1,"software":1,"input":1,"two":1,"primary":1,"demultiplexing":1,"dmic2":1,"onto":1,"generate":1}
,"registered":{"primary":1,"instance":1,"using":1,"codec":1}
,"channels":{"mapped":1,"maximum":1,"generating":1,"input":1,"bits":1,"bytes":1,"four":1,"32-bits":1,"lrck":1,"stereo":1,"audio":1,"need":1,"mask":1,"tdm":1,"data":1,"comp":1,"word_size":1,"given":1,"number":1,"used":1,"sample_format":1,"configured":1}
,"dev":{"snd":1,"rtd-":1,"failed":1}
,"snd":{"pcmc1dnp":1,"pcmc1dnc":1,"pcmc":1}
,"pcmc1dnp":{"playback":1}
,"pcmc1dnc":{"capture":1}
,"less":{"channel":1,"125":1,"add":1,"equal":1}
,"channel":{"number":1,"time":1,"amx":1,"byte":1,"therefore":1,"output":1,"count":1,"four":1,"port":1,"input":1,"1-8":1,"select":1,"mono":1,"polarity":1,"index":1,"used":1}
,"number":{"example":1,"words":1,"platform-specific":1,"nvidia":1,"child":1,"represents":1,"dai":1,"channels":1,"audio":1,"admaif":1,"bits":1,"decremented":1,"indicates":1,"failed":1,"milliseconds":1}
,"admaif1":{"mapped":1,"xbar":1,"mux":1,"i2s1":1,"direct":1,"transmit":1}
,"mapped":{"pcmc1d0p":1,"pcmc1d1p":1,"byte":1,"rxcif0":1,"channel":1,"output":1,"position":1,"txcif0":1,"specific":1}
,"pcmc1d0p":{"playback":1}
,"pcmc1d0c":{"capture":1}
,"admaif2":{"mapped":1,"admaif3":1,"mux":1}
,"pcmc1d1p":{"playback":1}
,"pcmc1d1c":{"capture":1}
,"overview":{"codec":1,"dai":1}
,"presented":{"section":1}
,"section":{"asoc":1,"adx":1,"definition":1,"topic":1,"information":1,"configure":1,"troubleshooting":1,"examples":1,"describes":1,"nvidia":1}
,"implementation":{"rest":1}
,"except":{"admaif":1,"direction":1,"noted":1,"jetson":1}
,"responsibilities":{"include":1}
,"defining":{"dais":1,"dapm":1}
,"establishing":{"dapm":1}
,"routes":{"dynamic":1,"established":1,"mixer":1,"propagate":1,"essential":1,"additionally":1,"connecting":1,"sgtl5000":1,"example":1,"codec":1,"case":1}
,"exposing":{"additional":1}
,"additional":{"kcontrols":1,"binding":1,"bluetooth":1,"configuration":1}
,"needed":{"user":1,"using":1,"device":1,"playback":1,"upscale":1}
,"based":{"architecture":1,"byte":1,"t186":1,"mclk":1}
,"makefile":{"following":1}
,"directory":{"conditionally":1,"jetson":1}
,"conditionally":{"compiles":1}
,"compiles":{"required":1}
,"files":{"dtb":1,"case":1,"respectively":1,"wav":1}
,"dtb":{"files":1,"file":1,"build":1}
,"$kernel_top":{"arch":1,"kernel":1}
,"arch":{"arm64":1}
,"arm64":{"boot":1}
,"flashed":{"flash":1}
,"flash":{"script":1}
,"script":{"chooses":1,"script":1,"user":1}
,"chooses":{"appropriate":1}
,"appropriate":{"board-specific":1,"bit":1,"i2c":1,"i2s":1,"dapm":1,"routes":1,"dai":1,"name":1,"value":1,"device":1,"section":1,"resolution":1,"carrier":1,"audio":1}
,"board-specific":{"dtb":1}
,"file":{"parsing":1,"identified":1,"name":1,"jetson":1,"defines":1,"sound":1,"played":1,"aplay":1,"arecord":1,"e.g":1,"second":1,"i2s4":1,"i2s1":1,"described":1,"below":1,"applying":1,"flashed":1,"system":1,"systems":1}
,"parsing":{"during":1}
,"during":{"boot":1,"platform":1,"init":1,"playback":1}
,"listed":{"device":1,"above":1}
,"instantiated":{"add":1,"due":1,"i2s":1,"enter":1,"name":1}
,"add":{"new":1,"device":1,"update":1,"codec":1,"initialization":1,"support":1,"volume":1,"route":1}
,"edit":{"dts":1,"override":1}
,"dts":{"file":1,"hardware":1,"proc":1}
,"identified":{"dmesg":1}
,"dmesg":{"log":1,"output":1,"grep":1,"kernel_log":1}
,"log":{"following":1,"widgets":1,"enter":1}
,"reflash":{"target":1}
,"0.977503":{"dts":1}
,"kernel-4.9":{"arch":1}
,"t19x":{"galen":1,"jakku":1}
,"galen":{"kernel-dts":1}
,"kernel-dts":{"tegra194-p2888-0001-p2822-0000.dts":1,"common":1,"tegra210-porg-p3448-common.dtsi":1,"t18x-common-platforms":1,"tegra210-jetson-cv-base-p2957-2180-a00.dts":1,"tegra210-soc":1}
,"0.977582":{"dtb":1}
,"build":{"time":1}
,"oct":{"2018":1}
,"2018":{"10:22:39":1}
,"base":{"address":1,"rate":1,"rates":1}
,"address":{"status":1,"few":1,"address":1,"range":1,"i2c":1,"i2s":1}
,"status":{"okay":1,"property":1}
,"mixer":{"sfc":1,"controls":1,"control":1,"mixes":1,"shown":1,"driver":1,"enable":1,"respectively":1,"corresponding":1,"refers":1,"module":1,"mixing":1,"others":1,"settings":1}
,"sfc":{"mvc":1,"converts":1,"input":1,"corresponding":1,"mux":1,"init":1,"output":1,"channels":1,"module":1,"rate":1,"mixer":1}
,"mvc":{"mux":1,"volume":1,"block":1,"corresponding":1,"vol":1,"mute":1,"curve":1,"channels":1,"input":1,"bits":1,"client":1,"module":1,"applying":1,"order":1,"essence":1,"used":1}
,"permanently":{"routed":1}
,"routed":{"corresponding":1}
,"snd_soc_dapm_route":{"structure":1}
,"interconnections":{"made":1}
,"made":{"connecting":1}
,"connecting":{"widget":1,"various":1,"usb":1,"machine":1}
,"widget":{"block":1,"found":1,"sink":1,"example":1}
,"block":{"mux":1,"needed":1,"generic":1,"used":1,"converts":1}
,"put":{"handlers":1}
,"handlers":{"widgets":1}
,"stored":{"setting":1}
,"indicates":{"machine":1,"bits":1,"type":1,"cpu":1}
,"interconnects":{"codec":1}
,"remaining":{"step":1}
,"step":{"obtaining":1}
,"obtaining":{"audio":1}
,"physical":{"codecs":1,"codec":1,"microphone":1}
,"involves":{"mux":1}
,"establish":{"dapm":1,"appropriate":1}
,"order":{"route":1,"example":1,"instantiate":1,"configure":1,"perform":1,"avoid":1}
,"dependent":{"applicable":1,"input":1}
,"applicable":{"case":1,"codec":1}
,"case":{"provides":1,"i2s":1,"dmic":1,"dspk":1,"strings":1,"significant":1,"machine":1,"codec":1,"pll":1,"mixer":1,"dap":1,"using":1,"cannot":1,"recording":1,"connected":1,"interface":1,"turn":1,"sfio":1,"example":1,"playback":1,"capture":1}
,"flexibility":{"complex":1}
,"complex":{"cases":1,"part":1}
,"tegrasndt19xmob":{"cset":1,"controls":1}
,"cset":{"name":1}
,"\u0027i2s1":{"mux":1}
,"\u0027admaif1":{"realizes":1}
,"realizes":{"internal":1}
,"internal":{"ahub":1,"i2s":1,"soc":1,"pll":1,"codec":1,"loopback":1}
,"i2s1":{"usage":1,"23454545":1,"via":1,"example":1,"mux":1,"i2s4":1,"located":1,"specify":1,"codec":1,"configured":1,"sync":1,"entry":1,"i2s1":1,"admaif1":1,"receive":1,"cif":1,"dap":1}
,"found":{"usage":1,"section":1,"device":1,"intel":1,"shown":1}
,"multiplex":{"four":1,"two":1,"three":1}
,"four":{"streams":1,"ports":1,"input":1,"bytes":1,"output":1,"slots":1}
,"maximum":{"bits":1,"output":1,"latency":1,"channels":1,"frame":1,"performance":1}
,"bits":{"per":1,"bytes":1,"necessary":1,"s16_le":1,"s32_le":1,"pcm":1,"s24_3le":1,"bits":1,"number":1}
,"per":{"channel":1,"sample":1,"stream":1,"guideline":1,"mode":1,"sensitivity":1,"platform":1}
,"division":{"multiplexed":1}
,"multiplexed":{"tdm":1,"output":1}
,"tdm":{"stream":1,"slot":1,"slots":1,"frame":1,"fsync":1,"data":1,"capture":1,"ad2:dac":1,"ad1:ad2:dac":1}
,"stream":{"channels":1,"uniquely":1,"software":1,"channel":1,"byte":1,"core":1,"based":1,"mapped":1,"mapping":1,"output":1,"two":1,"globally":1,"available":1,"adder":1,"mixing":1,"mvc":1,"sample":1,"number":1,"via":1}
,"receiving":{"data":1,"optional":1}
,"transmitting":{"multiplexed":1,"rx-mask":1,"probe":1,"receiving":1}
,"indicated":{"solid":1,"dotted":1,"tables":1}
,"solid":{"line":1}
,"line":{"routes":1,"line_out":1,"line":1,"correspond":1,"appropriate":1}
,"established":{"using":1}
,"dotted":{"lines":1}
,"code":{"driver":1,"modulation":1,"above":1}
,"capable":{"multiplexing":1}
,"multiplexing":{"four":1,"two":1,"three":1}
,"generating":{"output":1}
,"byte":{"ram":1,"map":1,"output":1,"four":1,"byte":1,"mapped":1,"input":1,"word":1,"populated":1}
,"ram":{"assemble":1,"map":1,"design":1,"amx":1,"file":1}
,"assemble":{"output":1}
,"frame":{"combination":1,"soon":1,"size":1,"samples":1,"sample":1,"bits":1,"bytes":1,"byte":1,"need":1,"software-configurable":1,"therefore":1,"two":1,"channels":1,"sync":1,"mode":1,"master":1,"mask":1,"slots":1,"rate":1,"formats":1,"clock":1}
,"combination":{"bytes":1,"input":1}
,"bytes":{"four":1,"input":1,"total":1,"word":1,"words":1,"programmed":1,"mapped":1,"order":1,"need":1}
,"two":{"modes":1,"channels":1,"mono":1,"input":1,"family":1,"groups":1,"usb-c":1,"ways":1,"three":1,"streams":1,"stereo":1}
,"modes":{"data":1,"i2s":1,"dsp":1,"support":1,"check":1,"codec":1,"review":1,"ljm":1}
,"synchronization":{"first":1,"subsequent":1}
,"first":{"output":1,"four":1,"followed":1,"sound":1}
,"wait":{"mode":1,"enabled":1}
,"mode":{"wait":1,"start":1,"left":1,"ljm":1,"rjm":1,"dsp-a":1,"operation":1,"codec":1,"setting":1,"dsp_a":1,"frame":1,"cbs-cfs":1,"i2s":1,"cbm-cfm":1,"configuration":1,"i2s4":1,"per":1}
,"enabled":{"input":1,"total":1,"product":1,"platform\u2019s":1,"ensuring":1,"disabled":1,"linux":1,"sgtl5000":1,"following":1,"run":1,"playback":1,"latencies":1}
,"start":{"forming":1,"playback":1,"record":1,"end":1}
,"soon":{"data":1,"input":1}
,"handles":{"data":1}
,"frames":{"differently":1,"until":1,"received":1,"contain":1}
,"differently":{"different":1}
,"platforms":{"jetson":1,"support":1,"based":1,"provide":1,"refer":1,"tegra186":1,"following":1,"ext4":1}
,"generate":{"subsequent":1,"single":1}
,"until":{"input":1}
,"received":{"jetson":1,"input":1,"zero":1,"bit":1,"external":1,"ahub":1}
,"generates":{"soon":1,"sample":1}
,"map":{"configuration":1,"amx":1,"encoded":1,"organized":1,"corresponds":1,"sample":1,"ignored":1,"byte_num":1,"bytemap":1,"forms":1,"adx":1,"byte":1,"128":1,"129":1,"130":1,"131":1,"132":1,"133":1,"134":1,"135":1}
,"uniquely":{"mapped":1}
,"mapping":{"bytes":1,"byte":1}
,"configurable":{"via":1}
,"encoded":{"fields":1}
,"identifies":{"four":1,"possible":1,"byte":1,"output":1,"codec":1}
,"size":{"supported":1,"sample":1,"channel":1,"bits":1,"input":1,"output":1,"size":1,"total":1,"channels":1,"100m":1,"audio":1}
,"sample":{"byte":1,"size":1,"rate":1,"bits":1,"several":1,"rates":1,"format":1,"sizes":1,"dapm":1,"frequency-converted":1,"complete":1,"width":1}
,"organized":{"words":1,"32-bit":1}
,"words":{"bits":1,"programmed":1,"bytes":1,"need":1}
,"total":{"32-bit":1,"tdm":1,"number":1}
,"32-bit":{"word":1,"words":1,"stage":1}
,"word":{"byte":1,"word":1,"need":1,"depends":1,"dependent":1}
,"corresponds":{"input":1,"channel":1,"audio":1}
,"therefore":{"output":1,"input":1,"separate":1,"necessary":1}
,"need":{"programmed":1,"mapped":1,"external":1,"present":1,"configuration":1,"configured":1,"pinmux":1,"add":1,"update":1,"codec-specific":1}
,"programmed":{"output":1,"bytes":1,"word":1,"input":1}
,"depends":{"output":1,"hdmi":1}
,"necessary":{"program":1,"changes":1,"configuration":1,"sure":1,"codec":1}
,"program":{"byte":1,"four":1}
,"bear":{"points":1}
,"points":{"mind":1}
,"position":{"output":1}
,"software-configurable":{"enable":1}
,"flag":{"particular":1,"cleared":1}
,"particular":{"byte\u2019s":1}
,"byte\u2019s":{"enable":1}
,"cleared":{"corresponding":1}
,"ignored":{"byte":1}
,"populated":{"zeros":1,"codec":1,"help":1,"file":1}
,"instance":{"amx":1,"specific":1,"adx":1,"given":1,"i2s":1,"mixer":1,"sfc":1,"dmic":1,"mvc":1,"dspk":1,"associated":1,"names":1,"number":1}
,"respective":{"codec":1,"connectors":1}
,"used":{"configure":1,"apply":1,"11.025x":1,"perform":1,"jetson":1,"pinmux":1,"access":1,"exactly":1,"patch":1,"i2s4":1,"running":1}
,"configure":{"path":1,"ape":1,"i2s":1,"tdm":1,"audio":1,"codec":1,"dapm":1,"various":1,"data":1,"either":1}
,"characteristics":{"processing":1}
,"processing":{"method":1,"block":1}
,"method":{"audio":1,"applied":1,"dmic":1,"inspect":1}
,"table":{"below":1,"table":1,"taken":1,"board":1,"above":1,"section":1,"shows":1,"ahub":1,"identify":1}
,"selects":{"ahub":1,"bytes":1,"channel":1}
,"receives":{"data":1,"input":1}
,"configures":{"channel":1,"byte":1,"length":1,"frame":1,"sample":1,"stereo":1,"mono":1,"cif\u2019s":1,"i2s":1,"codec":1,"gain":1,"sampling":1,"volume":1,"output":1,"osr":1,"dmic":1,"channels":1,"oversampling":1,"cpu":1}
,"count":{"input":1,"output":1,"audio":1,"maximum":1}
,"bytemap":{"configuration":1}
,"refers":{"instance":1,"input":1,"output":1,"data":1,"admaif":1}
,"demultiplex":{"single":1,"16-bit":1}
,"single":{"tdm":1,"stereo":1,"pll_a":1,"output":1}
,"transmit":{"demultiplexed":1,"receive":1,"data":1,"block":1,"direct":1}
,"demultiplexed":{"output":1}
,"lines":{"following":1,"i2s":1,"dmic":1}
,"rxcif":{"supplies":1}
,"supplies":{"input":1}
,"logic":{"selects":1}
,"forms":{"output":1}
,"directed":{"txcif":1}
,"txcif":{"fifo":1}
,"transmitted":{"downstream":1}
,"downstream":{"module":1}
,"demultiplexing":{"input":1,"single":1,"stereo":1}
,"contain":{"combination":1,"data":1}
,"design":{"exactly":1}
,"exactly":{"byte":1,"shown":1}
,"direction":{"data":1}
,"32-bits":{"per":1}
,"lists":{"instance-specific":1,"instance":1,"port":1}
,"instance-specific":{"mixer":1}
,"ahub-client":{"having":1}
,"stereo":{"stream":1,"data":1,"mono":1,"conv":1,"conversion":1,"recordings":1,"dac":1,"playback":1,"sound":1,"mic":1,"capture":1,"streams":1}
,"mono":{"streams":1,"conv":1,"conversion":1,"stereo":1,"format":1,"channel":1,"recording":1,"playback":1,"mic":1,"capture":1}
,"bidirectional":{"data":1}
,"thereby":{"defines":1}
,"cif":{"dap":1,"side":1,"starts":1,"transmit-i2s1":1,"transmit":1,"direct":1}
,"dap":{"widgets":1,"side":1,"registered":1,"cpu":1,"direct":1,"receive":1,"event":1}
,"follows":{"cif":1,"configure":1}
,"side":{"i2s":1,"interfaces":1}
,"shown":{"diagram":1,"figure":1,"table":1,"below":1,"following":1,"example":1}
,"expose":{"kernel":1}
,"implements":{"full-duplex":1}
,"full-duplex":{"half-duplex":1}
,"half-duplex":{"point-to-point":1}
,"point-to-point":{"serial":1}
,"serial":{"interfaces":1}
,"i2s-compatible":{"products":1}
,"tape":{"devices":1}
,"modems":{"bluetooth":1}
,"operate":{"master":1,"either":1,"lrck":1,"tdm":1}
,"master":{"slave":1,"mode":1,"codec":1,"properties":1,"clock":1,"case":1,"configuration":1,"i2s4":1}
,"lrck":{"modes":1}
,"left":{"justified":1,"right":1,"mic":1}
,"justified":{"mode":1}
,"ljm":{"right":1,"rjm":1}
,"right":{"justified":1,"channel":1,"mic":1}
,"fsync":{"modes":1,"width":1,"mode":1,"signal":1,"fsync":1}
,"s16_le":{"bits":1,"format":1,"out.wav":1}
,"rate":{"8000":1,"audio":1,"sfc":1,"input":1,"output":1,"conversion":1,"dmic":1,"i2s":1,"product":1,"req_rate":1,"newer":1,"cannot":1,"pll_a":1,"thus":1,"list":1,"changes":1,"older":1,"either":1,"fixed":1,"requires":1,"yield":1,"11.025x":1,"even":1,"channels":1,"32000":1,"chan":1,"sampling":1,"external":1,"codec\u2019s":1,"rate":1,"desired":1,"setting":1,"integer":1,"choose":1,"based":1,"codec":1,"usually":1,"equal":1,"scale":1,"used":1,"sample":1,"48000":1,"44100":1}
,"8000":{"11025":1,"16000":1}
,"11025":{"16000":1,"22050":1}
,"16000":{"22050":1,"22500":1,"44100":1,"24000":1}
,"22050":{"24000":1,"44100":1}
,"24000":{"32000":1}
,"32000":{"44100":1,"48000":1}
,"44100":{"48000":1,"88200":1,"channels":1}
,"48000":{"88400":1,"88200":1,"44100":1,"96000":1,"s16_le":1}
,"88400":{"96000":1}
,"96000":{"176400":1,"192000":1}
,"176400":{"192000":1}
,"entry":{"enables":1,"above":1,"specifies":1,"nvidia":1,"snd_soc_tegra210_audio_alt":1,"corresponding":1,"point":1}
,"compatible":{"nvidia":1,"specifies":1,"value":1,"jetson":1,"fsl":1,"fixed-clock":1}
,"tegra_axbar":{"ahub":1}
,"tegra_i2s1":{"i2s@2901000":1}
,"reg":{"0x0":1,"0x0a":1}
,"0x0":{"0x2901000":1,"0x100":1,"0x2904000":1,"0x2905000":1}
,"0x2901000":{"0x0":1}
,"clocks":{"&tegra_car":1,"needed":1,"&bpmp_clks":1,"required":1,"individual":1,"power":1,"&sgtl5000_mclk":1,"driven":1}
,"&tegra_car":{"tegra186_clk_i2s1":1,"tegra186_clk_pll_a_out0":1,"tegra186_clk_i2s1_sync_input":1,"tegra186_clk_sync_i2s1":1,"tegra186_clk_dmic1":1,"tegra186_clk_dspk1":1,"tegra186_clk_plla":1,"tegra186_clk_aud_mclk":1,"tegra186_reset_aud_mclk":1,"tegra210_clk_extern1":1,"tegra210_clk_pll_a_out0":1,"tegra210_clk_pll_a":1,"tegra186_clk_i2s4_sync_input":1}
,"clock-names":{"i2s":1,"dmic":1,"sources":1,"dspk":1,"pll_a":1}
,"pll_a_out0":{"ext_audio_sync":1,"sync_dmic1":1,"sync_dspk":1,"extern1":1}
,"ext_audio_sync":{"audio_sync":1}
,"audio_sync":{"clk_sync_input":1}
,"assigned-clocks":{"&tegra_car":1}
,"assigned-clock-parents":{"&tegra_car":1,"property":1}
,"assigned-clock-rates":{"1536000":1,"3072000":1,"12288000":1,"property":1,"11289600":1,"desired_fixed_rate":1}
,"snippet":{"above":1}
,"above":{"device":1,"specifies":1,"codec":1,"header":1,"jetson":1,"aud_mclk":1,"section":1,"i2s1":1,"platform-specific":1}
,"few":{"properties":1,"interfaces":1}
,"referenced":{"platform-specific":1}
,"specifies":{"names":1,"instance":1,"register":1,"number":1,"machine":1,"sound":1,"codec-specific":1,"routes":1,"parent":1}
,"names":{"clocks":1,"ahub":1,"represent":1,"following":1,"clock":1,"used":1}
,"source":{"clock":1,"archive":1,"clocking":1,"codec":1,"codec\u2019s":1,"available":1,"configured":1,"parameters":1,"adc1":1,"adc":1,"i2s1":1,"sink":1,"widget":1,"file":1}
,"clock":{"register":1,"information":1,"generic":1,"rate":1,"tree":1,"trees":1,"enable_cnt":1,"codec":1,"resume":1,"restores":1,"derived":1,"source":1,"mclk":1,"present":1,"added":1,"typically":1,"parents":1,"parent":1,"choose":1,"bit":1,"delay":1,"dai":1,"required":1,"aud_mclk":1,"signal":1,"case":1,"configuration":1,"drift":1,"internal":1,"sources":1,"sync":1,"following":1,"names":1,"used":1,"example":1,"bclk":1,"i2s":1,"slave":1,"provided":1,"enabled":1}
,"range":{"belonging":1,"105":1}
,"belonging":{"device":1}
,"fsync-width":{"may":1}
,"adjusted":{"fit":1}
,"fit":{"case\u2019s":1}
,"case\u2019s":{"requirements":1}
,"length":{"input":1,"output":1}
,"sync":{"signal\u2019s":1,"width":1,"clock":1,"bit":1}
,"signal\u2019s":{"width":1}
,"width":{"terms":1,"bits":1,"bit":1,"according":1,"data":1,"available":1}
,"22500":{"24000":1}
,"conversion":{"method":1,"applied":1,"streams":1,"48000":1,"pdm":1}
,"none":{"ch0":1,"zero":1,"i2s":1,"cbm-cfm":1,"ch1":1,"preceding":1}
,"ch0":{"ch1":1}
,"ch1":{"avg":1,"ch2":1}
,"zero":{"copy":1,"avg":1,"clock":1}
,"cif\u2019s":{"fifo":1}
,"threshold":{"needed":1}
,"dsp-a":{"refers":1,"dsp-b":1,"sent":1}
,"offset":{"dsp-b":1,"supported":1,"regard":1}
,"dsp-b":{"refers":1,"i2s":1}
,"left-j":{"right-j":1}
,"right-j":{"dsp-a":1}
,"i2s\u2019s":{"mode":1}
,"operation":{"bit-master":1,"during":1,"may":1,"master":1}
,"bit-master":{"bit-slave":1}
,"bit-slave":{"frame-slave":1}
,"frame-slave":{"frame-master":1}
,"cbm-cfm":{"cbs-cfs":1}
,"mixes":{"audio":1}
,"onto":{"xbar":1,"dspk1":1}
,"figure":{"below":1}
,"exposes":{"gain":1,"audio":1,"i2c":1,"i2s":1}
,"gain":{"mixer":1,"stream":1,"given":1,"instant":1,"attenuation":1,"data":1,"tuned":1,"400":1,"dmic":1,"mvc":1,"signal":1}
,"globally":{"enable":1}
,"disable":{"mixer":1,"capture":1}
,"mixing":{"input":1,"adder":1,"two":1}
,"five":{"outputs":1}
,"mix":{"combination":1,"two":1}
,"fixed":{"gain":1,"device":1,"rate":1,"codec":1,"given":1}
,"mixer1-":{"mux":1}
,"converts":{"input":1,"pdm":1,"multibit":1,"pcm":1}
,"low":{"latency":1}
,"latency":{"maximum":1,"less":1,"issue":1}
,"125":{"microseconds":1}
,"conversions":{"marked":1}
,"marked":{"shaded":1}
,"shaded":{"cells":1}
,"cells":{"represent":1}
,"represent":{"frequency":1,"codec\u2019s":1,"on-board":1,"cpu":1,"input":1}
,"cases":{"bypass":1,"dmesg":1}
,"bypass":{"frequency":1}
,"88200":{"96000":1,"176400":1}
,"pdm":{"signals":1,"input":1,"pulse":1,"transmit":1,"output":1}
,"signals":{"pcm":1,"clock":1,"oscilloscope":1}
,"pulse":{"code":1,"density":1,"audio":1}
,"modulation":{"signals":1}
,"pdm-capable":{"codec":1}
,"shows":{"dapm":1,"mvc\u2019s":1,"clock":1,"fix":1,"address":1,"accomplish":1,"kernel":1,"machine":1,"capture":1,"perform":1,"mvc":1,"amx":1,"adx":1,"mix":1,"source":1,"cpu":1}
,"density":{"modulation":1}
,"osr":{"oversampling":1,"value":1,"ndicates":1}
,"oversampling":{"ratio":1}
,"ratio":{"128":1,"osr":1,"osr_i":1}
,"128":{"256":1}
,"definition":{"illustrates":1,"dai":1,"audio":1}
,"entries":{"node":1,"above":1,"corresponding":1,"target":1}
,"tegra_dmic1":{"dmic@2904000":1}
,"0x2904000":{"0x0":1}
,"&bpmp_clks":{"tegra186_clk_dmic1":1,"tegra186_clk_plla_out0":1,"tegra186_clk_sync_dmic1":1,"tegra194_clk_dspk1":1,"tegra194_clk_plla_out0":1,"tegra194_clk_sync_dspk1":1}
,"ahub-dmic-id":{"specifies":1}
,"apart":{"clock-names":1}
,"boost":{"gain":1,"volume":1}
,"25599":{"representing":1}
,"representing":{"256":1,"-120":1}
,"256":{"linear":1,"times":1,"512":1}
,"linear":{"scale":1}
,"scale":{"100x":1,"factor":1,"sample_rate":1}
,"100x":{"factor":1,"scale":1}
,"ndicates":{"selecting":1}
,"selecting":{"sample":1,"kernel":1}
,"several":{"samples":1,"possible":1}
,"osr_64":{"osr_128":1}
,"osr_128":{"osr_256":1}
,"applies":{"gain":1,"jetson":1,"original":1,"platform":1}
,"attenuation":{"digital":1}
,"apply":{"volume":1,"compensatory":1}
,"per-stream":{"streams":1}
,"mvc\u2019s":{"dapm":1}
,"programmable":{"volume":1,"curve":1}
,"curve":{"ramp":1,"type":1}
,"ramp":{"volume":1,"curve":1,"feature":1,"may":1}
,"separate":{"mute":1,"base":1}
,"mute":{"unmute":1}
,"unmute":{"controls":1}
,"-120":{"100x":1}
,"mutes":{"unmutes":1}
,"unmutes":{"input":1}
,"poly":{"linear":1}
,"passing":{"mvc":1,"platform-related":1}
,"applying":{"gain":1,"override":1}
,"speaker":{"dspk":1,"outputs":1}
,"multibit":{"pcm":1}
,"oversampled":{"one-bit":1,"1-bit":1}
,"one-bit":{"pdm":1}
,"interpolator":{"oversamples":1}
,"oversamples":{"incoming":1}
,"incoming":{"pcm":1,"stream\u2019s":1}
,"delta-sigma":{"modulator":1}
,"modulator":{"converts":1}
,"passband":{"frequency":1}
,"response":{"0.5":1}
,"0.5":{"peak-to-peak":1}
,"peak-to-peak":{"khz":1}
,"khz":{"range":1}
,"tegra_dspk1":{"dspk@2905000":1}
,"0x2905000":{"0x0":1}
,"ahub-dspk-id":{"specifies":1}
,"osr_i":{"indicates":1}
,"1-bit":{"pdm":1}
,"osr_32":{"osr_64":1}
,"starts":{"transfer":1,"suspend":1,"codec":1,"transmitting":1}
,"list":{"names":1,"above":1,"install":1,"audio":1}
,"clients":{"ports":1}
,"suffix":{"refers":1}
,"represents":{"instance":1,"interface":1,"link":1,"soundcard":1,"admaif":1,"codec":1}
,"linking":{"dais":1}
,"snd_soc_dai_link":{"structure":1}
,"brief":{"machine":1}
,"driver\u2019s":{"functions":1,"dapm":1}
,"populate":{"soc":1,"codec":1,"corresponding":1}
,"links":{"i.e":1,"internal":1,"device":1,"audio":1,"dapm":1,"connect":1,"properties":1,"parsed":1}
,"i.e":{"xbar":1,"links":1,"hda":1}
,"platform\u2019s":{"interfaces":1,"physical":1,"device":1,"root":1}
,"headphone":{"jacks":1,"speaker":1,"speakers":1,"hp_out":1,"mic":1,"playback":1}
,"jacks":{"speakers":1}
,"speakers":{"microphones":1,"connected":1,"either":1}
,"find":{"platform-specific":1,"possible":1,"sys":1,".dts":1}
,"ape":{"subsystem":1,"150000000":1,"clock":1}
,"propagate":{"runtime":1}
,"runtime":{"pcm":1,"rate":1,"configuration":1}
,"parameters":{"sample-rate":1,"populated":1,"passed":1,"snd_soc_dai_set_pll":1,"fixed":1}
,"sample-rate":{"sample-size":1,"value":1,"channels":1}
,"sources":{"archive":1,"i2s1":1}
,"archive":{"location":1,"locations":1}
,"tegra-alt":{"machine_drivers":1,"kconfig":1,"utils":1}
,"machine_drivers":{"tegra_machine_driver_mobile.c":1}
,"update":{"dai":1,"items":1,"device":1,"apt-get":1,"various":1,"kernel":1,"machine":1,"sgtl5000":1}
,"link":{"dapm":1,"perform":1,"simple-card":1,"i2s":1,"following":1,"properties":1,"setup":1,"represents":1,"appropriate":1,"unique":1,"instance":1,"indicate":1,"node\u2019s":1,"identifies":1,"shows":1,"sound":1,"codec\u2019s":1,"point":1}
,"defined":{"device":1,"dai":1,"may":1,"required":1,"name-prefix":1,"buffer_bytes_max":1}
,"items":{"machine":1}
,"parses":{"device":1,"sound":1}
,"instantiate":{"sound":1,"accordingly":1,"i2s":1}
,"customize":{"platform":1,"device":1}
,"third-party":{"audio":1}
,"changes":{"configuring":1,"side-effects":1,"required":1,"send":1,"section":1}
,"configuring":{"codec":1,"audio":1,"40-pin":1}
,"gives":{"overview":1}
,"tree\u2019s":{"sound":1,"dai":1}
,"tegra_sound":{"sound":1}
,"model":{"tegra-snd-t186ref-mobile-rt565x":1,"specifies":1}
,"pll_a":{"pll_a_out0":1,"258000000":1,"base":1,"source":1,"jetson":1,"run":1,"ensures":1,"support":1}
,"resets":{"&tegra_car":1}
,"reset-names":{"extern1_rst":1}
,"mclk-fs":{"256":1,"scaling":1}
,"rt565x_dai_link":{"nvidia":1}
,"link-name":{"spdif-dit-0":1,"property":1,"jetson":1,"sgtl5000-codec":1}
,"cpu-dai":{"&tegra_i2s1":1,"codec-dai":1}
,"codec-dai":{"&spdif_dit0":1,"respectively":1,"&sgtl5000":1}
,"cpu-dai-name":{"i2s1":1,"codec-dai-name":1}
,"codec-dai-name":{"dit-hifi":1,"custom":1,"sgtl5000":1}
,"bit-format":{"s16_le":1,"data":1}
,"srate":{"48000":1,"pcm":1}
,"added":{"device":1,"appropriate":1}
,"platform-related":{"data":1}
,"node\u2019s":{"properties":1,"assigned-clock-rates":1,"format":1}
,"card\u2019s":{"name":1}
,"customized":{"necessary":1}
,"audio-routing":{"describes":1,"sound":1}
,"codec\u2019s":{"microphones":1,"device":1,"input":1,"on-board":1,"sysclk":1,"dai":1,"current":1}
,"microphones":{"headphones":1,"headsets":1,"either":1}
,"headphones":{"speakers":1}
,"num-codec-link":{"defines":1,"sound":1,"ensure":1}
,"dai-link-":{"number":1}
,"describe":{"configuration":1}
,"unique":{"number":1,"link-name":1,"cpu-dai":1}
,"dummy":{"codecs":1,"clock":1,"codec":1}
,"spdif-dit0":{"spdif-dit1":1}
,"spdif-dit1":{"testing":1}
,"testing":{"physical":1}
,"allows":{"soc":1}
,"drive":{"interface":1,"codec\u2019s":1}
,"pins":{"even":1,"may":1,"i2s":1,"configured":1,"alternate":1,"pertaining":1,"tool":1,"sdin":1,"input":1,"pins":1,"audio":1}
,"even":{"external":1,"audio":1}
,"replaced":{"actual":1}
,"rt5658":{"example":1,"codec":1}
,"uses":{"dai":1,"i2c":1,"soc":1,"codec\u2019s":1,"external":1}
,"link\u2019s":{"link-name":1}
,"identify":{"dai":1,"link":1,"additional":1,"bus":1}
,"simple-card":{"specification":1}
,"definitions":{"device":1}
,"jakku":{"kernel-dts":1}
,"common":{"tegra194-audio-p3668.dtsi":1,"tegra194-audio-p2822-0000.dtsi":1,"kernel-dts":1,"audio":1,"i2s":1,"problem":1}
,"t210":{"porg":1,"jetson":1,"processor\u2019s":1,"kernel-dts":1}
,"porg":{"kernel-dts":1}
,"t18x":{"common":1}
,"t18x-common-platforms":{"tegra186-quill-common.dtsi":1}
,"40-pin":{"gpio":1,"expansion":1}
,"gpio":{"expansion":1,"header":1,"power":1,"special-function":1}
,"expansion":{"header":1,"header\u2019s":1}
,"subnode":{"sound":1}
,"overall":{"format":1}
,"preceding":{"section":1,"steps":1}
,"bitclock-master":{"frame-master":1}
,"frame-master":{"optional":1,"implies":1}
,"optional":{"booleans":1,"configure":1}
,"booleans":{"specify":1}
,"specify":{"whether":1,"mixer":1}
,"slave":{"master":1,"absent":1,"modes":1,"i2s4":1,"details":1,"hence":1}
,"bit-clock":{"frame":1,"master":1}
,"cpu":{"codec":1,"dai":1,"writes":1,"reads":1,"unable":1}
,"value":{"may":1,"pcm":1,"yields":1,"prefix":1,"name-prefix":1,"sound":1,"link-name":1,"following":1,"admaif":1,"less":1,"num-codec-link":1}
,"right_j":{"left_j":1,"i2s":1}
,"left_j":{"dsp_a":1,"right_j":1}
,"dsp_a":{"dsp_b":1}
,"bclk-ratio":{"integer":1}
,"integer":{"used":1,"multiple":1}
,"product":{"value":1,"conformance":1}
,"yields":{"clock":1}
,"tx-mask":{"applicable":1}
,"rx-mask":{"applicable":1}
,"slot":{"enable":1}
,"mask":{"respectively":1,"0xff":1,"0x0f":1}
,"respectively":{"bit":1,"point":1,"details":1,"i2s":1,"files":1}
,"masks":{"indicate":1}
,"indicate":{"tdm":1,"codec":1}
,"slots":{"contain":1,"frame":1,"enabled":1,"ignored":1}
,"determined":{"number":1,"usb":1}
,"eight":{"channels":1}
,"0xff":{"enables":1}
,"0x0f":{"enables":1}
,"interface-based":{"dai":1}
,"num-channel":{"data":1}
,"debugfs":{"node":1}
,"listing":{"obtained":1}
,"obtained":{"sys":1}
,"sys":{"kernel":1}
,"debug":{"clk":1,"asoc":1,"tracing":1,"regmap":1}
,"clk":{"clk_summary":1,"pin":1,"aud_mclk":1,"extern1":1}
,"clk_summary":{"shows":1}
,"idle":{"state":1}
,"state":{"audio":1,"turned":1,"disables":1}
,"progress":{"clock":1}
,"trees":{"jetson":1}
,"enable_cnt":{"prepare_cnt":1}
,"prepare_cnt":{"rate":1}
,"req_rate":{"accuracy":1}
,"accuracy":{"phase":1}
,"pll_a1":{"600000000":1}
,"600000000":{"600000000":1}
,"150000000":{"150000000":1}
,"apb2ape":{"150000000":1}
,"258000000":{"258000000":1}
,"dmic4":{"12285714":1,"via":1}
,"12285714":{"12285714":1}
,"dmic3":{"12285714":1,"via":1,"boost":1,"output":1,"mono":1,"connected":1}
,"dmic2":{"12285714":1,"via":1,"pinmuxed":1,"connected":1}
,"dmic1":{"12285714":1,"via":1,"dmic2":1}
,"i2s6":{"23454545":1,"via":1}
,"23454545":{"23454545":1}
,"i2s5":{"23454545":1,"dspk1":1,"via":1}
,"i2s4":{"23454545":1,"via":1,"connected":1,"i2s1":1,"shown":1,"msut":1,"fsync":1,"bclk":1,"codec":1,"sync":1,"configured":1,"uses":1,"clock":1,"may":1}
,"i2s3":{"23454545":1,"via":1,"t210-based":1}
,"i2s2":{"23454545":1,"via":1,"admaif":1,"mux":1,"loopback":1,"channels":1}
,"86000000":{"86000000":1}
,"individual":{"modules":1,"codec":1,"pins":1}
,"afc":{"sfc":1}
,"others":{"internally":1}
,"internally":{"driven":1,"connected":1}
,"driven":{"ape":1,"codec\u0027s":1,"turn":1,"pll":1}
,"switched":{"idle":1}
,"turned":{"audio":1}
,"idle_bias_off":{"option":1}
,"option":{"asoc":1,"causes":1,"values":1}
,"causes":{"asoc":1,"solutions":1,"typical":1}
,"call":{"suspend":1}
,"suspend":{"resume":1,"saves":1}
,"resume":{"functions":1,"playback":1,"enables":1}
,"functions":{"codec":1,"e.g":1}
,"set_runtime_pm_ops":{"during":1}
,"calls":{"suspend":1}
,"stops":{"starts":1}
,"saves":{"device":1}
,"disables":{"clock":1}
,"restores":{"device":1}
,"changing":{"pll_a":1,"base":1}
,"newer":{"processors":1}
,"aud_mclk":{"clock":1,"codec":1,"external":1,"fixed":1,"obtain":1,"sysfs":1,"function":1,"rate":1,"uses":1,"available":1}
,"derived":{"pll_a":1}
,"family":{"sample":1}
,"multiples":{"8000":1,"11.025":1}
,"11.025":{"11.025x":1}
,"11.025x":{"11025":1,"machine":1,"operation":1,"sampling":1}
,"rates":{"time":1,"used":1,"listed":1,"change":1,"sample":1,"aud_mclk":1}
,"sets":{"rate":1}
,"run":{"time":1,"playback":1}
,"stream\u2019s":{"sample":1}
,"thus":{"users":1}
,"t186":{"later":1}
,"later":{"processors":1}
,"feature":{"pll_a":1}
,"ensures":{"runtime":1,"jetson":1}
,"side-effects":{"ensures":1}
,"older":{"processors":1}
,"processor\u2019s":{"pll_a":1}
,"lead":{"issues":1,"xrun":1}
,"issues":{"associated":1,"playing":1,"codec":1,"liable":1}
,"associated":{"changing":1,"40-pin":1}
,"consequently":{"nvidia":1,"sysclk":1}
,"recommends":{"fixing":1,"setting":1,"parameters":1,"configure":1}
,"fixing":{"pll_a":1}
,"init":{"phase":1,"function":1}
,"phase":{"base":1}
,"groups":{"sample":1}
,"requires":{"additional":1,"mclk":1,"default":1}
,"binding":{"sound":1,"documentation":1}
,"fix":{"base":1}
,"yield":{"sampling":1}
,"12288000":{"49152000":1}
,"49152000":{"368640000":1}
,"11289600":{"45158400":1}
,"45158400":{"338688000":1}
,"high":{"definition":1,"resolution":1,"sampling":1}
,"hda":{"interfaces":1,"hdmi":1,"card":1,"devices":1,"ports":1}
,"high-quality":{"audio":1}
,"rendering":{"devices":1,"audio":1,"capturing":1}
,"tvs":{"receivers":1}
,"receivers":{"hda":1}
,"connectors":{"usb-c":1}
,"usb-c":{"needs":1,"converter":1,"j512":1,"j513":1}
,"needs":{"usb-c":1}
,"compliant":{"high":1}
,"specification":{"revision":1,"document":1,"following":1}
,"revision":{"1.0":1}
,"192000":{"hdmi":1}
,"experience":{"issues":1}
,"playing":{"high":1}
,"resolution":{"audio":1,"least":1}
,"formats":{"using":1,"determined":1,"formats":1,"supported":1}
,"multichannel":{"output":1}
,"monitor":{"available":1,"speakers":1}
,"bandwidth":{"depends":1}
,"increasing":{"higher":1}
,"higher":{"display":1}
,"encounter":{"issues":1}
,"level":{"corresponds":1}
,"taken":{"hdmi":1}
,"1.3a":{"specification":1}
,"pixel":{"repetition":1}
,"vertical":{"frequency":1}
,"superaudio":{"channel":1}
,"accessible":{"standard":1}
,"standard":{"alsa":1}
,"-dhw":{"cardname":1,"cid":1}
,"cardname":{"deviceid":1,"sound":1,"represents":1,"cset":1,"i-1":1,"in.wav":1,"44100":1,"inputfile1.wav":1,"inputfile2.wav":1,"rate":1,"devid":1,"contents":1}
,"deviceid":{"in.wav":1,"sound":1}
,"interface\u2019s":{"device":1,"status":1}
,"in.wav":{"name":1,"out.wav":1}
,"played":{".wav":1}
,".wav":{"file":1}
,"further":{"details":1}
,"read":{"card":1}
,"proc":{"asound":1,"config.gz":1,"device-tree":1}
,"asound":{"cards":1,"card":1}
,"16-bit":{"audio":1,"stereo":1}
,"24-bit":{"audio":1}
,"s32_le":{"format":1}
,"provide":{"usb":1,"examples":1,"usage":1,"clues":1}
,"host":{"interface":1}
,"equipment":{"connected":1}
,"capturing":{"audio":1}
,"cid":{"file.wav":1,"rate":1,"card":1}
,"chan":{"sample_format":1,"number":1}
,"sample_format":{"file.wav":1,"sample":1,"out.wav":1}
,"file.wav":{"name":1}
,"wav":{"file":1,"files":1}
,"enumerated":{"upon":1}
,"upon":{"connecting":1}
,"enabling":{"bluetooth":1,"disabling":1,"codec":1,"asoc":1}
,"original":{"jetson":1}
,"ensure":{"bluetooth":1,"sync":1,"parsed":1,"physical":1}
,"stack":{"conformant":1}
,"conformant":{"configuration":1}
,"disabled":{"default":1,"linux":1}
,"profiles":{"enabled":1}
,"conformance":{"may":1}
,"navigate":{"file":1}
,"lib":{"systemd":1,"bluetooth":1}
,"systemd":{"system":1}
,"bluetooth.service.d":{"nv-bluetooth-service.conf":1}
,"text":{"editor":1,"white":1}
,"editor":{"change":1}
,"execstart":{"usr":1}
,"usr":{"lib":1}
,"bluetoothd":{"--noplugin":1}
,"--noplugin":{"audio":1}
,"a2dp":{"avrcp":1}
,"delete":{"\u2011\u2011noplugin":1}
,"\u2011\u2011noplugin":{"option":1}
,"enter":{"commands":1,"command":1}
,"commands":{"update":1,"determine":1,"create":1}
,"apt-get":{"package":1,"update":1,"install":1}
,"package":{"list":1}
,"install":{"pulse":1,"pulseaudio-module-bluetooth":1}
,"sudo":{"apt-get":1,"reboot":1,"mkdir":1,"mount":1,"tee":1}
,"command":{"reboot":1,"line":1,"enter":1,"prints":1,"scan":1,"find":1,"display":1,"i2s3":1,"delays":1}
,"reboot":{"jetson":1,"complete":1}
,"pair":{"connect":1}
,"tables":{"below":1,"pinmux":1}
,"kits":{"note":1,"40-pin":1}
,"bsp":{"provided":1}
,"configured":{"desired":1,"sfio":1,"dspk":1,"perspective":1,"initialization":1,"nvidia":1,".dts":1,"bit-clock":1,"slave":1,"source":1,"i2s4":1,"proper":1,"special":1}
,"desired":{"function":1,"default":1,"value":1,"sysclk":1,"i2c":1,"codec\u2019s":1,"audio":1}
,"pinmux":{"configuration":1,"setting":1,"i2sx":1,"settings":1,"worksheet":1,"changes":1,"change":1,"node":1}
,"adaptation":{"bring-up":1}
,"bring-up":{"applies":1}
,"dap3":{"pins":1}
,"m2.e":{"keyslot":1}
,"dspk1":{"dspk2":1,"via":1,"mux":1}
,"dspk2":{"dmic4":1,"mux":1}
,"dap5":{"pins":1}
,"sclk":{"pin":1}
,"din":{"pin":1}
,"dout":{"pin":1}
,"dap4":{"pins":1}
,"pin":{"sclk":1,"din":1,"dout":1,"dat":1,"configured":1,"port":1}
,"pinmuxed":{"dap3":1}
,"2gb":{"developer":1}
,"dap1":{"pins":1}
,"dap2":{"pins":1}
,"dat":{"pin":1}
,"camera":{"header":1}
,"dap6":{"pins":1}
,"esata":{"connector":1}
,"industrial":{"developer":1}
,"dspk0":{"via":1}
,"30-pin":{"expansion":1}
,"boards":{"used":1}
,"cards":{"jetson":1,"name":1,"file":1,"found":1}
,"choose":{"audio":1,"parent":1,"dsp-b":1,"admaif":1}
,"hardware-compatible":{"terms":1}
,"functional":{"pins":1,"changes":1}
,"sizes":{"frame":1}
,"show":{"configure":1}
,"general":{"setup":1,"refer":1}
,"integrating":{"i2s":1}
,"header\u2019s":{"pinout":1}
,"pinout":{"inferred":1,"configuration":1}
,"inferred":{"schematics":1}
,"schematics":{"jetson":1}
,"give":{"guidance":1,"clue":1}
,"guidance":{"software":1}
,"special-function":{"sfio":1}
,"sfio":{"i2s":1,"select":1,"pinmux":1,"configuration":1}
,"sure":{"audio":1,"relevant":1,"appropriate":1,"parent":1}
,"certain":{"pins":1,"codecs":1}
,"alternate":{"functions":1}
,"jetson-io":{"tool":1}
,"tool":{"supports":1,"used":1}
,"group":{"pins":1}
,"pertaining":{"function":1}
,"i2sx":{"pinmux":1,"pins":1}
,"sdin":{"sdout":1}
,"sdout":{"sck":1}
,"sck":{"lrclk":1}
,"i2c":{"spi":1,"control":1,"node":1,"controller":1,"address":1,"port":1,"bus":1,"buses":1,"bus\u2019s":1}
,"spi":{"access":1,"enabled":1}
,"i2c@":{"addr":1}
,"sgtl5000":{"sgtl5000@0a":1,"codec":1,"example":1,"fixed":1,"sysclk":1,"value":1}
,"fsl":{"sgtl5000":1}
,"micbias-voltage-m-volts":{"3000":1}
,"vdda-supply":{"&vdd_3v3":1}
,"vddio-supply":{"&vdd_3v3":1}
,"documentation":{"determine":1,"requires":1,"front":1}
,"relevant":{"control":1}
,"oscillator":{"clock":1,"example":1,"sitting":1,"codec":1}
,"mclk":{"codec\u2019s":1,"defined":1,"rate":1,"signals":1,"add":1,"frequency":1,"receive":1,"sourced":1}
,"clocked":{"12.288":1}
,"12.288":{"mhz":1}
,"mhz":{"fixed-rate":1}
,"fixed-rate":{"clock":1}
,"sgtl5000_mclk":{"sgtl5000_mclk":1}
,"clock-frequency":{"12288000":1}
,"clock-output-names":{"sgtl5000-mclk":1}
,"ensuring":{"status":1}
,"i2s@":{"addr":1}
,"essential":{"completion":1}
,"completion":{"dapm":1}
,"trace":{"playback":1}
,"initiated":{"codec":1}
,"codec-specific":{"routes":1,"user":1,"mixer":1,"controls":1}
,"additionally":{"entry":1}
,"mic_in":{"mic":1,"adc":1}
,"adc":{"mic":1,"line_in":1,"source":1,"mixl":1,"mixr":1,"direct":1,"swap":1,"volume":1,"mux":1}
,"line_in":{"line":1,"line_out":1}
,"bias":{"line":1}
,"correspond":{"machine":1}
,"hp_out":{"mic_in":1}
,"exploring":{"codec":1}
,"driver\u0027s":{"dapm":1}
,"guideline":{"mentioned":1}
,"observe":{"prefix":1}
,"prefix":{"route":1,"value":1,"widget":1}
,"name-prefix":{"specified":1,"property":1,"entry":1}
,"specified":{"corresponding":1,"first":1,"name-prefix":1,"number":1}
,"codec\u0027s":{"nvidia":1,"internal":1}
,"dai-link-x":{"entry":1,"entries":1,"correct":1}
,"pay":{"attention":1}
,"attention":{"case":1}
,"strings":{"define":1,"used":1}
,"significant":{"strings":1}
,"followed":{"codec":1,"machine":1}
,"point":{"soc":1,"failure":1,"device":1}
,"check":{"whether":1,"latter":1,"pinmux":1,"bit":1}
,"decide":{"mode":1}
,"operates":{"master":1}
,"typically":{"driven":1,"dsp_a":1,"occurs":1,"indicates":1}
,"pll":{"driven":1,"plla_out0":1,"may":1,"configuration":1,"setup":1,"source":1,"default":1}
,"always":{"configured":1}
,"perspective":{"codec":1}
,"absence":{"bitclock-master":1}
,"implies":{"codec":1}
,"sysclk":{"two":1,"mclk":1,"source":1,"rate":1}
,"ways":{"rate":1}
,"tegra186_clk_pll_a_out0":{"&tegra_car":1}
,"tegra186_clk_plla":{"&tegra_car":1}
,"refer":{"sound":1,"available":1,"mixer":1}
,"parent":{"aud_mclk":1,"clock\u2019s":1,"clock":1,"frequency":1}
,"obtain":{"information":1}
,"parents":{"rates":1}
,"sysfs":{"nodes":1}
,"alternatively":{"aud_mclk":1,"look":1}
,"scaling":{"factor":1}
,"factor":{"sampling":1}
,"clock\u2019s":{"rate":1}
,"plla_out0":{"clock":1}
,"equal":{"256":1,"sample_rate":1,"value":1}
,"times":{"sampling":1}
,"rjm":{"i2s":1}
,"dsp_b":{"format":1,"depending":1,"mode":1}
,"sent":{"received":1}
,"delay":{"regard":1,"configure":1}
,"regard":{"fsync":1}
,"according":{"codec":1}
,"timing":{"diagram\u2019s":1,"diagram":1}
,"diagram\u2019s":{"specification":1}
,"disabling":{"kernel":1}
,"symbols":{"jetson":1}
,"symbol":{"snd_soc_tegra210_\u200Caudio_alt":1,"select":1,"enables":1}
,"snd_soc_tegra210_audio_alt":{"symbol":1}
,"select":{"driver":1,"snd_soc_compress":1,"snd_soc_rt5640":1,"snd_soc_rt5659":1,"snd_soc_sgtl5000":1,"desired":1}
,"whenever":{"machine":1,"playback":1}
,"diff":{"patch":1,"--git":1}
,"patch":{"shows":1,"jetson":1,"codec":1,"updates":1,"i2s1":1,"above":1}
,"--git":{"sound":1}
,"kconfig":{"sound":1}
,"index":{"e44c2bb":1,"sound":1,"used":1,"dai":1}
,"e44c2bb":{".759dfe9":1}
,".759dfe9":{"100644":1}
,"---":{"sound":1}
,"-204,6":{"204,7":1}
,"204,7":{"config":1}
,"config":{"snd_soc_tegra210_audio_alt":1}
,"say":{"want":1}
,"want":{"enable":1}
,"tegra210":{"successor":1}
,"successor":{"platforms":1}
,"tegra186":{"tegra194":1}
,"similar":{"patch":1}
,"updated":{"support":1}
,"params":{"example":1}
,"initialization":{"function":1}
,"integrate":{"new":1}
,"sourced":{"soc":1}
,"sitting":{"codec":1}
,"usually":{"codec":1,"256":1}
,"set_sysclk":{"callbacks":1}
,"callbacks":{"triggered":1,"facilitating":1}
,"triggered":{"calling":1}
,"calling":{"snd_soc_dai_set_sysclk":1,"snd_soc_dai_set_pll":1}
,"snd_soc_dai_set_sysclk":{"facilitates":1,"expects":1,"rtd-":1}
,"expects":{"sysclk":1}
,"explained":{"below":1}
,"static":{"int":1,"void":1}
,"int":{"tegra_machine_sgtl5000_init":1,"err":1,"tegra_machine_dai_init":1,"rate":1,"channels":1}
,"tegra_machine_sgtl5000_init":{"struct":1}
,"struct":{"snd_soc_pcm_runtime":1,"device":1,"platform_device":1,"snd_soc_pcm_stream":1}
,"snd_soc_pcm_runtime":{"rtd":1,"runtime":1}
,"rtd-":{"card-":1,"codec_dai":1,"dai_link-":1}
,"card-":{"dev":1}
,"err":{"snd_soc_dai_set_sysclk":1}
,"codec_dai":{"sgtl5000_sysclk":1}
,"sgtl5000_sysclk":{"12288000":1}
,"dev_err":{"dev":1}
,"failed":{"sgtl5000":1,"add":1,"instantiate":1,"i2s0_tx":1,"-22":1}
,"return":{"err":1}
,"dai_link_setup":{"function":1,"struct":1}
,"executed":{"link-name":1}
,"sgtl5000-codec":{"section":1}
,"void":{"dai_link_setup":1}
,"platform_device":{"pdev":1}
,"machine-":{"num_codec_links":1}
,"tegra_machine_codec_links":{".name":1,".init":1}
,"else":{"strstr":1}
,"strstr":{"tegra_machine_codec_links":1}
,"updates":{"dai":1}
,"current":{"property":1}
,"upscale":{"bclk":1}
,"bclk":{"rate":1,"ratio":1,"verify":1}
,"512":{"codec":1}
,"set_pll":{"callbacks":1}
,"snd_soc_dai_set_pll":{"tegra_machine_dai_init":1,"defined":1}
,"tegra_machine_dai_init":{"infer":1,"struct":1}
,"infer":{"pll":1}
,"sheet":{"given":1}
,"sample_rate":{"channels":1,"parameters":1}
,"word_size":{"expected":1}
,"u64":{"formats":1}
,"bool":{"is_playback":1}
,"rtd":{"snd_soc_get_pcm_runtime":1}
,"snd_soc_get_pcm_runtime":{"card":1}
,"snd_soc_pcm_stream":{"rtd-":1}
,"dai_link-":{"params":1}
,"dai_params-":{"rate_min":1,"channels_min":1,"formats":1}
,"rate_min":{"clk_rate":1}
,"channels_min":{"channels":1}
,"integration":{"following":1}
,"guidelines":{"above":1}
,"j511":{"bottom":1,"supports":1}
,"bottom":{"developer":1}
,"close":{"text":1}
,"white":{"background":1}
,"background":{"description":1}
,"intel\u2019s":{"front":1}
,"connector":{"details":1,"port":1}
,"intel":{"document":1}
,"www.intel.com":{"content":1}
,"content":{"www":1}
,"www":{"support":1}
,"articles":{"000005512":1}
,"000005512":{"boards-and-kits":1}
,"boards-and-kits":{"desktop-boards.html":1}
,"prefixed":{"substring":1}
,"substring":{"defined":1}
,"view":{"codec-specific":1}
,"grep":{"name-prefix":1,"asoc":1,"codec_name":1,"config_snd_soc_spdif":1,"snd_soc_":1}
,"look":{"codec-specific":1}
,"recordings":{"mixer":1}
,"manufacturer\u2019s":{"documentation":1}
,"numbering":{"details":1}
,"dac":{"mixr":1,"switch":1,"mixl":1,"mux":1}
,"mixr":{"dac":1,"adc1":1,"direct":1,"direc:qt":1}
,"mixl":{"dac":1,"adc1":1,"direct":1}
,"hpo":{"playback":1}
,"hw:tegrasndt19xmob":{"in.wav":1}
,"recmix1l":{"bst1":1,"bst2":1,"direct":1}
,"bst1":{"switch":1,"bst1":1}
,"recmix1r":{"bst1":1,"bst2":1,"direct":1}
,"bst2":{"switch":1}
,"in2":{"boost":1}
,"stereo1":{"adc":1,"adc1":1}
,"adc1":{"source":1,"switch":1,"adc1":1,"stereo1":1}
,"-dhw:tegrasndt19xmob":{"48000":1}
,"in1":{"boost":1}
,"soundcard":{"name":1}
,"plugging":{"usb":1}
,"cardid":{"index":1}
,"devid":{"device":1,"may":1,"find":1,"values":1,"mappings":1,"in.wav":1,"rate":1}
,"pcmc":{"devid":1}
,"mappings":{"hda":1}
,"hdmi_dp0":{"usb-c":1}
,"hdmi_dp1":{"usb-c":1}
,"hdmi_dp2":{"hdmi":1}
,"out.wav":{"represent":1}
,"i-1":{"in.wav":1,"rate":1,"48000":1}
,"loopback":{"i2s2":1}
,"hostless":{"mode":1}
,"located":{"device":1}
,"graphical":{"user":1}
,"parameter":{"configuration":1}
,"override":{"sample":1,"prefixes":1,"case":1}
,"msut":{"send":1}
,"codec-x":{"rate":1}
,"remarks":{"following":1}
,"drift":{"i2s1":1,"i2s4":1,"issue":1,"caused":1}
,".dts":{"file":1}
,"issue":{"sync":1,"different":1}
,"caused":{"using":1}
,"i2s_clk_parent":{"ext_audio_sync":1}
,"pinctrl-names":{"dap_active":1}
,"dap_active":{"dap_inactive":1}
,"running":{"starting":1,"case":1,"jetson_clocks.sh":1}
,"starting":{"case":1,"playback":1}
,"multi-channel":{"tdm":1}
,"i\u20111":{"represents":1}
,"last":{"digit":1}
,"digit":{"i2s4":1}
,"changed":{"different":1}
,"datasheet":{"i2s4":1,"tracing":1}
,"tuned":{"per":1}
,"sensitivity":{"external":1}
,"mvc1":{"mux":1,"vol":1,"input":1}
,"vol":{"12602":1,"q8.24_val":1}
,"stage":{"maintained":1}
,"loss":{"due":1}
,"due":{"attenuation":1,"reasons":1,"loose":1}
,"essence":{"mvc":1}
,"compensatory":{"gain":1}
,"attenuated":{"dmic":1}
,"three":{"streams":1,"stereo":1}
,"rxcif0":{"dmic3":1}
,"amx2-1":{"mux":1}
,"amx2-2":{"mux":1}
,"amx2":{"output":1,"byte":1}
,"rxcif1":{"i2s":1}
,"amx2-3":{"mux":1}
,"adx1":{"mux":1,"input":1,"output1":1,"output2":1,"byte":1}
,"output1":{"channels":1}
,"output2":{"channels":1}
,"admaif3":{"feeds":1,"mux":1}
,"feeds":{"sfc1":1}
,"sfc1":{"generates":1,"mux":1,"input":1,"output":1}
,"frequency-converted":{"output":1}
,"adder1":{"mixer":1,"rx1":1,"rx2":1}
,"mixer1-1":{"mux":1}
,"mixer1-2":{"mux":1}
,"liable":{"occur":1}
,"occur":{"working":1,"start":1}
,"working":{"asoc":1}
,"probable":{"causes":1}
,"typical":{"ones":1}
,"ones":{"described":1}
,"sink":{"widget":1}
,"4.874720":{"tegra-audio-t210ref":1}
,"tegra-audio-t210ref":{"tegra-audio-t210ref.0":1}
,"tegra-audio-t210ref.0":{"asoc":1}
,"4.874724":{"tegra-audio-t210ref":1}
,"out-":{"direct-":1}
,"direct-":{"headphone-x":1}
,"4.874736":{"tegra-audio-t210ref":1}
,"4.874739":{"tegra-audio-t210ref":1}
,"linein-x-":{"direct-":1}
,"spdif-dit":{"dummy":1,"example":1}
,"verify":{"codec":1,"default":1,"timings":1,"generated":1}
,"cat":{"sys":1}
,"zcat":{"proc":1}
,"config.gz":{"grep":1}
,"codec_name":{"name":1,"config_snd_soc_spdif":1}
,"spdif":{"codec":1}
,"config_snd_soc_spdif":{"command":1}
,"prints":{"codec":1}
,"proper":{"pinmux":1}
,"worksheet":{"download":1}
,"download":{"searching":1,"center":1}
,"searching":{"jetson":1}
,"center":{"pinmux":1}
,"instructed":{"pinmux":1}
,"once":{"pinmux":1}
,"scan":{"desired":1,"indicate":1,"rest":1}
,"bus":{"confirm":1,"check":1,"connected":1}
,"confirm":{"codec":1,"settings":1,"audio":1}
,"i2cdetect":{"i2c-bus-number":1}
,"loose":{"connection":1}
,"connection":{"codec":1}
,"latter":{"cause":1}
,"cause":{"scan":1}
,"buses":{"identify":1}
,"place":{"codec":1}
,"bus\u2019s":{"node":1}
,"dai-link":{"desired":1}
,"ist":{"less":1}
,"prefixes":{"appropriately":1}
,"i2s-to-codec":{"dai":1}
,"tegra210-i2s":{"tegra":1,"tegra210-i2s.0":1}
,"type":{"processor":1}
,"processor":{"jetson":1}
,"failure":{"give":1}
,"clue":{"i2s":1}
,"accordingly":{"instantiate":1}
,"providing":{"suitable":1,"following":1}
,"suitable":{"entry":1}
,"audible":{"recorded":1}
,"follow":{"procedure":1}
,"procedure":{"diagnose":1}
,"diagnose":{"issue":1}
,"completed":{"may":1}
,"vendor":{"codec":1}
,"tracing":{"dapm":1,"events":1,"trace_pipe":1}
,"events":{"enabled":1,"-name":1,"enter":1}
,"-name":{"enable":1}
,"snd_soc_":{"echo":1}
,"echo":{"done":1,"sudo":1}
,"proceed":{"dapm":1}
,"trace_pipe":{"grep":1}
,"jack":{"jetson":1,"direct":1}
,"rt5659":{"admaif1":1}
,"snd_soc_dapm_path":{"admaif1":1,"i2s1":1,"aif1":1,"aif1tx":1,"if1":1,"dac":1,"dac1":1,"dac_ref":1,"tdm":1,"if_adc2":1,"if_adc1":1,"stereo1":1,"adc1":1,"recmix1r":1,"recmix1l":1,"bst1":1,"in1n":1,"in1p":1,"mic":1}
,"transmit-i2s1":{"receive":1}
,"aif1":{"capture-i2s1":1,"capture":1}
,"capture-i2s1":{"dap":1}
,"aif1tx":{"direct":1}
,"if1":{"adc":1,"dac1":1}
,"dac1":{"if1_dac1":1,"direct":1,"if1":1,"switch":1,"mixr":1,"mixl":1}
,"if1_dac1":{"spdif":1}
,"dac_ref":{"dac_ref":1,"if3":1,"direct":1}
,"if3":{"adc":1}
,"ad1:ad2:dac":{"ad1:ad2:dac:nul":1}
,"ad1:ad2:dac:nul":{"tdm":1}
,"swap":{"mux":1}
,"if_adc2":{"if_adc2":1,"if2":1,"direct":1}
,"if2":{"adc":1}
,"if_adc1":{"direct":1}
,"in1n":{"direct":1}
,"in1p":{"direct":1,"in2p":1}
,"in2p":{"case":1}
,"indirectly":{"codec":1,"platform":1}
,"dai\u2019s":{"aif_out":1}
,"aif_out":{"aif_in":1}
,"aif_in":{"aif_out":1,"aif1":1}
,"special":{"function":1}
,"ios":{"sfios":1}
,"sfios":{"gpios":1}
,"gpios":{"pinmux":1}
,"instructions":{"section":1}
,"okay":{"appropriate":1}
,"tegra210-soc":{"tegra210-audio.dtsi":1}
,"alternative":{"method":1}
,"inspect":{"device":1}
,"target":{"using":1}
,"dtc":{"dts":1}
,"device-tree":{"tmp":1}
,"tmp":{"dt.log":1}
,"timings":{"correct":1}
,"generated":{"desired":1}
,"steps":{"help":1}
,"post":{"query":1}
,"query":{"appropriate":1}
,"forum":{"providing":1}
,"conditions":{"problem":1}
,"problem":{"manifested":1,"i2s":1,"occurs":1}
,"manifested":{"sampling":1}
,"contents":{"settings.txt":1}
,"oscilloscope":{"snapshots":1}
,"snapshots":{"without":1}
,"dump":{"i2s":1}
,"regmap":{"tegra210-i2s.3":1}
,"tegra210-i2s.3":{"registers":1}
,"t210-based":{"device":1}
,"pathname":{"appropriate":1}
,"reset":{"failed":1,"fails":1}
,"fails":{"starting":1,"typically":1}
,"error":{"messages":1}
,"messages":{"appear":1}
,"appear":{"dmesg":1}
,"tegra210-i2s.0":{"failed":1,"asoc":1}
,"i2s0_tx":{"reset":1}
,"pre_pmu":{"i2s1":1}
,"event":{"failed":1,"typically":1,"signify":1}
,"occurs":{"clock":1,"i2s":1,"check":1,"try":1}
,"active":{"hence":1}
,"xrun":{"observed":1,"either":1,"event":1,"occurs":1,"events":1}
,"observed":{"during":1,"journaling":1}
,"underrun":{"playback":1}
,"overrun":{"capture":1}
,"circular":{"buffer":1}
,"buffer":{"case":1,"dma":1,"data":1,"reduce":1,"defined":1}
,"writes":{"audio":1}
,"reads":{"sends":1,"stale":1}
,"sends":{"data":1}
,"unable":{"keep":1}
,"keep":{"dma":1}
,"stale":{"data":1}
,"lost":{"hence":1}
,"signify":{"system":1}
,"performance":{"latency":1,"issue":1,"running":1}
,"try":{"measures":1}
,"measures":{"determine":1}
,"jetson_clocks.sh":{"script":1}
,"home":{"directory":1}
,"root":{"file":1}
,"reading":{"writing":1}
,"ext4":{"journaling":1,"lead":1}
,"journaling":{"enabled":1,"file":1}
,"latencies":{"observed":1,"default":1}
,"systems":{"ext4":1}
,"create":{"simple":1}
,"100":{"ram":1}
,"mkdir":{"mnt":1}
,"mnt":{"ramfs":1}
,"mount":{"tmpfs":1}
,"tmpfs":{"size":1,"mnt":1}
,"100m":{"tmpfs":1}
,"increase":{"size":1}
,"reduce":{"impact":1}
,"impact":{"system":1}
,"buffer_bytes_max":{"member":1}
,"member":{"tegra_alt_pcm_hardware":1}
,"tegra_alt_pcm_hardware":{"structure":1}
,"utils":{"tegra_pcm_alt.c":1}
,"pops":{"clicks":1}
,"clicks":{"may":1}
,"end":{"playback":1}
,"happen":{"i2s":1}
,"powered":{"down":1}
,"down":{"completely":1}
,"delays":{"transmission":1}
,"transmission":{"reception":1}
,"reception":{"data":1}
,"milliseconds":{"replace":1}
,"replace":{"sound":1}
,"tee":{"sys":1}
,"sound_card":{"dapm_pop_time":1,"sound":1}
}
;Search.control.loadWordPairs(pairs);
