var pairs =
{
"hardware":{"bring-up":1,"control":1,"software":1,"validation":1}
,"bring-up":{"checklist":1,"process":1,"topics":1,"considerations":1,"steps":1,"hardware":1}
,"section":{"provides":1,"read":1,"platform\u2019s":1}
,"provides":{"checklist":1}
,"checklist":{"platform":1,"complete":1,"software":1}
,"platform":{"hardware":1}
,"adaptation":{"bring-up":1}
,"topics":{"platforms":1}
,"platforms":{"contain":1}
,"contain":{"section":1,"current":1}
,"read":{"begin":1}
,"begin":{"bring-up":1}
,"process":{"sections":1}
,"sections":{"headings":1,"actual":1}
,"headings":{"bring-up":1}
,"considerations":{"generally":1}
,"generally":{"appear":1}
,"appear":{"near":1,"correctly":1}
,"near":{"end":1,"jetson":1,"btb":1,"processor":1,"panel":1}
,"end":{"topic":1,"link":1,"socket":1}
,"topic":{"check":1,"start":1,"actual":1}
,"check":{"section":1,"corresponding":1,"pinmux":1}
,"platform\u2019s":{"topic":1}
,"start":{"bring-up":1}
,"right-hand":{"columns":1}
,"columns":{"indicate":1}
,"indicate":{"bring-up":1}
,"steps":{"apply":1}
,"apply":{"processors":1}
,"processors":{"given":1}
,"given":{"processor\u2019s":1}
,"processor\u2019s":{"column":1,"cts":1}
,"column":{"indicates":1}
,"indicates":{"step":1}
,"step":{"applies":1,"processor":1}
,"applies":{"processor":1}
,"processor":{"space":1,"check":1,"device":1}
,"space":{"indicates":1}
,"nvidia":{"recommends":1,"jetson":1,"diagnostic":1,"tegra":1}
,"recommends":{"print":1}
,"print":{"topic":1,"hardware":1}
,"actual":{"checklist":1,"checklists":1}
,"complete":{"applicable":1}
,"applicable":{"step":1}
,"corresponding":{"ensure":1}
,"ensure":{"miss":1,"soc_pwr_req":1,"cpu":1,"cpu_pwr_req":1}
,"miss":{"repeat":1}
,"repeat":{"steps":1}
,"agx":{"xavier":1}
,"sure":{"module":1}
,"module":{"connected":1,"data":1,"provided":1,"available":1,"device":1,"meets":1}
,"connected":{"btb":1,"fan\u2019s":1}
,"btb":{"connector":1}
,"connector":{"correctly":1,"test":1,"using":1,"bidirectional":1,"devices":1}
,"correctly":{"securely":1,"unknown":1}
,"verify":{"power":1,"vdd_in":1,"power_en":1,"carrier_pwr_on":1,"system":1,"tegraboot":1,"runs":1,"uarts":1,"supplies":1,"enable":1,"carrier":1,"rails":1,"required":1,"usb0":1,"usb":1,"avdd_usb":1,"signals":1,"hdmi":1,"display":1,"signal":1,"reads":1,"playback":1,"capture":1,"tones":1,"audio":1,"processor\u2019s":1,"proper":1,"basic":1,"card":1,"module\u2019s":1,"fan":1,"fan\u2019s":1,"addresses":1,"interrupts":1,"functionality":1,"touch":1,"implemented":1,"i2c":1,"embedded":1,"dsi":1,"preview":1,"video":1,"flashes":1,"cameras":1,"available":1,"privacy":1,"update":1,"board":1,"operation":1,"pmic":1,"tegraflash":1,"uart":1,"kbd":1,"support":1}
,"power":{"supplies":1,"turned":1,"optimization":1,"rail":1,"mode":1,"system":1,"state":1,"sequencing":1,"tree":1,"reset":1,"clocks":1,"down":1}
,"supplies":{"shorted":1,"required":1}
,"shorted":{"ground":1}
,"ground":{"power":1}
,"initial":{"power-on":1,"software":1}
,"vdd_in":{"carrier":1}
,"carrier":{"board":1}
,"board":{"volts":1,"range":1,"power-on":1,"drive":1,"bct":1,"verify":1,"schematics":1,"pinmux":1,"flashing":1}
,"range":{"volts":1}
,"power_en":{"high":1,"signal":1}
,"high":{"power":1}
,"carrier_pwr_on":{"high":1,"signal":1}
,"system":{"enter":1,"flashed":1,"low":1,"deep":1,"enters":1,"supported":1,"state":1,"power":1,"edp":1}
,"enter":{"force":1,"lowest":1}
,"force":{"recovery":1}
,"software":{"flashing":1,"bring-up":1,"sections":1}
,"flashed":{"tegraflash":1}
,"tegraboot":{"cboot":1,"u\u2011boot":1}
,"cboot":{"run":1}
,"run":{"completion":1}
,"completion":{"checking":1}
,"checking":{"log":1,"lanes":1,"diff":1}
,"log":{"output":1}
,"u\u2011boot":{"run":1}
,"runs":{"desktop":1}
,"uarts":{"intended":1}
,"intended":{"debugging":1,"peripheral":1}
,"debugging":{"enabled":1}
,"enabled":{"functional":1,"normal":1}
,"required":{"power-on":1,"rails":1}
,"power-on":{"initially":1,"sequence":1}
,"initially":{"enabled":1,"disabled":1}
,"enable":{"disable":1}
,"disable":{"controllable":1}
,"controllable":{"supply":1}
,"supply":{"different":1}
,"different":{"voltage":1}
,"voltage":{"levels":1,"hardware":1,"comparator":1}
,"levels":{"applicable":1}
,"sequence":{"starts":1,"meets":1,"power":1}
,"starts":{"sys_reset":1,"power_en":1,"carrier_pwr_on":1}
,"sys_reset":{"high":1}
,"signal":{"asserted":1,"quality":1,"edges":1,"pulse":1}
,"capture":{"soc_pwr_req":1,"cpu":1,"cpu_pwr_req":1,"usb0_d":1,"usb2_d":1,"hdmi":1,"works":1,"signals":1}
,"soc_pwr_req":{"mod_sleep":1,"associated":1}
,"mod_sleep":{"pin":1}
,"pin":{"entering":1}
,"entering":{"exiting":1}
,"exiting":{"suspend":1,"deep":1}
,"suspend":{"sc7":1,"lp0":1,"lp1":1}
,"sc7":{"ensure":1,"optional":1}
,"associated":{"power":1,"display":1,"imager":1}
,"rail":{"sequence":1,"check":1}
,"meets":{"jetson":1,"appropriate":1,"eye":1,"manufacturer\u0027s":1}
,"jetson":{"xavier":1,"nano":1,"tx1":1,"agx":1,"tx2":1,"module":1,"developer":1,"pins":1,"download":1}
,"xavier":{"module":1,"tegra":1,"tuning":1,"series":1,"jetson":1,"edp":1}
,"data":{"sheet":1,"sheets":1}
,"sheet":{"requirements":1}
,"cpu":{"pwr":1,"core":1,"power":1}
,"pwr":{"request":1}
,"request":{"entering":1,"associated":1}
,"deep":{"sleep":1}
,"sleep":{"lp0":1,"sc7":1}
,"lp0":{"ensure":1,"suspend":1,"optional":1}
,"appropriate":{"module":1,"tuning":1,"test":1,"reference":1,"signals":1}
,"original":{"jetson":1}
,"nano":{"jetson":1,"module":1,"tegra":1,"interface":1,"developer":1,"nvidia":1,"product":1,"dsi":1}
,"tx1":{"jetson":1,"module":1,"usb":1,"additional":1,"nvidia":1,"oem":1,"dsi":1}
,"cpu_pwr_req":{"entering":1,"associated":1}
,"tx2":{"series":1}
,"series":{"data":1,"tegra":1,"tuning":1,"jetson":1,"interface":1,"hdmi":1,"nvidia":1,"oem":1,"dsi":1}
,"rails":{"deep":1,"back":1,"powered":1,"associated":1}
,"back":{"correct":1}
,"correct":{"voltage":1,"eye":1,"colors":1}
,"control":{"exiting":1,"interface":1}
,"usb":{"2.0":1,"recovery":1,"phys":1,"signals":1,"tuning":1,"3.0":1}
,"2.0":{"phy":1}
,"usb0":{"supports":1,"device":1,"usb1":1}
,"supports":{"usb":1}
,"recovery":{"device":1,"mode":1}
,"device":{"mode":1,"host":1,"similar":1,"look":1,"tree":1}
,"mode":{"works":1,"implemented":1,"used":1,"enabled":1,"system":1,"rails":1}
,"works":{"intended":1,"1080p":1,"properly":1,"wakes":1,"implemented":1,"cameras":1}
,"peripheral":{"types":1}
,"types":{"supported":1}
,"usb1":{"usb2":1}
,"usb2":{"host":1}
,"host":{"mode":1,"detection":1}
,"detection":{"supported":1,"works":1}
,"phys":{"lowest":1}
,"lowest":{"power":1}
,"used":{"system":1,"audio":1,"low":1}
,"low":{"power":1}
,"usb0_d":{"signals":1}
,"signals":{"ends":1,"meet":1,"connector":1,"receiver":1,"look":1,"probed":1,"near":1}
,"ends":{"link":1}
,"link":{"connector":1,"accessible":1,"near":1}
,"test":{"points":1,"fixture":1}
,"points":{"near":1,"access":1,"verify":1}
,"usb2_d":{"signals":1}
,"avdd_usb":{"avdd_pll_utmip":1}
,"avdd_pll_utmip":{"during":1}
,"during":{"deep":1}
,"using":{"usb-if":1,"ddc":1,"appropriate":1,"tach":1}
,"usb-if":{"procedures":1}
,"procedures":{"verify":1}
,"meet":{"requirements":1}
,"requirements":{"correct":1,"refer":1,"met":1,"appropriate":1}
,"eye":{"height":1,"diagram":1}
,"height":{"width":1}
,"refer":{"appropriate":1}
,"tuning":{"guide":1,"compliance":1,"jetson":1}
,"guide":{"adjust":1,"chapter":1,"document":1,"details":1,"available":1}
,"adjust":{"settings":1}
,"settings":{"until":1}
,"until":{"requirements":1}
,"tegra":{"usb":1,"hdmi":1,"mods":1}
,"chapter":{"jetson":1}
,"compliance":{"guide":1,"testing":1}
,"document":{"number":1}
,"number":{"da-09890":1,"da\u201109704":1,"da\u201109855":1,"da-09326":1,"da\u201108619":1,"da-09704":1,"da\u201109737":1,"da\u201109326":1,"dg-09502":1,"dg-09840":1}
,"interface":{"tuning":1,"lowest":1,"used":1,"able":1,"writes":1}
,"testing":{"guide":1}
,"3.0":{"host":1,"device":1,"interface":1}
,"hdmi":{"-compatible":1,"reads":1,"signals":1,"related":1,"tuning":1}
,"-compatible":{"display":1}
,"display":{"works":1,"detected":1,"using":1,"optional":1,"shows":1,"mode":1,"display":1,"bridge":1,"meets":1,"hdmi":1}
,"detected":{"properly":1}
,"properly":{"hpd":1,"speakers":1,"sound":1,"cameras":1,"implemented":1}
,"reads":{"writes":1,"display":1,"work":1}
,"writes":{"display":1,"i2c":1,"variety":1,"reads":1}
,"ddc":{"interface":1}
,"fixture":{"termination":1}
,"related":{"rails":1,"circuitry":1}
,"powered":{"used":1}
,"quality":{"acceptable":1}
,"acceptable":{"meets":1,"look":1,"probed":1,"including":1}
,"diagram":{"consult":1}
,"consult":{"appropriate":1}
,"additional":{"documentation":1}
,"documentation":{"available":1}
,"i2c":{"interface":1,"general":1,"devices":1,"touch":1,"spi":1,"control":1}
,"audio":{"codec":1}
,"playback":{"works":1}
,"speakers":{"headphones":1}
,"headphones":{"headset":1}
,"sound":{"recorded":1}
,"recorded":{"microphone":1}
,"microphone":{"headset":1,"speaker":1}
,"headset":{"supported":1}
,"tones":{"voice":1}
,"voice":{"heard":1}
,"heard":{"speakers":1}
,"codec":{"lowest":1}
,"enters":{"low":1}
,"receiver":{"end":1}
,"accessible":{"i2s":1}
,"i2s":{"used":1}
,"look":{"excessive":1}
,"excessive":{"undershoot":1}
,"undershoot":{"glitches":1}
,"glitches":{"signal":1}
,"cts":{"rts":1,"lines":1}
,"rts":{"pins":1,"cts":1}
,"pins":{"connect":1,"gpios":1}
,"connect":{"device\u2019s":1}
,"device\u2019s":{"rts":1}
,"lines":{"uart":1,"connected":1}
,"uart":{"used":1,"output":1}
,"card":{"pinouts":1,"reader":1,"insertion":1,"write":1,"low":1}
,"sdmmc3":{"available":1}
,"available":{"module":1,"custom":1,"jetson":1,"autofocus":1}
,"provided":{"jetson":1,"developer":1}
,"developer":{"kit":1}
,"kit":{"p3668-0000":1,"implemented":1,"p3468-0000":1}
,"p3668-0000":{"designed":1}
,"designed":{"production":1}
,"production":{"devices":1,"module":1}
,"devices":{"p3668-0001":1,"p3448-0002":1,"appear":1}
,"p3668-0001":{"custom":1}
,"custom":{"carrier":1,"desktop":1}
,"drive":{"card":1}
,"sdmmc1":{"drives":1}
,"drives":{"card":1}
,"reader":{"module":1,"skus":1}
,"implemented":{"production":1,"pex":1,"sata":1,"pcie":1}
,"p3468-0000":{"designed":1}
,"p3448-0002":{"custom":1}
,"skus":{"processors":1}
,"proper":{"connectivity":1}
,"connectivity":{"setting":1,"checking":1}
,"setting":{"jetson":1}
,"gpios":{"necessary":1}
,"necessary":{"debug":1}
,"basic":{"commands":1}
,"commands":{"operate":1}
,"operate":{"properly":1}
,"variety":{"cards":1}
,"insertion":{"detection":1}
,"wakes":{"system":1}
,"write":{"protect":1}
,"protect":{"works":1}
,"probed":{"receiver":1,"btb":1}
,"socket":{"test":1}
,"bidirectional":{"signals":1}
,"edges":{"abnormal":1}
,"abnormal":{"clock":1}
,"clock":{"duty":1}
,"duty":{"cycle":1}
,"module\u2019s":{"pwm":1}
,"pwm":{"tach":1,"signal":1}
,"tach":{"lines":1,"pin":1}
,"fan\u2019s":{"pwm":1,"rpm":1}
,"fan":{"speed":1}
,"speed":{"changed":1}
,"changed":{"based":1}
,"based":{"pwm":1}
,"pulse":{"width":1}
,"rpm":{"measured":1}
,"measured":{"using":1}
,"sensors":{"i2c":1}
,"addresses":{"i2c":1}
,"unknown":{"ghost":1}
,"ghost":{"devices":1}
,"including":{"rise":1}
,"rise":{"times":1}
,"times":{"signals":1}
,"touch":{"screen":1}
,"screen":{"optional":1,"controller":1}
,"spi":{"touch":1}
,"controller":{"functional":1,"lowest":1}
,"functional":{"reading":1}
,"reading":{"device":1}
,"similar":{"register":1}
,"register":{"successful":1}
,"interrupts":{"generated":1}
,"generated":{"properly":1}
,"functionality":{"touch":1}
,"pex":{"optional":1,"interfaces":1}
,"interfaces":{"transition":1}
,"transition":{"lowest":1}
,"state":{"deep":1,"suspend":1}
,"sata":{"optional":1,"interfaces":1}
,"diff":{"lines":1}
,"pcie":{"optional":1,"interfaces":1}
,"embedded":{"display":1,"display\u2019s":1}
,"able":{"perform":1}
,"perform":{"writes":1}
,"shows":{"correct":1}
,"display\u2019s":{"backlight":1}
,"backlight":{"enabled":1,"brightness":1,"disabled":1}
,"normal":{"display":1}
,"brightness":{"adjusted":1}
,"adjusted":{"properly":1}
,"disabled":{"low":1}
,"bridge":{"transitions":1}
,"transitions":{"lowest":1}
,"sequencing":{"rails":1}
,"manufacturer\u0027s":{"requirements":1}
,"dsi":{"edp":1,"lvds":1}
,"edp":{"timing":1,"signals":1,"contain":1}
,"timing":{"appropriate":1,"nvidia":1}
,"reference":{"details":1}
,"details":{"verify":1}
,"download":{"center":1}
,"product":{"design":1}
,"design":{"guide":1}
,"oem":{"product":1}
,"lvds":{"edp":1}
,"probe":{"appropriate":1,"mclk":1}
,"panel":{"driver":1}
,"driver":{"connector":1,"possible":1}
,"access":{"driver":1}
,"possible":{"verify":1}
,"imager":{"optional":1,"module":1}
,"work":{"cameras":1}
,"preview":{"displays":1}
,"displays":{"properly":1}
,"video":{"capture":1}
,"flashes":{"operate":1}
,"cameras":{"related":1}
,"circuitry":{"enter":1}
,"autofocus":{"mechanism":1}
,"mechanism":{"functions":1}
,"functions":{"properly":1}
,"privacy":{"led":1}
,"led":{"operates":1}
,"operates":{"properly":1}
,"mclk":{"output":1}
,"output":{"recommended":1}
,"recommended":{"test":1}
,"checklists":{"complete":1}
,"replaced":{"sdram":1,"carrier":1,"emmc":1}
,"sdram":{"mb1":1}
,"mb1":{"bct":1,"pmic":1,"pinmux":1,"mb2":1}
,"bct":{"new":1,".cfg":1,"full-speed":1}
,"new":{"ddr":1}
,"ddr":{"verify":1,"emmc":1}
,"update":{"bpmp":1}
,"bpmp":{".dts":1}
,".dts":{"file":1}
,"file":{"dvfs":1,"check":1}
,"dvfs":{"support":1}
,"operation":{"emmc":1}
,"emmc":{"memory":1,"verify":1,"cpu":1}
,"memory":{"nvidia":1}
,"diagnostic":{"tool":1}
,"pmic":{"pinmux":1,"configuration":1,"sdram":1}
,"pinmux":{"configuration":1,"modify":1,"pad":1,"pmic":1,"gpio":1}
,"obtain":{"board":1}
,"schematics":{"component":1}
,"component":{"data":1}
,"tree":{"modify":1,"mb1":1,"review":1}
,"modify":{"device":1,"mb1":1}
,"configuration":{"accordingly":1}
,"accordingly":{"carrier":1}
,"review":{"board":1,"pinmux":1}
,"pad":{"configuration":1}
,"reset":{"sequence":1}
,"nvtest":{"nvidia":1}
,"mods":{"ddr":1}
,"jtag":{"connection":1}
,"connection":{"check":1}
,"boot":{"validation":1,"scripts":1,"kernel":1,"u-boot":1}
,"kbd":{"connection":1}
,"flashing":{"profile":1}
,"profile":{".conf":1}
,".conf":{"file":1}
,"mb2":{"bct":1}
,".cfg":{"file":1}
,"kernel":{"device":1,"command":1,"peripherals":1}
,"support":{"configure":1}
,"configure":{"boot":1}
,"scripts":{"bootcmd":1}
,"command":{"line":1}
,"line":{"custom":1}
,"peripherals":{"port":1}
,"port":{"validation":1}
,"gpio":{"wake":1}
,"wake":{"pins":1}
,"pmu":{"regulator":1}
,"regulator":{"drivers":1}
,"thermal":{"sensor":1}
,"emc":{"dfs":1}
,"dfs":{"table":1}
,"core":{"gpu":1,"edp":1}
,"gpu":{"dvfs":1,"edp":1}
,"current":{"monitor":1}
,"monitor":{"voltage":1}
}
;Search.control.loadWordPairs(pairs);
