var pairs =
{
"glslc":{"shader":1,"compiler":1,"produces":1,"-gles":1,"enter":1,"--help":1,"displays":1,"match":1,"command\u2019s":1,"command":1,"\u2011chip":1}
,"shader":{"program":1,"source":1,"types":1,"programs":1,"disk":1}
,"program":{"compiler":1,"binaries":1,"characteristics":1,"binary":1}
,"topic":{"describes":1}
,"describes":{"glslc":1}
,"compiler":{"opengl":1,"runs":1,"libraries":1}
,"opengl":{"3.0":1,"driver":1,"program":1,"may":1}
,"3.0":{"program":1}
,"binaries":{"compiler":1,"transferred":1,"particular":1,"written":1,"used":1}
,"runs":{"linux":1}
,"linux":{"host":1}
,"host":{"system":1}
,"system":{"produce":1,"supports":1}
,"produce":{"program":1}
,"transferred":{"target":1}
,"target":{"nvidia":1}
,"nvidia":{"jetson":1}
,"jetson":{"device":1,"xavier":1,"agx":1,"nano":1,"tx1":1,"tx2":1}
,"produces":{"program":1,"binary":1}
,"particular":{"opengl":1}
,"driver":{"compiled":1,"installed":1,"fourth":1,"via":1,"invoke":1,"state":1,"draw":1,"during":1,"loads":1}
,"compiled":{"shaders":1,"binaries":1,"shader":1,"program":1}
,"shaders":{"programs":1,"found":1,"limited":1}
,"programs":{"recompiled":1,"file":1,"runtime":1}
,"recompiled":{"whenever":1}
,"whenever":{"new":1}
,"new":{"driver":1,"machine":1}
,"compile":{"shader":1}
,"enter":{"following":1,"command":1,"multiple":1,"\u2011driverstate":1}
,"following":{"command":1}
,"command":{"host":1,"enter":1,"obtain":1,"may":1,"produces":1}
,"-gles":{"-chip":1}
,"-chip":{"tbd_glsc_chip_id":1}
,"tbd_glsc_chip_id":{"-binary":1,"\u2011vs":1}
,"-binary":{"output_file":1}
,"output_file":{"-vs":1,"pathname":1}
,"-vs":{"vertex_shader_file":1}
,"vertex_shader_file":{"-fs":1,"fragment_shader_file":1}
,"-fs":{"fragment_shader_file":1}
,"chip_id":{"code":1}
,"code":{"indicates":1,"depending":1,"binary":1,"states":1,"configurations":1,"required":1}
,"indicates":{"type":1}
,"type":{"processor":1}
,"processor":{"jetson":1}
,"agx":{"xavier":1}
,"xavier":{"series":1}
,"nano":{"devices":1}
,"tx2":{"series":1}
,"pathname":{"file":1}
,"file":{"compiled":1,"gearslib.c":1,"output_file":1}
,"fragment_shader_file":{"respectively":1}
,"respectively":{"vertex":1,"information":1}
,"vertex":{"fragment":1,"attribute":1}
,"fragment":{"shader":1,"shaders":1}
,"source":{"files":1}
,"files":{"may":1}
,"may":{"contain":1,"optimize":1,"specify":1}
,"contain":{"include":1}
,"include":{"directives":1,"defaults":1}
,"display":{"complete":1}
,"complete":{"information":1}
,"information":{"additional":1,"loading":1}
,"additional":{"shader":1}
,"types":{"supported":1}
,"supported":{"options":1}
,"options":{"glslc":1,"single":1,"flags":1}
,"format":{"compiled":1,"program":1}
,"four":{"bytes":1}
,"bytes":{"containing":1}
,"containing":{"size":1,"format":1,"compiled":1}
,"size":{"program":1,"format":1}
,"variable":{"number":1}
,"number":{"bytes":1}
,"pass":{"parts":1}
,"parts":{"opengl":1}
,"fourth":{"second":1}
,"second":{"third":1,"draw":1}
,"third":{"arguments":1}
,"arguments":{"glprogrambinary":1}
,"glprogrambinary":{"respectively":1,"specific":1}
,"loading":{"shader":1,"runtime":1}
,"successful":{"compilation":1}
,"compilation":{"glslc":1}
,"displays":{"message":1}
,"binary":{"successfully":1,"produced":1,"via":1,"generated":1,"file":1,"optimized":1,"default":1,"during":1}
,"successfully":{"written":1}
,"written":{"output_file":1}
,"produced":{"glslc":1,"opengl":1}
,"match":{"program":1}
,"via":{"call":1,"glprogrambinary":1}
,"call":{"glgetprogrambinary":1,"glclear":1,"resulting":1,"arrays":1,"glslc":1}
,"libraries":{"loaded":1}
,"loaded":{"demand":1,"needed":1,"system":1}
,"two":{"libraries":1,"draw":1,"\u2011driverstate":1}
,"needed":{"compile":1}
,"libnvidia-glcore-cg.so":{"version":1}
,"libnvidia-glcore-ocg.so":{"version":1,"loading":1,"perform":1}
,"used":{"application":1}
,"application":{"precompiled":1,"run":1,"utilizes":1}
,"precompiled":{"opengl":1}
,"invoke":{"compiler":1}
,"supports":{"shader":1}
,"disk":{"cache":1}
,"cache":{"required":1}
,"required":{"shaders":1,"microcode":1}
,"found":{"usually":1}
,"usually":{"first":1}
,"first":{"time":1,"draw":1,"\u2011driverstate":1}
,"time":{"application":1}
,"run":{"libraries":1}
,"command\u2019s":{"\u2011driverstate":1}
,"\u2011driverstate":{"option":1,"options":1,"vertexattribenable":1,"flags":1,"flag":1,"\u2011driverstate":1}
,"option":{"allows":1,"draw":1,"followed":1,"include":1,"below":1}
,"allows":{"small":1}
,"small":{"subset":1}
,"subset":{"gpu":1,"flags":1}
,"gpu":{"machine":1}
,"machine":{"microcode":1,"code":1}
,"microcode":{"inserted":1,"appended":1,"part":1}
,"inserted":{"opengl":1}
,"specific":{"limited":1}
,"limited":{"cases":1,"vertex":1,"subset":1}
,"cases":{"prevent":1}
,"prevent":{"libnvidia-glcore-ocg.so":1}
,"runtime":{"opengl":1,"driver":1,"compilation":1}
,"optimize":{"machine":1}
,"depending":{"driver":1,"certain":1}
,"state":{"requiring":1,"arrays":1,"driver":1}
,"requiring":{"new":1}
,"generated":{"depending":1}
,"certain":{"states":1}
,"states":{"driver":1,"resembles":1}
,"draw":{"call":1,"calls":1}
,"multiple":{"\u2011driverstate":1}
,"single":{"glslc":1}
,"glclear":{"call":1}
,"resulting":{"microcode":1}
,"appended":{"program":1}
,"example":{"consider":1,"command":1,"first":1}
,"consider":{"application":1}
,"utilizes":{"vertex":1}
,"attribute":{"arrays":1,"array":1,"during":1}
,"arrays":{"makes":1,"changes":1,"enabled":1}
,"makes":{"two":1}
,"calls":{"state":1,"attribute":1,"glslc":1}
,"changes":{"draw":1}
,"array":{"enabled":1,"disabled":1}
,"enabled":{"attribute":1,"during":1}
,"disabled":{"constant":1}
,"constant":{"attribute":1}
,"during":{"first":1,"second":1,"two":1,"runtime":1}
,"obtain":{"binary":1}
,"optimized":{"gpu":1}
,"\u2011chip":{"tbd_glsc_chip_id":1}
,"\u2011vs":{"vs.vert":1,"vert.vs":1}
,"vs.vert":{"\u2011fs":1}
,"\u2011fs":{"fs.frag":1,"frag.fs":1}
,"fs.frag":{"\u2011binary":1}
,"\u2011binary":{"prog.bin":1}
,"prog.bin":{"\u2011driverstate":1}
,"vertexattribenable":{"\u2011driverstate":1,"vertexattribenable":1,"correspond":1}
,"flags":{"vertexattribenable":1,"different":1,"specify":1,"need":1,"currently":1,"producing":1}
,"correspond":{"state":1}
,"specify":{"multiple":1,"empty":1}
,"different":{"values":1}
,"values":{"value":1}
,"default":{"machine":1}
,"configurations":{"included":1}
,"included":{"\u2011driverstate":1}
,"empty":{"\u2011driverstate":1}
,"followed":{"flags":1}
,"need":{"default":1,"empty":1}
,"vert.vs":{"\u2011fs":1}
,"frag.fs":{"\u2011driverstate":1}
,"defaults":{"defaults":1,"included":1}
,"flag":{"kind":1}
,"below":{"redundant":1}
,"available":{"flags":1}
,"currently":{"limited":1}
,"producing":{"machine":1}
,"part":{"program":1}
,"loads":{"libnvidia-glcore-ocg.so":1}
,"perform":{"runtime":1}
}
;Search.control.loadWordPairs(pairs);
