var pairs =
{
"setting":{"file":1,"root":1,"ldk_rootfs_dir":1,"range":1,"rootfs_bl_unified_ab":1}
,"file":{"system":1,"home":1,"contains":1,"follows":1,"systems":1,"jetson":1,"non-redundant":1,"xml":1,"describes":1,"name":1,"target":1,"change":1,"slot_metadata.bin.rootfsab":1,"looks":1}
,"nvidia":{"jetson":1,"provides":1,"driver":1,"base":1,"user":1}
,"jetson":{"linux":1,"developer":1,"device":1,"xavier":1,"agx":1,"tx2":1,"platform":1}
,"linux":{"requires":1,"host":1,"driver":1,"provides":1,"uses":1,"booted":1,"supports":1,"image-based":1}
,"requires":{"root":1,"smd":1}
,"root":{"file":1,"directory":1}
,"system":{"create":1,"copy":1,"created":1,"tool":1,"downloads":1,"directory":1,"rootfs":1,"provided":1,"ldk_rootfs_dir":1,"proceed":1,"device":1,"yourself":1,"external":1,"redundancy":1,"partition":1,"architecture":1,"booted":1,"may":1,"image":1,"running":1,"attempted":1,"understanding":1,"particular":1,"disabled":1,"generate":1,"partitions":1,"switch":1}
,"create":{"linux":1,"customized":1,"redundant":1,"flash":1,"file":1}
,"host":{"system":1,"machine":1}
,"copy":{"reference":1,"rootfs":1,"nvidia":1,"binaries":1,"file":1,"slot_metadata.bin.rootfsab":1}
,"reference":{"board":1,"partition":1}
,"sample":{"root":1,"file":1}
,"driver":{"package":1}
,"package":{"l4t":1,"over-the-air":1,"recommended":1}
,"l4t":{"comes":1,"root":1,"provides":1,"system":1,"documents":1}
,"comes":{"pre-built":1}
,"pre-built":{"sample":1}
,"created":{"nvidia":1}
,"developer":{"kits":1}
,"provides":{"tool":1,"full":1,"option":1,"simple":1}
,"tool":{"generate":1,"navigate":1,"root":1,"following":1,"help":1,"shown":1}
,"generate":{"root":1,"new":1}
,"navigate":{"tools":1,"rootfs":1}
,"tools":{"samplefs":1,"kernel_flash":1}
,"samplefs":{"directory":1}
,"directory":{"extracted":1,"tarball":1,"assumed":1,"included":1,"linux_for_tegra":1}
,"extracted":{"nvidia":1}
,"your_l4t_root":{"linux_for_tegra":1,"l4t":1}
,"linux_for_tegra":{"tools":1,"rootfs":1,"bootloader":1,"enter":1,"p3668.conf.common":1,"p2972-0000.conf.common":1,"p2771-0000.conf.common":1}
,"execute":{"script":1,"commands":1,"specified":1}
,"script":{"nv_build_samplefs.sh":1,"name":1,"downloads":1,"copy":1,"shown":1,"installs":1,"success":1,"nv_smd_generator":1}
,"sudo":{"nv_build_samplefs.sh":1,"command":1,"tar":1,"apply_binaries.sh":1,"mkfs.ext4":1,"mount":1,"mntpoint":1,"rootfs_ab":1,"nvbootctrl":1}
,"nv_build_samplefs.sh":{"--abi":1}
,"--abi":{"aarch64":1}
,"aarch64":{"--distro":1}
,"--distro":{"ubuntu":1}
,"ubuntu":{"--version":1}
,"--version":{"bionic":1}
,"explanation":{"parameters":1}
,"parameters":{"enter":1}
,"enter":{"script":1,"following":1,"command":1}
,"name":{"alone":1,"without":1,"output":1,"identify":1}
,"alone":{"need":1}
,"need":{"sudo":1,"understand":1}
,"command":{"used":1,"format":1,"determine":1,"create":1,"runs":1,"commands":1,"sudo":1,"supported":1,"indicates":1,"shown":1}
,"used":{"exactly":1,"boot":1,"bootloader":1,"app":1,"app_b":1}
,"exactly":{"shown":1}
,"shown":{"need":1,"above":1,"below":1,"table":1,"create":1}
,"understand":{"parameters":1}
,"downloads":{"base":1,"installs":1}
,"base":{"image":1,"wish":1}
,"image":{"extracts":1,"used":1,"stored":1,"slot_metadata.bin.rootfsab":1,"file":1,"fails":1}
,"extracts":{"root":1}
,"installs":{"required":1,"binaries":1}
,"required":{"packages":1}
,"packages":{"compresses":1,"update":1}
,"compresses":{"root":1}
,"tarball":{"may":1}
,"may":{"several":1,"changed":1,"exchange":1,"older":1,"may":1,"bootable":1,"specify":1}
,"several":{"hours":1,"attributes":1}
,"hours":{"run":1}
,"run":{"depending":1,"apply_binaries.sh":1,"script":1,"ota":1,"nv_smd_generator":1}
,"depending":{"internet":1}
,"internet":{"speed":1}
,"speed":{"host":1}
,"booting":{"target":1,"immediately":1}
,"target":{"board":1,"file":1,"soc":1,"device":1,"command":1,"type":1,"either":1}
,"board":{"configure":1,"rootfs":1,"redundant":1}
,"configure":{"root":1}
,"rootfs":{"device":1,"skip":1,"directory":1,"already":1,"apply":1,"run":1,"onto":1,"jetson":1,"depends":1,"redundancy":1,"stored":1,"images":1,"selection":1,"rootfs":1,"enabled":1,"default":1,"disabled":1,"slot":1,"several":1,"occupies":1,"slots":1,"linux":1,"fails":1,"slot\u2019s":1,"contains":1,"partitions":1,"attribute":1,"three":1,"configured":1,"bootloader":1,"two":1,"size":1,"partition":1,"support":1,"autosync":1,"active":1,"switching":1,"disable":1,"line":1,"unified":1,"command":1,"information":1,"dump-slots-info":1,"set-active-boot-slot":1,"redundance":1}
,"step":{"root":1,"copy":1}
,"procedure":{"uses":1,"copy":1}
,"uses":{"sample":1,"two":1,"necessarily":1}
,"provided":{"nvidia":1}
,"wish":{"file":1}
,"ldk_rootfs_dir":{"environment":1,"execute":1}
,"environment":{"variable":1}
,"variable":{"point":1}
,"point":{"location":1,"rootfs":1,"host":1}
,"location":{"rootfs":1,"root":1}
,"skip":{"steps":1}
,"steps":{"setting":1}
,"download":{"following":1}
,"following":{"file":1,"procedure":1,"command":1,"commands":1,"list":1}
,"home":{"directory":1}
,"tegra-linux-sample-root-filesystem_":{"release_type":1}
,"release_type":{".tbz2":1}
,"contains":{"nvidia-provided":1,"valid":1}
,"nvidia-provided":{"sample":1}
,"extract":{"compressed":1,"sample":1}
,"compressed":{"file":1}
,"assumed":{"home":1}
,"tar":{"-jxpf":1}
,"-jxpf":{"tegra-linux-sample-root-filesystem_":1}
,"apply_binaries.sh":{"script":1}
,"user":{"space":1,"interface":1}
,"space":{"libraries":1,"allocated":1}
,"libraries":{"target":1,"setting":1}
,"using":{"different":1,"rootfs":1,"uuid":1}
,"different":{"rootfs":1}
,"already":{"configured":1}
,"configured":{"rootfs":1,"together":1}
,"apply":{"nvidia":1}
,"above":{"copy":1,"sets":1,"enables":1}
,"binaries":{"target":1,"correctly":1}
,"correctly":{"last":1}
,"last":{"message":1}
,"message":{"output":1,"description":1,"sudo":1}
,"output":{"script":1,"smd":1}
,"completed":{"setting":1}
,"proceed":{"flash":1,"flashing":1}
,"flash":{"rootfs":1,"command":1,"target":1,"redundant":1,"smd":1,"jetson":1,"root":1}
,"onto":{"target":1}
,"soc":{"device":1}
,"depends":{"type":1}
,"type":{"storage":1,"device":1,"target":1}
,"storage":{"want":1,"device":1}
,"want":{"hold":1}
,"flashing":{"tool":1,"booting":1}
,"device":{"topic":1,"host":1,"formatted":1,"mounted":1,"number":1,"attached":1,"following":1,"unmount":1,"system":1,"tries":1,"examine":1,"workflow":1,"redundant":1,"next":1,"rootfs":1,"boots":1,"name":1,"two":1}
,"topic":{"flashing":1,"jetson":1,"over-the-air":1}
,"prefer":{"root":1}
,"yourself":{"rather":1}
,"rather":{"flashing":1,"device":1}
,"external":{"storage":1,"disk":1}
,"plug":{"rootfs":1}
,"formatted":{"ext4":1}
,"ext4":{"enter":1,"file":1}
,"format":{"ext4":1}
,"mkfs.ext4":{"dev":1}
,"dev":{"port":1,"sdx1":1}
,"port":{"device_number":1,"port":1,"device":1,"dmesg":1}
,"device_number":{"device":1}
,"number":{"device":1,"times":1,"tries":1,"slots":1,"slot":1,"consecutive":1}
,"attached":{"port":1}
,"dmesg":{"command":1}
,"determine":{"port":1}
,"needed":{"mount":1}
,"mount":{"device":1,"dev":1,"point":1}
,"sdx1":{"mntpoint":1}
,"mntpoint":{"mount":1,"sync":1}
,"included":{"release":1}
,"release":{"executing":1}
,"executing":{"following":1,"flash":1}
,"copying":{"content":1}
,"content":{"external":1}
,"disk":{"device":1,"connect":1}
,"unmount":{"disk":1}
,"connect":{"target":1}
,"full":{"support":1}
,"support":{"root":1,"removing":1,"default":1}
,"redundancy":{"rootfs":1,"nvidia":1,"supports":1,"advanced":1,"kernel":1,"customizations":1,"works":1,"size":1,"requires":1,"disable":1,"change":1,"topic":1,"fails":1,"enabled":1}
,"xavier":{"jetson":1,"series":1,"memory":1,"emmc":1,"jetson-xavier-nx-devkit-emmc":1,"linux_for_tegra":1,"agx":1,"tx2":1}
,"agx":{"xavier":1}
,"series":{"jetson":1,"uses":1,"jetson-agx-xavier-devkit":1,"jetson-tx2-devkit":1,"linux_for_tegra":1}
,"tx2":{"series":1,"edit":1,"update":1}
,"two":{"root":1,"file":1,"combinations":1,"partitions":1}
,"systems":{"designated":1,"switching":1,"unbootable":1,"find":1,"various":1,"external":1,"changing":1,"two":1,"display":1,"change":1,"slot":1,"uuid":1,"rootfs":1}
,"designated":{"rootfs":1}
,"stored":{"usual":1,"new":1,"file":1,"bootloader":1}
,"usual":{"file":1}
,"partition":{"app":1,"app_b":1,"names":1,"image":1,"layout":1,"holds":1,"keep":1,"uuid":1,"xxxx":1,"stored":1}
,"app":{"designated":1,"disk":1,"app_b":1,"partition":1}
,"new":{"partition":1,"smd":1}
,"app_b":{"located":1,"may":1,"half":1,"partitions":1,"partition":1}
,"located":{"app":1}
,"graphical":{"user":1}
,"interface":{"text":1,"description":1}
,"text":{"application":1,"message":1,"description":1}
,"application":{"chat":1}
,"chat":{"text":1}
,"description":{"automatically":1}
,"automatically":{"generated":1}
,"supports":{"independent":1,"image-based":1}
,"independent":{"creation":1,"four":1}
,"creation":{"updates":1}
,"updates":{"two":1}
,"switching":{"failover":1,"roles":1}
,"advanced":{"feature":1}
,"feature":{"intended":1}
,"intended":{"customers":1}
,"customers":{"capability":1}
,"capability":{"create":1}
,"customized":{"rootfs":1}
,"names":{"app":1,"layout":1}
,"option":{"tie":1,"customize":1,"unified":1,"defined":1,"used":1}
,"tie":{"bootloader":1}
,"bootloader":{"rootfs":1,"tied":1,"consequently":1,"slots":1,"active":1,"linux":1,"current":1,"slot":1,"boots":1,"t186ref":1,"autosync":1,"root":1,"enabled":1,"auto":1,"information":1,"l4t-rootfs-uuid.txt":1,"l4t-rootfs-uuid.txt_b":1}
,"enabled":{"bootloader":1,"rootfs_active_a":1,"disabled":1,"unified":1,"possible":1,"command":1,"form":1,"information":1,"jetpack":1}
,"tied":{"rootfs":1}
,"information":{"enable":1,"status":1,"smd":1,"jetson":1,"slots":1,"update":1}
,"enable":{"disable":1,"rootfs":1,"bootloader":1}
,"disable":{"option":1,"support":1,"unified":1,"default":1,"bootloader":1,"rootfs":1}
,"customize":{"smd":1,"rootfs":1}
,"smd":{"partition":1,"slot":1,"partitions":1,"smd_b":1,"image":1,"configuration":1}
,"selection":{"unified":1,"independent":1}
,"unified":{"bootloader":1,"unified":1,"enabled":1,"rootfs":1,"disabled":1}
,"disabled":{"bootloader":1,"unified":1,"debian":1}
,"slot":{"selection":1,"redundant":1,"slot":1,"next":1,"whose":1,"system":1,"called":1,"relate":1,"may":1,"rootfs":1,"switched":1,"device":1,"smd_b":1,"customize":1,"retry":1,"info":1,"try":1,"default":1,"change":1,"slots":1,"good":1,"invalid":1,"bootable":1,"marked":1,"zero-based":1,"number":1,"information":1,"active":1,"switching":1,"makes":1,"vice":1,"rebooting":1}
,"four":{"possible":1}
,"possible":{"combinations":1,"option":1}
,"combinations":{"bootloader":1}
,"picture":{"containing":1}
,"containing":{"text":1,"graphical":1,"chat":1}
,"occupies":{"slot":1}
,"redundant":{"file":1,"root":1}
,"architecture":{"slot":1}
,"kernel":{"kernel-dtb":1,"image":1}
,"kernel-dtb":{"partitions":1}
,"partitions":{"belong":1,"smd":1,"flash":1,"together":1,"function":1,"target":1,"enabling":1,"app":1,"rootfs":1}
,"belong":{"userspace":1,"rootfs":1}
,"userspace":{"bootloader":1}
,"consequently":{"belong":1}
,"slots":{"selected":1,"bootloader":1,"course":1,"root":1,"setting":1,"nvbootctrl":1,"unbootable":1}
,"selected":{"rootfs":1}
,"active":{"rootfs":1,"slot":1}
,"next":{"boot":1,"rebooted":1}
,"boot":{"operation":1,"active":1,"device":1,"specified":1,"recovery":1,"rootfs":1,"load":1,"again":1}
,"operation":{"attempt":1}
,"attempt":{"boot":1}
,"whose":{"rootfs":1,"bootloader":1}
,"necessarily":{"bootloader":1,"bootable":1}
,"current":{"rootfs":1,"unused":1,"slot":1}
,"booted":{"currently":1}
,"currently":{"using":1,"running":1}
,"called":{"unused":1}
,"unused":{"rootfs":1}
,"exchange":{"roles":1}
,"roles":{"current":1}
,"course":{"update":1}
,"update":{"current":1,"engine":1,"mode":1,"rootfs":1,"redundancy":1,"process":1,"topic":1,"disabled":1,"debian":1,"files":1}
,"fails":{"repeatedly":1,"boot":1,"unused":1}
,"repeatedly":{"booting":1}
,"immediately":{"current":1}
,"relate":{"bootloader":1}
,"slot\u2019s":{"status":1}
,"status":{"attribute":1,"necessarily":1,"slot":1,"root":1,"autosync":1}
,"attribute":{"indicates":1,"managed":1,"handled":1,"switches":1}
,"indicates":{"whether":1,"system":1,"type":1,"bootloader":1}
,"whether":{"rootfs":1}
,"valid":{"system":1,"setting":1}
,"running":{"current":1,"slot":1}
,"bootable":{"unused":1,"status":1,"non-zero":1}
,"older":{"identical":1}
,"identical":{"newer":1}
,"newer":{"version":1}
,"version":{"system":1}
,"managed":{"cboot":1}
,"cboot":{"update":1,"resets":1,"tries":1}
,"engine":{"manages":1}
,"manages":{"updating":1}
,"updating":{"rootfs":1,"jetson":1}
,"mode":{"attribute":1}
,"attempted":{"run":1}
,"ota":{"update":1}
,"specified":{"number":1,"rootfssize":1,"slot":1}
,"times":{"cboot":1,"number":1,"customize":1}
,"resets":{"status":1}
,"switches":{"roles":1}
,"unbootable":{"device":1}
,"tries":{"boot":1,"configurable":1}
,"recovery":{"kernel":1}
,"default":{"cboot":1,"l4t_smd_info.rootfs_ab.cfg":1,"enabled":1,"disabled":1,"active":1,"setting":1,"value":1,"usage":1,"effective":1}
,"three":{"times":1}
,"configurable":{"customize":1}
,"together":{"bootloader":1,"smd":1}
,"switched":{"together":1}
,"boots":{"rootfs":1,"recovery":1}
,"simple":{"flash":1}
,"customizations":{"flashing":1}
,"find":{"layout":1}
,"layout":{"file":1,"l4t":1,"files":1,"jetson":1}
,"examine":{"side":1}
,"side":{"side":1,"corresponding":1}
,"corresponding":{"layout":1,"non-redundant":1}
,"non-redundant":{"system":1,"layout":1}
,"understanding":{"differences":1,"file":1}
,"differences":{"important":1}
,"important":{"understanding":1}
,"xml":{"file":1}
,"describes":{"partition":1}
,"particular":{"layout":1}
,"files":{"describe":1,"redundant":1,"documents":1,"executing":1,"current":1}
,"describe":{"partition":1}
,"platform":{"following":1}
,"list":{"names":1}
,"various":{"platforms":1}
,"platforms":{"case":1}
,"case":{"corresponding":1}
,"without":{"filename":1}
,"filename":{"suffix":1}
,"suffix":{"_rootfs_ab":1,"retry_count":1,"slot":1}
,"t186ref":{"cfg":1}
,"cfg":{"flash_l4t_t194_spi_sd_p3668_rootfs_ab.xml":1,"flash_l4t_t194_spi_emmc_p3668_rootfs_ab.xml":1,"flash_t194_sdmmc_rootfs_ab.xml":1,"flash_l4t_t186_rootfs_ab.xml":1}
,"rootfs_ab":{"flash.sh":1,"enables":1,"highlighted":1}
,"flash.sh":{"options":1,"jetson-tx2-devkit":1}
,"options":{"target_board":1}
,"target_board":{"rootdev":1,"indicates":1}
,"enables":{"rootfs":1,"disables":1,"default":1}
,"jetson-xavier-nx-devkit-emmc":{"jetson-xavier-nx-devkit":1}
,"rootdev":{"specifies":1}
,"specifies":{"location":1}
,"jetson-tx2-devkit":{"mmcblk0p1":1}
,"workflow":{"linux_for_tegra":1}
,"kernel_flash":{"readme.txt":1}
,"size":{"rootfs":1,"specified":1,"jetson":1}
,"half":{"size":1}
,"rootfssize":{"configuration":1,"flash":1,"14gib":1}
,"configuration":{"file":1}
,"change":{"amount":1,"customize":1,"rootfs":1,"line":1,"active":1}
,"amount":{"space":1}
,"allocated":{"root":1}
,"changing":{"value":1}
,"value":{"rootfssize":1,"otherwise":1}
,"example":{"change":1}
,"edit":{"p2771-0000.conf.common":1}
,"emmc_cfg":{"flash_l4t_t186_rootfs_ab.xml":1}
,"holds":{"information":1}
,"smd_b":{"slot":1,"partitions":1}
,"documents":{"refer":1}
,"refer":{"smd":1}
,"keep":{"mind":1}
,"mind":{"read":1}
,"read":{"reame":1}
,"reame":{"files":1}
,"function":{"smd":1}
,"slot_metadata.bin.rootfsab":{"script":1,"host":1}
,"nv_smd_generator":{"generates":1,"x86":1,"config_file":1,"l4t_smd_info.rootfs_ab.cfg":1}
,"generates":{"l4t_smd_info.rootfs_ab.cfg":1}
,"l4t_smd_info.rootfs_ab.cfg":{"file":1,"slot_metadata.bin.rootfsab":1}
,"maximum":{"rootfs":1}
,"retry":{"count":1}
,"please":{"sure":1}
,"sure":{"field":1}
,"field":{"slot":1}
,"info":{"config":1,"order":1}
,"config":{"disable":1,"enable":1}
,"removing":{"comments":1}
,"order":{"important":1}
,"priority":{"suffix":1}
,"retry_count":{"boot_successful":1}
,"autosync":{"rf_autosync_enable":1,"bl_autosync_disable":1,"enabled":1,"bootloader":1}
,"defined":{"rootfs_ab":1}
,"select":{"rootfs":1}
,"auto":{"sync":1}
,"sync":{"disabled":1,"bootloader":1,"enable":1,"change":1,"enables":1}
,"bl_autosync_disable":{"default":1,"highlighted":1,"note":1}
,"redundancy_enable":{"redundancy_user":1}
,"redundancy_user":{"defined":1}
,"max_rootfs_ab_retry_count":{"highlighted":1}
,"highlighted":{"above":1,"makes":1,"enables":1,"disables":1}
,"sets":{"maximum":1}
,"try":{"count":1}
,"count":{"number":1}
,"range":{"default":1}
,"line":{"rootfs_ab":1,"rootfs_active_b":1,"rootfs_bl_unified_ab":1,"bl_autosync_disable":1}
,"rootfs_active_a":{"highlighted":1,"precede":1}
,"makes":{"rootfs":1,"unused":1}
,"rootfs_bl_unified_ab":{"highlighted":1,"default":1,"auto":1,".cfg":1}
,"disables":{"unified":1,"bootloader":1}
,"precede":{"rootfs_bl_unified_ab":1}
,".cfg":{"file":1}
,"note":{"disables":1}
,"modify":{"l4t_smd_info.rootfs_ab.cfg":1}
,"x86":{"host":1}
,"config_file":{"output_file":1,"smd":1}
,"output_file":{"name":1}
,"enabling":{"rootfs":1}
,"managing":{"rootfs":1}
,"nvbootctrl":{"tool":1,"target":1,"rootfs":1,"prints":1,"command":1}
,"help":{"test":1}
,"test":{"develop":1}
,"develop":{"pair":1}
,"pair":{"redundant":1}
,"display":{"status":1}
,"tool\u2019s":{"default":1}
,"usage":{"shown":1}
,"below":{"bootloader":1}
,"shell":{"command":1}
,"runs":{"nvbootctrl":1}
,"either":{"bootloader":1}
,"effective":{"option":1}
,"commands":{"tool":1}
,"prints":{"number":1,"index":1,"suffix":1,"information":1,"status":1,"warning":1}
,"index":{"currently":1}
,"marks":{"current":1,"slot":1}
,"set-active-boot-slot":{"slot":1}
,"causes":{"next":1}
,"load":{"execute":1}
,"set-slot-as-unbootable":{"slot":1}
,"is-slot-bootable":{"slot":1}
,"returns":{"slot":1}
,"non-zero":{"value":1}
,"is-slot-marked-successful":{"slot":1}
,"marked":{"good":1}
,"good":{"non-zero":1}
,"get-suffix":{"slot":1}
,"toggles":{"enablement":1}
,"enablement":{"status":1}
,"fourth":{"combination":1}
,"combination":{"rootfs":1}
,"zero-based":{"slot":1}
,"supported":{"nvbootctrl":1}
,"warning":{"message":1}
,"dump":{"root":1}
,"switch":{"root":1,"active":1}
,"failover":{"rootfs":1}
,"consecutive":{"times":1}
,"vice":{"versa":1}
,"versa":{"tries":1}
,"uuid":{"root":1,"rather":1,"reference":1,"xxxx":1,"used":1,"writing":1,"files":1}
,"always":{"partition":1}
,"identify":{"app":1}
,"form":{"uuid":1}
,"xxxx":{"uuid":1,"partition\u2019s":1}
,"partition\u2019s":{"uuid":1}
,"l4t-rootfs-uuid.txt":{"uuid":1}
,"l4t-rootfs-uuid.txt_b":{"may":1}
,"specify":{"uuid":1}
,"writing":{"uuid":1}
,"over-the-air":{"update":1,"ota":1}
,"image-based":{"over-the-air":1}
,"process":{"updating":1}
,"jetpack":{"debian":1}
,"debian":{"package":1,"packages":1}
,"performing":{"ota":1}
,"recommended":{"systems":1}
,"redundance":{"although":1}
,"although":{"possible":1}
}
;Search.control.loadWordPairs(pairs);
