var pairs =
{
"power":{"management":1,"thermal":1,"gate":1,"state":1,"performance":1,"saving":1,"extend":1,"states":1,"audio":1,"consumption":1,"rails":1,"button":1,"tree":1,"gating":1,"state\u2019s":1,"efficiency":1,"trees":1,"budgets":1,"budget":1,"mode":1,"cycles":1,"dissipating":1,"tdp":1,"clocks":1,"domain":1,"delivery":1,"monitor":1,"milliwatts":1,"monitors":1,"rail":1,"input":1,"critical":1,"enter":1,"modes":1}
,"management":{"jetson":1,"thermal":1,"electrical":1,"features":1,"however":1,"bpmp":1,"firmware":1,"strategy":1,"tuned":1,"cpufreq":1,"cpuidle":1,"integrated":1,"essential":1,"provides":1,"performed":1,"processor":1,"action":1,"uses":1,"clock":1,"requires":1,"linux":1,"using":1,"cooling":1,"reporting":1,"host":1,"becomes":1,"hardware":1}
,"jetson":{"tx2":1,"board":1,"platforms":1,"device":1,"hardware":1,"tx2i":1,"thermal":1}
,"tx2":{"series":1,"name":1,"handled":1,"architecture":1,"uses":1,"bsp":1,"designed":1,"tx2":1,"4gb":1,"thermal":1,"performed":1,"several":1,"replaces":1,"four":1,"ensure":1,"trip":1,"module":1,"tx2i":1,"developer":1,"performance":1}
,"series":{"devices":1,"platforms":1,"modules":1}
,"nvidia":{"jetson":1,"selects":1,"provides":1,"tegra18x-cpuidle":1,"tegra186-cpuidle-denver":1,"soc":1,"follows":1,"icon":1,"socs":1,"icon\u2019s":1}
,"devices":{"nvidia":1,"soc":1,"may":1,"additionally":1,"regulator":1,"system":1,"17000000.gp10b":1,"measure":1,"control":1,"sense":1,"provides":1,"gpu.0":1,"pwm-fan":1,"generic_pwm_tachometer":1}
,"board":{"support":1,"configuration":1,"design":1,"power":1,"3-channel":1,"supply":1,"3.3":1,"1.8":1}
,"support":{"package":1,"firmware":1,"usb":1,"idle":1,"hardware":1}
,"package":{"bsp":1}
,"bsp":{"provide":1,"features":1,"maps":1,"configures":1,"act":1,"new":1,"drivers":1,"implements":1,"software":1,"includes":1,"provides":1,"supports":1,"specific":1,"defines":1,"reads":1,"thermal":1,"sensors":1,"performs":1,"uses":1}
,"provide":{"features":1,"interfaces":1,"optimum":1,"best":1,"accurate":1,"trip":1,"fails":1}
,"features":{"related":1,"deliver":1,"visible":1,"place":1,"bsp":1,"save":1,"implemented":1,"whose":1,"statically":1,"provided":1,"part":1}
,"related":{"power":1,"techniques":1,"frequency":1,"tools":1}
,"thermal":{"management":1,"electrical":1,"throttling":1,"sensor":1,"shutdown":1,"sensors":1,"action":1,"framework":1,"zone":1,"sysfs-api.txt":1,"response":1,"zones":1,"performance":1,"knobs":1,"sensing":1,"cooling":1,"constraints":1,"design":1,"capabilities":1,"events":1,"trip":1,"message":1,"sensor\u2019s":1,"specifications":1,"event":1,"actions":1,"alert":1,"mrq":1,"reset":1}
,"electrical":{"management":1,"problems":1,"limits":1,"thermal":1}
,"deliver":{"best":1,"requested":1}
,"best":{"user":1,"performance":1,"possible":1}
,"user":{"experience":1,"space":1}
,"experience":{"possible":1,"ensures":1,"jetson":1,"device":1,"minimally":1,"similarly":1}
,"possible":{"given":1,"performance":1}
,"given":{"constraints":1,"temperature":1,"group":1,"sensor":1,"trip":1}
,"constraints":{"particular":1,"operational":1,"imposed":1,"device":1}
,"particular":{"platform":1,"sensor":1,"software":1}
,"platform":{"target":1,"initialization":1,"power":1,"ensure":1,"avoids":1,"drivers":1,"driver":1,"bpmp":1,"performance":1}
,"target":{"user":1,"frequency":1,"mode":1}
,"ensures":{"perception":1,"cpu":1}
,"perception":{"device":1}
,"device":{"provides":1,"power":1,"note":1,"tree":1,"trees":1,"drivers":1,"driver":1,"becomes":1,"passive":1,"associated":1,"reduces":1,"essentially":1,"fan":1,"removing":1,"software":1,"performance":1,"within":1,"thermal":1,"pwm-fan":1,"maps":1,"attached":1,"feels":1,"device":1,"heats":1,"sc7":1,"events":1,"operating":1}
,"uniformly":{"high":1}
,"high":{"performance":1,"value":1,"efficiency":1,"temperature":1}
,"excellent":{"battery":1}
,"battery":{"life":1,"supply":1,"controller":1}
,"perfect":{"stability":1}
,"comfortable":{"cool":1}
,"cool":{"touch":1}
,"topic":{"describes":1,"introduces":1,"hardware":1,"clock":1}
,"describes":{"power":1,"bsp":1,"supported":1,"tools":1}
,"visible":{"software":1}
,"software":{"tools":1,"select":1,"actively":1,"initiate":1,"choose":1,"main":1,"support":1,"runtime":1,"clock":1,"shutdown":1,"hardware":1,"throttling":1,"cooling":1,"program":1,"thermal":1,"programmed":1,"trip":1,"becomes":1}
,"tools":{"related":1,"techniques":1}
,"interacting":{"features":1}
,"place":{"dynamic":1}
,"dynamic":{"constraints":1,"voltage":1,"frequency":1}
,"operational":{"settings":1}
,"settings":{"knobs":1,"boot":1,"govern":1,"store":1,"file":1}
,"clock":{"gate":1,"frequencies":1,"voltage":1,"register":1,"tree":1,"framework":1,"domains":1,"source":1,"adjustment":1,"speed":1,"cpu":1,"gating":1,"configuration":1,"settings":1,"throttling":1,"frequency":1,"rates":1,"throttled":1,"capping":1,"information":1}
,"gate":{"settings":1,"regulator":1}
,"regulator":{"enable":1,"framework":1,"consumer":1,"provider":1,"consumers":1,"provide":1,"tolerate":1}
,"enable":{"settings":1,"cpu":1,"appropriate":1,"device":1,"frequency":1}
,"processor":{"power":1,"bpmp":1}
,"state":{"i.e":1,"selected":1,"extraordinarily":1,"range":1,"maintained":1,"via":1,"information":1,"mapping":1,"scy":1,"program":1,"until":1,"idle":1,"restored":1,"during":1,"boot":1,"nodes":1,"node":1,"disabled":1,"core":1,"index":1,"name":1,"disable":1,"cpu":1,"statistics":1,"read":1,"usage":1,"enter":1,"time":1,"consequently":1,"fan":1,"operation":1,"perform":1,"oscillator":1,"sc7":1,"exited":1,"apart":1}
,"i.e":{"idle":1,"vdd_in":1}
,"idle":{"state":1,"display":1,"disabled":1,"power":1,"management":1,"states":1,"task":1,"offline":1,"enable":1,"configuration":1,"device":1,"status":1,"enabled":1}
,"selected":{"cpu":1,"controller":1,"runtime":1,"cpuidle":1}
,"peripheral":{"power":1,"devices":1}
,"chipset":{"power":1}
,"availability":{"cpu":1}
,"cpu":{"cores":1,"adjusts":1,"frequency":1,"thermal":1,"exposes":1,"via":1,"power":1,"dynamic":1,"clock":1,"naflls":1,"voltage":1,"frequencies":1,"core":1,"cluster":1,"idle":1,"complex":1,"cpuidle":1,"core\u2019s":1,"cpu":1,"ids":1,"cpu2":1,"gpu":1,"max":1,"cpu1":1,"cpu3":1,"cpu4":1,"cpu5":1,"cpu0":1,"aux":1,"sensors":1,"sensor":1,"temperatures":1,"cycle":1,"hot":1,"cpux":1,"online":1,"cpufreq":1,"lower":1,"upper":1}
,"knobs":{"constrained":1,"tune":1}
,"constrained":{"feature":1}
,"feature":{"example":1,"requires":1}
,"example":{"cpufreq":1,"prior":1,"vdd_gpu":1,"higher":1,"disable":1,"status":1,"number":1,"entry":1,"thermal":1,"jetson":1,"thermal_zone_cpu":1,"framework":1,"apply":1,"lxde":1}
,"cpufreq":{"implements":1,"therefore":1,"subsystem":1,"governor":1,"platform":1,"graphics":1,"scaling_min_freq":1,"scaling_max_freq":1,"scaling_available_governors":1,"scaling_governor":1,"cpuinfo_min_freq":1,"cpuinfo_max_freq":1,"cpuinfo_cur_freq":1,"scaling_available_frequencies":1}
,"implements":{"load":1,"cpu":1,"emc":1,"feedback":1,"hysteresis":1}
,"load":{"based":1}
,"based":{"scaling":1,"busy":1,"limits":1,"type":1,"current":1,"temperature":1,"proximity":1}
,"scaling":{"based":1,"closely":1,"example":1,"dynamic":1,"idle":1,"dfs":1,"policies":1,"depends":1,"memory":1,"policy":1,"enabled":1}
,"busy":{"cpu":1}
,"adjusts":{"cpu":1}
,"frequency":{"accordingly":1,"cpufreq":1,"proportional":1,"scaling":1,"lock":1,"management":1,"change":1,"mhz":1,"khz":1,"hertz":1,"cpu":1,"voltage":1,"direct":1,"tables":1,"cap":1,"changes":1,"temperature":1,"sensor":1,"governor":1,"governors":1,"settings":1,"value":1,"topic":1,"power":1}
,"accordingly":{"cpu":1}
,"however":{"override":1}
,"override":{"target":1}
,"therefore":{"attempt":1,"frequency-to-temperature":1,"continue":1}
,"attempt":{"debug":1}
,"debug":{"power":1,"cpuidle_a57":1,"cpuidle_denver":1,"tegra_mce":1,"clk":1,"bpmp":1}
,"performance":{"thermal":1,"encompasses":1,"power":1,"modify":1,"reducing":1,"within":1,"cause":1,"user":1,"given":1,"triggering":1,"measuring":1,"manage":1,"setting":1,"fan":1}
,"problems":{"familiarize":1}
,"familiarize":{"yourself":1}
,"yourself":{"power":1}
,"kernel":{"space":1,"support":1,"driver":1,"kernel-4.9":1,"configuration":1,"debug":1,"requested":1,"nvpmodel_emc_cap":1,"monitors":1,"software":1,"bpmp":1,"provided":1,"tegra_bpmp_thermal":1}
,"space":{"power":1,"command":1,"kernel":1,"interfaces":1}
,"saving":{"features":1,"feature":1}
,"section":{"describes":1,"voltage":1,"static":1}
,"save":{"power":1,"state":1}
,"extend":{"battery":1}
,"life":{"features":1}
,"implemented":{"linux":1}
,"linux":{"kernel":1,"power":1,"runlevel":1,"support":1,"common":1,"regulator":1,"device":1,"cpufreq":1,"cpuidle":1,"thermal":1}
,"firmware":{"hardware":1,"power":1,"running":1,"configured":1,"described":1,"hosts":1,"provides":1,"falls":1,"refers":1,"programs":1,"supports":1,"thermal":1}
,"hardware":{"without":1,"wake":1,"power":1,"reference":1,"assistance":1,"clock":1,"thermal":1,"throttling":1,"shutdown":1,"software":1,"bsp":1,"reset":1,"blocks":1,"handles":1,"worst-case":1,"setup":1}
,"without":{"significant":1,"knowledge":1,"thermal_zone":1,"side":1,"shutting":1,"overheating":1}
,"significant":{"involvement":1,"clock":1}
,"involvement":{"user":1}
,"supported":{"power":1,"denver":1,"modes":1}
,"states":{"listed":1,"devices":1,"onto":1,"follows":1,"core":1,"cpu":1,"applicable":1,"extending":1,"available":1,"denoted":1,"cluster":1,"ccplex":1,"enabled":1,"denver":1,"translate":1}
,"listed":{"order":1}
,"order":{"increasing":1}
,"increasing":{"flexibility":1}
,"flexibility":{"configurability":1}
,"deep":{"sleep":1}
,"sleep":{"sc7":1,"software":1,"enters":1,"user":1,"preferred":1,"common":1,"supply":1}
,"sc7":{"offers":1,"state":1,"restarted":1,"rail":1}
,"offers":{"small":1}
,"small":{"amount":1}
,"amount":{"configurability":1,"state":1,"current":1,"ripple":1}
,"configurability":{"example":1}
,"prior":{"entering":1}
,"entering":{"deep":1,"low":1,"sc7":1}
,"select":{"hardware":1,"subject":1,"cpu":1}
,"wake":{"events":1,"chip":1,"sources":1,"source":1,"lan":1}
,"events":{"wake":1,"temperature":1,"alarms":1,"rare":1,"detect":1,"change":1,"described":1,"transient":1,"notified":1}
,"chip":{"deep":1,"dedicated":1,"unavailable":1,"logically":1}
,"active":{"state":1,"power":1,"core":1,"cores":1,"passive":1,"cooling":1}
,"extraordinarily":{"flexible":1}
,"flexible":{"terms":1}
,"terms":{"power":1,"accuracy":1}
,"encompasses":{"activity":1}
,"activity":{"levels":1}
,"levels":{"low":1,"bsp":1,"sc7":1,"light":1}
,"low":{"power":1,"power-state":1,"trips":1}
,"audio":{"playback":1}
,"playback":{"peak":1}
,"peak":{"performance":1,"current":1}
,"consumption":{"active":1,"helps":1,"maximizing":1,"firmware":1,"modeling":1,"exceeds":1}
,"range":{"tens":1,"191":1,"0,255":1}
,"tens":{"milliwatts":1}
,"milliwatts":{"several":1}
,"several":{"watts":1,"useful":1,"configurations":1,"thermal":1,"types":1,"drivers":1,"cooling":1,"software":1,"trip":1}
,"none":{"power":1}
,"rails":{"supplying":1,"powered":1,"including":1,"vdd_core":1,"power":1}
,"supplying":{"soc":1}
,"soc":{"dram":1,"maintains":1,"devices":1,"core":1,"chipsets":1,"clocks":1,"several":1,"platforms":1,"enters":1,"exits":1,"thermal":1,"asserts":1,"power":1}
,"dram":{"powered":1,"power":1,"maintains":1,"rails":1,"critical":1}
,"maintained":{"soc":1}
,"via":{"cold":1,"pre-defined":1,"linux":1,"bpmp":1,"fan":1,"software":1,"oil":1,"nvpmodel":1}
,"cold":{"boot":1}
,"vdd_rtc":{"vddio_ddr":1}
,"vddio_ddr":{"vddio_sys":1}
,"vddio_sys":{"dram":1,"vdd_core":1}
,"powered":{"vdd_core":1,"power":1,"companion":1}
,"vdd_core":{"vdd_cpu":1,"dram":1}
,"vdd_cpu":{"powered":1,"may":1,"vdd_sram":1}
,"maintains":{"small":1,"state":1,"linux":1,"list":1}
,"information":{"pmc":1,"new":1,"linux":1,"nvpmodel":1,"thermal":1,"fan":1,"aotag":1,"read":1,"cpu":1}
,"pmc":{"block":1}
,"block":{"dram":1}
,"pre-defined":{"wake":1,"nvidia":1}
,"including":{"vdd_cpu":1}
,"may":{"powered":1,"idle":1,"power-gated":1,"present":1,"due":1,"result":1,"reduce":1,"following":1}
,"actively":{"manages":1,"manage":1}
,"manages":{"power":1}
,"initiate":{"transition":1,"deep":1}
,"transition":{"active":1}
,"mapping":{"linux":1,"various":1}
,"maps":{"hardware":1,"pwm":1}
,"onto":{"linux":1}
,"suspend":{"ram":1}
,"choose":{"whether":1}
,"whether":{"enter":1,"cpu":1}
,"enter":{"deep":1,"commands":1,"command":1,"specified":1}
,"enters":{"suspend":1,"sc7":1}
,"running":{"idle":1,"systemd":1,"bpmp":1,"host":1,"cpus":1,"therefore":1}
,"disabled":{"driver":1,"enabled":1,"enables":1}
,"driver":{"control":1,"cpu":1,"provides":1,"called":1,"reconciles":1,"plugs":1,"on-board":1,"module":1,"linux":1,"walks":1,"uses":1,"receives":1,"firmware":1,"may":1}
,"control":{"example":1,"bpmp":1,"temperature":1,"system":1,"loop":1,"throttling":1,"programming":1,"change":1,"during":1,"loop\u2019s":1,"heat":1}
,"vdd_gpu":{"may":1,"direct":1}
,"companion":{"gpu":1}
,"gpu":{"may":1,"frequencies":1,"max":1,"clock":1,"emmc":1,"emc":1,"balanced":1,"sensor":1,"temperatures":1,"clocks":1,"drawing":1,"power":1,"hardware":1,"frequency":1,"lower":1,"upper":1}
,"name":{"chipset":1,"core":1,"maxp_core_all":1,"shown":1,"voltage":1,"schematic":1,"i.e":1,"sys":1,"name":1,"governor":1}
,"scy":{"instead":1}
,"instead":{"lpx":1,"gpu":1}
,"command":{"systemd":1,"displays":1,"cmd_thermal_host_trip_reached":1,"turn":1,"cpu":1,"line":1}
,"systemd":{"init":1,"maintains":1}
,"init":{"system":1}
,"sudo":{"systemctl":1,"bash":1,"etherwake":1,"usr":1}
,"systemctl":{"suspend":1}
,"bash":{"echo":1}
,"echo":{"mem":1,"date":1,"sys":1,"current_in_ma":1,"name":1,"cpu_freq":1,"gpu_freq":1,"emc_freq":1,"pwm_duty_cycle":1}
,"mem":{"sys":1}
,"sys":{"power":1,"class":1,"devices":1,"kernel":1,"bus":1}
,"first":{"method":1,"line":1}
,"method":{"entering":1,"system":1}
,"preferred":{"cooperates":1}
,"cooperates":{"better":1}
,"better":{"systemd":1}
,"runlevel":{"second":1}
,"second":{"method":1}
,"system":{"running":1,"awakened":1,"cpu":1,"stability":1,"keeps":1,"tuning":1,"thermal":1,"save":1,"host":1,"low":1,"includes":1,"software":1,"power":1,"clock":1,"input":1,"throttled":1,"thermally":1}
,"awakened":{"deep":1}
,"common":{"wake":1,"clock":1,"loads":1}
,"sources":{"available":1}
,"available":{"jetson":1,"connect":1,"cpu":1}
,"press":{"release":1,"key":1}
,"release":{"power":1,"32.4":1}
,"button":{"jetson":1,"available":1,"pin":1}
,"connect":{"disconnect":1,"governors":1}
,"disconnect":{"power":1,"micro-usb":1}
,"pin":{"ground":1,"pmic":1}
,"rtc":{"alarm":1,"rtc0":1}
,"program":{"rtc":1,"static":1,"bpmp":1}
,"alarm":{"command":1}
,"date":{"seconds":1}
,"seconds":{"sys":1}
,"class":{"rtc":1}
,"rtc0":{"wakealarm":1}
,"micro":{"usb":1}
,"usb":{"cable":1,"micro-b":1,"remote":1,"keyboard":1,"mouse":1,"hdmi":1}
,"cable":{"hotplug":1,"usb":1}
,"micro-usb":{"cable":1}
,"micro-b":{"port":1}
,"port":{"flashing":1}
,"flashing":{"device":1}
,"remote":{"wakeup":1,"sensor":1,"diode":1}
,"key":{"usb":1,"connector":1}
,"keyboard":{"connected":1}
,"connected":{"device":1,"rail":1}
,"note":{"linux":1}
,"mouse":{"wake":1}
,"machine":{"lan":1}
,"lan":{"enter":1}
,"etherwake":{"interface":1}
,"interface":{"mac_address_of_target":1,"abi":1}
,"card":{"detection":1}
,"insert":{"remove":1}
,"remove":{"card":1,"disable":1}
,"voltage":{"management":1,"dynamic":1,"scaling":1,"current":1,"appropriate":1,"regulators":1,"rail":1,"reduces":1,"additionally":1,"pllx":1,"guaranteed":1,"levels":1,"drop":1,"millivolts":1,"drops":1}
,"proportional":{"voltage":1,"integral":1}
,"closely":{"related":1}
,"higher":{"frequencies":1,"voltages":1,"rpm":1,"temperature":1,"cooling":1,"frequency":1}
,"frequencies":{"require":1,"numbers":1,"pre-qualified":1,"select":1,"thereby":1,"optimized":1,"report":1,"cpu":1,"temperatures":1}
,"require":{"higher":1,"minimum":1}
,"voltages":{"vice":1,"rails":1}
,"vice":{"versa":1}
,"register":{"manipulation":1,"boot":1,"thermal":1,"trips":1}
,"manipulation":{"jetson":1}
,"handled":{"boot":1,"framework":1}
,"boot":{"power":1,"time":1,"read":1,"according":1,"configuration":1,"offset":1,"calibrates":1}
,"bpmp":{"firmware":1,"linux":1,"device":1,"ensures":1,"1088":1,"819.2":1,"monitors":1,"sensors":1,"sensor":1,"thermal":1,"jetson":1,"modules":1,"owned":1,"debug":1}
,"exposes":{"somewhat":1}
,"somewhat":{"simplified":1}
,"simplified":{"view":1}
,"view":{"physical":1}
,"physical":{"clock":1,"damage":1}
,"tree":{"software":1,"topology":1,"driver":1,"appropriately":1,"configured":1,"board":1,"blob":1,"node":1,"enable":1,"tegra186-denver-cpuidle.dtsi":1,"file":1,"define":1,"programs":1,"binary":1,"bindings":1}
,"main":{"cpu":1,"module":1}
,"domains":{"chip":1}
,"dedicated":{"clock":1}
,"source":{"known":1}
,"known":{"noise":1,"advance":1}
,"noise":{"aware":1}
,"aware":{"frequency":1}
,"lock":{"loop":1}
,"loop":{"nafll":1,"linux":1,"similarly":1}
,"framework":{"provides":1,"connect":1,"enable":1,"thermal":1,"maintains":1,"examines":1,"ensure":1,"sends":1,"implements":1,"sets":1}
,"provides":{"abstraction":1,"mechanism":1,"regulators":1,"soc-specific":1,"following":1,"generic":1,"knobs":1,"several":1,"example":1,"different":1,"simple":1,"thermal":1,"active":1,"aotag":1,"jetson_clocks.sh":1,"power-related":1}
,"abstraction":{"allows":1}
,"allows":{"regulator":1,"several":1,"operating":1,"continuous":1}
,"consumer":{"drivers":1,"apis":1}
,"drivers":{"dynamically":1,"within":1,"peripheral":1,"registering":1,"implement":1,"cpufreq":1,"usb":1,"provide":1,"on-die":1,"linux":1,"ina3221x":1}
,"dynamically":{"adjust":1,"imposed":1}
,"adjust":{"voltage":1}
,"current":{"regulators":1,"power":1,"temperature":1,"trip":1,"trips":1,"battery":1,"regulator":1,"inductor":1,"consumption":1,"voltage":1,"milliamperes":1,"limit":1,"0x41power":1,"3.6":1,"monitor":1,"frequency":1,"clock":1,"settings":1,"mode":1,"increases":1}
,"regulators":{"runtime":1,"node":1,"power":1,"supply":1}
,"runtime":{"without":1,"features":1}
,"knowledge":{"underlying":1}
,"underlying":{"hardware":1}
,"mechanism":{"platform":1}
,"initialization":{"code":1}
,"code":{"declare":1,"snippet":1}
,"declare":{"power":1}
,"topology":{"assign":1}
,"assign":{"driver":1,"custom":1}
,"node":{"hardware":1,"enabling":1,"cpuidle":1,"device":1,"status":1,"type":1,"value":1}
,"called":{"regulator":1,"critical":1}
,"provider":{"driver":1}
,"configures":{"platform":1,"sensors":1}
,"appropriately":{"soc":1}
,"additionally":{"drivers":1,"bsp":1,"sensors":1,"monitor":1,"framework":1,"nvidia":1}
,"within":{"bsp":1,"safe":1,"thermal":1,"recommended":1,"gpu":1}
,"act":{"regulator":1}
,"consumers":{"appropriate":1,"cause":1}
,"porting":{"bsp":1}
,"new":{"platform":1,"printed":1,"cooling":1}
,"configured":{"match":1,"via":1,"avfs":1,"trigger":1}
,"match":{"underlying":1}
,"apis":{"correctly":1}
,"configuration":{"file":1,"option":1,"table":1,"jetson":1}
,"file":{"information":1,"option":1,"restore":1,"default":1,"l4t_dfs.conf":1}
,"avoids":{"conflicts":1}
,"conflicts":{"functions":1}
,"functions":{"using":1}
,"using":{"pads":1,"device":1,"cpu-balanced":1,"application":1,"fan":1,"thermal":1,"callback":1,"performance":1,"battery":1,"sysfs":1}
,"pads":{"bsp":1,"chip":1}
,"registering":{"regulator":1}
,"cause":{"pads":1,"resets":1}
,"unavailable":{"functions":1}
,"core":{"power":1,"management":1,"framework":1,"cpuidle":1,"idle":1,"task":1,"low-power":1,"stays":1,"cpu":1,"cluster":1,"state":1,"states":1,"powergate":1,"ids":1,"read":1,"command":1,"enter":1,"actually":1,"spent":1,"entered":1,"settings":1,"number":1,"replace":1}
,"vdd_sram":{"vdd_gpu":1}
,"direct":{"control":1,"support":1,"impact":1}
,"blob":{"distinct":1}
,"distinct":{"linux":1}
,"strategy":{"includes":1}
,"includes":{"dynamic":1,"non-cpu":1,"drivers":1,"several":1,"driver":1,"current":1,"limitations":1}
,"tuned":{"jetson":1,"provide":1}
,"dfs":{"linux":1}
,"subsystem":{"cpufreq":1,"comprises":1}
,"implement":{"clock":1,"frequency":1}
,"adjustment":{"mechanism":1}
,"governors":{"implement":1,"platform":1,"bsp":1}
,"policy":{"frequency":1,"runtime":1}
,"depends":{"cpufreq":1}
,"governor":{"selected":1,"tunes":1,"requests":1,"core":1,"implements":1,"picks":1,"uses":1,"progressively":1,"schedutil":1}
,"details":{"information":1,"section":1}
,"top":{"kernel":1,"bar":1}
,"kernel-4.9":{"documentation":1}
,"documentation":{"cpu-freq":1,"cpuidle":1,"thermal":1,"devicetree":1}
,"reference":{"design":1}
,"design":{"nvidia":1,"emc":1,"power":1,"considerations":1,"limits":1}
,"selects":{"cpufreq":1}
,"tunes":{"achieve":1}
,"achieve":{"balance":1}
,"balance":{"power":1}
,"requests":{"cpu":1,"made":1,"mrqs":1,"handled":1}
,"change":{"soc-specific":1,"status":1,"power":1,"mode":1,"speed":1,"framework":1,"throttle":1,"cpu":1,"gpu":1,"emc":1}
,"soc-specific":{"cpufreq":1,"idle":1,"cpuidle":1}
,"reconciles":{"request":1}
,"request":{"constraints":1}
,"imposed":{"thermal":1}
,"limits":{"updates":1,"dynamically":1,"perform":1,"device":1,"software":1,"table":1,"events":1,"overcurrent":1}
,"updates":{"cpu":1}
,"uses":{"nafll":1,"trip":1,"temperature":1,"following":1,"fan":1,"current":1,"control":1,"fuses":1}
,"nafll":{"clock":1,"deliver":1}
,"naflls":{"configured":1}
,"avfs":{"hardware":1}
,"assistance":{"bpmp":1}
,"appropriate":{"nafll":1,"kernel":1,"device":1,"core":1,"node":1}
,"requested":{"cpu":1,"specified":1}
,"cpuidle":{"infrastructure":1,"lacks":1,"driver":1,"framework":1,"governor":1,"boot":1,"current_driver":1,"state":1,"state0":1,"state1":1}
,"infrastructure":{"supports":1}
,"supports":{"implementation":1,"two":1,"software":1,"fan":1,"capping":1}
,"implementation":{"soc-specific":1}
,"lacks":{"direct":1}
,"applicable":{"entire":1}
,"entire":{"cpu":1}
,"cluster":{"idle":1,"low-power":1,"ccplex":1,"state":1,"power":1,"rail":1,"states":1,"read":1,"enter":1,"gpu":1,"grouped":1}
,"extending":{"beyond":1}
,"beyond":{"cpu":1,"critical":1}
,"plugs":{"cpuidle":1}
,"task":{"scheduled":1,"places":1,"puts":1}
,"scheduled":{"runnable":1}
,"runnable":{"tasks":1}
,"tasks":{"left":1}
,"left":{"run":1}
,"run":{"queue":1,"script":1,"tegrastats":1}
,"queue":{"core":1}
,"places":{"core":1}
,"low-power":{"state":1}
,"stays":{"state":1,"mode":1}
,"until":{"interrupt":1,"change":1,"higher":1,"temperature":1}
,"interrupt":{"wakes":1}
,"wakes":{"process":1}
,"process":{"work":1}
,"last":{"active":1}
,"offline":{"state":1}
,"puts":{"entire":1}
,"table":{"below":1,"bct":1,"specific":1,"included":1,"identifies":1,"bsp":1,"thermal":1,"shows":1,"describes":1}
,"below":{"summarizes":1,"54c":1,"limit":1,"accuracy":1,"safe":1}
,"summarizes":{"different":1}
,"different":{"cpu":1,"governors":1,"different":1,"desktop":1}
,"ccplex":{"cpu":1,"state":1,"states":1}
,"complex":{"idle":1}
,"type":{"state":1,"cores":1,"critical":1,"passive":1,"cooling":1,"trip":1}
,"virtual":{"retention":1,"core":1,"object":1}
,"retention":{"power":1}
,"gating":{"architecture":1,"includes":1}
,"architecture":{"state":1}
,"restored":{"mts":1}
,"denver":{"cores":1,"core":1,"cluster":1,"cpu":1}
,"auto":{"clock":1}
,"non-cpu":{"logic":1}
,"rail":{"gating":1,"powers":1,"dependencies":1,"power-gated":1,"powering":1,"name":1,"current":1,"voltage":1,"power":1,"critical":1,"names":1,"overcurrent":1}
,"emc":{"reduction":1,"frequency":1,"dram":1,"dvfs":1,"clock":1,"frequencies":1,"clocks":1,"lower":1,"min_rate":1,"max_rate":1,"rate":1,"upper":1,"mrq_rate_locked":1,"state":1,"minimum":1}
,"reduction":{"state":1,"frequency":1}
,"during":{"cc3":1,"sc7":1,"various":1,"boot":1,"minimum":1}
,"denoted":{"states":1,"ccx":1,"ccpx":1}
,"ccx":{"states":1}
,"ccpx":{"states":1}
,"option":{"appropriate":1}
,"enabling":{"either":1}
,"either":{"alone":1,"following":1,"linux":1}
,"alone":{"effective":1}
,"compatible":{"nvidia":1}
,"status":{"okay":1,"state":1,"core":1,"write":1,"disables":1,"cluster":1}
,"disable":{"cpuidle":1,"device":1,"core":1,"appropriate":1,"power":1,"frequency":1}
,"display":{"cpu":1,"name":1,"810":1,"1620":1,"current":1,"provides":1}
,"determine":{"whether":1}
,"enabled":{"enter":1,"command":1,"reverse":1,"cluster":1,"boot":1,"default":1}
,"cat":{"sys":1}
,"following":{"procedures":1,"several":1,"device":1,"factors":1,"capabilities":1,"table":1,"components":1,"code":1,"paragraphs":1,"thermal":1,"balanced":1,"modes":1}
,"procedures":{"procedures":1,"apply":1,"manage":1,"frequencies":1,"cpu":1}
,"apply":{"device":1,"command":1}
,"modify":{"appropriate":1,"provided":1,"ina":1}
,"nodes":{"setting":1,"represent":1,"following":1,"modify":1,"read":1}
,"setting":{"property":1,"core":1,"results":1,"frequencies":1,"static":1}
,"property":{"min-residency-us":1}
,"min-residency-us":{"high":1,"0xffffffff":1}
,"value":{"e.g":1,"returned":1,"modifying":1,"available":1,"emc":1,"range":1}
,"e.g":{"0xffffffff":1}
,"state-name":{"virtual":1}
,"wakeup-latency-us":{"190":1}
,"pmstate":{"0x6":1}
,"arm":{"psci-suspend-param":1}
,"psci-suspend-param":{"0x6":1}
,"core\u2019s":{"power":1}
,"pathnames":{"nodes":1}
,"represent":{"core":1,"denver":1,"a57":1}
,"ids":{"represent":1,"valid":1,"denver":1,"a57":1}
,"a57":{"cores":1,"core":1,"cpu":1,"cluster":1}
,"index":{"core":1,"enter":1}
,"state\u2019s":{"status":1}
,"reverse":{"usual":1}
,"usual":{"boolean":1}
,"boolean":{"sense":1}
,"read":{"appropriate":1,"node":1,"following":1,"using":1,"rail":1,"ina3221":1,"vdd_in":1}
,"write":{"ascii":1}
,"ascii":{"node":1}
,"useful":{"commands":1}
,"commands":{"getting":1}
,"getting":{"setting":1}
,"state0":{"name":1}
,"state1":{"name":1,"usage":1,"time":1}
,"remember":{"status":1}
,"disables":{"core":1}
,"cores":{"cluster":1,"read":1,"online":1}
,"cpuidle_a57":{"deepest_cc_state":1}
,"cpuidle_denver":{"deepest_cc_state":1}
,"cc1":{"enabled":1,"cc6":1}
,"cc6":{"enabled":1,"cc7":1}
,"cc7":{"enabled":1}
,"per-core":{"state":1}
,"number":{"times":1,"field":1,"0-2":1,"example":1}
,"times":{"kernel":1,"specified":1,"denver":1}
,"specified":{"core":1,"state":1,"thermal":1}
,"actually":{"entered":1}
,"entered":{"specified":1,"state":1}
,"tegra_mce":{"cstats":1}
,"total":{"time":1}
,"time":{"microseconds":1}
,"microseconds":{"specified":1,"denver":1}
,"spent":{"specified":1,"state":1}
,"cpu2":{"cpuidle":1,"online":1}
,"memory":{"power":1,"controller":1,"bandwidth":1,"cpu":1,"max":1}
,"chipsets":{"include":1}
,"include":{"power":1,"bct":1}
,"whose":{"operation":1,"temperature":1,"frequency":1,"information":1}
,"operation":{"largely":1,"during":1,"cooling":1}
,"largely":{"invisible":1}
,"invisible":{"software":1}
,"statically":{"enabled":1}
,"according":{"settings":1}
,"controller":{"emc":1,"passive":1,"shut":1}
,"critical":{"power":1,"triggers":1,"trip":1,"current":1,"limit":1}
,"requires":{"tuning":1,"form":1}
,"tuning":{"characterization":1,"thermal":1,"limited":1,"cannot":1}
,"characterization":{"new":1}
,"printed":{"circuit":1}
,"circuit":{"board":1,"pmic":1}
,"calibration":{"results":1,"complete":1}
,"results":{"include":1,"higher":1,"bad":1,"large":1}
,"bct":{"emc":1}
,"dvfs":{"table":1,"capabilities":1}
,"specific":{"board":1,"thermal":1}
,"included":{"platform":1}
,"factors":{"affect":1}
,"affect":{"emc":1}
,"entries":{"emc":1,"device":1}
,"average":{"memory":1,"cpu":1,"instantaneous":1}
,"bandwidth":{"used":1}
,"used":{"measured":1}
,"measured":{"hardware":1,"frequency":1,"tachometer":1}
,"made":{"various":1}
,"various":{"device":1,"clocks":1,"power":1,"ramp":1,"bpmp":1,"throttle":1}
,"graphics":{"drivers":1}
,"hdmi":{"display":1}
,"modes":{"power":1,"operation":1}
,"designed":{"high":1,"power":1}
,"efficiency":{"power":1,"supports":1,"7.5":1,"speed":1}
,"integrated":{"circuit":1,"circuits":1}
,"pmic":{"voltage":1,"hardware":1}
,"trees":{"optimize":1}
,"optimize":{"power":1}
,"two":{"optimized":1,"types":1,"software":1}
,"optimized":{"power":1,"provide":1,"limiting":1}
,"max\u2011q":{"maximizing":1}
,"maximizing":{"power":1,"performance":1,"jetson":1}
,"7.5":{"watts":1}
,"watts":{"jetson":1,"watts":1,"respectively":1}
,"4gb":{"watts":1,"trip":1,"modules":1}
,"max-p":{"balancing":1,"mode":1,"watts":1}
,"balancing":{"power":1}
,"speed":{"watts":1,"control":1,"fan":1,"default":1,"limit":1,"manually":1,"measured":1}
,"budget":{"allows":1}
,"configurations":{"different":1,"pre-defined":1}
,"numbers":{"cores":1}
,"capping":{"memory":1,"cpu":1,"prevents":1}
,"pre-qualified":{"level":1}
,"level":{"confines":1,"input":1}
,"confines":{"module":1}
,"module":{"target":1,"stays":1,"soc":1,"registers":1,"power":1,"three-channel":1,"current":1}
,"mode":{"configurations":1,"max-p":1,"i.e":1,"module":1,"until":1,"persists":1,"displayed":1,"definition":1,"unique":1,"increase":1,"mode1sw":1,"click":1,"open":1,"want":1,"menu":1}
,"nvpmodel":{"clock":1,"gui":1,"window\u2019s":1,"command":1}
,"online":{"a57":1,"d15":1,"cpu":1}
,"d15":{"cpu":1}
,"max":{"frequency":1}
,"clocks":{"max":1,"system":1,"reduce":1,"reduction":1,"remedy":1,"frequencies":1,"part":1,"potentially":1,"maintain":1,"handle":1,"three":1,"script":1}
,"adsp":{"300":1,"951.9":1,"600":1}
,"ape":{"150":1,"158.6":1,"408":1}
,"axi_cbb":{"409.6":1,"499.2":1,"408":1}
,"bpmp_apb":{"408":1}
,"host1x":{"408":1,"496.9":1}
,"isp":{"1126.4":1,"857.6":1}
,"display_hub":{"652.8":1,"508.8":1}
,"nvcsi":{"225":1}
,"nvdec":{"1203.2":1,"908.8":1}
,"nvenc":{"1164.8":1,"883.2":1}
,"nvjpg":{"857.6":1,"646.4":1}
,"sce":{"960":1,"729.6":1}
,"tsec":{"716.8":1,"569.6":1}
,"vic":{"1024":1,"780.8":1,"frequency":1}
,"default":{"mode":1,"cpu":1,"file":1,"prefer":1}
,"tx2i":{"power":1,"ucm1":1,"ucm2":1,"trip":1,"tx2":1,"channel":1}
,"budgets":{"max-q":1}
,"max-q":{"max-p":1}
,"ucm1":{"profile":1}
,"ucm2":{"profile":1}
,"usr":{"sbin":1,"bin":1}
,"sbin":{"nvpmodel":1}
,"alternatively":{"nvpmodel":1,"mode":1}
,"gui":{"front":1,"later":1,"applet":1,"gui":1,"represented":1,"displays":1,"different":1}
,"front":{"end":1}
,"end":{"information":1,"nvpmodel":1}
,"later":{"topic":1}
,"once":{"power":1,"calibration":1}
,"persists":{"across":1}
,"across":{"power":1}
,"cycles":{"sc7":1}
,"displayed":{"right":1,"next":1}
,"right":{"nvidia":1,"sensors":1,"side":1}
,"icon":{"nvpmodel":1,"right":1,"illustration":1,"open":1,"click":1}
,"window\u2019s":{"menu":1}
,"menu":{"bar":1,"icon":1,"item":1}
,"bar":{"information":1}
,"learn":{"options":1}
,"define":{"custom":1,"sensors":1,"special":1}
,"custom":{"power":1,"mode":1}
,"add":{"mode":1}
,"definition":{"file":1}
,"entry":{"mode":1}
,"power_model":{"name":1}
,"cpu1":{"online":1,"cpufreq":1}
,"cpu3":{"online":1}
,"cpu4":{"online":1}
,"cpu5":{"online":1}
,"cpu0":{"cpufreq":1}
,"scaling_max_freq":{"1400000":1}
,"17000000.gp10b":{"devfreq":1,"min_freq":1,"max_freq":1,"enable_3d_scaling":1,"cur_freq":1,"available_frequencies":1}
,"devfreq":{"17000000.gp10b":1}
,"max_freq":{"1120000000":1}
,"nvpmodel_emc_cap":{"emc_iso_cap":1}
,"emc_iso_cap":{"1600000000":1}
,"unit":{"measure":1,"gpu":1}
,"measure":{"cpu":1,"temperature":1,"temperatures":1}
,"khz":{"unit":1}
,"emmc":{"frequency":1}
,"hertz":{"assign":1}
,"unique":{"number":1}
,"field":{"test":1}
,"test":{"case":1}
,"case":{"determine":1}
,"subject":{"edp":1}
,"edp":{"limit":1}
,"limit":{"defined":1,"orderly":1,"milliamperes":1,"enter":1,"nvpmodel":1,"heat":1}
,"defined":{"mode":1}
,"essential":{"system":1}
,"stability":{"quality":1}
,"quality":{"user":1}
,"sensing":{"on-board":1,"linux":1,"temperature":1,"sensors":1}
,"on-board":{"on-die":1,"thermal":1,"temperature":1,"sensor":1}
,"on-die":{"thermal":1,"on-board":1}
,"sensor":{"temperature":1,"clock":1,"thermal":1,"controlled":1,"devices":1,"gated":1,"stopped":1,"accounts":1,"hardware":1,"driver":1,"device":1,"exposed":1,"specified":1,"crosses":1,"input":1,"configured":1,"fixed":1,"once":1,"reports":1,"groups":1,"host":1,"power-gated":1,"entering":1,"measuring":1,"jetson":1,"always-on":1,"operates":1,"aotag":1,"generate":1,"ideal":1,"soc_therm":1,"gpu":1,"includes":1,"present":1}
,"temperature":{"reporting":1,"devices":1,"central":1,"monitored":1,"sensor":1,"limits":1,"thermal_zone_cpu":1,"101000":1,"95500":1,"sensors":1,"millidegrees":1,"perform":1,"power":1,"reducing":1,"governor":1,"sensing":1,"remote":1,"die":1,"board":1,"range":1,"threshold":1,"comes":1,"bsp":1,"increases":1,"reached":1,"crosses":1,"frequency":1,"rates":1,"convert":1,"oscillating":1,"known":1,"degrees":1,"given":1,"current":1,"measurements":1,"reports":1,"sc7":1,"readings":1,"measurement":1,"reaches":1,"drops":1,"rises":1,"dropped":1,"spikes":1,"ongoing":1,"table":1}
,"cooldown":{"removing":1,"supports":1,"software":1,"fan":1}
,"removing":{"heat":1,"thermal":1}
,"heat":{"via":1,"dissipation":1,"generation":1}
,"fan":{"controlling":1,"clock":1,"reduces":1,"management":1,"control":1,"speed":1,"smoothly":1,"cooling":1,"results":1,"produces":1,"first":1}
,"controlling":{"heat":1}
,"slowdown":{"hardware":1}
,"shutdown:for":{"orderly":1}
,"orderly":{"software":1,"shutdown":1}
,"shutdown":{"hardware":1,"cooling":1,"special":1,"thermal":1,"occurs":1,"failed":1,"limits":1,"mechanism":1,"physical":1}
,"previously":{"jetson":1}
,"performed":{"software":1,"using":1,"soctherm":1}
,"monitors":{"on-board":1,"on-die":1,"temperature":1,"i2c":1}
,"sensors":{"performs":1,"monitor":1,"die":1,"support":1,"follows":1,"operate":1,"generate":1,"allow":1,"except":1,"without":1,"programmable":1,"temperature":1,"sensor":1,"chip":1,"a57":1,"represented":1,"group":1,"report":1,"capable":1,"require":1,"cannot":1,"stop":1,"restarted":1,"invalidate":1,"measuring":1,"thermal":1,"receive":1}
,"performs":{"cooldown":1,"slowdown":1,"thermal":1}
,"identifies":{"thermal":1,"temperature":1}
,"action":{"associated":1}
,"associated":{"module":1,"certain":1}
,"soctherm.c":{"aotag.c":1}
,"generic":{"user":1}
,"interfaces":{"working":1,"components":1}
,"working":{"devices":1}
,"central":{"component":1}
,"component":{"framework":1}
,"zone":{"virtual":1,"acts":1,"nvidia":1,"using":1,"provides":1,"bsp":1,"jetson":1,"monitors":1,"responsible":1,"uses":1,"trip":1,"based":1,"driver":1,"users":1}
,"object":{"represents":1,"following":1}
,"represents":{"area":1}
,"area":{"die":1}
,"die":{"whose":1,"board":1,"near":1,"within":1}
,"monitored":{"controlled":1}
,"controlled":{"thermal":1,"either":1}
,"acts":{"object":1}
,"cooling":{"device":1,"actions":1,"trigger":1,"map":1,"devices":1,"strategies":1,"fan":1,"state":1,"throttling":1,"achieved":1,"states":1,"setting":1,"bsp":1,"action":1}
,"trip":{"points":1,"point":1,"thermal-zones":1,"allocated":1,"program":1,"message":1,"temperatures":1,"management":1,"host":1,"crossed":1,"temperature":1}
,"introduces":{"components":1}
,"components":{"demonstrates":1,"avoid":1}
,"demonstrates":{"form":1}
,"form":{"thermal":1,"feedback":1}
,"configuring":{"thermal":1}
,"tune":{"thermal":1}
,"response":{"zone":1}
,"zones":{"tuned":1,"editing":1,"trip":1,"zones":1,"guarantee":1,"bpmp":1,"mapped":1,"define":1,"without":1,"identified":1,"registered":1}
,"optimum":{"thermal":1}
,"provided":{"thermal":1,"bsp":1,"part":1}
,"editing":{"entries":1}
,"monitor":{"temperature":1,"temperatures":1,"two":1,"whose":1,"topic":1}
,"perform":{"cooling":1,"thermal":1,"orderly":1,"following":1,"notifications":1}
,"actions":{"based":1}
,"becomes":{"hot":1,"compelling":1,"unresponsive":1}
,"hot":{"resolve":1,"plug":1,"plugging":1}
,"resolve":{"problem":1}
,"problem":{"cases":1}
,"cases":{"tuning":1}
,"snippet":{"provides":1}
,"platforms":{"thermal":1,"sensors":1,"voltage":1,"running":1,"minimum":1}
,"thermal_zone_cpu":{"sensor":1,"operating":1,"trips":1}
,"throttling":{"performed":1,"reduces":1,"needs":1,"various":1,"until":1,"employs":1,"clocks":1,"trip":1,"hardware":1,"may":1,"clamps":1,"levels":1,"unable":1,"prevent":1}
,"cpu-balanced":{"cooling":1}
,"passive":{"trip":1,"based":1,"cooling":1,"throttling":1}
,"point":{"trip_bthrot":1,"identifies":1,"classified":1,"clock":1,"called":1,"triggers":1,"allows":1,"per":1,"sensors":1,"crossed":1}
,"trip_bthrot":{"crossed":1}
,"crossed":{"95.5":1,"example":1}
,"polling-delay-passive":{"500":1}
,"governor-name":{"step_wise":1}
,"thermal-zones":{"bcpu-therm":1}
,"bcpu-therm":{"trips":1}
,"trips":{"trip_bthrot":1,"thermal":1,"using":1,"per":1,"notifies":1,"changes":1,"owned":1,"sensors":1}
,"cdev-type":{"cpu-balanced":1}
,"cooling-device":{"bthrot_cdev":1}
,"bthrot_cdev":{"cpu_balanced":1}
,"cpu_balanced":{"thermal_no_limit":1}
,"thermal_no_limit":{"thermal_no_limit":1}
,"devicetree":{"bindings":1}
,"bindings":{"thermal.txt":1,"clock":1}
,"responsible":{"reporting":1}
,"reporting":{"temperature":1}
,"millidegrees":{"celsius":1}
,"celsius":{"nvidia":1,"0.5c":1}
,"types":{"temperature":1,"cooling":1,"sensors":1}
,"points":{"communicate":1,"classified":1,"bsp":1,"thermal":1,"perform":1,"given":1,"vector":1,"throttle":1,"changing":1}
,"communicate":{"thermal":1,"bpmp":1}
,"classified":{"active":1,"critical":1}
,"trigger":{"trip":1,"hardware":1}
,"triggers":{"thermal":1,"software":1,"hardware":1,"cpu":1}
,"map":{"specifies":1}
,"specifies":{"cooling":1}
,"certain":{"trip":1,"hardware":1}
,"reduces":{"temperature":1,"temperate":1,"power":1}
,"dissipating":{"device":1}
,"essentially":{"two":1}
,"temperate":{"power":1}
,"reducing":{"device":1,"heat":1,"clock":1}
,"feedback":{"control":1}
,"keeps":{"device":1}
,"safe":{"operating":1,"limits":1,"measures":1,"level":1}
,"operating":{"temperature":1,"frequencies":1,"frequency":1,"system":1,"reduced":1}
,"simple":{"proportional":1}
,"integral":{"derivative":1}
,"derivative":{"pid":1}
,"pid":{"controller":1}
,"defines":{"platform-specific":1,"critical":1}
,"platform-specific":{"thermal":1}
,"described":{"following":1,"device":1,"occur":1}
,"tmp451":{"local":1,"remote":1,"on-board":1}
,"local":{"sensor":1}
,"weighted":{"average":1}
,"aux":{"gpu":1}
,"aotag":{"versus":1,"thermal":1,"drivers":1,"sensor":1,"ring":1,"capability":1}
,"versus":{"gpu-therm":1}
,"gpu-therm":{"gpu":1}
,"balanced":{"throttles":1,"cooling":1}
,"throttles":{"aotag":1}
,"gains":{"achieved":1}
,"achieved":{"tuning":1,"reducing":1}
,"limited":{"thermal":1}
,"tdp":{"system":1,"removing":1}
,"cannot":{"remedy":1,"operate":1}
,"remedy":{"faulty":1,"tuning":1}
,"faulty":{"tdp":1}
,"guarantee":{"maximum":1}
,"maximum":{"performance":1,"allowable":1,"sensors":1,"frequencies":1,"pwm":1,"fan":1}
,"resets":{"irreversible":1}
,"irreversible":{"damage":1}
,"damage":{"device":1,"module":1,"system":1}
,"nct":{"sensors":1}
,"sense":{"temperature":1}
,"diode":{"nvidia":1}
,"sensed":{"location":1}
,"near":{"gpu":1}
,"operate":{"extended":1,"rail":1}
,"extended":{"mode":1}
,"increase":{"temperature":1}
,"powers":{"sensor":1}
,"gated":{"soc":1}
,"consequently":{"sensor":1,"nvidia":1}
,"stopped":{"soc":1}
,"restarted":{"soc":1}
,"exits":{"state":1}
,"generate":{"thermal":1,"interrupts":1}
,"correction":{"offset":1}
,"allow":{"software":1,"bpmp":1,"host":1}
,"static":{"offset":1,"cpu":1,"gpu":1,"emc":1,"vic":1,"maximum":1}
,"offset":{"temperature":1,"device":1,"register":1,"calculated":1,"result":1,"fallback":1,"compensates":1,"ensures":1}
,"accounts":{"inaccuracy":1}
,"inaccuracy":{"may":1}
,"present":{"sensor":1,"jetson":1,"nodes":1}
,"reads":{"offset":1}
,"programs":{"offset":1,"hardware":1}
,"calculated":{"validated":1}
,"validated":{"via":1}
,"oil":{"bath":1}
,"bath":{"experiments":1}
,"replaces":{"soctherm":1}
,"soctherm":{"aotag":1,"driver":1}
,"tegra_bpmp_thermal":{"sensor":1,"driver":1}
,"registers":{"itself":1}
,"itself":{"sensor":1}
,"except":{"nct":1}
,"exposed":{"using":1}
,"application":{"binary":1}
,"binary":{"interface":1,"pwm-fan":1,"holds":1}
,"abi":{"abi":1,"name":1}
,"shown":{"table":1,"nvidia":1}
,"thermal_zone":{"prefix":1}
,"prefix":{"work":1}
,"work":{"described":1}
,"paragraphs":{"bpmp":1}
,"programmable":{"temperature":1,"offset":1}
,"threshold":{"trip":1}
,"allocated":{"thermal":1}
,"walks":{"list":1}
,"list":{"thermal":1,"trips":1,"current":1,"available":1}
,"comes":{"trip":1}
,"message":{"requests":1,"particular":1,"relayed":1}
,"mrqs":{"communicate":1}
,"receives":{"cmd_thermal_host_trip_reached":1}
,"cmd_thermal_host_trip_reached":{"mrq":1,"trips":1}
,"mrq":{"message":1,"messages":1,"command":1,"requests":1}
,"crosses":{"trip":1,"software":1}
,"relayed":{"back":1}
,"back":{"linux":1,"pllx":1,"55c":1,"avoid":1}
,"part":{"bsp":1,"device":1,"firmware":1}
,"pwm-fan":{"provides":1,"cooling":1,"target_pwm":1}
,"programming":{"pwm":1}
,"pwm":{"controller":1,"values":1,"fan":1}
,"ramp-up":{"ramp-down":1}
,"ramp-down":{"control":1}
,"pwm-rpm":{"mapping":1}
,"ramp":{"rates":1}
,"rates":{"stored":1,"bsp":1,"using":1}
,"stored":{"part":1,"on-chip":1}
,"values":{"cooling":1,"ensure":1,"result":1}
,"attached":{"monitor":1}
,"increases":{"governor":1,"beyond":1}
,"picks":{"progressively":1,"higher":1}
,"progressively":{"deeper":1,"picks":1}
,"deeper":{"cooling":1}
,"rpm":{"fan":1}
,"produces":{"cooling":1}
,"line":{"defense":1,"tool":1}
,"defense":{"delay":1}
,"delay":{"clock":1}
,"sensor\u2019s":{"temperature":1,"oscillator":1}
,"employs":{"dvfs":1}
,"capabilities":{"clocks":1}
,"reduce":{"operating":1,"performance":1}
,"thereby":{"voltages":1}
,"helps":{"control":1}
,"impact":{"performance":1}
,"feels":{"warm":1}
,"warm":{"seems":1}
,"seems":{"sluggish":1}
,"sluggish":{"may":1}
,"due":{"thermal":1,"high":1}
,"mapped":{"following":1}
,"translate":{"maximum":1}
,"allowable":{"operating":1}
,"tables":{"clocks":1}
,"input":{"feedback":1,"voltage":1,"current":1}
,"similarly":{"governor":1,"designing":1}
,"loop\u2019s":{"output":1}
,"output":{"new":1,"voltage":1}
,"heats":{"governor":1}
,"cap":{"clocks":1}
,"potentially":{"greater":1}
,"greater":{"cooling":1,"200":1}
,"maintain":{"junction":1,"output":1}
,"junction":{"temperature":1}
,"recommended":{"safe":1}
,"temperatures":{"table":1,"pllx":1,"even":1,"instead":1,"voltage":1,"change":1,"thermal":1}
,"special":{"type":1,"trip":1}
,"reset":{"due":1,"thermtrip":1,"pin":1}
,"per":{"thermal":1,"sensor":1}
,"users":{"lower":1}
,"lower":{"limit":1,"voltage":1,"boundary":1}
,"occurs":{"cooling":1}
,"strategies":{"failed":1}
,"failed":{"considered":1,"particular":1,"occur":1}
,"considered":{"rare":1}
,"rare":{"event":1,"transient":1}
,"event":{"software":1,"detection":1}
,"occur":{"hardware":1,"results":1}
,"host":{"operating":1,"cpu":1,"bpmp":1,"continues":1,"therefore":1,"register":1,"various":1,"notified":1,"seeks":1}
,"hosts":{"soctherm":1,"thermal":1}
,"co-locate":{"tdiode":1}
,"tdiode":{"pad-ring":1}
,"placed":{"adjacent":1}
,"adjacent":{"pllx":1}
,"centrally":{"located":1}
,"located":{"denver":1,"a57":1}
,"soc_therm":{"collection":1,"reports":1,"sensors":1,"sensor":1}
,"collection":{"on-chip":1}
,"on-chip":{"ring":1,"fuses":1}
,"ring":{"oscillators":1,"oscillator":1}
,"oscillators":{"whose":1,"pllx":1}
,"changes":{"based":1,"notification":1}
,"convert":{"measured":1}
,"oscillating":{"frequency":1}
,"fixed":{"temperature":1}
,"advance":{"stored":1}
,"fuses":{"during":1}
,"calibrates":{"sensor":1}
,"complete":{"temperature":1}
,"reports":{"temperature":1,"sensors":1,"accurate":1}
,"degrees":{"celsius":1}
,"0.5c":{"precision":1}
,"precision":{"margin":1}
,"logically":{"grouped":1}
,"grouped":{"sensor":1,"cpu":1}
,"groups":{"based":1,"represented":1}
,"proximity":{"certain":1,"aotag":1}
,"blocks":{"sensor":1}
,"represented":{"single":1,"thermal_zone_cpu":1,"nvidia":1}
,"single":{"sensor":1,"notification":1}
,"four":{"temperature":1}
,"cpus":{"soc_therm":1,"manually":1}
,"group":{"taking":1}
,"taking":{"maximum":1}
,"report":{"temperature":1,"thermal":1,"current":1}
,"programmed":{"trip":1,"levels":1}
,"capable":{"monitoring":1}
,"monitoring":{"several":1,"gpu":1}
,"accurate":{"temperature":1,"temperatures":1}
,"minimum":{"voltage":1,"maximum":1}
,"power-state":{"firmware":1}
,"measurements":{"during":1,"greater":1}
,"powering":{"sensor":1}
,"power-gated":{"sc7":1}
,"oscillator":{"running":1,"platforms":1,"programmable":1,"added":1,"allows":1,"farther":1,"replacing":1,"based":1}
,"frequency-to-temperature":{"conversion":1}
,"conversion":{"may":1}
,"result":{"inaccurate":1,"sensors":1,"fast":1,"damage":1}
,"inaccurate":{"values":1}
,"ensure":{"spurious":1,"accurate":1,"notification":1}
,"spurious":{"temperature":1}
,"stop":{"sensor":1}
,"measuring":{"temperature":1,"cpu":1,"tool":1}
,"exited":{"sensors":1}
,"fallback":{"pllx":1,"programmable":1,"gpu":1}
,"pllx":{"sensor":1,"sensor\u2019s":1,"fallback":1}
,"readings":{"during":1}
,"guaranteed":{"firmware":1}
,"falls":{"back":1}
,"invalidate":{"oscillators":1}
,"added":{"offset":1}
,"continuous":{"temperature":1}
,"measurement":{"even":1}
,"even":{"lower":1,"device":1}
,"side":{"effect":1,"effects":1,"ubuntu":1}
,"effect":{"pllx":1}
,"compensates":{"fact":1}
,"fact":{"pllx":1}
,"farther":{"away":1}
,"away":{"oscillator":1}
,"replacing":{"host":1}
,"continues":{"thermal":1}
,"effects":{"offset":1}
,"continue":{"right":1}
,"always-on":{"thermal":1,"power":1}
,"alert":{"generator":1}
,"generator":{"aotag":1}
,"domain":{"monitor":1}
,"apart":{"distinction":1}
,"distinction":{"aotag":1}
,"operates":{"soc_therm":1}
,"just":{"soc_therm":1}
,"interrupts":{"additionally":1,"resulting":1}
,"ideal":{"monitoring":1}
,"capability":{"measure":1}
,"identified":{"thermal":1}
,"modules":{"register":1,"temperatures":1,"integrate":1,"three-channel":1}
,"examines":{"list":1}
,"notifies":{"owners":1}
,"owners":{"trips":1}
,"notification":{"sent":1,"generated":1,"temperature":1,"warn":1,"show":1}
,"sent":{"using":1}
,"callback":{"bpmp":1}
,"owned":{"trips":1,"host":1}
,"primary":{"thermal":1}
,"generated":{"whenever":1}
,"whenever":{"given":1}
,"sends":{"single":1,"notification":1}
,"hysteresis":{"prevent":1}
,"prevent":{"sending":1,"shutdown":1}
,"sending":{"notifications":1}
,"notifications":{"above":1,"thermal":1}
,"above":{"example":1,"current":1}
,"reaches":{"55c":1}
,"waits":{"until":1}
,"drops":{"below":1}
,"rises":{"back":1}
,"sets":{"low":1,"maximum":1}
,"receive":{"events":1}
,"dropped":{"below":1}
,"element":{"power":1}
,"delivery":{"system":1,"hardware":1,"systems":1}
,"supply":{"without":1,"hardware":1,"m.2":1}
,"shutting":{"down":1}
,"fails":{"maintain":1}
,"ripple":{"current":1}
,"inductor":{"switching":1}
,"switching":{"regulator":1}
,"tolerate":{"without":1}
,"limitations":{"result":1}
,"fast":{"transient":1}
,"transient":{"electrical":1,"nature":1,"advantage":1}
,"over-current":{"battery":1}
,"drop":{"pmic":1,"clock":1}
,"refers":{"events":1}
,"alarms":{"triggers":1}
,"triggering":{"events":1}
,"nature":{"user":1}
,"minimally":{"impacted":1}
,"notified":{"events":1,"userspace":1}
,"detect":{"resulting":1}
,"resulting":{"drop":1,"events":1}
,"tool":{"samples":1,"easy":1}
,"samples":{"cpu":1}
,"cycle":{"counters":1}
,"counters":{"thermal":1}
,"seeks":{"control":1}
,"ongoing":{"basis":1}
,"basis":{"hardware":1}
,"clamps":{"down":1}
,"down":{"clocks":1,"device":1}
,"handle":{"events":1}
,"throttle":{"points":1,"settings":1,"vectors":1}
,"vector":{"configuration":1}
,"holds":{"various":1}
,"govern":{"throttling":1}
,"handles":{"interrupts":1}
,"changing":{"bpmp":1}
,"shows":{"hardware":1,"naming":1}
,"throttled":{"percentage":1,"back":1,"gui":1}
,"vectors":{"optimized":1}
,"limiting":{"peak":1}
,"manage":{"peak":1,"components":1,"cpu":1}
,"three":{"levels":1}
,"light":{"medium":1}
,"medium":{"heavy":1}
,"heavy":{"described":1}
,"prevents":{"cpu":1}
,"drawing":{"current":1}
,"designing":{"fail":1,"power":1}
,"fail":{"safe":1}
,"measures":{"power":1}
,"circuits":{"pmics":1}
,"pmics":{"using":1}
,"shut":{"down":1}
,"bad":{"user":1}
,"worst-case":{"loads":1}
,"loads":{"results":1,"additionally":1}
,"large":{"costly":1}
,"costly":{"components":1}
,"socs":{"designed":1,"actively":1}
,"systems":{"adequate":1}
,"adequate":{"common":1}
,"avoid":{"exceeding":1,"shutdown":1}
,"exceeding":{"design":1}
,"advantage":{"approach":1}
,"approach":{"power":1}
,"final":{"failsafe":1}
,"failsafe":{"firmware":1}
,"thermtrip":{"software":1}
,"unable":{"control":1}
,"generation":{"system":1}
,"unresponsive":{"soc":1}
,"asserts":{"reset":1}
,"software-based":{"power":1}
,"integrate":{"three-channel":1}
,"three-channel":{"ina3221":1}
,"ina3221":{"power":1,"0x41":1,"triggers":1}
,"sysfs":{"nodes":1,"node":1}
,"naming":{"convention":1}
,"convention":{"sysfs":1}
,"exports":{"rail":1}
,"in_current":{"_input":1}
,"in_voltage":{"_input":1}
,"in_power":{"_input":1}
,"channel":{"number":1,"vdd_sys_gpu":1,"vdd_sys_soc":1,"vdd_4v0_wifi":1,"connected":1,"vdd_in":1,"vdd_sys_cpu":1,"vdd_sys_ddr":1,"vdd_mux":1,"vdd_5v_io_sys":1,"vdd_3v3_sys":1,"vdd_3v3_io_slp":1,"vdd_1v8_io":1,"vdd_3v3_sys_m2":1,"vdd_cpu_gpu":1,"vdd_soc":1}
,"ina":{"driver":1,"sysfs":1,"measurements":1}
,"modifying":{"values":1}
,"i2c":{"address":1,"drivers":1,"addresses":1}
,"address":{"0x40":1,"0x41":1,"0x42":1,"0x43":1}
,"0x40":{"0x421":1,"sysfs":1}
,"0x421":{"sysfs":1}
,"names":{"voltage":1,"i2c":1}
,"bus":{"i2c":1}
,"ina3221x":{"0-0040":1,"0-0041":1,"0-0042":1,"0-0043":1,"2-0040":1}
,"0-0040":{"iio:device0":1}
,"0-0041":{"iio:device1":1}
,"wifi":{"power":1}
,"ddr":{"power":1}
,"developer":{"kit":1}
,"kit":{"carrier":1}
,"carrier":{"board":1}
,"3-channel":{"ina3221":1}
,"addresses":{"0x42":1}
,"0x42":{"0x43":1}
,"0x43":{"sysfs":1}
,"0-0042":{"iio:device2":1}
,"0-0043":{"iio:device3":1}
,"3.3":{"supply":1,"sleep":1}
,"vdd_1v8_io":{"name":1}
,"schematic":{"vdd_1v8":1}
,"1.8":{"supply":1}
,"m.2":{"key":1}
,"0x41":{"channel-0":1}
,"channel-0":{"rail":1}
,"vdd_in":{"enter":1,"voltage":1,"critical":1,"rail":1}
,"iio:device1":{"rail_name_0":1,"in_current0_input":1,"in_voltage0_input":1,"in_power0_input":1,"crit_current_limit_0":1}
,"current_in_ma":{"sys":1}
,"accuracy":{"assume":1,"deviate":1}
,"assume":{"guard":1}
,"guard":{"band":1}
,"band":{"ina":1}
,"200":{"below":1}
,"2-0040":{"iio:device0":1}
,"overcurrent":{"thresholds":1,"events":1}
,"thresholds":{"average":1}
,"instantaneous":{"current":1}
,"3.6":{"respectively":1}
,"respectively":{"ina3221":1}
,"exceeds":{"limits":1}
,"userspace":{"via":1}
,"applet":{"details":1}
,"setup":{"document":1}
,"techniques":{"managing":1}
,"managing":{"power":1}
,"turn":{"secondary":1}
,"secondary":{"cpus":1,"cpu":1}
,"cpux":{"online":1}
,"check":{"cpu\u2019s":1,"online":1}
,"cpu\u2019s":{"state":1}
,"replace":{"cpu":1}
,"clk":{"clk_tree":1,"emc":1}
,"print":{"cpu":1,"gpu":1,"emc":1}
,"boundary":{"upper":1,"current":1}
,"upper":{"boundary":1}
,"cpu_freq":{"sys":1,"frequency":1}
,"gpu.0":{"devfreq":1}
,"gpu_freq":{"sys":1,"value":1}
,"emc_freq":{"sys":1,"frequency":1}
,"jetson_clocks.sh":{"script":1}
,"script":{"maximize":1,"show":1,"available":1,"enter":1}
,"maximize":{"jetson":1,"platform":1}
,"show":{"current":1,"device":1}
,"store":{"current":1}
,"restore":{"clock":1,"previous":1}
,"bin":{"jetson_clocks":1}
,"jetson_clocks":{"options":1,"--show":1,"--store":1,"--fan":1,"longer":1,"--restore":1}
,"displays":{"current":1,"desktop":1,"similar":1}
,"--store":{"file":1}
,"stores":{"current":1}
,"--restore":{"file":1}
,"restores":{"saved":1}
,"saved":{"settings":1}
,"execute":{"command":1}
,"starting":{"release":1}
,"32.4":{"jetson_clocks":1}
,"longer":{"sets":1}
,"prefer":{"old":1}
,"old":{"behavior":1}
,"behavior":{"--fan":1}
,"--fan":{"option":1}
,"previous":{"settings":1}
,"easy":{"access":1}
,"access":{"power-related":1}
,"power-related":{"functionality":1,"information":1}
,"functionality":{"information":1}
,"ubuntu":{"desktop\u2019s":1}
,"desktop\u2019s":{"top":1}
,"next":{"nvidia":1}
,"illustration":{"above":1}
,"switch":{"current":1}
,"click":{"nvidia":1,"power":1,"run":1}
,"open":{"dropdown":1,"submenu":1}
,"dropdown":{"menu":1}
,"submenu":{"power":1}
,"tegrastats":{"click":1,"spawn":1,"display":1}
,"spawn":{"terminal":1}
,"terminal":{"window":1}
,"window":{"run":1}
,"registered":{"system":1}
,"desktop":{"notification":1,"environments":1,"power":1}
,"warn":{"system":1}
,"thermally":{"throttled":1}
,"similar":{"notification":1}
,"reduced":{"speed":1}
,"examples":{"notifications":1}
,"pwm_duty_cycle":{"sys":1,"value":1}
,"generic_pwm_tachometer":{"hwmon":1}
,"hwmon":{"hwmon1":1}
,"hwmon1":{"rpm":1}
,"look":{"feel":1}
,"feel":{"nvpmodel":1}
,"environments":{"notable":1}
,"notable":{"example":1}
,"lxde":{"desktop":1}
,"item":{"shown":1}
,"icon\u2019s":{"dropdown":1}
}
;Search.control.loadWordPairs(pairs);
