var pairs =
{
"disk":{"encryption":1,"partition":1,"format":1,"itself":1,"uses":1,"luks":1,"driver":1,"input":1,"uuid":1,"image":1,"nvluks-srv-app":1,"even":1,"physically":1,"keep":1,"device":1,"may":1,"modify":1,"images":1,"works":1,"includes":1,"unlocking":1,"decrypts":1,"routed":1}
,"applies":{"jetson":1}
,"jetson":{"xavier":1,"agx":1,"tx2":1,"linux":1,"ram":1}
,"xavier":{"jetson":1,"series":1,"module":1,"developer":1}
,"agx":{"xavier":1}
,"series":{"jetson":1,"device":1}
,"tx2":{"series":1}
,"encryption":{"encrypts":1,"based":1,"standard":1,"provides":1,"functionality":1,"key":1,"decryption":1,"lock":1,"aes-cbc":1,"prevent":1,"cannot":1,"implementation":1,"fulfills":1,"requires":1,"enabled":1,"separates":1,"apply":1,"input":1,"reference":1}
,"encrypts":{"whole":1,"decrypts":1,"data":1}
,"whole":{"disk":1}
,"partition":{"protect":1,"header":1,"configures":1,"two":1,"contains":1,"definition":1,"configuration":1,"name":1,"defined":1,"partition":1,"encrypted":1,"layout":1,"helps":1,"boot":1,"accordingly":1,"u\u2011boot":1,"primary":1,"thus":1}
,"protect":{"data":1,"against":1}
,"data":{"contains":1,"blocks":1,"encryption":1,"transferred":1,"used":1,"stored":1,"look":1,"members":1,"disk":1,"cannot":1,"encrypted":1,"placed":1,"reads":1}
,"contains":{"jetson":1,"information":1,"boot":1,"rest":1,"rootfs":1,"encrypted":1}
,"linux":{"offers":1,"unified":1,"disk":1,"uses":1,"kernel":1,"provides":1,"reference":1}
,"offers":{"disk":1}
,"based":{"linux":1}
,"unified":{"key":1}
,"key":{"setup":1,"known":1,"dek":1,"used":1,"generated":1,"dev":1,"resides":1,"derived":1,"uses":1,"root":1,"deriving":1,"length":1,"derivation":1,"generic":1,"kdf":1,"generation":1,"label-string":1,"created":1,"file":1,"assets":1,"generate":1,"ekb":1,"nvidia":1,"source":1,"shown":1,"change":1,"passphrase":1,"kernel":1}
,"setup":{"luks":1,"information":1,"preparation":1}
,"luks":{"data-at-rest":1,"userspace":1,"partition":1,"header":1,"key":1,"device":1}
,"data-at-rest":{"encryption":1}
,"standard":{"linux":1,"disk":1,"device-mapper":1}
,"provides":{"standard":1,"reference":1}
,"format":{"stores":1}
,"stores":{"necessary":1}
,"necessary":{"setup":1,"ensure":1,"utilities":1}
,"information":{"disk":1,"cryptsetup":1,"related":1,"readme_initrd_flash.txt":1}
,"itself":{"partition":1}
,"header":{"passphrase":1,"encrypted":1}
,"passphrase":{"trusty":1,"password":1,"generated":1,"cryptsetup":1,"unlock":1,"luks_get_generic_pass":1,"implementation":1,"returned":1,"nvluks-srv-app":1,"boot":1,"until":1,"default":1,"disk":1,"generation":1,"requests":1}
,"trusty":{"architecture":1,"luks-srv":1}
,"architecture":{"supports":1}
,"supports":{"disk":1}
,"functionality":{"multiple":1,"linux":1}
,"multiple":{"user":1}
,"user":{"passwords":1,"disk":1,"interaction":1,"enter":1}
,"uses":{"cryptsetup":1,"dmcrypt":1,"derive":1,"passphrase":1,"key":1,"parameter":1,"board":1,"ekb":1,"app":1,"tegra-crypto":1,"security":1}
,"cryptsetup":{"luks":1,"cryptsetup":1,"project":1,"default":1,"uses":1,"nvluks-srv-app":1,"aes-cbc-essiv:sha256":1,"scripts":1,"utility":1,"unlocks":1,"invokes":1}
,"userspace":{"command":1}
,"command":{"line":1,"message":1,"type":1,"instructs":1,"passphrase":1,"line\u2019s":1,"luks-srv":1,"find":1}
,"line":{"utility":1,"flash.sh":1,"option":1,"file":1,"crypttab":1,"displays":1,"output":1,"looks":1,"specifies":1}
,"utility":{"unlock":1,"sets":1}
,"unlock":{"encrypted":1,"data":1,"boot":1,"mount":1,"additional":1,"subsequent":1}
,"encrypted":{"disk":1,"key":1,"data":1,"device":1,"files":1,"app_enc":1,"true":1,"root":1,"attribute":1,"rootfs":1,"file":1,"block":1}
,"dmcrypt":{"kernel":1,"documentation":1,"uses":1,"decrypts":1}
,"kernel":{"module":1,"sits":1,"dtb":1,"command":1,"initialized":1,"dmcrypt":1}
,"module":{"backend":1,"standard":1,"jetson":1,"hsm":1,"loads":1}
,"backend":{"utility":1}
,"sets":{"encrypted":1}
,"configures":{"passphrase":1}
,"device-mapper":{"interface":1}
,"interface":{"encryption":1}
,"sits":{"disk":1}
,"driver":{"file":1,"uses":1}
,"file":{"system":1,"l4t":1,"name":1,"enable":1,"appropriate":1,"device":1,"generate":1,"initrd":1,"rootfs":1,"ekb":1,"systems":1,"crypttab":1,"form":1}
,"system":{"encrypts":1,"disk":1,"images":1,"secure":1,"production":1,"booted":1,"boot":1,"want":1,"unlocked":1,"during":1,"subsequent":1,"hsm":1}
,"decrypts":{"data":1,"disk":1,"encrypts":1}
,"blocks":{"transparently":1}
,"project":{"dmcrypt":1}
,"documentation":{"hosted":1}
,"hosted":{"gitlab":1}
,"details":{"operation":1}
,"two":{"types":1,"applications":1,"partitions":1,"parts":1,"helper":1,"examples":1}
,"types":{"keys":1,"threat":1}
,"keys":{"used":1,"cannot":1,"needed":1}
,"used":{"disk":1,"data":1,"generate":1,"decrypt":1,"unlock":1,"key":1}
,"master":{"key":1}
,"known":{"disk":1,"special":1,"initrd":1}
,"dek":{"key":1,"passphrase":1}
,"decryption":{"data":1}
,"transferred":{"filesystem":1}
,"filesystem":{"disk":1,"including":1,"need":1}
,"generated":{"cryptsetup":1,"help":1,"reference":1,"host":1,"flash.sh":1,"secure":1,"time":1}
,"default":{"recommended":1,"context":1,"input":1,"bootloader":1}
,"recommended":{"source":1,"national":1}
,"source":{"data":1,"sake":1}
,"generate":{"key":1,"per-device":1,"generic":1,"passphrase":1,"file":1,"blue":1,"rootfs":1}
,"dev":{"random":1,"mmcblk0p1":1,"mapper":1,"mmcblk0p43":1}
,"random":{"key":1,"minimizing":1}
,"resides":{"luks":1}
,"derived":{"passphrase":1,"l4t":1,"key":1}
,"password":{"input":1,"attacker":1}
,"input":{"string":1,"used":1,"context":1,"red":1,"two":1}
,"string":{"pattern":1,"key":1,"contains":1,"disk\u2019s":1,"passed":1,"disk":1,"used":1,"uuid":1,"change":1}
,"pattern":{"supplied":1}
,"supplied":{"user":1}
,"lock":{"disk":1}
,"decrypt":{"unlock":1}
,"stored":{"disk":1}
,"help":{"two":1}
,"luks-srv":{"queries":1,"retrieve":1,"obtain":1,"respond":1,"tas":1,"pass":1}
,"queries":{"ekb":1,"hardware-based":1}
,"ekb":{"key":1,"partition":1}
,"derive":{"luks":1}
,"root":{"key":1,"partition":1,"parameter":1,"disk":1,"filesystem":1,"device":1}
,"deriving":{"passphrase":1}
,"nvluks-srv-app":{"normal":1,"communicates":1,"used":1,"unlock":1,"--context-string":1,"queries":1}
,"normal":{"non-secure":1,"world":1}
,"non-secure":{"world":1}
,"world":{"communicates":1,"following":1,"query":1}
,"communicates":{"luks-srv":1,"sending":1}
,"retrieve":{"passphrase":1}
,"cryptographic":{"algorithm":1}
,"algorithm":{"used":1,"key":1}
,"aes-cbc":{"essiv":1}
,"essiv":{"key":1}
,"length":{"128":1}
,"128":{"bits":1}
,"bits":{"mode":1}
,"mode":{"operation":1}
,"operation":{"makes":1}
,"makes":{"encrypted":1}
,"look":{"completely":1}
,"completely":{"random":1}
,"minimizing":{"potential":1}
,"potential":{"attack":1}
,"attack":{"entire":1,"extracting":1,"stealing":1}
,"entire":{"key":1}
,"derivation":{"process":1,"function":1,"using":1}
,"process":{"performed":1,"uses":1,"daemon":1,"access":1,"mount":1,"hwkey-agent":1,"sake":1,"jetson-based":1,"production":1}
,"performed":{"secure":1}
,"secure":{"world":1,"system":1,"host":1,"key":1}
,"following":{"diagram":1,"types":1,"example":1,"points":1}
,"diagram":{"outlines":1,"description":1,"below":1,"shows":1,"illustrates":1}
,"outlines":{"process":1}
,"description":{"automatically":1}
,"automatically":{"generated":1}
,"generation":{"process":1,"reference":1,"management":1,"flow":1}
,"function":{"kdf":1}
,"kdf":{"generate":1,"recommended":1,"uses":1}
,"per-device":{"unique":1,"encrypted":1}
,"unique":{"luks":1,"passphrase":1,"across":1}
,"generic":{"key":1}
,"nist-sp-800-108":{"key":1}
,"national":{"institute":1}
,"institute":{"standards":1}
,"standards":{"technology":1}
,"technology":{"algorithm":1}
,"using":{"pseudorandom":1,"cryptsetup":1}
,"pseudorandom":{"functions":1}
,"in-key":{"string":1}
,"l4t":{"implementation":1,"divide":1,"bsp":1}
,"implementation":{"ekb":1,"label-string":1,"default":1,"input":1,"jetson":1,"disk":1,"generates":1,"described":1}
,"label-string":{"identifies":1,"fixed":1,"luks-srv-ecid":1,"luks-srv-generic":1}
,"identifies":{"purpose":1,"partition":1}
,"purpose":{"key":1,"disk":1}
,"reference":{"implementation":1,"environment":1}
,"fixed":{"value":1,"known":1}
,"value":{"defined":1,"app_enc_size":1}
,"context-string":{"string":1}
,"related":{"derived":1}
,"parameter":{"key":1,"disk\u2019s":1,"specifies":1}
,"context":{"string":1}
,"disk\u2019s":{"uuid":1}
,"uuid":{"change":1,"user":1,"numbers":1,"partition\u2019s":1,"specified":1,"disk":1,"encrypted":1,"uuid":1,"underlying":1,"b5600ed6-69e7-42b8-bee3-ecfdd12649d1":1,"cf6fa01d-1127-4612-9992-2f6db77385e0":1,"line":1,"5096aa4d-6590-429b-9295-a1fe041b8fa3":1,"file":1}
,"change":{"modifying":1,"initrd":1,"key":1,"eks":1}
,"luks-srv-ecid":{"context\u2011string":1}
,"context\u2011string":{"ecid":1,"generic-key":1}
,"ecid":{"reference":1}
,"environment":{"variable":1}
,"variable":{"ecid":1}
,"luks-srv-generic":{"context\u2011string":1}
,"once":{"luks":1}
,"created":{"nvluks-srv-app":1}
,"query":{"luks-srv":1}
,"obtain":{"passphrase":1}
,"sending":{"ipc":1}
,"ipc":{"packet":1}
,"packet":{"packet\u2019s":1,"luks_get_unique_pass":1}
,"packet\u2019s":{"structure":1,"data":1}
,"typedef":{"struct":1}
,"struct":{"luks_srv_cmd_msg":1}
,"uint32_t":{"luks_srv_cmd":1}
,"char":{"context_str":1,"output_passphrase":1}
,"luks_srv_cmd":{"command":1}
,"message":{"tells":1}
,"tells":{"packet":1,"generate":1}
,"luks_get_unique_pass":{"tells":1}
,"luks_get_generic_pass":{"tells":1}
,"context_str":{"context":1}
,"passed":{"kdf":1}
,"interaction":{"needed":1}
,"needed":{"create":1,"board":1,"manufacturing":1}
,"create":{"encrypted":1,"file":1,"subdirectory":1}
,"image":{"unlock":1,"symbol":1,"generation":1,"includes":1,"contain":1}
,"boot":{"time":1,"branch":1,"partition":1,"encrypted":1,"directory":1,"flow":1,"line":1,"replacing":1}
,"output_passphrase":{"passphrase":1}
,"returned":{"output":1}
,"output":{"passphrase":1,"encrypted":1}
,"example":{"shows":1,"app":1,"commands":1,"above":1,"unlock":1}
,"shows":{"unlock":1,"disk":1,"elements":1,"default":1,"overall":1}
,"bin":{"bash":1}
,"--context-string":{"uuid":1}
,"luksdevice":{"dm_name":1}
,"prevent":{"form":1,"attack":1}
,"form":{"attack":1}
,"extracting":{"passphrase":1}
,"time":{"e.g":1,"security":1}
,"e.g":{"initrd":1,"linux_for_tegra":1,"cryptsetup":1}
,"initrd":{"luks_srv_cmd":1,"images":1,"includes":1,"accordingly":1,"system_boot.img":1,"flashing":1,"topic":1,"may":1,"unlock":1,"image":1,"follows":1,"describes":1,"instructions":1,"store":1,"originally":1,"mount":1}
,"type":{"luks_no_pass_response":1,"data":1,"elements":1,"crypto_luks":1}
,"luks_no_pass_response":{"command":1}
,"instructs":{"luks-srv":1}
,"respond":{"luks_get":1,"further":1}
,"luks_get":{"command":1}
,"until":{"reboot":1}
,"reboot":{"step":1}
,"step":{"crucial":1,"subdirectory":1}
,"crucial":{"ensure":1}
,"ensure":{"security":1,"keys":1}
,"security":{"design":1,"hole":1,"requirements":1,"module":1,"key":1,"engine":1,"keys":1,"machine":1}
,"threat":{"model":1}
,"stealing":{"tampering":1}
,"tampering":{"data":1}
,"even":{"disk":1}
,"physically":{"unmounted":1}
,"unmounted":{"case":1}
,"case":{"internal":1,"production":1}
,"internal":{"device":1}
,"device":{"emmc":1,"data":1,"access":1,"booting":1,"dev":1,"above":1,"linux_for_tegra":1,"boot":1,"name":1,"l4t_initrd_flash.sh":1,"kernel":1,"unlock":1,"root":1,"setting":1,"luks":1,"per-device":1,"containing":1,"several":1,"flashed":1,"designed":1}
,"emmc":{"removed":1}
,"removed":{"device":1}
,"cannot":{"exposed":1,"protect":1,"read":1,"leaked":1}
,"against":{"following":1}
,"background":{"process":1}
,"daemon":{"security":1}
,"hole":{"attacker":1,"gain":1}
,"attacker":{"may":1,"credentials":1}
,"may":{"able":1,"real":1,"found":1}
,"able":{"hole":1,"deploy":1}
,"gain":{"control":1}
,"control":{"process":1}
,"access":{"disk":1}
,"theft":{"leakage":1}
,"leakage":{"login":1}
,"login":{"password":1}
,"credentials":{"log":1}
,"log":{"device":1}
,"fulfills":{"security":1}
,"requirements":{"cases":1,"different":1}
,"cases":{"case\u2019s":1}
,"case\u2019s":{"requirements":1}
,"different":{"modify":1,"key":1}
,"modify":{"model":1,"script":1,"initrd":1}
,"model":{"implementing":1}
,"layout":{"encrypted":1,"new":1,"file":1}
,"bootloader":{"cannot":1,"cboot":1,"unlock":1,"unlocks":1}
,"read":{"encrypted":1}
,"files":{"disk":1,"e.g":1}
,"requires":{"l4t":1}
,"divide":{"na\u00EFve":1}
,"na\u00EFve":{"system\u2019s":1}
,"system\u2019s":{"app":1}
,"app":{"partition":1,"type":1,"two":1,"second":1,"app_enc":1,"specifies":1,"total":1}
,"unencrypted":{"app":1,"app_enc":1}
,"branch":{"filesystem":1,"rootfs":1}
,"including":{"kernel":1}
,"dtb":{"initrd":1}
,"new":{"encrypted":1,"partition":1,"parameters":1}
,"app_enc":{"partition":1,"type":1,"highlighted":1,"definition":1,"specifies":1,"partition\u2019s":1}
,"rest":{"filesystem":1,"operating":1,"rootfs":1}
,"definition":{"system":1,"l4t":1,"app":1,"identify":1}
,"enabled":{"find":1,"emmc_cfg":1}
,"find":{"definition":1,"file":1,"uuid":1}
,"bsp":{"partition":1,"e.g":1}
,"configuration":{"files":1,"file":1}
,"linux_for_tegra":{"\u200Cbootloader":1,"p2972-0000.conf.common":1,"tools":1}
,"\u200Cbootloader":{"\u200Ct186ref":1}
,"\u200Ct186ref":{"cfg":1}
,"cfg":{"\u200Cflash_t194_sdmmc.xml":1,"\u200Cflash_t194_sdmmc_enc_rfs.xml":1}
,"\u200Cflash_t194_sdmmc.xml":{"jetson":1}
,"booting":{"sdmmc":1,"encrypted":1,"target":1}
,"sdmmc":{"memory":1}
,"name":{"app":1,"app_enc":1,"appropriate":1,"during":1,"encrypted":1,"dev":1,"volume":1}
,"allocation_policy":{"sequential":1}
,"sequential":{"allocation_policy":1}
,"filesystem_type":{"basic":1}
,"basic":{"filesystem_type":1}
,"size":{"appsize":1,"104857600":1,"app_enc_size":1,"element":1,"app":1}
,"appsize":{"size":1}
,"file_system_attribute":{"file_system_attribute":1}
,"allocation_attribute":{"0x8":1}
,"0x8":{"allocation_attribute":1}
,"align_boundary":{"4096":1}
,"4096":{"align_boundary":1}
,"percent_reserved":{"percent_reserved":1}
,"filename":{"appfile":1,"system_boot.img":1,"system_root_encrypted.img":1,"element":1}
,"appfile":{"filename":1}
,"unique_guid":{"appuuid":1,"app_enc_uuid":1,"elements":1}
,"appuuid":{"unique_guid":1,"app_enc_uuid":1}
,"required":{"contains":1}
,"rootfs":{"partition":1,"size":1,"updated":1,"host":1,"generated":1,"green":1,"user":1,"secure":1,"external":1,"nvme":1,"initrd":1,"unencrypted":1,"encrypted":1}
,"primary_gpt":{"accessed":1}
,"accessed":{"fixed":1}
,"special":{"device":1}
,"separates":{"app":1}
,"partitions":{"find":1,"unique_guid":1,"uuids":1}
,"\u200Cflash_t194_sdmmc_enc_rfs.xml":{"device":1}
,"104857600":{"size":1}
,"system_boot.img":{"filename":1,"system_root_encrypted.img":1}
,"defined":{"primary_gpt":1}
,"app_enc_size":{"size":1,"later":1,"calculated":1}
,"system_root_encrypted.img":{"filename":1}
,"app_enc_uuid":{"unique_guid":1,"respectively":1}
,"differences":{"first":1}
,"first":{"example\u2019s":1,"partition":1}
,"example\u2019s":{"definition":1,"definitions":1}
,"second":{"example\u2019s":1}
,"definitions":{"app":1}
,"highlighted":{"red":1}
,"red":{"type":1}
,"elements":{"app_enc":1,"specify":1,"rootfs":1}
,"notice":{"size":1}
,"element":{"app":1,"app_enc":1,"specifies":1}
,"specifies":{"actual":1,"symbol":1,"key":1,"device":1,"uuid":1}
,"actual":{"number":1,"file":1}
,"number":{"size":1}
,"symbol":{"app_enc_size":1,"resolved":1}
,"later":{"value":1}
,"calculated":{"subtracting":1}
,"subtracting":{"size":1}
,"total":{"rootfs":1}
,"partition\u2019s":{"filename":1,"encrypted":1,"uuid":1}
,"appropriate":{"disk":1,"board":1}
,"resolved":{"file":1}
,"during":{"flashing":1,"system":1,"initialization":1}
,"specify":{"partitions":1}
,"uuids":{"appuuid":1}
,"respectively":{"symbols":1}
,"symbols":{"translated":1}
,"translated":{"real":1}
,"real":{"uuid":1,"device":1}
,"numbers":{"image":1}
,"attribute":{"indicates":1}
,"indicates":{"partition":1,"disk":1}
,"parameters":{"needed":1}
,"board":{"configuration":1,"rootdev":1}
,"enable":{"disk":1}
,"apply":{"new":1}
,"p2972-0000.conf.common":{"jetson":1}
,"developer":{"kit":1}
,"kit":{"disk_enc_enable":1}
,"disk_enc_enable":{"setting":1}
,"setting":{"indicates":1,"crypttab":1}
,"emmc_cfg":{"identifies":1,"flash_l4t_t194_sdmmc_enc_rfs.xml":1}
,"flash":{"tool":1,"onto":1,"encrypted":1}
,"tool":{"uses":1,"section":1}
,"images":{"flash":1,"support":1,"initrd":1,"starting":1,"blobs":1,"systems":1,"images":1,"generated":1}
,"onto":{"device":1,"production":1}
,"support":{"booting":1}
,"keep":{"following":1}
,"points":{"mind":1}
,"bootarg":{"kernel":1}
,"line\u2019s":{"root":1}
,"specified":{"partition":1,"step":1}
,"identify":{"root":1}
,"crypttab":{"file":1,"kept":1,"want":1,"encrypted":1}
,"includes":{"mount":1,"necessary":1,"disk\u2019s":1}
,"mount":{"point":1,"partition":1,"root":1,"unlocked":1}
,"point":{"device":1,"develop":1}
,"mmcblk0p1":{"uuid":1}
,"fstab":{"file":1}
,"updated":{"boot":1}
,"directory":{"app":1,"linux_for_tegra":1}
,"helps":{"automount":1}
,"automount":{"process":1}
,"host":{"flash.sh":1,"computer":1}
,"flash.sh":{"diagram":1,"invokes":1,"ekb.key":1,"command":1,"external":1}
,"below":{"shows":1}
,"green":{"utilities":1}
,"utilities":{"used":1,"e.g":1}
,"blue":{"input":1}
,"parts":{"plain":1}
,"plain":{"key":1}
,"script":{"generates":1,"suited":1,"different":1,"initrd":1}
,"generates":{"rootfs":1,"per-device":1}
,"enter":{"string":1,"command":1}
,"accordingly":{"user-supplied":1,"review":1}
,"user-supplied":{"string":1}
,"computer":{"equipped":1}
,"equipped":{"hardware":1}
,"hardware":{"security":1,"data":1}
,"hsm":{"hsm":1,"used":1,"holds":1}
,"management":{"secure":1}
,"assets":{"safe":1}
,"safe":{"transport":1}
,"transport":{"factory":1}
,"factory":{"floor":1}
,"floor":{"necessary":1}
,"leaked":{"unsecure":1}
,"unsecure":{"system":1}
,"production":{"line":1,"environment":1,"devices":1,"device":1}
,"invokes":{"two":1,"dmcrypt":1}
,"helper":{"scripts":1}
,"scripts":{"generate":1,"root":1}
,"gen_luks_passphrase.py":{"follows":1}
,"follows":{"process":1,"steps":1}
,"hwkey-agent":{"luks-srv":1}
,"tas":{"derive":1}
,"disk_encryption.sh":{"outputs":1}
,"outputs":{"disk":1}
,"starting":{"point":1}
,"develop":{"script":1}
,"suited":{"case":1}
,"commands":{"flash.sh":1,"l4t_initrd_flash.sh":1}
,"echo":{"00000000000000000000000000000000":1}
,"00000000000000000000000000000000":{"ekb.key":1}
,"sudo":{"rootfs_enc":1,"blkid":1}
,"rootfs_enc":{"flash.sh":1,"tools":1}
,"ekb.key":{"board":1}
,"option":{"\u2011\u2011i":1}
,"\u2011\u2011i":{"specifies":1}
,"described":{"above":1}
,"above":{"uses":1,"all-zero":1}
,"nvidia":{"recommends":1}
,"recommends":{"customize":1,"giving":1}
,"customize":{"script":1}
,"sake":{"security":1,"simplicity":1}
,"shown":{"example":1}
,"all-zero":{"emphasize":1}
,"emphasize":{"given":1}
,"given":{"change":1}
,"eks":{"partition":1}
,"review":{"overall":1}
,"overall":{"key":1,"flow":1}
,"flow":{"sure":1,"diagram":1,"encrypted":1}
,"sure":{"everything":1}
,"everything":{"works":1}
,"works":{"correctly":1,"either":1}
,"external":{"storage":1}
,"storage":{"device":1}
,"l4t_initrd_flash.sh":{"known":1,"flash":1,"--external-device":1}
,"flashing":{"tool":1,"initrd":1,"booting":1,"encrypted":1,"machines":1,"devices":1}
,"section":{"flashing":1,"modifying":1}
,"topic":{"flashing":1}
,"target":{"device":1}
,"nvme":{"ssd":1}
,"ssd":{"attached":1}
,"attached":{"jetson":1}
,"tools":{"kernel_flash":1,"instructions":1}
,"kernel_flash":{"l4t_initrd_flash.sh":1,"flash_l4t_nvme_rootfs_enc.xml":1,"detailed":1}
,"--external-device":{"nvme0n1p1":1}
,"flash_l4t_nvme_rootfs_enc.xml":{"--external-only":1}
,"--external-only":{"8gib":1}
,"jetson-xavier":{"external":1}
,"instructions":{"flashing":1,"section":1}
,"found":{"directory":1}
,"detailed":{"information":1}
,"readme_initrd_flash.txt":{"directory":1}
,"enhance":{"initrd":1}
,"need":{"initrd":1}
,"initialized":{"rest":1}
,"operating":{"system":1}
,"booted":{"image":1}
,"contain":{"app":1}
,"cboot":{"uses":1}
,"u\u2011boot":{"checks":1}
,"checks":{"first":1}
,"primary":{"gpt":1}
,"gpt":{"app":1}
,"thus":{"partition":1}
,"either":{"bootloader":1}
,"init":{"script":1}
,"steps":{"check":1,"process":1}
,"check":{"encrypted":1}
,"verify":{"root":1}
,"further":{"passphrase":1}
,"requests":{"until":1}
,"additional":{"encrypted":1}
,"kept":{"initrd":1}
,"describes":{"encrypted":1}
,"block":{"devices":1,"device":1}
,"devices":{"during":1,"generated":1}
,"volume-name":{"uuid":1,"name":1,"unique":1}
,"volume":{"decrypted":1,"mounted":1,"specified":1}
,"decrypted":{"data":1}
,"placed":{"block":1}
,"mapper":{"volume-name":1}
,"across":{"lines":1}
,"lines":{"file":1}
,"underlying":{"block":1}
,"containing":{"encrypted":1}
,"examples":{"entries":1}
,"entries":{"crypttab":1}
,"crypt_root":{"uuid":1}
,"crypt_uda":{"uuid":1}
,"several":{"encrypted":1}
,"systems":{"add":1,"flashing":1}
,"add":{"line":1}
,"want":{"bootloader":1,"unlock":1}
,"blkid":{"grep":1}
,"grep":{"type":1}
,"displays":{"line":1}
,"mmcblk0p43":{"uuid":1}
,"5096aa4d-6590-429b-9295-a1fe041b8fa3":{"type":1}
,"crypto_luks":{"partlabel":1}
,"partlabel":{"uda":1}
,"uda":{"partuuid":1}
,"partuuid":{"2b23da7f-2f18-44bf-9e1d-6e3a3a39ad21":1}
,"unpack":{"initrd":1}
,"modifying":{"jetson":1}
,"ram":{"disk":1}
,"subsequent":{"reboots":1,"reboot":1,"disk":1}
,"reboots":{"line":1}
,"unlocked":{"example":1,"file":1}
,"crypt_fs":{"uuid":1}
,"repackage":{"initrd":1}
,"store":{"boot":1}
,"replacing":{"initrd":1}
,"subdirectory":{"mnt":1,"name":1,"named":1}
,"mnt":{"initrd":1,"crypt_fs":1}
,"initialization":{"process":1}
,"simplicity":{"nvidia":1}
,"giving":{"subdirectory":1}
,"mounted":{"volume":1}
,"named":{"crypt_fs":1}
,"mkdir":{"mnt":1}
,"unlocks":{"encrypted":1,"disk":1}
,"unlocking":{"process":1}
,"hardware-based":{"passphrase":1}
,"pass":{"cryptsetup":1}
,"loads":{"key":1}
,"tegra-crypto":{"driver":1}
,"engine":{"hardware":1}
,"routed":{"dmcrypt":1}
,"reads":{"writes":1}
,"manufacturing":{"process":1}
,"illustrates":{"post-development":1}
,"post-development":{"manufacturing":1}
,"jetson-based":{"device":1}
,"blobs":{"flashed":1}
,"flashed":{"onto":1,"time":1}
,"holds":{"security":1}
,"machine":{"able":1}
,"deploy":{"images":1}
,"machines":{"flashing":1}
,"designed":{"per-device":1}
}
;Search.control.loadWordPairs(pairs);
