var pairs =
{
"jetson":{"xavier":1,"linux":1}
,"xavier":{"software":1,"devices":1}
,"software":{"features":1,"plugins":1,"firmware":1,"based":1,"hardware":1,"feature":1,"development":1}
,"nvidia":{"jetson":1,"tegra":1,"libglvnd":1,"gmsl":1}
,"linux":{"driver":1,"targeted":1,"fdt":1}
,"driver":{"package":1,"configuration":1,"suspend":1,"hbr2":1,"support":1,"release":1,"code":1}
,"package":{"l4t":1,"bring":1}
,"l4t":{"supports":1}
,"supports":{"software":1,"splash":1,"bmp":1,"tuning":1,"egl":1,"opengl4.6":1,"opengl":1,"vk1.1.1.1":1,"uvc":1,"pcm":1,"sample":1,"two":1,"stereo":1,"interfaces":1,"audio":1,"normal":1,"four":1,"eight":1,"sampling":1,"gain":1,"mixing":1,"outputs":1,"stream":1,"amixer":1}
,"features":{"provide":1,"probed":1,"eqos":1,"include":1,"following":1,"section":1}
,"provide":{"users":1}
,"users":{"complete":1}
,"complete":{"package":1,"handling":1}
,"bring":{"linux":1}
,"targeted":{"nvidia":1}
,"check":{"release":1}
,"release":{"notes":1,"1.1.73":1,"https":1,"supports":1}
,"notes":{"constraints":1,"instructions":1}
,"constraints":{"related":1}
,"related":{"features":1,"glx":1,"specifications":1,"specification":1,"documentation":1}
,"bootloader":{"binary":1}
,"bpmp":{"processor":1,"i2c":1}
,"processor":{"boot":1}
,"boot":{"binaries":1,"qspi":1,"downloaded":1,"order":1,"support":1,"via":1,"atf":1}
,"binaries":{"mb1":1}
,"mb1":{"nvtboot-bpmp":1}
,"storage":{"location":1,"device":1,"locations":1,"devices":1}
,"cold":{"boot":1}
,"rcm":{"boot":1,"support":1}
,"downloaded":{"usb":1}
,"usb":{"recovery":1,"via":1,"3.0":1,"host":1,"drives":1,"video":1,"ecm":1,"audio":1,"modem":1,"hid":1,"device":1,"camera":1,"dac":1}
,"recovery":{"port":1,"methods":1}
,"next":{"stage":1}
,"stage":{"storage":1}
,"device":{"support":1,"tree":1,"read":1,"property":1,"prepare":1,"life":1,"health":1,"lifetime":1,"activity":1,"wakeup":1,"xusb":1,"3.0":1,"2.0":1,"mode":1}
,"partition":{"table":1}
,"table":{"support":1}
,"gpt":{"protective":1}
,"protective":{"mbr":1}
,"filesystem":{"support":1}
,"bus":{"support":1,"clear":1,"held":1,"speed":1,"reduce":1}
,"console":{"uart":1}
,"cboot":{"boot":1,"display":1,"dynamic":1,"console":1,"drivers":1,"supported":1}
,"kernel":{"dtb":1,"decompression":1,"userspace":1}
,"dtb":{"storage":1,"depending":1,"memory":1,"library":1,"dtb":1}
,"via":{"recovery":1,"cbo":1,"tftp":1,"extlinux.conf":1,"dtb":1,"software":1}
,"tftp":{"dhcp":1,"using":1,"server":1}
,"dhcp":{"static":1}
,"static":{"configured":1,"address":1,"hdcp":1,"pinmux":1}
,"configured":{"cbo":1,"master":1}
,"cbo":{"device":1}
,"tree":{"file":1}
,"configurable":{"via":1}
,"ethernet":{"boot":1,"usb":1,"controller":1}
,"eqos":{"controller":1}
,"controller":{"marvell":1,"interface":1,"configuration":1,"features":1}
,"marvell":{"88e1512p":1}
,"88e1512p":{"realtek":1}
,"realtek":{"rtl8211fd":1}
,"rtl8211fd":{"phy":1}
,"using":{"dhcp":1,"nvboot":1,"cpu":1,"dma":1,"interrupt":1,"khronos":1,"libargus":1,"csi":1,"pwl":1}
,"supported":{"settings":1,"features":1,"modes":1,"driver":1,"vlan":1,"getting":1,"sensors":1}
,"settings":{"linux":1}
,"fdt":{"append":1}
,"append":{"initrd":1}
,"currently":{"limited":1,"edp":1}
,"limited":{"file":1}
,"file":{"entries":1}
,"library":{"driver":1}
,"configuration":{"via":1,"controller":1,"pins":1,"dumping":1,"software":1,"bootrom":1,"packet":1,"byte":1,"fifo":1}
,"decompression":{"support":1}
,"nvboot":{"cpu":1}
,"cpu":{"cpu-bl-ccplex":1,"access":1,"hang":1,"cache":1,"hotplug":1,"gpu":1}
,"secureboot":{"support":1}
,"authenticates":{"kernel":1}
,"depending":{"fuses":1}
,"hdmi":{"support":1,"1.4":1,"2.0":1,"mode":1,"monitors":1,"8-bit":1,"primary":1,"1.4b":1,"interfaces":1}
,"1.4":{"hdmi":1,"480p":1}
,"parses":{"edids":1}
,"edids":{"find":1}
,"find":{"best":1}
,"best":{"hdmi":1}
,"splash":{"screen":1}
,"screen":{"display":1,"decompression":1}
,"display":{"bmp":1,"transition":1,"outputs":1}
,"bmp":{"blob":1,"compression":1}
,"blob":{"supports":1,"decompression":1}
,"displayport":{"support":1,"interfaces":1}
,"edp":{"support":1}
,"data":{"types":1,"link":1,"receive":1,"transfer":1,"put":1,"simultaneously":1,"written":1,"commands":1,"necessary":1,"unmapped":1,"throughput":1,"bytes":1,"data":1,"upper":1}
,"printf":{"support":1}
,"seamless":{"display":1}
,"transition":{"kernel":1}
,"dynamic":{"hardware":1,"clock":1,"pinmux":1}
,"hardware":{"probe":1,"features":1,"information":1,"software":1,"based":1,"control":1,"chip":1,"flow":1,"command":1,"vlan":1}
,"carveouts":{"vpr":1}
,"vpr":{"plugin":1}
,"plugin":{"boards":1,"manager":1}
,"boards":{"eeproms":1}
,"information":{"added":1,"panel":1,"percentage":1,"opengl":1,"supported":1,"case":1,"dol":1,"csi":1}
,"added":{"dtb":1}
,"memory":{"passed":1,"memory":1,"transfer":1}
,"passed":{"kernel":1}
,"support":{"plugin":1,"mode":1,"pins":1,"sc7":1,"hdmi1.4":1,"hdmi":1,"bits":1,"beta":1,"primary":1,"aux":1,"xusb":1,"modem":1,"battery":1,"detecting":1,"data":1,"nfs":1,"9018":1,"lic":1,"gnome-wayland":1,"supports":1,"case":1,"topic":1,"validated":1,"dol":1,"mipi":1,"hdr":1,"u\u2011law":1}
,"uart":{"printf":1,"controller":1}
,"shell":{"capabilities":1,"release":1}
,"view":{"environment":1}
,"environment":{"variables":1}
,"variables":{"current":1}
,"current":{"boot\u2019s":1}
,"boot\u2019s":{"boot":1}
,"order":{"tftp":1}
,"standard":{"expanded":1,"combined":1,"bit":1}
,"spi":{"qspi":1,"master":1,"miso":1,"communication":1,"different":1,"transfer":1}
,"quad":{"ddr":1}
,"hs200":{"hs400":1}
,"hs400":{"ddr50":1,"mode":1}
,"ddr50":{"card":1}
,"ehci":{"xhci":1}
,"xhci":{"host":1}
,"host":{"mode":1,"device":1,"serviced":1,"3.1":1,"3.0":1,"2.0":1,"suspends":1,"resumes":1,"mass":1,"usb":1}
,"class":{"drivers":1}
,"drivers":{"msd":1}
,"msd":{"hub":1}
,"network":{"stack":1}
,"iwip":{"static":1}
,"hdcp":{"dns":1}
,"dns":{"tftp":1}
,"link":{"layer":1,"training":1,"synchronization":1,"rates":1,"rate":1,"width":1}
,"firmware":{"update":1,"upgrade":1}
,"update":{"security":1,"emmc":1}
,"ratcheting":{"support":1}
,"rollback":{"protection":1}
,"eeprom":{"manager":1}
,"detects":{"board":1}
,"tool":{"chains":1}
,"64-bit":{"kernel":1}
,"version":{"4.9.140":1,"10.0.166":1,"egl":1,"release":1,"2.0":1}
,"camera":{"interface":1,"support":1,"devices":1,"features":1,"functionality":1,"app":1,"software":1,"stack":1,"framework":1,"preview":1,"uvc":1,"supported":1}
,"csi":{"input":1,"usb":1,"sensor":1,"port":1}
,"input":{"support":1,"tristate":1,"formats":1,"stream":1,"streams":1}
,"v4l2":{"media-controller":1,"api":1}
,"api":{"bypasses":1,"support":1,"registry":1}
,"bypasses":{"isp":1}
,"csi0":{"csi1":1}
,"csi1":{"csi2":1}
,"csi2":{"csi3":1}
,"csi3":{"csi4":1}
,"csi4":{"csi5":1}
,"pio":{"mode":1,"non-dma":1}
,"fifo":{"access":1,"packed":1,"using":1,"read":1,"mode":1}
,"access":{"using":1,"fifo":1,"permission":1,"interface":1}
,"dma":{"mode":1,"fifo":1}
,"based":{"flow":1,"data":1,"split":1,"control":1,"external":1,"chip":1,"device":1}
,"flow":{"control":1}
,"control":{"line":1,"based":1,"access":1,"transfer":1,"setup":1,"maintain":1,"pause":1,"mvc":1}
,"line":{"toggling":1,"controlled":1,"stretching":1}
,"toggling":{"hardware":1}
,"buffer":{"throttling":1,"binding":1}
,"receive":{"buffer":1,"checksum":1}
,"mode":{"selection":1,"transfer":1,"standard":1,"uart":1,"support":1,"mhz":1,"200":1,"267":1,"esm":1,"ciphertext":1,"gbps":1,"480":1,"mbps":1,"1.5":1,"change":1,"creation":1,"ljm":1,"rjm":1}
,"transfer":{"path":1,"complete":1,"data":1,"power":1,"request":1,"done":1,"bus":1}
,"interrupt":{"mode":1,"based":1,"support":1,"stop":1,"coalescing":1}
,"handling":{"interrupt":1,"polling":1,"using":1,"bus":1}
,"polling":{"mode":1,"ping":1}
,"mcr":{"control":1}
,"modem":{"control":1,"ncm":1,"functionality":1}
,"baud":{"rate":1}
,"rate":{"port":1,"adjustment":1,"fall":1,"8.1":1,"frame":1}
,"port":{"configuration":1,"connected":1,"multiplier":1,"details":1}
,"changing":{"port":1}
,"adjusting":{"baud":1}
,"fall":{"within":1}
,"within":{"tolerance":1}
,"tolerance":{"range":1}
,"i2c":{"master":1,"mmio":1,"controller":1,"slave":1}
,"speed":{"mode":1,"change":1,"bus":1,"based":1,"configuration":1,"plus":1,"host":1,"device":1}
,"repeat":{"start":1}
,"start":{"transfer":1,"stop":1}
,"address":{"cycle":1,"space":1}
,"cycle":{"repeat":1}
,"packet":{"mode":1,"bit":1}
,"7-bit":{"10-bit":1,"addressing":1}
,"10-bit":{"addressing":1}
,"addressing":{"mode":1}
,"apb":{"gpc":1}
,"gpc":{"dma":1}
,"clock":{"gating":1,"always":1,"control":1,"speed":1,"rates":1,"delay":1,"enable":1,"accuracy":1,"calculation":1,"stretching":1,"line":1,"thermal":1}
,"gating":{"clock":1,"support":1}
,"power":{"saving":1,"management":1,"save":1,"down":1,"notification":1,"properly":1,"consumption":1,"switching":1,"gating":1,"state":1,"modes":1,"monitor":1}
,"runtime":{"power":1}
,"change":{"speed":1,"ethtool":1}
,"bit":{"banging":1,"first":1,"length":1,"addressing":1,"generator":1,"serial":1,"rate":1,"message":1}
,"banging":{"data":1}
,"gpio":{"apis":1,"based":1,"request":1,"access":1,"direction":1,"value":1,"register":1,"framework":1}
,"apis":{"data":1,"call":1,"opengl":1,"topic":1}
,"multiple":{"transfer":1,"spi":1}
,"clear":{"support":1,"handling":1}
,"held":{"device":1}
,"64k":{"software":1}
,"non-interruptible":{"transfer":1}
,"packed":{"unpacked":1,"format":1,"commands":1,"groups":1}
,"put":{"fifo":1}
,"unpacked":{"format":1}
,"format":{"packed":1,"reduces":1,"conversion":1}
,"reduces":{"number":1}
,"number":{"accesses":1,"generator":1}
,"accesses":{"fifo":1}
,"full":{"duplex":1,"link":1,"speed":1}
,"duplex":{"mode":1}
,"read":{"write":1,"fifo":1,"parse":1}
,"write":{"data":1,"pmc":1,"commands":1,"transfer":1}
,"least":{"significant":1}
,"significant":{"bit":1,"byte":1}
,"option":{"send":1}
,"send":{"least":1,"sideband":1}
,"first":{"packets":1}
,"dual":{"spi":1,"display":1}
,"miso":{"mosi":1}
,"mosi":{"act":1}
,"byte":{"first":1,"mode":1,"maximum":1}
,"setup":{"hold":1}
,"hold":{"time":1}
,"maintain":{"setup":1}
,"chip":{"select":1,"specific":1}
,"select":{"polarity":1,"active":1}
,"polarity":{"section":1}
,"active":{"high":1,"low":1}
,"high":{"active":1,"priority":1,"speed":1}
,"low":{"based":1,"power":1,"speed":1,"light":1}
,"external":{"device":1}
,"communication":{"support":1}
,"written":{"read":1}
,"non-dma":{"mode":1}
,"controlled":{"gpio":1}
,"different":{"clock":1,"packet":1,"properties":1}
,"interface":{"clock":1,"running":1,"devices":1,"mode":1,"khronos":1,"egl":1,"sensors":1,"configured":1}
,"prod":{"configuration":1,"setting":1}
,"platform":{"chip":1,"window":1,"graphics":1}
,"specific":{"configuration":1}
,"delay":{"packets":1}
,"provision":{"delay":1}
,"enable":{"disable":1,"gnome-wayland":1}
,"disable":{"power":1}
,"done":{"handling":1,"interrupt":1}
,"request":{"single":1,"free":1}
,"single":{"call":1}
,"pinmux":{"integration":1,"required":1,"function":1,"config":1,"different":1,"context":1,"configuration":1,"register":1}
,"integration":{"gpios":1}
,"call":{"pinmux":1}
,"required":{"pin":1}
,"pin":{"configuration":1,"user":1}
,"direction":{"configuration":1}
,"value":{"pin":1}
,"wakeup":{"support":1,"triggered":1,"sc7":1}
,"register":{"dump":1,"access":1,"ext_csd":1}
,"framework":{"sysfs":1,"support":1,"related":1}
,"sysfs":{"support":1}
,"suspend":{"resume":1}
,"function":{"configuration":1}
,"config":{"configuration":1,"bootrom":1}
,"properties":{"pull":1}
,"pull":{"down":1}
,"down":{"input":1,"configuration":1}
,"tristate":{"configuration":1}
,"save":{"restore":1,"power":1}
,"restore":{"pinmux":1}
,"drive":{"strength":1}
,"strength":{"configuration":1}
,"pinmux-gpio":{"integration":1}
,"apbdma":{"gpcdma":1}
,"cyclic-once":{"mode":1}
,"cyclic":{"mode":1}
,"queue":{"mechanism":1,"channels":1}
,"mechanism":{"transfer":1,"vital":1,"enabled":1}
,"tegra":{"wdt":1,"watchdog":1}
,"watchdog":{"framework":1,"interrupt":1,"polling":1,"reboot":1,"kick":1}
,"registration":{"wdt":1,"framework":1}
,"wdt":{"framework":1,"expiry":1,"reset":1,"start":1}
,"system":{"reset":1,"active":1,"boot":1,"handles":1,"https":1}
,"reset":{"cpu":1,"wdt":1,"isr":1}
,"resume":{"support":1,"handling":1,"low":1,"shutdown":1}
,"ping":{"support":1}
,"stop":{"pin":1,"ongoing":1}
,"user":{"space":1,"address":1,"experience":1}
,"pwm":{"ops":1,"registration":1}
,"accuracy":{"calculation":1}
,"controlling":{"pad":1}
,"pad":{"voltage":1}
,"voltage":{"pwr_detect":1,"configuration":1}
,"dpd":{"configuration":1}
,"deep":{"power":1,"color":1}
,"pmc":{"registers":1,"register":1,"config":1,"configuration":1}
,"bootrom":{"i2c":1}
,"mmio":{"command":1}
,"spe":{"dma":1}
,"continuous":{"mode":1}
,"normal":{"byte":1,"stereo":1}
,"edid":{"support":1}
,"parse":{"edid":1}
,"hot-plug":{"detection":1}
,"detection":{"hdmi":1,"monitors":1}
,"480p":{"720p":1}
,"720p":{"1080p":1}
,"1080p":{"4k@30hz":1}
,"hdmi1.4":{"following":1}
,"following":{"modes":1,"topics":1,"sections":1}
,"modes":{"480p":1,"profiles":1,"dsp\u2011a":1}
,"2.0":{"30hz":1,"resolution":1,"compliance":1,"mode":1,"1.2":1,"part":1}
,"30hz":{"60hz":1}
,"8-bit":{"yuv":1}
,"yuv":{"420":1}
,"primary":{"display":1,"volume":1}
,"mirroring":{"support":1}
,"1.4b":{"compliance":1}
,"color":{"support":1}
,"bits":{"cell":1,"s16_le":1,"s32_le":1,"sample":1,"s24_le":1,"bits":1,"s24_3le":1}
,"cell":{"rgb":1,"yuv422":1}
,"rgb":{"yuv444":1,"supported":1,"yuv422":1}
,"yuv444":{"bits":1}
,"sideband":{"information":1}
,"panel":{"during":1,"overlay":1}
,"during":{"video":1,"background":1,"power-on":1}
,"video":{"refresh":1,"class":1,"decoders":1,"decode":1,"encoders":1,"encode":1,"format":1,"scaling":1,"cropping":1,"rotation":1}
,"refresh":{"info":1}
,"info":{"frames":1}
,"frames":{"audio":1,"second":1}
,"audio":{"data":1,"class":1,"usb":1,"playback":1,"demultiplexer":1,"demultiplexing":1,"multiplexer":1,"multiplexing":1,"streams":1,"mixer":1}
,"hot":{"plug":1}
,"plug":{"support":1}
,"hbr3":{"support":1}
,"beta":{"level":1}
,"level":{"may":1,"power":1}
,"may":{"compatibility":1,"removed":1}
,"compatibility":{"issues":1,"drm":1}
,"enhanced":{"framing":1,"strobe":1}
,"error":{"recovery":1,"reporting":1}
,"handshake":{"signaling":1}
,"signaling":{"host":1}
,"hpd_irq":{"event":1}
,"feedback":{"panels":1}
,"panels":{"case":1}
,"case":{"link":1,"csi":1,"infinite":1}
,"synchronization":{"loss":1,"egl":1}
,"rates":{"1.62":1,"supported":1,"44.1":1,"11.025":1,"11.05":1,"11.025,16":1}
,"1.62":{"2.7":1}
,"2.7":{"5.4":1}
,"5.4":{"gbps":1}
,"various":{"link":1}
,"8.1":{"gbps":1}
,"aux":{"link":1}
,"controllers":{"link":1,"disabled":1}
,"max":{"link":1}
,"width":{"link":1,"coming":1}
,"coming":{"soc":1}
,"legacy":{"interrupts":1}
,"applicable":{"controllers":1}
,"msi":{"msi-x":1}
,"msi-x":{"interrupts":1}
,"128":{"byte":1,"256":1}
,"maximum":{"payload":1,"frequency":1,"signal":1,"data":1}
,"payload":{"size":1}
,"256":{"byte":1,"384":1,"sample":1}
,"gen-1":{"speed":1}
,"gen-2":{"speed":1}
,"gen-3":{"speed":1}
,"aspm":{"l0s":1,"l1.1":1,"l1.2":1}
,"disabled":{"default":1,"odmdata":1}
,"wake":{"support":1,"idle":1,"sleep":1}
,"advanced":{"error":1}
,"reporting":{"aer":1}
,"end":{"point":1}
,"point":{"mode":1,"addition":1,"double":1,"multiplication":1,"verification":1}
,"provided":{"converter":1}
,"converter":{"available":1,"sfc":1}
,"available":{"m.2":1}
,"m.2":{"key-m":1}
,"key-m":{"slot":1}
,"emmc":{"interface":1,"helps":1,"device":1,"firmware":1,"cqic":1}
,"running":{"ddr":1,"sdr":1,"simultaneously":1}
,"ddr":{"mode":1}
,"sdr":{"mode":1}
,"200":{"mhz":1}
,"267":{"mhz":1}
,"tuning":{"sdmmc":1}
,"sdmmc":{"controller":1}
,"commands":{"packed":1,"group":1}
,"groups":{"either":1}
,"either":{"read":1}
,"group":{"transfer":1}
,"reduce":{"overhead":1}
,"similar":{"cpu":1}
,"cache":{"implemented":1}
,"implemented":{"emmc":1}
,"helps":{"improve":1}
,"improve":{"performance":1,"user":1}
,"erases":{"data":1}
,"necessary":{"during":1}
,"background":{"erase":1}
,"erase":{"events":1,"cycles":1}
,"physically":{"removes":1}
,"removes":{"data":1}
,"unmapped":{"user":1}
,"secure":{"access":1,"hash":1,"monitor":1}
,"allows":{"execution":1,"device":1}
,"execution":{"back":1}
,"back":{"ground":1}
,"ground":{"operations":1}
,"operations":{"host":1}
,"priority":{"interrupt":1}
,"ongoing":{"bkops":1}
,"bkops":{"reliable":1}
,"reliable":{"writes":1}
,"prepare":{"itself":1}
,"itself":{"power":1}
,"properly":{"improve":1,"release":1}
,"experience":{"during":1}
,"minimizes":{"power":1}
,"consumption":{"emmc":1}
,"feature":{"save":1,"details":1}
,"switching":{"clocks":1}
,"clocks":{"transactions":1}
,"transactions":{"bus":1}
,"field":{"firmware":1}
,"life":{"estimation":1}
,"estimation":{"type":1}
,"health":{"mechanism":1,"information":1}
,"vital":{"nand":1}
,"nand":{"flash":1}
,"flash":{"program":1,"lifespan":1}
,"program":{"erase":1}
,"cycles":{"information":1}
,"percentage":{"useful":1}
,"useful":{"flash":1}
,"type":{"slc":1,"mlc":1}
,"slc":{"device":1}
,"mlc":{"device":1}
,"pre":{"eol":1}
,"eol":{"information":1}
,"provides":{"indication":1,"feature":1}
,"indication":{"device":1}
,"lifetime":{"reflected":1}
,"reflected":{"average":1}
,"average":{"blocks":1}
,"command":{"queue":1,"gst-inspect-1.0":1,"provides":1}
,"performed":{"mmc":1}
,"mmc":{"controller":1}
,"strobe":{"mode":1}
,"esm":{"hs400":1}
,"optional":{"devices":1}
,"devices":{"indicated":1}
,"indicated":{"strobe_support":1}
,"strobe_support":{"184":1}
,"184":{"register":1}
,"cqic":{"feature":1}
,"generates":{"coalesced":1}
,"coalesced":{"interrupts":1}
,"interrupts":{"interrupt":1}
,"coalescing":{"mechanism":1}
,"security":{"engine":1}
,"cbc-aes":{"host1x":1}
,"cipher":{"block":1}
,"block":{"chaining":1}
,"ebc-aes":{"host1x":1}
,"electronic":{"code":1}
,"code":{"book":1,"imx390":1}
,"ofb-aes":{"host1x":1}
,"output":{"feedback":1,"formats":1,"streams":1,"stream":1}
,"ctr-aes":{"host1x":1}
,"counter":{"mode":1}
,"cmac-aes":{"host1x":1}
,"cipher-based":{"message":1}
,"message":{"authentication":1,"identifiers":1}
,"authentication":{"code":1}
,"xts-aes":{"host1x":1}
,"xex-based":{"tweaked-codebook":1}
,"tweaked-codebook":{"mode":1}
,"ciphertext":{"stealing":1}
,"drbg":{"rng":1}
,"rng":{"host1x":1}
,"deterministic":{"random":1}
,"random":{"bit":1,"number":1}
,"sha":{"host1x":1}
,"hash":{"algorithm":1}
,"algorithm":{"variants":1,"sizes":1}
,"variants":{"sha1":1}
,"sha1":{"224":1}
,"224":{"256":1}
,"384":{"512":1}
,"rsa":{"host1x":1,"public":1,"apb":1}
,"public":{"key":1}
,"key":{"algorithm":1}
,"sizes":{"512":1,"3072":1,"bits":1}
,"512":{"1024":1}
,"1024":{"1536":1}
,"1536":{"2048":1}
,"true":{"random":1}
,"3072":{"4096":1}
,"montgomery":{"precomputation":1,"operations":1}
,"modular":{"addition":1,"operations":1,"division":1,"subtraction":1,"inversion":1,"reduction":1,"multiplication":1,"exponentiation":1,"square":1}
,"ecc":{"point":1,"shamir":1}
,"elliptic":{"curve":1}
,"curve":{"cryptography":1,"operations":1,"diffie-hellman":1,"digital":1}
,"cryptography":{"operations":1}
,"serial":{"modular":1}
,"reduction":{"double":1,"effective":1}
,"double":{"precision":1}
,"shamir":{"trick":1}
,"ecc-521":{"weierstrass":1}
,"weierstrass":{"point":1,"shamir\u2019s":1}
,"shamir\u2019s":{"trick":1}
,"non-modular":{"multiplication":1}
,"c25519":{"point":1,"modular":1}
,"x25519":{"operations":1}
,"ed25519":{"point":1,"modular":1,"shamir\u2019s":1}
,"edwards":{"curve":1}
,"diffie-hellman":{"algorithm":1}
,"digital":{"signature":1}
,"signature":{"algorithm":1}
,"super":{"speed":1}
,"plus":{"host":1}
,"3.1":{"gen2":1}
,"gen2":{"mode":1}
,"3.0":{"mode":1}
,"480":{"mbps":1}
,"1.2":{"mode":1}
,"1.5":{"mbps":1,"specification":1}
,"auto":{"suspend":1,"resume":1}
,"suspends":{"port":1}
,"connected":{"device":1,"system":1}
,"remote":{"wakeup":1}
,"resumes":{"port":1,"streaming":1,"working":1}
,"triggered":{"device":1,"host":1}
,"elpg":{"xusb":1}
,"xusb":{"partition":1}
,"engine":{"level":1,"gte":1}
,"lower":{"power":1}
,"state":{"state":1}
,"lpm":{"states":1}
,"states":{"states":1}
,"drives":{"may":1}
,"removed":{"connected":1}
,"multiplier":{"support":1}
,"hub":{"usb":1}
,"mass":{"storage":1}
,"protocol":{"storage":1,"camera":1,"ethernet":1,"audio":1,"support":1,"version":1}
,"ncm":{"protocol":1}
,"hid":{"protocol":1}
,"human":{"interface":1}
,"bc1.2":{"charging":1,"spec":1}
,"charging":{"support":1,"per":1}
,"battery":{"charging":1}
,"per":{"bc1.2":1}
,"apple":{"charger":1}
,"detecting":{"apple":1}
,"mtp":{"device":1,"protocol":1}
,"adb":{"device":1,"protocol":1}
,"rndis":{"device":1,"protocol":1}
,"nfs":{"boot":1}
,"100":{"mbps":1}
,"mbps":{"support":1,"mbps":1,"meters":1}
,"1000":{"mbps":1}
,"half-duplex":{"support":1}
,"arp":{"offload":1}
,"ieee":{"1588-2008":1}
,"1588-2008":{"ptp":1}
,"energy-efficient":{"ethernet":1}
,"transmit":{"checksum":1}
,"checksum":{"offload":1}
,"tcp":{"segmentation":1}
,"segmentation":{"offload":1}
,"jumbo":{"frame":1}
,"frame":{"support":1,"rate":1}
,"9018":{"untagged":1}
,"untagged":{"9022":1}
,"9022":{"tagged":1}
,"pause":{"frame":1}
,"eavb":{"support":1}
,"channels":{"size":1,"i2s":1,"output":1,"eight-port":1,"supports":1,"till":1}
,"vlan":{"insertion":1,"tag":1,"tag-based":1}
,"insertion":{"stripping":1}
,"stripping":{"vlan":1}
,"tag":{"hardware":1}
,"tag-based":{"filtering":1}
,"filtering":{"supported":1}
,"10w":{"15wprofiles":1}
,"15wprofiles":{"provided":1}
,"nvpmodel":{"interface":1}
,"selection":{"custom":1}
,"custom":{"mode":1}
,"reboot":{"hang":1,"support":1}
,"pmic":{"watchdog":1}
,"hang":{"disabled":1}
,"odmdata":{"default":1}
,"shutdown":{"support":1}
,"gpu":{"frequency":1}
,"frequency":{"governor":1,"bit":1,"250":1,"mbps":1,"converter":1,"conversion":1}
,"emc":{"bandwidth":1}
,"bandwidth":{"manager":1}
,"thermal":{"management":1}
,"initrd":{"support":1}
,"atf":{"secure":1}
,"experimental":{"generic":1,"support":1}
,"generic":{"timestamping":1}
,"timestamping":{"engine":1}
,"gte":{"support":1}
,"lic":{"irq":1}
,"irq":{"lines":1}
,"lines":{"aon":1}
,"aon":{"gpios":1}
,"graphics":{"apis":1,"context":1,"interface":1}
,"glvnd":{"version":1}
,"vendor":{"neutral":1}
,"neutral":{"dispatch":1}
,"dispatch":{"library":1}
,"nvdc":{"direct":1}
,"direct":{"rendering":1}
,"rendering":{"manager":1,"apis":1,"synchronization":1,"using":1}
,"manager":{"drm":1}
,"drm":{"2.0":1}
,"egl":{"stream":1,"egl":1,"without":1,"details":1,"interface":1,"enables":1,"1.5":1}
,"x11":{"abi-24":1,"wayland":1,"backend":1,"window":1}
,"without":{"x11":1}
,"extensions":{"supported":1}
,"getting":{"components":1}
,"components":{"work":1}
,"vulkan":{"loader":1,"details":1,"driver":1,"specs":1,"conformance":1}
,"loader":{"version":1}
,"1.1.73":{"verified":1}
,"verified":{"working":1}
,"working":{"properly":1}
,"https":{"developer.nvidia.com":1,"github.com":1,"www.khronos.org":1,"www.sony-semicon.co.jp":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"vulkan":1}
,"github.com":{"nvidia":1}
,"libglvnd":{"details":1}
,"details":{"glvnd":1,"related":1,"x11":1,"https":1,"example":1,"h.264":1,"argus":1,"citation":1}
,"gnome-wayland":{"desktop":1,"support":1}
,"desktop":{"shell":1}
,"instructions":{"enable":1}
,"khronos":{"rendering":1,"apis":1,"native":1,"opengl":1}
,"opengl":{"underlying":1,"driver":1,"specs":1,"index_gl.php":1,"common":1,"khronos":1,"api":1}
,"underlying":{"native":1}
,"native":{"platform":1}
,"window":{"system":1}
,"handles":{"graphics":1}
,"context":{"management":1}
,"management":{"surface":1}
,"surface":{"buffer":1}
,"binding":{"rendering":1}
,"enables":{"high-performance":1}
,"high-performance":{"accelerated":1}
,"accelerated":{"mixed-mode":1,"gstreamer":1}
,"mixed-mode":{"rendering":1}
,"specification":{"khronos":1,"3.2":1,"found":1}
,"opengl4.6":{"https":1}
,"www.khronos.org":{"registry":1,"conformance":1}
,"registry":{"opengl":1,"conformance":1,"vulkan":1}
,"specs":{"glspec46.core.pdf":1,"1.1":1}
,"glspec46.core.pdf":{"details":1}
,"glx":{"related":1}
,"specifications":{"found":1}
,"found":{"https":1}
,"index_gl.php":{"conformance":1}
,"conformance":{"details":1,"adopters":1}
,"wayland":{"windowing":1,"backend":1}
,"windowing":{"system":1}
,"adopters":{"conformant-products":1}
,"conformant-products":{"opengl":1,"opengles":1,"vulkan":1}
,"common":{"profile":1}
,"profile":{"specification":1}
,"3.2":{"information":1}
,"vk1.1.1.1":{"https":1}
,"1.1":{"pdf":1}
,"pdf":{"vkspec.pdf":1}
,"vkspec.pdf":{"details":1}
,"topics":{"list":1}
,"list":{"several":1}
,"several":{"classes":1}
,"classes":{"multimedia":1}
,"multimedia":{"features":1}
,"sampling":{"frequency":1}
,"nv12":{"nvmm:nv12":1,"nvmm:1420":1,"nvmm:i420":1}
,"3840":{"2160":1}
,"2160":{"fps":1,"resolution":1}
,"fps":{"120":1}
,"120":{"mbps":1}
,"full-frame":{"disable-dpb":1}
,"disable-dpb":{"skip-frames":1}
,"skip-frames":{"enable-error-check":1}
,"enable-error-check":{"enable-frame-type-reporting":1}
,"nvmm:nv12":{"nvmm:i420_10le":1}
,"7680":{"4320":1}
,"4320":{"fps":1}
,"240":{"mbps":1}
,"i420":{"nvmm:i420":1,"nv12":1}
,"600":{"sec":1}
,"160":{"mbps":1}
,"1920":{"1080":1,"1440":1}
,"1080":{"fps":1}
,"nvmm:1420":{"nvmm:nv12":1}
,"nvmm:i420":{"nvmm:nv12":1}
,"140":{"mbps":1}
,"gst-inspect-1.0":{"utility":1,"omxh264enc":1,"nvv4l2h264enc":1}
,"utility":{"understand":1}
,"understand":{"feature":1}
,"example":{"gst-inspect-1.0":1}
,"omxh264enc":{"command":1}
,"nvv4l2h264enc":{"command":1}
,"h.264":{"encoder":1}
,"wayland-weston":{"window":1}
,"conversion":{"scaling":1,"gstreamer-1.0":1,"pcm":1}
,"scaling":{"cropping":1,"gstreamer-1.0":1}
,"cropping":{"rotation":1,"gstreamer-1.0":1}
,"rotation":{"formats":1,"gstreamer-1.0":1}
,"flip-method":{"interpolation-method":1}
,"interpolation-method":{"crop":1}
,"crop":{"format":1}
,"additional":{"information":1}
,"sections":{"topic":1}
,"topic":{"accelerated":1,"camera":1}
,"basic":{"camera":1,"standard":1}
,"sensors":{"ov5693":1,"using":1,"validated":1,"https":1,"running":1}
,"ov5693":{"imx274":1,"sensors":1}
,"imx274":{"demonstrated":1,"information":1,"sensors":1}
,"demonstrated":{"argus":1}
,"argus":{"camera":1,"refer":1}
,"app":{"details":1}
,"refer":{"applications":1}
,"applications":{"using":1}
,"libargus":{"low-level":1}
,"low-level":{"apis":1}
,"development":{"solution":1}
,"infinite":{"timeout":1}
,"sensor":{"stops":1,"resumes":1}
,"stops":{"streaming":1}
,"streaming":{"indefinitely":1,"camera":1}
,"indefinitely":{"camera":1}
,"stack":{"idle":1,"resumes":1}
,"idle":{"csi":1}
,"timeout":{"support":1}
,"gmsl":{"camera":1}
,"validated":{"two":1,"sony":1}
,"two":{"simultaneous":1,"preview":1,"imx274":1,"output":1,"channels":1,"mvc":1}
,"simultaneous":{"imx390":1}
,"imx390":{"sensors":1,"included":1}
,"citation":{"nvidia":1}
,"documentation":{"official":1}
,"official":{"reference":1}
,"reference":{"driver":1,"topic":1}
,"included":{"future":1}
,"future":{"release":1}
,"dol":{"wdr":1,"sensors":1}
,"sony":{"imx274":1,"imx":1,"imx185":1}
,"www.sony-semicon.co.jp":{"products_en":1}
,"products_en":{"sensor2":1}
,"sensor2":{"technology":1}
,"technology":{"dol-hdr.html":1,"validated":1}
,"cphy":{"sensor":1,"interface":1}
,"mipi":{"cphy":1}
,"imx":{"318":1}
,"318":{"reaching":1}
,"reaching":{"performance":1}
,"performance":{"frames":1}
,"second":{"preview":1,"3840":1,"1920":1}
,"pwl":{"wdr":1}
,"hdr":{"using":1}
,"wdr":{"technology":1}
,"tnr":{"support":1}
,"vic-based":{"temporal":1}
,"temporal":{"noise":1}
,"noise":{"reduction":1}
,"effective":{"low":1}
,"light":{"scenes":1}
,"preview":{"fps":1,"performance":1}
,"resolution":{"two":1,"six":1}
,"six":{"camera":1,"ov5693":1}
,"1440":{"resolution":1}
,"uvc":{"compliant":1}
,"compliant":{"usb2.0":1}
,"usb2.0":{"usb3.0":1}
,"usb3.0":{"cameras":1}
,"section":{"nvgstcapture-1.0":1}
,"nvgstcapture-1.0":{"reference":1}
,"identifiers":{"originally":1}
,"originally":{"specified":1}
,"specified":{"operate":1}
,"operate":{"maximum":1}
,"250":{"kbps":1}
,"signal":{"frequency":1}
,"increases":{"maximum":1}
,"throughput":{"3.7":1}
,"3.7":{"mbps":1}
,"meters":{"maximum":1}
,"conforms":{"protocol":1}
,"part":{"iso":1}
,"iso":{"11898-1":1}
,"11898-1":{"data":1}
,"bytes":{"supported":1}
,"hda":{"hdmi":1}
,"pcm":{"playback":1,"audio":1}
,"playback":{"stereo":1,"capture":1}
,"stereo":{"5.1":1,"capture":1,"playback":1,"i2s":1,"pcm":1}
,"5.1":{"7.1":1}
,"7.1":{"channel":1}
,"channel":{"configurations":1}
,"sample":{"sizes":1,"rates":1}
,"s16_le":{"bits":1}
,"s32_le":{"sample":1,"osr":1}
,"44.1":{"88.2":1,"khz":1,"192":1}
,"88.2":{"khz":1,"176.4":1}
,"khz":{"displayport":1,"hdmi":1,"supports":1}
,"interfaces":{"44.1":1,"dmic1":1,"dspk1":1,"i2s1":1}
,"176.4":{"192":1}
,"192":{"khz":1}
,"note":{"24-bit":1}
,"24-bit":{"samples":1}
,"samples":{"stored":1}
,"stored":{"32-bit":1}
,"32-bit":{"data":1}
,"upper":{"bits":1,"24-bits":1}
,"dmic":{"support":1}
,"s24_le":{"bits":1}
,"osr":{"128":1}
,"dmic1":{"dmic2":1}
,"dmic2":{"dmic3":1}
,"dspk":{"support":1}
,"24-bits":{"sample":1}
,"dspk1":{"dspk2":1}
,"i2s":{"support":1,"left":1,"interface":1}
,"capture":{"loopback":1}
,"11.025":{"22.05":1,"22.5":1}
,"22.05":{"44.1":1,"32,44.1":1}
,"left":{"justified":1}
,"justified":{"mode":1}
,"ljm":{"right":1}
,"right":{"justified":1}
,"rjm":{"tdm":1}
,"tdm":{"modes":1}
,"dsp\u2011a":{"dsp\u2011b":1}
,"dsp\u2011b":{"channels":1}
,"master":{"slave":1}
,"slave":{"support":1}
,"u\u2011law":{"a\u2011law":1}
,"a\u2011law":{"compression":1}
,"compression":{"decompression":1}
,"i2s1":{"i2s2":1}
,"i2s2":{"i2s4":1}
,"i2s4":{"i2s6":1}
,"demultiplexer":{"adx":1}
,"demultiplexing":{"input":1}
,"stream":{"channels":1}
,"streams":{"channels":1,"two":1,"supports":1}
,"22.5":{"44.1":1}
,"four":{"adx":1,"amx":1,"sfc":1}
,"adx":{"instances":1}
,"instances":{"adx1":1,"amx1":1,"sfc1":1,"mvc1":1}
,"adx1":{"adx2":1}
,"adx2":{"adx3":1}
,"adx3":{"adx4":1}
,"multiplexer":{"amx":1}
,"multiplexing":{"input":1}
,"amx":{"instances":1}
,"amx1":{"amx2":1}
,"amx2":{"amx3":1}
,"amx3":{"amx4":1}
,"s24_3le":{"sample":1}
,"eight":{"channels":1,"stream":1}
,"eight-port":{"usb":1}
,"sfc":{"instances":1}
,"sfc1":{"sfc2":1}
,"sfc2":{"sfc3":1}
,"sfc3":{"sfc4":1}
,"volume":{"control":1}
,"gain":{"attenuation":1}
,"attenuation":{"range":1}
,"range":{"120db":1}
,"120db":{"40db":1}
,"11.05":{"22.05":1}
,"32,44.1":{"88.2":1}
,"mvc":{"instances":1}
,"mvc1":{"mvc2":1}
,"mixing":{"input":1}
,"outputs":{"contain":1}
,"contain":{"combination":1}
,"combination":{"input":1}
,"11.025,16":{"22.05":1}
,"amixer":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
