var pairs =
{
"kernel":{"customization":1,"used":1,"sources":1,"source":1,"subdirectory":1,"build":1,"including":1,"image":1,"dtb":1,"modules":1,"directory":1,"kernel_supplements.tbz2":1,"kernel-dtb":1,"headers":1,"module":1,"kernel_headers.tbz2":1,"parameters":1,"package":1,"release":1,"packages":1,"device":1,"want":1,"primary":1}
,"manually":{"rebuild":1,"downloading":1,"extract":1,"download":1,"built":1}
,"rebuild":{"kernel":1}
,"used":{"nvidia":1,"typical":1,"provide":1}
,"nvidia":{"jetson":1,"kernel":1,"recommends":1,"real-time":1,"repository":1}
,"jetson":{"linux":1,"xavier":1,"agx":1,"system":1,"rt-kernel":1}
,"linux":{"driver":1,"tag":1,"kernel":1}
,"driver":{"package":1}
,"package":{"l4t":1,"prior":1}
,"l4t":{"internet":1,"source":1,"toolchain":1,"kernel":1,"real-time":1,"packages":1}
,"internet":{"access":1}
,"access":{"required":1}
,"obtaining":{"kernel":1}
,"sources":{"git":1,"source":1,"e.g":1}
,"installed":{"git":1,"utilities":1,"kernel":1,"modules":1,"real-time":1}
,"git":{"install":1,"following":1,"port":1,"tag":1}
,"install":{"git":1,"git-core":1,"utilities":1,"build-essential":1,"kernel":1,"remove":1,"real-time":1,"nvidia-l4t-rt-kernel":1}
,"following":{"command":1,"environment":1,"commands":1,"archive":1,"topics":1}
,"sudo":{"apt":1,"arch":1,"vim":1}
,"apt":{"install":1,"source":1,"sources.list.d":1,"update":1,"remove":1}
,"system":{"default":1,"export":1,"files":1,"crash":1,"nvidia":1}
,"default":{"git":1,"property":1,"real-time":1}
,"port":{"9418":1}
,"9418":{"open":1}
,"open":{"outbound":1,"apt":1}
,"outbound":{"connections":1}
,"sync":{"kernel":1,"linux":1,"git":1}
,"source":{"running":1,"revision":1,"files":1,"file":1,"public":1,"extracted":1,"code":1,"tree":1,"source":1,"required":1,"configuration":1}
,"running":{"source_sync.sh":1,"apply_binaries.sh":1}
,"source_sync.sh":{"script":1}
,"prompted":{"enter":1}
,"enter":{"tag":1,"command":1}
,"tag":{"name":1,"however":1,"provided":1,"tegra-l4t":1}
,"name":{"provided":1}
,"provided":{"release":1,"following":1}
,"release":{"notes":1,"binary":1,"tags":1,"package":1,"32.5":1,"version":1}
,"however":{"tag":1}
,"notes":{"syncs":1}
,"syncs":{"sources":1}
,"revision":{"release":1}
,"binary":{"built":1,"files":1}
,"built":{"list":1,"nvidia":1}
,"list":{"available":1}
,"available":{"release":1}
,"downloading":{"expanding":1}
,"expanding":{"kernel":1}
,"alternative":{"download":1}
,"download":{"kernel":1,"expand":1,"l4t":1,"build":1}
,"files":{"manually":1,"release":1,"signed":1,"signature":1,"topic":1,"directory":1}
,"extract":{"possible":1,"tbz2":1,"kernel":1,"following":1}
,"possible":{"recommended":1}
,"recommended":{"instead":1}
,"instead":{"sync":1}
,"expand":{"kernel":1}
,"browser":{"navigate":1}
,"https":{"developer.nvidia.com":1,"repo.download.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"downloads":1}
,"locate":{"download":1}
,"tbz2":{"file":1}
,"tar":{"-xjf":1,"xjf":1,"--owner":1}
,"-xjf":{"public_sources.tbz2":1,"top":1}
,"linux_for_tegra":{"source":1,"kernel":1,"rootfs":1}
,"xjf":{"kernel_src.tbz2":1}
,"extracted":{"kernel":1,"release":1}
,"building":{"nvidia":1,"out-of-tree":1,"entire":1,"external":1}
,"follow":{"steps":1,"instructions":1}
,"steps":{"procedure":1}
,"procedure":{"build":1}
,"build":{"nvidia":1,"process":1,"jetson":1,"reference":1,"kernel":1,"external":1,"out-of-tree":1}
,"downloaded":{"kernel":1}
,"utilities":{"required":1,"command":1}
,"required":{"kernel":1,"shell":1}
,"shell":{"variable":1,"environment":1}
,"variable":{"command":1,"described":1}
,"tegra_kernel_out":{"outdir":1}
,"outdir":{"desired":1}
,"desired":{"destination":1}
,"destination":{"compiled":1}
,"compiled":{"kernel":1}
,"cross-compiling":{"non-jetson":1,"ensure":1}
,"non-jetson":{"system":1}
,"export":{"following":1,"cross_compile":1,"localversion":1}
,"environment":{"variables":1,"variable":1}
,"cross_compile":{"cross_prefix":1,"environment":1}
,"localversion":{"-tegra":1}
,"cross_prefix":{"absolute":1}
,"absolute":{"path":1}
,"path":{"arm64":1}
,"arm64":{"toolchain":1,"$tegra_kernel_out":1,"boot":1,"kernel_directory":1}
,"toolchain":{"without":1,"cross_prefix":1,"information":1}
,"without":{"gcc":1,"further":1,"building":1,"re-installing":1}
,"gcc":{"suffix":1}
,"suffix":{"example":1}
,"example":{"reference":1}
,"reference":{"arm64":1,"toolchains":1}
,"toolchain_install_path":{"bin":1}
,"bin":{"aarch64-linux-gnu-":1}
,"information":{"download":1}
,"recommends":{"using":1}
,"using":{"linaro":1,"following":1,"l4t":1}
,"linaro":{"7.3.1":1}
,"7.3.1":{"2018.05":1}
,"2018.05":{"toolchain":1}
,"execute":{"following":1}
,"commands":{"create":1,"build":1,"install":1,"strip":1}
,"create":{".config":1}
,".config":{"file":1}
,"mkdir":{"$tegra_kernel_out":1}
,"arch":{"arm64":1}
,"$tegra_kernel_out":{"tegra_defconfig":1,"arch":1,"modules_install":1,"kernel":1,"modules_prepare":1}
,"kernel_source":{"directory":1}
,"directory":{"contains":1,"extracted":1,"build":1,"commands":1}
,"contains":{"kernel":1}
,"e.g":{"kernel-4.9":1}
,"including":{"dtbs":1}
,"dtbs":{"modules":1}
,"indicates":{"number":1}
,"number":{"parallel":1,"cpus":1}
,"parallel":{"processes":1}
,"processes":{"used":1}
,"typical":{"value":1}
,"value":{"number":1}
,"cpus":{"system":1}
,"replace":{"release_packagep":1,"contents":1,"kernel":1,"0x1090000":1}
,"release_packagep":{"linux_for_tegra":1}
,"image":{"copy":1,"original":1,"without":1}
,"boot":{"image":1,"dts":1,"extlinux":1,"default":1}
,"contents":{"linux_for_tegra":1,"lib":1}
,"dtb":{"contents":1}
,"install_mod_path":{"top":1}
,"top":{"linux_for_tegra":1}
,"optionally":{"archive":1}
,"archive":{"installed":1,"replace":1,"place":1}
,"modules":{"using":1,"used":1,"kernel_version":1,"without":1,"specify":1,"uname":1,"building":1,"compatible":1}
,"--owner":{"root":1}
,"root":{"--group":1,"-cjf":1}
,"--group":{"root":1}
,"-cjf":{"kernel_supplements.tbz2":1}
,"lib":{"modules":1}
,"provide":{"contents":1}
,"kernel_version":{"target":1}
,"target":{"system":1}
,"prior":{"running":1}
,"sign":{"encrypt":1}
,"encrypt":{"kernel":1}
,"kernel-dtb":{"initrd":1}
,"initrd":{"binary":1}
,"applies":{"jetson":1}
,"xavier":{"jetson":1,"series":1}
,"agx":{"xavier":1}
,"support":{"secureboot":1,"nvidia":1}
,"secureboot":{"kernel":1}
,"signed":{"encrypted":1}
,"encrypted":{"keys":1,"binary":1}
,"keys":{"generate":1}
,"generate":{"encrypted":1}
,"signature":{"files":1}
,"section":{"signing":1,"explains":1}
,"signing":{"encrypting":1}
,"encrypting":{"kernel":1}
,"topic":{"secureboot":1}
,"preparing":{"build":1}
,"external":{"kernel":1}
,"procedures":{"describe":1}
,"describe":{"prepare":1}
,"prepare":{"kernel":1,"l4t":1,"jetson":1,"nvidia":1}
,"headers":{"kernel":1,"jetson":1,"non-jetson":1}
,"tree":{"allow":1,"building":1,"built":1,"without":1}
,"allow":{"building":1}
,"out-of-tree":{"kernel":1,"modules":1}
,"further":{"action":1}
,"usr":{"src":1}
,"src":{"linux-headers-$":1,"dir":1}
,"linux-headers-$":{"uname":1}
,"uname":{"-ubuntu18.04_aarch64":1,"build":1,"-linux_x86_64":1}
,"specify":{"kernel":1,"$tegra_kernel_out":1}
,"-ubuntu18.04_aarch64":{"lib":1}
,"place":{"local":1}
,"local":{"directory":1,"src":1}
,"local_src_dir":{"linux-headers-$":1}
,"dir":{"linux-headers-$":1}
,"compatible":{"linux":1}
,"entire":{"kernel":1}
,"variables":{"create":1}
,"file":{"follow":1,"enables":1,"sudo":1,"text":1}
,"instructions":{"provided":1}
,"command":{"prepare":1,"causes":1}
,"ensure":{"cross_compile":1}
,"described":{"previous":1}
,"previous":{"sections":1}
,"kernel_directory":{"pwd":1}
,"strip":{"unneeded":1}
,"unneeded":{"symbols":1}
,"symbols":{"kernel":1}
,"tool_chain_path":{"aarch64-linux-gnu-strip":1}
,"aarch64-linux-gnu-strip":{"strip-unneeded":1}
,"strip-unneeded":{"path-of-kernel-module.ko":1}
,"enable":{"pmic-wdt":1}
,"change":{"odm":1}
,"odm":{"data":1}
,"data":{"odm":1,"bits":1}
,"bits":{"17:16":1}
,"17:16":{"0b10":1}
,"0b10":{"flashing":1}
,"flashing":{"conf":1}
,"conf":{"file":1}
,"enables":{"pmic-wdt":1}
,"pmic-wdt":{"disables":1}
,"disables":{"tegra-wdt":1}
,"vim":{"p2771-0000.conf.common":1}
,"p2771-0000.conf.common":{"replace":1}
,"0x1090000":{"0x10a0000":1}
,"echo":{"sys":1,"proc":1}
,"sys":{"module":1}
,"module":{"kernel":1}
,"parameters":{"panic":1}
,"cat":{"dev":1}
,"dev":{"watchdog":1}
,"proc":{"sysrq-trigger":1}
,"latter":{"command":1}
,"causes":{"system":1}
,"wait":{"two":1}
,"two":{"minutes":1}
,"minutes":{"device":1}
,"device":{"reboots":1,"may":1}
,"reboots":{"reboot":1}
,"reboot":{"uart":1}
,"uart":{"logs":1}
,"logs":{"begin":1}
,"begin":{"appear":1}
,"appear":{"mb2":1}
,"mb2":{"logs":1}
,"0000.203":{"pmic":1}
,"pmic":{"reset":1}
,"reset":{"reason":1}
,"reason":{"nverc":1}
,"nverc":{"0x2":1}
,"real-time":{"kernel":1,"real-time":1}
,"series":{"processors":1}
,"processors":{"officially":1}
,"officially":{"support":1}
,"32.5":{"section":1}
,"explains":{"install":1}
,"remove":{"l4t":1,"real-time":1,"nvidia-l4t-rt-kernel":1}
,"packages":{"system":1,"point":1,"editing":1}
,"upgrade":{"l4t":1}
,"point":{"release":1}
,"version":{"real-time":1}
,"configuration":{"file":1}
,"text":{"editor":1}
,"editor":{"example":1}
,"sources.list.d":{"nvidia-l4t-apt-source.list":1}
,"add":{"new":1}
,"new":{"entry":1}
,"entry":{"rt-kernel":1}
,"rt-kernel":{"repo":1,"r32.5":1}
,"deb":{"https":1}
,"repo.download.nvidia.com":{"jetson":1}
,"r32.5":{"main":1}
,"nvidia-l4t-rt-kernel":{"nvidia-l4t-rt-kernel-headers":1}
,"switch":{"different":1,"real-time":1}
,"different":{"kernel":1}
,"once":{"installed":1}
,"may":{"want":1}
,"want":{"switch":1,"boot":1}
,"original":{"generic":1}
,"generic":{"kernel":1}
,"re-installing":{"removing":1}
,"removing":{"kernel":1}
,"editing":{"boot":1}
,"extlinux":{"extlinux.conf":1}
,"extlinux.conf":{"setting":1}
,"setting":{"default":1}
,"property":{"specify":1}
,"primary":{"generic":1}
}
;Search.control.loadWordPairs(pairs);
