var pairs =
{
"jetson":{"tx2":1,"linux":1,"tx2i":1,"download":1,"gpio":1,"p2597":1,"tx1-tx2":1}
,"tx2":{"series":1,"developer":1,"4gb":1,"compatible":1,"adaptation":1,"mb1":1,"module":1,"users":1,"pinmux":1,"bootloader":1,"device":1,"support":1,"pin":1,"lanes":1,"released":1,"technical":1,"processor":1,"configuration":1,"p2597":1,"xhci":1,"usb":1,"xudc":1,"oem":1}
,"series":{"adaptation":1,"processors":1,"want":1}
,"adaptation":{"bring-up":1}
,"topic":{"describes":1,"jetson":1,"board":1,"vendor":1,"substitute":1,"flashing":1,"display":1}
,"describes":{"port":1,"regulator":1,"usb":1}
,"port":{"nvidia":1,"depaux0":1,"number":1,"base":1,"pin":1,"kernel":1,"usb":1,"designed":1,"nine":1,"possible":1,"lanes":1,"usb_ss0":1,"according":1,"nodes":1,"numbers":1,"capability":1,"usb2":1,"port":1,"mapped":1,"usb3":1,"using":1,"switch":1,"otg":1,"j28":1,"host-only":1,"except":1,"separate":1,"switching":1,"operating":1,"transitions":1,"plus":1}
,"nvidia":{"jetson":1,"board":1,"reference":1,"tegra186-dpaux-padctl":1,"dtsfilename":1,"modified":1,"platform":1,"soc":1,"team":1,"num-lanes":1,"designing":1,"recommends":1,"further":1,"function":1,"usb2-companion":1,"oc-pin":1,"xusb-padctl.txt":1,"boost_cpu_freq":1,"boost_cpu_trigger":1,"xusb-padctl":1,"tegra-xhci.txt":1,"tegra186-xudc.txt":1}
,"linux":{"driver":1,"kernel":1,"rootfs":1}
,"driver":{"package":1,"xhci":1,"xudc":1,"node":1}
,"package":{"l4t":1,"linux_for_tegra":1}
,"l4t":{"u-boot":1,"release":1}
,"u-boot":{"bootloader":1,"linux":1,"command":1}
,"bootloader":{"nvidia":1,"mb1":1,"t186ref":1,"pinmux":1,"uses":1,"reapplied":1,"gets":1,"-------------":1,"binary":1,"images":1,"spe.bin":1,"nvtboot.bin":1}
,"developer":{"kit":1}
,"kit":{"hardware":1,"described":1,"p2771":1,"som":1,"code":1,"board":1,"nvidia":1,"carrier":1}
,"hardware":{"platform":1,"applied":1,"nvidia":1,"design":1}
,"information":{"applies":1,"customizing":1,"setting":1,"enable":1,"nvidia":1,"xusb_padctl":1,"xhci":1,"state":1,"extcon":1,"xudc":1}
,"applies":{"following":1,"jetson":1}
,"following":{"modules":1,"example":1,"procedures":1,"commands":1,"steps":1,"formula":1,"section":1,"table":1,"odd-numbered":1,"environment":1,"command":1}
,"modules":{"jetson":1}
,"original":{"jetson":1}
,"tx2i":{"industrial":1,"default":1}
,"4gb":{"memory":1}
,"compatible":{"carrier":1,"nvidia":1,"regulator":1,"regulator-fixed-sync":1,"port":1,"value":1,"extcon-gpio-states":1}
,"carrier":{"board":1,"board\u2019s":1}
,"board":{"jetson":1,"configuration":1,"part":1,"eeprom":1,"saved":1,"verify":1,"custom":1,"required":1,"naming":1,"assign":1,"combination":1,"represents":1,"name":1,"board":1,"names":1,"version":1,"schematic":1,"change":1,"using":1,"_pinmux.xlsm":1,"based":1,"translate":1,"gpio":1,"configurations":1,"additionally":1,"hosts":1,"modify":1,"designed":1,"consulting":1,"lane":1,"design":1,"find":1,"configure":1,".conf":1,"mmcblk0p1":1}
,"described":{"topic":1,"include":1,"table":1,"above":1,"create":1}
,"examples":{"described":1,"valid":1,"based":1}
,"include":{"code":1,"dashes":1,"version":1,"regulator":1,"statements":1}
,"code":{"jetson":1,"without":1,"supports":1,"device":1,"nvtbootwb0.bin":1}
,"customizing":{"configuration":1}
,"configuration":{"files":1,"modifications":1,"odm":1,"changes":1,"hardware":1,"tables":1,"applied":1,"download":1,"board":1,"want":1,"data":1,"file":1,"code":1,"bringup":1,"represents":1,"bit":1,"present":1}
,"files":{"topics":1,"nvidia":1,"customer":1,"directory":1,"names":1,"created":1,"generated":1,"disabling":1,"describe":1,"available":1,"referenced":1,"may":1,"overrides":1,"based":1,"already":1,"name":1}
,"topics":{"jetson":1}
,"mb1":{"platform":1,"configuration":1,"provides":1,"boot":1}
,"platform":{"configuration":1,"example":1,"supported":1,"c2f0000.gpio":1,"2200000.gpio":1,"modify":1,"t18x":1}
,"module":{"consists":1,"som":1,"carrier":1,"name":1,"selection":1,"board":1,"socket":1}
,"consists":{"p3310":1}
,"p3310":{"system":1,"board":1,"som":1,"module":1}
,"system":{"module":1,"platform":1,"assumes":1}
,"som":{"connected":1,"used":1,"carrier":1,"provided":1}
,"connected":{"p2597":1,"device":1,"pin":1,"cable":1,"remains":1,"logical":1,"boot":1,"property":1}
,"p2597":{"carrier":1,"custom":1}
,"part":{"number":1}
,"number":{"p2771":1,"a00":1,"files":1,"gpio15":1,"blocks":1,"entries":1,"cells":1}
,"p2771":{"designates":1,"name":1}
,"designates":{"complete":1}
,"complete":{"jetson":1}
,"used":{"without":1,"throughout":1,"uphy":1,"instead":1,"descriptive":1,"controller":1,"runtime":1}
,"without":{"software":1,"selecting":1}
,"software":{"configuration":1,"programming":1,"support":1}
,"modifications":{"som":1,"making":1}
,"eeprom":{"board":1,"custom":1,"values":1,"value":1}
,"replacing":{"p2597":1}
,"verify":{"software":1,".dts":1,"uphy":1,"lane":1}
,"programming":{"kernel":1}
,"kernel":{"device":1,"source":1,"proc":1,"pinmux":1,"messages":1,"debug":1,"configuration":1,"documents":1,"document":1,"kernel-4.9":1,"zimage":1}
,"device":{"tables":1,"tree":1,"holds":1,"new":1,"registers":1,"requires":1,"node":1,"trees":1,"tree\u2019s":1,"otg":1,"port":1,"type":1,"host":1,"client":1,"drivers":1,"driver":1,"wake":1,"mode":1,"sector":1,"emmc":1}
,"tables":{"mb1":1,"available":1}
,"odm":{"data":1}
,"data":{"flashing":1,".dtsi":1,"based":1,"transfer":1,"limit":1}
,"flashing":{"de-configure":1,"procedures":1,"booting":1,"jetson":1,"partition":1,"directory":1,"build":1,"script":1,"process":1}
,"de-configure":{"p2597":1}
,"custom":{"configurations":1,"board":1,"carrier":1,"uphy":1}
,"configurations":{"custom":1,"defined":1,"actual":1,"described":1,"during":1}
,"support":{"jetson":1,"three":1,"multiple":1,"configurations":1,"configuration":1,"special":1,"usb":1,"fifth":1,"contain":1,"contains":1,"phandle":1,"nvidia":1}
,"assign":{"module":1}
,"combination":{"lower":1}
,"lower":{"case":1}
,"case":{"alphanumeric":1,"letters":1}
,"alphanumeric":{"name":1}
,"name":{"name":1,"may":1,"select":1,"exposed":1,"character":1,"board":1,"obvious":1,"selected":1,"jetson":1,"organization":1,"vendor":1,"based":1,"e.g":1,"tab":1,"found":1,"tegra186-quill-p3310-1000-c03-00-base.dts":1,"used":1,"regulator":1,"parameter":1,"function":1,"extcon":1,"output":1,"vbus_id":1,"flashing":1,"mts_si":1,"mts_preboot_si":1}
,"may":{"include":1,"power-tree":1,"modified":1,"prefer":1,"microvolts":1,"different":1}
,"dashes":{"underscores":1}
,"underscores":{"spaces":1}
,"spaces":{"examples":1}
,"valid":{"names":1,"gpios":1}
,"select":{"appears":1,"similarly-constructed":1}
,"filenames":{"pathnames":1}
,"source":{"code":1,"file":1,"ldk_dir":1}
,"user-visible":{"device":1}
,"tree":{"filenames":1,"configure":1,"files":1,"version":1,"source":1,"platform":1,"otherwise":1,"odmdata":1,"changes":1,"examples":1,"structure":1,"values":1,"file":1}
,"additionally":{"name":1,"update":1}
,"exposed":{"user":1}
,"user":{"u-boot":1}
,"command":{"prompt":1,"jetson":1,"resulting":1,"usage":1}
,"prompt":{"various":1}
,"various":{"linux":1,"products":1}
,"proc":{"files":1,"device-tree":1}
,"represents":{"board":1,"vendor":1,"default":1}
,"similarly-constructed":{"vendor":1}
,"vendor":{"name":1,"represents":1,"board":1}
,"character":{"rules":1}
,"rules":{"apply":1}
,"apply":{"following":1}
,"re-use":{"modify":1}
,"modify":{"existing":1,"spreadsheet":1,".dts":1,"distributed":1}
,"existing":{"nvidia":1}
,"selecting":{"using":1}
,"using":{"board":1,"following":1,"p3310":1,"value":1,"member":1}
,"obvious":{"jetson":1}
,"users":{"whether":1}
,"whether":{"modified":1}
,"modified":{"source":1,"emmc":1,"reflect":1}
,"supports":{"original":1,"otg":1,"usb":1,"notifier":1}
,"placeholders":{"porting":1,"used":1}
,"porting":{"instructions":1,"linux":1,"usb":1}
,"throughout":{"topic":1}
,"substitute":{"appropriate":1,"prefix":1}
,"appropriate":{"value":1}
,"value":{"placeholder":1,"emmc":1,"positive":1,"cpu":1,"greater":1,"extcon-gpio-states":1,"array":1,"odmdata":1}
,"placeholder":{"executing":1}
,"executing":{"commands":1,"command":1}
,"function":{"functional":1,"i2c":1,"properties":1,"owns":1,"string":1,"mux":1,"xusb":1,"check":1}
,"functional":{"module":1}
,"power-tree":{"pinmux":1}
,"pinmux":{"sdmmc-drv":1,"changes":1,"configuration":1,"table":1,"settings":1,"spreadsheet":1,"setting":1,"t186":1}
,"sdmmc-drv":{"keys":1}
,"keys":{"comm":1}
,"comm":{"wi-fi":1}
,"wi-fi":{"bluetooth":1}
,"bluetooth":{"camera":1}
,"selected":{"represent":1}
,"represent":{"platform":1,"properties":1}
,"example":{"p2771":1,"file":1,"check":1,"gpio3_pbb.00":1,"output":1,"remove":1,"host-only":1,"create":1,"usb0_vbus_det":1,"confirm":1,"shows":1,"environment":1}
,"names":{"lower":1,"enter":1,"form":1}
,"version":{"board":1,"number":1,"determine":1,"device":1,"c03":1,".cfg":1,"found":1}
,"a00":{"files":1}
,"reference":{"boards":1,"manual":1,"file":1}
,"boards":{"include":1}
,"customer":{"platforms":1,"usage":1,"device":1}
,"platforms":{"required":1}
,"required":{"include":1,"pinmux":1,"device":1}
,"organization":{"name":1}
,"root":{"device":1,"file":1}
,"holds":{"root":1}
,"file":{"system":1,"name":1,"writable":1,"microsoft":1,"button":1,"generated":1,"store":1,"configures":1,"replace":1,"used":1,".dtsi":1,"including":1,"check":1,"odmdata":1,"thoroughly":1,"device":1,"p2597_c02_concept_schematics.pdf":1,"during":1,"board.conf":1,"flashed":1,"sign":1,"encrypt":1,"camera-rtcpu-sce.img":1,"path":1,"xxx":1}
,"supported":{"value":1}
,"provides":{"boot":1,"flexibility":1}
,"boot":{"time":1,"configuration":1,"power":1,"process":1,"expressed":1,"control":1,"partition":1}
,"time":{"configuration":1,"may":1,"milliseconds":1,"passed":1}
,"applied":{"bootloader":1,"software":1,"follow":1,"gpio3_pbb.00":1}
,"l4t_top":{"bootloader":1}
,"t186ref":{"bct":1,"cfg":1}
,"schematic":{"differs":1,"file":1,"conclude":1,"usb":1}
,"differs":{"jetson":1}
,"change":{"pinmux":1,"detected":1}
,"define":{"board\u2019s":1,"dpaux":1,"tegra_main_gpio_port_bb":1,"lane":1,"phy":1}
,"board\u2019s":{"pinmux":1,"requirements":1,"schematic":1}
,"download":{"jetson":1,"center":1}
,"table":{"jetson":1,"provided":1,"above":1,"shows":1,"gpio":1,"configuration":1}
,"center":{"customize":1}
,"customize":{"configuration":1,"spreadsheet":1,"pinmux":1}
,"provided":{"spreadsheet":1,"nvidia":1,"external":1,"host":1,"cable":1}
,"shows":{"locations":1,"gpio":1,"meanings":1,"values":1}
,"locations":{"default":1}
,"default":{"pinmux":1,"carrier":1,"flashing":1,"values":1,"512byte":1}
,"defines":{"pinmux":1}
,"settings":{"source":1,"i2c-4":1,"applied":1,"p2597":1,"otg-compatible":1,"external":1,"above":1}
,"spreadsheet":{"available":1,"configuration":1,"file":1,"columns":1,"reflects":1,"stored":1,"substitute":1,".cfg":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"downloads":1,"dlc":1}
,"create":{"copy":1,".dts":1,"pad":1,"xusb_padctl":1,"xhci":1,"fixed-regulators":1,"table":1,"extcon":1,"xudc":1}
,"copy":{"spreadsheet":1,"need":1}
,"based":{"board":1,"name":1,"schematic":1,"peripherals":1,"feature":1,"quill":1,"design":1,"device":1,"need":1,"odmdata":1}
,"e.g":{"board":1,"usb":1}
,"_pinmux.xlsm":{"note":1}
,"note":{"directory":1}
,"directory":{"stored":1,"spreadsheet":1,"two":1,"remove":1,"name":1}
,"stored":{"copy":1,"macro":1}
,"need":{"procedure":1,"cpu":1,"boosted":1}
,"procedure":{"updating":1}
,"updating":{"bootloader":1}
,"ensure":{"new":1,"plugin":1}
,"new":{"file":1,"pinmux":1}
,"windows":{"open":1}
,"open":{"new":1}
,"microsoft":{"excel":1}
,"excel":{"displays":1}
,"displays":{"warnings":1}
,"warnings":{"protected":1}
,"protected":{"view":1}
,"view":{"security":1}
,"security":{"warning":1}
,"warning":{"click":1}
,"click":{"enable":1,"jetson-tx2-config-template":1,"rename":1,"generate":1}
,"enable":{"editing":1,"content":1,"file":1,"disable":1}
,"editing":{"enable":1}
,"content":{"save":1}
,"save":{"changes":1,"secondary":1}
,"changes":{"new":1,"device":1,"include":1,"taken":1,"port":1}
,"rename":{"jetson-tx2-config-template":1,"menu":1,"newly":1}
,"jetson-tx2-config-template":{"tab":1}
,"tab":{"based":1,"bottom":1,"press":1}
,"right":{"click":1}
,"bottom":{"window":1}
,"menu":{"option":1}
,"type":{"board":1,"connector":1,"port_number":1,"usb2":1,"plug":1,"plug\u2019s":1,"device":1}
,"press":{"enter":1}
,"columns":{"grouped":1}
,"grouped":{"heading":1}
,"heading":{"filled":1}
,"filled":{"customers":1}
,"customers":{"required":1}
,"once":{"spreadsheet":1}
,"reflects":{"configuration":1}
,"want":{"click":1,"further":1,"remove":1,"override":1}
,"generate":{"file":1,".dts":1}
,"button":{"run":1}
,"run":{"macro":1}
,"macro":{"exports":1,"prompts":1}
,"exports":{"configuration":1}
,".dtsi":{"files":1,"file":1}
,"prompts":{"enter":1}
,"enter":{"prefix":1,"jetson-tx2-default":1,"following":1}
,"prefix":{"files":1,"recommended":1,"jetson-tx2-default":1}
,"jetson-tx2-default":{"default":1,".dtsi":1}
,"configure":{"pinmux":1,"qspi_i02":1,"odmdata":1}
,"setting":{"i2c-4":1,"top":1,"multiplexor":1,"device":1,"optional":1}
,"i2c-4":{"i2c-6":1,"dpaux1":1}
,"three":{"changes":1,"superspeed":1}
,"dpaux1":{"i2c-6":1}
,"i2c-6":{"dpaux0":1}
,"i2c":{"controller":1,"type":1}
,"controller":{"node":1,"address":1,"state":1,"complies":1,"node\u2019s":1,"names":1,"field\u2019s":1,"therefore":1,"supports":1}
,"node":{"pinctrl-0":1,"changes":1,"bpmp-dtb":1,"uphy":1,"follows":1,"describes":1,"configures":1,"property":1,"host-only":1}
,"pinctrl-0":{"point":1,"&dpaux_default":1}
,"point":{"dpaux-default":1}
,"dpaux-default":{"pinctrl-names":1}
,"pinctrl-names":{"default":1}
,"dpaux":{"controller":1}
,"dpaux@":{"nodename":1}
,"status":{"okay":1,"disabled":1}
,"dpaux_default":{"pinmux@0":1}
,"pins":{"dpaux-":1,"actual":1,"shown":1,"connect":1,"usb":1,"depending":1,"wire":1}
,"dpaux-":{"port":1}
,"delete-property":{"power-domains":1}
,"nodename":{"155c0000":1}
,"155c0000":{"dpaux0":1}
,"dpaux0":{"15040000":1}
,"15040000":{"dpaux1":1}
,"depaux0":{"dpaux1":1}
,"top":{"\u200Ckernel":1,"hardware":1,"hardware_nvidia":1}
,"\u200Ckernel":{"\u200Cnvidia":1}
,"\u200Cnvidia":{"\u200Cdocumentation":1,"tegra186-dpaux-pinctrl.txt":1}
,"\u200Cdocumentation":{"\u200Cdevicetree":1}
,"\u200Cdevicetree":{"\u200Cbindings":1}
,"\u200Cbindings":{"\u200Cpinctrl":1}
,"\u200Cpinctrl":{"\u200Cnvidia":1}
,"uses":{".cfg":1,"j19":1,"configuration":1}
,".cfg":{"file":1}
,"generated":{"device":1,"customize":1,"odmdata":1}
,"created":{"step":1,"files":1}
,"step":{"customize":1}
,"reapplied":{"linux":1}
,"update":{"bootloader":1,"number":1}
,"determine":{"jetson":1,"version":1,"gpio":1}
,"found":{"executing":1,"step":1}
,"cat":{"proc":1}
,"device-tree":{"nvidia":1,"chosen":1}
,"tegra186-quill-p3310-1000-c03-00-base.dts":{"version":1}
,"linux_for_tegra":{"kernel":1}
,"python":{"pinmux-dts2cfg.py":1}
,"pinmux-dts2cfg.py":{"--pinmux":1}
,"--pinmux":{"addr_info.txt":1}
,"addr_info.txt":{"gpio_addr_info.txt":1}
,"gpio_addr_info.txt":{"por_val.txt":1}
,"por_val.txt":{"--mandatory_pinmux_file":1}
,"--mandatory_pinmux_file":{"mandatory_pinmux.txt":1}
,"tegra18x-jetson-tx2-default-template-gpio-default.dtsi":{"1.0":1}
,"bct":{"tegra186-mb1-bct-pinmux-quill-p3310-1000-":1,"tegra186-mb1-bct-misc-si-l4t.cfg":1,"size":1}
,"tegra186-mb1-bct-pinmux-quill-p3310-1000-":{"version":1}
,"specified":{"prefix":1,"system":1}
,"recommended":{"step":1}
,"commands":{"convert":1}
,"convert":{".dtsi":1}
,"store":{"l4t":1}
,"release":{"package":1}
,"reflash":{"target":1}
,"target":{"device":1,"uphy":1,"lane":1,"cmdline":1,"machine":1,"board\u0027s":1}
,"follow":{"instructions":1}
,"instructions":{"section":1}
,"section":{"basic":1,"writing":1,"gives":1,"uses":1}
,"basic":{"flashing":1}
,"procedures":{"topic":1}
,"booting":{"target":1}
,"gpio":{"changes":1,"numbers":1,"mapping":1,"number":1,"group":1,"belongs":1,"groups":1,"expander-based":1,"regulator":1,"switch":1,"pin":1,"gpio":1,"enables":1,"&tegra_main_gpio":1,"corresponds":1,"states":1,"state":1}
,"designed":{"carrier":1,"verified":1,"internal":1}
,"translate":{"som-connector":1}
,"som-connector":{"pins":1}
,"actual":{"gpio":1,"setting":1}
,"numbers":{"understand":1,"controlled":1,"name":1}
,"understand":{"gpio":1}
,"mapping":{"formula":1,"compatibility":1,"issues":1,"issue":1,"consulting":1}
,"formula":{"below":1,"calculate":1}
,"below":{"translated":1,"reference":1}
,"translated":{"gpio":1}
,"controlled":{"driver":1,"qspi_io2":1,"usb1_en_oc":1,"regulators":1,"usb0_en_oc":1,"host":1,"state":1}
,"check":{"gpio":1,"changes":1,"usb":1,"pinmux":1,"lane":1,"value":1,"device":1,"values":1}
,"gpio15":{"ap2mdm_ready":1}
,"ap2mdm_ready":{"perform":1,"320":1}
,"perform":{"following":1,"lane":1,"steps":1}
,"search":{"gpio15_ap2mdm_ready":1,"kernel":1}
,"gpio15_ap2mdm_ready":{"jetson_tx2_generic_customer_pinmux_release.xlsx":1}
,"confirm":{"customer":1,"proper":1}
,"usage":{"field":1,"follows":1}
,"field":{"applied":1}
,"refer":{"tegra186-gpio.h":1}
,"tegra186-gpio.h":{"determine":1}
,"group":{"gpio":1,"example":1,"port":1,"command":1,"base":1,"xusb":1}
,"belongs":{"index":1,"main":1,"tegra-gpio":1}
,"index":{"gpio":1,"320":1,"256":1,"extcon-gpio":1,"specified":1}
,"gpio3_pbb.00":{"belongs":1}
,"main":{"jetson":1}
,"soc":{"device":1,"t18x":1,"controller":1}
,"registers":{"gpios":1}
,"gpios":{"dynamically":1,"256-319":1,"320-511":1,"tegra_main_gpio":1,"list":1,"states":1,"provided":1,"&tegra_main_gpio":1}
,"dynamically":{"search":1}
,"messages":{"find":1}
,"find":{"base":1,"wired":1,"corresponding":1}
,"base":{"index":1,"indices":1,"base":1,"port":1}
,"resulting":{"output":1}
,"output":{"similar":1,"shows":1,"cable":1}
,"sudo":{"grep":1,"flash.sh":1}
,"grep":{"tegra-gpio":1}
,"tegra-gpio":{"sys":1,"base":1,"group":1}
,"sys":{"kernel":1}
,"debug":{"gpio":1}
,"gpiochip1":{"gpios":1}
,"256-319":{"parent":1}
,"parent":{"platform":1}
,"c2f0000.gpio":{"tegra-gpio-aon":1}
,"gpiochip0":{"gpios":1}
,"320-511":{"parent":1}
,"2200000.gpio":{"tegra-gpio":1}
,"groups":{"base":1,"named":1}
,"tegra-gpio-aon":{"base":1}
,"pbb00":{"belongs":1}
,"320":{"following":1,"488":1}
,"calculate":{"gpio":1}
,"tegra_main_gpio":{"port":1}
,"hence":{"gpio":1,"compatible":1,"usb":1}
,"pmic":{"changes":1,"configuration":1,"p3310":1,"ddr":1}
,"configures":{"initial":1,"uphy":1,"property":1}
,"initial":{"pmic":1}
,"expander-based":{"gpio":1}
,"regulator":{"settings":1,"information":1,"parameter":1,"chip":1,"property":1,"child":1,"outputs":1,"corresponding":1}
,"defined":{"review":1,"uphy":1,"p2771-0000.conf.common":1,"updated":1,"pads":1,"ports":1,"state":1}
,"review":{"configuration":1}
,"replace":{"references":1}
,"references":{"p2597":1}
,"remove":{"following":1,"regions":1,"partitions":1}
,"writing":{"slave":1}
,"slave":{"i2c":1}
,"address":{"0x74":1}
,"0x74":{"p2597":1}
,"blocks":{"array":1}
,"array":{"number":1,"byte":1,"contain":1}
,"entries":{"block":1,"phy":1}
,"pmic.generic.1.block":{".type":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".block-delay":1,".count":1,".commands":1}
,".type":{"i2c":1}
,".slave-add":{"0xe8":1}
,"0xe8":{"7bit:0x74":1}
,".commands":{".0x07.0xff":1,".0x03.0xff":1}
,".0x07.0xff":{"0xef":1}
,".0x03.0xff":{"0x10":1}
,"assumed":{"using":1}
,"emmc":{"pmic":1,"boot":1,"boot0":1,"nand":1}
,"ddr":{"routing":1}
,"routing":{"lines":1}
,"lines":{"modifications":1}
,"making":{"carrier":1}
,"hosts":{"peripherals":1}
,"peripherals":{"consequently":1,"present":1}
,"consequently":{"based":1}
,"present":{"carrier":1,"rename":1,"nvidia":1,"board":1}
,".dts":{"files":1,".dtsi":1,"final":1}
,"disabling":{"enabling":1}
,"enabling":{"controllers":1}
,"controllers":{"changing":1}
,"changing":{"supplies":1}
,"distributed":{"configuration":1}
,"describe":{"design":1,"usb2":1}
,"design":{"platform":1,"changes":1,"jetson":1,"files":1,"consider":1,"guide":1}
,"hardware_nvidia":{"soc":1}
,"final":{"dtb":1,".dtb":1}
,"dtb":{"file":1,"dts":1,"provides":1}
,"reading":{"above":1}
,"above":{"file":1,"however":1,"table":1}
,"referenced":{"include":1}
,"statements":{"common":1}
,"common":{".dtsi":1,"kernel-dts":1}
,"reflect":{"hardware":1}
,"types":{"changes":1,"interfaces":1,"cables":1}
,"dtsi":{"filename":1}
,"filename":{"location":1}
,"power":{"supply":1,"management":1,"distribution":1}
,"supply":{"changes":1,"controlled":1,"host":1,"j19":1,"cable":1}
,"parameter":{"changes":1,"description":1}
,"display":{"panel":1,"configuration":1}
,"panel":{"node":1}
,"bringup":{"details":1}
,"feature":{"configuration":1,"support":1}
,"state":{"enable":1,"changes":1,"pin":1,"vbus_detect":1,"change":1,"following":1,"otg-compatible":1}
,"disable":{"controller":1}
,"t18x":{"kernel-dts":1}
,"kernel-dts":{"tegra186-soc":1,"panels":1}
,"panels":{"related":1}
,"related":{".dts":1,"properties":1,"uphy":1}
,"tegra":{"common":1}
,"including":{".dts":1}
,"overrides":{"changes":1}
,"best":{"practice":1}
,"practice":{"create":1}
,"quill":{"files":1}
,"already":{"present":1}
,"newly":{"created":1}
,"fdtdump":{"dtc":1,"dts":1}
,"dtc":{"generate":1,"dtb":1}
,".dtb":{"file":1}
,"taken":{"effect":1}
,"dts":{"tegra186-quill-p3310-1000-a00-00-base.dtb":1}
,"tegra186-quill-p3310-1000-a00-00-base.dtb":{"tegra186-quill-p3310-1000-a00-00-base.dts":1}
,"usb":{"universal":1,"ports":1,"2.0":1,"structure":1,"port":1,"pcie":1,"3.0":1,"superspeed":1,"connectors":1,"power-distribution":1,"nvidia":1,"on-the-go":1,"otg":1,"act":1,"supports":1,"connector":1,"power":1,"hdmi":1,"pin":1,"vbus":1,"charger":1,"lane":1}
,"universal":{"serial":1,"physical":1}
,"serial":{"bus":1}
,"superspeed":{"usb":1,"data":1,"port":1,"protocols":1}
,"ports":{"implementations":1,"used":1,"device":1,"describe":1,"form":1,"subnode":1}
,"implementations":{"ports":1}
,"uphy":{"lane":1,"handled":1,"lanes":1,"acronym":1,"node":1,"uphy":1}
,"lane":{"sharing":1,"mapping":1,"uphy":1,"assignment":1,"support":1,"assignments":1,"assigned":1,"configuration":1,"owners":1,"recognized":1,"usb3.0":1,"devmem2":1,"owned":1}
,"sharing":{"among":1}
,"among":{"pcie":1}
,"pcie":{"sata":1,"2_0":1,"0_3":1,"0_2":1,"0_1":1,"0_0":1,"1_0":1,"lane":1,"interface":1,"3x1":1}
,"sata":{"ufs":1}
,"ufs":{"xusb":1,"uphy":1}
,"xusb":{"jetson":1,"uphy":1}
,"verified":{"usb3.0":1}
,"usb3.0":{"port":1,"differential":1,"signal":1,"type":1}
,"2.0":{"otg-compatible":1,"signal":1,"highspeed":1,"hence":1,"micro":1,"micro-b":1}
,"otg-compatible":{"port":1,"support":1}
,"compatibility":{"p2597":1}
,"consulting":{"nvidia":1,"jetson":1}
,"enhanced":{"superspeed":1}
,"nine":{"pins":1}
,"shown":{"diagram":1,"following":1}
,"diagram":{"below":1}
,"two":{"differential":1,"groups":1,"flags":1}
,"differential":{"signal":1}
,"signal":{"pairs":1,"integrity":1,"pins":1,"pair":1}
,"pairs":{"superspeed":1,"tx_":1,"wired":1,"connector":1}
,"ground":{"gnd_drain":1,"logical":1}
,"gnd_drain":{"drain":1}
,"drain":{"wire":1}
,"wire":{"termination":1,"j19":1,"j28":1}
,"termination":{"managing":1}
,"managing":{"emi":1}
,"emi":{"rfi":1}
,"rfi":{"signal":1}
,"connect":{"utmi":1,"uphy":1}
,"utmi":{"pads":1,"pad":1}
,"pads":{"sstx":1,"ports":1,"subnode":1,"usb2":1,"usb3":1}
,"sstx":{"ssrx":1}
,"ssrx":{"signal":1}
,"handled":{"single":1}
,"single":{"uphy":1,"property":1}
,"lanes":{"shared":1,"assigned":1,"defined":1,"usb2-1":1,"usb3-0":1,"usb2-0":1}
,"shared":{"pcie":1}
,"assigned":{"according":1,"usb":1,"pcie":1,"sata":1,"correctly":1}
,"according":{"custom":1,"uphy":1,"state":1}
,"acronym":{"universal":1}
,"physical":{"layer":1,"interface":1}
,"layer":{"physical":1,"serve":1}
,"interface":{"layer":1,"brought":1}
,"serve":{"multiple":1}
,"multiple":{"types":1,"board":1,"regulators":1}
,"interfaces":{"e.g":1}
,"possible":{"cases":1}
,"cases":{"uphy":1}
,"assignments":{"shown":1,"odmdata":1,"nvidia":1,"programmed":1}
,"pin":{"names":1,"hence":1,"group":1,"port":1,"pin":1,"added":1,"grounded":1,"floating":1,"wires":1,"wired":1,"vbus_detect":1,"acts":1,"usb0_otg_id":1,"example":1,"designed":1,"pulled":1,"depends":1,"matter":1,"settings":1,"usb0_vbus_det":1,"extcon":1}
,"pex1":{"usb_ss0":1,"pins":1,"configure":1}
,"available":{"outputs":1}
,"outputs":{"jetson":1}
,"1x1":{"1x4":1,"1x2":1}
,"2x1":{"1x2":1,"configurations":1}
,"brought":{"pex1":1}
,"3.0":{"port":1,"type":1,"superspeed":1,"differential":1}
,"usb_ss0":{"pins":1,"pex1":1}
,"depending":{"setting":1}
,"multiplexor":{"module":1}
,"selection":{"controlled":1}
,"qspi_io2":{"configured":1}
,"configured":{"gpio":1,"bpmp-dtb":1}
,"switch":{"usb_ss0":1,"back":1}
,"qspi_i02":{"follows":1}
,"label":{"pcie-lane2-mux":1}
,"although":{"pcie":1}
,"3x1":{"2x1":1}
,"otherwise":{"pcie@1,0":1}
,"pcie@1,0":{"work":1}
,"released":{"software":1}
,"however":{"device":1}
,"odmdata":{"support":1,"defined":1,"priority":1,"related":1,"plugin":1,"checks":1,"uphy":1,"bits":1,"0x1090000":1,"0x90000":1,"0x6090000":1,"flashed":1,"properly":1,"jetson":1,"----------------":1,"used":1}
,"further":{"information":1,"assistance":1,"based":1}
,"technical":{"reference":1}
,"manual":{"trm":1}
,"trm":{"consult":1}
,"consult":{"nvidia":1}
,"designing":{"custom":1}
,"assignment":{"defined":1,"assignments":1,"modifying":1,"consult":1,"configured":1}
,"bpmp-dtb":{"file":1,"later":1}
,"p2771-0000.conf.common":{"sources":1}
,"sources":{"define":1}
,"requires":{"custom":1}
,"recommends":{"defining":1}
,"defining":{"odmdata":1}
,"properties":{"mux":1,"time":1,"various":1,"defined":1,"enabled":1,"generated":1}
,"mux":{"function":1,"pin":1}
,"prefer":{"perform":1}
,"modifying":{"bpmp-dtb":1}
,"thoroughly":{"familiar":1}
,"familiar":{"uphy":1}
,"assistance":{"considering":1}
,"bpmp":{"boot":1,"firmware":1}
,"management":{"processor":1,"clock":1,"reset":1}
,"processor":{"jetson":1,"handles":1}
,"handles":{"boot":1}
,"process":{"offloads":1}
,"offloads":{"power":1}
,"clock":{"management":1}
,"reset":{"control":1}
,"control":{"tasks":1,"table":1}
,"tasks":{"cpu":1}
,"cpu":{"uphy":1,"frequency":1,"loading":1,"boost":1,"load":1}
,"lane0-owner":{"tegra186_uphy_lane_xusb":1}
,"lane1-owner":{"tegra186_uphy_lane_pcie":1}
,"lane2-owner":{"tegra186_uphy_lane_pcie":1}
,"lane4-owner":{"tegra186_uphy_lane_pcie":1}
,"lane5-owner":{"tegra186_uphy_lane_sata":1}
,"plugin":{"manager":1}
,"manager":{"support":1,"override":1}
,"special":{"properties":1}
,"products":{"device":1}
,"trees":{"loading":1}
,"loading":{"bpmp":1,"cpu":1}
,"firmware":{"bpmp-fw":1,"based":1,"file":1}
,"bpmp-fw":{"bootloader":1,"configures":1}
,"gets":{"odmdata":1}
,"checks":{"odmdata":1}
,"bit":{"updates":1}
,"updates":{"uphy":1,"following":1}
,"owners":{"bpmp-dtb":1}
,"later":{"bpmp-fw":1}
,"updated":{"dtb":1}
,"flexibility":{"maintain":1}
,"maintain":{"multiple":1}
,"during":{"development":1,"flashing":1}
,"meanings":{"odmdata":1}
,"bits":{"related":1,"identify":1}
,"lane\u2019s":{"bits":1}
,"identify":{"function":1}
,"owns":{"lane":1}
,"recognized":{"values":1}
,"0x1090000":{"flashing":1}
,"0x90000":{"configuration":1}
,"0x6090000":{"configuration":1}
,"gives":{"step-by-step":1}
,"step-by-step":{"guidance":1}
,"guidance":{"checking":1}
,"checking":{"schematics":1}
,"schematics":{"configuring":1}
,"configuring":{"usb":1}
,"host-only":{"port":1}
,"j19":{"usb":1,"lead":1,"controlled":1,"usb3.0":1,"based":1}
,"connector":{"example":1,"class":1,"j28":1}
,"p2597_c02_concept_schematics.pdf":{"included":1}
,"included":{"jetson":1}
,"tx1-tx2":{"developer":1}
,"http":{"developer.nvidia.com":1}
,"dlc":{"jetson-tx1-tx2-developer-kit-carrier-board-c02-design-files":1,"jetson-tx2-series-modules-oem-product-design-guide":1}
,"connectors":{"p2597":1,"may":1}
,"wired":{"socket":1,"utmi":1,"uphy":1,"usb0_vbus_det":1,"usb0_otg_id":1}
,"socket":{"location":1,"u21":1,"u25":1,"vbus_detect":1}
,"location":{"p3310":1}
,"lead":{"a39":1,"c43":1,"a18":1,"b40":1}
,"a39":{"usb1_d":1}
,"usb1_d":{"a38":1,"module":1}
,"a38":{"usb1_d":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1,"subnode":1}
,"automatically":{"generated":1}
,"tx_":{"rx_":1}
,"rx_":{"wire":1}
,"c43":{"usb_ss0_tx":1}
,"usb_ss0_tx":{"c44":1,"f43":1}
,"c44":{"usb_ss0_tx":1}
,"f43":{"usb_ss0_rx":1}
,"usb_ss0_rx":{"f44":1,"module":1}
,"f44":{"usb_ss0_rx":1}
,"close":{"text":1}
,"text":{"white":1}
,"white":{"background":1}
,"background":{"description":1}
,"vbus":{"enabled":1,"supply":1,"pin":1,"regulator":1,"wires":1,"provided":1}
,"enabled":{"usb_vbus_en1":1,"xhci":1,"usb_vbus_en0":1,"xudc":1,"running":1}
,"usb_vbus_en1":{"lead":1}
,"a18":{"usb1_en_oc":1}
,"usb1_en_oc":{"module":1,"pin":1,"gpio":1}
,"u21":{"usb":1}
,"power-distribution":{"switch":1}
,"conclude":{"j19":1,"j28":1}
,"pair":{"wired":1}
,"pad":{"usb2":1,"port":1,"&battery_reg":1}
,"usb2":{"port":1,"usb3":1,"property":1,"lanes":1}
,"fixed-regulators":{"node":1,"settings":1}
,"host":{"driver":1,"device":1,"controller":1,"mode":1,"machine":1}
,"xhci":{"controlled":1,"node":1,"controller":1,"specifications":1,"documentation":1,"device":1,"settings":1}
,"regulators":{"device":1,"chip\u0027s":1}
,"tree\u2019s":{"fixed-regulators":1,"xusb_padctl":1}
,"follows":{"conventions":1}
,"conventions":{"regulator.txt":1,"pinctrl-bindings.txt":1}
,"regulator.txt":{"fixed-regulator.txt":1}
,"fixed-regulator.txt":{"gpio.txt":1}
,"gpio.txt":{"kernel":1}
,"documents":{"node\u2019s":1}
,"node\u2019s":{"properties":1}
,"chip":{"contains":1}
,"contains":{"multiple":1,"child":1,"two":1,"excon-cable":1}
,"chip\u0027s":{"binding":1}
,"binding":{"contains":1}
,"child":{"node":1}
,"property":{"indicates":1,"absent":1,"list":1,"defined":1,"values":1,"lists":1,"valid":1}
,"indicates":{"regulator":1}
,"absent":{"node\u0027s":1}
,"node\u0027s":{"name":1}
,"regulator-fixed-sync":{"fixed-regulator":1}
,"regulator-name":{"string":1,"vdd-usb1-5v":1,"vdd-usb0-5v":1}
,"string":{"used":1,"containing":1,"describes":1}
,"descriptive":{"name":1}
,"regulator-min-microvolt":{"smallest":1,"5000000":1}
,"smallest":{"voltage":1}
,"voltage":{"consumers":1}
,"consumers":{"may":1}
,"microvolts":{"5000000":1}
,"regulator-max-microvolt":{"largest":1,"5000000":1}
,"largest":{"voltage":1}
,"enables":{"disables":1}
,"disables":{"regulator":1}
,"nodes":{"property":1,"define":1}
,"list":{"j19":1,"based":1,"gpios":1,"j28":1}
,"structure":{"described":1}
,"vdd_usb1_5v":{"regulator@5":1}
,"&tegra_main_gpio":{"tegra_main_gpio":1,"tegra186_main_gpio":1}
,"corresponds":{"usb1_en_oc":1,"usb0_en_oc":1,"usb0_otg_id":1}
,"xusb_padctl":{"node":1,"documentation":1,"xusb_padctl@3520000":1,"settings":1}
,"pinctrl-bindings.txt":{"kernel":1}
,"document":{"contains":1}
,"named":{"pads":1}
,"usb3":{"signals":1,"port_number":1,"property":1,"lanes":1}
,"signals":{"along":1}
,"along":{"parameters":1}
,"parameters":{"port":1,"want":1,"added":1}
,"subnode":{"pads":1}
,"form":{"type":1}
,"port_number":{"type":1,"associated":1}
,"associated":{"port":1}
,"containing":{"name":1}
,"mode":{"string":1,"host":1,"otg":1}
,"capability":{"port":1}
,"values":{"host":1,"even-numbered":1,"used":1,"example":1,"listed":1,"parameters":1,"board-specific":1}
,"usb2-companion":{"specifies":1}
,"specifies":{"usb2":1,"overcurrent":1,"value":1}
,"mapped":{"port":1}
,"oc-pin":{"specifies":1}
,"overcurrent":{"vbus":1}
,"positive":{"zero":1}
,"vbus-supply":{"vbus":1,"&vdd_usb0_5v":1}
,"corresponding":{"utmi":1,"gpio":1,"output":1}
,"&battery_reg":{"dummy":1}
,"dummy":{"regulator":1}
,"detailed":{"information":1}
,"kernel-4.9":{"documentation":1}
,"documentation":{"devicetree":1}
,"devicetree":{"bindings":1}
,"bindings":{"phy":1,"usb":1,"extcon":1,"pinctrl":1}
,"phy":{"nvidia":1,"used":1,"phy-names":1}
,"lists":{"j19":1}
,"complies":{"xhci":1}
,"specifications":{"support":1}
,"highspeed":{"fullspeed":1}
,"fullspeed":{"lowspeed":1,"usb":1}
,"lowspeed":{"usb":1}
,"protocols":{"controller":1}
,"phys":{"contain":1,"xusb_padctl@3520000":1,"array":1}
,"contain":{"entry":1,"pointer":1,"pointers":1,"entries":1}
,"entry":{"entry":1,"phy-names":1,"phy":1,"usb":1,"detects":1}
,"phy-names":{"contain":1,"usb2-1":1,"usb2-0":1,"array":1,"usb2":1}
,"boost_cpu_freq":{"specifies":1,"value":1,"1200":1}
,"frequency":{"boosted":1,"dvfs":1,"further":1,"pmqos":1}
,"boosted":{"minimum":1}
,"minimum":{"frequency":1,"buffer":1}
,"dvfs":{"scale":1}
,"scale":{"cpu":1}
,"boost":{"frequency":1,"applicable":1}
,"pmqos":{"enabled":1}
,"field\u2019s":{"value":1}
,"greater":{"zero":1}
,"zero":{"boost":1}
,"applicable":{"bulk":1,"large":1}
,"bulk":{"isoc":1,"transfers":1,"endpoints":1}
,"isoc":{"transfers":1}
,"transfers":{"endpoints":1,"beyond":1,"bulk":1}
,"endpoints":{"need":1,"endpoints":1}
,"boost_cpu_trigger":{"minimum":1}
,"buffer":{"length":1}
,"length":{"bulk":1}
,"beyond":{"boost":1}
,"xusb-padctl":{"pointer":1,"node":1,"&xusb_padctl":1}
,"pointer":{"xusb-padctl":1,"excon-cable":1}
,"xusb_padctl@3520000":{"pads":1}
,"usb2-1":{"usb3-0":1}
,"otg":{"on-the-go":1,"just":1,"specification":1,"port":1,"features":1,"feature":1,"cable":1,"type":1,"roles":1,"featire":1}
,"on-the-go":{"compatible":1,"often":1}
,"often":{"abbreviated":1,"device":1}
,"abbreviated":{"usb":1}
,"just":{"otg":1}
,"specification":{"allows":1}
,"allows":{"usb":1}
,"act":{"host":1}
,"back":{"forth":1}
,"forth":{"roles":1}
,"roles":{"host":1,"controlled":1}
,"features":{"connected":1}
,"fifth":{"pin":1}
,"added":{"standard":1,"below":1}
,"standard":{"usb":1}
,"cable":{"type":1,"connected":1,"states":1,"names":1,"state":1}
,"plug":{"end":1,"inserted":1,"connected":1}
,"end":{"type":1}
,"plug\u2019s":{"pin":1}
,"grounded":{"type":1}
,"floating":{"device":1}
,"inserted":{"becomes":1}
,"becomes":{"otg":1,"type":1}
,"client":{"device":1}
,"j28":{"lead":1,"supports":1,"leads":1,"usb":1,"example":1,"based":1}
,"b40":{"usb0_d":1}
,"usb0_d":{"b39":1,"module":1}
,"b39":{"usb0_d":1}
,"usb_vbus_en0":{"leads":1}
,"leads":{"a17":1,"b37":1,"a36":1}
,"a17":{"usb0_en_oc":1}
,"usb0_en_oc":{"module":1,"pin":1}
,"u25":{"usb":1}
,"distribution":{"switch":1}
,"wires":{"j28":1}
,"b37":{"usb0_vbus_det":1}
,"usb0_vbus_det":{"module":1,"pin":1,"gpio":1,"pins":1}
,"vbus_detect":{"pin":1,"type":1,"initially":1}
,"a36":{"usb0_otg_id":1}
,"usb0_otg_id":{"module":1,"pin":1,"usb0_vbus_det":1}
,"micro":{"connector":1}
,"vdd_usb0_5v":{"regulator@4":1}
,"except":{"mode":1,"addition":1}
,"taking":{"j28":1}
,"micro-b":{"connector":1}
,"extcon":{"node":1,"introduced":1,"device":1,"documentation":1,"extcon-gpio-states.txt":1,"settings":1,"cable":1,"specifier":1}
,"external":{"connectors":1,"connector":1,"power":1}
,"different":{"types":1}
,"cables":{"attached":1}
,"attached":{"usb":1}
,"hdmi":{"analog":1}
,"analog":{"others":1}
,"others":{"often":1}
,"drivers":{"detect":1,"something":1}
,"detect":{"state":1}
,"separate":{"device":1}
,"something":{"according":1}
,"class":{"extcon":1,"node\u2019s":1}
,"introduced":{"2012":1}
,"2012":{"supports":1}
,"notifier":{"passing":1}
,"passing":{"information":1}
,"generally":{"port":1,"pin":1}
,"switching":{"otg":1}
,"xudc":{"defined":1,"node":1,"controller":1,"documentation":1}
,"acts":{"vbus_detect":1}
,"states":{"vbus_detect":1,"corresponding":1,"gpio":1,"value":1,"usb0_otg_id":1}
,"internal":{"pull":1,"emmc":1}
,"pull":{"high":1}
,"high":{"logical":1,"type":1}
,"logical":{"high":1,"low":1}
,"pulled":{"ground":1}
,"low":{"type":1,"vbus":1}
,"remains":{"logical":1}
,"operation":{"vbus_detect":1}
,"depends":{"device\u2019s":1}
,"device\u2019s":{"design":1}
,"consider":{"schematic":1}
,"initially":{"logical":1}
,"therefore":{"state":1}
,"matter":{"otg-compatible":1}
,"operating":{"host":1}
,"0x0":{"excon_none":1,"0x2":1}
,"0x2":{"extcon_usb_host":1,"0x1":1}
,"0x1":{"extcon_usb":1,"0x2":1}
,"extcon-gpio":{"name":1,"irq-flags":1,"debounce":1,"wait-for-gpio-scan":1,"out-cable-names":1,"cable-states":1}
,"irq-flags":{"irq":1}
,"irq":{"flags":1}
,"flags":{"gpio":1}
,"debounce":{"debounce":1,"time":1}
,"wait-for-gpio-scan":{"wait":1}
,"wait":{"timeout":1}
,"timeout":{"milliseconds":1}
,"milliseconds":{"scanning":1}
,"scanning":{"gpios":1}
,"detected":{"debounce":1}
,"out-cable-names":{"output":1,"first":1}
,"cable-states":{"gpio":1,"0x3":1}
,"byte":{"values":1,"gpio":1,"corresponding":1}
,"even-numbered":{"byte":1}
,"odd-numbered":{"byte":1}
,"cable-connected-on-boot":{"name":1}
,"expressed":{"index":1}
,"first":{"element":1}
,"element":{"index":1}
,"assumes":{"cable":1}
,"wakeup-source":{"boolean":1}
,"boolean":{"true":1}
,"true":{"device":1}
,"wake":{"system":1}
,"vbus_id_extcon":{"usb_otg":1}
,"0x3":{"0x0":1}
,"tegra186_main_gpio":{"&spmic":1}
,"extcon_usb":{"extcon_usb_host":1}
,"extcon_usb_host":{"extcon_none":1}
,"addition":{"extcon":1}
,"extcon-cables":{"otg-compatible":1,"&vbus_id_extcon":1,"otg":1}
,"excon-cable":{"entry":1}
,"transitions":{"host":1,"device":1}
,"extcon-cells":{"number":1}
,"cells":{"extcon":1}
,"plus":{"extcon":1}
,"featire":{"support":1}
,"detects":{"usb":1}
,"extcon-cable-names":{"vbus":1}
,"charger-detector":{"usb":1}
,"charger":{"detection":1}
,"detection":{"support":1,"driver":1}
,"phandle":{"usb":1}
,"pointers":{"nodes":1}
,"load":{"cpu":1}
,"large":{"bulk":1}
,"pinctrl":{"nvidia":1}
,"suspect":{"uphy":1}
,"issue":{"check":1}
,"programmed":{"bpmb":1}
,"bpmb":{"firmware":1}
,"devmem2":{"0x02520284":1,"0x02530284":1,"0x02540284":1,"0x02550284":1,"0x02560284":1,"0x02570284":1}
,"0x00":{"xusb":1}
,"0x01":{"pcie":1}
,"0x02":{"sata":1}
,"owned":{"correct":1}
,"correct":{"function":1}
,"flashed":{"sure":1,"image":1}
,"sure":{"target":1}
,"runtime":{"ensure":1}
,"override":{"unexpectedly":1,"environment":1,"eeprom":1}
,"proper":{"properties":1}
,"running":{"command":1,"host":1,"target":1}
,"chosen":{"plugin-manager":1}
,"plugin-manager":{"odm-data":1}
,"properly":{"check":1}
,"listed":{"proc":1}
,"odm-data":{"represent":1}
,"android-build":{"enable-denver-wdt":1}
,"enable-denver-wdt":{"enable-xusb-on-uphy-lane0":1}
,"disable-pmic-wdt":{"enable-pcie-on-uphy-lane1":1}
,"enable-pcie-on-uphy-lane1":{"name":1}
,"disable-sdmmc-hwcq":{"enable-pcie-on-uphy-lane2":1}
,"enable-pcie-on-uphy-lane2":{"no-battery":1}
,"disable-tegra-wdt":{"enable-pcie-on-uphy-lane4":1}
,"enable-pcie-on-uphy-lane4":{"normal-flashed":1}
,"enable-debug-console":{"enable-sata-on-uphy-lane5":1}
,"oem":{"product":1}
,"product":{"design":1}
,"guide":{"available":1}
,"removing":{"dram":1}
,"dram":{"ecc":1,"present":1}
,"ecc":{"partition":1,"dram":1,"support":1}
,"partition":{"layout":1,"size":1,"table":1}
,"layout":{"reserves":1}
,"reserves":{"regions":1}
,"regions":{"ecc":1,"save":1}
,"processors":{"using":1}
,"member":{"jetson":1}
,"secondary":{"storage":1}
,"storage":{"perform":1}
,"edit":{"bootloader":1}
,"tegra186-mb1-bct-misc-si-l4t.cfg":{"relative":1}
,"relative":{"flashing":1}
,"cfg":{"flash_l4t_t186.xml":1}
,"flash_l4t_t186.xml":{"relative":1}
,"build":{"image":1}
,"image":{"specific":1,"file":1}
,"specific":{"board":1}
,"script":{"uses":1,"updates":1}
,".conf":{"file":1}
,"optional":{"environment":1}
,"environment":{"variables":1,"variable":1}
,"flash.sh":{"script":1,"board":1}
,"variables":{"based":1,"default":1}
,"board-specific":{"file":1}
,"bctfile":{"----------------":1}
,"----------------":{"boot":1,"pass":1,"partition":1,"target":1,"device":1,"flash":1,"static":1,"nfsroot":1,"odmdata":1,"sce":1,"spe":1,"warmboot":1}
,"boardid":{"----------------":1,"override":1}
,"pass":{"boardid":1,"board_revision":1,"board_sku":1}
,"boardrev":{"---------------":1}
,"---------------":{"pass":1,"size":1,"flash":1}
,"board_revision":{"override":1}
,"boardsku":{"---------------":1}
,"board_sku":{"override":1}
,"-------------":{"bootloader":1,"mts":1,"linux":1}
,"binary":{"flashed":1}
,"bootpartlimit":{"----------":1}
,"----------":{"gpt":1}
,"gpt":{"data":1}
,"limit":{"max":1}
,"max":{"bct":1}
,"size":{"ppt":1,"default":1,"target":1,"internal":1}
,"ppt":{"size":1}
,"bootpartsize":{"-----------":1}
,"-----------":{"total":1,"linux":1}
,"total":{"emmc":1}
,"cfgfile":{"----------------":1}
,"cmdline":{"----------------":1,"help":1}
,"help":{"information":1}
,"devsectsize":{"------------":1}
,"------------":{"device":1}
,"sector":{"size":1}
,"dtbfile":{"----------------":1}
,"emmcsize":{"---------------":1}
,"boot0":{"boot1":1}
,"boot1":{"user":1}
,"flashapp":{"---------------":1}
,"flash":{"application":1,"server":1,"build":1}
,"application":{"running":1}
,"flasher":{"----------------":1}
,"server":{"running":1}
,"initrd":{"-----------------":1,"image":1}
,"-----------------":{"initrd":1,"rsa":1,"sbk":1}
,"kernel_image":{"-----------":1}
,"zimage":{"file":1}
,"mts":{"--------------------":1,"file":1,"preboot":1}
,"--------------------":{"mts":1,"target":1}
,"mtspreboot":{"-------------":1}
,"preboot":{"file":1}
,"nfsargs":{"----------------":1}
,"static":{"network":1}
,"network":{"assignments":1}
,"c-ipa":{"s-ipa":1}
,"s-ipa":{"g-ipa":1}
,"g-ipa":{"netmask":1}
,"nfsroot":{"----------------":1,"i.e":1}
,"i.e":{"addr":1}
,"addr":{"exported":1}
,"exported":{"rootfs_dir":1}
,"pkckey":{"-----------------":1}
,"rsa":{"key":1}
,"key":{"file":1}
,"sign":{"bootloader":1}
,"rootfssize":{"-------------":1}
,"rootfs":{"size":1,"directory":1}
,"rootfs_dir":{"-------------":1}
,"sbkkey":{"-----------------":1}
,"sbk":{"key":1}
,"encrypt":{"bootloader":1}
,"scefile":{"----------------":1}
,"sce":{"firmware":1}
,"spefile":{"----------------":1}
,"spe":{"firmware":1}
,"path":{"bootloader":1}
,"fab":{"--------------------":1}
,"board\u0027s":{"fab":1}
,"tegraboot":{"--------------":1}
,"--------------":{"lowerlayer":1}
,"lowerlayer":{"bootloader":1}
,"wb0boot":{"----------------":1}
,"warmboot":{"code":1}
,"xxx":{".conf.common":1}
,".conf.common":{"reflected":1}
,"reflected":{"flashed":1}
,"variable":{"settings":1}
,"ldk_dir":{"p2771-0000.conf.common":1}
,"pinmux_config":{"tegra186-mb1-bct-pinmux-quill-p3310-1000-a00.cfg":1}
,"bpfdtb_file":{"tegra186-a02-bpmp-quill-p3310-1000-a00-00-te770d-ucm2.dtb":1}
,"dtb_file":{"tegra186-quill-p3310-1000-a00-00-edp.dtb":1}
,"tbcdtb_file":{"tegra186-quill-p3310-1000-a00-00-edp.dtb":1}
,"emmc_bct":{"p3310_a00_8gb_samsung_8gb_lpddr4_204mhz_a02.cfg":1}
,"misc_cold_boot_config":{"tegra186-mb1-bct-misc-si.cfg":1}
,"execute":{"following":1}
}
;Search.control.loadWordPairs(pairs);
