var pairs =
{
"quick":{"start":1}
,"information":{"intended":1}
,"intended":{"help":1,"production":1,"development":1}
,"help":{"started":1}
,"started":{"quickly":1}
,"quickly":{"using":1}
,"using":{"nvidia":1}
,"nvidia":{"jetson":1,"software":1,"tegra":1,"carrier":1}
,"jetson":{"linux":1,"developer":1,"devices":1,"modules":1,"module":1,"xavier":1,"nano":1,"agx":1,"tx2":1,"tx1":1,"faq":1,"tx2i":1}
,"linux":{"driver":1,"host":1,"distribution":1}
,"driver":{"package":1}
,"package":{"l4t":1,"installed":1,"install":1,"sample":1}
,"l4t":{"conjunction":1,"supports":1,"installed":1,"release":1,"takes":1}
,"conjunction":{"nvidia":1}
,"developer":{"kit":1,"kits":1,"site":1,"kit\u2019s":1}
,"types":{"models":1}
,"models":{"jetson":1}
,"modules":{"jetson":1,"suitable":1,"tegra210_linux_r32.5_aarch64.tbz2":1,"tegra186_linux_r32.5_aarch64.tbz2":1,"configurations":1,"intended":1}
,"kits":{"available":1,"intended":1,"micro":1,"hardware":1}
,"available":{"nvidia":1,"installing":1,"jetson":1}
,"kit":{"includes":1,"flashing":1,"skip":1,"powered":1,"may":1,"host":1,"usb-c":1,"possibly":1,"l4t":1,"operating":1,"configured":1,"force":1,"starts":1,"powers":1,"jetson":1,"carrier":1,"automatically":1,"operational":1,"development":1,"assumptions":1}
,"includes":{"non-production":1}
,"non-production":{"specification":1}
,"specification":{"jetson":1}
,"module":{"attached":1,"ships":1,"jetson":1,"carrier":1,".conf":1,"may":1,"respective":1,"part":1,"notes":1,"expanded":1,"force":1,"description":1}
,"attached":{"reference":1}
,"reference":{"carrier":1}
,"carrier":{"board":1}
,"board":{"jetpack":1,"designed":1,"contains":1,".conf":1,"module":1,"jetson":1,"revision":1,"mmcblk0p1":1,"determines":1,"name":1,"filename":1}
,"jetpack":{"sdk":1}
,"sdk":{"develop":1}
,"develop":{"test":1}
,"test":{"software":1}
,"software":{"case":1,"preinstalled":1,"image":1,"jetson":1,"components":1,"installation":1}
,"case":{"jetson":1}
,"suitable":{"deployment":1}
,"deployment":{"production":1}
,"production":{"environment":1}
,"environment":{"throughout":1,"variable":1,"variables":1}
,"throughout":{"operating":1,"document":1}
,"operating":{"lifetime":1,"software":1}
,"lifetime":{"jetson":1}
,"ships":{"software":1}
,"preinstalled":{"attach":1}
,"attach":{"carrier":1}
,"designed":{"procured":1}
,"procured":{"product":1}
,"product":{"flash":1}
,"flash":{"software":1,"qspi-nor":1,"operating":1,"jetson":1,"install":1}
,"image":{"developed":1,"alternatively":1}
,"release":{"l4t":1,"package\u2019s":1,"package":1,"power":1,"recovery":1,"onto":1}
,"supports":{"following":1}
,"following":{"jetson":1,"procedure":1}
,"xavier":{"modules":1,"developer":1,"jetson":1,"series":1,"p3668-0000":1,"industrial":1}
,"nano":{"2gb":1,"modules":1,"developer":1,"module":1,"devices":1,"4gb":1,"less":1}
,"2gb":{"modules":1,"developer":1,"p3448-0003":1}
,"agx":{"xavier":1}
,"tx2":{"series":1,"developer":1,"4gb":1}
,"series":{"modules":1,"jetson":1,"notes":1,"demanding":1,"performance":1}
,"tx1":{"module":1,"developer":1,"modules":1}
,"details":{"jetson":1}
,"devices":{"jetson":1,"cables":1}
,"site":{"jetson":1}
,"preparing":{"jetson":1}
,"section":{"explains":1,"used":1,"describes":1}
,"explains":{"prepare":1}
,"prepare":{"jetson":1}
,"flashing":{"appropriate":1,"development":1,"script":1,"l4t":1}
,"appropriate":{"software":1}
,"either":{"jetson":1,"display":1,"emmc":1}
,"skip":{"guide":1}
,"guide":{"simply":1}
,"simply":{"download":1}
,"download":{"supported":1,"latest":1}
,"supported":{"microsd":1,"specific":1}
,"microsd":{"card":1}
,"card":{"image":1,"inserted":1,"memory":1,"slot":1}
,"alternatively":{"follow":1}
,"follow":{"instructions":1,"assume":1,"format":1,"prompts":1}
,"instructions":{"flash":1}
,"qspi-nor":{"flash":1,"microsd":1,"on-module":1,"emmc":1}
,"inserted":{"jetson":1,"card":1,"module\u2019s":1}
,"powered":{"connected":1,"larger":1}
,"connected":{"follows":1,"jetson":1,"underscores":1,"linux":1,"developer":1}
,"follows":{"note":1}
,"note":{"jetson":1}
,"may":{"devices":1,"either":1}
,"cables":{"listed":1}
,"listed":{"below":1}
,"usb":{"cable":1,"port":1,"peripherals":1,"hub":1,"ports":1}
,"cable":{"connects":1}
,"connects":{"correct":1}
,"correct":{"usb":1}
,"port":{"jetson":1,"next":1}
,"host":{"computer":1,"described":1,"flash":1,"correct":1,"enter":1}
,"computer":{"used":1,"run":1}
,"used":{"flashing":1,"throughout":1,"beginning":1,"repeatedly":1,"jetson":1}
,"development":{"support":1,"work":1,"production":1}
,"support":{"functions":1}
,"usb-c":{"port":1}
,"next":{"power":1}
,"power":{"button":1,"adapter":1}
,"button":{"jetson":1,"header":1}
,"micro":{"usb":1}
,"run":{"ubuntu":1}
,"ubuntu":{"16.04":1}
,"16.04":{"lts":1}
,"lts":{"18.04":1}
,"18.04":{"lts":1}
,"required":{"usb":1}
,"peripherals":{"keyboard":1}
,"keyboard":{"mouse":1}
,"mouse":{"connected":1}
,"possibly":{"usb":1}
,"wired":{"ethernet":1}
,"ethernet":{"connection":1}
,"connection":{"available":1}
,"installing":{"optional":1}
,"optional":{"software":1,"string":1}
,"installed":{"running":1,"linux":1}
,"display":{"device":1,"user":1}
,"device":{"serial":1,"ddd":1}
,"serial":{"console":1}
,"console":{"connected":1}
,"qemu-user-static":{"package":1}
,"sudo":{"apt-get":1,"tar":1,"apply_binaries.sh":1,"flash.sh":1}
,"apt-get":{"install":1}
,"install":{"qemu-user-static":1,"certain":1,"l4t":1}
,"installation":{"process":1}
,"process":{"needs":1,"point":1}
,"needs":{"package":1}
,"certain":{"nvidia":1}
,"components":{"onto":1}
,"onto":{"jetson":1}
,"placeholder":{"element":1,"top":1}
,"element":{"value":1}
,"value":{"pathname":1,"variable":1,"&0x3fff":1,"environment":1,"board":1}
,"pathname":{"option":1,"top":1}
,"option":{"environment":1}
,"variable":{"whose":1,"placeholders":1,"assignment":1,"board":1}
,"whose":{"value":1}
,"placeholders":{"single":1,"taken":1,"defined":1}
,"single":{"words":1}
,"words":{"words":1,"connected":1}
,"underscores":{"wrapped":1}
,"wrapped":{"angle":1}
,"angle":{"brackets":1}
,"brackets":{"examples":1}
,"examples":{"placeholders":1}
,"taken":{"later":1}
,"later":{"parts":1}
,"parts":{"document":1}
,"shell":{"script\u2019s":1}
,"script\u2019s":{"environment":1}
,"assignment":{"tegra_kernel_out":1}
,"tegra_kernel_out":{"outdir":1}
,"top":{"vendor":1,"used":1}
,"vendor":{"nvidia":1}
,"tegra":{"bootloader":1}
,"bootloader":{"partner":1}
,"partner":{"common":1}
,"line":{"code":1}
,"code":{"ec_boot_dev_cfg":1}
,"ec_boot_dev_cfg":{"value":1}
,"document":{"denote":1}
,"denote":{"top-level":1}
,"top-level":{"directory":1}
,"directory":{"files":1}
,"files":{"untarred":1,"names":1,"name":1,"assemble":1}
,"untarred":{"jetson":1}
,"defined":{"used":1}
,"beginning":{"section":1}
,"directions":{"follow":1}
,"l4t_release_package":{"contains":1}
,"contains":{"l4t":1,"filename":1,"name":1}
,"package\u2019s":{"name":1}
,"sample_fs_package":{"contains":1}
,"filename":{"sample":1,"board":1}
,"sample":{"filesystem":1,"file":1}
,"filesystem":{"package":1}
,"name":{"configuration":1,"generally":1,"represents":1,"value":1}
,"configuration":{"supported":1,"files":1,"flashing":1,"file":1}
,"specific":{"jetson":1}
,"recent":{"future":1}
,"future":{"configuration":1}
,"names":{"follow":1}
,"board_part_number":{"module_part_number":1,"p\u2011number":1}
,"module_part_number":{"modifier":1,"p\u2011number":1}
,"modifier":{".conf":1,"optional":1}
,"p\u2011number":{"full":1,"jetson":1}
,"full":{"part":1}
,"part":{"number":1}
,"number":{"nvidia":1,"represents":1}
,".conf":{"file":1,"example":1}
,"file":{"supports":1,"applies":1,"system":1,"corresponds":1}
,"string":{"indicates":1}
,"indicates":{"several":1}
,"several":{"configurations":1}
,"configurations":{".conf":1,"available":1,"respective":1}
,"applies":{"example":1,"table":1}
,"example":{"module":1,"configuration":1}
,"emmc":{"microsd":1,"development":1}
,"memory":{"uses":1}
,"uses":{"flash":1}
,"older":{"configuration":1}
,"generally":{"follow":1}
,"config_name":{"modifier":1,"name":1}
,"represents":{"carrier":1,"type":1}
,"latest":{"l4t":1}
,"system":{"jetson":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"linux-tegra":1}
,"enter":{"commands":1,"command":1}
,"commands":{"untar":1}
,"untar":{"files":1}
,"assemble":{"rootfs":1}
,"tar":{"l4t_release_package":1,"xpf":1}
,"linux_for_tegra":{"rootfs":1}
,"xpf":{"sample_fs_package":1}
,"ensure":{"jetson":1,"developer":1}
,"configured":{"connected":1}
,"described":{"assumptions":1}
,"put":{"jetson":1}
,"force":{"recovery":1}
,"recovery":{"mode":1,"button":1}
,"mode":{"rcm":1,"place":1,"following":1,"message":1}
,"larger":{"size":1,"microsd":1}
,"size":{"microsd":1}
,"starts":{"force":1}
,"place":{"jumper":1}
,"jumper":{"across":1,"pins":1,"frc":1}
,"across":{"pins":1,"frc":1,"j48":1}
,"pins":{"rec":1,"button":1,"j40":1,"j50":1}
,"rec":{"gnd":1}
,"gnd":{"button":1}
,"header":{"j14":1,"carrier":1}
,"j14":{"located":1}
,"located":{"edge":1,"near":1}
,"edge":{"carrier":1}
,"connect":{"included":1,"power":1,"linux":1}
,"included":{"power":1}
,"adapter":{"j16":1,"j25":1}
,"j16":{"developer":1}
,"powers":{"enters":1,"automatically":1}
,"enters":{"force":1}
,"remove":{"jumper":1}
,"continue":{"software":1}
,"module\u2019s":{"microsd":1}
,"frc":{"pins":1}
,"revision":{"a02":1,"b01":1}
,"a02":{"pins":1}
,"j40":{"located":1}
,"near":{"camera":1}
,"camera":{"header":1}
,"b01":{"pins":1}
,"j50":{"located":1}
,"j48":{"enable":1}
,"enable":{"power":1}
,"j25":{"developer":1}
,"automatically":{"enters":1,"reboots":1}
,"hardware":{"buttons":1}
,"press":{"hold":1,"release":1}
,"hold":{"down":1}
,"down":{"force":1}
,"confirm":{"developer":1}
,"procedure":{"determine":1}
,"determine":{"whether":1}
,"whether":{"developer":1}
,"command":{"linux":1,"lsusb":1}
,"flash.sh":{"board":1}
,"determines":{"configuration":1}
,"script":{"applies":1}
,"table":{"end":1}
,"end":{"section":1,"installation":1}
,"describes":{"configurations":1}
,"respective":{"jetson":1}
,"corresponds":{"value":1,"jetson-nano-devkit":1}
,"jetson-nano-devkit":{"jetson-nano-devkit.conf":1}
,"takes":{"minutes":1}
,"minutes":{"slow":1}
,"slow":{"host":1}
,"reboots":{"end":1}
,"point":{"jetson":1}
,"operational":{"follow":1}
,"prompts":{"display":1}
,"user":{"account":1}
,"account":{"log":1}
,"internal":{"qspi-nor":1,"qspi\u2011nor":1,"built-in":1,"emmc":1}
,"on-module":{"microsd":1}
,"small":{"form":1}
,"form":{"factor":1}
,"educational":{"experimental":1}
,"qspi\u2011nor":{"microsd":1,"on-module":1}
,"compact":{"economical":1}
,"4gb":{"p3448-0000":1,"p3448-0002":1}
,"built-in":{"qspi\u2011nor":1}
,"high-performance":{"series":1}
,"demanding":{"applications":1}
,"midrange":{"series":1}
,"performance":{"jetson":1}
,"less":{"cost":1}
,"cost":{"jetson":1}
,"industrial":{"module":1}
,"expanded":{"environmental":1}
,"environmental":{"limits":1}
,"limits":{"increased":1}
,"increased":{"useful":1}
,"useful":{"life":1}
,"recommended":{"new":1}
,"new":{"development":1}
,"except":{"noted":1}
,"noted":{"modules":1}
,"open":{"terminal":1}
,"terminal":{"window":1}
,"window":{"host":1}
,"bus":{"bbb":1}
,"bbb":{"device":1,"three-digit":1}
,"ddd":{"0955":1,"three-digit":1}
,"0955":{"nnnn":1}
,"nnnn":{"nvidia":1,"four-digit":1}
,"three-digit":{"number":1}
,"four-digit":{"number":1}
,"type":{"jetson":1}
,"supplied":{"developer":1,"jetson":1}
,"tx2i":{"industrial":1}
,"alternative":{"look":1}
,"look":{"message":1}
,"message":{"above":1}
,"above":{"display":1}
,"kit\u2019s":{"usb":1}
,"ports":{"assumptions":1}
}
;Search.control.loadWordPairs(pairs);
