var pairs =
{
"sensor":{"processing":1,"data":1}
,"processing":{"engine":1,"wake":1}
,"engine":{"spe":1}
,"nvidia":{"jetson":1}
,"jetson":{"products":1,"sensor":1,"platform":1,"download":1}
,"products":{"provide":1}
,"provide":{"built-in":1}
,"built-in":{"cortex-r5":1}
,"cortex-r5":{"microcontroller":1}
,"microcontroller":{"within":1}
,"within":{"always-on":1}
,"always-on":{"power":1}
,"power":{"domain":1}
,"domain":{"known":1}
,"known":{"sensor":1}
,"spe":{"spe":1,"useful":1,"jetson":1,"developer":1}
,"useful":{"sensor":1}
,"data":{"processing":1}
,"wake":{"management":1}
,"management":{"robotics":1}
,"robotics":{"runs":1}
,"runs":{"software":1}
,"software":{"based":1}
,"based":{"freertos":1}
,"detailed":{"information":1}
,"information":{"spe":1}
,"developer":{"guide":1}
,"guide":{"source":1}
,"source":{"files":1}
,"files":{"technical":1}
,"technical":{"reference":1}
,"reference":{"manual":1}
,"manual":{"jetson":1}
,"platform":{"provided":1}
,"provided":{"jetson":1}
,"download":{"center":1}
}
;Search.control.loadWordPairs(pairs);
