var pairs =
{
"jetson":{"xavier":1,"agx":1,"bsp":1}
,"xavier":{"jetson":1,"series":1}
,"agx":{"xavier":1}
,"series":{"boot":1,"bootloader":1,"microboot1":1,"tegraboot":1,"cboot":1}
,"boot":{"flow":1,"software":1,"media":1,"configuration":1,"except":1,"tegraboot-cpu":1,"path":1,"logo":1,"sequence":1,"extlinux":1,"information":1,"command":1,"dtb_file":1,"image":1,"image.sig":1,"kernel":1}
,"applies":{"jetson":1}
,"flow":{"control":1,"follows":1,"similar":1}
,"control":{"boot":1,"mb1":1,"tegraboot-cpu":1,"cboot":1}
,"software":{"follows":1,"architecture":1,"libraries":1,"component":1}
,"diagram":{"description":1,"shows":1}
,"description":{"automatically":1,"generated":1}
,"automatically":{"generated":1}
,"bootrom":{"hard-wired":1,"boot":1,"hardware":1,"uses":1}
,"hard-wired":{"processor":1}
,"processor":{"initializes":1,"executing":1}
,"initializes":{"boot":1,"usb":1}
,"media":{"loads":1}
,"loads":{"microboot1":1,"kernel":1,"kernel-dtb":1}
,"microboot1":{"mb1":1}
,"mb1":{"boot":1,"first":1,"signed":1,"responsible":1,"owned":1,"mb1":1,"bct":1,"component":1}
,"multiple":{"copies":1}
,"copies":{"bootrom":1}
,"configuration":{"table":1,"parameters":1,"including":1,"file":1,"extlinux.conf":1}
,"table":{"br-bct":1,"mb1-bct":1,"called":1}
,"br-bct":{"may":1,"contains":1}
,"may":{"stored":1,"internal":1}
,"stored":{"start":1,"separate":1}
,"start":{"boot-media":1}
,"boot-media":{"br-bct":1}
,"contains":{"configuration":1,"information":1,"kernel":1,"section":1}
,"parameters":{"used":1}
,"used":{"bootrom":1,"flashing":1,"cold":1,"mobile":1}
,"hardware":{"initialization":1}
,"bct":{"contains":1}
,"information":{"bootloader":1,"verify":1,"mb1":1,"contains":1}
,"bootloader":{"including":1,"boot":1,"components":1,"flash":1,"partner":1,"tboot-bpmp":1,"component":1,"used":1,"based":1}
,"entry":{"point":1,"kernel":1,"kernel-dtb":1}
,"load":{"address":1,"bootloader":1,"binary":1,"boot":1}
,"uses":{"information":1,"interrupt":1}
,"verify":{"load":1}
,"swdocs":{"mobile":1}
,"mobile":{"tegra":1,"platforms":1}
,"tegra":{"images":1,"bootloader":1}
,"images":{"bdk_bootrom_flow.jpg":1,"bdk_microboot.jpg":1}
,"nvidia":{"jetson":1,"tegra":1,"owned":1,"provided":1}
,"flash":{"components":1,"device":1}
,"tboot-cpu":{"used":1,"cboot":1,"follows":1}
,"cboot":{"used":1,"need":1,"primary":1,"feature-rich":1,"el2":1,"follows":1,"functionality":1,"looks":1,"performs":1,"authenticates":1,"assumes":1,"cannot":1,"ignores":1,"loosens":1}
,"cold":{"boot":1}
,"common":{"driver":1,"drivers":1,"across":1,"pool":1}
,"driver":{"framework":1}
,"tboot-bpmp":{"tboot-cpu":1,"two":1,"responsible":1,"follows":1}
,"need":{"common":1}
,"drivers":{"moreover":1,"libraries":1,"emmc":1,"uart":1,"hdmi":1,"mass":1}
,"moreover":{"libraries":1}
,"libraries":{"common":1,"binaries":1,"called":1,"modules":1}
,"across":{"bootloader":1}
,"components":{"instead":1,"tboot-bpmp":1,"tboot-cpu":1,"cboot":1}
,"instead":{"using":1}
,"using":{"separate":1,"boot":1,"extlinux.conf":1}
,"separate":{"sets":1,"device":1,"partitions":1}
,"sets":{"drivers":1}
,"binaries":{"share":1,"transferred":1,"host":1,"downloaded":1,"flashed":1}
,"share":{"common":1}
,"pool":{"drivers":1}
,"called":{"common":1,"mb1-bct":1}
,"framework":{"cdf":1,"follows":1,"consists":1}
,"architecture":{"common":1}
,"screenshot":{"cell":1,"video":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"generated":{"high":1}
,"high":{"confidence":1}
,"storage":{"drivers":1,"devices":1}
,"emmc":{"qspi-nor":1,"external":1}
,"qspi-nor":{"msata":1}
,"msata":{"ufs":1}
,"host":{"interface":1,"mode":1,"class":1,"usb":1,"one-by-one":1}
,"interface":{"drivers":1}
,"uart":{"usb":1}
,"display":{"drivers":1,"boot":1}
,"hdmi":{"edp":1}
,"debug":{"console":1}
,"console":{"library":1}
,"usb":{"host":1,"loaded":1,"starts":1,"binaries":1,"device":1}
,"mode":{"2.0":1,"executes":1,"initializes":1}
,"2.0":{"mode":1}
,"class":{"drivers":1}
,"mass":{"storage":1}
,"devices":{"hub":1,"following":1}
,"hub":{"hid":1}
,"hid":{"support":1}
,"partition":{"manager":1}
,"transport":{"libraries":1}
,"decompression":{"library":1}
,"library":{"supports":1,"cache":1}
,"supports":{"lzf":1,"display":1}
,"lzf":{"zlib":1}
,"zlib":{"lz4":1}
,"clib":{"dynamic":1}
,"dynamic":{"memory":1}
,"memory":{"allocation":1,"carveouts":1}
,"allocation":{"library":1}
,"cache":{"library":1}
,"cdf":{"provided":1}
,"top":{"vendor":1}
,"vendor":{"nvidia":1}
,"partner":{"common":1,"t18x":1}
,"t18x":{"common":1}
,"first":{"boot":1}
,"component":{"loaded":1,"implements":1,"executes":1,"divided":1,"runs":1}
,"loaded":{"sysram":1,"directly":1,"path":1,"kernel":1,"kernel-dtb":1}
,"sysram":{"runs":1}
,"runs":{"bpmp":1}
,"bpmp":{"component":1,"tboot-bpmp":1}
,"implements":{"certain":1}
,"certain":{"platform":1}
,"platform":{"initialization":1,"configuration":1,"using":1}
,"initialization":{"including":1,"gives":1,"passes":1}
,"including":{"cpu":1,"pinmux":1,"ones":1}
,"cpu":{"security":1,"complex":1,"starts":1,"bootloader":1}
,"security":{"configuration":1,"fuse":1}
,"signed":{"encrypted":1,"signature":1}
,"encrypted":{"nvidia":1}
,"owned":{"key":1,"nvidia":1}
,"key":{"following":1}
,"following":{"diagram":1,"order":1,"directory":1,"steps":1}
,"shows":{"flow":1}
,"pinmux":{"gpio":1}
,"gpio":{"pad":1}
,"pad":{"voltage":1}
,"voltage":{"scrs":1}
,"scrs":{"firewalls":1}
,"initializing":{"sdram":1,"firmware":1}
,"sdram":{"based":1,"tos":1}
,"based":{"mb1":1,"little":1}
,"loading":{"firmwares":1,"next":1,"initializing":1}
,"firmwares":{"including":1}
,"ones":{"initialize":1}
,"initialize":{"cpu":1}
,"complex":{"ccplex":1}
,"programming":{"pmic":1}
,"pmic":{"enabling":1}
,"enabling":{"vdd_cpu":1}
,"vdd_cpu":{"rail":1}
,"creating":{"memory":1}
,"next":{"stage":1}
,"stage":{"bootloader":1}
,"provided":{"binary":1}
,"binary":{"jetson":1,"configure":1,"file\u2019s":1,"file":1,"files":1,"loaded":1,"add":1,"kernel-dtb":1,"signed":1,"respective":1,"boot":1,"corresponding":1,"without":1}
,"bsp":{"package":1}
,"package":{"although":1}
,"although":{"provided":1}
,"configure":{"behavior":1}
,"behavior":{"specific":1}
,"specific":{"platform":1}
,"tegraboot":{"bootloader":1,"runs":1}
,"executes":{"mb1":1,"tos":1}
,"divided":{"two":1}
,"two":{"portions":1,"variants":1}
,"executing":{"determines":1}
,"determines":{"component":1}
,"portion":{"tegraboot":1}
,"variants":{"tegraboot-bpmp":1}
,"flashing":{"rcm":1,"tegraboot-cpu":1}
,"rcm":{"recovery":1,"boot":1}
,"recovery":{"boot":1}
,"firmware":{"components":1}
,"unhalting":{"cpu":1}
,"supporting":{"flashing":1,"rcm":1}
,"video":{"game":1}
,"game":{"description":1}
,"tegraboot-cpu":{"responsible":1,"el2":1,"takes":1}
,"similar":{"cold":1}
,"except":{"binaries":1,"nfs":1}
,"transferred":{"host":1}
,"directly":{"sdram":1}
,"tos":{"bpmp-fw":1,"monitor":1,"completes":1}
,"bpmp-fw":{"loaded":1}
,"starts":{"execution":1,"protocol":1,"el3":1}
,"execution":{"el3":1}
,"el3":{"mode":1}
,"monitor":{"tos":1,"completes":1}
,"completes":{"initialization":1}
,"gives":{"control":1}
,"el2":{"mode":1}
,"protocol":{"flash":1}
,"normal":{"flashing":1}
,"takes":{"binaries":1}
,"one-by-one":{"flashes":1}
,"flashes":{"device":1}
,"downloaded":{"usb":1}
,"flashed":{"onto":1}
,"onto":{"device":1}
,"primary":{"cpu":1}
,"platforms":{"cold":1}
,"path":{"cboot":1}
,"feature-rich":{"bootloader":1}
,"little":{"kernel":1}
,"finds":{"boots":1,"loads":1}
,"boots":{"kernel":1}
,"kernel":{"dtb":1,"separate":1,"boot":1,"selection":1,"binary":1,"selections":1,"kernel-dtb":1,"partition":1,"signature":1,"cboot":1,"developers":1}
,"logo":{"secureboot":1}
,"interrupt":{"scheduling":1}
,"scheduling":{"frameworks":1}
,"passes":{"control":1}
,"device":{"trees":1,"except":1,"external":1}
,"trees":{"stored":1}
,"sequence":{"using":1,"scans":1}
,"functionality":{"includes":1}
,"includes":{"default":1}
,"default":{"booting":1,"selection":1,"extlinux.conf":1}
,"booting":{"scan":1,"location":1}
,"scan":{"sequence":1}
,"scans":{"bootable":1}
,"bootable":{"devices":1,"device":1}
,"external":{"card":1,"nvme":1}
,"nvme":{"device":1}
,"internal":{"emmc":1}
,"nfs":{"device":1}
,"looks":{"extlinux.conf":1}
,"extlinux.conf":{"configuration":1,"standard":1,"file":1}
,"file":{"following":1,"extlinux.conf":1,"contains":1,"cboot":1,"linux":1,"fdt":1,"folder":1,"filename":1,"kernel":1}
,"directory":{"bootable":1}
,"rootfs":{"boot":1}
,"standard":{"text-format":1}
,"text-format":{"file":1}
,"section":{"kernel":1}
,"selection":{"indicates":1,"user":1}
,"indicates":{"kernel":1}
,"file\u2019s":{"name":1}
,"name":{"kernel-dtb":1,"kernel":1,"file":1}
,"kernel-dtb":{"binary":1,"partition":1,"partitions":1,"continues":1}
,"command":{"line":1,"boot":1}
,"upon":{"finding":1}
,"finding":{"extlinux.conf":1}
,"performs":{"following":1}
,"reads":{"boot":1}
,"displays":{"kernel":1}
,"waits":{"user":1}
,"user":{"choose":1,"respond":1}
,"choose":{"kernel":1}
,"selects":{"default":1}
,"respond":{"expiration":1}
,"expiration":{"timeout":1}
,"timeout":{"period":1}
,"period":{"seconds":1}
,"linux":{"entry":1}
,"fdt":{"entry":1,"boot":1}
,"files":{"user-accessible":1,"cboot":1}
,"user-accessible":{"booting":1}
,"location":{"rootfs":1}
,"partitions":{"may":1}
,"card":{"usb":1}
,"example":{"replace":1}
,"replace":{"dtb":1}
,"dtb":{"binary":1}
,"add":{"command":1}
,"extlinux":{"extlinux.conf":1}
,"dtb_file":{"name":1}
,"support":{"secureboot":1}
,"secureboot":{"kernel":1,"policy":1}
,"signature":{"file":1,"files":1,"filename":1}
,"authenticates":{"kernel":1}
,"respective":{"signature":1}
,"assumes":{"signature":1}
,"folder":{"corresponding":1}
,"corresponding":{"binary":1,"partition":1}
,"filename":{"extension":1,"boot":1}
,"extension":{".sig":1}
,"instance":{"kernel":1}
,"image":{"kernel":1}
,"cannot":{"authenticate":1}
,"authenticate":{"binary":1}
,"continues":{"load":1}
,"board\u2019s":{"security":1}
,"fuse":{"burned":1}
,"burned":{"cboot":1}
,"ignores":{"authentication":1}
,"authentication":{"result":1}
,"result":{"continues":1}
,"loosens":{"secureboot":1}
,"policy":{"kernel":1}
,"developers":{"easily":1}
,"easily":{"modify":1}
,"modify":{"kernel":1}
,"without":{"going":1}
,"going":{"signing":1}
,"signing":{"procedure":1}
,"procedure":{"every":1}
,"every":{"time":1}
}
;Search.control.loadWordPairs(pairs);
