var pairs =
{
"gnome-wayland":{"desktop":1,"windowing":1,"currently":1}
,"desktop":{"shell":1}
,"shell":{"support":1}
,"l4t":{"release":1,"support":1,"logs":1}
,"release":{"32.4.2":1}
,"32.4.2":{"nvidia":1}
,"nvidia":{"supports":1}
,"supports":{"gnome-wayland":1}
,"windowing":{"system":1}
,"system":{"l4t":1,"nvargus-daemon.service":1}
,"support":{"gnome-wayland":1}
,"currently":{"experimental":1}
,"section":{"describes":1}
,"describes":{"procedures":1}
,"procedures":{"using":1}
,"using":{"gnome-wayland":1}
,"start":{"windowing":1,"line":1}
,"systemd":{"nvuser.sh":1,"nv.sh":1,"system":1}
,"nvuser.sh":{"change":1}
,"modprobe.d":{"tegra-udrm.conf":1}
,"tegra-udrm.conf":{"uncomment":1}
,"uncomment":{"line":1}
,"options":{"tegra-udrm":1}
,"tegra-udrm":{"modeset":1}
,"remove":{"start":1}
,"nv.sh":{"change":1}
,"nvargus-daemon.service":{"stop":1}
,"stop":{"nvargus":1}
,"nvargus":{"daemon":1}
,"daemon":{"launched":1}
,"launched":{"boot":1}
,"boot":{"inserting":1}
,"inserting":{"beginning":1}
,"beginning":{"line":1}
,"execstart":{"usr":1}
,"usr":{"sbin":1}
,"sbin":{"nvargus-daemon":1}
,"reboot":{"device":1}
,"device":{"auto-login":1}
,"auto-login":{"enabled":1}
,"enabled":{"l4t":1}
,"logs":{"wayland":1,"session":1}
,"wayland":{"session":1,"command":1}
,"session":{"otherwise":1,"type":1}
,"otherwise":{"displays":1}
,"displays":{"list":1}
,"list":{"available":1}
,"available":{"interfaces":1}
,"interfaces":{"e.g":1}
,"e.g":{"wayland":1}
,"command":{"line":1}
,"line":{"logs":1}
,"type":{"select":1}
}
;Search.control.loadWordPairs(pairs);
