var pairs =
{
"sensor":{"software":1,"driver":1,"csi":1,"validating":1,"drivers":1,"typical":1,"orientation":1,"relation":1,"device":1,"dtsi":1,"using":1,"control":1,"millimeters":1,"module":1,"crop":1,"mode":1,"programmed":1,"image":1,"rotated":1,"output":1,"pixel":1,"data":1,"may":1,"used":1,"modules":1,"port":1,"determines":1,"flags":1,"correctly":1,"vendors":1,"imx185_v1.c":1,"timing":1,"properties":1,"determine":1,"shown":1,"information":1,"registers":1,"uses":1,"power-on":1,"specification":1,"power-off":1,"streaming":1,"supports":1,"test":1,"group":1,"hardware":1,"operating":1,"fuse":1,"frame":1,"coarse":1,"located":1,"register":1,"i2c":1,"char":1,"controls":1,"gain":1,"running":1,"exposure":1,"settings":1,"operation":1,"power":1,"specific":1,"operations":1,"sensors":1,"name":1,"common":1,"v4l2":1,"drover":1}
,"software":{"driver":1,"uses":1,"control":1}
,"driver":{"programming":1,"acquires":1,"package":1,"without":1,"driver":1,"development":1,"architecture":1,"imx185_v1.c":1,"imx185.c":1,"specific":1,"value":1,"drop":1,"returns":1,"returned":1,"delays":1,"immediately":1,"bypasses":1,"attempts":1,"documentation":1,"tegra-vi4":1,"version":1,"sony":1,"call":1,"released":1,"v4l2":1,"sensor":1,"control":1,"default":1,"uses":1,"pre-processing":1,"responsible":1,"implements":1,"read-only":1,"probing":1,"receives":1,"convert":1,"tegra_camera_cid_group_hold":1,"implement":1,"during":1,"initialization":1,"perform":1,"basic":1,"instantiated":1,"creates":1,"jetson":1,"according":1,"need":1,"update":1,"load":1,"back":1,"loadable":1,"rebuilt":1,"file":1,"add":1}
,"camera":{"sensor":1,"programming":1,"application":1,"core":1,"framework":1,"modules":1,"module":1,"board":1,"part":1,"position":1,"stack":1,"software":1,"connected":1,"common":1,"drivers":1,"devices":1,"operation":1,"device":1,"control":1,"name":1,"e.g":1,".ko":1,"config_video_":1,"loadable":1,"plugin":1,"configuration":1}
,"acquires":{"data":1,"resources":1,"static":1}
,"data":{"camera\u2019s":1,"sensor":1,"type":1,"multi-exposure":1,"sheet":1,"row":1,"rate":1,"specific":1,"information":1,"populated":1,"controls":1,"sensor-private":1,"pdata":1,"format":1,"linking":1,"above":1,"minimum":1,"fuse":1,"user":1,"link":1,"respectively":1,"tegracam_device":1,"private":1,"tc_dev":1,"applied":1}
,"camera\u2019s":{"sensor":1,"fused":1}
,"csi":{"bus":1,"lanes":1,"lane":1,"module":1,"port":1}
,"bus":{"sensor\u2019s":1,"width":1,"info":1}
,"sensor\u2019s":{"native":1,"imaging":1,"i2c":1,"internal":1,"implementation":1,"device":1}
,"native":{"format":1}
,"two":{"types":1,"versions":1,"exposure":1,"exposures":1,"ports":1,"different":1,"input":1,"corresponding":1,"pairs":1,"ways":1}
,"types":{"camera":1,"equal":1,"vbp":1,"usually":1,"exposure":1,"controls":1,"function":1,"array":1,"corresponding":1,"control":1}
,"programming":{"paths":1,"table":1,"related":1}
,"paths":{"choose":1}
,"choose":{"depending":1,"gain":1,"exposure_factor":1,"framerate":1}
,"depending":{"camera":1,"information":1}
,"core":{"library":1,"video":1}
,"library":{"interface":1,"provides":1,"path":1,"converts":1,"passes":1}
,"direct":{"v4l2":1}
,"v4l2":{"interface":1,"drivers":1,"driver":1,"sensor":1,"camera":1,"implementation":1,"subdev":1,"kernel":1,"controls":1,"handler":1,"control":1,"subdevice":1,"framework":1,"subdevices":1,"cid_frame_rate":1,"media":1,"cid_exposure":1,"set-control":1,"open":1,"s_ctrl":1,"compliant":1,"device":1}
,"provides":{"controls":1,"list":1}
,"controls":{"performs":1,"jetson":1,"including":1,"sensor":1,"needed":1,"dynamic":1,"linked":1,"control":1,"initialized":1,"defined":1,"change":1,"integer":1,"unless":1,"handler":1,"may":1,"pair":1,"implement":1,"received":1,"tegra_camera_cid_fuse_id":1,"calls":1,"get-control":1,"eeprom":1,"binding":1,"supported":1,"format":1,"tegra_camera_cid_exposure_short":1,"64\u2011bit":1,"fixed":1,"two":1,"report":1,"entry":1,"implemented":1,"registering":1,"provided":1,"first":1,"reading":1,"required":1,"properties":1}
,"performs":{"processing":1,"power-on":1,"power-off":1,"device":1}
,"processing":{"application":1}
,"application":{"kernel-mode":1,"kernel":1,"uses":1}
,"kernel-mode":{"v4l2":1}
,"drivers":{"typical":1,"shown":1,"files":1,"used":1,"media":1,"nvidia":1,"camera":1,"camera_common.h":1,"control":1}
,"typical":{"cases":1,"rear":1,"front":1,"device":1}
,"cases":{"camera":1}
,"interface":{"include":1,"interface":1,"communicate":1,"1.8v":1,"lanes":1,"supports":1,"correctly":1,"following":1,"modify":1,"e.g":1,"sensor":1,"i2c":1,"may":1}
,"applications":{"jetson":1,"convert":1,"support":1}
,"jetson":{"isp":1,"linux":1,"v4l2":1,"nano":1,"tx1":1,"agx":1,"tx2":1,"platforms":1,"device":1,"device\u2019s":1}
,"isp":{"functionality":1,"clock":1,"underrun":1}
,"convert":{"rgb":1,"floating":1,"back":1,"fixed":1}
,"rgb":{"format":1}
,"format":{"yuv":1,"perform":1,"sensor":1,"frame":1,"24\u2011bit":1,"adjust":1,"42\u2011bit":1,"format":1,"upper":1,"multiply":1,"divide":1,"mode":1,"definition":1,"macro":1,"value":1,"range":1,"conversion":1,"values":1,"avoid":1,"function":1,"table":1}
,"yuv":{"format":1}
,"perform":{"various":1,"multiplication":1,"additional":1,"subdevice":1,"critical":1,"specific":1}
,"various":{"post-processing":1}
,"post-processing":{"tasks":1}
,"tasks":{"bayer":1,"performed":1}
,"bayer":{"sensors":1,"pixel":1}
,"nvidia":{"jetson":1,"v4l2":1,"recommends":1,"platform":1,"tegra-camera-platform":1,"imx185":1,"tegra":1,"drivers":1,"kernel":1}
,"linux":{"driver":1,"kernel":1,"v4l2":1}
,"package":{"l4t":1}
,"l4t":{"architecture":1}
,"architecture":{"framework":1,"encapsulate":1}
,"framework":{"application":1,"modularize":1,"communicate":1,"kernel":1,"imx185_s_ctrl":1,"acts":1,"defining":1,"establishing":1,"provides":1,"control":1,"specific":1,"setter":1,"providing":1,"using":1,"supports":1,"operations":1,"need":1,"ops":1,"start":1,"iterates":1,"sets":1,"uses":1,"registration":1,"context":1,"calls":1,"built":1}
,"kernel":{"mode":1,"source":1,"uses":1,"driver":1,"nvidia":1,"functions":1,"v4l2":1,"boot":1,"module":1,"run":1,"image":1,"configuration":1,"sensor":1,"drivers":1,"load":1,"follows":1,"kernel-4.9":1,"device":1,"boots":1}
,"mode":{"v4l2":1,"driver":1,"selection":1,"false":1,"based":1,"group":1,"type":1,"uses":1,"types":1,"used":1,"table":1,"pixel":1,"value":1,"microseconds":1,"hdr":1,"frames":1,"fps":1,"two":1,"tables":1,"true":1,"deprecated":1,"bypassing":1,"index":1}
,"shown":{"following":1}
,"following":{"diagram":1,"table":1,"properties":1,"node":1,"diagrams":1,"example":1,"values":1,"functions":1,"code":1,"declaration":1,"directions":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"generated":1}
,"generated":{"high":1,"using":1}
,"high":{"confidence":1}
,"support":{"direct":1,"package":1,"device\u2019s":1,"feature":1,"hardware":1,"multiple":1}
,"communicate":{"nvidia":1,"camera_common_sensor_ops":1,"v4l2":1}
,"without":{"using":1,"change":1,".ko":1}
,"using":{"camera":1,"version":1,"clock":1,"power":1,"pll":1,"sensor":1,"frame":1,"register":1,"mode":1,"default":1,"factor":1,"floating":1,"ctrl_cid_list":1,"jetson":1,"plugin":1,"main":1}
,"path":{"capturing":1}
,"capturing":{"raw":1}
,"raw":{"data":1}
,"validating":{"sensor":1}
,"uses":{"kernel":1,"new":1,"keyword":1,"tegra_camera_cid_sensor_mode_id":1,"default":1,"piece-wise":1,"sensor":1,"interface":1,"regulator_enable":1,"regulator_put":1,"camera_common_regulator_get":1,"member":1,"24.8":1,"minimum":1,"42.22":1,"values":1,"fixed":1,"jetson":1,"camera":1}
,"bring":{"bayer":1}
,"pixel":{"format":1,"active":1,"data":1,"phase":1,"line":1,"clock":1,"binning":1,"rows":1,"area":1,"vbp":1}
,"add":{"appropriate":1,"camera":1,"completely":1,"control-specific":1,"new":1,".dtsi":1,"override":1}
,"appropriate":{"device":1,"formula":1,"values":1,"functions":1,"control":1,"volatile":1,"subdevice":1}
,"device":{"tree":1,"component":1,"assign":1,"datasheet":1,"properties":1,"identifier":1,"driver":1,"default":1,"xxx":1,"information":1,"topology":1,"node":1,"work":1,"trees":1,"controls":1,"represented":1,"behaves":1,"source":1,"sink":1,"shutdown":1,"instance":1,"sensor":1,"tegra":1,"using":1,"initialize":1,"v4l2":1,"simply":1,"registration":1,"module":1,"replace":1}
,"tree":{"node":1,"nodes":1,"files":1,"parser":1,"respective":1,"establishes":1,"complete":1,".dtsi":1,"parsing":1,"registered":1,"instead":1,"file":1,"entries":1}
,"node":{"kernel":1,"create":1,"camera":1,"support":1,"device":1,"contains":1,"imx185":1,"properties":1,"definitions":1,"name":1,"subtype":1,"linux":1,"settings":1,"sensor":1,"looks":1}
,"develop":{"v4l2":1}
,"either":{"two":1,"pair":1}
,"versions":{"sensor":1}
,"version":{"1.0":1,"used":1,"2.0":1,"uses":1,"new":1,"0.1.0":1,"0.0.0":1}
,"1.0":{"version":1,"features":1,"driver":1,"representing":1,"drivers":1}
,"used":{"past":1,"ensure":1,"calibrate":1,"piece-wise":1,"diagram":1,"version":1,"exposure":1,"generate":1,"specify":1,"access":1,"run":1,"initialize":1,"group":1,"user-mode":1,"switch":1,"define":1,"static":1,"program":1,"sensor":1,"camera":1,"calculating":1,"gain":1,"perform":1,"jetson":1,"short":1,"later":1,"v4l2":1}
,"past":{"releases":1}
,"releases":{"version":1,"resources":1}
,"features":{"available":1,"camera":1}
,"available":{"later":1,"unique":1,"device":1,"hdr":1,"system":1}
,"later":{"releases":1,"register":1}
,"2.0":{"new":1,"driver":1,"sensor":1,"controls":1}
,"new":{"version":1,"jetson":1,"driver":1,"modes":1,"custom":1,"settings":1,"v4l2":1,"kernel":1,"sensor":1,"device":1,"module":1}
,"modularize":{"code":1}
,"code":{"simplify":1,"nvidia":1,"sony":1,"lists":1,"below":1,"snippets":1,"removing":1,"linux":1}
,"simplify":{"sensor":1}
,"encapsulate":{"redundant":1}
,"redundant":{"code":1}
,"recommends":{"using":1}
,"examples":{"provided":1,"reading":1}
,"provided":{"sony":1,"camera":1,"sensor":1,"nvidia":1,"jetson":1,"driver":1}
,"sony":{"imx185":1}
,"imx185":{"sensors":1,"sensor":1,"30-001a":1,"camera":1,"v4l2":1,"standard":1,"functions":1,"sizeof":1,"regmap":1,"gives":1,"gfp_kernel":1}
,"sensors":{"source":1,"drop":1,"integer":1,"therefore":1,"supporting":1,"vendor\u2019s":1,"information":1,"support":1,"ready":1}
,"source":{"code":1,"tree":1,"provided":1,"file":1,"pad":1,"port":1,"files":1}
,"modules":{"device":1,"modules":1,"module":1,"serdes":1,"serializer":1,"power":1}
,"module":{"attached":1,"includes":1,"may":1,"table":1,"contain":1,"properties":1,"modulex":1,"name":1,"example":1,"datasheet":1,"rear-facing":1,"different":1,"e.g":1,"handles":1,"based":1,"cropped":1,"port":1,"represents":1,"tegra_camera_cid_otp_data":1,"lkm":1,"sensor":1,"jetson":1,"enter":1,"on-board":1,"meet":1,"returned":1,"reboot":1,"works":1}
,"attached":{"target":1}
,"target":{"platform":1,"&imx185_cam0":1}
,"platform":{"consist":1,"t19x":1,"dtsi":1,"data":1,"device":1}
,"consist":{"devices":1,"three":1}
,"devices":{"typical":1,"inside":1,"refer":1,"jetson":1,"media":1,"focuser":1,"register":1,"tegracam_core.h":1,"system":1,"change":1}
,"rear":{"camera":1,"front":1,"facing":1}
,"includes":{"complementary":1,"optical":1,"rows":1}
,"complementary":{"metal-oxide":1}
,"metal-oxide":{"semiconductor":1}
,"semiconductor":{"cmos":1}
,"cmos":{"sensor":1}
,"front":{"camera":1,"facing":1}
,"may":{"include":1,"know":1,"increased":1,"exceed":1,"different":1,"implemented":1,"implement":1,"specified":1,"modify":1,"find":1}
,"include":{"single":1,"digital":1,"angle":1,"limited":1}
,"single":{"cmos":1,"exposure":1,"register":1,"system":1}
,"locate":{"create":1}
,"create":{"tegra-camera-platform":1,"module":1,"empty":1,"dummy":1}
,"tegra-camera-platform":{"device":1}
,"top":{"hardware":1,"directory":1,"center":1,"image":1,"sensor\u2019s":1,"display":1,"exposure":1,"kernel":1}
,"hardware":{"nvidia":1,"calculate":1,"support":1,"simply":1,"group":1,"information":1,"accessible":1}
,"t19x":{"common":1}
,"common":{"kernel-dts":1,"data":1,"platform":1,"kernel":1,"sets":1,"registering":1,"code":1,"ops":1}
,"kernel-dts":{"t19x-common-modules":1}
,"t19x-common-modules":{"tegra194-camera-imx185-a00.dtsi":1,"tegra194-camera-plugin-manager.dtsi":1}
,"directory":{"installed":1}
,"installed":{"board":1}
,"board":{"support":1,"camera_board_id":1,"setup":1,"found":1}
,"table":{"modules":1,"describes":1,"specified":1,"sensor":1,"shows":1,"registers":1,"determine":1,"displays":1}
,"contain":{"basic":1}
,"basic":{"information":1,"functions":1}
,"information":{"definition":1,"modulex":1,"added":1,"information":1,"port":1,"imx185":1,"consult":1,"sensor":1,"serdes":1,"header":1,"indicating":1,"helps":1,"provided":1,"v4l2":1,"struct":1,"setting":1,"configuring":1,"sensor-private":1,"macro":1,"used":1,"gain":1,"exposure":1,"eeprom":1,"device":1,"kernel":1,"system":1,"runtime":1,"synchronizing":1}
,"definition":{"devices":1,"sensor_regmap_config":1,"v4l2_ctrl_ops":1,"imx185_set_gain":1,"generally":1}
,"inside":{"module":1,"camera":1}
,"compatible":{"nvidia":1,"property":1,"member":1}
,"badge":{"imx185_bottom_liimx185":1}
,"position":{"bottom":1,"module":1,"making":1,"values":1}
,"pcl_id":{"v4l2_sensor":1}
,"devname":{"imx185":1}
,"proc":{"device-tree":1}
,"device-tree":{"i2c@3180000":1}
,"i2c@3180000":{"tca9546@70":1}
,"tca9546@70":{"i2c@0":1}
,"i2c@0":{"imx185_a@1a":1}
,"modulex":{"module":1,"modules":1}
,"unique":{"name":1,"identifier":1}
,"name":{"identifies":1,"consist":1,"unique":1,"input":1,"sensor":1,"defined":1,"suffix":1,"dev":1,"control":1,"list":1,"match":1,"tegra":1,"imx185":1,"camera":1}
,"identifies":{"module":1,"node":1,"gpio":1}
,"three":{"parts":1,"kinds":1,"types":1,"string":1}
,"parts":{"separated":1}
,"separated":{"underscores":1}
,"module\u2019s":{"camera":1,"part":1,"eeprom":1,"one-time":1}
,"example":{"rear":1,"imx185_rear_liimx185":1,"device":1,"clock":1,"serial_a":1,"suppose":1,"piece-wise":1,"digital":1,"two-exposure":1,"above":1,"code":1,"discussion":1,"statements":1,"value":1}
,"part":{"number":1}
,"number":{"find":1,"available":1,"significant":1,"llimx185":1,"cameras":1,"frames":1,"lane":1,"extra":1,"control":1,"exposure":1,"lines":1,"vbp":1,"exposures":1,"rows":1,"pixels":1,"left":1,"right":1,"csi":1,"lanes":1,"v4l2":1,"q42.22":1,"format":1,"controls":1,"formats":1}
,"find":{"module":1}
,"datasheet":{"part":1}
,"identifier":{"last":1,"linux":1,"regulator":1}
,"last":{"six":1,"property":1}
,"six":{"characters":1,"decimal":1}
,"characters":{"part":1}
,"imx185_rear_liimx185":{"represents":1}
,"represents":{"module":1,"bit":1,"input":1,"actual":1,"factor":1,"ratio":1}
,"rear-facing":{"imx185":1}
,"system":{"multiple":1,"rear":1,"bottom":1,"bottomleft":1,"load":1,"kernel":1,"image":1}
,"multiple":{"identical":1,"pads":1,"camera":1}
,"identical":{"modules":1}
,"different":{"position":1,"dtsi":1,"types":1,"exposure":1,"modules":1,"jetson":1,"results":1}
,"making":{"module":1}
,"values":{"supported":1,"frame":1,"driver":1,"appropriate":1,"fixed":1,"apply":1,"computed":1,"include":1,"control":1,"required":1,"reg_bits":1,"structure\u2019s":1,"initial":1,"gain":1,"define":1,"likely":1,"pairs":1,"code":1,"immediately":1,"originally":1,"camera":1,"program":1,"q42.22":1,"lower":1,"workaround":1,"common":1,"used":1,"regmap_config":1,"unprocessed":1,"tegra_camera_cid_gain":1,"generated":1,"kernel":1,"back":1,"specified":1}
,"supported":{"depend":1,"sensor":1,"version":1,"jetson":1}
,"depend":{"number":1}
,"cameras":{"system":1,"connected":1}
,"two-camera":{"system":1,"systems":1}
,"three-camera":{"system":1}
,"bottom":{"top":1}
,"six-camera":{"system":1}
,"bottomleft":{"bottomright":1}
,"bottomright":{"centerleft":1}
,"centerleft":{"centerright":1}
,"centerright":{"topleft":1}
,"topleft":{"topright":1}
,"orientation":{"numeric":1,"sensor":1}
,"numeric":{"index":1}
,"index":{"representing":1,"include":1,"used":1,"represents":1,"mapping":1,"sensor":1,"specified":1}
,"representing":{"orientation":1,"gain":1}
,"relation":{"indices":1}
,"indices":{"orientations":1}
,"orientations":{"arbitrary":1}
,"arbitrary":{"typically":1}
,"typically":{"two-camera":1}
,"systems":{"rear":1}
,"facing":{"front":1}
,"individual":{"imaging":1,"sensor":1}
,"imaging":{"device":1,"surface":1,"area":1}
,"component":{"inside":1}
,"added":{"device":1,"individual":1}
,"device\u2019s":{"operation":1,"name":1,"slave":1,"file":1,"filesystem":1}
,"assign":{"device":1}
,"slave":{"address":1}
,"address":{"available":1,"bits":1,"value":1,"values":1}
,"property":{"identifies":1,"used":1,"represents":1,"name":1,"values":1,"specified":1,"described":1}
,"except":{"devices":1,"format":1}
,"refer":{"device":1}
,"nodes":{"value":1,"string":1,"disabled":1,"made":1}
,"value":{"fields":1,"extperiph1":1,"reference":1,"&en_vdd_cam_hv_2v8":1,"&en-vdd-cam_1v2":1,"&en-vdd-cam":1,"&en_vdd_vcm_2v8":1,"field":1,"false":1,"driver":1,"greater":1,"equation":1,"specifies":1,"based":1,"rounded":1,"truncated":1,"according":1,"may":1,"gain":1,"equal":1,"used":1,"exposure":1,"framerate":1,"specified":1,"float":1,"calculated":1,"rows":1,"four":1,"pixels":1,"zero":1,"control":1,"frame_length":1,"bits":1,"pairs":1,"actual":1,"zero-based":1,"camera":1,"determine":1,"fixed":1,"stored":1,"defined":1,"macros":1,"format":1,"1:n":1,"represents":1,"indicates":1,"sensor":1,"true":1,"pair":1}
,"fields":{"camera-related":1}
,"camera-related":{"device":1}
,"string":{"data":1,"defined":1,"name":1,"control":1,"controls":1}
,"reg":{"0x1a":1}
,"physical_w":{"15.0":1}
,"physical_h":{"12.5":1}
,"sensor_model":{"imx185":1}
,"use_decibel_gain":{"true":1}
,"delayed_gain":{"true":1}
,"use_sensor_mode_id":{"true":1}
,"mclk_khz":{"37125":1}
,"tegra_sinterface":{"serial_a":1}
,"phy_mode":{"dphy":1}
,"dpcm_enable":{"false":1}
,"mode_type":{"bayer":1,"bayer_wdr_pwl":1}
,"pixel_phase":{"rggb":1}
,"active_w":{"1920":1,"total":1}
,"active_h":{"1080":1,"total":1}
,"line_length":{"2200":1,"pix_clk_hz":1,"maximum":1,"minimum":1}
,"pix_clk_hz":{"74250000":1,"1000000":1,"line_length":1}
,"min_gain_val":{"0db":1,"minimum":1}
,"max_gain_val":{"480":1,"maximum":1}
,"480":{"48db":1}
,"step_gain_val":{"0.3":1}
,"framerate_factor":{"1000000":1}
,"min_framerate":{"1500000":1,"pix_clk_hz":1,"minimum":1}
,"max_framerate":{"30000000":1,"pix_clk_hz":1,"maximum":1}
,"max_exp_time":{"660000":1,"maximum":1}
,"default_exp_time":{"33334":1,"integer":1,"int":1}
,"liimx185_imx185_out0":{"endpoint":1}
,"remote-endpoint":{"&liimx185_csi_in0":1,"&liimx185_csi_out0":1,"&liimx185_imx185_out0":1,"&liimx185_vi_in0":1}
,"describes":{"device":1,"property-value":1,"sensor":1,"functions":1,"control":1,"controls":1,"probing":1}
,"properties":{"v4l2":1,"table":1,"specified":1,"per-mode":1,"applies":1,"instead":1,"supported":1,"match":1,"device":1}
,"specified":{"different":1,"platform":1,"sensor":1,"mode":1,"multiplied":1,"correctly":1,"array":1,"sensor\u2019s":1,"hdr":1,"device":1}
,"dtsi":{"files":1,"file":1}
,"files":{"example":1,"enclosed":1,"information":1}
,"clock":{"gpio":1,"device":1,"source":1,"frequency":1,"mipi":1,"period":1,"lane":1,"calculating":1,"mclk":1,"rate":1,"calculate":1,"specified":1,"based":1}
,"gpio":{"regulator":1,"pins":1,"pin":1}
,"regulator":{"properties":1,"device":1,"name":1,"xxx":1}
,"file":{"rest":1,"obtain":1,"camera_common.h":1,"imx185_mode_tbls.h":1,"imx185.c":1,"imx185_1.c":1,"uses":1,"gets":1,"replacing":1,"system":1,"camera":1,"enabled":1}
,"rest":{"properties":1}
,"keyword":{"bind":1}
,"bind":{"device":1,"driver":1}
,"specific":{"device":1,"controls":1,"sensor":1,"resolution":1,"operations":1,"camera":1}
,"i2c":{"slave":1,"imx185_1.c":1,"client":1,"read":1,"interface":1,"imx185.c":1,"register":1,"camera":1}
,"input":{"clock":1,"output":1,"module":1,"signal":1,"device":1,"stream":1,"parameters":1,"value":1}
,"default":{"value":1,"gpio":1,"mode":1,"gain":1,"exposure":1,"framerate":1,"settings":1,"true":1,"sensor":1,"change":1,"frame":1,"data":1,"values":1}
,"maximum":{"frequency":1,"wait":1,"gain":1,"exposure":1,"coarse":1,"hdr":1,"frame":1,"framerate":1,"output":1,"values":1,"default":1}
,"frequency":{"extperiph1":1,"greater":1,"kilohertz":1,"hertz":1}
,"extperiph1":{"mhz":1}
,"mhz":{"frequency":1,"required":1}
,"greater":{"mhz":1,"equal":1,"pixel_clk_hz":1,"non-hdr":1}
,"required":{"external":1,"camera":1,"cropping":1,"sensor":1,"imager":1,"therefore":1,"driver":1,"parameters":1}
,"external":{"clock":1}
,"needed":{"sensor":1,"value":1,"v4l2":1,"media":1,"jetson":1}
,"xxx":{"-gpio":1,"identifies":1,"-supply":1,"regulator":1,"-reg":1}
,"general-purpose":{"input":1}
,"output":{"gpio":1,"csi":1,"piece-wise":1,"clock":1,"signal":1,"frame":1,"returned":1,"rate":1,"size":1,"serdes":1}
,"pins":{"device":1,"camera":1}
,"pin":{"camera":1}
,"h3-gpio":{"camera0":1}
,"camera0":{"reset":1,"power":1}
,"h6-gpio":{"camera0":1}
,"power":{"down":1,"sources":1,"controls":1,"functions":1,"&priv-":1,"states":1}
,"t6-gpio":{"camera1":1}
,"camera1":{"reset":1,"power":1}
,"t5-gpio":{"camera1":1}
,"control":{"mechanism":1,"select":1,"points":1,"point":1,"represent":1,"specified":1,"adjusted":1,"initialization":1,"handler":1,"handlers":1,"accessible":1,"setting":1,"ops":1,"flags":1,"used":1,"registers":1,"types":1,"value":1,".id":1,".value64":1,"top-level":1,"needs":1,"sensors":1,"applies":1,"two":1,"values":1,"switch":1,"control":1,"register":1,"new":1,"v4l2":1,"initialize":1,"imx185_ctrls_init":1,"camera":1,"optional":1,"required":1,"sensor":1,"bits":1,"operations":1,"controls":1,"table":1}
,"mechanism":{"require":1,"adding":1}
,"require":{"specific":1}
,"specifies":{"regulator":1,"sensor":1,"whether":1,"height":1,"width":1,"clockwise":1,"bit":1,"calculated":1,"minimum":1,"maximum":1,"number":1,"media":1,"gain":1,"pre-processed":1,"unprocessed":1}
,"reference":{"actual":1}
,"actual":{"regulator":1,"value":1,"property":1,"default":1,"output":1,"csi":1,"gain":1,"implementations":1}
,"defined":{"elsewhere":1,"regulators":1,"imx185":1,"camera_common.h":1,"ctrl_config_list":1,"driver":1}
,"elsewhere":{"device":1}
,"enclosed":{"angle":1}
,"angle":{"brackets":1}
,"vana-supply":{"value":1}
,"&en_vdd_cam_hv_2v8":{"analog":1}
,"analog":{"2.8v":1,"gain":1}
,"vdig-supply":{"value":1}
,"&en-vdd-cam_1v2":{"digital":1}
,"digital":{"1.2v":1,"gain":1,"overlap":1}
,"vif-supply":{"value":1}
,"&en-vdd-cam":{"interface":1}
,"vvcm-supply":{"value":1}
,"&en_vdd_vcm_2v8":{"analog":1}
,"2.8v":{"vcm":1}
,"sources":{"provided":1}
,"field":{"regulator":1,"required":1}
,"suffix":{"-reg":1}
,"avdd-reg":{"vana":1}
,"dvdd-reg":{"vdig":1}
,"iovdd-reg":{"vif":1}
,"vcmvdd-reg":{"vvcm":1}
,"physical":{"width":1,"height":1}
,"width":{"sensor":1,"pixel":1,"horizontal":1,"pixel-active":1}
,"height":{"sensor":1,"pixel":1,"pixel-active":1}
,"type":{"sensor":1,"possible":1,"bayer_wdr_pwl":1,"vbp":1,"v4l2":1,"node":1,"control":1}
,"e.g":{"imx185":1,"spi":1}
,"wait":{"time":1}
,"time":{"first":1,"mipi":1,"limit":1,"line_":1,"minimum":1,"line_length":1,"maximum":1,"scaled":1,"float":1,"frame":1,"registers":1,"lines":1,"seconds":1,"settings":1,"wdr":1,"steps":1}
,"first":{"frame":1,"acquire":1,"division":1,"allocates":1,"three":1}
,"frame":{"capture":1,"false":1,"rate":1,"length":1,"usually":1,"reside":1,"two-exposure":1,"start":1,"3840":1,"included":1,"includes":1,"example":1,"rows":1,"size":1,"format":1,"hdr":1}
,"capture":{"starts":1,"sequence":1,"above":1}
,"starts":{"milliseconds":1,"sensor":1}
,"frames":{"driver":1,"avoid":1,"applying":1,"second":1,"dol":1,"type":1,"may":1,"received":1}
,"drop":{"applying":1,"frames":1}
,"applying":{"sensor":1,"crop":1}
,"crop":{"settings":1,"top":1}
,"avoid":{"receiving":1,"potential":1,"buffer":1,"using":1}
,"receiving":{"corrupted":1}
,"corrupted":{"frames":1}
,"boolean":{"default":1,"indicates":1,"specifies":1,"true":1,"value":1}
,"false":{"determines":1,"analog":1,"true":1,"sends":1,"uses":1,"available":1}
,"determines":{"whether":1,"bus":1}
,"whether":{"driver":1,"sensor":1,"enable":1,"device":1}
,"returns":{"analog":1}
,"gain":{"decibels":1,"received":1,"values":1,"obtained":1,"limit":1,"control":1,"factor":1,"configured":1,"value":1,"scaled":1,"float":1,"coarse":1,"string":1,"exposure":1,"settings":1,"setting":1,"range":1,"access":1,"64-bit":1}
,"decibels":{"according":1}
,"according":{"formula":1,"mclk_multiplier":1,"equation":1,"sensor":1,"i2c":1,"specification":1,"sensor-related":1}
,"log":{"analog":1}
,"received":{"driver":1,"soc":1,"control":1}
,"returned":{"without":1,"similar":1,"bootloader":1}
,"true":{"user":1,"dynamic":1,"normal":1,"bypasses":1,"using":1,"bypass":1}
,"user":{"mode":1,"space":1}
,"delays":{"sending":1}
,"sending":{"updated":1}
,"updated":{"gain":1,"values":1}
,"sends":{"updated":1}
,"bypasses":{"default":1,"settings":1}
,"selection":{"logic":1}
,"logic":{"uses":1,"selects":1}
,"tegra_camera_cid_sensor_mode_id":{"control":1}
,"select":{"specific":1}
,"selects":{"mode":1,"specific":1}
,"based":{"resolution":1,"compression":1,"input":1,"case":1,"video":1,"control":1,"default":1}
,"resolution":{"color":1,"format":1}
,"color":{"format":1}
,"property-value":{"pairs":1}
,"pairs":{"apply":1,"version":1,"control":1,"specified":1,"used":1,"controls":1}
,"apply":{"sensor":1,"diagram":1}
,"per-mode":{"precisely":1}
,"group":{"properties":1,"hold":1}
,"applies":{"0-based":1,"per-frame":1}
,"0-based":{"index":1}
,"media":{"controller":1,"pad":1,"device":1,"i2c":1,"entity":1,"links":1,"operations":1}
,"controller":{"graph":1,"api":1,"device":1,"framework":1,"setup":1,"v4l2":1,"usage":1,"pad":1}
,"graph":{"binding":1}
,"binding":{"information":1,"nvcsi":1,"properties":1,"connection":1,"two":1,"expects":1,"result":1,"parses":1}
,"port":{"binding":1,"connection":1,"index":1,"sink":1,"camera":1,"imager":1,"bound":1,"source":1,"binds":1,"represented":1}
,"standard":{"mipi":1,"ones":1}
,"mipi":{"driving":1,"lanes":1,"lane":1,"alliance":1}
,"driving":{"clock":1}
,"lane":{"channels":1,"nanoseconds":1,"output":1,"mbps":1}
,"channels":{"sensor":1}
,"programmed":{"output":1,"discontinuous":1,"sensor":1,"valid":1}
,"base":{"nvidia":1}
,"tegra":{"serial":1,"video":1,"20linux":1,"camera":1}
,"serial":{"interface":1}
,"lanes":{"connected":1,"bits":1}
,"connected":{"example":1,"sensor":1,"serdes":1}
,"indicates":{"whether":1}
,"discontinuous":{"clock":1}
,"ths":{"settle":1}
,"settle":{"time":1}
,"nanoseconds":{"calculate":1}
,"calculate":{"range":1,"value":1,"exposure":1}
,"range":{"acceptable":1,"mode":1,"signal":1,"delta":1,"driver":1,"control":1}
,"acceptable":{"values":1}
,"nano":{"devices":1,"series":1}
,"period":{"102":1,"204":1,"rows":1,"vbp":1}
,"102":{"mhz":1}
,"agx":{"xavier":1}
,"xavier":{"series":1}
,"series":{"jetson":1}
,"tx2":{"series":1}
,"204":{"mhz":1}
,"unit":{"interval":1,"lines":1,"device":1}
,"interval":{"equal":1}
,"equal":{"duration":1,"csi_pixel_bit_depth":1,"active_w":1,"actual":1,"default":1}
,"duration":{"state":1}
,"state":{"clock":1,"used":1}
,"attempts":{"auto-calibrate":1}
,"auto-calibrate":{"according":1}
,"mclk_multiplier":{"parameter":1,"desired":1}
,"alliance":{"specification":1}
,"specification":{"d-phy":1,"sheets":1}
,"d-phy":{"details":1}
,"enable":{"dpcm":1,"flag":1,"function":1,"sensor":1}
,"dpcm":{"compression":1}
,"compression":{"mode":1,"function":1}
,"active":{"region":1,"pixel":1}
,"deprecated":{"following":1,"uses":1,"64\u2011bit":1}
,"possible":{"values":1}
,"bayer_wdr_pwl":{"wide":1,"property":1,"specifies":1}
,"wide":{"dynamic":1}
,"dynamic":{"range":1,"array":1}
,"piece-wise":{"linear":1}
,"linear":{"function":1,"compression":1}
,"function":{"compress":1,"based":1,"compressing":1,"index":1,"digital":1,"takes":1,"updates":1,"according":1,"uses":1,"regulator_get":1,"enables":1,"providing":1,"selecting":1,"leave":1,"controls":1,"contains":1,"redirects":1,"iterates":1,"control":1,"parses":1,"call":1,"operations":1,"driver\u2019s":1,"first":1,"links":1,"called":1,"update":1,"calls":1,"acquire":1,"program":1,"enable":1,"initializes":1,"removes":1}
,"compress":{"multi-exposure":1}
,"multi-exposure":{"fused":1,"fusion":1}
,"fused":{"pixel":1,"output":1,"module":1}
,"fusion":{"performed":1}
,"performed":{"sensor":1,"during":1,"errors":1}
,"clockwise":{"rotation":1,"top":1,"counterclockwise":1}
,"rotation":{"degrees":1}
,"degrees":{"sensor":1}
,"image":{"presented":1,"display":1,"falls":1,"right":1,"270":1,"data":1,"jetson":1,"flashing":1,"support":1}
,"presented":{"display":1}
,"display":{"intended":1,"oriented":1,"appears":1,"top":1}
,"intended":{"android":1}
,"android":{"environment":1}
,"environment":{"effect":1}
,"effect":{"jetson":1}
,"ensure":{"sensor":1}
,"oriented":{"correctly":1}
,"correctly":{"end":1,"avoid":1,"configure":1}
,"end":{"user":1,"long":1}
,"suppose":{"sensor":1}
,"rotated":{"counterclockwise":1,"clockwise":1}
,"counterclockwise":{"top":1,"rotating":1}
,"falls":{"right":1}
,"right":{"side":1,"correct":1,"margin":1}
,"side":{"sensor\u2019s":1,"display":1}
,"surface":{"image":1}
,"appears":{"rotated":1}
,"area":{"top":1,"effective":1,"pixels":1}
,"correct":{"readout_orientation":1,"sensor":1,"gain8":1}
,"readout_orientation":{"270":1}
,"270":{"rotates":1,"clockwise":1}
,"rotates":{"displayed":1}
,"displayed":{"image":1}
,"rotating":{"top":1}
,"bit":{"depth":1}
,"depth":{"sensor":1,"multi-exposure":1}
,"phase":{"possible":1}
,"consult":{"imx185":1}
,"line":{"width":1,"information":1,"distinguish":1}
,"horizontal":{"timing":1}
,"timing":{"size":1,"capture":1,"general":1}
,"size":{"sensor":1,"line":1,"left":1,"right":1,"frame":1,"final":1,"total":1,"2200":1,"1920":1,"register":1,"string":1}
,"calibrate":{"features":1}
,"mclk":{"multiplier":1,"prevent":1,"pll":1,"mclk":1,"24mhz":1}
,"multiplier":{"timing":1,"pll":1,"6.67":1}
,"sequence":{"hardware":1,"modify":1}
,"desired":{"isp":1}
,"hertz":{"mclk":1,"required":1}
,"pixel_clk_hz":{"divided":1,"mclk":1,"24000000":1,"sensor":1,"891":1,"2200":1}
,"divided":{"mclk":1}
,"prevent":{"isp":1}
,"switch":{"longer":1,"group":1,"switch":1,"statement":1,"ctrl-":1}
,"longer":{"needed":1}
,"calculated":{"internally":1}
,"calculating":{"exposure":1,"new":1}
,"exposure":{"frame":1,"time":1,"intervals":1,"frames":1,"rows":1,"short":1,"video":1,"control":1,"configured":1,"value":1,"vpb":1,"settings":1,"controls":1,"sensor":1,"values":1,"controlled":1}
,"pll":{"settings":1,"multiplier":1,"pre":1,"pre-divider":1,"post-divider":1}
,"settings":{"sensor":1,"mode":1,"function":1,"frame":1,"exposure":1,"kernel":1,"default":1,"clocks":1,"tegra_camera_cid_exposure":1,"during":1,"programming":1}
,"sheet":{"detailed":1}
,"detailed":{"instructions":1}
,"rate":{"serializer":1,"limit":1,"control":1,"configured":1,"sensor":1,"per":1,"891":1,"fps":1,"values":1,"settings":1,"frames":1,"exposure":1}
,"serializer":{"deserializer":1}
,"deserializer":{"gmsl":1,"chips":1}
,"gmsl":{"fpd":1}
,"fpd":{"link":1}
,"link":{"hertz":1,"frames":1,"controls":1,"declaration\u2019s":1,"open":1,"v4l2":1,"validation":1,"appropriate":1,"ops":1,"common":1,"subdevice":1,"control":1,"setter":1}
,"serdes":{"pixel":1,"sensors":1,"sure":1,"maximum":1}
,"obtained":{"inherently":1,"kernel":1}
,"inherently":{"mode":1}
,"know":{"actual":1}
,"minimum":{"gain":1,"exposure":1,"coarse":1,"high-dynamic-range":1,"frame":1,"delta":1,"framerate":1,"maximum":1}
,"limit":{"mode":1,"specified":1}
,"rounded":{"down":1,"integer":1}
,"down":{"six":1,"device":1}
,"decimal":{"places":1}
,"places":{"usually":1}
,"usually":{"1.0":1,"includes":1,"less":1}
,"truncated":{"six":1}
,"increased":{"include":1}
,"microseconds":{"value":1}
,"min_exp_time":{"minimum":1}
,"coarse":{"integration":1}
,"integration":{"time":1}
,"line_":{"length":1}
,"length":{"pix_clk_hz":1,"register":1,"lines":1,"converts":1,"coarse":1}
,"intervals":{"unit":1}
,"high-dynamic-range":{"hdr":1}
,"hdr":{"ratio":1,"sensors":1,"sensor":1}
,"ratio":{"denominator":1,"1:3":1}
,"denominator":{"mode":1}
,"integer":{"greater":1,"value":1,"menu":1,"control":1,"values":1,"8\u2011bit":1,"22\u2011bit":1}
,"non-hdr":{"sensors":1}
,"second":{"fps":1}
,"fps":{"value":1}
,"extra":{"embedded":1}
,"embedded":{"metadata":1}
,"metadata":{"rows":1,"support":1}
,"rows":{"frame":1,"ignored":1,"line":1,"appearing":1,"filtered":1,"appear":1,"hence":1,"different":1,"long":1,"thus":1,"top":1,"header":1,"read":1,"rows":1,"end":1,"start":1,"vbp":1,"example":1}
,"disable":{"embedded":1}
,"points":{"used":1,"struct":1}
,"compressing":{"multi-exposure":1}
,"valid":{"mode_type":1,"data":1,"camera":1}
,"supports":{"control":1,"sensor":1,"eight":1}
,"coordinate":{"control":1}
,"point":{"piece-wise":1,"values":1,"properties":1,"g_volatile_ctrl":1,"s_ctrl":1,"scaling":1,"sensor\u2019s":1,"scaled":1,"format":1,"capability":1,"number":1,"initialization":1,"function":1,"ctrl_cid_list":1,"first":1}
,"brackets":{"actual":1}
,"exceed":{"2dynamic_pixel_width_depth":1,"2csi_pixel_width_depth":1}
,"wdr":{"dol":1,"pwl":1,"exposure":1,"frame":1,"two":1,"mode":1}
,"dol":{"digital":1,"multi-frame":1,"mode":1,"frame":1,"sensor":1}
,"overlap":{"sensors":1,"wdr":1,"multi-frame":1,"capture":1}
,"lines":{"crop":1,"required":1,"frame":1,"exposure":1,"short":1}
,"optical":{"black":1}
,"black":{"rows":1}
,"ignored":{"area":1}
,"effective":{"pixel":1}
,"header":{"exposure":1,"row":1,"pixels":1}
,"reside":{"video":1,"hence":1}
,"video":{"input":1,"linux":1,"members":1}
,"handles":{"cropping":1,"initialized":1}
,"cropping":{"lines":1,"alignment":1}
,"vbp":{"rows":1,"row":1,"vertical":1,"long":1,"4448":1}
,"appearing":{"single":1}
,"two-exposure":{"dol":1}
,"multi-frame":{"vbp":1,"number":1}
,"filtered":{"line":1,"video":1}
,"indicating":{"blank":1}
,"note":{"number":1}
,"appear":{"end":1}
,"long":{"exposure":1}
,"start":{"short":1,"line":1,"driver":1}
,"short":{"exposure":1,"coarse":1}
,"row":{"two":1,"types":1,"pixels":1,"required":1}
,"hence":{"parameter":1,"rows":1}
,"parameter":{"extended":1}
,"extended":{"number_of_offset_1":1}
,"number_of_offset_1":{"number_of_offset_2":1}
,"number_of_offset_2":{"number":1}
,"less":{"number":1}
,"pixels":{"line":1,"lines":1,"help":1,"start":1,"image":1,"required":1,"sensor":1}
,"helps":{"differentiate":1}
,"differentiate":{"vbp":1,"vertical":1}
,"vertical":{"blank":1}
,"blank":{"period":1}
,"left":{"margin":1}
,"margin":{"active":1,"right":1,"3856":1,"pixels":1}
,"alignment":{"video":1,"example":1}
,"alternative":{"pixel_t":1}
,"pixel_t":{"wdr":1}
,"pwl":{"sensor":1}
,"diagram":{"below":1,"shows":1,"example":1,"above":1}
,"multiplication":{"factor":1,"first":1}
,"factor":{"gain":1,"ensures":1,"exposure":1,"frame":1,"lower":1,"upper":1,"default":1,"step":1}
,"represent":{"float":1,"floating":1}
,"float":{"values":1,"gain_factor":1,"exposure_factor":1,"framerate_factor":1,"minimum":1,"maximum":1,"pix_clk_hz":1}
,"fixed":{"point":1}
,"ensures":{"range":1}
,"delta":{"gain":1,"value":1,"exposure":1,"frame":1}
,"configured":{"required":1}
,"default_gain":{"integer":1,"int":1}
,"scaled":{"gain_factor":1,"exposure_factor":1,"framerate_factor":1,"integers":1}
,"int":{"default":1,"numctrls":1}
,"floating":{"point":1}
,"exposure_factor":{"ensures":1}
,"framerate":{"factor":1,"value":1,"control":1,"scaled":1,"float":1}
,"default_framerate":{"integer":1,"int":1}
,"multiplied":{"gain_factor":1,"exposure_factor":1,"framerate_factor":1}
,"equation":{"calculate":1}
,"shows":{"example":1,"control":1,"values":1,"port":1,"members":1,"override":1}
,"signal":{"16-bit":1,"12-bit":1}
,"16-bit":{"depth":1}
,"12-bit":{"depth":1}
,"3840":{"2160":1,"left":1}
,"help":{"differentiate":1}
,"thus":{"three":1}
,"kinds":{"diagram":1}
,"above":{"vbp":1,"example":1,"value":1}
,"vpb":{"rows":1}
,"computed":{"follows":1}
,"total":{"width":1,"height":1,"number":1}
,"pixel-active":{"region":1}
,"region":{"case":1}
,"case":{"3840":1,"2160":1,"number":1,"adopt":1,"statement":1,"tegra_camera_cid_gain":1,"tegra_camera_cid_eeprom_data":1,"tegra_camera_cid_hdr_en":1,"tegra_camera_cid_fuse_id":1}
,"2160":{"ignored":1}
,"num_of_exposure":{"number":1}
,"exposures":{"digital":1}
,"num_of_ignored_lines":{"number":1}
,"included":{"output":1}
,"read":{"module":1,"write":1,"hardware":1}
,"cropped":{"example":1}
,"num_of_lines_offset_0":{"number":1}
,"num_of_ignored_pixels":{"number":1}
,"distinguish":{"different":1}
,"four":{"pixels":1}
,"num_of_left_margin_pixels":{"number":1}
,"num_of_right_margin_pixels":{"number":1}
,"zero":{"pixels":1}
,"definitions":{"demonstrate":1,"imx185_set_frame_rate":1,"include":1}
,"demonstrate":{"port":1}
,"nvcsi":{"sensor":1}
,"liimx185_vi_in0":{"endpoint":1}
,"liimx185_csi_in0":{"endpoint@0":1}
,"liimx185_csi_out0":{"endpoint@1":1}
,"pad":{"port":1,"binding":1,"link":1,"used":1,"source":1,"determines":1,"flags":1,"true":1}
,"connection":{"imager":1,"field":1,"two":1}
,"imager":{"devices":1,"device":1}
,"defines":{"sensor":1}
,"focuser":{"flash":1}
,"label":{"binding":1}
,"ports":{"binding":1}
,"expects":{"port":1}
,"sink":{"source":1,"pad":1,"port":1}
,"verify":{"port":1}
,"enter":{"command":1}
,"sudo":{"media-ctl":1,"rmmod":1,"insmod":1}
,"media-ctl":{"dev":1}
,"dev":{"media0":1,"v4l-subdev0":1,"i2c_client":1,"media":1,"&client-":1}
,"api":{"version":1}
,"model":{"nvidia":1}
,"revision":{"0x3":1}
,"entity":{"15a00000.nvcsi--1":1,"imx185":1,"vi-output":1,"function":1,"pads":1,"unit":1,"multiple":1,"types":1,"operations":1,"type":1,"&priv-":1,"media":1}
,"15a00000.nvcsi--1":{"pads":1,"enabled":1}
,"pads":{"links":1,"information":1,"framework":1}
,"subdev":{"subtype":1,"operations":1,"client":1,"&common_data-":1}
,"subtype":{"unknown":1,"sensor":1,"v4l":1}
,"unknown":{"flags":1}
,"pad0":{"sink":1,"source":1}
,"30-001a":{"enabled":1,"pad":1}
,"pad1":{"source":1}
,"vi-output":{"imx185":1}
,"v4l":{"flags":1}
,"potential":{"issues":1}
,"vendors":{"several":1}
,"several":{"ways":1}
,"ways":{"obtain":1,"registering":1}
,"obtain":{"correct":1,"complete":1}
,"pre":{"post":1}
,"post":{"dividers":1}
,"pre-divider":{"pll":1}
,"6.67":{"pixel_clk_hz":1,"160000000":1}
,"24000000":{"6.67":1}
,"per":{"lane":1,"pixel":1}
,"mbps":{"number":1,"per":1,"356400000":1}
,"bits":{"per":1,"fraction":1,"storing":1,"val_bits":1,"check":1,"registers":1}
,"891":{"mbps":1}
,"final":{"output":1,"calculation":1}
,"generate":{"final":1,"proper":1}
,"2200":{"1125":1}
,"1125":{"actual":1,"74250000":1}
,"1920":{"1080":1}
,"chips":{"gmsl":1}
,"soc":{"output":1}
,"therefore":{"serdes":1,"driver":1}
,"configure":{"soc-camera":1,"sensor":1}
,"soc-camera":{"interface":1}
,"buffer":{"overrun":1}
,"overrun":{"issues":1}
,"sure":{"case":1}
,"adopt":{"serdes":1}
,"specify":{"connection":1}
,"stream":{"csi":1,"functions":1,"control":1}
,"diagrams":{"show":1}
,"show":{"port":1}
,"mapping":{"different":1}
,"http":{"sw-mobile-docs":1}
,"sw-mobile-docs":{"draft":1}
,"draft":{"l4t_32":1}
,"l4t_32":{"tegra":1}
,"20linux":{"20driver":1}
,"20driver":{"20package":1}
,"20package":{"20development":1}
,"20development":{"20guide":1}
,"20guide":{"images":1}
,"images":{"image5_3.png":1}
,"topic":{"based":1,"describes":1}
,"examine":{"source":1}
,"complete":{"understanding":1,"binding":1,"add":1}
,"understanding":{"driver":1}
,"implementation":{"consult":1,"s_stream":1}
,"https":{"linuxtv.org":1}
,"linuxtv.org":{"downloads":1}
,"downloads":{"v4l-dvb-apis":1}
,"macro":{"definitions":1,"values":1}
,"sensor-specific":{"macro":1}
,"general":{"functionality":1}
,"sensor-private":{"data":1,"values":1}
,"structure":{"contains":1,"appropriate":1,"initialize":1,"members":1,"looks":1,"highlighted":1,"tells":1,"jetson":1}
,"contains":{"private":1,"switch":1}
,"private":{"data":1}
,"struct":{"imx185":1,"camera_common_power_rail":1,"v4l2_ctrl_handler":1,"i2c_client":1,"v4l2_subdev":1,"media_pad":1,"regmap":1,"camera_common_data":1,"camera_common_pdata":1,"v4l2_ctrl":1,"regmap_config":1,"v4l2_ctrl_ops":1,"v4l2_ctrl_config":1,"v4l2_subdev_video_ops":1,"v4l2_subdev_core_ops":1,"v4l2_subdev_ops":1,"of_device_id":1,"camera_common_sensor_ops":1,"v4l2_subdev_internal_ops":1,"media_entity_operations":1,"tegracam_device":1,"tegracam_ctrl_ops":1}
,"camera_common_power_rail":{"power":1}
,"v4l2_ctrl_handler":{"ctrl_handler":1,"free":1}
,"i2c_client":{"i2c_client":1,"used":1,"client":1,"dev":1,"priv-":1}
,"v4l2_subdev":{"subdev":1}
,"media_pad":{"pad":1}
,"u32":{"frame_length":1,"ctrl_cid_list":1}
,"s32":{"group_hold_prev":1}
,"bool":{"group_hold_en":1}
,"s64":{"last_wdr_et_val":1,"switch_ctrl_qmenu":1}
,"regmap":{"regmap":1,"i2c":1,"devm_regmap_init_i2c":1,"interface":1,"configuration":1}
,"camera_common_data":{"s_data":1,"file":1,"structures":1,"gfp_kernel":1,"holds":1}
,"camera_common_pdata":{"pdata":1}
,"v4l2_ctrl":{"ctrls":1}
,"generic":{"power":1}
,"including":{"regulators":1}
,"regulators":{"clocks":1,"gpio_set_value":1,"prior":1,"driver":1,"device-specific":1,"calls":1}
,"clocks":{"gpios":1}
,"holds":{"v4l2":1,"handle":1,"media":1,"previous":1,"group":1,"register":1,"handles":1,"fuse":1,"information":1,"size":1}
,"handler":{"controls":1,"check":1,"private":1,"expected":1,"sensor":1,"writes":1,"linking":1,"group":1}
,"handle":{"i2c_client":1,"v4l2":1,"common":1}
,"access":{"sensor\u2019s":1,"sensor":1,"ctrl_cid_list":1}
,"client":{"instance":1,"&sensor_regmap_config":1,"&subdev_ops":1,"passed":1}
,"subdevice":{"used":1,"camera":1,"internal":1,"function":1,"link":1,"ops":1,"handler":1,"dev":1,"registers":1,"flags":1,"media":1,"operations":1,"information":1,"unregister":1}
,"run":{"subdev":1,"board":1,"time":1}
,"operations":{"ops":1,"writes":1,"link":1,"examples":1,"sensor":1,"described":1,"handled":1}
,"initialize":{"media":1,"structure":1,"controls":1,"core":1,"default":1,"camera":1,"register":1,"values":1,"regmap":1,"sensor":1,"framework":1}
,"work":{"sink":1}
,"previous":{"state":1,"value":1,"exposure":1,"config_video":1}
,"hold":{"control":1,"enable":1,"hdr":1,"register":1,"functionality":1,"handler":1,"pointers":1}
,"check":{"change":1,"vendor\u2019s":1,"sensors":1}
,"change":{"state":1,"camera":1,"controls":1,"format":1}
,"flag":{"directly":1}
,"directly":{"related":1}
,"related":{"group":1,"registers":1}
,"register":{"map":1,"address":1,"value":1,"programming":1,"write":1,"frame":1,"hold":1,"setup":1,"themselves":1,"subdevice":1,"addresses":1,"controls":1,"read":1,"imx185":1,"device":1,"driver":1}
,"map":{"setup":1}
,"setup":{"i2c":1,"functions":1,"likely":1,"default":1,"media":1,"ensure":1,"successful":1}
,"populated":{"reading":1}
,"reading":{"device":1,"writing":1,"settings":1,"eeprom":1}
,"initialized":{"v4l2":1,"values":1}
,"array":{"last":1,"register":1,"based":1,"address":1}
,"configuring":{"regmap":1,"controls":1,"peripherals":1}
,"update":{"sensor_regmap_config":1,"sensor":1,"rebuild":1,"device":1,"camera":1}
,"sensor_regmap_config":{"structure":1,"looks":1}
,"reg_bits":{"val_bits":1,"holds":1}
,"val_bits":{"describe":1,"members":1,"holds":1}
,"describe":{"sensor\u2019s":1,"functions":1}
,"members":{"structure":1,"follows":1,"references":1,"appropriate":1,"according":1}
,"regmap_config":{"sensor_regmap_config":1,"structure\u2019s":1}
,"vendor\u2019s":{"register":1}
,"determine":{"values":1,"bits":1,"proper":1}
,"structure\u2019s":{"members":1,"reg_bits":1}
,"linked":{"control":1}
,"define":{"static":1,"scaling":1,"states":1,"driver":1,"fixed_point_scaling_factor":1,"sensor":1,"additional":1,"tegracam_ctrl_ops":1}
,"static":{"v4l2_ctrl_ops":1,"const":1,"struct":1,"sensor":1,"data":1}
,"v4l2_ctrl_ops":{"structure":1,"imx185_ctrl_ops":1}
,"g_volatile_ctrl":{"sensor\u2019s":1}
,"internal":{"volatile":1,"control":1,"operation":1,"media":1}
,"volatile":{"control":1}
,"s_ctrl":{"sensor\u2019s":1,"perform":1,"function":1}
,"const":{"struct":1,"s64":1,"u32":1}
,".g_volatile_ctrl":{"imx185_g_volatile_ctrl":1}
,".s_ctrl":{"imx185_s_ctrl":1}
,"lists":{"controls":1}
,"initial":{"ctrls_init":1}
,"ctrls_init":{"call":1}
,"call":{"loops":1,"function":1,"imx185_power_get":1,"imx185_power_put":1,"placeholder":1,"power_get":1,"power_put":1}
,"loops":{"list":1}
,"list":{"initialize":1,"names":1,"known":1}
,"accessible":{"ctrls":1}
,"ctrls":{"handler":1}
,"ones":{"used":1}
,"user-mode":{"library":1}
,"implement":{"additional":1,"either":1,"function":1,"handler":1,"sensor":1}
,"additional":{"controls":1,"control-handling":1,"components":1}
,"menu":{"string":1,"control":1}
,"v4l2_ctrl_config":{"ctrl_config_list":1}
,"setting":{"integer":1,"control":1,"v4l2":1,"takes":1,"device":1,"registers":1,"necessary":1,"kernel":1,"camera":1}
,".ops":{"&imx185_ctrl_ops":1}
,"&imx185_ctrl_ops":{"pointer":1}
,"pointer":{"control":1,"following":1}
,"ops":{"function":1,"setting":1,"imx185_common_ops":1,"hold":1,"communicate":1,"update":1,"ops":1,"implemented":1,"used":1,"tegra":1}
,".id":{"tegra_camera_cid_gain":1,"tegra_camera_cid_group_hold":1,"tegra_camera_cid_fuse_id":1,"tegra_camera":1}
,"tegra_camera_cid_gain":{"defined":1,"tegra_camera_cid_frame_rate":1}
,".name":{"gain":1,"group":1,"fuse":1}
,".type":{"v4l2_ctrl_type_integer":1,"v4l2_ctrl_type_integer_menu":1,"v4l2_ctrl_type_string":1}
,"v4l2_ctrl_type_integer":{"type":1}
,".flags":{"v4l2_ctrl_flag_slider":1,"v4l2_ctrl_flag_read_only":1}
,"v4l2_ctrl_flag_slider":{"control":1}
,"scaling":{"factor":1,"factors":1}
,"likely":{"change":1,"need":1}
,".min":{"fixed":1}
,"lower":{"bound":1,"bits":1}
,".max":{"fixed":1,"array_size":1,"imx185_fuse_id_str_size":1}
,"upper":{"bound":1,"bits":1}
,".def":{"fixed":1}
,".step":{"fixed":1}
,"increment":{"step":1}
,"step":{"size":1,"properties":1}
,"switch_ctrl_qmenu":{"used":1}
,"need":{"change":1,"modify":1,"changed":1,"added":1}
,"unless":{"add":1}
,"enum":{"switch_state":1}
,"array_size":{"switch_ctrl_qmenu":1,"ctrl_config_list":1,"imx185_frmfmt":1,"ctrl_cid_list":1}
,".qmenu_int":{"switch_ctrl_qmenu":1}
,"eeprom":{"content":1,"data":1,"otp":1,"fuse":1,"programmed":1}
,"content":{"fuse":1}
,"helper":{"functions":1,"function":1}
,"functions":{"below":1,"wrappers":1,"regmap":1,"power-related":1,"used":1,"highlighted":1,"file":1,"boot-time":1,"sensor":1,"interfaces":1,"control":1,"handlers":1}
,"below":{"update":1,"shows":1,"point":1,"match":1,"generate":1,"unregister":1}
,"registers":{"based":1,"read":1,"using":1,"time":1,"majority":1,"control":1,"media":1,"functions":1,"values":1,"device":1}
,"takes":{"two":1,"32-bit":1}
,"parameters":{"array":1,"deprecated":1,"required":1,"include":1}
,"handlers":{"call":1,"control":1,"writes":1,"called":1,"actual":1,"jetsonv4l2":1,"fill-string":1,"writing":1,"reading":1,"update":1,"defined":1}
,"updates":{"address":1,"gain":1,"frame":1,"coarse":1,"short":1,"sensor":1}
,"program":{"sensor":1,"frame":1,"registers":1}
,"write":{"wrapper":1,"single":1,"table":1,"functions":1,"control":1}
,"wrapper":{"functions":1,"register":1,"function":1}
,"read-write":{"wrapper":1,"interface":1}
,"wrappers":{"reading":1,"read-write":1}
,"writing":{"sensor":1,"settings":1}
,"modify":{"sensor":1,"function":1,"declaration":1,"functions":1}
,"power-related":{"controls":1}
,"implements":{"sensor":1,"tegra_camera_cid_frame_rate":1}
,"power-on":{"sequence":1}
,"regulator_enable":{"turn":1}
,"turn":{"regulators":1}
,"gpio_set_value":{"toggle":1}
,"toggle":{"gpio":1}
,"power-off":{"sequence":1}
,"resources":{"used":1,"regulators":1,"prior":1}
,"regulator_put":{"release":1,"regulators":1}
,"release":{"resources":1,"regulators":1}
,"camera_common_regulator_get":{"helper":1}
,"regulator_get":{"acquire":1,"function":1}
,"acquire":{"regulators":1}
,"imx185_power_get":{"first":1,"priv":1}
,"prior":{"calling":1,"removing":1}
,"calling":{"imx185_power_on":1}
,"imx185_power_on":{"imx185_power_off":1}
,"additionally":{"driver":1}
,"imx185_power_put":{"release":1}
,"imx185_s_stream":{"function":1}
,"enables":{"disables":1}
,"disables":{"sensor":1}
,"streaming":{"programs":1,"states":1,"enabling":1,"disabling":1,"controls":1}
,"programs":{"sensor":1}
,"tables":{"file":1,"override":1,"programmed":1,"mode":1}
,"imx185_mode_tbls.h":{"file":1}
,"instead":{"using":1,"following":1}
,"override":{"settings":1,"gain":1,"information":1,"data":1}
,"providing":{"updated":1,"link":1}
,"immediately":{"mode":1}
,"tegra_camera":{"_cid_frame_rate":1,"_cid_exposure":1}
,"err":{"v4l2_g_ext_ctrls":1,"imx185_set_gain":1,"imx185_fuse_id_setup":1}
,"v4l2_g_ext_ctrls":{"&priv-":1}
,"&priv-":{"ctrl_handler":1,"power":1,"subdev-":1,"pad":1}
,"ctrl_handler":{"&cotrl":1,"&priv-":1}
,"imx185_set_gain":{"priv":1,"file":1}
,"priv":{"control":1,"devm_kzalloc":1,"void":1}
,"test":{"pattern":1}
,"pattern":{"enable":1,"mode":1,"setting":1}
,"selecting":{"proper":1}
,"proper":{"test":1,"values":1,"register":1,"information":1,"override":1}
,"sets":{"v4l2":1,"sensor":1,"controls":1}
,"camera_common_sensor_ops":{"camera_common_data":1,"imx185_common_ops":1}
,"structures":{"define":1,"highlighted":1}
,"details":{"modifying":1,"definition":1,"freeing":1,"mode":1,"control":1}
,"modifying":{"adding":1}
,"adding":{"new":1,"code":1}
,"modes":{"mode":1}
,"snippets":{"v4l2":1}
,"subdevices":{"camera":1}
,"registering":{"sensor":1,"jetson":1,"controls":1,"device":1}
,"s_stream":{"pointer":1,"function":1}
,"declaration":{"highlighted":1,"initialize":1}
,"highlighted":{"below":1}
,"leave":{"pointers":1}
,"v4l2_subdev_video_ops":{"imx185_subdev_video_ops":1}
,".s_stream":{"imx185_s_stream":1}
,"v4l2_subdev_core_ops":{"imx185_subdev_core_ops":1}
,"references":{"two":1}
,"corresponding":{"structures":1,"media":1}
,"v4l2_subdev_ops":{"imx185_subdev_ops":1}
,".core":{"&imx185_subdev_core_ops":1}
,".video":{"&imx185_subdev_video_ops":1}
,"member":{"of_device_id":1,"identify":1,"number":1,"point":1}
,"of_device_id":{"structure":1,"imx185_of_match":1}
,"match":{"specified":1,"name":1,"devices":1}
,"identify":{"bind":1}
,".compatible":{"nvidia":1}
,"declaration\u2019s":{"power_on":1}
,"power_on":{"power_off":1}
,"power_off":{"write_reg":1,"call":1}
,"write_reg":{"read_reg":1}
,"read_reg":{"members":1}
,".power_on":{"imx185_power_on":1}
,".power_off":{"imx185_power_off":1}
,".write_reg":{"imx185_write_reg":1}
,".read_reg":{"imx185_read_reg":1}
,"top-level":{"structure":1}
,"tells":{"function":1}
,"expected":{"handle":1}
,"implemented":{"sensor":1}
,"needs":{"dedicated":1}
,"dedicated":{"control":1}
,"originally":{"floating":1}
,"integers":{"respective":1}
,"respective":{"scaling":1,"property-value":1}
,"factors":{"example":1}
,"discussion":{"fixed":1}
,"seconds":{"exposure":1,"available":1,"information":1,"used":1}
,"supporting":{"feature":1}
,"empty":{"control":1}
,"operating":{"hdr":1}
,"normal":{"sensor":1}
,"reads":{"module\u2019s":1,"sensor":1,"camera\u2019s":1,"one-time":1}
,"one-time":{"programmable":1,"tasks":1}
,"programmable":{"otp":1,"read-only":1}
,"otp":{"memory":1,"fuse":1,"data":1}
,"memory":{"data":1,"case":1,"common":1,"sensor-private":1}
,"zero-based":{"index":1}
,"overrides":{"gain":1}
,"per-frame":{"gain":1}
,"32-bit":{"64-bit":1,"mode":1,"value":1}
,"64-bit":{"input":1,"mode":1,"value":1}
,"24.8":{"format":1}
,"24\u2011bit":{"integer":1}
,"8\u2011bit":{"fraction":1}
,"fraction":{"default":1,"fixed":1,"values":1}
,"adjust":{"min":1}
,"min":{"max":1}
,"max":{"gain":1}
,"42.22":{"format":1}
,"42\u2011bit":{"integer":1}
,"22\u2011bit":{"fraction":1}
,"exercise":{"exposure":1}
,"pair":{"32\u2011bit":1,"controls":1,"used":1}
,"32\u2011bit":{"input":1}
,"64\u2011bit":{"may":1,"exposure":1}
,"tegra_camera_cid_frame_length":{"tegra_camera_cid_coarse_time":1}
,"pre-processed":{"32-bit":1}
,"converts":{"frame":1,"exposure":1}
,"tegra_camera_cid_frame_rate":{"v4l2":1,"tegra_camera_cid_exposure":1,"controls":1}
,"unprocessed":{"64-bit":1,"except":1}
,"passes":{"frame":1}
,"pre-processing":{"driver":1}
,"responsible":{"converting":1}
,"converting":{"values":1}
,"imx185_set_frame_rate":{"imx185_set_exposure":1}
,"imx185_set_exposure":{"functions":1}
,"tegra_camera_cid_exposure":{"controls":1,"tegra_camera_cid_exposure_short":1}
,"q42.22":{"fixed":1,"format":1}
,"storing":{"integer":1}
,"workaround":{"lack":1}
,"lack":{"floating":1}
,"capability":{"kernel":1}
,"multiply":{"convert":1}
,"back":{"floating":1,"original":1,"linux":1}
,"divide":{"manifest":1}
,"manifest":{"constant":1}
,"constant":{"fixed_point_scaling_factor":1,"values":1}
,"fixed_point_scaling_factor":{"represents":1,"1ull":1,"160":1}
,"minimize":{"loss":1}
,"loss":{"precision":1}
,"precision":{"perform":1}
,"division":{"example":1}
,"statements":{"yield":1}
,"yield":{"different":1}
,"u64":{"gain64":1}
,"gain64":{"10485760":1,"fixed_point_scaling_factor":1,"160":1}
,"10485760":{"2.5":1}
,"2.5":{"fixed_point_scaling_factor":1}
,"gain8":{"gain64":1}
,"incorrect":{"gain8":1}
,"160":{"fixed_point_scaling_factor":1}
,"set-control":{"operation":1,"function":1,"calls":1}
,"statement":{"redirect":1,"control":1}
,"redirect":{"set-control":1}
,"calls":{"appropriate":1,"control":1,"simply":1,"initialization":1,"regulator_enable":1,"regulator_put":1,"camera_common_regulator_get":1,"power_on":1,"device":1}
,"read-only":{"controls":1,"memory":1,"driver-specific":1}
,"tegra_camera_cid_fuse_id":{"reads":1}
,"tegra_camera_cid_otp_data":{"reads":1}
,"tegra_camera_cid_hdr_en":{"pure":1}
,"pure":{"software":1}
,"writes":{"hardware":1,"registers":1}
,"simply":{"break":1,"return":1,"unload":1}
,"break":{"switch":1}
,"setter-control":{"handlers":1}
,"called":{"s_ctrl":1,"control":1,"device":1,"v4l2":1,"during":1}
,"control-handling":{"operations":1}
,"majority":{"controls":1}
,"get-volatile":{"control":1}
,"imx185_g_volatile_ctrl":{"wrapper":1}
,"redirects":{"get-control":1}
,"get-control":{"calls":1}
,"non-volatile":{"controls":1}
,"return":{"previously":1}
,"previously":{"written":1}
,"written":{"value":1}
,"stored":{"control":1,"private":1}
,"boot-time":{"initialization":1}
,"sections":{"describe":1}
,"imx185_ctrls_init":{"function":1,"call":1,"priv":1}
,"iterates":{"ctrl_config_list":1,"entries":1}
,"ctrl_config_list":{"registers":1}
,"custom":{"control":1,"v4l2":1}
,"imx185_s_ctrl":{"called":1}
,"fuse":{"implement":1,"information":1,"provide":1,"otp":1,"configuring":1}
,"imx185_fuse_id_setup":{"priv":1}
,"imx185_parse_dt":{"function":1,"client":1}
,"parses":{"device":1}
,"trees":{"searches":1,"device":1,"stored":1}
,"searches":{"device":1}
,"gpios":{"regulators":1}
,"device-specific":{"properties":1}
,"names":{"device":1}
,"few":{"additional":1}
,"components":{"needed":1}
,"open":{"function":1,"operation":1}
,"placeholder":{"operation":1}
,"operation":{"satisfying":1,"requirements":1,"setter":1,"details":1}
,"satisfying":{"v4l2":1}
,"requirements":{"setup":1,"main":1}
,"changed":{"apart":1}
,"apart":{"changing":1}
,"changing":{"name":1}
,".open":{"imx185_open":1}
,"validation":{"method":1}
,"media_entity_operations":{"imx185_media_ops":1}
,".link_validate":{"v4l2_subdev_link_validate":1}
,"probing":{"functions":1}
,"entry":{"point":1,"provide":1}
,"initialization":{"during":1,"functions":1,"details":1,"assigns":1,"read":1,"perform":1}
,"during":{"boot":1,"final":1,"sensor":1,"initialization":1,"driver":1,"normal":1,"camera":1}
,"imx185_probe":{"function":1}
,"driver\u2019s":{"entry":1}
,"allocates":{"memory":1}
,"common_data":{"devm_kzalloc":1,"imx185":1}
,"devm_kzalloc":{"&client-":1}
,"&client-":{"dev":1}
,"sizeof":{"struct":1,"tc_dev-":1}
,"initializes":{"regmap":1,"context":1}
,"priv-":{"regmap":1,"i2c_client":1,"s_data":1,"subdev":1,"subdev-":1,"pad.flags":1,"tc_dev":1}
,"devm_regmap_init_i2c":{"client":1}
,"section":{"parser":1,"describes":1}
,"parser":{"device":1}
,"pdata":{"field":1}
,"v4l2_i2c_subdev_init":{"&common_data-":1}
,"&common_data-":{"subdev":1}
,"next":{"function":1}
,"links":{"common":1,"once":1,"devices":1}
,"common_data-":{"ops":1,"ctrl_handler":1,"i2c_client":1,"frmfmt":1,"colorfmt":1,"power":1,"priv":1,"numfmts":1,"def_mode":1,"def_width":1,"def_height":1,"def_clk_freq":1}
,"passed":{"probe":1}
,"frmfmt":{"imx185_frmfmt":1}
,"generally":{"defaults":1}
,"colorfmt":{"camera_common_find_datafmt":1}
,"power-handler":{"linking":1}
,"void":{"priv":1}
,"numfmts":{"array_size":1}
,"camera_common_initialize":{"common_data":1}
,"def_mode":{"imx185_default_mode":1}
,"def_width":{"imx185_default_width":1}
,"def_height":{"imx185_default_height":1}
,"def_clk_freq":{"imx185_default_clk_freq":1}
,"s_data":{"common_data":1}
,"subdev-":{"dev":1,"internal_ops":1,"flags":1,"entity.type":1,"entity.ops":1,"entity":1}
,"themselves":{"sub-devices":1}
,"sub-devices":{"media":1,"registered":1}
,"acts":{"primary":1}
,"primary":{"device":1}
,"establishes":{"media":1}
,"once":{"sub-devices":1,"setup":1}
,"defining":{"entity":1}
,"represented":{"media":1,"device":1}
,"establishing":{"connections":1}
,"connections":{"media":1}
,"known":{"entity":1}
,"behaves":{"sink":1}
,"bound":{"imager":1}
,"binds":{"device":1}
,"internal_ops":{"imx185_subdev_internal_ops":1}
,"flags":{"media":1,"v4l2_subdev_fl_has_devnode":1}
,"pad.flags":{"media_pad_fl_source":1}
,"entity.type":{"media_ent_t_v4l2_subdev_sensor":1}
,"entity.ops":{"&imx185_media_ops":1}
,"tegra_media_entity_init":{"&priv-":1}
,"v4l2_async_register_subdev":{"priv-":1}
,"removing":{"sensor":1,"code":1}
,"imx185_remove":{"function":1}
,"shutdown":{"release":1}
,"unregister":{"v4l2":1,"subdevice":1,"sensor":1,"driver":1}
,"v4l2_async_unregister_subdev":{"priv-":1}
,"cleanup":{"unregister":1}
,"media_entity_cleanup":{"&priv-":1}
,"freeing":{"control":1}
,"free":{"&priv-":1}
,"clean":{"camera":1}
,"camera_common_cleanup":{"s_data":1}
,"control-specific":{"data":1}
,"macros":{"define":1}
,".dtsi":{"file":1,"proper":1}
,"fuse_id":{"fuse_id_size":1}
,"tegracam_device":{"tc_dev":1,"used":1,"structure":1,"gfp_kernel":1}
,"char":{"array":1}
,"camera_common.h":{"details":1}
,"tegracam_core.h":{"details":1}
,"displays":{"custom":1}
,"1:n":{"ratio":1}
,"1:3":{"yielding":1}
,"yielding":{"amplification":1}
,"gain_factor":{"property":1}
,"described":{"property-value":1,"below":1,"load":1}
,"running":{"hdr":1}
,"forces":{"jetson":1}
,"bypassing":{"default":1}
,"bypass":{"settings":1}
,"controlled":{"exposure":1}
,"tegra_camera_cid_exposure_short":{"tegra_camera_cid_frame_rate":1,"control":1,"controls":1}
,"optional":{"may":1,"called":1}
,"conversion":{"fixed":1}
,"receives":{"control":1}
,"original":{"precisions":1}
,"precisions":{"during":1}
,"implementations":{"controls":1}
,"jetsonv4l2":{"camera":1}
,"setter":{"control":1,"controls":1}
,"fill-string":{"control":1,"controls":1}
,"tegra_camera_cid_group_hold":{"control":1}
,"functionality":{"create":1}
,"dummy":{"group":1}
,"report":{"static":1}
,"driver-specific":{"controls":1}
,"provide":{"valid":1,"link":1,"size":1}
,"space":{"requests":1}
,"requests":{"routine":1}
,"routine":{"acquires":1}
,"assigns":{"controls":1}
,"ctrl_cid_list":{"structure":1,"member":1,"registering":1}
,"tegracam_ctrl_ops":{"structure":1,"imx185_ctrl_ops":1}
,"numctrls":{"member":1}
,".set_gain":{"imx185_set_gain":1}
,".set_exposure":{"imx185_set_exposure":1}
,".set_frame_rate":{"imx185_set_frame_rate":1}
,".set_group_hold":{"imx185_set_group_hold":1}
,".string_ctrl_size":{"imx185_fuse_id_str_size":1}
,".fill_string_ctrl":{"imx185_fill_string_ctrl":1}
,"eight":{"fill-string":1}
,"power_get":{"acquire":1}
,"power_put":{"release":1}
,"enabling":{"stream":1}
,"necessary":{"registers":1}
,"stops":{"sensor":1}
,"disabling":{"stream":1}
,"miscellaneous":{"functions":1}
,"parsing":{"called":1}
,"critical":{"one-time":1}
,"peripherals":{"needed":1}
,"pointers":{"functions":1}
,"compliant":{"sensor":1}
,"handled":{"automatically":1}
,"automatically":{"jetson":1,"rebuilding":1,"links":1}
,".numctrls":{"array_size":1}
,".ctrl_cid_list":{"ctrl_cid_list":1}
,"formats":{"format":1}
,".numfrmfmts":{"array_size":1}
,".frmfmt_table":{"imx185_frmfmt":1}
,".power_get":{"imx185_power_get":1}
,".power_put":{"imx185_power_put":1}
,".parse_dt":{"imx185_parse_dt":1}
,".set_mode":{"imx185_set_mode":1}
,".start_streaming":{"imx185_start_streaming":1}
,".stop_streaming":{"imx185_stop_streaming":1}
,"instantiated":{"kernel":1}
,"boot":{"time":1}
,"steps":{"performed":1}
,"errors":{"reported":1}
,"reported":{"driver":1}
,"creates":{"new":1}
,"gives":{"access":1}
,"entries":{"sets":1,"proper":1}
,"gets":{"device":1}
,"looks":{"parameters":1}
,"sensor-related":{"private":1}
,"sensor-driver":{"probing":1}
,"tc_dev":{"devm_kzalloc":1,"void":1,"true":1}
,"context":{"needed":1}
,"tc_dev-":{"i2c_client":1,"name":1,"dev_regmap_config":1,"sensor_ops":1,"tcctrl_ops":1}
,"strncpy":{"tc_dev-":1}
,"dev_regmap_config":{"&sensor_regmap_config":1}
,"sensor_ops":{"&imx185_common_ops":1}
,"tcctrl_ops":{"&imx185_ctrl_ops":1}
,"tegracam_device_register":{"tc_dev":1}
,"tegracam_set_privdata":{"tc_dev":1}
,"finally":{"registers":1}
,"successful":{"register":1}
,"tegracam_v4l2subdev_register":{"tc_dev":1}
,"removes":{"sensor":1}
,"instance":{"framework":1}
,"tegracam_v4l2subdev_unregister":{"priv-":1}
,"tegracam_device_unregister":{"priv-":1}
,"loadable":{"kernel":1,"module":1}
,"lkm":{"mechanism":1,"helpful":1}
,"built":{"loadable":1,"configure":1}
,"helpful":{"during":1}
,"development":{"especially":1,"complete":1}
,"especially":{"debugging":1}
,"debugging":{"rather":1}
,"rather":{"flash":1}
,"flash":{"new":1}
,"unload":{"driver":1,"old":1}
,"rebuild":{"driver":1,"kernel":1}
,"load":{"rebuilt":1,"described":1,"new":1,"sensor":1}
,"rebuilt":{"driver":1,"may":1}
,"place":{"setting":1}
,"configuration":{"file":1,".dtsi":1}
,"replacing":{"previous":1}
,"config_video":{"setting":1,"camera":1}
,"copy":{"sensor":1}
,"alternatively":{"linux":1}
,"drover":{"automatically":1}
,"rebuilding":{"kernel":1}
,"flashing":{"jetson":1}
,".ko":{"built":1,"extension":1}
,"old":{"sensor":1}
,"rmmod":{"sensor_lkm_module_basename":1}
,"basename":{"filename":1}
,"filename":{"without":1}
,"insmod":{"path_to_sensor_drive_file":1}
,"finished":{"developing":1}
,"developing":{"driver":1}
,"enabled":{"kernel":1}
,"config_video_":{"camera":1}
,"kernel-4.9":{"arch":1}
,"arch":{"arm64":1}
,"arm64":{"configs":1}
,"configs":{"tegra_defconfig":1}
,"registered":{"instantiated":1}
,"boots":{"two":1,"plugin":1,"override":1}
,"plugin":{"manager":1}
,"on-board":{"eeprom":1}
,"manager":{"register":1,"automatically":1,"uses":1,"allows":1,"support":1,".dtsi":1}
,"meet":{"requirements":1}
,"main":{"platform":1}
,"directions":{"using":1}
,"bootloader":{"update":1}
,"runtime":{"plugin":1}
,"allows":{"single":1}
,"replace":{"camera":1}
,"reboot":{"new":1}
,"works":{"automatically":1}
,"synchronizing":{"kernel":1}
,"status":{"device":1,"disabled":1,"okay":1}
,"imx185_cam0":{"imx185_a@1a":1}
,"ids":{"lprd-002001":1}
,"found":{"kernel":1}
,"applied":{"specific":1}
,"made":{"available":1}
}
;Search.control.loadWordPairs(pairs);
