var pairs =
{
"jetson":{"nano":1,"linux":1,"download":1,"tx1":1,"module":1}
,"nano":{"adaptation":1,"describes":1,"processor":1,"som":1,"developer":1,"identified":1,"necessary":1,"2gb":1,"module":1,"p3541":1,"users":1,"p3449":1,"variant":1,"porg":1,"pinmux":1,"configuration":1,"jetson_nano_module":1,"device":1,"0000":1,"a02":1,"sku":1,"include":1,"nvidia":1,"arch":1,"configs":1,"board":1,"p3448-0000":1,"p3448-0002":1,"support":1,"reference":1,"devices":1,"supporting":1,"carrier":1,"xhci":1,"usb":1,"pin":1,"xudc":1}
,"adaptation":{"bring-up":1}
,"topic":{"software":1,"l4t":1,"kernel":1,"flashing":1,"u\u2011boot":1}
,"software":{"developers":1,"upstreamed":1,"designed":1}
,"developers":{"whose":1}
,"whose":{"target":1}
,"target":{"nvidia":1,"device":1,"device\u2019s":1,"rootfs":1,"config":1,"uphy":1,"lane":1}
,"nvidia":{"jetson":1,"nvidia":1,"reference":1,"board":1,"customization":1,"dtsfilename":1,"p3450-0000":1,"p3541-0000":1,"p3450-porg":1,"recommends":1,"contains":1,"specific":1,"gpu":1,"soc":1,"platform":1,"linux":1,"function":1,"representative":1,"usb2-companion":1,"oc-pin":1,"xusb-padctl.txt":1,"boost_cpu_freq":1,"boost_cpu_trigger":1,"xusb-padctl":1,"tegra-xhci.txt":1,"tegra-xudc.txt":1}
,"describes":{"port":1,"usb":1}
,"port":{"nvidia":1,"plan":1,"nine":1,"verified":1,"according":1,"numbers":1,"number":1,"capability":1,"usb2":1,"port":1,"mapped":1,"usb3":1,"using":1,"jetson":1,"root":1,"node":1,"usb":1,"switch":1,"otg":1,"separate":1,"switching":1,"operating":1,"fixed":1,"host-only":1,"except":1,"transitions":1,"plus":1}
,"linux":{"l4t":1,"kernel":1,"standard":1,"root":1,"driver":1,"network":1,"documentation":1}
,"l4t":{"u-boot":1,"release":1}
,"u-boot":{"bootloader":1,"linux":1,"command":1,"source":1,"rather":1}
,"bootloader":{"developer":1,"configuration":1,"pinmux":1,"uses":1}
,"developer":{"kit":1,"kits":1}
,"kit":{"hardware":1,"developer":1,"comprises":1,"develop":1,"used":1,"p3450":1,"intended":1,"p3541":1,"code":1,"carrier":1,"jetson":1,"included":1,"cannot":1}
,"hardware":{"platforms":1,"\u200Cnvidia":1,"nvidia":1,"support":1,"custom-designed":1,"nodes":1,"cameras":1,"sure":1}
,"board":{"configuration":1,"som":1,"eeprom":1,"developer":1,"developed":1,"custom":1,"need":1,"jetson":1,"p3448-0003":1,"naming":1,"assign":1,"combination":1,"names":1,"name":1,"original":1,"using":1,"initialization":1,"schematic":1,"change":1,"_pinmux.xlsm":1,"based":1,"prompted":1,"appropriate":1,"example":1,".dts":1,".dtb":1,"_defconfig":1,"vendor":1,"nvidia":1,"refer":1,"maintainers":1,"board":1,"provide":1,"required":1,"enable":1,"look":1,"consult":1,"note":1,"provided":1,"design":1,"p3449":1,"p3542-0000":1,"find":1,"controlled":1,"verify":1}
,"configuration":{"developer":1,"odm":1,"support":1,"boot":1,"file\u2019s":1,"applied":1,"download":1,"board":1,"tab":1,"want":1,"data":1,"generate":1,"needs":1,"file":1,"files":1,"parameter":1}
,"processor":{"contained":1}
,"contained":{"system":1,"subdirectories":1}
,"system":{"module":1,"network":1,"install":1,"present":1,"configured":1,"along":1,"assumes":1}
,"module":{"som":1,"carrier":1,"name":1,"example":1,"note":1,"socket":1,"review":1}
,"som":{"supported":1,"reference":1,"custom":1,"p3448-0000":1,"micro":1,"flash":1,"sold":1,"attached":1,"similar":1}
,"supported":{"developer":1,"value":1}
,"comprises":{"som":1,"jetson":1}
,"reference":{"carrier":1,"manual":1}
,"carrier":{"board":1,"board\u2019s":1,"p-number":1,"boards":1,"ver":1,".dts":1,"-0000.dtb":1,"-0000-":1,"dtb":1}
,"eeprom":{"store":1,"board":1}
,"store":{"carrier":1}
,"board\u2019s":{"board":1,"version":1,"vendor":1,"pinmux":1,"device":1,"uphy":1,"requirements":1,"schematic":1}
,"develop":{"applications":1}
,"applications":{"incorporated":1}
,"incorporated":{"production":1}
,"production":{"systems":1,"emmc":1,"jetson":1}
,"incorporate":{"jetson":1,"relevant":1}
,"custom":{"carrier":1,"board":1,"fan":1}
,"developed":{"application":1}
,"application":{"change":1}
,"change":{"kernel":1,"pinmux":1,"properties":1,"anything":1,"detected":1,"project\u2019s":1,"secondary":1}
,"kernel":{"device":1,"source":1,"proc":1,"command":1,"advisable":1,"sources":1,"customization":1,"kernel-4.9":1,"dtb":1,"debug":1,"uses":1,"code":1,"always":1,"configuration":1,"includes":1,"dtb\u2019s":1,"directory":1,"image":1,"build":1,"without":1,"reduces":1,"boot":1}
,"device":{"tree":1,"holds":1,"executing":1,"original":1,"version":1,"new":1,"labels":1,"jetson-nano-devkit":1,"jetson-nano-emmc":1,"jetson-nano-2gb-devkit":1,"tree\u2019s":1,"port":1,"otg":1,"type":1,"role":1,"drivers":1,"driver":1,"node":1,"wake":1}
,"tree":{"bootloader":1,"file":1,"files":1,"image":1,"source":1,"schema":1,"kernel":1,"overlay":1,"edit":1,"hardware":1,"located":1,"review":1,"necessary":1,"structure":1,"changes":1,"examples":1,"node":1,"properties":1}
,"odm":{"data":1}
,"data":{"flashing":1,"pair":1,"follow":1,"transmit":1,"receive":1}
,"flashing":{"configuration":1,"procedures":1,"booting":1,"module":1}
,"support":{"new":1,"platforms":1,"jetson":1,"board":1,"sensors":1,"add-in":1,"kernel":1,"three":1,"multiple":1,"configurations":1,"usb":1,"contain":1,"contains":1,"phandle":1}
,"new":{"carrier":1,"file":1,"pinmux":1,"hardware":1,"look":1}
,"need":{"eeprom":1,"include":1,"procedure":1,"change":1,"property":1,"control":1,"cpu":1,"boosted":1,"specify":1,"changed":1}
,"procedures":{"topic":1,"sure":1}
,"release":{"includes":1,"tree":1,"timelines":1}
,"includes":{"example":1,"support":1}
,"example":{"code":1,"vendor":1,"p3450":1,"access":1,"define":1,"create":1,"host-only":1,"consider":1,"otg":1,"suppose":1,"shows":1,"j28":1,"defines":1}
,"code":{"developer":1,"support":1,"user-visible":1,"without":1,"supports":1,"codename":1,"\u200Ckernel-dts":1,"-platforms":1,"-pinmux-p3448-":1,"correct":1,"add":1}
,"used":{"model":1,"development":1,"few":1,"uphy":1,"controller":1}
,"model":{"code":1}
,"p3450":{"comprises":1,"appropriate":1,"represent":1}
,"p3448-0000":{"p3449-0000":1,"som":1,"five-year":1,"p3448-0002":1,"device":1,"jetson-nano-sd.conf":1,"jetson-nano-qspi.conf":1}
,"p3449-0000":{"carrier":1}
,"micro":{"card":1,"connector":1}
,"card":{"slot":1,"som":1,"directly":1,"original":1}
,"slot":{"instead":1,"p3448-0000":1,"otherwise":1}
,"instead":{"built-in":1,"micro":1,"kernel":1}
,"built-in":{"ram":1,"qspi":1}
,"ram":{"install":1}
,"install":{"micro":1,"som\u2019s":1,"configure":1,"lightdm":1,"component":1,"lightdm-gtk-greeter":1,"enable":1,"lxde":1}
,"flash":{"host":1,"card":1,"device":1,"configuration":1,"dtb":1,"drive":1,"qspi":1,"emmc":1,"jetson":1}
,"host":{"system":1,"accessible":1,"directory":1,"device":1,"e.g":1,"driver":1,"controller":1,"role":1}
,"network":{"connection":1}
,"connection":{"flash":1}
,"directly":{"host":1,"excel":1,"extlinux.conf":1}
,"som\u2019s":{"card":1}
,"sold":{"component":1,"separately":1}
,"component":{"jetson":1,"enter":1}
,"intended":{"development":1}
,"p3448-00002":{"som":1}
,"separately":{"production":1}
,"emmc":{"storage":1,"appropriate":1,"original":1,"size":1}
,"storage":{"instead":1,"card":1,"specify":1}
,"otherwise":{"similar":1}
,"similar":{"p3448-0000":1,"original":1}
,"five-year":{"operating":1}
,"operating":{"lifetime":1,"host":1}
,"lifetime":{"qualified":1}
,"qualified":{"deployment":1}
,"deployment":{"commercial":1}
,"commercial":{"environments":1}
,"environments":{"used":1}
,"development":{"p3449":1,"kit\u2019s":1,"however":1}
,"p3449":{"carrier":1,"p3452":1}
,"identified":{"original":1,"step":1}
,"original":{"jetson":1}
,"necessary":{"distinguish":1,"change":1}
,"distinguish":{"variants":1}
,"2gb":{"developer":1,"som":1,"devboard":1,"p3542":1,"batuu":1,"jetson_nano_2gb_module":1,"0003":1,"absent":1,"sku":1,"include":1,"nvidia":1,"arch":1,"configs":1,"board":1,"p3448-0003":1,"version":1,"carrier":1,"jetson-nano-2gb-devkit.conf":1}
,"p3541":{"consists":1,"appropriate":1}
,"consists":{"p3448-0003":1}
,"p3448-0003":{"som":1,"device":1,"jetson-nano-2gb-devkit.conf":1}
,"attached":{"p3542-0000":1,"usb":1}
,"p3542-0000":{"carrier":1,"consult":1}
,"p3448-0002":{"built-in":1,"device":1,"jetson-nano-qspi.conf":1,"jetson-nano-emmc.conf":1}
,"qspi":{"storage":1,"original":1,"card":1}
,"assign":{"module":1}
,"combination":{"lower":1,"carrier":1}
,"lower":{"case":1}
,"case":{"alphanumeric":1,"letters":1}
,"alphanumeric":{"name":1}
,"name":{"name":1,"may":1,"choose":1,"character":1,"nvidia":1,"board":1,"obvious":1,"power-tree":1,"chosen":1,"board\u2019s":1,"based":1,"e.g":1,"tab":1,"device":1,"matches":1,"mismatch":1,"rather":1,"function":1,"parameter":1,"extcon":1,"output":1,"vbus_id":1,"vbus":1,"thermal-fan-est":1,"compton":1,"rename":1}
,"may":{"contain":1,"add":1,"different":1,"considered":1,"backported":1,"reduce":1,"want":1}
,"contain":{"hyphens":1,"several":1,"entry":1,"pointer":1,"pointers":1}
,"hyphens":{"underscores":1}
,"underscores":{"spaces":1}
,"spaces":{"following":1}
,"following":{"examples":1,"procedures":1,"locations":1,"actions":1,"directory":1,"tables":1,"schematic":1,"table":1,"odd-numbered":1}
,"examples":{"valid":1,"u-boot":1,"based":1}
,"valid":{"board":1,"gpios":1}
,"appropriate":{"original":1,"jetson":1,"value":1,"targeted":1,"board":1,"reference":1,"configuration":1}
,"choose":{"appear":1,"similarly":1}
,"appear":{"file":1}
,"file":{"names":1,"system":1,"name":1,"writable":1,"microsoft":1,"button":1,"forms":1,"sys":1,"generated":1,"include":1,"arch":1,"configs":1,"technique":1,"location":1,"device":1,"nvidia":1,"included":1,"xdg":1,"p3448-0000.conf.common":1}
,"names":{"path":1,"u-boot":1,"exposed":1,"lower":1,"default":1,"wired":1,"form":1}
,"path":{"names":1}
,"source":{"code":1,"file":1,"tree":1,"available":1,"contained":1,"upstreamed":1,"package":1}
,"user-visible":{"device":1}
,"exposed":{"user":1,"assigned":1}
,"user":{"via":1,"experience":1}
,"via":{"u-boot":1,"gpio":1,"device":1}
,"command":{"prompt":1,"line":1,"device":1,"displays":1,"convert":1,"build":1,"check":1}
,"prompt":{"various":1,"asks":1}
,"various":{"linux":1}
,"proc":{"files":1,"device-tree":1}
,"similarly":{"constructed":1}
,"constructed":{"vendor":1}
,"vendor":{"name":1,"organization\u2019s":1,"board":1}
,"character":{"rules":1}
,"rules":{"apply":1}
,"apply":{"example":1,"xudc":1}
,"simply":{"re-use":1}
,"re-use":{"modify":1}
,"modify":{"existing":1,"spreadsheet":1,"kernel":1,"recompile":1,"device":1,"two":1}
,"existing":{"jetson":1}
,"without":{"choosing":1,"having":1,"changing":1}
,"choosing":{"using":1}
,"using":{"board":1,"script":1,"following":1,"value":1,"properties":1}
,"obvious":{"jetson":1}
,"users":{"whether":1}
,"whether":{"modified":1,"wish":1,"need":1}
,"modified":{"source":1,"customize":1,"kernel":1,"cboot":1,"device":1}
,"supports":{"carrier":1,"otg":1,"highspeed":1,"notifier":1,"usb":1}
,"placeholders":{"porting":1,"substitute":1,"used":1}
,"porting":{"instructions":1,"u-boot":1,"linux":1,"usb":1}
,"sections":{"below":1,"defined":1}
,"below":{"refer":1,"table":1,"suggestions":1}
,"refer":{"filenames":1,"board":1,"documentation":1,"reference":1,"fan":1}
,"filenames":{"pathnames":1,"nvidia":1}
,"pathnames":{"contain":1}
,"several":{"common":1}
,"common":{"placeholders":1,"file":1}
,"substitute":{"appropriate":1}
,"value":{"placeholder":1,"sdcard":1,"positive":1,"cpu":1,"extcon-gpio-states":1,"array":1,"greater":1}
,"placeholder":{"enter":1}
,"enter":{"commands":1,"prefix":1,"command":1}
,"few":{"sections":1}
,"defined":{"sections":1,"pcie":1,"state":1,"thermal":1,"active_trip_temps":1,"active_pwm":1}
,"function":{"functional":1,"string":1,"mux":1,"pcie-x1":1,"pcie-x4":1,"xusb":1,"host":1,"device":1,"owns":1,"check":1}
,"functional":{"module":1}
,"power-tree":{"pinmux":1}
,"pinmux":{"sdmmc-drv":1,"changes":1,"configuration":1,"table":1,"spreadsheet":1,"settings":1,"jetson":1}
,"sdmmc-drv":{"keys":1}
,"keys":{"comm":1}
,"comm":{"wi\u2011fi":1}
,"wi\u2011fi":{"bluetooth":1}
,"bluetooth":{"camera":1}
,"p-number":{"reference":1}
,"version":{"reference":1,"number":1,"table":1,"jetson":1,"identified":1,".dtb":1,".dts":1,"omit":1,"preceding":1,"-a00.dts":1}
,"number":{"a00":1,"files":1,"cores":1,"outputs":1,"cells":1,"register":1}
,"a00":{".dts":1}
,".dts":{"filenames":1,"appropriate":1,"file":1,"files":1}
,"boards":{"include":1,"designed":1}
,"include":{"version":1,"configs":1,"entry":1}
,"files":{"customer":1,"directory":1,"names":1,"generated":1,"applied":1,"rebuild":1,"define":1,"directly":1,"pinmux":1,"saved":1,"linux":1,"board":1,"boot":1,"dtbos":1,"refer":1,"p3449_b01_concept_schematics.pdf":1,"jetson":1,"described":1,"whether":1}
,"customer":{"platforms":1}
,"platforms":{"need":1}
,"codename":{"jetson":1}
,"variant":{"using":1}
,"chosen":{"represent":1}
,"represent":{"combination":1,"carrier":1,"data":1}
,"note":{"nvidia":1,"directory":1,"tegra":1}
,"organization\u2019s":{"name":1}
,"root":{"device":1,"file":1,"filesystem":1,"hub":1}
,"holds":{"platform\u2019s":1}
,"platform\u2019s":{"root":1}
,"present":{"supported":1}
,"filesystem":{"configuration":1,"rootfs":1,"provided":1,"may":1}
,"standard":{"customized":1,"usb":1}
,"customized":{"linux":1,"jetson":1}
,"rootfs":{"appropriate":1,"configurations":1,"location":1,"kernel":1,"append":1}
,"targeted":{"embedded":1}
,"embedded":{"application":1}
,"however":{"certain":1,"considering":1}
,"certain":{"settings":1}
,"settings":{"configured":1,"device":1,"external":1,"otg-compatible":1,"above":1,"flashing":1}
,"configured":{"rootfs\u2019s":1,"execute":1,"target":1}
,"rootfs\u2019s":{"boot-up":1}
,"boot-up":{"framework":1,"perform":1}
,"framework":{"default":1}
,"default":{"configuration":1,"board":1,"value":1,"display":1,"lightdm":1}
,"boot":{"core":1,"extlinux":1,"dts":1,"adds":1,"load":1,"directory":1,"expressed":1,"time":1,"storage":1}
,"core":{"functionalities":1}
,"functionalities":{"run":1}
,"run":{"expected":1,"macro":1}
,"expected":{"configuration":1}
,"file\u2019s":{"pathname":1}
,"pathname":{"boot":1,"windows":1,"kernel":1}
,"extlinux":{"extlinux.conf":1}
,"line":{"parameters":1}
,"parameters":{"passed":1,"e.g":1,"port":1,"applicable":1}
,"passed":{"boot":1}
,"execute":{"nv.sh":1}
,"nv.sh":{"nvfb-early.sh":1}
,"nvfb-early.sh":{"nvfb.sh":1}
,"nvfb.sh":{"scripts":1}
,"scripts":{"systemd":1}
,"systemd":{"boot-up":1}
,"perform":{"basic":1,"following":1}
,"basic":{"default":1,"flashing":1}
,"initialization":{"kernel":1}
,"advisable":{"add":1}
,"add":{"folder":1,"support":1,"remove":1,"tegra210-":1,"target":1,"driver":1,"quiet":1}
,"folder":{"delete":1}
,"delete":{"anything":1}
,"xorg":{"libraries":1}
,"libraries":{"correctly":1}
,"correctly":{"configured":1}
,"device\u2019s":{"nvpmodel":1,"design":1}
,"nvpmodel":{"number":1}
,"cores":{"clock":1}
,"clock":{"frequency":1}
,"frequency":{"configured":1,"boosted":1,"dvfs":1,"further":1,"pmqos":1}
,"configurations":{"customizations":1,"tables":1}
,"customizations":{"provided":1}
,"provided":{"driver":1,"nvidia":1,"bsp":1,"developer":1,"external":1,"host":1,"cable":1}
,"driver":{"package":1,"described":1,"xhci":1,"xudc":1,"node":1}
,"package":{"directory":1,"toolchain":1}
,"directory":{"subdirectories":1,"stored":1,"spreadsheet":1,"contains":1,"contents":1,"linux_for_tegra":1,"flashing":1,"instead":1,"ethernet":1}
,"linux_for_tegra":{"nv_tegra":1,"apply_binaries.sh":1,"kernel":1}
,"relevant":{"customization":1}
,"customization":{"target":1,"applied":1,"instructions":1}
,"sample":{"root":1}
,"applied":{"using":1,"software":1,"cboot":1,"follow":1}
,"script":{"linux_for_tegra":1}
,"schematic":{"differs":1,"file":1,"conclude":1,"j28":1,"example":1}
,"differs":{"developer":1}
,"define":{"board\u2019s":1,"pinmux":1,"manifest":1,"phy":1,"trip":1}
,"download":{"appropriate":1,"center":1,"linux":1,"jetson":1}
,"table":{"jetson":1,"som":1,"uphy":1,"gpio":1,"modified":1}
,"center":{"customize":1,"modify":1}
,"customize":{"configuration":1,"pinmux":1,"settings":1}
,"sure":{"right":1,"file":1,"observe":1,"understand":1,"target":1}
,"right":{"version":1,"click":1}
,"create":{"copy":1,"device":1,"custom":1,"pcie":1,"pad":1,"xhci":1,"table":1,"extcon":1,"xudc":1,"configuration":1}
,"copy":{"file":1,"need":1,"generated":1,"updated":1,"device":1,"directory":1,"kernel":1}
,"based":{"board":1,"name":1,"schematic":1,"device":1,"design":1,"need":1}
,"e.g":{"board":1,"gpio":1,"usb":1,"connect":1}
,"_pinmux.xlsm":{"note":1}
,"stored":{"copy":1,"macro":1}
,"procedure":{"updating":1}
,"updating":{"bootloader":1}
,"ensure":{"new":1}
,"windows":{"open":1,"host":1}
,"open":{"new":1}
,"microsoft":{"excel":1}
,"excel":{"displays":1,"spreadsheet":1}
,"displays":{"warnings":1,"file":1,"output":1}
,"warnings":{"protected":1}
,"protected":{"view":1}
,"view":{"security":1}
,"security":{"warning":1}
,"warning":{"click":1}
,"click":{"enable":1,"jetson":1,"rename":1,"generate":1}
,"enable":{"editing":1,"content":1,"disable":1,"vdd_hub_3v3":1,"autologin":1,"lxde":1}
,"editing":{"enable":1}
,"content":{"save":1}
,"save":{"changes":1}
,"changes":{"new":1,"port":1,"device":1,"root":1,"may":1}
,"rename":{"jetson":1,"menu":1,"device-specific":1}
,"tab":{"based":1,"bottom":1,"press":1}
,"bottom":{"window":1}
,"menu":{"option":1}
,"type":{"board":1,"port_number":1,"usb2":1,"plug":1,"plug\u2019s":1,"application":1}
,"press":{"enter":1}
,"spreadsheet":{"columns":1,"reflects":1,"stored":1,"configure":1,"modified":1,"remember":1,"following":1,"click":1,"file":1}
,"columns":{"grouped":1}
,"grouped":{"heading":1}
,"heading":{"filled":1}
,"filled":{"customers":1}
,"customers":{"required":1}
,"required":{"pinmux":1,"device":1}
,"once":{"spreadsheet":1}
,"reflects":{"configuration":1}
,"want":{"click":1,".conf":1,"dynamic":1}
,"generate":{"file":1,"files":1,"device":1}
,"button":{"run":1}
,"macro":{"exports":1,"prompts":1}
,"exports":{"configuration":1}
,"pair":{".dtsi":1,"wired":1}
,".dtsi":{"files":1}
,"prompts":{"enter":1}
,"prefix":{"files":1,"-pinmux.dtsi":1,"-gpio.dtsi":1,"filename":1,"entered":1}
,"cboot":{"bootloader":1,"reapplied":1,"cboot":1,"passes":1}
,"uses":{"device":1,"u27":1,"j28":1}
,"generated":{"pinmux":1,".dtsi":1,"sure":1,"dtb":1}
,"configure":{"pinmux":1,"lightdm":1}
,"reapplied":{"linux":1}
,"updated":{"device":1}
,"rebuild":{"device":1,"kernel":1}
,"image":{"jetson":1,"l4t":1,"kernel":1,"host":1,"boot":1,"alone":1,"target\u2019s":1}
,"update":{"device":1,"kernel":1}
,"sources":{"instructions":1,"git":1,"topic":1,"downloaded":1,"provided":1}
,"instructions":{"section":1}
,"section":{"obtaining":1,"jetson":1,"basic":1,"gives":1,"uses":1,"discusses":1}
,"obtaining":{"kernel":1}
,"git":{"manually":1}
,"manually":{"downloading":1}
,"downloading":{"expanding":1}
,"expanding":{"kernel":1}
,"build":{"environment":1,"device":1,"kernel":1}
,"environment":{"installing":1,"variable":1}
,"installing":{"toolchain":1}
,"toolchain":{"setting":1,"topic":1}
,"setting":{"environment":1}
,"variable":{"cross_compile":1}
,"cross_compile":{"described":1}
,"described":{"section":1,"linux":1,"above":1,"xusb":1}
,"determine":{"sku":1}
,"sku":{"version":1,"carrier":1,"sku":1,"jetson":1,"followed":1,"alone":1,"module\u2019s":1}
,"executing":{"command":1}
,"cat":{"proc":1}
,"device-tree":{"nvidia":1}
,"tegra210-p3448-":{"sku":1}
,"ver":{".dts":1,"version":1,"example":1}
,"0000":{"0002":1}
,"0002":{"jetson":1}
,"a02":{"b00":1}
,"b00":{"jetson":1}
,"absent":{"preceding":1,"device":1}
,"preceding":{"hyphen":1}
,"hyphen":{"absent":1,"followed":1}
,"locate":{"directory":1}
,"contains":{"pinmux":1,"spreadsheet":1,"source":1,"nvidia":1,"two":1,"extcon-cable":1}
,"remember":{"pathname":1}
,"accessible":{"linux":1}
,"-pinmux.dtsi":{"src":1}
,"src":{"hardware":1,"pathname":1}
,"\u200Cnvidia":{"platform":1}
,"platform":{"\u200Ct210":1,"t210":1}
,"\u200Ct210":{"code":1}
,"\u200Ckernel-dts":{"code":1}
,"-platforms":{"\u200Ctegra210-":1,"\u200Cjetson_nano_2gb_module-pinmux.dtsi":1}
,"\u200Ctegra210-":{"code":1}
,"-pinmux-p3448-":{"sku_ver":1}
,"sku_ver":{".dtsi":1,"module\u2019s":1}
,"-gpio.dtsi":{"src":1}
,"filename":{"prefix":1}
,"entered":{"step":1}
,"step":{"customize":1}
,"downloaded":{"step":1}
,"module\u2019s":{"sku":1}
,"followed":{"hyphen":1,"ver":1}
,"alone":{"i.e":1}
,"i.e":{"0003":1}
,"src_path":{"kernel":1}
,"arch":{"arm64":1,"arm":1}
,"arm64":{"tegra_defconfig":1,"dtbs":1,"boot":1}
,"dts":{"tegra210-p3448-":1,"tegra210-":1,"tegra210-p3450-porg.dts":1,"tegra210-p3541-0000.dts":1,"makefile":1,"back":1,"dtb":1}
,"-0000.dtb":{"path-to-l4t-release":1}
,"path-to-l4t-release":{"kernel":1}
,"reflash":{"target":1,"kernel":1}
,"follow":{"instructions":1,"examples":1}
,"booting":{"target":1}
,"accessing":{"gpios":1}
,"gpios":{"via":1,"routed":1,"list":1,"states":1,"provided":1,"&gpio":1}
,"gpio":{"device":1,"expansion":1,"file":1,"lists":1,"irq":1,"states":1,"state":1,"corresponds":1}
,"access":{"gpios":1,"gpio-19":1}
,"routed":{"40-pin":1}
,"40-pin":{"gpio":1}
,"expansion":{"header":1}
,"header":{"via":1}
,"labels":{"begin":1}
,"begin":{"gpio":1}
,"sys":{"kernel":1}
,"debug":{"gpio":1}
,"lists":{"labels":1,"functions":1}
,"gpio-19":{"enter":1}
,"gpiofind":{"spi0_cs0":1}
,"exporting":{"pinmux":1}
,"answer":{"prompt":1}
,"asks":{"whether":1}
,"wish":{"generate":1}
,"provide":{"name":1,"correct":1,"plugin":1}
,"saved":{"location":1}
,"location":{"excel":1,"jetson":1}
,"matches":{"kernel":1}
,"correct":{"file":1,"maintainer":1,"pmic":1,"function":1}
,"mismatch":{"later":1}
,"later":{"copy":1}
,"actions":{"u-boot":1}
,"configs":{"board":1,"p3450-0000.h":1,"p3541-0000.h":1,"p3450-0000_defconfig":1,"p3541-0000_defconfig":1}
,"edit":{"enabled":1,"nodes":1,"board":1,"arch":1,"files":1,"kernel":1}
,"enabled":{"devices":1,"xhci":1,"xudc":1}
,"devices":{"features":1,"parameters":1,"verify":1,"further":1,"nvidia":1}
,"features":{"board":1,"connected":1}
,"manifest":{"constant":1}
,"constant":{"config_tegra_board_string":1}
,"arm":{"dts":1,"mach-tegra":1}
,"tegra210-":{"board":1}
,"irq":{"ids":1,"flags":1}
,"ids":{"tegra210-":1}
,"remove":{"edit":1,"revise":1}
,"nodes":{"properties":1,"necessary":1,"define":1}
,"always":{"exactly":1,"connected":1}
,"exactly":{"device":1}
,"schema":{"bindings":1}
,"bindings":{"represent":1,"nvidia":1,"pinctrl":1,"phy":1,"usb":1,"extcon":1}
,"rather":{"linux":1,"p3450-porg":1}
,".dtb":{"arch":1,"tegra210-p3448-":1}
,"_defconfig":{"refer":1}
,"mach-tegra":{"tegra210":1}
,"tegra210":{"kconfig":1}
,"kconfig":{"add":1}
,"config":{"kconfig":1,"mmcblk0p1":1,"basename":1}
,"contents":{"board":1}
,"p3450-porg":{"p3541-0000":1}
,"maintainers":{"provide":1}
,"maintainer":{"contact":1}
,"contact":{"information":1}
,"information":{"board":1,".dts":1,"design":1,"xusb_padctl":1,"xhci":1,"state":1,"extcon":1,"xudc":1}
,"pmic":{"programming":1}
,"programming":{"board":1}
,"two":{"ways":1,"groups":1,"flash":1}
,"ways":{"adapt":1}
,"adapt":{"device":1}
,"overlay":{"files":1}
,"adds":{"kernel":1}
,"dtb":{"support":1,"sources":1,"replace":1,"recompiled":1,"host":1,"alone":1,"dts":1,"tegra210-p3448-":1,"sure":1,"following":1,"included":1,"selected":1,"partition":1,"config":1}
,"recommends":{"technique":1,"lightdm":1}
,"technique":{"types":1,"yields":1,"supporting":1}
,"types":{"hardware":1,"interfaces":1,"cables":1}
,"sensors":{"add-in":1}
,"add-in":{"boards":1,"hardware":1}
,"yields":{"complete":1}
,"complete":{"modified":1,"flash":1,"device":1}
,"supporting":{"fixed":1,"software":1}
,"fixed":{"hardware":1,"device":1}
,"custom-designed":{"carrier":1}
,"available":{"download":1,"outputs":1}
,"bsp":{"add":1}
,"revise":{"kernel":1}
,"dtb\u2019s":{"hardware":1}
,"properties":{"differ":1,"pads":1,"listed":1,"apply":1,"xusb_padctl":1}
,"differ":{"recompile":1}
,"recompile":{"dtb":1,"reflash":1}
,"replace":{"development":1,"reference":1,"according":1}
,"kit\u2019s":{"dtb":1}
,"recompiled":{"reflash":1}
,"creating":{"device":1,"custom":1}
,"load":{"device":1,"cpu":1}
,"dtbos":{"directly":1}
,"extlinux.conf":{"feature":1,"target":1}
,"feature":{"lets":1,"carrier":1,"support":1,"disable":1}
,"lets":{"add":1}
,"cameras":{"controllers":1}
,"controllers":{"spi":1}
,"spi":{"without":1}
,"having":{"decompile":1}
,"decompile":{"modify":1}
,"u\u2011boot":{"customization":1,"turn":1}
,"modifying":{"kernel":1,"device":1}
,"subdirectories":{"kernel":1}
,"kernel-4.9":{"contains":1,"documentation":1}
,"specific":{"software":1}
,"nvgpu":{"contains":1}
,"gpu":{"driver":1,"soc":1}
,"documentation":{"modifying":1,"documentation":1,"devicetree":1}
,"observe":{"points":1}
,"soc-related":{"device":1}
,"top":{"hardware":1}
,"soc":{"t210":1,"technical":1,"thermal":1}
,"generally":{"need":1,"controlled":1,"pin":1}
,"board-related":{"device":1}
,"t210":{"code":1,"porg":1}
,"disable":{"feature":1,"kernel":1}
,"review":{".dts":1,"modify":1,"parameters":1}
,"building":{"kernel":1}
,"sudo":{"flash.sh":1,"apt-get":1,"dpkg-reconfigure":1}
,"flash.sh":{"config":1,"dtb":1}
,"basename":{"flash":1}
,"convert":{"dtb":1,"dts":1}
,"dtc":{"dtb":1,"dts":1}
,"-0000-":{"version":1}
,"omit":{"version":1}
,"back":{"dtb":1,"forth":1}
,"-a00.dts":{"tegra210-p3448-":1}
,"replacing":{"reference":1}
,"look":{"instances":1,"user":1}
,"instances":{"carrier":1}
,"understand":{"replace":1}
,"according":{"needs":1,"custom":1,"uphy":1,"state":1}
,"plugin":{"manager":1}
,"manager":{"support":1,"ubuntu":1,"lightdm":1,"enter":1,"lxde":1}
,"included":{"file":1,"carrier":1,"design":1}
,"along":{"kernel":1,"parameters":1}
,"selected":{"dtb":1}
,"partition":{"modified":1}
,"passes":{"u\u2011boot":1,"kernel":1}
,"turn":{"passes":1}
,"changing":{"data":1}
,"steps":{"update":1}
,"target\u2019s":{"boot":1}
,"detailed":{"information":1}
,"devicetree":{"bindings":1}
,"three":{"superspeed":1}
,"superspeed":{"usb":1,"data":1,"on-board":1,"hub":1,"protocols":1}
,"usb":{"ports":1,"3.0":1,"structure":1,"port":1,"pcie":1,"2.0":1,"nvidia":1,"on-the-go":1,"otg":1,"act":1,"supports":1,"connector":1,"type":1,"connectors":1,"hdmi":1,"pin":1,"vbus":1,"charger":1}
,"ports":{"implementations":1,"used":1,"device":1,"describe":1,"form":1,"subnode":1}
,"implementations":{"ports":1}
,"uphy":{"lane":1,"handled":1,"lanes":1,"physical":1}
,"lane":{"sharing":1,"mapping":1,"uphy":1,"assignment":1,"support":1,"assignments":1,"exposed":1,"usb":1,"mux":1,"recognized":1,"owned":1,"assigned":1}
,"sharing":{"among":1}
,"among":{"pcie":1}
,"pcie":{"xusb":1,"single":1,"subnode":1,"lanes":1}
,"designed":{"verified":1,"support":1,"internal":1}
,"verified":{"usb":1,"cases":1}
,"3.0":{"port":1,"realtek":1,"differential":1,"signal":1,"superspeed":1}
,"plan":{"create":1}
,"consult":{"product":1,"nvidia":1}
,"product":{"design":1}
,"design":{"guide":1,"custom":1,"jetson":1,"files":1,"consider":1}
,"guide":{"jetson":1}
,"verify":{"board\u2019s":1,"lane":1}
,"mapping":{"functionally":1,"issues":1,"issue":1,"consulting":1,"table":1,"temperature":1}
,"functionally":{"compatible":1}
,"compatible":{"appropriate":1,"port":1,"value":1,"extcon-gpio-states":1,"thermal-fan-est":1,"pwm-fan":1}
,"nine":{"pins":1}
,"sstx":{"sstx":1,"superspeed":1,"ssrx":1}
,"ssrx":{"ssrx":1,"superspeed":1,"signal":1}
,"gnd_drain":{"drain":1}
,"drain":{"wire":1}
,"wire":{"termination":1,"u27":1,"j28":1}
,"termination":{"managing":1}
,"managing":{"emi":1}
,"emi":{"rfi":1}
,"rfi":{"signal":1}
,"signal":{"integrity":1,"pins":1,"pairs":1,"pair":1,"pulse":1}
,"pins":{"connect":1,"usb_dp":1,"115":1,"161":1,"wire":1}
,"connect":{"utmi":1,"uphy":1,"flash":1}
,"utmi":{"pads":1,"pad":1}
,"pads":{"sstx":1,"ports":1,"subnode":1,"usb2":1,"pcie":1}
,"handled":{"single":1}
,"single":{"uphy":1}
,"lanes":{"shared":1,"assigned":1,"uphy":1,"usb2-1":1,"pcie-6":1,"usb2-0":1}
,"shared":{"pcie":1}
,"xusb":{"uphy":1,"functions":1,"node":1}
,"assigned":{"according":1,"uphy":1,"pcie-x1":1,"correctly":1}
,"universal":{"physical":1}
,"physical":{"layer":1,"interface":1}
,"layer":{"uphy":1,"serve":1}
,"interface":{"layer":1}
,"serve":{"multiple":1}
,"multiple":{"types":1}
,"interfaces":{"e.g":1}
,"cases":{"uphy":1,"example":1}
,"assignments":{"shown":1}
,"shown":{"following":1}
,"outputs":{"reference":1}
,"output":{"type":1,"cable":1}
,"assignment":{"cases":1,"defined":1}
,"pin":{"names":1,"group":1,"port":1,"called":1,"added":1,"grounded":1,"floating":1,"vbus_detect":1,"gpio_pz1":1,"complete":1,"pin":1,"designed":1,"pulled":1,"depends":1,"matter":1,"settings":1,"connector":1,"extcon":1}
,"pex_tx1":{"pex_rx1":1}
,"pex_tx2":{"pex_rx2":1}
,"pex_tx3":{"pex_rx3":1}
,"pex_tx4":{"pex_rx4":1}
,"pex_tx6":{"pex_rx6":1}
,"tables":{"tegra":1}
,"tegra":{"soc":1,"technical":1}
,"technical":{"reference":1}
,"manual":{"trm":1,"applies":1}
,"trm":{"consult":1}
,"further":{"information":1,"based":1}
,"applies":{"jetson":1}
,"subnode":{"xusb_padctl":1,"lists":1,"property":1,"pads":1,"properties":1}
,"xusb_padctl":{"corresponding":1,"node":1,"based":1,"refer":1,"xusb_padctl@7009f000":1,"settings":1,"sure":1}
,"corresponding":{"device":1,"utmi":1,"gpio":1,"output":1,"pulse":1,"cooling":1}
,"tree\u2019s":{"xusb_padctl":1}
,"node":{"follows":1,"property":1,"definition":1,"host-only":1,"properties":1}
,"follows":{"conventions":1}
,"conventions":{"document":1,"pinctrl-bindings.txt":1}
,"pinctrl":{"pinctrl-bindings.txt":1}
,"functions":{"assigned":1}
,"string":{"containing":1,"describes":1}
,"containing":{"name":1,"commands":1}
,"mux":{"pin":1,"may":1}
,"group":{"values":1,"xusb":1}
,"property":{"xusb_padctl":1,"values":1,"list":1,"valid":1,"file":1}
,"structure":{"described":1}
,"status":{"okay":1}
,"pcie-x1":{"xusb":1}
,"gives":{"step-by-step":1}
,"step-by-step":{"guidance":1}
,"guidance":{"checking":1}
,"checking":{"schematics":1}
,"schematics":{"configuring":1}
,"configuring":{"usb":1}
,"host-only":{"port":1}
,"u27":{"usb":1,"lead":1,"realtek":1,"reference":1,"based":1}
,"realtek":{"superspeed":1}
,"on-board":{"hub":1}
,"hub":{"example":1,"reference":1,"itself":1,"always":1,"port":1,"power":1,"create":1}
,"p3452":{"jetson":1}
,"obtain":{"design":1}
,"check":{"usb":1,"pinmux":1,"lane":1,"values":1}
,"find":{"pin":1,"wired":1,"corresponding":1}
,"wired":{"socket":1,"utmi":1,"uphy":1,"gpio00":1}
,"socket":{"jetson":1,"pins":1,"location":1}
,"2.0":{"signal":1,"highspeed":1,"micro":1}
,"usb_dp":{"usb_dm":1}
,"usb_dm":{"wire":1}
,"lead":{"module":1,"111":1}
,"115":{"usb1_dn":1}
,"usb1_dn":{"116":1}
,"116":{"usb1_dp":1}
,"screenshot":{"cell":1}
,"cell":{"phonedescription":1}
,"phonedescription":{"automatically":1}
,"automatically":{"generated":1}
,"differential":{"signal":1}
,"pairs":{"usp_sstx":1,"wired":1,"tegra":1}
,"usp_sstx":{"usp_ssrx":1}
,"usp_ssrx":{"wire":1}
,"161":{"sbss_rx_n":1}
,"sbss_rx_n":{"163":1}
,"163":{"usbss_rx_p":1}
,"usbss_rx_p":{"166":1}
,"166":{"usbss_tx_n":1}
,"usbss_tx_n":{"168":1}
,"168":{"usbss_tx_p":1}
,"conclude":{"u27":1}
,"pad":{"usb2":1,"&battery_reg":1,"port":1}
,"usb2":{"port":1,"usb3":1,"property":1,"lanes":1}
,"pinctrl-bindings.txt":{"contains":1}
,"groups":{"named":1}
,"named":{"pads":1}
,"describe":{"usb2":1}
,"usb3":{"signals":1,"port_number":1,"property":1,"port":1}
,"signals":{"along":1}
,"numbers":{"name":1}
,"parameter":{"description":1,"quiet":1,"already":1,"config_tegra_\u200C210_dvfs":1}
,"description":{"subnode":1}
,"form":{"type":1}
,"port_number":{"type":1,"associated":1}
,"associated":{"port":1}
,"mode":{"string":1,"host":1,"usb":1,"otg":1,"maxn":1}
,"capability":{"port":1}
,"usb2-companion":{"usb2":1}
,"mapped":{"port":1}
,"oc-pin":{"overcurrent":1}
,"overcurrent":{"vbus":1,"detection":1}
,"vbus":{"pin":1,"regulator":1,"provided":1}
,"positive":{"zero":1}
,"detection":{"handling":1,"support":1,"driver":1}
,"handling":{"u27":1}
,"controlled":{"hub":1,"host":1,"pwm":1}
,"itself":{"therefore":1}
,"therefore":{"need":1,"dummy":1,"state":1,"below":1}
,"vbus-supply":{"vbus":1,"&battery_reg":1,"&p3449_vdd_usb_vbus":1}
,"regulator":{"corresponding":1}
,"&battery_reg":{"dummy":1}
,"dummy":{"regulator":1,"regulators":1}
,"connected":{"root":1,"usb2":1,"device":1,"pin":1,"cable":1,"remains":1,"vbus_detect":1,"logical":1,"boot":1,"property":1}
,"control":{"hub":1,"mapping":1}
,"power":{"just":1,"supply":1,"mode":1}
,"just":{"enable":1,"otg":1}
,"vdd_hub_3v3":{"therefore":1}
,"regulators":{"u27":1}
,"phy":{"nvidia":1,"used":1,"phy-names":1}
,"consider":{"u27":1,"following":1}
,"list":{"u27":1,"using":1,"gpios":1,"based":1,"j28":1}
,"xhci":{"controller":1,"specifications":1,"documentation":1,"node":1,"device":1,"settings":1}
,"controller":{"complies":1,"names":1,"field\u2019s":1,"therefore":1,"supports":1}
,"complies":{"xhci":1}
,"specifications":{"support":1}
,"highspeed":{"fullspeed":1,"mode":1}
,"fullspeed":{"lowspeed":1,"usb":1}
,"lowspeed":{"usb":1}
,"phys":{"contain":1,"xusb_padctl@7009f000":1,"array":1}
,"entry":{"entry":1,"phy-names":1,"phy":1,"usb":1,"detects":1}
,"phy-names":{"include":1,"usb2-1":1,"usb2-0":1,"array":1,"usb2":1}
,"boost_cpu_freq":{"value":1}
,"cpu":{"frequency":1,"loading":1,"boost":1,"load":1,"gpu":1}
,"boosted":{"minimum":1}
,"minimum":{"frequency":1,"buffer":1}
,"dvfs":{"scale":1}
,"scale":{"cpu":1}
,"loading":{"cpu":1}
,"boost":{"frequency":1,"applicable":1}
,"pmqos":{"enabled":1}
,"field\u2019s":{"greater":1,"value":1}
,"greater":{"zero":1}
,"zero":{"boost":1}
,"applicable":{"bulk":1,"large":1,".conf":1}
,"bulk":{"isoc":1,"transfers":1,"endpoints":1}
,"isoc":{"transfers":1}
,"transfers":{"endpoints":1,"beyond":1,"bulk":1}
,"endpoints":{"need":1,"endpoints":1}
,"boost_cpu_trigger":{"minimum":1}
,"buffer":{"length":1}
,"length":{"bulk":1}
,"beyond":{"boost":1}
,"xusb-padctl":{"pointer":1,"node":1,"&xusb_padctl":1}
,"pointer":{"xusb-padctl":1,"extcon-cable":1}
,"xusb_padctl@7009f000":{"pads":1}
,"usb2-1":{"usb3-0":1}
,"otg":{"on-the-go":1,"just":1,"specification":1,"port":1,"features":1,"feature":1,"cable":1,"a-device":1,"roles":1}
,"on-the-go":{"compatible":1,"often":1}
,"often":{"abbreviated":1,"device":1}
,"abbreviated":{"usb":1}
,"specification":{"allows":1}
,"allows":{"usb":1}
,"act":{"host":1}
,"switch":{"back":1}
,"forth":{"roles":1}
,"roles":{"host":1,"generally":1,"defined":1}
,"fifth":{"pin":1}
,"called":{"pin":1}
,"added":{"standard":1}
,"connector":{"otg":1,"example":1,"j28":1,"class":1,"wired":1,"create":1}
,"cable":{"usb":1,"connected":1,"states":1,"names":1,"state":1}
,"plug":{"end":1,"inserted":1,"connected":1}
,"end":{"type":1}
,"plug\u2019s":{"pin":1}
,"grounded":{"type":1}
,"floating":{"device":1,"j28":1,"vbus_detect":1,"port":1}
,"inserted":{"becomes":1}
,"becomes":{"otg":1,"b-device":1}
,"a-device":{"host":1}
,"b-device":{"device":1}
,"j28":{"fixed":1,"usb":1,"lead":1,"supports":1,"connector\u2019s":1,"function":1,"corresponding":1,"usb2.0":1,"based":1}
,"role":{"developer":1,"jetson":1}
,"cannot":{"function":1}
,"drive":{"keyboard":1}
,"keyboard":{"mouse":1}
,"connectors":{"reference":1,"may":1}
,"111":{"usb0_dp":1}
,"usb0_dp":{"109":1}
,"109":{"usb0_dn":1}
,"usb0_dn":{"module":1}
,"external":{"connector":1,"connectors":1,"power":1}
,"class":{"extcon":1}
,"different":{"types":1}
,"cables":{"attached":1}
,"hdmi":{"analog":1}
,"analog":{"others":1}
,"others":{"often":1}
,"drivers":{"detect":1,"something":1}
,"detect":{"state":1}
,"state":{"changes":1,"pin":1,"vbus_detect":1,"change":1,"following":1,"otg-compatible":1,"pwm":1}
,"separate":{"device":1}
,"something":{"according":1}
,"extcon":{"supports":1,"node":1,"device":1,"refer":1,"extcon-gpio-states.txt":1,"settings":1,"cable":1,"specifier":1}
,"notifier":{"passing":1}
,"passing":{"information":1}
,"switching":{"otg":1}
,"xudc":{"defined":1,"node":1,"controller":1,"refer":1}
,"vbus_detect":{"pin":1,"logical":1,"initially":1}
,"suppose":{"gpio_pcc4":1}
,"gpio_pcc4":{"vbus_detect":1,"vbus_dtect":1,"hence":1,"customized":1}
,"gpio_pz1":{"pin":1}
,"states":{"vbus_detect":1,"corresponding":1,"following":1,"cable":1,"above":1,"gpio":1,"value":1,"example":1,"j28":1,"gpio_pcc4":1,"thermal":1,"creating":1,"defined":1}
,"internal":{"pull":1}
,"pull":{"high":1}
,"high":{"logical":1,"type":1}
,"logical":{"high":1,"low":1}
,"pulled":{"ground":1}
,"ground":{"logical":1}
,"low":{"type":1,"vbus":1}
,"remains":{"logical":1}
,"operation":{"vbus_detect":1}
,"depends":{"device\u2019s":1}
,"supply":{"cable":1}
,"initially":{"logical":1}
,"matter":{"otg-compatible":1}
,"otg-compatible":{"port":1}
,"0x0":{"excon_none":1,"0x2":1,"0x1":1}
,"0x2":{"extcon_usb_host":1,"0x1":1}
,"0x1":{"extcon_usb":1,"0x2":1,"0x0":1}
,"listed":{"below":1}
,"extcon-gpio":{"name":1,"irq-flags":1,"debounce":1,"wait-for-gpio-scan":1,"out-cable-names":1,"cable-states":1}
,"irq-flags":{"irq":1}
,"flags":{"gpio":1}
,"debounce":{"debounce":1,"time":1}
,"time":{"milliseconds":1,"passed":1,"reduction":1,"tweaking":1,"seconds":1}
,"wait-for-gpio-scan":{"wait":1}
,"wait":{"timeout":1}
,"timeout":{"milliseconds":1}
,"milliseconds":{"scanning":1}
,"scanning":{"gpios":1}
,"detected":{"debounce":1}
,"out-cable-names":{"output":1,"first":1}
,"cable-states":{"gpio":1,"0x3":1,"0x0":1}
,"array":{"byte":1,"contain":1}
,"byte":{"values":1,"gpio":1,"corresponding":1}
,"values":{"even-numbered":1,"pcie":1}
,"even-numbered":{"byte":1}
,"odd-numbered":{"byte":1}
,"cable-connected-on-boot":{"name":1}
,"expressed":{"index":1}
,"index":{"extcon-gpio":1,"specified":1}
,"first":{"element":1}
,"element":{"index":1}
,"specified":{"system":1}
,"assumes":{"cable":1,"gpio_pcc4":1}
,"wakeup-source":{"boolean":1}
,"boolean":{"true":1}
,"true":{"device":1}
,"wake":{"system":1}
,"above":{"table":1}
,"shows":{"node":1}
,"definition":{"assumes":1}
,"vbus_dtect":{"pin":1}
,"vbus_id_extcon":{"usb_otg":1}
,"0x3":{"0x0":1}
,"&gpio":{"tegra_gpio":1}
,"extcon_usb":{"extcon_usb_host":1}
,"extcon_usb_host":{"extcon_none":1}
,"connector\u2019s":{"pin":1}
,"gpio00":{"corresponds":1}
,"corresponds":{"gpio_pcc4":1,"pin":1}
,"hence":{"j28":1}
,"vbus_id_gpio_extcon":{"usb_otg":1}
,"except":{"mode":1,"additional":1}
,"additional":{"extcon":1,"settings":1}
,"extcon-cables":{"otg":1,"&vbus_id_gpio_extcon":1}
,"extcon-cable":{"entry":1}
,"transitions":{"host":1,"device":1}
,"extcon-cells":{"number":1}
,"cells":{"extcon":1}
,"usb2.0":{"micro":1}
,"plus":{"additional":1}
,"detects":{"usb":1}
,"extcon-cable-names":{"vbus":1}
,"charger-detector":{"usb":1}
,"charger":{"detection":1}
,"phandle":{"usb":1}
,"pointers":{"nodes":1}
,"large":{"bulk":1}
,"resolve":{"possible":1}
,"possible":{"uphy":1}
,"suspect":{"uphy":1}
,"issue":{"enter":1}
,"devmem":{"0x7009f028":1}
,"hexadecimal":{"number":1}
,"register":{"address":1}
,"address":{"uphy":1}
,"considered":{"constant":1}
,"lane\u2019s":{"bits":1}
,"bits":{"identify":1}
,"identify":{"function":1}
,"owns":{"lane":1}
,"recognized":{"values":1}
,"owned":{"correct":1}
,"consulting":{"product":1}
,"fan":{"speed":1,"cooling":1,"thermal":1,"mapping":1,"trip":1}
,"speed":{"control":1,"mapping":1,"controlled":1,"defined":1}
,"temperature":{"fan":1,"approximated":1,"degrees":1}
,"fan\u2019s":{"thermal":1}
,"thermal":{"zone":1,"sensor":1,"trips":1,"zone\u2019s":1}
,"zone":{"temperature":1,"trip":1}
,"approximated":{"average":1}
,"average":{"cpu":1}
,"sensor":{"readings":1}
,"readings":{"fan":1}
,"pwm":{"signal":1,"signal\u2019s":1}
,"pulse":{"width":1,"widths":1}
,"width":{"range":1}
,"range":{"0-255":1}
,"0-255":{"units":1}
,"trips":{"fan":1,"refer":1}
,"cooling":{"states":1,"state":1}
,"zone\u2019s":{"temperature":1}
,"degrees":{"celsius":1}
,"celsius":{"fan":1}
,"signal\u2019s":{"corresponding":1}
,"widths":{"define":1}
,"trip":{"temperatures":1,"points":1}
,"temperatures":{"corresponding":1,"defined":1}
,"active_trip_temps":{"property":1,"51000":1}
,"porg":{"kernel-dts":1}
,"kernel-dts":{"porg-platforms":1}
,"porg-platforms":{"tegra210-porg-thermal-fan-est.dtsi":1,"tegra210-porg-pwm-fan.dtsi":1}
,"defines":{"fan":1,"corresponding":1}
,"shared_data":{"&thermal_fan_est_shared_data":1,"&pwm_fan_shared_data":1}
,"51000":{"61000":1}
,"61000":{"71000":1}
,"71000":{"82000":1}
,"140000":{"150000":1}
,"150000":{"160000":1}
,"160000":{"170000":1}
,"170000":{"180000":1}
,"active_hysteresis":{"15000":1}
,"15000":{"9000":1}
,"9000":{"9000":1,"10000":1}
,"active_pwm":{"property":1,"120":1}
,"pwms":{"&tegra_pwm":1}
,"&tegra_pwm":{"45334":1}
,"120":{"160":1}
,"160":{"255":1}
,"255":{"255":1}
,"considerations":{"porting":1,"recommendations":1}
,"discusses":{"considerations":1}
,"recommendations":{"keep":1}
,"keep":{"mind":1}
,"mind":{"porting":1}
,"gnome":{"shell":1}
,"shell":{"default":1,"issues":1}
,"display":{"window":1,"manager":1}
,"window":{"manager":1}
,"ubuntu":{"18.04":1,"release":1}
,"18.04":{"although":1}
,"although":{"brings":1}
,"brings":{"new":1}
,"experience":{"comes":1}
,"comes":{"performance":1}
,"performance":{"memory":1}
,"memory":{"overhead":1}
,"overhead":{"problems":1}
,"problems":{"gdm3":1}
,"gdm3":{"gnome":1,"saves":1}
,"issues":{"known":1}
,"known":{"fixes":1}
,"fixes":{"development":1,"fixes":1,"may":1}
,"considering":{"ubuntu":1}
,"timelines":{"trivial":1}
,"trivial":{"nature":1}
,"nature":{"fixes":1}
,"backported":{"ubuntu":1}
,"suggestions":{"reduce":1}
,"reduce":{"boot":1}
,"tweaking":{"rootfs":1}
,"autologin":{"gdm3":1}
,"saves":{"seconds":1}
,"seconds":{"boot":1,"start":1,"bring":1}
,"maxn":{"saves":1}
,"lightweight":{"display":1,"window":1}
,"lightdm":{"lightdm":1,"service":1,"display":1,"gtk":1,"login":1}
,"service":{"takes":1}
,"takes":{"seconds":1}
,"apt-get":{"update":1,"install":1}
,"dpkg-reconfigure":{"lightdm":1}
,"gtk":{"greeter":1}
,"greeter":{"default":1,"install":1}
,"login":{"greeter":1}
,"lxde":{"lxde":1,"takes":1,"compton":1}
,"bring":{"desktop":1}
,"desktop":{"login":1,"entry":1}
,"compton":{"enter":1,"compositor":1,"--backend":1}
,"xdg":{"autostart":1}
,"autostart":{"lxde-compton.desktop":1}
,"lxde-compton.desktop":{"containing":1}
,"genericname":{"compositor":1}
,"comment":{"compositor":1}
,"tryexec":{"compton":1}
,"exec":{"compton":1}
,"--backend":{"glx":1}
,"onlyshowin":{"lxde":1}
,"pass":{"quiet":1}
,"quiet":{"option":1,"add":1,"parameter":1}
,"option":{"kernel":1}
,"reduces":{"kernel":1}
,"append":{"parameter":1,"cbootargs":1}
,"already":{"defined":1}
,"cbootargs":{"quiet":1}
,"customizing":{"settings":1}
,"device-specific":{"file":1}
,".conf":{"files":1}
,"project\u2019s":{"name":1}
,"specify":{"eeprom":1,"size":1,"emmc":1}
,"don\u2019t":{"want":1}
,"dynamic":{"freq":1}
,"freq":{"voltage":1}
,"voltage":{"scaling":1}
,"scaling":{"feature":1}
,"secondary":{"boot":1}
,"size":{"emmc":1,"p3448-0000.conf.common":1}
}
;Search.control.loadWordPairs(pairs);
