var pairs =
{
"nvidia":{"jetson":1,"plug-ins":1,"ffmpeg":1}
,"jetson":{"linux":1,"platforms":1,"ffmpeg":1}
,"linux":{"driver":1}
,"driver":{"package":1}
,"package":{"l4t":1,"supports":1,"support":1}
,"l4t":{"includes":1,"release":1,"builds":1}
,"includes":{"multimedia":1}
,"multimedia":{"framework":1,"api":1,"playback":1,"local":1,"player":1}
,"framework":{"modules":1,"gstreamer":1,"nvgstplayer":1}
,"modules":{"testing":1}
,"testing":{"purposes":1,"multimedia":1}
,"gstreamer":{"information":1,"developers":1,"open":1,"directly":1,"openmax":1,"framework":1,"consult":1,"directed":1,"api":1,"default":1}
,"information":{"accelerated":1,"nvgstplayer":1,"gstreamer":1,"consult":1,"input":1,"decoded":1}
,"accelerated":{"gstreamer":1,"nvidia":1,"decode":1}
,"api":{"collection":1,"includes":1,"encoding":1,"provides":1,"reference":1,"using":1}
,"collection":{"low-level":1}
,"low-level":{"apis":1}
,"apis":{"support":1,"enable":1}
,"support":{"flexible":1,"nvdec":1,"nvenc":1,"migrated":1,"mpeg4":1}
,"flexible":{"application":1}
,"application":{"development":1,"refer":1,"nvgstcapture":1,"supports":1,"deprecated":1,"accelerated":1}
,"development":{"low-level":1,"path":1,"instead":1}
,"enable":{"flexibility":1}
,"flexibility":{"providing":1}
,"providing":{"better":1}
,"better":{"control":1}
,"control":{"underlying":1}
,"underlying":{"hardware":1}
,"hardware":{"blocks":1}
,"libargus":{"imaging":1}
,"imaging":{"applications":1}
,"v4l2":{"api":1,"video":1,"buffer":1,"device":1}
,"encoding":{"decoding":1}
,"decoding":{"scaling":1,"multiple":1,"process":1}
,"scaling":{"media":1}
,"media":{"functions":1,"file":1}
,"nvosd":{"on-screen":1}
,"on-screen":{"display":1}
,"buffer":{"utility":1,"allocation":1,"plane":1,"information":1}
,"utility":{"buffer":1,"testing":1}
,"allocation":{"management":1}
,"management":{"sharing":1}
,"sharing":{"transform":1}
,"transform":{"composition":1}
,"composition":{"blending":1}
,"example":{"applications":1}
,"applications":{"provided":1,"complete":1}
,"provided":{"demonstrate":1}
,"video":{"decode":1,"encode":1,"convert":1,"streams":1,"processing":1,"record":1,"files":1,"data":1,"decoder":1}
,"decode":{"dual":1,"support":1,"drm":1,"multi-channels":1,"decoding":1,"jpeg":1,"ffmpeg":1,"jetson":1,"read":1,"functional":1,"process":1}
,"dual":{"decode":1,"encode":1}
,"encode":{"dual":1,"support":1}
,"drm":{"based":1}
,"based":{"render":1}
,"multivideo":{"decode":1}
,"multiple":{"video":1}
,"streams":{"parallel":1}
,"jpeg":{"decode":1,"encode":1,"capture":1}
,"image":{"video":1}
,"processing":{"cuda":1}
,"camera":{"jpeg":1,"capture":1,"encapsulate":1}
,"capture":{"video":1,"cuda":1,"composition":1,"application":1,"thread":1,"plane":1}
,"cuda":{"processing":1}
,"multicamera":{"capture":1}
,"object":{"detection":1,"device":1}
,"detection":{"classification":1}
,"classification":{"cudnn":1}
,"tensorrt":{"opencv":1}
,"opencv":{"usage":1}
,"provides":{"application":1}
,"path":{"using":1}
,"using":{"framework":1,"nvgstplayer":1,"camera":1,"nvarguscamerasrc":1}
,"developers":{"leveraging":1}
,"leveraging":{"custom":1}
,"custom":{"frameworks":1}
,"reference":{"available":1,"implementation":1}
,"available":{"download":1}
,"https":{"developer.nvidia.com":1,"repo.download.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"downloads":1}
,"gstreamer-based":{"multimedia":1,"camera":1}
,"open":{"source":1}
,"source":{"multimedia":1,"files":1,"ffmpeg":1}
,"nvgstplayer":{"utility":1,"used":1,"application":1,"multimedia":1,"nvgstcapture":1,"command":1,"supports":1}
,"local":{"playback":1,"file":1}
,"playback":{"http":1,"cases":1,"playback":1,"rstp":1}
,"http":{"rtsp":1,"gstreamer.freedesktop.org":1,"udp":1}
,"rtsp":{"streaming":1}
,"streaming":{"playback":1}
,"cases":{"nvgstplayer":1}
,"used":{"reference":1}
,"refer":{"readme":1}
,"readme":{"file":1}
,"file":{"included":1,"available":1,"player":1,"playback":1}
,"included":{"release":1}
,"installing":{"gstreamer":1}
,"download":{"install":1}
,"install":{"gstreamer":1,"ffmpeg":1}
,"directly":{"target":1}
,"target":{"wrapper":1}
,"wrapper":{"library":1}
,"library":{"gst-openmax":1,"l4t":1}
,"gst-openmax":{"interface":1}
,"interface":{"gstreamer":1}
,"openmax":{"enables":1}
,"enables":{"accelerated":1}
,"plug-ins":{"gstreamer":1}
,"player":{"test":1,"plays":1}
,"test":{"application":1}
,"running":{"nvgstplayer":1}
,"nvgstcapture":{"applications":1,"command":1,"captures":1,"application":1}
,"complete":{"prerequisite":1}
,"prerequisite":{"steps":1}
,"steps":{"install":1}
,"directed":{"readme":1}
,"nv_tegra":{"nv_sample_apps":1,"\u200Cnv_sample_apps":1}
,"nv_sample_apps":{"nvgstcapture_readme.txt":1}
,"gst-omx":{"plugin":1}
,"plugin":{"deprecated":1,"development":1}
,"deprecated":{"l4t":1}
,"release":{"32.1":1}
,"32.1":{"gst-v4l2":1}
,"gst-v4l2":{"plugin":1}
,"command":{"line":1}
,"line":{"media":1,"camera":1}
,"plays":{"audio":1}
,"audio":{"video":1}
,"files":{"encapsulated":1,"following":1,"ffmpeg":1}
,"supports":{"local":1,"argus":1,"hardware-accelerated":1}
,"rstp":{"http":1}
,"consult":{"readme":1}
,"\u200Cnv_sample_apps":{"nvgstplayer-1.0_readme.txt":1,"nvgstcapture-1.0_readme.txt":1}
,"default":{"support":1}
,"migrated":{"version":1}
,"version":{"1.14.0":1}
,"1.14.0":{"ubuntu":1}
,"ubuntu":{"18.04":1}
,"captures":{"video":1}
,"data":{"using":1,"container":1,"pass":1}
,"encapsulate":{"encoded":1}
,"encoded":{"video":1}
,"container":{"file":1,"formats":1,"files":1}
,"argus":{"api":1}
,"nvarguscamerasrc":{"plugin":1}
,"usage":{"legacy":1}
,"legacy":{"nvcamerasrc":1}
,"nvcamerasrc":{"nvgstcapture":1}
,"ffmpeg":{"package":1,"binary":1,"library":1,"main":1,"decoding":1,"start":1,"dumping":1}
,"hardware-accelerated":{"decode":1,"decoded":1}
,"read":{"video":1,"buffers":1}
,"following":{"elementary":1,"lines":1}
,"elementary":{"container":1}
,"formats":{"dump":1}
,"dump":{"yuv":1}
,"yuv":{"420":1}
,"420":{"format":1}
,"mpeg4":{"container":1}
,"binary":{"package":1}
,"enter":{"commands":1,"command":1}
,"sudo":{"apt":1,"tee":1}
,"apt":{"install":1,"source":1,"sources.list":1,"update":1}
,"include":{"ffmpeg":1}
,"add":{"following":1}
,"lines":{"apt":1}
,"echo":{"deb":1,"deb-src":1}
,"deb":{"https":1}
,"repo.download.nvidia.com":{"jetson":1}
,"main":{"main":1,"sudo":1}
,"tee":{"apt":1}
,"deb-src":{"https":1}
,"functional":{"flow":1}
,"section":{"describes":1}
,"describes":{"function":1,"key":1}
,"function":{"flow":1}
,"flow":{"ffmpeg":1}
,"call":{"nvv4l2dec_init_decoder":1,"subscribe_event":1,"set_output_plane_format":1,"capture_thread":1,"set_capture_plane_format":1,"nvv4l2dec_decode":1,"nvv4l2dec_decoder_get_frame":1,"nvv4l2dec_decoder_close":1}
,"nvv4l2dec_init_decoder":{"create":1}
,"create":{"new":1}
,"new":{"v4l2":1}
,"decoder":{"object":1,"context":1}
,"device":{"node":1}
,"node":{"dev":1}
,"dev":{"nvhost-nvdec":1}
,"subscribe_event":{"subscribe":1}
,"subscribe":{"resolution":1}
,"resolution":{"change":1}
,"change":{"events":1}
,"set_output_plane_format":{"format":1}
,"format":{"output":1,"capture":1}
,"output":{"plane":1}
,"capture_thread":{"start":1}
,"start":{"capture":1,"decode":1}
,"set_capture_plane_format":{"format":1}
,"nvv4l2dec_decode":{"read":1}
,"buffers":{"ffmpeg":1,"close":1,"output":1,"capture":1}
,"nvv4l2dec_decoder_get_frame":{"hardware-accelerated":1}
,"decoded":{"data":1,"frames":1}
,"pass":{"ffmpeg":1}
,"nvv4l2dec_decoder_close":{"destroy":1}
,"destroy":{"buffers":1}
,"close":{"device":1}
,"table":{"describes":1}
,"key":{"structure":1,"function":1}
,"contains":{"information":1}
,"input":{"packets":1,"bitstream":1}
,"specifies":{"different":1}
,"different":{"codec":1}
,"codec":{"type":1}
,"holds":{"buffer":1}
,"plane":{"parameters":1,"filled":1,"format":1}
,"defines":{"decoder":1}
,"creates":{"new":1}
,"subscribes":{"resolution":1}
,"sets":{"format":1,"capture":1}
,"requests":{"buffers":1}
,"filled":{"input":1}
,"dequeues":{"v4l2":1,"event":1}
,"queues":{"v4l2":1}
,"starts":{"capture":1}
,"event":{"reported":1}
,"reported":{"v4l2":1}
}
;Search.control.loadWordPairs(pairs);
