var pairs =
{
"hardware":{"setup":1,"directly":1,"support":1,"production":1,"reduces":1,"throttling":1,"nvidia":1,"reacts":1}
,"developing":{"systems":1,"application":1}
,"systems":{"application":1}
,"application":{"software":1,"board":1}
,"software":{"nvidia":1,"simulator":1,"computer":1,"shutdown":1,"stack":1}
,"nvidia":{"jetson":1,"platform":1}
,"jetson":{"device":1,"nano":1,"developer":1,"modules":1,"xavier":1,"agx":1,"reference":1,"tx2":1,"tx2i":1,"tx1":1,"module":1,"linux":1,"socthem_oc":1,"kernel-dts":1}
,"device":{"linux":1,"boot":1,"tree":1}
,"linux":{"run":1,"host":1,"shutdown":1,"driver":1}
,"run":{"test":1}
,"test":{"code":1}
,"code":{"actual":1,"targets":1,"ecc":1,"snippet":1}
,"actual":{"reference":1,"available":1}
,"reference":{"platform":1,"carrier":1,"manual":1}
,"platform":{"nvidia":1,"following":1,"location":1,"t19x":1,"t210":1,"t18x":1}
,"nano":{"developer":1,"devices":1,"modules":1,"development":1,"production":1,"2gb":1,"p3448-003":1,"module":1,"carrier":1,"reference":1}
,"developer":{"kit":1,"kits":1,"kit\u2019s":1}
,"kit":{"code":1,"setup":1,"specific":1,"on-module":1,"on-board":1,"user":1,"revision":1,"jetson":1,"collectively":1,"available":1,"sold":1,"p2771":1,"carrier":1}
,"targets":{"hardware":1}
,"directly":{"rather":1}
,"rather":{"software":1}
,"simulator":{"emulator":1}
,"accordingly":{"acquire":1}
,"acquire":{"carrier":1}
,"carrier":{"board":1,"boards":1}
,"board":{"using":1,"documentation":1,"sections":1,"preparation":1,"supports":1,"following":1,"layout":1,"top":1,"bottom":1,"jetson":1,"recovery":1,"revisions":1,"revision":1,"compatible":1,"two":1,"compatibility":1,"p2822":1,"specification":1}
,"using":{"l4t":1,"jetson":1}
,"l4t":{"consult":1,"uses":1}
,"consult":{"board":1,"jetson":1}
,"documentation":{"guidance":1}
,"guidance":{"setting":1}
,"setting":{"configuring":1,"determines":1}
,"configuring":{"board":1,"voltage":1}
,"sections":{"below":1,"describe":1}
,"below":{"additional":1,"third":1}
,"additional":{"notes":1,"information":1,"bluetooth":1}
,"section":{"provides":1,"bsp":1,"contains":1,"disable":1,"describes":1}
,"provides":{"additional":1}
,"notes":{"apply":1,"using":1}
,"apply":{"jetson":1}
,"specific":{"jetson":1,"input":1}
,"xavier":{"small":1,"series":1,"modules":1,"developer":1,"module":1,"board":1,"carrier":1,"industrial":1}
,"small":{"economical":1}
,"economical":{"module":1}
,"module":{"memory":1,"data":1,"reduced":1,"differs":1,"include":1,"uses":1,"feeds":1,"power":1,"input":1,"located":1,"alert":1}
,"memory":{"uses":1,"lacks":1,"used":1,"parity":1,"bandwidth":1,"storage":1,"available":1}
,"uses":{"processor":1,"may":1,"included":1,"error":1,"reference":1,"power":1}
,"processor":{"powerful":1,"carrier":1}
,"powerful":{"nvidia":1}
,"agx":{"xavier":1,"developer":1,"industrial":1}
,"two":{"types":1,"three":1,"power":1,"regions":1}
,"types":{"jetson":1,"nvidia":1}
,"modules":{"available":1,"jetson":1,"collectively":1,"distinguished":1,"functionally":1,"include":1,"located":1}
,"part":{"number":1}
,"number":{"p3668-0000":1,"p3668-0001":1,"samples":1}
,"p3668-0000":{"distributed":1}
,"distributed":{"jetson":1}
,"on-module":{"card":1}
,"card":{"socket":1,"flashed":1,"flashing":1}
,"socket":{"programming":1}
,"programming":{"inserting":1}
,"inserting":{"card":1}
,"flashed":{"operating":1}
,"operating":{"software":1,"system":1,"life":1,"conditions":1,"lifetime":1,"temperature":1,"profiles":1}
,"p3668-0001":{"sold":1}
,"sold":{"production":1,"original":1}
,"production":{"compatible":1,"uses":1,"module":1,"systems":1}
,"compatible":{"jetson":1,"p2597":1,"ina3221x":1}
,"on-board":{"emmc":1,"power":1}
,"emmc":{"memory":1}
,"lacks":{"card":1}
,"information":{"jetson":1,"modules":1,"several":1,"sce":1}
,"data":{"sheet":1,"powermon.dtsi":1}
,"although":{"carrier":1}
,"supports":{"variety":1,"features":1,"dram":1}
,"variety":{"peripheral":1}
,"peripheral":{"devices":1}
,"devices":{"start":1,"modules":1,"specified":1,"nvidia":1,"carrier":1}
,"start":{"developing":1}
,"larger":{"uhs-1":1}
,"uhs-1":{"microsd":1}
,"microsd":{"card":1}
,"flashing":{"operating":1,"instructions":1,"support":1}
,"system":{"software":1,"operational":1,"operate":1,"cannot":1,"bluetooth.service.d":1,"electrical":1,"edp":1}
,"usb":{"cable":1,"micro\u2011b":1}
,"cable":{"plug":1}
,"plug":{"usb":1,"board":1,"board\u2019s":1}
,"micro\u2011b":{"connector":1}
,"instructions":{"developer":1}
,"setup":{"jetson":1,"nvidia":1}
,"user":{"guide":1}
,"layout":{"connections":1}
,"connections":{"shown":1,"board":1}
,"shown":{"following":1,"below":1,"jetson":1}
,"following":{"diagrams":1,"diagram":1,"procedure":1,"lines":1,"table":1,"sections":1,"power":1,"code":1}
,"top":{"view":1,"linux_for_tegra":1,"directory":1}
,"bottom":{"view":1}
,"three":{"types":1,"modules":1,"common":1}
,"p3448-0000":{"version":1,"p3448-0002":1}
,"version":{"original":1}
,"original":{"jetson":1,"8gb":1}
,"development":{"work":1,"educational":1}
,"work":{"included":1,"correctly":1}
,"included":{"jetson":1}
,"p3448-0002":{"version":1,"p3448":1}
,"may":{"used":1,"impacted":1,"need":1}
,"used":{"carrier":1,"original":1,"revised":1,"profiles":1}
,"revision":{"b01":1,"a02":1,"b04":1,"c02":1}
,"b01":{"newer":1,"top":1}
,"p3448-0003":{"jetson":1}
,"2gb":{"development":1,"developer":1,"jetson":1,"reference":1}
,"educational":{"uses":1}
,"collectively":{"described":1}
,"described":{"jetson":1}
,"distinguished":{"p3448-0000":1}
,"p3448":{"sku":1}
,"sku":{"0000":1,"0002":1,"0003":1}
,"0000":{"sku":1}
,"0002":{"called":1}
,"called":{"jetson":1}
,"p3448-003":{"sku":1}
,"0003":{"called":1}
,"functionally":{"identical":1}
,"identical":{"information":1}
,"storage":{"devices":1}
,"specified":{"boot":1,"system":1,"system\u2019s":1}
,"boot":{"options":1,"time":1,"ecc":1}
,"options":{"section":1,"topic":1}
,"bsp":{"customization":1}
,"customization":{"topic":1}
,"recovery":{"port":1}
,"diagrams":{"show":1,"apply":1}
,"show":{"jetson":1}
,"revisions":{"a02":1,"jetson":1,"p2597":1}
,"a02":{"b01":1,"top":1}
,"series":{"devices":1,"modules":1,"module":1,"carrier":1,"soc":1,"except":1}
,"available":{"production":1,"kernel":1,"regions":1}
,"revised":{"jetson":1}
,"usb\u2011c":{"cable":1,"flash":1}
,"board\u2019s":{"usb\u2011c":1}
,"flash":{"port":1,"module":1}
,"industrial":{"information":1,"uses":1,"ecc":1,"version":1}
,"contains":{"additional":1,"settings":1}
,"several":{"aspects":1,"revisions":1}
,"aspects":{"jetson":1}
,"error":{"correcting":1,"correction":1,"detection":1}
,"correcting":{"code":1}
,"ecc":{"dram":1,"reserves":1,"enabled":1,"disabled":1,"explains":1,"function":1,"features":1}
,"correction":{"code":1,"safety":1,"enabled":1,"sce":1}
,"dram":{"supports":1,"scrubbing":1,"ecc":1}
,"staged":{"dram":1}
,"scrubbing":{"mb1":1}
,"mb1":{"mb2":1,"generate":1}
,"mb2":{"cboot":1}
,"cboot":{"reduces":1}
,"reduces":{"boot":1,"module":1}
,"time":{"compared":1,"absolute":1,"number":1}
,"compared":{"full":1}
,"full":{"dram":1}
,"single-bit":{"error":1}
,"safety":{"cluster":1}
,"cluster":{"engine":1}
,"engine":{"sce":1}
,"sce":{"firmware":1,"xavier":1}
,"double-bit":{"error":1}
,"detection":{"reboot":1}
,"reboot":{"sce":1,"jetson":1,"complete":1}
,"soc":{"technical":1,"input":1}
,"technical":{"reference":1}
,"reserves":{"12.5":1}
,"12.5":{"memory":1,"ecc":1,"reduction":1}
,"parity":{"bits":1}
,"bits":{"reducing":1,"required":1,"causing":1}
,"reducing":{"memory":1}
,"bandwidth":{"12.5":1,"reduced":1}
,"enabled":{"default":1,"ecc":1,"product":1,"bus":1}
,"default":{"following":1,"section":1,"additional":1,"jetson":1}
,"procedure":{"disable":1}
,"disable":{"jetson":1,"feature":1}
,"open":{"configuration":1}
,"configuration":{"file":1,"bluetooth":1,"data":1,"register":1}
,"file":{"top":1,"jetson-tx2i.conf":1,"soft":1,"located":1,"following":1,"code":1,"jetson":1,"contains":1}
,"linux_for_tegra":{"jetson-agxi.conf":1,"jetson-tx2i.conf":1}
,"comment":{"following":1}
,"lines":{"prefix":1}
,"prefix":{"semicolon":1}
,"emmc_bct":{"tegra194-mb1-bct-memcfg-4x-derated-ecc-p2888.cfg":1,"specification":1,"p3489_a00_8gb_samsung_8gb_lpddr4_204mhz_p134_a02_l4t.cfg":1}
,"misc_config":{"tegra194-mb1-bct-misc-flash-jaxi.cfg":1}
,"misc_cold_boot_config":{"tegra194-mb1-bct-misc-l4t-jaxi.cfg":1}
,"save":{"configuration":1}
,"tx2":{"series":1,"module":1,"designed":1,"4gb":1,"modules":1,"developer":1,"processor":1,"reference":1,"jetson":1,"tx1":1,"carrier":1,"shown":1,"sectionplatform":1,"original":1}
,"tx2i":{"industrial":1,"information":1,"works":1,"system":1,"configuration":1,"module":1,"compatible":1,"dedicated":1,"various":1,"may":1,"supports":1,"ecc":1}
,"designed":{"operation":1}
,"operation":{"longer":1}
,"longer":{"operating":1}
,"life":{"broader":1,"maximum":1,"years":1,"4.4":1}
,"broader":{"range":1}
,"range":{"operating":1}
,"4gb":{"low-priced":1}
,"low-priced":{"module":1}
,"reduced":{"memory":1,"ecc":1}
,"jetxon":{"tx2":1}
,"common":{"ones":1,"tegra194-powermon-p3668.dtsi":1,"tegra194-powermon-p2888.dtsi":1,"kernel-dts":1,"tegra186-p3636-0001-a00-powermon.dts":1}
,"ones":{"b04":1}
,"b04":{"c02":1,"top":1,"newer":1,"works":1}
,"c02":{"shown":1,"top":1}
,"third":{"b02":1}
,"b02":{"similar":1}
,"similar":{"b04":1}
,"tx1":{"devices":1,"reference":1,"modules":1,"series":1,"module":1}
,"differs":{"thus":1}
,"thus":{"diagrams":1}
,"power":{"profiles":1,"profile":1,"button":1,"monitor":1,"consumption":1,"rail":1,"rails":1}
,"works":{"two":1,"correctly":1}
,"profiles":{"ucm1":1,"enabled":1}
,"ucm1":{"ucm2":1,"profile":1}
,"ucm2":{"ucm1":1,"power":1}
,"profile":{"default":1,"operating":1}
,"table":{"describes":1,"summarizes":1}
,"describes":{"power":1,"hardware":1}
,"mission":{"profile":1}
,"vmax":{"volts":1}
,"fmax":{"mhz":1}
,"cpu":{"d15":1,"gpu":1}
,"d15":{"a57":1}
,"1958":{"1920":1}
,"emc":{"soc":1}
,"voltage":{"frequency":1,"current":1,"conversion":1,"unless":1}
,"frequency":{"settings":1}
,"settings":{"specified":1,"ina":1}
,"operational":{"life":1}
,"maximum":{"temperature":1,"operating":1,"possible":1}
,"temperature":{"years":1,"105":1}
,"hours":{"day":1}
,"ensure":{"operational":1,"bluetooth":1}
,"years":{"jetson":1}
,"operate":{"above":1}
,"above":{"100":1,"3000":1,"3600":1}
,"100":{"hours":1}
,"day":{"less":1,"105":1}
,"less":{"remaining":1}
,"remaining":{"time":1}
,"absolute":{"maximum":1}
,"4.4":{"years":1}
,"1497":{"1420":1}
,"system\u2019s":{"operational":1}
,"host":{"computer":1}
,"computer":{"navigate":1}
,"navigate":{"jetson":1,"file":1}
,"jetson-tx2i.conf":{"file":1}
,"soft":{"link":1}
,"link":{"p2771-3489-ucm1.conf":1,"p2771-3489-ucm2.conf":1}
,"change":{"soft":1,"setting":1,"line":1,"configure":1}
,"compatibility":{"issues":1}
,"issues":{"noted":1}
,"noted":{"jetson":1}
,"p2597":{"carrier":1}
,"cannot":{"shut":1}
,"shut":{"down":1}
,"down":{"software":1}
,"shutdown":{"attempt":1,"command":1}
,"attempt":{"reboots":1}
,"reboots":{"device":1}
,"command":{"reboots":1,"reboot":1}
,"button":{"work":1}
,"correctly":{"reference":1,"revision":1}
,"dedicated":{"reference":1}
,"p2822":{"included":1}
,"p2771":{"consult":1}
,"specification":{"notes":1}
,"various":{"revisions":1}
,"105":{"hours":1}
,"feature":{"support":1}
,"support":{"error":1,"bluetooth":1,"provided":1,"development":1}
,"explains":{"disable":1}
,"function":{"original":1}
,"features":{"include":1}
,"generate":{"parity":1}
,"required":{"ecc":1}
,"sbe":{"correction":1}
,"dbe":{"detection":1}
,"kernel":{"extended":1}
,"extended":{"two":1}
,"regions":{"actual":1}
,"position":{"independent":1}
,"independent":{"u\u2011boot":1}
,"u\u2011boot":{"support":1}
,"causing":{"12.5":1}
,"reduction":{"memory":1}
,"edit":{"jetson":1}
,"directory":{"downloaded":1}
,"downloaded":{"installed":1}
,"installed":{"nvidia":1}
,"driver":{"package":1}
,"package":{"l4t":1,"list":1}
,"modify":{"dtb":1,"critical":1}
,"bpfdtb_file":{"tegra186-a02-bpmp-storm-p3489-a00-00-ta795sa-ucm1.dtb":1,"tegra186-a02-bpmp-storm-p3489-a00-00-ta795sa-ecc-disabled-ucm1.dtb":1}
,"topic":{"bsp":1}
,"boards":{"jetson":1,"built-in":1}
,"sectionplatform":{"carrier":1}
,"enabling":{"bluetooth":1}
,"bluetooth":{"audio":1,"support":1,"hardware":1,"software":1,"bluetoothd":1,"headset":1}
,"audio":{"varies":1,"disabled":1,"profiles":1,"a2dp":1,"package":1}
,"varies":{"platform":1}
,"summarizes":{"support":1}
,"provided":{"case":1}
,"m.2":{"key":1}
,"key":{"connector":1}
,"connector":{"customer":1}
,"customer":{"add":1,"supply":1}
,"add":{"bluetooth":1}
,"supply":{"bluetooth":1}
,"built-in":{"bluetooth":1}
,"stack":{"conformant":1}
,"conformant":{"configuration":1}
,"disabled":{"default":1}
,"product":{"conformance":1}
,"conformance":{"may":1}
,"enable":{"bluetooth":1}
,"lib":{"systemd":1,"bluetooth":1}
,"systemd":{"system":1}
,"bluetooth.service.d":{"nv-bluetooth-service.conf":1}
,"text":{"editor":1}
,"editor":{"change":1}
,"execstart":{"usr":1}
,"usr":{"lib":1}
,"bluetoothd":{"--noplugin":1}
,"--noplugin":{"audio":1}
,"a2dp":{"avrcp":1}
,"delete":{"\u2011\u2011noplugin":1}
,"\u2011\u2011noplugin":{"option":1}
,"option":{"values":1}
,"enter":{"commands":1,"command":1}
,"commands":{"update":1}
,"update":{"apt-get":1}
,"apt-get":{"package":1,"update":1,"install":1}
,"list":{"install":1}
,"install":{"pulse":1,"pulseaudio-module-bluetooth":1}
,"pulse":{"audio":1}
,"sudo":{"apt-get":1,"reboot":1}
,"complete":{"pair":1}
,"pair":{"connect":1}
,"connect":{"bluetooth":1}
,"current":{"monitor":1,"certain":1,"limits":1,"limit":1,"exceeds":1,"following":1,"above":1,"lower":1}
,"include":{"on-board":1}
,"monitor":{"ina3221":1,"voltage":1,"implement":1,"accepts":1,"supported":1,"device":1}
,"ina3221":{"monitor":1,"outputs":1,"continues":1,"single":1,"input":1,"warning":1,"critical":1,"monitors":1,"include":1}
,"certain":{"rails":1}
,"rails":{"l4t":1}
,"implement":{"system":1}
,"electrical":{"design":1}
,"design":{"point":1}
,"point":{"edp":1}
,"edp":{"management":1,"constraints":1}
,"management":{"strategy":1}
,"strategy":{"maximizes":1}
,"maximizes":{"cpu":1}
,"gpu":{"performance":1,"hardware":1}
,"performance":{"within":1}
,"within":{"system":1}
,"constraints":{"platform":1}
,"feeds":{"ina3221":1}
,"outputs":{"soc_therm":1,"asserted":1,"ina3221":1,"fed":1}
,"soc_therm":{"input":1,"hardware":1}
,"input":{"alert":1,"channel":1,"power":1,"soc_therm":1,"jetson":1,"voltage":1}
,"alert":{"outputs":1}
,"asserted":{"soc_therm":1,"channel\u2019s":1}
,"consumption":{"avoid":1}
,"avoid":{"violating":1}
,"violating":{"current":1}
,"accepts":{"configuration":1}
,"powermon.dtsi":{"source":1,"file":1}
,"source":{"file":1}
,"describe":{"device":1}
,"tree":{"properties":1,"source":1}
,"properties":{"may":1,"used":1}
,"need":{"change":1}
,"configure":{"power":1,"critical":1}
,"supported":{"platform":1}
,"location":{"file":1}
,"snippet":{"showing":1,"file":1}
,"showing":{"properties":1}
,"continuous-config":{"ina3221":1,"0x7c07":1,"0x7607":1}
,"continues":{"conversion":1}
,"conversion":{"mode":1,"time":1}
,"mode":{"configuration":1}
,"register":{"setting":1,"setting.determines":1}
,"determines":{"channels":1}
,"channels":{"enabled":1}
,"bus":{"voltage":1}
,"samples":{"collected":1}
,"collected":{"averaged":1}
,"averaged":{"together":1}
,"trigger-config":{"ina3221":1,"0x7003":1}
,"single":{"shot":1}
,"shot":{"conversion":1}
,"setting.determines":{"channels":1}
,"rail-name":{"name":1,"vdd_in":1,"vdd_cpu_gpu_cv":1,"vdd_soc":1,"pom_5v_gpu":1,"pom_5v_in":1,"pom_5v_cpu":1,"gpu":1,"cpu":1,"soc":1,"vddrq":1,"sys5v":1,"vdd_sys_gpu":1,"vdd_sys_soc":1,"vdd_4v0_wifi":1,"vdd_sys_cpu":1,"vdd_sys_sram":1,"vdd_cpu_gpu":1,"vdd_mux":1,"vdd_5v_io_sys":1,"vdd_3v3_sys":1,"vdd_3v3_io":1,"vdd_1v8_io":1,"vdd_m2_in":1,"vdd_gpu":1,"vdd_cpu":1}
,"name":{"power":1}
,"rail":{"connected":1,"sense":1,"vdd_in":1}
,"connected":{"ina3221":1,"channel":1}
,"shunt-resistor-mohm":{"power":1}
,"sense":{"resistor":1}
,"resistor":{"value":1}
,"value":{"milliohms":1,"8190":1}
,"current-warning-limit-ma":{"channel":1,"3000":1}
,"channel":{"average":1,"instantaneous":1,"configured":1}
,"average":{"current":1}
,"limit":{"milliamperes":1,"triggering":1,"vdd_in":1,"specific":1}
,"milliamperes":{"ina3221":1}
,"warning":{"signal":1}
,"signal":{"asserted":1}
,"channel\u2019s":{"average":1,"instantaneous":1}
,"exceeds":{"limit":1}
,"triggering":{"cpu":1}
,"throttling":{"via":1,"average":1}
,"via":{"jetson":1}
,"current-critical-limit-ma":{"channel":1,"3600":1}
,"instantaneous":{"current":1}
,"critical":{"signal":1,"current":1}
,"monitors":{"voltage":1}
,"vdd_in":{"connected":1,"maximum":1}
,"configured":{"trigger":1}
,"trigger":{"cpu":1}
,"3000":{"instantaneous":1}
,"t19x":{"jakku":1,"galen":1}
,"jakku":{"kernel-dts":1}
,"kernel-dts":{"common":1,"porg-platforms":1,"t18x-common-platforms":1,"jetson-platforms":1}
,"ina3221x_40":{"ina3221x@40":1}
,"reg":{"0x40":1,"0x0":1,"0x1":1,"0x2":1,"0x41":1,"0x42":1,"0x43":1}
,"t210":{"porg":1,"jetson":1}
,"porg":{"kernel-dts":1}
,"porg-platforms":{"tegra210-porg-powermon-p3448-0000-a00.dtsi":1}
,"ina3221x":{"ina3221x@40":1}
,"status":{"okay":1,"disabled":1}
,"crit":{"warn":1}
,"warn":{"tied":1}
,"tied":{"together":1}
,"together":{"routed":1}
,"routed":{"vmon":1,"soc":1}
,"vmon":{"soc_gpio07":1}
,"soc_gpio07":{"pin":1}
,"galen":{"kernel-dts":1}
,"shunt-volt-offset-uv":{"&p2888_shuntv_offset":1,"&p2180_shuntv_offset":1}
,"ina3221x_41":{"ina3221x@41":1}
,"except":{"jetson":1}
,"vdd_wifi":{"original":1}
,"fed":{"soc_therm":1}
,"reacts":{"reduce":1}
,"reduce":{"module":1}
,"kit\u2019s":{"critical":1}
,"possible":{"value":1}
,"8190":{"therefore":1}
,"therefore":{"necessary":1}
,"necessary":{"modify":1}
,"lower":{"input":1}
,"unless":{"want":1}
,"want":{"configure":1}
,"t18x":{"common":1,"lanai":1}
,"t18x-common-platforms":{"tegra186-quill-p3310-1000-a00-powermon.dtsi":1,"tegra186-quill-p3489-1000-a00-powermon.dtsi":1}
,"lanai":{"kernel-dts":1}
,"base":{"powermon.dtsi":1}
,"jetson-platforms":{"tegra210-jetson-cv-powermon-p2597.dtsi":1,"tegra210-jetson-cv-powermon-p2180-1000-a00.dtsi":1}
,"ina":{"channels":1,"channel":1}
,"plugin":{"manager\u2019s":1}
,"manager\u2019s":{"powermon.dtsi":1}
,"power-critical-limit-mw":{"40000":1}
}
;Search.control.loadWordPairs(pairs);
