var pairs =
{
"using":{"jetson-io":1,"jetson\u2011io":1,"main":1}
,"jetson-io":{"tool":1,"topic":1}
,"camera":{"module":1,"attach":1,"test":1,"i.e":1,"want":1,"applications":1,"device":1,"sensor":1}
,"module":{"on-board":1,"apply":1,"dtb":1,"works":1,"lkm":1,"speed":1}
,"on-board":{"eeprom":1}
,"eeprom":{"create":1}
,"create":{"dtb":1,"apply":1,"new":1,"tegracam_ctrl_ops":1,"dummy":1}
,"dtb":{"overlay":1}
,"overlay":{"file":1,"using":1,"files":1}
,"file":{"statically":1,"jetson":1,"example":1,"proper":1,"generate":1,"move":1,"boot":1,"include":1,"new":1,"change":1,"back":1,"named":1,"enumeration":1,"extend":1,"release":1,"gain":1}
,"statically":{"configure":1}
,"configure":{"board":1,"dtb":1}
,"board":{"attached":1,".dts":1}
,"attached":{"camera":1}
,"attach":{"camera":1}
,"apply":{"camera":1,"dtb":1}
,"jetson\u2011io":{"tool":1,"section":1}
,"tool":{"reboot":1,"recognize":1,"configure":1}
,"reboot":{"new":1}
,"new":{"module":1,".dts":1,"device":1,"controls":1,"element":1,"mode":1,"wrapper":1,"phy_mode":1,"struct":1,"tegracam_device_register":1,"board_setup":1,"ctrl_id_list":1}
,"works":{"soon":1}
,"soon":{"jetson":1}
,"jetson":{"linux":1,"board":1,"devices":1,"nano":1,"tx1":1,"tx2":1,"agx":1,"device":1}
,"linux":{"starts":1,"driver":1,"kernel":1}
,"add":{".dtsi":1,"override":1,"device":1,"register":1,"array":1,"new":1,"factor":1}
,".dtsi":{"file":1,"format":1}
,".dts":{"file":1}
,"status":{"device":1,"disabled":1,"okay":1,"disable":1,"field":1}
,"device":{"tree":1,"updating":1,".dtsi":1,"information":1,"using":1,"path":1,"name":1,"names":1,"v4l2":1}
,"tree":{"nodes":1,"file":1,".dtsi":1,"node":1,"driver":1,"values":1,"fields":1,"probing":1,"compiler":1,"node\u2019s":1,"update":1,"property":1,"properties":1,"files":1}
,"nodes":{"disabled":1}
,"imx185_cam0":{"imx185_a@1a":1}
,"override":{"information":1}
,"information":{"new":1,"compatible":1,"writing":1,"main":1,"sensor-private":1,"setting":1,"loadable":1}
,"top":{"hardware":1}
,"hardware":{"nvidia":1,"setup":1,"describe":1,"support":1}
,"nvidia":{"platform":1,"p3449-0000":1,"p3509-0000":1,"imx185":1,"kernel":1,"drivers":1,"provides":1,"recommends":1}
,"platform":{"t19x":1,"device":1,".dtsi":1}
,"t19x":{"common":1,"galen":1}
,"common":{"kernel-dts":1,"tegra194-p2822-camera-modules.dtsi":1,"problem":1,"issues":1}
,"kernel-dts":{"t19x-common-modules":1,"tegra194-p2888-0001-p2822-0000.dtsi":1}
,"t19x-common-modules":{"tegra194-camera-overlay-file.dts":1}
,"update":{".dtbo":1,"necessary":1}
,".dtbo":{"file":1}
,"proper":{"override":1,"state":1}
,"compatible":{"string":1,"nvidia":1,"kernel":1}
,"p3449-0000":{"p3668-0000":1,"p3668-0001":1}
,"p3668-0000":{"nvidia":1}
,"p3668-0001":{"nvidia":1}
,"p3509-0000":{"p3668-0000":1,"p3668-0001":1}
,"target":{"&imx185_cam0":1}
,"detailed":{"information":1}
,"writing":{"dtb":1}
,"files":{"jetson\u2011io":1}
,"section":{"running":1,"describes":1}
,"running":{"jetson-io":1,"camera":1,"continuous":1,"discontinuous":1}
,"topic":{"hardware":1}
,"compile":{".dts":1}
,"generate":{".dtbo":1}
,"move":{".dtbo":1}
,"boot":{"jetson\u2011io":1}
,"recognize":{"launch":1}
,"launch":{"jetson\u2011io":1}
,"main":{"platform":1,"device":1,"driver":1}
,"register":{"new":1,"device":1,"writes":1,"values":1,"setup":1,"address":1,"mode":1,"structure":1,"addresses":1}
,"updating":{"main":1}
,"include":{"new":1,"tegra194-camera-plugin-manager.dtsi":1,"common":1,"statement":1,"group":1}
,"devices":{"plugin":1}
,"plugin":{"manager":1}
,"manager":{"default":1,"support":1}
,"default":{"first":1,"values":1,"macros":1,"value":1}
,"first":{"unregister":1,"value":1,"frame":1}
,"unregister":{"plugin":1}
,"support":{"add":1,"i2c":1,"group":1}
,"locate":{"edit":1}
,"edit":{".dtsi":1}
,"galen":{"kernel-dts":1}
,"remove":{"following":1,"hard":1}
,"following":{"line":1,"code":1,"changes":1}
,"line":{"file":1}
,"replace":{"following":1}
,"statement":{"specifying":1}
,"specifying":{"dtsi":1,"\u2011\u2011stream-count":1}
,"dtsi":{"file":1}
,"save":{"close":1}
,"close":{"file":1}
,"tegra194-p2822-camera-modules.dtsi":{"model":1}
,"model":{"generating":1}
,"generating":{"dtsi":1}
,"change":{"status":1,"scaling":1}
,"disable":{"status":1}
,"verifying":{"v4l2":1}
,"v4l2":{"sensor":1,"interface":1,"framework":1,"api":1,"subdevice":1}
,"sensor":{"driver":1,"timeout":1,"configuration":1,"connected":1,"running":1,"i2c":1,"power-on":1,"specifications":1,"table":1,"supports":1,"device":1,"starts":1,"outputs":1,"vendor":1,"operations":1,"drivers":1,"mode":1,"type":1,"dtsi":1,"started":1,"settings":1,"context":1,"probing":1}
,"driver":{"complete":1,"ready":1,"populated":1,"name":1,"kernel":1,"device":1,"loadable":1,"tables":1,"supports":1,"package":1,"modify":1,"interface":1,"source":1,"compatible":1,"version":1,"code":1,"driver":1,".dtsi":1,"fulfill":1,"mandatory":1}
,"complete":{"run":1}
,"run":{"v4l2-compliance":1,"v4l2-ctl":1,"completion":1}
,"v4l2-compliance":{"v4l2-ctl":1,"test":1,"dev":1,"above":1}
,"v4l2-ctl":{"ensure":1,"test":1,"--set-fmt-video":1,"capture":1,"available":1}
,"ensure":{"capture":1,"values":1,"device":1,"isp":1}
,"capture":{"raw":1,"\u2011\u2011stream-to":1,"engine":1}
,"raw":{"data":1,"memory":1}
,"data":{"v4l2":1,"specifying":1,"macro":1,"sheets":1,"sensor":1}
,"details":{"raw":1}
,"memory":{"format":1,"new":1}
,"format":{"video":1,"examine":1,"v4l2":1,"pairs":1}
,"video":{"input":1}
,"input":{"topic":1}
,"nano":{"series":1}
,"series":{"jetson":1,"soc":1}
,"tx1":{"tegra":1}
,"tegra":{"soc":1,"parker":1}
,"soc":{"technical":1}
,"technical":{"referene":1,"reference":1}
,"referene":{"manual":1}
,"tx2":{"tegra":1}
,"parker":{"series":1}
,"reference":{"manual":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"technical":1}
,"enter":{"command":1}
,"dev":{"video":1,"video0":1}
,"number":{"camera":1,"registers":1,"i2c":1,"controls":1}
,"system":{"camera":1,"multiple":1}
,"i.e":{"device":1}
,"path":{"dev":1}
,"multiple":{"cameras":1}
,"cameras":{"specify":1}
,"specify":{"index":1,"sensor":1}
,"index":{"camera":1,"device":1}
,"want":{"test":1,"add":1}
,"--set-fmt-video":{"width":1}
,"width":{"1920":1}
,"1920":{"height":1,"1080":1}
,"height":{"1080":1}
,"1080":{"pixelformat":1,"imx185_mode_1920x1080_crop_30fps":1}
,"pixelformat":{"rg12":1}
,"rg12":{"--stream-mmap":1}
,"--stream-mmap":{"--set-ctrl":1}
,"--set-ctrl":{"sensor_mode":1}
,"sensor_mode":{"--stream-count":1}
,"--stream-count":{"100":1}
,"100":{"dev":1}
,"\u2011\u2011stream-count":{"switch":1}
,"switch":{"frames":1,"output":1}
,"frames":{"capture":1}
,"\u2011\u2011stream-to":{"switch":1}
,"output":{"path":1}
,"available":{"open":1,"linuxtv":1}
,"open":{"source":1}
,"source":{"projects":1,"file":1,"package":1,"code":1}
,"projects":{"documentation":1}
,"documentation":{"commands":1}
,"commands":{"available":1}
,"https":{"www.linuxtv.org":1}
,"www.linuxtv.org":{"wiki":1}
,"wiki":{"index.php":1}
,"index.php":{"v4l-utils":1}
,"debugging":{"tips":1,"typically":1}
,"ready":{"testing":1}
,"testing":{"running":1}
,"applications":{"check":1}
,"check":{"camera":1,"mode-specific":1,"power_on":1}
,"node":{"populated":1,"displayed":1}
,"populated":{"correctly":1,"properly":1}
,"correctly":{"system":1,"linked":1,"control":1}
,"properly":{"name":1}
,"name":{"camera\u2019s":1,"matches":1,"device":1,"example":1}
,"camera\u2019s":{"device":1}
,"problems":{"probing":1,"occur":1,"may":1}
,"probing":{"process":1,"fails":1,"succeeds":1,"create":1}
,"process":{"require":1,"data":1}
,"require":{"debugging":1}
,"typically":{"problems":1,"default":1}
,"occur":{"clock":1,"control":1}
,"clock":{"gpio":1,"names":1,"mode":1}
,"gpio":{"regulator":1,"numbers":1,"timing":1}
,"regulator":{"setup":1,"names":1}
,"verify":{"driver":1,"device":1,"functions":1,"default":1,"control":1,"mode-specific":1,"i2c":1,"sensor":1}
,"matches":{"name":1}
,"kernel":{"binds":1,"logs":1,"module":1,"image":1,"driver":1,"version":1,"kernel-4.4":1,"nvidia":1,"4.9":1}
,"binds":{"driver":1}
,"static":{"struct":1,"imx185_reg":1,"oimx185_reg":1,"const":1,"array":1}
,"struct":{"of_device_id":1,"camera_common_frmfmt":1,"tc_dev":1}
,"of_device_id":{"imx185_of_match":1}
,".compatible":{"nvidia":1}
,".name":{"imx185":1}
,".owner":{"this_module":1}
,".of_match_table":{"of_match_ptr":1}
,"of_match_ptr":{"imx185_of_match":1}
,"names":{"match":1,"read":1,"gpio":1,"date":1}
,"match":{"device":1,"hardware":1,"modes":1}
,"read":{"parse_dt":1}
,"parse_dt":{"match":1}
,"values":{"match":1,"assigned":1,"correctly":1,"linked":1,"mode":1,"register":1,"correct":1,"settings":1,"separate":1,"end":1,"need":1}
,"assigned":{"device":1}
,"fields":{"match":1}
,"describe":{"regulator":1}
,"numbers":{"clock":1}
,"date":{"device":1}
,"compiler":{"dtc":1}
,"dtc":{"convert":1}
,"convert":{".dtb":1,"32\u2011bit":1}
,".dtb":{"file":1}
,"back":{".dtsi":1}
,"examine":{"content":1,"kernel":1}
,"content":{"ensure":1}
,"node\u2019s":{"status":1}
,"field":{"proper":1}
,"functions":{"run":1,"sensor":1}
,"sure":{"functions":1,"contain":1,"control":1,"without":1,"include":1}
,"completion":{"pay":1}
,"pay":{"special":1}
,"special":{"attention":1,"requirements":1}
,"attention":{"kernel":1}
,"logs":{"look":1,"closely":1}
,"look":{"errors":1}
,"errors":{"cause":1,"associated":1,"check":1}
,"cause":{"function":1,"sensor":1}
,"function":{"exit":1,"verify":1,"deprecated":1,"tegra_media_entity_init":1,"replace":1,"probe":1}
,"exit":{"unexpectedly":1}
,"it\u2019s":{"good":1}
,"good":{"practice":1}
,"practice":{"code":1}
,"code":{"print":1,"release":1,"compare":1,"version":1}
,"print":{"error":1}
,"error":{"message":1}
,"message":{"point":1}
,"point":{"fail":1}
,"fail":{"silent":1}
,"silent":{"failure":1}
,"failure":{"harder":1}
,"harder":{"catch":1}
,"linked":{"correctly":1}
,"control":{"configuration":1,"handlers":1,"setting":1,"register":1,"registers":1,"version":1}
,"configuration":{"verify":1,"list":1}
,"macros":{"updated":1}
,"updated":{"appropriately":1}
,"appropriately":{"values":1}
,"mode":{"tables":1,"free":1,"gated":1,"sensor":1,"table":1,"resolution":1,"camera_common_frmfmt":1,"value":1}
,"tables":{"sensor":1,"data":1,"reside":1,"list":1,"separated":1,"separate":1,"exist":1,"may":1}
,"sensor-private":{"data":1}
,"macro":{"definitions":1}
,"controls":{"added":1,"needed":1,"provides":1,"64\u2011bit":1}
,"added":{"control":1}
,"list":{"sure":1,"reg_8":1,"maps":1,"table":1,"enumerations":1,"controls":1}
,"contain":{"appropriate":1}
,"appropriate":{"control":1}
,"handlers":{"default":1}
,"succeeds":{"problems":1}
,"may":{"occur":1,"omit":1,"time":1,"able":1}
,"setting":{"common":1,"control":1,"mode":1}
,"problem":{"incorrect":1}
,"incorrect":{"values":1}
,"setup":{"contains":1}
,"contains":{"correct":1,"mode\u2019s":1}
,"correct":{"register":1,"order":1,"problem":1}
,"address":{"formats":1}
,"formats":{"according":1}
,"according":{"mode":1,"register":1}
,"sheets":{"information":1}
,"mode-specific":{"settings":1}
,"settings":{"correct":1,"device":1,"sensor":1}
,"double":{"check":1}
,"necessary":{"common":1,"changes":1}
,"issues":{"cause":1}
,"timeout":{"due":1}
,"due":{"incorrect":1}
,"num_lanes":{"depending":1}
,"depending":{"sensor":1}
,"tegra_sinterface":{"csi":1}
,"csi":{"port":1,"endpoints":1}
,"port":{"sensor":1,"version":1}
,"discontinuous_clk":{"specify":1}
,"continuous":{"clock":1}
,"free":{"running":1}
,"discontinuous":{"clock":1}
,"gated":{"unsure":1}
,"unsure":{"first":1}
,"mclk_multiplier":{"equal":1}
,"equal":{"greater":1}
,"greater":{"pix_clk_hz":1}
,"pix_clk_hz":{"mclk":1}
,"mclk":{"ensure":1}
,"isp":{"runs":1}
,"runs":{"fast":1}
,"fast":{"enough":1}
,"enough":{"process":1}
,"i2c":{"accesses":1,"errors":1,"spi":1,"imx185.c":1}
,"accesses":{"working":1}
,"working":{"properly":1}
,"closely":{"i2c":1}
,"associated":{"camera":1}
,"power_on":{"function":1}
,"power-on":{"sequence":1}
,"sequence":{"correct":1}
,"order":{"enabling":1}
,"enabling":{"power":1}
,"power":{"clock":1}
,"timing":{"comply":1}
,"comply":{"sensor":1}
,"configuring":{"sensor":1}
,"loadable":{"kernel":1}
,"speed":{"development":1}
,"development":{"eliminating":1}
,"eliminating":{"need":1}
,"need":{"reflash":1,"updated":1}
,"reflash":{"kernel":1}
,"image":{"jetson":1,"dark":1}
,"register\u2019s":{"mode":1}
,"reside":{"separate":1}
,"separate":{"header":1,"mode":1,"delete":1,"stream-on":1}
,"header":{"file":1}
,"named":{"sensor_mode_tbls.h":1}
,"sensor_mode_tbls.h":{"included":1}
,"included":{"main":1}
,"reg_8":{"reg_16":1}
,"reg_16":{"address-value":1}
,"address-value":{"pairs":1}
,"pairs":{"mode":1,"according":1}
,"separated":{"resolution":1}
,"start":{"stop":1,"stream-register":1}
,"stop":{"stream-register":1}
,"stream-register":{"values":1}
,"delete":{"start":1}
,"end":{"resolution":1,"mode":1,"table":1}
,"resolution":{"mode":1,"part":1}
,"imx185_reg":{"imx185_start":1,"imx185_stop":1,"tp_colorbars":1,"mode_":1,"mode_table":1}
,"0x3000":{"0x00":1,"0x01":1}
,"imx185_table_wait_ms":{"imx185_wait_ms_start":1,"imx185_wait_ms_stream":1,"imx185_wait_ms_stop":1}
,"0x3002":{"0x00":1}
,"0x3049":{"0x02":1}
,"imx185_table_end":{"0x00":1}
,"table":{"color":1,"required":1,"header":1,"pointers":1,"match":1,"want":1,"place":1,"array":1,"considerations":1,"refer":1}
,"color":{"bars":1}
,"bars":{"test":1}
,"test":{"pattern":1,"patterns":1}
,"pattern":{"used":1}
,"used":{"test_mode":1,"version":1}
,"test_mode":{"flag":1}
,"flag":{"enabled":1,"enumeration":1}
,"enabled":{"activating":1}
,"activating":{"test-pattern":1}
,"test-pattern":{"mode":1}
,"required":{"sensor":1,"program":1}
,"supports":{"test":1,"regmap":1}
,"enumeration":{"mode":1,"table":1}
,"maps":{"enumeration":1}
,"oimx185_reg":{"mode_table":1}
,"imx185_mode_1920x1080_crop_30fps":{"imx185_1920x1080_crop_30fps":1}
,"modes":{"list":1,"listed":1}
,"listed":{"sensor":1}
,"camera_common_frmfmt":{"array":1,"imx185_frmfmt":1}
,"array":{"sets":1,"contains":1,"mode":1}
,"sets":{"format":1}
,"framework":{"element":1}
,"element":{"array":1,"list":1}
,"mode\u2019s":{"resolutions":1}
,"resolutions":{"is_hdr":1}
,"is_hdr":{"flag":1}
,"const":{"struct":1}
,"obtain":{"address-value":1}
,"stream-on":{"stream-off":1}
,"stream-off":{"mode":1}
,"exist":{"may":1}
,"omit":{"mode":1}
,"structure":{"initialize":1,"specifies":1}
,"initialize":{"static":1}
,"part":{"name":1}
,"addr":{"val":1}
,"val":{"pairs":1}
,"place":{"end":1}
,"enumerations":{"add":1}
,"imx185_mode_":{"mode_":1}
,"refer":{"thousands":1}
,"thousands":{"registers":1}
,"registers":{"increases":1,"extreme":1,"referenced":1,"typically":1,"small":1,"reduce":1}
,"increases":{"delay":1}
,"delay":{"sensor":1,"capture":1}
,"starts":{"streaming":1}
,"streaming":{"time":1}
,"time":{"required":1,"sensor":1,"first":1,"setting":1}
,"program":{"registers":1}
,"extreme":{"cases":1}
,"cases":{"recipient":1}
,"recipient":{"engine":1}
,"engine":{"may":1,"prevent":1}
,"outputs":{"first":1}
,"several":{"possible":1}
,"possible":{"ways":1}
,"ways":{"correct":1}
,"reduce":{"number":1}
,"referenced":{"mode":1}
,"able":{"smaller":1}
,"smaller":{"mode":1}
,"vendor":{"registers":1,"sure":1}
,"arrange":{"registers":1}
,"small":{"groups":1}
,"groups":{"consecutive":1}
,"consecutive":{"register":1,"registers":1}
,"addresses":{"nvidia":1}
,"regmap":{"bulk":1}
,"bulk":{"writes":1}
,"writes":{"consecutive":1}
,"spi":{"transactions":1,"buses":1}
,"transactions":{"consult":1}
,"consult":{"sensor":1}
,"without":{"affecting":1}
,"affecting":{"sensor":1}
,"request":{"longer":1}
,"longer":{"delay":1}
,"prevent":{"timeouts":1}
,"timeouts":{"add":1}
,"property":{"set_mode_delay_ms":1,"sensor":1}
,"set_mode_delay_ms":{"sensor\u2019s":1}
,"sensor\u2019s":{".dtsi":1}
,"extend":{"wait":1}
,"wait":{"time":1}
,"drivers":{"porting":1,"developed":1,"locations":1,"media":1,"version":1,"imx185.c":1}
,"package":{"l4t":1,"current":1}
,"l4t":{"release":1}
,"release":{"upgraded":1,"work":1,"driver":1,"current":1,"source":1,"sample":1,"28.2":1,"later":1}
,"upgraded":{"linux":1}
,"version":{"4.4":1,"1.0":1,"2.0":1}
,"4.4":{"4.9":1}
,"4.9":{"sensor":1,"nvidia":1}
,"developed":{"l4t":1}
,"work":{"current":1,"release":1,"properly":1}
,"current":{"release":1,"sensor":1}
,"modify":{"work":1,"following":1}
,"interface":{"section":1}
,"describes":{"necessary":1,"changes":1}
,"find":{"differences":1}
,"differences":{"release":1}
,"compare":{"imx185.c":1,"source":1}
,"imx185.c":{"sample":1,"imx185_v1.c":1}
,"sample":{"driver":1,"drivers":1}
,"28.2":{"28.2.1":1}
,"kernel-4.4":{"drivers":1}
,"media":{"i2c":1}
,"changes":{"v4l2":1,"modify":1,"device":1,"current":1,"port":1,"driver":1}
,"media_entity_init":{"function":1,"&priv-":1}
,"deprecated":{"kernel":1}
,"provides":{"new":1,"pointer":1}
,"wrapper":{"function":1}
,"tegra_media_entity_init":{"adapt":1,"&priv-":1}
,"adapt":{"changes":1}
,"driver\u2019s":{"probe":1}
,"probe":{"function":1,"allocate":1,"call":1}
,"priv-":{"subdev-":1}
,"subdev-":{"entity.type":1,"entity.ops":1,"entity":1}
,"entity.type":{"media_ent_t_v4l2_subdev_sensor":1}
,"entity.ops":{"&imx185_media_ops":1}
,"err":{"media_entity_init":1,"tegra_media_entity_init":1}
,"&priv-":{"subdev-":1,"pad":1}
,"entity":{"&priv-":1}
,"pad":{"true":1}
,"true":{"true":1}
,"later":{"support":1}
,"buses":{"cphy":1}
,"cphy":{"dphy":1,"depending":1}
,"dphy":{"interfaces":1,"cphy":1}
,"interfaces":{"avoid":1}
,"avoid":{"confusion":1}
,"confusion":{"following":1}
,"rename":{"csi-port":1}
,"csi-port":{"port-index":1}
,"port-index":{"csi":1}
,"phy_mode":{"property":1}
,"value":{"dphy":1,"properties":1}
,"porting":{"version":1}
,"1.0":{"drivers":1,"driver":1,"flexible":1}
,"factor":{"step":1,"used":1,"version":1}
,"step":{"default":1}
,"properties":{"sensor":1,"work":1}
,"gain":{"exposure":1}
,"exposure":{"framerate":1,"time":1}
,"framerate":{"properties":1}
,"recommends":{"default_gain":1}
,"default_gain":{"min_gain_val":1}
,"min_gain_val":{"default_framerate":1}
,"default_framerate":{"max_framerate":1}
,"max_framerate":{"default_exp_time":1}
,"default_exp_time":{"don\u2019t":1}
,"don\u2019t":{"min_exp_time":1}
,"min_exp_time":{"max_exp_time":1}
,"max_exp_time":{"image":1}
,"dark":{"bright":1}
,"bright":{"sensor":1}
,"started":{"instead":1}
,"instead":{"exposure":1}
,"2.0":{"version":1,"driver":1}
,"imx185_v1.c":{"differences":1}
,"hard":{"coded":1}
,"coded":{"sensor":1}
,"allocate":{"memory":1}
,"tc_dev":{"new":1}
,"tegracam_device_register":{"tegracam_subdev_register":1}
,"tegracam_subdev_register":{"functions":1}
,"context":{"register":1}
,"fulfill":{"special":1}
,"requirements":{"during":1}
,"during":{"sensor":1}
,"board_setup":{"function":1}
,"ctrl_id_list":{"list":1}
,"needed":{"sensor":1}
,"tegracam_ctrl_ops":{"structure":1}
,"specifies":{"number":1}
,"pointer":{"handler":1}
,"handler":{"control":1}
,"32\u2011bit":{"controls":1}
,"64\u2011bit":{"controls":1}
,"scaling":{"factor":1}
,"flexible":{"scaling":1}
,"group":{"hold":1}
,"hold":{"control":1,"feature":1,"function":1}
,"mandatory":{"hardware":1}
,"feature":{"create":1}
,"dummy":{"group":1}
}
;Search.control.loadWordPairs(pairs);
