var pairs =
{
"applications":{"tools":1,"runs":1,"provides":1}
,"topic":{"describes":1}
,"describes":{"applications":1}
,"tools":{"provided":1,"available":1,"debugging":1,"profiling":1}
,"provided":{"nvidia":1}
,"nvidia":{"jetson":1,"nsight":1}
,"jetson":{"linux":1,"xavier":1,"nano":1,"agx":1,"tx2":1,"tx1":1,"system":1,"products":1}
,"linux":{"driver":1,"host":1}
,"driver":{"package":1}
,"package":{"l4t":1}
,"following":{"tables":1}
,"tables":{"describe":1}
,"describe":{"tools":1}
,"available":{"debugging":1}
,"debugging":{"performance":1,"applications":1,"application":1,"via":1,"profiling":1,"optimizing":1}
,"performance":{"measurement":1,"identifying":1,"metrics":1}
,"measurement":{"l4t":1}
,"l4t":{"descriptions":1}
,"descriptions":{"links":1}
,"links":{"sources":1}
,"sources":{"further":1}
,"further":{"information":1}
,"tool":{"purpose":1,"cuda":1,"debugging":1}
,"nano":{"devices":1}
,"agx":{"xavier":1}
,"xavier":{"series":1}
,"tx2":{"series":1}
,"nsight":{"eclipse":1,"systems":1,"compute":1,"graphics":1}
,"eclipse":{"edition":1}
,"developing":{"gpu-accelerated":1}
,"gpu-accelerated":{"applications":1}
,"runs":{"linux":1,"jetson":1}
,"host":{"computer":1}
,"system":{"linux":1}
,"application":{"memory":1,"multi-core":1,"performance":1,"profiling":1,"debugging":1}
,"memory":{"errors":1}
,"errors":{"runs":1}
,"profiling":{"optimization":1,"runs":1,"across":1,"interactive":1,"tool":1,"console-grade":1}
,"multi-core":{"cpu":1}
,"cpu":{"profiling":1,"runs":1}
,"computer":{"helps":1,"supports":1}
,"helps":{"improve":1}
,"improve":{"application":1}
,"identifying":{"slow":1}
,"slow":{"parts":1}
,"parts":{"code":1}
,"visual":{"profiler":1}
,"across":{"gpu":1}
,"gpu":{"cpu":1}
,"supports":{"jetson":1}
,"kernel":{"profiling":1}
,"interactive":{"profiling":1}
,"cuda":{"applications":1}
,"provides":{"detailed":1}
,"detailed":{"performance":1}
,"metrics":{"api":1}
,"api":{"debugging":1}
,"via":{"user":1}
,"user":{"interface":1}
,"interface":{"command":1}
,"command":{"line":1}
,"line":{"tool":1}
,"graphics":{"application":1}
,"console-grade":{"tool":1}
,"optimizing":{"opengl":1}
,"opengl":{"opengl":1,"programs":1}
,"programs":{"runs":1}
,"deprecated":{"supported":1}
}
;Search.control.loadWordPairs(pairs);
