var pairs =
{
"debugging":{"jetson":1,"tools":1,"support":1,"strategies":1,"improvements":1,"features":1}
,"jetson":{"platforms":1,"devices":1,"application":1,"architecture\u2019s":1,"board":1,"processor":1,"nano":1,"tx1":1,"xavier":1,"agx":1,"tx2":1,"characteristics":1,"nvidia":1}
,"nvidia":{"jetson":1,"higher":1,"processors":1,"uncore":1,"tegra":1,"carmel-pmu.txt":1}
,"devices":{"support":1,"jetson":1}
,"support":{"debugging":1,"provides":1,"package":1,"via":1}
,"tools":{"allow":1}
,"allow":{"jetson":1}
,"application":{"developers":1}
,"developers":{"place":1}
,"place":{"processor":1}
,"processor":{"known":1,"family":1,"tracing":1}
,"known":{"states":1}
,"states":{"trace":1}
,"trace":{"behavior":1,"storage":1,"buffer":1,"sinks":1,"sink":1,"fifo":1,"watchdog":1,"low":1,"avoid":1,"atid":1,"multiple":1,"data":1}
,"behavior":{"running":1}
,"running":{"jetson":1}
,"architecture\u2019s":{"debugging":1}
,"reduced":{"power":1}
,"power":{"leakage":1}
,"enhanced":{"security":1}
,"availability":{"standard":1}
,"standard":{"interfaces":1,"arm":1}
,"topic":{"describes":1}
,"describes":{"debuggable":1,"software":1,"improvements":1,"coresight":1,"features":1}
,"debuggable":{"blocks":1}
,"blocks":{"debugging":1}
,"strategies":{"information":1}
,"information":{"help":1,"debugging":1,"using":1}
,"help":{"determine":1}
,"determine":{"something":1}
,"something":{"may":1}
,"may":{"working":1,"downloaded":1}
,"working":{"software":1}
,"software":{"developed":1,"implementation":1,"features":1,"access":1}
,"developed":{"using":1}
,"using":{"nvidia":1,"a57":1,"counters":1}
,"board":{"support":1}
,"package":{"bsp":1}
,"implementation":{"hardware":1}
,"hardware":{"software":1,"feature":1,"interface":1}
,"features":{"jetson":1,"limitations":1}
,"family":{"technical":1}
,"technical":{"reference":1}
,"reference":{"manuals":1,"manual":1}
,"manuals":{"trms":1}
,"trms":{"appropriate":1}
,"appropriate":{"trm":1}
,"trm":{"primary":1}
,"primary":{"source":1}
,"source":{"information":1,"code":1}
,"nano":{"devices":1}
,"tx1":{"tegra":1}
,"tegra":{"soc":1,"parker":1,"systems":1,"nvidia":1}
,"soc":{"technical":1}
,"xavier":{"jetson":1,"series":1}
,"agx":{"xavier":1}
,"series":{"processors":1,"soc":1,"jetson":1,"t194":1,"modules":1}
,"processors":{"xavier":1,"tegra":1,"jetson":1}
,"tx2":{"series":1}
,"parker":{"series":1}
,"following":{"table":1,"tables":1}
,"table":{"describes":1}
,"improvements":{"debugging":1}
,"feature":{"benefit":1}
,"interface":{"debugger":1,"connected":1}
,"jtag":{"4-pin":1,"swd":1}
,"4-pin":{"connector":1}
,"swd":{"2-pin":1}
,"2-pin":{"connector":1}
,"debug":{"interface":1,"communication":1,"connection":1}
,"connected":{"cpu":1}
,"cpu":{"via":1,"frequency":1}
,"via":{"debug":1,"jtag":1,"etr":1}
,"communication":{"channel":1}
,"channel":{"memory":1}
,"memory":{"access":1,"coherent":1}
,"access":{"mode":1,"cpus":1,"mmio":1,"entire":1,"performance":1}
,"debugger":{"downloads":1,"accesses":1}
,"downloads":{"uploads":1}
,"uploads":{"code":1}
,"code":{"faster":1,"optimization":1}
,"connection":{"axi-ap":1,"snic":1,"ape":1,"bpmp":1,"rce":1}
,"axi-ap":{"via":1,"34-bit":1}
,"system":{"access":1}
,"cpus":{"unavailable":1}
,"unavailable":{"powered":1}
,"powered":{"down":1}
,"down":{"dead":1}
,"dead":{"reset":1}
,"34-bit":{"address":1}
,"address":{"access":1}
,"mmio":{"dram":1}
,"dram":{"requiring":1,"bandwidth":1}
,"requiring":{"smmu":1}
,"snic":{"allows":1}
,"allows":{"access":1,"arm":1}
,"entire":{"system":1}
,"accesses":{"memory":1}
,"coresight":{"support":1,"trace":1,"amba":1}
,"bpmp":{"spe":1}
,"spe":{"sce":1}
,"rce":{"pva0":1}
,"pva0":{"pva1":1}
,"storage":{"circular":1}
,"circular":{"buffer":1}
,"larger":{"buffer":1}
,"buffer":{"yields":1,"preserved":1}
,"yields":{"longer":1}
,"longer":{"duration":1}
,"duration":{"trace":1}
,"preserved":{"wdt":1}
,"wdt":{"resets":1}
,"sinks":{"etf":1}
,"etf":{"etr":1,"kib":1}
,"sink":{"characteristics":1}
,"characteristics":{"jetson":1,"include":1}
,"include":{"corresponding":1}
,"corresponding":{"embedded":1}
,"embedded":{"trace":1}
,"fifo":{"etf":1}
,"etr":{"usb":1,"dma":1,"atids":1}
,"usb":{"limits":1,"speeds":1}
,"ddr":{"via":1}
,"tpiu":{"jetson":1}
,"41.58":{"gbps":1}
,"gbps":{"408":1}
,"408":{"mhz":1}
,"mhz":{"128\u2011bit":1}
,"800":{"mbps":1}
,"real":{"time":1}
,"time":{"processor":1}
,"tracing":{"requires":1,"limited":1}
,"requires":{"reduction":1}
,"reduction":{"cpu":1}
,"available":{"commercial":1}
,"commercial":{"devices":1}
,"collect":{"trace":1}
,"watchdog":{"reset":1}
,"reset":{"code":1}
,"optimization":{"ccplex":1}
,"collects":{"trace":1}
,"ccplex":{"tracing":1,"using":1,"e.g":1}
,"limited":{"bandwidth":1,"usb":1}
,"bandwidth":{"speed":1,"saturation":1,"requirement":1}
,"single-cpu":{"trace":1}
,"low":{"frequency":1}
,"frequency":{"ape-only":1,"requirements":1}
,"ape-only":{"trace":1}
,"avoid":{"dram":1}
,"saturation":{"tracing":1}
,"contact":{"nvidia":1}
,"higher":{"frequency":1}
,"note":{"high":1}
,"high":{"bandwidth":1}
,"requirement":{"ddr":1}
,"amba":{"trace":1}
,"atid":{"mapping":1,"collecting":1}
,"tables":{"describe":1}
,"describe":{"mapping":1}
,"mapping":{"coresight":1}
,"collecting":{"trace":1}
,"multiple":{"sources":1}
,"sources":{"trace":1}
,"atids":{"segregate":1}
,"segregate":{"trace":1}
,"bccplex":{"called":1}
,"called":{"fast":1,"uncore":1}
,"fast":{"cluster":1}
,"cluster":{"big":1,"using":1}
,"big":{"cluster":1}
,"a57":{"processors":1}
,"ape":{"cortex":1}
,"mipi":{"stp":1}
,"cpu0":{"cpu7":1}
,"pva":{"pva1":1}
,"uncore":{"performance":1,"report":1,"perfmon":1,"permon":1}
,"performance":{"monitor":1,"events":1,"counters":1}
,"monitor":{"unit":1,"extension":1}
,"applies":{"t186":1}
,"t186":{"processors":1,"used":1}
,"t194":{"processors":1,"ccplex":1,"used":1}
,"several":{"functional":1}
,"functional":{"units":1}
,"units":{"t194":1,"collectively":1}
,"e.g":{"scf":1}
,"scf":{"outside":1}
,"outside":{"cores":1}
,"cores":{"units":1,"denver":1,"clusters":1}
,"collectively":{"referred":1}
,"referred":{"uncore":1}
,"report":{"uncore":1}
,"events":{"event":1,"supported":1}
,"event":{"counters":1}
,"counters":{"counted":1,"core\u2019s":1,"uncore":1,"kernel":1}
,"counted":{"core":1}
,"core":{"performance":1}
,"core\u2019s":{"performance":1}
,"unit":{"pmu":1}
,"perfmon":{"extension":1,"allows":1,"specific":1,"events":1}
,"extension":{"arm":1,"called":1,"designed":1,"possible":1}
,"arm":{"performance":1,"software":1,"pmu":1}
,"designed":{"resemble":1}
,"resemble":{"standard":1}
,"pmu":{"documentation":1}
,"documentation":{"may":1,"within":1,"devicetree":1}
,"downloaded":{"linux":1}
,"linux":{"kernel":1}
,"kernel":{"archives":1,"documentation":1}
,"device-specific":{"features":1}
,"section":{"describes":1}
,"limitations":{"uncore":1}
,"specific":{"nvidia":1}
,"systems":{"chip":1}
,"chip":{"socs":1}
,"used":{"nvidia":1}
,"permon":{"events":1}
,"supported":{"denver":1,"cores":1}
,"denver":{"cores":1,"cluster":1}
,"within":{"source":1}
,"kernel-source-path":{"documentation":1}
,"devicetree":{"bindings":1}
,"bindings":{"platform":1}
,"platform":{"tegra":1}
}
;Search.control.loadWordPairs(pairs);
