var pairs =
{
"partition":{"configuration":1,"configurations":1,"elements":1,"layout":1,"definitions":1,"element":1,"name":1,"properties":1,"overview":1,"names":1,"type":1,"certain":1,"types":1,"legacy":1,"bytes":1,"size":1,"specifying":1,"erase":1,"defined":1,"extended":1,"immediately":1,"filename":1,"boot":1,"tools":1,"allocation":1,"table":1,"may":1,"change":1,"partition":1,"device":1}
,"nvidia":{"jetson":1,"tegra":1,"signed":1}
,"jetson":{"linux":1,"platforms":1,"xavier":1,"nano":1,"tx1":1,"tx2":1,"tx2i":1,"agx":1}
,"linux":{"driver":1,"kernel":1}
,"driver":{"package":1}
,"package":{"l4t":1}
,"l4t":{"supports":1,"default":1}
,"supports":{"formatting":1}
,"formatting":{"mass":1}
,"mass":{"storage":1}
,"storage":{"media":1,"devices":1,"medium":1,"device":1,"available":1}
,"media":{"multiple":1}
,"multiple":{"partitions":1,"subdevices":1,"device":1,"partition":1}
,"partitions":{"storing":1,"platform":1,"element":1,"subdevices":1,"treated":1,"mandatory":1,"begin":1,"partitions":1,"identified":1,"defined":1,"master_boot_record":1}
,"storing":{"data":1}
,"data":{"device":1,"bootloader":1,"written":1,"removable":1}
,"device":{"image":1,"firmware":1,".xml":1,".conf":1,"elements":1,"element":1,"spanning":1,"type":1,"attributes":1,"emmc":1,"instance":1,"always":1,"supported":1,"tree":1,"selection":1,"partitions":1,"dev":1,"except":1,"partition":1,"start":1,"examples":1,"1024209543168":1,"description":1,"partition_layout":1}
,"image":{"bootloader":1,"device":1,"removable":1,"removeable":1}
,"bootloader":{"image":1,"splash":1,"t210ref":1,"t186ref":1,"flash.xml":1,"tegraflash.py":1,"dtb":1,"binary":1,"device":1}
,"firmware":{"bootloader":1,"file":1,"device":1}
,"splash":{"screens":1,"screen":1}
,"platforms":{"platform":1,"similar":1,"series":1,"grouped":1}
,"platform":{"series":1,"l4t":1,"may":1}
,"certain":{"jetson":1,"partition":1}
,"similar":{"characteristics":1}
,"characteristics":{"including":1}
,"including":{"identical":1}
,"identical":{"partition":1}
,"configurations":{"topic":1}
,"topic":{"describes":1,"end":1}
,"describes":{"platforms":1,"mass":1,"supported":1,"attributes":1}
,"series":{"discusses":1,"jetson":1,"flash_l4t_t186.xml":1,"partition":1,"append":1,"p2888":1,"p3489":1}
,"discusses":{"together":1}
,"together":{"supported":1}
,"supported":{"platforms":1,"device":1,"partition":1,"platform":1}
,"includes":{"platforms":1}
,"xavier":{"sku":1,"series":1,"16gb":1,"32gb":1,"industrial":1,"jetson":1,"development":1,"production":1}
,"sku":{"0000":1,"0001":1,"0002":1,"0003":1}
,"0000":{"development":1,"flash_l4t_t210_max-spi_sd_p3448.xml":1}
,"development":{"sku":1,"jetson":1,"kit":1,"module":1}
,"0001":{"production":1,"flash_l4t_t194_spi_sd_p3668.xml":1}
,"nano":{"devices":1,"sku":1,"development":1,"2gb":1,"production":1}
,"devices":{"jetson":1,"partitions":1,"divided":1,"e.g":1}
,"kit":{"sku":1,"nvidia":1}
,"0002":{"production":1,"flash_l4t_t210_emmc_p3448.xml":1}
,"production":{"jetson":1,"module":1}
,"2gb":{"sku":1,"development":1}
,"0003":{"jetson":1,"flash_l4t_t210_max-spi_p3448.xml":1}
,"tx2":{"series":1,"jetson":1,"4gb":1}
,"tx2i":{"jetson":1}
,"4gb":{"jetson":1}
,"agx":{"xavier":1}
,"16gb":{"jetson":1,"flash_t194_sdmmc.xml":1}
,"32gb":{"jetson":1,"flash_t194_sdmmc.xml":1}
,"configuration":{"file":1,"table":1}
,"file":{"describes":1,"directory":1,"translates":1,"composed":1,"following":1,"contains":1,"contain":1,"written":1,"size":1,"modified":1,"write":1,"value":1,"name":1,"making":1,"flashing":1}
,"default":{"partition":1,"translated":1,"cbo.dtb":1,"card":1}
,"directory":{"available":1}
,"top":{"linux_for_tegra":1}
,"linux_for_tegra":{"bootloader":1}
,"t210ref":{"cfg":1}
,"cfg":{"jetson":1}
,"t186ref":{"cfg":1}
,"filename":{"specified":1,"empty":1}
,"specified":{"device":1,"bootloader":1,"partition":1,"less":1}
,".xml":{"typical":1}
,"typical":{"values":1}
,"values":{"systems":1,"specified":1,"follows":1,"valid":1,"jetson":1}
,"systems":{"booting":1}
,"booting":{"emmc":1}
,"industrial":{"flash_l4t_t194_spi_emmc_jaxi.xml":1}
,"tx1":{"gnu_linux_tegraboot_emmc_full.xml":1,"partition":1,"platform":1,"p2180":1}
,"during":{"flashing":1,"boot":1}
,"flashing":{"procedure":1,"specified":1,"external":1}
,"procedure":{"flash.sh":1}
,"flash.sh":{"reads":1}
,"reads":{"partition":1,"bootloader":1}
,"translates":{"keywords":1}
,"keywords":{"values":1,"may":1}
,".conf":{"option":1}
,"option":{"parameters":1,"file":1}
,"parameters":{"saves":1}
,"saves":{"data":1}
,"flash.xml":{"bootloader":1,"performs":1}
,"tegraflash.py":{"reads":1}
,"performs":{"actual":1}
,"actual":{"flashing":1}
,"details":{"list":1}
,"list":{"translated":1,"keywords":1}
,"translated":{"keywords":1,"value":1}
,"composed":{"following":1}
,"following":{"xml":1,"syntax":1,"table":1}
,"xml":{"format":1,"version":1}
,"format":{"elements":1}
,"root":{"element":1}
,"elements":{"jetson":1,"partition":1,"following":1,"device":1,"legal":1}
,"element":{"configuration":1,"subdevice":1,"present":1,"storage":1,"may":1,"jetson":1,"attributes":1,"child":1}
,"version":{"1.0":1,"1.0.0":1,"01.00.0000":1,"information":1,"info":1}
,"1.0":{"nvidia":1}
,"tegra":{"partition":1}
,"layout":{"version":1}
,"1.0.0":{"partition_layout":1}
,"partition_layout":{"version":1}
,"01.00.0000":{"device":1}
,"contains":{"device":1,"boot":1,"nvidia":1,"mb1":1,"memory":1,"bpmp":1,"tegraboot":1,"denver":1,"microcode":1,"warm":1,"slot":1,"xusb":1,"cboot":1,"bootloader":1,"bmp":1,"trusted":1,"encrypted":1,"adsp":1,"camera-rtcpu-rce":1,"camera-rtcpu-sce":1,"bsp":1,"redundant":1,"secondary":1,"protective":1,"primary":1,"rootfs":1,"boot.img":1,"kernel":1,"recovery":1,"partition":1,"sc7":1,"tos":1,"u-boot":1,"linux":1,"dram-ecc":1,"badpage":1}
,"subdevice":{"example":1}
,"example":{"emmc":1,"jetson":1,"below":1}
,"emmc":{"boot":1,"boot0":1}
,"boot":{"user":1,"option":1,"device":1,"configuration":1,"power":1,"firmware":1,"update":1,"stage":1,"control":1,"binary":1,"pack":1}
,"user":{"hardware":1,"defined":1,"specified":1,"data":1}
,"hardware":{"partitions":1}
,"present":{"even":1}
,"even":{"devices":1}
,"divided":{"subdevices":1,"multiple":1}
,"contain":{"device":1,"multiple":1,"least":1}
,"definitions":{"appear":1}
,"appear":{"directly":1,"partition":1}
,"directly":{"root":1}
,"medium":{"divided":1}
,"subdevices":{"example":1,"treated":1}
,"treated":{"single":1}
,"single":{"linear":1,"sdmmc_boot":1}
,"linear":{"device":1}
,"spanning":{"subdevices":1}
,"may":{"contain":1,"equal":1,"appear":1,"mounted":1}
,"type":{"device":1,"instance":1,"type":1,"oem_sign":1,"user":1,"data":1,"partition":1,"allocation":1,"nvme":1,"protective_master_boot_record":1,"primary_gpt":1,"secondary_gpt":1}
,"instance":{"instance":1,"partition":1,"spi":1,"number":1,"sector_size":1}
,"attributes":{"table":1,"legal":1,"supported":1}
,"table":{"describes":1,"bct":1,"template":1}
,"legal":{"values":1,"information":1}
,"sdmmc_boot":{"sdmmc_user":1,"entry":1,"partition":1,"device":1}
,"sdmmc_user":{"spi":1,"device":1,"partition":1}
,"spi":{"nvme":1,"device":1}
,"required":{"specifies":1,"partitions":1,"optional":1,"contains":1,"slot":1,"automatically":1,"u-boot":1}
,"specifies":{"type":1,"device":1,"name":1,"raw":1,"size":1}
,"boot0":{"boot1":1}
,"boot1":{"hardware":1}
,"nvme":{"typically":1,"instance":1,"devices":1,"ssds":1,"update":1,"device":1}
,"typically":{"emmc":1}
,"name":{"name":1,"type":1,"partition":1,"maximum":1,"file":1,"default":1,"appropriate":1,"jetson-xavier-nx-development-module-p3668-0000-sd-card-partition":1,"external-storage-device-partition":1,"master_boot_record":1,"primary_gpt":1,"secondary_gpt":1}
,"oem_sign":{"true":1}
,"true":{"partition":1,"false":1,"usb":1}
,"properties":{"partition":1}
,"maximum":{"characters":1}
,"characters":{"three":1}
,"three":{"kinds":1,"partitions":1}
,"kinds":{"partitions":1}
,"mandatory":{"optional":1}
,"optional":{"user":1,"partition":1,"slot":1,"contains":1,"future":1,"fuse":1,"efi":1,"nct":1,"mts":1,"removeable":1}
,"defined":{"mandatory":1,"end":1,"entry":1,"primary_gpt":1}
,"names":{"associated":1}
,"associated":{"specific":1,"partition":1,"boot":1,"execution":1}
,"specific":{"partition":1}
,"types":{"valid":1}
,"valid":{"associated":1,"partition":1}
,"false":{"unspecified":1}
,"append":{"generic":1,"null":1}
,"generic":{"signature":1}
,"signature":{"header":1}
,"header":{"binary":1}
,"binary":{"perform":1,"loads":1,"kernel":1,"can\u0027t":1}
,"perform":{"oem":1,"null":1}
,"oem":{"signing":1}
,"signing":{"append":1}
,"null":{"signature":1,"signing":1}
,"child":{"elements":1}
,"allocation":{"policy":1,"attribute":1}
,"policy":{"sequential":1}
,"sequential":{"partitions":1,"allocation_policy":1}
,"begin":{"immediately":1}
,"immediately":{"preceding":1}
,"preceding":{"partition":1,"secondary":1}
,"basic":{"filesystem_type":1}
,"filesystem_type":{"specifies":1,"basic":1,"size":1}
,"raw":{"partition":1}
,"legacy":{"ext2":1}
,"ext2":{"filesystem":1}
,"filesystem":{"deprecated":1,"removable":1}
,"byte":{"size":1}
,"size":{"partition":1,"may":1,"file":1,"allows":1,"increase":1,"specified":1,"align":1,"property":1,"automatically":1,"512":1,"file_system_attribute":1,"pptsize":1,"0xffffffffffffffff":1}
,"bytes":{"decimal":1,"available":1}
,"decimal":{"hexadecimal":1}
,"hexadecimal":{"values":1}
,"equal":{"larger":1}
,"larger":{"size":1}
,"written":{"partition":1}
,"specifying":{"larger":1}
,"allows":{"file":1}
,"increase":{"later":1}
,"later":{"without":1}
,"without":{"requiring":1}
,"requiring":{"partition":1}
,"modified":{"partition":1}
,"less":{"erase":1}
,"erase":{"block":1}
,"block":{"size":1,"boundary":1}
,"align":{"itself":1}
,"itself":{"partition":1}
,"boundary":{"size":1}
,"property":{"secondary":1}
,"secondary":{"gpt":1}
,"gpt":{"partition":1,"spi":1,"sdcard":1,"sdmmc_user":1,"sdmmc_boot":1}
,"end":{"device":1,"document":1}
,"always":{"0xffffffffffffffff":1}
,"0xffffffffffffffff":{"tegraflash":1,"size":1}
,"tegraflash":{"calculates":1}
,"calculates":{"size":1}
,"automatically":{"preceding":1,"takes":1}
,"extended":{"fill":1}
,"fill":{"free":1}
,"free":{"space":1}
,"space":{"secondary":1,"device":1,"occupied":1}
,"0x008":{"0x808":1}
,"0x808":{"partition":1,"may":1}
,"write":{"partition":1}
,"empty":{"data":1}
,"tables":{"below":1,"section":1,"refer":1}
,"below":{"list":1,"external":1}
,"value":{"allowed":1,"flash.xml":1}
,"allowed":{"keyword":1}
,"appropriate":{"bootloader":1,"bpmp":1,"kernel":1,"cboot":1,"recovery":1}
,"dtb":{"file":1,"image":1,"binary":1}
,"bpmp":{"dtb":1,"spe-fw":1,"firmware":1}
,"kernel":{"dtb":1,"image":1,"partition":1,"accessible":1,"initrd":1,"rootfs":1,"device":1}
,"cboot":{"boot":1,"final":1}
,"recovery":{"kernel":1,"image":1,"dtb":1,"filesystem":1}
,"section":{"describe":1}
,"describe":{"partition":1}
,"note":{"table\u2019s":1,"several":1}
,"table\u2019s":{"description":1}
,"description":{"column":1,"required":1,"partition":1}
,"column":{"identifies":1}
,"identifies":{"required":1}
,"identified":{"required":1}
,"several":{"entries":1}
,"entries":{"tables":1}
,"refer":{"arm":1}
,"arm":{"arm":1,"code":1,"registered":1,"limited":1,"presented":1}
,"code":{"arm":1}
,"registered":{"trademark":1}
,"trademark":{"arm":1}
,"limited":{"complete":1}
,"complete":{"attribution":1}
,"attribution":{"statement":1}
,"statement":{"arm":1}
,"presented":{"legal":1}
,"information":{"topic":1}
,"module":{"p3668-0000":1,"p3668-0001":1,"p3448-0000":1,"p3448-0002":1,"p3448-0003":1,"card":1}
,"p3668-0000":{"qspi_nor":1,"card":1}
,"qspi_nor":{"partition":1}
,"alloc":{"policy":1,"attribute":1}
,"slot":{"contains":1,"status":1,"future":1}
,"signed":{"mb1":1}
,"mb1":{"binary":1,"boot":1}
,"memory":{"configuration":1}
,"spe-fw":{"binary":1}
,"tegraboot":{"binary":1,"cpu-side":1}
,"denver":{"preboot":1,"boot":1}
,"preboot":{"firmware":1}
,"microcode":{"associated":1}
,"power":{"management":1}
,"management":{"clocks":1}
,"execution":{"optimization":1}
,"optimization":{"arm":1}
,"warm":{"boot":1}
,"status":{"boot":1}
,"xusb":{"module\u2019s":1,"true":1}
,"module\u2019s":{"firmware":1}
,"making":{"xusb":1}
,"usb":{"3.0":1}
,"3.0":{"compliant":1}
,"compliant":{"host":1}
,"host":{"controller":1}
,"final":{"boot":1}
,"stage":{"cpu":1}
,"cpu":{"bootloader":1}
,"loads":{"binary":1,"launches":1}
,"tree":{"blob":1}
,"blob":{"dtb":1}
,"bmp":{"images":1}
,"images":{"splash":1}
,"screen":{"display":1}
,"display":{"during":1}
,"encrypted":{"keys":1}
,"adsp":{"software":1}
,"camera-rtcpu-rce":{"firmware":1}
,"camera-rtcpu-sce":{"firmware":1}
,"selection":{"priority":1}
,"priority":{"list":1}
,"bsp":{"version":1}
,"redundant":{"copy":1}
,"copy":{"bsp":1,"tegraboot":1,"partition":1,"bootloader":1,"cboot":1,"warm":1,"sc7":1,"kernel":1,"tos":1,"encrypted":1,"u-boot":1,"boot":1,"kkernel":1}
,"card":{"partition":1}
,"protective":{"mbr":1}
,"primary":{"gpt":1}
,"sdcard":{"device":1}
,"entry":{"configured":1,"firmware":1}
,"configured":{"kernel":1}
,"accessible":{"standard":1}
,"standard":{"partition":1}
,"tools":{"gdisk":1}
,"gdisk":{"parted":1}
,"rootfs":{"partition":1,"boot":1}
,"primary_gpt":{"accessed":1,"secondary_gpt":1,"type":1,"allocation_policy":1}
,"accessed":{"fixed":1}
,"fixed":{"known":1}
,"known":{"special":1}
,"special":{"device":1}
,"dev":{"mmcblk0p1":1}
,"boot.img":{"kernel":1}
,"initrd":{"loaded":1}
,"loaded":{"cpu-bootloader":1}
,"cpu-bootloader":{"failes":1}
,"failes":{"launch":1}
,"launch":{"kernel":1}
,"control":{"data":1}
,"future":{"recovery":1,"bpmp":1,"boot":1,"redundant":1,"removable":1}
,"takes":{"remaining":1}
,"remaining":{"space":1}
,"except":{"occupied":1,"space":1}
,"occupied":{"secondary_gpt":1}
,"secondary_gpt":{"partition":1,"allocation":1,"type":1,"allocation_policy":1}
,"attribute":{"0x808":1}
,"mounted":{"used":1}
,"used":{"store":1}
,"store":{"user":1}
,"p3668-0001":{"qspi_nor":1,"emmc_user":1}
,"emmc_user":{"partition":1}
,"p3448-0000":{"flashed":1}
,"flashed":{"on-board":1,"micro":1}
,"on-board":{"memory":1}
,"u-boot":{"environment":1,"loads":1}
,"micro":{"card":1}
,"cpu-side":{"binary":1}
,"sc7":{"entry":1}
,"can\u0027t":{"remove":1}
,"fuse":{"bypass":1}
,"bypass":{"removeable":1}
,"tos":{"binary":1}
,"launches":{"kernel":1}
,"p3448-0003":{"flashed":1}
,"p2888":{"p2888-nnnn":1}
,"p2888-nnnn":{"sdmmc_boot":1,"sdmmc_user":1}
,"p3489":{"p3489-nnnn":1}
,"p3489-nnnn":{"sdmmc_boot":1,"sdmmc_user":1}
,"dram-ecc":{"firmware":1}
,"badpage":{"firmware":1}
,"pack":{"firmware":1,"image":1}
,"kkernel":{"dtb":1}
,"efi":{"image":1}
,"nct":{"image":1}
,"mts":{"pre-boot":1,"boot":1}
,"pre-boot":{"image":1}
,"external":{"storage":1,"partition":1,"device":1}
,"create":{"partition":1}
,"start":{"default":1}
,"template":{"example":1}
,"change":{"device":1,"num_sectors":1}
,"number":{"zero":1}
,"zero":{"example":1}
,"least":{"three":1}
,"master_boot_record":{"primary_gpt":1,"type":1}
,"scsi":{"devices":1,"flash":1}
,"e.g":{"scsi":1,"nvme":1}
,"flash":{"drives":1}
,"drives":{"hard":1,"nvme":1}
,"hard":{"disk":1}
,"disk":{"drives":1}
,"ssds":{"device":1}
,"update":{"num_sectors":1}
,"num_sectors":{"correctly":1,"1024209543168":1,"61071360":1}
,"correctly":{"specify":1}
,"specify":{"total":1}
,"total":{"amount":1}
,"amount":{"storage":1}
,"available":{"external":1,"change":1}
,"examples":{"nvme":1}
,"1024209543168":{"bytes":1,"512":1}
,"512":{"2000409264":1,"num_sectors":1,"size":1}
,"2000409264":{"sectors":1}
,"sector_size":{"512":1}
,"61071360":{"partition":1}
,"protective_master_boot_record":{"allocation_policy":1}
,"allocation_policy":{"sequential":1,"filesystem_type":1}
,"file_system_attribute":{"file_system_attribute":1,"allocation_attribute":1}
,"allocation_attribute":{"allocation_attribute":1,"percent_reserved":1}
,"percent_reserved":{"percent_reserved":1,"description":1}
,"mbr":{"description":1}
,"pptsize":{"size":1}
,"parted":{"description":1}
}
;Search.control.loadWordPairs(pairs);
