var pairs =
{
"nvidia":{"hardware":1,"integrates":1,"low-level":1,"nvvideoencoderfactory.h":1}
,"hardware":{"acceleration":1,"accelerated":1,"encoding":1}
,"acceleration":{"webrtc":1,"supports":1}
,"webrtc":{"framework":1,"free":1,"ability":1,"project":1,"encoding":1,"detects":1,":sdpvideoformat&":1,"package":1,"library":1,"header":1}
,"free":{"open":1}
,"open":{"source":1}
,"source":{"project":1,"webrtc":1,"delivers":1}
,"project":{"provides":1,"framework":1,"used":1}
,"provides":{"real-time":1}
,"real-time":{"communication":1}
,"communication":{"capabilities":1}
,"capabilities":{"browsers":1}
,"browsers":{"mobile":1}
,"mobile":{"apps":1}
,"screenshot":{"video":1,"cell":1}
,"video":{"game":1,"encoding":1,"loopback":1,"encoder":1,"formats":1}
,"game":{"description":1}
,"description":{"automatically":1}
,"automatically":{"generated":1,"second":1}
,"major":{"feature":1}
,"feature":{"webrtc":1}
,"ability":{"send":1}
,"send":{"receive":1}
,"receive":{"interactive":1}
,"interactive":{"videos":1}
,"videos":{"fast":1,"requires":1}
,"fast":{"processing":1}
,"processing":{"videos":1,"required":1}
,"requires":{"hardware":1}
,"accelerated":{"video":1,"h.264":1,"webrtc":1}
,"currently":{"open":1,"supports":1,"sdpvideoformat":1,"hardware":1,"done":1}
,"framework":{"supports":1,"document":1,"converts":1,"works":1,"cpu":1}
,"supports":{"various":1,"h.264":1}
,"various":{"software":1}
,"software":{"encoder":1,"jetson":1}
,"encoder":{"types":1,"output":1,"returns":1,"unit":1}
,"types":{"vp8":1}
,"vp8":{"vp9":1}
,"vp9":{"h264":1}
,"h264":{"nvidia":1,"--width":1}
,"integrates":{"hardware":1}
,"h.264":{"encoding":1,"unit":1,"supported":1,"encoder":1}
,"encoding":{"webrtc":1,"framework":1,"libraries":1,"format":1,"currently":1}
,"document":{"uses":1}
,"uses":{"name":1,"\u2011\u2011autocall":1}
,"name":{"nvencoder":1}
,"nvencoder":{"denote":1,"using":1,"returns":1,"sample":1,"enter":1,"based":1,"expects":1}
,"denote":{"feature":1}
,"typical":{"buffer":1}
,"buffer":{"flow":1}
,"following":{"diagram":1}
,"diagram":{"shows":1}
,"shows":{"typical":1}
,"flow":{"hardware":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"delivers":{"yuv":1}
,"yuv":{"frames":1}
,"frames":{"framework":1}
,"converts":{"i420":1}
,"i420":{"format":1,"nv12":1}
,"format":{"queues":1,"hardware":1,"specifies":1,"currently":1,"nvencoder":1,"requiring":1}
,"queues":{"output":1}
,"output":{"plane":1}
,"plane":{"encoder":1,"buffers":1}
,"buffers":{"sent":1,"capture":1,"yuy2":1}
,"sent":{"nvencoder":1,"further":1}
,"using":{"proprietary":1,"webrtc":1}
,"proprietary":{"nvidia":1}
,"low-level":{"encoding":1}
,"libraries":{"nvencoder":1}
,"returns":{"filled":1,"nvvideoencoder":1,"codec":1,"vector":1}
,"filled":{"encoded":1}
,"encoded":{"buffers":1}
,"capture":{"plane":1}
,"further":{"processing":1}
,"required":{"application":1}
,"application":{"unit":1,"usage":1,"run":1,"enter":1,"displays":1,"jetson":1,"test":1,"connects":1,"creates":1}
,"unit":{"test":1}
,"test":{"setup":1,"nvencoder":1,"basic":1,"application":1}
,"readme":{"file":1,"readme":1}
,"file":{"webrtc_r32.2.0_aarch64.tbz2":1,"package":1,"applications":1}
,"webrtc_r32.2.0_aarch64.tbz2":{"package":1,"contains":1}
,"package":{"contains":1,"webrtc_r32.2.0_aarch64.tbz2":1}
,"contains":{"additional":1,"files":1}
,"additional":{"information":1}
,"information":{"application":1}
,"usage":{"setup":1}
,"sample":{"application":1}
,"loopback":{"application":1,"functionality":1}
,"run":{"application":1}
,"enter":{"command":1,"commands":1}
,"video_loopback":{"--codec":1,"application":1,"works":1}
,"--codec":{"h264":1,"specifies":1}
,"--width":{"1280":1,"specifies":1}
,"1280":{"--height":1}
,"--height":{"720":1,"specifies":1}
,"720":{"--capture_device_index":1}
,"specifies":{"encoding":1,"frame":1,"index":1,"desired":1}
,"frame":{"width":1,"height":1,"drops":1}
,"--capture_device_index":{"specifies":1}
,"index":{"dev":1}
,"dev":{"video":1}
,"works":{"correctly":1,"h.264":1}
,"correctly":{"application":1}
,"displays":{"camera":1,"error":1}
,"camera":{"stream":1,"setup":1,"jetson":1,"outputs":1}
,"stream":{"desired":1}
,"desired":{"width":1,"encoding":1}
,"width":{"height":1}
,"height":{"scales":1}
,"scales":{"webrtc":1}
,"detects":{"frame":1}
,"peer":{"connection":1}
,"connection":{"client":1}
,"client":{"server":1,"setup":1,"application":1}
,"server":{"application":1,"setup":1,"port":1,"automatically":1,"without":1,"clients":1,"interface":1}
,"setup":{"connect":1,"start":1}
,"connect":{"usb":1}
,"usb":{"camera":1}
,"jetson":{"device":1,"platform":1}
,"start":{"peerconnection_client":1,"two":1,"pulseaudio":1}
,"peerconnection_client":{"application":1,"--autoconnect":1,"--server":1,"client":1}
,"platform":{"enter":1}
,"command":{"starts":1,"uses":1,"install":1,"start":1}
,"starts":{"server":1,"instance":1}
,"port":{"8888":1}
,"8888":{"default":1}
,"default":{"configuration":1}
,"two":{"instances":1}
,"instances":{"peerconnection_client":1}
,"--autoconnect":{"--server":1,"--autocall":1}
,"--server":{"server.ip":1}
,"server.ip":{"--autoconnect":1}
,"instance":{"connects":1}
,"connects":{"client":1,"server":1}
,"second":{"command":1}
,"\u2011\u2011autocall":{"option":1}
,"option":{"call":1}
,"call":{"first":1}
,"first":{"available":1}
,"available":{"client":1}
,"without":{"user":1}
,"user":{"intervention":1}
,"modules_tests":{"--gtest_filter":1}
,"--gtest_filter":{"testnvh264impl":1}
,"testnvh264impl":{"--gtest_repeat":1}
,"--gtest_repeat":{"num_of_iterations":1}
,"device":{"displays":1}
,"error":{"pulseaudio":1}
,"install":{"pulseaudio":1}
,"sudo":{"apt":1}
,"apt":{"install":1}
,"pulseaudio":{"daemon":1,"start":1}
,"important":{"method":1,"calls":1}
,"method":{"calls":1,"call":1,"creates":1,"returns":1}
,"based":{"nvvideoencoderfactory":1}
,"nvvideoencoderfactory":{"class":1}
,"class":{"defined":1}
,"defined":{"header":1}
,"header":{"file":1,"files":1}
,"webrtc_headers":{"modules":1}
,"modules":{"video_coding":1}
,"video_coding":{"codecs":1}
,"codecs":{"nvidia":1}
,"section":{"summarizes":1}
,"summarizes":{"important":1}
,"calls":{"nvencoder":1}
,"create":{"hardware-enabled":1}
,"hardware-enabled":{"video":1}
,"execute":{"method":1,"function":1}
,"std":{":unique_ptr":1,":vector":1}
,":unique_ptr":{"videoencoder":1}
,"videoencoder":{"createvideoencoder":1}
,"createvideoencoder":{"const":1}
,"const":{"webrtc":1,"sdpvideoformat&":1}
,":sdpvideoformat&":{"format":1}
,"sdpvideoformat":{"h.264":1,"getsupportedformats":1,"objects":1}
,"creates":{"returns":1,"server":1}
,"nvvideoencoder":{"object":1}
,"object":{"specified":1}
,"specified":{"format":1}
,"query":{"video":1}
,"function":{"call":1,"queries":1}
,"codecinfo":{"queryvideoencoder":1}
,"queryvideoencoder":{"const":1}
,"sdpvideoformat&":{"format":1}
,"queries":{"video":1}
,"codec":{"information":1}
,"supported":{"video":1,"encoder":1}
,":vector":{"sdpvideoformat":1}
,"vector":{"sdpvideoformat":1}
,"objects":{"formats":1}
,"formats":{"supported":1}
,"libwebrtc.a":{"webrtc":1}
,"library":{"file":1,"8f22a28e30b05a4716091f6425d34e537cddcb86":1}
,"files":{"webrtc":1,"respective":1}
,"respective":{"pathnames":1}
,"basic":{"video":1}
,"peerconnection_server":{"application":1}
,"interface":{"clients":1}
,"module_test":{"encoder":1}
,"applications":{"nvvideoencoderfactory":1}
,"base":{"commit":1}
,"commit":{"library":1,"corresponds":1}
,"corresponds":{"oss":1}
,"oss":{"webrtc":1}
,"used":{"development":1}
,"development":{"link":1}
,"link":{"instructions":1}
,"instructions":{"sync":1}
,"sync":{"oss":1}
,"outputs":{"buffers":1}
,"yuy2":{"color":1}
,"color":{"format":1,"conversion":1}
,"expects":{"input":1}
,"input":{"i420":1}
,"nv12":{"format":1}
,"requiring":{"color":1}
,"conversion":{"currently":1}
,"done":{"using":1}
}
;Search.control.loadWordPairs(pairs);
