var pairs =
{
"jetson":{"tx2":1,"linux":1}
,"tx2":{"series":1}
,"series":{"software":1,"devices":1}
,"software":{"features":1,"hardware":1}
,"nvidia":{"jetson":1,"tegra":1,"libglvnd":1,"gmsl":1}
,"linux":{"driver":1,"targeted":1,"kernel":1}
,"driver":{"package":1,"suspend":1,"release":1,"code":1}
,"package":{"l4t":1,"bring":1}
,"l4t":{"supports":1}
,"supports":{"software":1,"egl":1,"following":1,"uvc":1,"pcm":1,"sample":1,"two":1,"stereo":1,"interfaces":1,"interface":1,"audio":1,"normal":1,"interfacs":1,"four":1,"eight":1,"sampling":1,"gain":1,"mixing":1,"outputs":1,"amixer":1}
,"features":{"provide":1,"eqos":1,"include":1,"following":1,"nvgstcapture-1.0":1}
,"provide":{"users":1}
,"users":{"complete":1}
,"complete":{"package":1}
,"bring":{"linux":1}
,"targeted":{"nvidia":1}
,"check":{"release":1}
,"release":{"notes":1,"1.1.73":1,"https":1,"supports":1}
,"notes":{"constraints":1,"instructions":1}
,"constraints":{"related":1}
,"related":{"features":1,"documentation":1}
,"execution":{"cpu":1}
,"storage":{"location":1,"device":1}
,"cold":{"boot":1}
,"boot":{"emmc":1,"downloaded":1,"atf":1}
,"rcm":{"boot":1}
,"downloaded":{"usb":1}
,"usb":{"recovery":1,"usb1":1,"3.0":1,"2.0":1,"video":1,"camera":1,"audio":1,"dac":1}
,"recovery":{"port":1}
,"next":{"stage":1}
,"stage":{"storage":1}
,"device":{"support":1,"life":1,"power":1,"mode":1,"port":1,"elpg":1}
,"partition":{"table":1}
,"table":{"support":1}
,"gpt":{"protective":1}
,"protective":{"mbr":1}
,"filesystem":{"support":1}
,"bus":{"support":1,"clear":1,"speed":1}
,"console":{"uart":1}
,"u-boot":{"linux":1}
,"i2c":{"gpio":1}
,"gpio":{"spi":1,"pcie":1,"expansion":1,"support":1}
,"spi":{"qspi":1,"miso":1,"transfer":1}
,"emmc":{"card":1,"200":1}
,"mbr":{"dos":1}
,"dos":{"mbr":1}
,"ext2":{"fat":1}
,"pcie":{"spi":1,"link":1}
,"tool":{"chains":1}
,"64-bit":{"kernel":1}
,"kernel":{"userspace":1,"interfaces":1}
,"userspace":{"u-boot":1}
,"version":{"4.9.140":1,"10.0.166":1,"egl":1,"release":1}
,"debug":{"interface":1,"115200":1}
,"jtag":{"attach":1,"halt":1}
,"debugging":{"capability":1}
,"halt":{"step":1}
,"camera":{"interface":1,"support":1,"gpio":1,"features":1,"functionality":1,"app":1,"development":1,"stack":1,"framework":1,"preview":1,"uvc":1,"supported":1}
,"csi":{"input":1,"usb":1,"sensor":1,"port":1}
,"input":{"support":1,"formats":1,"stream":1,"streams":1}
,"v4l2":{"media":1,"api":1}
,"media":{"controller":1}
,"api":{"bypasses":1,"support":1,"registry":1}
,"bypasses":{"isp":1}
,"csi0":{"csi1":1}
,"csi1":{"csi2":1}
,"csi2":{"csi3":1}
,"csi3":{"csi4":1}
,"csi4":{"csi5":1}
,"cameras":{"supported":1,"1920":1}
,"maximum":{"resolution":1,"bus":1}
,"resolution":{"frame":1,"six":1}
,"frame":{"rate":1,"support":1}
,"rate":{"cameras":1,"frame":1}
,"1920":{"1080":1,"1440":1}
,"1080":{"frames":1,"240":1}
,"frames":{"sec":1,"second":1}
,"dsi":{"display":1,"ganged":1}
,"display":{"support":1,"outputs":1}
,"ganged":{"mode":1}
,"pwm":{"backlight":1,"operations":1,"registration":1}
,"continuous":{"mode":1}
,"dual":{"display":1,"spi":1}
,"run":{"time":1}
,"time":{"power":1}
,"power":{"management":1,"mode":1,"notification":1,"efficiency":1,"consumption":1}
,"edid":{"support":1}
,"hot-plug":{"detection":1,"using":1}
,"detection":{"mechanism":1}
,"support":{"hdmi":1,"edp":1,"l0s":1,"l1.1":1,"default":1,"9018":1,"gnome-wayland":1,"gstreamer":1,"case":1,"validated":1,"dol":1,"hdr":1,"u\u2011law":1}
,"hdmi":{"1.4":1,"primary":1,"1.4b":1,"2.0":1,"interfaces":1}
,"1.4":{"480p":1}
,"480p":{"720p":1}
,"720p":{"1080p":1}
,"1080p":{"rgb":1}
,"rgb":{"444":1}
,"suspend":{"resume":1,"support":1}
,"resume":{"low":1,"nfs":1}
,"low":{"power":1,"light":1}
,"primary":{"display":1,"volume":1}
,"multi":{"display":1}
,"1.4b":{"compliance":1}
,"2.0":{"compliance":1,"support":1}
,"audio":{"support":1,"playback":1,"demultiplexer":1,"demultiplexing":1,"multiplexer":1,"multiplexing":1,"streams":1,"mixer":1}
,"edp":{"primary":1}
,"wake":{"support":1,"idle":1,"sleep":1}
,"registration":{"framework":1}
,"prod":{"setting":1}
,"jetson-specific":{"controller":1}
,"controller":{"configuration":1,"features":1}
,"clock":{"accuracy":1,"calculation":1,"power":1,"speed":1}
,"accuracy":{"calculation":1}
,"dma":{"mode":1}
,"clear":{"support":1}
,"multi-master":{"support":1}
,"normal":{"byte":1,"stereo":1}
,"byte":{"mode":1,"first":1}
,"general":{"support":1}
,"physical":{"port":1}
,"port":{"pci-e":1,"cpi-e":1,"spi1":1,"spi2":1,"spi":1,"multiplier":1,"transition":1,"details":1}
,"speed":{"gen1":1,"mhz":1,"mode":1}
,"gen1":{"gen2":1}
,"gen2":{"lane":1}
,"lane":{"width":1,"muxing":1}
,"host":{"controller":1,"auto":1,"mode":1,"port":1,"elpg":1}
,"lanes":{"xbar":1}
,"xbar":{"config":1}
,"config":{"x4_x0_x1":1}
,"x4_x0_x1":{"x2_x1_x1":1}
,"x2_x1_x1":{"x1_x1_x1":1}
,"using":{"gpio":1,"khronos":1,"libargus":1,"csi":1,"pwl":1}
,"pci":{"features":1}
,"message":{"signaled":1}
,"signaled":{"interrupts":1}
,"link":{"capabilities":1,"power":1}
,"aspm":{"support":1}
,"l1.1":{"l1.2":1}
,"root":{"control":1}
,"pme":{"interrupt":1}
,"interrupt":{"enable":1}
,"extended":{"capabilities":1}
,"advanced":{"error":1}
,"error":{"reporting":1}
,"reporting":{"aer":1,"technology":1}
,"miscellaneous":{"features":1}
,"dynamic":{"voltage":1}
,"voltage":{"frequency":1,"switching":1}
,"frequency":{"dvfs":1,"tuning":1,"bit":1,"converter":1,"conversion":1}
,"tegra":{"low":1,"watchdog":1}
,"mode":{"lp0":1,"support":1,"change":1,"ljm":1,"rjm":1}
,"rest":{"capabilities":1}
,"supported":{"tx2i":1,"modes":1,"vlan":1,"getting":1,"features":1}
,"bluetooth":{"4.0":1,"3000000":1}
,"ble":{"4.0":1}
,"bcm4354":{"bluez":1}
,"bluez":{"limitation":1}
,"peripheral":{"devices":1}
,"ina":{"support":1}
,"current":{"monitoring":1}
,"monitoring":{"cpu":1}
,"cpu":{"gpu":1,"hotplug":1,"load":1}
,"gpu":{"vdd_in":1}
,"platform":{"support":1,"window":1,"graphics":1}
,"p3310-b00":{"c03":1}
,"multi-region":{"support":1}
,"region":{"support":1}
,"default":{"lowest-common-denominator":1,"reference":1}
,"dual-band":{"2.4":1}
,"2.4":{"ghz":1}
,"ghz":{"ghz":1}
,"bcm":{"4354":1}
,"sta":{"mode":1}
,"ibss":{"mode":1}
,"wpa2":{"security":1}
,"packed":{"unpacked":1,"commands":1}
,"full":{"duplex":1}
,"duplex":{"mode":1}
,"enable":{"bit":1,"byte":1,"gnome-wayland":1,"tnr.v1":1,"tnr.v2":1}
,"least":{"significant":1}
,"significant":{"bit":1,"byte":1}
,"hardware":{"chip":1,"flow":1,"vlan":1}
,"chip":{"select":1}
,"select":{"polarity":1,"option":1}
,"polarity":{"section":1}
,"miso":{"mosi":1}
,"mosi":{"act":1}
,"multiple":{"transfer":1,"spi":1}
,"transfer":{"request":1}
,"request":{"single":1}
,"single":{"call":1}
,"speeds":{"clock":1}
,"sdmmc1":{"card":1}
,"card":{"204":1,"sdmmc4":1}
,"204":{"mhz":1}
,"sdmmc4":{"emmc":1}
,"200":{"mhz":1}
,"hot":{"plug":1}
,"plug":{"support":1}
,"high":{"speed":1,"power":1}
,"ddr":{"mode":1}
,"cache":{"control":1}
,"field":{"firmware":1}
,"firmware":{"upgrade":1}
,"life":{"estimation":1}
,"estimation":{"type":1}
,"pre":{"eol":1}
,"eol":{"information":1}
,"ahci":{"mode":1}
,"sata":{"specification":1}
,"multiplier":{"support":1}
,"management":{"states":1,"surface":1}
,"runtime":{"time":1}
,"self-monitoring":{"analysis":1}
,"analysis":{"reporting":1}
,"dev":{"sleep":1}
,"sleep":{"support":1}
,"usb0":{"480":1,"micro":1}
,"480":{"mbps":1}
,"mbps":{"usb1":1,"support":1}
,"usb1":{"gps":1,"lane":1,"type":1}
,"muxing":{"sharing":1}
,"sharing":{"pcie":1}
,"3.0":{"support":1}
,"micro":{"usb1":1}
,"remote":{"wakeup":1}
,"wakeup":{"support":1,"sc7":1}
,"auto":{"suspend":1}
,"xotg":{"support":1}
,"xusb":{"host":1,"device":1}
,"class":{"support":1}
,"mass":{"storage":1}
,"video":{"class":1,"decoders":1,"decode":1,"encoders":1,"encode":1,"format":1,"scaling":1,"cropping":1,"rotation":1}
,"thumb":{"hard":1}
,"hard":{"drive":1}
,"cdc":{"ncm":1}
,"ncm":{"ecm":1}
,"uart":{"controllers":1}
,"uart0":{"debug":1}
,"uart1":{"camera":1}
,"expansion":{"header":1}
,"header":{"used":1}
,"uart2":{"connector":1}
,"connector":{"921600":1}
,"uart3":{"bluetooth":1}
,"flow":{"control":1}
,"control":{"debug":1,"pause":1,"mvc":1}
,"pio":{"mode":1}
,"fifo":{"mode":1}
,"lp_iddq":{"mode":1}
,"nfs":{"support":1,"boot":1}
,"ethernet":{"controller":1}
,"change":{"ethtool":1}
,"100":{"mbps":1}
,"1000":{"mbps":1}
,"half-duplex":{"support":1}
,"arp":{"offload":1}
,"ieee":{"1588-2008":1}
,"1588-2008":{"ptp":1}
,"energy-efficient":{"ethernet":1}
,"transmit":{"checksum":1}
,"checksum":{"offload":1}
,"receive":{"checksum":1}
,"tcp":{"segmentation":1}
,"segmentation":{"offload":1}
,"jumbo":{"frame":1}
,"9018":{"untagged":1}
,"untagged":{"9022":1}
,"9022":{"tagged":1}
,"pause":{"frame":1}
,"eavb":{"support":1}
,"queue":{"channels":1}
,"channels":{"size":1,"i2s":1,"output":1,"eight\u2011port":1,"supports":1}
,"vlan":{"insertion":1,"tag":1,"tag-based":1}
,"insertion":{"stripping":1}
,"stripping":{"vlan":1}
,"tag":{"hardware":1}
,"tag-based":{"filtering":1}
,"filtering":{"supported":1}
,"max-q":{"max-p":1}
,"watchdog":{"reboot":1,"kick":1}
,"reboot":{"hang":1,"support":1}
,"pmic":{"watchdog":1}
,"system":{"programable":1,"boot":1,"handles":1}
,"programable":{"gpio":1,"pinmux":1}
,"pinmux":{"supportwakeable":1}
,"supportwakeable":{"gpio":1}
,"timestamping":{"gpio":1}
,"ucm2":{"24x7":1}
,"shutdown":{"support":1}
,"emc":{"scaling":1}
,"initrd":{"support":1}
,"load":{"behavior":1}
,"atf":{"secure":1}
,"secure":{"monitor":1}
,"graphics":{"apis":1,"context":1,"interface":1}
,"glvnd":{"version":1}
,"vendor":{"neutral":1}
,"neutral":{"dispatch":1}
,"dispatch":{"library":1}
,"nvdc":{"direct":1}
,"direct":{"rendering":1}
,"rendering":{"manager":1,"apis":1,"synchronization":1,"using":1}
,"manager":{"drm":1}
,"compatibility":{"drm":1}
,"drm":{"2.0":1}
,"egl":{"stream":1,"egl":1,"without":1,"opengl":1,"interface":1,"enables":1,"1.5":1}
,"x11":{"abi-20":1,"window":1}
,"without":{"x11":1}
,"extensions":{"supported":1}
,"getting":{"components":1}
,"components":{"work":1}
,"vulkan":{"loader":1,"details":1}
,"loader":{"version":1}
,"1.1.73":{"verified":1}
,"verified":{"working":1}
,"working":{"properly":1}
,"properly":{"release":1}
,"https":{"developer.nvidia.com":1,"github.com":1,"www.sony-semicon.co.jp":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"vulkan":1}
,"github.com":{"nvidia":1}
,"libglvnd":{"details":1}
,"details":{"glvnd":1,"example":1,"h.264":1,"argus":1,"citation":1}
,"experimental":{"support":1}
,"gnome-wayland":{"desktop":1,"support":1}
,"desktop":{"shell":1}
,"shell":{"release":1}
,"instructions":{"enable":1}
,"opengl":{"support":1,"underlying":1,"driver":1,"specifications":1,"common":1,"4.5":1,"khronos":1,"api":1}
,"interface":{"khronos":1,"egl":1,"dspk2":1,"configured":1}
,"khronos":{"rendering":1,"apis":1,"native":1,"opengl":1}
,"apis":{"opengl":1,"topic":1}
,"underlying":{"native":1}
,"native":{"platform":1}
,"window":{"system":1}
,"handles":{"graphics":1}
,"context":{"management":1}
,"surface":{"buffer":1}
,"buffer":{"binding":1}
,"binding":{"rendering":1}
,"synchronization":{"egl":1}
,"enables":{"high-performance":1}
,"high-performance":{"accelerated":1}
,"accelerated":{"mixed-mode":1,"gstreamer":1}
,"mixed-mode":{"rendering":1}
,"1.5":{"specification":1}
,"specification":{"khronos":1,"2.0":1}
,"following":{"opengl":1,"sections":1}
,"common":{"profile":1}
,"profile":{"specification":1}
,"information":{"opengl":1,"supported":1,"dol":1,"csi":1}
,"output":{"formats":1,"streams":1,"stream":1}
,"sampling":{"frequency":1}
,"bit":{"rate":1}
,"nv12":{"nvmm:nv12":1,"nvmm:1420":1,"nvmm:i420":1}
,"3840":{"2160":1}
,"2160":{"fps":1}
,"fps":{"120":1}
,"120":{"mbps":1}
,"full-frame":{"disable-dpb":1}
,"disable-dpb":{"skip-frames":1}
,"skip-frames":{"enable-error-check":1}
,"enable-error-check":{"enable-frame-type-reporting":1}
,"nvmm:nv12":{"nvmm:i420_10le":1}
,"160":{"mbps":1}
,"decode":{"support":1}
,"gstreamer":{"1.4.5":1,"user":1}
,"1.4.5":{"later":1}
,"i420":{"nvmm:i420":1,"nv12":1}
,"600":{"sec":1}
,"140":{"mbps":1}
,"240":{"fps":1}
,"nvmm:1420":{"nvmm:nv12":1}
,"nvmm:i420":{"nvmm:nv12":1}
,"gst-inspect-1.0":{"utility":1,"omxh264enc":1,"nvv4l2h264enc":1}
,"utility":{"understand":1}
,"understand":{"feature":1}
,"feature":{"details":1}
,"example":{"gst-inspect-1.0":1}
,"omxh264enc":{"command":1}
,"command":{"gst-inspect-1.0":1,"provides":1}
,"nvv4l2h264enc":{"command":1}
,"provides":{"feature":1}
,"h.264":{"encoder":1}
,"panel":{"overlay":1}
,"conversion":{"scaling":1,"gstreamer-1.0":1,"pcm":1}
,"scaling":{"cropping":1,"gstreamer-1.0":1}
,"cropping":{"rotation":1,"gstreamer-1.0":1}
,"rotation":{"formats":1,"gstreamer-1.0":1}
,"flip-method":{"interpolation-method":1}
,"interpolation-method":{"crop":1}
,"crop":{"format":1}
,"format":{"conversion":1}
,"additional":{"information":1}
,"sections":{"topic":1}
,"topic":{"accelerated":1,"camera":1}
,"basic":{"camera":1}
,"reference":{"sensor":1,"driver":1,"section":1}
,"sensor":{"ov5693":1,"stops":1,"resumes":1}
,"ov5693":{"demonstrated":1,"sensors":1}
,"demonstrated":{"argus":1}
,"argus":{"camera":1,"refer":1}
,"app":{"details":1}
,"refer":{"applications":1}
,"applications":{"using":1}
,"libargus":{"low-level":1}
,"low-level":{"apis":1}
,"infinite":{"timeout":1}
,"case":{"csi":1}
,"stops":{"streaming":1}
,"streaming":{"indefinitely":1,"camera":1}
,"indefinitely":{"camera":1}
,"stack":{"idle":1,"resumes":1}
,"idle":{"csi":1}
,"resumes":{"streaming":1,"working":1}
,"gmsl":{"camera":1}
,"validated":{"two":1,"sony":1}
,"two":{"simultaneous":1,"types":1,"output":1,"channels":1,"mvc":1}
,"simultaneous":{"imx390":1}
,"imx390":{"sensors":1,"included":1}
,"sensors":{"using":1,"validated":1,"https":1,"running":1}
,"citation":{"nvidia":1}
,"framework":{"related":1}
,"documentation":{"official":1}
,"official":{"reference":1}
,"code":{"imx390":1}
,"included":{"release":1}
,"dol":{"wdr":1,"sensors":1}
,"sony":{"imx274":1,"imx185":1}
,"imx274":{"information":1}
,"www.sony-semicon.co.jp":{"products_en":1}
,"products_en":{"sensor2":1}
,"sensor2":{"technology":1}
,"technology":{"dol-hdr.html":1,"validated":1}
,"pwl":{"wdr":1}
,"hdr":{"using":1}
,"wdr":{"technology":1}
,"tnr":{"support":1}
,"option":{"switch":1,"enable":1,"reference":1}
,"switch":{"two":1}
,"types":{"noise":1}
,"noise":{"reduction":1}
,"vic-based":{"temporal":1}
,"temporal":{"noise":1}
,"reduction":{"compromises":1,"improves":1}
,"compromises":{"image":1}
,"image":{"quality":1}
,"quality":{"due":1,"cost":1}
,"due":{"low":1}
,"consumption":{"select":1,"especially":1}
,"tnr.v1":{"camera_overrides.isp":1}
,"gpu-based":{"temporal":1}
,"improves":{"image":1}
,"cost":{"high":1}
,"especially":{"effective":1}
,"effective":{"low":1}
,"light":{"scenes":1}
,"scenes":{"select":1}
,"tnr.v2":{"camera_overrides.isp":1}
,"six":{"camera":1,"ov5693":1}
,"preview":{"fps":1,"performance":1}
,"performance":{"frames":1}
,"second":{"1920":1}
,"1440":{"resolution":1}
,"running":{"simultaneously":1}
,"uvc":{"compliant":1}
,"compliant":{"usb2.0":1}
,"usb2.0":{"usb3.0":1}
,"usb3.0":{"cameras":1}
,"nvgstcapture-1.0":{"option":1}
,"section":{"accelerated":1}
,"user":{"guide":1}
,"hda":{"hdmi":1}
,"pcm":{"playback":1,"audio":1}
,"playback":{"stereo":1,"capture":1}
,"stereo":{"5.1":1,"capture":1,"playback":1,"i2s":1,"pcm":1}
,"5.1":{"7.1":1}
,"7.1":{"channel":1}
,"channel":{"configurations":1}
,"sample":{"sizes":1,"rates":1}
,"sizes":{"bits":1,"sample":1}
,"bits":{"s16_le":1,"s32_le":1,"sample":1,"s24_le":1,"bits":1}
,"s16_le":{"bits":1}
,"s32_le":{"sizes":1,"osr":1,"sample":1}
,"rates":{"44.1":1,"11.025":1,"11.025,16":1}
,"44.1":{"88.2":1,"khz":1,"192":1}
,"88.2":{"khz":1,"176.4":1,"192":1}
,"khz":{"displayport":1,"hdmi":1,"supports":1}
,"displayport":{"interfaces":1}
,"interfaces":{"44.1":1,"dmic1":1}
,"176.4":{"192":1}
,"192":{"khz":1}
,"note":{"24-bit":1}
,"24-bit":{"samples":1}
,"samples":{"stored":1}
,"stored":{"32-bit":1}
,"32-bit":{"data":1}
,"data":{"data":1,"upper":1}
,"upper":{"bits":1}
,"dmic":{"support":1}
,"s24_le":{"bits":1,"sample":1}
,"osr":{"128":1}
,"128":{"256":1}
,"256":{"sample":1}
,"dmic1":{"dmic22":1}
,"dmic22":{"dmic3":1}
,"dspk":{"support":1}
,"i2s":{"support":1,"left":1,"interface":1}
,"capture":{"loopback":1}
,"11.025":{"22.05":1,"22.5":1}
,"22.05":{"44.1":1}
,"left":{"justified":1}
,"justified":{"mode":1}
,"ljm":{"right":1}
,"right":{"justified":1}
,"rjm":{"tdm":1}
,"tdm":{"modes":1}
,"modes":{"dsp":1}
,"dsp":{"dsp":1,"channels":1}
,"configured":{"master":1}
,"master":{"slave":1}
,"slave":{"support":1}
,"u\u2011law":{"a\u2011law":1}
,"a\u2011law":{"compression":1}
,"compression":{"decompression":1}
,"interfacs":{"i2s1":1}
,"i2s1":{"i2s2":1}
,"i2s2":{"i2s3":1}
,"i2s3":{"i2s4":1}
,"i2s4":{"i2s5":1}
,"i2s5":{"i2s6":1}
,"demultiplexer":{"adx":1}
,"demultiplexing":{"input":1}
,"stream":{"channels":1}
,"streams":{"channels":1,"two":1,"supports":1}
,"22.5":{"44.1":1}
,"four":{"adx":1,"amx":1,"sfc":1}
,"adx":{"instances":1}
,"instances":{"adx1":1,"amx1":1,"sfc1":1,"mvc1":1}
,"adx1":{"adx2":1}
,"adx2":{"adx3":1}
,"adx3":{"adx4":1}
,"multiplexer":{"amx":1}
,"multiplexing":{"input":1}
,"amx":{"instances":1}
,"amx1":{"amx2":1}
,"amx2":{"amx3":1}
,"amx3":{"amx4":1}
,"eight":{"channels":1,"stream":1}
,"eight\u2011port":{"usb":1}
,"converter":{"sfc":1}
,"sfc":{"instances":1}
,"sfc1":{"sfc2":1}
,"sfc2":{"sfc3":1}
,"sfc3":{"sfc4":1}
,"volume":{"control":1}
,"gain":{"attenuation":1}
,"attenuation":{"range":1}
,"range":{"120db":1}
,"120db":{"40db":1}
,"mvc":{"instances":1}
,"mvc1":{"mvc2":1}
,"mixing":{"input":1}
,"outputs":{"contain":1}
,"contain":{"combination":1}
,"combination":{"input":1}
,"11.025,16":{"22.05":1}
,"amixer":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
