var pairs =
{
"flashing":{"booting":1,"flash":1,"generally":1,"initrd":1,"tools":1,"procedures":1,"target":1,"board":1,"usb":1,"emmc":1,"device":1,"external":1,"nvme":1,"card":1,"utilizing":1,"tool":1,"specific":1,"whole":1,"nfs":1,"internal":1,"individual":1,"fused":1,"massflash":1,"combined":1,"process":1,"capability":1,"multiple":1,"jetson":1,"network":1,"assumptions":1,"finds":1}
,"booting":{"target":1,"option":1,"related":1,"explained":1,"using":1,"following":1,"nvme":1}
,"target":{"device":1,"devices":1,"board":1,"device\u0027s":1,"boot":1,"start":1,"automatically":1,"nfs":1,"system":1}
,"flash.sh":{"helper":1,"section":1,"using":1,"script":1,"options":1,"gets":1,"board":1,"app":1,"creates":1,"ip_addr":1,"command":1,"usage":1,"two":1,"--no-flash":1,"flash":1,"partition_name":1,"chooses":1,"dtb":1,"kernel":1,"mb1_bct":1,"cpu-bootloader":1,"change":1,"size":1,"course":1}
,"helper":{"script":1}
,"script":{"flash":1,"l4t_initrd_flash.sh":1,"uses":1,"usage":1,"included":1,"top-level":1,"supplied":1,"creates":1,"automatically":1,"saves":1,"supports":1,"l4t_create_images_for_kernel_flash.sh":1,"run":1,"enter":1,"l4t_create_default_user.sh":1,"generates":1,"prompts":1}
,"flash":{"board":1,"root":1,"internal":1,"external":1,"script":1,"local":1,"target":1,"enter":1,"image":1,"board\u2019s":1,"partition":1,"application":1,"applications":1,"server":1,"drive":1,"initrd":1,"drive\u2019s":1,"device":1,"write":1,"specific":1,"whole":1,"jetson":1,"kernel":1,"mb1":1,"cpu":1,"network":1,"requires":1,"package":1,"images_to_flash":1,"location":1,"larger":1,"default":1,"system.img":1,"sd-blob.img":1,"images":1,"option":1,"first-time":1}
,"board":{"bootloader":1,"rootdev":1,"specifies":1,".conf":1,"hold":1,"e.g":1,"mmcblk0p1":1,"internal":1,"external":1,"already":1,"flashed":1,"eth0":1,"configuration":1,"script":1,"sda1":1,"nvme0n1p1":1,"revision":1,"specified":1,"press":1,"target":1,"l4t_flash_from_kernel.sh":1,"board":1,"name":1,"verify":1}
,"bootloader":{"kernel":1,"bootloader":1,"plus":1,"l4t-rootfs-uuid.txt":1,"l4t-rootfs-uuid.txt_ext":1,"system.img":1,"directory":1,"tegraflash.py":1,"cboot.bin":1,"update":1,"system.img.raw":1,"jetson":1,"filesystem":1}
,"kernel":{"optionally":1,"flashing":1,"kernel":1,"image":1,"modules":1,"command":1,"kernel-dtb":1,"file":1,"change":1,"dtb":1,"jetson":1,"jetson-xavier":1,"option":1,"partition":1,"boot":1,"launch":1,"tftp":1}
,"optionally":{"flash":1}
,"root":{"file":1,"filesystem":1,"linux":1,"address":1,"partition":1,"used":1,"represents":1,"jetson-disk-image-creator.sh":1,"account":1}
,"file":{"system":1,"named":1,"bootloader":1,"executing":1,"used":1,"containing":1,"kernel-4.9":1,"default":1,"zimage":1,"mts_si":1,"boot":1,"saved":1,"create":1,"manually":1,"executable":1,"created":1,"booted":1,"readme_initrd_flash.txt":1,"omitted":1,"l4t":1,"user_path":1,"readme_nfs_flash.txt":1,"linux_for_tegra":1,"pxelinux.cfg":1,"name":1,"missing":1,"directory":1,"different":1,"producing":1,"host":1,"nv-oem-config":1,"backup.img.raw":1,"oem-config":1,"file":1,"line":1,"first":1,"press":1,"select":1,"screen":1,"plan":1,"may":1,"enter":1}
,"system":{"internal":1,"download":1,"located":1,"execute":1,"topic":1,"system":1,"card":1,"nfs":1,"root":1,"ip_addr":1,"nv-oem-config.target":1,"boots":1,"clock":1,"expects":1,"selections":1,"run":1}
,"internal":{"external":1,"media":1,"storage":1,"rootdev":1,"emmc":1,"memory":1}
,"external":{"storage":1,"media":1,"internal":1,"stage":1,"usb":1,"nvme":1,"card":1,"device":1,"partition":1}
,"storage":{"device":1,"class":1,"devices":1,"during":1}
,"l4t_initrd_flash.sh":{"flash":1,"board-name":1}
,"media":{"connected":1,"procedure":1,"external":1}
,"connected":{"jetson":1,"recovery":1,"select":1}
,"jetson":{"device":1,"xavier":1,"agx":1,"tx2":1,"nano":1,"tx1":1,"details":1,"developer":1,"modules":1,"module":1,"device\u2019s":1,"devices":1,"platform":1,"linux":1,"ram":1}
,"device":{"script":1,"flashed":1,"names":1,"emmc":1,"reset":1,"described":1,"root":1,"mount":1,"e.g":1,"enter":1,"flash":1,"specified":1,"tree":1,"mass":1,"booted.you":1,"cannot":1,"boot":1,"name":1,"host":1,"assign":1,"power":1,"secureboot":1,"attached":1,"hot-plugging":1,"booted":1,"details":1,"card":1,"allows":1,"overview":1,"create":1,"partition":1,"number":1,"change":1,"using":1,"copy":1,"network":1,"recovery":1,"procedure":1,"mode":1,"during":1,"table":1,"rcm-boot":1,"example":1,"rcm":1,"pxe":1,"oem-config":1,"equipped":1,"without":1,"runs":1,"manually":1,"disables":1,"type":1,"necessary":1,"enable":1,"mounted":1,"remove":1,"target":1,"usb":1,"supports":1,"boots":1,"artificial":1}
,"uses":{"recovery":1,"kernel":1,"initrd":1,"networkmanager":1,"usb":1,"flash.sh":1,"hostmane":1}
,"recovery":{"initial":1,"port":1,"mode":1,"button":1,"usb":1}
,"initial":{"ramdisk":1,"ram":1,"setup":1}
,"ramdisk":{"flashing":1}
,"procedure":{"script":1,"uses":1,"rcm":1,"reconfigure":1,"alternative":1,"modify":1}
,"generally":{"faster":1}
,"faster":{"flash.sh":1,"compact":1}
,"section":{"flashing":1,"describes":1,"step":1,"configuring":1,"complements":1,"flash":1,"signing":1,"nvme":1,"prepare":1,"external":1,"default":1,"create":1,"jetson":1,"reconfigure":1}
,"initrd":{"details":1,"file":1,"binary":1,"flash":1,"flashing":1,"initial":1,"usb":1,"may":1,"instead":1,"tmp":1,"cpio":1,"content":1,"customized":1,"boot":1}
,"following":{"directories":1,"commands":1,"steps":1,"things":1,"command":1,"dependencies":1,"sections":1,"packages":1,"procedure":1}
,"directories":{"present":1}
,"plus":{"flashing":1,"primary":1}
,"tools":{"tegraflash":1,"instructions":1,"kernel_flash":1,"detailed":1}
,"tegraflash":{"cfg":1}
,"cfg":{"bct":1}
,"image":{"vmlinux.uimg":1,"smaller":1,"named":1,"target":1,"app":1,"specified":1,"file":1,"signed":1,"card":1,"flashed":1,"name":1,"partitions":1,"blob":1,"u\u2011boot":1,"root":1,"using":1,"either":1,"custom-built":1,"directly":1,"boot":1,"tftpboot":1,"modified":1}
,"vmlinux.uimg":{"dtb":1}
,"dtb":{"files":1,"jetson":1,"tegra210-p3448-0003-p3542-0000.dtb":1,"jetson-nano-2gb-devkit":1,"server_args":1,"tegra210-p3448-0002-p3449-0000-b00.dtb":1}
,"files":{"kernel":1,"boot":1,"topic":1,"pxe":1,"included":1,"listed":1}
,"rootfs":{"root":1,"specified":1,"directory":1,"bytes":1,"without":1,"thus":1,"external":1,"partition":1}
,"directory":{"starts":1,"release":1,"sparsed":1,"enter":1,"default":1,"linux_for_tegra":1,"card":1,"network":1,"tools":1}
,"starts":{"empty":1}
,"empty":{"populate":1,"enter":1}
,"populate":{"sample":1}
,"sample":{"file":1,"applications":1,"rootfs":1}
,"nv_tegra":{"user":1}
,"user":{"space":1,"key":1,"account":1,"defined":1,"thus":1,"pswd":1,"specified":1,"named":1,"automatically":1,"log":1}
,"space":{"binaries":1}
,"binaries":{"sample":1,"image":1,"partition":1}
,"additionally":{"running":1}
,"running":{"commands":1,"flash.sh":1,"once":1}
,"commands":{"usb":1,"generate":1,"change":1,"host":1,"run":1}
,"usb":{"cable":1,"device":1,"instance":1,"port":1,"drive":1,"nvme":1,"mass":1,"drives":1,"connector":1,"ttl":1}
,"cable":{"connected":1,"low-quality":1,"may":1}
,"basic":{"flash":1,"usage":1,"flashing":1,"procedures":1}
,"locate":{"up-to-date":1,"appropriate":1}
,"up-to-date":{"usage":1}
,"usage":{"information":1,"follows":1,"providing":1}
,"information":{"running":1,"flash.sh":1,"section":1,"flashing":1,"readme_initrd_flash.txt":1,"file":1,"l4t_flash_from_kernel.sh":1,"topic":1}
,"using":{"flash.sh":1,"flash":1,"etcher":1,"command":1,"default":1,"predefined":1,"user-specified":1,"kernel":1,"tools":1,"tool":1,"following":1,"mount":1,"minicom":1,"operating":1,"first":1,"lower":1,"ethernet":1}
,"included":{"release":1,"readme_massflash.txt":1,"apply_binaries":1}
,"release":{"basic":1,"script":1}
,"sudo":{"flash.sh":1,"clone":1,"lsblk":1,"parted":1,"mkfs.ext4":1,"mount":1,"bootdev":1,"mkdir":1,"rsync":1,"umount":1,"sd_blob_name":1,"sd-blob.img":1,"apt":1,"tools":1,"flash":1,"linux_for_tegra":1,"apt-get":1,"dpkg":1,"apply_binaries.sh":1,"default.target":1,"lib":1,"mksparse":1,"rootfs_dir":1,"fallocate":1,"chmod":1,"mkswap":1,"swapon":1}
,"options":{"board":1,"command":1,"aspects":1}
,"command":{"line":1,"stores":1,"above":1,"change":1,"run":1,"method":1,"generates":1,"u\u2011boot":1,"prompt":1,"flashes":1,"terminal":1,"target\u0027s":1,"booted":1,"install":1,"unmount":1,"configure":1}
,"line":{"switches":1,"options":1,"option":1,"syntax":1,"arguments":1,"defines":1,"save":1,"may":1}
,"switches":{"switches":1,"optional":1,"described":1}
,"optional":{"switches":1}
,"described":{"flash":1,"table":1,"basic":1,"section":1,"elsewhere":1}
,"specifies":{"configuration":1,"type":1,"device":1}
,"configuration":{"applied":1,"configuration":1,"file":1,"target":1,"files":1,"directory":1,"parameters":1,"filename":1,"inspecting":1,"clone":1,"bug":1,"jetson":1}
,"applied":{"device":1,"apply_binaries":1}
,"flashed":{"values":1,"value":1,"reflash":1,"flash":1,"card":1,"device":1,"possible":1,"kernel":1,"sdk":1,"tool":1}
,"values":{"listed":1,"defined":1,"parameters":1,"depend":1}
,"listed":{"table":1,"nv-oem-config":1,"select":1}
,"table":{"device":1,"configuration":1,"jetson":1,"root":1,"describes":1}
,"names":{"topic":1,"copies":1}
,"topic":{"quick":1,"setting":1,"bsp":1,"jetson":1,"bootloader":1,"secureboot":1,"clock":1}
,"quick":{"start":1}
,"start":{"flash.sh":1,"address":1,"rcm":1,"serial":1}
,"gets":{"configuration":1}
,"named":{"board":1,"clone":1,"original.img":1,"original.img.raw":1,"sd-blob.img":1,"nv_flash_from_nfs_image.tbz2":1,"images_to_flash":1,"nvidia":1,"ubuntu":1}
,"rootdev":{"specifies":1,"suffixes":1}
,"type":{"device":1,"jetson":1,"target":1}
,"value":{"mmcblk0p1":1,"null":1,"board":1,"environment":1,"serverip":1,"property":1}
,"mmcblk0p1":{"flash":1}
,"local":{"storage":1,"time":1}
,"emmc":{"card":1,"size":1,"memory":1,"hardware":1,"flashed":1,"cannot":1,"first":1,"jetson":1}
,"card":{"depending":1,"enter":1,"jetson":1,"available":1,"easy":1,"flashed":1,"image":1,"etcher":1,"card":1,"slot":1,"reader":1,"block":1,"space":1,"first":1,"host":1,"insert":1,"ext4":1,"appropriate":1,"mount":1,"details":1,"due":1,"case":1}
,"depending":{"platform":1}
,"platform":{"distinguished":1,"instructions":1}
,"distinguished":{"nfs":1}
,"nfs":{"server":1,"root":1,"rootfs":1,"network":1,"booting":1,"deprecated":1,"nvidia":1,"flashing":1,"target":1,"procedure":1,"boot":1,"rcm-boot":1,"manually":1,"device\u2019s":1}
,"server":{"example":1,"cboot.bin":1,"again":1}
,"describes":{"common":1,"procedures":1,"command":1}
,"common":{"procedures":1}
,"procedures":{"flashing":1,"using":1}
,"put":{"target":1,"device":1,"recovery":1,"jetson":1,"nfs":1}
,"reset":{"recovery":1,"button":1}
,"power":{"carrier":1,"reboot":1,"source":1,"management":1}
,"carrier":{"board":1}
,"hold":{"recovery":1}
,"press":{"reset":1,"hold":1,"tab":1,"left":1,"enter":1}
,"run":{"flash.sh":1,"bootcmd_nvme0":1,"boot":1,"saveenv":1,"oem-config":1,"command":1,"tftp":1,"bootcmd_pxe":1,"subsequent":1,"first":1,"script":1,"jetson-disk-image-creator.sh":1,"host":1}
,"top-level":{"directory":1}
,"supplied":{"target":1}
,"e.g":{"jetson-xavier":1,"emmc":1,"nvme":1,"bus":1,"003":1,"3-14":1,"dev":1,"john":1}
,"jetson-xavier":{"root":1,"mmcblk0p1":1}
,"located":{"described":1,"folder":1}
,"execute":{"script":1,"command":1,"following":1}
,"mount":{"rootfs":1,"dev":1,"bootloader":1,"backup.img.raw":1,"point":1,"partition":1}
,"specified":{"uuid":1,"table":1,"flash.xml":1,"overrides":1,"enclosed":1,"file":1,"option":1,"rootfs":1,"section":1,"cbootargs":1,"default":1,"username":1,"password":1,"hostname":1}
,"enter":{"command":1,"following":1,"run":1,"u\u2011boot":1,"commands":1,"boot":1,"back":1,"using":1,"full":1,"password":1,"weak":1,"advance":1,"skip":1,"zero":1,"ssid":1,"host":1,"hostname":1}
,"stores":{"uuid":1,"signature":1,"tarball":1}
,"uuid":{"used":1,"writing":1,"file":1}
,"used":{"root":1,"flash":1,"mts_preboot":1,"signing":1,"odm":1,"otherwise":1,"encrypt":1,"components":1,"target":1,"create":1,"boot":1,"flash.sh":1,"flashing":1,"select":1}
,"filesystem":{"partition":1,"first":1,"root":1,"scsi":1,"nvidia":1,"image":1,"boot":1,"script":1,"triggers":1,"extract":1,"host":1,"rcm":1}
,"partition":{"file":1,"want":1,"enter":1,"table":1,"name":1,"size":1,"saves":1,"least":1,"contain":1,"dev":1,"mount":1,"fill":1,"always":1,"resize2fs":1,"fit":1,"layout":1,"bootloader":1,"instead":1,"flashed":1,"overview":1,"actually":1,"device":1,"root":1,"8589934592":1,"backup.img":1,"card":1,"megabytes":1,"statically":1}
,"l4t-rootfs-uuid.txt":{"may":1}
,"may":{"specify":1,"used":1,"larger":1,"format":1,"external":1,"found":1,"update":1,"flashing":1,"multiple":1,"putty":1,"shorten":1,"choose":1,"perform":1,"separated":1}
,"specify":{"uuid":1,"number":1,"name":1,"username":1,"password":1,"strong":1,"desired":1}
,"writing":{"uuid":1}
,"executing":{"command":1}
,"stage":{"device":1}
,"nvme":{"usb":1,"ssd":1,"drive":1,"storage":1,"drive\u2019s":1,"cut":1,"boot":1,"devices":1,"linux":1}
,"l4t-rootfs-uuid.txt_ext":{"may":1}
,"clone":{"jetson":1,"board":1,"determines":1,"top":1,"exact":1,".raw":1,"original.img":1,".img":1,"image":1,"production":1,"source":1}
,"copy":{"system.img":1,"named":1,"clone":1,"image":1,"custom":1,"kernel":1}
,"system.img":{"filesystem":1,"directory":1,"reuse":1,"file":1,"target":1}
,"want":{"flash":1,"decrease":1,"run":1,"installation":1,"system":1}
,"app":{"clone":1,"partition":1,"board":1,"0gb":1,"ext4":1,"ext2":1,"partition\u2019s":1}
,"determines":{"names":1}
,"step":{"creates":1,"root":1,"prompts":1,"select":1,"section":1}
,"creates":{"two":1,"sparsed":1,"system.img":1,"stores":1,"user":1,"default":1}
,"two":{"copies":1,"arguments":1,"spaces":1,"basic":1}
,"copies":{"clone":1}
,"top":{"directory":1,"nv-oem-config.conf.t210":1,"nv-oem-config.conf.t194":1,"nv-oem-config.conf.t186":1}
,"sparsed":{"image":1}
,"smaller":{"original":1}
,"original":{"named":1,"jetson":1}
,"exact":{"copy":1}
,"example":{"clone":1,"2gib":1,"host":1,"sdx":1,"nvmexn1":1,"create":1,"copy":1,"provided":1,"flash":1,"u-boot":1}
,"original.img":{"flash.sh":1,"exact":1}
,".img":{"l4t":1,"bootloader":1}
,"l4t":{"bootloader":1,"supports":1,"kernel":1}
,"already":{"flashed":1,"done":1}
,"reflash":{"clone":1}
,"board\u2019s":{"partitions":1}
,"partitions":{"enter":1,"per":1}
,"rcm":{"boot":1}
,"boot":{"nfs":1,"control":1,"partition":1,"key":1,"binary":1,"file":1,"firmware":1,"usb":1,"successfully":1,"flash":1,"image":1,"image.sig":1,"flow":1,"prompt":1,"first":1,"command":1,"nvme":1,"device":1,"order":1,"change":1,"configurations":1,"devices":1,"extlinux":1,"entry":1,"directory":1,"time":1,"manually":1,"target":1,"pxelinux":1,"configuration":1,"options":1,"check":1,"disables":1,"again":1,"open":1,"process":1,"initrd":1}
,"applies":{"jetson":1,"target":1}
,"xavier":{"jetson":1,"series":1,"nvidia":1,"module":1,"\u2011\u2011r":1,"development":1,"using":1,"gigabytes":1}
,"agx":{"xavier":1}
,"series":{"jetson":1,"0x19":1,"0x18":1,"nvidia":1,"devices":1,"boot":1,"information":1,"top":1}
,"tx2":{"series":1,"using":1,"image":1}
,"create":{"bootable":1,"new":1,"signature":1,"raw":1,"card":1,"external":1,"flash":1,"configuration":1,"enable":1,"swap":1,"manually":1}
,"bootable":{"nfs":1}
,"perform":{"process":1,"operation":1,"time":1}
,"process":{"described":1,"fail":1,"press":1,"skip":1,"runs":1}
,"setting":{"file":1,"dedicated":1,"highlighted":1}
,"configuring":{"nfs":1,"production":1}
,"linux":{"host":1,"etcher":1,"x64":1,"command":1,"filesystem":1,"dev":1,"bsp":1,"kernel":1,"accomplish":1,"image":1,"expects":1,"log":1}
,"host":{"topic":1,"system":1,"computer":1,"i.e":1,"enter":1,"usb":1,"uses":1,"following":1,"providing":1,"procedure":1,"mount":1,"using":1,"computer\u2019s":1,"script":1,"name":1}
,"bsp":{"customization":1,"package":1}
,"ip_addr":{"root_path":1,"address":1}
,"root_path":{"--rcm-boot":1,"path":1,"board":1,"root":1}
,"--rcm-boot":{"board":1}
,"address":{"host":1,"my_ip_address":1,"size":1}
,"path":{"nfs":1,"e.g":1,"backup.img.raw":1}
,"complements":{"basic":1}
,"providing":{"detailed":1,"nfs":1}
,"detailed":{"information":1,"instructions":1}
,"aspects":{"flash.sh":1}
,"deprecated":{"pathname":1,"target":1,"pkc":1,"end":1,"flashing":1}
,"pathname":{"boot":1,"flash":1,"device":1,"file":1,"tegraboot":1,"warm":1,"initrd":1,"kernel":1,"bootloader":1,"mts":1,"sample":1,"necessary":1}
,"control":{"table":1,"headless":1}
,"tree":{"file":1}
,"device\u0027s":{"emmc":1,"app":1}
,"memory":{"size":1,"consequently":1,"partition":1}
,"size":{"applies":1,"ppt":1,"rootfs":1,"size":1,"partition":1,"without":1,"boot":1,"following":1,"jetson":1,"board":1,"desired":1,"app":1,"leave":1}
,"devices":{"emmc":1,"nvidia":1,"jetson":1,"boot":1,"booted":1,"l4t":1,"appear":1,"device":1,"dev":1,"cboot":1,"u\u2011boot":1,"priority":1,"connect":1,"partition":1,"nvme":1,"flashing":1,"efficiently":1,"support":1,"typical":1,"purchaser":1}
,"name":{"flash":1,"number":1,"mts":1,"e.g":1,"host":1,"sdb":1,"app":1,"jetson":1,"nvme0n1":1,"pathname":1,"dev":1,"partition":1,"image":1,"used":1,"typical":1,"system.img":1,"enter":1,"select":1,"using":1,"ask":1,"tegra-ubuntu":1}
,"application":{"used":1,"bootloader":1,"configure":1,"headless":1,"host":1,"communicates":1,"issues":1}
,"applications":{"stored":1}
,"stored":{"bootloader":1,"internal":1}
,"default":{"flash":1,"value":1,"values":1,"partition":1,"file":1,"bootloader":1,"boot":1,"primary":1,"last":1,"board":1,"configuration":1,"setting":1,"user":1}
,"prints":{"descriptions":1,"description":1}
,"descriptions":{"command":1}
,"syntax":{"command":1}
,"number":{"specified":1,"target":1,"jetson":1,"detected":1,"dev":1,"tabs":1}
,"flash.xml":{"flash.cfg":1}
,"mts":{"preboot":1,"boot":1}
,"preboot":{"file":1}
,"static":{"nfs":1}
,"network":{"assignments":1,"file":1,"management":1,"flashing":1,"boot":1,"interface":1,"configuration":1,"administrator":1,"may":1}
,"assignments":{"client_ip":1}
,"client_ip":{"server_ip":1}
,"server_ip":{"gateway_ip":1}
,"gateway_ip":{"netmask":1}
,"odm":{"data":1,"fused":1}
,"total":{"emmc":1}
,"hardware":{"boot":1}
,"skips":{"building":1}
,"building":{"system.img":1,"bl_update_payload":1,"multi-spec":1}
,"reuse":{"existing":1}
,"pkc_":{"key_":1}
,"key_":{"file":1}
,"containing":{"pkc":1,"secure":1,"user":1}
,"pkc":{"key":1,"secureboot":1}
,"key":{"used":1,"sbk":1,"may":1}
,"signing":{"building":1,"kernel":1}
,"bl_update_payload":{"obsolete":1}
,"tegraboot":{"binary":1}
,"binary":{"nvtboot.bin":1,"nvtbootwb0.bin":1,"images":1,"files":1}
,"fused":{"board":1,"jetson":1}
,"secure":{"boot":1}
,"sbk":{"used":1}
,"warm":{"boot":1}
,"processor":{"chip":1}
,"chip":{"default":1}
,"nvidia":{"jetson":1,"provides":1,"recommends":1,"recommend":1,"suggests":1,"software":1,"password":1,"ndzjmwm4":1,"randomly":1}
,"nano":{"devices":1,"development":1,"revision":1,"2gb":1,"card":1,"device":1}
,"tx1":{"0x21":1,"booted":1,"devices":1,"default":1,"top":1}
,"secureboot":{"used":1,"package":1,"installed":1}
,"serial":{"number":1,"application":1}
,"arguments":{"option":1,"specified":1,"documented":1}
,"option":{"specified":1,"nfs":1,"omitted":1,"may":1,"select":1}
,"overrides":{"default":1}
,"defined":{"flash.sh":1,"l4_create_default_user.sh":1}
,"enclosed":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"separated":1}
,"separated":{"spaces":1,"combination":1}
,"documented":{"file":1}
,"kernel-4.9":{"documentation":1}
,"documentation":{"kernel-parameters.txt":1,"page":1}
,"case":{"nfs":1,"flash":1,"letters":1,"flashing":1,"uses":1}
,"related":{"arguments":1}
,"reads":{"boot":1}
,"saves":{"image":1,"raw":1}
,"zimage":{"image":1}
,"cboot.bin":{"u-boot-dtb.bin":1,"jetson-tx2":1}
,"my_ip_address":{"exported":1}
,"exported":{"nfs":1}
,"end":{"ppt":1,"boot":1,"disk":1}
,"ppt":{"plus":1}
,"primary":{"gpt":1,"kernel":1,"network":1}
,"gpt":{"start":1,"header":1}
,"bytes":{"valid":1}
,"valid":{"internal":1,"values":1}
,"suffixes":{"represent":1,"represents":1}
,"represent":{"units":1}
,"units":{"1000":1}
,"1000":{"10002":1}
,"10002":{"10003":1}
,"10003":{"kib":1}
,"kib":{"mib":1}
,"mib":{"gib":1}
,"gib":{"suffixes":1,"want":1}
,"represents":{"1024":1,"backup.img.raw":1,"partition":1}
,"1024":{"10242":1,"1024":1,"bytes":1}
,"10242":{"10243":1}
,"10243":{"example":1}
,"2gib":{"represents":1}
,"generates":{"bootloader":1,"raw":1,"flash":1,"random":1}
,"update":{"payload":1,"linux":1,"boot":1,"completed":1,"using":1,"succeeded":1,"fails":1}
,"payload":{"bup":1}
,"cleans":{"bup":1}
,"bup":{"buffer":1}
,"buffer":{"\u2011\u2011multi-spec":1}
,"\u2011\u2011multi-spec":{"enabled":1}
,"enables":{"support":1}
,"support":{"building":1,"network":1,"micro":1}
,"multi-spec":{"bup":1}
,"performs":{"steps":1}
,"steps":{"except":1,"section":1}
,"except":{"physically":1}
,"physically":{"flashing":1}
,"prevents":{"creation":1,"oem\u2011config":1}
,"creation":{"re-creation":1}
,"re-creation":{"system.img":1}
,"instance":{"connect":1}
,"connect":{"integer":1,"flash":1,"jetson":1,"nvme":1}
,"integer":{"e.g":1}
,"bus":{"dev":1}
,"dev":{"e.g":1,"sdb":1,"sdx":1,"nvme0n1":1,"nvmexn1":1,"mmcblk":1,"mmcblk1":1,"nvme":1,"filesystem":1,"parameters":1}
,"003":{"091":1}
,"091":{"usb":1}
,"port":{"path":1,"host":1,"used":1,"40\u2011pin":1,"instead":1,"easiest":1}
,"3-14":{"last":1}
,"last":{"recommended":1,"lowest":1}
,"recommended":{"form":1,"faster":1}
,"--user_key":{"user_key_file":1}
,"encrypt":{"decrypt":1}
,"decrypt":{"kernel":1}
,"kernel-dtb":{"initrd":1,"binary":1}
,"images":{"\u2011\u2011user_key":1,"external":1,"target":1}
,"\u2011\u2011user_key":{"specified":1}
,"booted":{"usb":1,"nvme":1,"card":1,"runs":1,"target":1,"omitted":1}
,"mass":{"storage":1}
,"class":{"bulk":1}
,"bulk":{"protocol":1}
,"protocol":{"flash":1}
,"drive":{"hot":1,"attached":1,"booting":1,"manually":1,"connected":1,"host":1,"device":1,"enough":1,"disconnect":1,"target":1,"secureboot":1,"u-boot":1}
,"hot":{"plugging":1}
,"plugging":{"supported":1}
,"supported":{"flash":1,"nvme":1}
,"attached":{"device":1,"jetson":1}
,"booted.you":{"manually":1}
,"manually":{"flash":1,"booting":1,"save":1,"information":1,"nvme":1,"outside":1,"want":1,"card":1,"described":1,"instead":1}
,"explained":{"section":1}
,"provides":{"simplify":1,"necessary":1,"tool":1}
,"simplify":{"flashing":1}
,"details":{"usb":1,"nvme":1,"section":1,"clone":1,"generate":1,"flashing":1,"ubuntu.com":1}
,"firmware":{"stored":1}
,"consequently":{"type":1}
,"cannot":{"boot":1,"correct":1,"update":1}
,"ssd":{"until":1,"attached":1,"usb":1}
,"until":{"internal":1,"initial":1}
,"method":{"confirm":1,"prefer":1,"need":1}
,"confirm":{"device":1,"flags":1,"want":1,"entered":1}
,"successfully":{"emmc":1,"determine":1}
,"correct":{"problem":1}
,"problem":{"flashing":1}
,"check":{"flash":1,"nvme":1,"flag":1}
,"drive\u2019s":{"device":1}
,"lsblk":{"grep":1}
,"new":{"gpt":1,"boot":1,"external":1,"version":1,"file":1,"card":1}
,"parted":{"dev":1}
,"sdx":{"mklabel":1,"device":1,"mkpart":1,"sdb":1,"mnt":1}
,"mklabel":{"gpt":1}
,"computer":{"assigned":1,"assigns":1,"put":1,"customarily":1,"may":1}
,"assigned":{"flash":1}
,"assigns":{"flash":1,"nvme":1}
,"sdb":{"command":1,"mklabel":1,"partition":1,"mkpart":1}
,"add":{"app":1,"new":1,"line":1}
,"mkpart":{"app":1}
,"0gb":{"size":1,"16gb":1}
,"least":{"may":1,"upper":1}
,"larger":{"flash":1,"nvme":1,"partition":1}
,"enough":{"space":1}
,"contain":{"enter":1}
,"format":{"app":1}
,"ext4":{"partition":1,"strongly":1,"image":1,"filesystem":1}
,"mkfs.ext4":{"dev":1}
,"ext2":{"ext3":1}
,"ext3":{"ext4":1}
,"strongly":{"recommended":1}
,"compact":{"reliable":1}
,"mode":{"enter":1,"power":1,"requires":1,"flow":1,"following":1,"select":1,"runtime":1}
,"generate":{"rootfs":1,"image":1,"flash":1}
,"without":{"flashing":1,"having":1,"display":1}
,"bootdev":{"sda1":1,"nvme0n1p1":1}
,"sda1":{"flash.sh":1,"device":1}
,"--no-flash":{"board":1}
,"mkdir":{"tmp_system":1,"tftpboot":1,"tmp":1}
,"system.img.raw":{"tmp_system":1}
,"rsync":{"-axhawx":1}
,"-axhawx":{"--numeric-ids":1}
,"--numeric-ids":{"--info":1}
,"--info":{"progress2":1}
,"progress2":{"--exclude":1}
,"--exclude":{"proc":1}
,"proc":{"tmp_system":1,"device-tree":1}
,"tmp_system":{"mnt":1}
,"assign":{"app":1}
,"unmount":{"flash":1,"nvme":1,"device":1}
,"disconnect":{"host":1}
,"umount":{"mnt":1,"tmp_system":1,"$root":1}
,"plug":{"flash":1,"nvme":1}
,"prepare":{"files":1}
,"package":{"installed":1,"may":1,"topic":1,"nfs":1,"stores":1,"folder":1,"device":1,"structure":1,"put":1,"available":1,"flash":1,"nvidia-l4f-oem-config":1,"initrd":1}
,"installed":{"kernel":1,"script":1,"installing":1}
,"signed":{"signature":1}
,"signature":{"file":1}
,"saved":{"boot":1}
,"automatically":{"creates":1,"puts":1,"rcm":1,"first":1,"generated":1,"booted":1,"boot":1}
,"save":{"manually":1,"close":1}
,"hot-plugging":{"supported":1}
,"grep":{"nvme":1}
,"note":{"two":1,"having":1,"case":1}
,"nvmexn1":{"mklabel":1,"device":1,"mkpart":1,"nvme0n1":1,"mnt":1}
,"nvme0n1":{"command":1,"mklabel":1,"partition":1,"mkpart":1}
,"nvme0n1p1":{"flash.sh":1,"device":1}
,"u-boot":{"environment":1,"changing":1,"prompt":1}
,"test":{"directly":1,"configuration":1,"plain":1}
,"directly":{"enter":1}
,"bootcmd_nvme0":{"boot":1}
,"first":{"plain":1,"time":1,"booted":1,"dhcp":1,"boot":1,"subsequent":1,"name":1,"displays":1}
,"plain":{"boot":1}
,"change":{"u\u2011boot":1,"permanent":1,"size":1,"partition":1,"boot":1,"boot_targets":1,"parts":1,"flash":1,"value":1,"nvpmodel":1}
,"u\u2011boot":{"variable":1,"command":1,"boot":1,"required":1,"image":1,"loads":1,"test":1,"prompt":1}
,"variable":{"boot_targets":1,"board":1}
,"boot_targets":{"nvme0":1,"booting":1,"list":1,"pxe":1}
,"nvme0":{"mmc1":1}
,"mmc1":{"mmc0":1,"enter":1}
,"mmc0":{"usb0":1}
,"usb0":{"pxe":1}
,"pxe":{"dhcp":1,"protocol":1,"boot":1,"searches":1}
,"dhcp":{"enter":1,"mmc1":1,"sd-card":1}
,"permanent":{"run":1}
,"saveenv":{"u-boot":1}
,"changing":{"boot_targets":1,"boot":1}
,"development":{"modules":1,"module":1}
,"utilizing":{"card":1}
,"module":{"p3668-0000":1,"p3448-0000":1,"used":1,"per":1,"revision":1}
,"p3668-0000":{"jetson":1}
,"p3448-0000":{"p3448-0003":1}
,"p3448-0003":{"modules":1}
,"modules":{"used":1,"configurations":1,"drivers":1}
,"components":{"jetson":1}
,"developer":{"kits":1,"kit":1}
,"download":{"etcher":1,"extract":1}
,"etcher":{"linux":1,"tool":1,"copy":1,"select":1}
,"tool":{"copy":1,"run":1,"supports":1,"section":1,"uses":1,"instructions":1,"part":1,"included":1,"automatically":1,"change":1,"useful":1}
,"https":{"www.balena.io":1}
,"www.balena.io":{"etcher":1}
,"x64":{"64-bit":1}
,"64-bit":{"appimage":1}
,"appimage":{"downloaded":1}
,"downloaded":{"file":1}
,"recommends":{"using":1,"select":1,"specify":1,"create":1,"spacing":1}
,"easy":{"foolproof":1}
,"foolproof":{"method":1}
,"prefer":{"perform":1}
,"operation":{"linux":1}
,"need":{"download":1}
,"done":{"expand":1}
,"expand":{"archive":1}
,"archive":{"linux_for_tegra.tbz2":1}
,"linux_for_tegra":{"tools":1,"\u200Ctools":1,"folder":1,"kernel":1,"bootloader":1}
,"jetson-disk-image-creator.sh":{"blob_name":1,"sd-blob.img":1,"script":1,"create":1}
,"blob_name":{"board":1,"filename":1}
,"filename":{"script":1,"wiki":1}
,"raw":{"image":1}
,"configurations":{"topic":1,"extlinux.conf":1}
,"revision":{"revision":1,"number":1,"a01":1,"a02":1,"b00":1}
,"100":{"original":1}
,"200":{"original":1}
,"300":{"original":1}
,"b00":{"b01":1}
,"nothing":{"jetson":1}
,"2gb":{"jetson":1,"using":1}
,"\u2011\u2011r":{"option":1}
,"per":{"spi\u2011sd":1,"min-spi":1}
,"spi\u2011sd":{"profile":1}
,"profile":{"jetson":1}
,"min-spi":{"profile":1}
,"sd-blob.img":{"jetson":1,"jetson-nano-devkit":1,"working":1,"dev":1,"new":1}
,"jetson-nano-devkit":{"100":1}
,"supports":{"modified":1,"flashing":1,"external":1,"utf\u20118":1}
,"modified":{"rootfs":1}
,"thus":{"create":1,"prevents":1}
,"rootfs_dir":{"modified_rootfs_path":1,"root":1}
,"modified_rootfs_path":{"jetson-disk-image-creator.sh":1}
,"insert":{"card":1,"host":1}
,"slot":{"host":1,"may":1}
,"launch":{"etcher":1,"u\u2011boot":1}
,"select":{"blob":1,"card":1,"source":1,"language":1,"press":1,"cancel":1,"location":1,"keyboard\u2019s":1,"select":1,"time":1,"eth0":1,"nvpmodel":1,"keep":1}
,"blob":{"image":1,"file":1,"normal":1}
,"created":{"jetson-disk-image-creator.sh":1,"end":1}
,"click":{"flash":1}
,"write":{"blob":1}
,"sd_blob_name":{"dev":1}
,"mmcblk":{"oflag":1}
,"oflag":{"direct":1}
,"sd_blocb_name":{"name":1}
,"necessary":{"blob":1,"tools":1,"packages":1,"back":1}
,"block":{"number":1}
,"detected":{"linux":1}
,"working":{"directory":1}
,"mmcblk1":{"oflag":1}
,"resize":{"root":1}
,"fill":{"available":1}
,"available":{"card":1,"linux_for_tegra":1}
,"always":{"created":1,"scp":1}
,"allows":{"change":1}
,"having":{"move":1,"swap":1}
,"move":{"partitions":1}
,"resize2fs":{"tool":1}
,"oem-config":{"first":1,"whose":1,"tool":1,"username":1,"runs":1,"manually":1,"running":1,"next":1,"oem-config-gtk":1,"host":1,"configuration":1,"port":1,"40\u2011pin":1,"headless":1,"displays":1,"asks":1,"creates":1,"ask":1,"later":1,"prompts":1,"reconfigures":1,"may":1,"system":1}
,"time":{"newly":1,"boots":1,"zone":1,"start":1,"flashing":1,"zones":1,"utc":1,"linux":1,"however":1,"run":1}
,"newly":{"copied":1}
,"copied":{"image":1}
,"freshly":{"initialized":1}
,"initialized":{"card":1}
,"runs":{"oem-config":1,"gui":1,"character":1,"oem\u2011config":1}
,"whose":{"functions":1}
,"functions":{"app":1}
,"partition\u2019s":{"size":1}
,"moves":{"backup":1}
,"backup":{"gpt":1}
,"header":{"end":1,"edit":1,"uart":1}
,"deletes":{"re-creates":1}
,"re-creates":{"root":1}
,"informs":{"kernel":1}
,"resizes":{"filesystem":1}
,"fit":{"expected":1}
,"expected":{"partition":1}
,"overview":{"tool":1,"topic":1}
,"layout":{"information":1,"select":1}
,"appear":{"linux":1}
,"scsi":{"devices":1}
,"instructions":{"part":1,"workflows":1,"example":1,"flashing":1,"using":1,"open":1}
,"part":{"linux":1}
,"found":{"directory":1}
,"kernel_flash":{"detailed":1,"l4t_initrd_flash.sh":1,"l4t_create_images_for_kernel_flash.sh":1,"current":1,"readme_nfs_flash.txt":1}
,"workflows":{"file":1,"flash":1}
,"readme_initrd_flash.txt":{"directory":1,"contains":1}
,"order":{"cboot":1,"verify":1,"u-boot":1,"flashed":1,"enter":1}
,"cboot":{"boot":1,"environment":1,"loading":1}
,"environment":{"flashed":1,"variable":1,"tool":1}
,"interrupt":{"cboot":1}
,"loading":{"boot":1}
,"extlinux.conf":{"pressing":1,"add":1,"means":1}
,"pressing":{"key":1,"tab":1}
,"verify":{"change":1,"update":1}
,"setvar":{"boot-order":1}
,"boot-order":{"dev1":1}
,"dev1":{"dev2":1}
,"dev2":{"dev3":1}
,"printvar":{"boot-order":1}
,"parameters":{"valid":1,"configuration":1}
,"nvme:c":{"device":1}
,"nvme:pcie@":{"addr":1}
,"addr":{"net":1,"device\u2019s":1}
,"net":{"addr":1}
,"device\u2019s":{"pcie":1,"recovery":1,"command":1,"configuration":1,"ram":1}
,"pcie":{"address":1}
,"reboot":{"enter":1,"ubiquity":1}
,"list":{"boot":1,"configuration":1,"interfaces":1,"wait":1}
,"priority":{"order":1,"several":1}
,"specific":{"partition":1}
,"instead":{"flashing":1,"change":1,"root":1,"selecting":1}
,"whole":{"device":1}
,"partition_name":{"--image":1,"name":1}
,"--image":{"image_name":1}
,"image_name":{"board":1,"name":1}
,"possible":{"values":1,"size":1}
,"depend":{"target":1}
,"omitted":{"flash.sh":1,"script":1,"user":1}
,"chooses":{"image":1}
,"kit":{"operating":1}
,"operating":{"software":1,"system":1}
,"software":{"topic":1,"omitted":1}
,"jetson-nano-2gb-devkit":{"mmcblk0p1":1}
,"mb1":{"bct":1}
,"bct":{"jetson":1}
,"predefined":{"list":1}
,"mb1_bct":{"jetson-xavier":1}
,"cpu":{"bootloader":1}
,"user-specified":{"image":1}
,"user_path":{"cboot.bin":1}
,"cpu-bootloader":{"-image":1}
,"-image":{"user_path":1}
,"jetson-tx2":{"mmcblk0p1":1}
,"notes":{"kernel":1}
,"required":{"jetson":1}
,"actually":{"u\u2011boot":1,"used":1}
,"loads":{"linux":1}
,"reason":{"cannot":1}
,"either":{"means":1,"enter":1}
,"modify":{"boot":1,"default":1,"ram":1,"initrd":1}
,"extlinux":{"extlinux.conf":1}
,"follow":{"instructions":1}
,"provided":{"boot":1}
,"means":{"always":1}
,"scp":{"replace":1}
,"replace":{"boot":1,"initrd":1}
,"custom-built":{"kernel":1}
,"t210":{"jetson":1}
,"ums":{"mmc":1}
,"connects":{"emmc":1}
,"custom":{"kernel":1,"configuring":1}
,"button":{"press":1}
,"flashes":{"bootloader":1}
,"ram":{"disk":1}
,"disk":{"internal":1,"encryptions":1}
,"requires":{"secureboot":1,"high-quality":1}
,"installing":{"secureboot":1}
,"\u200Ctools":{"\u200Ckernel_flash":1}
,"\u200Ckernel_flash":{"detailed":1}
,"contains":{"examples":1,"entries":1,"least":1}
,"examples":{"several":1}
,"several":{"workflows":1,"configuration":1}
,"enabling":{"rootfs":1,"disk":1}
,"encryptions":{"external":1}
,"individual":{"partitions":1}
,"massflash":{"blob":1}
,"normal":{"fused":1}
,"generating":{"separate":1}
,"separate":{"images":1}
,"combined":{"images":1}
,"high-quality":{"usb\u2011c":1}
,"usb\u2011c":{"micro-usb":1}
,"micro-usb":{"cable":1}
,"low-quality":{"cable":1}
,"networkmanager":{"network":1}
,"management":{"application":1,"read":1,"section":1}
,"configure":{"network":1,"oem-config":1,"wireless":1,"wifi":1}
,"automount":{"temporarily":1,"swap":1}
,"temporarily":{"disabled":1}
,"disabled":{"new":1}
,"during":{"flashing":1,"installation":1}
,"debian-based":{"distributions":1}
,"distributions":{"linux":1}
,"accomplish":{"following":1}
,"systemctl":{"stop":1}
,"stop":{"udisks2.service":1}
,"apt":{"install":1}
,"install":{"libxml2-utils":1,"run":1,"package":1,"packages":1,"--no-install-recommends":1,"following":1}
,"libxml2-utils":{"simg2img":1}
,"simg2img":{"network-manager":1}
,"network-manager":{"abootimg":1}
,"abootimg":{"sshpass":1}
,"sshpass":{"device-tree-compiler":1}
,"board-name":{"rootdev":1,"value":1}
,"rcm-boot":{"nfs":1}
,"sections":{"provide":1}
,"provide":{"two":1}
,"readme_nfs_flash.txt":{"directory":1}
,"l4t_create_images_for_kernel_flash.sh":{"ipaddr":1,"generates":1}
,"ipaddr":{"nfsroot":1}
,"nfsroot":{"board-name":1,"location":1}
,"location":{"nfs":1,"flash":1,"select":1}
,"tarball":{"named":1}
,"nv_flash_from_nfs_image.tbz2":{"directory":1,"nfs":1}
,"current":{"host":1}
,"puts":{"flash":1}
,"folder":{"named":1,"instructions":1}
,"images_to_flash":{"root":1,"board":1}
,"triggers":{"target":1}
,"extract":{"nv_flash_from_nfs_image.tbz2":1,"build":1}
,"multiple":{"folders":1,"jetson":1}
,"folders":{"generate":1}
,"structure":{"may":1}
,"terminal":{"run":1}
,"target\u0027s":{"console":1}
,"console":{"flash":1}
,"l4t_flash_from_kernel.sh":{"readme":1}
,"readme":{"file":1}
,"efficiently":{"factory":1}
,"factory":{"environment":1}
,"readme_massflash.txt":{"located":1}
,"pxelinux":{"implementation":1,"boot":1,"information":1}
,"implementation":{"pxe":1}
,"build":{"ready":1}
,"ready":{"applicable":1}
,"applicable":{"platform":1}
,"open":{"source":1,"read":1,"configuration":1,"fstab":1}
,"source":{"page":1,"device":1,"device\u0027s":1}
,"page":{"install":1,"pxelinux":1,"configure":1}
,"tftp":{"server":1}
,"server_args":{"directory":1}
,"tegra210-p3448-0002-p3449-0000-b00.dtb":{"tftboot":1}
,"tftpboot":{"pxelinux.cfg":1}
,"version":{"default":1,"updated":1}
,"pxelinux.cfg":{"contains":1}
,"menu":{"title":1,"label":1}
,"title":{"pxelinux":1}
,"label":{"primary":1}
,"fdt":{"tegra210-p3448-0002-p3449-0000-b00.dtb":1}
,"append":{"cbootargs":1}
,"cbootargs":{"booted-via-pxe":1,"actually":1}
,"booted-via-pxe":{"true":1}
,"lowest":{"priority":1}
,"searches":{"configuration":1}
,"wiki":{"page":1}
,"dummy":{"flag":1}
,"flag":{"booted-via-pxe":1,"boot":1}
,"true":{"confirm":1}
,"flags":{"specified":1}
,"inspecting":{"node":1}
,"node":{"proc":1}
,"device-tree":{"chosen":1}
,"chosen":{"bootargs":1}
,"restart":{"xinetd":1}
,"xinetd":{"service":1}
,"service":{"tftp":1}
,"serverip":{"u\u2011boot":1,"your-tftp-server-ip":1}
,"bootcmd_pxe":{"u\u2011boot":1}
,"try":{"pxe":1}
,"sd-card":{"example":1}
,"pci":{"enum":1}
,"enum":{"pci":1}
,"setenv":{"serverip":1,"autoload":1}
,"increasing":{"internal":1}
,"suggested":{"rootfs":1}
,"gigabytes":{"specified":1}
,".conf":{"file":1}
,"size-in-bytes":{"argument":1}
,"argument":{"flash.sh":1}
,"desired":{"size":1}
,"8589934592":{"gib":1}
,"decrease":{"size":1}
,"determining":{"success":1}
,"success":{"driver":1,"failure":1,"message":1}
,"driver":{"update":1}
,"updating":{"drivers":1}
,"drivers":{"target":1,"nvidia_drv.so":1}
,"completed":{"successfully":1}
,"determine":{"success":1}
,"failure":{"driver":1}
,"sha1sum":{"nv_tegra_release":1,"usr":1}
,"succeeded":{"output":1}
,"output":{"displays":1}
,"displays":{"word":1,"welcome":1,"license":1,"screen":1,"message":1,"list":1}
,"word":{"file":1}
,"typical":{"success":1,"error":1,"case":1}
,"message":{"looks":1,"summarizes":1,"decide":1}
,"usr":{"lib":1}
,"lib":{"xorg":1,"systemd":1}
,"xorg":{"modules":1}
,"fails":{"file":1,"new":1}
,"missing":{"typical":1}
,"error":{"message":1}
,"nvidia_drv.so":{"file":1,"failed":1}
,"failed":{"open":1}
,"different":{"existing":1,"location":1}
,"existing":{"file":1}
,"producing":{"error":1}
,"reconfiguring":{"jetson":1}
,"sdk":{"manager":1}
,"manager":{"runs":1,"re-enable":1}
,"boots":{"flashed":1,"install":1,"first":1}
,"parts":{"device\u2019s":1}
,"useful":{"custom":1}
,"production":{"devices":1}
,"purchaser":{"device":1}
,"username":{"password":1,"user":1,"omitted":1}
,"password":{"language":1,"user":1,"select":1,"i.e":1,"oem-config":1,"again":1,"times":1,"next":1,"omitted":1,"ndzjmwm4":1,"host":1,"hostname":1}
,"language":{"time":1,"want":1,"selected":1}
,"headed":{"target":1}
,"equipped":{"display":1}
,"display":{"oem-config":1,"runs":1,"device":1}
,"gui":{"application":1,"information":1,"subsection":1}
,"headless":{"target":1,"jetson":1,"mode":1}
,"character":{"interface":1}
,"interface":{"application":1,"during":1,"sure":1}
,"disables":{"tool":1,"oem-config":1}
,"subsequent":{"boots":1,"boot":1}
,"outside":{"sdk":1}
,"re-enable":{"oem-config":1}
,"again":{"target":1,"confirm":1}
,"packages":{"installed":1,"source":1}
,"enable":{"oem-config":1,"swap":1}
,"next":{"reboot":1,"screen":1,"step":1}
,"ubiquity":{"oem-config":1}
,"oem-config-gtk":{"enter":1}
,"apt-get":{"install":1}
,"--no-install-recommends":{"ubiquity":1}
,"remove":{"package":1,"card":1}
,"dpkg":{"--purge":1}
,"--purge":{"nvidia-l4t-oem-config":1}
,"backup.img":{"backup.img.raw":1}
,"backup.img.raw":{"details":1,"ext4":1,"mount":1,"name":1,"system.img":1}
,"point":{"choice":1,"details":1}
,"apply":{"jetson-specific":1}
,"jetson-specific":{"binaries":1}
,"nv-oem-config":{"setup":1,"applied":1}
,"setup":{"files":1,"complete":1}
,"apply_binaries":{"script":1}
,"apply_binaries.sh":{"root":1}
,"nv-oem-config.target":{"default.target":1}
,"$root":{"systemd":1}
,"systemd":{"system":1}
,"mounted":{"step":1}
,"sparse":{"version":1}
,"updated":{"image":1}
,"mksparse":{"fillpattern":1}
,"fillpattern":{"path":1}
,"appropriate":{"files":1,"configuration":1,"power":1}
,"communication":{"debugging":1}
,"debugging":{"port":1}
,"customarily":{"communicates":1}
,"communicates":{"oem-config":1,"host":1}
,"computer\u2019s":{"tty":1,"hostname":1}
,"tty":{"device":1}
,"assumptions":{"topic":1}
,"kits":{"uart":1}
,"uart":{"port":1}
,"40\u2011pin":{"header":1}
,"edit":{"oem-config":1}
,"micro":{"usb":1}
,"connector":{"debugging":1}
,"easiest":{"control":1}
,"ttl":{"adapter":1}
,"adapter":{"required":1}
,"defines":{"property":1}
,"nv-oem-config-uart-port":{"ttygs0":1}
,"property":{"ttys0":1}
,"ttys0":{"ttyths1":1}
,"close":{"configuration":1}
,"proceed":{"flash":1}
,"elsewhere":{"topic":1}
,"flow":{"oem-config":1}
,"putty":{"screen":1}
,"screen":{"serial":1,"advance":1,"press":1,"lists":1,"preceding":1,"doing":1,"shot":1,"explains":1}
,"utf\u20118":{"character":1}
,"recommend":{"using":1}
,"minicom":{"application":1}
,"issues":{"dealing":1}
,"dealing":{"utf\u20118":1}
,"finds":{"display":1}
,"reconfigure":{"target":1}
,"welcome":{"screen":1}
,"advance":{"next":1}
,"tab":{"enter":1}
,"license":{"governs":1,"accept":1}
,"governs":{"read":1}
,"read":{"license":1,"message":1,"nvpmodel":1}
,"accept":{"pressing":1,"eula":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1,"script\u2019s":1}
,"lists":{"languages":1,"locations":1,"keyboard":1,"time":1}
,"languages":{"down-arrow":1}
,"down-arrow":{"keys":1}
,"keys":{"select":1}
,"installation":{"process":1}
,"left":{"right-arrow":1}
,"right-arrow":{"keys":1}
,"back":{"screen":1}
,"preceding":{"select":1}
,"cancel":{"press":1,"times":1}
,"doing":{"once":1}
,"locations":{"language":1,"choose":1}
,"selected":{"used":1}
,"keyboard":{"layouts":1}
,"layouts":{"select":1}
,"keyboard\u2019s":{"layout":1}
,"zones":{"exist":1}
,"exist":{"location":1}
,"zone":{"select":1,"listed":1}
,"times":{"necessary":1,"sets":1}
,"choose":{"different":1,"name":1}
,"asks":{"whether":1,"specify":1,"enter":1}
,"whether":{"want":1,"create":1}
,"clock":{"universal":1,"utc":1,"local":1,"frequency":1}
,"universal":{"coordinated":1}
,"coordinated":{"time":1}
,"utc":{"greenwich":1,"therefore":1}
,"greenwich":{"mean":1}
,"mean":{"time":1}
,"expects":{"system":1}
,"therefore":{"nvidia":1}
,"however":{"select":1}
,"shot":{"smart":1}
,"smart":{"phone":1}
,"full":{"name":1}
,"john":{"smith":1}
,"smith":{"select":1}
,"account":{"oem-config":1,"name":1,"instead":1,"non-administrative":1,"enter":1}
,"suggests":{"using":1}
,"lower":{"case":1}
,"letters":{"account":1,"numerals":1}
,"non-administrative":{"activities":1}
,"strong":{"password":1}
,"i.e":{"eight":1}
,"eight":{"characters":1}
,"characters":{"long":1,"enter":1}
,"long":{"contains":1}
,"upper":{"lower":1}
,"numerals":{"punctuation":1}
,"punctuation":{"characters":1}
,"weak":{"password":1}
,"ask":{"confirm":1,"network":1}
,"entered":{"correctly":1}
,"correctly":{"enter":1}
,"sets":{"password":1}
,"prompts":{"specify":1,"create":1,"enter":1,"select":1,"accept":1}
,"oem\u2011config":{"prompts":1,"default":1,"running":1}
,"swap":{"file":1,"swap":1,"defaults":1}
,"summarizes":{"pluses":1}
,"pluses":{"minuses":1}
,"minuses":{"doing":1}
,"decide":{"whether":1}
,"skip":{"step":1,"boot":1}
,"explains":{"nvida":1}
,"nvida":{"recommends":1}
,"plan":{"jetson":1}
,"artificial":{"intelligence":1}
,"intelligence":{"deep":1}
,"deep":{"learning":1}
,"learning":{"applications":1}
,"shorten":{"life":1}
,"life":{"card":1}
,"due":{"increased":1,"known":1}
,"increased":{"writes":1}
,"writes":{"medium":1}
,"later":{"create":1}
,"megabytes":{"request":1}
,"request":{"maximum":1}
,"maximum":{"possible":1}
,"leave":{"field":1}
,"field":{"empty":1}
,"course":{"enlarge":1}
,"enlarge":{"app":1}
,"statically":{"flash":1}
,"interfaces":{"primary":1}
,"ethernet":{"primary":1,"cable":1,"option":1}
,"sure":{"ethernet":1}
,"eth0":{"ethernet":1}
,"known":{"wireless":1}
,"wireless":{"network":1,"networking":1}
,"bug":{"wizard":1}
,"wizard":{"either":1}
,"ssid":{"manually":1}
,"selecting":{"list":1}
,"wait":{"until":1}
,"complete":{"nmcli":1}
,"nmcli":{"command":1}
,"networking":{"details":1}
,"ubuntu.com":{"documentation":1}
,"wifi":{"connections":1}
,"hostname":{"don\u2019t":1,"select":1,"option":1,"tegra-ubuntu":1,"tegra":1}
,"don\u2019t":{"know":1}
,"know":{"host\u2019s":1,"mode":1}
,"host\u2019s":{"name":1}
,"administrator":{"setting":1}
,"dedicated":{"network":1}
,"nvpmodel":{"mode":1,"gui":1}
,"keep":{"default":1}
,"highlighted":{"screen":1}
,"runtime":{"nvpmodel":1}
,"frequency":{"power":1}
,"subsection":{"appropriate":1}
,"reconfigures":{"system":1}
,"selections":{"made":1}
,"made":{"proceeds":1}
,"proceeds":{"system\u2019s":1}
,"system\u2019s":{"log-in":1}
,"log-in":{"prompt":1}
,"alternative":{"step":1}
,"fallocate":{"swapfile":1}
,"chmod":{"600":1}
,"600":{"swapfile":1}
,"mkswap":{"swapfile":1}
,"swapon":{"swapfile":1}
,"fstab":{"text":1}
,"text":{"editor":1}
,"editor":{"add":1}
,"swapfile":{"swap":1}
,"fields":{"line":1,"align":1,"file\u2019s":1}
,"combination":{"number":1}
,"tabs":{"spaces":1}
,"spaces":{"nvidia":1}
,"spacing":{"fields":1}
,"align":{"fields":1}
,"file\u2019s":{"lines":1}
,"skipping":{"oem-config":1}
,"don\u0027t":{"want":1}
,"l4t_create_default_user.sh":{"flash":1,"user":1,"nvidia":1,"ubuntu":1,"tegra":1}
,"first-time":{"boot":1}
,"l4_create_default_user.sh":{"creates":1}
,"script\u2019s":{"usage":1}
,"pswd":{"host":1}
,"\u2011\u2011username":{"user":1}
,"\u2011\u2011password":{"pswd":1}
,"random":{"password":1}
,"\u2011\u2011hostname":{"host":1}
,"hostmane":{"tegra-ubuntu":1}
,"configures":{"jetson":1}
,"log":{"default":1,"manually":1,"automatically":1}
,"accepts":{"eula":1}
,"eula":{"nvidia":1}
,"ndzjmwm4":{"hostname":1}
,"ubuntu":{"randomly":1}
,"randomly":{"generated":1}
,"generated":{"password":1}
,"tegra-ubuntu":{"configures":1}
,"modifying":{"jetson":1}
,"unpack":{"initrd":1}
,"tmp":{"temp":1,"initrd":1}
,"gunzip":{"tmp":1}
,"content":{"tmp":1}
,"temp":{"folder":1}
,"find":{"cpio":1}
,"cpio":{"newc":1}
,"newc":{"gzip":1}
,"gzip":{"initrd":1}
,"customized":{"initrd":1}
}
;Search.control.loadWordPairs(pairs);
