var pairs =
{
"jetson":{"tx1":1,"linux":1,"download":1,"nano":1,"kernel-dts":1,"processors":1}
,"tx1":{"adaptation":1,"module":1,"developer":1,"users":1,"pinmux":1,"configuration":1,"entry":1,"module\u2019s":1,"pin":1,"lanes":1,"lan":1,"oem":1}
,"adaptation":{"bring-up":1}
,"document":{"software":1,"l4t":1,"board":1,"vendor":1}
,"software":{"developers":1,"uses":1}
,"developers":{"whose":1}
,"whose":{"target":1,"name":1}
,"target":{"nvidia":1,"device":1,"config":1,"system":1,"cmdline":1,"machine":1,"board\u0027s":1}
,"nvidia":{"jetson":1,"board":1,"reference":1,"platform":1,"p2371-2180":1,"recommends":1,"io-pad-init-voltage":1,"released":1,"portmap":1,"ss_portmap":1,"lane_owner":1,"lane-map":1,"common_padctl":1,"lanes":1,"function":1,"port-cap":1,"usb3-port":1,"usb2-map":1,"pcie-lane-select":1,"num-lanes":1,"usb2-mapportmap":1,"pcie-controller":1,"tegra":1}
,"module":{"describes":1,"carrier":1,"name":1,"som":1,"definition":1,"configured":1,"type":1,"development":1}
,"describes":{"port":1,"device":1,"wifi":1,"configured":1}
,"port":{"nvidia":1,"kernel":1,"bit":1,"lsb":1,"usb":1,"enabled":1,"lines":1,"starting":1,"entered":1,"available":1,"require":1,"valid":1,"standalone":1,"role":1,"lane":1,"linked":1,"using":1,"ball":1,"map":1,"sufficient":1,"matched":1,"value":1,"xhci":1,"property":1,"used":1,"specify":1,"case":1,"matches":1,"supports":1,"specifies":1,"bound":1,"sub-node":1,"usb3-m2":1,"following":1,"&tegra_padctl_uphy":1,"usb3-2":1,"usb3-standalone":1}
,"linux":{"driver":1,"kernel":1,"host":1,"network":1,"code":1,"rootfs":1}
,"driver":{"package":1}
,"package":{"l4t":1,"toolchain":1}
,"l4t":{"u-boot":1,"includes":1,"release":1}
,"u-boot":{"boot":1,"linux":1,"command":1,"source":1,"rather":1}
,"boot":{"loader":1,"dts":1,"directory":1,"partition":1,"control":1}
,"loader":{"nvidia":1,"locate":1}
,"developer":{"kit":1}
,"kit":{"hardware":1,"p2371-2180":1,"code":1,"carrier":1}
,"hardware":{"platform":1,"nvidia":1,"support":1,"custom-designed":1,"nodes":1,"cameras":1,"configure":1,"modules":1}
,"procedures":{"document":1,"topic":1}
,"includes":{"code":1,"support":1,".dtsi":1}
,"code":{"jetson":1,"user-visible":1,"without":1,"supports":1,"add":1,"device":1,"key_power":1,"nvtbootwb0.bin":1}
,"p2371-2180":{"serve":1,"directory":1,"files":1,"board":1}
,"serve":{"example":1}
,"board":{"naming":1,"assign":1,"lower":1,"represents":1,"name":1,"board":1,"note":1,"names":1,"version":1,"schematic":1,"change":1,"using":1,"_pinmux.xlsm":1,"based":1,"appropriate":1,"example":1,".dts":1,".dtb":1,"_defconfig":1,"nvidia":1,"vendor":1,"refer":1,"maintainers":1,"provide":1,"required":1,"som":1,"refers":1,"p2597":1,"function":1,"-gpio.dtsi":1,"-pinmux.dtsi":1,"modeled":1,".conf":1,"matches":1,"info":1,"type":1,"eeprom":1,"mmcblk0p1":1}
,"support":{"jetson":1,"board":1,"new":1,"sensors":1,"add-in":1,"kernel":1}
,"carrier":{"board":1}
,"assign":{"module":1}
,"lower":{"case":1}
,"case":{"alphanumeric":1,"letters":1,"usb":1,"possible":1,"usb_ss":1,"follows":1,"look":1}
,"alphanumeric":{"name":1}
,"name":{"name":1,"may":1,"choose":1,"character":1,"board":1,"obvious":1,"chosen":1,"jetson":1,"2180":1,"board\u2019s":1,"based":1,"e.g":1,"tab":1,"rather":1,"form":1,"xml":1,"flashing":1,"mts_si":1,"mts_preboot_si":1}
,"may":{"include":1,"power-tree":1,"rename":1,"need":1,"represent":1}
,"include":{"dashes":1,"version":1,"configs":1}
,"dashes":{"underscores":1}
,"underscores":{"spaces":1}
,"choose":{"appear":1,"similarly-constructed":1}
,"appear":{"file":1}
,"file":{"names":1,"system":1,"name":1,"writable":1,"microsoft":1,"button":1,"files":1,"includes":1,".dtsi":1,"chosen":1,"whose":1,"refer":1,"appropriate":1,"nodes":1,"\u0027power":1,"during":1,"provided":1,"board_config_p2597-devkit.xml":1,"format":1,"p2371-2180-devkit.conf":1,"option":1,"contains":1,"board":1,"used":1,"flashed":1}
,"names":{"path":1,"u-boot":1,"exposed":1,"lower":1,"enter":1,"form":1,"ball":1,"determining":1,"used":1,"e41":1,"b42":1,"g42":1,"usb":1}
,"path":{"names":1}
,"kernel":{"source":1,"proc":1,"sources":1,"customization":1,"kernel-4.9":1,"dtb":1,"always":1,"configuration":1,"device":1,"includes":1,"dtb\u2019s":1,"work":1,"rather":1,"pinmux":1,"image":1,"without":1,"version":1,"modify":1,"zimage":1}
,"source":{"code":1,"package":1,"ldk_dir":1}
,"user-visible":{"device":1}
,"device":{"tree":1,"holds":1,"new":1,"connected":1,"sector":1,"emmc":1}
,"tree":{"file":1,"files":1,"image":1,"schema":1,"kernel":1,"overlay":1,"technique":1,"edit":1,"platform":1,"reference":1,"item":1,"module":1,"changes":1,"properties":1}
,"exposed":{"user":1}
,"user":{"via":1}
,"via":{"u-boot":1}
,"command":{"prompt":1}
,"prompt":{"various":1}
,"various":{"linux":1,"types":1}
,"proc":{"files":1,"2180":1,"display":1}
,"represents":{"board":1,"vendor":1,"port":1,"usb":1,"following":1}
,"similarly-constructed":{"vendor":1}
,"vendor":{"name":1,"represents":1,"organization\u2019s":1,"board":1}
,"character":{"rules":1}
,"rules":{"apply":1}
,"apply":{"following":1}
,"following":{"example":1,"sections":1,"procedures":1,"actions":1,"procedure":1,"directory":1,"examples":1,"r24":1,"mapping":1,"device":1,"r28":1,"properties":1,"lines":1,"environment":1,"command":1}
,"simply":{"re-use":1}
,"re-use":{"modify":1}
,"modify":{"existing":1,"spreadsheet":1,"kernel":1,"recompile":1,"distributed":1,"copies":1,"odmdata":1,"line":1,"debug_uartport":1}
,"existing":{"nvidia":1,"jetson":1}
,"without":{"choosing":1,"having":1,"diluting":1,"usb":1}
,"choosing":{"using":1}
,"using":{"board":1,"following":1,"lane":1,"xml":1}
,"obvious":{"jetson":1}
,"users":{"whether":1}
,"whether":{"modified":1}
,"modified":{"source":1,"customize":1,"kernel":1,"cboot":1,"0x14":1}
,"supports":{"original":1,"host":1}
,"original":{"jetson":1}
,"placeholders":{"porting":1,"substitute":1}
,"porting":{"instructions":1,"u-boot":1,"linux":1,"follows":1}
,"sections":{"refer":1}
,"refer":{"filenames":1,"board":1,"copies":1,"documentation":1}
,"filenames":{"pathnames":1,"accordingly":1}
,"pathnames":{"contain":1}
,"contain":{"placeholders":1,"instances":1}
,"substitute":{"appropriate":1}
,"appropriate":{"value":1,"board":1}
,"value":{"placeholder":1,"emmc":1,"changes":1,"0xff56":1,"nvidia":1,"file":1}
,"placeholder":{"enter":1}
,"enter":{"commands":1,"prefix":1,"jetson-tx1-default":1,"superspeed":1,"0xf":1}
,"function":{"functional":1,"board":1,".dtsi":1,"running":1,"nvidia":1,"xusb":1,"usb3":1,"pcie":1}
,"functional":{"module":1}
,"power-tree":{"pinmux":1}
,"pinmux":{"sdmmc-drv":1,"changes":1,"configuration":1,"table":1,"spreadsheet":1,"settings":1,"files":1,"pcie-m2":1}
,"sdmmc-drv":{"keys":1}
,"keys":{"comm":1}
,"comm":{"wifi":1}
,"wifi":{"camera":1,"interrupt":1,"module":1}
,"chosen":{"represent":1,"location":1}
,"represent":{"platform":1,"data":1,"usb":1,"hsic":1,"end-connector":1}
,"platform":{"example":1,"t210":1,"modify":1,"copies":1,"mmcblk0p1":1,"circuit":1}
,"example":{"p2597":1,"change":1,"vdd":1,"file":1,"meant":1,"configuration":1,"0x0e02":1,"0x7730":1,"0xff56":1,"following":1,"environment":1}
,"p2597":{"name":1}
,"note":{"nvidia":1,"directory":1}
,"som":{"system":1,"board":1,".dts":1,"version":1,"mmcblk0p1":1}
,"system":{"module":1,"present":1,"along":1,"reboot":1}
,"version":{"board":1,"number":1,".dtsi":1,"changes":1,"3.10":1,"4.4":1,"4.9":1,"1.0":1}
,"number":{"a00":1,"files":1,"entered":1,"usb":1,"port":1}
,"a00":{"files":1}
,"files":{"nvidia":1,"customer":1,"directory":1,"names":1,"generated":1,"applied":1,"rebuild":1,"windows":1,"board":1,"u\u2011boot":1,"dtbos":1,"describe":1,"arch":1,"included":1,"various":1,"references":1,"earlier":1,"refer":1}
,"reference":{"boards":1,"board":1}
,"boards":{"include":1,"p2597":1}
,"customer":{"platforms":1,"pinmux":1}
,"platforms":{"need":1}
,"need":{"include":1,"procedure":1,"added":1,"add":1}
,"organization\u2019s":{"name":1}
,"board\u2019s":{"vendor":1,"pinmux":1}
,"root":{"device":1,"file":1,"port":1}
,"holds":{"platform\u2019s":1}
,"platform\u2019s":{"root":1,"design":1}
,"present":{"supported":1,"root":1}
,"supported":{"value":1}
,"schematic":{"differs":1}
,"differs":{"jetson":1}
,"change":{"pinmux":1,"filenames":1,"following":1,"properties":1,"power":1,"gpio":1,"setting":1,"usb":1,"nvidia":1,"uart":1,"uarta":1}
,"configuration":{"applied":1,"download":1,"board":1,"tab":1,"want":1,"data":1,"needs":1,"code":1,"files":1,"pins":1,"given":1,"changes":1,"uses":1,"file":1}
,"applied":{"software":1,"cboot":1,"follow":1}
,"define":{"board\u2019s":1,"config_tegra_board_string":1,"key":1,"config_tegra_enable_uarta":1,"config_tegra_enable_uartd":1}
,"download":{"jetson":1,"center":1,"linux":1}
,"table":{"jetson":1,"configuration":1}
,"center":{"customize":1}
,"customize":{"configuration":1,"pinmux":1}
,"create":{"copy":1,"device":1,"two":1}
,"copy":{"file":1,"need":1,"newly":1,"updated":1,"include":1,"arch":1,"configs":1,"board":1,".dts":1,"generated":1,"kernel":1,"copy":1,"linux_for_tegra":1}
,"based":{"board":1,"name":1,"schematic":1}
,"e.g":{"board":1,"gpio":1}
,"_pinmux.xlsm":{"note":1}
,"directory":{"stored":1,"spreadsheet":1,"contains":1,"board":1,"contain":1,"copy":1,"flashing":1,"instead":1,"name":1}
,"stored":{"copy":1,"macro":1}
,"procedure":{"updating":1,"guide":1}
,"updating":{"bootloader":1}
,"bootloader":{"pinmux":1,"uses":1,"target_board":1,"-------------":1,"binary":1,"images":1,"nvtboot.bin":1}
,"ensure":{"new":1}
,"new":{"file":1,"pinmux":1,"hardware":1,"sub-nodes":1}
,"windows":{"open":1,"host":1}
,"open":{"new":1}
,"microsoft":{"excel":1}
,"excel":{"displays":1}
,"displays":{"warnings":1}
,"warnings":{"protected":1}
,"protected":{"view":1}
,"view":{"security":1}
,"security":{"warning":1}
,"warning":{"click":1}
,"click":{"enable":1,"rename":1,"generate":1}
,"enable":{"editing":1,"content":1}
,"editing":{"enable":1}
,"content":{"save":1,"tegra210-":1,"generated":1}
,"save":{"changes":1}
,"changes":{"new":1,"due":1,"0x7721":1,"1x1":1}
,"rename":{"jetson":1,"menu":1,"copies":1}
,"tab":{"based":1,"bottom":1,"press":1}
,"right-click":{"jetson":1}
,"bottom":{"window":1}
,"menu":{"option":1}
,"type":{"board":1,"proc":1,"display":1,"pmu":1}
,"press":{"enter":1}
,"spreadsheet":{"columns":1,"reflects":1,"stored":1,"configure":1,"recommended":1,"modified":1,"remember":1,"contains":1}
,"columns":{"grouped":1}
,"grouped":{"heading":1}
,"heading":{"filled":1}
,"filled":{"customers":1}
,"customers":{"required":1}
,"required":{"pinmux":1,"device":1}
,"once":{"spreadsheet":1}
,"reflects":{"configuration":1}
,"want":{"click":1,"example":1,"override":1}
,"generate":{"file":1}
,"button":{"run":1}
,"run":{"macro":1}
,"macro":{"exports":1,"prompts":1}
,"exports":{"configuration":1}
,"data":{"pair":1,"follow":1,"limit":1}
,"pair":{".dtsi":1}
,".dtsi":{"files":1,"file":1}
,"prompts":{"enter":1}
,"prefix":{"files":1,"entered":1}
,"jetson-tx1-default":{"default":1,"filename":1}
,"cboot":{"bootloader":1,"reapplied":1,"cboot":1,"passes":1}
,"uses":{"device":1,"lines":1,"boardid":1,"eeprom":1,"configuration":1}
,"generated":{"pinmux":1,"device":1,"kernel":1,"dtb":1}
,"configure":{"pinmux":1,"kernel":1}
,"settings":{"device":1}
,"reapplied":{"linux":1}
,"updated":{"device":1}
,"rebuild":{"device":1}
,"image":{"jetson":1,"l4t":1,"boot":1,"following":1,"specific":1,"file":1}
,"update":{"device":1}
,"sources":{"instructions":1,"git":1,"topic":1,"downloaded":1,"provided":1}
,"instructions":{"section":1}
,"section":{"obtaining":1,"jetson":1,"basic":1,"looks":1,"5.1":1}
,"obtaining":{"kernel":1}
,"git":{"manually":1}
,"manually":{"downloading":1,"dts":1}
,"downloading":{"expanding":1}
,"expanding":{"kernel":1}
,"topic":{"kernel":1,"flashing":1,"u\u2011boot":1}
,"build":{"environment":1,"image":1}
,"environment":{"installing":1,"variable":1,"variables":1}
,"installing":{"toolchain":1}
,"toolchain":{"setting":1,"topic":1}
,"setting":{"environment":1,"check":1,"according":1,"optional":1}
,"variable":{"cross_compile":1,"settings":1}
,"cross_compile":{"described":1}
,"described":{"section":1}
,"commands":{"copy":1}
,"newly":{"generated":1}
,"host":{"proper":1,"accessible":1,"port":1,"mode":1,"machine":1}
,"proper":{"locations":1}
,"locations":{"linux":1}
,"src_path":{"hardware":1,"pathname":1,"kernel":1}
,"t210":{"jetson":1,"defaults":1,"auto":1}
,"kernel-dts":{"jetson-platforms":1}
,"dt_path":{"jetson-tx1-default-pinmux.dtsi":1,"jetson-tx1-default-gpio.dtsi":1,"pathname":1}
,"jetson-tx1-default-pinmux.dtsi":{"tegra210-jetson-cv-pinmux-p2597-2180-a00.dtsi":1}
,"jetson-tx1-default-gpio.dtsi":{"tegra210-jetson-cv-gpio-p2597-2180-a00.dtsi":1}
,"pathname":{"kernel":1,"directory":1,"windows":1}
,"downloaded":{"step":1}
,"filename":{"prefix":1}
,"entered":{"step":1}
,"step":{"customize":1}
,"recommended":{"default":1}
,"default":{"change":1,"configuration":1,"512byte":1}
,"contains":{"pinmux":1,"jetson":1,"processor":1}
,"remember":{"pathname":1}
,"accessible":{"linux":1}
,"arch":{"arm64":1,"arm":1}
,"arm64":{"tegra_defconfig":1,"dtbs":1,"boot":1}
,"release":{"tree":1,"24.x":1,"28.x":1,"32.x":1}
,"dts":{"tegra210-jetson-cv-":1,"tegra210-p2371-2180.dts":1,"tegra210-":1,"makefile":1,"names":1,"tegra210-jetson-cv-base-p2597-2180-a00.dts":1,"tegra210-platforms":1,"1.8":1}
,"tegra210-jetson-cv-":{".dtb":1,"function":1}
,".dtb":{"path-to-l4t-release":1,"arch":1}
,"path-to-l4t-release":{"kernel":1}
,"reflash":{"target":1,"kernel":1}
,"follow":{"instructions":1,"examples":1}
,"basic":{"flashing":1}
,"flashing":{"procedures":1,"booting":1,"build":1,"read":1,"software":1,"config":1,"script":1,"process":1}
,"booting":{"target":1}
,"perform":{"following":1,"secure":1}
,"actions":{"u-boot":1}
,"add":{"support":1,"tegra210-":1,"target":1,"remove":1,"entry":1,"&tegra_padctl_uphy":1,"utmi-3":1}
,"configs":{"jetson-p2371-2180.h":1,"board":1,"p2371-2180_defconfig":1,"p2371-2180.h":1}
,"jetson-p2371-2180.h":{"include":1}
,"edit":{"enabled":1,"board":1,"arch":1,"files":1,"kernel":1,"copy":1,".dtsi":1,"sysbootfile":1}
,"enabled":{"devices":1,"port":1,"lane":1}
,"devices":{"features":1,"parameters":1}
,"features":{"board":1}
,"config_tegra_board_string":{"nvidia":1}
,"arm":{"dts":1,"mach-tegra":1}
,"tegra210-p2371-2180.dts":{"arch":1}
,"tegra210-":{"board":1}
,"parameters":{"e.g":1,"want":1}
,"gpio":{"irq":1,"configurations":1,"setting":1,"pin":1,"&gpio":1}
,"irq":{"ids":1}
,"ids":{"tegra210-":1,"copied":1}
,".dts":{"appropriate":1,"board":1,"file":1,"files":1}
,"nodes":{"properties":1,"necessary":1}
,"properties":{"need":1,"differ":1,"change":1,"changed":1,"patch":1}
,"added":{"removed":1}
,"removed":{"edited":1}
,"always":{"exact":1,"tegra_padctl_pcie_lane_x4":1}
,"exact":{"device":1}
,"schema":{"bindings":1}
,"bindings":{"represent":1,"nvidia":1}
,"examples":{"u-boot":1,"linux":1,"modifications":1}
,"rather":{"linux":1,"p2371-2180":1,"u-boot":1}
,"p2371-2180_defconfig":{"configs":1}
,"_defconfig":{"refer":1}
,"mach-tegra":{"tegra210":1}
,"tegra210":{"kconfig":1}
,"kconfig":{"add":1}
,"config":{"kconfig":1,"file":1}
,"instances":{"p2371-2180":1}
,"maintainers":{"provide":1}
,"provide":{"correct":1,"plugin":1}
,"correct":{"maintainer":1,"pmic":1}
,"maintainer":{"contact":1}
,"contact":{"information":1}
,"information":{"board":1,".dts":1}
,"pmic":{"programming":1}
,"programming":{"board":1}
,"two":{"ways":1,"usb":1,"new":1,"sub-nodes":1}
,"ways":{"adapt":1}
,"adapt":{"device":1}
,"overlay":{"files":1}
,"u\u2011boot":{"adds":1,"load":1,"customization":1,"turn":1,"execute":1}
,"adds":{"kernel":1}
,"dtb":{"support":1,"sources":1,"replace":1,"recompiled":1,"following":1,"included":1,"selected":1,"partition":1,"execute":1,"platform":1}
,"recommends":{"technique":1,"file":1}
,"technique":{"types":1,"yields":1,"supporting":1}
,"types":{"hardware":1}
,"sensors":{"add-in":1}
,"add-in":{"boards":1,"hardware":1}
,"yields":{"complete":1}
,"complete":{"modified":1}
,"supporting":{"fixed":1}
,"fixed":{"hardware":1,"on-board":1}
,"custom-designed":{"carrier":1}
,"provided":{"bsp":1,"otherwise":1}
,"bsp":{"add":1}
,"remove":{"revise":1,"edit":1}
,"revise":{"kernel":1}
,"dtb\u2019s":{"hardware":1}
,"necessary":{"change":1}
,"differ":{"recompile":1}
,"recompile":{"dtb":1,"reflash":1}
,"replace":{"development":1,"content":1}
,"development":{"kit\u2019s":1,"kit":1}
,"kit\u2019s":{"dtb":1}
,"recompiled":{"reflash":1}
,"creating":{"device":1}
,"load":{"device":1}
,"dtbos":{"directly":1}
,"directly":{"extlinux.conf":1}
,"extlinux.conf":{"feature":1}
,"feature":{"lets":1}
,"lets":{"add":1}
,"cameras":{"controllers":1}
,"controllers":{"spi":1}
,"spi":{"without":1}
,"having":{"decompile":1}
,"decompile":{"modify":1}
,"customization":{"instructions":1}
,"distributed":{"configuration":1}
,"describe":{"platform\u2019s":1}
,"form":{"tegra210-jetson-cv-base-":1}
,"tegra210-jetson-cv-base-":{"board":1}
,"refers":{"nvidia":1}
,"included":{"describes":1,"file":1}
,"work":{"platform":1,"easier":1}
,"copies":{".dts":1,"correspond":1,"makes":1,".dtsi":1}
,"references":{"modify":1}
,"correspond":{"platform\u2019s":1}
,"guide":{"process":1,"external":1}
,"tegra210-platforms":{"directory":1,"tegra210-":1,"tegra210-jetson-cv-power-tree-p2597-2180-a00.dtsi":1,"tegra210-comms-p2530-0930.dtsi":1,"tegra210-keys-p2530-0930.dtsi":1}
,"makes":{"work":1}
,"copied":{"file":1}
,"-gpio.dtsi":{"tegra210-":1}
,"-pinmux.dtsi":{"content":1}
,"makefile":{"add":1}
,"entry":{"board":1}
,"modeled":{"existing":1}
,"linux_for_tegra":{"kernel":1,"jetson-tx1.conf":1,"board":1}
,"rel-28":{"releases":1}
,"releases":{"provide":1}
,"plugin":{"manager":1}
,"manager":{"support":1}
,"along":{"kernel":1}
,"instead":{"kernel":1}
,"selected":{"dtb":1}
,"partition":{"modified":1,"target":1,"size":1,"table":1}
,"passes":{"u\u2011boot":1,"kernel":1,"name":1}
,"turn":{"passes":1}
,"diluting":{"data":1}
,"flash":{"dtb":1,"u\u2011boot":1,"kernel":1,"build":1,"boardid":1,"application":1,"server":1}
,"execute":{"command":1,"following":1}
,"sudo":{"flash.sh":1}
,"flash.sh":{"dtb":1,"lnx":1,"platform":1,"board":1,"script":1}
,"lnx":{"platform":1}
,"optionally":{"perform":1}
,"secure":{"copy":1}
,"jetson-tx1.conf":{"linux_for_tegra":1}
,"sysbootfile":{"dtb_file":1}
,"dtb_file":{"board":1,"tegra210-jetson-tx1-p2597-2180-a02-devkit-24x7.dtb":1}
,".conf":{"refer":1,"modify":1,"file":1}
,"modifications":{"may":1}
,"vddio":{"sdmmc1":1}
,"sdmmc1":{"comes":1}
,"comes":{"pmu":1}
,"pmu":{"ldo2":1,"2180":1,"processor":1,"module":1}
,"ldo2":{"section":1}
,"regulator-name":{"vddio-sdmmc1":1}
,"power":{"tree":1,"detection":1,"jetson":1,"detect":1,"key":1,"management":1}
,"item":{"changed":1}
,"pad":{"power":1}
,"module\u2019s":{"t210":1}
,"defaults":{"3.3":1}
,"3.3":{"unlike":1}
,"unlike":{"jetson":1}
,"processors":{"t210":1}
,"auto":{"power":1}
,"detect":{"cells":1}
,"cells":{"pads":1}
,"pads":{"powered":1}
,"powered":{"1.8":1}
,"1.8":{"manually":1}
,"io-pad-init-voltage":{"io_pad_voltage_1_8v":1}
,"configurations":{"different":1}
,"different":{"hardware":1}
,"modules":{"change":1,"interrupt":1}
,"check":{"related":1}
,"related":{"device":1}
,"vdd":{"sdmmc":1}
,"sdmmc":{"controlled":1}
,"controlled":{"gpio":1,"xusb":1}
,"pin":{"gpio_pz3":1,"wifi_wake_ap":1,"wifi":1,"names":1}
,"gpio_pz3":{"power":1}
,"definition":{"part":1}
,"en_vdd_sd":{"regulator@4":1}
,"&gpio":{"tegra_gpio":1}
,"according":{"platform":1}
,"interrupt":{"requests":1,"request":1}
,"requests":{"interrupt":1,"declared":1}
,"declared":{".dts":1}
,"compatible":{"android":1}
,"android":{"bcmdhd_wlan":1}
,"interrupt-parent":{"&gpio":1}
,"interrupts":{"tegra_gpio":1}
,"tegra_gpio":{"0x14":1,"gpio_active_low":1}
,"wlan-pwr-gpio":{"&gpio":1}
,"status":{"okay":1,"disabled":1}
,"specifies":{"gpio_ph02":1,"function":1,"usb":1,"pcie":1}
,"gpio_ph02":{"pin":1}
,"wifi_wake_ap":{"interrupt":1}
,"request":{"pin":1}
,"key":{"defined":1,".dts":1,"special":1,"cannot":1,"file":1}
,"label":{"power":1}
,"gpios":{"&gpio":1}
,"gpio-key":{"wakeup":1}
,"meant":{"show":1}
,"show":{"define":1}
,"\u0027power":{"key":1}
,"special":{"key":1}
,"cannot":{"changed":1}
,"detailed":{"information":1}
,"documentation":{"documentation":1,"devicetree":1}
,"devicetree":{"bindings":1}
,"released":{"linux":1}
,"usb":{"lane":1,"3.0":1,"2.0":1,"configuration":1,"connector":1}
,"lane":{"mapping":1,"sharing":1,"number":1,"mapped":1,"usb_ss1":1,"usb":1,"owner":1,"xusb":1,"pex1":1,"map":1,"assign":1,"matches":1,"used":1,"nvidia":1}
,"mapping":{"required":1,"usb":1,"indicate":1,"indicates":1}
,"due":{"kernel":1}
,"24.x":{"r24":1}
,"r24":{"kernel":1,"required":1,"device":1,"example":1}
,"28.x":{"r28":1}
,"r28":{"kernel":1,"required":1,"device":1,"example":1}
,"32.x":{"r32":1}
,"r32":{"kernel":1}
,"3.0":{"superspeed":1,"shown":1,"lines":1,"available":1,"ports":1,"port":1,"por":1,"standalone":1,"usb":1,"pcie":1,"controller":1,"connector":1,"phys":1}
,"superspeed":{"ports":1,"port":1}
,"ports":{"used":1,"2.0":1,"controlled":1,"port":1,"without":1,"two":1,"mapped":1,"case":1,"usb_ss":1,"property":1}
,"used":{"implementation":1,"super-speed":1,"usb3.0":1,"standalone":1,"superspeed":1,"port":1,"usb":1,"pcie":1,"xusb":1,"m2.key":1,"sign":1,"encrypt":1}
,"implementation":{"lane":1}
,"sharing":{"pcie":1}
,"pcie":{"sata":1,"1_0":1,"0_3":1,"0_2":1,"0_1":1,"0_0":1,"disabled":1,"module":1,"configuration":1,"indicates":1,"controller":1,"port":1,"m2.key":1,"lanes":1}
,"sata":{"xusb":1,"ports":1}
,"xusb":{"possible":1,"controller":1,"used":1,"indicates":1,"usb2-m2":1,"usb2-standalone":1}
,"possible":{"combinations":1,"exception":1,"mappings":1,"values":1}
,"combinations":{"usb":1}
,"shown":{"tables":1,"below":1}
,"tables":{"below":1}
,"usb_ss":{"jetson":1,"port":1,"enabled":1}
,"available":{"outputs":1,"xusb":1,"single":1,"pcie":1}
,"outputs":{"jetson":1}
,"1x1":{"1x4":1,"1x1":1,"usb_ss":1,"change":1,"always":1}
,"ball":{"names":1}
,"determining":{"ball":1}
,"super-speed":{"connector":1,"lines":1,"port":1,"ports":1}
,"connector":{"pinmux":1,"usb":1,"possible":1,"carrier":1,"default":1,"standalone":1,"m2.key":1,"usb3-m2":1,"supports":1,"usb3-m2standalone":1}
,"given":{"section":1}
,"5.1":{"jetson":1}
,"oem":{"product":1}
,"product":{"design":1}
,"design":{"guide":1,"eeprom":1}
,"external":{"super-speed":1,"connector":1}
,"2.0":{"usb":1,"compatibility":1,"3.0":1,"ports":1,"port":1,"lines":1,"standalone":1,"controller":1}
,"lines":{"linked":1,"require":1,"usb":1,"available":1,"m2.key":1,"connector":1,"include":1}
,"linked":{"connector":1,"external":1}
,"exception":{"fixed":1}
,"on-board":{"device":1}
,"connected":{"super-speed":1}
,"require":{"usb":1,"mapping":1}
,"lists":{"ports":1}
,"bit":{"represents":1,"ports":1}
,"bits":{"0-7":1,"8-15":1,"16-23":1}
,"0-7":{"represent":1}
,"8-15":{"represent":1}
,"16-23":{"represent":1}
,"hsic":{"ports":1}
,"0x0e02":{"represents":1}
,"por":{"lines":1}
,"single":{"connector":1,"usb":1}
,"nibble":{"represents":1}
,"starting":{"lsb":1}
,"lsb":{"matching":1}
,"matching":{"usb":1,"lane":1}
,"0x7730":{"represents":1}
,"standalone":{"ports":1,"usb":1,"port":1,"sub":1}
,"valid":{"host":1,"usb":1}
,"mapped":{"single":1,"external":1}
,"role":{"may":1}
,"end-connector":{"mapping":1}
,"pex":{"hsio":1,"lanes":1}
,"hsio":{"pex":1,"lanes":1}
,"lanes":{"used":1,"available":1,"property":1,"case":1,"uphy-lane-0":1,"otg-3":1,"uphy-lane-3":1,"sub-node":1,"uphy-lane-1":1,"uphy-lane-4":1}
,"usb3.0":{"ports":1,"port":1,"port2":1}
,"0xf":{"port":1,"disable":1}
,"0xff56":{"represents":1,"becomes":1,"0xf":1}
,"matches":{"case":1,"valid":1}
,"mappings":{"superspeed":1,"super-speed":1,"super":1}
,"usb_ss1":{"pins":1,"usb":1}
,"pins":{"ball":1}
,"e41":{"e42":1}
,"e42":{"h41":1}
,"h41":{"h42":1}
,"h42":{"usb":1}
,"b42":{"b43":1}
,"b43":{"mapped":1}
,"indicate":{"lane":1,"usb":1}
,"ss_portmap":{"super-speed":1,"0x21":1,"0x321":1,"superspeed":1,"0x7721":1,"0x7221":1}
,"map":{"match":1,"modified":1}
,"match":{"usb":1}
,"sufficient":{"case":1}
,"matched":{"usb":1}
,"0x7721":{"0x7321":1,"0x7221":1}
,"portmap":{"control":1,"0x0e03":1,"0x0e07":1}
,"control":{"super-speed":1,"config":1,"superspeed":1,"table":1}
,"xhci":{"replacing":1}
,"replacing":{"0x0e03":1}
,"0x0e03":{"0x0e07":1}
,"lane_owner":{"lane":1,"0xff56":1,"0xf056":1,"0xf356":1}
,"owner":{"lane":1}
,"property":{"value":1,"indicates":1,"otg-":1,"uphy-lane-":1,"tegra_padctl_port_host_only":1,"usb":1,"present":1,"usb3-m2":1,"usb3-standalone":1}
,"becomes":{"0xf056":1,"0xf356":1}
,"lane-map":{"property":1,"0x14":1,"0x4":1,"0x12":1,"0x11":1}
,"indicates":{"pex":1,"lane":1,"port":1,"maximum":1}
,"configured":{"lane":1}
,"pex1":{"usb":1,"pins":1}
,"0x14":{"0x4":1,"0x11":1}
,"overall":{"device":1}
,"patch":{"case":1,"above":1}
,"xusb_pad_ctl":{"xusb_padctl":1}
,"xusb_padctl":{"put":1}
,"put":{"common":1}
,"common":{"control":1}
,"disable":{"lane":1,"pcie-m2":1,"pcie":1}
,"0xf056":{"0xf":1}
,"g42":{"g43":1}
,"g43":{"d42":1}
,"d42":{"d43":1}
,"d43":{"pcie":1}
,"1x4":{"1x1":1}
,"specify":{"valid":1,"uart":1}
,"0xf356":{"0xf":1}
,"common_padctl":{"&xusb_pad_ctl":1}
,"pinctrl@7009f000":{"pinmux":1}
,"identifies":{"lane":1,"phy":1}
,"otg-":{"number":1}
,"uphy-lane-":{"lane":1}
,"running":{"port":1,"host":1,"target":1}
,"values":{"include":1,"parameters":1,"board-specific":1}
,"usb3":{"indicates":1,"usb3-m2":1,"usb3-standalone":1}
,"mode":{"property":1}
,"bound":{"lane":1}
,"phy":{"handles":1,"names":1}
,"handles":{"usb":1}
,"phys":{"used":1,"phy-names":1,"add":1,"&tegra_padctl_uphy":1}
,"sequence":{"phys":1}
,"phy-names":{"match":1,"add":1,"utmi-2":1}
,"sub-node":{"pcie":1,"usb3-m2":1,"standalone":1,"nvidia":1,"case":1}
,"controller":{"parent":1}
,"parent":{"node":1}
,"pci@1,0":{"pci@2,0":1}
,"pci@2,0":{"pci@3,0":1}
,"pci@3,0":{"nodes":1}
,"maximum":{"link":1}
,"link":{"width":1}
,"width":{"root":1}
,"controller-0":{"0x4for":1}
,"0x4for":{"cases":1}
,"controller-1":{"0x1":1}
,"0x1":{"supported":1}
,"m2.key":{"pcie":1,"adding":1,"nvidia":1,"supports":1}
,"disabled":{"usb_ss":1,"pinctrl@7009f000":1}
,"pcie-m2":{"sub":1}
,"sub":{"node":1}
,"adding":{"status":1}
,"sub-nodes":{"pinctrl@7009f000":1,"usb2-m2":1,"usb":1,"usb2-standalone":1}
,"usb2-m2":{"represent":1,"sub-node":1,"nvidia":1,"usb3-m2":1}
,"usb3-m2":{"instance":1,"usb":1,"sub-nodes":1,"indicate":1,"sub-node":1}
,"instance":{"usb3.0":1}
,"uphy-lane-0":{"sub-node":1}
,"otg-3":{"usb2-m2":1,"usb2-":1}
,"port-cap":{"nvidia":1,"tegra_padctl_port_host_only":1}
,"tegra_padctl_port_host_only":{"usb2-m2":1,"usb2-standalone":1}
,"usb3-port":{"property":1,"usb3-m2.nvidia":1,"usb3-standalone":1}
,"usb3-m2.nvidia":{"ss_portmap":1}
,"usb2-map":{"nvidia":1,"match":1}
,"usb2-mapportmap":{"match":1}
,"&tegra_padctl_uphy":{"tegra_padctl_uphy_utmi_p":1,"tegra_padctl_uphy_usb3_p":1}
,"tegra_padctl_uphy_utmi_p":{"usb":1}
,"tegra_padctl_uphy_usb3_p":{"usb3.0":1}
,"utmi-3":{"usb":1,"usb3-2":1}
,"usb3-2":{"usb":1}
,"pcie-lane-select":{"tegra_padctl_pcie_lane_x1":1,"pcie":1}
,"utmi-2":{"usb3-1":1}
,"usb3-1":{"utmi-1":1}
,"utmi-1":{"usb3-0":1}
,"usb3-0":{"utmi-0":1}
,"super":{"speed":1}
,"speed":{"ports":1}
,"usb2-standalone":{"represent":1,"nvidia":1,"usb3-standalone":1}
,"usb3-standalone":{"instance":1,"sub-node":1,"sub-nodes":1,"indicate":1}
,"uphy-lane-3":{"usb3-standalone":1,"uphy-lane-4":1}
,"usb2-":{"standalone":1}
,"uphy-lane-1":{"uphy-lane-2":1}
,"uphy-lane-2":{"uphy-lane-3":1}
,"uphy-lane-4":{"uphy-lane-4":1}
,"usb3-m2standalone":{"sub-node":1}
,"tegra_padctl_pcie_lane_x4":{"controller":1}
,"above":{"case":1}
,"considerations":{"porting":1,"recommendations":1}
,"recommendations":{"consider":1}
,"consider":{"porting":1}
,"specific":{"board":1}
,"boardid":{"design":1,"either":1,"xml":1,"----------------":1,"override":1}
,"either":{"passed":1}
,"passed":{"using":1}
,"xml":{"file":1,"version":1}
,"during":{"flashing":1}
,"read":{"eeprom":1}
,"eeprom":{"flashing":1,"value":1,"values":1}
,"otherwise":{"uses":1}
,"board_config_p2597-devkit.xml":{"shown":1}
,"below":{"illustrates":1}
,"illustrates":{"xml":1}
,"tegra":{"board":1}
,"info":{"configuration":1}
,"2180":{"sku":1}
,"sku":{"1000":1,"0000":1}
,"1000":{"fab":1}
,"display":{"0000":1,"board":1,"power":1}
,"0000":{"sku":1}
,"p2371-2180-devkit.conf":{"passes":1}
,"bcffile":{"bootloader":1}
,"target_board":{"cfg":1}
,"cfg":{"board_config_p2597-devkit.xml":1}
,"processor":{"module":1,"pmu":1}
,"management":{"unit":1}
,"unit":{"type":1}
,"uart":{"port":1,"want":1}
,"odmdata":{"assignment":1,"0x60084000":1,"----------------":1,"used":1,"0x90000":1}
,"locate":{"following":1}
,"line":{"specify":1}
,"uarta":{"uartd":1}
,"debug_uartport":{"assignment":1,"lsport":1}
,"script":{"uses":1,"updates":1}
,"optional":{"environment":1}
,"updates":{"following":1}
,"variables":{"based":1,"values":1}
,"override":{"variables":1,"eeprom":1}
,"board-specific":{"file":1}
,"bctfile":{"----------------":1}
,"----------------":{"boot":1,"pass":1,"partition":1,"target":1,"device":1,"flash":1,"static":1,"nfsroot":1,"odmdata":1,"warmboot":1}
,"pass":{"boardid":1,"board_revision":1,"board_sku":1}
,"boardrev":{"---------------":1}
,"---------------":{"pass":1,"size":1,"flash":1}
,"board_revision":{"override":1}
,"boardsku":{"---------------":1}
,"board_sku":{"override":1}
,"-------------":{"bootloader":1,"mts":1,"linux":1}
,"binary":{"flashed":1}
,"bootpartlimit":{"----------":1}
,"----------":{"gpt":1}
,"gpt":{"data":1}
,"limit":{"max":1}
,"max":{"bct":1}
,"bct":{"size":1}
,"size":{"ppt":1,"default":1,"target":1,"internal":1}
,"ppt":{"size":1}
,"bootpartsize":{"-----------":1}
,"-----------":{"total":1,"linux":1}
,"total":{"emmc":1}
,"emmc":{"boot":1,"boot0":1,"nand":1}
,"cfgfile":{"----------------":1}
,"cmdline":{"----------------":1,"help":1}
,"help":{"information":1}
,"devsectsize":{"------------":1}
,"------------":{"device":1}
,"sector":{"size":1}
,"dtbfile":{"----------------":1}
,"emmcsize":{"---------------":1}
,"boot0":{"boot1":1}
,"boot1":{"user":1}
,"flashapp":{"---------------":1}
,"application":{"running":1}
,"flasher":{"----------------":1}
,"server":{"running":1}
,"initrd":{"-----------------":1,"image":1}
,"-----------------":{"initrd":1,"rsa":1,"sbk":1}
,"kernel_image":{"-----------":1}
,"zimage":{"file":1}
,"mts":{"--------------------":1,"file":1,"preboot":1}
,"--------------------":{"mts":1,"target":1}
,"mtspreboot":{"-------------":1}
,"preboot":{"file":1}
,"nfsargs":{"----------------":1}
,"static":{"network":1}
,"network":{"assignments":1}
,"c-ipa":{"s-ipa":1}
,"s-ipa":{"g-ipa":1}
,"g-ipa":{"netmask":1}
,"nfsroot":{"----------------":1,"i.e":1}
,"i.e":{"addr":1}
,"addr":{"exported":1}
,"exported":{"rootfs_dir":1}
,"pkckey":{"-----------------":1}
,"rsa":{"key":1}
,"sign":{"bootloader":1}
,"rootfssize":{"-------------":1}
,"rootfs":{"size":1,"directory":1}
,"internal":{"emmc":1}
,"rootfs_dir":{"-------------":1}
,"sbkkey":{"-----------------":1}
,"sbk":{"key":1}
,"encrypt":{"bootloader":1}
,"fab":{"--------------------":1}
,"board\u0027s":{"fab":1}
,"tegraboot":{"--------------":1}
,"--------------":{"lowerlayer":1}
,"lowerlayer":{"bootloader":1}
,"wb0boot":{"----------------":1}
,"warmboot":{"code":1}
,"ldk_dir":{"p2371-2180-devkit.conf":1}
}
;Search.control.loadWordPairs(pairs);
