var pairs =
{
"configuring":{"jetson":1,"production":1,"pins":1,"csi":1}
,"jetson":{"expansion":1,"developer":1,"tx2":1,"tx1":1,"platform":1,"xavier":1,"nano":1,"agx":1,"devices":1,"device":1,"soc":1,"module":1,"platforms":1,"40pin":1,"30pin":1,"m.2":1,"overlay":1}
,"expansion":{"header":1,"headers":1}
,"developer":{"kit":1,"kits":1}
,"kit":{"includes":1,"off-the-shelf":1,"lets":1,"rebooted":1,"main":1,"apply":1,"displays":1,"module":1,"command":1,"display":1,"a02":1}
,"includes":{"several":1}
,"several":{"expansion":1}
,"headers":{"connectors":1,"available":1,"applied":1,"supported":1,"redisplays":1,"command":1,"lists":1,"hfs":1,"interface":1,"simplest":1}
,"connectors":{"collectively":1}
,"collectively":{"headers":1}
,"40\u2011pin":{"expansion":1,"header":1}
,"header":{"lets":1,"nvidia":1,"similar":1,"available":1,"tool":1,"screen":1,"jetson":1,"looks":1,"pins":1,"configuration":1,"certain":1,"supports":1,"screen\u2019s":1,"displays":1,"configurations":1,"number":1,"numbers":1,"specified":1,"option":1,"pin":1,"special":1,"hardware":1,"configured":1,"create":1,"default":1,"needed":1,"enter":1}
,"lets":{"connect":1,"change":1,"select":1,"specify":1,"configure":1}
,"connect":{"jetson":1}
,"off-the-shelf":{"raspberry":1}
,"raspberry":{"hats":1}
,"hats":{"hardware":1}
,"hardware":{"attached":1,"displays":1,"screen":1,"modules":1,"module":1,"add":1,"jetson\u2011io":1,"add-ons":1,"configurations":1,"adding":1}
,"attached":{"top":1,"header":1}
,"top":{"seeed":1}
,"seeed":{"grove":1}
,"grove":{"modules":1}
,"modules":{"sparkfun":1,"attached":1,"jetson":1,"hds":1,"updates":1,"handled":1}
,"sparkfun":{"qwiic":1}
,"qwiic":{"products":1}
,"products":{"others":1}
,"others":{"pins":1}
,"pins":{"used":1,"jetson":1,"manually":1,"associated":1,"complete":1,"creates":1,"defined":1}
,"used":{"either":1,"gpio":1,"together":1,"enables":1}
,"either":{"gpio":1,"menu-oriented":1}
,"gpio":{"special":1}
,"special":{"function":1,"functions":1}
,"function":{"sfio":1,"pressing":1,"specified":1}
,"sfio":{"i2c":1}
,"i2c":{"i2s":1}
,"30\u2011pin":{"expansion":1,"connector":1}
,"nvidia":{"custom":1,"jetson":1,"provides":1,"jetson-io":1,"p3509-0000":1,"p3449-0000-a02":1,"p3449-0000-b00":1,"p3542-0000":1,"p2597-0000":1,"p2822-0000":1}
,"custom":{"header":1,"configurations":1,"hardware":1,"property":1,"device":1}
,"similar":{"40-pin":1}
,"40-pin":{"header":1,"expansion":1}
,"available":{"nvidia":1,"jetson":1,"supported":1,"hardware":1}
,"tx2":{"jetson":1,"series":1,"csi":1}
,"tx1":{"platforms":1,"tx2":1}
,"platforms":{"pins":1,"supported":1}
,"csi":{"connector":1,"nano":1}
,"connector":{"30\u2011pin":1,"jetson":1,"csi":1,"lets":1,"screen":1}
,"m.2":{"key":1}
,"key":{"slot":1}
,"table":{"shows":1,"describes":1}
,"shows":{"expansion":1,"pins":1,"save":1}
,"30-pin":{"header":1,"expansion":1}
,"nano":{"a02":1,"2gb":1,"devices":1,"connector":1,"developer":1,"example":1,"4gb":1,"csi":1,"device":1,"b0x":1}
,"a02":{"b0x":1,"carrier":1,"module":1,"enables":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"jetson":1,"csi":1,"developer":1,"production":1}
,"jetson-io":{"identifies":1,"jetson-io.py":1,"displays":1,"redisplays":1,"config-by-pin.py":1,"config-by-function.py":1,"config-by-hardware.py":1}
,"identifies":{"csi":1,"pcb":1}
,"devices":{"csi":1,"standard":1,"module":1}
,"standard":{"128\u2011pin":1}
,"128\u2011pin":{"connector":1}
,"configuration":{"pins":1,"directly":1,"jetson":1,"expansion":1,"selected":1,"screen":1,"jetson\u2011io":1,"reflect":1,"returns":1,"changes":1,"original":1,"option":1,"new":1,"topic":1,"select":1,"file":1,"rebooting":1,"pin":1,"supported":1,"display":1,"displayed":1,"overlay":1,"saved":1}
,"kits":{"statically":1}
,"statically":{"defined":1}
,"defined":{"programmed":1,"headers":1}
,"programmed":{"device":1}
,"device":{"flashed":1,"tree":1,"example":1,"given":1}
,"flashed":{"change":1}
,"change":{"pin":1}
,"pin":{"configuration":1,"configurations":1,"changes":1,"functions":1,"header":1,"expansion":1}
,"directly":{"update":1}
,"update":{"pinmux":1}
,"pinmux":{"spreadsheet":1}
,"spreadsheet":{"platform":1}
,"platform":{"flash":1,"header\u2019s":1,"entering":1,"following":1}
,"flash":{"new":1}
,"new":{"configuration":1,"state":1,"device":1,"dtb":1,"option":1,"custom":1,"overlay":1}
,"suitable":{"means":1}
,"means":{"configuring":1}
,"production":{"systems":1,"module":1}
,"systems":{"development":1,"inconvenient":1}
,"development":{"systems":1}
,"inconvenient":{"therefore":1}
,"therefore":{"nvidia":1}
,"provides":{"jetson":1,"command":1}
,"tool":{"known":1}
,"known":{"jetson\u2011io":1}
,"jetson\u2011io":{"python":1,"modifies":1,"enter":1,"displays":1,"returns":1,"redisplays":1,"preserves":1,"support":1,"understand":1,"manages":1,"finds":1,"configure":1,"script":1}
,"python":{"script":1}
,"script":{"runs":1,"associated":1}
,"runs":{"jetson":1}
,"configurations":{"graphic":1,"hardware":1,"interfacing":1,"shown":1,"updates":1,"saved":1,"addition":1,"time":1,"configures":1,"found":1}
,"graphic":{"user":1}
,"user":{"interface":1}
,"interface":{"jetson\u2011io":1,"specified":1,"40\u2011pin":1}
,"modifies":{"device":1}
,"tree":{"blob":1,"overlay":1,"overlays":1,"source":1}
,"blob":{"dtb":1}
,"dtb":{"firmware":1,"file":1,"applying":1,"updates":1,"dtbo":1,"device":1,"creates":1,"i2s4":1,"my-overlay.dtbo":1,"dts":1}
,"firmware":{"new":1,"devicetree":1}
,"applied":{"developer":1}
,"running":{"jetson-io":1}
,"launch":{"jetson\u2011io":1}
,"enter":{"command":1,"space":1,"following":1}
,"command":{"developer":1,"line":1,"jetson":1,"identifies":1,"compile":1}
,"sudo":{"opt":1,"my-overlay.dtbo":1}
,"opt":{"nvidia":1}
,"main":{"screen":1,"menu":1}
,"screen":{"selecting":1,"lists":1,"looks":1,"configure":1,"displays":1,"40-pin":1,"offers":1,"lets":1,"40\u2011pin":1,"updates":1,"main":1,"save":1,"above":1,"updated":1,"shows":1,"plus":1,"allows":1,"original":1}
,"selecting":{"header":1}
,"displays":{"main":1,"current":1,"compatible":1,"expansion":1,"list":1,"different":1,"csi":1,"name":1,"additional":1,"menu":1,"usage":1,"configures":1}
,"lists":{"expansion":1,"headers":1,"functions":1}
,"supported":{"jetson":1,"functions":1,"headers":1,"target":1,"hardware":1}
,"example":{"jetson":1,"header":1,"compatible":1,"expansion":1,"external":1,"consider":1,"create":1}
,"select":{"options":1,"list":1,"configuration":1,"back":1,"configure":1,"save":1,"header":1,"current":1}
,"options":{"display":1,"configuring":1,"header":1,"described":1,"specify":1,"specified":1}
,"display":{"header":1,"options":1,"properties":1}
,"configure":{"selected":1,"compatible":1,"header":1,"jetson":1,"30\u2011pin":1,"reconfigure":1,"headers":1}
,"selected":{"header":1,"functions":1,"header\u2019s":1}
,"current":{"configuration":1,"older":1}
,"offers":{"two":1}
,"two":{"options":1}
,"compatible":{"hardware":1,"property":1,"string":1,"properties":1,"nvidia":1}
,"list":{"configurations":1,"special":1,"compatible":1,"functions":1,"supported":1,"available":1}
,"manually":{"displays":1}
,"specify":{"functions":1,"part":1,"header":1,"hfs":1,"hds":1,"values":1}
,"functions":{"enable":1,"selected":1,"parentheses":1,"highlight":1,"technical":1,"select":1,"header":1,"available":1,"supported":1,"enabled":1,"currently":1,"headers":1}
,"enable":{"header":1}
,"back":{"returns":1,"return":1,"jetson\u2011io":1}
,"returns":{"main":1,"header":1}
,"interfacing":{"selected":1}
,"certain":{"hardware":1}
,"updates":{"header":1,"configuration":1,"extlinux.conf":1,"linux":1}
,"reflect":{"hardware":1,"new":1}
,"module":{"selected":1,"configurations":1,"hardware":1,"header":1,"alone":1,"creating":1,"following":1,"define":1,"unique":1,"associated":1,"carrier":1,"example":1,"sku":1,"target\u2019s":1,"attach":1,"attaches":1,"requires":1}
,"different":{"options":1}
,"save":{"pin":1,"below":1,"selection":1,"reboot":1,"exit":1}
,"changes":{"saves":1,"discards":1,"redisplays":1,"discard":1,"options":1,"save":1,"header":1,"option":1,"made":1}
,"saves":{"header\u2019s":1}
,"header\u2019s":{"new":1,"configuration":1,"header":1}
,"discard":{"pin":1}
,"discards":{"header\u2019s":1,"changes":1}
,"redisplays":{"prior":1,"header":1,"main":1}
,"prior":{"configuration":1}
,"original":{"options":1}
,"above":{"select":1}
,"option":{"again":1,"configure":1,"jetson-io":1,"used":1,"boot":1,"generates":1}
,"again":{"select":1}
,"return":{"main":1}
,"supports":{"shows":1,"specify":1}
,"associated":{"functions":1,"specify":1,"config-by-":1}
,"parentheses":{"jetson":1}
,"toggle":{"pin":1}
,"highlight":{"function":1}
,"pressing":{"up-arrow":1}
,"up-arrow":{"down-arrow":1}
,"down-arrow":{"keys":1}
,"keys":{"press":1}
,"press":{"enter":1}
,"space":{"bar":1}
,"details":{"supported":1}
,"technical":{"reference":1}
,"reference":{"manual":1}
,"manual":{"jetson":1}
,"soc":{"developer":1}
,"accept":{"selected":1}
,"updated":{"reflect":1,"new":1}
,"state":{"selected":1}
,"described":{"section":1,"depending":1,"below":1}
,"section":{"compatible":1}
,"plus":{"additional":1}
,"additional":{"option":1,"options":1,"nodes":1}
,"export":{"device-tree":1,"configuration":1}
,"device-tree":{"overlay":1}
,"overlay":{"exports":1,"dtbo":1,"file":1,"hardware":1,"files":1,"others":1,"supports":1,"add":1,"custom":1,"either":1,"jetson":1,"device":1}
,"exports":{"selected":1}
,"dtbo":{"stores":1,"hfs":1,"--out":1,"creates":1,"i2s4":1}
,"stores":{"file":1}
,"file":{"boot":1,"modified":1,"booting":1,"just":1,"linux":1,"reconfigured":1,"specified":1,"named":1,"overlay":1,"allows":1,"entering":1}
,"boot":{"directory":1,"extlinux":1,"allowing":1,"configuration":1,"using":1,"tegra210-p3448-0000-p3449-0000-a02-fe-pi-audio.dtbo":1,"tegra210-p3448-0000-p3449-0000-a02-hdr40-user-custom.dtbo":1,"kernel_tegra210-p3448-0000-p3449-0000-a02-hdr40-user-custom.dtbo":1}
,"applies":{"jetson":1}
,"menu":{"option":1,"select":1,"configurations":1}
,"add":{"custom":1,"support":1,"new":1}
,"shown":{"kernel":1}
,"kernel":{"configuration":1}
,"topic":{"sensor":1}
,"sensor":{"software":1}
,"software":{"driver":1}
,"driver":{"programming":1}
,"selection":{"made":1}
,"reboot":{"reconfigure":1,"device":1,"reboot":1,"developer":1}
,"reconfigure":{"pins":1,"header":1}
,"complete":{"reconfiguration":1}
,"name":{"dtb":1,"hardware":1,"distinguishes":1}
,"modified":{"prompts":1}
,"prompts":{"reboot":1}
,"finished":{"making":1}
,"making":{"changes":1}
,"screen\u2019s":{"save":1}
,"allows":{"configure":1,"apply":1}
,"creates":{"new":1,"device":1}
,"applying":{"device":1}
,"overlays":{"header":1,"incorporating":1}
,"booting":{"linux":1}
,"linux":{"boot":1}
,"extlinux":{"extlinux.conf":1,"\u200Cextlinux.conf":1}
,"extlinux.conf":{"reboots":1,"save":1}
,"reboots":{"developer":1}
,"exit":{"without":1}
,"without":{"rebooting":1}
,"rebooting":{"creates":1,"time":1}
,"apply":{"new":1}
,"time":{"choice":1,"boot":1}
,"made":{"headers":1}
,"preserves":{"configurations":1}
,"saved":{"configuration":1,"configurations":1,"boot":1}
,"just":{"latest":1}
,"latest":{"saved":1}
,"addition":{"default":1}
,"default":{"developer":1,"jetson":1}
,"allowing":{"select":1}
,"line":{"interface":1,"instead":1,"utilities":1,"options":1,"option":1,"tools":1}
,"prefer":{"configure":1}
,"instead":{"menus":1}
,"menus":{"nvidia":1}
,"utilities":{"offer":1,"header":1}
,"offer":{"functionality":1}
,"functionality":{"following":1}
,"following":{"sections":1,"table":1,"command":1,"contents":1}
,"sections":{"describe":1}
,"describe":{"utilities":1,"process":1}
,"config-by-pin":{"view":1}
,"view":{"header":1,"overlay-name":1}
,"config-by-pin.py":{"options":1}
,"part":{"configuration":1}
,"specified":{"entire":1,"header":1,"hardware":1}
,"entire":{"configuration":1}
,"describes":{"command":1}
,"usage":{"message":1}
,"message":{"exits":1}
,"target":{"platform":1}
,"number":{"command":1,"header":1,"defaults":1,"e.g":1}
,"numbers":{"refer":1}
,"refer":{"specific":1}
,"specific":{"headers":1}
,"specifies":{"header":1,"name":1,"expansion":1}
,"defaults":{"currently":1}
,"currently":{"represents":1,"enabled":1}
,"represents":{"40\u2011pin":1}
,"together":{"specify":1}
,"config-by-function":{"configure":1}
,"configures":{"functions":1,"jetson":1,"headers":1}
,"config-by-function.py":{"enabled":1,"dtb":1,"dtbo":1}
,"hfs":{"hfs":1,"forms":1}
,"enabled":{"--list":1,"lists":1,"header":1}
,"--list":{"enabled":1}
,"--out":{"dtb":1}
,"incorporating":{"configuration":1}
,"\u200Cextlinux.conf":{"updated":1,"new":1}
,"using":{"dtb":1}
,"reconfigured":{"header":1}
,"enables":{"functions":1,"i2s":1}
,"quotation":{"marks":1}
,"marks":{"may":1}
,"may":{"omitted":1}
,"omitted":{"function":1}
,"forms":{"configure":1}
,"i2s4":{"spi1":1}
,"spi1":{"dmic2":1}
,"config-by-hardware":{"configure":1}
,"given":{"hardware":1}
,"config-by-hardware.py":{"hds":1,"adafruit":1,"jetson":1}
,"hds":{"hds":1,"\u2011name":1,"form":1,"module":1}
,"\u2011name":{"hds":1}
,"alone":{"configure":1}
,"generates":{"new":1}
,"adafruit":{"sph0645lm4h":1,"uda1334a":1}
,"adding":{"support":1,"additional":1}
,"support":{"custom":1,"hardware":1}
,"creating":{"device":1,"simple":1,"custom":1}
,"understand":{"jetson\u2011io":1}
,"manages":{"hardware":1}
,"add-ons":{"support":1}
,"handled":{"device":1}
,"files":{".dtbo":1,"names":1,"view":1}
,".dtbo":{"files":1}
,"overlay-name":{"property":1,"jetson-header-name":1,"jetson":1}
,"property":{"specifies":1,"indicates":1,"values":1,"jetson":1}
,"unique":{"name":1}
,"distinguishes":{"overlay":1}
,"jetson-header-name":{"property":1,"compatible":1,"jetson":1}
,"values":{"described":1}
,"depending":{"header":1,"jetson":1}
,"indicates":{"combination":1}
,"combination":{"jetson":1}
,"carrier":{"board":1}
,"board":{"overlay":1,"a02":1}
,"below":{"depending":1}
,"special-function":{"pins":1}
,"nodes":{"properties":1}
,"properties":{"devices":1,"example":1,"entering":1,"hardware":1}
,"external":{"integrated":1}
,"integrated":{"circuits":1}
,"circuits":{"audio":1}
,"audio":{"codecs":1,"module":1}
,"40pin":{"header":1}
,"30pin":{"header":1}
,"sku":{"0000":1,"0001":1}
,"p3509-0000":{"p3668-0000":1,"p3668-0001":1}
,"p3449-0000-a02":{"p3448-0000-a02":1}
,"p3449-0000-b00":{"p3448-0000-b00":1}
,"p3542-0000":{"p3448-0003":1}
,"p2597-0000":{"p3310-1000":1,"p2180-1000":1}
,"p2822-0000":{"p2888-0001":1}
,"users":{"obtain":1}
,"obtain":{"correct":1}
,"correct":{"compatible":1}
,"string":{"jetson":1}
,"entering":{"following":1,"command":1}
,"pcb":{"revision":1}
,"cat":{"sys":1}
,"sys":{"firmware":1}
,"devicetree":{"base":1}
,"base":{"compatible":1}
,"consider":{"fe-pi":1}
,"fe-pi":{"audio":1}
,"target\u2019s":{"boot":1}
,"directory":{"overlay":1,"jetson\u2011io":1}
,"names":{"matching":1}
,"matching":{"pattern":1}
,"fdtdump":{"utility":1,"boot":1}
,"utility":{"inspect":1}
,"inspect":{"contents":1}
,"contents":{"overlay":1}
,"simple":{"device":1}
,"create":{"simple":1,"file":1,"overlay":1}
,"attach":{"40\u2011pin":1}
,"named":{"my-overlay.dts":1}
,"my-overlay.dts":{"target":1,"boot":1}
,"my-custom-property":{"overlay":1}
,"compile":{"dts":1}
,"dts":{"source":1,"my-overlay.dts":1}
,"source":{"file":1,"necessary":1,"place":1}
,"dtc":{"dtb":1}
,"my-overlay.dtbo":{"my-overlay.dts":1,"boot":1}
,"copy":{"new":1}
,"finds":{"overlay":1}
,"mcp251x":{"controller":1}
,"respeaker":{"mic":1}
,"mic":{"array":1}
,"want":{"create":1}
,"attaches":{"supported":1}
,"simplest":{"jetson\u2011io":1}
,"needed":{"export":1}
,"menu-oriented":{"jetson\u2011io":1}
,"config-by-":{"command":1}
,"i2s":{"interface":1}
,"convert":{"overlay":1}
,"modify":{"generated":1}
,"generated":{"device":1}
,"necessary":{"custom":1}
,"requires":{"re-compile":1}
,"re-compile":{"device":1}
,"place":{"boot":1}
}
;Search.control.loadWordPairs(pairs);
