var pairs =
{
"eglstream":{"mechanism":1,"architecture":1,"producers":1,"producer":1,"correct":1,"egl":1,"consumers":1,"consumer":1,"operation":1,"operates":1,"conceptually":1,"attribute":1,"retrieve":1,"sets":1,"gets":1,"fifo":1,"pipeline":1,"cannot":1,"may":1,"bind":1,"eglstreamcube.c":1,"connected":1,"destroyed":1,"nvgldemo_main.c":1,"without":1,"state":1,"created":1,"i.e":1,"just":1,"whose":1,"sends":1,"file":1,"example":1,"opengl":1,"surface":1}
,"mechanism":{"efficiently":1}
,"efficiently":{"transfers":1}
,"transfers":{"sequence":1}
,"sequence":{"image":1}
,"image":{"frames":1,"frame":1}
,"frames":{"api":1,"stream":1,"eglstream":1,"deliver":1,"processed":1,"bound":1,"render":1,"eglswapbuffers":1}
,"api":{"e.g":1}
,"e.g":{"opengl":1}
,"opengl":{"cuda":1,"producers":1,"consumers":1,"textures":1,"consumer":1,"producer":1,"texture":1}
,"architecture":{"producer":1}
,"producer":{"consumer":1,"adds":1,"posts":1,"responsible":1,"new":1,"eglstream":1,"controls":1,"attempts":1,"blocks":1,"connected":1,"appropriate":1,"remains":1,"until":1,"case":1,"uses":1,"producer":1,"posted":1,"inserts":1,"process":1,"receives":1,"processes":1,"created":1,"socket":1,"application":1}
,"consumer":{"attached":1,"retrieves":1,"display":1,"responsible":1,"applicable":1,"finished":1,"operates":1,"notice":1,"eglstream":1,"image":1,"uses":1,"producer":1,"first":1,"once":1,"remains":1,"egloutput":1,"initialize":1,"appropriate":1,"until":1,"order":1,"acquires":1,"case":1,"connected":1,"acquired":1,"longer":1,"begins":1,"destroyed":1,"different":1,"process":1,"application":1,"end":1}
,"attached":{"end":1}
,"end":{"stream":1,"eglstream":1}
,"stream":{"object":1,"consumer":1,"time":1,"fifo":1,"eglcreatestreamkhr":1,"egl_no_stream_khr":1,"methods":1,"releasing":1,"dependent":1,"file":1,"eglstreamcube.c":1,"nvgldemo_main.c":1}
,"object":{"producer":1,"eglstream":1}
,"adds":{"image":1}
,"retrieves":{"image":1,"egl":1}
,"posts":{"egl":1,"image":1,"buffer":1,"new":1}
,"egl":{"image":1,"provides":1,"display":1,"stream":1}
,"responsible":{"inserting":1,"noticing":1,"latency":1}
,"inserting":{"image":1,"stream":1}
,"frame":{"eglstream":1,"appropriate":1,"available":1,"time":1,"retrieval":1,"information":1,"empties":1,"mailbox":1,"either":1,"back":1,"displayed":1,"queue":1,"immediately":1,"last":1,"inserted":1,"intended":1,"posted":1,"opengl":1,"consumer":1,"texture":1}
,"correct":{"time":1,"result":1}
,"time":{"consumer":1,"elapsed":1,"indicated":1,"egl_consumer_latency_usec_khr":1,"image":1,"eglstream":1,"producer":1}
,"display":{"image":1,"time":1}
,"appropriate":{"period":1,"type":1}
,"period":{"time":1}
,"two":{"types":1,"modes":1}
,"types":{"producers":1,"consumers":1}
,"cuda":{"producers":1,"array":1,"pointer":1,"consumers":1,"frames":1,"domain":1,"producer-consumer":1}
,"producers":{"post":1,"consumers":1}
,"post":{"cuda":1,"graphic":1}
,"array":{"cuda":1}
,"pointer":{"eglstream":1,"cuda":1}
,"graphic":{"surfaces":1}
,"surfaces":{"eglstream":1}
,"noticing":{"image":1}
,"available":{"displaying":1,"eglstream":1}
,"displaying":{"otherwise":1}
,"otherwise":{"consuming":1}
,"consuming":{"consumer":1}
,"latency":{"acquired":1,"indicates":1}
,"acquired":{"frame":1,"recently":1}
,"elapsed":{"image":1}
,"retrieval":{"display":1,"consumer":1}
,"three":{"types":1}
,"consumers":{"retrieve":1,"egldevice":1}
,"retrieve":{"egl":1,"display":1}
,"deliver":{"frame":1}
,"information":{"cuda":1}
,"processed":{"cuda":1}
,"bound":{"opengl":1}
,"textures":{"graphics":1}
,"graphics":{"rendering":1}
,"egloutput":{"consumers":1,"egloutput":1,"consumer":1,"used":1}
,"egldevice":{"window":1}
,"window":{"system":1,"create":1}
,"system":{"retrieve":1,"initialization":1,"resources":1}
,"render":{"directly":1}
,"directly":{"egloutput":1}
,"applicable":{"egloutput":1}
,"used":{"egldevice":1,"until":1}
,"operation":{"modes":1}
,"operates":{"two":1,"mailbox":1,"fixed":1}
,"modes":{"mailbox":1}
,"mailbox":{"mode":1,"producer":1,"discards":1,"consumer":1,"examines":1,"mailbox":1,"empty":1}
,"mode":{"fifo":1,"eglstream":1,"images":1,"responsibility":1,"attribute":1}
,"fifo":{"mode":1,"queue":1,"mailbox":1}
,"conceptually":{"operates":1}
,"new":{"image":1,"egl":1}
,"empties":{"mailbox":1}
,"discards":{"old":1,"mailbox":1}
,"old":{"contents":1}
,"contents":{"inserts":1}
,"inserts":{"new":1,"egl":1}
,"examines":{"consumer":1}
,"finished":{"examining":1}
,"examining":{"image":1}
,"either":{"puts":1}
,"puts":{"frame":1}
,"back":{"mailbox":1,"stream":1}
,"empty":{"discards":1}
,"timing":{"mainly":1,"eglstream":1}
,"mainly":{"controlled":1}
,"controlled":{"producer":1}
,"fixed":{"latency":1}
,"indicates":{"producer":1}
,"attribute":{"egl_consumer_latency_usec_khr":1,"egl_stream_fifo_length_khr":1}
,"egl_consumer_latency_usec_khr":{"consumer":1,"producer":1,"time":1}
,"notice":{"new":1}
,"indicated":{"egl_consumer_latency_usec_khr":1}
,"controls":{"image":1}
,"displayed":{"inserting":1}
,"images":{"discarded":1}
,"discarded":{"producer":1}
,"queue":{"subsequent":1,"size":1,"producer":1,"full":1,"consumer":1,"timestamp":1}
,"subsequent":{"retrieval":1}
,"sets":{"queue":1}
,"size":{"creates":1}
,"creates":{"queue":1,"eglstream":1,"corresponding":1,"stream":1,"instance":1}
,"attempts":{"insert":1}
,"insert":{"frame":1}
,"full":{"producer":1}
,"blocks":{"until":1}
,"until":{"room":1,"connected":1,"destroyed":1,"eglstream":1}
,"room":{"queue":1}
,"gets":{"image":1,"file":1}
,"immediately":{"follows":1}
,"follows":{"image":1}
,"last":{"retrieved":1,"time":1}
,"retrieved":{"unless":1}
,"unless":{"frame":1}
,"inserted":{"case":1}
,"case":{"retrieves":1,"eglswapbuffers":1,"eglstreamcube.c":1,"application":1}
,"responsibility":{"consumer":1}
,"timestamp":{"producer":1,"determine":1}
,"uses":{"timestamp":1,"releases":1}
,"determine":{"image":1}
,"intended":{"displayed":1}
,"provides":{"functions":1,"pair":1}
,"functions":{"create":1}
,"create":{"destroy":1,"egldisplay":1,"eglstream":1,"egl":1,"consumer":1,"producer":1,"stream":1}
,"destroy":{"eglstreams":1,"eglstream":1,"producer":1,"consumer":1,"window":1}
,"eglstreams":{"query":1,"connect":1,"producers":1,"created":1}
,"query":{"attributes":1,"eglstream\u2019s":1}
,"attributes":{"eglstreams":1}
,"connect":{"eglstreams":1,"eglstream":1}
,"cannot":{"used":1}
,"connected":{"consumer":1,"producer":1,"entity":1,"eglstream":1,"eglstreams":1}
,"may":{"connected":1}
,"once":{"connected":1,"eglstream":1}
,"remains":{"connected":1,"state":1}
,"entity":{"until":1}
,"build":{"simple":1,"cross-process":1}
,"simple":{"eglstream":1}
,"egldisplay":{"object":1,"dpy":1}
,"call":{"eglinitialize":1,"eglstreamconsumerreleasekhr":1}
,"eglinitialize":{"initialize":1}
,"initialize":{"egl":1,"rendering":1}
,"rendering":{"window":1,"frames":1}
,"producer-consumer":{"window":1}
,"initialization":{"required":1}
,"example":{"creating":1,"connecting":1,"acquiring":1,"communication":1}
,"creating":{"eglstream":1}
,"client-":{"stream":1,"eglgetstreamfiledescriptorkhr":1}
,"eglcreatestreamkhr":{"demostate.display":1}
,"demostate.display":{"streamattr":1,"client-":1,"stream":1}
,"nvgldemolog":{"couldn\u0027t":1}
,"couldn\u0027t":{"create":1,"bind":1}
,"goto":{"fail":1}
,"streamattr":{"according":1,"numattrs":1}
,"according":{"whether":1}
,"whether":{"using":1}
,"using":{"mailbox":1}
,"egl_stream_fifo_length_khr":{"initialized":1}
,"numattrs":{"egl_stream_fifo_length_khr":1,"demooptions.nfifo":1}
,"type":{"connect":1,"stream":1,"consumer":1}
,"connecting":{"opengl":1}
,"glbindtexture":{"gl_texture_external_oes":1}
,"gl_texture_external_oes":{"texture":1}
,"eglstreamconsumergltextureexternalkhr":{"demostate.display":1}
,"bind":{"texture":1}
,"remember":{"once":1}
,"eglcreatestreamproducersurfacekhr":{"demostate.display":1}
,"order":{"depending":1,"produce":1}
,"depending":{"type":1}
,"opendgl":{"producer":1}
,"eglswapbuffers":{"posts":1}
,"buffer":{"consumer":1}
,"acquires":{"image":1}
,"posted":{"producer":1,"image":1,"least":1,"egl":1}
,"releases":{"frame":1}
,"methods":{"acquiring":1}
,"acquiring":{"frames":1,"releasing":1,"newly":1}
,"releasing":{"back":1,"frame":1}
,"dependent":{"type":1}
,"eglstreamconsumeracquirekhr":{"demostate.display":1,"twice":1}
,"clientlist":{".stream":1}
,"eglstreamconsumerreleasekhr":{"demostate.display":1,"eglstreamconsumerreleasekhr":1,"implicitly":1}
,"application":{"calls":1,"destory":1,"performs":1,"content":1}
,"calls":{"eglstreamconsumeracquirekhr":1}
,"twice":{"eglstream":1}
,"without":{"intervening":1}
,"intervening":{"call":1}
,"implicitly":{"called":1}
,"called":{"start":1}
,"start":{"eglstreamconsumeracquirekhr":1,"consumer":1,"producer":1}
,"destory":{"resources":1}
,"resources":{"order":1}
,"produce":{"correct":1}
,"created":{"states":1,"connected":1,"consumer":1,"step":1}
,"egl_stream_state_created_khr":{"created":1,"initial":1,"egl_stream_state_connecting_khr":1}
,"egl_stream_state_connecting_khr":{"connected":1,"occurs":1,"egl_stream_state_empty_khr":1}
,"egl_stream_state_empty_khr":{"connected":1,"occurs":1,"egl_stream_state_new_frame_available_khr":1}
,"egl_stream_state_new_frame_available_khr":{"producer":1,"occurs":1,"egl_stream_state_old_frame_available_khr":1}
,"least":{"image":1}
,"egl_stream_state_old_frame_available_khr":{"producer":1,"occurs":1,"egl_stream_state_new_frame_available_khr":1}
,"recently":{"posted":1}
,"egl_stream_state_disconnected_khr":{"producer":1,"occurs":1}
,"longer":{"connected":1}
,"i.e":{"destroyed":1}
,"destroyed":{"once":1,"state":1}
,"state":{"remains":1,"until":1,"valid":1,"transitions":1,"eglstream":1,"egl_stream_state_disconnected_khr":1}
,"valid":{"operations":1}
,"operations":{"egstream":1}
,"egstream":{"eglquerystreamkhr":1}
,"eglquerystreamkhr":{"egldestroystreamkhr":1}
,"eglstream\u2019s":{"state":1}
,"eglboolean":{"eglquerystreamkhr":1}
,"eglstreamkhr":{"stream":1}
,"eglenum":{"attribute":1}
,"egluint64khr":{"value":1}
,"transitions":{"occur":1}
,"initial":{"state":1}
,"just":{"created":1}
,"occurs":{"consumer":1,"producer":1,"first":1}
,"first":{"time":1}
,"begins":{"acquiring":1}
,"newly":{"posted":1}
,"building":{"cross-process":1}
,"cross-process":{"eglstream":1}
,"whose":{"producer":1}
,"different":{"processes":1}
,"process":{"creates":1,"gets":1,"producer":1}
,"file":{"descriptor":1}
,"descriptor":{"eglstream":1,"socket":1,"eglstreams":1,"stream":1,"producer":1}
,"sends":{"socket":1}
,"socket":{"producer":1,"creates":1,"specified":1}
,"receives":{"file":1,"stream":1}
,"corresponding":{"eglstream":1}
,"processes":{"consumer":1}
,"l4t":{"provides":1}
,"pair":{"sample":1}
,"sample":{"applications":1}
,"applications":{"constitute":1}
,"constitute":{"example":1}
,"communication":{"cross-process":1}
,"samples":{"opengles2":1}
,"opengles2":{"eglstreamcube":1,"bubble":1}
,"eglstreamcube":{"consumer":1,"-dispno":1}
,"bubble":{"producer":1,"-eglstreamsocket":1,"application":1}
,"demonstrate":{"communication":1}
,"pipeline":{"starting":1,"example":1}
,"starting":{"consumer":1}
,"performs":{"operations":1}
,"eglgetstreamfiledescriptorkhr":{"demostate.display":1}
,"shares":{"file":1}
,"binds":{"consumer":1,"thread":1}
,"texture":{"eglstreamcube.c":1,"eglstreamconsumeracquirekhr":1,"face":1}
,"latches":{"recent":1}
,"recent":{"image":1}
,"renders":{"texture":1}
,"face":{"cube":1}
,"specified":{"\u2011eglstreamsocket":1}
,"\u2011eglstreamsocket":{"option":1}
,"option":{"create":1}
,"eglcreatestreamfromfiledescriptorkhr":{"demostate.display":1}
,"surface":{"refer":1,"created":1}
,"refer":{"nvgldemo_main.c":1}
,"instance":{"eglcontext":1}
,"eglcontext":{"binds":1}
,"thread":{"calling":1}
,"calling":{"eglmakecurrent":1}
,"eglmakecurrent":{"eglstream":1}
,"starts":{"rendering":1}
,"run":{"cross-process":1}
,"enter":{"command":1}
,"command":{"start":1}
,"-dispno":{"-layer":1}
,"-layer":{"-windowoffset":1}
,"-windowoffset":{"1000":1}
,"1000":{"-socket":1}
,"-socket":{"tmp":1}
,"tmp":{"test":1}
,"-eglstreamsocket":{"tmp":1}
,"content":{"appears":1}
,"appears":{"face":1}
}
;Search.control.loadWordPairs(pairs);
