var pairs =
{
"debugging":{"register":1}
,"register":{"trace":1,"access":1}
,"trace":{"buffers":1,"buffer":1}
,"yout":{"nvidia":1}
,"nvidia":{"jetson":1}
,"jetson":{"rtrace":1}
,"rtrace":{"determine":1,"kernel":1,"require":1,"automatically":1,"enter":1,"output":1,"available":1}
,"determine":{"register":1}
,"access":{"happened":1}
,"happened":{"reset":1}
,"reset":{"panic":1}
,"panic":{"rtrace":1}
,"kernel":{"traces":1,"configuration":1,"debug":1}
,"traces":{"trigger":1}
,"trigger":{"read":1}
,"read":{"write":1}
,"write":{"calls":1}
,"calls":{"persistent":1}
,"persistent":{"register":1}
,"buffer":{"decoded":1}
,"decoded":{"dumped":1}
,"dumped":{"reboot":1}
,"reboot":{"using":1,"following":1}
,"using":{"pstore":1}
,"pstore":{"file":1,"record_rtrace":1,"rtrace-ramoops":1}
,"file":{"system":1,"device":1}
,"system":{"rtrace":1}
,"require":{"ramdump":1}
,"ramdump":{"prints":1}
,"prints":{"parsed":1}
,"parsed":{"output":1}
,"output":{"device":1,"rtrace":1,"similar":1}
,"device":{"directly":1}
,"enable":{"rtrace":1}
,"setting":{"kernel":1,"start":1}
,"add":{"setting":1}
,"start":{"rtrace":1,"stop":1}
,"stop":{"rtrace":1}
,"enter":{"command":1}
,"echo":{"sys":1}
,"sys":{"kernel":1,"pstore":1}
,"debug":{"pstore":1}
,"locating":{"rtrace":1}
,"available":{"reboot":1}
,"following":{"file":1}
,"similar":{"following":1}
,"fe406314":{"c038df4c":1}
,"c038df4c":{"mem_serial_in":1}
,"mem_serial_in":{"0x2c":1}
,"0x2c":{"0x38":1}
,"fe406304":{"c038df18":1}
,"c038df18":{"mem_serial_out":1}
,"mem_serial_out":{"0x30":1}
,"0x30":{"0x38":1}
}
;Search.control.loadWordPairs(pairs);
