var pairs =
{
"topic":{"describes":1}
,"describes":{"security":1,"secureboot":1}
,"security":{"features":1}
,"features":{"nvidia":1}
,"nvidia":{"jetson":1}
,"jetson":{"linux":1}
,"linux":{"driver":1,"boot":1}
,"driver":{"package":1}
,"package":{"l4t":1}
,"l4t":{"two":1}
,"two":{"subtopics":1}
,"secureboot":{"describes":1,"feature":1}
,"feature":{"ensures":1,"provides":1}
,"ensures":{"jetson":1}
,"boot":{"process":1}
,"process":{"cannot":1}
,"cannot":{"redirected":1}
,"redirected":{"compromised":1}
,"trusty":{"feature":1}
,"provides":{"secure":1}
,"secure":{"environment":1}
,"environment":{"trusted":1}
,"trusted":{"tos":1}
,"tos":{"applications":1}
,"applications":{"run":1}
}
;Search.control.loadWordPairs(pairs);
