var pairs =
{
"jetson":{"nano":1,"tx1":1,"linux":1,"carrier":1,"devices":1,"software":1,"boot-specific":1,"gpios":1,"gpio":1,"ota":1,"platforms":1,"developer":1,"support":1,"community":1,"zoo":1,"xavier":1,"hda":1,"ape":1,"sound":1,"driver":1,"development":1,"video":1,"v4l2":1,"tegra":1,"\u200Cboard.py":1,"\u200Cboards":1,"\u200Cheader_def.py":1,"\u200Cheader.py":1,"\u200C__init__.py":1,"\u200Cio.py":1,"pins":1,"pinmux":1}
,"nano":{"jetson":1,"devices":1,"2gb":1,"flash":1,"sku":1}
,"tx1":{"package":1,"provided":1,"development":1,"audio":1,"on-board":1,"t21x":1}
,"package":{"manifest":1,"l4t":1,"postinstall":1}
,"nvidia":{"jetson":1,"drivers":1,"configuration":1,"gstreamer":1,"sample":1,"gstreamer-based":1,"tegra":1,"tools":1,"driver":1,"wayland":1,"proprietary":1,"reference":1,"users":1,"init":1,"first":1,"late":1,"weston":1,"bluetooth":1,"default":1,"l4t-bootloader-config":1,"l4t-usb-device-mode":1,"license":1,"eula":1,"resizefs":1,"swap":1,"logo":1,"wallpaper":1,"trademark":1,"\u200Cgraphics_demos":1,"bug":1,"tool":1,"vendor":1,"camera":1,"tvmr":1,"tls":1,"multimedia":1,"abstraction":1,"nvmmlite":1,"kernel":1,"sensor":1,"nvcam":1,"jetson-io":1,"\u200Ctegra_drm.h":1}
,"linux":{"driver":1,"source":1,"kernel":1,"bmp.blob":1,"tegra":1,"debian":1,"\u200Cdebugfs.py":1,"debugfs":1,"\u200Cdt.py":1,"device":1,"\u200Cextlinux.py":1,"configuration":1,"\u200Cpinctrl.py":1,"pinctrl":1,"\u200C__init__.py":1}
,"driver":{"package":1,".inf":1,"versioning":1,"components":1,"openmax":1,"loading":1,"file":1,"cuda":1,"abstraction":1,"used":1,"jetson":1,"egl":1}
,"l4t":{"nvidia":1,"initrd":1,"dependencies":1,"debian":1,"usb":1,"device":1,"eula":1}
,"devices":{"nvidia":1,"simultaneously":1,"jetson":1,"t210":1,"usb":1}
,"provided":{"tar":1,"images":1}
,"tar":{"file":1}
,"table":{"lists":1,"bct":1,"nct":1}
,"lists":{"top-level":1,"directories":1}
,"top-level":{"directories":1}
,"directories":{"files":1}
,"files":{"created":1,"contents":1,"host":1,"target":1,"jetson":1,"specific":1,"needed":1,"obtained":1,"debug":1,"add":1,"bluez":1,"used":1}
,"created":{"expanding":1,"decompressing":1}
,"expanding":{"tar":1}
,"pathnames":{"relative":1}
,"relative":{"installation\u2019s":1,"top":1}
,"installation\u2019s":{"home":1}
,"home":{"directory":1}
,"directory":{"top":1,"target":1,"root":1,"contains":1,"specified":1,"file":1}
,"script":{"apply":1,"calls":1,"flash":1,"flash.sh":1,"sdk":1,"download":1,"tegraflash.py":1,"signing":1,"modify":1,"repackaging":1,"parses":1,"calculations":1,"build":1,"open":1,"initialization":1,"nvidia":1,"create":1,"execute":1,"phs":1,"setting":1,"run":1,"update":1}
,"apply":{"nv_tegra":1}
,"nv_tegra":{"components":1,"git":1,"directory":1,"nv_sample_apps":1,"config.tbz2":1,"graphics_demos.tbz2":1,"nvidia_drivers.tbz2":1,"nv_tools.tbz2":1,"weston.tbz2":1}
,"bootloader":{"related":1,"kernel":1,"directory":1,"license.tegraopenssl":1,"component":1,"software":1,"e2220-1170-specific":1,"binary":1,"microboot":1,"code":1,"files":1,"device":1,"encryption":1,"loading":1,"debian":1,"partitions":1}
,"related":{"components":1,"functions":1}
,"wrapper":{"shell":1,"script":1,"library":1}
,"shell":{"script":1}
,"calls":{"flash.sh":1}
,"flash.sh":{"along":1,"specific":1,"called":1}
,"along":{"specific":1}
,"specific":{"parameters":1,"jetson":1,"p2371-2180":1,"included":1,"sample":1}
,"parameters":{"command":1,"nvidia":1,"jetson":1,"derive":1}
,"command":{"line":1}
,"line":{"options":1}
,"options":{"generate":1}
,"generate":{"bup":1,"exif":1}
,"flash":{"bootloader":1,"qspi-nor":1}
,"kernel":{"package":1,"images":1,"modules":1,"multi-specification":1,"files":1,"u-boot":1,"supports":1,"directory":1,"device":1,"binary":1,"header":1,"zimage":1,"boot":1,"supplements":1,"kernel_supplements.tbz2":1,"headers":1,"kernel_headers.tbz2":1,"module":1,"version":1,"driver":1,"drivers":1,"graphics":1,"interface":1,"rtcpu":1}
,"configuration":{"file":1,"table":1,"directory":1,"files":1,"fuse":1,"nvidia":1,"default":1,"nvphs":1,"proper":1,"wi-fi":1,"jetson":1,"pin":1}
,"file":{"jetson":1,"flash.sh":1,"nvautoflash.sh":1,"rapid-boot":1,"system":1,"describing":1,"containing":1,"contains":1,"board":1,"mkbctpart":1,"mkgpt":1,"mksparse":1,"openssl":1,"arm":1,"cboot.bin":1,"create":1,"input":1,"listing":1,"partition":1,"l4t":1,"alternatively":1,"gst":1,"gstreamer":1,"v4l2":1,"configured":1,"systems":1,"modprobe":1,"bcmdhd":1,"auto-load":1,"used":1,"explicitly":1,"specifying":1,"sysrq":1,"systemd-resolved":1,"suspend-to-ram":1,"invoke":1,"xorg":1,"board-specific":1,"auto":1,"spawn":1,"user\u2019s":1,"nvlicense.templates":1,"nvswap":1,"representing":1,"nvpmodel":1,"tegrastats":1,"video":1,"jpeg":1,"glvnd":1,"source":1,"libnvv4lconvert":1,"extlinux.conf":1,"permissions":1}
,"2gb":{"flash":1,"carrier":1}
,"qspi-nor":{"microsd":1,"internal":1,"memory":1}
,"microsd":{"card":1}
,"internal":{"emmc":1}
,"sku":{"0002":1,"0000":1}
,"0002":{"flashes":1}
,"flashes":{"boot-related":1}
,"boot-related":{"software":1,"softwsare":1,"dtb":1}
,"software":{"emmc":1,"license":1,"trademarks":1,"component":1,"image":1}
,"emmc":{"memory":1}
,"0000":{"flashes":1}
,"softwsare":{"qspi-nor":1}
,"memory":{"card":1,"less":1,"management":1}
,"development":{"platform":1}
,"platform":{"files":1,"wifi":1,"odm":1,"support":1}
,"images":{"kernel":1,"used":1}
,"generates":{"bootloader":1,"final":1,"file":1}
,"multi-specification":{"bup":1}
,"payloads":{"jetson":1}
,"carrier":{"boards":1}
,"called":{"without":1,"bootloader":1}
,"without":{"specifying":1,"having":1,"bootloader":1}
,"specifying":{"device":1,"l4t":1}
,"device":{"name":1,"communication":1,"tree":1,"mode":1,"host":1,"nodes":1,"hardware":1}
,"simultaneous":{"flashing":1}
,"flashing":{"multiple":1,"interface":1,"bootloader":1,"application":1,"jetson":1,"port\u0027s":1}
,"multiple":{"target":1,"jetson":1}
,"target":{"devices":1,"rootfs":1,"device":1,"system":1}
,"interface":{"script":1,"code":1,"library":1,"argus":1,"avp":1,"nvidia":1}
,"sdk":{"manager":1}
,"drivers":{"sample":1,"tbz2":1,"gstreamer":1,"support":1,"jetson":1,"nvidia_drv.so":1}
,"sample":{"applications":1,"filesystem":1,"graphics":1,"wpa":1,"application":1,"program":1}
,"nv_tools":{"scripts":1}
,"scripts":{"nv_apply_kernel_files.sh":1,"nv_customize_rootfs.sh":1}
,"copies":{"kernel":1}
,"host":{"directory":1,"name":1,"x86":1,"avp":1}
,"rootfs":{"directory":1,"readme.txt":1}
,"helps":{"copy":1}
,"copy":{"customized":1}
,"customized":{"files":1}
,"p2597-0000":{"p2180-1000-24x7.conf":1,"p2180-1000.conf":1}
,"platform-specific":{"configuration":1,"bct":1,"debugfs":1}
,"p3449-0000":{"p3448-0000-qspi.conf":1,"p3448-0000-qspi-sd.conf":1,"p3448-0002.conf":1}
,"p3542-0000":{"p3448-0003-qspi.conf":1,"p3448-0003-qspi-sd.conf":1}
,"readme":{"file":1,"installing":1,"doc":1}
,"instructions":{"flashing":1,"installing":1}
,"rapid-boot":{"jetson":1}
,"staging":{"directory":1}
,"root":{"file":1,"filesystem":1}
,"installing":{"root":1,"various":1}
,"source":{"nv_src_build.sh":1,"code":1,"plugin":1,"abstraction":1}
,"builds":{"jetson":1}
,"download":{"kernel":1,"headers":1}
,"u-boot":{"source":1,"bootloader":1}
,"describing":{"boot":1}
,"boot":{"firmware":1,"configuration":1,"mods":1,"binary":1,"time":1,"script":1,"service":1,"default":1}
,"firmware":{"redundancy":1,"atf":1,"adsp.elf":1,"bcm4354.hcd":1,"bcm4354":1,"brcm":1,"directory":1,"gm20b":1,"\u200Cnv-bt-version":1,"\u200Cnv-wifi-version":1,"version":1,"\u200Crtl8822cu_config":1,"\u200Crtl8822cu_fw":1,"support":1,"\u200Crtl8822_setting.bin":1,"tegra21x":1,"files":1,"runs":1,"file":1,"\u200Ctegra21x_xusb_firmware":1,"parameters":1}
,"redundancy":{"process":1}
,"contains":{"directories":1,"bup":1,"files":1,"sysfs":1,"configuration":1,"default":1,"version":1,"core":1}
,"top":{"bootloader":1,"usr":1,"nv_tegra":1}
,"three":{"bmps":1}
,"bmps":{"simple":1}
,"simple":{"header":1}
,"utility":{"generates":1,"library":1,"loading":1}
,"final":{"bup":1}
,"bup":{"bl_update_payload":1,"generation":1}
,"bl_update_payload":{"input":1}
,"input":{"rollback.bin":1,"model_frontal.xml":1,"\u200Creadme.txt":1,"readme.txt":1}
,"rollback.bin":{"entry":1}
,"entry":{"list":1,"points":1,"linux":1}
,"provides":{"board":1,"documentation":1,"symbols":1,"jit":1,"reference":1,"necessary":1,"easy":1,"helpers":1}
,"board":{"information":1}
,"encrypted":{"key":1,"data":1}
,"key":{"data":1,"registered":1}
,"data":{"file":1,"pkc":1,"sbk":1,"pmu":1,"used":1}
,"containing":{"zero-length":1,"l4t":1,"tuning":1}
,"zero-length":{"keys":1}
,"helper":{"file":1,"binary":1,"implementation":1,"script":1,"library":1,"libraries":1,"function":1,"functions":1}
,"generation":{"related":1}
,"initrd":{"image":1}
,"image":{"based":1,"files":1,"flashing":1,"arm":1,"target":1,"given":1,"encoder":1,"postprocessing":1,"post-processing":1,"driver":1,"quality":1,"data":1}
,"based":{"minimal":1,"specified":1,"camera":1,"renderer":1,"gstreamer-1.0":1,"menus":1}
,"minimal":{"ubuntu":1}
,"ubuntu":{"environment":1,"bionic":1,"distribution-specific":1,"prevents":1,"entering":1}
,"license":{"file":1,"mkbootimg":1,"u-boot":1,"sc7":1,"gpl":1,"brcm_patchram_plus":1,"l4t-usb-device-mode-filesystem.img":1,"nvidia":1,"image":1,"libnveventlib":1,"core":1,"nvtracebuf":1,"libtegrav4l2":1,"wayland":1,"weston":1,"gst-v4l2":1,"libgstomx.so":1,"gstreamer":1,"gst":1,"jetson":1,"nvlicense":1,"\u200Cnvlicense-templates.sh":1,"files":1,"adsp":1,"wi-fi":1,"libnvv4l2":1,"vulkan":1,"nvdla":1,"realtek":1,"icons":1}
,"mkgpt":{"tool":1}
,"mksparse":{"tool":1}
,"arm":{"trusted":1}
,"trusted":{"firmware":1}
,"atf":{"binary":1}
,"bct":{"partition":1,"directory":1,".cfg":1,"files":1,"operation":1,"configuration":1}
,"partition":{"updating":1,"layout":1,"information":1}
,"updating":{"library":1}
,"tool":{"img":1,"encodes":1,"manipulating":1,"select":1}
,"img":{"creation":1}
,"encodes":{"primary":1,"camera":1}
,"primary":{"secondary":1}
,"secondary":{"gpt":1}
,"gpt":{"flashable":1}
,"flashable":{"binary":1}
,"binary":{"image":1,"used":1,"load":1,"avp":1,"help":1,"running":1,"dtb":1}
,"sparse":{"image":1}
,"current":{"board-specific":1,"power":1}
,"board-specific":{"information":1,"xorg":1}
,"information":{"nv_bootloader_payload_updater":1,"python":1,"used":1,"file":1,"dram":1}
,"nvidia-l4t-bootloader_32.6.0-":{"_arm64.deb":1}
,"deb":{"packages":1}
,"packages":{"contain":1,"containing":1,"using":1,"installed":1,"install":1,"target":1,"jetson":1,"different":1}
,"contain":{"l4t":1}
,"dependencies":{"associated":1}
,"associated":{"components":1,"-components":1}
,"pdf":{"software":1}
,"trademarks":{"licenses":1}
,"cpu":{"part":1,"binary":1}
,"part":{"tegraboot":1}
,"tegraboot":{"tlk":1,"used":1}
,"tlk":{"hand":1}
,"hand":{"transition":1}
,"first-stage":{"bootloader":1}
,"component":{"runs":1,"jetson":1,"sensor":1,"nvidia":1}
,"runs":{"ccplex":1,"serial-getty@.service":1,"nv-oem-config-gui.service":1,"without":1}
,"avp":{"bootrom":1,"bootloader":1,"audio":1,"communication":1}
,"bootrom":{"applet":1,"executed":1,"rcm":1}
,"applet":{"binary":1}
,"used":{"tegraflash":1,"rcm":1,"flashing":1,"jetson-disk-image-creator.sh":1,"add":1,"every":1,"first":1,"available":1,"timesyncd":1,"converting":1,"wifi":1,"applications":1,"libdrm.so.2":1,"libegl":1,"libgl":1,"cuda":1,"nvidia":1,"submitting":1,"jetson":1,"face":1,"jetson-io":1,"panel":1,"compiling":1,"weston":1}
,"rcm":{"boot":1,"communications":1}
,"xusb":{"firmware":1}
,"t210-specific":{"files":1,"dtb":1,"dtbo":1}
,"t210ref":{"bct":1,"cboot.bin":1,"cboot_rb.bin":1,"cfg":1,"e2220-1170":1,"license.cboot":1,"license.sc7entry-firmware":1,"nvtboot.bin":1,"nvtboot_rb.bin":1,"p2371-0000":1,"p2371-2180":1,"p3450-0000":1,"p3541-0000":1,"sc7entry-firmware.bin":1,"warmboot.bin":1}
,"load":{"kernel":1}
,"supports":{"fastboot":1,"interactions":1}
,"fastboot":{"charging":1}
,"charging":{"display":1}
,"second-stage":{"bootloader":1}
,"t210ref-specific":{"configuration":1}
,"cfg":{".xml":1}
,"e2220-1170-specific":{"directory":1,"u-boot":1}
,"e2220-1170":{"u-boot.bin":1}
,"cboot.bin":{"binary":1}
,"sc7":{"firmware":1}
,"boot-specific":{"bootloader":1}
,"microboot":{"miniloader":1}
,"code":{"loaded":1,"openssl":1,"v4l2":1,"plugins":1,"used":1,"using":1}
,"loaded":{"bootrom":1,"lxde":1,"nvphsd":1,"nvidia":1}
,"executed":{"cpu":1,"boot":1}
,"p2371-0000-specific":{"directory":1,"u-boot":1}
,"p2371-0000":{"u-boot.bin":1}
,"dtb":{"configuration":1,"files":1,"tegra210-":1,"device":1}
,"p2371-2180":{"u-boot.bin":1}
,"p2371-2180-specific":{"u-boot":1}
,"p3450-specific":{"directory":1,"u-boot":1}
,"p3450-0000":{"u-boot.bin":1}
,"p3541-0000":{"u-boot.bin":1}
,"p3541-0000-specific":{"u-boot":1}
,"help":{"system":1}
,"system":{"enter":1,"based":1,"permit":1,"paths":1,"memory":1,"\u200Capt-daily.timer.d":1,"apt-daily.timer.d":1,"\u200Capt-daily-upgrade.timer.d":1,"\u200Cgetty.target.wants":1,"\u200Cmulti-user.target.wants":1,"boots":1,"\u200Cnvargus-daemon.service":1,"\u200Cnvfb-early.service":1,"\u200Cnvfb.service":1,"\u200Cnvgetty.service":1,"\u200Cnv-l4t-usb-device-mode-runtime.service":1,"\u200Cnv-l4t-usb-device-mode.service":1,"\u200Cnv-late-init.service":1,"unit":1,"\u200Cnvmemwarning.service":1,"\u200Cnv-oem-config.target.wants":1,"\u200Cnvphs.service":1,"\u200Cnvpmodel.service":1,"\u200Cnv.service":1,"\u200Cnvs-service.service":1,"\u200Cnvweston.service":1,"\u200Cnvwifibt.service":1,"\u200Cnvzramconfig.service":1,"\u200Cbluetooth.service.d":1,"\u200Cnv-oem-config-debconf@.service":1,"\u200Cnv-oem-config-gui.service":1,"\u200Cnv-oem-config.service":1,"\u200Cnv-oem-config.target":1,"properties":1,"interaction":1,"libraries":1,"daemon":1,"power":1}
,"enter":{"low":1,"password":1}
,"low":{"power":1}
,"power":{"state":1,"mode":1,"model":1}
,"warm":{"boot":1}
,"operation":{"helper":1}
,"communication":{"library":1}
,"default":{"flashing":1,"user":1,"locale":1,"rng-tools":1,"multimedia":1,"nvidia":1,"loglevel":1,"suspend":1,"power":1,"wallpaper":1,"compositor":1,"target":1}
,"application":{"used":1,"contents":1,"nvgstcapture":1,"script":1,"utilities":1,"readme.txt":1,"configuring":1,"displaying":1}
,"implementation":{"api":1,"configuration":1,"mapping":1,"unified":1,"uses":1,"gstreamer":1,"display":1,"file":1,"used":1}
,"api":{"script":1,"github":1,"based":1,"wrapper":1,"calls":1,"access":1}
,"encryption":{"binary":1}
,"parses":{"partition":1,"xml":1}
,"layout":{"common":1}
,"common":{"bct":1,"code":1}
,"fuse":{"bypass":1}
,"bypass":{"configuration":1}
,"communications":{"binary":1}
,"tegrasign":{"creates":1}
,"creates":{"signature":1,"bmp.blob":1,"disk":1,"default":1}
,"signature":{"data":1,"fecs":1,"gpmu_ucode_image.bin":1}
,"pkc":{"operating":1}
,"operating":{"mode":1}
,"mode":{"hash":1,"feature":1,"ethernet":1,"protocol":1,"pmu":1,"provides":1,"launch":1}
,"hash":{"encrypted":1}
,"sbk":{"operating":1}
,"python":{"helper":1,"script":1,"packages":1,"library":1,"class":1,"search":1,"classes":1}
,"signing":{"encryption":1}
,"monitor":{"binary":1}
,"running":{"el3":1,"oem-config":1,"daemon":1}
,"el3":{"exception":1}
,"exception":{"space":1}
,"space":{"armv8":1}
,"armv8":{"cpus":1}
,"secure-world":{"software":1}
,"soc-specific":{"kernel":1}
,"tree":{"binary":1,"hard-code":1,"properties":1,"compiler":1}
,"tegra210-":{".dtb":1,".dtbo":1}
,"dtbo":{"files":1}
,"device-tree-compiler":{"binary":1}
,"compressed":{"kernel":1}
,"header":{"files":1,"supported":1,"configuration":1,"graphically":1}
,"needed":{"compiling":1,"interprets":1}
,"compiling":{"kernel":1,"drm":1}
,"modules":{"download":1,"specific":1,"4.9.253-tegra":1,"drivers":1,"extensions":1}
,"headers":{"sources":1,"tbz2":1,"makefiles":1}
,"sources":{"nv_tegra":1,"version":1}
,"git":{"server":1}
,"loadable":{"kernel":1}
,"included":{"kernel":1,"nvgstapps.tbz2":1}
,"zimage":{"built":1}
,"built":{"defconfig":1}
,"defconfig":{"enabled":1}
,"enabled":{"device":1}
,"gnu":{"general":1,"weston-specific":1}
,"general":{"public":1}
,"public":{"license":1,"key":1}
,"gpl":{"device-tree-compiler":1,"subsections":1}
,"modify":{"dtb":1}
,"hard-code":{"linux":1}
,"time":{"display":1}
,"display":{"mode":1,"imp":1}
,"nvidia-l4t-kernel":{".deb":1}
,"supplements":{"tbz2":1}
,"obtained":{"decompressing":1}
,"decompressing":{"kernel_supplements.tbz2":1,"nvgstapps.tbz2":1,"config.tbz2":1,"graphics_demos.tbz2":1,"nvidia_drivers.tbz2":1,"nv_tools.tbz2":1,"weston.tbz2":1}
,"kernel_supplements.tbz2":{"archive":1}
,"archive":{"located":1}
,"lib":{"modules":1,"aarch64-linux-gnu":1,"systemd":1,"nvidia":1,"ubiquity":1,"firmware":1,"xorg":1,"weston":1}
,"makefiles":{"configuration":1}
,"debug":{"files":1}
,"tools":{"directory":1,"documentation":1,"tbz2":1,"tests":1}
,"bmp-splash":{"bmp-blob-readme.txt":1,"bmp_generator_l4t.py":1,"config_file.example":1,"genbmpblob_l4t.sh":1}
,"create":{"bmp.blob":1,"chromium-browser.desktop":1}
,"bmp.blob":{"using":1}
,"using":{"configuration":1,"jetson":1,"existing":1,"nvidia":1,"kernel-level":1,"device":1}
,"example":{"configuration":1}
,"listing":{"bmp":1}
,"bmp":{"files":1,"blob":1}
,"add":{"bmp":1,"gst":1,"weston-launch":1}
,"drives":{"creation":1}
,"creation":{"jetson":1}
,"documentation":{"managing":1,"usb":1}
,"managing":{"debian":1}
,"debian":{"scripts":1,"nvdebrepack.sh":1,"packages":1,"nvdebrepack.txt":1,"apt":1,"package":1}
,"repackaging":{"existing":1}
,"existing":{"l4t":1,"sysfs":1}
,"doc":{"nvdebrepack.sh":1,"nvidia-tegra":1,"bluez":1,"\u200Cnetwork-manager":1,"\u200Cnvidia-l4t-oem-config":1,"procps":1,"rng-tools":1,"udev":1}
,"jetson-gpio-common_2.0.17_arm64.deb":{"python-jetson-gpio_2.0.17_arm64.deb":1}
,"gpios":{"packages":1}
,"installed":{"host\u2019s":1}
,"host\u2019s":{"python":1}
,"library":{"directory":1,"jetson":1,"gstreamer-1.0":1,"nvdrmvideosink":1,"cuda":1,"gstreamer":1,"used":1,"configuration":1,"libnvutils":1,"egl":1,"glx":1,"gst":1,"nvidia":1,"encodes":1,"v4l2":1,"implementation":1,"trace":1,"generate":1,"generic":1,"supports":1,"library":1,"implicitly":1,"provides":1,"implements":1,"loaded":1,"graphics":1}
,"specified":{"environment":1,"command":1,"--version":1}
,"environment":{"variable":1}
,"variable":{"pythonpath":1}
,"gpio":{"api":1}
,"github":{"page":1}
,"page":{"jetson.gpio":1,"gives":1,"procps":1}
,"jetson.gpio":{"linux":1}
,"disk":{"image":1}
,"user":{"skips":1,"configuration":1,"session":1,"provided":1}
,"skips":{"running":1}
,"oem-config":{"first":1,"writes":1,"text":1,"gui":1,"debconf":1}
,"first":{"boot":1,"time":1}
,"extracts":{"jetson":1}
,"xml":{"configuration":1}
,"samplefs":{"nv_build_samplefs.sh":1,"nvubuntu-bionic-aarch64-packages":1,"nvubuntu-bionic-aarch64-samplefs":1,"nvubuntu_samplefs.sh":1}
,"downloads":{"base":1}
,"base":{"image":1}
,"given":{"distriution":1,"location":1}
,"distriution":{"installs":1}
,"installs":{"necessary":1,"ubuntu":1,"bsp":1}
,"necessary":{"packages":1,"sensor":1}
,"list":{"ubuntu":1,"generic":1}
,"bionic":{"packages":1,"distribution":1}
,"install":{"base":1}
,"generic":{"details":1,"buffer":1}
,"details":{"regarding":1}
,"regarding":{"ubuntu":1}
,"distribution-specific":{"packages":1}
,"filesystem":{"contents":1}
,"contents":{"described":1}
,"described":{"config":1,"graphics":1,"nvgstapps":1,"nvidia":1,"weston":1}
,"config":{"tbz2":1,"drivers":1}
,"graphics":{"application":1,"demos":1,"demo":1,"drivers":1,"driver":1,"host":1}
,"bsp":{"packages":1}
,"registered":{"debian":1}
,"apt":{"system":1,"timer":1,"upgrade":1}
,"permit":{"downloading":1}
,"downloading":{"packages":1}
,"ota":{"server":1}
,"usb":{"device":1,"flashing":1,"hub":1,"firmware":1,"3.0":1}
,"feature":{"windows":1}
,"windows":{"driver":1,"system":1}
,".inf":{"file":1}
,"mit":{"license":1}
,"alternatively":{"mentions":1}
,"mentions":{"gpl":1}
,"gstreamer":{"plugin":1,"1.0":1,"videosink":1,"components":1,"sources":1,"camera":1,"conversion":1,"video":1,"egl":1,"buffer":1,"nvdrmvideosink":1}
,"libnveventlib":{"trace":1}
,"trace":{"buffer":1,"events":1}
,"buffer":{"library":1,"conversion":1,"exif":1,"pool":1,"management":1}
,"core":{"camera":1,"library":1,"accelerated":1}
,"camera":{"driver":1,"capture":1,"application":1,"plugin":1,"gstreamer":1,"source":1,"api":1,"utilities":1,"yuv":1,"runtime":1,"image":1}
,"nvtracebuf":{"library":1}
,"wayland":{"ivi":1,"support":1,"library":1,"driver":1}
,"ivi":{"extensions":1}
,"weston":{"data":1,"tbz2":1,"debian":1,"service":1,"weston.ini":1,"initialization":1,"binaries":1,"library":1,"backend":1,"sample":1,"tools":1,"apps":1,"\u200Cdesktop-shell.so":1,"\u200Cdrm-backend.so":1,"\u200Cfullscreen-shell.so":1,"\u200Cgl-renderer.so":1,"\u200Chmi-controller.so":1,"\u200Civi-controller.so":1,"\u200Civi-shell.so":1,"\u200Cwayland-backend.so":1,"weston-desktop-shell":1,"weston-keyboard":1,"\u200Cweston-screenshooter":1,".png":1,"images":1,"docs":1,"\u200Clicense.wayland-ivi-extension":1,"\u200Clicense.weston":1,"\u200Clicense.weston-data":1,"wayland.svg":1,"icons":1}
,"nv_sample_apps":{"\u200Clicense.gst-nvvideo4linux2":1,"\u200Clicense.gst-openmax":1,"\u200Clicense.gstvideocuda":1,"\u200Clicense.libgstnvvideosinks":1,"nvgstapps.tbz2":1,"nvgstcapture-1.0_readme.txt":1,"nvgstplayer-1.0_readme.txt":1}
,"gst-v4l2":{"video":1}
,"video":{"codec":1,"player":1,"composition":1,"sink":1,"code":1,"cuda":1,"decode":1,"format":1,"acceleration":1,"post-processing":1,"driver":1,"mixer":1}
,"codec":{"plugins":1,"plugin":1}
,"libgstomx.so":{"libgstnvegl-1.0.so.0":1}
,"libgstnvegl-1.0.so.0":{"libnvgstjpeg.so":1}
,"libnvgstjpeg.so":{"libraries":1}
,"libraries":{"included":1,"argus":1,"loaded":1,"required":1,"drivers":1}
,"1.0":{"cuda":1,"eglproducer":1}
,"cuda":{"post-processing":1,"library":1,"driver":1,"fatbinaries":1}
,"post-processing":{"plugin":1,"based":1,"helper":1,"jetson":1}
,"plugin":{"library":1,"jpeg":1,"deepstream":1,"nvswap":1,"nvpmodel":1,"fornvqspi-update":1,"resize":1,"video":1,"nvpmodel_indicator":1}
,"components":{"applications":1,"contents":1}
,"applications":{"contents":1,"loaded":1,"vulkan":1,"making":1}
,"nvgstapps":{"tbz2":1}
,"read":{"nvidia":1,"vic":1}
,"gstreamer-based":{"camera":1,"multimedia":1}
,"capture":{"application":1,"camera":1,"requests":1}
,"multimedia":{"player":1,"capture":1,"video":1,"encoding":1,"programming":1,"image":1,"driver":1,"utilities":1,"parser":1,"framework":1,"jetson":1,"api":1}
,"player":{"nvgstplayer":1,"application":1}
,"tegra":{"driver":1,"\u200Clibnvddk_2d_v2.so":1,"\u200Clibnvddk_vic.so":1,"\u200Clibnvdsbufferpool.so.1.0.0":1,"\u200Clibnveglstream_camconsumer.so":1,"\u200Clibnveglstreamproducer.so":1,"\u200Clibnveventlib.so":1,"\u200Clibnvexif.so":1,"libnvfnet.so":1,"libnvfnetstoredefog.so":1,"libnvfnetstorehdfx.so":1,"libnvgbm.so":1,"libnvgov_boot.so":1,"libnvgov_camera.so":1,"libnvgov_force.so":1,"libnvgov_generic.so":1,"libnvgov_gpucompute.so":1,"libnvgov_graphics.so":1,"libnvgov_il.so":1,"libnvgov_spincircle.so":1,"libnvgov_tbc.so":1,"libnvgov_ui.so":1,"libnvidia-eglcore.so":1,"libnvidia-egl-wayland.so":1,"libnvidia-fatbinaryloader.so":1,"libnvidia-glcore.so":1,"libnvidia-glsi.so":1,"libnvidia-glvkspirv.so":1,"libnvidia-ptxjitcompiler.so":1,"libnvidia-rmapi-tegra.so":1,"libnvidia-tls.so":1,"libnvid_mapper.so":1,"libnvid_mapper.so.1.0.0":1,"libnvimp.so":1,"libnvjpeg.so":1,"\u200Clibnvll.so":1,"\u200Clibnvmedia.so":1,"\u200Clibnvmm_contentpipe.so":1,"libnvmm_parser.so":1,"\u200Clibnvmm_utils.so":1,"\u200Clibnvodm_imager.so":1,"\u200Clibnvofsdk.so":1,"libnvomxilclient.so":1,"libnvomx.so":1,"libnvosd.so":1,"libnvos.so":1,"libnvparser.so":1,"libnvphsd.so":1,"libnvphs.so":1,"libnvrm_gpu.so":1,"libnvrm_graphics.so":1,"libnvrm.so":1,"libnvscf.so":1,"libnvtestresults.so":1,"libnvtnr.so":1,"libnvtracebuf.so":1,"libnvtvmr.so":1,"libnvv4l2.so":1,"libnvv4lconvert.so":1,"libnvvulkan-producer.so":1,"libnvwinsys.so":1,"libsensors.hal-client.nvs.so":1,"libsensors_hal.nvs.so":1,"libsensors.l4t.no_fusion.nvs.so":1,"libtegrav4l2.so":1,"libv4l2_nvargus.so":1,"libv4l2_nvvidconv.so":1,"libv4l2_nvvideocodec.so":1,"libvulkan.so.1.2.141":1,"nvidia_icd.json":1,"\u200Cweston":1}
,"versioning":{"file":1}
,"tegrastats":{"application":1,"run":1}
,"calculations":{"loads":1}
,"loads":{"frequencies":1,"dispatches":1}
,"frequencies":{"ram":1}
,"ram":{"sizes":1}
,"sizes":{"using":1}
,"sysfs":{"nodes":1,"system":1}
,"nodes":{"contents":1,"docker":1,"registers":1}
,"support":{"contents":1,"forums":1,"realtek":1,"libraries":1,"vulkan":1,"image":1}
,"nvgstapps.tbz2":{"archive":1}
,"bin":{"gst-install":1,"nvgstcapture":1,"nvgstcapture-1.0":1,"nvgstplayer":1,"nvgstplayer-1.0":1,"nvidia-bug-report-tegra.sh":1,"nvidia-xconfig":1,"jetson_clocks":1,"tegrastats":1}
,"build":{"gstreamer":1}
,"version":{"specified":1,"adsp":1,"file":1,"string":1,"kernel":1,"used":1}
,"--version":{"option":1}
,"option":{"1.12.3":1}
,"1.12.3":{"default":1}
,"link":{"nvgstcapture-1.0":1,"nvgstplayer-1.0":1,"nvlxde-exempt.sh":1,"cuda":1,"libnvbufsurf":1,"libnvbufsurftransform.so.1.0.0":1,"libnvbuf_utils.so.1.0.0":1}
,"aarch64-linux-gnu":{"\u200Cgstreamer-1.0":1,"\u200Clibgstnvegl-1.0.so.0":1,"\u200Clibgstnvexifmeta.so":1,"\u200Clibgstnvivameta.so":1,"\u200Clibnvsample_cudaprocess.so":1,"\u200Clibcuda.so":1,"\u200C\u200Clibdrm_nvdc.so":1,"\u200Clibv4l":1,"\u200Clibv4l2.so.0.0.999999":1,"\u200Clibv4lconvert.so.0.0.999999":1,"libv4l":1,"\u200Clibvulkan.so.1.2.141":1,"\u200Ctegra":1,"\u200Ctegra-egl":1,"tegra":1,"\u200Clibilmclient.so.2.2.0":1,"libilmcommon.so.2.2.0":1,"libilmcontrol.so.2.2.0":1,"\u200Clibilminput.so.2.2.0":1,"\u200Clibweston-6.so.0":1,"\u200Clibweston-desktop-6.so.0":1,"weston":1}
,"plugins":{"drivers":1,"\u200Cnvlicense.py":1,"\u200Cnvpmodel.py":1,"\u200Cnvqspi-update.py":1,"\u200Cnvresizefs.py":1,"\u200Cnvswap.py":1}
,"\u200Cgstreamer-1.0":{"libgstnvarguscamerasrc.so":1,"libgstnvcompositor.so":1,"libgstnvdrmvideosink.so":1,"libgstnveglglessink.so":1,"libgstnveglstreamsrc.so":1,"libgstnvegltransform.so":1,"libgstnvivafilter.so":1,"libgstnvjpeg.so":1,"libgstnvtee.so":1,"libgstnvv4l2camerasrc.so":1,"libgstnvvidconv.so":1,"libgstnvvideo4linux2.so":1,"libgstnvvideocuda.so":1,"libgstnvvideosink.so":1,"libgstnvvideosinks.so":1,"libgstomx.so":1}
,"argus":{"api":1,"camera":1}
,"composition":{"plugin":1}
,"accelerated":{"egl":1,"functionality":1,"libjpeg":1}
,"egl":{"based":1,"api":1,"implementation":1,"driver":1,"library":1,"nvbuf_utils":1,"\u200Cegl_external_platform.d":1,"external":1}
,"renderer":{"element":1}
,"element":{"gstreamer-1.0":1}
,"eglstream":{"consumer":1,"producer":1}
,"consumer":{"functionality":1,"library":1}
,"functionality":{"library":1,"draw":1}
,"nvm":{"buffer":1}
,"conversion":{"eglimage":1,"plugin":1,"helper":1}
,"eglimage":{"plugin":1}
,"jpeg":{"files":1,"encode":1,"using":1}
,"deepstream":{"sdk":1}
,"v4l2":{"camera":1,"video":1,"standard":1,"kernel":1,"driver":1,"library":1}
,"proprietary":{"gstreamer":1,"version":1}
,"eglproducer":{"video":1}
,"sink":{"plugin":1}
,"openmax":{"driver":1,"client":1,"implementation":1}
,"client":{"plugin":1,"library":1,"interface":1,"nvidia":1}
,"exif":{"metadata":1,"header":1}
,"metadata":{"library":1,"read":1}
,"gst":{"metadata":1,"v4l2":1,"openmax":1,"video":1,"camera":1}
,"gst-nvivafilter":{"plugin":1}
,"share":{"doc":1,"alsa":1,"backgrounds":1,"polkit-1":1,"egl":1,"glvnd":1,"nvpmodel_indicator":1,"weston":1}
,"nvidia-tegra":{"\u200Clicense.gst-nvvideo4linux2":1,"\u200Clicense.gst-openmax":1,"\u200Clicense.gstvideocuda":1,"\u200Clicense.libgstnvdrmvideosink":1,"\u200Clicense.libgstnvv4l2camerasrc":1,"\u200Clicense.libgstnvvideosinks":1,"\u200Cl4t_end_user_\u200Clicense_agreement.txt":1,"\u200Cnvidia_trademark_license_\u200Caddendum_sw.pdf":1,"\u200Clicense.\u200Cadsp":1,"\u200Clicense.brcm_patchram_plus":1,"license.cypress_wifibt":1,"license.libnvargus":1,"license.libnvcam_imageencoder":1,"license.libnveventlib":1,"license.libnvtracebuf":1,"license.libnvv4l2":1,"license.libnvv4lconvert":1,"license.libtegrav4l2":1,"license.libvulkan1":1,"license.minigbm":1,"license.nvdla":1,"license.realtek_8822ce_wifibt":1,"license.tegra_sensors":1}
,"usr":{"share":1,"lib":1,"sbin":1,"src":1,"bin":1,"include":1}
,"nvdrmvideosink":{"library":1}
,"videosink":{"library":1}
,"config.tbz2":{"archive":1}
,"asound":{"configuration":1}
,"audio":{"supermodule":1,"video":1}
,"configured":{"different":1}
,"different":{"random":1,"ptx":1,"architectures":1}
,"random":{"nodes":1}
,"encoding":{"parameters":1}
,"reference":{"platforms":1,"implementation":1}
,"static":{"information":1}
,"mapping":{"host":1,"unmapping":1}
,"name":{"addresses":1}
,"lightdm":{"lightdm.conf.d":1,"guest":1}
,"lightdm.conf.d":{"\u200C50-nvidia.conf":1}
,"guest":{"user":1}
,"modprobe.d":{"bcmdhd.conf":1,"\u200Ctegra-udrm.conf":1}
,"nvidia-specific":{"modprobe":1,"early":1,"oem":1}
,"modprobe":{"configuration":1}
,"bcmdhd":{"driver":1}
,"auto-load":{"kernel":1}
,"module":{"tegra-drm.ko":1,"server":1}
,"tegra-drm.ko":{"boot":1}
,"modules-load.d":{"nv.conf":1}
,"every":{"boot":1}
,"networkmanager":{"conf.d":1}
,"conf.d":{"\u200C10-globally-managed-devices.conf":1}
,"explicitly":{"unmanage":1}
,"unmanage":{"anything":1}
,"anything":{"wifi":1}
,"wifi":{"wwan":1,"pre-initialization":1,"firmware":1,"certification":1,"drivers":1}
,"nvidia-container-runtime":{"\u200Chost-files-for-container.d":1}
,"\u200Chost-files-for-container.d":{"l4t.csv":1}
,"csv":{"file":1}
,"docker":{"container":1}
,"control":{"file":1,"firmware":1,"script":1}
,"specifies":{"uart":1,"applications":1}
,"uart":{"port":1}
,"port":{"oem-config":1}
,"writes":{"output":1,"during":1}
,"output":{"headless":1,"\u200Creadme.txt":1,"readme.txt":1}
,"headless":{"mode":1,"configuration":1}
,"defines":{"uart":1,"usb":1}
,"during":{"headless":1}
,"paths":{"nvphs":1}
,"nvphs":{"needs":1}
,"needs":{"initialize":1}
,"initialize":{"itself":1}
,"itself":{"start":1}
,"start":{"jetson":1}
,"skel":{"desktop":1,".xsessionrc":1}
,"desktop":{"\u200Cgnome-terminal.desktop":1,"icon":1,"\u200Clxterminal.desktop":1,"\u200Cnv_devzone.desktop":1,"\u200Cnv_forums.desktop":1,"\u200Cnv_jetson_projects.desktop":1,"\u200Cnv_jetson_zoo.desktop":1,"\u200Cnv_l4t_readme.desktop":1,"file":1,"environment":1,"panel":1}
,"icon":{"gnome-terminal":1,"lxterminal":1,"hyperlink":1,"link":1}
,"gnome-terminal":{"application":1}
,"lxterminal":{"application":1}
,"hyperlink":{"jetson":1,"elinux.org\u2019s":1}
,"developer":{"zone":1}
,"forums":{"jetson":1}
,"community":{"projects":1}
,"projects":{"page":1}
,"elinux.org\u2019s":{"jetson":1}
,"zoo":{"page":1}
,"gives":{"instructions":1}
,"various":{"open-source":1,"gnu-specific":1,"gnu":1}
,"open-source":{"add-on":1}
,"add-on":{"pages":1,"modules":1}
,"pages":{"jetson":1}
,"open":{"browse":1}
,"browse":{"l4t-readme":1}
,"l4t-readme":{"directory":1}
,"xsession":{"auto-run":1}
,"auto-run":{"script":1}
,"sysctl.d":{"\u200C30-nv-console-messages.conf":1,"\u200C90-tegra-settings.conf":1}
,"loglevel":{"console":1}
,"console":{"messages":1}
,"systemd":{"nvfb-early.sh":1,"nvfb.sh":1,"nvgetty.sh":1,"nv-late-init.sh":1,"\u200Cnvmemwarning.sh":1,"\u200Cnv-oem-config-post.sh":1,"\u200Cnv-oem-config.sh":1,"nv.sh":1,"nvweston.sh":1,"nvwifibt-pre.sh":1,"nvwifibt.sh":1,"nvzramconfig.sh":1,"resolved.conf.d":1,"sleep.conf":1,"system":1,"startup":1,"unit":1,"service":1,"nvwifibut-pre":1,"\u200Ctimesyncd.conf.d":1}
,"init":{"script":1,"postinit":1}
,"starts":{"getty":1}
,"getty":{"service":1}
,"late":{"initialization":1,"initinialization":1}
,"initialization":{"script":1,"system":1,"file":1}
,"displays":{"warning":1,"single":1}
,"warning":{"notification":1}
,"notification":{"available":1}
,"available":{"system":1,"network":1}
,"less":{"threshold":1}
,"nv-oem-config-gui.service":{"nv-oem-config-debconf@.service":1}
,"post-installation":{"script":1}
,"bluetooth":{"wifi":1,"wi-fi":1,"systemd":1,"firmware":1}
,"pre-initialization":{"script":1}
,"wi-fi":{"init":1,"bluetooth":1,"firmware":1}
,"configures":{"zram":1,"on-board":1}
,"zram":{"devices":1}
,"t210":{"chips":1}
,"resolved.conf.d":{"\u200Cnv-fallback-dns.conf":1}
,"systemd-resolved":{"sets":1}
,"sets":{"dns":1,"nvidia":1}
,"dns":{"server":1}
,"server":{"used":1,"configuration":1,"side":1}
,"network":{"connection":1}
,"connection":{"usb":1}
,"ubuntu-specific":{"suspend":1}
,"suspend":{"hibernation":1,"state":1}
,"hibernation":{"conf":1}
,"conf":{"file":1}
,"suspend-to-ram":{"mem":1}
,"mem":{"default":1}
,"state":{"ubuntu":1,"pin":1}
,"prevents":{"ubuntu":1}
,"entering":{"unsupported":1}
,"unsupported":{"suspend-to-idle":1}
,"suspend-to-idle":{"freeze":1}
,"freeze":{"state":1}
,"apt-daily.timer.d":{"\u200Coverride.conf":1}
,"override":{"settings":1}
,"settings":{"daily":1,"\u200Creadme.txt":1,"readme.txt":1}
,"daily":{"apt":1}
,"timer":{"service":1}
,"\u200Capt-daily-upgrade.timer.d":{"\u200Coverride.conf":1}
,"upgrade":{"timer":1}
,"\u200Cgetty.target.wants":{"\u200Cserial-getty@ttygs0.service":1}
,"enables":{"autologin":1,"compton":1}
,"autologin":{"console":1}
,"libargus":{"daemon":1,"consumer":1,"clients":1,"camera":1}
,"daemon":{"systemd":1,"shared":1,"providing":1,"provides":1}
,"startup":{"service":1}
,"\u200Cmulti-user.target.wants":{"nvargus-daemon.service":1,"\u200Cnvfb-early.service":1,"\u200Cnvfb.service":1,"\u200Cnvgetty.service":1,"\u200Cnv-l4t-bootloader-config.service":1,"\u200Cnv-l4t-usb-device-mode.service":1,"\u200Cnv-late-init.service":1,"\u200Cnvmemwarning.service":1,"\u200Cnvphs.service":1,"\u200Cnv.service":1,"\u200Cnvs-service.service":1,"\u200Cnvweston.service":1,"\u200Cnvzramconfig.service":1}
,"early":{"first":1}
,"service":{"launch":1,"invoke":1,"automatically":1,"add":1,"executed":1,"launches":1,"look":1,"bluez":1,"run":1,"image":1,"daemon":1}
,"launch":{"systemd":1,"nvzramconfig.sh":1,"tegrastats":1}
,"nvfb.sh":{"script":1}
,"invoke":{"nvgetty.sh":1,"nv-l4t-usb-device-mode.sh":1}
,"nvgetty.sh":{"script":1}
,"automatically":{"check":1,"checks":1}
,"check":{"perform":1}
,"perform":{"qspi":1}
,"qspi":{"update":1}
,"update":{"once":1,"system":1,"bootloader":1}
,"once":{"system":1,"detected":1}
,"unit":{"file":1,"service":1}
,"initinialization":{"systemd":1}
,"invokes":{"nvmemwarning.sh":1}
,"phs":{"service":1,"governor":1,"daemon":1,"client":1,"binary":1}
,"nv.sh":{"script":1}
,"weston-launch":{"group":1}
,"deprecated":{"service":1}
,"port\u0027s":{"device":1}
,"protocol":{"support":1}
,"\u200Cnv-oem-config.target.wants":{"\u200Cnvweston.service":1}
,"nvwifibut-pre":{"nvwifibt":1}
,"nvwifibt":{"scripts":1}
,"launches":{"nvzramconfig.sh":1,"nvbackground.sh":1}
,"\u200Ctimesyncd.conf.d":{"\u200Cnv-fallback-ntp.conf":1}
,"ntp":{"configuration":1,"servers":1}
,"timesyncd":{"service":1}
,"look":{"fallback":1}
,"fallback":{"ntp":1}
,"udev":{"rules.d":1,"rule":1,"\u200Ccopyright.compliant":1}
,"rules.d":{"\u200C90-alsa-asound-tegra.rules":1,"\u200C91-xorg-conf-tegra.rules":1,"\u200C92-hdmi-audio-tegra.rules":1,"\u200C99-nv-l4t-usb-device-mode.rules":1,"\u200C99-nv-l4t-usb-host-config.rules":1,"\u200C99-nv-ufs-mount.rules":1,"\u200C99-nv-wifibt.rules":1,"\u200C99-tegra-devices.rules":1,"\u200C99-tegra-mmc-ra.rules":1}
,"rules":{"configuration":1}
,"proper":{"asound.conf":1,"xorg.conf":1,"pulse":1}
,"asound.conf":{"selection":1}
,"xorg.conf":{"selection":1}
,"pulse":{"default.pa":1}
,"default.pa":{"selection":1}
,"on-board":{"usb":1,"wi-fi":1}
,"hub":{"nvidia":1}
,"adds":{"udev":1}
,"rule":{"auto-mount":1}
,"auto-mount":{"ufs":1}
,"ufs":{"card":1}
,"card":{"once":1,"read_ahead_kb":1}
,"permission":{"setting":1}
,"setting":{"jetson":1,"system":1}
,"read_ahead_kb":{"configuration":1}
,"wpa":{"supplicant":1}
,"x11":{"xorg.conf":1,"xorg.conf.jetson_e":1}
,"xdg":{"autostart":1,"format":1,"weston":1}
,"autostart":{"\u200Cnvbackground.desktop":1,"\u200Cnvbackground.sh":1,"\u200Cnvchrome.desktop":1,"nvchrome.sh":1,"\u200Cnvl4t-readme.sh":1,"\u200Cnvlxde-compton.desktop":1,"\u200Cnvlxde-exempt.desktop":1,"\u200Cnvlxde-exempt.sh":1,"\u200Cnvpmodel_indicator.desktop":1}
,"auto":{"launches":1}
,"nvbackground.sh":{"user":1}
,"session":{"created":1}
,"format":{"desktop":1,"conversion":1,"packages":1}
,"spawn":{"nvchrome.sh":1}
,"nvchrome.sh":{"boot":1}
,"chromium-browser.desktop":{"file":1}
,"user\u2019s":{"desktop":1}
,"compton":{"default":1}
,"compositor":{"lxde":1}
,"nvlxde-exempt.sh":{"script":1}
,"lxde":{"environment":1}
,"\u200Cbluetooth.service.d":{"\u200Cnv-bluetooth-service.conf":1}
,"bluez":{"debian":1,"\u200Ccopyright.compliant":1}
,"run":{"oem-config":1,"nv-oem-config.sh":1,"without":1,"usage":1}
,"text":{"mode":1,"given":1,"based":1}
,"gui":{"mode":1,"plugin":1,"page":1,"front":1}
,"boots":{"first":1}
,"opt":{"nvidia":1}
,"l4t-bootloader-config":{"\u200Cnv-l4t-bootloader-config.service":1,"\u200Cnv-l4t-bootloader-config.sh":1}
,"checks":{"performs":1}
,"performs":{"qspi":1}
,"l4t-usb-device-mode":{"\u200Cfilesystem.img":1,"\u200Clicense.filesystem.img":1,"\u200Cnv-l4t-usb-device-mode.service":1}
,"shows":{"nvidia":1,"l4t":1,"current":1}
,"eula":{"content":1}
,"content":{"oem-config":1,"pipe":1}
,"resizefs":{"\u200Cnvresizefs-query":1,"\u200Cnvresizefs.sh":1,"\u200Cnvresizefs.templates":1}
,"resize":{"questions":1,"function":1,"plugin":1}
,"questions":{"definition":1}
,"definition":{"text":1}
,"main":{"script":1}
,"execute":{"resize":1}
,"string":{"definitions":1,"identify":1}
,"definitions":{"ubiquity":1}
,"ubiquity":{"resize":1,"plugins":1,"plugin":1}
,"swap":{"\u200Cnvswap-query":1,"\u200Cnvswap.sh":1,"\u200Cnvswap.templates":1}
,"debconf":{"plugin":1,"configuration":1}
,"sbin":{"nv-oem-config-firstboot":1,"nvphsd_setup.sh":1,"nvsetprop":1,"brcm_patchram_plus":1,"nvargus-daemon":1,"nvphsd":1,"nvs-service":1,"nvtunerd":1,"\u200Cl4t_payload_updater_t210":1,"nv_get_dram_info":1,"nvpmodel":1}
,"oem":{"first-boot":1}
,"first-boot":{"configuration":1}
,"setup":{"script":1}
,"properties":{"later":1,"via":1}
,"later":{"queried":1}
,"queried":{"phs":1}
,"alsa":{"cards":1,"configuration":1,"init":1,"library":1}
,"cards":{"\u200Ctegra-hda.conf":1,"\u200Ctegra-snd-t210r.conf":1}
,"ape":{"soundcard":1}
,"soundcard":{"alsa":1}
,"postinit":{"\u200C00-tegra.conf":1,"\u200C01-tegra-rt565x.conf":1}
,"sound":{"cards":1}
,"backgrounds":{"\u200Cnvidia_login_logo.png":1,"\u200Cnvidia_logo.png":1,"\u200Cnvidia_wallpaper.jpg":1}
,"png":{"file":1}
,"representing":{"nvidia":1}
,"wallpaper":{"image":1}
,"compliance":{"files":1}
,"\u200Cnetwork-manager":{"\u200Ccopyright.compliant":1}
,"\u200Cnvidia-l4t-oem-config":{"\u200Ccopyright":1}
,"trademark":{"license":1}
,"procps":{"\u200Ccopyright.compliant":1}
,"rng-tools":{"\u200Ccopyright":1}
,"polkit-1":{"actions":1}
,"actions":{"\u200Ccom.nvidia.\u200Cpkexec.nvpmodel.\u200Cpolicy":1,"\u200Ccom.nvidia.\u200Cpkexec.tegrastats.\u200Cpolicy":1}
,"policykit":{"configuration":1}
,"nvpmodel":{"run":1,"nvpmodel_t210.conf":1,"clock":1,"\u200Cnvpmodel_t210_jetson-nano.conf":1,"indicator":1,"backend":1}
,"having":{"enter":1}
,"password":{"desktop":1}
,"graphics_demos.tbz2":{"archive":1}
,"src":{"nvidia":1}
,"demo":{"applications":1}
,"nvidia_drivers.tbz2":{"archive":1}
,"ld.so.conf.d":{"\u200Cnvidia-tegra.conf":1}
,"ldconf":{"file":1}
,"vulkan":{"icd.d":1,"icd":1,"library":1,"api":1,"spir\u2011v":1,"loader":1,"libraries":1}
,"icd.d":{"\u200Cnvidia_icd.json":1}
,"icd":{"configuration":1}
,"compiled":{"version":1,"different":1}
,"adsp":{"apps":1}
,"apps":{"plugins":1,"readme.txt":1}
,"bcm4354":{"chip":1}
,"brcm":{"firmware":1,"\u200Cfw_bcmdhd.bin":1,"nvram.txt":1}
,"tuning":{"parameters":1,"tools":1}
,"gm20b":{"\u200Cacr_ucode.bin":1,"\u200Cfecs.bin":1,"\u200Cfecs_sig.bin":1,"\u200Cgpccs.bin":1,"\u200Cgpmu_ucode.bin":1,"\u200Cgpmu_ucode_desc.bin":1,"\u200Cgpmu_ucode_image.bin":1,"\u200Cgpu2cde.bin":1,"\u200Cnetb_img.bin":1,"\u200Cpmu_bl.bin":1,"\u200Cpmu_sig.bin":1}
,"high-secure":{"mode":1}
,"pmu":{"code":1,"ucode":1}
,"gpu":{"fecs":1,"gpccs":1,"pmu":1,"shader":1,"compression":1,"device":1,"machine":1}
,"fecs":{"firmware":1,"microcode":1}
,"gpccs":{"firmware":1}
,"ucode":{"firmware":1,"control":1}
,"descriptor":{"data":1}
,"low-secure":{"mode":1}
,"shader":{"program":1,"compiler":1}
,"program":{"used":1}
,"converting":{"gpu":1}
,"compression":{"metadata":1}
,"vic":{"display":1,"hardware-specific":1}
,"hardware":{"description":1,"units":1,"abstraction":1,"add-on":1}
,"loading":{"acr_ucode.bin":1,"broadcom":1}
,"identify":{"platform":1}
,"realtek":{"bluetooth":1,"wifi":1}
,"t21x":{"devices":1}
,"tegra21x":{"\u200Cacr_ucode.bin":1,"\u200Cfecs.bin":1,"\u200Cfecs_sig.bin":1,"\u200Cgpccs.bin":1,"\u200Cgpmu_ucode.b\u200Cin":1,"\u200Cgpmu_ucode_desc.bin":1,"\u200Cgpmu_ucode_image.bin":1,"\u200Cgpu2cde.bin":1,"\u200Cnetb_img.bin":1,"\u200Cnvhost_nvdec020_ns.fw":1,"\u200Cnvhost_nvenc050.fw":1,"\u200Cnvhost_nvjpg010.fw":1,"\u200Cpmu_bl.bin":1,"\u200Cpmu_sig.bin":1,"\u200Cvic04_ucode.\u200Cbin":1}
,"high":{"secure":1}
,"secure":{"mode":1}
,"nvdec":{"firmware":1}
,"nvenc":{"firmware":1}
,"nvjp":{"firmware":1}
,"encode":{"decode":1}
,"hardware-specific":{"ucode":1}
,"3.0":{"firmware":1}
,"bug":{"reporting":1}
,"reporting":{"script":1}
,"usage":{"tips":1}
,"manipulating":{"server":1}
,"alternative":{"oss":1}
,"oss":{"libdrm":1}
,"libdrm":{"library":1,"nvidia":1}
,"libnv4l2":{"shared":1}
,"shared":{"libraries":1,"object":1,"library":1}
,"libv4lconvert":{"shared":1}
,"\u200Clibv4l":{"\u200Cplugins":1}
,"libv4l":{"\u200Cplugins":1}
,"\u200Cplugins":{"\u200Clibv4l2_nvargus.so":1,"\u200Clibv4l2_nvvidconv.so":1,"\u200Clibv4l2_nvvideocodec.so":1}
,"implements":{"v4l2":1,"libv4l2":1,"eglstream":1,"common":1,"functionality":1,".wsi":1,"python":1,"helper":1,"simplified":1}
,"standard":{"interface":1}
,"libv4l2":{"plugin":1}
,"\u200Ctegra-egl":{"ld.so.conf":1,"\u200Clibegl_nvidia.so.0":1,"\u200Clibglesv1_cm_nvidia.so.1":1,"\u200Clibglesv2_nvidia.so.2":1,"\u200Cnvidia.json":1}
,"symbols":{"glesv2":1}
,"glesv2":{"entry":1}
,"points":{"loads":1,"location":1}
,"dispatches":{"vendor":1}
,"vendor":{"libraries":1,"library":1}
,"location":{"vendor-specific":1,"frame":1}
,"vendor-specific":{"library":1}
,"glvnd":{"egl":1,"egl_vendor.d":1}
,"\u200Ctegra":{"\u200Clibcuda.so":1,"\u200Clibcuda.so.1.1":1,"\u200Clibdrm.so.2":1,"\u200Clibglx_nvidia.so.0":1,"\u200Clibnvapputil.so":1,"\u200Clibnvargus.so":1,"\u200Clibnvargus_socketclient.so":1,"\u200Clibnvargus_socketserver.so":1,"\u200Clibnvavp.so":1,"\u200Clibnvbuf_fdmap.so.1.0.0":1,"\u200Clibnvbufsurface.so":1,"\u200Clibnvbufsurface.so.1.0.0":1,"\u200Clibnvbufsurftransform.so":1,"libnvbufsurftransform.so.1.0.0":1,"libnvbuf_utils.so":1,"\u200Clibnvbuf_utils.so.1.0.0":1,"\u200Clibnvcameratools.so":1,"\u200Clibnvcamerautils.so":1,"\u200Clibnvcam_imageencoder.so":1,"\u200Clibnvcamlog.so":1,"\u200Clibnvcamv4l2.so":1,"\u200Clibnvcolorutil.so":1,"\u200Clibnvdc.so":1,"\u200Clibnvdecode2eglimage.so":1,"\u200Clibnvdla_compiler.so":1,"\u200Clibnvdla_runtime.so":1,"\u200Clibnvdsbufferpool.so":1,"\u200Clibnvmmlite_image.so":1,"\u200Clibnvmmlite.so":1,"\u200Clibnvmmlite_utils.so":1,"\u200Clibnvmmlite_video.so":1,"\u200Clibnvmm.so":1}
,"x86":{"shared":1}
,"object":{"application":1}
,"user-space":{"interface":1}
,"acceleration":{"via":1}
,"via":{"nvavp":1,"text":1,"linux":1}
,"nvavp":{"kernel":1}
,"unmapping":{"apis":1}
,"libnvbufsurf":{"arace.so.1.0.0":1}
,"unified":{"memory":1}
,"management":{"transformation":1,"utility":1,"gbm":1}
,"transformation":{"apis":1}
,"libvl2":{"helper":1}
,"supporting":{"library":1}
,"yuv":{"frames":1}
,"frames":{"jpeg":1}
,"tvmr":{"architecture":1}
,"runtime":{"tracing":1,"library":1}
,"tracing":{"logging":1}
,"logging":{"helper":1}
,"nvcolor":{"utility":1}
,"ddk":{"vic":1}
,"uses":{"nvmedia":1}
,"nvmedia":{"nvmmbuffer":1}
,"nvmmbuffer":{"egl":1}
,"dla":{"compiler":1,"runtime":1}
,"compiler":{"library":1,"compiles":1}
,"pool":{"unified":1}
,"libray":{"implements":1}
,"producer":{"functionality":1}
,"opengl":{"image":1,"core":1,"system":1}
,"postprocessing":{"helper":1}
,"filter":{"service":1}
,"gbm":{"implementation":1}
,"governor":{"libraries":1}
,"interactions":{"cuda":1}
,"fatbinaries":{"fatbinary":1}
,"fatbinary":{"container":1}
,"container":{"format":1}
,"ptx":{"cubins":1,"gpu":1}
,"cubins":{"compiled":1}
,"implicitly":{"used":1}
,"libgl":{"libglx":1}
,"libglx":{"contains":1}
,"interaction":{"library":1}
,"spir\u2011v":{"shader":1}
,"jit":{"compiler":1}
,"compiles":{"ptx":1}
,"machine":{"code":1}
,"kernel-level":{"graphics":1}
,"tls":{"libraries":1}
,"low-level":{"helper":1}
,"required":{"deepstream":1}
,"libjpeg":{"jetson":1}
,"libdrm.so.2":{"memory":1}
,"programming":{"api":1}
,"access":{"hardware":1,"libargus":1}
,"units":{"encoder":1}
,"encoder":{"decoder":1,"library":1}
,"decoder":{"video":1}
,"pipe":{"implementation":1}
,"framework":{"utilities":1}
,"odm":{"adaptation":1}
,"adaptation":{"imager":1}
,"function":{"optical":1,"reading":1,"adding":1}
,"optical":{"flow":1}
,"flow":{"stereo":1}
,"stereo":{"disparity":1}
,"disparity":{"user":1}
,"draw":{"regions":1}
,"regions":{"put":1}
,"put":{"text":1}
,"abstraction":{"library":1,"layer":1}
,"parser":{"used":1}
,"resource":{"manager":1}
,"manager":{"nvrm":1,"kernel":1}
,"nvrm":{"graphics":1}
,"usermode":{"driver":1}
,"submitting":{"capture":1}
,"requests":{"kernel":1}
,"rtcpu":{"drivers":1}
,"test":{"results":1}
,"results":{"library":1}
,"temporal":{"noise":1}
,"noise":{"reduction":1}
,"reduction":{"tnr":1}
,"tnr":{"api":1}
,"mixer":{"renderer":1}
,".wsi":{"extension":1}
,"extension":{"support":1,"module":1}
,"winsys":{"library":1}
,"sensor":{"socket":1,"stack":1,"hal":1,"fusion":1}
,"socket":{"client":1,"services":1}
,"hal":{"hardware":1}
,"layer":{"component":1}
,"fusion":{"component":1}
,"loader":{"library":1}
,"making":{"vulkan":1}
,"xorg":{"modules":1}
,"extensions":{"libglxserver_nvidia.so":1}
,"glx":{"extension":1,"support":1}
,"side":{"glx":1}
,"broadcom":{"bluetooth":1}
,"providing":{"libargus":1}
,"clients":{"access":1}
,"services":{"client":1}
,"quality":{"tuning":1}
,"libnvv4l2":{"libraries":1}
,"libnvv4lconvert":{"libraries":1}
,"licence":{"generic":1}
,"nvdla":{"libraries":1}
,"\u200Cegl_external_platform.d":{"\u200Cnvidia_wayland.json":1}
,"external":{"platform":1}
,"egl_vendor.d":{"\u200C10_nvidia.json":1}
,"var":{"nvidia":1}
,"nvcam":{"apps":1,"application":1,"input":1,"output":1,"settings":1}
,"readme.txt":{"file":1}
,"haar":{"cascade":1}
,"cascade":{"generated":1}
,"generated":{"face":1}
,"face":{"image":1,"detection":1}
,"nv_tools.tbz2":{"archive":1}
,"clock":{"configuration":1,"frequency":1}
,"auto-start":{"nvpmodel":1}
,"indicator":{"desktop":1,"shows":1}
,"jetson-io":{"\u200Cconfig-by-function.py":1,"\u200Cconfig-by-hardware.py":1,"\u200Cconfig-by-pin.py":1,"headers":1,"tool":1,"jetson":1,"jetson\u200C":1,"\u200Cjetson-io.py":1,"linux":1,"utils":1}
,"configuring":{"40-pin":1}
,"40-pin":{"header":1}
,"supported":{"functions":1,"hardware":1}
,"displaying":{"40-pin":1}
,"class":{"helper":1}
,"functions":{"jetson":1,"reading":1,"using":1,"checking":1,"subprocess":1}
,"makes":{"python":1}
,"search":{"subdirectory":1}
,"subdirectory":{"modules":1}
,"classes":{"jetson":1}
,"pins":{"pin":1}
,"pin":{"groups":1,"state":1,"functions":1}
,"groups":{"pin":1}
,"jetson\u200C":{"pmx.py":1}
,"curses-based":{"application":1}
,"graphically":{"via":1}
,"reading":{"linux":1}
,"adding":{"entry":1}
,"pinctrl":{"debugfs":1}
,"debugfs":{"entries":1,"nodes":1}
,"utils":{"\u200C__init__.py":1,"\u200Cdtc.py":1,"\u200Cfio.py":1,"\u200Csyscall.py":1}
,"checking":{"file":1}
,"simplified":{"helper":1}
,"subprocess":{"module":1}
,"frequency":{"control":1}
,"performance":{"measurement":1}
,"measurement":{"utility":1}
,"postinstall":{"script":1}
,"reads":{"platform-specific":1}
,"registers":{"needed":1}
,"interprets":{"parameters":1}
,"derive":{"information":1}
,"dram":{"capabilities":1}
,"select":{"system":1}
,"model":{"maxq":1}
,"maxq":{"maxp":1}
,"nvpmodel_indicator":{"\u200Cnv_logo.svg":1,"\u200Cnvpmodel_indicator.py":1,"\u200Cnvpmodel.py":1,"\u200Cover_current.py":1,"\u200Cthermal_throttle_alert.py":1}
,"svg":{"logo":1}
,"logo":{"that\u0027s":1}
,"that\u0027s":{"suitable":1}
,"suitable":{"used":1}
,"panel":{"indicator":1}
,"easy":{"switch":1}
,"switch":{"power":1}
,"backend":{"provides":1,"libraries":1}
,"helpers":{"gui":1}
,"front":{"end":1}
,"overcurrent":{"event":1}
,"event":{"plugin":1}
,"thermal":{"event":1}
,"weston.tbz2":{"archive":1}
,"sumlinks":{"weston":1}
,"include":{"libdrm":1}
,"drm":{"samples":1}
,"samples":{"multimedia":1}
,"gnu-specific":{"files":1}
,"weston-ivi-layer":{"libraries":1,"test":1}
,"weston-specific":{"files":1}
,"\u200Cweston":{"\u200Cdesktop-shell.so":1,"\u200Cdrm-backend.so":1,"\u200Ceglwlinputeventexample":1,"\u200Ceglwlmocknavigation":1,"\u200Cfullscreen-shell.so":1,"\u200Cgl-renderer.so":1,"\u200Chmi-controller.so":1,"\u200Civi-controller.so":1,"\u200Civi-shell.so":1,"\u200Clayermanagercontrol":1,"\u200Clibilmclient.so.2.2.0":1,"\u200Clibilmcommon.so.2.2.0":1,"\u200Clibilmcontrol.so.2.2.0":1,"\u200Clibilminput.so.2.2.0":1,"\u200Clibweston-6.so.0":1,"\u200Clibweston-desktop-6.so.0":1,"\u200Csimple-weston-client":1,"\u200Cspring-tool":1,"\u200Cwayland-backend.so":1,"\u200Cweston":1,"\u200Cweston-calibrator":1,"\u200Cweston-clickdot":1,"\u200Cweston-cliptest":1,"\u200Cweston-content-protection":1,"\u200Cweston-debug":1,"\u200Cweston-desktop-shell":1,"\u200Cweston-dnd":1,"\u200Cweston-eventdemo":1,"\u200Cweston-flower":1,"\u200Cweston-fullscreen":1,"\u200Cweston-image":1,"\u200Cweston-info":1,"\u200Cweston-ivi-shell-user-interface":1,"\u200Cweston-keyboard":1,"\u200Cweston-launch":1,"\u200Cweston-multi-resource":1,"\u200Cweston-output-mode":1,"\u200Cweston-resizor":1,"\u200Cweston-scaler":1,"\u200Cweston-screenshooter":1,"\u200Cweston-simple-dmabuf-egldevice":1,"\u200Cweston-simple-egl":1,"\u200Cweston-simple-shm":1,"\u200Cweston-simple-touch":1,"\u200Cweston-smoke":1,"\u200Cweston-stacking":1,"\u200Cweston-subsurfaces":1,"\u200Cweston-terminal":1,"\u200Cweston-transformed":1}
,"single":{"surface":1}
,"surface":{"per":1}
,"per":{"output":1}
,"implemens":{"weston-content-protection":1}
,"weston-content-protection":{"protocol":1}
,"docs":{"weston":1}
,"apache":{"license":1}
,"icons":{"images":1}
}
;Search.control.loadWordPairs(pairs);
