var pairs =
{
"nvidia":{"jetson":1,"jetpack":1,"offers":1,"drivers":1,"sdk":1,"publishes":1,"autonomous":1,"developer":1}
,"jetson":{"world\u0027s":1,"platform":1,"modules":1,"module":1,"linux":1,"developer":1,"product":1,"software":1,"download":1,"device":1,"products":1,"module\u2019s":1,"xavier":1,"nano":1,"agx":1,"tx2":1,"tx2i":1,"tx1":1,"faq":1,"devices":1}
,"world\u0027s":{"leading":1}
,"leading":{"platform":1}
,"platform":{"edge":1,"compute-intensive":1,"includes":1,"software":1}
,"edge":{"high-performance":1}
,"high-performance":{"low-power":1}
,"low-power":{"computing":1}
,"computing":{"deep":1,"system":1}
,"deep":{"learning":1}
,"learning":{"computer":1}
,"computer":{"vision":1}
,"vision":{"makes":1}
,"makes":{"ideal":1}
,"ideal":{"platform":1}
,"compute-intensive":{"projects":1}
,"projects":{"jetson":1}
,"includes":{"variety":1,"l4t":1,"p3668-0000":1,"p3448-0000":1,"p3448-0003":1,"p2888-0001":1,"p3310-1000":1,"versions":1}
,"variety":{"jetson":1}
,"modules":{"together":1,"different":1,"suitable":1,"developer":1,"pcb":1}
,"together":{"nvidia":1,"jetpack":1,"accelerated":1}
,"jetpack":{"sdk":1,"bundles":1,"components":1}
,"module":{"computing":1,"nvidia":1,"attached":1,"ships":1,"bootloader":1,"production":1,"adaptation":1,"reference":1,"name":1,"eeprom":1}
,"system":{"packaged":1,"module":1,"excluding":1}
,"packaged":{"plug-in":1}
,"plug-in":{"unit":1}
,"unit":{"system":1}
,"offers":{"variety":1}
,"different":{"capabilities":1,"suffixed":1}
,"bundles":{"jetson":1}
,"software":{"starting":1,"case":1,"pre-installed":1,"image":1,"jetson":1,"libraries":1,"fit":1,"development":1,"hardware":1,"features":1}
,"starting":{"nvidia":1}
,"linux":{"driver":1,"kernel":1}
,"driver":{"package":1}
,"package":{"l4t":1,"developer":1}
,"l4t":{"l4t":1,"provides":1,"together":1,"jetpack":1,"software":1,"home":1,"module":1}
,"provides":{"linux":1}
,"kernel":{"bootloader":1}
,"bootloader":{"nvidia":1,"file":1}
,"drivers":{"flashing":1}
,"flashing":{"utilities":1}
,"utilities":{"sample":1}
,"sample":{"filesystem":1,"applications":1}
,"filesystem":{"jetson":1}
,"developer":{"kits":1,"tools":1,"kit":1,"guide":1,"web":1,"site":1}
,"kits":{"modules":1,"include":1,"intended":1,"derived":1,"sale":1,"jetson":1}
,"include":{"non-production":1,"jetson":1}
,"non-production":{"specification":1}
,"specification":{"jetson":1}
,"attached":{"reference":1}
,"reference":{"carrier":1}
,"carrier":{"board":1}
,"board":{"together":1,"designed":1,"topic":1,"combinations":1,"pcb":1}
,"sdk":{"used":1,"comprehensive":1,"manager":1}
,"used":{"develop":1}
,"develop":{"test":1}
,"test":{"software":1}
,"case":{"jetson":1}
,"intended":{"production":1}
,"suitable":{"deployment":1}
,"deployment":{"production":1}
,"production":{"environment":1,"jetson":1,"carrier":1,"version":1}
,"environment":{"throughout":1}
,"throughout":{"operating":1}
,"operating":{"lifetime":1}
,"lifetime":{"jetson":1}
,"ships":{"software":1}
,"pre-installed":{"attach":1}
,"attach":{"carrier":1}
,"designed":{"procured":1}
,"procured":{"end":1}
,"end":{"product":1}
,"product":{"flash":1,"feature":1,"dropdown":1}
,"flash":{"software":1,"jetson":1}
,"image":{"you\u2019ve":1}
,"you\u2019ve":{"developed":1}
,"comprehensive":{"resource":1}
,"resource":{"building":1,"information":1}
,"building":{"applications":1}
,"applications":{"includes":1,"developer":1}
,"accelerated":{"software":1}
,"libraries":{"apis":1}
,"apis":{"sample":1}
,"tools":{"documentation":1}
,"manager":{"install":1}
,"install":{"l4t":1}
,"components":{"jetson":1}
,"kit":{"instructions":1,"user":1,"production":1,"p3518-0000":1,"version":1,"p3450-0000":1,"p3541-0000":1,"p2972-0000":1,"p2771-0000":1,"p3449-0000":1}
,"instructions":{"appropriate":1}
,"appropriate":{"jetson":1}
,"user":{"guide":1,"guides":1}
,"guide":{"alternatively":1,"contains":1,"primary":1,"covers":1,"topics":1,"topic":1}
,"alternatively":{"topic":1}
,"topic":{"quick":1,"jetson":1,"related":1,"concern":1}
,"quick":{"start":1}
,"start":{"flash":1}
,"file":{"system":1}
,"excluding":{"jetpack":1}
,"information":{"moving":1,"need":1,"software":1,"various":1}
,"moving":{"completed":1}
,"completed":{"application":1}
,"application":{"jetson":1}
,"adaptation":{"bring-up":1}
,"bring-up":{"jetson":1}
,"customize":{"l4t":1}
,"fit":{"needs":1}
,"needs":{"project":1}
,"project":{"developer":1}
,"contains":{"information":1,"links":1}
,"need":{"optimize":1}
,"optimize":{"complete":1}
,"complete":{"jetson":1}
,"documentation":{"jetson":1}
,"primary":{"resource":1}
,"development":{"jetson":1}
,"publishes":{"documents":1}
,"documents":{"address":1,"others":1,"specific":1,"useful":1}
,"address":{"specific":1}
,"specific":{"aspects":1,"jetson":1}
,"aspects":{"jetson":1}
,"hardware":{"several":1}
,"several":{"important":1,"documents":1}
,"important":{"ones":1,"facts":1}
,"ones":{"listed":1}
,"listed":{"topic":1}
,"related":{"documentation":1}
,"others":{"available":1}
,"available":{"jetson":1}
,"download":{"center":1}
,"center":{"find":1}
,"find":{"document":1}
,"document":{"enter":1}
,"enter":{"string":1}
,"string":{"consecutive":1}
,"consecutive":{"words":1}
,"words":{"document\u2019s":1}
,"document\u2019s":{"title":1}
,"title":{"search":1}
,"search":{"box":1,"documents":1}
,"box":{"product":1}
,"dropdown":{"restrict":1}
,"restrict":{"search":1}
,"autonomous":{"machines":1}
,"machines":{"getting":1}
,"getting":{"started":1}
,"started":{"page":1,"guides":1}
,"page":{"contains":1,"links":1,"nvidia":1}
,"links":{"several":1,"getting":1}
,"useful":{"developers":1}
,"developers":{"new":1}
,"new":{"artificial":1}
,"artificial":{"intelligence":1}
,"intelligence":{"programming":1}
,"programming":{"jetson":1}
,"products":{"page":1}
,"guides":{"user":1,"jetson":1}
,"module\u2019s":{"developer":1}
,"additional":{"resources":1}
,"resources":{"important":1}
,"facts":{"l4t":1}
,"home":{"page":1}
,"web":{"site":1}
,"devices":{"supported":1,"heading":1,"variants":1,"includes":1}
,"supported":{"document":1,"jetson":1}
,"covers":{"l4t":1}
,"combinations":{"described":1}
,"described":{"table":1}
,"type":{"module":1}
,"name":{"p\u2011number":1}
,"compatible":{"developer":1,"p3448-0000":1,"p3448-0002":1}
,"xavier":{"p3668-0000":1,"developer":1,"p3668-0001":1,"series":1,"16gb":1,"32gb":1,"industrial":1,"devices":1,"scope":1,"original":1,"note":1,"considered":1}
,"p3518-0000":{"includes":1}
,"p3668-0000":{"module":1}
,"nano":{"devices":1,"p3448-0000":1,"developer":1,"p3448-0002":1,"2gb":1,"scope":1}
,"p3450-0000":{"includes":1}
,"p3448-0000":{"module":1,"modules":1,"production":1}
,"2gb":{"p3448-0003":1,"developer":1}
,"experimental":{"educational":1}
,"p3541-0000":{"p3541-0001":1}
,"p3541-0001":{"includes":1}
,"p3448-0003":{"module":1}
,"agx":{"xavier":1}
,"16gb":{"p2888-0001":1}
,"p2972-0000":{"includes":1}
,"p2888-0001":{"module":1}
,"32gb":{"p2888-0004":1}
,"industrial":{"p2888-0008":1,"hostile":1}
,"tx2":{"series":1,"p3310-1000":1,"developer":1,"4gb":1,"p3636-0010":1,"scope":1,"original":1,"include":1}
,"p2771-0000":{"includes":1}
,"p3310-1000":{"module":1}
,"tx2i":{"p3489-0008":1,"jetson":1}
,"hostile":{"environments":1}
,"4gb":{"p3489-0888":1}
,"tx1":{"p2180-1000":1}
,"p-numbers":{"jetson":1}
,"derived":{"699-level":1}
,"699-level":{"part":1}
,"part":{"number":1,"jetson":1}
,"number":{"jetson":1,"modules":1}
,"eeprom":{"layout":1}
,"layout":{"details":1}
,"details":{"structure":1}
,"structure":{"699-level":1}
,"p3449-0000":{"carrier":1}
,"pcb":{"revision":1}
,"revision":{"a02":1}
,"a02":{"compatible":1}
,"p3448-0002":{"modules":1,"jetson":1}
,"sale":{"outside":1}
,"outside":{"united":1}
,"united":{"states":1}
,"states":{"may":1}
,"may":{"different":1}
,"suffixed":{"numbers":1}
,"various":{"jetson":1}
,"site":{"jetson":1}
,"topics":{"identify":1}
,"identify":{"devices":1}
,"concern":{"supported":1}
,"heading":{"subheading":1}
,"subheading":{"specifies":1}
,"specifies":{"scope":1}
,"scope":{"examples":1,"jetson":1}
,"examples":{"headings":1,"subheadings":1}
,"series":{"software":1,"devices":1,"variants":1}
,"power":{"management":1}
,"management":{"jetson":1}
,"applies":{"jetson":1}
,"variants":{"jetson":1}
,"version":{"original":1,"p3448-0002":1}
,"original":{"jetson":1}
,"versions":{"jetson":1}
,"note":{"jetson":1}
,"considered":{"part":1}
,"similarly":{"scope":1}
}
;Search.control.loadWordPairs(pairs);
