var pairs =
{
"legal":{"information":1}
,"nvidia":{"design":1,"makes":1,"assumes":1,"specifications":1,"products":1,"nvidia":1,"logo":1,"united":1,"license":1,"affiliates":1}
,"design":{"specifications":1}
,"specifications":{"reference":1,"mentioned":1}
,"reference":{"boards":1}
,"boards":{"files":1}
,"files":{"drawings":1}
,"drawings":{"diagnostics":1}
,"diagnostics":{"lists":1}
,"lists":{"documents":1}
,"documents":{"together":1}
,"together":{"separately":1}
,"separately":{"materials":1}
,"materials":{"provided":1,"express":1}
,"provided":{"nvidia":1}
,"makes":{"warranties":1}
,"warranties":{"express":1,"including":1}
,"express":{"implied":1,"written":1}
,"implied":{"statutory":1,"conditions":1,"warranty":1}
,"statutory":{"otherwise":1}
,"otherwise":{"respect":1,"patent":1}
,"respect":{"materials":1}
,"conditions":{"representations":1}
,"representations":{"warranties":1}
,"including":{"implied":1}
,"warranty":{"condition":1}
,"condition":{"title":1}
,"title":{"merchantability":1}
,"merchantability":{"satisfactory":1}
,"satisfactory":{"quality":1}
,"quality":{"fitness":1}
,"fitness":{"particular":1}
,"particular":{"purpose":1}
,"purpose":{"non-infringement":1}
,"non-infringement":{"hereby":1}
,"hereby":{"excluded":1}
,"excluded":{"maximum":1}
,"maximum":{"extent":1}
,"extent":{"permitted":1}
,"permitted":{"law":1}
,"information":{"furnished":1,"infringement":1,"previously":1}
,"furnished":{"believed":1}
,"believed":{"accurate":1}
,"accurate":{"reliable":1}
,"reliable":{"however":1}
,"however":{"nvidia":1}
,"assumes":{"responsibility":1}
,"responsibility":{"consequences":1}
,"consequences":{"information":1}
,"infringement":{"patents":1}
,"patents":{"third":1}
,"third":{"parties":1}
,"parties":{"may":1}
,"may":{"result":1,"trademarks":1}
,"result":{"license":1}
,"license":{"granted":1}
,"granted":{"implication":1}
,"implication":{"otherwise":1}
,"patent":{"patent":1,"nvidia":1}
,"mentioned":{"publication":1}
,"publication":{"subject":1,"supersedes":1}
,"subject":{"change":1}
,"change":{"without":1}
,"without":{"notice":1,"express":1}
,"notice":{"publication":1}
,"supersedes":{"replaces":1}
,"replaces":{"information":1}
,"previously":{"supplied":1}
,"supplied":{"nvidia":1}
,"products":{"authorized":1}
,"authorized":{"critical":1}
,"critical":{"components":1}
,"components":{"life":1}
,"life":{"support":1}
,"support":{"devices":1}
,"devices":{"systems":1}
,"systems":{"without":1}
,"written":{"approval":1}
,"approval":{"nvidia":1}
,"logo":{"cuda":1,"high-definition":1}
,"cuda":{"jetson":1}
,"jetson":{"tegra":1,"nano":1,"agx":1,"xavier":1}
,"tegra":{"jetson":1}
,"nano":{"jetson":1}
,"agx":{"xavier":1}
,"xavier":{"jetson":1,"nsight":1}
,"nsight":{"tensorrt":1}
,"tensorrt":{"visionworks":1}
,"visionworks":{"trademarks":1}
,"trademarks":{"registered":1,"nvidia":1,"respective":1,"hdmi":1,"arm":1,"owned":1}
,"registered":{"trademarks":1}
,"united":{"states":1}
,"states":{"countries":1}
,"countries":{"company":1}
,"company":{"product":1,"arm":1}
,"product":{"names":1}
,"names":{"may":1,"property":1}
,"respective":{"companies":1,"holders":1}
,"companies":{"associated":1}
,"android":{"robot":1}
,"robot":{"reproduced":1}
,"reproduced":{"modified":1}
,"modified":{"work":1}
,"work":{"created":1}
,"created":{"shared":1}
,"shared":{"google":1}
,"google":{"used":1}
,"used":{"according":1,"represent":1}
,"according":{"terms":1}
,"terms":{"described":1}
,"described":{"creative":1}
,"creative":{"commons":1}
,"commons":{"3.0":1}
,"3.0":{"attribution":1}
,"attribution":{"license":1}
,"hdmi":{"hdmi":1,"logo":1,"licensing":1}
,"high-definition":{"multimedia":1}
,"multimedia":{"interface":1}
,"interface":{"trademarks":1}
,"licensing":{"llc":1}
,"arm":{"amba":1,"powered":1,"limited":1,"used":1,"holdings":1,"arm":1,"korea":1,"taiwan":1,"france":1,"consulting":1,"germany":1,"embedded":1,"norway":1,"sweden":1}
,"amba":{"arm":1}
,"powered":{"registered":1}
,"limited":{"cortex":1,"brands":1,"regional":1,"arm":1}
,"cortex":{"mpcore":1}
,"mpcore":{"mali":1}
,"mali":{"trademarks":1}
,"brands":{"product":1}
,"property":{"respective":1}
,"holders":{"arm":1}
,"represent":{"arm":1}
,"holdings":{"plc":1}
,"plc":{"operating":1}
,"operating":{"company":1}
,"regional":{"subsidiaries":1}
,"subsidiaries":{"arm":1}
,"korea":{"limited":1}
,"taiwan":{"limited":1}
,"france":{"sas":1}
,"sas":{"arm":1}
,"consulting":{"shanghai":1}
,"shanghai":{"ltd":1}
,"ltd":{"arm":1}
,"germany":{"gmbh":1}
,"gmbh":{"arm":1}
,"embedded":{"technologies":1}
,"technologies":{"pvt":1}
,"pvt":{"ltd":1}
,"norway":{"arm":1}
,"bluetooth":{"word":1,"sig":1}
,"word":{"mark":1}
,"mark":{"logos":1}
,"logos":{"registered":1}
,"owned":{"bluetooth":1}
,"sig":{"marks":1}
,"marks":{"nvidia":1}
,"2019-2021":{"nvidia":1}
}
;Search.control.loadWordPairs(pairs);
