var pairs =
{
"graphics":{"sample":1,"samples":1,"systems":1,"system":1,"x11":1}
,"sample":{"applications":1,"source":1,"built":1,"appropriate":1,"application":1}
,"topic":{"contains":1,"gives":1}
,"contains":{"information":1,"instructions":1}
,"information":{"several":1}
,"several":{"sample":1}
,"applications":{"provided":1,"may":1,"either":1,"three":1,"start":1,"selected":1,"first":1,"ensure":1,"started":1,"overlay":1,"\u2011layer":1,"ways":1}
,"provided":{"nvidia":1}
,"nvidia":{"jetson":1,"graphics":1,"graphics_demos":1,"application":1,"sample":1}
,"jetson":{"linux":1}
,"linux":{"driver":1}
,"driver":{"package":1,"uses":1}
,"package":{"l4t":1,"download":1}
,"samples":{"included":1,"target":1,"currently":1,"directory":1}
,"included":{"l4t":1}
,"l4t":{"topic":1,"provides":1}
,"gives":{"detailed":1}
,"detailed":{"steps":1}
,"steps":{"building":1}
,"building":{"running":1,"samples":1,"sample":1}
,"running":{"samples":1,"sample":1,"default":1,"weston":1,"weston-launch":1,"egldevice":1,"5.000000":1}
,"source":{"files":1}
,"files":{"available":1}
,"available":{"directory":1}
,"directory":{"usr":1,"chosen":1}
,"usr":{"src":1,"bin":1,"lib":1}
,"src":{"nvidia":1}
,"graphics_demos":{"samples":1,"readme":1,"bin":1,"prebuilts":1}
,"currently":{"provided":1}
,"may":{"built":1}
,"built":{"either":1,"target":1}
,"either":{"host":1,"system":1,"running":1}
,"host":{"target":1}
,"target":{"file":1,"run":1,"system":1}
,"file":{"usr":1,"removing":1}
,"readme":{"contains":1}
,"instructions":{"building":1}
,"provides":{"pre-built":1}
,"pre-built":{"binaries":1,"version":1}
,"binaries":{"sample":1}
,"three":{"supported":1}
,"supported":{"graphics":1}
,"systems":{"pre-built":1}
,"starting":{"graphics":1,"preferred":1}
,"section":{"describes":1}
,"describes":{"procedure":1}
,"procedure":{"starting":1}
,"preferred":{"graphics":1}
,"system":{"prerequisite":1,"ethernet":1}
,"prerequisite":{"running":1}
,"x11":{"window":1,"graphics":1,"wayland":1}
,"window":{"system":1,"i.e":1}
,"run":{"x11":1,"wayland":1,"weston":1,"egldevice":1,"sample":1,"pre-built":1,"log":1,"gears":1,"application":1}
,"start":{"server":1,"sample":1}
,"server":{"background":1,"open":1,"running":1,"compositor":1}
,"background":{"export":1}
,"export":{"display":1,"xdg_runtime_dir":1}
,"display":{"variable":1,"environment":1,"server":1,"using":1,"prints":1,"rate":1}
,"variable":{"driver":1,"start":1}
,"uses":{"launch":1}
,"launch":{"sample":1,"instance":1,"weston":1}
,"selected":{"display":1}
,"enter":{"commands":1}
,"commands":{"export":1,"stop":1,"run":1,"need":1}
,"environment":{"variable":1,"directory":1}
,"open":{"terminal":1}
,"terminal":{"window":1,"shows":1}
,"i.e":{"launch":1}
,"instance":{"xterm":1}
,"wayland":{"graphics":1,"egldevice":1}
,"first":{"stop":1}
,"stop":{"server":1,"gdm":1,"sample":1}
,"default":{"launch":1,"default":1,"crtc":1}
,"weston":{"either":1,"binary":1,"root":1,"-launch":1,"--idle-time":1,"using":1}
,"binary":{"usr":1}
,"bin":{"weston":1,"weston-launch":1,"graphics":1,"es2gears":1,"glxgears":1}
,"root":{"user":1,"usr":1}
,"user":{"running":1,"commands":1}
,"weston-launch":{"binary":1,"non-root":1,"$user":1}
,"sudo":{"systemctl":1,"loginctl":1,"pkill":1,"modprobe":1,"-sf":1,"groupadd":1,"usermod":1,"chown":1,"chmod":1,"apt":1,"apt-get":1}
,"systemctl":{"stop":1}
,"loginctl":{"terminate-seat":1}
,"terminate-seat":{"seat0":1}
,"tegra":{"dummy":1,"libnvgbm.so":1}
,"dummy":{"drm":1}
,"drm":{"driver":1}
,"modprobe":{"tegra-udrm":1}
,"tegra-udrm":{"modeset":1}
,"-sf":{"usr":1}
,"lib":{"aarch64-linux-gnu":1}
,"aarch64-linux-gnu":{"tegra":1,"libgbm.so.1":1}
,"libnvgbm.so":{"usr":1}
,"unset":{"display":1}
,"mkdir":{"tmp":1}
,"tmp":{"xdg":1}
,"chmod":{"700":1,"usr":1}
,"700":{"tmp":1}
,"xdg_runtime_dir":{"tmp":1}
,"using":{"weston-launch":1,"egloutput":1,"alpha":1}
,"non-root":{"user":1}
,"need":{"entered":1}
,"entered":{"once":1}
,"once":{"booting":1}
,"groupadd":{"weston-launch":1}
,"usermod":{"weston-launch":1}
,"chown":{"root":1}
,"egldevice":{"graphics":1,"applications":1}
,"ensure":{"display":1}
,"compositor":{"running":1}
,"started":{"default":1}
,"crtc":{"plane":1}
,"plane":{"communicate":1,"sample":1}
,"communicate":{"directly":1}
,"directly":{"display":1}
,"egloutput":{"ext":1}
,"ext":{"information":1,"egl_ext_stream_consumer_egloutput.txt":1}
,"https":{"www.khronos.org":1}
,"www.khronos.org":{"registry":1}
,"registry":{"egl":1}
,"egl":{"extensions":1}
,"extensions":{"ext":1}
,"want":{"start":1}
,"overlay":{"plane":1}
,"\u2011layer":{"option":1}
,"appropriate":{"subdirectory":1}
,"subdirectory":{"samples":1}
,"chosen":{"graphics":1}
,"example":{"run":1,"upstream":1}
,"version":{"gears":1}
,"prebuilts":{"bin":1}
,"application":{"presents":1,"press":1,"gears":1,"example":1,"nvidia":1,"distinct":1,"steps":1}
,"presents":{"rendered":1}
,"rendered":{"screen":1}
,"screen":{"display":1}
,"prints":{"run":1}
,"log":{"terminal":1}
,"shows":{"display":1}
,"rate":{"frames":1}
,"frames":{"second":1}
,"alpha":{"value":1,"1.0":1}
,"value":{"specified":1}
,"specified":{"constant":1}
,"constant":{"blending":1}
,"blending":{"range":1}
,"range":{"using":1}
,"demo":{"mode":1}
,"mode":{"1920":1}
,"1920":{"1080":1}
,"5.000000":{"seconds":1}
,"press":{"ctrl":1}
,"upstream":{"sample":1,"graphics":1}
,"gears":{"application":1}
,"distinct":{"nvidia":1}
,"install":{"run":1,"mesa-utils":1,"mesa-utils-extra":1}
,"boot":{"target":1}
,"ethernet":{"connection":1}
,"enable":{"package":1}
,"download":{"universe":1}
,"universe":{"repository":1}
,"repository":{"editing":1}
,"editing":{"apt":1}
,"apt":{"sources.list":1}
,"sources.list":{"root":1}
,"uncomment":{"following":1}
,"following":{"line":1}
,"line":{"file":1}
,"removing":{"leading":1}
,"leading":{"character":1}
,"deb":{"http":1}
,"http":{"ports.ubuntu.com":1}
,"ports.ubuntu.com":{"ubuntu-ports":1}
,"ubuntu-ports":{"bionic":1}
,"bionic":{"universe":1}
,"update":{"repository":1}
,"apt-get":{"update":1,"install":1}
,"mesa-utils":{"mesa-utils-extra":1}
,"mesa-utils-extra":{"packages":1}
}
;Search.control.loadWordPairs(pairs);
