var pairs =
{
"weston":{"wayland":1,"implementation":1,"6.0":1,"root":1,"--tty":1,"output":1,"using":1,"tests":1,"weston-test.so":1,"ivi-shell":1,"binary":1,"reports":1,"running":1,"monitors":1,"tegra-udrm":1,"without":1,"codeline":1,"main":1,"crashes":1,"page":1,"configured":1,"supports":1,"assigns":1,"evaluates":1,"surfaces":1,"--debug":1,"client":1,"compositor":1,"test":1,"currently":1,"dma-buf":1,"following":1,"uses":1,"creates":1,"obtains":1,"calls":1,"recompositing":1,"\u2011\u2011debug":1,"debug":1}
,"wayland":{"windowing":1,"dma-buf":1,"protocol":1,"surface":1}
,"windowing":{"system":1}
,"l4t":{"supports":1,"weston.ini":1}
,"supports":{"weston":1,"multiple":1,"mixed":1,"implemented":1,"nv16":1,"formats":1,"modifiers":1}
,"implementation":{"wayland":1}
,"system":{"current":1}
,"current":{"release":1,"limitations":1}
,"release":{"l4t":1,"jetpack":1,"jetson":1}
,"running":{"weston":1,"hot":1,"applications":1,"verify":1,"prepare":1}
,"jetpack":{"supports":1}
,"6.0":{"launch":1,"supports":1}
,"launch":{"entering":1,"weston":1,"once":1,"nvgldemo":1,"few":1}
,"entering":{"commands":1}
,"stop":{"xerver":1,"sudo":1,"running":1}
,"sudo":{"service":1,"pkill":1,"modprobe":1,"-sf":1,"xdg_runtime_dir":1,"groupadd":1,"usermod":1,"chown":1,"chmod":1}
,"service":{"gdm":1}
,"gdm":{"stop":1}
,"pkill":{"xorg":1}
,"tegra":{"dummy":1,"libnvgbm.so":1,"weston":1}
,"dummy":{"drm":1,"kernel":1}
,"drm":{"driver":1,"subsystem":1,"driver-like":1,"module":1,"supports":1,"read":1,"compositor":1,"framebuffer":1}
,"modprobe":{"tegra-udrm":1}
,"tegra-udrm":{"modeset":1,"drivers":1,"driver":1}
,"-sf":{"usr":1}
,"usr":{"lib":1,"bin":1}
,"lib":{"aarch64-linux-gnu":1}
,"aarch64-linux-gnu":{"tegra":1,"libgbm.so.1":1}
,"libnvgbm.so":{"usr":1}
,"environment":{"directory":1,"variable":1}
,"directory":{"setup":1}
,"unset":{"display":1}
,"mkdir":{"tmp":1}
,"tmp":{"xdg":1}
,"chmod":{"700":1,"usr":1}
,"700":{"tmp":1}
,"choose":{"valid":1,"categories":1}
,"valid":{"tty":1}
,"export":{"weston_tty":1}
,"root":{"user":1,"usr":1}
,"xdg_runtime_dir":{"tmp":1}
,"xdg":{"weston":1,"weston-simple-egl":1,"weston-simple-dmabuf-egldevice":1,"weston-debug":1,"color-format.weston":1}
,"--tty":{"$weston_tty":1}
,"$weston_tty":{"--idle-time":1}
,"optional":{"wayland_debug":1,"--use-egldevice":1}
,"wayland_debug":{"server":1}
,"--use-egldevice":{"disable":1}
,"disable":{"gbm":1}
,"gbm":{"swapchains":1,"eglstream":1,"specify":1,"commonly":1,"buffer":1,"library":1,"functions":1}
,"swapchains":{"eglstreams":1}
,"eglstreams":{"weston":1,"add":1}
,"using":{"weston-launch":1,"udev":1,"ivi-shell":1,"ivi-layermanagement":1,"dma-buf":1,"mixed":1,"renderer":1,"different":1,"nbuf_utils":1,"vpr":1,"linux":1,"gbm":1,"egl_ext_image_dma_buf_import":1,"drmmodesetplane":1,"weston-debug":1}
,"weston-launch":{"non-root":1,"$user":1}
,"non-root":{"user":1}
,"groupadd":{"weston-launch":1}
,"usermod":{"weston-launch":1}
,"chown":{"root":1}
,"bin":{"weston-launch":1}
,"run":{"client":1,"weston-debug":1,"test":1,"verified":1,"sample":1,"weston-simple-dmabuf-egldevice":1,"app":1,"weston":1}
,"tests":{"weston-test.so":1}
,"weston-test.so":{"module":1}
,"module":{"loaded":1,"notify":1,"example":1}
,"loaded":{"parameter":1}
,"parameter":{"weston.ini":1,"gl_texture_protected_ext":1}
,"e.g":{"--modules":1}
,"--modules":{"usr":1,"ivi-controller.so":1,"weston-test.so":1}
,"launching":{"weston":1}
,"ivi-shell":{"ivi-controller":1,"display":1,"originally":1}
,"device":{"pass":1,"launching":1,"gbm_create_device":1,"width":1}
,"pass":{"arguments":1,"nvbuffercreate":1,"weston-debug":1}
,"arguments":{"weston":1}
,"--shell":{"ivi-shell.so":1}
,"ivi-shell.so":{"--modules":1}
,"multiple":{"display":1,"overlays":1,"heads":1,"displays":1,"hotplug":1}
,"display":{"heads":1,"configuration":1,"window":1,"options":1,"connection":1,"launching":1,"application":1,"connected":1,"re-connected":1,"certain":1,"windows":1,"video":1,"vpr":1,"hardware":1}
,"nvidia":{"jetson":1,"enhancement":1}
,"jetson":{"nano":1,"tx2":1,"linux":1}
,"nano":{"devices":1}
,"devices":{"jetson":1,"support":1,"display":1}
,"tx2":{"series":1}
,"series":{"devices":1}
,"support":{"multiple":1,"added":1,"hotplug":1,"nv16":1,"protected":1,"available":1,"weston":1}
,"heads":{"multiple":1,"l4t":1}
,"overlays":{"described":1,"compositing":1}
,"described":{"display":1}
,"configuration":{"bring-up":1,"changes":1}
,"bring-up":{"topic":1}
,"topic":{"jetson":1}
,"linux":{"driver":1,"dma-buf":1}
,"driver":{"package":1,"instead":1,"drm-nvdc":1,"tegra-udrm":1,"signals":1}
,"package":{"development":1}
,"development":{"guide":1}
,"weston.ini":{"expected":1,"display":1}
,"expected":{"resolution":1}
,"resolution":{"orientation":1}
,"orientation":{"monitors":1}
,"displays":{"connected":1,"ivi-shell":1,"hot-plugging":1,"eight":1}
,"connected":{"applications":1,"different":1,"connect":1,"launch":1}
,"applications":{"launched":1,"dynamically":1,"wl_shm_format_nv24":1,"call":1}
,"launched":{"contains":1,"drag":1}
,"contains":{"mouse":1}
,"mouse":{"pointer":1}
,"pointer":{"time":1}
,"time":{"launch":1}
,"once":{"application":1}
,"application":{"launched":1,"nvgldemo":1,"drawing":1,"connect":1,"window":1,"weston-simple-dmabuf-egldevice":1,"weston-debug":1,"displays":1}
,"drag":{"across":1}
,"across":{"boundary":1}
,"boundary":{"displays":1}
,"different":{"resolutions":1,"color":1}
,"resolutions":{"weston":1}
,"reports":{"frame":1}
,"frame":{"rate":1,"weston":1}
,"rate":{"display":1}
,"window":{"displayed":1,"disappears":1,"gfx":1,"\u0027simple-dmabuf-egldevice":1,"\u0027simple-egl":1}
,"monitor":{"removed":1}
,"removed":{"weston":1,"takes":1}
,"hot":{"removal":1,"plugging":1}
,"removal":{"running":1}
,"dynamically":{"shift":1}
,"shift":{"remaining":1}
,"remaining":{"active":1}
,"active":{"monitor":1}
,"example":{"weston.ini":1,"model":1,"code":1,"weston":1}
,"model":{"setting":1}
,"setting":{"display":1,"environment":1,"wayland_debug":1}
,"options":{"weston.ini":1}
,"name":{"hdmi-a-1":1}
,"mode":{"1920":1,"drm":1,"weston":1,"compositing":1}
,"1920":{"1080":1}
,"transform":{"0,90,180,270":1}
,"monitors":{"events":1}
,"events":{"sent":1,"ivi-wm-screen":1}
,"sent":{"direct":1,"ivi-controller":1}
,"direct":{"rendering":1}
,"rendering":{"manager":1,"formats":1}
,"manager":{"drm":1}
,"subsystem":{"using":1}
,"udev":{"display":1,"receives":1}
,"changes":{"udev":1}
,"receives":{"hotplug":1,"linux":1,"via":1,"prints":1}
,"hotplug":{"event":1,"displays":1,"nvidia":1,"using":1}
,"event":{"calls":1,"display":1,"sent":1,"during":1}
,"calls":{"drmmodegetresources":1,"involved":1,"drmmodeaddfb2withmodifiers":1}
,"drmmodegetresources":{"identify":1}
,"identify":{"connectors":1}
,"connectors":{"added":1}
,"added":{"removed":1,"multiple":1,"supported_drm_formats":1,"later":1}
,"takes":{"actions":1,"form":1}
,"actions":{"accordingly":1}
,"t210":{"real":1,"three":1}
,"real":{"kernel":1,"drm":1}
,"kernel":{"mode":1}
,"instead":{"user":1}
,"user":{"mode":1}
,"drm-nvdc":{"dummy":1}
,"drivers":{"work":1}
,"work":{"together":1,"run":1}
,"together":{"provide":1}
,"provide":{"real":1}
,"driver-like":{"interface":1}
,"interface":{"weston":1,"ivi-wm":1}
,"signals":{"hotplug":1}
,"connection":{"state":1}
,"state":{"changes":1,"composition":1}
,"verified":{"cases":1,"displayport":1,"case":1}
,"disconnect":{"connect":1}
,"connect":{"hdmi":1}
,"hdmi":{"display":1}
,"nvgldemo":{"running":1,"application":1}
,"verify":{"application":1,"overlay":1,"correctness":1}
,"drawing":{"visible":1}
,"visible":{"connection":1}
,"without":{"hdmi":1,"using":1,"establishing":1}
,"cases":{"above":1}
,"above":{"verified":1}
,"displayport":{"displays":1}
,"issues":{"fixed":1}
,"fixed":{"weston":1}
,"disappears":{"display":1}
,"fix":{"issue":1,"adds":1}
,"issue":{"backported":1}
,"backported":{"downstream":1}
,"downstream":{"weston":1}
,"codeline":{"upstream":1,"freedesktop.org":1}
,"upstream":{"weston":1}
,"main":{"codeline":1,"calls":1}
,"freedesktop.org":{"gitlab":1}
,"gitlab":{"information":1}
,"crashes":{"using":1}
,"originally":{"designed":1}
,"designed":{"support":1}
,"adds":{"protocol":1,"support":1}
,"protocol":{"ivi-vm":1,"notifications":1,"wayland":1,"post":1,"using":1,"uses":1,"example":1}
,"ivi-vm":{"lets":1}
,"lets":{"client":1}
,"client":{"receive":1,"handle":1,"create":1,"applications":1,"application":1,"debug":1}
,"receive":{"hotplug":1}
,"ivi-controller":{"client":1}
,"handle":{"event":1,"gbm_bo_get_handle_for_plane":1,"&dmabuf_fd":1}
,"during":{"hotplug":1,"vblank":1}
,"ivi-layermanagement":{"api":1}
,"api":{"relocate":1,"function":1}
,"relocate":{"surfaces":1}
,"surfaces":{"destroy":1,"client":1,"views":1,"assigned":1,"overlay-composited":1,"gl-composited":1}
,"destroy":{"surfaces":1}
,"create":{"listeners":1,"specifying":1}
,"listeners":{"listen":1}
,"listen":{"connector_name":1}
,"connector_name":{"screen_id":1,"void":1}
,"screen_id":{"screen_destroy":1,"void":1}
,"screen_destroy":{"events":1,"void":1}
,"ivi-wm-screen":{"interface":1}
,"ivi-wm":{"protocol":1}
,"notifications":{"hot":1}
,"following":{"example":1,"procedure":1,"components":1,"code":1,"gbm":1}
,"static":{"void":1}
,"void":{"data":1,"gbo_mapping":1}
,"data":{"struct":1,"directly":1,"written":1,"read":1,"dst_ptr":1}
,"struct":{"ivi_wm_screen":1,"ivi_wm_screen_listener":1}
,"ivi_wm_screen":{"ivi_wm_screen":1,"uint32_t":1,"const":1,"&wm_screen_listener":1}
,"const":{"char":1}
,"char":{"process_name":1,"dst_ptr":1}
,"ivi_wm_screen_listener":{"wm_screen_listener":1}
,"ivi_wm_screen_add_listener":{"ivi_wm_screen":1}
,"&wm_screen_listener":{"args":1}
,"known":{"issues":1}
,"currently":{"drm":1,"supports":1,"block-linear":1}
,"notify":{"weston":1}
,"page":{"flip":1}
,"flip":{"failed":1,"pending":1,"reference":1}
,"failed":{"consequently":1}
,"consequently":{"weston":1}
,"configured":{"support":1}
,"hot-plugging":{"display":1}
,"certain":{"times":1}
,"times":{"may":1}
,"may":{"cause":1,"create":1}
,"cause":{"drmatomiccommit":1}
,"drmatomiccommit":{"fail":1}
,"fail":{"page":1}
,"pending":{"assertion":1}
,"compositing":{"mode":1,"using":1,"path":1,"weston":1}
,"mixed":{"mode":1,"state":1}
,"dma-buf":{"t210":1,"support":1,"buffers":1,"unstable":1,"file":1,"wayland":1,"object":1,"receives":1,"available":1}
,"three":{"display":1}
,"windows":{"per":1,"screen":1}
,"per":{"head":1}
,"head":{"weston":1}
,"assigns":{"window":1}
,"gfx":{"plane":1}
,"plane":{"two":1,"4002":1,"4001":1,"property":1}
,"two":{"available":1}
,"available":{"renamed":1,"supported":1,"display":1}
,"renamed":{"secondary":1}
,"secondary":{"overlay":1}
,"overlay":{"planes":1,"plans":1,"provisionally":1,"4002":1,"4001":1,"placing":1,"free":1,"couldn\u0027t":1,"plane":1,"glcomposition":1,"composition":1}
,"planes":{"every":1,"others":1,"using":1}
,"every":{"frame":1}
,"evaluates":{"surfaces":1}
,"views":{"chooses":1,"descriptions":1}
,"chooses":{"strategies":1}
,"strategies":{"composite":1}
,"drm_output_propose_state_mixed":{"overlay":1}
,"drm_output_propose_state_planes_only":{"overlay":1}
,"demo":{"application":1}
,"weston-simple-dmabuf-egldevice":{"demonstrates":1,"app":1}
,"demonstrates":{"mixed-mode":1}
,"mixed-mode":{"compositing":1}
,"path":{"weston":1,"drmmodeatomiccommit":1,"takes":1}
,"assigned":{"overlay":1,"following":1}
,"others":{"composited":1}
,"weston-debug":{"verify":1,"application":1,"output":1,"receives":1,"protocol":1,"work":1,"additional":1}
,"plans":{"assigned":1}
,"prepare":{"device":1}
,"--debug":{"switch":1}
,"--idle-time":{"--debug":1,"--modules":1}
,"few":{"weston":1}
,"look":{"information":1}
,"information":{"shown":1}
,"shown":{"below":1}
,"below":{"weston-debug":1}
,"output":{"blue":1,"hdmi-a-1":1,"display:1":1,"setting":1}
,"blue":{"colored":1}
,"colored":{"surfaces":1}
,"overlay-composited":{"green-colored":1}
,"green-colored":{"surfaces":1}
,"layer":{"pos":1}
,"pos":{"0x50000000":1,"0x2":1}
,"view":{"role":1,"evaluating":1,"0x33c798b0":1,"view":1,"0x33bb9500":1,"0x31769110":1,"0x314c6430":1}
,"role":{"xdg_toplevel":1}
,"xdg_toplevel":{"pid":1}
,"pid":{"8080":1,"8073":1,"8066":1,"8051":1}
,"8080":{"surface":1}
,"surface":{"top-level":1,"file":1,"views":1}
,"top-level":{"window":1}
,"\u0027simple-dmabuf-egldevice":{"0x33c798b0":1,"0x33bb9500":1,"0x31769110":1}
,"position":{"714":1,"209":1,"1129":1,"1343":1}
,"714":{"860":1}
,"860":{"970":1}
,"970":{"1116":1}
,"outputs":{"hdmi-a-1":1}
,"hdmi-a-1":{"primary":1}
,"dmabuf":{"buffer":1,"egl":1,"created":1}
,"format":{"0x34325258":1,"xrgb8888":1,"appear":1,"string":1,"nvdrmvideosink":1,"nv16":1,"modifiers":1,"flags":1}
,"0x34325258":{"xrgb8888":1}
,"modifier":{"0x3800000000fe014":1,"encoding":1,"gbm_bo_get_modifier":1,"0xffffffff":1}
,"8073":{"surface":1}
,"209":{"591":1}
,"591":{"465":1}
,"465":{"847":1}
,"8066":{"surface":1}
,"1129":{"339":1}
,"339":{"1385":1}
,"1385":{"595":1}
,"8051":{"surface":1}
,"\u0027simple-egl":{"0x314c6430":1}
,"1343":{"642":1}
,"642":{"1593":1}
,"1593":{"892":1}
,"egl":{"buffer":1,"case":1,"call":1}
,"evaluating":{"view":1}
,"0x33c798b0":{"output":1,"format":1,"overlay":1}
,"provisionally":{"placing":1}
,"placing":{"view":1}
,"4002":{"mixed":1}
,"0x33bb9500":{"output":1,"format":1,"overlay":1}
,"4001":{"mixed":1}
,"0x31769110":{"output":1,"format":1,"overlay":1,"using":1}
,"free":{"overlay":1}
,"0x314c6430":{"output":1,"overlay":1,"using":1}
,"repaint":{"using":1,"view":1}
,"renderer":{"composition":1,"weston":1}
,"nv16":{"nv24":1}
,"nv24":{"weston":1,"content":1,"color":1,"video":1}
,"compositor":{"adds":1,"weston":1}
,"content":{"via":1,"rendered":1,"support":1,"onscreen":1}
,"via":{"shared":1,"exposed":1,"nvbuffercreateparams":1,"linux":1}
,"shared":{"memory":1}
,"memory":{"buffers":1,"using":1,"map":1}
,"wl_shm_format_nv24":{"enum":1}
,"enum":{"substitute":1}
,"substitute":{"drm_format_nv24":1}
,"drm_format_nv24":{"convention":1,"added":1}
,"convention":{"enums":1}
,"enums":{"symbols":1}
,"symbols":{"defined":1}
,"defined":{"drm_fourcc.h":1}
,"shared-memory":{"rendering":1}
,"test":{"color-format.weston":1,"case":1,"application":1,"patterns":1,"enter":1}
,"color-format.weston":{"exercises":1}
,"exercises":{"shared-memory":1}
,"formats":{"weston":1,"formats":1,"construct":1,"stream":1,"drm_format_xrgb8888":1}
,"implemented":{"test":1}
,"case":{"intended":1,"video":1,"dmabuf":1}
,"intended":{"visual":1}
,"visual":{"verification":1}
,"verification":{"manually":1}
,"manually":{"terminated":1}
,"start":{"weston":1}
,"enter":{"command":1,"ctrl-c":1}
,"command":{"execute":1,"gstreamer":1}
,"execute":{"test":1}
,"eight":{"color":1}
,"color":{"test":1,"format":1,"formats":1}
,"patterns":{"rendered":1}
,"rendered":{"using":1,"screen":1,"excess":1}
,"appear":{"substantially":1}
,"substantially":{"identical":1}
,"identical":{"minor":1}
,"minor":{"variations":1}
,"variations":{"caused":1}
,"caused":{"limitations":1}
,"limitations":{"formats":1}
,"terminate":{"test":1}
,"dma":{"buffer":1}
,"buffer":{"rendering":1,"via":1,"layouts":1,"allocation":1,"using":1,"layout":1,"write":1,"cpu-accessible":1,"management":1,"object":1,"swapped":1}
,"construct":{"eglimage":1}
,"eglimage":{"dma":1,"dma-buf":1,"calling":1,"texture":1}
,"exposed":{"ext_image_dma_buf_import":1}
,"ext_image_dma_buf_import":{"ext_image_dma_buf_import_modifiers":1}
,"ext_image_dma_buf_import_modifiers":{"extensions":1}
,"block-linear":{"dma":1}
,"layouts":{"supported":1}
,"supported":{"drm_format_nv21":1,"future":1,"drm":1}
,"drm_format_nv21":{"drm_format_nv16":1}
,"drm_format_nv16":{"drm_format_nv24":1}
,"video":{"playback":1,"uses":1,"displayed":1}
,"playback":{"test":1}
,"gst-launch-1.0":{"filesrc":1,"command":1}
,"filesrc":{"location":1}
,"location":{"mp4_src_file":1}
,"mp4_src_file":{"qtdemux":1,"pathname":1}
,"qtdemux":{"h264parse":1}
,"h264parse":{"nvv4l2decoder":1}
,"nvv4l2decoder":{"nvvidconv":1}
,"nvvidconv":{"\u0027video":1,"plugin":1}
,"\u0027video":{"x-raw":1}
,"x-raw":{"memory:nvmm":1}
,"memory:nvmm":{"width":1}
,"width":{"int":1,"height":1}
,"int":{"1280":1,"720":1}
,"1280":{"height":1}
,"height":{"int":1}
,"720":{"format":1}
,"string":{"format":1}
,"pathname":{"apt":1}
,"apt":{"source":1}
,"source":{"file":1}
,"gstreamer":{"pipeline":1}
,"pipeline":{"display":1}
,"uses":{"nvvidconv":1,"drm":1,"generic":1,"framebuffer":1}
,"plugin":{"convert":1,"internally":1}
,"convert":{"formats":1}
,"stream":{"nv16":1}
,"displayed":{"nvdrmvideosink":1}
,"nvdrmvideosink":{"plugin":1}
,"internally":{"uses":1}
,"vpr":{"memory":1,"content":1}
,"allocate":{"vpr":1,"buffers":1,"buffer":1}
,"nbuf_utils":{"gbm":1}
,"nvbuf_utils":{"add":1}
,"add":{"nvbuffertag_protected":1,"egl_protected_content_ext":1}
,"nvbuffertag_protected":{"tag":1}
,"tag":{"via":1}
,"nvbuffercreateparams":{"pass":1}
,"specify":{"gbm_bo_use_protected":1,"texture":1,"attribute":1}
,"gbm_bo_use_protected":{"usage":1}
,"usage":{"flag":1}
,"flag":{"gbm_bo_create":1}
,"egl_protected_content_ext":{"attribute":1}
,"attribute":{"creating":1,"note":1,"import":1}
,"creating":{"eglsurface":1}
,"eglsurface":{"objects":1}
,"objects":{"specify":1}
,"texture":{"parameter":1,"target":1}
,"gl_texture_protected_ext":{"protected":1}
,"protected":{"textures":1,"context":1,"content":1}
,"write":{"protected":1,"read":1,"data":1}
,"textures":{"protected":1}
,"context":{"may":1}
,"specifying":{"egl_protected_content_ext":1}
,"note":{"specify":1}
,"import":{"dmabuf":1}
,"created":{"vpr":1}
,"sample":{"case":1}
,"app":{"switch":1,"without":1}
,"correctness":{"result":1}
,"result":{"examine":1}
,"examine":{"screen":1}
,"screen":{"run":1,"overlay":1,"exceeding":1}
,"glcomposition":{"support":1}
,"later":{"releases":1}
,"thus":{"several":1}
,"several":{"windows":1}
,"exceeding":{"limit":1}
,"limit":{"overlay":1}
,"composition":{"protected":1}
,"excess":{"windows":1}
,"hdcp":{"support":1,"link":1}
,"future":{"release":1}
,"onscreen":{"even":1}
,"even":{"without":1}
,"establishing":{"hdcp":1}
,"clients":{"post":1}
,"post":{"dma-buf":1}
,"buffers":{"weston":1,"backed":1}
,"unstable":{"protocol":1}
,"commonly":{"used":1}
,"used":{"allocate":1,"eglimage":1}
,"backed":{"dma-buf":1}
,"file":{"descriptor":1,"descriptors":1}
,"code":{"snippet":1}
,"snippet":{"shows":1}
,"shows":{"allocate":1,"main":1}
,"drm_fd":{"open":1,"handle":1}
,"open":{"dev":1}
,"dev":{"dri":1}
,"dri":{"card0":1}
,"card0":{"o_rdwr":1}
,"gbm_create_device":{"drm_fd":1}
,"gbm_bo_create_with_modifiers":{"device":1}
,"modifiers":{"modifiers_count":1,"supported":1}
,"drm_format_xrgb8888":{"drm_format_argb8888":1}
,"encoding":{"vendor-specific":1}
,"vendor-specific":{"buffer":1}
,"layout":{"parameters":1}
,"parameters":{"weston":1,"gbm":1,"provided":1,"choose":1}
,"read":{"in_formats":1,"cpu":1,"following":1,"data":1}
,"in_formats":{"plane":1}
,"property":{"blob":1}
,"blob":{"egl":1}
,"call":{"eglquerydmabufmodifiersext":1,"following":1}
,"function":{"write":1}
,"directly":{"gbm":1}
,"gbm_bo_write":{"user_buffer":1}
,"user_buffer":{"sizeof":1}
,"sizeof":{"user_buffer":1}
,"map":{"gbm":1,"cpu":1}
,"cpu-accessible":{"address":1}
,"address":{"data":1}
,"written":{"read":1}
,"uint32_t":{"dst_stride":1}
,"gbo_mapping":{"null":1}
,"cpu":{"accessible":1}
,"accessible":{"address":1}
,"dst_ptr":{"gbm_bo_map":1}
,"gbm_bo_unmap":{"gbo_mapping":1}
,"generic":{"buffer":1}
,"management":{"gbm":1}
,"library":{"allocate":1}
,"descriptors":{"client":1}
,"functions":{"dma-buf":1}
,"descriptor":{"associated":1,"parameters":1}
,"associated":{"parameters":1}
,"object":{"post":1,"receives":1}
,"provided":{"via":1}
,"stride":{"gbm_bo_get_stride_for_plane":1,"modifier":1}
,"offset":{"gbm_bo_get_offset":1}
,"drmprimehandletofd":{"drm_fd":1}
,"zwp_linux_buffer_params_v1_add":{"params":1}
,"params":{"dmabuf_fds":1,"width":1}
,"dmabuf_fds":{"offset":1}
,"zwp_linux_buffer_params_v1_create":{"params":1}
,"creates":{"eglimage":1}
,"egl_ext_image_dma_buf_import":{"egl_ext_image_dma_buf_import_modifiers":1}
,"egl_ext_image_dma_buf_import_modifiers":{"extensions":1}
,"extensions":{"weston":1}
,"obtains":{"texture":1}
,"target":{"used":1}
,"calling":{"eglquerydmabufmodifiersext":1}
,"eglquerydmabufmodifiersext":{"binds":1}
,"binds":{"eglimage":1}
,"hardware":{"compositing":1,"planes":1}
,"drmmodeaddfb2withmodifiers":{"associate":1}
,"associate":{"drm":1}
,"framebuffer":{"dma-buf":1,"present":1}
,"present":{"dma-buf":1}
,"drmmodesetplane":{"legacy":1}
,"legacy":{"path":1}
,"drmmodeatomiccommit":{"atomic":1}
,"atomic":{"modeset":1}
,"modeset":{"path":1}
,"form":{"flip":1}
,"reference":{"new":1}
,"new":{"buffer":1}
,"swapped":{"during":1}
,"prints":{"debug":1,"surface":1}
,"debug":{"messages":1,"output":1,"setting":1}
,"messages":{"using":1}
,"recompositing":{"prints":1}
,"descriptions":{"decision":1}
,"decision":{"process":1}
,"process":{"regarding":1}
,"regarding":{"assignment":1}
,"assignment":{"overlays":1}
,"\u2011\u2011debug":{"switch":1}
,"switch":{"switch":1,"production":1}
,"additional":{"parameters":1}
,"categories":{"debug":1}
,"alternatively":{"enable":1}
,"enable":{"weston":1}
,"variable":{"wayland_debug":1}
,"server":{"weston":1}
}
;Search.control.loadWordPairs(pairs);
