var pairs =
{
"nvidia":{"jetson":1,"drivers":1,"clocks-config":1}
,"jetson":{"board":1,"clocks":1,"clock":1,"processor":1,"custom":1,"linux":1,"agx":1,"tx2":1,"xavier":1,"nano":1,"tx1":1,"platform":1}
,"board":{"support":1,"modified":1}
,"support":{"package":1}
,"package":{"bsp":1,"l4t":1}
,"bsp":{"supports":1}
,"supports":{"configuring":1}
,"configuring":{"jetson":1,"gpu":1,"vic":1,"clocks":1}
,"clocks":{"peripheral":1,"software":1,"configure":1,"required":1,"controlled":1,"device":1,"declared":1,"&tegra_car":1,"kernel":1,"add":1,"disabled":1,"property":1,"0x4":1,"pllaon":1,"configured":1}
,"peripheral":{"clocks":1}
,"software":{"topic":1,"bpmp.bin":1,"clock":1}
,"topic":{"describes":1}
,"describes":{"check":1,"clock":1,"several":1}
,"check":{"clock":1,"available":1}
,"clock":{"status":1,"sources":1,"reset":1,"source":1,"framework":1,"drivers":1,"programming":1,"driver":1,"rates":1,"rate":1,"node":1,"divider":1,"configurations":1,"desired":1,"frequency":1,"clk_prepare":1,"operation":1,"disabled":1,"setting":1,"pllaon":1,"list":1,"provider":1,"pair":1}
,"status":{"maximum":1,"active":1}
,"maximum":{"rates":1,"supported":1,"possible":1,"frequency":1}
,"rates":{"clocks":1,"example":1}
,"configure":{"clock":1,"vic":1}
,"information":{"available":1,"vic":1,"given":1}
,"available":{"jetson":1,"clock":1,"nvidia":1,"frequencies":1,"frequency":1,"vic":1,"divider":1}
,"sources":{"capabilities":1,"component":1,"clocks":1}
,"capabilities":{"clock":1}
,"reset":{"controller":1}
,"controller":{"section":1}
,"section":{"technical":1,"trm":1,"describes":1}
,"technical":{"reference":1}
,"reference":{"manual":1}
,"manual":{"trm":1}
,"trm":{"jetson":1,"describes":1}
,"processor":{"section":1,"runs":1}
,"source":{"multiplexers":1,"register":1,"registers":1,"selection":1,"using":1,"target":1,"dts":1,"files":1}
,"multiplexers":{"provides":1}
,"provides":{"descriptions":1,"override":1,"video":1}
,"descriptions":{"available":1,"follow":1}
,"kernel":{"4.9":1,"running":1,"debug":1,"device":1,"dtb":1,"dts":1}
,"4.9":{"following":1}
,"following":{"common":1,"command":1,"commands":1,"procedures":1,"clocks":1}
,"common":{"clock":1}
,"framework":{"ccf":1,"gpu":1}
,"ccf":{"supported":1,"apis":1}
,"supported":{"result":1,"frequency":1}
,"device":{"drivers":1,"tree":1,"enter":1,"driver":1}
,"drivers":{"public":1,"including":1,"clk":1}
,"public":{"ccf":1}
,"apis":{"include":1}
,"include":{"linux":1}
,"linux":{"clk.h":1,"clk-provider.h":1,"kernel":1,"driver":1}
,"clk.h":{"include":1}
,"clk-provider.h":{"including":1}
,"including":{"functions":1,"jetson":1,"geometry":1}
,"functions":{"clk_get":1,"ungate":1}
,"clk_get":{"clk_enable":1}
,"clk_enable":{"devm_clk_get":1,"functions":1,"ungate":1}
,"devm_clk_get":{"clk_prepare_enable":1,"function":1}
,"clk_prepare_enable":{"clk_prepare_disable":1,"clk_prepare":1}
,"clk_prepare_disable":{"clk_disable":1}
,"clk_disable":{"others":1}
,"others":{"instead":1}
,"instead":{"platform-specific":1,"run":1,"clk_enable":1}
,"platform-specific":{"apis":1}
,"custom":{"clk":1}
,"clk":{"driver":1,"tegra":1,"clk_tree":1,"can1":1,"emc":1}
,"driver":{"implement":1,"package":1,"wrapper":1,"requesting":1,"module":1}
,"implement":{"clk_ops":1}
,"required":{"devices":1}
,"devices":{"defined":1,"17000000.gp10b":1,"gpu.0":1,"13e10000.host1x":1,"jetson":1,"50000000.host1x":1}
,"defined":{"device":1}
,"controlled":{"called":1,"bpmp":1}
,"called":{"boot":1}
,"boot":{"power":1,"updated":1}
,"power":{"management":1,"based":1,"performance":1,"control":1,"runtime_status":1}
,"management":{"processor":1,"suspend":1}
,"runs":{"rtos":1}
,"rtos":{"software":1}
,"bpmp.bin":{"linux":1}
,"running":{"ccplex":1}
,"ccplex":{"requests":1}
,"requests":{"software":1}
,"l4t":{"clock":1,"platforms":1}
,"wrapper":{"available":1}
,"tegra":{"directory":1}
,"applies":{"jetson":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"clocks":1,"jetson":1,"platform":1}
,"series":{"jetson":1}
,"tx2":{"series":1}
,"enter":{"following":1,"command":1}
,"command":{"launch":1,"displays":1,"display":1,"lists":1}
,"launch":{"debugfs":1}
,"debugfs":{"check":1,"output":1,"service":1,"debugging":1}
,"cat":{"sys":1,"available_frequencies":1,"knobpath":1,"knobpath_devfreq":1}
,"sys":{"kernel":1,"devices":1}
,"debug":{"bpmp":1,"clk":1}
,"bpmp":{"debug":1,"debugfs":1,"example":1}
,"example":{"debugfs":1,"override":1,"fix":1,"padctl-uphy":1,"follow":1}
,"output":{"nvidia":1}
,"screenshot":{"cell":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"generated":1}
,"generated":{"high":1}
,"high":{"confidence":1}
,"overriding":{"default":1}
,"default":{"clock":1,"load":1,"value":1,"pllaon":1}
,"rate":{"component":1,"fixed":1,"debugfs":1,"state":1,"following":1,"successful":1,"accuracy":1}
,"component":{"during":1}
,"during":{"boot":1}
,"updated":{"control":1}
,"control":{"driver":1,"logic":1,"knobs":1,"operation":1,"vic":1,"terminology":1,"knob":1,"module":1}
,"requesting":{"bpmp":1}
,"service":{"provides":1}
,"override":{"default":1,"emc":1}
,"fixed":{"clock":1,"frequency":1,"time":1,"value":1}
,"debugging":{"experimental":1,"power":1}
,"experimental":{"purposes":1}
,"find":{"child":1}
,"child":{"nodes":1}
,"nodes":{"shown":1,"parent":1,"dvfs":1,"control":1}
,"shown":{"below":1}
,"below":{"clock":1}
,"node":{"change":1,"select":1}
,"change":{"nodes":1,"clock":1,"mttcan":1}
,"parent":{"rates":1,"possible_parents":1,"clock":1,"can1":1,"remove":1,"add":1}
,"root@jetson-0422818069479":{"sys":1}
,"children":{"dvfs":1}
,"dvfs":{"flags":1,"enabled":1,"operations":1,"control":1,"enter":1,"wmark_active":1,"userspace":1,"jetson":1}
,"flags":{"fmon":1}
,"fmon":{"max_rate":1}
,"max_rate":{"min_rate":1}
,"min_rate":{"mrq_rate_locked":1}
,"mrq_rate_locked":{"parent":1}
,"possible_parents":{"pto_counter":1}
,"pto_counter":{"rate":1}
,"state":{"vdd_aon":1,"configure":1}
,"emc":{"rate":1,"mrq_rate_locked":1,"state":1}
,"echo":{"sys":1,"max":1,"1377000000":1,"freq":1,"828750000":1,"gov":1,"userspace":1,"wmark_active":1,"period":1,"target":1,"knobpath":1,"value":1,"frequency":1,"auto":1}
,"gpu":{"clocks":1,"dvfs":1,"frequency":1,"fixed":1}
,"enabled":{"using":1,"default":1,"wmark_active":1}
,"using":{"devfreq":1,"clock-names":1,"dtc":1}
,"devfreq":{"framework":1,"17000000.gp10b":1,"17000000.gv11b":1,"governor":1,"15340000.vic":1,"54340000.vic":1}
,"frequency":{"changes":1,"necessary":1,"maximum":1,"example":1,"list":1,"828750000":1,"dynamically":1,"scaling":1,"reducing":1,"increasing":1,"step":1,"boost":1,"fmax":1,"hertz":1,"scales":1,"freq_boost_en":1,"fixed":1,"directly":1,"commands":1,"settings":1,"vic":1,"value":1,"knobpath_devfreq":1,"target":1,"clock":1,"configured":1}
,"changes":{"based":1,"curr_freq":1,"modifying":1}
,"based":{"load":1,"utilization":1}
,"load":{"instead":1,"ratio":1,"current":1,"outside":1,"lower":1,"target":1,"load":1,"level":1}
,"run":{"gpu":1}
,"17000000.gp10b":{"devfreq":1}
,"gpu.0":{"devfreq":1}
,"list":{"available":1,"step":1,"possible":1,"clocks":1,"clock-names":1}
,"displays":{"list":1}
,"114750000":{"216750000":1}
,"216750000":{"318750000":1}
,"318750000":{"420750000":1}
,"420750000":{"522750000":1}
,"522750000":{"624750000":1}
,"624750000":{"675750000":1}
,"675750000":{"828750000":1}
,"828750000":{"905250000":1,"min_freq":1,"max_freq":1}
,"905250000":{"1032750000":1}
,"1032750000":{"1198500000":1}
,"1198500000":{"1236750000":1}
,"1236750000":{"1338750000":1}
,"1338750000":{"1377000000":1}
,"fix":{"frequency":1,"supported":1}
,"max":{"min_freq":1,"maximum":1,"knobpath":1,"frequency":1}
,"1377000000":{"min_freq":1}
,"freq":{"min_freq":1,"max_freq":1,"desired":1}
,"desired":{"supported":1,"clock":1}
,"vic":{"clocks":1,"provides":1,"voltage":1,"video":1,"dynamic":1,"actmon":1,"active":1,"frequency":1,"dvfs":1,"knobs":1,"devfreq":1,"load":1,"runtime":1,"hardware":1,"maximum":1}
,"video":{"image":1,"processing":1}
,"image":{"compositor":1}
,"compositor":{"vic":1,"section":1}
,"processing":{"services":1,"lens":1}
,"services":{"including":1}
,"geometry":{"transform":1}
,"transform":{"processing":1}
,"lens":{"distortion":1}
,"distortion":{"correction":1}
,"correction":{"temporal":1}
,"temporal":{"noise":1}
,"noise":{"reduction":1}
,"reduction":{"vic":1}
,"voltage":{"frequency":1}
,"dynamically":{"scaled":1}
,"scaled":{"conserve":1,"1000":1}
,"conserve":{"power":1}
,"utilization":{"measured":1}
,"measured":{"activity":1}
,"activity":{"monitor":1}
,"monitor":{"actmon":1}
,"dynamic":{"voltage":1}
,"actmon":{"hardware":1,"raises":1,"skips":1}
,"hardware":{"block":1}
,"block":{"monitors":1,"power-on":1,"module":1}
,"monitors":{"vic":1}
,"active":{"cycles":1,"cycle":1}
,"cycles":{"fixed":1}
,"time":{"window":1,"adjusted":1}
,"window":{"works":1}
,"works":{"wmark_active":1}
,"wmark_active":{"devfreq":1,"tries":1,"raise":1,"boosts":1,"sys":1}
,"governor":{"perform":1,"used":1}
,"perform":{"dynamic":1}
,"scaling":{"dvfs":1,"aggressive":1,"operations":1,"last":1,"operation":1}
,"operations":{"vic":1,"microseconds":1}
,"tries":{"keep":1,"maintain":1}
,"keep":{"current":1,"vic":1}
,"current":{"load":1,"vic":1,"instantaneous":1,"clock":1}
,"ratio":{"vic":1}
,"cycle":{"total":1,"scaled":1,"current":1,"exceeds":1}
,"total":{"cycle":1}
,"1000":{"within":1,"wmark_active":1,"fmax":1,"default":1}
,"within":{"certain":1}
,"certain":{"percentage":1,"cases":1}
,"percentage":{"range":1}
,"range":{"sets":1,"1000":1}
,"sets":{"upper":1,"vic":1,"frequency":1}
,"upper":{"lower":1}
,"lower":{"bounds":1,"frequency":1,"load":1}
,"bounds":{"current":1,"vic":1}
,"outside":{"bounds":1}
,"raises":{"interrupt":1}
,"interrupt":{"causes":1}
,"causes":{"wmark_active":1}
,"raise":{"vic":1}
,"reducing":{"current":1}
,"logic":{"wmark_active":1}
,"freq_boost_en":{"curr_load":1,"knob":1,"control":1,"above":1}
,"curr_load":{"load_max":1,"current":1,"wmark_active":1,"value":1}
,"load_max":{"else":1,"frequency":1,"control":1}
,"select":{"first":1,"specified":1,"pllaon":1}
,"first":{"available":1,"adding":1}
,"step":{"greater":1}
,"greater":{"equal":1}
,"equal":{"avg_target_freqcurrent":1}
,"knob":{"enables":1,"defines":1,"sets":1,"below":1,"adjusts":1}
,"enables":{"disables":1}
,"disables":{"frequency":1,"pllaon":1}
,"boost":{"feature":1,"threshold":1,"enabled":1,"enter":1,"disable":1}
,"fmax":{"maximum":1,"load_level":1,"vic":1}
,"possible":{"vic":1,"parent":1,"parents":1}
,"threshold":{"range":1,"load_max":1,"wmark_active":1,"enter":1}
,"boosts":{"vic":1}
,"load_level":{"exceeds":1}
,"exceeds":{"threshold":1,"load":1,"frequency":1}
,"load_target":{"load":1,"current":1,"control":1,"enter":1}
,"target":{"value":1,"frequency":1,"default":1,"700":1,"makes":1,"1000":1,"load_target":1,"knobpath":1,"load":1,"clock":1,"rate":1}
,"value":{"curr_load":1,"load_target":1,"900":1,"avg_target_freq":1,"knobpath":1,"value":1,"static":1}
,"curr_freq":{"current":1,"recalculated":1}
,"curr_ideal_freq":{"vic":1,"given":1,"100":1,"time":1}
,"hertz":{"yield":1,"used":1,"moving":1}
,"yield":{"curr_load":1}
,"instantaneous":{"operating":1}
,"operating":{"conditions":1}
,"avg_target_freq":{"moving":1,"average":1,"toward":1}
,"moving":{"average":1}
,"average":{"target":1}
,"used":{"avoid":1,"instead":1}
,"avoid":{"abrupt":1}
,"abrupt":{"changes":1}
,"recalculated":{"property":1}
,"property":{"described":1,"remove":1}
,"described":{"fully":1}
,"fully":{"customize":1}
,"customize":{"vic":1}
,"sysfs":{"paths":1,"nodes":1}
,"paths":{"dvfs":1}
,"several":{"knobs":1}
,"knobs":{"control":1,"located":1,"concern":1}
,"operation":{"vic":1,"performed":1,"may":1}
,"pathnames":{"sysfs":1,"jetson":1}
,"located":{"pair":1}
,"pair":{"directories":1,"pllaon":1}
,"directories":{"whose":1}
,"whose":{"locations":1}
,"locations":{"platform-dependent":1}
,"platform-dependent":{"descriptions":1}
,"follow":{"placeholders":1,"steps":1}
,"placeholders":{"represent":1,"appropriate":1}
,"represent":{"directories":1}
,"knobpath":{"represents":1,"block_window":1,"load_target":1,"freq_boost_en":1,"load_max":1,"smooth":1,"power":1}
,"13e10000.host1x":{"15340000.vic":1}
,"knobpath_devfreq":{"represents":1,"governor":1,"available_frequencies":1,"max_freq":1,"userspace":1}
,"15340000.vic":{"devfreq":1,"governor":1}
,"nano":{"devices":1,"platform":1}
,"50000000.host1x":{"54340000.vic":1}
,"54340000.vic":{"devfreq":1,"governor":1}
,"procedures":{"replace":1}
,"replace":{"placeholders":1}
,"appropriate":{"pathnames":1}
,"concern":{"current":1}
,"700":{"i.e":1}
,"i.e":{"wmark_active":1}
,"makes":{"vic":1}
,"aggressive":{"vic":1}
,"scales":{"fmax":1}
,"enable":{"disable":1,"vic":1,"frequency":1,"clock":1,"pllaon":1}
,"disable":{"vic":1,"frequency":1}
,"gov":{"knobpath_devfreq":1,"name":1}
,"name":{"vic":1,"name":1,"pllaon":1}
,"platform":{"enter":1}
,"userspace":{"sys":1,"knobpath_devfreq":1,"set_freq":1}
,"block_window":{"control":1,"microseconds":1,"enter":1,"value":1}
,"defines":{"shortest":1}
,"shortest":{"period":1}
,"period":{"vic":1,"knobpath":1,"block_window":1}
,"microseconds":{"vic":1,"ago":1}
,"skips":{"frequency":1}
,"last":{"vic":1}
,"performed":{"less":1}
,"less":{"block_window":1}
,"feature":{"frequency":1}
,"level":{"exceeds":1}
,"note":{"wmark_active":1}
,"above":{"enabled":1}
,"smooth":{"knob":1,"weight":1,"enter":1}
,"adjusts":{"weights":1}
,"weights":{"avg_target_freqprevious":1}
,"avg_target_freqprevious":{"curr_ideal_freq":1,"weight":1}
,"given":{"adjusting":1,"register":1}
,"adjusting":{"value":1}
,"toward":{"target":1}
,"weight":{"avg_target_freqprevious":1,"curr_ideal_freq":1}
,"100":{"avg_target_freqcurrent":1}
,"avg_target_freqcurrent":{"curr_ideal_freq":1}
,"static":{"vic":1}
,"performance":{"evaluation":1}
,"evaluation":{"may":1}
,"may":{"want":1,"sleep":1}
,"want":{"vic":1,"enable":1}
,"directly":{"disable":1}
,"runtime":{"power":1,"status":1,"suspend":1}
,"suspend":{"forces":1}
,"forces":{"vic":1}
,"power-on":{"state":1}
,"read":{"runtime":1}
,"display":{"runtime":1}
,"lists":{"available":1}
,"115200000":{"268800000":1}
,"268800000":{"409600000":1}
,"409600000":{"550400000":1}
,"550400000":{"691200000":1}
,"691200000":{"844800000":1}
,"844800000":{"985600000":1}
,"985600000":{"1036800000":1}
,"choose":{"available":1}
,"frequencies":{"vic":1}
,"auto":{"knobpath":1}
,"general":{"block":1}
,"module":{"dedicated":1,"divider":1,"frequency":1}
,"dedicated":{"clock":1}
,"register":{"detailed":1,"clk_rst_controller_clk_source_":1}
,"detailed":{"information":1}
,"clk_rst_controller_clk_source_":{"module_name":1}
,"module_name":{"technical":1}
,"registers":{"provide":1}
,"provide":{"clock":1}
,"selection":{"clock":1}
,"divider":{"control":1,"typically":1,"calculated":1,"module":1}
,"typically":{"bits":1}
,"bits":{"integer":1,"fractional":1}
,"integer":{"bits":1}
,"fractional":{"bit":1}
,"bit":{"u7.1":1}
,"configurations":{"kernel":1}
,"declare":{"clocks":1}
,"tree":{"example":1}
,"padctl-uphy":{"clocks":1}
,"declared":{"follows":1}
,"&tegra_car":{"tegra210_clk_hsic_trk":1,"tegra210_clk_usb2_trk":1,"tegra210_clk_pll_e":1}
,"clock-names":{"hsic_trk":1,"add":1,"name":1}
,"hsic_trk":{"usb2_trk":1}
,"usb2_trk":{"pll_e":1}
,"function":{"obtain":1,"select":1,"frequency":1,"exact":1,"used":1}
,"obtain":{"desired":1,"parent":1,"kernel\u2019s":1}
,"clk_get_parent":{"function":1}
,"clk_set_parent":{"function":1}
,"specified":{"clock":1}
,"clk_set_rate":{"function":1}
,"calculated":{"automatically":1}
,"automatically":{"according":1}
,"according":{"target":1}
,"successful":{"clock":1}
,"settings":{"meet":1}
,"meet":{"available":1}
,"clk_round_rate":{"function":1}
,"exact":{"clock":1}
,"configured":{"current":1,"pllaon":1}
,"clk_prepare":{"clk_enable":1,"function":1}
,"ungate":{"enable":1,"clock":1}
,"pllaon":{"clock":1,"achieve":1,"possible":1,"symbol":1,"parent":1,"entry":1,"list":1}
,"disabled":{"t194":1}
,"t194":{"l4t":1}
,"platforms":{"conserve":1}
,"achieve":{"higher":1}
,"higher":{"clock":1}
,"accuracy":{"certain":1}
,"cases":{"pwm":1}
,"pwm":{"first":1}
,"adding":{"pllaon":1}
,"setting":{"parent":1,"enables":1}
,"modifying":{"bpmpfw":1}
,"bpmpfw":{"dtb":1}
,"dtb":{"kernel":1,"files":1,"holds":1,"contains":1,"e.g":1,"build":1,"edited":1}
,"files":{"bpmpfw":1}
,"holds":{"configuration":1}
,"configuration":{"clocks":1}
,"contains":{"setting":1}
,"taking":{"case":1}
,"case":{"example":1}
,"steps":{"add":1}
,"add":{"pllaon":1,"clock":1,"entry":1}
,"convert":{"bpmpfw":1,"dts":1,"kernel":1}
,"e.g":{"tegra194-a02-bpmp-p2888-a04.dtb":1,"tegra194-p2888-0001-p2822-0000.dtb":1}
,"tegra194-a02-bpmp-p2888-a04.dtb":{"dts":1}
,"dts":{"using":1,"file":1}
,"dtc":{"tool":1}
,"edit":{"dts":1,"kernel":1,"clocks":1}
,"file":{"add":1,"clocks":1,"back":1,"using":1,"pllaon":1,"dtb":1}
,"symbol":{"clk_pllaon":1}
,"clk_pllaon":{"decimal":1}
,"decimal":{"hex":1}
,"hex":{"0x5e":1}
,"0x5e":{"allowed-parents":1,"list":1,"new":1}
,"allowed-parents":{"list":1,",94":1}
,"clk-id":{"confirming":1}
,"confirming":{"tegra194_clk_can1":1}
,",94":{"tegra194_clk_pllaon":1}
,"allows":{"pllaon":1}
,"back":{"dtb":1}
,"tegra194-p2888-0001-p2822-0000.dtb":{"dts":1}
,"tool":{"obtain":1}
,"kernel\u2019s":{"source":1}
,"remove":{"pllaon":1,"clock":1}
,"entry":{"0x4":1}
,"0x4":{"0x5e":1}
,"compatible":{"nvidia":1}
,"provider":{"clock":1}
,"mttcan":{"node":1}
,"pll_source":{"pllaon":1}
,"new":{"entry":1}
,"build":{"kernel":1}
,"edited":{"source":1}
,"flash":{"board":1}
,"modified":{"dtb":1}
}
;Search.control.loadWordPairs(pairs);
