var pairs =
{
"topic":{"describes":1}
,"describes":{"egl":1}
,"egl":{"mechanisms":1,"display":1,"displays":1,"without":1,"resources":1,"device":1,"extensions":1,"egl":1,"extension":1,"stream":1,"context":1,"eglinitialize":1,"rendering":1,"surface":1}
,"mechanisms":{"render":1}
,"render":{"images":1,"egl":1,"egldevice":1}
,"images":{"pure":1}
,"pure":{"egl":1}
,"display":{"display":1,"window":1,"control":1,"output":1,"frames":1,"device":1,"egl":1,"drm":1,"settings":1,"contains":1,"setting":1}
,"window":{"system":1,"systems":1,"directly":1,"object":1}
,"egldevice":{"provides":1,"extensions":1,"devices":1,"stream":1,"consumer":1}
,"provides":{"mechanism":1,"binding":1}
,"mechanism":{"access":1,"share":1}
,"access":{"graphics":1}
,"graphics":{"functionality":1,"api":1}
,"functionality":{"absence":1,"eglstream":1}
,"absence":{"without":1,"window":1,"underlying":1}
,"without":{"reference":1,"native":1,"copying":1}
,"reference":{"native":1}
,"native":{"window":1,"apis":1,"platform":1,"e.g":1,"interfaces":1,"interface":1}
,"system":{"method":1,"objects":1,"additionally":1,"startup":1,"stream":1}
,"method":{"initialize":1,"discover":1}
,"initialize":{"egl":1,"setup":1,"display":1}
,"displays":{"surfaces":1,"gpus":1,"managing":1,"changing":1,"documentation":1}
,"surfaces":{"directly":1,"behave":1,"stream":1,"application":1}
,"directly":{"top":1,"screen":1,"typically":1,"display":1}
,"top":{"gpus":1}
,"gpus":{"devices":1,"egldevice":1,"displays":1}
,"devices":{"rather":1,"displays":1,"allows":1}
,"rather":{"native":1,"presenting":1}
,"objects":{"cross-platform":1}
,"cross-platform":{"method":1}
,"discover":{"media":1}
,"media":{"devices":1}
,"extensions":{"boot":1,"specify":1,"nvidia":1,"eglgetprocaddress":1}
,"boot":{"strap":1}
,"strap":{"egl":1}
,"egloutput":{"graphical":1,"allows":1,"provides":1,"instances":1,"consumer":1,"layer":1,"detailed":1,"window":1}
,"graphical":{"outputs":1}
,"outputs":{"egldevice":1,"device":1,"often":1,"selecting":1}
,"allows":{"enumeration":1,"rendering":1,"applications":1}
,"enumeration":{"outputs":1}
,"device":{"egloutput":1,"using":1,"detailed":1,"eglgetplatformdisplayext":1,"file":1}
,"rendering":{"directly":1,"defines":1,"display":1,"stream":1,"api":1,"egldevice":1,"egloutput":1,"context":1,"thread":1,"manager":1}
,"screen":{"absence":1,"rendering":1,"handle":1,"surface":1,"stream":1,"specified":1}
,"additionally":{"allows":1}
,"applications":{"bypass":1,"helloconsumer":1,"listen":1,"passing":1,"built":1,"run":1}
,"bypass":{"native":1}
,"systems":{"direct":1}
,"direct":{"rendering":1,"output":1}
,"defines":{"certain":1}
,"certain":{"egl":1}
,"resources":{"referencing":1,"drmmodegetresources":1}
,"referencing":{"display":1}
,"control":{"hardware":1}
,"hardware":{"associated":1}
,"associated":{"egl":1,"native":1}
,"binding":{"nvidia":1,"stream":1}
,"nvidia":{"cuda":1,"jetson":1,"customer":1}
,"cuda":{"multimedia":1}
,"multimedia":{"rendering":1,"producer":1}
,"output":{"typical":1,"screen":1,"associated":1,"layer":1}
,"typical":{"embedded":1}
,"embedded":{"setting":1}
,"setting":{"outputs":1,"display":1}
,"often":{"initialized":1,"suitable":1}
,"initialized":{"fixed":1}
,"fixed":{"state":1}
,"state":{"system":1}
,"startup":{"cases":1}
,"cases":{"configurable":1}
,"configurable":{"interfaces":1}
,"interfaces":{"drm":1}
,"drm":{"used":1,"screen":1,"framework":1,"mentioned":1,"device":1,"api":1}
,"eglstream":{"mechanism":1,"cannot":1,"cross-process":1,"applications":1,"bound":1,"connect":1}
,"share":{"data":1}
,"data":{"efficiently":1,"apis":1}
,"efficiently":{"different":1}
,"different":{"apis":1}
,"apis":{"without":1,"opengl":1,"direct":1}
,"copying":{"data":1}
,"opengl":{"cuda":1,"information":1,"attached":1}
,"producer":{"consumer":1,"adds":1,"attached":1,"rendering":1,"surfaces":1,"end":1,"surface":1,"stream":1,"connected":1,"following":1,"video":1,"applications":1,"screen":1}
,"consumer":{"attached":1,"retrieves":1,"producer":1,"end":1,"send":1,"connected":1,"following":1,"combination":1,"combinations":1,"-crosspart":1,"requiring":1,"texture":1}
,"attached":{"two":1,"stream":1,"producer":1,"connector":1,"encoder":1}
,"two":{"ends":1,"sub-sections":1}
,"ends":{"stream":1}
,"stream":{"object":1,"surface":1,"surfaces":1,"producers":1,"rather":1,"needs":1,"producer":1,"stream":1,"consumer":1,"using":1,"eglcreatestreamkhr":1,"bind":1,"egloutput":1,"eglcreatestreamproducersurfacekhr":1,"eglswapbuffers":1}
,"adds":{"content":1}
,"content":{"stream":1}
,"retrieves":{"content":1}
,"instances":{"specified":1}
,"specified":{"consumers":1,"platform":1}
,"consumers":{"allowing":1}
,"allowing":{"apis":1}
,"specify":{"behavior":1}
,"behavior":{"procedures":1}
,"procedures":{"functions":1}
,"functions":{"egl":1,"drm":1}
,"description":{"egl":1}
,"jetson":{"linux":1}
,"linux":{"graphics":1,"api":1}
,"api":{"reference":1,"opengl":1,"details":1,"nvidia":1}
,"khronos":{"egl":1}
,"extension":{"specifications":1,"function":1}
,"specifications":{"khronos.org":1}
,"khronos.org":{"web":1}
,"web":{"site":1}
,"runtime":{"configuration":1,"configurations":1}
,"sections":{"below":1}
,"below":{"describe":1}
,"describe":{"runtime":1,"steps":1}
,"conditions":{"requiring":1}
,"requiring":{"stream":1,"eglcontext":1}
,"underlying":{"window":1}
,"surface":{"necessary":1,"producer":1,"i.e":1,"contents":1,"uses":1,"feed":1,"eglmakecurrent":1,"screen":1,"stream":1,"binds":1,"current":1,"required":1,"native":1}
,"necessary":{"screen":1,"initialize":1,"mode":1}
,"behave":{"eglsurface":1}
,"eglsurface":{"example":1,"connects":1}
,"example":{"eglswapbuffers":1}
,"eglswapbuffers":{"called":1,"submits":1}
,"called":{"indicate":1,"mode-setting":1}
,"indicate":{"end":1}
,"end":{"frame":1,"egl":1,"egloutput":1,"stream":1}
,"frame":{"however":1}
,"however":{"stream":1}
,"producers":{"eglswapbuffers":1}
,"submits":{"rendering":1}
,"presenting":{"native":1}
,"typically":{"egloutput":1}
,"needs":{"surface":1}
,"information":{"creating":1,"documentation":1,"drmmodegetplane":1,"connectors":1}
,"creating":{"stream":1}
,"common":{"case":1}
,"case":{"stream":1}
,"application":{"producing":1,"binary":1}
,"producing":{"display":1}
,"frames":{"using":1,"directly":1}
,"using":{"opengl":1,"stream":1,"swap":1,"egl_khr_stream_consumer_gltexture":1}
,"layer":{"sending":1,"stream":1,"plane":1}
,"sending":{"frames":1}
,"following":{"two":1,"functions":1,"additions":1,"command":1}
,"sub-sections":{"describe":1}
,"steps":{"render":1,"follow":1,"setting":1,"creating":1}
,"detailed":{"steps":1}
,"create":{"egl":1,"stream":1}
,"context":{"egl":1,"stream":1,"current":1,"draw":1,"surface":1}
,"bind":{"context":1,"consumer":1}
,"i.e":{"current":1,"stream":1}
,"post":{"surface":1}
,"contents":{"stream":1}
,"swap":{"buffers":1}
,"uses":{"following":1}
,"function":{"description":1,"call":1}
,"creates":{"eglsurface":1,"egldisplay":1}
,"connects":{"producer":1}
,"binds":{"egloutput":1,"context":1,"handle":1}
,"send":{"rendering":1}
,"according":{"egl_khr_stream":1}
,"egl_khr_stream":{"specification":1}
,"specification":{"eglstream":1}
,"cannot":{"used":1}
,"used":{"until":1,"cross-partition":1,"initialize":1,"save":1,"drmmodesetplane":1}
,"until":{"connected":1}
,"connected":{"consumer":1,"producer":1,"monitors":1}
,"query":{"egl":1,"available":1,"desired":1,"info":1}
,"available":{"egldevices":1,"encoders":1,"connector":1}
,"egldevices":{"eglquerydevicesext":1}
,"obtain":{"egl":1,"drm-kms":1,"layer":1}
,"step":{"creates":1,"creating":1}
,"egldisplay":{"belong":1,"handle":1}
,"belong":{"native":1}
,"setup":{"egl":1,"egloutput":1}
,"selecting":{"output":1,"known":1}
,"done":{"enumerating":1,"looking":1}
,"enumerating":{"outputs":1}
,"known":{"index":1}
,"looking":{"output":1}
,"e.g":{"drm":1}
,"settings":{"native":1,"part":1}
,"connect":{"output":1,"surface":1}
,"object":{"eglstreamconsumeroutputext":1}
,"buffer":{"configurations":1,"rendered":1}
,"configurations":{"choosing":1}
,"choosing":{"eglconfig":1}
,"feed":{"stream":1}
,"current":{"binding":1,"rendering":1,"context":1,"modes":1}
,"cross-process":{"mode":1,"cross-partition":1,"egldevice":1}
,"additions":{"changes":1}
,"changes":{"nvm_eglstream.int":1}
,"addressspace":{"nvm_eglstream_producer":1,"nvm_eglstream_consumer":1}
,"filename":{"nvm_eglstream_as0":1}
,"arguments":{"-producer":1,"-consumer":1}
,"-producer":{"nfsmount":1}
,"nfsmount":{"welcome_animation.264":1,"nvm_eglstream_egldevice":1}
,"welcome_animation.264":{"-standalone":1}
,"memorypoolsize":{"32m":1}
,"extendedmemorypoolsize":{"64m":1}
,"heapextensionreservedsize":{"64m":1}
,"task":{"initial":1}
,"startit":{"false":1}
,"-consumer":{"-standalone":1}
,"rebuild":{"application":1}
,"load":{"application":1,"nfsmount":1,"demo_dd":1}
,"binary":{"following":1}
,"start":{"consumer":1,"producer":1,"helloconsumer":1,"helloproducer":1}
,"nvm_eglstream_consumer":{"initial":1}
,"nvm_eglstream_producer":{"initial":1}
,"procedure":{"enables":1,"extended":1}
,"enables":{"video":1}
,"video":{"producer":1,"consumer":1}
,"combination":{"procedure":1}
,"extended":{"producer":1}
,"cross-partition":{"eglstream":1,"applications":1}
,"release":{"includes":1}
,"includes":{"simple":1}
,"simple":{"cross-process":1}
,"helloconsumer":{"helloproducer":1,"target":1,"initial":1}
,"helloproducer":{"applications":1,"target":1,"initial":1}
,"listen":{"127.0.0.1":1}
,"127.0.0.1":{"port":1}
,"port":{"8888":1}
,"8888":{"default":1}
,"default":{"used":1,"mode":1}
,"passing":{"-crosspart":1}
,"-crosspart":{"consumer":1,"consumer_ip":1}
,"consumer_ip":{"consumer_ip":1,"producer":1}
,"built":{"demo_dd":1}
,"target":{"following":1}
,"run":{"correctly":1}
,"correctly":{"upper-left":1}
,"upper-left":{"corner":1}
,"corner":{"display":1}
,"contains":{"flashing":1,"list":1}
,"flashing":{"square":1}
,"egl_khr_stream_consumer_gltexture":{"functionality":1,"khronos.org":1}
,"bound":{"gltexture":1}
,"gltexture":{"consumer":1}
,"eglcontext":{"consumer":1}
,"texture":{"buffer":1}
,"rendered":{"eglsurface":1}
,"documentation":{"egl_khr_stream_consumer_gltexture":1,"hardware":1}
,"connecting":{"surface":1,"stream":1}
,"eglgetplatformdisplayext":{"returns":1}
,"returns":{"egldisplay":1,"handle":1}
,"handle":{"belonging":1,"screen":1,"current":1}
,"belonging":{"screen":1}
,"platform":{"argument":1,"relationship":1}
,"argument":{"function":1}
,"eglmakecurrent":{"attaches":1,"binds":1}
,"attaches":{"egl":1}
,"draw":{"read":1}
,"read":{"egl":1}
,"required":{"connecting":1}
,"manager":{"drm":1}
,"framework":{"manage":1}
,"manage":{"gpus":1}
,"managing":{"connected":1}
,"monitors":{"displays":1}
,"changing":{"current":1}
,"modes":{"called":1,"connector":1}
,"mode-setting":{"functions":1}
,"mentioned":{"necessary":1}
,"part":{"step":1}
,"interface":{"used":1}
,"select":{"encoder":1,"mode":1,"suitable":1,"crtcs":1}
,"encoder":{"crtc":1,"attached":1,"incompatible":1,"contains":1}
,"crtc":{"connector":1,"plane":1,"drive":1,"iterate":1,"drmmodegetcrtc":1}
,"open":{"drm":1}
,"file":{"drmopen":1}
,"drm-kms":{"resources":1}
,"optional":{"plane":1}
,"plane":{"information":1,"find":1,"crtc":1,"used":1}
,"drmmodegetplane":{"drmmodegetplaneresources":1}
,"desired":{"connector":1}
,"connector":{"drmmodegetconnector":1,"retrieved":1,"choose":1,"find":1,"encoder":1,"call":1}
,"valid":{"modes":1}
,"retrieved":{"call":1}
,"call":{"drmmodegetconnector":1,"drmmodesetcrtc":1}
,"drmmodegetconnector":{"select":1}
,"mode":{"used":1,"list":1,"highest":1,"drmmodesetcrtc":1}
,"save":{"first":1}
,"first":{"mode":1}
,"list":{"default":1,"encoders":1,"crtcs":1}
,"highest":{"resolution":1}
,"resolution":{"possible":1}
,"possible":{"often":1}
,"suitable":{"choice":1,"crtc":1}
,"already":{"encoder":1}
,"choose":{"drmmodegetencoder":1}
,"incompatible":{"crtc":1}
,"find":{"iterating":1,"crtc":1,"suitable":1}
,"iterating":{"available":1}
,"drive":{"connector":1,"selected":1}
,"iterate":{"list":1}
,"encoders":{"available":1}
,"crtcs":{"work":1}
,"work":{"select":1}
,"info":{"crtc":1}
,"drmmodesetcrtc":{"obtain":1}
,"selected":{"connector":1}
,"details":{"drm":1}
,"ask":{"nvidia":1}
,"customer":{"engineer":1}
,"engineer":{"sample":1}
,"sample":{"implementation":1}
,"implementation":{"window_egldevice.zip":1}
,"board-to-display":{"connectors":1}
,"connectors":{"platform":1,"displays":1}
,"relationship":{"connectors":1}
}
;Search.control.loadWordPairs(pairs);
