var pairs =
{
"applies":{"jetson":1,"jeton":1}
,"jetson":{"xavier":1,"nano":1,"agx":1,"tx2":1,"tx1":1,"linux":1,"platforms":1,"platform":1,"download":1,"board":1,"devices":1,"secureboot":1,"device":1,"module\u2019s":1,"module":1,"modules":1}
,"xavier":{"original":1,"series":1,"jetson":1,"fuse":1,"0x19":1,"jetson-xavier-nx-devkit-emmc":1}
,"original":{"jetson":1}
,"nano":{"jetson":1,"devices":1,"key":1,"production":1,"development":1}
,"agx":{"xavier":1}
,"series":{"jetson":1,"t194":1,"t186":1,"fuse":1,"excluding":1,"platforms":1,"0x19":1,"0x18":1,"jetson-agx-xavier-devkit":1,"jetson-tx2-devkit":1,"encrypt":1,"boot":1}
,"tx2":{"series":1,"jetson":1,"fuse":1,"key":1}
,"nvidia":{"jetson":1,"socs":1,"fuses":1,"strongly":1,"provides":1}
,"linux":{"driver":1}
,"driver":{"package":1}
,"package":{"l4t":1,"secureboot":1,"openssl":1,"platform":1,"installed":1,"provides":1,"available":1}
,"l4t":{"provides":1,"release":1}
,"provides":{"boot":1,"means":1,"tool":1,"two":1,"values":1}
,"boot":{"security":1,"codes":1,"vector":1,"once":1,"strap":1,"failures":1,"image":1,"files":1,"device":1,"file":1,"sequence":1,"flow":1}
,"security":{"using":1,"boot":1,"information":1,"device":1,"key":1,"module":1,"application":1,"applications":1}
,"using":{"secureboot":1,"public":1,"flash.sh":1,"user":1,"private":1,"odmfuse.sh":1,"shown":1,"pkc-key":1,"sbk":1,"tool":1,"extlinux.conf":1}
,"secureboot":{"package":1,"prevents":1,"key":1,"fuses":1,"jetson":1,"process":1,"requires":1,"additional":1,"software":1,"kernel":1}
,"prevents":{"execution":1,"script":1}
,"execution":{"unauthorized":1,"openssl":1,"environment":1}
,"unauthorized":{"boot":1}
,"codes":{"chain":1,"bct":1}
,"chain":{"trust":1}
,"trust":{"root-of-trust":1}
,"root-of-trust":{"on-die":1}
,"on-die":{"bootrom":1}
,"bootrom":{"code":1}
,"code":{"authenticates":1}
,"authenticates":{"boot":1}
,"bct":{"bootloader":1}
,"bootloader":{"warm":1,"images":1,"tos":1,"kernel":1,"directory":1}
,"warm":{"boot":1}
,"vector":{"using":1}
,"public":{"key":1}
,"key":{"cryptography":1,"sbk":1,"hash":1,"encrypting":1,"encryption":1,"seed":1,"blob":1,"using":1,"pair":1,"option":1,"file":1,"hardware":1,"conversion":1,"pkc":1,"consists":1,"need":1,"stored":1,"ekb":1,"flash.sh":1,"specified":1,"format":1,"interpreted":1,"odm_production_mode":1,"used":1,"pkc_disable":1,"signing":1,"encrypt_keyfile":1,"fields":1,"section":1}
,"cryptography":{"pkc":1}
,"pkc":{"keys":1,"sbk":1,"key":1,"kek":1,"fuses":1,"sbkpkc":1,"--kek2":1,"jetson":1,"pkc":1,"file":1,"hash":1,"key.pem":1,"kek2":1,"encryption":1,"signing":1,"signed":1,"keyfile":1,"tegrafuse.sh":1}
,"keys":{"stored":1,"different":1,"example":1,"together":1,"content":1,"generate":1}
,"stored":{"write-once-read-multiple":1,"file":1,"encrypted":1,"four":1}
,"write-once-read-multiple":{"fuse":1}
,"fuse":{"devices":1,"bit":1,"value":1,"write":1,"addresses":1,"names":1,"specification":1,"name":1,"values":1,"burned":1,"burning":1,"sign":1,"bits":1,"information":1,"using":1,"blob":1,"command":1,"greater":1,"pkc":1,"jtag":1,"target":1}
,"devices":{"jetson":1,"security":1,"topic":1,"efficiently":1}
,"platforms":{"support":1}
,"support":{"secureboot":1,"package":1}
,"sbk":{"encrypt":1,"aes":1,"requires":1,"odm":1,"key":1,"security":1,"fuse":1,"pkc":1,"fuses":1,"jetson-xavier-8gb":1,"kek2":1,"file":1,"pkc-key":1}
,"encrypt":{"bootloader":1,"decrypted":1,"kernel":1,"bootloaders":1,"decrypt":1,"application":1,"sign":1,"file":1}
,"fuses":{"security":1,"control":1,"writable":1,"public_key_hash":1,"related":1,"jetson":1,"handled":1,"user\u2019s":1,"fuse":1,"remain":1,"programmed":1,"software":1,"customer":1,"first":1,"disabled":1,"pkc":1,"using":1,"odmfuse.sh":1,"completely":1,"follows":1,"repeatedly":1,"pre-burn":1,"written":1,"cannot":1,"target":1,"enter":1}
,"socs":{"contain":1}
,"contain":{"multiple":1}
,"multiple":{"fuses":1,"jetson":1}
,"control":{"different":1}
,"different":{"items":1,"combinations":1,"meaning":1,"formats":1,"purposes":1}
,"items":{"security":1}
,"once":{"fuse":1,"odm_production_mode":1,"burned":1,"example":1}
,"bit":{"cannot":1,"already":1,"programmed":1,"size":1,"disables":1,"different":1,"map":1,"ignore_dev_sel_straps":1,"enable_watchdog":1,"disable":1,"burned":1,"locks":1,"definitions":1}
,"cannot":{"change":1,"changed":1,"later":1}
,"change":{"value":1}
,"value":{"back":1,"0x01":1,"0x1":1,"bit":1,"odmfuse.sh":1,"odm":1,"example":1,"&0x3fff":1,"setting":1,"value":1,"quoted":1,"board":1,"fab":1,"sku":1,"environment":1}
,"back":{"example":1}
,"example":{"fuse":1,"kek2":1,"0x2":1,"sbk":1,"user":1,"0xddccbbaa":1,"setting":1,"device":1,"implementations":1}
,"0x01":{"changed":1}
,"changed":{"0x03":1,"once":1}
,"0x03":{"0x05":1}
,"0x05":{"0x4":1}
,"0x4":{"bit":1}
,"already":{"programmed":1}
,"odm_production_mode":{"fused":1,"fuses":1,"fuse":1}
,"fused":{"value":1,"values":1}
,"0x1":{"further":1,"jtag":1,"locks":1}
,"further":{"fuse":1,"changes":1}
,"write":{"requests":1,"corresponding":1}
,"requests":{"blocked":1}
,"blocked":{"fused":1}
,"values":{"available":1,"non-secure":1,"jetson":1,"major":1,"cannot":1,"fill":1}
,"available":{"provided":1,"linux_for_tegra":1}
,"provided":{"api":1}
,"api":{"however":1}
,"however":{"odm_reserved":1,"msb":1}
,"odm_reserved":{"odm_lock":1,"field":1,"setting":1,"specified":1}
,"odm_lock":{"fields":1,"bit":1,"fuses":1,"specified":1,"0x1":1,"0x5":1}
,"fields":{"writable":1,"separated":1,"signature":1,"filled":1}
,"writable":{"until":1,"odmfuse.sh":1}
,"until":{"odm_lock":1}
,"programmed":{"changing":1,"zeros":1}
,"changing":{"value":1}
,"although":{"soc":1}
,"soc":{"fuses":1,"device":1}
,"odmfuse.sh":{"script":1,"options":1,"pkc":1,"allows":1,"command":1,"boards":1,"offline":1,"--noburn":1,"option":1,"chip_id":1,"disable-jtag":1}
,"script":{"program":1,"flashes":1,"odmfush.sh":1,"actually":1,"usage":1,"ubuntu@":1,"command":1,"replaces":1,"stores":1}
,"program":{"fuses":1,"odm":1}
,"public_key_hash":{"pkc_disable":1}
,"pkc_disable":{"t210":1,"key":1}
,"t210":{"secure_boot_key":1,"processor":1}
,"secure_boot_key":{"odm_production_mode":1,"three":1}
,"following":{"two":1,"documents":1,"procedures":1,"placeholders":1}
,"two":{"tables":1,"keys":1,"different":1,"example":1}
,"tables":{"describe":1}
,"describe":{"user-programmable":1,"fuse":1}
,"user-programmable":{"fuses":1}
,"related":{"secureboot":1}
,"tx1":{"t210":1,"jetson":1,"fuse":1,"0x21":1}
,"default":{"value":1}
,"rsa":{"public":1,"key-pair":1,"key":1,"3072\u2011bits":1}
,"software":{"configuration":1,"version":1,"converts":1}
,"configuration":{"fuses":1,"options":1}
,"t194":{"jetson":1}
,"aes":{"encryption":1}
,"encryption":{"key":1,"keys":1,"mode":1,"service":1}
,"encrypting":{"bootloader":1,"kernel":1}
,"four":{"32\u2011bit":1,"reservedodm":1,"32-bit":1,"big-endian":1,"8\u2011digit":1}
,"32\u2011bit":{"registers":1,"words":1,"word":1,"eight-digit":1,"big-endian":1}
,"registers":{"named":1}
,"named":{"kek00":1,"kek10":1,"kek20":1,"rsa_priv.pem":1,"filename":1}
,"kek00":{"kek03":1}
,"kek10":{"kek13":1}
,"distinct":{"fuse":1}
,"addresses":{"kek0":1}
,"kek0":{"kek1":1}
,"kek1":{"single":1}
,"single":{"256\u2011bit":1,"big-endian":1,"32-bit":1,"128-bit":1,"256-bit":1}
,"256\u2011bit":{"fuse":1,"64\u2011digit":1}
,"kek20":{"kek23":1}
,"may":{"secure_boot_key":1,"purposes":1,"sbk":1,"required":1,"omitted":1,"placed":1}
,"three":{"key":1}
,"combinations":{"width":1}
,"width":{"key":1}
,"seed":{"encode":1,"encrypt":1}
,"encode":{"keys":1}
,"kek2":{"used":1,"sbk":1,"jetson":1,"file":1}
,"used":{"key":1,"burn":1,"consult":1,"high-level":1,"encrypt":1,"along":1,"repeatedly":1,"fuse":1,"jetson":1,"device":1,"procedures":1,"generate":1,"flash":1}
,"decrypted":{"encrypted":1}
,"encrypted":{"key":1,"keyblob":1,"form":1,"kernel":1,"signed":1,"files":1}
,"blob":{"ekb":1,"used":1,"trusted":1,"factory":1,"untrusted":1}
,"ekb":{"tos":1,"encrypted":1,"uses":1,"generated":1,"generation":1,"target":1,"flashed":1,"file":1}
,"tos":{"enabled":1,"prepare":1,"content":1}
,"handled":{"user":1}
,"user":{"follows":1,"key":1,"guide":1,"sbk":1}
,"0x0":{"jtag":1}
,"jtag":{"enabled":1,"disabled":1,"option":1,"debugger":1}
,"enabled":{"default":1,"t210":1}
,"programmable":{"fuses":1,"fuse_security_mode":1}
,"user\u2019s":{"direction":1}
,"direction":{"however":1}
,"msb":{"nvidia":1}
,"disables":{"write":1,"further":1,"reservedodm0":1,"reservedodm1":1,"reservedodm2":1,"reservedodm3":1,"jtag":1}
,"corresponding":{"32-bit":1,"32\u2011bit":1}
,"32-bit":{"odm":1,"words":1,"number":1,"big":1,"big-endian":1}
,"odm":{"fuses":1,"fuse":1,"production":1}
,"0x2":{"locks":1}
,"locks":{"bits":1,"makes":1,"first":1}
,"bits":{"odm_reserved":1,"described":1,"2-0":1,"rsa":1,"may":1,"eight":1,"nvidia":1,"7-6":1}
,"depending":{"sec_boot_dev_sel":1,"application":1}
,"sec_boot_dev_sel":{"bit":1,"meaningful":1,"boot":1}
,"map":{"configuration":1}
,"options":{"bits":1,"blow":1}
,"2-0":{"sec_boot_dev_sel":1}
,"meaningful":{"ignore_dev_sel_straps":1}
,"ignore_dev_sel_straps":{"enabled":1,"ignore":1}
,"emmc":{"spi":1}
,"ignore":{"device":1}
,"device":{"selection":1,"erroneous":1,"depends":1,"expects":1,"forced":1,"emmc":1,"key":1,"name":1,"names":1,"determine":1,"reflash":1,"first":1,"table":1,"force":1,"pkc":1,"zero-key":1,"recovery":1,"root":1}
,"selection":{"boot":1}
,"disable":{"rcm":1}
,"rcm":{"mode":1}
,"mode":{"t194":1,"uses":1,"run":1,"fusing":1}
,"details":{"hardware":1,"signature":1}
,"hardware":{"fuses":1,"security":1}
,"names":{"consult":1,"topic":1}
,"consult":{"following":1,"hardware":1,"user":1}
,"specification":{"application":1,"app":1}
,"application":{"note":1,"fuses":1,"prepare":1,"used":1,"generate":1,"encryption":1,"encrypt":1,"keys":1}
,"excluding":{"jetson":1}
,"app":{"note":1}
,"name":{"aliases":1,"jetson":1}
,"aliases":{"recognized":1}
,"recognized":{"tegraflash":1}
,"tegraflash":{"t210":1,"alias":1,"t186":1}
,"alias":{"notes":1}
,"t186":{"t194":1}
,"odm_reserved0":{"odm_reserved1":1}
,"odm_reserved1":{"odm_reserved7":1}
,"reservedodm0":{"reservedodm1":1}
,"reservedodm1":{"reservedodm7":1}
,"customer":{"programmable":1,"programming":1}
,"remain":{"programmable":1,"writable":1}
,"fuse_security_mode":{"programmed":1}
,"intended":{"application":1}
,"version":{"revocation":1}
,"revocation":{"may":1}
,"purposes":{"discretion":1}
,"odm_reserved8":{"odm_reserved11":1}
,"reservedodm8":{"reservedodm11":1}
,"reservedodm11":{"t194":1}
,"programming":{"result":1}
,"result":{"boot":1}
,"failures":{"unexpected":1}
,"unexpected":{"behavior":1}
,"changes":{"reservedodm":1}
,"reservedodm":{"fuses":1}
,"first":{"four":1,"32\u2011bit":1,"third":1,"flashed":1}
,"disabled":{"means":1,"t210":1}
,"odmlock":{"disables":1}
,"overall":{"fusing":1}
,"fusing":{"signing":1,"xml":1,"multiple":1,"jetson":1}
,"signing":{"binaries":1,"flashing":1,"signing":1,"key":1,"used":1,"specified":1,"type":1,"burned":1,"encrypting":1,"pkc-key":1,"jetson":1,"modules":1}
,"binaries":{"flow":1}
,"process":{"pkc":1}
,"install":{"secureboot":1}
,"necessary":{"prepare":1}
,"prepare":{"kek":1,"sbk":1,"user":1}
,"kek":{"sbk":1,"odm":1,"file":1}
,"generate":{"rsa":1,"key-pair":1,"truly":1,"application":1,"encrypted":1,"signature":1,"ekb":1}
,"flash.sh":{"option":1,"\u2011\u2011user_key":1,"encrypt":1,"command":1,"pkc_keyfile":1,"device_name":1,"procedure":1,"-no-flash":1,"--no-flash":1}
,"\u2011\u2011user_key":{"option":1,"command":1}
,"burn":{"kek":1,"fuse":1,"pkc":1,"fuses":1,"secure":1}
,"information":{"odm_production_mode":1,"ekb":1,"section":1,"differs":1,"generate":1,"user":1}
,"sign":{"boot":1,"flash":1,"extlinux.conf":1,"kernel":1,"image":1}
,"image":{"files":1,"kernel":1,"target":1,"nfs":1}
,"files":{"pkc":1,"jetson":1,"prepare":1,"encrypted":1,"signature":1,"authenticate":1}
,"flash":{"signed":1,"step":1,"boot":1,"jetson":1,"nfs":1,"separate":1,"initrd":1,"script":1,"target":1,"firmware":1}
,"signed":{"boot":1,"binaries":1,"keys":1}
,"burned":{"protect":1,"fuses":1}
,"protect":{"soc":1,"odm":1}
,"erroneous":{"odm":1}
,"production":{"fuse":1,"mode":1,"module":1}
,"installing":{"secureboot":1}
,"x86":{"host":1}
,"host":{"running":1,"usb":1,"necessary":1,"system":1}
,"running":{"ubuntu":1,"odmfuse.sh":1}
,"ubuntu":{"16.04":1}
,"16.04":{"18.04":1}
,"18.04":{"lts":1}
,"libftdi-dev":{"usb":1}
,"usb":{"debug":1,"cable":1}
,"debug":{"port":1,"serial":1}
,"port":{"support":1,"connected":1}
,"openssh-server":{"package":1}
,"full":{"installation":1}
,"installation":{"latest":1}
,"latest":{"l4t":1,"release":1,"secureboot":1}
,"release":{"host":1}
,"download":{"latest":1,"center":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"embedded":{"linux-tegra-archive":1}
,"platform":{"connected":1,"jetson":1,"using":1}
,"connected":{"host":1,"i.e":1}
,"serial":{"port":1}
,"center":{"search":1}
,"search":{"database":1}
,"database":{"downloads":1}
,"downloads":{"secure":1}
,"secure":{"boot":1,"engine":1,"fuse":1}
,"directory":{"contains":1,"directory":1,"created":1,"installed":1,"factory":1,"linux_for_tegra":1,"host":1}
,"contains":{"linux_for_tegra":1,"filename":1,"four":1,"key":1}
,"linux_for_tegra":{"directory":1,"\u200Cfuseblob.tbz2":1,"\u200Cbootloader":1,"pkc":1,"folder":1,"readme_massflash.txt":1}
,"created":{"jetson":1}
,"board":{"support":1,"possible":1,"setting":1,"number":1,"target":1,"boots":1,"login":1,"display":1,"via":1}
,"enter":{"command":1,"commands":1}
,"command":{"untar":1,"overlays":1,"line":1,"file":1,"command":1,"performs":1,"reports":1,"without":1,"flashing":1,"sign":1,"flash":1,"below":1}
,"untar":{"downloaded":1}
,"downloaded":{"file":1,"untarred":1}
,"tar":{"xvjf":1}
,"xvjf":{"secureboot_":1}
,"secureboot_":{"release_version":1}
,"release_version":{".tbz2":1}
,"overlays":{"contents":1}
,"contents":{"file":1}
,"file":{"linux_for_tegra":1,"named":1,"securely":1,"used":1,"restrict":1,"big-endian":1,"containing":1,"example":1,"pem":1,"security":1,"single":1,"high-level":1,"jtag":1,"sbk_file":1,"sbk":1,"--kek2":1,"device_name":1,"dk_file":1,"specified":1,"may":1,"user":1,"system":1,"keyfile":1,"authenticating":1,"encrypted":1,"save":1,"run":1,"section":1,".pem":1,"provides":1,"key":1,"contains":1,"user_keyfile":1}
,"generating":{"rsa":1,"ekb":1}
,"requires":{"rsa":1}
,"key-pair":{"whose":1}
,"whose":{"length":1}
,"length":{"2048":1}
,"2048":{"bits":1}
,"3072\u2011bits":{"rsa":1}
,"3072-bit":{"rsa":1}
,"option":{"supported":1,"flash.sh":1,"specifies":1,"examples":1,"block":1,"generates":1,"running":1,"normally":1,"verify":1,"specified":1}
,"supported":{"jetson":1}
,"execute":{"commands":1}
,"openssl":{"genrsa":1,"generates":1,"utilities":1,"burn":1,"sign":1}
,"genrsa":{"-out":1}
,"-out":{"rsa_priv.pem":1}
,"rsa_priv.pem":{"2048":1,"3072":1,"file":1}
,"upon":{"successful":1}
,"successful":{"execution":1}
,"generates":{"key":1,"linux_for_tegra":1}
,"rename":{"save":1}
,"save":{"key":1,"copy":1}
,"securely":{"safely":1,"keep":1}
,"depends":{"securely":1}
,"keep":{"key":1}
,"ensure":{"security":1}
,"restrict":{"access":1}
,"access":{"permission":1,"fuses":1,"fuse":1,"target\u2019s":1}
,"permission":{"minimum":1}
,"minimum":{"number":1}
,"number":{"personnel":1,"key":1,"stored":1,"form":1,"hexadecimal":1,"field":1}
,"truly":{"random":1}
,"random":{"number":1}
,"module":{"hsm":1,"user":1,"eeprom":1,"0x21":1,"jetson":1}
,"guide":{"output":1,"application":1}
,"output":{"format":1,"big-endian":1}
,"format":{"private":1,"example":1,"leading":1,"format":1,"jetson":1,"follows":1,"file":1}
,"private":{"key":1}
,"conversion":{"pem":1}
,"pem":{"format":1}
,"preparing":{"sbk":1,"user":1,"kek":1}
,"want":{"encrypt":1,"security":1,"re-enter":1}
,"uses":{"two":1,"decrypt":1,"openssl":1,"zero-key":1}
,"together":{"called":1}
,"called":{"sbkpkc":1}
,"consists":{"four":1}
,"words":{"stored":1,"odm_reserved":1}
,"big-endian":{"hexadecimal":1,"32\u2011bit":1,"128\u2011bit":1,"hex":1,"format":1,"numbers":1,"number":1}
,"hexadecimal":{"format":1,"numbers":1,"digits":1,"number":1}
,"0x12345678":{"0x9abcdef0":1}
,"0x9abcdef0":{"0xfedcba98":1,"0xffeeddcc":1}
,"0xfedcba98":{"0x76543210":1}
,"representation":{"fusing":1}
,"xml":{"file":1}
,"kernel":{"image":1,"kernel-dtb":1,"images":1,"boot":1}
,"kernel-dtb":{"initrd":1}
,"initrd":{"extlinux.conf":1,"jetson":1,"binary":1,"using":1,"file":1}
,"extlinux.conf":{"files":1,"separately":1,"file":1,"topic":1}
,"need":{"user":1}
,"keyblob":{"ekb":1}
,"form":{"secure":1,"0xnnnn":1,"0xnnnnnnnn":1}
,"engine":{"retrieves":1}
,"retrieves":{"user":1}
,"decrypt":{"kernel":1,"keys":1}
,"generated":{"ekb":1}
,"generation":{"topic":1}
,"topic":{"trusty":1,"plan":1,"jetson":1,"quick":1,"basic":1}
,"trusty":{"trusted":1}
,"trusted":{"execution":1,"environment":1}
,"images":{"script":1,"ekb":1}
,"flashes":{"ekb":1,"image":1}
,"target":{"along":1,"using":1,"device":1,"board":1,"address":1,"contains":1}
,"along":{"encrypted":1,"pkc":1}
,"flashed":{"eks":1,"device":1,"pkc":1}
,"eks":{"partition":1}
,"specified":{"two":1,"value":1,"fuses":1,"flashing":1,"key":1}
,"formats":{"different":1}
,"line":{"option":1,"options":1,"appropriate":1}
,"containing":{"four":1,"hexadecimal":1}
,"8\u2011digit":{"hexadecimal":1}
,"numbers":{"\u2011\u2011user_key":1,"presented":1,"hexadecimal":1}
,"specifies":{"pathname":1,"device":1}
,"pathname":{"file":1,"key":1,"256-bit":1}
,"0xffeeddcc":{"0xbbaa9988":1}
,"section":{"sign":1,"ekb":1,"signing":1,"following":1,"kernel":1,"generating":1,"preparing":1}
,"step":{"using":1,"above":1}
,"digits":{"represent":1,"zero":1}
,"represent":{"key":1}
,"interpreted":{"single":1}
,"128\u2011bit":{"value":1}
,"described":{"documentation":1,"topic":1,"section":1,"placeholders":1}
,"documentation":{"security":1}
,"hex":{"format":1}
,"128-bit":{"number":1,"big-endian":1,"key":1}
,"256-bit":{"number":1,"key":1,"big-endian":1}
,"applications":{"secureboot":1,"encrypt":1}
,"additional":{"odm":1}
,"required":{"specific":1}
,"specific":{"fuse":1}
,"differs":{"depending":1}
,"presented":{"big-endian":1}
,"leading":{"may":1}
,"omitted":{"jetson":1}
,"converts":{"big-endian":1}
,"expects":{"standard":1}
,"standard":{"openssl":1,"odmfuse.sh":1}
,"utilities":{"output":1}
,"burning":{"pkc":1,"fuses":1,"tests":1,"operations":1}
,"steps":{"burning":1}
,"navigate":{"directory":1,"linux_for_tegra":1}
,"installed":{"l4t":1}
,"put":{"jetson":1}
,"forced":{"recovery":1}
,"recovery":{"mode":1,"button":1}
,"odmfush.sh":{"command":1,"uses":1}
,"examples":{"examples":1,"common":1}
,"common":{"operations":1}
,"allows":{"program":1}
,"completely":{"discretion":1}
,"discretion":{"skip":1}
,"skip":{"topic":1}
,"plan":{"modify":1}
,"modify":{"fuses":1}
,"blow":{"odm":1}
,"sets":{"sec_boot_dev_cfg":1,"odm_lock":1,"odm_reserved":1,"production":1,"sw_reserved":1,"device":1,"secureboot":1,"authentication":1}
,"sec_boot_dev_cfg":{"value":1}
,"&0x3fff":{"detail":1}
,"detail":{"refer":1}
,"refer":{"trm":1}
,"block":{"jtag":1}
,"setting":{"bit":1,"odm_lock":1,"environment":1}
,"makes":{"read-only":1}
,"read-only":{"corresponding":1}
,"word":{"odm_reserved":1}
,"0x5":{"locks":1}
,"third":{"32\u2011bit":1}
,"quoted":{"256\u2011bit":1,"32\u2011bit":1}
,"64\u2011digit":{"hexadecimal":1}
,"0xnnnn":{"nnnn":1}
,"nnnn":{"last":1}
,"last":{"bits":1}
,"eight":{"digits":1}
,"zero":{"bits":1}
,"eight-digit":{"hexadecimal":1}
,"sw_reserved":{"0xxx":1}
,"0xxx":{"bit":1}
,"high-level":{"security":1,"application":1}
,"content":{"dk_file":1,"sbk_file":1,"file":1}
,"dk_file":{"single":1,"--disable-jtag":1}
,"big":{"endian":1}
,"endian":{"hash":1}
,"hash":{"hex":1,".pem":1}
,"sbk_file":{"four":1,"device_name":1,"--disable-jtag":1}
,"bootloaders":{"used":1}
,"prepares":{"fuse":1}
,"repeatedly":{"factory":1,"instead":1}
,"factory":{"floor":1,"host":1,"environment":1}
,"\u200Cfuseblob.tbz2":{"downloaded":1}
,"untarred":{"linux_for_tegra":1}
,"fuseblob.tbz2":{"untarred":1}
,"\u200Cbootloader":{"\u200Cfusecmd.sh":1}
,"\u200Cfusecmd.sh":{"used":1}
,"instead":{"standard":1}
,"--kek2":{"path":1,"kek2":1}
,"--kek256":{"path":1}
,"authentication":{"status":1}
,"status":{"board":1}
,"possible":{"values":1}
,"non-secure":{"pkc":1}
,"boards":{"connected":1}
,"i.e":{"offline":1}
,"offline":{"mode":1}
,"run":{"odmfuse.sh":1,"script":1}
,"--noburn":{"command":1,"0x19":1}
,"specify":{"carrier":1,"user_key":1}
,"carrier":{"board":1}
,"environment":{"variables":1,"variable":1,"tool":1,"linux_for_tegra":1}
,"variables":{"command":1}
,"appropriate":{"values":1}
,"module\u2019s":{"eeprom":1}
,"eeprom":{"described":1,"layout":1}
,"boardid":{"value":1,"2888":1}
,"fab":{"value":1,"number":1,"400":1}
,"boardsku":{"value":1,"0006":1}
,"sku":{"number":1}
,"boardrev":{"values":1,"b.0":1}
,"major":{"revision":1}
,"revision":{"minor":1,"fields":1}
,"minor":{"revision":1}
,"separated":{"period":1}
,"sudo":{"fab":1,"odmfuse.sh":1,"flash.sh":1,"bash":1,"tools":1,"tegrafuse.sh":1,"odmfuseread.sh":1}
,"400":{"boardid":1}
,"2888":{"boardsku":1}
,"0006":{"boardrev":1}
,"b.0":{"odmfuse.sh":1}
,"0x19":{"--auth":1,"pkc_keyfile":1,"--key":1}
,"--auth":{"sbkpkc":1}
,"sbkpkc":{"pkc":1,"signing":1}
,"actually":{"burning":1,"burn":1}
,"pre-burn":{"processing":1}
,"processing":{"tests":1,"verification":1}
,"tests":{"performed":1,"fuse":1}
,"performed":{"usual":1}
,"usual":{"option":1}
,"normally":{"used":1}
,"non-destructive":{"testing":1}
,"testing":{"fuse":1}
,"operations":{"high-risk":1,"perform":1}
,"high-risk":{"can\u2019t":1}
,"can\u2019t":{"reversed":1}
,"reversed":{"nvidia":1}
,"strongly":{"recommends":1}
,"recommends":{"\u2011\u2011test":1}
,"\u2011\u2011test":{"option":1,"odmfuse.sh":1,"burn":1}
,"verify":{"fuse":1}
,"add":{"\u2011\u2011test":1}
,"performs":{"pre-burn":1}
,"verification":{"actually":1}
,"reports":{"results":1}
,"results":{"want":1}
,"re-enter":{"command":1}
,"without":{"\u2011\u2011test":1}
,"greater":{"confidence":1}
,"confidence":{"doing":1}
,"doing":{"correctly":1}
,"chip_id":{"pkc":1,"key.pem":1}
,".pem":{"file":1}
,"key.pem":{"dk_file":1,"--kek":1}
,"--kek":{"0-2":1}
,"0-2":{"kek":1}
,"--disable-jtag":{"device_name":1}
,"service":{"preparation":1}
,"preparation":{"jetson":1}
,"disable-jtag":{"chip_id":1}
,"development":{"module":1}
,"device_name":{"device":1,"mmcblk0p1":1}
,"shown":{"table":1}
,"table":{"device":1,"devices":1,"jetson":1}
,"quick":{"start":1}
,"start":{"placeholder":1}
,"placeholder":{"used":1}
,"flashing":{"boot":1,"utility":1,"factory-signed":1,"massflash":1}
,"procedures":{"sign":1,"described":1}
,"pkc-key":{"zero-key":1,"sbk-key":1,"signing":1}
,"zero-key":{"signing":1,"signed":1,"user":1}
,"separate":{"steps":1}
,"reflash":{"previously":1,"type":1}
,"previously":{"flashed":1}
,"determine":{"type":1}
,"type":{"signing":1,"type":1}
,"written":{"once":1}
,"later":{"reflashed":1}
,"reflashed":{"sbkpkc":1}
,"utility":{"uses":1}
,"procedure":{"jetson":1,"overlaps":1,"flashes":1}
,"separately":{"section":1}
,"binary":{"files":1}
,"placeholders":{"used":1,"commands":1,"described":1}
,"pkc_keyfile":{"rsa":1,"device_name":1,"sbk_keyfile":1}
,"sbk_keyfile":{"sbk":1,"device_name":1,"--user_key":1,"board_name":1}
,"user_keyfile":{"user":1,"device_name":1,"used":1}
,"place":{"jetson":1}
,"force":{"recovery":1}
,"jeton":{"xavier":1}
,"neither":{"pkc":1}
,"placed":{"bootloader":1}
,"user_key":{"command":1}
,"--user_key":{"user_keyfile":1}
,"none":{"pkc":1}
,"overlaps":{"subject":1}
,"subject":{"matter":1}
,"matter":{"sign":1}
,"nfs":{"using":1}
,"sbk-key":{"below":1}
,"below":{"flashes":1,"used":1}
,"-no-flash":{"--sign":1,"device_name":1}
,"--sign":{"keyfile":1,"0x21":1,"pkc_keyfile":1}
,"keyfile":{"device_name":1,"script":1,"--encrypt_key":1,"rsa":1}
,"--no-flash":{"--sign":1,"pkc_keyfile":1}
,"0x21":{"pkc":1}
,"bash":{"flashcmd.txt":1}
,"sure":{"press":1}
,"press":{"reset":1}
,"reset":{"recovery":1}
,"button":{"even":1}
,"even":{"jetson":1}
,"tools":{"kernel_flash":1}
,"kernel_flash":{"l4t_initrd_flash.sh":1}
,"l4t_initrd_flash.sh":{"--no-flash":1,"--flash-only":1}
,"board_name":{"rootdev":1,"value":1}
,"addition":{"placeholders":1}
,"variable":{"board":1}
,"modules":{"configurations":1}
,"configurations":{"topic":1}
,"rootdev":{"specifies":1,"step":1}
,"root":{"file":1}
,"system":{"located":1}
,"located":{"described":1,"folder":1}
,"basic":{"flash":1}
,"--flash-only":{"pkc_keyfile":1}
,"accessing":{"fuse":1}
,"means":{"access":1}
,"copy":{"top":1,"old":1}
,"top":{"linux_for_tegra":1}
,"tegrafuse.sh":{"script":1}
,"ubuntu@":{"target":1}
,"target\u2019s":{"fuses":1}
,"login":{"target":1}
,"display":{"fuses":1}
,"via":{"force":1}
,"odmfuseread.sh":{"0x18":1}
,"0x18":{"0x19":1}
,"tool":{"instructions":1,"part":1,"readme_massfuse.txt":1}
,"instructions":{"fusing":1,"using":1}
,"efficiently":{"factory":1}
,"part":{"secureboot":1}
,"folder":{"instructions":1}
,"readme_massfuse.txt":{"located":1}
,"building":{"flashing":1,"firmware":1,"massflash":1}
,"factory-signed":{"firmware":1}
,"firmware":{"blob":1,"factory":1}
,"implementations":{"flashing":1}
,"massflash":{"blob":1}
,"untrusted":{"environment":1}
,"signature":{"files":1,"file":1}
,"pair":{"file":1}
,"authenticating":{"file":1}
,"encrypt_keyfile":{"script":1,"pathname":1}
,"l4t_sign_image.sh":{"--file":1}
,"--file":{"filename":1}
,"filename":{"--chip":1,"kernel":1,".sig":1}
,"--chip":{"0x19":1}
,"--key":{"keyfile":1}
,"--encrypt_key":{"encrypt_keyfile":1}
,"replaces":{"file":1}
,"old":{"file":1}
,"stores":{"signature":1}
,".sig":{"directory":1}
,"authenticate":{"kernel":1}
,"sequence":{"using":1}
,"fill":{"key":1}
}
;Search.control.loadWordPairs(pairs);
