var pairs =
{
"display":{"configuration":1,"edid":1,"variable":1,"resolution":1,"supported":1,"environment":1,"boot":1,"monitors":1,"mode":1,"head":1,"heads":1,"whole":1,"including":1,"e.g":1,"hardware":1,"driver":1,"usb-c":1,"display":1,"initialization":1,"polls":1,"disabled":1}
,"configuration":{"bringup":1,"imp":1,"possible":1,"loosely":1,"command":1,"topic":1,"following":1,"device":1}
,"nvidia":{"jetson":1,"packaged":1,"fbcon-default-mode":1,"total_disp_bw_with_catchup":1,"total_disp_bw_without_catchup":1,"disp_emc_floor":1,"disp_min_hubclk":1,"total_win_fetch_slots":1,"total_cursor_fetch_slots":1,"win_fetch_meter_slots":1,"win_dvfs_watermark_values":1,"win_pipe_meter_values":1,"win_mempool_buffer_entries":1,"win_thread_groups":1,"cursor_fetch_meter_slots":1,"cursor_dvfs_watermark_values":1,"cursor_pipe_meter_values":1,"cursor_mempool_buffer_entries":1,"imp_win_mapping":1,"imp_head_mapping":1,"soc":1}
,"jetson":{"board":1,"agx":1,"tx2":1,"display":1}
,"board":{"support":1}
,"support":{"package":1,"configuration":1,"display":1,"proposed":1}
,"package":{"bsp":1}
,"bsp":{"supports":1}
,"supports":{"variety":1}
,"variety":{"modes":1}
,"modes":{"hdmi":1,"detailed":1,"display":1}
,"hdmi":{"monitors":1,"screen":1,"settings":1,"monitor":1,"mapped":1}
,"monitors":{"including":1,"due":1,"include":1}
,"including":{"cea":1,"catchup":1}
,"cea":{"modes":1}
,"detailed":{"timing":1}
,"timing":{"modes":1}
,"setting":{"hdmi":1,"implemented":1,"groups":1}
,"screen":{"resolution":1}
,"resolution":{"modified":1,"desired":1,"example":1}
,"modified":{"using":1}
,"using":{"xrandr":1,"instructions":1}
,"xrandr":{"utility":1,"--output":1,"display":1}
,"utility":{"randr":1,"update":1,"favorite":1,"script":1,"using":1,"lets":1,"outputs":1}
,"randr":{"protocol":1}
,"protocol":{"available":1}
,"https":{"www.x.org":1,"cgit.freedesktop.org":1}
,"www.x.org":{"releases":1}
,"releases":{"x11r7.5":1}
,"x11r7.5":{"doc":1}
,"doc":{"man":1}
,"man":{"man1":1}
,"man1":{"xrandr.1.html":1}
,"cgit.freedesktop.org":{"xorg":1}
,"xorg":{"proto":1}
,"proto":{"randrproto":1}
,"randrproto":{"tree":1}
,"tree":{"randrproto.txt":1,"support":1,"accordingly":1,"configuration":1,"jetson":1,"boot":1,"two":1,"property":1,"properties":1,"settings":1,"source":1,"entry":1}
,"change":{"default":1}
,"default":{"hdmi":1,"display":1,"false":1,"format_4bpp_packed":1,"pitch":1,"zero":1,"trying":1}
,"export":{"display":1}
,"obtain":{"applicable":1}
,"applicable":{"resolutions":1}
,"resolutions":{"list":1}
,"resulting":{"output":1}
,"output":{"shows":1,"lookup":1,"width":1,"height":1,"x-coordinate":1,"y-coordinate":1,"values":1,"settings":1}
,"shows":{"list":1,"values":1}
,"list":{"hdmi":1}
,"settings":{"connected":1,"window":1,"cursor":1,"sections":1,"calculated":1,"programmed":1,"directly":1}
,"switch":{"resolution":1}
,"desired":{"display":1,"resolution":1,"refresh":1}
,"--output":{"hdmi-0":1,"dp-0":1}
,"hdmi-0":{"--mode":1}
,"--mode":{"res":1}
,"dp-0":{"--mode":1,"--same-as":1,"--left-of":1,"--right-of":1}
,"res":{"desired":1,"--rate":1}
,"example":{"640x480":1,"suppose":1}
,"highest":{"rate":1}
,"rate":{"supported":1,"example":1,"hubclk":1,"pixels":1}
,"supported":{"specified":1,"refresh":1,"whether":1}
,"specified":{"mode":1,"instead":1,"output_lut_enable":1,"window":1,"per-window":1}
,"mode":{"automatically":1,"hdmi":1,"default":1,"720x480p@60hz":1,"parameters":1,"given":1,"possible":1}
,"automatically":{"chosen":1}
,"select":{"desired":1}
,"refresh":{"rate":1,"rates":1}
,"--rate":{"refresh_rate":1}
,"refresh_rate":{"desired":1}
,"rates":{"mode":1}
,"mirroring":{"extending":1}
,"extending":{"displays":1}
,"multiple":{"displays":1,"active":1}
,"displays":{"connected":1,"specified":1,"version":1,"output":1}
,"connected":{"choose":1}
,"choose":{"relative":1}
,"relative":{"position":1}
,"position":{"monitor":1}
,"monitor":{"hdmi":1,"left":1,"right":1,"specified":1}
,"execute":{"following":1,"command":1}
,"following":{"command":1,"head-to-window":1,"values":1,"device":1}
,"command":{"mirror":1,"extend":1,"place":1,"update":1,"line":1}
,"mirror":{"monitor":1}
,"--same-as":{"hdmi-0":1}
,"extend":{"display":1}
,"environment":{"placing":1}
,"placing":{"monitor":1}
,"left":{"hdmi":1,"colon":1,"corner":1}
,"--left-of":{"hdmi-0":1}
,"place":{"monitor":1}
,"right":{"hdmi":1}
,"--right-of":{"hdmi-0":1}
,"hard-coding":{"kernel":1}
,"kernel":{"display":1,"boot":1,"dtb":1,"directory":1}
,"boot":{"mode":1,"logs":1,"programs":1,"time":1}
,"linux":{"kernel":1}
,"logs":{"text-mode":1}
,"text-mode":{"login":1}
,"login":{"prompt":1}
,"prompt":{"fails":1}
,"fails":{"display":1}
,"due":{"known":1}
,"known":{"fbconsole":1,"working":1}
,"fbconsole":{"pixel":1,"displays":1}
,"pixel":{"clock":1}
,"clock":{"calculation":1,"value":1,"used":1}
,"calculation":{"issue":1}
,"affected":{"monitors":1}
,"acer":{"s277hk":1}
,"dell":{"24-inch":1}
,"24-inch":{"monitor":1}
,"viewsonic":{"vp2780":1}
,"asus":{"mx27uq":1,"vw220te":1}
,"samsung":{"8500":1}
,"8500":{"uhd":1}
,"nec":{"multisync":1}
,"multisync":{"lcd2070vx":1}
,"flatron":{"w2246":1}
,"packaged":{"utility":1}
,"update":{"kernel":1,"dtb":1,"values":1,"dts":1}
,"dtb":{"file":1,"tegra194-p2888-0001-p2822-0000.dtb":1,"files":1,"blob":1}
,"file":{"workaround":1,"may":1}
,"workaround":{"issue":1}
,"navigate":{"kernel":1}
,"top":{"linux_for_tegra":1,"generic":1}
,"linux_for_tegra":{"kernel":1}
,"nv-enable-hard-coded-kernel-boot-display-mode.sh":{"dtb":1}
,"flash":{"system":1,"new":1}
,"upon":{"successful":1}
,"successful":{"booting":1}
,"booting":{"fbconsole":1}
,"720x480p@60hz":{"cea":1}
,"files":{"available":1}
,"specify":{"different":1,"device":1,"input":1,"array":1,"window":1}
,"different":{"mode":1,"number":1,"type-c":1,"amounts":1}
,"open":{"utility":1}
,"favorite":{"editor":1}
,"properties":{"array":1,"specify":1,"explicitly":1,"operate":1}
,"array":{"update":1,"values":1}
,"values":{"left":1,"programmed":1,"specify":1,"calculated":1,"divided":1,"apply":1,"brief":1,"active":1,"described":1,"device":1,"compression":1,"displayed":1,"value":1,"delete":1}
,"colon":{"mode":1}
,"save":{"utility":1}
,"script":{"exit":1,"may":1}
,"exit":{"editor":1}
,"re-execute":{"utility":1}
,"instructions":{"update":1}
,"working":{"mode":1}
,"given":{"monitor":1,"certain":1}
,"instead":{"720x480p":1}
,"720x480p":{"mode":1}
,"fbcon-default-mode":{"node":1}
,"node":{"already":1,"path":1,"contains":1,"appears":1,"second":1,"applies":1,"add":1}
,"already":{"exists":1}
,"exists":{"script":1}
,"may":{"print":1,"omitted":1,"found":1,"connect":1,"incur":1}
,"print":{"error":1}
,"error":{"message":1}
,"message":{"safe":1}
,"safe":{"ignore":1}
,"ignore":{"message":1}
,"mapped":{"sor1":1}
,"sor1":{"platforms":1}
,"platforms":{"updated":1,"ignored":1}
,"updated":{"sor0":1,"assigned":1}
,"sor0":{"ensure":1}
,"ensure":{"node":1}
,"path":{"updated":1}
,"assigned":{"fbcon_node":1,"number":1,"window":1}
,"fbcon_node":{"variable":1}
,"variable":{"script":1}
,"nvimp_util":{"tool":1,"offline":1,"run":1,"fall":1,"allows":1,"command":1,"--head":1,"outputs":1,"prints":1,"100":1,"output":1,"writes":1}
,"tool":{"calculating":1}
,"calculating":{"memory":1}
,"memory":{"bandwidth":1,"layout":1,"controller":1}
,"bandwidth":{"particular":1,"constraints":1,"values":1,"display":1,"allocated":1}
,"particular":{"display":1,"head":1}
,"imp":{"stands":1,"maximum":1,"takes":1,"imp":1,"passes":1,"program":1,"values":1,"settings":1,"setting":1,"output":1,"device":1}
,"stands":{"mode":1}
,"possible":{"algorithm":1,"given":1,"expected":1}
,"algorithm":{"run":1}
,"run":{"determine":1,"imp":1,"tool":1,"nvimp_util":1}
,"whether":{"proposed":1,"head\u2019s":1,"hardware":1,"apply":1}
,"proposed":{"display":1}
,"certain":{"bandwidth":1,"input":1,"configurations":1}
,"expected":{"bandwidth":1}
,"programmed":{"hardware":1,"device":1,"specific":1}
,"hardware":{"support":1,"cursor":1,"window":1,"scan_column":1,"unit":1,"allows":1,"rotation":1,"nvidia":1}
,"loosely":{"refers":1}
,"refers":{"state":1}
,"state":{"active":1}
,"active":{"heads":1,"window":1,"raster":1,"display":1,"windows":1,"cursors":1,"cursor":1}
,"heads":{"windows":1}
,"windows":{"cursors":1,"arguments":1,"think":1}
,"general":{"several":1}
,"several":{"factors":1}
,"factors":{"impact":1,"account":1}
,"impact":{"imp":1}
,"maximum":{"downscaling":1}
,"downscaling":{"factor":1}
,"factor":{"active":1,"added":1}
,"window":{"surface":1,"raster":1,"option":1,"pixels":1,"specified":1,"lines":1,"always":1,"per-cursor":1,"cursor":1,"pipe":1,"output":1,"precomp":1,"mempool":1,"thread":1,"attached":1,"settings":1,"per":1}
,"surface":{"dimensions":1,"fetch":1}
,"dimensions":{"window":1}
,"raster":{"timings":1,"width":1,"height":1}
,"timings":{"particular":1}
,"head":{"imp":1,"per-head":1,"argument":1,"window":1}
,"takes":{"factors":1}
,"offline":{"utility":1}
,"lets":{"input":1}
,"input":{"display":1,"width":1,"height":1,"color":1,"x-coordinate":1,"y-coordinate":1,"configurations":1,"configuration":1,"formats":1,"parameters":1}
,"line":{"run":1,"options":1,"blanking":1,"look":1}
,"passes":{"utility":1}
,"outputs":{"bandwidth":1}
,"device":{"tree":1}
,"topic":{"explains":1}
,"explains":{"nvimp_util":1}
,"program":{"device":1,"displays":1}
,"sudo":{"permissions":1}
,"permissions":{"run":1}
,"options":{"nvimp_util":1,"apply":1,"may":1,"specified":1}
,"fall":{"two":1}
,"two":{"main":1,"groups":1,"simple":1}
,"main":{"categories":1,"interface":1}
,"categories":{"per-head":1,"system":1}
,"per-head":{"per-window":1,"options":1}
,"required":{"per-head":1,"per-window":1,"options":1,"specified":1,"iso":1,"satisfy":1,"hubclk":1}
,"option":{"name":1,"optional":1,"apply":1}
,"specifies":{"physical":1,"number":1,"whether":1,"dvfs":1,"thread":1}
,"physical":{"display":1,"hardware":1}
,"apply":{"head":1,"window":1,"cde":1,"display":1,"specific":1}
,"agx":{"xavier":1}
,"xavier":{"series":1}
,"tx2":{"series":1}
,"value":{"megahertz":1,"name":1,"per":1}
,"megahertz":{"head":1}
,"floating":{"point":1}
,"horizontal":{"active":1,"line":1}
,"width":{"pixels":1,"window":1}
,"vertical":{"active":1,"blanking":1}
,"height":{"lines":1,"window":1}
,"total":{"horizontal":1,"vertical":1,"required":1}
,"blanking":{"pixels":1,"lines":1}
,"optional":{"per-head":1,"subsequent":1,"per-window":1}
,"indicates":{"whether":1}
,"head\u2019s":{"hardware":1,"olut":1}
,"cursor":{"active":1,"pipe":1,"output":1,"mempool":1,"attached":1,"settings":1,"device":1,"nvidia":1,"node":1}
,"zero":{"false":1}
,"false":{"non-zero":1}
,"non-zero":{"true":1}
,"lower":{"case":1}
,"olut":{"output":1}
,"lookup":{"table":1}
,"table":{"enabled":1,"present":1,"lists":1}
,"number":{"entries":1,"nvimp_util":1,"fetch":1,"mempool":1,"threads":1,"windows":1,"cursors":1,"heads":1,"imp":1,"corresponds":1}
,"entries":{"olut":1,"allocated":1}
,"output_lut_enable":{"true":1}
,"257":{"1025":1}
,"per-window":{"options":1,"per-cursor":1,"values":1}
,"omitted":{"completely":1}
,"completely":{"required":1}
,"subsequent":{"table":1}
,"applies":{"corresponding":1,"jetson":1}
,"corresponding":{"head":1,"parameter":1,"device":1}
,"argument":{"window":1}
,"always":{"owned":1}
,"owned":{"head":1}
,"--format":{"str":1}
,"color":{"format":1}
,"format":{"window\u0027s":1}
,"window\u0027s":{"surface":1,"upper":1}
,"--surface":{"str":1}
,"describes":{"memory":1}
,"layout":{"window\u0027s":1}
,"x-coordinate":{"window\u0027s":1,"surface":1}
,"upper":{"left":1}
,"corner":{"active":1}
,"y-coordinate":{"window\u0027s":1,"surface":1}
,"fetch":{"offset":1,"entire":1,"slots":1,"slot":1,"dram":1}
,"offset":{"fetch":1}
,"entire":{"surface":1}
,"scan_column":{"rotation":1}
,"rotation":{"enabled":1,"done":1}
,"enabled":{"window":1,"nvida":1}
,"cde":{"compression":1}
,"compression":{"window\u0027s":1,"setting":1}
,"true":{"default":1}
,"lists":{"available":1,"output":1}
,"available":{"command-line":1}
,"command-line":{"arguments":1}
,"arguments":{"short":1,"immediately":1}
,"short":{"description":1}
,"version":{"number":1}
,"multi-head":{"multi-window":1}
,"multi-window":{"input":1}
,"allows":{"specify":1,"memory":1}
,"configurations":{"contain":1}
,"contain":{"multiple":1,"different":1}
,"immediately":{"follow":1}
,"follow":{"\u2011\u2011head":1}
,"\u2011\u2011head":{"\u2011\u2011window":1}
,"\u2011\u2011window":{"option":1}
,"suppose":{"want":1,"run":1}
,"want":{"specify":1}
,"head-to-window":{"mapping":1}
,"head0":{"window0":1}
,"window0":{"window1":1}
,"head1":{"window2":1}
,"window2":{"window3":1}
,"head2":{"window4":1}
,"window4":{"window5":1}
,"look":{"represents":1,"above":1}
,"represents":{"options":1}
,"--head":{"--window":1}
,"--window":{"--window":1}
,"calculated":{"imp":1,"certain":1}
,"divided":{"three":1}
,"three":{"categories":1}
,"system":{"per-window":1,"values":1,"output":1}
,"per-cursor":{"system":1,"values":1}
,"whole":{"per-window":1}
,"specific":{"window":1,"cursor":1,"input":1}
,"brief":{"description":1}
,"iso":{"bandwidth":1}
,"catchup":{"factor":1}
,"added":{"margin":1}
,"margin":{"cover":1}
,"cover":{"events":1}
,"events":{"disrupt":1}
,"disrupt":{"instantaneous":1}
,"instantaneous":{"bandwidth":1}
,"allocated":{"display":1,"active":1,"window":1,"cursor":1}
,"e.g":{"dvfs":1}
,"emc":{"floor":1}
,"floor":{"required":1}
,"satisfy":{"various":1}
,"various":{"latency":1}
,"latency":{"allowance":1,"trigger":1}
,"allowance":{"constraints":1}
,"minimum":{"required":1}
,"hubclk":{"rate":1,"main":1}
,"interface":{"clock":1}
,"used":{"isohub":1}
,"isohub":{"isohub":1,"hardware":1,"precomp":1}
,"unit":{"fetches":1}
,"fetches":{"surfaces":1}
,"surfaces":{"dram":1}
,"dram":{"buffers":1,"window":1}
,"buffers":{"drains":1}
,"drains":{"nvdisplay":1}
,"nvdisplay":{"pipeline":1}
,"aggregate":{"number":1}
,"slots":{"allocated":1,"described":1}
,"think":{"fetch":1}
,"slot":{"time":1,"allocated":1}
,"time":{"slot":1,"seamless":1}
,"pipe":{"fetch":1,"assigned":1,"current":1}
,"described":{"below":1,"above":1}
,"cursors":{"individual":1}
,"individual":{"cursor":1}
,"dvfs":{"watermark":1,"event":1}
,"watermark":{"values":1,"threshold":1}
,"current":{"amount":1,"release":1}
,"amount":{"buffering":1,"metering":1}
,"buffering":{"above":1,"entries":1}
,"above":{"watermark":1,"console":1,"global":1,"example":1}
,"threshold":{"display":1}
,"controller":{"schedule":1}
,"schedule":{"dvfs":1}
,"event":{"necessary":1}
,"metering":{"applied":1}
,"applied":{"window":1}
,"precomp":{"side":1,"unsigned":1}
,"side":{"effectively":1}
,"effectively":{"controls":1}
,"controls":{"rate":1,"semi-planar":1}
,"pixels":{"flow":1}
,"flow":{"isohub":1}
,"unsigned":{"fixed":1}
,"fixed":{"point":1}
,"point":{"u8.8":1}
,"u8.8":{"value":1}
,"mempool":{"buffering":1,"entry":1}
,"entry":{"128":1,"look":1}
,"128":{"bytes":1,"505":1}
,"bytes":{"wide":1}
,"thread":{"group":1}
,"group":{"assigned":1,"potentially":1,"nodes":1}
,"potentially":{"contain":1}
,"threads":{"number":1,"controls":1}
,"semi-planar":{"planar":1}
,"planar":{"input":1}
,"formats":{"supported":1}
,"done":{"combination":1}
,"combination":{"certain":1}
,"prints":{"output":1}
,"console":{"values":1}
,"driver":{"reads":1}
,"reads":{"values":1}
,"programs":{"hardware":1}
,"100":{"480":1}
,"480":{"640":1}
,"640":{"128":1,"480":1}
,"505":{"257":1}
,"format_4bpp_packed":{"blocklinear":1}
,"blocklinear":{"640":1,"1280":1}
,"74.25":{"1280":1}
,"1280":{"720":1}
,"720":{"370":1,"1280":1}
,"370":{"257":1}
,"format_1bpp_packed":{"blocklinear":1}
,"pclkmhz":{"100":1,"74.25":1}
,"h_active":{"480":1,"1280":1}
,"v_active":{"640":1,"720":1}
,"h_blank":{"128":1,"370":1}
,"v_blank":{"505":1}
,"output_lut_size":{"257":1}
,"color_format":{"format_4bpp_packed":1,"format_1bpp_packed":1}
,"surface_format":{"blocklinear":1}
,"sizeinx":{"640":1,"1280":1}
,"sizeiny":{"480":1,"720":1}
,"sizeoutx":{"640":1,"1280":1}
,"sizeouty":{"480":1,"720":1}
,"parameters":{"parsing":1}
,"parsing":{"done":1}
,"attached":{"head":1}
,"requested":{"mode":1}
,"add":{"following":1}
,"global":{"settings":1}
,"total_disp_bw_with_catchup":{"1497231":1}
,"total_disp_bw_without_catchup":{"1361119":1}
,"disp_emc_floor":{"102000000":1}
,"disp_min_hubclk":{"28073088":1}
,"total_win_fetch_slots":{"bits":1}
,"total_cursor_fetch_slots":{"bits":1}
,"imp_win_mapping":{"bits":1,"nvidia":1}
,"win_fetch_meter_slots":{"bits":1}
,"win_dvfs_watermark_values":{"28274":1}
,"28274":{"16893":1}
,"16893":{"26794":1}
,"win_pipe_meter_values":{"256":1}
,"256":{"256":1}
,"win_mempool_buffer_entries":{"2399":1}
,"2399":{"1269":1}
,"1269":{"280":1}
,"win_thread_groups":{"bits":1}
,"imp_head_mapping":{"bits":1,"properties":1}
,"cursor_fetch_meter_slots":{"bits":1}
,"cursor_dvfs_watermark_values":{"9135":1}
,"9135":{"2762":1}
,"cursor_pipe_meter_values":{"256":1}
,"cursor_mempool_buffer_entries":{"798":1}
,"798":{"241":1}
,"although":{"nvimp_util":1}
,"implemented":{"t194":1}
,"t194":{"platforms":1}
,"displayed":{"above":1}
,"sections":{"copied":1}
,"copied":{"device":1}
,"groups":{"nodes":1,"imp":1,"contained":1}
,"nodes":{"involved":1,"number":1}
,"host1x":{"disp_imp_table":1}
,"contains":{"groups":1,"imp":1}
,"num_settings":{"property":1}
,"property":{"specifies":1,"names":1}
,"contained":{"within":1}
,"within":{"node":1}
,"disp_imp_table":{"disp_imp_settings_":1,"first":1,"node":1,"disp_imp_table":1}
,"corresponds":{"order":1}
,"order":{"node":1}
,"appears":{"host1x":1}
,"first":{"node":1}
,"disp_imp_settings_":{"node":1}
,"names":{"corresponding":1,"nvimp_util":1}
,"parameter":{"names":1}
,"writes":{"console":1}
,"per":{"window":1,"cursor":1}
,"explicitly":{"specify":1}
,"operate":{"64-bit":1}
,"64-bit":{"numbers":1}
,"simple":{"approaches":1}
,"approaches":{"copy":1}
,"copy":{"values":1}
,"edit":{"soc-level":1}
,"soc-level":{"imp":1}
,"series":{"soc-level":1,"source":1,"insert":1,"current":1}
,"source":{"file":1}
,"$top":{"hardware":1}
,"soc":{"t19x":1,"t18x":1}
,"t19x":{"kernel-dts":1}
,"kernel-dts":{"tegra194-soc":1,"tegra186-soc":1}
,"tegra194-soc":{"tegra194-soc-disp-imp.dtsi":1}
,"t18x":{"kernel-dts":1}
,"tegra186-soc":{"tegra186-soc-disp-imp.dtsi":1}
,"delete":{"comment":1}
,"comment":{"existing":1,"include":1}
,"existing":{"disp_imp_table":1}
,"create":{"dtsi":1}
,"dtsi":{"fragment":1}
,"fragment":{"appropriate":1,"tegra194-soc-base.dtsi":1,"tegra186-soc-base.dtsi":1}
,"appropriate":{"disp_imp_table":1}
,"insert":{"fragment":1}
,"tegra194-soc-base.dtsi":{"comment":1}
,"include":{"top":1}
,"generic":{"tegra194-soc-disp-imp.dtsi":1,"tegra186-soc-disp-imp.dtsi":1}
,"tegra194-soc-disp-imp.dtsi":{"file":1}
,"tegra186-soc-base.dtsi":{"comment":1}
,"tegra186-soc-disp-imp.dtsi":{"file":1}
,"status":{"okay":1,"increase":1}
,"dts":{"rebuild":1}
,"rebuild":{"flash":1}
,"new":{"dtb":1}
,"blob":{"onto":1}
,"onto":{"device":1}
,"seamless":{"display":1}
,"initialization":{"bootloader":1}
,"bootloader":{"enabled":1,"display":1}
,"nvida":{"jetson":1}
,"polls":{"msec":1}
,"msec":{"default":1}
,"trying":{"detect":1}
,"detect":{"hpd":1}
,"hpd":{"asserted":1,"status":1}
,"asserted":{"sink":1}
,"sink":{"different":1}
,"type-c":{"downstream":1,"ports":1,"delay":1}
,"downstream":{"devices":1}
,"devices":{"may":1}
,"connect":{"type-c":1}
,"ports":{"galen":1}
,"galen":{"cables":1}
,"cables":{"adapters":1}
,"adapters":{"hubs":1}
,"hubs":{"may":1}
,"incur":{"different":1}
,"amounts":{"latency":1}
,"trigger":{"handshake":1}
,"handshake":{"process":1}
,"process":{"needed":1}
,"needed":{"drive":1}
,"drive":{"type-c":1}
,"delay":{"non-deterministic":1}
,"non-deterministic":{"adding":1}
,"adding":{"loop":1}
,"loop":{"poll":1}
,"poll":{"hpd":1}
,"increase":{"boot":1}
,"disabled":{"avoid":1}
,"avoid":{"inconsistent":1}
,"inconsistent":{"behavior":1}
}
;Search.control.loadWordPairs(pairs);
