var pairs =
{
"kernel":{"boot":1,"development":1,"based":1,"includes":1,"reduce":1,"respect":1,"image":1,"version":1,"driver":1,"hacks":1}
,"boot":{"time":1,"kernel":1,"scripts":1,"configurations":1,"asynchronously":1,"hid":1}
,"time":{"optimization":1,"customize":1,"initialize":1,"thereby":1,"storage":1,"configure":1,"need":1,"modifying":1,"reduce":1,"u-boot":1,"filesystem":1,"disable":1,"modularize":1}
,"nvidia":{"jetson":1,"platform":1,"soc":1,"tegra":1,"tegra-rtc":1}
,"jetson":{"linux":1,"tx1":1,"soc":1,"nano":1,"agx":1,"tx2":1,"tx2i":1}
,"linux":{"driver":1}
,"driver":{"package":1,"thread":1,"follows":1}
,"package":{"l4t":1}
,"l4t":{"provides":1,"default":1}
,"provides":{"generic":1}
,"generic":{"boot":1}
,"development":{"product":1,"needs":1}
,"product":{"decrease":1}
,"decrease":{"kernel":1,"boot":1}
,"customize":{"provided":1}
,"provided":{"kernel":1}
,"based":{"requirements":1,"development":1}
,"requirements":{"product":1}
,"includes":{"default":1}
,"default":{"configuration":1,"kernel":1}
,"configuration":{"enables":1,"takes":1,"tegra21_defconfig":1,"root":1,"file":1,"examine":1}
,"enables":{"supported":1,"out-of-the":1}
,"supported":{"hardware":1}
,"hardware":{"features":1,"support":1,"nvidia":1}
,"features":{"searches":1,"storage":1,"mostly":1}
,"searches":{"available":1}
,"available":{"devices":1,"default":1}
,"devices":{"boot":1,"takes":1,"need":1,"edit":1}
,"scripts":{"enables":1}
,"out-of-the":{"box":1}
,"box":{"support":1}
,"support":{"widest":1,"takes":1}
,"widest":{"possible":1}
,"possible":{"variety":1}
,"variety":{"controllers":1}
,"controllers":{"features":1}
,"storage":{"devices":1,"network":1,"device":1}
,"flexibility":{"comes":1,"may":1}
,"comes":{"cost":1}
,"takes":{"time":1,"seconds":1}
,"enabling":{"software":1}
,"software":{"features":1}
,"mostly":{"advanced":1}
,"advanced":{"peripheral":1}
,"peripheral":{"bus":1}
,"bus":{"apb":1}
,"apb":{"takes":1}
,"scanning":{"attached":1}
,"attached":{"storage":1}
,"network":{"devices":1}
,"thereby":{"delaying":1}
,"delaying":{"execution":1}
,"execution":{"final":1}
,"final":{"operating":1}
,"operating":{"system":1}
,"constrained":{"pre-configured":1}
,"pre-configured":{"systems":1}
,"systems":{"flexibility":1}
,"may":{"necessary":1,"know":1,"review":1}
,"necessary":{"system":1}
,"system":{"designer":1,"boot":1,"running":1,"turned":1,"concerned":1}
,"designer":{"may":1}
,"know":{"ahead":1}
,"ahead":{"time":1}
,"device":{"contains":1,"tree":1}
,"contains":{"required":1}
,"required":{"files":1,"flashing":1,"once":1,"configurations":1,"during":1}
,"files":{"certain":1}
,"certain":{"devices":1}
,"need":{"initialized":1,"enable":1}
,"initialized":{"kernel":1}
,"reduce":{"system":1,"bottleneck":1,"volume":1,"compile-time":1,"boot":1}
,"configure":{"kernel":1,"whether":1}
,"respect":{"constraints":1}
,"tx1":{"system":1}
,"running":{"l4t":1,"flash.sh":1}
,"seconds":{"cold":1}
,"cold":{"power-on":1}
,"power-on":{"begin":1}
,"begin":{"showing":1}
,"showing":{"login":1}
,"login":{"prompt":1}
,"prompt":{"following":1}
,"following":{"optimization":1,"differences":1,"configuration":1,"modifications":1,"running":1,"topics":1,"configurations":1}
,"optimization":{"techniques":1}
,"techniques":{"applied":1}
,"applied":{"process":1}
,"process":{"reduced":1}
,"reduced":{"approximately":1,"ram":1}
,"approximately":{"three":1}
,"three":{"seconds":1}
,"tree":{"nodes":1,"entries":1,"directory":1}
,"using":{"controller":1}
,"controller":{"jetson":1}
,"soc":{"disable":1,"t18x":1}
,"disable":{"device":1,"rtc":1,"console":1,"audio":1,"debugging":1}
,"nodes":{"device":1}
,"entries":{"device":1}
,"directory":{"available":1}
,"top":{"hardware":1,"tegra_for_linux":1}
,"platform":{"t18x":1,"configuration":1}
,"dtb":{"flashed":1}
,"flashed":{"available":1}
,"t18x":{"quill":1}
,"quill":{"kernel-dts":1}
,"kernel-dts":{"tegra186-quill-p3310-1000-a00-00-base.dts":1}
,"real-time":{"clock":1,"clocks":1}
,"two":{"real-time":1}
,"clocks":{"rtc":1}
,"rtc":{"enabled":1,"fastest":1,"system":1,"work":1,"however":1,"disabling":1,"speed":1,"disabled":1}
,"enabled":{"default":1}
,"tegra":{"rtc":1}
,"pmic":{"rtc":1}
,"enable":{"none":1,"rtc":1}
,"none":{"based":1}
,"needs":{"aware":1}
,"aware":{"following":1}
,"fastest":{"response":1}
,"response":{"cannot":1,"transfer":1}
,"cannot":{"work":1}
,"work":{"backup":1}
,"backup":{"rtc":1,"time":1}
,"however":{"slow":1}
,"slow":{"response":1}
,"transfer":{"average":1}
,"average":{"i2c":1}
,"shutdown":{"system":1}
,"concerned":{"backup":1}
,"disabling":{"rtc":1}
,"speed":{"boot":1}
,"remove":{"following":1,"specification":1,"u\u2011boot":1,"boot":1}
,"tegra21_defconfig":{"file":1}
,"add":{"following":1,"probe_type":1}
,"disabled":{"dts":1}
,"dts":{"file":1}
,"file":{"follows":1,"system":1,"p3448-0000.conf":1,"p2972-0000.conf.com":1,"included":1,"p2771-0000-devkit.conf":1,"identify":1}
,"compatible":{"nvidia":1}
,"reg":{"0x00000000":1}
,"0x00000000":{"0x00000003":1,"0x00000005":1}
,"0x00000003":{"0x00000002":1}
,"0x00000002":{"0x0000009b":1}
,"interrupts":{"0x00000000":1}
,"0x00000005":{"0x00000002":1}
,"status":{"disabled":1}
,"environment":{"configuration":1,"variable":1}
,"optimize":{"boot":1}
,"modifying":{"environment":1}
,"root":{"file":1}
,"console":{"uart":1,"printing":1,"ttys0":1,"ttytcu0":1,"logs":1}
,"printing":{"uart":1}
,"uart":{"major":1,"removing":1,"follow":1}
,"major":{"bottleneck":1}
,"bottleneck":{"kernel":1,"reduce":1}
,"volume":{"console":1,"printing":1}
,"removing":{"console":1}
,"ttys0":{"platform":1,"file":1}
,"follow":{"instructions":1}
,"nano":{"devices":1}
,"edit":{"platform":1,"p2771-000.conf.common":1,"common":1,"line":1}
,"p3448-0000.conf":{"remove":1}
,"specification":{"console":1}
,"agx":{"xavier":1}
,"xavier":{"series":1}
,"series":{"edit":1}
,"p2972-0000.conf.com":{"remove":1}
,"tx2":{"series":1,"p2771-3489-ucm1.conf":1}
,"p2771-000.conf.common":{"remove":1}
,"included":{"platform":1}
,"p2771-0000-devkit.conf":{"jetson":1}
,"p2771-3489-ucm1.conf":{"jetson":1}
,"review":{"console":1}
,"logs":{"framebuffer":1}
,"framebuffer":{"console":1}
,"secondary":{"bootloader":1}
,"u\u2011boot":{"secondary":1}
,"bootloader":{"remove":1}
,"u-boot":{"following":1}
,"modifications":{"required":1}
,"common":{"configuration":1}
,"tegra_for_linux":{"p2771-000.conf":1}
,"whether":{"u-boot":1}
,"either":{"following":1}
,"variable":{"use_uboot":1}
,"line":{"below":1}
,"below":{"use_uboot":1}
,"compile-time":{"configuration":1}
,"examine":{"generated":1,"required":1}
,"generated":{"configuration":1}
,"identify":{"configurations":1,"ones":1}
,"configurations":{"required":1,"defined":1,"drivers":1,"verify":1,"modules":1,"follows":1}
,"once":{"required":1}
,"defined":{"identify":1}
,"ones":{"boot":1}
,"asynchronously":{"configurations":1,"separate":1}
,"drivers":{"probe":1,"loaded":1,"required":1}
,"probe":{"executed":1,"feature":1}
,"executed":{"asynchronously":1}
,"separate":{"thread":1}
,"thread":{"instead":1}
,"instead":{"main":1}
,"main":{"initial":1}
,"initial":{"thread":1}
,"additionally":{"examine":1}
,"verify":{"programmed":1}
,"programmed":{"modules":1}
,"modules":{"drivers":1}
,"loaded":{"called":1,"kernel":1}
,"called":{"drivers":1}
,"image":{"reduced":1}
,"ram":{"space":1}
,"space":{"available":1}
,"topics":{"provide":1}
,"provide":{"examples":1}
,"examples":{"conditions":1}
,"asynchronous":{"probe":1}
,"feature":{"available":1}
,"version":{"3.18":1}
,"https":{"lkml.org":1}
,"lkml.org":{"lkml":1}
,"lkml":{"2015":1}
,"2015":{"576":1}
,"move":{"driver":1}
,"probe_type":{"driver":1}
,"static":{"struct":1}
,"struct":{"platform_driver":1}
,"platform_driver":{"sdhci_tegra_driver":1}
,".name":{"sdhci-tegra":1}
,".of_match_table":{"sdhci_tegra_dt_match":1}
,".pm":{"sdhci_pltfm_pmops":1}
,".probe_type":{"probe_prefer_asynchronous":1}
,".probe":{"sdhci_tegra_probe":1}
,".remove":{"sdhci_tegra_remove":1}
,".shutdown":{"sdhci_tegra_shutdown":1}
,"filesystem":{"modify":1}
,"modify":{"following":1}
,"audio":{"codec":1,"configurations":1}
,"codec":{"requires":1}
,"requires":{"time":1}
,"initialize":{"eliminate":1}
,"eliminate":{"initialization":1}
,"initialization":{"time":1}
,"modularize":{"kernel":1,"drivers":1}
,"during":{"boot":1}
,"hid":{"net":1}
,"net":{"qspi":1}
,"qspi":{"usb":1}
,"debugging":{"kernel":1}
,"hacks":{"production":1}
,"production":{"configuration":1}
,"example":{"ftrace":1}
,"ftrace":{"tracer":1}
,"tracer":{"kmemleak":1}
}
;Search.control.loadWordPairs(pairs);
