var pairs =
{
"following":{"diagram":1,"sections":1}
,"diagram":{"shows":1}
,"shows":{"nvidia":1}
,"nvidia":{"jetson":1,"drivers":1,"tensorrt":1,"sdk":1,"cuda":1,"visionworks":1,"optimized":1,"userspace":1,"accelerated":1,"nsight":1}
,"jetson":{"board":1,"user":1,"platform":1,"device\u2019s":1,"developer":1,"bsp":1,"download":1,"driver":1,"products":1,"development":1}
,"board":{"support":1}
,"support":{"package":1,"scripts":1,"cuda":1,"flexible":1}
,"package":{"bsp":1,"computer":1}
,"bsp":{"architecture":1,"cuda":1}
,"sections":{"describe":1}
,"describe":{"components":1}
,"components":{"module":1,"names":1,"separate":1}
,"module":{"components":1}
,"names":{"links":1}
,"links":{"component\u2019s":1,"additional":1}
,"component\u2019s":{"primary":1}
,"primary":{"documentation":1,"web":1}
,"documentation":{"either":1,"may":1,"web":1,"provides":1}
,"either":{"developer":1}
,"developer":{"guide":1,"kit":1,"tools":1}
,"guide":{"elsewhere":1}
,"elsewhere":{"components":1}
,"separate":{"links":1}
,"additional":{"description":1}
,"linux":{"kernel":1,"host":1}
,"kernel":{"unix-like":1,"mostly":1,"multimedia":1,"operations":1}
,"unix-like":{"computer":1}
,"computer":{"operating":1,"vision":1,"supports":1}
,"operating":{"system":1}
,"system":{"kernel":1,"chip":1}
,"mostly":{"used":1}
,"used":{"mobile":1,"optimize":1}
,"mobile":{"devices":1}
,"sample":{"root":1,"source":1}
,"root":{"filesystem":1,"filesystems":1}
,"filesystem":{"derived":1,"ubuntu":1}
,"derived":{"ubuntu":1}
,"ubuntu":{"sample":1,"distribution":1,"host":1}
,"distribution":{"helps":1}
,"helps":{"create":1,"improve":1}
,"create":{"root":1}
,"filesystems":{"different":1}
,"different":{"configurations":1}
,"toolchain":{"development":1}
,"development":{"tools":1,"package":1,"better":1,"multimedia":1,"jetson":1,"platform":1}
,"tools":{"chained":1,"scripts":1,"assist":1}
,"chained":{"together":1}
,"together":{"stages":1}
,"stages":{"runs":1}
,"runs":{"various":1,"linux":1}
,"various":{"architectures":1}
,"bootloader":{"boot":1}
,"boot":{"software":1,"initializing":1}
,"software":{"boot":1,"development":1,"library":1}
,"initializing":{"system":1}
,"sources":{"source":1}
,"source":{"code":1}
,"code":{"kernel":1,"applications":1,"developing":1}
,"multimedia":{"applications":1,"api":1}
,"user":{"space":1,"interface":1}
,"space":{"drivers":1}
,"drivers":{"provides":1,"run":1}
,"provides":{"nvidia":1,"high-performance":1,"samples":1,"opencv":1,"collection":1,"higher-level":1,"parallel":1,"detailed":1,"details":1}
,"run":{"userspace":1,"faster":1}
,"flashing":{"support":1,"system":1}
,"scripts":{"tools":1,"associated":1}
,"associated":{"tools":1}
,"assist":{"flashing":1}
,"applications":{"sample":1,"jetson":1,"used":1,"provides":1}
,"developing":{"embedded":1}
,"embedded":{"applications":1,"systems":1}
,"artificial":{"intelligence":1}
,"tensorrt":{"provides":1,"opencv4tegra":1}
,"high-performance":{"neural":1}
,"neural":{"network":1,"networks":1}
,"network":{"inference":1,"library":1}
,"inference":{"engine":1,"jetson":1}
,"engine":{"production":1}
,"production":{"deployment":1}
,"deployment":{"deep":1,"support":1}
,"deep":{"learning":1,"neural":1}
,"learning":{"applications":1}
,"optimize":{"validate":1}
,"validate":{"deploy":1}
,"deploy":{"trained":1}
,"trained":{"neural":1}
,"networks":{"inference":1}
,"platform":{"multimedia":1,"contains":1,"window":1}
,"api":{"provides":1,"based":1,"rendering":1,"full-function":1,"gives":1,"mmapi":1,"includes":1,"extensions":1,"framework":1,"debugging":1}
,"samples":{"engine":1,"demonstrate":1,"designed":1}
,"sdk":{"manager":1}
,"manager":{"installs":1}
,"installs":{"component":1}
,"component":{"part":1}
,"part":{"low-level":1,"multimedia":1}
,"low-level":{"multimedia":1,"api":1}
,"cudnn":{"nvidia":1,"tensorrt":1}
,"cuda":{"deep":1,"toolkit":1,"object":1,"applications":1}
,"visionworks":{"nvidia":1,"software":1}
,"vision":{"image":1,"programming":1}
,"image":{"processing":1}
,"opencv":{"provides":1,"nvidia":1,"implementation":1,"documentation":1}
,"optimized":{"specifically":1}
,"specifically":{"jetson":1}
,"contains":{"jetson-specific":1}
,"jetson-specific":{"optimizations":1}
,"optimizations":{"enable":1}
,"enable":{"run":1}
,"faster":{"opencv":1}
,"may":{"found":1}
,"found":{"opencv":1}
,"web":{"site":1}
,"site":{"general":1}
,"general":{"information":1}
,"information":{"opencv.org":1}
,"opencv.org":{"primary":1}
,"programming":{"interface":1}
,"interface":{"vpi":1,"khronos":1,"command":1}
,"vpi":{"software":1}
,"library":{"implements":1,"api":1}
,"implements":{"computer":1}
,"processing":{"algorithms":1,"hardware":1,"cuda":1}
,"algorithms":{"using":1}
,"using":{"jetson":1}
,"device\u2019s":{"gpu":1}
,"gpu":{"image":1,"developers":1}
,"hardware":{"acceleration":1,"blocks":1}
,"libargus":{"low-level":1,"imaging":1}
,"based":{"camera":1,"wayland":1}
,"camera":{"core":1}
,"core":{"stack":1}
,"collection":{"apis":1,"lower-level":1}
,"apis":{"supports":1,"opengl":1,"support":1,"lower-level":1}
,"supports":{"flexible":1,"jetson":1}
,"flexible":{"application":1}
,"application":{"development":1,"framework":1,"execution":1,"performance":1}
,"better":{"control":1}
,"control":{"underlying":1}
,"underlying":{"hardware":1,"native":1}
,"nvdc-drm":{"nvidia":1}
,"userspace":{"driver":1}
,"driver":{"display":1,"nvidia":1,"installed":1}
,"accelerated":{"driver":1,"weston":1}
,"weston":{"nvidia":1,"compositor":1}
,"compositor":{"based":1}
,"wayland":{"protocol":1}
,"toolkit":{"ubuntu":1,"host":1,"jetson":1}
,"host":{"cross":1,"computer":1}
,"cross":{"deployment":1}
,"kit":{"running":1}
,"running":{"jetson":1}
,"opengl":{"open":1,"cross-platform":1,"openvg":1,"opengl":1,"graphics":1}
,"open":{"graphics":1}
,"graphics":{"library":1,"embedded":1,"debugs":1,"programs":1}
,"rendering":{"vector":1,"apis":1}
,"vector":{"graphics":1}
,"cross-platform":{"api":1}
,"full-function":{"graphics":1}
,"egl":{"interface":1}
,"khronos":{"rendering":1}
,"openvg":{"underlying":1}
,"native":{"platform":1}
,"window":{"system":1}
,"vulkan":{"low":1}
,"low":{"level":1}
,"level":{"api":1}
,"gives":{"direct":1}
,"direct":{"access":1}
,"access":{"gpu":1}
,"mmapi":{"collection":1,"includes":1,"developers":1,"separately":1}
,"lower-level":{"apis":1,"multimedia":1}
,"imaging":{"applications":1}
,"buffer":{"utility":1,"allocation":1}
,"utility":{"buffer":1}
,"allocation":{"management":1}
,"management":{"sharing":1}
,"nvosd":{"on-screen":1}
,"on-screen":{"display":1}
,"v4l2":{"api":1}
,"extensions":{"video":1}
,"video":{"converter":1}
,"converter":{"decoder":1}
,"decoder":{"encoder":1}
,"framework":{"optional":1,"wish":1,"gstreamer":1,"provides":1,"installed":1,"alternative":1}
,"includes":{"samples":1}
,"demonstrate":{"image":1}
,"object":{"detection":1}
,"detection":{"classification":1}
,"classification":{"cudnn":1}
,"opencv4tegra":{"usage":1}
,"developers":{"custom":1}
,"custom":{"framework":1}
,"wish":{"avoid":1}
,"avoid":{"framework":1}
,"separately":{"downloaded":1}
,"downloaded":{"nvidia":1}
,"download":{"center":1,"jetson":1}
,"center":{"included":1}
,"included":{"download":1}
,"gstreamer":{"provides":1,"framework":1}
,"higher-level":{"multimedia":1}
,"parallel":{"capability":1}
,"capability":{"collection":1}
,"installed":{"download":1,"sdk":1}
,"alternative":{"multimedia":1}
,"nsight":{"systems":1,"compute":1,"graphics":1}
,"systems":{"profiles":1}
,"profiles":{"application":1,"kernel":1,"opengl":1}
,"execution":{"across":1}
,"across":{"multiple":1}
,"multiple":{"cpu":1}
,"cpu":{"cores":1}
,"cores":{"helps":1}
,"improve":{"application":1}
,"performance":{"identifying":1,"metrics":1}
,"identifying":{"slow":1}
,"slow":{"parts":1}
,"parts":{"code":1}
,"compute":{"interactively":1}
,"interactively":{"profiles":1}
,"operations":{"cuda":1}
,"detailed":{"performance":1}
,"metrics":{"api":1}
,"debugging":{"via":1}
,"via":{"user":1}
,"command":{"line":1}
,"line":{"tool":1}
,"debugs":{"profiles":1}
,"programs":{"console":1}
,"console":{"interface":1}
,"jetpack":{"sdk":1}
,"details":{"development":1}
,"designed":{"give":1}
,"give":{"hands-on":1}
,"hands-on":{"practical":1}
,"practical":{"examples":1}
,"examples":{"using":1}
}
;Search.control.loadWordPairs(pairs);
