var pairs =
{
"accelerated":{"gstreamer":1,"solution":1,"decode":1,"encode":1,"supported":1,"h.264":1}
,"applies":{"jetson":1}
,"jetson":{"xavier":1,"nano":1,"agx":1,"tx2":1,"linux":1,"platforms":1}
,"xavier":{"jetson":1,"series":1,"support":1}
,"nano":{"jetson":1,"nvidia":1,"enable-low-outbuffer":1}
,"agx":{"xavier":1}
,"series":{"jetson":1,"devices":1,"supported":1,"h265":1,"capture":1,"support":1,"using":1}
,"tx2":{"series":1,"jetson":1,"tx2i":1,"hdmi":1}
,"topic":{"user":1,"audio":1,"sensor":1}
,"user":{"guide":1}
,"guide":{"gstreamer":1}
,"gstreamer":{"version":1,"source":1,"1.0":1,"pipelines":1,"pipeline":1,"package":1,"build":1,"using":1,"example":1,"manually":1,"available":1,"building":1,"options":1,"elements":1,"element":1,"supports":1}
,"version":{"1.0":1,"1.14":1,"following":1,"0.10":1,"3.3":1,"section":1,"gstreamer":1,"example":1,"1.16.2":1,"directory":1,"version":1,"number":1}
,"1.0":{"1.14":1,"apply":1,"includes":1,"recommended":1,"currently":1}
,"1.14":{"based":1}
,"based":{"accelerated":1,"jpeg":1,"gstreamer":1,"operation":1,"opencv":1,"videosink":1,"low":1,"exposure":1}
,"solution":{"included":1}
,"included":{"nvidia":1}
,"nvidia":{"jetson":1,"plugins":1,"proprietary":1,"accelerated":1,"v4l2":1,"egl":1,"video":1,"input":1,"formats":1,"cuda":1,"gstreamer-1.0":1}
,"linux":{"driver":1}
,"driver":{"package":1,"sensor":1,"programming":1}
,"package":{"l4t":1,"release":1,"libnvsample_cudaprocess.so":1,"usb":1}
,"references":{"gstreamer":1}
,"apply":{"gstreamer":1,"specified":1}
,"gstreamer-1.0":{"installation":1,"platform":1,"version":1,"plugin":1,"application":1,"based":1,"plugins":1,"registry.aarch64.bin":1,"libraries":1}
,"installation":{"setup":1}
,"section":{"describes":1,"show":1,"provides":1}
,"describes":{"install":1,"example":1,"procedures":1,"gstreamer-1.0":1,"nvgstcapture-1.0":1,"application\u2019s":1,"runtime":1,"operation":1,"nvgstplayer-1.0":1,"nvgstplayer":1,"supported":1}
,"install":{"configure":1,"gstreamer-1.0":1,"gstreamer1.0-tools":1,"libgstreamer1.0-dev":1,"following":1,"gstreamer1.0-plugins-bad":1,"specific":1,"needed":1,"build-essential":1,"libxv-dev":1,"libbz2-dev":1,"faad":1,"libx264-dev":1}
,"configure":{"gstreamer":1,"--prefix":1}
,"platform":{"following":1,"table":1,"gstreamer-1.0":1}
,"following":{"commands":1,"command":1,"gst-omx":1,"gst-v4l2":1,"egl":1,"drm":1,"proprietary":1,"libjpeg":1,"examples":1,"example":1,"modes":1,"profiles":1,"levels":1,"formula":1,"entropy":1,"values":1,"table":1,"video":1,"steps":1,"properties":1,"sample":1,"dependent":1,"files":1,"image":1,"features":1,"camera":1,"usb":1}
,"sudo":{"add-apt-repository":1,"apt-get":1,"sys":1,"systemctl":1,"loginctl":1,"-sf":1,"modprobe":1,"xdg_runtime_dir":1}
,"add-apt-repository":{"universe":1,"multiverse":1}
,"apt-get":{"update":1,"install":1}
,"gstreamer1.0-tools":{"gstreamer1.0-alsa":1}
,"gstreamer1.0-alsa":{"gstreamer1.0-plugins-base":1}
,"gstreamer1.0-plugins-base":{"gstreamer1.0-plugins-good":1}
,"gstreamer1.0-plugins-good":{"gstreamer1.0-plugins-bad":1}
,"gstreamer1.0-plugins-bad":{"gstreamer1.0-plugins-ugly":1}
,"gstreamer1.0-plugins-ugly":{"gstreamer1.0-libav":1}
,"libgstreamer1.0-dev":{"libgstreamer-plugins-base1.0-dev":1}
,"libgstreamer-plugins-base1.0-dev":{"libgstreamer-plugins-good1.0-dev":1}
,"libgstreamer-plugins-good1.0-dev":{"libgstreamer-plugins-bad1.0-dev":1}
,"check":{"gstreamer-1.0":1}
,"gst-inspect-1.0":{"--version":1,"omxh264enc":1,"nvv4l2h264enc":1,"nvvidconv":1,"nvcompositor":1}
,"plugin":{"reference":1,"deprecated":1,"instead":1,"argus":1,"v4l2":1,"gstreamer-1.0":1,"expect":1,"legacy":1,"support":1,"default":1,"currently":1,"capture":1,"modify":1,"application":1,"video":1,"mp4":1,"development":1,"allows":1,"performs":1,"perform":1,"directory":1,"longer":1}
,"gst-omx":{"plugin":1,"video":1,"decoder":1,"encoders":1,"encoder":1,"pipeline":1,"overlay":1}
,"deprecated":{"jetson":1}
,"release":{"32.1":1,"24.2":1,"contains":1}
,"32.1":{"gst-v4l2":1,"nvdrmvideosink":1}
,"gst-v4l2":{"plugin":1,"video":1,"decoder":1,"encoder":1,"encoders":1,"pipeline":1}
,"includes":{"following":1}
,"video":{"decoders":1,"decoder":1,"encoders":1,"encoder":1,"sink":1,"format":1,"compositor":1,"transform":1,"encode":1,"decode":1,"display-id":1,"stream":1,"usability":1,"capture":1,"x-raw":1,"encoding":1,"playback":1,"output":1,"sinks":1,"connected":1,"decoding":1,"streaming":1,"h264":1,"rendering":1,"render":1,"formats":1,"scaling":1,"cropping":1,"transcode":1,"transcoding":1,"post-processing":1,"using":1,"rotation":1,"degrees":1,"180":1,"composition":1,"decoded":1,"width":1,"preview":1,"snapshot":1,"content":1,"mode":1,"processing":1,"tracks":1,"non-full-screen":1,"postprocessing":1}
,"openmax":{"h.265":1,"h.264":1,"mpeg4":1,"mpeg2":1,"vp8":1,"vp9":1,"videosink":1}
,"h.265":{"video":1,"avc":1,"decode":1,"encode":1,"vp8":1,"stream":1,"vp9":1,"access":1}
,"h.264":{"video":1,"avc":1,"decode":1,"encode":1,"h.265":1,"format":1}
,"mpeg4":{"video":1,"aacplus":1,"aac":1,"eaacplus":1,"amr-wb":1,"amr-nb":1}
,"mpeg2":{"video":1}
,"vp8":{"video":1,"decode":1,"encode":1,"vp9":1,"supported":1}
,"vp9":{"video":1,"decode":1,"encode":1,"encoder":1,"encoders":1,"gst-omx":1,"gst-v4l2":1}
,"v4l2":{"h.265":1,"h.264":1,"vp8":1,"vp9":1,"mpeg4":1,"mpeg2":1,"api":1,"driver":1,"csi":1,"default":1}
,"avc":{"video":1}
,"encoder":{"supported":1,"element":1,"plugin":1,"features":1,"properties":1,"drop":1,"intentionally":1,"skips":1,"property":1,"achieve":1,"best":1,"gray8":1,"type":1,"profile":1,"configuration":1,"h.264":1,"feature":1}
,"supported":{"nvidia":1,"jetson":1,"nveglglessink":1,"high444":1,"main":1,"h.264":1,"using":1,"1.2":1,"main1":1,"omxh265enc":1,"h.265":1,"poc-type":1,"opencv":1,"formats":1,"values":1,"resolutions":1,"nvarguscamera":1,"usb":1,"options":1,"cameras":1,"gmsl":1}
,"tx2i":{"supported":1,"jetson":1}
,"videosink":{"element":1,"display":1,"using":1,"component":1}
,"egl":{"image":1,"gles":1,"images":1,"window":1}
,"image":{"video":1,"decode":1,"encode":1,"capture":1,"transform":1,"width":1,"encoder":1,"resolutions":1,"display":1}
,"gles":{"videosink":1}
,"element":{"x11":1,"nvmm":1,"uses":1,"works":1,"properties":1,"file":1}
,"x11":{"wayland":1,"using":1,"disabled":1,"helps":1,"backend":1}
,"wayland":{"backends":1,"backend":1,"display":1,"xorg":1,"server":1,"back":1}
,"drm":{"video":1,"videosink":1,"render":1}
,"nvoverlaysink":{"plugin":1,"display-id":1,"overlay-x":1,"display":1,"nvdrmvideosink":1}
,"nvdrmvideosink":{"nv3dsink":1,"plugin":1,"supports":1}
,"nv3dsink":{"instead":1,"video":1,"window-x":1,"gray8":1}
,"instead":{"render":1,"default":1}
,"render":{"pipelines":1,"video":1,"pipeline":1}
,"pipelines":{"gst-v4l2":1,"csi":1,"different":1,"video":1}
,"proprietary":{"nvidia":1,"plugin":1,"nvvidconv":1,"gstreamer-1.0":1,"nvcompositor":1,"nvegltransform":1}
,"camera":{"plugin":1,"capture":1,"support":1,"csi":1,"captured":1,"pipeline":1,"source":1,"sensor":1,"saturation":1,"supported":1,"supports":1,"runtime":1,"images":1,"validated":1,"uvc":1,"details":1}
,"argus":{"api":1}
,"format":{"conversion":1,"produces":1,"string":1,"framerate":1,"i420":1,"range":1,"support":1,"using":1,"nv12":1,"conversions":1}
,"conversion":{"scaling":1,"gstreamer-1.0":1,"oss":1,"raw":1,"described":1}
,"acts":{"gstreamer":1}
,"source":{"component":1,"video":1}
,"component":{"accepts":1}
,"accepts":{"eglstream":1,"yuv-i420":1}
,"eglstream":{"eglstream":1,"producer":1,"rgba":1}
,"sink":{"component":1,"video":1,"element":1,"supports":1}
,"yuv-i420":{"format":1}
,"produces":{"eglstream":1}
,"transform":{"element":1,"example":1,"pipeline":1}
,"nvmm":{"eglimage":1,"buffers":1}
,"eglimage":{"supported":1,"transform":1}
,"libjpeg":{"based":1}
,"jpeg":{"image":1,"encoder":1,"decoder":1,"decode":1,"encode":1}
,"encode":{"decode":1,"examples":1,"gstreamer":1,"gstreamer-1.0":1,"oss":1,"using":1,"nvidia":1,"supported":1,"ivf":1,"two-pass":1,"main":1,"num-b-frames":1,"support":1,"pipeline":1,"h.264":1,"opencv":1,"rtp":1}
,"decode":{"plugins":1,"pipeline":1,"examples":1,"gstreamer":1,"using":1,"oss":1,"gstreamer-1.0":1,"nvidia":1,"cases":1,"h264":1,"divx":1,"support":1,"different":1,"video":1,"file":1,"vp9":1,"nvidia-accelerated":1,"h.264":1,"h.265":1,"vp8":1,"mpeg-4":1,"theora":1,"h.263":1,"command":1,"gst-omx":1}
,"decoder":{"element":1,"plugin":1,"network":1,"gray8":1,"nv3dsink":1}
,"execute":{"command":1,"following":1}
,"command":{"target":1,"capture":1,"start":1,"illustrates":1,"starts":1,"unset":1,"line":1,"sequence":1}
,"target":{"starting":1,"bit":1,"csi":1,"network":1}
,"starting":{"video":1,"every":1}
,"pipeline":{"using":1,"below":1,"example":1,"similarly":1,"opencv_nvgstcam":1,"opencv_nvgstenc":1,"wayland":1,"creation":1,"requires":1,"gst-1.14":1,"preview":1}
,"using":{"gst-launch":1,"gst-launch-1.0":1,"gstreamer-1.0":1,"gst-omx":1,"gst-v4l2":1,"maxperf-enable":1,"nvarguscamerasrc":1,"nvv4l2camerasrc":1,"nvidia":1,"v4l2src":1,"plugin":1,"nvv4l2h264enc":1,"hdmi":1,"overlay":1,"following":1,"non-x11":1,"default":1,"nveglglesink":1,"wayland":1,"target\u2019s":1,"drm":1,"nvdrmvideosink":1,"graphics":1,"nv3dsink":1,"properties":1,"nvv4l2decoder":1,"nvgstplayer-1.0":1,"network":1,"nveglglessink":1,"command":1,"gst-omx-decoder":1,"gst-install":1,"nvgstcapture":1}
,"gst-launch":{"nvgstplayer":1}
,"export":{"display":1,"environment":1,"ld_library_path":1,"path":1,"pkg_config_path":1}
,"start":{"server":1,"gstreamer":1,"wayland":1,"weston":1,"recording":1,"playback":1,"percent":1,"resume":1}
,"server":{"xinit":1,"support":1,"weston":1}
,"xinit":{"already":1}
,"already":{"running":1}
,"examples":{"section":1,"using":1,"show":1,"valid":1}
,"show":{"perform":1,"help":1,"gstreamer":1}
,"perform":{"audio":1,"video":1,"jpeg":1}
,"audio":{"video":1,"decode":1,"hdmi":1,"setup":1,"jetson":1,"encode":1,"tracks":1,"rendering":1,"decoding":1,"postprocessing":1}
,"0.10":{"support":1}
,"support":{"deprecated":1,"8kp30":1,"opencv":1,"gstreamer":1,"wayland":1,"switch":1,"following":1,"yuv":1,"validated":1,"mipi":1,"added":1}
,"24.2":{"gstreamer":1}
,"recommended":{"development":1}
,"aac":{"decode":1,"encode":1,"plus":1}
,"oss":{"software":1,"raw":1}
,"software":{"decode":1,"encode":1,"driver":1,"hardware":1,"memory":1}
,"gst-launch-1.0":{"filesrc":1,"audiotestsrc":1,"videotestsrc":1,"nvarguscamerasrc":1,"usage":1,"nvv4l2camerasrc":1,"v4l2src":1,"pipeline":1,"udpsrc":1,"nvcompositor":1}
,"filesrc":{"location":1}
,"location":{"filename.mp4":1,"filename.mp3":1,"filename_10bit.mkv":1,"filename_12bit.mkv":1,"filename.ts":1,"filename_h264.mp4":1,"filename_h265.mp4":1,"filename_8bit_yuv444.265":1,"filename_vp9.mkv":1,"filename_vp8.mkv":1,"filename_mpeg4.mp4":1,"filename_divx.avi":1,"filename_mpeg2.ts":1,"filename.jpg":1,"test.mp4":1,"filename_8k_h265.mkv":1,"test.h265":1,"test_10bit.mkv":1,"test.mkv":1,"filename_nv24_352_288.yuv":1,"filename_8bit_nv24.264":1,"filename_10bit_h265.mp4":1,"filename_8bit_nv24.265":1,"filename_vp9.vp9":1,"filename_vp8.vp8":1,"test.jpg":1,"test1.mp4":1,"filename_h264_vbr.mp4":1,"filename_h264_cbr.mp4":1,"filename_h264.264":1,"filename_1080p.mp4":1,"test.yuv":1,"640x480_30p.mp4":1,"720x480_30i_mp.mp4":1,"1280x720_30p.mp4":1,"transcoded_filename.mkv":1,"filename.webm":1,"transcoded_filename.mp4":1,"filename.mebm":1,"filename.mkv":1,"transcoded_filename.ogg":1,"filename_h264_1080p.mp4":1,"filename_h264_1080p_30fps.mp4":1,"filename_h265_1080p_30fps.mp4":1,"filename_vp8_1080p_30fps.webm":1,"filename_vp9_1080p_30fps.webm":1,"installing":1}
,"filename.mp4":{"qtdemux":1,"matroskademux":1}
,"qtdemux":{"name":1,"h265parse":1,"queue":1,"h264parse":1}
,"name":{"demux":1,"mux":1,"comp":1,"nvcamtest":1}
,"demux":{"demux.audio_0":1,"demux.video_0":1,"h264parse":1}
,"demux.audio_0":{"queue":1}
,"queue":{"avdec_aac":1,"avdec_amrwb":1,"avdec_amrnb":1,"h264parse":1,"h265parse":1,"omxvp8dec":1,"omxvp9dec":1,"mpeg4videoparse":1,"mpegvideoparse":1,"nvv4l2decoder":1,"matroskamux":1,"qtmux":1,"seconds":1,"bytes":1,"automatic":1}
,"avdec_aac":{"audioconvert":1}
,"audioconvert":{"alsasink":1,"audioresample":1,"osssink":1}
,"amr-wb":{"decode":1,"encode":1}
,"avdec_amrwb":{"audioconvert":1}
,"amr-nb":{"decode":1}
,"avdec_amrnb":{"audioconvert":1}
,"mp3":{"decode":1}
,"filename.mp3":{"mpegaudioparse":1}
,"mpegaudioparse":{"avdec_mp3":1}
,"avdec_mp3":{"audioconvert":1}
,"route":{"audio":1}
,"hdmi":{"alsasink":1,"hdmi":1,"port":1,"connector":1}
,"alsasink":{"property":1,"device":1}
,"property":{"device":1,"gst-omx":1,"nvoverlaysink":1,"gst-v4l2":1,"enable-frame-type-reporting":1,"gst-inspect-1.0":1,"sets":1,"enables":1,"inserts":1,"removed":1,"jetson":1,"name":1,"value":1,"adjust":1,"auto":1,"select":1,"emit":1}
,"device":{"value":1,"map":1,"hw:0,7":1,"dev":1,"win_mask":1,"node":1,"demixer":1}
,"value":{"given":1,"configured":1,"256":1,"-2.0":1,"elements":1}
,"given":{"platform":1}
,"table":{"port":1,"shows":1,"describes":1}
,"port":{"device":1,"8001":1,"brick":1}
,"map":{"topic":1}
,"setup":{"development":1}
,"example":{"device":1,"pipeline":1,"refer":1,"shows":1,"gst-launch-1.0":1,"gstreamer-1.16.2":1,"br:4000000":1,"ep:1":1,"my_uri.txt":1,"-cxpr":1}
,"hw:0,7":{"route":1}
,"demux.video_0":{"queue":1}
,"h264parse":{"omxh264dec":1,"nvv4l2decoder":1,"qtmux":1,"filesink":1,"queue":1}
,"omxh264dec":{"nveglglessink":1,"nvoverlaysink":1,"nvvidconv":1,"omxvp9enc":1,"omxvp8enc":1,"videocuda":1,"--svc":1,"nvivafilter":1,"comp":1}
,"h265parse":{"omxh265dec":1,"nvv4l2decoder":1,"matroskamux":1,"qtmux":1,"filesink":1,"queue":1}
,"omxh265dec":{"nvoverlaysink":1,"nvvidconv":1,"enable-low-outbuffer":1,"disable-dvfs":1,"omxvp9enc":1,"omxvp8enc":1,"comp":1}
,"10-bit":{"h.265":1}
,"filename_10bit.mkv":{"matroskademux":1}
,"matroskademux":{"h265parse":1,"name":1,"queue":1,"omxvp8dec":1,"omxvp9dec":1,"nvv4l2decoder":1}
,"nvvidconv":{"\u0027video":1,"nvv4l2h264enc":1,"gstreamer-1.0":1,"plugin":1,"supports":1,"left":1,"avenc_mpeg4":1,"theoraenc":1,"flip\u2011method":1,"flip-method":1,"command":1,"interpolation\u2011method":1,"interpolation-method":1}
,"\u0027video":{"x-raw":1,"raw":1,"x-h264":1}
,"x-raw":{"memory:nvmm":1,"format":1,"width":1}
,"memory:nvmm":{"format":1,"width":1}
,"string":{"nv12":1,"s16le":1,"interleaved":1,"i420":1,"byte-stream":1,"i420_10le":1,"nv24":1,"p010_10le":1,"2.2":1,"filesink":1,"uyvy":1,"yuy2":1,"h264":1,"gray8":1,"rgba":1}
,"nv12":{"nvoverlaysink":1,"fakesink":1,"nvv4l2h265enc":1,"framerate":1,"width":1,"nv16":1,"nvegltransform":1,"csi":1}
,"12-bit":{"h.265":1}
,"filename_12bit.mkv":{"matroskademux":1}
,"cases":{"low":1}
,"low":{"memory":1,"high":1,"threshold":1}
,"memory":{"allocation":1,"bandwidth":1,"copies":1,"queue":1}
,"allocation":{"requirements":1}
,"requirements":{"e.g":1}
,"e.g":{"jetson":1,"st:1.25":1,"jx5000":1,"j:6":1,"br:4000000":1,"s5.120":1,"v54":1,"f23.901":1}
,"enable-low-outbuffer":{"property":1,"\u0027video":1}
,"raw":{"memory:nvmm":1,"yuv":1,"video":1,"bayer":1}
,"fakesink":{"sync":1}
,"enable":{"max":1,"error":1,"two-pass":1,"stringent":1,"cabac-entropy-coding":1,"mvbuffermeta":1,"two":1,"lock":1,"awb":1,"decodebin":1}
,"max":{"perf":1}
,"perf":{"mode":1}
,"mode":{"disable-dvfs":1,"enable-max-performance":1,"maxperf-enable":1,"default":1,"decision":1,"bitrate":1,"decisions":1,"using":1,"specifying":1,"v4l2_memory_dmabuf":1,"enter":1,"resolution":1,"staying":1,"ignoring":1,"nveglglessink":1}
,"disable-dvfs":{"property":1,"\u0027video":1}
,"expect":{"increased":1}
,"increased":{"power":1}
,"power":{"consumption":1}
,"consumption":{"max":1}
,"omxvp8dec":{"nvoverlaysink":1,"omxh264enc":1,"nvvidconv":1,"comp":1}
,"primary":{"display":1}
,"display":{"used":1,"detailed":1,"order":1,"nvdrmvideosink":1,"nv3dsink":1,"xvimagesink":1,"setting":1,"controller":1,"fb0":1,"server":1,"manager":1,"environment":1,"application":1,"lightdm":1,"information":1,"command":1,"value":1,"time":1}
,"used":{"render":1,"scaling":1,"default":1,"multiplexed":1,"validation":1}
,"display-id":{"property":1,"filesrc":1}
,"refer":{"pipeline":1,"tegra":1}
,"omxvp9dec":{"nvoverlaysink":1,"omxh265enc":1,"nvvidconv":1,"comp":1}
,"mpeg-4":{"decode":1,"encode":1}
,"mpeg4videoparse":{"omxmpeg4videodec":1,"nvv4l2decoder":1}
,"omxmpeg4videodec":{"nveglglessink":1,"omxvp9enc":1,"omxh264enc":1}
,"mpeg-2":{"decode":1}
,"filename.ts":{"tsdemux":1}
,"tsdemux":{"name":1,"queue":1}
,"mpegvideoparse":{"omxmpeg2videodec":1,"nvv4l2decoder":1}
,"omxmpeg2videodec":{"nveglglessink":1}
,"filename_h264.mp4":{"qtdemux":1}
,"nvv4l2decoder":{"nv3dsink":1,"enable-max-performance":1,"enable-frame-type-reporting":1,"nvvidconv":1,"nvdrmvideosink":1,"plugin":1,"nvv4l2h264enc":1,"nvv4l2h265enc":1,"nvv4l2vp9enc":1,"nvv4l2vp8enc":1,"nvivafilter":1,"comp":1,"nvegltransform":1}
,"enable-max-performance":{"property":1,"nv3dsink":1}
,"h264":{"h265":1,"format":1,"test_file_h264.3gp":1,"aac":1,"eaacplus":1,"amr-wb":1,"amr-nb":1,"aacplus":1,"payload":1,"vp8":1}
,"h265":{"gdr":1,"vp9":1}
,"gdr":{"streams":1}
,"streams":{"enable":1,"different":1,"sharing":1}
,"error":{"reporting":1}
,"reporting":{"setting":1}
,"setting":{"property":1,"echo":1,"window":1,"specific":1,"zoom":1}
,"enable-frame-type-reporting":{"true":1,"nv3dsink":1}
,"filename_h265.mp4":{"qtdemux":1}
,"8-bit":{"yuv444":1}
,"yuv444":{"nv24":1,"h.264":1,"h.265":1}
,"nv24":{"h.265":1,"h.264":1,"nvvidconv":1,"nvv4l2h264enc":1,"nvv4l2h265enc":1,"p010_10le":1,"gray8":1}
,"filename_vp9.mkv":{"matroskademux":1}
,"filename_vp8.mkv":{"matroskademux":1}
,"filename_mpeg4.mp4":{"qtdemux":1}
,"divx":{"nvidia":1}
,"filename_divx.avi":{"avidemux":1}
,"avidemux":{"queue":1}
,"filename_mpeg2.ts":{"tsdemux":1}
,"shows":{"perform":1,"usb":1,"supported":1,"tags":1,"stream":1}
,"filename.jpg":{"nvjpegdec":1}
,"nvjpegdec":{"imagefreeze":1}
,"imagefreeze":{"xvimagesink":1}
,"audiotestsrc":{"\u0027audio":1}
,"\u0027audio":{"x-raw":1}
,"s16le":{"layout":1}
,"layout":{"string":1}
,"interleaved":{"rate":1}
,"rate":{"int":1,"encoder":1,"control":1,"frame":1,"control-rate":1,"vbr":1,"cbr":1,"bytes":1}
,"int":{"44100":1,"voaacenc":1,"16000":1,"voamrwbenc":1,"640":1,"480":1,"3840":1,"2160":1,"7860":1,"4320":1,"1920":1,"1080":1,"704":1,"576":1,"1280":1,"720":1,"256":1}
,"44100":{"channels":1}
,"channels":{"int":1}
,"voaacenc":{"qtmux":1}
,"qtmux":{"filesink":1,"name":1}
,"filesink":{"location":1}
,"16000":{"channels":1}
,"voamrwbenc":{"qtmux":1}
,"videotestsrc":{"\u0027video":1,"num-buffers":1}
,"i420":{"width":1,"nvjpegenc":1,"omxh264enc":1,"framerate":1,"nvv4l2h264enc":1,"nvvidconv":1,"format":1,"filesink":1,"uyvy":1,"nv3dsink":1,"avenc_h263":1,"nvoverlaysink":1,"nvdrmvideosink":1,"nv12":1}
,"width":{"int":1,"352":1,"1280":1,"1920":1,"640":1,"height":1,"non-overlay":1}
,"640":{"height":1,"480":1,"overlay-h":1,"format":1}
,"height":{"int":1,"288":1,"720":1,"1080":1,"480":1,"csi":1,"order":1,"non-overlay":1}
,"480":{"omxh264enc":1,"omxh265enc":1,"omxvp8enc":1,"omxvp9enc":1,"avenc_mpeg4":1,"format":1,"overlay":1,"framerate":1,"xvimagesink":1,"height":1}
,"omxh264enc":{"\u0027video":1,"omxh265enc":1,"iframeinterval":1,"temporal-tradeoff":1,"control-rate":1,"bitrate":1,"qp-range":1,"preset-level":1,"profile":1,"following":1,"num-b-frames":1,"insert-sps-pps":1,"enabletwopasscbr":1,"vbv-size":1,"slice-header-spacing":1,"qtmux":1}
,"x-h264":{"stream-format":1,"level":1}
,"stream-format":{"string":1}
,"byte-stream":{"h264parse":1,"alignment":1}
,"8kp30":{"h.265":1}
,"2160":{"format":1,"fps":1}
,"framerate":{"fraction":1}
,"fraction":{"nvvidconv":1,"nvv4l2h264enc":1,"nvv4l2h265enc":1,"nvv4l2vp9enc":1,"nvv4l2vp8enc":1,"omxh264enc":1,"nvdrmvideosink":1,"nvivafilter":1}
,"4320":{"format":1}
,"preset-level":{"control-rate":1,"qtmux":1,"measureencoderlatency":1}
,"control-rate":{"bitrate":1,"qtmux":1,"mode":1,"vbv-size":1,"two-pass":1}
,"bitrate":{"40000000":1,"8000000":1,"6000000":1,"40000":1,"fps":1,"enabled":1,"supported":1,"mode":1,"30000000":1,"10000000":1,"20000000":1,"4000000":1}
,"omxh265enc":{"filesink":1,"matroskamux":1,"encoder":1,"omxvp8enc":1,"following":1,"bitrate":1}
,"nvarguscamerasrc":{"\u0027video":1,"num-buffers":1,"plugin":1,"preview":1,"plugin\u2019s":1}
,"1920":{"height":1,"--height":1,"sink_0":1}
,"1080":{"format":1,"--fps":1,"sink_1":1}
,"i420_10le":{"omxh265enc":1}
,"matroskamux":{"filesink":1,"name":1}
,"omxvp8enc":{"matroskamux":1,"omxvp9enc":1,"bitrate":1}
,"omxvp9enc":{"matroskamux":1,"command":1,"bitrate":1}
,"avenc_mpeg4":{"qtmux":1,"bitrate":1}
,"h.263":{"encode":1}
,"704":{"height":1}
,"576":{"avenc_h263":1,"format":1,"nvoverlaysink":1,"nv3dsink":1}
,"avenc_h263":{"qtmux":1,"bitrate":1}
,"nvv4l2h264enc":{"bitrate":1,"maxperf-enable":1,"profile":1,"nvv4l2h265enc":1,"control-rate":1,"poc-type":1,"plugin":1,"insert-sps-pps":1,"\u0027video":1}
,"8000000":{"h264parse":1,"h265parse":1,"matroskamux":1,"filesink":1}
,"maxperf-enable":{"property":1,"bitrate":1}
,"videoparse":{"width":1}
,"352":{"height":1}
,"288":{"format":1}
,"profile":{"high444":1,"main":1,"qtmux":1,"supported":1,"\u0027video":1,"cabac-entropy-coding":1,"h.264":1,"baseline":1}
,"high444":{"h264parse":1,"profile":1}
,"nvv4l2h265enc":{"bitrate":1,"profile":1,"nvv4l2vp9enc":1,"nvv4l2vp8enc":1}
,"p010_10le":{"nvv4l2h265enc":1,"gray8":1}
,"main":{"h265parse":1,"profile":1,"high":1}
,"nvv4l2vp9enc":{"bitrate":1,"enable-headers":1,"nvv4l2vp8enc":1,"command":1}
,"ivf":{"headers":1}
,"headers":{"nvidia":1}
,"enable-headers":{"bitrate":1}
,"nvv4l2vp8enc":{"bitrate":1,"enable-headers":1,"encoder":1,"nvv4l2vp9enc":1}
,"num-buffers":{"\u0027video":1,"200":1,"300":1}
,"nvjpegenc":{"filesink":1}
,"features":{"gstreamer-1.0":1,"supported":1,"setting":1,"respectively":1}
,"usage":{"features":1,"information":1,"commands":1}
,"detailed":{"information":1}
,"information":{"omxh264enc":1,"nvv4l2h264enc":1,"vui":1,"enter":1,"nvgstcapture-1.0":1,"nvvidconv":1,"command":1,"run":1}
,"properties":{"gst-inspect-1.0":1,"shown":1,"file":1,"separated":1}
,"i-frame":{"interval":1}
,"200":{"\u0027video":1,"is-live":1,"bit-packetization":1,"configures":1,"maximum":1,"bottom":1}
,"1280":{"height":1,"720":1}
,"720":{"format":1,"nvvidconv":1,"nvoverlaysink":1,"nvdrmvideosink":1}
,"iframeinterval":{"100":1}
,"100":{"qtmux":1,"h264parse":1,"overlay-y":1,"overlay-w":1}
,"temporal-tradeoff":{"rate":1,"qtmux":1}
,"drop":{"frames":1,"input":1}
,"configuring":{"temporal":1,"virtual":1}
,"temporal":{"tradeoff":1,"noise":1}
,"tradeoff":{"causes":1}
,"causes":{"encoder":1}
,"intentionally":{"periodically":1}
,"periodically":{"drop":1}
,"input":{"frames":1,"formats":1,"cpu":1,"output":1,"format":1,"uri":1}
,"frames":{"following":1,"necessary":1,"effect":1,"two":1,"supported":1,"renders":1}
,"modes":{"supported":1,"costs":1,"various":1}
,"control":{"mode":1,"method":1}
,"variable":{"bit":1,"bitrate":1,"using":1,"following":1,"default":1}
,"bit":{"rate":1}
,"constant":{"bit":1,"bitrate":1}
,"frame":{"skip":1,"h.264":1,"occurrence":1,"supported":1,"video":1}
,"skip":{"encoder":1}
,"skips":{"frames":1}
,"necessary":{"meet":1}
,"meet":{"target":1}
,"peak":{"bitrate":1}
,"is-live":{"true":1}
,"true":{"\u0027video":1,"qtmux":1,"h264parse":1,"customer-lib-name":1}
,"6000000":{"peak-bitrate":1}
,"peak-bitrate":{"6500000":1}
,"6500000":{"qtmux":1}
,"takes":{"effect":1}
,"effect":{"variable":1,"number":1}
,"default":{"value":1,"supports":1,"currently":1,"x11":1,"mode":1,"nvgstcapture-1.0":1,"videotest":1,"csi":1,"v4l2":1,"dev":1,"disabled":1}
,"configured":{"1.2":1}
,"1.2":{"bitrate":1,"1.3":1}
,"quantization":{"range":1}
,"range":{"frame":1,"following":1,"frames":1,"3840x2160":1,"5632x4224":1,"3896x2192":1,"nanoseconds":1,"value":1}
,"i_range":{"p_range":1}
,"p_range":{"b_range":1}
,"b_range":{"expressed":1}
,"expressed":{"hyphenated":1}
,"hyphenated":{"values":1}
,"values":{"shown":1,"supported":1,"nvvidconv":1}
,"shown":{"following":1,"example":1}
,"qp-range":{"10,30:10,35:10,35":1,"supported":1,"24,24:28,28:30,30":1}
,"10,30:10,35:10,35":{"qtmux":1}
,"number":{"frames":1,"bits":1,"gstreamer":1,"images":1,"times":1,"play":1,"buffers":1}
,"hardware":{"preset":1,"memory":1,"software":1}
,"preset":{"level":1}
,"integer":{"pixel":1}
,"pixel":{"integer-pel":1,"half-pel":1,"qpel":1}
,"integer-pel":{"block":1}
,"block":{"motion":1}
,"motion":{"estimated":1,"estimation":1,"vector":1}
,"estimated":{"macroblock":1}
,"macroblock":{"mode":1,"-based":1}
,"decision":{"intra":1}
,"intra":{"cost":1,"intra":1,"modes":1,"frame":1}
,"cost":{"compared":1}
,"compared":{"inter":1,"intermode":1}
,"inter":{"modes":1}
,"costs":{"supports":1}
,"supports":{"intra":1,"half":1,"quarter":1,"argus":1,"dmabuf":1,"yuv":1,"single-instance":1,"camera":1,"currently":1,"specific":1,"following":1,"setting":1,"video":1,"format":1,"i420":1,"nvidia":1,"scaling":1,"native":1,"simultaneous":1}
,"half":{"pixel":1}
,"half-pel":{"block":1}
,"estimation":{"macroblock":1}
,"quarter":{"pixel":1}
,"qpel":{"block":1}
,"profiles":{"supported":1}
,"baseline":{"profile":1,"main":1}
,"high":{"profile":1,"percent":1,"threshold":1}
,"256":{"height":1,"framerate":1}
,"40000":{"\u0027video":1}
,"level":{"string":1,"supported":1}
,"2.2":{"qtmux":1,"3.1":1}
,"levels":{"supported":1}
,"1.3":{"2.1":1}
,"2.1":{"2.2":1}
,"3.1":{"3.2":1}
,"3.2":{"4.1":1}
,"4.1":{"4.2":1}
,"4.2":{"5.1":1}
,"5.1":{"5.2":1}
,"main1":{"main2":1}
,"main2":{"main2.1":1}
,"main2.1":{"main3":1}
,"main3":{"main3.1":1}
,"main3.1":{"main4":1}
,"main4":{"main4.1":1}
,"main4.1":{"main5":1}
,"main5":{"high1":1}
,"high1":{"high2":1}
,"high2":{"high2.1":1}
,"high2.1":{"high3":1}
,"high3":{"high3.1":1}
,"high3.1":{"high4":1}
,"high4":{"high4.1":1}
,"high4.1":{"high5":1}
,"two":{"reference":1,"pass":1}
,"reference":{"frames":1,"guide":1,"manual":1,"gmsl":1}
,"num-b-frames":{"qtmux":1,"filesink":1,"\u0027video":1,"enable":1}
,"b-frame-encoding":{"supported":1}
,"insert":{"sps":1,"aud":1,"vui":1}
,"sps":{"pps":1,"picture":1}
,"pps":{"idr":1,"inserted":1}
,"insert-sps-pps":{"qtmux":1,"true":1}
,"enabled":{"sequence":1,"along":1,"virtual":1,"enable":1}
,"sequence":{"parameter":1,"expression":1}
,"parameter":{"sps":1,"pps":1,"bit-packetization":1}
,"picture":{"parameter":1,"order":1}
,"inserted":{"idr":1}
,"idr":{"frame":1,"supported":1}
,"two-pass":{"cbr":1}
,"enabletwopasscbr":{"control-rate":1,"true":1,"\u0027video":1}
,"cbr":{"enabled":1,"supported":1,"encoding":1}
,"along":{"constant":1}
,"virtual":{"buffer":1,"channel":1}
,"buffer":{"size":1}
,"vbv-size":{"qtmux":1,"bitrate":1,"enabletwopasscbr":1}
,"size":{"decoder":1,"cause":1,"vbv-size":1}
,"network":{"bandwidth":1,"abstraction":1,"sink":1,"source":1}
,"bandwidth":{"limited":1,"contention":1}
,"limited":{"configuring":1}
,"cause":{"video":1}
,"stream":{"generation":1,"multiple":1,"statistics":1,"supported":1}
,"generation":{"correspond":1}
,"correspond":{"limitations":1}
,"limitations":{"according":1}
,"according":{"following":1}
,"stringent":{"bitrate":1}
,"enablestringentbitrate":{"true":1}
,"slice-header-spacing":{"spacing":1,"200":1,"1024":1,"bit-packetization":1,"configures":1,"1400":1}
,"spacing":{"terms":1,"spacing":1}
,"bit-packetization":{"qtmux":1,"configures":1,"\u0027video":1}
,"configures":{"network":1,"nal":1}
,"abstraction":{"layer":1}
,"layer":{"nal":1}
,"nal":{"packet":1}
,"packet":{"macroblock":1,"200":1,"size-based":1,"1024":1,"maximum":1,"1400":1}
,"-based":{"slice-header-spacing":1}
,"slice":{"header":1}
,"header":{"spacing":1,"default":1}
,"terms":{"number":1,"supported":1}
,"1024":{"bit-packetization":1,"configures":1,"bytes":1,"sink_2":1,"sink_3":1}
,"size-based":{"slice-header-spacing":1}
,"bytes":{"maximum":1,"automatic":1}
,"interval":{"supported":1}
,"sets":{"encoding":1,"number":1,"quanatization":1}
,"encoding":{"intra":1,"formats":1,"bit-rate":1,"bit":1,"profile":1}
,"occurrence":{"frequency":1}
,"30000000":{"h264parse":1}
,"ratecontrol-enable":{"quant-i-frames":1}
,"quant-i-frames":{"quant-p-frames":1}
,"quant-b-frames":{"num-b-frames":1}
,"measureencoderlatency":{"\u0027video":1}
,"alignment":{"string":1}
,"decisions":{"intra":1}
,"intermode":{"costs":1}
,"main10":{"profile":1}
,"300":{"\u0027video":1,"--window-y":1,"--window-width":1,"window-y":1,"window-width":1}
,"10000000":{"enabletwopasscbr":1}
,"multi-instance":{"encode":1,"capture":1}
,"achieve":{"best":1}
,"best":{"performance":1}
,"performance":{"expect":1}
,"bits":{"supported":1}
,"1400":{"bit-packetization":1,"configures":1,"bytes":1}
,"cabac-entropy-coding":{"supported":1,"\u0027video":1}
,"entropy":{"coding":1}
,"coding":{"types":1,"type":1,"order":1}
,"types":{"supported":1}
,"specifying":{"maxperf-enable":1}
,"24,24:28,28:30,30":{"num-b-frames":1}
,"quanatization":{"range":1}
,"mvbuffermeta":{"supported":1}
,"enablemvbuffermeta":{"\u0027video":1}
,"enables":{"motion":1}
,"vector":{"metadata":1}
,"metadata":{"encoding":1,"available":1}
,"aud":{"supported":1}
,"insert-aud":{"\u0027video":1}
,"inserts":{"h.264":1}
,"access":{"unit":1}
,"unit":{"delimiter":1}
,"delimiter":{"aud":1}
,"vui":{"supported":1,"sps":1}
,"insert-vui":{"\u0027video":1}
,"usability":{"information":1}
,"order":{"count":1,"display":1}
,"count":{"poc":1,"number":1,"type":1}
,"poc":{"type":1,"explicitly":1}
,"type":{"supported":1,"sensor":1}
,"poc-type":{"h264parse":1,"property":1}
,"explicitly":{"specified":1}
,"specified":{"slice":1,"function":1}
,"decoding":{"coding":1,"opencv_nvgstdec":1}
,"capture":{"gstreamer-1.0":1,"using":1,"preview":1,"uyvy":1,"yuv":1,"images":1,"vga":1,"480p":1,"raw":1,"encode":1,"pipeline":1,"usb":1,"video":1,"mode":1,"whitebalance":1,"timeout":1,"device":1,"image":1,"delay":1,"5-second":1,"count":1,"resolution":1,"camera":1,"data":1,"multiple":1,"validated":1}
,"nvgstcapture-1.0":{"usage":1,"--help":1,"application":1,"reference":1,"--camsrc":1}
,"enter":{"following":1,"command":1,"single":1}
,"application":{"default":1,"uses":1,"opencv_nvgstcam":1,"opencv_nvgstenc":1,"enter":1,"distributed":1,"support":1,"supports":1,"opencv_nvgstdec":1,"currently":1,"utilizes":1,"usage":1,"display":1,"command":1,"generates":1,"itself":1,"reference":1}
,"api":{"using":1,"performs":1}
,"legacy":{"nvcamerasrc":1}
,"nvcamerasrc":{"plugin":1}
,"preview":{"display":1,"rendering":1,"width":1,"resolution":1}
,"plugin\u2019s":{"maxpef":1}
,"maxpef":{"property":1}
,"removed":{"vic":1}
,"vic":{"actmon":1,"frequency":1}
,"actmon":{"dfs":1}
,"dfs":{"implemented":1}
,"implemented":{"handle":1}
,"handle":{"vic":1}
,"frequency":{"scaling":1}
,"scaling":{"per":1,"gstreamer-1.0":1,"nvvidconv":1,"format":1,"raw":1}
,"per":{"load":1}
,"load":{"enabling":1}
,"enabling":{"clients":1}
,"clients":{"required":1}
,"required":{"performance":1,"yuv":1,"overlay":1,"first":1,"subsequent":1}
,"progressive":{"capture":1}
,"nvv4l2camerasrc":{"device":1,"plugin":1,"enhanced":1}
,"dev":{"video3":1,"video0":1,"video1":1,"video2":1,"dsp1":1}
,"interlace-mode":{"progressive":1}
,"currently":{"supports":1,"verified":1,"supported":1,"following":1,"operates":1,"nvvidconv":1}
,"dmabuf":{"importer":1}
,"importer":{"role":1}
,"role":{"streaming":1}
,"streaming":{"mode":1,"gstreamer-1.0":1,"gstreamer\u20111.0":1,"nvgstplayer-1.0":1,"video":1,"using":1,"file":1}
,"verified":{"using":1}
,"sensor":{"supports":1,"capture":1,"software":1,"orientation":1,"value":1,"streams":1}
,"yuv":{"capture":1,"formats":1,"format":1,"i420":1,"input":1,"output":1,"raw":1}
,"uyvy":{"format":1,"yuy2":1,"width":1,"videoconvert":1}
,"need":{"different":1,"version":1}
,"different":{"type":1,"video":1,"formats":1}
,"formats":{"topic":1,"application":1,"display":1,"video":1,"nvidia":1,"nvvidconv":1,"format":1,"scaling":1,"respectively":1}
,"programming":{"case":1}
,"case":{"nvv4l2camerasrc":1,"issue":1}
,"enhanced":{"required":1}
,"uses":{"v4l2src":1,"opencv-based":1,"drm":1,"commands":1}
,"v4l2src":{"plugin":1,"preview":1,"device":1}
,"images":{"video":1,"render":1,"succession":1,"via":1}
,"usb":{"camera":1,"specifies":1,"2.0":1,"3.0":1}
,"vga":{"640":1}
,"480p":{"720p":1}
,"720p":{"h.264":1}
,"raw-yuv":{"capture":1,"input":1,"output":1}
,"opencv":{"sample":1,"version":1,"enter":1,"based":1}
,"sample":{"application":1,"applications":1,"pipeline":1,"decode":1,"csi":1,"cuda":1}
,"opencv_nvgstcam":{"simulates":1,"camera":1,"sample":1,"--help":1,"application":1,"--width":1}
,"simulates":{"camera":1,"video":1}
,"similarly":{"opencv":1}
,"opencv_nvgstenc":{"simulates":1,"camera":1,"sample":1,"--help":1,"application":1,"--width":1}
,"applications":{"based":1}
,"simulate":{"camera":1,"video":1,"eglstream":1,"egl":1}
,"distributed":{"currently":1,"current":1}
,"single-instance":{"csi":1}
,"csi":{"capture":1,"multi-instance":1,"camera":1,"default":1,"yuy2":1,"nvoverlaysink":1,"cameras":1,"interface":1,"virtual":1,"port":1,"stream":1}
,"modify":{"rebuild":1}
,"rebuild":{"application":1}
,"opencv-based":{"videosink":1}
,"rendering":{"opencv":1,"api":1}
,"--width":{"1920":1}
,"--height":{"1080":1}
,"mp4":{"container":1}
,"container":{"file":1}
,"file":{"modify":1,"dump":1,"case":1,"type":1,"name":1,"containing":1,"home":1,"may":1,"source":1}
,"--fps":{"--time":1}
,"--filename":{"test_h264_1080p_30fps.mp4":1}
,"playback":{"gstreamer-1.0":1,"overlay":1,"examples":1,"using":1,"nvidia":1,"seconds":1}
,"nvgstplayer-1.0":{"usage":1,"--help":1,"application":1,"filename":1,"enter":1,"rtsp":1,"filename_h264_1080p.mp4":1,"reference":1,"command-line":1}
,"output":{"displays":1,"formats":1,"cpu":1,"format":1,"files":1}
,"displays":{"using":1}
,"connector":{"platform":1,"display":1}
,"overlay":{"sink":1,"full-screen":1,"parameters":1,"property":1,"windows":1,"overlay-depth":1,"video":1,"render":1,"configuration":1}
,"full-screen":{"mode":1}
,"steps":{"required":1}
,"win_mask":{"following":1,"clears":1,"assigns":1}
,"sys":{"class":1}
,"class":{"graphics":1}
,"graphics":{"fb0":1,"api":1,"rendering":1}
,"fb0":{"echo":1}
,"echo":{"blank":1,"0x0":1,"0x3f":1}
,"blank":{"blanks":1,"unblank":1}
,"blanks":{"monitor":1}
,"monitor":{"changing":1}
,"changing":{"display":1}
,"0x0":{"device":1}
,"clears":{"current":1}
,"current":{"window":1,"supports":1,"versions":1,"track":1,"position":1}
,"window":{"setting":1,"disabling":1,"position":1,"coordinates":1,"non-overlay":1,"width":1,"height":1}
,"0x3f":{"device":1}
,"assigns":{"overlay":1}
,"windows":{"display":1}
,"controller":{"display":1,"please":1}
,"unblank":{"display":1}
,"stop":{"x11":1,"gdm":1,"display":1,"recording":1,"playback":1}
,"systemctl":{"stop":1}
,"loginctl":{"terminate-seat":1}
,"terminate-seat":{"seat0":1}
,"introduction":{"overlay":1}
,"please":{"refer":1}
,"tegra":{"technical":1,"libnvgbm.so":1}
,"technical":{"reference":1}
,"manual":{"trm":1}
,"six":{"overlays":1}
,"overlays":{"x11":1}
,"disabled":{"occupies":1}
,"occupies":{"window":1}
,"disabling":{"x11":1}
,"helps":{"avoid":1}
,"avoid":{"memory":1,"overwriting":1}
,"contention":{"using":1}
,"non-x11":{"overlay":1}
,"filename_1080p.mp4":{"qtdemux":1}
,"overlay-x":{"100":1,"250":1}
,"overlay-y":{"100":1,"250":1}
,"overlay-w":{"640":1}
,"overlay-h":{"480":1}
,"overlay-depth":{"gst-launch-1.0":1}
,"250":{"overlay-y":1,"overlay-w":1}
,"nveglglessink":{"windowed":1,"winsys":1,"nvmm":1,"max-lateness":1}
,"windowed":{"video":1,"playback":1}
,"nveglglesink":{"default":1,"wayland":1}
,"specific":{"window":1,"gstreamer":1}
,"position":{"dimensions":1,"time":1}
,"dimensions":{"windowed":1,"using":1}
,"filename":{"--window-x":1}
,"--window-x":{"300":1,"--window-y":1}
,"--window-y":{"300":1,"--window-width":1}
,"--window-width":{"500":1,"960":1}
,"500":{"--window-height":1}
,"--window-height":{"500":1,"540":1}
,"nveglglsink":{"wayland":1}
,"backend":{"instead":1}
,"ubuntu":{"16.04":1,"gst-1.16.2":1,"gst_1.16.2":1,"movie.avi":1}
,"16.04":{"support":1}
,"switch":{"wayland":1}
,"xorg":{"start":1}
,"weston":{"using":1,"based":1,"6.0":1,"compositor":1,"--idle-time":1}
,"target\u2019s":{"shell":1}
,"shell":{"performing":1}
,"performing":{"weston":1}
,"first":{"run":1}
,"run":{"gstreamer":1,"application":1}
,"back":{"end":1}
,"end":{"required":1}
,"subsequent":{"runs":1}
,"6.0":{"tegra_drm":1}
,"tegra_drm":{"driver":1}
,"-sf":{"usr":1}
,"usr":{"lib":1}
,"lib":{"aarch64-linux-gnu":1,"pkgconfig":1,"gstreamer-1.0":1}
,"aarch64-linux-gnu":{"tegra":1,"libgbm.so.1":1,"gstreamer-1.0":1}
,"libnvgbm.so":{"usr":1}
,"modprobe":{"tegra-udrm":1}
,"tegra-udrm":{"modeset":1}
,"unset":{"display":1}
,"environment":{"variable":1,"variables":1}
,"create":{"temporary":1,"gst_":1}
,"temporary":{"xdg":1}
,"xdg":{"directory":1,"weston":1,"gst-launch-1.0":1}
,"mkdir":{"tmp":1}
,"tmp":{"xdg":1}
,"chmod":{"700":1}
,"700":{"tmp":1}
,"xdg_runtime_dir":{"tmp":1}
,"winsys":{"wayland":1}
,"connected":{"displays":1}
,"resolution":{"playback":1}
,"illustrates":{"properties":1}
,"conn_id":{"plane_id":1}
,"plane_id":{"set_mode":1}
,"works":{"nvmm":1}
,"buffers":{"renders":1,"queue":1}
,"renders":{"using":1,"video":1}
,"performs":{"better":1,"cuda":1,"pre":1}
,"better":{"nveglglessink":1}
,"starts":{"gstreamer":1}
,"window-x":{"300":1}
,"window-y":{"300":1}
,"window-width":{"512":1}
,"512":{"window-height":1}
,"window-height":{"512":1}
,"operates":{"opencv":1}
,"opencv_nvgstdec":{"enter":1,"--help":1,"application":1,"--file-path":1}
,"utilizes":{"opencv":1}
,"--file-path":{"test_file_h264.mp4":1}
,"procedures":{"video":1}
,"rtsp":{"10.25.20.77:554":1,"source":1}
,"10.25.20.77:554":{"rtsp_contents":1}
,"rtsp_contents":{"video":1}
,"test_file_h264.3gp":{"stats":1}
,"h263":{"amr-wb":1,"amr-nb":1,"aacplus":1,"aac":1}
,"eaac":{"plus":1}
,"transmitting":{"target":1}
,"rtp":{"streaming":1}
,"rtph264pay":{"udpsink":1}
,"udpsink":{"host":1}
,"host":{"127.0.0.1":1}
,"127.0.0.1":{"port":1}
,"8001":{"sync":1}
,"sync":{"false":1}
,"receiving":{"target":1}
,"udpsrc":{"address":1}
,"address":{"127.0.0.1":1}
,"caps":{"\u0027application":1}
,"\u0027application":{"x-rtp":1}
,"x-rtp":{"encoding-name":1}
,"encoding-name":{"string":1}
,"payload":{"int":1}
,"rtph264depay":{"queue":1}
,"allows":{"conversion":1,"perform":1,"choose":1,"simulation":1}
,"conversions":{"described":1}
,"described":{"section":1,"following":1,"below":1}
,"yuy2":{"yvyu":1,"v4l2":1}
,"yvyu":{"nv12":1}
,"nv16":{"nv24":1}
,"gray8":{"bgrx":1,"pipeline":1,"width":1,"videoconvert":1,"nvvidconv":1}
,"bgrx":{"rgba":1}
,"rgba":{"y42b":1,"nvoverlaysink":1,"nvdrmvideosink":1}
,"y42b":{"raw-yuv":1}
,"gst":{"-launch-1.0":1}
,"-launch-1.0":{"videotestsrc":1,"filesrc":1}
,"cpu":{"intensive":1}
,"intensive":{"operation":1}
,"operation":{"software":1,"hardware":1,"nvgstplayer-1.0":1,"re-enable":1}
,"copies":{"involved":1}
,"640x480_30p.mp4":{"qtdemux":1}
,"videoconvert":{"xvimagesink":1,"qos":1,"videoscale":1}
,"720x480_30i_mp.mp4":{"qtdemux":1}
,"commands":{"convert":1,"options":1,"described":1}
,"convert":{"nvidia":1}
,"1280x720_30p.mp4":{"qtdemux":1}
,"cropping":{"gstreamer-1.0":1}
,"crop":{"video":1}
,"left":{"400":1,"arrow":1}
,"400":{"right":1}
,"right":{"1520":1,"diagonal":1,"arrow":1}
,"1520":{"top":1}
,"top":{"200":1}
,"bottom":{"880":1}
,"880":{"nvoverlaysink":1,"nv3dsink":1}
,"transcode":{"gstreamer-1.0":1}
,"transcoding":{"following":1}
,"nvidia-accelerated":{"encode":1}
,"20000000":{"matroskamux":1,"queue":1,"qtmux":1,"h264parse":1,"h265parse":1}
,"mux":{"filesink":1}
,"filename.mebm":{"matroskademux":1}
,"filename.webm":{"matroskademux":1}
,"filename.mkv":{"matroskademux":1}
,"4000000":{"queue":1,"qtmux":1,"oggmux":1}
,"theora":{"encode":1}
,"theoraenc":{"bitrate":1}
,"oggmux":{"name":1}
,"cuda":{"video":1,"post-processing":1,"implementation":1}
,"post-processing":{"gstreamer-1.0":1,"operations":1}
,"plugins":{"nvidia":1,"allow":1}
,"operations":{"decoder-provided":1,"csi":1,"gst-omx":1}
,"decoder-provided":{"egl":1}
,"creation":{"application":1}
,"filename_h264_1080p.mp4":{"qtdemux":1,"--svd":1}
,"videocuda":{"nveglglessink":1,"--svs":1}
,"--svd":{"omxh264dec":1,"chain":1,"avdec_h264":1}
,"--svc":{"videocuda":1,"chain":1,"videoconvert":1}
,"--svs":{"nveglglessink":1,"chain":1,"videoconvert":1}
,"max-lateness":{"--disable-vnative":1}
,"--disable-vnative":{"--no-audio":1}
,"--no-audio":{"--window-x":1}
,"960":{"--window-height":1}
,"pre":{"post":1}
,"post":{"cuda":1}
,"captured":{"decoded":1,"file":1}
,"decoded":{"frames":1,"streams":1}
,"gst-nvivafilter":{"pipeline":1}
,"requires":{"unsetting":1}
,"unsetting":{"display":1}
,"lightdm":{"stopped":1}
,"nvivafilter":{"cuda-process":1}
,"cuda-process":{"true":1}
,"customer-lib-name":{"libnvsample_cudaprocess.so":1}
,"libnvsample_cudaprocess.so":{"\u0027video":1,"library":1,"replaced":1}
,"3840":{"height":1,"2160":1}
,"nvsample_cudaprocess_src.tbz2":{"package":1}
,"library":{"sources":1}
,"sources":{"sample":1}
,"implementation":{"libnvsample_cudaprocess.so":1}
,"replaced":{"custom":1}
,"custom":{"cuda":1,"preview":1}
,"rotation":{"gstreamer-1.0":1,"operations":1,"default":1}
,"flip\u2011method":{"property":1}
,"flip":{"method":1}
,"identity":{"rotation":1}
,"counterclockwise":{"degrees":1,"direction":1,"enter":1}
,"rotate":{"180":1,"video":1}
,"180":{"degrees":1}
,"clockwise":{"degrees":1,"direction":1,"enter":1}
,"horizontal":{"flip":1}
,"upper":{"right":1}
,"diagonal":{"flip":1}
,"vertical":{"flip":1}
,"upper-left":{"diagonal":1}
,"flip-method":{"property":1,"\u0027video":1}
,"degrees":{"counterclockwise":1,"clockwise":1,"enter":1}
,"direction":{"enter":1}
,"scale":{"rotate":1}
,"composition":{"gstreamer-1.0":1,"operations":1}
,"nvcompositor":{"gstreamer-1.0":1,"supports":1,"name":1}
,"dependent":{"gstreamer":1}
,"clear":{"registry":1}
,"registry":{"cache":1}
,"cache":{"file":1}
,"issue":{"gst-inspect-1.0":1}
,".cache":{"gstreamer-1.0":1}
,"composite":{"decoded":1}
,"comp":{"sink_0":1,"filesrc":1}
,"sink_0":{":xpos":1,":ypos":1,":width":1,":height":1}
,":xpos":{"sink_0":1,"sink_1":1,"sink_2":1,"sink_3":1}
,":ypos":{"sink_0":1,"sink_1":1,"sink_2":1,"sink_3":1}
,":width":{"1920":1,"1600":1,"1366":1,"1024":1}
,":height":{"1080":1,"1024":1,"768":1,"576":1}
,"sink_1":{":xpos":1,":ypos":1,":width":1,":height":1}
,"1600":{"sink_1":1}
,"sink_2":{":xpos":1,":ypos":1,":width":1,":height":1}
,"1366":{"sink_2":1}
,"768":{"sink_3":1}
,"sink_3":{":xpos":1,":ypos":1,":width":1,":height":1}
,"filename_h264_1080p_30fps.mp4":{"qtdemux":1}
,"filename_h265_1080p_30fps.mp4":{"qtdemux":1}
,"filename_vp8_1080p_30fps.webm":{"matroskademux":1}
,"filename_vp9_1080p_30fps.webm":{"matroskademux":1}
,"interpolation":{"methods":1,"method":1}
,"methods":{"video":1}
,"choose":{"interpolation":1}
,"method":{"used":1,"scaling":1}
,"interpolation\u2011method":{"property":1}
,"smart":{"default":1}
,"interpolation-method":{"property":1,"\u0027video":1}
,"bilinear":{"interpolation":1}
,"producer":{"example":1,"pipeline":1}
,"nvidia-proprietary":{"nveglstreamsrc":1}
,"nveglstreamsrc":{"nvvideosink":1}
,"nvvideosink":{"gstreamer-1.0":1}
,"allow":{"simulation":1}
,"simulation":{"eglstream":1,"eglimage":1}
,"nvegltransform":{"gstreamer-1.0":1,"nveglglessink":1}
,"build":{"instructions":1,"gstreamer":1,"gst-plugins-base-1.16.2":1,"gst-plugins-good-1.16.2":1,"gst-plugins-bad-1.16.2":1,"gst-plugins-ugly-1.16.2":1}
,"contains":{"gst-install":1}
,"gst-install":{"script":1,"--prefix":1}
,"script":{"install":1}
,"provides":{"procedure":1}
,"procedure":{"building":1}
,"building":{"current":1}
,"versions":{"gstreamer":1}
,"--prefix":{"install_path":1,"home":1}
,"install_path":{"--version":1,"location":1,"lib":1,"bin:$path":1}
,"--version":{"version":1,"1.16.2":1}
,"installing":{"gstreamer":1}
,"home":{"ubuntu":1}
,"gst-1.16.2":{"--version":1,"lib":1,"bin:$path":1}
,"variables":{"following":1}
,"ld_library_path":{"install_path":1,"home":1,"environment":1}
,"path":{"install_path":1,"home":1,"file":1}
,"download":{"latest":1}
,"latest":{"version":1}
,"http":{"gstreamer.freedesktop.org":1,"www.joedoe.com":1,"source":1,"www.logitech.com":1,"www.e-consystems.com":1}
,"gstreamer.freedesktop.org":{"src":1}
,"files":{"need":1,"gst_":1,"directory":1,"runs":1}
,"needed":{"packages":1}
,"packages":{"following":1}
,"build-essential":{"dpkg-dev":1}
,"dpkg-dev":{"flex":1}
,"flex":{"bison":1}
,"bison":{"autotools-dev":1}
,"autotools-dev":{"automake":1}
,"automake":{"liborc-dev":1}
,"liborc-dev":{"autopoint":1}
,"autopoint":{"libtool":1}
,"libtool":{"gtk-doc-tools":1}
,"gtk-doc-tools":{"libgstreamer1.0-dev":1}
,"directory":{"create":1,"version":1,"using":1,"application":1}
,"gst_":{"version":1}
,"copy":{"downloaded":1,"nvidia":1}
,"downloaded":{"tar.xz":1}
,"tar.xz":{"files":1}
,"uncompress":{"tar.xz":1}
,"pkg_config_path":{"environment":1,"home":1}
,"gst_1.16.2":{"lib":1,"plugin":1}
,"gstreamer-1.16.2":{"following":1}
,"gst-plugins-base-1.16.2":{"following":1}
,"libxv-dev":{"libasound2-dev":1}
,"libasound2-dev":{"libtheora-dev":1}
,"libtheora-dev":{"libogg-dev":1}
,"libogg-dev":{"libvorbis-dev":1}
,"gst-plugins-good-1.16.2":{"following":1}
,"libbz2-dev":{"libv4l-dev":1}
,"libv4l-dev":{"libvpx-dev":1}
,"libvpx-dev":{"libjack-jackd2-dev":1}
,"libjack-jackd2-dev":{"libsoup2.4-dev":1}
,"libsoup2.4-dev":{"libpulse-dev":1}
,"obtain":{"build":1}
,"gst-plugins-bad-1.16.2":{"following":1}
,"faad":{"libfaad-dev":1,"min-latency":1}
,"libfaad-dev":{"libfaac-dev":1}
,"gst-plugins-ugly-1.16.2":{"following":1}
,"libx264-dev":{"libmad0-dev":1}
,"libraries":{"gst_1.16.2":1,"include":1}
,"libgstnv":{"libgstomx.so":1}
,"libgstomx.so":{"gst_1.16.2":1}
,"longer":{"supported":1}
,"line":{"options":1,"option":1}
,"options":{"display":1,"except":1,"index":1,"nvarguscamera":1,"supported":1,"enter":1}
,"option":{"information":1}
,"help":{"command":1,"options":1}
,"except":{"gstreamer":1}
,"application\u2019s":{"command-line":1}
,"command-line":{"options":1}
,"notes":{"examples":1}
,"--cus-prev-res":{"1920x1080":1}
,"videotest":{"eglstream":1}
,"1-still":{"2-video":1}
,"framework":{"type":1}
,"bit-rate":{"bytes":1,"control":1}
,"--enc-bitrate":{"4000000":1}
,"pass":{"cbr":1}
,"0-baseline":{"1-main":1}
,"1-main":{"2-high":1}
,"0-jpeg_sw":{"jpegenc":1}
,"jpegenc":{"1-jpeg_hw":1}
,"1-jpeg_hw":{"nvjpegenc":1}
,"0-mp4":{"1-3gp":1}
,"1-3gp":{"2-mkv":1}
,"nvcamtest":{"used":1}
,"color":{"format":1}
,"orientation":{"value":1}
,"coordinates":{"x_pos":1,"index":1}
,"x_pos":{"y_pos":1}
,"y_pos":{"order":1,"width":1}
,"--eglconfig":{"100":1}
,"whitebalance":{"value":1,"levels":1}
,"timeout":{"value":1}
,"saturation":{"value":1}
,"configuration":{"options":1}
,"index":{"coordinates":1,"x_pos":1}
,"--overlayconfig":{"1280":1}
,"video0":{"default":1,"dev":1}
,"chain":{"chain":1,"gstreamer":1,"video":1,"described":1,"audio":1,"http":1,"rtsp":1,"udp":1,"file":1}
,"specifies":{"chain":1,"track":1}
,"adjust":{"exposure":1,"gain":1,"digital":1,"temporal":1,"edge":1}
,"exposure":{"time":1,"compensation":1,"antibanding":1,"whitebalance":1}
,"time":{"range":1,"run":1,"queue":1,"seconds":1,"start":1}
,"--exposuretimerange":{"34000":1}
,"34000":{"358733000":1}
,"gain":{"range":1}
,"digital":{"gain":1}
,"--ispdigitalgainrange":{"range":1}
,"awb":{"lock":1}
,"-2.0":{"2.0":1}
,"--exposurecompensation":{"0.5":1}
,"auto":{"exposure":1}
,"antibanding":{"mode":1}
,"select":{"temporal":1,"edge":1}
,"noise":{"reduction":1}
,"reduction":{"mode":1,"strength":1}
,"--tnr-strength":{"0.5":1}
,"edge":{"enhancement":1}
,"enhancement":{"mode":1,"strength":1}
,"--ee-strength":{"0.5":1}
,"resolutions":{"nvarguscamera":1}
,"runtime":{"commands":1,"video":1}
,"nvarguscamera":{"described":1}
,"1-image":{"2-video":1}
,"1-rotate":{"counter-clockwise":1}
,"counter-clockwise":{"degrees":1}
,"2-rotate":{"180":1}
,"3-rotate":{"clockwise":1}
,"white":{"balance":1}
,"balance":{"mode":1}
,"0-off":{"1-auto":1}
,"1-auto":{"2-incandescent":1}
,"2-incandescent":{"3-fluorescent":1}
,"3-fluorescent":{"4-warm-fluorescent":1}
,"4-warm-fluorescent":{"5-daylight":1}
,"5-daylight":{"6-cloudy-daylight":1}
,"6-cloudy-daylight":{"7-twilight":1}
,"7-twilight":{"8-shade":1}
,"8-shade":{"9-manual":1}
,"0-2":{"e.g":1}
,"delay":{"delay":1,"e.g":1}
,"jx5000":{"capture":1}
,"5-second":{"delay":1}
,"succession":{"e.g":1}
,"j:6":{"capture":1}
,"recording":{"video":1}
,"snapshot":{"recording":1}
,"pcr":{"value":1}
,"0-176x144":{"1-320x240":1}
,"1-320x240":{"2-640x480":1}
,"2-640x480":{"3-1280x720":1}
,"cdn":{"value":1}
,"video1":{"dev":1}
,"gets":{"encoding":1}
,"forces":{"idr":1}
,"generates":{"image":1}
,"filenames":{"image":1}
,"content":{"formats":1}
,"nvcamtest_":{"pid":1}
,"pid":{"sensor_id":1,"process":1}
,"sensor_id":{"counter":1,"sensor":1}
,"counter":{".jpg":1,".mp4":1,"counter":1,"starting":1}
,"every":{"time":1}
,"rename":{"move":1}
,"move":{"files":1}
,"runs":{"avoid":1}
,"overwriting":{"results":1}
,"results":{"want":1}
,"want":{"save":1}
,"native":{"capture":1,"audio":1,"video":1}
,"advanced":{"features":1}
,"zoom":{"brightness":1}
,"brightness":{"exposure":1}
,"nvgstplayer":{"command":1,"runtime":1}
,"list":{"supported":1}
,"description":{"example":1}
,"--urifile":{"path":1}
,"containing":{"uris":1}
,"--uri":{"uri":1}
,"-uri":{"file":1,"http":1}
,"www.joedoe.com":{"foo.ogg":1}
,"--elemfile":{"path":1}
,"may":{"contain":1}
,"contain":{"audio":1}
,"processing":{"elements":1}
,"elements":{"chain":1,"apply":1,"separated":1}
,"pipe":{"alsasink":1}
,"times":{"play":1}
,"play":{"media":1,"uri":1,"video":1}
,"multiple":{"audio":1,"video":1,"csi":1}
,"tracks":{"specifies":1}
,"track":{"number":1}
,"--start":{"seconds":1}
,"point":{"start":1}
,"seconds":{"beginning":1,"automatic":1,"start":1,"relative":1}
,"beginning":{"media":1}
,"media":{"segment":1,"playing":1}
,"--duration":{"seconds":1}
,"duration":{"playback":1}
,"disable":{"sync":1,"dpms":1,"audio":1,"video":1,"native":1}
,"unconditionally":{"disable":1}
,"dpms":{"screenblanking":1}
,"screenblanking":{"during":1}
,"during":{"operation":1}
,"re-enable":{"exit":1}
,"operate":{"stealth":1,"background":1}
,"stealth":{"mode":1}
,"staying":{"alive":1}
,"alive":{"even":1}
,"even":{"media":1}
,"background":{"mode":1}
,"ignoring":{"keyboard":1}
,"keyboard":{"input":1}
,"playbin":{"gstreamer":1}
,"decodebin":{"property":1}
,"emit":{"gst_message_buffering":1}
,"gst_message_buffering":{"based":1}
,"percent":{"thresholds":1,"duration":1}
,"--low-percent":{"percent":1}
,"threshold":{"buffering":1}
,"buffering":{"start":1,"finish":1}
,"--high-percent":{"percent":1}
,"finish":{"percent":1}
,"uri":{"endless":1}
,"endless":{"loop":1}
,"--max-size-time":{"seconds":1}
,"maximum":{"time":1,"amount":1,"number":1}
,"amount":{"memory":1}
,"coordinate":{"player":1}
,"player":{"window":1}
,"non-overlay":{"rendering":1}
,"non-full-screen":{"mode":1}
,"--image-display-time":{"seconds":1}
,"tags":{"metadata":1}
,"statistics":{"enabled":1}
,"dump":{"stream":1}
,"--sad":{"chain":1,"aacparse":1}
,"--sac":{"chain":1,"audioconvert":1}
,"--sas":{"chain":1,"audioconvert":1}
,"--shttp":{"chain":1}
,"--srtsp":{"chain":1}
,"--sudp":{"chain":1}
,"udp":{"source":1}
,"--sfsrc":{"chain":1}
,"function":{"value":1}
,"separated":{"element":1}
,"valid":{"instances":1}
,"instances":{"chain":1}
,"avdec_h264":{"skip-frame":1}
,"skip-frame":{"output-corrupt":1}
,"output-corrupt":{"false":1}
,"aacparse":{"faad":1}
,"min-latency":{"4000000":1}
,"qos":{"videoscale":1}
,"videoscale":{"ximagesink":1}
,"ximagesink":{"sync":1}
,"osssink":{"device":1}
,"dsp1":{"latency-time":1}
,"latency-time":{"20000":1}
,"next":{"track":1}
,"restart":{"current":1}
,"down":{"arrow":1}
,"previous":{"track":1}
,"query":{"position":1,"duration":1}
,"seek":{"seconds":1,"pct":1,"backward":1,"forward":1}
,"pct":{"percent":1}
,"shift":{"seconds":1}
,"relative":{"current":1}
,"backward":{"seconds":1}
,"forward":{"seconds":1}
,"pause":{"playback":1}
,"resume":{"playback":1}
,"single":{"uri":1}
,"gstreamer-1.0-based":{"gst-omx":1,"gst-v4l2":1}
,"encoders":{"support":1}
,"slice-header":{"spacing":1}
,"via":{"csi":1}
,"bayer":{"capture":1}
,"simultaneous":{"capture":1}
,"cameras":{"support":1}
,"validated":{"using":1,"sdr":1,"jetson":1}
,"nvgstcapture":{"application":1,"app":1}
,"sdr":{"pwl":1}
,"pwl":{"hdr":1}
,"hdr":{"dol":1,"modes":1}
,"dol":{"hdr":1}
,"various":{"sensors":1}
,"sensors":{"using":1}
,"mipi":{"csi":1}
,"channel":{"feature":1,"unique":1,"identifier":1}
,"feature":{"virtual":1}
,"unique":{"channel":1}
,"identifier":{"used":1}
,"multiplexed":{"sensor":1}
,"sharing":{"csi":1}
,"brick":{"csi":1}
,"gmsl":{"gigabit":1,"capture":1,"module":1}
,"gigabit":{"multimedia":1}
,"multimedia":{"serial":1}
,"serial":{"link":1}
,"link":{"aggregators":1}
,"module":{"max9295-serializer":1}
,"max9295-serializer":{"max9296-deserializer":1}
,"max9296-deserializer":{"imx390-sensor":1}
,"imx390-sensor":{"used":1}
,"validation":{"purposes":1}
,"2.0":{"cameras":1,"ports":1}
,"platforms":{"running":1}
,"running":{"jetson":1}
,"ports":{"camera":1}
,"uvc":{"compliant":1}
,"logitech":{"c920":1}
,"www.logitech.com":{"en-in":1}
,"en-in":{"product":1}
,"product":{"hd-pro-webcam-c920":1}
,"industrial":{"camera":1}
,"3.0":{"industrial":1}
,"www.e-consystems.com":{"ultrahd-usb-camera.asp":1}
,"fps":{"4224":1,"cannot":1}
,"4224":{"3156":1}
,"3156":{"fps":1}
,"purpose":{"embedded":1}
,"embedded":{"navigation":1}
,"test":{"using":1}
,"issues":{"encountered":1}
,"cannot":{"fixed":1,"changed":1}
,"fixed":{"changes":1}
,"changes":{"based":1}
,"changed":{"needs":1}
,"needs":{"payment":1}
,"payment":{"vendor":1}
,"vendor":{"support":1}
,"added":{"firmware":1}
}
;Search.control.loadWordPairs(pairs);
