var pairs =
{
"binary":{"shader":1,"program":1,"loaded":1,"compiled":1,"exists":1,"cache":1}
,"shader":{"program":1,"programs":1,"compiler":1,"cache":1,"driver":1}
,"program":{"management":1,"instead":1,"binaries":1,"application":1,"saves":1}
,"programs":{"ordinarily":1,"glslc":1,"run":1,"application":1,"store":1,"need":1,"cache":1,"available":1}
,"ordinarily":{"stored":1}
,"stored":{"source":1}
,"source":{"form":1,"current":1}
,"form":{"compiled":1,"subdirectory":1}
,"compiled":{"linked":1,"program":1,"source":1,"new":1}
,"linked":{"opengl":1,"programs":1,"program":1}
,"opengl":{"driver":1,"api":1,"3.0":1,"2.0":1}
,"driver":{"application":1,"save":1,"l4t":1,"maintains":1,"searches":1,"binary":1,"installed":1,"disables":1,"version":1,"hashed":1,"cannot":1,"sometimes":1,"updated":1}
,"application":{"first":1,"uses":1,"control":1,"save":1,"requests":1,"runs":1,"whenever":1,"test":1,"read-only":1,"addition":1,"keep":1,"direct":1}
,"first":{"uses":1}
,"uses":{"making":1,"precompiled":1}
,"making":{"opengl":1}
,"api":{"calls":1,"automatic":1}
,"precompile":{"shader":1}
,"glslc":{"offline":1}
,"offline":{"shader":1}
,"compiler":{"eliminates":1,"libraries":1,"driver":1,"portion":1}
,"eliminates":{"need":1}
,"need":{"compile":1,"compiled":1,"recompile":1,"replaced":1}
,"compile":{"shader":1}
,"run":{"time":1,"programs":1,"application":1}
,"time":{"shader":1,"resources":1,"application":1,"new":1}
,"precompiled":{"opengl":1,"shader":1}
,"save":{"additional":1,"load":1,"binaries":1}
,"additional":{"time":1,"link":1}
,"resources":{"loading":1}
,"loading":{"compiler":1,"shader":1,"critical":1}
,"control":{"binary":1}
,"management":{"directly":1}
,"directly":{"glgetprogrambinary":1,"calling":1,"furthermore":1,"instance":1}
,"glgetprogrambinary":{"function":1}
,"function":{"added":1,"loads":1,"opengl":1}
,"added":{"opengl":1}
,"3.0":{"read":1,"driver":1}
,"read":{"back":1,"write":1}
,"back":{"binaries":1}
,"binaries":{"compiled":1,"unlike":1,"either":1,"opengl":1,"compiles":1,"directly":1,"recompiled":1,"need":1}
,"store":{"later":1}
,"later":{"glprogrambinary":1}
,"glprogrambinary":{"function":1,"operates":1}
,"loads":{"saved":1,"binary":1}
,"saved":{"binaries":1}
,"unlike":{"glshaderbinary":1}
,"glshaderbinary":{"function":1}
,"2.0":{"glprogrambinary":1}
,"operates":{"linked":1}
,"instead":{"individual":1}
,"individual":{"vertex":1}
,"vertex":{"fragment":1}
,"fragment":{"shaders":1}
,"shaders":{"additional":1,"internally":1,"search":1}
,"link":{"step":1}
,"step":{"required":1}
,"required":{"binary":1}
,"load":{"compiled":1,"others":1}
,"either":{"directly":1}
,"calling":{"opengl":1}
,"automatic":{"shader":1}
,"cache":{"described":1,"shader":1,"support":1,"file":1,"binary":1,"otherwise":1,"persists":1,"enabled":1,"placed":1,"setting":1,"create":1,"kept":1,"made":1,"contains":1,"read-only":1,"directory":1,"directory\u2019s":1,"specify":1,"handled":1,"eliminates":1,"load":1,"manager":1}
,"described":{"below":1,"above":1}
,"l4t":{"supports":1}
,"supports":{"nvidia":1}
,"nvidia":{"proprietary":1}
,"proprietary":{"shader":1}
,"support":{"enabled":1}
,"enabled":{"driver":1,"default":1,"generated":1}
,"maintains":{"shader":1}
,"file":{"program":1}
,"requests":{"shader":1}
,"searches":{"cache":1}
,"current":{"versions":1}
,"versions":{"compiler":1}
,"exists":{"loads":1}
,"otherwise":{"compiles":1}
,"compiles":{"program":1,"run":1}
,"saves":{"binary":1}
,"persists":{"application":1}
,"runs":{"thorough":1}
,"thorough":{"initial":1}
,"initial":{"run":1}
,"new":{"driver":1,"version":1}
,"default":{"read":1,"cache":1,".nv":1}
,"write":{"filesystems":1,"access":1}
,"filesystems":{"assign":1}
,"assign":{"environment":1}
,"environment":{"variable":1,"variables":1}
,"variable":{"__gl_shader_disk_cache":1,"__gl_shader_disk_cache_path":1}
,"__gl_shader_disk_cache":{"value":1}
,"value":{"disable":1}
,"disable":{"cache":1}
,"placed":{".nv":1}
,".nv":{"directory":1}
,"directory":{"created":1,"exist":1,"default":1,"desired":1}
,"created":{"already":1}
,"already":{"exist":1}
,"exist":{"specify":1,"driver":1}
,"specify":{"different":1,"location":1}
,"different":{"location":1}
,"location":{"cache":1,"target":1}
,"setting":{"environment":1}
,"__gl_shader_disk_cache_path":{"directory\u2019s":1}
,"directory\u2019s":{"pathname":1,"permissions":1}
,"pathname":{"specified":1}
,"specified":{"directory":1}
,"disables":{"cache":1}
,"create":{"missing":1}
,"missing":{"directory":1}
,"wherever":{"cache":1}
,"kept":{"takes":1}
,"takes":{"form":1}
,"subdirectory":{"named":1}
,"named":{"glcache":1}
,"glcache":{"contains":1}
,"contains":{"files":1,"precompiled":1}
,"files":{"hashed":1,"encode":1}
,"hashed":{"names":1}
,"names":{"files":1,"change":1}
,"encode":{"driver":1}
,"version":{"gpu":1,"driver":1}
,"gpu":{"application":1}
,"whenever":{"install":1}
,"install":{"new":1}
,"change":{"users":1}
,"users":{"may":1}
,"may":{"want":1}
,"want":{"remove":1}
,"remove":{"old":1}
,"old":{"directories":1}
,"directories":{"running":1}
,"running":{"applications":1}
,"application\u2019s":{"shader":1}
,"made":{"read-only":1}
,"read-only":{"cache":1,"access":1}
,"cannot":{"save":1}
,"test":{"development":1}
,"development":{"system":1}
,"system":{"whose":1}
,"whose":{"filesystem":1}
,"filesystem":{"write":1}
,"copy":{"cache":1,"operations":1}
,"desired":{"location":1}
,"target":{"image":1}
,"permissions":{"give":1}
,"give":{"application":1}
,"variables":{"described":1}
,"above":{"enable":1}
,"enable":{"cache":1}
,"comparison":{"combination":1}
,"main":{"advantage":1}
,"advantage":{"using":1}
,"using":{"shader":1}
,"handled":{"automatically":1}
,"automatically":{"transparently":1}
,"transparently":{"application":1}
,"addition":{"driver":1}
,"sometimes":{"generates":1}
,"generates":{"shaders":1}
,"internally":{"certain":1}
,"certain":{"clear":1}
,"clear":{"copy":1}
,"operations":{"cache":1}
,"generated":{"once":1}
,"once":{"rather":1}
,"rather":{"time":1}
,"although":{"cache":1}
,"recompile":{"shaders":1}
,"search":{"maintenance":1}
,"maintenance":{"overhead":1}
,"overhead":{"applications":1,"saving":1}
,"applications":{"avoid":1}
,"avoid":{"overhead":1}
,"saving":{"loading":1}
,"furthermore":{"cached":1}
,"cached":{"binaries":1}
,"recompiled":{"time":1}
,"installed":{"saved":1}
,"replaced":{"compiler":1}
,"portion":{"driver":1}
,"keep":{"shader":1}
,"others":{"directly":1}
,"instance":{"application":1}
,"direct":{"loading":1}
,"critical":{"shader":1}
,"available":{"soon":1}
,"soon":{"possible":1}
,"possible":{"startup":1}
,"startup":{"rely":1}
,"rely":{"cache":1}
,"manager":{"less":1}
,"less":{"frequently":1}
,"frequently":{"used":1}
,"used":{"shaders":1}
}
;Search.control.loadWordPairs(pairs);
