var pairs =
{
"jetson":{"agx":1,"linux":1,"xavier":1,"tx1":1,"tx2":1,"download":1,"gpio":1,"module":1,"safety":1,"p2822":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"developer":1,"memory":1,"industrial":1,"jetson":1,"module":1,"users":1,"pinmux":1,"16gb":1,"six":1,"default":1,"specific":1,"designed":1,"technical":1,"p2822":1,"xhci":1,"j512":1,"xudc":1,"oem":1}
,"series":{"adaptation":1,"mb1":1,"pinmux":1,"support":1}
,"adaptation":{"bring-up":1}
,"topic":{"describes":1,"board":1,"vendor":1,"substitute":1,"kernel":1}
,"describes":{"port":1,"camera":1,"usb":1,"whether":1}
,"port":{"nvidia":1,"number":1,"index":1,"base":1,"pin":1,"kernel":1,"available":1,"nine":1,"according":1,"numbers":1,"capability":1,"usb2":1,"port":1,"mapped":1,"usb3":1,"using":1,"speed":1,"p2822":1,"node":1,"usb":1,"switch":1,"adds":1,"separate":1,"switching":1,"controlled":1,"operating":1,"defined":1,"j512":1,"host-only":1,"except":1,"transitions":1,"plus":1,"transition":1}
,"nvidia":{"jetson":1,"board":1,"reference":1,"customization":1,"platform":1,"soc":1,"tegra19x-pcie.txt":1,"team":1,"designing":1,"function":1,"usb2-companion":1,"oc-pin":1,"usb3-gen1-only":1,"xusb-padctl.txt":1,"boost_cpu_freq":1,"boost_cpu_trigger":1,"xusb-padctl":1,"tegra-xhci.txt":1,"tegra-xudc.txt":1}
,"linux":{"driver":1,"kernel":1,"root":1,"rootfs":1}
,"driver":{"package":1,"xhci":1,"xudc":1,"jetson":1,"source":1,"usb":1,"thus":1,"hence":1,"node":1}
,"package":{"l4t":1,"directory":1,"package":1,"available":1}
,"l4t":{"nvidia":1,"standard":1}
,"developer":{"kit":1}
,"kit":{"hardware":1,"p2972":1,"consists":1,"som":1,"ttp":1,"thermal":1,"code":1,"board":1,"nvidia":1,"carrier":1,"role":1}
,"hardware":{"platform":1,"applied":1,"nvidia":1,"design":1}
,"platform":{"applies":1,"configuration":1,"example":1,"supported":1,"modify":1,"t19x":1,"tegra":1}
,"applies":{"modules":1}
,"modules":{"members":1}
,"members":{"jetson":1}
,"p2888-0001":{"jetson":1}
,"p2888-0004":{"jetson":1}
,"p2888-0008":{"jetson":1}
,"examples":{"described":1,"valid":1,"based":1}
,"described":{"include":1,"above":1,"xhci":1}
,"include":{"code":1,"configuration":1,"hyphens":1,"version":1,"regulator":1,"statements":1,"configuring":1,"entry":1}
,"code":{"jetson":1,"without":1,"supports":1,"device":1,"nvtbootwb0.bin":1}
,"information":{"customizing":1,"enable":1,"file":1,"jetson":1,"consult":1,"xusb_padctl":1,"xhci":1,"state":1,"extcon":1,"ucsi_ccg":1,"xudc":1}
,"customizing":{"configuration":1}
,"configuration":{"files":1,"modifications":1,"odm":1,"include":1,"new":1,"boot":1,"kernel":1,"changes":1,"hardware":1,"tables":1,"applied":1,"download":1,"board":1,"file":1,"code":1,"bringup":1,"part":1,"device":1}
,"files":{"topics":1,"nvidia":1,"customer":1,"define":1,"disabling":1,"describe":1,"available":1,"referenced":1,"may":1,"overrides":1,"based":1,"already":1,"name":1}
,"topics":{"jetson":1,"include":1}
,"mb1":{"platform":1,"configuration":1,"boot":1}
,"board":{"configuration":1,"part":1,"eeprom":1,"saved":1,"p2822":1,"instead":1,"required":1,"naming":1,"assign":1,"combination":1,"represents":1,"name":1,"board":1,"names":1,"version":1,"schematic":1,"change":1,"translate":1,"configurations":1,"custom":1,"additionally":1,"modified":1,"consequently":1,"modify":1,"designed":1,"verify":1,"consulting":1,"design":1,"find":1,"controlled":1,"supports":1,".conf":1,"mmcblk0p1":1}
,"consists":{"p2888":1}
,"p2888":{"system":1,"som":1}
,"system":{"module":1,"platform":1,"update":1,"assumes":1}
,"module":{"som":1,"shipped":1,"carrier":1,"name":1,"earlier":1,"registers":1}
,"som":{"connected":1,"carrier":1,"used":1,"sold":1,"table":1,"connector":1,"gpio":1,"socket":1}
,"connected":{"p2822":1,"pcie":1,"pin":1,"cable":1,"remains":1,"vbus_detect":1,"logical":1,"boot":1,"property":1}
,"p2822":{"b03":1,"change":1,"eeprom":1,"carrier":1,"custom":1}
,"b03":{"revision":1}
,"revision":{"carrier":1}
,"carrier":{"board":1,"board\u2019s":1}
,"part":{"number":1,"developer":1,"jetson":1,"device-tree":1}
,"number":{"p2972":1,"a00":1,"files":1,"slvs_hsync":1,"blocks":1,"entries":1,"outputs":1,"describes":1,"number":1,"integer":1,"cells":1}
,"p2972":{"designates":1,"name":1}
,"designates":{"complete":1}
,"complete":{"jetson":1}
,"eeprom":{"board":1,"custom":1,"parameters":1,"value":1}
,"saved":{"som":1}
,"used":{"without":1,"throughout":1,"uphy":1,"controller":1,"p2822":1}
,"without":{"software":1,"selecting":1,"jetson":1}
,"software":{"configuration":1,"supports":1}
,"sold":{"incorporation":1}
,"incorporation":{"customer":1}
,"customer":{"products":1,"platforms":1,"usage":1}
,"products":{"thermal":1}
,"thermal":{"transfer":1,"solution":1}
,"transfer":{"plate":1}
,"plate":{"ttp":1}
,"ttp":{"ready":1,"instead":1}
,"ready":{"accept":1,"removed":1}
,"accept":{"customer-provided":1}
,"customer-provided":{"thermal":1}
,"solution":{"module":1,"designed":1,"removed":1}
,"shipped":{"part":1}
,"instead":{"thermal":1,"p2822":1}
,"designed":{"specifically":1,"carrier":1,"verified":1,"support":1,"internal":1}
,"specifically":{"developer":1}
,"removed":{"module":1}
,"using":{"som":1,"board":1,"script":1,"p2888":1,"value":1}
,"change":{"kernel":1,"pinmux":1,"detected":1}
,"kernel":{"device":1,"proc":1,"pinmux":1,"messages":1,"configuration":1,"customization":1,"document":1,"kernel-4.9":1,"kernel4.9":1,"zimage":1}
,"device":{"tree":1,"holds":1,"gpiochip0":1,"gpiochip1":1,"tree\u2019s":1,"port":1,"a-plug":1,"b-plug":1,"driver":1,"drivers":1,"wake":1,"node":1,"tree\u0027s":1,"mode":1,"sector":1,"emmc":1}
,"tree":{"mb1":1,"filenames":1,"platform":1,"documentation":1,"changes":1,"examples":1,"structure":1,"file":1}
,"odm":{"data":1}
,"data":{"flashing":1,"based":1,"transfer":1,"limit":1}
,"flashing":{"configuration":1,"build":1,"script":1,"process":1}
,"new":{"carrier":1,"dtb":1}
,"custom":{"board":1,"carrier":1}
,"support":{"jetson":1,"gen4":1,"dual":1,"aspm":1,"four":1,"multiple":1,"configurations":1,"usb":1,"contain":1,"contains":1,"phandle":1}
,"assign":{"module":1}
,"combination":{"lower":1}
,"lower":{"case":1}
,"case":{"alphanumeric":1,"letters":1}
,"alphanumeric":{"name":1}
,"name":{"name":1,"may":1,"select":1,"exposed":1,"character":1,"board":1,"obvious":1,"selected":1,"jetson":1,"organization":1,"vendor":1,"parameter":1,"function":1,"extcon":1,"output":1,"vbus_id":1,"subnode":1,"flashing":1,"mts_si":1,"mts_preboot_si":1}
,"may":{"include":1,"power-tree":1,"modified":1,"different":1}
,"hyphens":{"underscores":1}
,"underscores":{"spaces":1}
,"spaces":{"examples":1}
,"valid":{"names":1,"gpios":1}
,"select":{"appears":1,"similarly-constructed":1}
,"filenames":{"pathnames":1}
,"user-visible":{"device":1}
,"additionally":{"name":1,"update":1}
,"exposed":{"user":1}
,"user":{"various":1}
,"various":{"linux":1}
,"proc":{"files":1}
,"represents":{"board":1,"vendor":1,"type-c":1}
,"similarly-constructed":{"vendor":1}
,"vendor":{"name":1,"represents":1,"board":1}
,"character":{"rules":1}
,"rules":{"apply":1}
,"apply":{"following":1}
,"following":{"example":1,"steps":1,"formula":1,"section":1,"line":1,"two":1,"diagram":1,"odd-numbered":1,"environment":1,"command":1}
,"re-use":{"modify":1}
,"modify":{"existing":1,".dts":1,"distributed":1}
,"existing":{"nvidia":1}
,"selecting":{"using":1}
,"obvious":{"jetson":1}
,"users":{"whether":1}
,"whether":{"modified":1,"limit":1}
,"modified":{"source":1,"emmc":1,"reflect":1}
,"source":{"code":1,"ldk_dir":1}
,"supports":{"original":1,"configurations":1,"usb3.1":1,"notifier":1,"usb":1}
,"original":{"jetson":1}
,"placeholders":{"porting":1,"used":1}
,"porting":{"instructions":1,"linux":1,"usb":1}
,"throughout":{"topic":1}
,"substitute":{"appropriate":1}
,"appropriate":{"value":1,"targeted":1}
,"value":{"placeholder":1,"emmc":1,"positive":1,"cpu":1,"extcon-gpio-states":1,"array":1,"represents":1,"greater":1}
,"placeholder":{"executing":1}
,"executing":{"commands":1}
,"function":{"functional":1,"wdt_reset_out_n":1,"string":1,"mux":1,"xusb":1}
,"functional":{"module":1}
,"power-tree":{"pinmux":1}
,"pinmux":{"sdmmc-drv":1,"changes":1,"configuration":1,"table":1,"settings":1,"t19x":1,"function":1}
,"sdmmc-drv":{"keys":1}
,"keys":{"comm":1}
,"comm":{"wi-fi":1}
,"wi-fi":{"bluetooth":1,"connected":1}
,"bluetooth":{"camera":1}
,"selected":{"represent":1}
,"represent":{"platform":1}
,"example":{"p2972":1,"check":1,"remove":1,"host-only":1,"create":1,"otg":1,"extcon":1,"environment":1}
,"names":{"lower":1,"form":1}
,"version":{"board":1,"number":1,"table":1}
,"a00":{"files":1}
,"reference":{"boards":1,"manual":1,"xxx":1}
,"boards":{"include":1}
,"platforms":{"required":1}
,"required":{"include":1,"device":1}
,"organization":{"name":1}
,"root":{"device":1,"file":1,"filesystem":1}
,"holds":{"root":1}
,"file":{"system":1,"generated":1,"configures":1,"replace":1,"used":1,".dtsi":1,"including":1,"check":1,"covers":1,"p2822_b03_concept_schematics.pdf":1,"during":1,"board.conf":1,"flashed":1,"name":1,"sign":1,"encrypt":1,"camera-rtcpu-sce.img":1,"path":1,"reflected":1}
,"supported":{"value":1}
,"camera":{"connector":1}
,"connector":{"pin":1,"pins":1,"example":1,"called":1,"class":1}
,"pin":{"differences":1,"watchdog":1,"gpio3_pq.03":1,"names":1,"group":1,"port":1,"standard":1,"otg":1,"grounded":1,"floating":1,"vbus_detect":1,"gpio_q0":1,"example":1,"pin":1,"designed":1,"pulled":1,"depends":1,"matter":1,"settings":1,"extcon":1}
,"table":{"below":1,"jetson":1,"som":1,"spreadsheet":1,"pinmux":1,"gpio":1,"configuration":1}
,"below":{"describes":1,"translated":1,"reference":1}
,"differences":{"jetson":1}
,"earlier":{"nvidia":1}
,"tx1":{"jetson":1,"tx2":1}
,"tx2":{"modules":1}
,"summary":{"jetson":1}
,"adds":{"four":1,"fifth":1}
,"four":{"additional":1,"enhanced":1}
,"additional":{"csi":1}
,"csi":{"lanes":1,"lane":1,"replaces":1}
,"lanes":{"places":1,"shared":1,"assigned":1,"usb2-1":1,"usb3-0":1,"usb2-0":1,"usb3-2":1}
,"places":{"csi6":1}
,"csi6":{"csi5":1}
,"csi5":{"csi5":1,"moves":1}
,"moves":{"uart":1}
,"uart":{"dmic":1,"spi":1,"present":1}
,"removes":{"1.2v":1,"uart":1,"flash":1,"motion":1}
,"1.2v":{"rails":1,"dvdd_cam_io_1v2":1,"removed":1}
,"rails":{"changes":1}
,"changes":{"3.3v":1,"include":1,"taken":1,"port":1,"device":1}
,"spi":{"dmic":1}
,"dmic":{"i2s":1}
,"flash":{"auto-focus":1,"removed":1,"new":1,"application":1,"server":1,"build":1}
,"auto-focus":{"strobe":1}
,"strobe":{"control":1}
,"motion":{"int":1}
,"int":{"modem":1,"removed":1}
,"modem":{"ready":1}
,"different":{"csi":1,"base":1,"aspm":1,"types":1}
,"replaces":{"uart":1,"spi":1,"dmis":1,"i2s":1}
,"i2c_gp3":{"cam_i2c":1}
,"i2s":{"removed":1}
,"2.8v":{"avdd_cam":1}
,"3.3v":{"vdd_3v3_slp":1,"vdd_3v3":1}
,"functionality":{"removed":1}
,"cam2":{"pwdn":1,"rst":1}
,"pwdn":{"removed":1}
,"rst":{"removed":1}
,"1.8v":{"dvdd_cam_io_1v8":1,"vdd_1v8":1}
,"torch":{"removed":1}
,"modem-ap":{"ready":1}
,"changed":{"3.3v":1}
,"filesystem":{"configuration":1,"rootfs":1,"provided":1}
,"standard":{"customized":1,"usb":1}
,"customized":{"linux":1}
,"rootfs":{"appropriate":1,"configurations":1,"location":1,"size":1,"directory":1}
,"targeted":{"embedded":1}
,"embedded":{"applications":1,"downloads":1,"dlc":1}
,"however":{"certain":1}
,"certain":{"settings":1}
,"settings":{"configured":1,"source":1,"p2822":1,"external":1,"otg":1,"above":1}
,"configured":{"rootfs\u2019s":1,"target":1,"endpoints":1}
,"rootfs\u2019s":{"boot-up":1}
,"boot-up":{"framework":1,"scripts":1}
,"framework":{"default":1}
,"default":{"configuration":1,"pinmux":1,"pcie":1,"u513":1,"values":1,"512byte":1}
,"boot":{"core":1,"time":1,"configuration":1,"expressed":1,"control":1,"partition":1}
,"core":{"functionalities":1}
,"functionalities":{"run":1}
,"run":{"expected":1}
,"nv.sh":{"nvfb.sh":1}
,"nvfb.sh":{"boot-up":1}
,"scripts":{"platform-specific":1}
,"platform-specific":{"configuration":1}
,"xorg":{"libraries":1}
,"libraries":{"correctly":1}
,"correctly":{"configured":1}
,"target":{"device":1,"rootfs":1,"cmdline":1,"machine":1,"board\u0027s":1}
,"nvpmodel":{"clock":1}
,"clock":{"frequency":1}
,"frequency":{"configured":1,"boosted":1,"dvfs":1,"further":1,"pmqos":1}
,"configurations":{"customizations":1,"defined":1,"listed":1,"further":1}
,"customizations":{"provided":1}
,"provided":{"driver":1,"nvidia":1,"external":1,"host":1,"cable":1}
,"directory":{"subdirectories":1,"name":1}
,"linux_for_tegra":{"nv_tegra":1,"apply_binaries.sh":1,"kernel":1,"bootloader":1}
,"incorporate":{"relevant":1}
,"relevant":{"customization":1}
,"customization":{"target":1,"applied":1}
,"sample":{"ubuntu":1}
,"ubuntu":{"root":1,"dmesg":1}
,"applied":{"using":1,"bootloader":1,"software":1,"gpio3_pq.04":1}
,"script":{"linux_for_tegra":1,"uses":1,"updates":1}
,"multiple":{".cfg":1,"types":1}
,".cfg":{"files":1,"instructions":1}
,"define":{"boot":1,"board\u2019s":1,"pinmux":1,"tegra_main_gpio_port_q":1,"board-specific":1}
,"time":{"configuration":1,"milliseconds":1,"passed":1}
,"bootloader":{"mb1":1,"t186ref":1,"-------------":1,"binary":1,"images":1,"spe.bin":1,"nvtboot.bin":1}
,"tables":{"available":1,"released":1}
,"l4t_top":{"bootloader":1}
,"t186ref":{"bct":1}
,"schematic":{"differs":1,"file":1,"conclude":1,"j513":1,"following":1}
,"differs":{"jetson":1}
,"board\u2019s":{"pinmux":1,"requirements":1,"schematic":1}
,"download":{"jetson":1,"center":1}
,"center":{"sure":1}
,"sure":{"right":1}
,"right":{"version":1}
,"spreadsheet":{"provided":1,"available":1,"configuration":1}
,"show":{"locations":1}
,"locations":{"default":1}
,"https":{"developer.nvidia.com":1}
,"developer.nvidia.com":{"embedded":1}
,"customize":{"spreadsheet":1}
,"once":{"done":1}
,"done":{"convert":1}
,"convert":{".dtsi":1}
,".dtsi":{"file":1,"files":1}
,"generated":{"excel":1}
,"excel":{".cfg":1}
,"instructions":{"readme":1}
,"readme":{"file":1}
,"perform":{"conversion":1,"following":1}
,"conversion":{"gpio.dtsi":1}
,"gpio.dtsi":{"padvoltage.dtsi":1}
,"gpio":{"changes":1,"numbers":1,"mapping":1,"number":1,"group":1,"allocation":1,"ports":1,"expander-based":1,"regulator":1,"states":1,"state":1,"corresponds":1}
,"translate":{"som":1}
,"pins":{"actual":1,"connect":1,"usb1_d":1,"usb0_d":1}
,"actual":{"gpio":1}
,"numbers":{"understand":1,"controlled":1,"name":1}
,"understand":{"gpio":1}
,"mapping":{"formula":1,"compatibility":1,"consulting":1}
,"formula":{"below":1,"calculate":1}
,"translated":{"gpio":1}
,"controlled":{"driver":1,"u513":1,"host":1,"cypress":1,"default":1}
,"check":{"gpio":1,"changes":1,"usb":1,"pinmux":1}
,"slvs_hsync":{"perform":1,"jetson":1,"288":1}
,"search":{"slvs_hsync":1,"kernel":1}
,"confirm":{"customer":1,"tegra194-gpio.h":1,"pinmux":1}
,"usage":{"field":1}
,"field":{"applied":1}
,"tegra194-gpio.h":{"gpio3_pq.04":1}
,"gpio3_pq.04":{"belongs":1}
,"belongs":{"main":1,"tegra-gpio":1}
,"main":{"jetson":1}
,"group":{"port":1,"command":1,"xusb":1}
,"registers":{"gpios":1}
,"gpios":{"dynamically":1,"288":1,"248":1,"list":1,"states":1,"provided":1,"&tegra_main_gpio":1}
,"dynamically":{"search":1}
,"messages":{"check":1}
,"allocation":{"ranges":1}
,"ranges":{"gpio":1}
,"command":{"resulting":1,"usage":1}
,"resulting":{"output":1}
,"output":{"similar":1,"above":1,"type":1,"cable":1}
,"similar":{"following":1}
,"root@jetson-p2888a01p0229":{"home":1}
,"home":{"ubuntu":1}
,"dmesg":{"grep":1}
,"grep":{"gpiochip_setup_dev":1}
,"0.894912":{"gpiochip_setup_dev":1}
,"gpiochip_setup_dev":{"registered":1}
,"registered":{"gpios":1}
,"288":{"511":1,"following":1,"420":1}
,"511":{"device":1}
,"gpiochip0":{"tegra-gpio":1}
,"0.904338":{"gpiochip_setup_dev":1}
,"248":{"287":1}
,"287":{"device":1}
,"gpiochip1":{"tegra-gpio-aon":1}
,"shown":{"output":1,"following":1}
,"above":{"two":1,"file":1,"table":1,"j512":1}
,"two":{"jetson":1,"differential":1,"tables":1,"sets":1}
,"ports":{"different":1,"implementations":1,"used":1,"designed":1,"verified":1,"device":1,"describe":1,"form":1,"subnode":1,"p2822":1}
,"base":{"indices":1,"index":1,"tegra_main_gpio_port_":1}
,"tegra-gpio":{"base":1,"group":1}
,"index":{"288":1,"248":1,"step":1,"extcon-gpio":1,"specified":1}
,"tegra-gpio-aon":{"base":1}
,"pq04":{"belongs":1}
,"step":{"base":1}
,"calculate":{"gpio":1}
,"tegra_main_gpio":{"port":1}
,"tegra_main_gpio_port_":{"port":1}
,"hence":{"gpio":1,"extcon":1}
,"pmic":{"changes":1,"configuration":1,"p2888":1,"ddr":1}
,"configures":{"initial":1,"wdt_reset_out":1}
,"initial":{"pmic":1}
,"expander-based":{"gpio":1}
,"regulator":{"settings":1,"information":1,"parameter":1,"corresponding":1}
,"defined":{"review":1,"information":1,"state":1}
,"review":{"configuration":1}
,"replace":{"references":1}
,"references":{"p2822":1}
,"enable":{"file":1,"wdt_reset_out_n":1,"disable":1,"smbus":1}
,"remove":{"following":1}
,"section":{"writing":1,"topic":1,"gives":1,"takes":1,"part":1}
,"writing":{"slave":1}
,"slave":{"i2c":1}
,"i2c":{"controller":1}
,"controller":{"address":1,"state":1,"configuration":1,"based":1,"features":1,"operates":1,"controller":1,"therefore":1,"complies":1,"names":1,"field\u2019s":1,"ucsi_ccg":1,"supports":1}
,"address":{"0x74":1}
,"0x74":{"p2822":1}
,"update":{"number":1,"mb1_bct":1}
,"blocks":{"array":1}
,"array":{"number":1,"byte":1,"contain":1}
,"entries":{"block:tegra194-mb1-bct-pmic-p2888-0001-a04-p2822-0000.cfg":1}
,"pmic.system.block":{".type":1,".controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".block-delay":1,".commands":1}
,".type":{"i2c":1}
,".slave-add":{"0x78":1}
,"0x78":{"7bit:0x3c":1}
,".commands":{".0x53.0x38":1,".0x55.0x38":1,".0x41.0x1c":1}
,".0x53.0x38":{"0x00":1}
,"0x00":{"sd4":1}
,"sd4":{"fps":1}
,"fps":{"slot":1}
,".0x55.0x38":{"0x10":1}
,"0x10":{"gpio2":1}
,"gpio2":{"fps":1}
,".0x41.0x1c":{"0x1c":1}
,"0x1c":{"slpen":1}
,"slpen":{"clrse":1}
,"enabling":{"wdt_reset_out_n":1,"controllers":1}
,"wdt_reset_out_n":{"pin":1}
,"watchdog":{"timeout":1,"expiry":1}
,"gpio3_pq.03":{"wdt_reset_outa":1}
,"add":{"pmc_rst_req_cfg":1}
,"pmc_rst_req_cfg":{"entry":1,"0x3":1,"configures":1}
,"entry":{"e.g":1,"entry":1,"phy-names":1,"phy":1,"usb":1,"entry-of-ucsi_ccg":1,"detects":1}
,"e.g":{"pmc_rst_req_cfg":1,"usb":1}
,"0x3":{"linux_for_tegra":1,"0x0":1}
,"bct":{"tegra194-mb1-bct-misc-l4t.cfg":1,"size":1}
,"wdt_reset_out":{"signal":1,"expiry":1,"software-initiated":1}
,"signal":{"generation":1,"pairs":1,"integrity":1,"pins":1,"pair":1}
,"generation":{"watchdog":1,"enabled":1}
,"bit":{"toggle":1}
,"toggle":{"wdt_reset_out":1}
,"expiry":{"wdt":1,"aowdt":1}
,"software-initiated":{"reset":1}
,"enabled":{"reset":1,"xhci":1,"xudc":1}
,"reset":{"caused":1,"halts":1,"toggled":1}
,"caused":{"wdt":1}
,"wdt":{"aowdt":1}
,"aowdt":{"reset":1}
,"halts":{"booting":1}
,"booting":{"until":1}
,"until":{"rst_in":1}
,"rst_in":{"external":1}
,"external":{"reset":1,"connector":1,"connectors":1,"power":1}
,"reflash":{"whole":1}
,"whole":{"system":1}
,"mb1_bct":{"partition":1}
,"assumed":{"using":1}
,"emmc":{"pmic":1,"boot":1,"boot0":1,"nand":1}
,"ddr":{"routing":1}
,"routing":{"lines":1}
,"lines":{"modifications":1}
,"modifications":{"making":1}
,"making":{"som":1}
,"consequently":{"based":1}
,"based":{"peripherals":1,"feature":1,"galen":1,"synopsis":1,"design":1,"device":1,"need":1,"board":1}
,"peripherals":{"present":1}
,"present":{"carrier":1,"rename":1}
,".dts":{"files":1,".dtsi":1,"final":1}
,"disabling":{"enabling":1}
,"controllers":{"changing":1,"specifications":1,"support":1,"controllers":1}
,"changing":{"supplies":1}
,"distributed":{"configuration":1}
,"describe":{"design":1,"usb2":1}
,"design":{"platform":1,"changes":1,"jetson":1,"files":1,"consider":1,"guide":1}
,"top":{"hardware":1}
,"soc":{"t19x":1,"controller":1}
,"final":{"dtb":1,".dtb":1}
,"dtb":{"file":1,"dts":1}
,"tegra194-p2888-0001-p2822-0000.dtb":{"16gb":1}
,"16gb":{"32gb":1}
,"32gb":{"tegra194-p2888-0008-p2822-0000.dtb":1}
,"tegra194-p2888-0008-p2822-0000.dtb":{"industrial":1}
,"reading":{"above":1}
,"referenced":{"include":1}
,"statements":{"common":1}
,"common":{".dtsi":1,"kernel-dts":1,"properties":1,"tegra194-p2888-0000-a00.dtsi":1,"tegra194-e3366-1199-a00.dtsi":1}
,"reflect":{"hardware":1}
,"types":{"changes":1,"interfaces":1,"cables":1}
,"dtsi":{"filename":1}
,"filename":{"location":1}
,"power":{"supply":1}
,"supply":{"changes":1,"cable":1}
,"parameter":{"changes":1,"description":1}
,"display":{"panel":1,"configuration":1}
,"panel":{"node":1}
,"node":{"changes":1,"follows":1,"property":1,"used":1,"host":1,"host-only":1,"defines":1}
,"details":{"refer":1}
,"refer":{"display":1,"documentation":1,"device":1,"driver":1}
,"bringup":{"section":1}
,"feature":{"configuration":1}
,"state":{"enable":1,"changes":1,"pin":1,"vbus_detect":1,"change":1,"following":1,"otg":1}
,"disable":{"controller":1}
,"t19x":{"kernel-dts":1,"galen":1}
,"kernel-dts":{"tegra194-soc":1,"panels":1,"common":1}
,"panels":{"related":1}
,"related":{".dts":1}
,"tegra":{"common":1}
,"verify":{".dts":1,"uphy":1,"lane":1}
,"including":{".dts":1}
,"overrides":{"changes":1}
,"best":{"practice":1}
,"practice":{"create":1}
,"create":{".dts":1,"pad":1,"xhci":1,"table":1,"extcon":1,"ucsi_ccg":1,"xudc":1}
,"galen":{"files":1,"kernel-dts":1}
,"already":{"present":1}
,"rename":{"newly":1}
,"newly":{"created":1}
,"created":{"files":1}
,"fdtdump":{"dtc":1,"dts":1}
,"dtc":{"generate":1,"dtb":1}
,"generate":{".dts":1}
,".dtb":{"file":1,"dtsfile":1}
,"taken":{"effect":1}
,"dts":{"dtsfile":1}
,"dtsfile":{".dtb":1,".dts":1}
,"industrial":{"without":1,"jetson":1}
,"safety":{"extension":1}
,"extension":{"package":1}
,"available":{"request":1,"jetson":1,"connect":1}
,"pcie":{"controller":1,"host":1,"intellectual":1,"controllers":1,"configuration":1,"slots":1,"slot":1,"card":1,"ufs":1}
,"host":{"controller":1,"device":1,"driver":1,"mode":1,"machine":1}
,"synopsis":{"designware":1}
,"designware":{"pcie":1}
,"intellectual":{"property":1}
,"property":{"thus":1,"values":1,"j512":1,"list":1,"valid":1}
,"thus":{"inherits":1,"extcon-cables":1}
,"inherits":{"common":1}
,"properties":{"defined":1}
,"kernel_top":{"documentation":1}
,"documentation":{"devicetree":1,"file":1}
,"devicetree":{"bindings":1}
,"bindings":{"pci":1,"phy":1,"usb":1,"extcon":1}
,"pci":{"nvidia":1}
,"six":{"pcie":1}
,"speed":{"controllers":1,"link":1,"usb3.1":1,"therefore":1}
,"gen4":{"speed":1}
,"lane":{"width":1,"sharing":1,"mapping":1,"uphy":1,"assignment":1,"lane":1,"assignments":1,"usb3.1":1}
,"dual":{"mode":1}
,"mode":{"configured":1,"m.2":1,"pcie":1,"switch":1,"string":1,"host":1,"otg":1,"detect":1}
,"aspm":{"controllers":1,"states":1}
,"slots":{"available":1}
,"m.2":{"key":1}
,"key":{"controller":1,"form":1,"file":1}
,"operates":{"m.2":1,"esata":1,"mode":1}
,"form":{"factor":1,"type":1,"port-":1}
,"factor":{"nvme":1,"cards":1}
,"nvme":{"cards":1}
,"cards":{"connected":1,"wi-fi":1}
,"esata":{"controller":1,"port":1}
,"connect":{"sata":1,"x16":1,"utmi":1,"uphy":1}
,"sata":{"drive":1}
,"slot":{"controller":1,"x16":1}
,"card":{"connected":1,"operates":1}
,"x16":{"size":1,"card":1}
,"size":{"connect":1,"ppt":1,"default":1,"target":1,"internal":1}
,"specific":{"pcie":1,"board":1,"values":1}
,"covers":{"topics":1}
,"configuring":{"maximum":1,"usb":1}
,"maximum":{"link":1}
,"link":{"speed":1,"width":1}
,"width":{"advertisement":1}
,"advertisement":{"different":1}
,"smbus":{"pcie":1}
,"uncomment":{"following":1}
,"&tegra_main_gpio":{"tegra194_main_gpio":1}
,"tegra194_main_gpio":{"gpio_active_high":1}
,"gpio_active_high":{"i2c":1}
,"usb":{"universal":1,"ports":1,"structure":1,"port":1,"pcie":1,"3.1":1,"connectors":1,"type-c":1,"2.0":1,"nvidia":1,"on-the-go":1,"otg":1,"act":1,"connector":1,"hdmi":1,"typec":1,"pin":1,"vbus":1,"charger":1}
,"universal":{"serial":1,"physical":1}
,"serial":{"bus":1}
,"enhanced":{"superspeed":1}
,"superspeed":{"usb":1,"data":1,"protocols":1}
,"implementations":{"ports":1}
,"uphy":{"lane":1,"handled":1,"lanes":1,"acronym":1,"support":1}
,"sharing":{"among":1}
,"among":{"pcie":1}
,"ufs":{"xusb":1,"uphy":1}
,"xusb":{"jetson":1,"uphy":1}
,"verified":{"three":1,"cases":1}
,"three":{"usb3.1":1}
,"usb3.1":{"ports":1,"differential":1,"signal":1,"port":1,"gen1":1,"type-c":1}
,"compatibility":{"p2822":1}
,"consulting":{"nvidia":1,"jetson":1}
,"nine":{"pins":1}
,"differential":{"signal":1}
,"pairs":{"superspeed":1,"wire":1,"wired":1}
,"ground":{"gnd_drain":1,"logical":1}
,"gnd_drain":{"drain":1}
,"drain":{"wire":1}
,"wire":{"termination":1,"j513":1,"j512":1}
,"termination":{"managing":1}
,"managing":{"emi":1}
,"emi":{"rfi":1}
,"rfi":{"signal":1}
,"utmi":{"pads":1,"pad":1}
,"pads":{"sstx":1,"ports":1,"subnode":1,"usb2":1,"usb3":1}
,"sstx":{"ssrx":1}
,"ssrx":{"signal":1}
,"handled":{"single":1}
,"single":{"uphy":1}
,"shared":{"pcie":1}
,"assigned":{"according":1}
,"according":{"custom":1,"uphy":1,"state":1}
,"acronym":{"universal":1}
,"physical":{"layer":1,"interface":1}
,"layer":{"physical":1,"serve":1}
,"interface":{"layer":1}
,"serve":{"multiple":1}
,"interfaces":{"e.g":1}
,"cases":{"uphy":1}
,"assignments":{"shown":1}
,"uphy_tx0":{"uphy_rx0":1}
,"uphy_tx7":{"uphy_rx7":1}
,"uphy_tx1":{"uphy_rx1":1}
,"uphy_tx8":{"uphy_rx8":1}
,"uphy_tx2":{"uphy_rx2":1}
,"uphy_tx9":{"uphy_rx9":1}
,"uphy_tx3":{"uphy_rx3":1}
,"uphy_tx10":{"uphy_rx10":1}
,"uphy_tx4":{"uphy_rx4":1}
,"uphy_tx11":{"uphy_rx11":1}
,"nvhs":{"7:0":1}
,"uphy_tx6":{"uphy_rx6":1}
,"listed":{"tables":1}
,"released":{"software":1}
,"further":{"information":1,"based":1}
,"consult":{"nvidia":1}
,"technical":{"reference":1}
,"manual":{"trm":1}
,"trm":{"consult":1}
,"designing":{"custom":1}
,"gives":{"step-by-step":1}
,"step-by-step":{"guidance":1}
,"guidance":{"checking":1}
,"checking":{"schematics":1}
,"schematics":{"configuring":1}
,"host-only":{"port":1}
,"takes":{"j513":1,"j512":1}
,"j513":{"usb":1,"lead":1,"p2822":1,"controlled":1,"usb3.1":1,"based":1}
,"3.1":{"type-c":1,"superspeed":1}
,"type-c":{"connector":1,"alt":1,"controller":1,"port":1}
,"p2822_b03_concept_schematics.pdf":{"included":1}
,"included":{"jetson":1}
,"http":{"developer.nvidia.com":1}
,"dlc":{"jetson-xavier-developer-kit-carrier-board-design-files-b03":1}
,"connectors":{"p2822":1,"may":1}
,"find":{"socket":1,"corresponding":1}
,"socket":{"location":1,"u523":1,"u522":1}
,"location":{"wired":1}
,"wired":{"p2888":1,"utmi":1,"uphy":1}
,"screenshot":{"cell":1,"social":1}
,"cell":{"phone":1}
,"phone":{"description":1}
,"description":{"automatically":1,"subnode":1}
,"automatically":{"generated":1}
,"usb2.0":{"signal":1}
,"usb1_d":{"wire":1}
,"lead":{"c10":1,"k16":1,"f12":1,"g22":1}
,"c10":{"usb1_n":1}
,"usb1_n":{"c11":1}
,"c11":{"usb1_p":1}
,"usb1_p":{"som":1}
,"k16":{"uphy_tx6_n":1}
,"uphy_tx6_n":{"k17":1}
,"k17":{"uphy_tx6_p":1}
,"uphy_tx6_p":{"b16":1}
,"b16":{"uphy_rx6_n":1}
,"uphy_rx6_n":{"b17":1}
,"b17":{"uphy_rx6_p":1}
,"uphy_rx6_p":{"som":1}
,"u523":{"usb":1}
,"alt":{"mode":1}
,"social":{"media":1}
,"media":{"post":1}
,"post":{"description":1}
,"conclude":{"j513":1}
,"pair":{"wired":1}
,"pad":{"usb2":1,"&battery_reg":1,"port":1}
,"usb2":{"port":1,"usb3":1,"property":1,"lanes":1}
,"xusb_padctl":{"node":1,"refer":1,"xusb_padctl@3520000":1,"settings":1}
,"tree\u2019s":{"xusb_padctl":1}
,"follows":{"conventions":1}
,"conventions":{"pinctrl-bindings.txt":1}
,"pinctrl-bindings.txt":{"kernel":1}
,"document":{"contains":1}
,"contains":{"two":1,"excon-cable":1}
,"sets":{"groups":1}
,"groups":{"named":1}
,"named":{"pads":1}
,"usb3":{"signals":1,"port_number":1,"property":1,"lanes":1}
,"signals":{"along":1}
,"along":{"parameters":1}
,"parameters":{"port":1,"passed":1,"added":1}
,"subnode":{"pads":1,"names":1}
,"type":{"port_number":1,"usb2":1}
,"port_number":{"type":1,"associated":1}
,"associated":{"port":1}
,"string":{"containing":1,"describes":1}
,"containing":{"name":1}
,"mux":{"pin":1}
,"capability":{"port":1}
,"usb2-companion":{"usb2":1}
,"mapped":{"port":1}
,"oc-pin":{"overcurrent":1}
,"overcurrent":{"vbus":1,"detection":1}
,"vbus":{"pin":1,"regulator":1,"regulators":1,"provided":1}
,"positive":{"zero":1}
,"detection":{"handling":1,"support":1,"driver":1}
,"handling":{"j512":1}
,"j512":{"j513":1,"usb3.1":1,"port":1,"lead":1,"host":1,"based":1}
,"u513":{"cypress":1}
,"cypress":{"type-c":1}
,"therefore":{"need":1,"dummy":1,"nvidia":1,"state":1,"section":1}
,"need":{"property":1,"cpu":1,"boosted":1}
,"vbus-supply":{"vbus":1,"&battery_reg":1}
,"corresponding":{"utmi":1,"gpio":1,"output":1}
,"&battery_reg":{"dummy":1}
,"dummy":{"regulator":1,"regulators":1}
,"regulators":{"j512":1,"ports":1}
,"usb3-gen1-only":{"number":1,"true":1}
,"limit":{"port":1,"max":1}
,"j507":{"esata":1}
,"gen1":{"speed":1}
,"true":{"j507":1,"device":1}
,"detailed":{"information":1}
,"kernel-4.9":{"documentation":1}
,"phy":{"nvidia":1,"used":1,"phy-names":1}
,"list":{"j513":1,"gpios":1,"based":1,"j512":1}
,"structure":{"described":1}
,"status":{"okay":1,"ucsi_ccg":1}
,"xhci":{"node":1,"controller":1,"specifications":1,"refer":1,"device":1,"settings":1}
,"complies":{"xhci":1}
,"specifications":{"support":1}
,"2.0":{"highspeed":1}
,"highspeed":{"fullspeed":1}
,"fullspeed":{"lowspeed":1,"usb":1}
,"lowspeed":{"usb":1}
,"phys":{"contain":1,"xusb_padctl@3520000":1,"array":1}
,"contain":{"entry":1,"pointer":1}
,"phy-names":{"include":1,"usb2-1":1,"usb2-0":1,"array":1,"usb2":1}
,"boost_cpu_freq":{"value":1,"1200":1}
,"cpu":{"frequency":1,"loading":1,"boost":1,"load":1}
,"boosted":{"minimum":1}
,"minimum":{"frequency":1,"buffer":1}
,"dvfs":{"scale":1}
,"scale":{"cpu":1}
,"loading":{"cpu":1}
,"boost":{"frequency":1,"applicable":1}
,"pmqos":{"enabled":1}
,"field\u2019s":{"greater":1,"value":1}
,"greater":{"zero":1}
,"zero":{"boost":1}
,"applicable":{"bulk":1,"large":1}
,"bulk":{"isoc":1,"transfers":1,"endpoints":1}
,"isoc":{"transfers":1}
,"transfers":{"endpoints":1,"beyond":1,"bulk":1}
,"endpoints":{"need":1,"endpoints":1}
,"boost_cpu_trigger":{"minimum":1}
,"buffer":{"length":1}
,"length":{"bulk":1}
,"beyond":{"boost":1}
,"xusb-padctl":{"pointer":1,"node":1,"&xusb_padctl":1}
,"pointer":{"xusb-padctl":1,"excon-cable":1,"node":1}
,"tegra_xhci":{"xhci@3610000":1}
,"xusb_padctl@3520000":{"pads":1}
,"usb2-1":{"usb3-0":1}
,"otg":{"on-the-go":1,"just":1,"specification":1,"port":1,"cable":1,"a-device":1,"support":1}
,"on-the-go":{"port":1,"often":1}
,"often":{"abbreviated":1,"device":1}
,"abbreviated":{"usb":1}
,"just":{"otg":1}
,"specification":{"allows":1}
,"allows":{"usb":1}
,"act":{"host":1}
,"switch":{"back":1,"host":1,"controlled":1}
,"back":{"forth":1}
,"forth":{"roles":1}
,"roles":{"host":1,"j512":1,"otg":1,"controlled":1}
,"fifth":{"pin":1}
,"called":{"pin":1}
,"cable":{"a-plug":1,"connected":1,"states":1,"names":1,"state":1,"entry":1}
,"a-plug":{"end":1,"inserted":1,"connected":1}
,"end":{"b-plug":1,"a-plug\u2019s":1}
,"b-plug":{"end":1,"inserted":1,"connected":1}
,"a-plug\u2019s":{"pin":1}
,"grounded":{"b-plug\u2019s":1}
,"b-plug\u2019s":{"pin":1}
,"floating":{"device":1}
,"inserted":{"becomes":1}
,"becomes":{"otg":1,"b-device":1}
,"a-device":{"host":1}
,"b-device":{"device":1}
,"xudc":{"controlled":1,"defined":1,"roles":1,"modes":1,"node":1,"controller":1,"refer":1}
,"ucsi_ccg":{"driver":1,"node":1,"refer":1,"ucsi_ccg@8":1,"ucsi_ccg":1}
,"usb0_d":{"wire":1}
,"f12":{"usb0_p":1}
,"usb0_p":{"f13":1}
,"f13":{"usb0_n":1}
,"usb0_n":{"som":1}
,"g22":{"uphy_tx1_n":1}
,"uphy_tx1_n":{"g23":1}
,"g23":{"uphy_tx1_p":1}
,"uphy_tx1_p":{"c22":1}
,"c22":{"uphy_rx1_n":1}
,"uphy_rx1_n":{"c23":1}
,"c23":{"uphy_rx1_p":1}
,"uphy_rx1_p":{"som":1}
,"u522":{"usb":1}
,"class":{"extcon":1}
,"cables":{"attached":1}
,"attached":{"usb":1}
,"hdmi":{"analog":1}
,"analog":{"others":1}
,"others":{"often":1}
,"drivers":{"detect":1,"something":1}
,"detect":{"state":1,"status":1}
,"separate":{"device":1}
,"something":{"according":1}
,"extcon":{"introduced":1,"node":1,"device":1,"refer":1,"extcon-gpio-states.txt":1,"specifier":1,"settings":1,"cable":1}
,"introduced":{"2012":1}
,"2012":{"supports":1}
,"notifier":{"passing":1}
,"passing":{"information":1}
,"generally":{"port":1,"pin":1}
,"switching":{"roles":1,"host":1,"port":1}
,"vbus_detect":{"pin":1,"logical":1,"initially":1}
,"taking":{"gpio_m3":1,"j512":1}
,"gpio_m3":{"vbus_detect":1}
,"gpio_q0":{"pin":1,"gpio_m3":1}
,"states":{"vbus_detect":1,"corresponding":1,"gpio":1,"value":1,"gpio_q0":1}
,"internal":{"pull":1,"emmc":1}
,"pull":{"high":1}
,"high":{"logical":1,"a-plug":1}
,"logical":{"high":1,"low":1}
,"pulled":{"ground":1}
,"low":{"b-plug":1,"vbus":1}
,"remains":{"logical":1}
,"operation":{"vbus_detect":1}
,"depends":{"device\u2019s":1}
,"device\u2019s":{"design":1}
,"consider":{"schematic":1}
,"diagram":{"example":1}
,"close":{"map":1}
,"map":{"description":1}
,"initially":{"logical":1}
,"matter":{"otg":1}
,"operating":{"host":1}
,"0x0":{"excon_none":1,"0x2":1}
,"0x2":{"extcon_usb_host":1,"0x1":1}
,"0x1":{"extcon_usb":1,"0x2":1}
,"compatible":{"value":1,"extcon-gpio-states":1}
,"extcon-gpio":{"name":1,"irq-flags":1,"debounce":1,"wait-for-gpio-scan":1,"out-cable-names":1,"cable-states":1}
,"irq-flags":{"irq":1}
,"irq":{"flags":1}
,"flags":{"gpio":1}
,"debounce":{"debounce":1,"time":1}
,"wait-for-gpio-scan":{"wait":1}
,"wait":{"timeout":1}
,"timeout":{"scanning":1}
,"scanning":{"gpios":1}
,"detected":{"debounce":1}
,"out-cable-names":{"output":1,"first":1}
,"cable-states":{"gpio":1,"0x3":1}
,"byte":{"values":1,"gpio":1,"corresponding":1}
,"values":{"even-numbered":1,"variables":1}
,"even-numbered":{"byte":1}
,"odd-numbered":{"byte":1}
,"cable-connected-on-boot":{"name":1}
,"expressed":{"index":1}
,"first":{"element":1}
,"element":{"index":1}
,"specified":{"system":1}
,"assumes":{"cable":1}
,"wakeup-source":{"boolean":1}
,"boolean":{"true":1}
,"wake":{"system":1}
,"device-tree":{"jetson":1}
,"vbus_id_extcon":{"extcon@1":1}
,"extcon_usb":{"extcon_usb_host":1}
,"extcon_usb_host":{"extcon_none":1}
,"tree\u0027s":{"source":1}
,"corresponds":{"pin":1}
,"role":{"switching":1,"jetson":1}
,"modes":{"controlled":1}
,"port-":{"number":1}
,"integer":{"value":1}
,"extcon-cells":{"number":1}
,"cells":{"extcon":1}
,"kernel4.9":{"driver":1}
,"typec":{"ucsi":1}
,"ucsi":{"ucsi_ccg.c":1}
,"typec_port0":{"port-0":1}
,"except":{"mode":1,"addition":1}
,"addition":{"extcon":1}
,"extcon-cables":{"otg":1,"entry":1,"&typec_port0":1}
,"excon-cable":{"entry":1}
,"transitions":{"host":1}
,"entry-of-ucsi_ccg":{"ucsi_ccg":1,"host":1}
,"plus":{"extcon":1}
,"usb2-0":{"usb3-2":1}
,"detects":{"usb":1}
,"transition":{"device":1}
,"extcon-cable-names":{"vbus":1}
,"charger-detector":{"usb":1}
,"charger":{"detection":1}
,"phandle":{"usb":1}
,"defines":{"phy":1}
,"load":{"cpu":1}
,"large":{"bulk":1}
,"tegra_xudc":{"xudc@3550000":1}
,"oem":{"product":1}
,"product":{"design":1}
,"build":{"image":1}
,"image":{"specific":1,"file":1}
,"uses":{"configuration":1}
,".conf":{"file":1}
,"during":{"flashing":1}
,"setting":{"optional":1}
,"optional":{"environment":1}
,"environment":{"variables":1,"variable":1}
,"flash.sh":{"script":1,"board":1}
,"updates":{"following":1}
,"variables":{"based":1,"define":1}
,"passed":{"want":1}
,"want":{"give":1}
,"give":{"specific":1}
,"board-specific":{"file":1}
,"board.conf":{"override":1}
,"override":{"default":1,"eeprom":1}
,"bctfile":{"----------------":1}
,"----------------":{"boot":1,"pass":1,"partition":1,"target":1,"device":1,"flash":1,"static":1,"nfsroot":1,"odmdata":1,"sce":1,"spe":1,"warmboot":1}
,"control":{"table":1}
,"boardid":{"----------------":1,"override":1}
,"pass":{"boardid":1,"board_revision":1,"board_sku":1}
,"boardrev":{"---------------":1}
,"---------------":{"pass":1,"size":1,"flash":1}
,"board_revision":{"override":1}
,"boardsku":{"---------------":1}
,"board_sku":{"override":1}
,"-------------":{"bootloader":1,"mts":1,"linux":1}
,"binary":{"flashed":1}
,"bootpartlimit":{"----------":1}
,"----------":{"gpt":1}
,"gpt":{"data":1}
,"max":{"bct":1}
,"ppt":{"size":1}
,"bootpartsize":{"-----------":1}
,"-----------":{"total":1,"linux":1}
,"total":{"emmc":1}
,"partition":{"size":1,"table":1}
,"cfgfile":{"----------------":1}
,"cmdline":{"----------------":1,"help":1}
,"help":{"information":1}
,"devsectsize":{"------------":1}
,"------------":{"device":1}
,"sector":{"size":1}
,"dtbfile":{"----------------":1}
,"emmcsize":{"---------------":1}
,"boot0":{"boot1":1}
,"boot1":{"user":1}
,"flashapp":{"---------------":1}
,"application":{"running":1}
,"running":{"host":1,"target":1}
,"flasher":{"----------------":1}
,"server":{"running":1}
,"initrd":{"-----------------":1,"image":1}
,"-----------------":{"initrd":1,"rsa":1,"sbk":1}
,"kernel_image":{"-----------":1}
,"zimage":{"file":1}
,"mts":{"--------------------":1,"file":1,"preboot":1}
,"--------------------":{"mts":1,"target":1}
,"mtspreboot":{"-------------":1}
,"preboot":{"file":1}
,"nfsargs":{"----------------":1}
,"static":{"network":1}
,"network":{"assignments":1}
,"c-ipa":{"s-ipa":1}
,"s-ipa":{"g-ipa":1}
,"g-ipa":{"netmask":1}
,"nfsroot":{"----------------":1,"i.e":1}
,"i.e":{"addr":1}
,"addr":{"exported":1}
,"exported":{"rootfs_dir":1}
,"odmdata":{"----------------":1,"used":1}
,"pkckey":{"-----------------":1}
,"rsa":{"key":1}
,"sign":{"bootloader":1}
,"rootfssize":{"-------------":1}
,"rootfs_dir":{"-------------":1}
,"sbkkey":{"-----------------":1}
,"sbk":{"key":1}
,"encrypt":{"bootloader":1}
,"scefile":{"----------------":1}
,"sce":{"firmware":1}
,"firmware":{"file":1}
,"spefile":{"----------------":1}
,"spe":{"firmware":1}
,"path":{"bootloader":1}
,"fab":{"--------------------":1}
,"board\u0027s":{"fab":1}
,"tegraboot":{"--------------":1}
,"--------------":{"lowerlayer":1}
,"lowerlayer":{"bootloader":1}
,"wb0boot":{"----------------":1}
,"warmboot":{"code":1}
,"added":{"below":1}
,"xxx":{".conf.common":1}
,".conf.common":{"file":1}
,"reflected":{"flashed":1}
,"flashed":{"image":1}
,"variable":{"settings":1}
,"ldk_dir":{"p2972-0000.conf.common":1}
,"pinmux_config":{"tegra19x-mb1-pinmux-p2888-0000-a04-p2822-0000-b01.cfg":1}
,"bpfdtb_file":{"tegra194-a02-bpmp-p2888-as-galen-8gb.dtb":1}
,"dtb_file":{"tegra194-p2888-0006-p2822-0000.dtb":1}
,"tbcdtb_file":{"tegra194-p2888-0006-p2822-0000.dtb":1}
,"emmc_bct":{"tegra194-mb1-bct-memcfg-p2888-0006.cfg":1}
,"misc_cold_boot_config":{"tegra194-mb1-bct-misc-l4t-p2888-0006.cfg":1}
,"execute":{"following":1}
,"sudo":{"flash.sh":1}
}
;Search.control.loadWordPairs(pairs);
