var pairs =
{
"over-the-air":{"update":1,"ota":1}
,"ota":{"update":1,"used":1,"lets":1,"payload":1,"debian":1,"updates":1,"packages":1,"further":1,"currently":1,"over-the-air":1,"process":1,"tool":1,"tools":1,"server":1,"client":1,"requires":1,"package":1,"solution":1,"put":1,"ota_payload_package.tar.gz":1,"supports":1,"device":1,"work":1}
,"update":{"enables":1,"nvidia":1,"jetson":1,"full":1,"uses":1,"update":1,"jetpack":1,"system":1,"new":1,"example":1,"minor":1,"packages":1,"failsafe":1,"bsp":1,"old":1,"versions":1,"payload":1,"performed":1,"tool":1,"involves":1,"tot_bsp":1,"release":1,"without":1,"rootfs":1,"process":1,"fails":1,"maximum":1,"determined":1,"log":1,"solution":1,"layout":1,"partition":1,"triggered":1,"procedure":1,"bootloader":1,"kernel":1,"successfully":1,"perform":1,"may":1,"maintains":1,"failure":1,"redundancy":1,"image-based":1,"bootable":1,"script":1,"proceed":1,"located":1,"distributed":1,"payloads":1,"server":1,"found":1,"client":1,"changes":1,"among":1,"two":1,"target":1,"partitions":1,"run":1,"specific":1,"customized":1}
,"enables":{"update":1}
,"nvidia":{"jetson":1,"apt":1,"recommend":1,"updated":1,"provides":1,"recommends":1,"l4t-bootloader-config":1}
,"jetson":{"devices":1,"development":1,"linux":1,"components":1,"device":1,"common":1,"platform":1,"tx2":1,"agx":1,"xavier":1,"nano":1,"tx1":1,"t194":1,"jetson-ota-public.asc":1,"x86_64":1,"web":1}
,"devices":{"host":1,"running":1,"jetson":1}
,"host":{"computers":1,"computer":1,"system\u2019s":1,"packages":1,"apt":1,"machine":1,"system":1}
,"computers":{"jetson":1}
,"linux":{"supports":1,"jetson":1,"update":1,"components":1,"release":1,"enter":1,"officially":1,"support":1,"image-based":1,"feature":1,"bsp":1,"unpack":1,"want":1,"sample":1,"boot":1,"utilities":1}
,"supports":{"two":1,"updates":1,"update":1,"updating":1}
,"two":{"forms":1,"steps":1,"additional":1,"sets":1,"intermediate":1}
,"forms":{"ota":1}
,"used":{"different":1,"create":1,"flashing":1,"boot":1,"separately":1,"update":1,"jetson-tx2-r28_3-r32i-emmc.conf":1,"jetson-tx2-r32a-r32i-emmc.conf":1}
,"different":{"purposes":1,"partition":1}
,"purposes":{"debian":1}
,"debian":{"package":1,"packages":1,"bootloader":1}
,"package":{"management-based":1,"host":1,"yourself":1,"name":1,"click":1,"ota":1,"used":1,"named":1,"includes":1,"signature":1,"ota_tools_":1,"ota_payload_package.tar.gz":1,"contents":1,"trigger":1,"prepares":1,"current":1,"enter":1,"release":1,"unpacked":1,"updating":1,"prepare":1,"default":1,"step":1}
,"management-based":{"ota":1}
,"running":{"jetson":1,"ubuntu":1,"script":1,"nv_update_engine":1,"nv_bootloader_payload_updater":1,"operating":1}
,"components":{"host":1,"installed":1,"new":1,"install":1}
,"computer":{"image-based":1,"running":1,"install":1,"vision":1}
,"image-based":{"ota":1,"over-the-air":1}
,"lets":{"create":1,"overwrite":1}
,"create":{"ota":1,"directory":1,"complete":1,"alternative":1,"customized":1,"file":1}
,"payload":{"packages":1,"file":1,"package":1,"nv_recovery.sh":1,"bup":1}
,"packages":{"update":1,"obtained":1,"purpose":1,"provide":1,"jetson":1,"remote":1,"add":1,"nvidia":1,"maintained":1,"bsp":1,"instructions":1,"jetpack":1,"hosts":1,"contain":1,"help":1,"building":1,"later":1,"store":1,"open":1}
,"full":{"image":1,"release":1,"system":1,"pathname":1}
,"image":{"running":1,"recovery":1,"recovery.img.r32_1_2":1,"option":1,"generated":1,"written":1,"self-generated":1,"example":1,"cloned":1,"line":1,"bl_only_payload":1,"kernel_only_payload":1,"corresponding":1,"customization":1,"file":1,"rootfs":1,"path":1,"specify":1}
,"device":{"partition":1,"running":1,"jetpack":1,"upgrade":1,"host":1,"writing":1,"steps":1,"recovery":1,"fully":1,"apply":1,"add":1,"reboot":1,"reboots":1,"boots":1,"fails":1,"rootfs":1,"rebooted":1,"unbootable":1,"images":1,"node":1,"whose":1}
,"partition":{"partition":1,"topic":1,"layouts":1,"layout":1,"information":1,"customized":1,"inactive":1,"changes":1,"during":1,"addition":1,"called":1,"example":1,"update":1,"updated":1}
,"topic":{"describes":1,"bsp":1,"setting":1,"bootloader":1}
,"describes":{"forms":1,"tools":1,"process":1}
,"updating":{"nvidia":1,"jetson":1,"host":1,"full":1,"bootloader":1,"rootfs":1,"r32.5":1,"version":1,"system":1,"release":1,"partitions":1,"newly":1,"default":1,"individual":1}
,"apt":{"server":1,"update":1,"reads":1,"repository":1,"list":1,"displays":1,"upgrade":1,"source":1,"sources.list.d":1,"dist-upgrade":1,"prompts":1,"download":1,"host":1}
,"first":{"form":1,"step":1}
,"form":{"ota":1,"rmm-n":1,"always":1}
,"uses":{"debian":1,"following":1,"slot":1,"create":1,"two":1,"intermediate":1}
,"obtained":{"nvidia":1}
,"server":{"form":1,"maintains":1,"jetson":1,"download":1,"implement":1,"function":1}
,"jetpack":{"components":1,"installed":1,"jetson":1,"release":1,"documentation":1,"ota":1,"user":1}
,"installed":{"host":1,"instructions":1}
,"ubuntu":{"apt":1,"without":1,"16.04":1,"18.04":1}
,"maintains":{"respective":1,"two":1}
,"respective":{"groups":1}
,"groups":{"debian":1}
,"section":{"describes":1,"lists":1,"list":1,"uses":1,"update":1,"examples":1}
,"tools":{"packages":1,"generating":1,"package":1,"ota_tools":1}
,"provide":{"basic":1}
,"basic":{"support":1,"packages":1,"functionality":1}
,"support":{"jetson":1,"release":1,"components":1,"carrier":1}
,"cannot":{"ota":1,"render":1}
,"new":{"jetpack":1,"point":1,"minor":1,"upgradable":1}
,"release":{"system":1,"earlier":1,"32.3.1":1,"minor":1,"example":1,"32.4.1":1,"32.3.x":1,"main":1,"release":1,"number":1,"want":1,"32.2":1,"specified":1,"32.2.1":1,"32.4":1,"20.04":1,"notes":1,"32.6":1,"package":1,"28.3":1,"updated":1,"jetson":1,"28.2":1,"32.3":1,"32.1":1,"partition":1,"refer":1}
,"system":{"installed":1,"based":1,"git":1,"device":1,"designated":1,"partitions":1,"ota":1,"example":1,"board":1}
,"instructions":{"jetpack":1,"applying":1}
,"recommend":{"installing":1}
,"installing":{"ota":1,"debian":1}
,"earlier":{"release":1,"versions":1}
,"32.3.1":{"system":1}
,"based":{"ubuntu":1,"default":1,"target_bsp":1}
,"without":{"customization":1,"using":1,"layout":1,"partition":1}
,"customization":{"jetson":1,"done":1,"intermediate":1,"ota":1,"comprises":1,"current":1}
,"appropriate":{"procedure":1,"configuration":1,"type":1,"command":1}
,"procedure":{"below":1,"target":1,"executed":1,"employs":1}
,"below":{"update":1,"describes":1}
,"point":{"release":1}
,"minor":{"release":1,"version":1}
,"example":{"release":1,"update":1,"current":1,"adding":1,"r32-3":1,"following":1,"image":1,"add":1,"slot":1,"ota":1,"customizing":1,"jetson":1,"above":1,"dev":1,"ota_work":1}
,"32.4.1":{"32.4.2":1}
,"32.3.x":{"32.4.2":1}
,"enter":{"command":1,"commands":1,"following":1}
,"sudo":{"apt":1,"apt-key":1,"apt-get":1,"tar":1,"apply_binaries.sh":1,"rootfs":1,"tot_bsp":1,"tools":1,"nv_ota_start.sh":1,"l4t_generate_soc_bup.sh":1,"nv_part_update":1}
,"reads":{"list":1}
,"list":{"packages":1,"--upgradable":1,"new":1,"ota":1,"jetpack":1,"debian":1}
,"remote":{"apt":1}
,"repository":{"identifies":1,"name":1,"public":1,"host":1}
,"identifies":{"new":1,"platform\u2019s":1}
,"upgradable":{"packages":1}
,"displays":{"list":1}
,"install":{"basic":1,"jetson":1,"public":1,"required":1,"nsight-graphics-for-embeddedlinux-2021.1.1":1,"apt":1,"manually":1,"ota":1}
,"reboot":{"jetson":1,"target":1,"recovery":1,"during":1}
,"upgrade":{"finished":1}
,"open":{"apt":1,"https":1}
,"source":{"configuration":1,"list":1,"control":1}
,"configuration":{"file":1,"name":1,"files":1}
,"file":{"text":1,"reply":1,"contains":1,"source":1,"sbk":1,"target_board":1,"optional":1,"used":1,"ota_payload_package.tar.gz":1,"system":1,"ota_backup_files_list.txt":1,"flash_l4t_t186_r28-3_r32i_emmc.xml":1,"flash_l4t_t186_r32a_r32i_emmc.xml":1,"required":1,"upgradetasklist.txt.xxx":1,"recovery_copy_binlist.txt":1,"explanation":1,"named":1,"update_list.conf":1,"included":1}
,"text":{"editor":1}
,"editor":{"example":1}
,"sources.list.d":{"nvidia-l4t-apt-source.list":1}
,"change":{"repository":1,"involved":1,"value":1}
,"name":{"download":1,"hyperlink":1,"specified":1,"file":1}
,"download":{"url":1,"install":1,"packages":1,"package":1,"ota":1}
,"url":{"deb":1,"displays":1}
,"deb":{"commands":1,"https":1,"http":1}
,"original":{"commands":1,"jetson":1}
,"https":{"repo.download.nvidia.com":1}
,"repo.download.nvidia.com":{"jetson":1}
,"common":{"release":1,"r32.4":1}
,"platform":{"release":1,"identifies":1,"jetson":1}
,"number":{"minor":1,"specified":1,"e.g":1,"times":1}
,"want":{"update":1,"add":1}
,"32.2":{"replace":1,"32.3":1}
,"replace":{"r32":1}
,"r32":{"r32.2":1}
,"r32.2":{"ota":1}
,"updates":{"latest":1,"versions":1,"current":1,"jetson":1,"whether":1,"partitions":1,"slot":1}
,"latest":{"point":1,"revision":1}
,"specified":{"minor":1,"release":1,"option":1,"build-base-recovery-image.sh":1}
,"32.2.1":{"case":1}
,"platform\u2019s":{"processor":1}
,"t186":{"nvidia":1}
,"tx2":{"series":1,"module":1,"jetson-xavier-nx-devkit-tx2-nx":1,"p3310-1000":1,"carrier":1,"update":1,"uses":1,"board":1,"flash_l4t_t186.xml":1,"t18x":1}
,"t194":{"nvidia":1,"r32.4":1}
,"agx":{"xavier":1}
,"xavier":{"series":1,"commands":1,"jetson":1,"modules":1,"p3668-0000":1,"p3668-0001":1,"p2888-0001":1,"agx":1,"tx2":1,"t19x":1}
,"series":{"jetson":1,"modules":1}
,"t210":{"nvidia":1}
,"nano":{"devices":1}
,"current":{"release":1,"release\u2019s":1,"jetson":1,"point":1,"bsp":1}
,"32.4":{"platform":1,"32.5":1}
,"r32.4":{"main":1}
,"save":{"close":1}
,"close":{"source":1}
,"prompts":{"choose":1}
,"choose":{"configuration":1,"ways":1}
,"reply":{"nvidia":1}
,"updated":{"version":1,"i.e":1,"step":1,"slot":1}
,"version":{"file":1,"release":1,"form":1,"numbers":1,"may":1,"specified":1,"partition":1,"ota_backup_files_list.txt":1}
,"do-release-upgrade":{"command":1}
,"command":{"disabled":1,"install":1,"completed":1,"generates":1,"line":1}
,"disabled":{"jetson":1,"target":1,"need":1}
,"officially":{"support":1}
,"20.04":{"time":1}
,"provides":{"group":1,"necessary":1,"basic":1,"default":1,"several":1}
,"group":{"debian":1}
,"add":{"update":1,"following":1,"required":1,"line":1,"append":1,"pathnames":1,"comment":1,"recovery":1,"names":1}
,"prepare":{"host":1,"ota":1,"start":1,"bootloader":1}
,"public":{"key":1,"apt":1}
,"key":{"x86_64":1,"file":1,"sbk":1,"generates":1}
,"x86_64":{"repository":1,"xenial":1,"bionic":1}
,"apt-key":{"adv":1}
,"adv":{"--fetch-key":1}
,"--fetch-key":{"http":1}
,"http":{"repo.download.nvidia.com":1}
,"following":{"x86_64":1,"list":1,"table":1,"earlier":1,"terms":1,"steps":1,"sections":1,"commands":1,"command":1,"subsections":1}
,"system\u2019s":{"source":1}
,"16.04":{"host":1}
,"xenial":{"relno":1}
,"relno":{"main":1,"current":1}
,"18.04":{"host":1}
,"bionic":{"relno":1}
,"release\u2019s":{"full":1}
,"required":{"packages":1,"libraries":1,"sure":1}
,"apt-get":{"install":1}
,"nsight-graphics-for-embeddedlinux-2021.1.1":{"cuda-toolkit-10-2":1,"nsight-systems-2021.2.3":1}
,"cuda-toolkit-10-2":{"cuda-cross-aarch64-10-2":1}
,"cuda-cross-aarch64-10-2":{"libvisionworks":1}
,"libvisionworks":{"libvisionworks-dev":1}
,"libvisionworks-dev":{"libvisionworks-samples":1}
,"libvisionworks-samples":{"libvisionworks-sfm":1}
,"libvisionworks-sfm":{"libvisionworks-sfm-dev":1}
,"libvisionworks-sfm-dev":{"libvisionworks-tracking":1}
,"libvisionworks-tracking":{"libvisionworks-tracking-dev":1}
,"libvisionworks-tracking-dev":{"libnvvpi1":1}
,"libnvvpi1":{"vpi1-dev":1}
,"vpi1-dev":{"vpi1-samples":1}
,"vpi1-samples":{"vpi1-cross-aarch64-l4t":1}
,"vpi1-cross-aarch64-l4t":{"nsight-systems-2021.2.3":1}
,"nsight-systems-2021.2.3":{"cuda-toolkit-10-2":1}
,"lists":{"debian":1,"jetson":1}
,"maintained":{"nvidia":1}
,"bsp":{"jetson":1,"customization":1,"versions":1,"provides":1,"bsp":1,"release":1,"package":1,"desired":1,"version":1,"supports":1,"boots":1,"example":1}
,"applying":{"section":1,"security":1,"changes":1}
,"user":{"guide":1}
,"component":{"group":1}
,"table":{"lists":1}
,"cuda":{"cross-compile":1}
,"cross-compile":{"package":1}
,"vision":{"visionworks":1,"vpi":1}
,"customizing":{"debian":1,"rootfs":1}
,"customize":{"debian":1}
,"help":{"implement":1}
,"implement":{"solution":1,"complete":1,"ota":1,"fail-safe":1}
,"solution":{"example":1,"implement":1,"according":1,"following":1}
,"adding":{"support":1,"removing":1,"files":1,"tasks":1,"code":1,"lines":1}
,"carrier":{"board":1}
,"board":{"information":1,"without":1,"reboots":1,"layouts":1,"flashed":1,"above":1}
,"information":{"repackaging":1,"updating":1,"slots":1,"update":1}
,"repackaging":{"debian":1}
,"building":{"debian":1}
,"bootloader":{"package":1,"update":1,"smd_info.cfg":1,"nv_smd_generator":1,"tegraparser_v2":1,"tegraparser_v2.backup":1,"tegraflash.py":1,"tegraflash.py.backup":1,"tegrahost_v2":1,"tegrahost_v2.backup":1,"tegrabct_v2":1,"tegrabct_v2.backup":1,"tegraflash_internal.py":1,"tegraflash_internal.py.backup":1,"tegrasign_v3_util.py":1,"tegrasign_v3_internal.py":1,"tegrasign_v3.py":1,"tegraopenssl":1,"recovery":1,"option":1,"target_board":1,"partitions":1,"rootfs":1}
,"yourself":{"topic":1}
,"downloading":{"debian":1}
,"alternative":{"installing":1,"bootable":1}
,"store":{"later":1,"msi":1}
,"later":{"install":1}
,"web":{"browser":1}
,"browser":{"url":1}
,"hyperlink":{"download":1}
,"click":{"link":1}
,"applies":{"jetson":1,"updates":1}
,"failsafe":{"update":1}
,"writing":{"pre-generated":1,"ota":1}
,"pre-generated":{"images":1,"bup":1,"rootfs":1}
,"images":{"partitions":1,"minimal":1,"needed":1,"target":1,"stored":1,"msi":1}
,"partitions":{"update":1,"updated":1,"rootfs":1,"inactive":1,"booting":1,"slot":1,"located":1,"called":1,"excluding":1,"bct":1,"cpu-bootloader":1}
,"old":{"bsp":1}
,"versions":{"newer":1,"different":1,"adapt":1,"either":1}
,"newer":{"ones":1}
,"further":{"supports":1}
,"layouts":{"require":1,"uses":1,"corresponding":1,"created":1,"during":1,"layouts":1,"actual":1,"match":1}
,"require":{"layout":1}
,"layout":{"changes":1,"change":1,"release":1,"r32.6":1,"released":1,"apply":1,"modify":1,"customization":1,"accommodate":1,"file":1,"based":1,"target_bsp":1}
,"changes":{"course":1,"supports":1,"needed":1,"script":1,"below":1,"challenging":1,"directly":1,"require":1,"rootfs":1}
,"course":{"update":1}
,"28.3":{"release":1,"28.4":1,"used":1,"partition":1}
,"currently":{"supports":1}
,"32.6":{"following":1,"jetson":1,"modify":1}
,"adapt":{"process":1}
,"process":{"update":1,"target":1,"include":1,"environment":1,"executing":1,"stores":1,"end":1,"updating":1,"whether":1,"image-based":1,"jetson":1,"creates":1,"modify":1,"create":1,"may":1,"apply":1,"customization":1,"image":1}
,"28.2":{"28.3":1,"forward":1}
,"28.4":{"32.1":1,"release":1}
,"32.1":{"32.2":1,"jetson":1}
,"32.3":{"32.4":1}
,"terms":{"abbreviations":1}
,"bup":{"bootloader":1,"image":1,"host":1,"named":1,"convenient":1,"bl_update_payload":1}
,"contains":{"firmware":1,"current":1,"bsp":1}
,"firmware":{"binaries":1}
,"binaries":{"type":1,"rootfs":1}
,"type":{"needed":1,"update":1}
,"needed":{"update":1,"boot":1,"executes":1}
,"msi":{"minimal":1,"example":1}
,"minimal":{"images":1}
,"boot":{"jetson":1,"target":1,"extlinux":1,"image":1,"initrd":1,"updated":1}
,"feature":{"enables":1}
,"tot":{"top":1}
,"top":{"tree":1}
,"tree":{"latest":1}
,"revision":{"file":1}
,"control":{"system":1}
,"overall":{"high-level":1}
,"high-level":{"flow":1}
,"performed":{"two":1,"identified":1,"host":1,"jetson":1}
,"steps":{"first":1,"following":1,"host":1,"performed":1,"jetson":1}
,"step":{"prepare":1,"otherwise":1,"update":1,"reboot":1,"target":1,"steps":1}
,"machine":{"second":1,"target":1,"specify":1}
,"second":{"trigger":1}
,"trigger":{"ota":1,"update":1}
,"target":{"device":1,"board":1,"bootloader":1,"boots":1}
,"preparing":{"ota":1,"image-based":1}
,"necessary":{"tools":1}
,"generating":{"ota":1,"rootfs":1}
,"tool":{"package":1,"ota":1,"decompresses":1,"handles":1}
,"ota_tools_":{"rel":1}
,"rel":{"_aarch64.tbz2":1,"current":1}
,"e.g":{"r32.6.1":1,"\u2011sb":1}
,"generated":{"ota":1,"specified":1}
,"named":{"ota_payload_package.tar.gz":1,"nv_ota_rootfs_updater.sh":1,"bl_update_payload":1,"update_list.conf":1}
,"ota_payload_package.tar.gz":{"package":1,"ota":1,"target_bsp":1,"archive":1,"target":1}
,"includes":{"images":1}
,"recommends":{"applying":1}
,"security":{"mechanism":1,"requirements":1,"mechanisms":1,"policy":1}
,"mechanism":{"package":1}
,"signature":{"encryption":1}
,"upload":{"ota_payload_package.tar.gz":1}
,"_aarch64.tbz2":{"ota":1,"tot_bsp":1,"workdir":1,"determines":1,"backs":1}
,"responsible":{"writing":1}
,"client":{"service":1,"executes":1,"target":1}
,"service":{"triggers":1}
,"triggers":{"ota":1}
,"include":{"following":1}
,"validate":{"downloaded":1}
,"downloaded":{"ota":1}
,"contents":{"according":1}
,"according":{"security":1,"requirements":1,"needs":1}
,"decompresses":{"ota":1}
,"prepares":{"ota":1}
,"handles":{"cases":1}
,"cases":{"partition":1}
,"involved":{"rootfs":1}
,"rootfs":{"enabled":1,"opt":1,"usr":1,"target_bsp":1,"image":1,"option":1,"partition":1,"built":1,"occupies":1,"may":1,"linux_for_tegra":1,"build":1,"example":1,"apply":1,"partitions":1,"disabled":1,"redundancy":1,"updater":1,"changing":1,"customization":1,"updater\u2019s":1}
,"detailed":{"steps":1}
,"involves":{"steps":1}
,"identified":{"procedure":1}
,"environment":{"variable":1}
,"variable":{"base_bsp":1,"tot_bsp":1,"target_bsp":1,"workdir":1,"ota_max_retry_count":1}
,"base_bsp":{"full":1,"base_bsp":1,"rootfs":1}
,"pathname":{"base":1,"current-release":1,"linux_for_tegra":1}
,"base":{"bsp\u2019s":1,"bsp":1,"recovery":1,"system":1}
,"bsp\u2019s":{"linux_for_tegra":1}
,"linux_for_tegra":{"directory":1,"rootfs":1,"tools":1,"payloads_":1,"\u200Ctools":1}
,"directory":{"base":1,"contains":1,"package":1,"hold":1,"ota":1,"deleted":1,"example":1,"linux_for_tegra":1,"opt":1}
,"i.e":{"supported":1}
,"supported":{"version":1,"jetson":1}
,"unpack":{"apply":1,"ota_tools_":1,"ota":1}
,"apply":{"sample":1,"image-based":1,"running":1,"security":1,"customization":1,"ota":1}
,"sample":{"root":1,"rootfs":1,"scripts":1}
,"root":{"filesystem":1,"device":1,"dev":1,"filesystems":1,"may":1}
,"filesystem":{"directory":1,"root":1}
,"tar":{"xpf":1}
,"xpf":{"tegra186_linux_":1,"ota_tools_":1,"tot_bsp":1}
,"tegra186_linux_":{"rel":1}
,"tegra_linux_sample-root-filesystem_":{"rel":1}
,"tot_bsp":{"full":1,"environment":1,"step":1,"target_bsp":1,"ota_tools_":1,"tools":1,"modify":1,"flash.sh":1,"l4t_sign_image.sh":1,"l4t_generate_soc_bup.sh":1,"bootloader":1,"rootfs":1,"linux_for_tegra":1}
,"current-release":{"bsp\u2019s":1,"bsp":1}
,"target_bsp":{"tot_bsp":1,"full":1,"bootloader":1,"rootfs":1,"\u200Ctools":1,"current":1,"jetson":1}
,"otherwise":{"next":1}
,"next":{"step":1}
,"desired":{"release":1}
,"32.5":{"unpack":1,"partition":1,"current":1}
,"r32.5":{"supported":1}
,"unpacked":{"step":1}
,"copy":{"files":1,"bup":1}
,"files":{"tot_bsp":1,"target_bsp":1,"generated":1,"directory":1,"generate":1,"app":1,"preserved":1,"directories":1,".tar.gz":1,"according":1,"distributed":1,"rootfs":1,"jetson-tx2-r28_3-r32i-emmc.conf":1,"recovery":1,"want":1}
,"ota_tools":{"version_upgrade":1}
,"version_upgrade":{"target_bsp":1,"tools":1,"smd_info.boot_slot_a.cfg":1,"smd_info.boot_slot_b.cfg":1,"slot_metadata.bin.a":1,"slot_metadata.bin.b":1,"build_base_recovery_image.sh":1,"l4t_generate_ota_package.sh":1}
,"generate":{"slot":1,"base":1,"ota":1}
,"slot":{"metadata":1,"updated":1,"just":1,"running":1,"device":1,"several":1,"information":1,"slot":1,"uses":1,"time":1,"swaps":1,"active":1,"applies":1,"ensures":1}
,"metadata":{"files":1}
,"smd_info.cfg":{"tools":1}
,"sed":{"tools":1}
,"nv_smd_generator":{"tools":1}
,"smd_info.boot_slot_a.cfg":{"tools":1}
,"smd_info.boot_slot_b.cfg":{"tools":1}
,"modify":{"p2771-0000.conf.common":1,"process":1,"files":1,"upgradetasklist.txt.\u200Cjetson-tx2.\u200Cr28_to_r32-tot_emmc":1}
,"p2771-0000.conf.common":{"p2972-0000.conf.common":1}
,"p2972-0000.conf.common":{"p3668.conf.common":1}
,"flash.sh":{"flash.sh.backup":1}
,"l4t_sign_image.sh":{"l4t_sign_image.sh.backup":1}
,"l4t_generate_soc_bup.sh":{"l4t_generate_soc_bup.sh.backup":1,"processor":1}
,"tegraparser_v2":{"bootloader":1}
,"tegraflash.py":{"bootloader":1}
,"tegrahost_v2":{"bootloader":1}
,"tegrabct_v2":{"bootloader":1}
,"tegraflash_internal.py":{"bootloader":1}
,"tegrasign_v3_util.py":{"bootloader":1}
,"tegrasign_v3_internal.py":{"bootloader":1}
,"tegrasign_v3.py":{"bootloader":1}
,"tegraopenssl":{"bootloader":1}
,"opt":{"nvidia":1,"ota_package":1}
,"l4t-bootloader-config":{"nv-l4t-bootloader-config.sh":1,"nv-l4t-bootloader-config.sh.backup":1}
,"nv-l4t-bootloader-config.sh":{"rootfs":1}
,"usr":{"sbin":1}
,"sbin":{"nvbootctrl":1,"nvbootctrl.backup":1,"nv_bootloader_payload_updater":1,"nv_bootloader_payload_updater.backup":1,"nv_update_engine":1,"nv_update_engine.backup":1}
,"nvbootctrl":{"rootfs":1}
,"nv_bootloader_payload_updater":{"rootfs":1,"pre-generated":1}
,"nv_update_engine":{"rootfs":1,"nv_bootloader_payload_updater":1,"pre-generated":1}
,"echo":{"smdfile":1}
,"smdfile":{"slot_metadata.bin":1}
,"slot_metadata.bin":{"p2771-0000.conf.common":1,"p2972-0000.conf.common":1,"p3668.conf.common":1}
,"recovery":{"image":1,"dtb":1,"kernel":1,"initrd":1,"task":1}
,"dtb":{"enter":1,"stores":1,"used":1,"release":1,"recovery.dtb.r32_1_2":1,"ota":1}
,"build_base_recovery_image.sh":{"pkc":1,"jetson-tx2":1}
,"pkc":{"key":1}
,"sbk":{"key":1}
,"target_board":{"bsp_version":1,"appropriate":1,"configuration":1}
,"bsp_version":{"base_bsp":1,"base":1}
,"p3668-0000":{"jetson-xavier-nx-devkit":1}
,"p3668-0001":{"jetson-xavier-nx-devkit-emmc":1}
,"p2888-0001":{"p2888-0004":1}
,"p2888-0004":{"jetson-agx-xavier-devkit":1}
,"p3310-1000":{"jetson-tx2-devkit":1}
,"rmm-n":{"respectively":1}
,"respectively":{"major":1}
,"major":{"minor":1}
,"numbers":{"base":1}
,"may":{"minor":1,"used":1,"combined":1,"yield":1,"fail":1,"think":1,"add":1,"meet":1,"arguments":1}
,"forward":{"example":1}
,"r32-3":{"specifies":1}
,"specifies":{"base":1,"script":1}
,"optional":{"pkc":1,"sbk":1}
,"flashing":{"images":1}
,"completed":{"successfully":1,"device":1}
,"successfully":{"script":1,"completed":1}
,"script":{"generates":1,"used":1,"variable":1,"perform":1,"executes":1,"verifies":1,"nv_ota_preserve_data.sh":1,"nv_recovery.sh":1,"writes":1,"nv_part_update":1}
,"generates":{"recovery":1,"file":1,"default":1,"bup":1}
,"stores":{"target_bsp":1,"logs":1}
,"using":{"pkc":1}
,"recovery.img.r32_1_2":{"recovery":1}
,"recovery.dtb.r32_1_2":{"target_bsp":1}
,"jetson-tx2":{"r32-1":1}
,"r32-1":{"base_bsp":1}
,"l4t_generate_ota_package.sh":{"pkc_key_file":1,"uses":1}
,"pkc_key_file":{"sbk_key_file":1,"optional":1}
,"sbk_key_file":{"rootfs_updater":1,"optional":1}
,"rootfs_updater":{"rootfs_image":1,"specifies":1}
,"rootfs_image":{"target_board":1,"path":1}
,"separately":{"shown":1}
,"shown":{"may":1}
,"combined":{"single":1}
,"single":{"word":1}
,"word":{"e.g":1}
,"\u2011sb":{"\u2011sr":1}
,"skip":{"generating":1}
,"option":{"rootfs":1,"meaningful":1,"valid":1,"lets":1,"enabled":1,"specify":1}
,"meaningful":{"update":1}
,"valid":{"update":1}
,"customized":{"updater":1,"top-of-tree":1,"sample":1,"released":1,"rootfs":1,"devices":1}
,"updater":{"image":1,"option":1,"script":1,"named":1,"process":1,"specify":1}
,"path":{"rootfs":1,"composed":1,"ota":1}
,"written":{"rootfs":1,"relative":1}
,"default":{"rootfs":1,"partition":1,"layouts":1,"partitions":1}
,"built":{"target_bsp":1}
,"overwrite":{"default":1}
,"self-generated":{"rootfs":1}
,"cloned":{"jetson":1}
,"fully":{"customized":1,"booted":1}
,"top-of-tree":{"release":1}
,"build-base-recovery-image.sh":{"step":1}
,"archive":{"script":1,"decompressing":1,"jetson":1,"choose":1,"ota_tools_":1}
,"occupies":{"self-generated":1}
,"yield":{"larger":1}
,"larger":{"smaller":1}
,"smaller":{"archive":1}
,"decompressing":{"archive":1}
,"requires":{"least":1}
,"least":{"free":1}
,"free":{"space":1}
,"build":{"recovery":1}
,"kernel":{"recovery":1,"runs":1,"continue":1,"enters":1,"update":1,"kernel-dtb":1,"running":1}
,"libraries":{"binaries":1}
,"put":{"ota":1}
,"complete":{"ota":1,"secure":1}
,"review":{"boot":1}
,"extlinux":{"extlinux.conf":1}
,"initrd":{"entry":1,"boot":1}
,"entry":{"add":1}
,"line":{"linux":1,"example":1,"parameters":1}
,"append":{"line":1}
,"dev":{"mmcblk0p1":1,"mmcblk0":1}
,"mmcblk0p1":{"rootwait":1}
,"rootwait":{"rootfstype":1}
,"rootfstype":{"ext4":1}
,"hold":{"files":1}
,"workdir":{"directory\u2019s":1,"directory":1,"linux_for_tegra":1,"image":1,"path":1}
,"directory\u2019s":{"full":1}
,"start":{"ota":1}
,"nv_ota_start.sh":{"dev":1,"utility":1,"handles":1,"included":1}
,"mmcblk0":{"ota":1}
,"error":{"occurs":1}
,"occurs":{"last":1}
,"last":{"step":1}
,"enabled":{"target":1,"disabled":1,"ota":1,"root":1}
,"inactive":{"slot":1}
,"reboots":{"slot":1,"continues":1}
,"just":{"updated":1}
,"boots":{"recovery":1,"runs":1}
,"runs":{"ota":1,"operating":1}
,"executing":{"step":1}
,"fails":{"due":1,"number":1,"logs":1,"boot":1}
,"due":{"power":1}
,"power":{"loss":1}
,"loss":{"target":1}
,"continue":{"update":1}
,"maximum":{"number":1}
,"times":{"target":1}
,"continues":{"update":1}
,"determined":{"script":1}
,"ota_max_retry_count":{"defaults":1,"target_bsp":1}
,"defaults":{"zero":1}
,"zero":{"update":1}
,"enters":{"bash":1}
,"bash":{"shell":1}
,"shell":{"change":1}
,"value":{"ota_max_retry_count":1}
,"\u200Ctools":{"\u200Cota_tools":1}
,"\u200Cota_tools":{"\u200Cversion_upgrade":1}
,"\u200Cversion_upgrade":{"\u200Cnv_recovery.sh":1,"\u200Cimage_based_ota_examples.txt":1}
,"logs":{"ota_logs":1,"record":1}
,"ota_logs":{"target":1}
,"record":{"details":1}
,"details":{"ota":1,"examples":1}
,"end":{"successful":1}
,"successful":{"ota":1}
,"log":{"files":1}
,"secure":{"ota":1}
,"executes":{"procedure":1,"script":1,"nv_ota_\u200Cupdate_without_\u200Clayout_change.sh":1,"nv_ota_\u200Cupdate_with_\u200Clayout_change.sh":1}
,"mechanisms":{"according":1}
,"policy":{"requirements":1}
,"utility":{"triggering":1,"nv_ota_start.sh":1,"run":1}
,"triggering":{"ota":1}
,"either":{"without":1}
,"whether":{"rootfs":1,"layout":1,"unified":1}
,"need":{"aware":1}
,"aware":{"difference":1}
,"difference":{"utility":1}
,"included":{"ota_tools_":1,"ota":1}
,"determines":{"whether":1}
,"perform":{"appropriate":1,"update":1,"partition":1,"individual":1}
,"nv_ota_\u200Cupdate_with_\u200Clayout_change.sh":{"section":1}
,"redundancy":{"enabled":1,"topic":1}
,"triggered":{"nv_ota_start.sh":1}
,"run":{"whole":1,"script":1}
,"whole":{"procedure":1}
,"executed":{"fully":1}
,"booted":{"system":1}
,"rebooted":{"recovery":1,"updated":1}
,"employs":{"two":1}
,"additional":{"utilities":1}
,"utilities":{"nv_update_engine":1,"services":1}
,"unified":{"bootloader":1}
,"kernel-dtb":{"partitions":1}
,"corresponding":{"rootfs":1,".conf":1,"configuration":1}
,"once":{"ota":1}
,"several":{"retries":1,"jetson":1,"examples":1}
,"retries":{"switches":1}
,"switches":{"back":1}
,"back":{"previous":1,"restore":1}
,"previous":{"known":1}
,"known":{"good":1}
,"good":{"slot":1}
,"slots":{"switching":1,"example":1,"partition":1,"adding":1}
,"switching":{"rootfs":1}
,"filesystems":{"redundancy":1,"pathnames":1}
,"setting":{"file":1}
,"challenging":{"process":1}
,"directly":{"unexpected":1}
,"unexpected":{"reboot":1}
,"during":{"update":1,"ota":1}
,"fail":{"leave":1}
,"leave":{"jetson":1}
,"unbootable":{"state":1}
,"sets":{"partitions":1}
,"booting":{"running":1}
,"operating":{"system":1}
,"designated":{"slot":1}
,"time":{"applies":1}
,"swaps":{"roles":1}
,"roles":{"slots":1}
,"active":{"bsp":1}
,"ensures":{"update":1}
,"failure":{"cannot":1}
,"render":{"device":1}
,"fail-safe":{"update":1}
,"creates":{"intermediate":1}
,"intermediate":{"partition":1}
,"bootable":{"paths":1,"path":1}
,"paths":{"case":1}
,"case":{"unexpected":1}
,"composed":{"partitions":1}
,"located":{"free":1,"linux_for_tegra":1}
,"space":{"storage":1,"starting":1}
,"storage":{"device":1}
,"stored":{"partitions":1}
,"called":{"minimal":1,"appropriate":1}
,"flash_l4t_t186_r28-3_r32i_emmc.xml":{"based":1}
,"flash_l4t_t186_r32a_r32i_emmc.xml":{"based":1}
,"r32.6":{"used":1}
,".conf":{"files":1,"file":1}
,"created":{"based":1,"partition":1}
,"released":{"bsp":1}
,"done":{"default":1}
,"verifies":{"layouts":1}
,"actual":{"board":1}
,"match":{"ota":1}
,"restore":{"files":1}
,"app":{"partition":1}
,"nv_ota_preserve_data.sh":{"ota_tools_":1,"packs":1}
,"backs":{"restores":1}
,"restores":{"files":1}
,"edit":{"configuration":1,"add":1}
,"ota_backup_files_list.txt":{"add":1,"contains":1}
,"pathnames":{"files":1,"written":1,"leading":1}
,"preserved":{"ota":1}
,"distributed":{"version":1,"image-based":1}
,"directories":{"listed":1}
,"listed":{"absolute":1,"files":1}
,"absolute":{"path":1,"pathnames":1}
,"relative":{"form":1,"filesystem":1}
,"always":{"interpreted":1}
,"interpreted":{"relative":1}
,"think":{"absolute":1}
,"leading":{"slash":1}
,"slash":{"omitted":1}
,"comment":{"lines":1}
,"lines":{"starting":1}
,"starting":{"pound":1,"msi_emmc_offset":1}
,"pound":{"sign":1}
,"sign":{"column":1}
,"packs":{"listed":1}
,".tar.gz":{"archive":1}
,"ways":{"backing":1}
,"backing":{"restoring":1}
,"restoring":{"files":1}
,"functionality":{"updating":1}
,"needs":{"modified":1}
,"modified":{"process":1}
,"meet":{"requirements":1}
,"encrypting":{"ota":1}
,"hosting":{"ota":1}
,"payloads":{"ota":1}
,"found":{"ota":1}
,"function":{"ota":1}
,"authenticating":{"ota":1}
,"decrypting":{"ota":1}
,"determining":{"apply":1}
,"changing":{"partition":1,"size":1,"location":1,"process":1}
,"subsections":{"discuss":1}
,"discuss":{"possible":1}
,"possible":{"types":1}
,"types":{"customization":1}
,"removing":{"files":1,"partitions":1}
,"modifying":{"files":1,"provided":1,"current":1,"msi_emmc_offset":1,"intermediate":1}
,"size":{"partitions":1}
,"location":{"partitions":1,"target":1}
,"provided":{"intermediate":1,"file":1,"script":1}
,"accommodate":{"base":1}
,"flashed":{"release":1}
,"above":{"partition":1,"corresponding":1}
,"msi_emmc_offset":{".conf":1,"large":1}
,"sure":{"free":1}
,"large":{"enough":1}
,"enough":{"store":1}
,"jetson-tx2-r28_3-r32i-emmc.conf":{"jetson-tx2-r32a-r32i-emmc.conf":1}
,"refer":{"tothe":1}
,"tothe":{"section":1}
,"examples":{"below":1,"changes":1,"apply":1,"file":1}
,"newly":{"created":1}
,"addition":{"default":1}
,"upgradetasklist.txt.xxx":{"example":1}
,"upgradetasklist.txt.\u200Cjetson-tx2.\u200Cr28_to_r32-tot_emmc":{"specify":1}
,"specify":{"partitions":1,"filesystems":1,"rootfs":1,"expect":1}
,"editing":{"provided":1}
,"recovery_copy_binlist.txt":{"specify":1}
,"explanation":{"examples":1}
,"task":{"customization":1}
,"tasks":{"recovery":1}
,"nv_recovery.sh":{"example":1,"encrypted":1}
,"code":{"decrypt":1}
,"decrypt":{"payload":1}
,"writes":{"rootfs":1}
,"parameters":{"options":1}
,"options":{"several":1,"nv_ota_rootfs_updater.sh":1,"depending":1}
,"services":{"ota":1}
,"among":{"nvidia":1}
,"nv_ota_rootfs_updater.sh":{"distribution":1,"devnode":1,"update":1}
,"distribution":{"archive":1}
,"updater\u2019s":{"usage":1}
,"devnode":{"workdir":1,"device":1}
,"node":{"path":1}
,"work":{"directory":1}
,"ota_work":{"system.img":1}
,"expect":{"arguments":1}
,"arguments":{"options":1}
,"depending":{"specific":1}
,"specific":{"needs":1,"cases":1}
,"individual":{"partition":1,"partitions":1}
,"excluding":{"partitions":1}
,"bct":{"mb1":1}
,"mb1":{"app":1}
,"commands":{"host":1}
,"bl_update_payload":{"directory":1}
,"payloads_":{"processor":1}
,"processor":{"bl_update_payload":1}
,"convenient":{"location":1}
,"whose":{"partitions":1}
,"move":{"bup":1}
,"update_list.conf":{"edit":1,"input":1}
,"names":{"slots":1}
,"cpu-bootloader":{"bootloader-dtb":1,"non-current":1}
,"bootloader-dtb":{"non-current":1}
,"non-current":{"slots":1}
,"nv_part_update":{"name":1,"update_list.conf":1}
,"input":{"parameter":1}
,"upgrading":{"release":1}
,"ota-demo-host.sh":{"ota-demo-target.sh":1}
,"ota-demo-target.sh":{"sample":1}
}
;Search.control.loadWordPairs(pairs);
