Jetson Linux Multimedia API Reference: Argus::Size2D< T > Class Template Reference
Argus::Size2D< T > Class Template Reference
Detailed Description
template<typename T>
class Argus::Size2D< T >
Size2D template class.
This is a Tuple specialization containing 2 elements corresponding to the width and height of a 2D size, in that order. Values can be accessed using the named methods.
Definition at line 643 of file Types.h.
Public Member Functions
Size2D ()
Size2D (const Tuple< 2, T > &other)
Size2D (T init)
Size2D (T _width, T _height)
T & width ()
const T & width () const
T & height ()
const T & height () const
T area () const
Returns the area of the size (width * height).
bool operator== (const Tuple< N, T > &rhs) const
Returns true when every element in the two tuples are identical.
bool operator!= (const Tuple< N, T > &rhs) const
Returns true if there are any differences between the two tuples.
Tuple< N, T > & operator+= (const Tuple< N, T > &rhs)
Adds every element of another tuple to the elements of this tuple.
Tuple< N, T > & operator-= (const Tuple< N, T > &rhs)
Subtracts every element of another tuple from the elements of this tuple.
Tuple< N, T > & operator*= (const T &rhs)
Multiplies every element in the tuple by a single value.
Tuple< N, T > & operator/= (const T &rhs)
Divides every element in the tuple by a single value.
const Tuple< N, T > operator+ (const Tuple< N, T > &rhs) const
Returns the result of adding another tuple to this tuple.
const Tuple< N, T > operator- (const Tuple< N, T > &rhs) const
Returns the result of subtracting another tuple from this tuple.
const Tuple< N, T > operator* (const T &rhs) const
Returns the result of multiplying this tuple by a single value.
const Tuple< N, T > operator/ (const T &rhs) const
Returns the result of dividing this tuple by a single value.
T & operator[] (unsigned int i)
const T & operator[] (unsigned int i) const
Static Public Member Functions
static unsigned int tupleSize ()
Returns the number of elements in the tuple.
Protected Attributes
T m_data [N]
Constructor & Destructor Documentation
template<typename T> Argus::Size2D< T >::Size2D () inline
Definition at line 646 of file Types.h.
template<typename T> Argus::Size2D< T >::Size2D (const Tuple< 2, T > & other) inline
Definition at line 647 of file Types.h.
template<typename T> Argus::Size2D< T >::Size2D (T init) inline
Definition at line 649 of file Types.h.
template<typename T> Argus::Size2D< T >::Size2D (T _width, T _height) inline
Definition at line 654 of file Types.h.
Member Function Documentation
template<typename T> T Argus::Size2D< T >::area () const inline
Returns the area of the size (width * height).
Definition at line 666 of file Types.h.
template<typename T> T& Argus::Size2D< T >::height () inline
Definition at line 662 of file Types.h.
Referenced by Argus::Size2D< uint32_t >::area(), Argus::Array2D< T >::Array2D(), Argus::Array2D< T >::resize(), and Argus::Size2D< uint32_t >::Size2D().
template<typename T> const T& Argus::Size2D< T >::height () const inline
Definition at line 663 of file Types.h.
bool Argus::Tuple< N, T >::operator!= (const Tuple< N, T > & rhs) const inline inherited
Returns true if there are any differences between the two tuples.
Definition at line 471 of file Types.h.
const Tuple<N, T> Argus::Tuple< N, T >::operator* (const T & rhs) const inline inherited
Returns the result of multiplying this tuple by a single value.
Definition at line 521 of file Types.h.
Tuple<N, T>& Argus::Tuple< N, T >::operator*= (const T & rhs) inline inherited
Multiplies every element in the tuple by a single value.
Definition at line 493 of file Types.h.
References Argus::Tuple< N, T >::m_data.
const Tuple<N, T> Argus::Tuple< N, T >::operator+ (const Tuple< N, T > & rhs) const inline inherited
Returns the result of adding another tuple to this tuple.
Definition at line 509 of file Types.h.
Tuple<N, T>& Argus::Tuple< N, T >::operator+= (const Tuple< N, T > & rhs) inline inherited
Adds every element of another tuple to the elements of this tuple.
Definition at line 477 of file Types.h.
References Argus::Tuple< N, T >::m_data.
const Tuple<N, T> Argus::Tuple< N, T >::operator- (const Tuple< N, T > & rhs) const inline inherited
Returns the result of subtracting another tuple from this tuple.
Definition at line 515 of file Types.h.
Tuple<N, T>& Argus::Tuple< N, T >::operator-= (const Tuple< N, T > & rhs) inline inherited
Subtracts every element of another tuple from the elements of this tuple.
Definition at line 485 of file Types.h.
References Argus::Tuple< N, T >::m_data.
const Tuple<N, T> Argus::Tuple< N, T >::operator/ (const T & rhs) const inline inherited
Returns the result of dividing this tuple by a single value.
Definition at line 527 of file Types.h.
Tuple<N, T>& Argus::Tuple< N, T >::operator/= (const T & rhs) inline inherited
Divides every element in the tuple by a single value.
Definition at line 501 of file Types.h.
References Argus::Tuple< N, T >::m_data.
bool Argus::Tuple< N, T >::operator== (const Tuple< N, T > & rhs) const inline inherited
Returns true when every element in the two tuples are identical.
Definition at line 465 of file Types.h.
References Argus::Tuple< N, T >::m_data.
T& Argus::Tuple< N, T >::operator[] (unsigned int i) inline inherited
Definition at line 532 of file Types.h.
References Argus::Tuple< N, T >::m_data.
const T& Argus::Tuple< N, T >::operator[] (unsigned int i) const inline inherited
Definition at line 533 of file Types.h.
References Argus::Tuple< N, T >::m_data.
static unsigned int Argus::Tuple< N, T >::tupleSize () inline static inherited
Returns the number of elements in the tuple.
Definition at line 536 of file Types.h.
template<typename T> T& Argus::Size2D< T >::width () inline
Definition at line 660 of file Types.h.
Referenced by Argus::Size2D< uint32_t >::area(), Argus::Array2D< T >::Array2D(), Argus::Array2D< T >::resize(), and Argus::Size2D< uint32_t >::Size2D().
template<typename T> const T& Argus::Size2D< T >::width () const inline
Definition at line 661 of file Types.h.
Field Documentation
T Argus::Tuple< N, T >::m_data[N] protected inherited
Definition at line 539 of file Types.h.
The documentation for this class was generated from the following file:
Argus/Types.h