Jetson Linux Multimedia API Reference: Argus::Array2D< T > Class Template Reference
Argus::Array2D< T > Class Template Reference
Detailed Description
template<typename T>
class Argus::Array2D< T >
A template class to hold a 2-dimensional array of data.
Data in this array is tightly packed in a 1-dimensional vector in row-major order; that is, the vector index for any value given its 2-dimensional location (Point2D) is index = location.x() + (location.y() * size.x()); Indexing operators using iterators, 1-dimensional, or 2-dimensional coordinates are provided.
Definition at line 775 of file Types.h.
Public Types
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
Array2D ()
Default Constructor.
Array2D (const Size2D< uint32_t > &size)
Constructor given initial array size.
Array2D (const Size2D< uint32_t > &size, const T &value)
Constructor given initial array size and initial fill value.
Array2D (const Array2D< T > &other)
Copy constructor.
Array2D & operator= (const Array2D< T > &other)
Assignment operator.
bool operator== (const Array2D< T > &other) const
Equality operator.
Size2D< uint32_t > size () const
Returns the size (dimensions) of the array.
bool resize (const Size2D< uint32_t > &size)
Resize the array.
const_iterator begin () const
STL style iterators.
const_iterator end () const
iterator begin ()
iterator end ()
T & operator[] (unsigned int i)
Array indexing using [] operator.
const T & operator[] (unsigned int i) const
const T & operator() (uint32_t i) const
Array indexing using () operator.
const T & operator() (uint32_t x, uint32_t y) const
const T & operator() (const Point2D< uint32_t > &p) const
T & operator() (uint32_t i)
T & operator() (uint32_t x, uint32_t y)
T & operator() (const Point2D< uint32_t > &p)
const T * data () const
T * data ()
Member Typedef Documentation
template<typename T> typedef const T* Argus::Array2D< T >::const_iterator
Definition at line 780 of file Types.h.
template<typename T> typedef T* Argus::Array2D< T >::iterator
Definition at line 779 of file Types.h.
Constructor & Destructor Documentation
template<typename T> Argus::Array2D< T >::Array2D () inline
Default Constructor.
Definition at line 783 of file Types.h.
template<typename T> Argus::Array2D< T >::Array2D (const Size2D< uint32_t > & size) inline
Constructor given initial array size.
Definition at line 786 of file Types.h.
References Argus::Size2D< T >::height(), and Argus::Size2D< T >::width().
template<typename T> Argus::Array2D< T >::Array2D (const Size2D< uint32_t > & size, const T & value) inline
Constructor given initial array size and initial fill value.
Definition at line 792 of file Types.h.
References Argus::Size2D< T >::height(), and Argus::Size2D< T >::width().
template<typename T> Argus::Array2D< T >::Array2D (const Array2D< T > & other) inline
Copy constructor.
Definition at line 798 of file Types.h.
Member Function Documentation
template<typename T> const_iterator Argus::Array2D< T >::begin () const inline
STL style iterators.
Definition at line 834 of file Types.h.
template<typename T> iterator Argus::Array2D< T >::begin () inline
Definition at line 836 of file Types.h.
template<typename T> const T* Argus::Array2D< T >::data () const inline
Definition at line 854 of file Types.h.
template<typename T> T* Argus::Array2D< T >::data () inline
Definition at line 855 of file Types.h.
template<typename T> const_iterator Argus::Array2D< T >::end () const inline
Definition at line 835 of file Types.h.
template<typename T> iterator Argus::Array2D< T >::end () inline
Definition at line 837 of file Types.h.
template<typename T> const T& Argus::Array2D< T >::operator() (uint32_t i) const inline
Array indexing using () operator.
Definition at line 844 of file Types.h.
template<typename T> const T& Argus::Array2D< T >::operator() (uint32_t x, uint32_t y) const inline
Definition at line 845 of file Types.h.
template<typename T> const T& Argus::Array2D< T >::operator() (const Point2D< uint32_t > & p) const inline
Definition at line 846 of file Types.h.
References Argus::Point2D< T >::x(), and Argus::Point2D< T >::y().
template<typename T> T& Argus::Array2D< T >::operator() (uint32_t i) inline
Definition at line 848 of file Types.h.
template<typename T> T& Argus::Array2D< T >::operator() (uint32_t x, uint32_t y) inline
Definition at line 849 of file Types.h.
template<typename T> T& Argus::Array2D< T >::operator() (const Point2D< uint32_t > & p) inline
Definition at line 850 of file Types.h.
References Argus::Point2D< T >::x(), and Argus::Point2D< T >::y().
template<typename T> Array2D& Argus::Array2D< T >::operator= (const Array2D< T > & other) inline
Assignment operator.
Definition at line 805 of file Types.h.
template<typename T> bool Argus::Array2D< T >::operator== (const Array2D< T > & other) const inline
Equality operator.
Definition at line 813 of file Types.h.
template<typename T> T& Argus::Array2D< T >::operator[] (unsigned int i) inline
Array indexing using [] operator.
Definition at line 840 of file Types.h.
template<typename T> const T& Argus::Array2D< T >::operator[] (unsigned int i) const inline
Definition at line 841 of file Types.h.
template<typename T> bool Argus::Array2D< T >::resize (const Size2D< uint32_t > & size) inline
Resize the array.
Array contents after resize are undefined. Boolean return value enables error checking when exceptions are not available.
Definition at line 823 of file Types.h.
References Argus::Size2D< T >::height(), Argus::Array2D< T >::size(), and Argus::Size2D< T >::width().
template<typename T> Size2D<uint32_t> Argus::Array2D< T >::size () const inline
Returns the size (dimensions) of the array.
Definition at line 819 of file Types.h.
Referenced by Argus::Array2D< T >::resize().
The documentation for this class was generated from the following file:
Argus/Types.h