Jetson Linux Multimedia API Reference: Argus::UniqueObj< T > Class Template Reference
Argus::UniqueObj< T > Class Template Reference
Detailed Description
template<typename T>
class Argus::UniqueObj< T >
Template helper emulating C++11 rvalue semantics.
Movable smart pointer mimicking std::unique_ptr.
Definition at line 412 of file Types.h.
Public Member Functions
UniqueObj (T *obj=NULL)
void reset (T *obj=NULL)
T * release ()
UniqueObj (rv< UniqueObj > &moved)
UniqueObj & operator= (rv< UniqueObj > &moved)
~UniqueObj ()
T & operator* () const
T * get () const
operator bool () const
operator rv< UniqueObj > & ()
operator const rv< UniqueObj > & () const
Constructor & Destructor Documentation
template<typename T> Argus::UniqueObj< T >::UniqueObj (T * obj = NULL) inline explicit
Definition at line 415 of file Types.h.
template<typename T> Argus::UniqueObj< T >::UniqueObj (rv< UniqueObj< T > > & moved) inline
Definition at line 422 of file Types.h.
template<typename T> Argus::UniqueObj< T >::~UniqueObj () inline
Definition at line 425 of file Types.h.
References Argus::UniqueObj< T >::reset().
Member Function Documentation
template<typename T> T* Argus::UniqueObj< T >::get () const inline
Definition at line 428 of file Types.h.
Referenced by Argus::interface_cast().
template<typename T> Argus::UniqueObj< T >::operator bool () const inline
Definition at line 430 of file Types.h.
template<typename T> Argus::UniqueObj< T >::operator const rv< UniqueObj > & () const inline
Definition at line 433 of file Types.h.
template<typename T> Argus::UniqueObj< T >::operator rv< UniqueObj > & () inline
Definition at line 432 of file Types.h.
template<typename T> T& Argus::UniqueObj< T >::operator* () const inline
Definition at line 427 of file Types.h.
template<typename T> UniqueObj& Argus::UniqueObj< T >::operator= (rv< UniqueObj< T > > & moved) inline
Definition at line 423 of file Types.h.
References Argus::UniqueObj< T >::reset().
template<typename T> T* Argus::UniqueObj< T >::release () inline
Definition at line 419 of file Types.h.
template<typename T> void Argus::UniqueObj< T >::reset (T * obj = NULL) inline
Definition at line 417 of file Types.h.
Referenced by Argus::UniqueObj< T >::operator=(), and Argus::UniqueObj< T >::~UniqueObj().
The documentation for this class was generated from the following file:
Argus/Types.h