Jetson Linux Multimedia API Reference: Argus::AcRegion Class Reference
Argus::AcRegion Class Reference
Detailed Description
Defines an autocontrol region of interest (in pixel space).
This region consists of a rectangle (inherited from the Rectangle<uint32_t> Tuple) and a floating point weight value.
Definition at line 747 of file Types.h.
Public Member Functions
AcRegion ()
AcRegion (uint32_t _left, uint32_t _top, uint32_t _right, uint32_t _bottom, float _weight)
float & weight ()
const float & weight () const
uint32_t & left ()
const uint32_t & left () const
uint32_t & top ()
const uint32_t & top () const
uint32_t & right ()
const uint32_t & right () const
uint32_t & bottom ()
const uint32_t & bottom () const
uint32_t width () const
Returns the width of the rectangle.
uint32_t height () const
Returns the height of the rectangle.
uint32_t area () const
Returns the area of the rectangle (width * height).
bool operator== (const Tuple< N, uint32_t > &rhs) const
Returns true when every element in the two tuples are identical.
bool operator!= (const Tuple< N, uint32_t > &rhs) const
Returns true if there are any differences between the two tuples.
Tuple< N, uint32_t > & operator+= (const Tuple< N, uint32_t > &rhs)
Adds every element of another tuple to the elements of this tuple.
Tuple< N, uint32_t > & operator-= (const Tuple< N, uint32_t > &rhs)
Subtracts every element of another tuple from the elements of this tuple.
Tuple< N, uint32_t > & operator*= (const uint32_t &rhs)
Multiplies every element in the tuple by a single value.
Tuple< N, uint32_t > & operator/= (const uint32_t &rhs)
Divides every element in the tuple by a single value.
const Tuple< N, uint32_t > operator+ (const Tuple< N, uint32_t > &rhs) const
Returns the result of adding another tuple to this tuple.
const Tuple< N, uint32_t > operator- (const Tuple< N, uint32_t > &rhs) const
Returns the result of subtracting another tuple from this tuple.
const Tuple< N, uint32_t > operator* (const uint32_t &rhs) const
Returns the result of multiplying this tuple by a single value.
const Tuple< N, uint32_t > operator/ (const uint32_t &rhs) const
Returns the result of dividing this tuple by a single value.
uint32_t & operator[] (unsigned int i)
const uint32_t & operator[] (unsigned int i) const
Static Public Member Functions
static unsigned int tupleSize ()
Returns the number of elements in the tuple.
Protected Attributes
float m_weight
uint32_t m_data [N]
Constructor & Destructor Documentation
Argus::AcRegion::AcRegion () inline
Definition at line 750 of file Types.h.
Argus::AcRegion::AcRegion (uint32_t _left, uint32_t _top, uint32_t _right, uint32_t _bottom, float _weight) inline
Definition at line 755 of file Types.h.
Member Function Documentation
uint32_t Argus::Rectangle< uint32_t >::area () const inline inherited
Returns the area of the rectangle (width * height).
Definition at line 710 of file Types.h.
References Argus::Rectangle< T >::height(), and Argus::Rectangle< T >::width().
uint32_t & Argus::Rectangle< uint32_t >::bottom () inline inherited
Definition at line 700 of file Types.h.
const uint32_t & Argus::Rectangle< uint32_t >::bottom () const inline inherited
Definition at line 701 of file Types.h.
uint32_t Argus::Rectangle< uint32_t >::height () const inline inherited
Returns the height of the rectangle.
Definition at line 707 of file Types.h.
References Argus::Rectangle< T >::bottom(), and Argus::Rectangle< T >::top().
uint32_t & Argus::Rectangle< uint32_t >::left () inline inherited
Definition at line 694 of file Types.h.
const uint32_t & Argus::Rectangle< uint32_t >::left () const inline inherited
Definition at line 695 of file Types.h.
bool Argus::Tuple< N, uint32_t >::operator!= (const Tuple< N, uint32_t > & rhs) const inline inherited
Returns true if there are any differences between the two tuples.
Definition at line 471 of file Types.h.
const Tuple<N, uint32_t > Argus::Tuple< N, uint32_t >::operator* (const uint32_t & rhs) const inline inherited
Returns the result of multiplying this tuple by a single value.
Definition at line 521 of file Types.h.
Tuple<N, uint32_t >& Argus::Tuple< N, uint32_t >::operator*= (const uint32_t & rhs) inline inherited
Multiplies every element in the tuple by a single value.
Definition at line 493 of file Types.h.
const Tuple<N, uint32_t > Argus::Tuple< N, uint32_t >::operator+ (const Tuple< N, uint32_t > & rhs) const inline inherited
Returns the result of adding another tuple to this tuple.
Definition at line 509 of file Types.h.
Tuple<N, uint32_t >& Argus::Tuple< N, uint32_t >::operator+= (const Tuple< N, uint32_t > & rhs) inline inherited
Adds every element of another tuple to the elements of this tuple.
Definition at line 477 of file Types.h.
const Tuple<N, uint32_t > Argus::Tuple< N, uint32_t >::operator- (const Tuple< N, uint32_t > & rhs) const inline inherited
Returns the result of subtracting another tuple from this tuple.
Definition at line 515 of file Types.h.
Tuple<N, uint32_t >& Argus::Tuple< N, uint32_t >::operator-= (const Tuple< N, uint32_t > & rhs) inline inherited
Subtracts every element of another tuple from the elements of this tuple.
Definition at line 485 of file Types.h.
const Tuple<N, uint32_t > Argus::Tuple< N, uint32_t >::operator/ (const uint32_t & rhs) const inline inherited
Returns the result of dividing this tuple by a single value.
Definition at line 527 of file Types.h.
Tuple<N, uint32_t >& Argus::Tuple< N, uint32_t >::operator/= (const uint32_t & rhs) inline inherited
Divides every element in the tuple by a single value.
Definition at line 501 of file Types.h.
bool Argus::Tuple< N, uint32_t >::operator== (const Tuple< N, uint32_t > & rhs) const inline inherited
Returns true when every element in the two tuples are identical.
Definition at line 465 of file Types.h.
uint32_t & Argus::Tuple< N, uint32_t >::operator[] (unsigned int i) inline inherited
Definition at line 532 of file Types.h.
const uint32_t & Argus::Tuple< N, uint32_t >::operator[] (unsigned int i) const inline inherited
Definition at line 533 of file Types.h.
uint32_t & Argus::Rectangle< uint32_t >::right () inline inherited
Definition at line 698 of file Types.h.
const uint32_t & Argus::Rectangle< uint32_t >::right () const inline inherited
Definition at line 699 of file Types.h.
uint32_t & Argus::Rectangle< uint32_t >::top () inline inherited
Definition at line 696 of file Types.h.
const uint32_t & Argus::Rectangle< uint32_t >::top () const inline inherited
Definition at line 697 of file Types.h.
static unsigned int Argus::Tuple< N, uint32_t >::tupleSize () inline static inherited
Returns the number of elements in the tuple.
Definition at line 536 of file Types.h.
float& Argus::AcRegion::weight () inline
Definition at line 760 of file Types.h.
References m_weight.
const float& Argus::AcRegion::weight () const inline
Definition at line 761 of file Types.h.
References m_weight.
uint32_t Argus::Rectangle< uint32_t >::width () const inline inherited
Returns the width of the rectangle.
Definition at line 704 of file Types.h.
References Argus::Rectangle< T >::left(), and Argus::Rectangle< T >::right().
Field Documentation
uint32_t Argus::Tuple< N, uint32_t >::m_data[N] protected inherited
Definition at line 539 of file Types.h.
float Argus::AcRegion::m_weight protected
Definition at line 764 of file Types.h.
Referenced by weight().
The documentation for this class was generated from the following file:
Argus/Types.h